return {
	-- Nomes e Descrições
	--heist_big = "The Big Bank",--The Big Bank
	--heist_big_hl = "The Big Bank",--The Big Bank
	heist_big_crimenet = "Esse é a mãe de todos os nossos trabalhos de banco. As portas do Benevolent Bank estão muito além de qualquer coisa que vocês já viram.$NL;$NL;» Planeje o Roubo usando um Planejamento Prévio$NL;» Cubra o Corredor Principal e os Escritórios Laterais$NL;» Encontre um jeito de Entrar no Cofre$NL;» Roube tudo o que puder e dê o fora",--This is the Mother of all bank jobs. The vault doors at the Benevolent Bank are way beyond anything that you've seen before.$NL;$NL;» Plan your heist using preplanning$NL;» Case the main hall and side offices$NL;» Find a way into the vault$NL;» Steal anything you can and get out
	heist_big_briefing = "O Benevolent Bank tem história. É o Banco mais antigo dos Estados Unidos, saqueado pelos britânicos em 1812, tinha o ouro da Guerra Civil, teve os primeiros títulos FDR. Caramba, vocês vão ter que achar até mesmo nas costas de seus dez locais. E adivinhem - nesse tempo todo de existência, ele nunca sofreu um roubo com sucesso. Felizmente. Bem, hoje é a a vez de vocês tentarem mudar essa história.$NL;$NL;Vocês irão pela porta da frente. Explorem o lugar para descobrir o melhor caminho através do corredor até chegar ao cofre. Eu tenho umas ideias de como a gente pode levar todo esse loot! Confiem em mim. Façam história, pessoal.",--The Benevolent Bank has history. Oldest US bank, sacked by the British in 1812, held Civil War gold, issued FDR's first bonds. Hell, you'll even find it on the back of your ten-spots. And guess what - in all that time, it has never been successfully knocked over. Successfully. Well, today it is your turn to try and change that.$NL;$NL;You're going in through the front door. Scope the place to figure your best way through the lobby to the vaults beyond. I've got some ideas of how we're going to boost all that loot. Trust me. Make history, guys.
	
	-- Legendas
	pln_bb1_intro_01_01 = "A segurança aqui é bem rígida. Nós podemos fazer esse roubo silenciosamente. Mas se as coisas ficarem complicadas, não se preocupem. Eu tenho sempre um Plano B.",--Security here is tight. We might be able to do this heist silently. But if things go loud, don't worry. I've always got a Plan B.
	dlg_pln_bb1_intro_01_01 = "A segurança aqui é bem rígida. Nós podemos fazer esse roubo silenciosamente. Mas se as coisas ficarem complicadas, não se preocupem. Eu tenho sempre um Plano B.",--Security here is tight. We might be able to do this heist silently. But if things go loud, don't worry. I've always got a Plan B.
	pln_bb1_intro_01_02 = "É um banco grande, mas ainda é um banco. Vocês sabem o que fazer. Chequem os locais, e decidam se querem fazer as coisas em silêncio ou partir para o jeito clássico.",--It's a big bank, but still a bank. You know the drill. Check the place out, and decide whether to keep things quiet or bring the noise.
	pln_bb1_intro_01_03 = "É esse. O maior banco de todos. Tudo foi treinado para esse momento. Vocês já sabem o que fazer.",--This is the one. Biggest bank job yet. Everything has been training for this moment. You know what to do.
	pln_bb1_25_03 = "Cheguem aos controles e virem o guindaste. Vocês irão gostar disso.",--Get to the controls and turn the crane. You're going to like this.
	pln_bb1_34_01 = "Olhem para essa belezinha. É chamada de A Besta. Agora iniciem.",--Look at that beauty. It's called A Besta. Now start it up.
	pln_bb1_20_01 = "Enquanto a gente espera, e se vocês tiverem as pedras, vão para o telhado e instalem a tirolesa.",--While we wait for that, and if you've got the stones, get to the roof and get the zip-line set up.
	pln_bb1_68_01 = "Tem um policial entrando no banco. Aqui vai uma ideia: Cuidem dele.",--There's a cop entering the bank. Here's an idea: take care of him.
	pln_bb1_30_02 = "Na mosca! Pela primeira vez, nós fomos ajudados por um porco.",--Bullseye! For once, we're helped by a pig.
	pln_bb1_35_01 = "Eu senti o tremor disso daqui.",--I felt the tremor of that starting from here.
	pln_bb1_56_02 = "Beleza. Estamos conectados.",--Great. We're connected.
	pln_bb1_26_02 = "Sim, isso é um cofrinho gigante. Não, eu não perdi o juízo.",--Yes, that is a giant piggy bank. No, I haven't lost my mind. 
	pln_bb1_41_01 = "Tem um helicóptero a caminho. Comecem a levar as bolsas para o telhado.",--I got a chopper on the way. Start getting the loot to the roof.
	pln_bb1_03_01 = "Essa é a Sala de Servidores. Entrem e me conectem.",--That's the server room. Get inside and get me connected.
	pln_bb1_37_02 = "Eu coloquei as ferramentas da furadeira no porco cofrinho. Peguem.",--I put a few replacement bits for the drill in the piggy bank. Fetch 'em.
	pln_bb1_67_03 = "Gente, os elevadores estão se movendo. Esperem encrenca de lá.",--Guys, the elevators are moving. Expect heat from there.
	pln_bb1_62_01 = "Estão prontos para o show de fogos de artifício?",--Are you ready for the fireworks show?
	pln_bb1_55_01 = "Beleza. Agora a última etapa. Encontrem o código do gerente. Deve estar no computador dele.",--Great. Now the last step. Find the managers code. It should be on his computer.
	pln_bb1_19_01 = "Funcionou! Ótimo. Agora mantenham os policiais longe disso.",--It worked! Great. Now keep the cops off it.
	pln_bb1_18_02 = "Ok. Agora vamos reiniciar o bloqueio de tempo e ver se funcionou.",--OK. Now let's restart the time lock and see if this worked.
	pln_bb1_30_01 = "Boom! Que tal isso para um depósito, Benevolent!",--Boom! How's that for a deposit, Benevolent!
	pln_bb1_40_01 = "A van está lá fora. Vão preparando as bolsas!",--The van's outside. Get stowing that loot!
	pln_bb1_68_02 = "Consegui um lacaio verificando o banco. Certifiquem-se de que ele seja... Bem vindo.",--Got a footman checking out the bank. Make sure he's... Welcomed.
	pln_bb1_21_01 = "Os policiais mexeram no bloqueio de tempo! Façam funcionar de novo!",--The cops messed up the time lock! Get it going again!
	pln_bb1_31_02 = "Ouch! Cuidado com esse guindaste, pessoal. Essa é uma joia de um edifício.",--Ouch! Careful with that crane, guys. This is a gem of a building.
	pln_bb1_46_02 = "A ventilação do elevador está aberta. Esse é o caminho para a van. Comecem a levar.",--The elevator shaft is open. That's the path to the van. Start hauling.
	pln_bb1_07_01 = "Conectando. Nós só podemos fazer um de cada vez, então cruzem os dedos para esse ser o correto.",--Connecting. We can only do them one at a time, so fingers crossed this is the right one.
	pln_bb1_41_02 = "Levem as bolsas até o telhado, gangue. Eu tenho um helicóptero a caminho.",--Get the loot to the roof, gang. I got a chopper en-route.
	pln_bb1_54_01 = "Um já foi, falta mais um.",--One down, one to go.
	pln_bb1_44_02 = "O ônibus está programado para... Bem, vocês se preocupam em enviar o sinal. E então vocês vão ver.",--The bus is all set up to... Well, you worry about sending the signal. Then you'll see.
	pln_bb1_25_01 = "Boa vista, hein? Bem, eu tenho outra coisa para mostrar. Vão para a cabine de controle.",--Quite the view, huh? Well, I've got something else to show you. Get to the control booth.
	pln_bb1_50_01 = "Alguém pode ir atender o telefone?",--Is anyone going to pick up the phone?
	pln_bb1_19_02 = "Ótimo. Agora mantenham os policiais longe disso.",--Great. Now keep the cops away from it.
	pln_bb1_60_02 = "termite é o melhor jeito de entrar no cofre. Nós já fizemos isso antes.",--Thermite is our best way into the vault. We've done this before.
	pln_bb1_26_01 = "Porcos podem voar.",--Pigs will fly. 
	pln_bb1_22_02 = "Todo esse trabalho será em vão se vocês não conseguirem fazer o bloqueio de tempo fazer tick-tock de novo.",--This whole enterprise will be for nothing if you dont get that time lock tick-tocking again.
	pln_bb1_11_02 = "Esse é o código! Ótimo. Agora façam o bloqueio de tempo funcionar.",--That's the code! Great. Now get it working on that time lock.
	pln_bb1_12_01 = "Um dos terminais do pessoal da staff está segurando um código. Encontre-o e comecem a hackear.",--One of the staff terminals is holding a code. Find it, and start hacking.
	pln_bb1_36_01 = "Até pedaços de diamante quebram! Vocês precisarão das partes separadas para fazer isso funcionar de novo.",--Even diamond bits break! You're gonna need the spare parts to get it going again.
	pln_bb1_58_01 = "Funcionou! Bom trabalho, pessoal.",--It worked! Great job everyone.
	pln_bb1_64_02 = "A termite já queimou. Tudo certo. Desçam e comecem a empacotar.",--Thermite's burned out. You're all clear. Drop in and start bagging.
	pln_bb1_01_02 = "É uma construção bonita, mas nós estamos trazendo negócios feios. Precisaremos de códigos para nos aprofundarmos, então, procurem pelos servidores.",--It's a beautiful building, but we're bringing ugly business. We'll need codes to get deeper in, so look for their servers.
	pln_bb1_13_02 = "O alarme desligou o bloqueio de tempo. Fiquem de boa. Tem um escritório de manutenção no telhado. Cheguem lá. Nós devemos ser capazes de religá-lo.",--The alarm shut down the time lock. Stay cool. There's a maintenance office on the roof. Get there. We should be able to rewire it.
	pln_bb1_39_02 = "Agora isso se classifica como uma pontuação. Limpem isso, gangue.",--Now this qualifies as a score. Clean it out, gang.
	pln_bb1_27_02 = "Está em posição! Deixe ir!",--It's in position. Let it go!
	pln_bb1_13_01 = "O alarme desativou o bloqueio de tempo. É um azar, mas não é uma falha. Tem uma Sala de Manutenção no telhado. Cheguem lá. Nós devemos ser capazes de reiniciá-lo.",--The alarm disabled the time lock. It's a setback but not a fail. There's a maintenance room on the roof. Get there. We should be able to reboot it.
	pln_bb1_49_01 = "Vocês podem terminar quando quiserem, mas peguem o máximo que puderem.",--You can finish this when you want, but grab as much as you can.
	pln_bb1_16_01 = "Tem uma escada no telhado. Sobre a garagem.",--There's a ladder leading to the roof. Over the garage.
	pln_bb1_28_02 = "Operem o guindaste, pessoal. Coloquem o porco cofre em posição.",--Operate the crane, guys. Get that piggy into position.
	pln_bb1_38_01 = "Aí vamos nós. As portas abriram! Vamos ver o quão ricos nós vamos ser.",--Here we go. Doors open! Let's see how rich we are.
	pln_bb1_10_03 = "Esse aqui foi perda de tempo. Outro. Rápido!",--This one's a wash-out. Another one. Quick!
	pln_bb1_52_02 = "Cartões de Acesso podem desabilitar os lasers. Fiquem de olho para algum.",--Keycards can disable the lasers. Keep an eye out for any.
	pln_bb1_08_03 = "Acessando agora...",--Accessing now...
	pln_bb1_67_01 = "Uh... Gangue... Os elevadores estão se movendo. Esperem companhia aí.",--Uh... Gang... Elevators are on the move. Expect company.
	pln_bb1_66_02 = "Gente, os painéis de controle acenderam. Acho que é o alarme.",--Guys, switchboards just lit up. Guess that's the alarm.
	pln_bb1_20_03 = "Certo, enquanto nós esperamos, se vocês quiseram adiantar as coisas, vocês podem ir para o telhado. Tem uma tirolesa para vocês instalarem lá.",--Right, while we wait, and if you want to get ahead of things, you can get yourselves to the roof. Got a zip-line to set up there.
	pln_bb1_12_02 = "Terá um computador em uma das Salas dos Funcionários que podemos hackear. Encontre-o.",--There will be a computer in one of the staff rooms that we can hack. Find it.
	pln_bb1_58_02 = "É isso aí! Ótimo trabalho, gangue.",--That's it! Great job, gang.
	pln_bb1_45_02 = "O helicóptero está aqui, pessoal. Comecem a mover as bolsas.",--Chopper's here, guys. Start hauling the loot.
	pln_bb1_63_02 = "Alumínio e Óxido de ferro... Lindo.",--Aluminum and iron oxide... Beautiful.
	pln_bb1_32_02 = "Comecem a mover essas bolsas para o cofre, gangue. Hora de arrebentar esse lugar.",--Start hauling those bags to the vault, gang. Time to crack this place.
	pln_bb1_10_02 = "Terminal errado. Tentem outro.",--Wrong terminal. Try another.
	pln_bb1_04_02 = "Me conectem. Eu consigo fazer umas travessuras daqui.",--Patch me in. I can do some mischief from here.
	pln_bb1_08_02 = "Obtendo acesso....",--Getting access...
	pln_bb1_05_02 = "Firewalls desabilitados. Vamos precisar de uma porta local - Um dos terminais de funcionários. Verifique-os.",--Firewalls are tripped. We're going to need a local port - one of the staff terminals. Check them out.
	pln_bb1_27_01 = "Ok, a posição parece boa. Joguem!",--OK, position looks good. Drop it!
	pln_bb1_35_02 = "A Besta está fazendo o seu trabalho.",--A Besta is at work. 
	pln_bb1_02_02 = "Vocês sabem como é que é. Olhos abertos para segurança. Civis precisam ser controlados. E os cartões de acesso são sempre úteis.",--You know how this goes. Eyes peeled for security. Civvies need to be controlled. And keycards are always useful.
	pln_bb1_25_02 = "Ok, vão para os controles. Eu tenho algo planejado.",--OK, get to the controls. I've got something planned.
	pln_bb1_49_02 = "Vocês podem terminar isso agora, ou vocês podem terminar isso com estilo, e esvaziar o local.",--You can finish this now, or you can finish this in style, and empty the place.
	pln_bb1_48_01 = "Nós acabamos de dar ao jornal das seis ótimas imagens! Peguem as bolsas e joguem pra dentro da van.",--We just gave the six o'clock news some great footage! Get the loot in the van.
	pln_bb1_64_01 = "A termite acabou. Agora pulem dentro e peguem a grana.",--The thermite's done. Now jump in and get that cash.
	pln_bb1_23_01 = "Boa. Agora mantenham os policiais longe daí.",--Good. Now keep the cops off of it.
	pln_bb1_36_02 = "Esse cofre é complicado. A furadeira quebrou. Peguem uma parte separada, rápido!",--That vault is tough. The drill bit broke. Get a spare part, quick!
	pln_bb1_51_01 = "O bloqueio de tempo já era. Tentem manter o silêncio. Agora, o cofre tem um controle de liberação de três etapas. Eu já cuidei do primeiro. Basta irem lá e usarem o leitor de impressão digital.",--That's the time lock done. Try and keep the sneak going. Now, the vault has a three step clearance control. The first I've already taken care of. Just head there and use the fingerprint scanner.
	pln_bb1_28_01 = "Continuem movendo o guindaste. Não o joguem aí.",--Keep moving the crane. Can't drop it there.
	pln_bb1_60_01 = "Peguem a termite. Esse é o nosso caminho até o cofre.",--Pick up the thermite. That's our way into the vault.
	pln_bb1_39_01 = "Cacete... Vocês já viram algo assim? Abram essas portas. Levem tudo.",--Holy... Have you ever seen anything like it? Get those doors open. Bag it all.
	pln_bb1_59_02 = "Todas as portas tem chaves. Se vocês querem fazer isso furtivamente, vão precisar encontrar as chaves.",--All doors have keys. If you want to do this quietly, find the keys.
	pln_bb1_56_01 = "Conectei... Vamos ver o que temos.",--Connected... Let's see what we have.
	pln_bb1_33_01 = "Levem essa bolsa para o cofre. Preparem a furadeira.",--Get that bag to the vault. Get the drill assembled.
	pln_bb1_34_03 = "Os fabricantes a chamam de aparelho de perfuração industrial de serviço pesado, mas os bandidos o conhecem como A Besta. Cavalheiros, liguem ela.",--The manufacturers call it a heavy-duty industrial drilling apparatus, but heisters know it as A Besta. Gentlemen, start it up.
	pln_bb1_50_02 = "Alguém atenda o telefone!",--Someone answer the phone!
	pln_bb1_26_03 = "Prepare-se para a queda, Floyd. Sim, eu o nomeei de Floyd.",--Get ready to drop Floyd. Yeah, I named him Floyd.
	pln_bb1_04_01 = "Me conectem. Eu devo ser capaz de entrar no sistema deles daqui.",--Hook me up. I should be able to get into their system from here. 
	pln_bb1_43_01 = "Perfeito. Agora explodam o muro e vamos dar o fora daqui.",--Perfect.  Now blow the wall and let's get the hell out of here.
	pln_bb1_38_02 = "O cofre abriu! Agora, vamos ver o que o Benevolent tem.",--Vault's breached! Now, let's see what Benevolent has.
	pln_bb1_03_02 = "A Sala de Servidores. Me conectem, pessoal.",--The server room. Get me hooked up, guys.
	pln_bb1_34_02 = "Olhem essa furadeira. Vamos ver se isso funciona tão bem quanto parece. Iniciem.",--What a drill. Let's see if it works as good as it looks. Fire it up.
	pln_bb1_53_02 = "Quando se trata de terceirizar coisas como polegares, eu opero uma política de não pergunte, não diga. Agora vão para os consoles de segurança.",--When it comes to sourcing things like thumbs I operate a "don't ask, don't tell" policy. Now get to the security consoles.
	pln_bb1_29_02 = "Gente. Operem o guindaste. Coloquem-o na posição.",--Guys. Operate the crane. Get it into position.
	pln_bb1_51_02 = "Lá se vai o bloqueio de tempo. Vocês estão indo bem. Tentem manter as coisas em silêncio. Agora, o cofre tem três etapas para abri-lo. O primeiro está na bolsa. Basta ir lá e usar o leitor de impressão digital.",--There goes the time lock. You're doing great. Try and keep things quiet. Now, the vault has three steps to open it. First is in the bag - just go there and use the fingerprint scanner.
	pln_bb1_45_01 = "O Bile está no local, gangue. Comecem a entregar as bolsas pra ele.",--Bile's on-site, gang. Start getting the bags to him.
	pln_bb1_48_02 = "Quem disse que os ônibus dessa cidade não conseguem manter um cronograma!? Comecem a mover as bolsas.",--Who said the buses in this town can't keep to a schedule! Get moving that loot.
	pln_bb1_15_01 = "Segurem os policiais até o bloqueio de tempo terminar.",--Hold the cops off until the time lock runs down.
	pln_bb1_21_02 = "Os policiais mexeram no bloqueio de tempo. Reiniciem.",--Cops have messed with the time lock. Restart it.
	pln_bb1_18_01 = "Isso deve resolver. Agora iniciem o bloqueio de tempo de novo. Eu espero que funcione.",--That should do it. Now start the time lock again. I hope that it worked.
	pln_bb1_01_01 = "Benevolent Bank. Uma beleza neoclássica. Mas o dever nos chama. Nós iremos precisar de uns códigos, então cheguem até os servidores. ",--Benevolent Bank. A Neoclassical beauty. But business calls. We're going to need some codes, so get to their servers. 
	pln_bb1_57_01 = "Foi! Agora voltem para o cofre e insiram o código.",--Got it! Now get back to the vault and enter the code.
	pln_bb1_40_02 = "A van está só esperando vocês guardarem as bolsas. Se apressem!",--The van is just waiting for you to stash that loot. Get busy!
	pln_bb1_61_02 = "Levem essa termite de volta para o cofre.",--Get that thermite back to the vault.
	pln_bb1_47_01 = "Boom! Tem um caminhão de lixo posicionado para pegar as bolsas. Déjà vu, eu sei. ",--Boom! There's a garbage truck positioned to pick up the bags. Déjà vu, I know.
	pln_bb1_14_01 = "E agora a gente espera. Alguem aí conhece uma boa história?",--And now we wait. Anyone have any good stories?
	pln_bb1_02_01 = "Vocês sabem do esquema. Cuidado com guardas e câmeras. Mantenham os civis sob controle. Procurem por cartões de segurança, e o gerente do banco - Qualquer coisa que possa ajudar.",--You know the drill. Watch for guards and cameras. Keep civilians in check. Look around for keycards, and the bank manager - anything that might help.
	pln_bb1_14_02 = "Agora nós esperamos o bloqueio de tempo acabar. Eu já contei sobre o meu avô e seus dias de assaltos?",--Now we wait for the time lock to run down. Did I ever tell you about my grandpa and his heisting days?
	pln_bb1_44_01 = "Eu manipulei o ônibus para... Bem, apenas esperem o sinal. E se afastem.",--I've rigged the bus to... Well, just give the signal. And stand back.
	pln_bb1_33_02 = "Esse lugar tem um cofre formidável. Felizmente, eu achei a ferramente certa pra isso. Levem essa bolsa para o cofre.",--This place has a formidable vault. Thankfully, I found just the tool for it. Get that bag to the vault.
	pln_bb1_11_01 = "Certo! Peguei o código! Iniciem o bloqueio de tempo.",--Alright! Got the code! Start the time lock.
	pln_bb1_08_01 = "Conectando...",--Connecting...
	pln_bb1_68_03 = "Um policial acabou de entrar no banco. Não o deixem ter uma ideia errada.",--Cop just entered the bank. Don't let him get the wrong idea.
	pln_bb1_53_01 = "Não me perguntem aonde eu achei esse dedo. Agora verifiquem a identificação dos consoles de segurança. Não deve ser um problema.",--Don't ask me where I got that thumb. Now verify identification from the security consoles. Shouldn't be a problem.
	pln_bb1_37_01 = "Tem umas partes separadas da furadeira no porco cofre.",--There were spare drill bits in the piggy bank.
	pln_bb1_55_02 = "Quase lá. Protocolo final - O código do gerente. Verifiquem o computador dele.",--Almost there. Final protocol - the managers code. Check his computer.
	pln_bb1_67_02 = "Os elevadores estão indo para o andar de vocês. Fiquem de olho.",--Elevators are headed to your floor. Keep an eye on that.
	pln_bb1_47_02 = "Lá se vai a parede. O caminhão de lixo é o ponto de entrega. Comecem a levar.",--There goes the wall. A garbage truck is your drop-off. Get hauling.
	pln_bb1_20_02 = "Agora enquanto o bloqueio de tempo faz a contagem, vocês podem avançar pra ação. Tem uma tirolesa no telhado que precisa ser instalada.",--Now while the time lock counts down, you can get ahead of the action. There's a zip-line on the roof that will need setting up.
	pln_bb1_65_01 = "Aí estão as chaves para as portas de dentro do cofre. Bom achado.",--They're the keys for the doors inside the vault. Good find.
	pln_bb1_63_01 = "Fogo no buraco!",--Fire in the hole!
	pln_bb1_06_02 = "Entrei. Esperem, pessoal - Eu preciso de um tempinho.",--I'm in. Hold on, guys - I need a little time.
	pln_bb1_65_02 = "Essas chaves irão abrir as portas do cofre. Isso deve ajudar.",--Those keys will open the doors in the vault. That should help.
	pln_bb1_29_01 = "Vamos, gangue. Vocês precisam posicionar o guindaste.",--Come on, gang. You've gotta get the crane in position.
	pln_bb1_16_02 = "Tem uma escada de acesso em cima da garagem. Deve dar pra chegar ao telhado.",--There's an access ladder over the garage. Should be able to get to the roof there.
	pln_bb1_43_02 = "Boa. Agora coloquem o C4 e podemos começar a sair desse lugar.",--Great. Now place that C4 and we can start getting out of this place.
	pln_bb1_06_01 = "Ok, eu entrei! Aguentem aí. Isso não deve demorar muito.",--Ok, I'm in! Stand by. This shouldn't take me long.
	pln_bb1_62_02 = "Hora de ligar, pessoal.",--Time to light it up, guys.
	pln_bb1_17_01 = "Boa. Aí está a caixa de energia. Tirar a fiação deve fazer um reset rígido no bloqueio de tempo.",--Good. There's the circuit box. Rewiring it should do a hard reset on the time lock.
	pln_bb1_05_01 = "Droga! Parece que precisaremos de acesso local. Provavelmente por um dos terminais dos funcionários. Descubram qual é. Tentem todos se for preciso.",--Damn it! Looks like we need local access. Most likely one of the staff terminals. Figure out which one. Try 'em all, if you have to.
	pln_bb1_07_02 = "Conectando agora. Melhor rezar pra esse ser o correto.",--Connecting now. Better pray this is the right one.
	pln_bb1_09_01 = "Esse não é o computador certo. Tentem outro. Talvez haja uma maneira de descobrir qual terminal nós precisamos.",--That was the wrong computer. Try another one. Maybe there's a way to figure out which terminal we need.
	pln_bb1_09_02 = "Esse terminal está errado. Continuem tentando. Procurem por alguma pista, o tempo está passando e nós precisamos encontrar o correto.",--That was the wrong terminal. Keep trying. Look for some clue, clock is ticking and we need to find the right one.
	pln_bb1_10_01 = "Sem códigos. Tente outro.",--No code. Try another one.
	pln_bb1_15_02 = "Bunker derrubado, gangue. Segurem as pontas até o tempo terminar.",--Bunker down, gang. Hold the line until the time lock finishes.
	pln_bb1_17_02 = "Removam esses circuitos. Isso deve resetar o bloqueio de tempo.",--Rewire those circuits. That should reset the time lock.
	pln_bb1_22_01 = "Vamos! Façam o bloqueio de tempo funcionarem de novo!",--Come on! Get the time lock going again!
	pln_bb1_23_02 = "Ótimo. Agora, por favor, mantenham os policiais longe do bloqueio de tempo.",--Great. Now, please, keep the cops away from the time lock.
	pln_bb1_24_01 = "Ajustem a tirolesa no telhado, e levem a bunda de vocês para o guindaste.",--Set the zip-line up on the roof, then haul ass to the crane.
	pln_bb1_24_02 = "Instalem a tirolesa no telhado. Em seguida, conectem-o ao guindaste.",--Get the zip-line set up on the roof. Then connect it to the crane.
	pln_bb1_31_01 = "Uhrm... talvez nós devêssemos ter contratado o Alex, afinal.",--Uhrm... maybe we should have hired Alex after all.
	pln_bb1_32_01 = "Peguem essas bolsas e levem-as até o cofre. Pode ser uma boa ideia pegar umas ferramentas de reparo também.",--Grab those bags and get them to the vault. Might be a good idea to take some spares too.
	pln_bb1_42_01 = "Abram a ventilação do elevador. A van está esperando por vocês na garagem.",--Open up the elevator shaft. The van's waiting for you in the garage.
	pln_bb1_42_02 = "Eu coloquei a van na garagem, mas vocês precisam ir pela ventilação do elevador.",--I got the van in the garage, but you need to go through the elevator shaft.
	pln_bb1_46_01 = "Agora desçam e levem as bolsas até a van. Cuidado aonde pisam.",--Now climb down and get the bags to the van. Watch your step.
	pln_bb1_52_01 = "Se esses lasers estão dificultando, vocês podem desativá-los usando cartões de acesso.",--If those lasers are giving you a hard time you can deactivate them with keycards.
	pln_bb1_54_02 = "Esse foi o primeiro console. Agora o segundo.",--That's the first console. Now the second.
	pln_bb1_57_02 = "Peguei o código. Voltem para a cofre.",--Got the code. Get back to the vault.
	pln_bb1_59_01 = "O jeito silencioso para abrir essas portas é usando as chaves. Vocês podem encontrá-las.",--The silent way to open those doors would be to use the keys. If you can find them.
	pln_bb1_61_01 = "Agora vão até o cofre e montem essa plataforma.",--Now get to the vault and assemble that rig.
	pln_bb1_66_01 = "Aí vai o alarme.",--That's the alarm.
	pln_bb1_end_01_01 = "Demorou duzentos anos, mas o Benevolent Bank foi finalmente roubado. Excelente trabalho!",--It took two hundred years, but the Benevolent Bank has finally been robbed. Outstanding work!
	pln_bb1_end_01_02 = "Esse é um dia histórico, gangue. Haha, vocês finalmente arrebentaram o Benevolent.",--This is a historic day, gang. Haha, you finally cracked the Benevolent.
	pln_bb1_end_02_01 = "Vamos falar de números. Treze gerentes ao longo de duzentos anos, com milhões de clientes, movimentando trilhões de dólares. E um roubo feito por quatro gangsters fodões.",--Let's talk numbers. Thirteen managers over two hundred years, with millions of customers, moving trillions of dollars. And one heist by four badass gangsters.
	pln_bb1_end_02_02 = "Vocês não só roubaram pilhas de dinheiro, como também roubaram milhões do preço das ações do Benevolent. Ótimo trabalho!",--Not only did you boost a crapload of cash, this caper wiped millions off Benevolent's share price. Great work!
	pln_bb1_end_03_01 = "Assaltantes estudarão a nossa técnica para esse trabalho nos próximos anos. Ótimo trabalho!",--Heisters will be studying your technique for this job for years to come. Great work!
	pln_bb1_end_03_02 = "Vocês acabaram de garantir os seus próprios lugares nos livros de história, gangue. Simplesmente excelente!",--You just ensured yourselves a place in the history books, gang. Simply outstanding!
	pln_bb1_end_04_01 = "Esse será para sempre um dia da carta vermelha para a comunidade criminosa. O dia em que a Gangue do Payday destruiu o Benevolent.",--This will forever be a Red Letter day for the criminal community. The day the Payday Gang broke the Benevolent.
	pln_bb1_end_04_02 = "(canta) Eles são a gangue que quebrou o banco em Monte Carlo. Excelente!",--(sings) "They're the gang that broke the bank at Monte Carlo". Outstanding!
	
	-- Objetivos
	hud_heist_big_mission17_hl = "Abra o Cofre",--Open the vault
	hud_heist_big_mission5_hl = "Espere o Bloqueio de Tempo terminar",--Wait for the time lock to finish
	hud_heist_big_mission18_hl = "Use a Tirolesa para chegar até o Guindaste",--Use the zip-line to get to the crane
	hud_heist_big_mission12 = "Leve as bolsas para o veículo de fuga.",--Get the loot to your escape vehicle and secure it.
	hud_heist_big_mission16_hl = "Consiga o Código do Computador do Gerente",--Get the code from the managers computer
	hud_heist_big_mission22_hl = "Coloque a termite",--Place the thermite
	hud_heist_big_mission8 = "Pegue as bolsas que contém as partes da furadeira e leve-as para o cofre.",--Pick up the bags containing the drill parts and bring them to the vault.
	hud_heist_big_mission9_hl = "Monte a Besta",--Assemble the Beast
	hud_heist_big_mission10_hl = "Perfure o Cofre",--Drill into the vault
	hud_heist_big_mission3_hl = "Encontre e Hackeie o Computador Correto",--Find and hack the correct computer
	hud_heist_big_mission13_hl = "Fuga Disponível!",--Escape available!
	hud_heist_big_mission10 = "Instale a furadeira para entrar no cofre.",--Drill your way into the vault.
	hud_heist_big_mission24 = "O helicoptero de fuga vai chegar no telhado do banco, coloque as bolsas lá.",--The escape helicopter will arrive soon on the roof of the bank, get the bags over there.
	hud_heist_big_mission15_hl = "Conceda acesso a partir dos Consoles de Segurança",--Grant access from the security consoles
	hud_heist_big_mission3 = "Descubra qual é o computador e acesse-o localmente. Na pior das hipóteses, você poderá sempre hackear todos eles.",--Figure out which staff computer it is and access it locally. Worst case scenario you can always hack them all.
	hud_heist_big_mission21 = "Pegue a bolsa que contém a termite.",--Pick up the bag containing the thermite.
	hud_heist_big_mission28 = "Entre no Benevolent Bank.",--Enter the Benevolent Bank.
	hud_heist_big_mission12_hl = "Assegure os Espólios",--Secure the loot
	hud_heist_big_mission23_hl = "Espere a termite terminar de queimar",--Wait for the thermite to finish burning
	hud_heist_big_mission13 = "A fuga já está disponível!",--The escape is now available!
	hud_heist_big_mission6 = "Devemos reconectar o sistema de segurança para iniciar o bloqueio de tempo.",--We must re-wire the security system to start the time lock.
	hud_heist_big_mission9 = "Use as partes da furadeira para montar a Besta.",--Use the drill parts to set up A Besta.
	hud_heist_big_mission16 = "Etapa de identificação 3/3: Acesse o computador do gerente do banco para obter os códigos do cofre.",--Identification step 3/3: Access the bank managers computer to get hold of the vault codes.
	hud_heist_big_mission4 = "Use o keypad para iniciar o bloqueio de tempo na porta que abrirá o portão de segurança para a área do cofre.",--Use the keypad to start the time lock on the door which will open the security gate to the vault area.
	hud_heist_big_mission11 = "Pegue todo espólio que você encontrar no cofre.",--Bag all the loot you can find in the vault.
	hud_heist_big_mission4_hl = "Inicie o Bloqueio de Tempo",--Start the time lock to open the security gate
	hud_heist_big_mission22 = "Coloque a termite em cima do cofre.",--Place the thermite over the vault.
	hud_heist_big_mission6_hl = "Religue o Bloqueio de Tempo",--Re-wire the time lock
	hud_heist_big_mission18 = "Instale a tirolesa no telhado e suba para o guindaste.",--Set up the zip-line on the roof and get up to the crane.
	hud_heist_big_mission27 = "Use o telefone para sinalizar o ônibus para atravessar a parede.",--Use the phone to signal to make the bus drive through the wall.
	hud_heist_big_mission25 = "Force a abertura das portas do elevador para que possamos acessar a ventilação do elevador.",--Force open the elevator doors so we can access the elevator shaft.
	hud_heist_big_mission19_hl = "Rotacione o Guindaste para que fique em cima da Clarabóia",--Rotate the crane so it is above the skylights
	hud_heist_big_mission23 = "Aguarde até que a termite queime até a parte interna do cofre.",--Hold the fort until the thermite has burned through the vault.
	hud_heist_big_mission20 = "Solte o porco cofre do guindaste.",--Release the piggybank from the crane.
	hud_heist_big_mission8_hl = "Pegue as Bolsas que contêm as partes da Furadeira",--Pick up the bags containing the drill parts
	hud_heist_big_mission28_hl = "Entre no Banco",--Enter the bank
	hud_heist_big_mission2_hl = "Obtenha Acesso Remoto ao Computador",--Get remote access to the computer
	hud_heist_big_mission2 = "Use o servidor para obter acesso remoto até o computador que contêm os códigos que podem abrir o portão de segurança para a área do cofre.",--Use the server to get remote access to the computer containing the codes to unlock the security gate to the vault area.
	hud_heist_big_mission26 = "Coloque os explosivos C4 na parede e exploda para fugir.",--Place the C4 explosive charges on the wall and blow it up in order to escape.
	hud_heist_big_mission21_hl = "Pegue a termite",--Pick up the thermite
	hud_heist_big_mission20_hl = "Solte o Porco Cofre",--Drop the piggy bank
	hud_heist_big_mission5 = "Espere pelo bloqueio de tempo abrir o portão de segurança.",--Wait for the timelock to open the security gate.
	hud_heist_big_mission7 = "Os policiais pararam o bloqueio de tempo. Use o keypad para iniciá-lo novamente.",--The cops stoped the time lock. Use the keypad to start it again.
	hud_heist_big_mission14 = "Etapa de identificação 1/3: Escaneie o polegar no leitor de impressão digital.",--Identification step 1/3: Scan the thumb in the fingerprint scanner.
	hud_heist_big_mission27_hl = "Sinalize o Ônibus",--Signal the bus
	hud_heist_big_mission7_hl = "Reinicie o Bloqueio de Tempo",--Unpause the time lock
	hud_heist_big_mission1 = "Descubra onde a sala do servidor está localizada e acesse-a.",--Find out where the server room is located and access it.
	hud_heist_big_mission14_hl = "Use o Leitor de Impressão Digital",--Use the fingerprint scanner
	hud_heist_big_mission19 = "Rotacione o guindaste sobre o banco para soltar o porco cofre.",--Rotate the crane over the bank to drop the piggy bank.
	hud_heist_big_mission26_hl = "Exploda a Parede",--Blow up the wall
	hud_heist_big_mission1_hl = "Encontre e Acesse a Sala de Servidores",--Locate and access the server room
	hud_heist_big_mission25_hl = "Abra as Portas do Elevador",--Open the elevator doors
	hud_heist_big_mission24_hl = "Espere o Helicóptero de Fuga chegar",--Wait for the escape helicopter to arrive
	hud_heist_big_mission15 = "Etapa de identificação 2/3: Use o console de segurança para conceder acesso ao cofre.",--Identification step 2/3: Use the security consoles to grant access to the vault.
	hud_heist_big_mission11_hl = "Pegue o espólio do Cofre",--Loot the vault
	hud_heist_big_mission17 = "Insira os códigos e abra o cofre.",--Input the vault codes and open the vault.
		}