Hooks:Add("LocalizationManagerPostInit", "doctorfantastic", function(loc)
	LocalizationManager:add_localized_strings({
	-- Nomes e Descrições
	heist_welcome_to_the_jungle = "Big Oil",--Big Oil
	heist_welcome_to_the_jungle_crimenet = "O Elefante precisa de uma invenção politicamente perturbadora.$NL;$NL;» Encontre mais Informações sobre o Inventor$NL;» Localize e Roube a Invenção$NL;» Localize e Roube a Invenção do Cientista",--The Elephant needs a politically-disruptive invention dealt with.$NL;$NL;» Find more information about the inventor$NL;» Locate and steal the invention
	heist_welcome_to_the_jungle_1_hl = "Club House",--Club House
	heist_welcome_to_the_jungle_1_briefing = "O Elefante nos deu a localização da gangue de motoqueiros que está procurando pelo dispositivo do cientista. Acho que estão bem perto de encontrá-lo - Precisamos dessa informação para chegar nele primeiro. Aposto que está no cofre deles.",--The Elephant gave us the location of the biker gang hunting for the scientist's little device. I think they're close to finding him - we need their intel so we can get to him first. I'm betting it's in their safe.
	pln_bigoil_stage1_brief_01b = "Aposto que está no cofre deles.",--I'm betting it's in their safe.
	pln_bigoil_stage1_brief_02 = "É, eles estão prontos para nós a julgar pelo número de guardas. Parece que eles tem câmeras também. Tenham certeza de chegar perto antes de começar a agir.",--Yeah, they're ready for us judging by the number of lookouts... Looks like they have cameras too. Make sure you get close before you hit 'em.
	pln_bigoil_stage1_brief_02b = "Não queremos eles nos impedindo de conseguir a informação. Encontrem o cofre, provavelmente estará lá.",--We don't want them stopping us from getting the intel before we get it. Find the safe, it's probably there.
	heist_welcome_to_the_jungle_2_hl = "Engine Problem",--Engine Problem
	heist_welcome_to_the_jungle_2_briefing = "Bem, examinei a informação e isso está ficando interessante. Verifiquem as pistas. Conheçam elas de cima a baixo. Precisamos fazer uma visita ao Laboratório do cara, e depois, roubar o seu motor de fusão.",--Well, I've been through the intel, and this is gonna be interesting. Check out the assets. Get to know them upside down. We need to sneak in to find this guy's lab, and, in the lab, his fusion engine.
	pln_bigoil_stage2_brief_01b = "Não é surpresa que a segurança vai estar rígida, então iremos pelo ar em vez de dirigir. Silenciosos e mortais. Encontrem o motor, e mandem ele pelo helicóptero. Boa sorte.",--No surprise security's going to be real tight, so we'll airdrop in instead of driving. Quiet and deadly. Find the engine, and i'll have it flown out. Good luck.

	-- Legendas (Dia 1)
	pln_bigoil_stage1_intro_a_01 = "Eu não sei como que os motoqueiros sabiam que viríamos mas agora eles sabem. Talvez a metanfetamina que estão usando dá a eles um sexto sentido.",--I don't know how the bikers know we're coming but they do. Maybe all that meth they're doing gives them a sixth sense...
	pln_bigoil_stage1_intro_a_01b = "Enfim, cheguem perto, invadam com tudo, encontrem o cofre, e peguem qualquer pedaço de informação que vocês acharem por lá. Peguem tudo.",--Anyway get close, hit 'em hard, find the safe, and get whatever intel you can find there. Take all of it.
	pln_bigoil_stage1_intro_a_02 = "Parece que eles estavam esperando uma briga. Sei que vocês darão uma pra eles. Encontrem o cofre e o endereço... peguem o máximo de informação que vocês puderem desses idiotas. Vamos nessa.",--Looks like they expect a fight. I know you will give em one. Find the safe and the address... get as much intel from these scumbags as you can. Let's roll.
	pln_bigoil_stage1_intro_a_03 = "Dirigir ou morrer - esse era o lema deles. Bom trabalho. Essa informação vai nos ajudar muito. Estudem-a com cuidado antes de invadir a mansão do cientista. Vamos lá roubar esse motor de fusão.",--Ride or die - that was their motto. Well done. This intel will help us greatly. Study it closely before we hit the scientists house. Let's go get this fusion engine.
	pln_bigoil_stage1_01_any_01 = "Certo, entrem na casa e achem o endereço, mas tomem cuidado.",--Alright, get to the house and find the address, be careful.
	pln_bigoil_stage1_06_any_01 = "Parecem códigos, isso pode ser útil.",--Looks like some codes, that'll come in handy.
	pln_bigoil_stage1_17_any_01 = "Eles estão vindo do sul pela Fábrica.",--They're coming from the south by the factory.
	pln_bigoil_stage1_end_a_01 = "Ok, a informação é boa. Vai nos ajudar a invadir a mansão que o cientista está se escondendo. Vamos nos preparar e ir pra lá.",--OK the intel is good. It'll help us plan the attack on the big villa that the scientist seems to be hiding in. Let's saddle up and go there.
	pln_bigoil_stage1_03_any_01 = "Vocês já encontraram? Provavelmente esconderam em um cofre.",--Have you found it yet? They probably kept it somewhere safe.
	pln_bigoil_stage1_end_b_01 = "Ok, temos o endereço - Ele mora numa mansão de alta segurança, nas montanhas, bem isolada de tudo e luxuosa. Estaremos às cegas sem informações. Preparem-se e vamos lá.",--OK we got the address - he lives in a high security villa, up in the mountains, real secluded, luxurious area. We will be going in blind with no intel. Arm yourself and let's go. 
	pln_bigoil_stage1_05_any_01 = "Isso parece ser um Cartão de Acesso, provavelmente poderemos usar depois.",--That seems to be a keycard, we can probably use that later.
	pln_bigoil_stage1_04_any_01 = "Esse é o endereço! Temos o que precisamos. Voltem para a van e deem o fora.",--That's the address! We've got what we need. Get back to the van and we can get out of here.
	pln_bigoil_stage1_end_b_02 = "Temos o endereço - o problema é que não conseguimos nenhuma informação. Isso significa que vamos invadir com tudo e sem saber o que irá nos aguardar. O tempo está acabando - vamos para as montanhas e roubar esse motor de fusão.",--We got the address - problem is we did not get any intel. This means we are coming in hard and with no info on what to expect. Time is ticking - let's get up the mountains and steal this engine. 
	pln_bigoil_stage1_10_any_01 = "Essas fotos podem nos ajudar depois.",--Those pictures might help us later.
	pln_bigoil_stage1_07_any_01 = "Isso parece ser útil.",--That looks useful.
	pln_bigoil_stage1_16_any_01 = "Eles estão vindo do oeste, pela construção.",--They're coming from the west, by the construction site.
	pln_bigoil_stage1_02_any_01 = "Certo galera, procurem em volta. O endereço está em algum lugar.",--OK guys, search the place. I know the address is there somewhere.
	pln_bigoil_stage1_15_any_01 = "Eles estão vindo do leste, pela Floresta.",--They're coming from the east, by the forest.
	pln_bigoil_stage1_08_any_01 = "Parece que é informação. Vai ser útil mais pra frente.",--Looks like some intel. That'll come in handy.
	pln_bigoil_stage1_14_any_01 = "Caralho! Eles possuem minas terrestres ligadas ao sistema de câmera!",--Holy shit! They've got mines hooked up to the camera system!
	pln_bigoil_stage1_09_any_01 = "Provavelmente tem informação útil no meio desses arquivos...",--There's probably some useful info among these files...
	pln_bigoil_stage1_11_any_01 = "Isso é provavelmente as plantas da construção.",--That's probably blueprints of the building.
	pln_bigoil_stage1_12_any_01 = "Droga, os policiais chegaram!",--Shit, the cops are here!
	pln_bigoil_stage1_13_any_01 = "Droga! Eles viram vocês!",--Damn it! They saw you!
	pln_bigoil_stage1_18_any_01 = "Boa, levem o dinheiro para a van.",--Nice, bring the money to the van.
	pln_bo1_08_any_02 = "Ok, legal - poderá ser útil.",--OK, cool - might come in handy.
	pln_bo1_04_any_01 = "Ok, é isso! Agora abram essa coisa.",--OK, that's it! Now get that thing open.
	pln_bo1_01_any_03 = "Quietos agora. Vão de fininho e acertem eles com força.",--Quietly now. Sneak up and hit them hard. 
	pln_bo1_13_any_01 = "Eles estão vindo do leste, pela Floresta.",--They're coming from the east, by the forest.
	pln_bo1_07_any_02 = "Códigos. Tragam eles.",--Codes. Bring them.
	pln_bo1_02_any_03 = "Não deixem eles destruírem nenhuma informação. Peguem tudo!",--Don't let them destroy any intel. Get it all!
	pln_bo1_04_any_02 = "Vocês acharam. Agora abram e peguem aquele endereço.",--You found it. Now get it open and get that address.
	pln_bo1_17_any_02 = "Vocês estão bem? Os motociclistas agem como se fosse uma guerra - Peguem eles!",--You guys OK? Bikers sure act like it is war - go get 'em!
	pln_bo1_03_any_03 = "Verifiquem o cofre - Encontre-o. Rápido!",--Check the safe - find it. Fast!
	pln_bo1_20_any_02 = "Esperava fazer isso sem a polícia pelo menos uma vez.",--Was hoping we'd do this without police for once.
	pln_bo1_19_any_02 = "Ótimo! Traga a bolsa para a van.",--Sweet! Bring the bag to the van.
	pln_bo1_07_any_01 = "Parecem alguns códigos, isso com certeza vai ser útil.",--Looks like some codes, that'll come in handy.
	pln_bo1_14_any_01 = "Eles estão vindo do sul pela Fábrica.",--They're coming from the south by the factory.
	pln_bo1_09_any_02 = "Plantas de construção - Perfeito! Muito bem.",--Blueprints - perfect. Well done.
	pln_bo1_11_any_03 = "Ok, isso é uma luta - Eles vão destruir a informação!",--OK, this is a fight - they will destroy the intel!
	pln_bo1_06_any_02 = "Cartão de Acesso para algum lugar no próximo local. Ótimo.",--Keycard to somewhere in on the next location. Sweet.
	pln_bo1_01_any_02 = "Ok, é esse o clube. Os motociclistas possuem o endereço que nós precisamos. Entrem furtivamente lá.",--OK, that's the clubhouse. Bikers' got the address we need. Sneak in.
	pln_bo1_15_any_03 = "As câmeras vão definir as minas, pessoal! Fiquem longe!",--Cameras will set of the mines, guys! Stay away!
	pln_bo1_11_any_02 = "Merda! Os motociclistas estão no nosso caso.",--Shit! Bikers are on your case.
	pln_bo1_10_any_01 = "Parecem chaves de um avião ou algo assim.",--Looks like keys to an airplane or something.
	pln_bo1_12_any_03 = "Local de construção - Policiais chegando.",--Construction site - cops coming in.
	pln_bo1_18_any_02 = "Cara, eles estão fudendo mais informações!",--Guys they are fucking up more intel!
	pln_bo1_12_any_02 = "Policiais vindo no seu lado oeste. Local de construção.",--Cops coming up on your west side. Construction site.
	pln_bo1_19_any_01 = "Ótimo! Levem isso para a van.",--Nice! Get it to the van.
	pln_bo1_05_any_01 = "Sim, esse é o endereço dos inventores. Lindo.",--Yep, that's the inventors address. Beautiful.
	pln_bo1_06_any_01 = "Parece ser um Cartão de Acesso, provavelmente podemos usar isso mais tarde.",--That seems to be a keycard, we can probably use that later.
	pln_bo1_15_any_01 = "Eles minaram o lugar! Cuidado onde pisam aí!",--They've mined the place! Watch your step!
	pln_bo1_03_any_01 = "Já encontraram o cofre? O endereço provavelmente estará lá.",--Have you found the safe yet? The address is probably in there.
	pln_bo1_18_any_03 = "A Informação pessoal, a informação! Peguem!",--Intel guys, intel! Get it!
	pln_bo1_05_any_02 = "É esse o endereço! Já temos o que precisamos. Voltem para a van e poderemos dar o fora daqui.",--That's the address! We've got what we need. Get back to the van and we can get out of here.
	pln_bo1_13_any_03 = "Verifiquem as árvores - Policiais avançando.",--Check the trees - cops advancing.
	pln_bo1_09_any_01 = "Parecem plantas da casa do inventor. Que delícia.",--Looks like blueprints of the inventor's house. Very tasty.
	pln_bo1_14_any_03 = "Pela Fábrica - policiais chegando.",--By the factory - cops incoming.
	pln_bo1_18_any_04 = "Está tudo indo pro inferno - Peguem a informação!",--It is all going to hell - get the intel!
	pln_bo1_15_any_02 = "Porra! São minas terrestres. Fiquem fora da grama e também do campo de visão da câmera.",--Fuck! That's landmines. Keep off the grass and stay out of the camera view.
	pln_bo1_18_any_01 = "Droga, eles estão queimando.",--Damn it, they're burning it!
	pln_bo1_03_any_02 = "Procurem pelo cofre, pessoal. Tem que estar por aqui em algum lugar.",--Check for the safe guys. Got to be there somewhere.
	pln_bo1_17_any_01 = "Puta merda! Eles colocaram armadilhas nas portas!",--Holy shit! They've boobytrapped the doors!
	pln_bo1_12_any_01 = "Eles estão vindo do oeste, pelo local de construção.",--They're coming from the west, by the construction site.
	pln_bo1_13_any_02 = "Floresta - Policiais atravessando.",--Forest - cops coming through.
	pln_bo1_08_any_03 = "Ótimo, vocês pegaram alguns. Vamos checar isso mais tarde.",--Great, you got some. Let's check this later.
	pln_bo1_04_any_03 = "É isso. Abram e vamos ver o que temos.",--That's it. Open it up and let's see what we got.
	pln_bo1_01_any_01 = "Certo, vão até a casa e encontrem o endereço, e tenham cuidado.",--Alright, get to the house and find the address, be careful.
	pln_bo1_20_any_01 = "Merda, os policiais devem ter recebido uma ligação.",--Crap, the cops must have recieved a call.
	pln_bo1_14_any_02 = "Fábrica, policiais aos montes.",--Factory, cops in numbers.
	pln_bo1_02_any_02 = "Ok, sem tempo a perder, peguem todas as informações.",--OK, no time to lose, get all that intel.
	pln_bo1_02_any_01 = "Ok pessoal, procurem no local. Eles possuem um cofre em algum lugar, provavelmente estará lá.",--OK guys, search the place. They have a safe somewhere, it's probably in there.
	pln_bo1_08_any_01 = "Isso pode ser útil.",--That might be useful.
	pln_bo1_10_any_02 = "Parece ser a chave de um avião.",--Seems to be keys to an airplane.
	pln_bo1_11_any_01 = "Droga! Eles viram vocês!",--Damn it! They've spotted you!
	pln_bo1_16_any_01 = "Eles eletrificaram a cerca! Encontrem um jeito de contornar isso!",--They've electrified the fence! Find a way around it!
	pln_bo1_16_any_02 = "Ai - isso com certeza chamou a atenção.",--Ouch - that sure drew attention.
	
	-- Legendas (Dia 2)
	pln_bigoil_stage2_intro_a_01 = "Todo mundo está aqui, ótimo. A mansão fica do outro lado da pista de pouso. Cheguem até lá, e encontrem o Laboratório. Quando encontrar o motor, leve-o de volta a esse campo de aviação e esperem pela coleta.",--Everyone's here, good. The villa's on the other side of the airstrip. Sneak in there, find the lab. when you've found the engine,  hustle it back to this airfield and wait for pick-up.
	pln_bigoil_stage2_intro_a_01b = "E não derrubem isso...",--And don't drop it...
	pln_bigoil_stage2_intro_a_02 = "Aterrissagem nota dez. Bom drop. Vocês estão a um passo de distância de sua mansão. Cheguem lá tranquilamente pelo campo de aviação, e entrem na casa. Encontrem o motor e traga-o de volta aqui. Eu farei o resto.",--Ten point landing. Nice drop. You're a click away from his villa. Sneak across the airfield, get into the house. Find the engine, and bring it back here. I will do the rest.
	pln_bigoil_stage2_intro_a_03 = "Na mira. Ponto de divisão: Entre na casa, encontre o Laboratório, pegue o motor, voltem para esse campo de aviação, e no fim fuja. Boa sorte.",--Bull's-eye. Point Break-down: get inside the house, find the lab, get the engine, get back to this airfield, escape. Good luck.
	pln_bigoil_stage2_end_a_01 = "O Elefante vai ficar muito animado. Lá está o financiamento da sua campanha pela petroleira até 2050. Muito profissional, pessoal.",--The Elephant will be very excited. That's his campaign funding by big oil until 2050 right there. Very professional, folks.
	pln_bigoil_stage2_20_any_01 = "Não... Isso também não está funcionando. Me tragam outro, estarei aí em um segundo.",--Nope... This isn't working either.  Get me another one, I'll be there in a sec.
	pln_bigoil_stage2_23_any_01 = "Eles estão implantando a SWAT no telhado!",--They're deploying SWATs on the roof!
	pln_bigoil_stage2_11_any_01 = "Está feito! Abram a porta do Laboratório!",--It's done! Open the lab door!
	pln_bigoil_stage2_15_any_01 = "Estamos a cerca de um minuto de distância.",--We're about a minute away.
	pln_bigoil_stage2_14_any_01 = "Ok, eu vejo isso! Estaremos aí em breve.",--OK I see it! We'll be there soon.
	pln_bigoil_stage2_08_any_03 = "Eu perdi a conexão, preciso que vocês liguem a energia.",--I lost connection, I need you to get the power back.
	pln_bigoil_stage2_16_any_01 = "Ok, estou chegando, preparem o servidor!",--OK, I'm coming in, get the server ready!
	pln_bigoil_stage2_end_b_03 = "Vocês simplesmente não amam a Ciência? Ótimo trabalho em equipe! Retiramos o motor até... Bem, até decidirmos liberá-lo nós mesmos. Aproveitem mais um dia de pagamento.",--Don't you just love science? Great team effort. We've retired the engine until... Well until we decide to liberate it ourselves. Enjoy the payday.
	pln_bigoil_stage2_08_any_02 = "Religuem o servidor!",--Get the power to the server back on!
	pln_bigoil_stage2_06_any_01 = "Certifiquem-se de que ninguém perceba o hack...",--Make sure no one notices the hacking...
	pln_bigoil_stage2_05_any_01 = "Estou dentro, isso pode demorar um pouco...",--I'm in, this might take a few...
	pln_bigoil_stage2_17_any_01 = "Me passem o reator, rápido, agora!",--Hand me the reactor, quickly now!
	pln_bigoil_stage2_24_any_01 = "Eles colocaram Snipers. Fiquem abaixados.",--They've deployed snipers. Stay low.
	pln_bigoil_stage2_01_any_01 = "Certo, vocês estão vendo a casa? Entrem e encontrem a Sala do Servidor. Precisamos invadir o sistema de segurança para chegar ao Laboratório.",--Alright, do you see the house? Get inside and find the server room. We need to hack into the security system to get to the lab.
	pln_bigoil_stage2_25_any_01 = "Vocês podem usar os códigos que encontrou para fechar as persianas.",--You can use the codes you found to close the window shutters.
	pln_bigoil_stage2_20_any_03 = "Não, tem alguma coisa errado com esse aqui, voltando para pegar outro...",--No, there's something wrong with this one, heading back to pick up another one...
	pln_bigoil_stage2_end_a_02 = "Bem, sem fusão, mas pelo menos podemos dirigir carros movidos a gasolina por muito mais tempo desse jeito. Eu amo meu Firebird tanto quanto qualquer outro homem.",--Well, no fusion, but at least we get to drive gas-guzzling cars a lot longer this way. I love my Firebird as much as the next man.
	pln_bigoil_stage2_end_b_02 = "Bom trabalho, pessoal. Foi uma coisa terrível de mover, mas é o motor certo e está bem travado. Talvez um dia nós iremos trabalhar como freelancer e pegar de voltar, hein?",--Good work people. That was a hell of a thing to move, but it's the right engine and it's locked up tight. Maybe one day we'll go freelancing and take it back, huh?
	pln_bigoil_stage2_09_any_01 = "Ótimo! Agora configurem a conexão novamentente.",--Great! Now set up the connection again.
	pln_bigoil_stage2_07_any_01 = "Porra! Eles desligaram a energia do servidor! Liguem ela de novo!",--Damn it! They've turned of the power to the server! Get it back up!
	pln_bigoil_stage2_10_any_01 = "Ótimo trabalho, eu tenho conexão!",--Great job, I've got connection!
	pln_bigoil_stage2_02_any_01 = "Essa é a Sala do Servidor, entrem e conectem-me ao computador.",--That's the server room, get inside and hook me up to the computer.
	pln_bigoil_stage2_end_a_03 = "Vocês sabem quem é Tucker? Espero que não. Ótimo trabalho.",--You guys know who Tucker is? I hope you don't. Great work back there.
	pln_bigoil_stage2_18_any_01 = "Obrigado, vou mandar umcara aqui inspecioná-lo e se for o certo estaremos prontos para ir. Portanto, aguardem um segundo.",--Thanks, I'll have my man here inspect it and if it's the right one we're good to go. So hang tight for a second.
	pln_bigoil_stage2_19_any_01 = "Desculpe galera, ele disse que não é esse. Estarei de volta em alguns minutos para que vocês consigam me entregar o que está funcionando.",--Sorry guys, he says this ain't the one. I'll be back in a few so you can give me the working one.
	pln_bigoil_stage2_13_any_01 = "Ótimo, acionem o sinalizador para que possamos pousar!",--Great, set off the flare so we can land!
	pln_bigoil_stage2_22_any_01 = "Os policiais estão aqui, mantenham a posição!",--Cops are here, hold your ground!
	pln_bigoil_stage2_end_b_01 = "Ok, pessoal - foi um trabalho pesado! O motor certo foi entregue e agora está bloqueado. Nosso dia de pagamento está chegando!",--OK, guys - that was some heavy lifting! The right engine has been delivered and is now locked away. Our payday is coming up!
	pln_bigoil_stage2_09_any_02 = "Certo, me conectem de novo.",--Alright, connect me again.
	pln_bigoil_stage2_08_any_01 = "Eles desligaram a energia, liguem de volta!",--They pulled the power, get it back on!
	pln_bigoil_stage2_03_any_01 = "Vocês podem usar o Cartão de Acesso que encontrou antes.",--You can use the keycard you found.
	pln_bigoil_stage2_04_any_01 = "Bom, agora configurem a conexão.",--Good, now set up the connection.
	pln_bigoil_stage2_12_any_01 = "Certo, parece que temos... 11... 12 protótipos. Vejam se conseguem encontrar algo pela casa que indique qual que está funcionando. Então pegue-o e entregue-o para mim.",--Alright, looks like we have... 11... 12 prototypes. See if you can find something around the house that can indicate which is the working one. Then pick it up and get it to me.
	pln_bigoil_stage2_20_any_02 = "Esse parece estar com defeito, voltarei para pegar outro.",--This one seems to be malfunctioning, I'll be back to pick up another one.
	pln_bigoil_stage2_21_any_01 = "Ótimo trabalho, pessoal! Esse parece ser o certo! É melhor vocês sairem daí o mais rápido possível.",--Nice work guys! This seems to be the right one! You guys better head out of there ASAP.
	pln_bo2_39_any_02 = "OK, ele vai nos trazer. Vamos verificar.",--OK, he flies it to us. We will verify it.
	pln_bo2_38_any_02 = "Joguem aí dentro!",--Load it in!
	pln_bo2_45_any_01 = "Senhor Doutor Fantástico! Vocês arrasaram. Isso que é Ciência - muito bom trabalho, equipe. Agora saiam daí! Usem o avião.",--Mr Dr Fantastic Sir! You nailed it. Thats some science - well done team. Get your big brains out of there! Use the plane.
	pln_bo2_50_any_01 = "Helicóptero no telhado! Isso não parece bom galera!",--Blackhawk on the roof! This looks bad guys!
	pln_bo2_30_any_01 = "Boa, agora façam a conexão de novo.",--Good, now set up the connection again.
	pln_bo2_44_any_01 = "Doutor Fantástico! Vocês são super espertos. Temos a motor certa e vocês estão ricos. Agora deem o fora! O helicóptero está vindo.",--Dr Fantastic! You guys sure are smart. We got the right engine and you are rich. Now make it out of there! Chopper is incoming.
	pln_bo2_34_any_03 = "Merda, isso é outro nível de Ciência - usem os cérebros - algum código de cor, ingredientes químicos e algo do tipo podem ser boas pistas.",--Shit this is top science stuff - use those brains - any color code, chemicals or such can be a clue.
	pln_bo2_50_any_03 = "Telhado, telhado! Helicóptero no telhado!",--Roof, Roof! Blackhawk on the roof!
	pln_bo2_48_any_01 = "OK, ele está reabastecendo. Eu disse pra ir rápido...",--OK, he's refueling now. I've told him to hurry but...
	pln_bo2_21_any_03 = "A casa está logo após essas árvores. Apressem-se.",--The house is right across and through the woods. Leg it. 
	pln_bo2_48_any_03 = "O piloto está reabastecendo o helicóptero - prometo que ele iráa voltar logo.",--The pilot is refueling the chopper - he will be back soon I promise.
	pln_bo2_30_any_03 = "Me conectem de novo.",--Hook me up again.
	pln_bo2_28_any_03 = "Estamos indo bem - mantenham distância dos guardas.",--We are doing good - keep away from the guards.
	pln_bo2_41_any_03 = "Droga, parece que esse não está funcionando! Estou mandando o helicóptero de volta para pegar outro.",--Damn it, this one seems to be malfunctioning! I'm sending the chopper back to pick up another one.
	pln_bo2_47_any_02 = "Hmm, nós temos um pequeno problema. O helicóptero está sem combustível depois de todo esse vai e vem. Ele vai voltar após reabastecer. Aguentem mais um pouco aí!",--Hmm we got a slight problem. Chopper is running out of fuel after all these back and forths. He will be back after refueling. Hold you ground!
	pln_bo2_40_any_03 = "OK, estamos inspecionando... Até agora tudo bem... ele está fazendo os testes...",--OK, we're inspecting it... So far so good... He's running tests now...
	pln_bo2_34_any_01 = "Pessoal... Vocês conseguem achar pistas sobre como se parece o motor correto?",--Guys... Can you see any hints on what the correct one should look like?
	pln_bo2_50_any_02 = "Helicóptero! Helicóptero descendo! Atirem nele!",--Blackhawk! Blackhawk coming down! Gun up team!
	pln_bo2_28_any_02 = "Fiquem longe dos guardas.",--Stay clear of the guards.
	pln_bo2_24_any_03 = "O Laboratório que estamos atrás deve abrir ao hackear o servidor deles. Encontrem a Sala dos Servidores.",--The lab we are after should open by hacking their server. Find the server room.
	pln_bo2_29_any_03 = "Perdi a conexão, preciso que vocês religuem a energia.",--I lost connection, I need you to get the power back.
	pln_bo2_33_any_01 = "Certo, estamos dentro, encontrem o motor de fusão correto. Verifiquem as notas. Descubram!",--Alright, we are in. Find the correct working fusion engine. Check his notes. Figure it out!
	pln_bo2_49_any_01 = "Isso! Ele reabasteceu e já está voltando aí!",--Yes! He's fueled up and heading back!
	pln_bo2_51_any_01 = "Porra! O alarme! A casa inteira sabe que estamos aqui agora!",--Damn it! The alarm! The whole house knows we are coming now!
	pln_bo2_42_any_01 = "Sim! Essa é a maquina certa. Estou mandando o helicóptero para extrair vocês! Aguentem aí!",--Yes! This is the one. I'm sending the helicopter to pick you up! Hang tight!
	pln_bo2_22_any_01 = "E... Alex fez a entrega requisitada. Em algum lugar.",--And... Alex made the requested drop. Somewhere.
	pln_bo2_42_any_02 = "Ótimo! Essa é a certa. Energia de fusão está a 100%. Obrigado, pessoal. Agora deem o fora daí.",--Sweet! That's the one. Fusion power in full swing. Thanks guys. Now get out of there. 
	pln_bo2_35_any_01 = "Muito bom, agora iluminem o sinalizador para que o helicóptero possa pousar!",--Great, Set off the flare so the chopper can land!
	pln_bo2_22_any_02 = "Procurem pelo pacote de munição do Alex... Isso me lembra da Sala do Pânico...",--Check for Alex ammo drop... Panic room all over again...
	pln_bo2_40_any_01 = "Ok, já temos o motor, vou mandar o cara aqui inspecionar.",--We've got the engine, I'll have my guy here inspect it.
	pln_bo2_27_any_02 = "Ok, estou na rede dele. O Laboratório vai abrir logo logo.",--OK, I'm in his system. Lab will open shortly.
	pln_bo2_49_any_02 = "O helicóptero está voltando - Desculpem a demora.",--Chopper is heading back- sorry it took so long.
	pln_bo2_30_any_02 = "Certo, me conectem de novo.",--Alright, connect me again.
	pln_bo2_36_any_03 = "Ok, o helicóptero está vindo para pegar o motor de fusão.",--OK, chopper is coming in to pick up that Fusion Engine.
	pln_bo2_23_any_01 = "Alex deixou a munição, eu sabia que estava certo em dar a ele uma terceira chance.",--Alex made the drop, I knew I was right in giving him a third chance.
	pln_bo2_22_any_03 = "Alex... esse idiota deixou a munição... em algum lugar.",--Alex... The idiot dropped the ammo... Elsewhere. 
	pln_bo2_36_any_02 = "O helicóptero está a caminho. Esperem um pouco.",--Chopper is on its way. Stay put.
	pln_bo2_26_any_03 = "Boa, isso deve nos ajudar a abrir a porta do Laboratório.",--Good this should help us get the lab door open.
	pln_bo2_47_any_01 = "Desculpe galera, o piloto disse que precisará recarregar o combustível... e vai demorar um pouco. Aguentem mais um pouco, ok?",--I'm sorry guys, the pilot says he needs to refuel... And it's gonna take a while. Just hang in there for a while, OK?
	pln_bo2_25_any_03 = "Encontrem a Sala de Servidores.",--Find the server room. 
	pln_bo2_39_any_01 = "Certo! Ele vai trazer aqui para inspecionarmos.",--Alright! He'll bring it over here so we can inspect it.
	pln_bo2_31_any_03 = "Mantenham-se firmes. Estou conectado.",--Keep it steady. I'm connected.
	pln_bo2_35_any_03 = "Marquem o pouso - Usem o sinalizador e o helicóptero vai vir.",--Mark the landing - use the flare and the chopper will come in.
	pln_bo2_36_any_01 = "Certo, o helicóptero está a caminho.",--Alright, the chopper is on its way.
	pln_bo2_37_any_03 = "Helicópteros pousando. Joguem o motor dentro e vamos esperar que seja o certo.",--Helicopters landing. Load up the engine and hope it is the one.
	pln_bo2_29_any_01 = "Religuem a energia da Sala de Servidores!",--Get the power to the server back on!
	pln_bo2_42_any_03 = "A reação de fusão foi confirmada - tudo certo! Vocês já podem dar o fora dessa merda!",--Fusion reaction is confirmed - all good and green. You guys skip out of there !
	pln_bo2_26_any_02 = "Ótimo - agora me conectem na rede deles.",--Great - now log me into the system.
	pln_bo2_48_any_02 = "Ok, ele está reabastecendo o helicóptero. Aguentem firme pessoal!",--OK, he is filling up that chopper now. Hold on guys!
	pln_bo2_21_any_01 = "Certo, vocês conseguem ver a casa? Entrem lá. Fiquem de olho em câmeras e guardas.",--Alright, do you see the house? Get inside. Look out for guards and cameras.
	pln_bo2_29_any_02 = "Eles desligaram a energia, religue-a!",--They pulled the power, get it back on!
	pln_bo2_21_any_02 = "A casa está entre essas árvores, conseguem ver? Cheguem até lá.",--House is beyond those trees, see? Sneak right up.
	pln_bo2_27_any_01 = "Estou dentro, pode demorar um pouco para abrir as portas do Laboratório.",--I'm in, might take a few to get the lab door open.
	pln_bo2_46_any_01 = "Certo senhores! É hora de dar o fora daí!",--Alright gentlemen! It's time to get the hell out of there!
	pln_bo2_24_any_01 = "Os protótipos devem estar no Laboratório. Para obter acesso a eles precisamos hackear o servidor principal. Encontrem a Sala de Servidores.",--The prototypes should be in the lab. To gain access to it we need to hack the main server. Find the server room.
	pln_bo2_25_any_02 = "Sala de Servidores - Encontrem-na.",--Server room - find it.
	pln_bo2_31_any_02 = "Consegui conexão. Continuem trabalhando.",--Got connection. Keep working.
	pln_bo2_24_any_02 = "Encontrem a Sala de Servidores. De lá poderemos abrir a porta do Laboratório.",--Find the server room. From there we should be able to open the lab door.
	pln_bo2_31_any_01 = "Bom trabalho, estou conectado.",--Great job, I'm connected.
	pln_bo2_39_any_03 = "Quando chegar aqui eu vou verificar. Esperem um pouco.",--Once here I will have it verified. Stay put. 
	pln_bo2_49_any_03 = "Finalmente, o piloto do helicóptero está voltando para buscar vocês pessoal. Desculpem a demora.",--Finally, the chopper pilot is heading back to get you guys. Sorry for the hold up.
	pln_bo2_43_any_02 = "Ahá! É esse mesmo! Fusão fria, bem aqui. Vocês já tem a chave do avião, lembram? Vazem desse caralho de lugar!",--Aha! That's it! Cold Fusion, right here. You've got the keys to his airplane, remember? Get the hell out of there!
	pln_bo2_29_any_04 = "Droga, perdemos a energia do servidor! Liguem-a!",--Damn it! I lost power to the server! Get it back up!
	pln_bo2_26_any_01 = "Boa! É o servidor, agora estabeleçam a conexão.",--Great! That's the server, now set up the connection.
	pln_bo2_32_any_01 = "Tudo pronto! Abram a porta do Laboratório!",--It's done! Open the labdoor!
	pln_bo2_46_any_03 = "Bom trabalho. Entrem no helicóptero e vamos pegar o nosso pagamento.",--Well done. Get into the chopper and lets go get our payday.
	pln_bo2_32_any_02 = "Ok, a porta do Laboratório está destrancada - Abram ela.",--OK, the lab door is unlocked - open it.
	pln_bo2_28_any_01 = "Tenham certeza de que os guardas não vão encontrar vocês.",--Make sure the guards don't spot us now.
	pln_bo2_25_any_01 = "Lembrem-se, vocês estão procurando pela Sala de Servidores.",--Remember you're looking for the server room.
	pln_bo2_47_any_03 = "Ah... OK pessoal, temos que reabastecer um pouco o helicóptero. O tanque está vazio. Vocês precisam esperar por uns 10 ou 15 minutos.",--Ah... OK guys, we got a small refuling need for the chopper. He is dry. You guys gotta stay put for about 10 - 15 minutes. 
	pln_bo2_33_any_03 = "Ah OK... Parece que tem bastante desses motores aqui. Encontrem o correto.",--Ah OK... So, seems to be a bit too many of them here. Fusion Engines that is. Find the correct one.
	pln_bo2_23_any_03 = "O Alex conseguiu. A munição está logo aí.",--Alex nailed it. Ammo is right there.
	pln_bo2_38_any_01 = "Joguem o motor dentro!",--Throw in the engine!
	pln_bo2_35_any_02 = "Acendam o sinalizador para que eu possa enviar o helicóptero.",--Pop the flare so we can bring the chopper in.
	pln_bo2_41_any_01 = "Parece que estamos sem sorte. Não é essa. Mandem outra. Estou mandando o helicóptero para pegar outro motor.",--Looks like we're out of luck. This one's no good. Go get me another. I'm sending the chopper back to pick it up.
	pln_bo2_27_any_03 = "OK, estou dentro. Vou abrir o Laboratório logo logo.",--OK, I'm in. I'll get the lab door open in no time.
	pln_bo2_41_any_02 = "Desculpe galera, ele disse que essa não é a certa. O helicóptero vai voltar em pouco tempo para que vocês possam mandar outra, esperamos que seja a certa dessa vez.",--Sorry guys, he says this ain't the one. The chopper will be back in a few so you can get another one over here, hopefully the right one.
	pln_bo2_41_any_04 = "Toda quebrada e saindo fumaça essa aqui. Preciso de uma nova do Laboratório.",--All broken and smoking this one. Get me a fresh one from the lab.
	pln_bo2_37_any_01 = "OK, o helicóptero está vindo, preparem o protótipo.",--OK, chopper's coming in, get the prototype ready.
	pln_bo2_23_any_02 = "Bem no alvo. O Alex mandou bem agora.",--Smack daddy in the middle. Alex dropped good.
	pln_bo2_33_any_02 = "OK, doutores - Mostrem suas habilidades de tecnologia. Descubram qual o motor de fusão é o correto. Vão!",--OK, doctors - bring your MIT skills. Figure out which one is the correct fusion engine. Go!
	pln_bo2_34_any_02 = "Verifiquem os papéis, anotações e computadores. Qualquer coisa que sirva de pista para o motor correto.",--Check his papers, notes and computers. Anything for a hint on what is correct here.
	pln_bo2_37_any_02 = "OK, o helicóptero chegou - Coloquem nele o motor.",--OK, chopper is here - get the engine loaded up.
	pln_bo2_40_any_02 = "Ele entregou o motor. Vou pedir pro cara aqui inspecionar, se for o certo vocês podem ir embora. Aguentem um pouco.",--He delivered the engine. I'll have my man here inspect it, and if it's the right one we're good to go. So hang tight for a sec.
	pln_bo2_43_any_01 = "Bom trabalho pessoal! Esse parece ter sido o motor correto! Melhor vocês saírem logo daí. Usem as chaves do avião que vocês acharam.",--Nice work guys! This seems to be the right one! You guys better head out of there ASAP. Use the plane keys you found.
	pln_bo2_46_any_02 = "OK, vocês me trouxeram! Agora deixa eu tirar vocês daí.",--OK, you delivered! Now let me get you out of there.
	
	-- Objetivos (Dia 1)
	hud_e_welcome_jungle_stage1_mission1 = "Encontre um caminho até a casa.",--Make your way to the house
	hud_e_welcome_jungle_stage1_mission1_hl = "Chegue na Casa",--Get to the house
	hud_e_welcome_jungle_stage1_mission3_hl = "Fuga está Disponível",--Escape is available
	hud_e_welcome_jungle_stage1_mission2 = "Encontre o endereço, localize o cofre e abra-o.",--Find the address, locate the safe and open it up
	hud_e_welcome_jungle_stage1_mission2_hl = "Encontre o Endereço",--Find the address
	hud_e_welcome_jungle_stage1_mission3 = "Vá para o veículo de fuga.",--Get to the escape vehicle
	
	-- Objetivos (Dia 2)
	hud_e_welcome_jungle_stage2_mission3_hl = "Religue a Energia",--Get the power back on
	hud_e_welcome_jungle_stage2_mission9_hl = "Abra o Laboratório",--Open the lab door
	hud_e_welcome_jungle_stage2_mission1_hl = "Entre na Sala dos Servidores",--Get into the server room
	hud_e_welcome_jungle_stage2_mission4_hl = "Descubra qual é o Motor certo",--Figure out which engine it is
	hud_e_welcome_jungle_stage2_mission7 = "Aguente enquanto espera pelos resultados.",--Hold the fort while waiting for the results
	hud_e_welcome_jungle_stage2_mission5_hl = "Sinalize ao Helicóptero",--Call down the helicopter
	hud_e_welcome_jungle_stage2_mission1 = "Encontre o caminho para a casa, e entre na sala de servidores.",--Find your way into his house, and get into the server room
	hud_e_welcome_jungle_stage2_mission8_hl = "Leve outro Motor para o Helicóptero",--Take another engine to the helicopter
	hud_e_welcome_jungle_stage2_mission6 = "Leve o motor para o helicóptero e espere ele ser analisado.",--Throw the engine into the helicopter and wait for it to be analyzed
	hud_e_welcome_jungle_stage2_mission6_hl = "Leve o Motor para o Helicóptero",--Take the engine to the helicopter
	hud_e_welcome_jungle_stage2_mission5 = "Use o sinalizador na pista para chamar o helicóptero.",--Use the flare on the run way to call down the helicopter
	hud_e_welcome_jungle_stage2_mission11 = "Espere o helicóptero voltar.",--Wait for the helicopter to get back
	hud_e_welcome_jungle_stage2_mission9 = "Use o painel do lado de fora do Laboratório para a abrir a porta.",--Use the panel outside of the lab in order to open the lab door
	hud_e_welcome_jungle_stage2_mission10_hl = "Fuga está Disponível",--Escape is available
	hud_e_welcome_jungle_stage2_mission7_hl = "Espere pelos Resultados",--Wait for the results
	hud_e_welcome_jungle_stage2_mission4 = "Procure por pistas de qual motor está funcionando e roube-o",--Look for clues as to which engine is the working one and bag it up
	hud_e_welcome_jungle_stage2_mission8 = "Leve outro motor para o helicóptero para ver se é o certo.",--Bring another engine to the helicopter to see if it's the right one
	hud_e_welcome_jungle_stage2_mission10 = "Vá para o veículo de fuga.",--Get to the escape vehicle
	hud_e_welcome_jungle_stage2_mission3 = "Eles cortaram a energia, então você precisa religá-la.",--They cut the power so you need to get it back on
	hud_e_welcome_jungle_stage2_mission2_hl = "Derrube o Sistema de Segurança",--Override the security system
	hud_e_welcome_jungle_stage2_mission2 = "Hackeie o sistema de segurança para ganhar acesso ao Laboratório.",--Hack the security system in order to get access to Rossy's Lab
	hud_e_welcome_jungle_stage2_mission11_hl = "Espere pelo Helicóptero",--Wait for the helicopter
		})
end)