Hooks:Add("LocalizationManagerPostInit", "elefantedoidao", function(loc)
	LocalizationManager:add_localized_strings({
	-- Nomes e Descrições
	heist_framing_frame = "Framing Frame",--Framing Frame
	pln_framing_stage1_brief_01 = "O senador ama colecionar arte - Arte estrangeira, em particular. Para a nossa sorte, a Galeria de Arte Capitólio está recebendo uma exibição nessa semana.",--The senator loves to collect art - outsider art in particular. Lucky for us, the Capitol Art Gallery is hosting an exhibition this week.
	heist_framing_frame_1_briefing = "O senador ama colecionar arte - Arte estrangeira, em particular. Para a nossa sorte, a Galeria de Arte Capitólio está recebendo uma exibição nessa semana. Vocês precisam levar as pinturas para o apartamento do senador. Essas pinturas terão câmeras instaladas nelas. Tendo olhos lá dentro o trabalho será mais fácil, pode confiar.",--The senator loves to collect art - outsider art in particular. Lucky for us, the Capitol Art Gallery is hosting an exhibition this week. You need to take the marked paintings to the senator's apartment. They'll have cameras installed in them. Eyes on the inside will make your job easier, trust me.
	heist_framing_frame_2_hl = "Train Trade",--Train Trade
	heist_framing_frame_crimenet = "O Elefante está querendo incriminar um senador rival.$NL;$NL;» Roube as Artes da Galeria que o Senador deseja$NL;» Instale Câmeras nas Artes roubadas e faça um acordo$NL;» Infiltre-se no Apartamento do Senador e coloque a Cocaína no cofre dele",--The Elephant wants to frame a rival senator.$NL;$NL;» Steal art that the senator wants from the art gallery$NL;» Install cameras in the stolen art and make a deal$NL;» Infiltrate the senator's apartment and plant coke in his vault
	heist_framing_frame_2_briefing = "Certo, as câmeras estão instaladas nas pinturas. Estamos prontos. Os homens do senador são nervosos mas estão prontos para fazer o acordo conosco. Então vamos negociar. Grana por arte. Eu já marquei um local de encontro. Vocês vão se encontrar em um depósito de trem abandonado. Boa sorte.",--OK, the cameras are installed in the paintings. We're ready. The senator's men are jumpy but ready to deal with us. So let's deal. Money for art. I've set up the meeting location. You meet in an abandoned trainyard. Good luck.
	pln_framing_stage2_brief_01 = "Certo, as câmeras estão instaladas nas pinturas. Estamos prontos. Os homens do senador são nervosos mas estão prontos para fazer o acordo conosco. Então vamos negociar. Grana por arte.",--OK, the cameras are installed in the paintings. We're ready. The senator's men are jumpy but ready to deal with us. So let's deal. Money for art.
	heist_framing_frame_3_hl = "Framing",--Framing
	heist_framing_frame_1_hl = "Art Gallery",--Art Gallery
	pln_framing_stage3_brief_01 = "Esse é o apartamento do senador. Boa vizinhança, embora a segurança seja pesada. Ele já pendurou as pinturas, então nossas câmeras estão online e transmitindo.",--This is the senator's apartment. Nice neighborhood, high security though. He's already got the paintings hung, so our cameras are online and transmitting.
	heist_framing_frame_3_briefing = "Esse é o apartamento do senador. Boa vizinhança, embora a segurança seja pesada. Ele já pendurou as pinturas, então nossas câmeras estão online e transmitindo. Vocês podem acessá-las através da cobertura do prédio. Foi mal, mas nós não conseguimos nada melhor. Entrem no cofre escondido dele, peguem o ouro e deixem um pouco de cocaína para finalizar o trabalho de incriminação. No entanto, nós só podemos ter acesso ao cofre através de uma senha. Então encontrem alguns aparelhos dele e eu faço o resto. Boa sorte.",--This is the senator's apartment. Nice neighborhood, high security though. He's already got the paintings hung, so our cameras are online and transmitting. You can tap the feed from the roof of the building, sorry we couldn't do better. Get into his hidden vault, take the gold, and leave a little coke there to finish the frame job. We can only get access to the vault with a password though, so find me some of his gadgets and I'll do the rest. Good luck.

	-- Legendas (Dia 1 + Intro)
	pln_framing_stage1_intro_a_01 = "Vocês estão quase chegando na galeria. Infiltrem-se, evitem as câmeras, guardas e detectores de movimentos. A segurança está alta por causa de uma ameaça de bomba.",--You're almost at the gallery. Slip in, avoid cameras, guards, and motion detectors. Security's high because of a bomb threat.
	pln_framing_stage1_intro_a_02 = "Essa é a galeria. Vocês vão procurar por pinturas marcadas com um adesivo vermelho de venda. Nós precisamos de pelo menos quatro pinturas para fazer esse trabalho. O local está fechado e trancado. Encontrem uma forma de entrar. Bora.",--This is the gallery.  You're looking for the paintings marked by a red sold sticker. We need at least four to make this work. The place is closed and locked down. Find a way in. Go.
	pln_framing_stage1_intro_a_03 = "Beleza, a galeria está logo adiante. Cuidado com os detectores de movimentos, câmeras e guardas. Entrem lá e me tragam quatro pinturas marcadas com um adesivo vermelho de venda. O tempo está passando, galera.",--OK, gallery's just ahead. Watch out for motion detectors, cameras and guards. Get in there and bring me four of the paintings marked with a red sold sticker. Time is ticking guys.
	pln_framing_stage1_intro_a_04 = "Isso vai ser fácil desde que vocês evitem os sistemas de segurança e os guardas. Bem, talvez não tão fácil. Encontrem as pinturas marcadas como vendidas e peguem elas. Nós precisamos de pelo menos quatro delas.",--This is gonna be easy as long as you steer clear of the security systems and guards. Well maybe not so easy. Take the paintings with red sold stickers and clear out. We need four at least.
	pln_framing_stage1_intro_a_01b = "De qualquer forma, encontrem as pinturas marcadas como vendidas e peguem elas. Nós precisamos de pelo menos quatro.",--Anyway, find the paintings marked as sold and take them. We need at least four to be safe.
	pln_framing_stage1_brief_01b = "Vocês precisam levar as pinturas marcadas para o apartamento do senador. Elas terão câmeras instalada nelas. Olhos no interior facilitarão o trabalho de vocês, confie em mim.",--You need to take the marked paintings to the senator's apartment. They'll have cameras installed in them. Eyes on the inside will make your job easier, trust me.
	pln_framing_stage1_15_any_01 = "Os agentes da SWAT estão vindo com tudo. Se mexam.",--SWAT responders, coming in hard. Dig in.
	pln_framing_stage1_16_any_01 = "Eles simplesmente fizeram um buraco na parede! Segure-os!",--They just blew a hole in the wall! Hold them back!
	pln_framing_stage1_13_any_02 = "Beleza, beleza. Eu terminei de hackear a segurança, tudo está desbloqueado.",--OK, OK, I'm done with the security hack, everything's unlocked.
	pln_framing_stage1_end_a_01b = "Vou entrar em contato com os caras do senador e vou convencer eles de comprar as pinturas de nós.",--I'll get in touch with the senator's people and talk 'em into buying the paintings from us.
	pln_framing_stage1_17_any_01 = "Conectando... Isso pode levar alguns minutos.",--Connecting... This might take a minute.
	pln_framing_stage1_04_any_01 = "Escutem. Se vocês puderem me dar acesso ao computador na sala de vigilância, eu posso abri-lo.",--Listen up, if you can get me access to the computer in the surveillance room I'll get it open.
	pln_framing_stage1_08_any_01 = "Dêem uma olhada em volta. Tem que ter um jeito de acessá-lo. Nós estamos perdendo um tempo precioso.",--Have a look around - there has to be a way in, we're losing precious time.
	pln_framing_stage1_16_any_03 = "Eles estão quebrando a parede!",--They're breaching the wall!
	pln_framing_stage1_10_any_03 = "Já estamos na metade do processo com as pinturas. Só peguem o que falta e estará tudo certo.",--Halfway there with the painting collection. Now just get the rest and we're home free.
	pln_framing_stage1_03_any_01 = "Que merda! É o alarme!",--Damn it! That's the alarm!
	pln_framing_stage1_09_any_03 = "Beleza, isso é um começo. Nós só precisamos de mais três desse tipo. Peguem eles! Levem até a van que está no estacionamento, próximo à galeria em que estamos trabalhando.",--OK, that's a start, we need three more just like it. Get 'em! Take them to the van in the parking lot next to the gallery and we're in business.
	pln_framing_stage1_04_any_02 = "Certo, nós não podemos mais perder tempo. Só me dêem acesso ao computador na sala de vigilância, eu lido com isso remotamente.",--OK we can't screw around anymore. Just get me access to the computer in the surveillance room, I'll deal with it remotely.
	pln_framing_stage1_11_any_01 = "Fechou quatro. Nós já podemos vazar agora. Se quiserem pegar as pinturas que restam, ai é com vocês.",--Thats four, we're good to go now. If you want to get the rest of the paintings thats up to you.
	pln_framing_stage1_13_any_01 = "Fechou! Consegui hackear, tudo deve estar desbloqueado agora.",--Yes! Hack's done, everything should be unlocked now.
	pln_framing_stage1_07_any_01 = "Não podemos ficar comendo-bola aqui - entrem no prédio o mais rápido que vocês puderem. Tentem pela cobertura.",--Can't wait around out here - get into that building as fast as you can. Try the roof.
	pln_framing_stage1_end_b_02b = "Então só nos falta pegar o ouro.",--Then we just need to go in to get the gold.
	pln_framing_stage1_15_any_03 = "A SWAT está em cena... Ai vamos nós.",--SWATs on the scene... Here we go.
	pln_framing_stage1_16_any_04 = "Eles estão explodindo a parede!",--They're blowing the wall!
	pln_framing_stage1_02_any_04 = "Bom trabalho, pessoal. Agora o que vocês precisam procurar são por pinturas com andesivos vermelhos. São esses que o democrata quer. Peguem pelo menos quatro.",--Nice work, folks. Now what you're looking for are paintings with red stickers. Those are the ones the democrat wants. Get at least four. 
	pln_framing_stage1_end_b_01 = "Excelente trabalho. Com esses quadros dentro do apartamento do senador, nós teremos bastante apoio. Tipo um Cavalo de Tróia, só que em maior número.",--Excellent work. With these paintings in place in the senator's apartment, we'll have plenty of coverage. Like a Trojan Horse, but lots of them.
	pln_framing_stage1_02_any_02 = "Beleza... Certo, nós precisamos de pelo menos quatro pinturas. Lembrem-se, aquelas com o adesivo vermelho.",--Alright... OK, we need at least four paintings, remember, the ones with red stickers.
	pln_framing_stage1_01_any_01 = "Beleza, galera. Entrem e encontrem os quadros. Nós queremos as pinturas que possuem um adesivo vermelho. Cuidado com as câmeras e os guardas.",--OK guys, get inside and locate the art. We want the paintings with the red stickers on. Look out for guards and cameras.
	pln_framing_stage1_10_any_01 = "Já foi a metade, precisamos de mais 2.",--That's half, we need 2 more.
	pln_framing_stage1_12_any_01 = "Bum! São as portas. Eu ainda estou trabalhando nas pinturas.",--Bam, that's the doors, I'm still working on the paintings.
	pln_framing_stage1_04_any_03 = "Nós ainda não temos pinturas suficientes! Alguém consegue me dar acesso ao computador da sala de vigilância de maneira rápida? Eu vou abrir isso, não se preocupem com a suas lindas cabecinhas.",--We don't have enough paintings yet! Can someone get me access to the computer in the surveillance room, fast? I'll get it open, don't you worry about your pretty little heads.
	pln_framing_stage1_10_any_02 = "Essa é a metade das pinturas necessárias, vocês precisam pegar o que falta antes de nós vazarmos.",--That's half the required paintings, you need to get the rest before we can roll out.
	pln_framing_stage1_02_any_03 = "Ok, vocês estão dentro, boa. Agora vocês precisam de pelo menos quatro pinturas. Aquelas com adesivos vermelho - essas são os que nosso amante da arte pretende comprar.",--OK you're in, good. Now you need at least four paintings, the good ones have red stickers - those are the ones our art lover intends to buy.
	pln_framing_stage1_06_any_02 = "Tudo está trancado - Se vocês querem que eu arrume isso, então eu vou precisar acessar a sala de vigilância.",--Everything's locked down - if you want me to fix it then I need to get into the surveillance room.
	pln_framing_stage1_05_any_02 = "Beleza, galera. Vocês já possuem o suficiente para darem o fora. Se quiserem pegar mais, então eu vou precisar acessar a sala de vigilância. Eu me viro se conseguirem entrar lá.",--OK crew, you have enough to get the hell out now. If you want more then I need access to the surveillance room. I'll do the rest once you get in.
	pln_framing_stage1_end_b_01b = "Eu vou marcar a negocioação com os caras do senador e dar sequência.",--I'll set up the trade with the senator's people and get us rolling.
	pln_framing_stage1_05_any_01 = "Beleza, já é o suficiente para vocês vazarem, se quiserem. Mas se nós quisermos mais - me dêem acesso à sala de vigilância e então eu posso invadir a rede deles.",--Alright, that's enough to go now if you want, but if we want more - get me access to the surveillance room so I can see what's on their network.
	pln_framing_stage1_02_any_01 = "Beleza, vocês estão dentro. Encontrem as pinturas com adesivos vermelhos nelas, nós queremos pelos menos quatro.",--OK, you're inside. Find the paintings with the red stickers on them, we want at least four.
	pln_framing_stage1_09_any_01 = "Ótimo! Precisamos de pelo menos mais 3. Levem elas até a van. Ela está no estacionamento ao lado da galeria.",--Great, we need at least 3 more, get it to the van. It's in the parking lot next to the gallery.
	pln_framing_stage1_01_any_02 = "Beleza, esse é o plano: Nós estamos procurando por pinturas com um adesivo vermelho nelas. A segurança estará pesada, com câmeras e guardas.",--OK, here's the setup: we're looking for the paintings with red stickers on them. Security is going to be on the heavy side, cameras and guards. 
	pln_framing_stage1_01_any_03 = "Estão preparados? Beleza, escutem: Vocês estão procurando por pinturas marcadas com adesivos vermelhos. Eles possuem uma segurança excepcionalmente foda aqui. Muitas câmeras e até uma sala de segurança, então façam bem feito.",--Ready for the shot? OK listen: you are looking for the paintings marked with red stickers. They've got unusually tight security here. A lot of cameras, even a security room, so do your homework.
	pln_framing_stage1_06_any_01 = "Puta merda! Se vocês querem tudo aberto novamente, vocês vão precisar ir até a sala de vigilância.",--Dammit! If you want everything open again, you're going to need to get into the surveillance room.
	pln_framing_stage1_06_any_03 = "Nós estamos presos... Se querem que eu abra isso para vocês, então vão precisar acessar a sala de vigilância rápido.",--We're locked down... if you want me to open it up you need to get the surveilance room open fast.
	pln_framing_stage1_07_any_02 = "Não temos tempo para ficar esperando - Não conseguem encontrar uma forma de entrar? Que tal a cobertura?",--We don't have the time to wait around - can't you find a way in? What about the roof?
	pln_framing_stage1_08_any_02 = "Vocês já checaram se há alguma opção através dos prédios vizinhos? Tem que ter algum acesso ao interior lá por cima.",--Have you checked any of the vertical options? There's got to be access to the interior up there.
	pln_framing_stage1_08_any_03 = "Chequem a cobertura - encontrem uma forma de entrar.",--Check the roof - find your route inside. Get creative, we don't have time.
	pln_framing_stage1_09_any_02 = "Show, agora precisamos de pelo menos mais 3 como esse e levá-los para a van. Ela está no estacionamento próximo à galeria.",--Good, now we need at least 3 more just like this and you need to get them to the van. It's in the parking lot next to the gallery.
	pln_framing_stage1_11_any_02 = "Temos quatro pinturas agora e quatro é o que precisamos - mas se quiserem pegar mais, é com vocês.",--We have four now and four's what we need - now if you want to get more, your move.
	pln_framing_stage1_12_any_02 = "Ai está, como uma roupa de gala. Ainda estou trabalhando nas pinturas.",--There we go, off like a prom dress, I'm still working on the paintings.
	pln_framing_stage1_14_any_01 = "Beleza. Com esse cara fora de cena, adeus câmeras.",--Good, with that guy out of the picture, no more cameras.
	pln_framing_stage1_14_any_02 = "Ótimo, o alarme da câmera tocou.",--Great, so much for the camera alarm.
	pln_framing_stage1_15_any_02 = "Unidades da SWAT estão se movendo para dentro do local, se preparem.",--SWAT units are moving into the building, get ready!
	pln_framing_stage1_16_any_02 = "A SWAT simplesmente explodiu a parede!",--SWATs just breached the wall! 
	pln_framing_stage1_end_a_01 = "Bem vindo de volta, galera. Agora nós instalamos as câmeras nas pinturas, negociamos elas com os caras do senador e veremos quem são esses traficantes.",--Welcome back, crew.  Now we install the cameras in the pictures, trade them to the senator's guys and get a look on whoever this arms dealer is.
	pln_framing_stage1_end_a_02 = "Bom trabalho, time. Com as microcâmeras instaladas nas pinturas, nós só precisamos negociá-las com os caras do senador. Eu vou marcar o encontro agora mesmo.",--Good work, team. With micro cameras installed in the paintings, we just need to trade them to the senator's people. I'll set up the meet right now.
	pln_framing_stage1_end_b_02 = "Vocês limparam o local. Agora teremos informações completas do apartamento do senador. Vou garantir que tenhamos as câmeras instaladas nas pinturas e já marcamos a negociação.",--You cleaned the joint out. Now we'll have perfect coverage in the senator's apartment. I'll ensure we get the surveillance equipment in the paintings and set up the trade.
	
	-- Legendas (Dia 2 + Intro)
	pln_framing_stage2_intro_a_01 = "Beleza, esse é o lugar. Vão para o vagão e procurem pelo contato de vocês. Eles disseram que encontrariam vocês lá. Até agora tudo está tranquilo. Apenas troquem as pinturas e vazem de lá. Vamos nessa.",--Right, this is the place. Get to the traincar and look for your contact. They said they'd meet you there. So far it all looks good. Just trade the paintings and get out fast. Keep it rolling.
	pln_framing_stage2_brief_02 = "Ok, vocês estão em posição no pátio de trem. Fiquem espertos. Fiquem de olho em qualquer ação. Eu não consigo ver nenhuma atividade de veículos por perto, mas isso não quer dizer nada. Vão até o vagão e esperem pelo contato.",--OK, you're  in position at the trainyard. Eyes open. Watch for suits. I can't see any active vehicles nearby but that doesn't mean much. Go to the train car and wait for contact.
	pln_framing_stage2_17_any_02 = "Porra! Alguém tem um Bloqueador de ECM?! Essa é a única coisa que vai arrombar essa porta. Caso contrário, vocês precisam de outra rota. ",--Dammit does anyone have an ECM jammer - that's about the only thing that'll crack that door. Othewise you need another route.
	pln_framing_stage2_12_any_02 = "Isso definitivamente facilitará nossas vidas quando entrarmos no prédio do democrata.",--This is definitely going to make our lives easier when we go in to hit the Democrat's place.
	pln_framing_stage2_09_any_01 = "Beleza. Agora se lembrem, Uma bolsa de dinheiro para cada pintura.",--OK now remember, one bag of cash for every painting. 
	pln_framing_stage2_16_any_01 = "Essas são as portas... Eles bloquearam as portas! Tem que ter outra saída!",--That's the doors, they blocked off the doors! There's gotta be another way out!
	pln_framing_stage2_10_any_02 = "Terminamos aqui. Tem uma van esperando no outro lado do galpão. Sigam em frente, carreguem o carro e pronto.",--We're done here, there's a van waiting on the other side of the building. Go on through, load the car up, and we're done.
	pln_framing_stage2_05_any_01 = "Isso é tudo. Esperem a ligação deles.",--That's everything, wait for their call.
	pln_framing_stage2_18_any_01 = "Esses túneis levarão vocês até o depósito.",--Those tunnels will lead you into the warehouse.
	pln_framing_stage2_03_any_01 = "Eles são um tanto impacientes - só coloquem as pinturas na mesa e fiquem de olho para qualquer coisa suspeita.",--They're pretty antsy - just get the paintings on the table and keep both eyes open for anything weird.
	pln_framing_stage2_brief_01b = "Eu marquei o local de encontro. Vocês vão se encontrar em um depósito de trem abandonado. Boa sorte.",--I've set up the meeting location. You meet in an abandoned trainyard. Good luck.
	pln_framing_stage2_19_any_01 = "Seus safados! Vocês contornaram eles usando esses túneis!",--You clever bastards, you'll get around them using those tunnels.
	pln_framing_stage2_01_any_03 = "O telefone está tocando. Hora de atender e iniciar a negociação.",--Phone's ringing, time to pick it up and start this trade off.
	pln_framing_stage2_09_any_02 = "Agora nós esperamos. Lembrem-se, pegamos uma bolsa com dinheiro para cada pintura que jogarmos para o helicóptero. Tudo o que precisamos fazer é sermos pacientes e sortudos.",--Now we wait. Remember we get a bag of cash for every painting we throw into the chopper. All we need to do is be patient and lucky. 
	pln_framing_stage2_17_any_01 = "Somente um Bloqueador de ECM vai abrir essa porta... Caso contrário, vocês precisarão encontrar outra rota.",--Only an ECM jammer's going to get that door open...Otherwise you need another way around.
	pln_framing_stage2_end_a_01 = "Os caras do senador acabaram de me dizer que receberam as pinturas. Eles estão felizes com a negociação. Agora eles estão exatamente onde queremos, graças ao bom trabalho de vocês. Espero que vocês também recebam parte dessa grana.",--The senator's man just told me they got the paintings. They're thrilled with the trade. Now they're right where we want 'em, thanks to your good work. Hopefully you got some of that money too.
	pln_framing_stage2_brief_02b = "Certifiquem-se de pegar as pinturas.",--Make sure we get the paintings.
	pln_framing_stage2_06_any_02 = "Bingo. Peguem tudo isso.",--Bingo. Pick it up.
	pln_framing_stage2_brief_01 = "Beleza. As câmeras estão instaladas nas pinturas. Nós estamos no gatilho. Os caras do senador são nervosos mas estão prontos para negociar com a gente. Então vamos negociar. Grana por arte.",--OK, the cameras are installed in the paintings. We're ready. The senator's men are jumpy but ready to deal with us. So let's deal. Money for art.
	pln_framing_stage2_19_any_02 = "Vocês são muito espertos em usarem os tunéis dessa forma - muito profissional.",--Very smart to use the tunnels like that - very professional.
	pln_framing_stage2_20_any_02 = "Por questão de segurança, mantenham-se discretos próximos dos trabalhadores.",--Keep a low profile near the workers to be safe.
	pln_framing_stage2_end_a_02 = "Bem, vocês não receberam nada do dinheiro. Mas a parte importante foi feita. As pinturas foram entregues e o senador pode contemplar elas em paz... Por enquanto.",--Well you didn't get any of the money but the important part is done. The art was delivered and the senator can look at his paintings in peace... For a little while. 
	pln_framing_stage2_10_any_01 = "Certo, boa. Agora tem uma van esperando por vocês no outro lado do galpão. Vão até lá, carreguem o carro e acabamos o serviço por hoje.",--OK good, now there is a van waiting for you on the other side of that building. Go through, load up the car, and we're done for the day.
	pln_framing_stage2_13_any_03 = "Peguem o dinheiro e vazem o mais rápido possível.",--Get the money and clear out ASAP!
	pln_framing_stage2_18_any_03 = "Boa jogada... Isso nos leva ao depósito.",--Good move.. that's bound to lead to the warehouse.
	pln_framing_stage2_01_any_01 = "Beleza, galera. Atendam o telefone. E bora agilizar essa negociação.",--OK people, get the phone. Let's get this trade out of the way.
	pln_framing_stage2_07_any_02 = "Todos vocês entrem no trem.",--Get everyone into the train.
	pln_framing_stage2_01_any_02 = "Vão até o telefone, ele está tocando. Façam o contato.",--Head over to the phone, the phone's ringing. Make the contact there.
	pln_framing_stage2_13_any_02 = "Puta merda! Emboscada da SWAT. Eu não tinha visto isso!",--Dammit! SWAT ambush. I didn't see it!
	pln_framing_stage2_02_any_01 = "Alguém atenda o telefone...",--Someone pick up the phone...
	pln_framing_stage2_02_any_02 = "Alguém vai pegar isso? Não se pode iniciar negociação até que um de vocês faça isso...",--Is someone going to get that? Can't start the trade until you do..
	pln_framing_stage2_03_any_02 = "Eu não estou gostando disso... Vamos acabar com isso depressa, coloquem as pinturas na mesa.",--I don't like it... Let's get this over with as soon as we can, get the paintings on the table. 
	pln_framing_stage2_03_any_03 = "Isso é meio suspeito, eu não sei - coloquem as pinturas na mesa e mantenham seus sensores aranha ligados.",--This seems fishy but I don't know - get the paintings on the table and keep your spider sense tingling.
	pln_framing_stage2_05_any_02 = "Beleza. Agora vamos esperar que eles façam a ligação logo.",--OK, now let's just hope they call you fast.
	pln_framing_stage2_05_any_03 = "Show. Eles só precisam retornar a ligação. Quanto mais rápido melhor.",--Alright, they just need to call you back. Faster the better.
	pln_framing_stage2_06_any_01 = "Ai está, atendam o telefone.",--There it is, get the phone.
	pln_framing_stage2_06_any_03 = "Beleza, são eles ligando.",--OK, that's them calling.
	pln_framing_stage2_07_any_01 = "Beleza, pessoal. Todo mundo pra dentro do trem.",--OK folks, everyone into the train.
	pln_framing_stage2_12_any_01 = "Boa, boa. Isso fará nossas vidas mais fáceis quando formos lidar com o tal Democrata.",--Good, good. This'll make our lives easier when we hit the Democrat...
	pln_framing_stage2_13_any_01 = "SWAT! Eu sabia que isso estava fácil demais!",--SWAT! I knew it was too easy!
	pln_framing_stage2_18_any_02 = "Eu acho que esses túneis nos levarão até o galpão, pessoal.",--I think those tunnels will get you into the warehouse folks.
	pln_framing_stage2_19_any_03 = "Que puta jogada usar os túneis - eles ficarão perdidos.",--Hell of a good move to use the tunnels - they'll be off-balance.
	pln_framing_stage2_20_any_01 = "Não deixem os trabalhadores verem vocês ou eles podem ferrar com todo o lance.",--Don't let the workers see you or they might blow the whole deal.
	pln_framing_stage2_20_any_03 = "A menos que vocês ainda queiram que a polícia apareça, é melhor ter cuidado com esses trabalhadores.",--Unless you still want the cops to show up you better be careful around those workers
	pln_framing_stage2_20_any_04 = "Hey. Eles podem ser só trabalhadores, mas não são burros e cegos - mantenham-se discretos.",--Hey they might be workers but they're not dumb and blind - keep your profile low.
	pln_framing_stage2_end_a_01b = "Vamos garantir de pegar o nosso ouro - É o nosso dia de pagamento também.",--Lets make sure we get our gold - it's our payday too.
	pln_framing_stage2_end_a_02b = "Agora é a nossa vez de terminar o trabalho e tomar o lugar dele. Vejo vocês na Safe House.",--Now it's our turn to finish the job and take his place down. See you at the safe house.
	pln_framing_stage2_end_b_01 = "Então os caras do senador estão muito gratos? O chefe está pendurando o quadro? O cara não tem ideia de que vamos limpá-lo. Bem, bom trabalho pegando o dinheiro pelo caminho.",--So the senator's people are very appreciative. The boss is hanging the art. Guy has no clue we're going to clean him out. Oh well. Nice work grabbing the money by the way.
	pln_framing_stage2_end_b_01b = "Vou ficar com isso no dia do pagamento - que, além do ouro do apartamento do senador, deve encher o cofre de vocês muito bem. Ótimo trabalho.",--I'll keep this for the payday - that plus the gold from the senator's apartment should load your safe house vault nicely. Great work.
	dlr_framing_stage2_17_any_01 = "Isso é tudo! Muito bom fazer negócios com vocês, senhores!",--Thats everything, nice doing business with you gentlemen!
	dlr_framing_stage2_11_any_01 = "Não se preocupem. É só por segurança.",--Don't worry, it's just for safety.
	dlr_framing_stage2_02_any_01 = "Comecem colocando todas as pinturas em cima da mesa do vagão. Entrarei em contato com vocês quando terminarem.",--Start with putting all the paintings on the table in the train car. I'll contact you when you are done.
	dlr_framing_stage2_05_any_01 = "Eu posso ver sete pinturas",--I can see seven paintings.
	dlr_framing_stage2_04_any_01 = "Nós contamos oito pinturas. Bom trabalho.",--We count eight paintings. Good job.
	dlr_framing_stage2_12_any_01 = "Certo, nosso negociante está chegando. Só um momento.",--Alright, our dealer is arriving, hold on for a second.
	dlr_framing_stage2_07_any_01 = "Ok. Eu contei 5 pinturas.",--OK, I count 5 paintings. 
	dlr_framing_stage2_06_any_01 = "Então são 6 pinturas.",--So that's 6 paintings.
	dlr_framing_stage2_18_any_01 = "As portas estão abertas para vocês! Nós estamos indo embora!",--Doors are open for you, we are leaving!
	dlr_framing_stage2_15_any_01 = "Valeu! Ai vai o dinheiro!",--Thanks, here's the cash!
	dlr_framing_stage2_09_any_01 = "Certo. Então ouçam - nosso cliente é um pouco nervoso. Ele não faz coisas que o envolvam, sabe? Infringir leis de outras formas e tals. Então, precisamos que todos vocês entrem no trem.",--OK. So listen - our client is a little jumpy. He doesn't do things involving, you know, lawbreaking otherwise. So we need to have all of you in the train.
	dlr_framing_stage2_08_any_01 = "4 pinturas. Não são muitas mas nós ficaremos com elas.",--4 paintings, not much, but we'll take it.
	dlr_framing_stage2_16_any_01 = "Ótimo! Nós pegamos!",--Great, we got it!
	dlr_framing_stage2_10_any_01 = "Não é que não confiamos em vocês. Nós só precisamos garantir que nada demais irá acontecer.",--It's not that we don't trust you, we just need to make sure that nothing will happen.
	dlr_framing_stage2_03_any_01 = "Então vocês pegaram 9 pinturas?! Isso é incrível!",--So you got nine of the paintings? That's awesome.
	dlr_framing_stage2_19_any_01 = "Puta merda! Os policias! Vamos vazar daqui!",--Oh shit, it's the cops! Let's get out of here! 
	dlr_framing_stage2_01_any_01 = "Olá, senhores. Nosso cliente está muito satisfeito que vocês tenham concordado em fazer esse negócio conosco. Mas saibam disso - a única maneira pela qual isso será feito é se fizermos do nosso jeito. ",--Hello gentlemen. Our client is very pleased that you agreed to do this with us. But know this - the only way this is going through is if we do it our way.
	dlr_framing_stage2_14_any_01 = "Ótimo! Dinheiro descendo!",--Great, money coming down.
	dlr_framing_stage2_13_any_01 = "Ok! Joguem as pinturas para mim e vocês terão o dinheiro de vocês.",--OK, throw me the paintings, and you'll get your money!
	
	-- Legendas (Dia 3 + Intro)
	pln_framing_stage3_intro_01b = "Vão até o telhado com os aparelhos e Boom! Nós somos preciosos - literalmente.",--Get to the roof with the gadgets and bang, we're gold - literally.
	pln_framing_stage3_intro_01 = "Este lugar está cheio de guardas. Vocês precisam pegar qualquer coisa tecnológica dele que não seja fixo - telefones celulares, laptops, HDs. Entrem e encontrem o cofre.",--This place is crawling with guards. You need to grab anything technological of his that isn't nailed down - mobile phones, laptops, hard drives. Slip in and find the vault.
	pln_framing_stage3_04_any_01 = "Eu espero que vocês tenham muitas câmeras. Isso facilitará a localização de todos os dispositivos.",--I hope you got a lot of cameras. It'll make it easier for us to find all the devices.
	pln_framing_stage3_14_any_01 = "Ótimo! Agora levem eles até a estação no telhado e conecte-os.",--Great! Now get them up to the station on the roof and connect them.
	pln_framing_stage3_brief_02 = "Beleza. O equipamento de digitalização já estão em posição no telhado. Entrem, peguem o telefone celular, laptop, HDs e o tablet dele. Qualquer coisa técnica. Então levem para o telhado.",--Alright. Scanning equipment is in position on the rooftop. Sneak in, take his mobile phone, laptop, hard drives, and tablet pc. Anything technical. Then bring it to the roof.
	pln_framing_stage3_51_any_01 = "Ok. Nós estamos quase terminando.",--OK, we're almost done!
	pln_framing_stage3_35_any_01 = "Ótimo. Essa é a sala do servidor. Liguem o computador, precisamos fazer o upload de todos os arquivos.",--Great, that's the server room, start the computer in there, we need to upload all the files.
	pln_framing_stage3_50_any_01 = "Em breve estaremos inundados de helicópteros de notícias. E sobre nosso helicóptero de fuga? Bem, ele está no meio deles.",--Pretty soon we're going to be swamped with news choppers. Our escape chopper? Blend right in.
	pln_framing_stage3_48_any_02 = "Beleza. Para tornar as coisas um pouco mais interessantes, estou enviando essas imagens ao vivo para todos os grandes meios de comunicação enquanto fazemos o upload. Um monte cobertura televisiva.",--OK, to make things a little more interesting I'm sending this feed live to all the big media outlets while we upload. Lots of coverage.
	pln_framing_stage3_46_any_03 = "Vocês não podem deixar eles desligarem a energia. Isso tornará tudo mais lento.",--You can't let them kill the power, it'll slow everything down!
	pln_framing_stage3_39_any_01 = "Certifiquem-se de manter a energia ligada.",--Make sure you keep the power up.
	pln_framing_stage3_26_any_01 = "Bom trabalho. Bora nessa.",--Good job, we are gone.
	pln_framing_stage3_51_any_06 = "Está upando... está quase lá.",--It's uploading... It's almost there.
	pln_framing_stage3_09_any_01 = "Esse é um dos HDs externos.",--That's one of the external hard drives.
	pln_framing_stage3_01_any_01 = "Então, o plano é o seguinte. Entrem lá, consigam para mim esses objetos. E quando vocês tiverem eles, vamos conectar à nossa estação na cobertura.",--So the plan is, go in, get me the following objects. When you have them we'll connect them to our station on the roof.
	pln_framing_stage3_50_any_03 = "Bain tem um pequeno plano - acho que todos esses helicópteros da mídia são uma cortina de fumaça conveniente para o nosso helicóptero de fuga, não acham?",--Bain's got a little plan - I think all those media choppers are a convenient smokescreen for our escape chopper, don't you?
	pln_framing_stage3_51_any_02 = "Está chegando lá!",--It's getting there!
	pln_framing_stage3_47_any_02 = "Mantenham eles longe do disjuntor, estão me ouvindo?",--Keep them the hell away from the circuit breaker, you hear me?
	pln_framing_stage3_19_any_01 = "Ok, beleza. Vocês podem abrir o cofre agora. Também ativei a imagem da câmera do cofre.",--Good, OK, you can open the vault now. I have turned on the vault's camera feed as well.
	pln_framing_stage3_48_any_01 = "Então, eu vou enviar essa imagem ao vivo para todos os meios de comunicação enquanto vocês fazem o upload. Eles vão se esbaldar nisso.",--So I'm going to send this feed live to all the media outlets as you're uploading. They're gonna eat this up.
	pln_framing_stage3_20_any_01 = "Só tem um probleminha... Eu não sei onde o cofre está, fisicamente falando.",--There's just a little problem... I don't actually know where the vault is, physically.
	pln_framing_stage3_15_any_01 = "Conectem os dispositivos na estação que está na cobertura.",--Connect the devices to the station on the roof.
	pln_framing_stage3_24_any_01 = "Levem a cocaína até o cofre e armazenem ela na sala de pré-cofre.",--Carry the coke down to the vault and plant it outside in the pre vault room.
	pln_framing_stage3_43_any_01 = "Beleza. Todos os arquivos foram upados. Isso deve funcionar.",--Alright, the files are all uploaded, it should do the trick.
	pln_framing_stage3_12_any_01 = "Mais dois, continuem procurando.",--Two more, keep on searching.
	pln_framing_stage3_02_any_01 = "Precisamos do telefone, tablet, laptop e dois HDs externos.",--We need his phone, his tablet, his laptop and two external hard drives.
	pln_framing_stage3_33_any_01 = "Encontrem a sala do servidor dele e entrem lá.",--Find his server room and get in there.
	pln_framing_stage3_34_any_01 = "Vejam se conseguem encontrar os cartões de acesso para entrar lá. Caso contrário, teremos que perfurar as portas.",--See if you can find the keycards to  get in there, otherwise we have to drill the doors.
	pln_framing_stage3_52_any_01 = "Levem o ouro até a cobertura. Coloquem as bolsas na tirolesa. Estamos levando elas para casa!",--Get that gold up to the roof, put it in the bag on the zip line, we are bringing it home!
	pln_framing_stage3_51_any_07 = "Meu Deus... isso é lag?! Vai logo! Porquê eles não têm fibra do Google?! Maldita banda larga americana.",--Christ... Is it buffering? Go faster! Why don't they have Google fiber... Goddam American broadband.
	pln_framing_stage3_18_any_01 = "Está localizado no escritório dele.",--It's located in his office.
	pln_framing_stage3_03_any_01 = "Vocês podem acessar as câmeras escondidas nas pinturas através do laptop na cobertura.",--You can access the hidden cameras in the paintings with the laptop on the roof.
	pln_framing_stage3_53_any_02 = "Quando vocês estiverem prontos, vão até a cobertura e nós tiraremos vocês daí pela tirolesa.",--When you're ready, get to the roof and we'll get you clear with the zipline.
	pln_framing_stage3_42_any_01 = "Procure por um disjuntor para ligar a energia de volta.",--Look for a circuit breaker to get the power back up.
	pln_framing_stage3_46_any_02 = "Mantenham a polícia afastada dos disjuntores se querem fazer isso!",--Keep the cops off the circuit breakers if you want to make it!
	pln_framing_stage3_36_any_01 = "Isso levará algum tempo, uma renca de dados para upar em uma rede pequena.",--It'll take some time, lots of data to up and a small pipe.
	pln_framing_stage3_13_any_01 = "Isso é tudo.",--Thats all of them.
	pln_framing_stage3_51_any_05 = "Vamos finalizar isso logo-logo... eu espero.",--We're going to be done soon - I hope.
	pln_framing_stage3_brief_01b = "Vocês podem acessar as imagens na cobertura do prédio. Foi mal por não conseguirmos algo melhor. Entrem no cofre escondido, peguem o ouro e deixem um pouco de cocaína lá para finalizar o trabalho.",--You can tap the feed from the roof of the building, sorry we couldn't do better. Get into his hidden vault, take the gold, and leave a little coke there to finish the frame job.
	pln_framing_stage3_51_any_03 = "Quase lá! Quase lá, quase lá!!",--Almost! Almost, almost...
	pln_framing_stage3_16_any_01 = "Certo. Agora eu tenho acesso. Segura aí...",--Alright now, I have access, hold on a sec...
	pln_framing_stage3_44_any_01 = "Nosso helicóptero está chegando. Ele vai se misturar com todos os helicópteros dos noticiários.",--Our chopper is coming in, he'll blend in with all the news choppers.
	pln_framing_stage3_06_any_01 = "Esse é o telefone dele, Boa.",--That's his phone. Good.
	pln_framing_stage3_22_any_01 = "Procurem por estantes de livros. Vejam se vocês podem movimentar elas e encontar alguma coisa.",--Look for bookshelves, see if you can move them and find something.
	pln_framing_stage3_41_any_01 = "Liguem a energia de volta!",--Get the power back up!
	pln_framing_stage3_21_any_01 = "Então isso significa que vocês precisam encontrá-lo. As referências parecem indicar que o cofre está... Conectado a uma estante de livros. Eu sei, deixe o político ser clichê mesmo.",--So this means you have to find it. References seem to indicate it's... Connected to a bookshelf. I know, leave it to a politician to be cliche.
	pln_framing_stage3_08_any_01 = "Esse é o HD externo. Boa.",--That's the external hard drive. Nice. 
	pln_framing_stage3_30_any_01 = "Usem o computador dele de volta. Cuidado. Eles só vão desativar por um curto período de tempo.",--Use his computer again, be careful, they only go down for a small amount of time.
	pln_framing_stage3_05_any_01 = "Ótimo. Vocês encontraram o laptop.",--Great, you found the laptop.
	pln_framing_stage3_07_any_01 = "Esse é o tablet. Perfeito.",--That's the tablet PC. Perfect.
	pln_framing_stage3_10_any_01 = "Esse é o segundo HD externo.",--That's the second external hard drive.
	pln_framing_stage3_11_any_01 = "Só mais um. Continuem procurando.",--One more, keep looking.
	pln_framing_stage3_17_any_01 = "Beleza! Nós somos preciosos. Eu acho que peguei tudo o que nós precisávamos. Vocês devem conseguir acessar o computador dele agora.",--OK! We're gold. I think I got everything we need. You should be able to access his desktop computer now.
	pln_framing_stage3_23_any_01 = "Ai está. Agora vamos incriminar esse cara. Subam até a cobertura e nosso colega vai jogar pra vocês a cocaína.",--There you go.  Now let's frame this guy, get up to the roof, and our guy will throw you the coke.
	pln_framing_stage3_25_any_01 = "É isso aí, bom trabalho. A fuga está pronta para vocês. A menos que vocês queiram ficar por ai e limpar o cofre. De qualquer forma, o veículo está à espera.",--That's it, fine work. The escape is ready for you. Unless you want to stick around and clean out the vault. Either way the vehicle's waiting.
	pln_framing_stage3_27_any_01 = "Se vocês quiserem pegar mais, usem o PC de mesa. Ele deve abrir o cofre para vocês.",--If you want to go for more, use his desktop PC, it should open the vault up for you.
	pln_framing_stage3_28_any_01 = "Certo, o cofre está exposto. Mas cuidado com os lasers, eles se conectam diretamente ao alarme",--Alright, vault is popped, but watch out for those lasers, they connect directly to the alarm
	pln_framing_stage3_29_any_01 = "Desativamos os lasers.",--We have to shut them off.
	pln_framing_stage3_31_any_01 = "Usem a câmera para ver quando os lasers reativarem e então podem desativá-los novamente.",--Use the camera to see when they turn on, and then turn them off again.
	pln_framing_stage3_32_any_01 = "É a porra do alarme! Hora de mudarmos para o plano B, pessoal.",--That's the damn alarm! Time to shift to plan B, folks. 
	pln_framing_stage3_37_any_01 = "Agora espero que eles não notem nada. Porque nós somos sortudos.",--Now hopefully they won't notice anything. Because we're just that lucky.
	pln_framing_stage3_40_any_01 = "Eles cortaram a energia! Liguem de volta!",--They cut the power! Get it back up!
	pln_framing_stage3_45_any_01 = "Vão para o helicóptero para escaparem!",--Get to the chopper to escape!
	pln_framing_stage3_46_any_01 = "Eles vão tentar desligar a energia! Impeça eles!",--They're gonna try to kill the power! Don't let them!
	pln_framing_stage3_47_any_01 = "O que quer que vocês façam, não deixem esses filhos da puta cortarem a energia!",--Whatever you do don't let the sons of bitches cut the power!
	pln_framing_stage3_50_any_02 = "Quando toda essa mídia aparecer em seus helicópteros, ninguém vai ligar para a nosso pássaro de fuga.",--When all that media shows up in their choppers, no one's gonna look sideways at our escape bird. 
	pln_framing_stage3_51_any_04 = "Esse upload não está indo rápido o bastante, droga!",--This upload isn't going fast enough, dammit!
	pln_framing_stage3_52_any_02 = "Agilizem com esse ouro até a cobertura. Coloquem as bolsas na tirolesa. Vamos levá-los.",--Hustle that gold onto the roof, get it into the bag on the zipline, we're taking it. 
	pln_framing_stage3_53_any_01 = "Assim que estiverem prontos, eu quero vocês na cobertura. Então vamos tirá-los de lá através da tirolesa.",--Whenever you're ready, I want you on the roof, then we'll get you outta there with the zipline.
	pln_framing_stage3_brief_01c = "No entanto, só podemos ter acesso ao cofre com uma senha. Então encontrem alguns dos aparelhos dele e eu farei o resto. Boa sorte.",--We can only get access to the vault with a password though, so find me some of his gadgets and I'll do the rest. Good luck.
	pln_framing_stage3_brief_02b = "Procurem bem e fiquem de olho nos guardas.",--Search well and eyes peeled for guards. 
	pln_framing_stage3_end_a_01 = "Drogas implantadas, senador incriminado. Bandidos 1, Políticos 0. Bem feito, operação muito tranquila. O Elefante vai adorar esse resultado.",--Drugs planted, senator framed. Bad guys 1, Politicians 0. Well done, very smooth operation in there. The Elephant will love this outcome.
	pln_framing_stage3_end_b_01 = "Bem, não conseguimos o ouro mas ainda seremos compensados ​​pelo trabalho bem sucedido na incriminação que realizamos. Muito bem, pessoal.",--Well, we didn't get the gold, but we'll still be compensated for the successful frame job we pulled. Well done, people.
	pln_framing_stage3_end_c_01 = "Vocês sempre podem contar com a imprensa para se envolver em escândalos em Washington. O tráfico de armas é o assunto da cidade. O Elefante e sua turma estão muito satisfeitos. Que sufoco de plano B, hein pessoal.",--You can always rely on the press to swarm on scandal in DC. The weapons deal is the talk of the town. The Elephant and his party are very pleased. Hell of a plan B, folks.
	pln_ff3_15_any_01 = "Sim, esse é o epicentro - bem aí. Eu imagino que tipo de tesouro essa casa pode esconder. OK, foco no golpe.",--Yes, that is the epicenter - right there. I wonder what kind of treasure that house can hold. OK, on with our heist here.
	pln_ff3_11_any_01 = "OK, tenham cuidado! Vai valer a pena se esgueirar a todo momento, rapazes. Sem alarmes e essa incriminação será perfeita!",--OK, be careful! It will be worth sneaking all the way through, boys. No alarms and this framing will be perfect!
	pln_ff3_18_any_01 = "É triste deixar todo esse ouro para trás, mas vamos ser pagos. Talvez possamos retornar.",--It feels bad to leave the gold, but we will get paid. Maybe we can return.
	pln_ff3_07_any_08 = "A imprensa vai festejar em cima desse pobre coitado. Parece que o acordo foi por água abaixo em um escritório público também!",--Press are going to party on this poor guy. Seems the deal went down in public office too!
	pln_ff3_16_any_01 = "1600 Penn, talvez iremos lá para o nosso próximo grande golpe.",--1600 Penn, maybe we go there for our next big score.
	pln_ff3_10_any_01 = "Cara... esse lugar... Encontrem o ouro e poderemos comprar um para nós.",--Man... This place... Find that gold and we can buy one of our own.
	pln_ff3_05_any_01 = "Encontrem a sala do servidor. Vou scannear as coisas dele para conseguir informações no acordo de armas.",--Find me his server room. I will scan his stuff for info on the arms deal.
	pln_ff3_07_any_06 = "Nossa! Parece que o bom senador fez o acordo e festejou ao mesmo tempo - parece um acordo de armas-ouro-cocaína.",--Oh, my! Seems like the good senator did the deal and partied at the same time - looks like a arms-gold-coke deal.
	pln_ff3_04_any_01 = "O acordo de armas galera... Precisamos expor isso na mídia e rápido. Com certeza vai criar um efeito de incriminação.",--The arms deal guys... We got to get that deal exposed in the media and fast. It will create a framing effect for sure.
	pln_ff3_07_any_02 = "Parece que o acordo foi uma transação de armas e ouro. Feito aqui mesmo na capital.",--Seems like the deal was a gold arms transaction. Made here in DC.
	pln_ff3_13_any_01 = "Escritório do governo. Nossa, estamos no caminho errado de trabalho, senhores.",--Public office. Wow, we are in the wrong line of work gentlemen.
	pln_ff3_08_any_01 = "Isso vai funcionar como uma incriminação - não vai ser fantástica, mas seremos pagos. Vamos tirar vocês daí!",--This will work as a frame - won't be fantastic, but we will get paid. Let's get you out!
	pln_ff3_12_any_01 = "Olhem para todas essas coisas valiosas. Ele deve ter feito muitos trabalhos públicos na carreira.",--Look at all these nice things. Must have done a lot of public service in his career.
	pln_ff3_07_any_07 = "OK! Temos algo realmente escandaloso aqui. Ele vendeu armas do governo para um estado ilegal - e foi pago em ouro. Os Democratas não irão gostar disso.",--OK! We got some real scandal stuff here. He sold government arms to a rogue state - got paid in gold. The Democrats aint gonna like this.
	pln_ff3_14_any_01 = "Olhem essa vista...",--Look at the that view...
	pln_ff3_07_any_10 = "Mantenham esse feed de notícias rodando e eu vou começar a achar um jeito de tirar vocês daí.",--Keep that news feed alive and I'll start getting you a way out of there.
	pln_ff3_07_any_03 = "Entendi por que o Elefante quer isso. Tem muito ouro na jogada!",--I get why the Elephant wants this. It is tons of gold in this deal!
	pln_ff3_09_any_01 = "Que apartamento! Certeza de que esse acordo de armas foi uma grande adição ao pagamento do Senador.",--What a flat! These arms deals sure are a nice addition to his senator pay.
	pln_ff3_03_any_01 = "OK, OK, teremos que mudar os planos!",--OK, OK, we gotta change this up!
	pln_ff3_06_any_01 = "Ótimo! Agora me conectem!",--Great! Now hook me up!
	pln_ff3_07_any_01 = "Ah, OK! Estou conseguindo coisas boas aqui!",--Ah, OK! I'm getting some juicy stuff here!
	pln_ff3_07_any_04 = "Ah, seria melhor fazer isso no Stealth. Muito ouro envolvido.",--Ah, we should have sneaked this. Tons of gold in this deal.
	pln_ff3_07_any_05 = "Certo, achei um vídeo dele fazendo o acordo... É insano. Ele é muito exibido.",--Alright, I found video of him doing the deal... It is insane. He sure is a show-off.
	pln_ff3_07_any_09 = "Vou empacotar isso em arquivos e já se preparem para colocar isso ao vivo na imprensa.",--I'll pack this into files and get ready to stream it up to the press.
	pln_ff3_17_any_01 = "Ah, esse é o cofre galera. Essa porta, não podemos passar por ela dessa vez. Mas o ouro... O ouro está do outro lado! Bom, teremos que abandoná-lo.",--Ah, that is the vault guys. That door, we can't get through it this time. But the gold... The gold on the other side! Well, we got to leave it.
	
	-- Objetivos (Dia 1)
	hud_e_framing_frame_stage1_mission1_hl = "Entre na Galeria",--Enter the gallery
	hud_e_framing_frame_stage1_mission2_hl = "Roube as Pinturas Marcadas",--Steal the marked paintings
	hud_e_framing_frame_stage1_mission4 = "Para acessar as pinturas, acesse a sala de segurança e hackeie o sistema de segurança.",--To reach the paintings, access the security room and hack the security system
	hud_e_framing_frame_stage1_mission3 = "Pegue as pinturas e coloque dentro da van.",--Carry the paintings and throw them into the van
	hud_e_framing_frame_stage1_mission2 = "Procure por pinturas que possuam o adesivo de venda (Sold) vermelho nelas.",--Look for paintings that have the red "sold" sticker on them
	hud_e_framing_frame_stage1_mission5 = "Vá até o veículo de fuga.",--Get to the escape vehicle
	hud_e_framing_frame_stage1_mission1 = "Encontre uma forma de entrar na galeria.",--Find a way to get inside the gallery
	hud_e_framing_frame_stage1_mission4_hl = "Desabilite as Barreiras",--Disable the barriers
	hud_e_framing_frame_stage1_mission3_hl = "Leve as Pinturas até a Van",--Take the paintings to the van
	hud_e_framing_frame_stage1_mission5_hl = "Fuga está Disponível!",--Escape is available!
	
	-- Objetivos (Dia 2)
	hud_e_framing_frame_stage2_mission1_hl = "Atenda o Telefone",--Answer the phone
	hud_e_framing_frame_stage2_mission6 = "Vá até o veículo de fuga.",--Get to the escape vehicle
	hud_e_framing_frame_stage2_mission3_hl = "Entre no Vagão de Trem",--Get into the train cart
	hud_e_framing_frame_stage2_mission5_hl = "Emboscada!",--Ambushed
	hud_e_framing_frame_stage2_mission1 = "Atenda o telefone e faça a negociação.",--Answer the phone to make the trade
	hud_e_framing_frame_stage2_mission6_hl = "Fuga está Diponível",--Escape is available
	hud_e_framing_frame_stage2_mission3 = "Para continuar a negociação, certifique-se que todos estão dentro do vagão de trem.",--To continue the trade, make sure everyone is in the train cart
	hud_e_framing_frame_stage2_mission4 = "Joguem as bolsas para executar a troca.",--Throw the bags to do the trade
	hud_e_framing_frame_stage2_mission4_hl = "Faça a Troca",--Do the trade
	hud_e_framing_frame_stage2_mission2_hl = "Coloque as Pinturas",--Place the paintings
	hud_e_framing_frame_stage2_mission2 = "Coloquem as pinturas em cima da mesa.",--Place the paintings on the table
	hud_e_framing_frame_stage2_mission5 = "É uma Emboscada! Escapem!",--It's an ambush! Make for the escape
	
	-- Objetivos (Dia 3)
	hud_e_framing_frame_stage3_mission8 = "Cuidado com os lasers e levem o ouro ao ponto inicial.",--Take care of the lasers and carry the gold to the insertion point
	hud_e_framing_frame_stage3_mission4_hl = "Acesse o Computador",--Access the computer
	hud_e_framing_frame_stage3_mission2_hl = "Roube os Itens",--Steal the items
	hud_e_framing_frame_stage3_mission13_hl = "Fuga está Disponível",--Escape is available
	hud_e_framing_frame_stage3_mission1_hl = "Entre no Apartamento",--Get into the apartment
	hud_e_framing_frame_stage3_mission6 = "Levem as bolsas com cocaína da cobertura e coloque em frente da porta do cofre.",--Carry the bags with coke from the roof and place it infront of the vault door
	hud_e_framing_frame_stage3_mission11 = "Use o computador na sala do servidor para iniciar o upload dos arquivos do FBI.",--Use the computer in the server room to start uploading the files to the FBI
	hud_e_framing_frame_stage3_mission5_hl = "Encontre o Cofre Escondido",--Find the hidden vault
	hud_e_framing_frame_stage3_mission11_hl = "Faça o Upload dos Arquivos",--Upload the files
	hud_e_framing_frame_stage3_mission5 = "Localize e entre no cofre escondido.",--Locate and get into the hidden vault
	hud_e_framing_frame_stage3_mission14_hl = "Reative o Computador ",--Reactivate the computer
	hud_e_framing_frame_stage3_mission12_hl = "Restaure a Energia de volta",--Turn the power back on
	hud_e_framing_frame_stage3_mission7 = "Use o computador fixo e abra a porta do cofre.",--Use the stationary computer and open the vault door
	hud_e_framing_frame_stage3_mission4 = "Entre no escritório do democrata e acesse seu computador fixo.",--Get into the democrat's office and access his stationary computer
	hud_e_framing_frame_stage3_mission8_hl = "Pegue o Ouro",--Get the gold
	hud_e_framing_frame_stage3_mission3_hl = "Coloque tudo na Cobertura",--Set-up everything at the roof
	hud_e_framing_frame_stage3_mission9_hl = "Escape",--Escape
	hud_e_framing_frame_stage3_mission7_hl = "Abra a porta do Cofre",--Open the vault door
	hud_e_framing_frame_stage3_mission14 = "Use o teclado para reativar o computador e continuar o hackeamento.",--Use the keyboard to reactivate the computer and continue the hacking
	hud_e_framing_frame_stage3_mission10_hl = "Localize a Sala do Servidor",--Locate the server room
	hud_e_framing_frame_stage3_mission10 = "Encontre a sala do servidor que está em algum lugar do apartamento do democrata.",--Find the server room somewhere in the democrats' apartment
	hud_e_framing_frame_stage3_mission3 = "Instale todos os dispositivos na estação de vocês que está na cobertura.",--Set-up all the devices at your station on the roof
	hud_e_framing_frame_stage3_mission6_hl = "Coloque a Cocaína em frente à Porta do Cofre",--Plant the coke infront of the vault door
	hud_e_framing_frame_stage3_mission13 = "Chegue até o veículo de fuga.",--Get to the escape vehicle
	hud_e_framing_frame_stage3_mission1 = "Entre no apartamento do democrata.",--Get into the Democrat's apartment
	hud_e_framing_frame_stage3_mission2 = "Encontre o Laptop, HDs, Tablet e Telefone.",--Find the laptop, hard drive, tablet and the phone
	hud_e_framing_frame_stage3_mission9 = "Escape pela tirolesa na cobertura próximo ao ponto inicial.",--Escape via the zip line on the roof next to the insertion point
	hud_e_framing_frame_stage3_mission12 = "Encontre o disjuntor para ligá-lo novamente e continuar o upload.",--Find the circuitbreaker to turn the power back on and continue the upload	
		})
end)