return {
	-- Nomes e Descrições
	--heist_pbr = "Beneath the Mountain",
	--heist_pbr_hl = "Beneath the Mountain",
	heist_pbr_briefing = "Locke quer que nós ataquemos uma instalação da Murkywater no deserto. A Black Ridge. Era uma antiga instalação das forças aéreas. A Murkywater comprou o lugar depois da guerra fria, o transformando em seu próprio Fort Knox, então vocês podem apostar que eles estão guardando grandes coisas por lá. Não tenho certeza do que esperar, não tem muita coisa online então temos poucas informações. Mas uma coisa é certa - Você não vai atravessar esse lugar de forma furtiva. Se preparem para mais uma guerra.",--Locke has us hitting a Murky facility out in the desert. Black Ridge. Was an old air force place, back in the day. Murkywater bought it up after the Cold War, turned it into their own Fort Knox, so you can bet they're holding some serious loot here. Not sure what to expect. Not much online, so we got little in the way of intel. One thing is certain though - you're not going to sneak through this one. Dress for loud.
	heist_pbr_crimenet = "O alvo da vez é uma instalação da Murkywater no deserto. Considerem o próprio Fort Knox deles. Force a sua entrada e traga qualquer espólio que eles estejam guardando.\n\n» Recupere os Recursos deixados por Locke\n» Lute pelo caminho até o Complexo interior\n» Abra os Cofres e pegue os Espólios\n» Encontre-se com o Locke\n» Destrua os Radares e fuja!",--The target is a Murkywater facility in the desert. Consider it their Fort Knox. Force your way in, and bring out whatever loot they're holding.\n\n» Retrieve assets left by Locke\n» Fight your way to the inner complex\n» Open the vaults and retrieve the loot\n» Meet with Locke\n» Destroy the radars and escape
	
	-- Legendas
	mer_jr1_intro_01_01 = "Intrusos! Fogo!",--Intruders! Fire!
	loc_jr1_08_02 = "Agora conectem as cargas de explosivos. Uma para cada uma das quatro travas.",--Now wire up those breaching charges. One for each of the four locks, if you please.
	loc_jr1_45_02 = "Ainda bem que eu tenho um suprimento de C4 bem aqui.",--Thankfully, I have a supply of C4 right here.
	loc_jr1_57_09 = "Vi aquela arma em uma vila lá em Uganda. Homem bom.",--Saw that one gun down a village in Uganda. Good man.
	loc_jr1_57_13 = "Ha, ele sempre disse que queria morrer em um bordel. Bem, ao menos ele se fudeu, yeah?",--Ha, he always said he wanted to die in a brothel. Well, at least he got fucked, yeah?
	loc_jr1_15_01 = "Boom! Ótimo! Agora, pra dentro. Chutem, atirem e destruam!",--Boom! Good! Now, inside. Skop, skiet en boomklim!
	loc_jr1_24_01 = "Ah! aí está! Agora, por favor, saiam da trava de ar e vão para o complexo interior.",--Ah! There it is! Now, please, out of the airlock and into the inner complex!
	loc_jr1_70_03 = "Tem um lindo pequeno protótipo em uma dessas caixas, queridos amigos. Abram-nas para achá-lo",--There's a lovely little prototype in one of those crates, dear friends. Open them to find it.
	loc_jr1_34_03 = 'Isso foi encontrado pela nossa divisão "Tomb Raider". Eles eram ótimas pessoas. Porém bebiam como irlandeses.',--This was found by our "tomb raider" division. They're great guys. Drink like fucking micks though.
	loc_jr1_71_03 = "Ah, e outro cofre já está pronto para ser saqueado!",--Ahhh, and another vault is ready to be plundered!
	loc_jr1_66_02 = "Apenas dois de vocês de cada vez na tirolesa, por favor. E é uma viagem de ida apenas. Mas que viagem, yeah?",--Only two of you at a time up the zipline, please. And it's a one way trip. But what a trip, yeah?
	loc_jr1_44_01 = "Seria melhor que esses radares fossem destruidos. Sim?",--It would be best if these radars were destroyed. Yes?
	loc_jr1_20_03 = "Nós precisamos de aprovação da estação de segurança. Eu mesmo faria, mas infelizmente...",--We need approval from the security station. I would do it myself, but alas...
	loc_jr1_47_03 = "Depois de vocês!",--After you!
	loc_jr1_66_03 = "Apenas dois usando a tirolesa de cada vez, meus bons amigos. e quando estiverem lá em cima, não tem mais volta. Então vão.",--Only two riding the ziplines at a time, my good friends. And once you're up, that's it. So come on.
	loc_jr1_22_01 = "Tenham certeza que todos vocês estejam dentro, a porta de fora deverá fechar para a de dentro abrir.",--Make sure all you fine people are inside, the outer door must close before the inner door can open.
	loc_jr1_27_02 = "O controle será encontrado com uma boa vista para o complexo.",--The control will be found overlooking the complex.
	loc_jr1_51_01 = "Eu tenho um ótimo lugar, apenas para as bolsas de espólios... bem aqui.",--I have a nice spot, just for those loot bags... right here.
	loc_jr1_40_01 = "Ah! Cavalheiros! Saudações!",--Ah! Gentlemen! Greetings!
	loc_jr1_23_02 = "Vai abrir em um segundo ou dois. E então...",--It will open in a second or two. And then... 
	loc_jr1_14_02 = "Vocês deixaram os kerels fuderem vocês. Fodam eles de volta e consertem o detonador.",--You let the kerels fuck you. Fuck 'em back and fix the detonator.
	loc_jr1_50_01 = "Ok, amigos, movam essas bolsas para o helicóptero. Não percam tempo agora!",--Okay, friends, let us now move the lootbags to the helicopter. Do not dawdle now!
	loc_jr1_15_02 = "Ka-boom! Essa foi bem no alvo, sim. Mandem bala lá dentro!",--Ka-boom! That was on the bullseye, yes. Fight your way in!
	loc_jr1_58_02 = "Esses cobres não valem nada.",--These coppers ain't worth a yak's baff.
	loc_jr1_53_01 = "Eu sei que é uma imposição, mas vocês acham que podem conectar a mangueira de combustivel no helicóptero?",--I know it is an imposition, but do you think you could connect the fuel hose to the helicopter?
	loc_jr1_58_04 = "Faça-os ganhar o tomo deles hoje a noite, yeah? Com certeza.",--Make them earn their tom tonight, yeah? For sure.
	loc_jr1_69_03 = "É uma pena ter que ver uma ótima tecnologia como essa explodir assim. Mas foda-se!",--Shame to see nice tech blow up like that. But fuck it!
	loc_jr1_57_12 = "Eu não gostava das maneiras daquele filho de uma puta.",--I didn't like that poephol's manners.
	loc_jr1_11_03 = "Por favor? Conectem o detonador?",--Please? Attach the detonator?
	loc_jr1_51_03 = "Apenas tragam essas bolsas para o helicóptero, meus queridos amigos.",--Just bring thoses bags to the chopper, dear friends.
	loc_jr1_62_03 = "Eu preciso que vocês façam a maior violência, yeah? Meu uniforme deve me misturar entre eles. Ficar fora dessa luta.",--I need you guys to distribute the violence, yeah? My uniform should let me blend in with them, keep out of the fight.
	loc_jr1_16_01 = "Venham agora, todos para dentro! Depressa!",--Come now, everyone inside! Hurry!
	loc_jr1_07_01 = "Lembrem-se, larguem as cargas perto da porta.",--Remember, drop the charges near the door.
	loc_jr1_17_03 = "Essa porta tem um protocolo de segurança de dois estágios. O primeiro estágio é usar o cartão de acesso. então... quando vocês quiserem.",--This door has a two-stage security protocol. First stage is using the keycard. So...if you please.
	loc_jr1_12_01 = "A contagem começou. mantenham a policia longe do detonador, yeah? Nada de se esconder!",--The countdown has started. Keep the police off the detonator, yes? No snippy-snip!
	loc_jr1_50_02 = "Agora, se vocês quiserem ser gentis.. As bolsas de espólios para dentro do helicóptero, pode ser?",--And now, if you would be so kind, the loot bags to the helicopter? Please?
	loc_jr1_43_01 = "Nosso helicóptero de fuga está lá fora, mas vocês também irão ver vários equipamentos de radar. É com isso que eles conseguiriam nos seguir para qualquer lugar que voássemos.",--Our escape chopper is out here, but you will also see a lot of radar equipment. With this, they could follow us anywhere we could fly to. 
	loc_jr1_46_03 = "Quase aberta. lembrem-se, vocês lidam com os radares e eu preparo o helicóptero.",--Almost open. Remember, you deal with the radars, and I will prepare the helicopter.
	loc_jr1_67_02 = "Esse sistema foi construido para ser simples. Tudo o que vocês precisam fazer é escolher um cofre e pressionar um botão. fácil, yeah? Com certeza.",--This system is built to be simple. All you got to do is choose a vault and press a button. Easy, yeah? For sure.
	loc_jr1_43_03 = "Nossa fuga de helicóptero é iminente, mas nós temos que nos cobrir. Atrás dessa porta a Murkywater tem uma força de equipamentos de radar.",--Our escape by helicopter is imminent, but we must cover ourselves. Beyond the door Murkywater has an impressive array of radar equipment.
	loc_jr1_56_01 = "Nós estamos finalmente quase terminados! Por favor, Juntem-se a mim no helicóptero!",--We are finally almost finished! Please, join me at the helicopter!
	loc_jr1_19_02 = "Bravo! Agora, segundo passo - Encontrem a estação de segurança, Entrem e aprovem a sequência de abertura",--Bravo! Now, second step - find the local security station, cut through and approve the opening sequence.
	loc_jr1_53_03 = "Sim, seria mais agradável conseguir combustível para o helicóptero.",--Yes, it would be most agreeable to get some fuel in this chopper.
	loc_jr1_58_01 = "A luta continua!",--A luta continua!
	loc_jr1_32_01 = "E eu acredito que seja isso, meus amigos! Agora, por favor tenham certeza de que nossos espólios duramente conquistados estejam amarrados nos cabos e sejam trazidos até mim.",--And I believe that about does it, my friends! Now, please ensure that our hard-earned loot is placed on the cables and conveyed up to me. 
	loc_jr1_59_03 = "Agora apenas deixem a trava de tempo acabar, queridos amigos. Vai valer a pena. Eu prometo.",--Now just let the timelock run down, dear friends. It will be worth it, I promise.
	loc_jr1_58_06 = "Nós poderiamos ter usado vocês lá em Rodésia.",--We could have done with you guys in Rhodesia.
	loc_jr1_52_03 = "Amigos! Alguns zé bucetas estiveram passeando com esse pássaro. O tanque tá totalmente vazio. Vocês poderiam ser bons companheiros e enganchar a mangueira de combustível?",--Ach! Some poes has been joyriding this bird. Gas is empty. Can you be a good chap and hook up the fuel line?
	loc_jr1_03_01 = "Cavalheiros? As caixas marcadas? Por favor?",--Gentlemen? The crates with the strobes? Please?
	loc_jr1_35_02 = "Esse servidor tem segredos, gravações, informações que podem mudar o mundo. E todos os meus jogos salvos. Yeah, com certeza.",--This server has secrets, recordings, data that can change the world. And all my saved games. Yeah, for sure.
	loc_jr1_35_01 = 'Essa coisa tem segredos que podem derrubar o governo. Quer ver o que o presidente mantém guardado em uma pasta chamada "Interesses de Cavalheiros"?. você quer, com certeza!',--This thing has secrets that can topple the government. Wanna see what the President keeps in a folder called "Gentlemen's Interests"? Yeah, you do - for sure!
	loc_jr1_28_02 = "Agora, apenas um cofre pode ser aberto por vez, e não são todos os cofres que tem espólios. Eu vou deixar para vocês decidirem qual vale a pena ser aberto.",--Now, only one vault can be opened at a time, and not all vaults are containing the loot. I will leave it to you to figure out which is worth opening. 
	loc_jr1_21_01 = "Esplêndido! Tudo está progredindo perfeitamente. Agora, por favor, Todos para dentro da trava de ar.",--Superb! Everything is proceeding perfectly. Now, please, everybody into the airlock.
	loc_jr1_44_02 = "Nós queremos sair em paz, então esses devem ser destruidos. Eu posso deixar isso com vocês, yeah?",--We want to get away cleanly so these must be destroyed. I can leave that to you, yes?
	loc_jr1_41_02 = "Nós podemos nos conhecer melhor depois, mas agora eu sinto que seria oportuno, como vocês dizem, DAR O FORA, sim?",--We can get better acquainted later, but I feel now would be the opportune time to, how you say, GTFO, yes?
	loc_jr1_69_02 = "Boom, bang e cambalhota! Ótimo!",--Boom, bang and tumble! Great! 
	loc_jr1_57_20 = "É, morra seu maldito arrombado.",--Yeah, die you fucking cuiter. 
	loc_jr1_39_03 = "Eu estou ansioso para conhecer vocês todos. Por favor, subam pela tirolesa.",--I'm keen to meet you all. Please, zipline up the shaft.
	loc_jr1_23_03 = "A qualquer momento agora. Alguém conhece alguma piada?",--Any second now. Does anybody know any jokes?
	loc_jr1_37_02 = "As bolsas vão estar perfeitamente seguras comigo. Mandem elas aqui para cima, por favor.",--The bags will be perfectly safe with me. Send them up, please.
	loc_jr1_19_01 = "Ótimo. Segundamente, tem uma sala de segurança por perto. Entrem nela e aprovem a sequência da trava de ar.",--Good. Secondly, there is a security room close by. Cut through to it, and approve the airlock sequence.
	loc_jr1_57_11 = "Ele era material oficial. Era!",--He was officer material. Was! 
	loc_jr1_51_02 = "Nós estamos quase acabando, mas deixem-me lembrar a todos de novo para trazer as bolsas para o helicóptero.",--We're almost done, but may I remind you again about bringing the bags to the helicopter?
	loc_jr1_58_05 = "Façam isso como vocês fizeram no armazém. Yeah, eu vi aquilo, com certeza.",--Do it like you did it at the warehouse. Yeah, I saw that. For sure.
	loc_jr1_32_02 = "Maravilhoso! Creio eu que isso seja o suficiente para fazer nossa viagem ter valido a pena. Por favor tenham certeza de que todas as bolsas estejam presas aos cabos e cheguem até mim.",--Wonderful! I believe that that is enough to make this a worthwhile venture. Please, ensure all of the bags are placed on the cables and sent up to me.
	loc_jr1_30_03 = "Essa é uma boa quantidade de espólios, amigos. O suficiente para fazer isso ter valido a pena. Mas, se vocês quiserem foder a Murkywater mais um pouquinho... vocês podem pegar mais.",--That is a good amount of loot, friends. Enough to make this worthwhile. Still, if you feel like you still got a little lead in your pencil and wanted to fuck Murkywater a little longer... you can get more.
	loc_jr1_37_03 = "Vocês veem os cabos? Sim, mandem as bolsas aqui pra cima.",--Do you see the shaft? Yes, just send the bags of loot up here.
	loc_jr1_14_01 = "Esses zé bucetas foderam com o detonador. Consertem!",--Those poes fucked the detonator, mans. Fix it!
	loc_jr1_66_01 = "Ok, vocês podem subir dois de cada vez. E não tem como descer de volta, amigos.",--Okay, you can only zipline up two at a time. And there's no going back down, friends. 
	loc_jr1_09_01 = 'Eu falei em Africano? Me desculpem! Eu quis dizer "por favor" "plantem" "as" "cargas" "nas fechaduras"... seus merdinhas.',--Did I speak in Afrikaans? My apologies! I meant to say "please" "plant" "the" "charges" "on the locks"... you kaks.
	loc_jr1_60_01 = "Merda, esses comedores de bosta desativaram o destravamento. Ativem-no de novo!",--Shit, those fucking shit-eating kerels shut down the unlocking. Get it going again!
	loc_jr1_01_03 = "Ah! Meus amigos! Bem-vindos ao Black Ridge. Ela é usada para... bem, por enquanto, guardar uma quantia significável de espólio de grande valor. Vamos roubá-los!",--Ah! My friends! Welcome to Black Ridge. It's used for, well, for now is holding loot of a significent value. Let's steal it!
	loc_jr1_33_01 = "É uma linda pintura. Última vez vista nas paredes de um Ditador conhecido da América do Sul. Veem como o artista retratou a luz e todas essas besteiras? Lindo.",--It's a beautiful painting. Last seen on the walls of a well known South American dictator. See how the artist captured the light and all that shit? Beautiful.
	loc_jr1_57_06 = "Ele tinha apenas uma semana sobrando em seu contrato.",--He only had a week left on his contract.
	loc_jr1_40_03 = "Olá para vocês, meus novos amigos!",--Hello, to you, my new friends!
	loc_jr1_26_03 = "Essa área tem diversos cofres, que podem ser abertos a partir de uma sala de controle. então por demanda de necessidade nós vamos para a sala de controle.",--This area has several vaults, which can be opened from a control room. We want what's in the vaults so necessity demands we get to the control room.
	loc_jr1_56_03 = "Nós acabamos, meus bons amigos! Todos para dentro do helicóptero!",--We are done, my good friends! Everyone into the helicopter!
	loc_jr1_41_01 = 'Agora, vai ter tempo para "olás" mais longos depois, Mas nós realmente deveriamos escapar agora, yeah?',--Now, there will be time for longer hellos later, but we should really make our escape now, yes?
	loc_jr1_57_19 = "Ele era meu amigo. Mas merdas acontecem, certo?",--He was my chomma. Shit happens though, right?
	loc_jr1_21_02 = "Bakgat! Agora mexam-se, meus amigos. A trava de ar espera por vocês!",--Bakgat! Now, onwards, my friends. The airlock awaits you!
	loc_jr1_63_03 = "Se eles vão seguir o roteiro de sempre, eles vão ter snipers posicionados logo em frente. E esses caras sempre seguem o roteiro à risca.",--If they're going by the book they'll have snipers set up ahead. These cocks always go by the book.
	loc_jr1_55_02 = "Ótimo. Nós temos um tanque cheio, várias luzes verdes e estamos cheios de espólios roubados. Entrem, meus amigos, vamos concluir isso.",--Great. We got a full tank, lots of green lights and we're fat with stolen loot. Hop aboard, my friends. Let's conclude this.
	loc_jr1_12_03 = "Tick-tock, disse o detonador. Mantenha os kerels longe.",--Tick-tock, said the detonator. Keep the kerels away. 
	loc_jr1_57_14 = "Ele bombardeou uma escola. Boa libertação.",--He bombed a school. Good riddance.
	loc_jr1_10_02 = "Muito bem-feito. Próximo, nós precisamos de um detonador naquelas cargas. Vocês não querem acioná-las?",--Nicely done. Next, we need a detonator on those charges. Rig it up, won't you?
	loc_jr1_53_02 = "Posso lembrar-lhes de que esse helicóptero ficará no chão até que ele esteja reabastecido?",--Can I remind you that this chopper is grounded until it is refueled?
	loc_jr1_24_03 = "Ah, a porta abre! Agora, vamos proceder para o complexo interior com velocidade e violência.",--Ah, the door opens! Now, let us proceed into the inner complex with speed and violence.
	loc_jr1_38_02 = "Deixe-me ver.. um, dois. Sim, todas aqui! Agora, por favor, usem os cabos para se juntarem à mim aqui.",--Let me see, one, two. Yes, all here! Now, please use the cables to join me up here. 
	loc_jr1_68_01 = "Kaboom! Bom trabalho, continuem!",--Kaboom, good work! Keep it up!
	loc_jr1_10_03 = "Bravo! Agora, porque nós não colocamos um detonador lá também?.",--Bravo! Now, why don't we get a detonator on there too.
	loc_jr1_62_01 = "Vocês dão os tiros, meus amigos, eu vou me misturar um pouco com meu uniforme da Murky. Não misturem as coisas, ok?",--You do the shooting, my friends, I'll just blend in a bit with my Murky Uniform. Don't get me mixed up, okay?
	loc_jr1_59_02 = "E agora nós esperamos a trava de tempo acabar. Esse é um lugar seguro caso vocês não saibam.",--And now we wait for the vault timelock to run down. This is a secured site, you know.
	loc_jr1_04_03 = "Tem um cartão de acesso, um cortador de arco e um pequeno número de cargas explosivas que vocês devem coletar. Entrar explodindo tudo é rude, mas ajudará a tirar a suspeita de mim.",--There is a keycard, an arc cutter and a small number of breaching charges, that you must collect. Blasting in is crude, but it will help deflect suspicion from me.
	loc_jr1_62_02 = "Vocês fazem toda a matança, yeah? Eu sou um soldado cibernético, não a porra de um comandante. Meu uniforme deve me manter fora de vista.",--You do all the killing, yeah? I'm cyberwarfare, not a fucking commando. My uniform should keep me out of the fray.
	loc_jr1_49_02 = "Essa foi na mosca! Agora nós podemos voar pra longe e não se preocupar em sermos seguidos.",--That was a bulleye, yes! Now we can fly away and worry not a jot about being followed!
	loc_jr1_54_01 = "Ah merda, eles sabem que estamos tentando sair. Eles vão vir com tudo! Segurem-se firme, amigos!",--Ah kak, they know we're trying to fuck off. They're going all in! Hold steady, friends!
	loc_jr1_70_01 = "Escutem! Aquele cofre contém o protótipo. Está em uma das caixas. As outras são distrações.",--Listen! That vault contains the prototype. It's in one of the crates. The others are decoys..
	loc_jr1_49_03 = "Me entristece ver um hardware tão bonito assim reduzido a cinzas, mas é um mau necessário. Agora nossa fuga está garantida!",--It saddens me to see such beautiful hardware reduced to ruins, but it is a necessary evil. Now, our clean escape is assured!
	loc_jr1_70_02 = "Ahhh! Tem um protótipo valioso naquele cofre. Está em uma das caixas, e não nas outras. Abram-nas para encontrá-lo.",--Ahhh! There's a valuable prototype in that vault. It's in one of the crates, and not in the others. Open them to find it.
	loc_jr1_41_03 = "Nós podemos nos conhecer com whiskey e cigarros depois, porque eu sinto que essa é a hora perfeita para fugirmos, sim?",--We can get to know each other over whiskey and cigars later, because I feel that now would be the perfect time for a getaway, yes?
	loc_jr1_03_02 = "Eu odeio incomodar vocês, eu realmente odeio, mas encontrar aquelas caixas é o nosso objetivo principal.",--I hate to bother you,I really do, but finding the crates is our primary objective.
	loc_jr1_60_03 = "Ei, o que aconteceu? Ah, merda - Os policiais interromperam a abertura do cofre. Façam voltar a funcionar de novo. E matem a porra dos policiais!",--Hey, what happened? Ah, shit - cops interrupted the vault. Get it going again. And kill the fucking cops.
	loc_jr1_47_01 = "E... Aqui vamos nós!",--And... we go!
	loc_jr1_58_09 = "Vocês batem mais forte que minha primeira esposa.",--You fellas hit harder than my first wife.
	loc_jr1_07_02 = "Deixe-me verificar minhas anotações. Sim, eu mencionei que as cargas devem ser deixadas perto da porta.",--Let me check my records. Yes, I mentioned that the charges must be dropped near the door.
	loc_jr1_69_01 = "E mais um morde a poeira! Ótimo!",--And another one bites the dust! Nice!
	loc_jr1_17_02 = "Agora, o cartão de acesso que eu deixei para vocês. Aquela porta grande tem dois estágios de segurança e uma trava de ar atrás. O primeiro estágio é usar o cartão, então...",--Now, the keycard I left for you. That large door has two security stages, and an airlock beyond. The first is using the keycard. So...
	loc_jr1_61_03 = "Isso meus amigos! Ok, o cofre está se abrindo de novo. Ótimo!",--Fuck yes, my friends. Okay, the vault is opening again. Good!
	loc_jr1_68_02 = "Isso foi um estouro! Muito satisfatório!",--That was a bang! Most satisfying!
	loc_jr1_42_02 = "Cavalheiros? Por favor?",--Gentlemen? Please?
	loc_jr1_16_03 = "Entrem, Por favor! Juntem-se a festa de dentro!",--Come on, please, join the party inside!
	loc_jr1_57_05 = "Ele sabia que iria morrer essa noite. Apenas sabia.",--He knew he was going to die tonight. Just knew it.
	loc_jr1_57_24 = "Ele sempre tava com a boca no trombone, então meus agradecimentos.",--He was always on the vuvuzela, so my thanks.
	loc_jr1_42_03 = "Por aqui, meus amigos, com toda pressa.",--This way, my friends, with all haste.
	loc_jr1_11_02 = "Eu sei que as coisas estão agitadas e que vocês estão muito ocupados, mas vocês se importariam de pôr o detonador naquelas cargas?",--I know things are hectic and you are very busy, but would you mind getting the detonator onto the charges?
	loc_jr1_58_10 = "Não se preocupem com os corpos. Nós temos... Uma instalação.",--Don't worry about all the bodies. We have... a facility.
	loc_jr1_57_07 = "Ha! Eu aposto que eles não esperavam por isso, com certeza!",--Ha! I bet he didn't expect that, for sure!
	loc_jr1_54_02 = "Parece uma última tentativa desesperada de cortar as nossas asas, hein? Fiquem firmes, Bravos heróis.",--Looks like a last desperate attempt to clip our wings, hey? Stand firm, brave warriors.
	loc_jr1_63_01 = "Eu estou ouvindo pelas comunicações e parece que eles prepararam uma emboscada com Snipers. Abaixem as cabeças!",--I'm hearing over the comms that they've set up a sniper ambush ahead. Watch your heads!
	loc_jr1_02_01 = "Antes de nós começarmos, eu preparei alguns itens para vocês. Encontrem as caixas com as marcas vermelhas.",--Before we begin, I've arranged for a few small articles to be left for you. Find the crates with the red strobe.
	loc_jr1_22_03 = "Por favor, todos dentro da trava de ar. As portas são projetadas para que o interior não abra até que o exterior esteja fechado.",--Please, everyone into the airlock. The doors are designed so that the inner cannot open until the outer is closed.
	loc_jr1_67_01 = "É a simplicidade em si, amigos. Apenas pressionem o botão do cofre que vocês querem abrir. Apenas se certifiquem de que tem algo lá dentro.",--It's simplicity itself, friends. Just press the button of the vault you want to open. Just be sure it actually contains something.
	loc_jr1_09_02 = "Talvez tenha ocorrido uma interferência no rádio, então permitam-me repetir. Plantem a porra das cargas nas travas, por gentileza.",--Perhaps there was interference on the radio, so let me repeat. Plant the fucking charges on the locks. Please.
	loc_jr1_29_03 = "Ahhh, se algum som é mais satisfatório do que o de um cofre abrindo é o de empacotar espólios valiosos. Vocês estão produzindo uma bela sinfonia para os meus ouvidos!",--Ahhh, if any sound is sweeter than that of an opening vault it is that of bagging loot. You are producing a symphony for my ears!
	loc_jr1_25_03 = "Seria lindo se vocês pudessem concluir isso apenas se escondendo na trava de ar, Mas... Infelizmente...",--It would be beautiful if we could do this with you hiding in the airlock, but... alas...
	loc_jr1_05_01 = "Seria muito gentil se vocês coletassem os itens que deixei para vocês.",--If you would be so kind as to collect the articles I have left for you.
	loc_jr1_29_02 = "Ahhh, Meus ouvidos me enganam ou esse é o som de um cofre de titânio se abrindo? Continuem com seus esforços, amigos!",--Ahhh, do my ears deceive me or is that the sound of a titanium vault opening. Maintain your efforts, friends!
	loc_jr1_33_02 = "Eu não sei muito sobre arte, mas eu sei que alguém vai pagar caro por aquilo.",--I don't know much about fine art, but I know some poe will pay through the arse for that.
	loc_jr1_33_03 = "É uma obra-prima. Embora perdido por décadas. Eu penduraria no meu vaso sanitário, mas vale uma puta grana.",--It's a masterpiece. Thought lost for decades. I'd hang it in my crapper, but it's worth a shitload of cash.
	loc_jr1_45_03 = "Esse estoque de C4 deve lidar com os radares, yeah?",--This cache of C4 should deal with the radars, yes?
	loc_jr1_24_02 = "A porta está abrindo! Ótimo! Agora, por gentileza, invadam o complexo interno.",--The door is opening! Good! Now, if you would be so kind, please storm the inner complex.
	loc_jr1_59_01 = "Ok, paciência agora, meus amigos. Cada cofre tem uma pequena trava de tempo. Vocês sabem, por segurança.",--Okay, patience now, my friends. Each vault has a short timelock. You know, for security.
	loc_jr1_40_02 = "Meus amigos! Muito prazer!",--My friends! My pleasure!
	loc_jr1_18_03 = "Eu ainda preciso que um de vocês passem o cartão.",--I still require one of you poes to swipe the card.
	loc_jr1_01_01 = "Meus novos amigos! Bem-vindos ao Black Ridge. É como um armazém para espólios - Um armazém fortificado, com espólioss muitos valiosos.",--My new friends! Welcome to Black Ridge. Like a storehouse for loot - an armored storehouse, with very valuable loot.
	loc_jr1_17_01 = "O cartão de acesso que vocês coletaram mais cedo vai iniciar a abertura da trava de ar, que leva para o complexo interno. Passem esse pequeno merdinha.",--The keycard you collected earlier will initiate the opening of this airlock, which leads to the inner complex. Swipe that little kaka.
	loc_jr1_58_07 = "Vocês sabem mesmo como lutar.",--You guys know how to fight.
	loc_jr1_04_01 = "Cartão de acesso, cortador de arco e, sim, as cargas explosivas. Nós precisamos fazer parecer como se eu não estivesse envolvido. Colete-os",--Keycard, arc cutter and, yes, those are breaching charges. We need to make it look like I am not involved. Collect them.
	loc_jr1_25_01 = "Vamos, não precisam ficar nervosos. Saiam da trava de ar, amigos!",--Come on, no need to be nervous. Out of the airlock, friends!
	loc_jr1_71_01 = "Outro cofre se abriu. Bravo!",--Another vault opens. Bravo!
	loc_jr1_58_11 = "Yeah. Claro.",--Yeah. For sure.
	loc_jr1_16_02 = "Não fiquem tímidos agora. Para o complexo!",--Don't be shy now. Into the complex!
	loc_jr1_36_03 = "Certo, cuidado com isso agora. Vocês pressionam os botões errados e não tem como dizer o que vocês irão se tornar.",--All right now, careful with this. You press the wrong buttons and there's no telling what you might turn into.
	loc_jr1_13_02 = "A qualquer momento...",--Any... second...
	loc_jr1_59_05 = "Apenas segurem-se em seus cavalos, amigos. O cofre vai se abrir a qualquer momento.",--Just hold on to your horses, friends. The vault will be open any second. 
	loc_jr1_20_02 = "A porta precisa de uma aprovação, lembrem-se. Rápido. Parem de brincar com suas rolas.",--The door needs approval, remember. Hurry. Stop playing with your dicks.
	loc_jr1_31_02 = "Ah! A primeira bolsa! Vocês vão encontrar uma conveniência vertical perto dos cofres que vai levar as bolsas até mim. Vai ser perfeitamente seguro!",--Ah! The first bag! You will find a vertical conveyance near the vaults that will relay the loot up to me. It will be perfectly safe! 
	loc_jr1_26_01 = 'Vão para a sala de controle - o coração negro da instalação. De lá, vocês vão poder abrir os cofres e pegar toda aquela, como vocês dizem, "Merda da Boa".',--Get to the control room - the black heart of the facility. From there, you can open the vaults and grab all that, as you say, 'good shit'.
	loc_jr1_37_01 = "Yoohoooooo! Mandem as bolsas aqui pra cima, meus amigos!",--Yoohoooooo! Send the bags up here, my friends!
	loc_jr1_71_02 = "Mais um cofre aberto e pronto.",--That's another vault open and ready. 
	loc_jr1_31_01 = "Essa é a primeira bolsa de espólio bom pra caralho! Excelente! Agora, vocês vão encontrar um grande eixo vertical por perto. Mandem os espólios por cabos. Eu vou cuidar disso.",--That is the first of some fucking sweet loot! Excellent! Now, you will find a large vertical shaft nearby. Send loot up it by cable. I will look after it.
	loc_jr1_35_03 = "É feito de metal e plástico, mas esse servidor tem segredos que fariam a caixa de pandora parecer uma caixa de brinquedos de criança.",--It's made of metal and plastic, but this server has secrets that makes Pandora's Box look like a fucking kiddies toy-chest.
	loc_jr1_38_03 = "Um, dois, feijão com arroz. Sim, parece que todas as bolsas estão presentes. Agora, por favor, se prendam aos cabos e juntem-se a mim.",--One, two, buckle my shoe. Yes, it would seem all of the bags are present. Now, please, attach your good selves to the cables and join me.
	loc_jr1_42_01 = "Por aqui, por favor.",--Over here, please.
	loc_jr1_67_03 = "É fácil. Apenas escolham um cofre, e pressionem o botão. Isso vai iniciar uma trava de tempo, e o cofre irá abrir. Abracadabra!",--It's easy. Just choose a vault, and press the button. That will start the timelock, and the vault will open. Abracadabra!
	loc_jr1_05_03 = "Os itens, amigos. Coletar eles é uma chatice, eu sei, mas é necessário para concluir essa operação.",--The items, friends. Collecting them is a bother, I know, but necessary to this operation.
	loc_jr1_59_04 = "Amigos, deixem a trava de tempo acabar, yeah? Sua paciência irá ser bem recompensada. ",--Friends, let the timelock go tick-tock, yeah? Your patience will be rewarded.
	loc_jr1_57_17 = "Ele era um carinha risonho, em todo caso.",--He was a bakvissie anyway.
	loc_jr1_04_02 = "Eu deixei para vocês um cartão de acesso, um cortador de arco e algumas cargas explosivas, meus amigos. Eu poderia apertar um botão e abrir a porta mas devemos manter meu envolvimento em segredo, sim.",--I've left you a keycard, an arc cutter and some breaching charges, my friends. I could press a button and open a door, but we must hide my involvement, yes.
	loc_jr1_57_15 = "Porque ele estava aí? Ele é o cozinheiro!",--Why was he there? He's the cook!
	loc_jr1_13_03 = "Só mais um pouquinho...",--Just a little longer...
	loc_jr1_06_01 = "Bom. Agora, larguem as cargas na frente da porta principal bem ali.",--Good. Now, drop the charges at the main door over there.
	loc_jr1_39_02 = "Sim, tudo certo, todos vocês presos nos cabos, por favor.",--Yes, that's right, all of you up the shaft, please.
	loc_jr1_27_03 = "Vocês veem a sala de controle lá em cima?",--You see the control room up there?
	loc_jr1_06_03 = "Excelente. Agora, se vocês forem gentis de largarem as cargas perto da porta.",--Excellent. Now if you would be so kind as to deposit the charges near the door.
	loc_jr1_11_01 = 'Por algum acaso as palavras "Conecte o detonador nas cargas" soam um sino?',--Do the words "rig the detonator to the charges" ring a bell?
	loc_jr1_61_02 = "É isso. Bem-feito! O cofre está se abrindo de novo!",--That's it. Well done! The vault is opening again!
	loc_jr1_19_03 = "Legal legal. Agora, segundamente deve haver uma estação de segurança por perto. Vão para lá e aprovem a abertura.",--Kwaai kwaai. Now secondly there should be a security station nearby. Head there and approve the opening.
	loc_jr1_02_02 = "Aos negócios! Tem algumas caixas perto da entrada. Elas têm umas pequenas listras vermelhas. Encontrem elas. Tem alguns presentinhos para vocês nelas.",--To business! There are crates near the entrance. Got a little red strobe on. Find them. They have a few little presents within.
	loc_jr1_57_21 = "Que retardado. Ele é melhor morto mesmo.",--What a mompie. He's better dead.
	loc_jr1_57_23 = "Não se sintam mal. Ele era um cara ruim, com certeza.",--Don't feel bad. He was a bad man, for sure.
	loc_jr1_48_01 = "Usem a C4 e mandem esses radares para o ares, meus amigos!",--Use the C4 to send those radars tumbling, my friends!
	loc_jr1_48_03 = "Lembrem-se, vocês devem aplicar o C4 em cada um dos radares.",--Remember, you must apply the C4 to each of those radars.
	loc_jr1_54_03 = "Eles estão mandando tudo pra cima da gente. Segurem eles, meus amigos. Eles irão matar vocês, mas vão me fuder junto. Com certeza.",--They're throwing everything into this. Hold them off, my friends. They'll kill you, but they'll fuck me proper. For sure.
	loc_jr1_30_02 = "Ótimo. Essas bolsas vão satisfazer nosso acordo... entretanto, se vocês quiserem continuar... Eu estou apenas dizendo... hmmm?",--Great. That loot will satisfy our arrangement... however, if you wanted to carry on... I am just saying... hmmmm?
	loc_jr1_31_03 = "A primeira bolsa! Belissimo! Agora, perto dos cofres vocês irão encontrar um grande eixo vertical com cabos. Prendam as bolsas nos cabos e elas serão enviadas até mim.",--The first bag! Bellissimo! Now, close to the vaults you will find a tall vertical shaft with cables. Attach the bags to the cables, and they will be lifted to me.
	loc_jr1_10_01 = "Excelente. Agora, coloquem um detonador lá também.",--Excellent. Now, let's just get a detonator on there too.
	loc_jr1_06_02 = "Esplêndido! Agora, larguem as cargas perto da porta principal.",--Superb! Now, just drop the charges near the main door.
	loc_jr1_18_01 = "Lembrem-se - O cartão de acesso vai na trava ali, Não é nenhuma ciência de foguetes.",--Remember - the keycard on the lock there? Not fucking rocket science.
	loc_jr1_30_01 = "Certo, meus queridos amigos. Isso é o suficiente para fazer essa operação ter valido a pena. Vocês decidem se querem continuar ou ir embora. Cada dólar extra fortalece nossa amizade, com certeza.",--All right, my dear friends. That's enough loot to make this op worthwhile. You decide if you want to keep going. Every extra dollar, rand and rouble strengthens our friendship, yeah? For sure.
	loc_jr1_55_01 = "Certo, o tanque está cheio, As hélices estão girando e a carga está segura. Hora de sair daqui. Cavalheiros, por favor juntem-se a mim e estejam a bordo.",--Right, the fuel tank is full, the blades are spinning and the cargo is secure. Time to get out of here. Gentlemen, please join me aboard!
	loc_jr1_21_03 = "E... Abra-te sésamo! Bravo, meus amigos! Agora, por favor, vão para a porra da trava de ar.",--And..open the sesame! Bravo, my friends! Now, please, get in the fucking airlock. 
	loc_jr1_56_02 = "O fim está próximo. E é uma belo fim! Por favor, dentro do helicóptero!",--The end is upon us. And it is a good ending! Please, into the helicopter!
	loc_jr1_28_01 = "Vocês podem abrir apenas um cofre de cada vez, E eu devo avisar que não são todos cofres que tem algo dentro. Como descobrir os cofres certos eu deixarei para vocês esse problema.",--You can only open one vault at a time, and I should make you aware that not all vaults contain loot. How you figure out which to open is your problem.
	loc_jr1_61_01 = "Ah! Sim. O cofre está abrindo de novo! Bom!",--Ah! Yes. The vault is opening again! Good!
	loc_jr1_57_03 = "Obrigado. Eu odiava aquele cara. Só roubava meu shampoo.",--Thanks. I hated that poes. Kept stealing my shampoo.
	loc_jr1_34_02 = "Talvez eu devia ter estudado mais sobre essas coisas anciãs. Poderia a maldição ser verdadeira? Ah, é apenas uma merda antiga que vale uma baita grana pra mim.",--Maybe I should've studied this ancient stuff more. Could the curse be true? Ah, it's just old shit worth money to me.
	loc_jr1_15_03 = "Eu senti essa daqui! Agora, para dentro, continuem lutando.",--I felt that one here! Now, inside, keep fighting. 
	loc_jr1_58_03 = "Façam esses desgraçados crentes.",--Make these guys believers.
	loc_jr1_60_02 = "Bem, que merda. Os policiais pararam a abertura do cofre. Façam voltar a funcionar, E matem qualquer kerel que chegar perto dos controles denovo!",--Well, fuck and shit. Cops shut down the vault's opening. Get it going again, and kill any fucking kerel that goes near it.
	loc_jr1_32_03 = "Bravo, meus amigos! Agora, para prosseguir, por favor prendam as bolsas aos cabos no grande eixo vertical. Eu estou no topo e irei recebê-las em segurança.",--Bravo, my friends! Now, to proceed, please attach the bags to the cables in the large vertical shaft. I am at the top, and will receive them safely.
	loc_jr1_64_02 = "Resposta padrão é ter uma forte linha de soldados lá, Então esperem por Bulldozers à frente. Preparem-se!",--Standard response is to get a strong line of armor in there, so expect bulldozers up ahead. Get ready!
	loc_jr1_02_03 = "Eu consegui arranjar algumas ferramentas necessárias para este trabalho. Encontrem elas nas caixas. Elas tem uma marca vermelha nelas.",--I've managed to organise some necessary tools for this job. Find them in the crates. They got a little strobe on them.
	loc_jr1_57_10 = "Ele era um cara entediante. Obrigado.",--He was a boring poe. Thank you.
	loc_jr1_52_01 = "Droga, e merda. A equipe de voo são desleixados pra caralho! O helicóptero está sem gasolina. Ei, vocês podem conectar a mangueira no helicóptero?",--Damn, and shit. The aircrew are sloppy as kak. Helicopter ain't got no fuel. Hey, can you hook up the fuel line?
	loc_jr1_57_16 = "Esse era o nosso padre. Vocês são frios como uma pedra.",--That was our chaplain. You guys are stone cold.
	loc_jr1_39_01 = "Venham, cavalheiros! Não sejam tímidos! Entrem e digam olá.",--Come on, gentlemen! Don't be shy! Come and say hello.
	loc_jr1_57_22 = "Aquele merda venderia sua própria mãe por um dólar.",--That kak woulda sold his mother for a dollar.
	loc_jr1_57_02 = "Eu gostava daquele cara. Nós iremos mandar uma quantia para sua esposa. Yeah, com certeza.",--I liked that guy. We'll send his wife a ham. Yeah, for sure.
	loc_jr1_65_03 = "De todos os cofres, vocês abriram logo um vazio! Tentem de novo, amigos.",--Of all the vaults, you had to open an empty one! Try again, friends.
	loc_jr1_36_02 = "Nós roubamos isso de um laboratório faz algumas milhas daqui. Duzentas e trinta e oito mil, seiscentas e seis milhas, para ser mais exato.",--We stole this from a lab not a million miles from here. Two hundred thirty eight thousand six hundred and six miles, to be precise.
	loc_jr1_26_02 = "Agora. Olhando de cima vocês vão encontrar a sala de controle. É de lá que os cofres dessa instalação são controlados. Seria bem útil ir pra lá, yeah?",--Now. Overlooking this area you will find the control room. From there the vaults in this part of the facility are controlled. That would be useful, yes?
	loc_jr1_08_03 = "Essas cargas devem estar grudadas nas quatro travas. Eu tenho certeza de que vocês não precisam de um passo-a-passo pra fazer isso.",--Those charges must be hooked up to the four locks. I am sure you don't need walking through the procedure.
	loc_jr1_57_04 = "Eu ja vi ele tomar um tiro antes. Embora da última vez ele tenha durado um pouco mais.",--I've seen him take a bullet before. Thought he'd last longer.
	loc_jr1_38_01 = "E... Sim, Essa é uma relação de negócios muito satisfatória! Todas as bolsas! Agora, por favor, se prendam aos cabos e subam aqui para nos encontrarmos pessoalmente!",--And... yes, that is a satisfactory piece of business! All of the bags! Now, please, attach yourselves to the cables, join me up here and let us meet in person!
	loc_jr1_64_01 = "Acabei de ouvir que eles tem um esquadrão de Bulldozers na área logo em frente. Eles vão fuder com nosso rabo. E eu não quero isso. Tomem cuidado!",--Just heard they've got a squad of bulldozers up in the area ahead. They'll fuck us in the ass. I don't want that. Watch it!
	loc_jr1_43_02 = "Quando vocês estiverem do lado de fora irão ver um helicóptero, assim como irão ver uma grande escala de equipamentos avançados de radar. Estado da arte. Eles poderiam nos rastrear a qualquer lugar que fossemos.",--Once we are outside you will see our escape helicopter, as well as a large array of advanced radar equipment. State of the art. It could track us anywhere west of the Rockies.
	loc_jr1_65_01 = "Bem, Que merda, Isso foi uma perca de tempo. O cofre está vazio. Encontrem os bem cheios, escutaram?",--Well, fuck me, that was a waste of time. The vault is empty. Find the good ones, you hear?!
	loc_jr1_63_02 = "Protocolo significa que eles tem Snipers prontos para uma emboscada logo à frente. Se cuidem, yeah?",--Protocol means they'll have snipers ready to ambush up ahead. You fellas watch yourselves, yeah?
	loc_jr1_50_03 = "Agora, por favor! Tragam as bolsas para o helicóptero.",--Now, please, bring the loot bags to the helicopter.
	loc_jr1_57_08 = "Ahhh, ele era meu amigo. Bem, o que se pode fazer?",--Ahhh, he was my friend. Well, what can you do?
	loc_jr1_13_01 = "Quase... lá...",--Almost... there.
	loc_jr1_12_02 = "O detonador está na contagem regressiva. Mantenham os kerels longe dele. Vocês não precisam deles cortando os cabos, com certeza.",--Detonator is counting down. Keep the kerels away from it. Don't need them cutting it, for sure.
	loc_jr1_59_06 = "Cofres levam apenas um momento para abrir. Um procedimento de segurança. Segurança é importante, sabiam?",--Vaults take just a moment to open. A security measure. Security is important, you know.
	loc_jr1_20_01 = "A estação de segurança local, queridos amigos. Essa é a nossa próxima parada.",--The local security station, dear friends. That's your next stop.
	loc_jr1_05_02 = "Nós só podemos prosseguir qunado vocês adquirirem os itens, meus amigos.",--We can only proceed once you have acquired those items, my friends.
	loc_jr1_58_08 = "Ei, vocês não estariam interessados em um pequeno trabalho mercenário, né? não?",--Hey, you wouldn't be interested in a little mercenary work, eh? No?
	loc_jr1_34_01 = "Seja lá o que for essa merda. Dizem que ela tem um maldição. Faz seu nariz ficar parecendo um pau. Então, porque as pessoas pagariam toneladas de dinheiro por isso? eu não sei.",--Fuck knows what that thing is. They say it has a curse. Makes your nose look like a dick. So why people pay craploads for it, I don't know.
	loc_jr1_07_03 = "Por favor, deixem as cargas perto da porta, meus amigos.",--Please, leave the charges at the door, my friends.
	loc_jr1_03_03 = "As caixas, cavalheiros? Com as marcas?",--The crates, gentlemen? With the strobes?
	loc_jr1_47_02 = "Apres vous!",--Apres vous!
	loc_jr1_22_02 = "Tenham certeza de estarem dentro da trava de ar. A porta exterior não pode fechar até que todos estejam dentro.",--Make sure your gang are safely gathered in the airlock. The outer door cannot close until this is so.
	loc_jr1_49_01 = "Excelente. Eles são cegos! Cegos como morcegos. Apesar de que morcegos supostamente são cegos e localizam a presa por ecolocalização, então...",--Excellent. They are blind! Blind as a bat. Though bats are supposed to be blind, and locate prey by echolocation, so that is...
	loc_jr1_44_03 = "Por favor, destruam os radares. Ceguem eles, para ser mais preciso.",--Please, destroy the radars. Stab their fucking eyes out, so to speak.
	loc_jr1_01_02 = "Amigos! Bem-vindos ao Black Ridge. Super secreto! O que eu posso contar para vocês é que tem muitos e muitos espólios aqui. Bem valiosos.",--Friends! Welcome to Black Ridge. Top secret! What I can tell you is that there is loot here. Very valuable loot. 
	loc_jr1_28_03 = "Apenas um cofre pode ser aberto por vez, E apenas certos cofres contém espólios. Como isso é determinado eu deixo para vocês, já que eu confio em suas habilidades.",--Only one vault can be opened at a time. Further, only certain vaults have loot within them. How that is determined is up to you, but I have confidence in your ability.
	loc_jr1_25_02 = "O complexo interno não é nada que deva ser temido.",--The inner complex is nothing to be scared of. 
	loc_jr1_52_02 = "Merda! Algum bastardo desleixado esqueceu de reabastecer o helicóptero. Poderiam engatar a mangueira no tanque de combustível?",--Kak! Some sloppy bastard forgot to refuel the chopper. Hook up the fuel, would you?
	loc_jr1_29_01 = "Sim, eu acredito que ouvi um cofre abrindo. Excelente! Continuem assim, cavalheiros!",--Yes, I do believe I hear a vault opening. Excellent! Keep at it, gentlemen!
	loc_jr1_23_01 = "Vai levar apenas um tempinho, cavalheiros. Talvez usem esse tempo para reabastecer suas munições.",--It will just take a moment, gentlemen. Perhaps use the time to assess your current situation re ammo.
	loc_jr1_65_02 = "Bem, macacos me mordam - Cofre vazio! Abram apenas os bons, yeah? com certeza.",--Well, I'll be a donkeys uncle - empty fucking vault! Only open the good ones, yeah? For sure.
	loc_jr1_64_03 = "Se eu conheço eles, e eu conheço, acreditem nisso, eles vão ter Bulldozers logo à frente. Então se preparem pra esses merdas, yeah?",--If I know them, and I know them, trust me on that, they'll have bulldozers up ahead. So get ready for those shits, yeah.
	loc_jr1_36_01 = "Eu não vou dizer para vocês o que é isso, porque vocês iriam cagar nas calças. Apenas não pressionem nenhum botão.",--I won't tell you what this is, 'cos you'll fucking shit your undies. Just don't press any buttons.
	loc_jr1_46_01 = "Não se esqueçam. Eliminem os radares. Eu vou preparar o helicóptero.",--Do not forget. Take out those radars. I'll get the chopper ready.
	loc_jr1_08_01 = "Ok, ótimo! Agora, por favor coloquem as cargas nas quatro travas que vocês veem ali.",--Okay, good! Now, please to place the charges onto the four locks you see there.
	loc_jr1_09_03 = "Por favor, lembrem-se da porra de seus trabalhos! As cargas devem estar conectadas nas quatro travas.",--Please remember your fucking jobs - the breaching charges need to be attached to all four locks.
	loc_jr1_14_03 = "Ei, gente, Esses kerels estão fudendo o rabo de vocês. Fodam eles de volta, só que com mais força. E consertem a porra do detonador!",--Hey man, the kerel poes are fucking you in the ass. Fuck 'em back, harder. And fix the fucking detonator!
	loc_jr1_18_02 = "Tem como um de vocês, quando o tempo permitir, passar o cartão de acesso na trava?",--Can one of you please, when time permits, swipe the keycard in the lock?
	loc_jr1_27_01 = "A sala de controle fica lá em cima. Vocês conseguem ver?",--The control room is up there. You see?
	loc_jr1_45_01 = "Eu tenho algumas C4 para o trabalho bem aqui.",--I've got some C4 for the job right here.
	loc_jr1_46_02 = "Então. Eu irei preparar o helicóptero. Vocês lidam com os radares. Concordam?",--So. I will prepare the helicopter. You will deal with the radar dishes. Agreed?
	loc_jr1_48_02 = "Isso mesmo. C4 para cada um desses radares.",--That's right. C4 each of those dishes.
	loc_jr1_55_03 = "Bravo! Nós estamos de tanque cheio e prontos para partir. Por favor, façam seu caminho a bordo e vamos dar o fora daqui. Esse foi um ótimo dia.",--Ah, bravo! We're fueled and ready to go. Please, make your way aboard and let us get out of here. This was a fine day.
	loc_jr1_57_01 = "Aquele puto me devia 20 dólares. Ah, bem.",--Ah! That fucker owed me $20. Ah well.
	loc_jr1_57_18 = "Na mosca, yeah!",--Right in the bradley, yeah.
	loc_jr1_68_03 = "Isso foi divertido!",--That was fun!
	pln_jr1_01_01 = "Deem a eles a autorização, gangue.",--Give 'em the authorization, gang.
	pln_jr1_03_01 = "Prendam as cargas na porta, pessoal.",--Ditch the charges at the door, guys.
	pln_jr1_07_03 = "Ai está ele. Locke.",--There he is. Locke.
	pln_jr1_09_01 = "Ótimo trabalho, grupo. O Locke já separou a nossa parte. Ainda não tenho certeza sobre esse cara mas talvez possamos confiar nele.",--Great job, crew. Locke's already wired our cut. Still not sure about this guy, but maybe we can trust him.
	pln_jr1_09_02 = "Isso foi intenso, gente. O Locke já nos enviou nossa parte. Ainda tenho dúvidas sobre ele mas vamos ver como as coisas vão.",--That was intense, gang. Locke already sent over our share. Still uneasy about him, but let's see where things go with this guy.
	pln_jr1_08_03 = "Colocar esses radares fora de ação é o nosso próximo trabalho, gangue. Façam isso.",--Putting those radars out of action is our next job, gang. Do it.
	pln_jr1_02_02 = "Ei, pessoal, Lembrem-se de encontrar as caixas que o Locke deixou. Elas tem uma marca vermelha nelas.",--Hey guys, remember to find the crates Locke has left. They got a strobe on.
	pln_jr1_04_01 = "Melhor fazer o que ele diz.",--Better do what he says.
	pln_jr1_01_02 = "Mostrem pra eles, gangue.",--Show 'em, gang
	pln_jr1_08_02 = "Locke quer que nós sabotemos os radares. Melhor fazermos isso.",--Locke wants us to sabotage the radars. Better get to it.
	pln_jr1_05_03 = "Pessoal, procurem a sala de segurança. Usem o cortador de arco para entrar, E aprovem a sequência.",--Guys, look for a security room around there. Use the arc welder to cut through, and approve the sequence.
	pln_jr1_06_03 = "Vocês ouviram eles. Prendam as bolsas na tirolesa que tem no eixo. Levem elas lá pra cima até o Locke.",--You heard him. Get the bags onto the ziplines in the shaft. Get them up to Locke.
	pln_jr1_03_02 = "Locke quer que nós explodamos aquela porta. Melhor largar as cargas perto dela.",--Locke wants us to blow that door. Better drop the charges off there.
	pln_jr1_07_02 = "Então esse é o Locke.",--So that's Locke.
	pln_jr1_01_03 = "Deixe-os tê-lo, gangue!",--Let em have it, gang!
	pln_jr1_02_01 = "Encontrem as caixas do Locke, gangue. Procurem pelas caixas com uma marca nelas.",--Find Locke's crates, gang. Look for the ones with the strobe on.
	pln_jr1_02_03 = "Vamos lá, grupo. Locke precisa que nós achemos aquelas caixas. Mostrem pra ele como nós fazemos.",--Come on, crew. Locke needs us to find those crates. Show him how we do it.
	pln_jr1_03_03 = "É melhor seguirmos as instruções do Locke nesse trabalho. Coloquem as cargas perto da porta.",--We better follow Locke's directions on this one. Take the charges to the door.
	pln_jr1_04_02 = "Soa um pouco desequilibrado. Melhor fazer.",--Sounds a little unhinged. Best do it.
	pln_jr1_04_03 = "Locke parece um pouco... chateado. Melhor fazermos o que ele está dizendo.",--Locke sounds a bit...mad. We'd better do what he says.
	pln_jr1_05_01 = "Deve haver uma sala de segurança por perto. Usem o cortador de arco para entrar e dar o sinal verde para a trava de ar.",--There should be a security room close by. Use the arc welder to cut through and green llight the airlock.
	pln_jr1_05_02 = "Locke quer que nós cortemos nosso caminho até a sala de segurança. Encontrem-na, gente, e aprovem a sequência.",--Locke wants us to cut through to the security room. Find it, gang, then approve the sequence
	pln_jr1_06_01 = "Levem as bolsas para o Locke assim que puderem, Procurem pelo eixo vertical aí por perto.",--Get the bags up to Locke as soon as you can, crew. Look for the large vertical shaft around there.
	pln_jr1_06_02 = "Encontrem o eixo e enviem as bolsas pro Locke assim que possível.",--Find the shaft and zipline those bags up to Locke ASAP.
	pln_jr1_07_01 = "É ele. Locke.",--That's him. Locke.
	pln_jr1_08_01 = "O plano de fuga do Locke depende de nós explodirmos aqueles radares, gangue. Cuidem disso.",--Locke's escape plan depends on blasting the radars, gang. See to it.
	pln_jr1_09_03 = "Muito bom, pessoal. Locke transferiu nossa parte. Eu não sei nada sobre esse cara mas vamos ver como as coisas vão acontecer com ele.",--Nicely done, guys. Locke transferred our cut. I don't know about this guy, yet, but let's see how things pan out with him.
	
	-- Objetivos
	hud_heist_jerry01_04_hl = "Acione o Detonador",--Rig the detonator
	hud_heist_jerry01_06 = "Entre na Black Ridge e vá até o complexo interno.",--Get inside Black Ridge and fight your way to the inner complex.
	hud_heist_jerry01_10 = "Entre na trava de ar. Ela leva direto para o complexo interno.",--Step inside the airlock. It leads to the inner complex.
	hud_heist_jerry01_vault_loop_002_hl = "Encontre espólios destrancando os Cofres",--Find loot by unlocking vaults
	hud_heist_jerry01_07_hl = "Use o Cartão de Acesso",--Use the keycard
	hud_heist_jerry01_17 = "Junte-se com Locke perto da saída.",--Join with Locke near the surface exit.
	hud_heist_jerry01_22_hl = "Fuga Disponivel!",--Escape available!
	hud_heist_jerry01_06_hl = "Chegue no Complexo Interno",--Reach the inner complex
	hud_heist_jerry01_01_hl = "Colete o Equipamento",--Collect the stashed equipment
	hud_heist_jerry01_19_hl = "Leve os espólios para o Helicóptero",--Get the vault loot to the helicopter
	hud_heist_jerry01_17_hl = "Reuna-se na Saída",--Gather at the surface exit
	hud_heist_jerry01_16 = "Use a tirolesa no elevador para chegar à superficie. Você também pode ficar para pegar mais espólios, caso tenha algum.",--Use ziplines in the elevator shaft to reach the surface. You can also stay and find more loot.
	hud_heist_jerry01_07 = "Use o cartão de acesso dado por Locke para iniciar o destravamento da trava de ar.",--Use the keycard provided by Locke to initiate the airlock opening sequence.
	hud_heist_jerry01_11_hl = "Juntem-se dentro",--Gather everyone inside
	hud_heist_jerry01_05restart = "Re-acione o detonador desativado.",--Re-arm the disabled detonator.
	hud_heist_jerry01_03_hl = "Plante as Cargas Explosivas",--Plant the breaching charges
	hud_heist_jerry01_vault_loop_001 = "Use o painel de controle para selecionar um cofre para abrir.",--Use the control panel to select a vault to unlock first.
	hud_heist_jerry01_05restart_hl = "Rearme o Detonador",--Re-arm the detonator
	hud_heist_jerry01_00 = "Locke deixou equipamento vital em três caixas. As caixas estão marcadas em vermelho.",--Locke has supplied vital equipment in three crates. The crates are marked with a strobe light.
	hud_heist_jerry01_15 = "Prenda a bolsa de espólios na tirolesa do elevador. o Locke vai manter elas seguras.",--Attach a bag of loot to the zipline in the elevator shaft. Locke will keep it safe.
	hud_heist_jerry01_19 = "Guarde os espólios no helicóptero.",--Secure the vault loot in the helicopter.
	hud_heist_jerry01_22 = "Entre no helicóptero e se prepare para fugir!",--Get in the helicopter and prepare for take off!
	hud_heist_jerry01_03 = "Plante as cargas explosivas na porta de entrada da Black Ridge.",--Plant the breaching charges on Black Ridge's blast door.
	hud_heist_jerry01_08 = "Entre na estação de segurança e aprove a sequência de abertura da porta.",--Get into the local security station and approve the door opening sequence.
	hud_heist_jerry01_02_hl = "Largue as Cargas Explosivas",--Drop off the breaching charges
	hud_heist_jerry01_18_hl = "Destrua os Radares e Equipamentos de Comunicação",--Destroy radars and communication equipment
	hud_heist_jerry01_vault_loop_001_hl = "Selecione um Cofre para abrir",--Select a vault to open first
	hud_heist_jerry01_08_hl = "Aprove a Sequência de Abertura",--Approve the opening sequence
	hud_heist_jerry01_15_hl = "Mande os espólios para cima",--Send up the loot
	hud_heist_jerry01_02 = "A Black Ridge é protegida por portas pesadas. Largue as cargas explosivas perto da porta.",--Black Ridge is protected by heavy blast doors. Drop off the breaching charges at the doors.
	hud_heist_jerry01_12_hl = "Chegue na Sala de Controle",--Reach the control room
	hud_heist_jerry01_20 = "Use o equipamento de abastecimento para reabastecer o helicóptero.",--Use the refueling equipment to refuel the helicopter.
	hud_heist_jerry01_18 = "Previna sua fuga de ser rastreada usando o C4 para destruir os radares e comunicações da Murkywater.",--Prevent your escape being tracked by using C4 to destroy Murkywater's radar and communication equipment.
	hud_heist_jerry01_20_hl = "Reabasteça o Helicóptero",--Refuel the helicopter
	hud_heist_jerry01_00_hl = "Encontre as Caixas Marcadas",--Find the marked crates
	hud_heist_jerry01_11 = "Reuna o grupo todo dentro da trava de ar. Ela precisa fechar para a porta de dentro abrir.",--Get the whole crew into the airlock. It needs to close before the inner door opens.
	hud_heist_jerry01_05 = "O detonador é vulnerável à interferência. Previna os policiais de desativá-lo.",--The detonator is vulnerable to interference. Prevent law enforcement from disabling it.
	hud_heist_jerry01_10_hl = "Entre na Trava de Ar",--Enter the airlock
	hud_heist_jerry01_00_first = "Vá até a entrada da instalação da Black Ridge.",--Push forward and reach the entrance of the Black Ridge facility.
	hud_heist_jerry01_00_first_hl = "Vá para a instalação da Black Ridge",--Get to the Black Ridge facility
	hud_heist_jerry01_01 = "Pegue o equipamento das caixas marcadas.",--Gather the equipment from the marked crates.
	hud_heist_jerry01_04 = "Coloque o detonador das cargas explosivas e acione-o.",--Rig the detonator to the breaching charges and arm it.
	hud_heist_jerry01_05_hl = "Defenda o Detonador",--Defend the detonator
	hud_heist_jerry01_12 = "Vá até a sala de controle.",--Fight your way to the overhead control room.
	hud_heist_jerry01_16_hl = "Escape para a Superfície",--Escape to the surface
	hud_heist_jerry01_vault_loop_002 = "Continue usando o painel de controle para destravar os cofres e encontrar espólios.",--Continue using the control panel to unlock vaults and find loot.
		}