return {
	-- Descrições
	heist_pbr2_briefing = "Certo, o plano é esse. O Locke irá contrabandear vocês no avião. Esperem o sinal dele e invadam. A Resistência deverá ser leve - apenas a tripulação. O dinheiro está embalado em grandes cargas. Tirem eles pelo portão de carga, e nós iremos coletá-los quando eles cairem no chão. Simples.",--Okay, here's the plan. Locke is going to have you smuggled onto the plane. Wait until you get his signal and burst out. Resistance should be light - just the crew. The money is packed into large pallets. Get them out of the cargo doors, and we'll collect them when they hit the ground. Simple.
	heist_pbr2_crimenet = "O alvo é um avião de transporte da Murkywater. Ele está carregando cargas de dinheiro. Vocês serão contrabandeados a bordo. Derrubem a carga do avião e o recuperem.\n\n» Saia do Compartimento de Carga \n» Abra o Portão de Carga e solte as Cargas de Dinheiro\n» Salte de Paraquedas para a Superfície\n» Recupere as Cargas de Dinheiro na Cidade e Sinalize ao Locke\n» Desça nos Esgotos e Fuja",--The target is a Murkywater transport plane. It is carrying pallets of currency. You will be smuggled aboard. Drop the money from the plane and recover it.\n\n» Emerge into the cargo compartment\n» Open the cargo doors and release the money pallets\n» Skydive to the surface\n» Recover the money pallets in the town and signal Locke\n» Descend into the sewers and escape
	
	-- Legendas
	pln_jr2_01_02 = "Vamos lá, gangue. Saiam desse esconderijo!",--Come on, gang. Out of that hidey-hole!
	loc_jr2_41_01 = "Escutem aqui seus zé bucetas. Vocês só irão chegar no telhado usando a escada do depósito, e vocês só irão entrar lá com o cartão de acesso. Procurem por ele!",--Listen you fucking poes. You're only getting on the roof from the store room ladder, and you're only getting in that with the keycard. Look for it!
	loc_jr2_39_03 = "Uma das cargas está no telhado da lanchonete. O que esses fritadores de hambúrguer fariam com tanto dinheiro, yeah? ",--One of the pallets is on the roof of the diner. What would those burger-flippers do to have that kind of cash, eh? 
	loc_jr2_18_02 = "Vocês poderiam achar esses malditos pacotes? A análise da trajetória indica... que eles devem estar perto, porra!",--Find those fucking bundles, will you? Analysis of trajectory indicates...they must be fucking close!
	loc_jr2_40_01 = "Tem uma escada de serviço que leva ao telhado. Apesar de que vocês irão precisar de um cartão de acesso para isso. Deve ter um por aí em algum lugar.",--There's a service ladder leading to the roof. You'll need a keycard to access it though. Got to be one here somewhere.
	pln_jr2_03_02 = "Gangue, apressem-se com os paraquedas. Não saiam do caminho.",--Gang, hurry with the parachutes. Don't get off course.
	pln_jr2_03_03 = "Pessoal, peguem os paraquedas, rápido! Não vão muito longe do dinheiro!",--Guys, get the parachutes, quickly! Don't get too far from the money!
	loc_jr2_06_03 = "Boa. Os controles do oficial de logística estão na sua frente. Operem eles. Façam o dinheiro voar.",--Good. The logisitic officers' controls are right in front of you. Operate them. Let the money go.
	pln_jr2_02_03 = "Gangue, vocês precisam chegar na frente do avião. Depois subir as escadas, e voltar para os fundos. Único jeito de chegar aos controles.",--You need to make your way to the front of the plane, gang. Then up the stairs, and all the way back. Only way to get to the controls.
	loc_jr2_08_03 = "Então, o dinheiro está tendo uma queda, por vocês. Boa. Agora, peguem uns paraquedas e juntem-se a eles. Vamos lá, meus pequenos anjos.",--So, the money is falling, for you. Good. Now, grab yourselves some parachutes and join it. Come on, my little angels.
	loc_jr2_25_02 = "Hey! Não esqueçam de prender o dinheiro no helicóptero!",--Hey! Don't forget to strap the fucking money to the chopper!
	loc_jr2_11_01 = "A primeira carga acertou o chão em algum lugar por aqui. Achem-no, marquem sua posição e irei coletá-lo.",--The first pallet hit the ground around here somewhere. Find it, mark the position and I'll come and collect it.
	loc_jr2_27_01 = "Irei encontrá-los fora da cidade. A melhor maneira de despistar esses policiais são os esgotos. Desçam lá. Eu arranjei uma coisinha.",--I'm going to meet you just outside town. Best way for you to shake these kerel is the sewers. Get down there. I've arranged a little something.
	loc_jr2_39_01 = "Parece que uma das cargas caiu no telhado da lanchonete. Imaginem todo aquele dinheiro caindo nos seus ovos e grãos, yeah!? Com certeza.",--It looks like one of the pallets landed on the roof of the diner. Imagine all that money falling in your eggs and grits, eh! For sure.
	loc_jr2_42_01 = "Ah! Esses bucetas comedores de merda estão roubando meu dinheiro. Perdão... nosso dinheiro. Parem eles!",--Ah! Those fucking shit-eating poes are stealing my money. Our money...sorry. Stop them!
	pln_jr2_07_01 = "Gangue, subam no barco! Nós estamos quase terminando!",--Get into the boat, gang! We're almost done here!
	pln_jr2_02_02 = "Apenas abram caminho até a frente do avião, subam as escadas e voltem. É o único jeito de chegar naqueles controles.",--Just fight to the front of the plane, up the stairs and then all the way back. It's the only way to reach those controls.
	loc_jr2_05_01 = "Bom. Ah, ar fresco! Agora, as cargas estão presos ao convés por fixadores mecânicos. Esses fixadores são controlados pelo oficial de logística, e seus controles estão... ah, lá em cima. E o acesso ao convés superior é pela frente do avião.",--Good. Ah, fresh air! Now, the pallets are secured to the deck by mechanical fasteners. These fasteners are controlled by the logistics officer, and his controls are... ah, up there. And the access to the upper deck is at the front of the plane. 
	pln_jr2_07_02 = "Equipe, não fiquem parados. Todos - subam no barco!",--Don't hang around, crew. Everyone - into the boat!
	loc_jr2_26_01 = "Ah merda - aqueles bucetas estão trazendo mais turrets da SWAT, com o propósito de me derrubar. Beleza, não vou conseguir pegá-los na cidade, mas estava preparado para isso.",--Ah kak - those poes are bringing in more SWAT turrets, with the express purpose of bringing me down. All right, I can't pick you up in town, but I am prepared for this.
	loc_jr2_15_01 = "E esse é o segundo. Oh, eu posso sentir o cheiro da riqueza! Mas ganância é bom, não é. Com certeza. Achem a terceira carga.",--And that's the second. Oh, I can smell the wealth! But greed is good, yeah. For sure. Find the third pallet.
	loc_jr2_38_02 = "Deixe-me lembrá-los - procurem por uma escada.",--Let me remind you - look for a ladder. 
	loc_jr2_44_01 = "Outra aquisição bem sucedida! Bem feito, meus amigos!",--Another successful acquisition! Well done, my friends!
	loc_jr2_44_02 = "Outra colaboração bem-sucedida! Vocês tem minha gratidão, minha admiração e, mais importante, sua parte do dinheiro.",--Yet another successful collaboration! You have my thanks, my admiration and, most importantly, your share of the money.
	pln_jr2_intro_01_01 = "Certo gangue... conectando Locke a vocês.",--Okay gang...patching Locke through to you.
	loc_jr2_33_02 = "Aquele barco precisa de pessoas dentro dele. Vocês. Façam o que o barco precisa, yeah?",--That boat needs people inside it. You people. Do what the boat needs, yeah?
	pln_jr2_04_03 = "Lembrem-se, gangue - Locke precisa que vocês acendam aquele sinalizador.",--Crew, remember - Locke needs you to light that flare.
	loc_jr2_45_03 = "Isso aí. Isso aí! Vamos lá, estão quase lá!",--That's it. That's it! You're almost here, come on!
	loc_jr2_17_01 = "Ah, soquem uma tocha no meu rabo. A droga da carga quebrou e nós temos pacotes de dinheiro espalhados por aí como calcinhas de uma puta velha. Achem e ensaquem eles.",--Ah, fuck me with a firestick. Fucking pallet broke and we got fucking bundles of cash scattered around like an old whore's knickers. Find them and bag them.
	loc_jr2_01_06 = "Saudações, amigos. O avião está quase sobre o ponto de pouso. Saiam, por favor, matem alguns Murkies e vamos fazer aquele dinheiro nosso, ta bom?",--Greetings, friends. The plane is almost above the drop point. Please, get out, kill some Murkies and let's make that money ours, yeah?
	loc_jr2_41_03 = "Deixe-me lembrá-los. Procurem por um cartão de acesso se quiserem acesso aos telhados. Merda...",--Let me remind you. Look for a keycard if you want to get access to the roofs. Kak...
	loc_jr2_43_01 = "Ah! Sim, acredito que aquela escada será útil!",--Ah! Yes, I believe that ladder will be useful!
	loc_jr2_43_02 = "Peguem aquela escada, meus amigos. Peguem-na, e lucrem!",--Take that ladder, my friends. Take it, and profit!
	loc_jr2_37_02 = "Talvez seja bom olharem as coisas dos telhados, huh? Com certeza. Procurem uma escada para subir.",--Might be good to see things from the roofs, huh? For sure. Look for a ladder to get up.
	loc_jr2_30_01 = "E outra grade. Já sabem. Apenas usem a pasta de Térmite.",--And another grate. Same as before. Just use the thermal paste.
	loc_jr2_18_03 = "Olhem, meus amigos, se isso irá funcionar, algumas vezes vocês terão que fazer o que eu disser. E estou dizendo para acharem aqueles malditos pacotes!!",--Look, my friends, if this is going to work, sometimes you have to do what I say. And I'm saying find those fucking bundles!!
	loc_jr2_29_03 = "Vamos lá. Apenas colem a Térmite na grade e derretam ela. Não é difícil.",--Come on. Just stick the thermal paste on the grate and burn through. It's not hard.
	loc_jr2_36_02 = "Procurem por uma escada, se quiserem subir naquele telhado. E vocês querem subir naquele telhado, eu garanto.",--Have a look around for a ladder, if you want to get up on that roof. And you want to get up on that roof, I assure you.
	loc_jr2_01_02 = "Amigos! Belos amigos! Como está o voo? Estamos chegando perto do ponto de pouso. Então, por favor, abram a comporta e...",--Friends! Beautiful friends! How is the flight? We are getting close to the drop location. So, please, open the hatch and...
	loc_jr2_01_04 = "Olá amigos. Vocês estão quase no ponto de pouco que eu selecionei, então, se puderem  emergir e, como vocês dizem, começar a festa.",--Hello, friends. You're almost at the drop point I have selected, so, if you would emerge and, as you say, get the party started.
	loc_jr2_38_03 = "Vocês precisam achar a porra da escada, seus bucetas. Puta merda. Vamos lá!",--You poes need to find a fucking ladder. Fuck me. Come on!
	loc_jr2_30_03 = "É outra grade, mas isso está bem. Usem outro lote de pasta de Térmite.",--It's another grate, but that's fine. Use another batch of thermal paste.
	loc_jr2_22_03 = "Não atirem no grande helicóptero que está vindo para o dinheiro, certo? Aquele sou eu. Certeza, yeah.",--Don't shoot down the big helicopter that's coming in for the money, okay? That's me. Yeah, for sure.
	loc_jr2_24_03 = "Queridos corações! Estão me vendo? Sim, estou aqui. Com certeza. Odeio incomodar, mas se importariam de fixar aquele amável dinheiro ao meu helicóptero?",--Dear hearts! You see me? Yes, I am here. For sure. I hate to be a bother, but would you mind strapping that lovely money to my helicopter?
	loc_jr2_23_01 = "Ah! Sim, estou vendo. Estou chegando. Estejam prontos para fixar a carga ao helicóptero. E façam rápido, se isso for possível. As coisas estão pegando fogo.",--Ah! Yes, I see it. I'm coming in. Be ready to attach the pallets to the helicopter. And do it quickly, if that is possible. Things are hot.
	loc_jr2_04_02 = "Deixe-me dar uma mexida nas suas memórias, ta bom? Abram o portão da baía de carga. Por favor.",--Let me give your memories a jog, yeah? Open the cargo bay door. Please.
	loc_jr2_33_01 = "Preciso de todos vocês no barco, o mais breve possível, muito obrigado.",--I need all of you in the boat, as soon as possible, thank you very fucking much.
	loc_jr2_24_01 = "Certo. Aqui estou. Agora, se puderem apenas fixem essas cintas a carga e poderei evacuar com essa linda montanha de dinheiro.",--Okay. Here I am. Now, if you could just affix the straps to the pallet and I can evacuate this beautiful mountain of money.
	loc_jr2_29_01 = "Peguem a pasta e derretam a grade. Inferno.",--Grab that paste and burn through the gate. Fucking hell.
	loc_jr2_23_02 = "Estou vendo o sinalizador. Bravo! Chegando. Quando eu chegar, vocês poderiam conectar a carga ao helicóptero. Com toda a pressa, devo acrescentar.",--I see the flare. Bravo! On approach. When I am there, would you please attach the pallet to the helicopter. With all haste, I might add,
	loc_jr2_05_02 = "Excelente. O arrasto aumentado irá desacelerar o avião e forçar o piloto a voar baixo. Como esperado. Agora, vão para o controle de carga. Estão vendo eles acima de vocês? Tão perto, mas ainda sim tão longe. O único jeito de chegar lá é pelas escadas na frente do avião.",--Excellent. The increased drag will slow the plane and force the pilot to fly lower. As expected. Now, get to the cargo controls. You see them above you? So close, yet so far. The only way to get up there is by the stairs at the front of the plane.
	loc_jr2_32_02 = "Um bom bote de borracha. Todos a bordo!",--A nice rubber dinghy. All aboard!
	loc_jr2_27_03 = "Irei coletar vocês na periferia da cidade mas cheguem lá rápido e sem os policiais na cola. Desçam para os esgotos!",--I will collect you on the edge of town but get there are quickly and without the cops in tow. Get down to the sewers!
	loc_jr2_43_03 = "Acredito que possamos colocar aquela escada em bom uso. Sim, com certeza!",--I do believe we can put that ladder to good use. Yeah, for sure!
	loc_jr2_11_02 = "Todo mundo no chão, firmes que nem rocha? Ótimo. Agora procurem pela primeira carga de dinheiro. Quando acharem-no, acendam um sinalizador e chegarei rapidamente.",--Everyone on the ground, sound as a pound? Great. Now look around for the first money pallet. When you find 'it, pop a flare and I'll be right over.
	loc_jr2_04_05 = "Seus pintos não são para segurar. Eles são para fuder. E tem um monte de Murkies lá em cima esperando por eles. Peço desculpas às garotas da equipe.",--Your dicks ain't for holding. They're for fucking. And there's a lot of Murkies up there waiting for it. Apologies to any ladies in the crew.
	loc_jr2_32_03 = "Conseguem ver aquele barco? É a sua saída daí. Sim, com certeza. Entrem.",--See that boat? That's your way out right there. Yeah, for sure. Get in.
	loc_jr2_37_01 = "Amigos, subam nos telhados. Talvez vocês vejam as coisas mais claras lá em cima, ta bom? Provavelmente irão precisar de uma escada para subir.",--Get up on the roofs, friends. Maybe you will see things clearer up there, yeah? You'll probably need a ladder to get up.
	loc_jr2_32_01 = "Aí está o bote. Subam, meus bons amigos! Vamos levá-lá para um gentil cruzeiro.",--There's the boat. Hop in, my good friends! Let us take her for gentle cruise.
	loc_jr2_19_01 = "Certo. Bem, vocês sabem onde ele está, mas eu não. Acendam um sinalizador, yeah?",--Okay. Well, you know where it is, but I don't fucking know. Light a flare, yeah?
	loc_jr2_40_03 = "O telhado daquela lanchonete pode ser acessado por uma escada de serviço, mas vocês irão precisar de um cartão para isso. Com certeza está aí em algum lugar.",--The roof of that diner can be accessed by a service ladder, but you're going to need a keycard to get to it. Surely there's one around somewhere.
	pln_jr2_05_02 = "Tenham certeza de que aquelas cintas estão bem presas. Não queremos o Locke derrubando o loot antes da hora agora.",--Make sure those straps are nicely fastened. Don't want Locke dropping the loot too early now.
	loc_jr2_05_03 = "Esplêndido. O dinheiro está carregado nas cargas, que estão presas ao convés. Somente o oficial de logística pode soltá-las, e seus controles ficam acima de vocês - estão vendo? Para acessá-los, vocês deverão chegar nas escadas na frente do avião, e depois voltar nesse caminho.",--Superb. The cash is loaded on pallets, which are secured to the deck. Only the logistics officer can release them, and his controls are up above you - you see? To access them, you must get to the stairs at the front of the aircraft, and then return this way.
	loc_jr2_19_02 = "Certo. Agora ajudem seu amigo Locke. Acendam um sinalizador. Me mostrem onde está o dinheiro.",--Okay. Now help your friend Locke. Light a flare. Show me where the money is.
	loc_jr2_03_05 = "Abram essas portas! A alavanca está logo alí!",--Get those doors open! The switch is right there!
	loc_jr2_12_02 = "Vamos lá, continuem procurando. Vocês procuraram em todos os telhados? Eu sei que está na área.",--Come on, keep looking. Have you checked every roof? I know it's in the area.
	loc_jr2_10_02 = "Não tenham medo. Apenas pulem!",--Don't be scared. Just jump!
	loc_jr2_07_02 = "Vocês veem aquele botão? Tudo o que precisam fazer é apertá-lo.",--You see the button there? All you need to do is press it. 
	loc_jr2_27_02 = "Irei encontrá-los na periferia da cidade, mas não quero vocês trazendo todo o exército de policiais. Entrem nos esgotos. Organizei o transporte.",--I will meet you on the edge of town, but I don't want you bringing the whole fucking cop army. Get in the sewers. I've organised transport.
	loc_jr2_12_01 = "Procurem nos telhados, prédios, estacionamentos - todos esses tipos de lugares. A carga está aí em algum lugar.",--Check roofs, buildings, car parks - all those kinds of places. That pallet is around there somewhere.
	pln_jr2_04_02 = "Gangue, não se esqueçam - vocês precisam acender um sinalizador antes do Locke chegar.",--Gang, don't forget - you need to light a flare before Locke will come in.
	loc_jr2_14_02 = "Amigos, não sejam distraídos pela bela cidadezinha. Vocês estão procurando por uma tonelada de dinheiro.",--Don't get distracted by the beautiful little town. You're looking for a fuck-ton of money, friends.
	loc_jr2_13_03 = "Essa é a primeira carga. Beleza, boa. Agora, para o segundo. ",--That's the first pallet. All right, good. Now, onto the second.
	pln_jr2_01_03 = "Equipe, vocês ouviram o Locke - para dentro do porão de carga!",--You heard Locke, crew - into the cargo hold!
	loc_jr2_15_03 = "A segunda carga! Boa. Mas coisas boas vem em três. Como aquela semana em que todas as minhas esposas morreram. Achem a terceira carga.",--The second pallet! Good. But good things come in threes. Like that week all my wives died. Find the third pallet.
	loc_jr2_02_05 = "Agora, levantem, meus amigos!",--Now, rise, my friends!
	loc_jr2_31_03 = "Puta merda, mas que demora. Derretam a grade com a pasta de Térmite!",--Holy shit, what is the delay. Burn the grate away with the thermal paste!
	loc_jr2_34_02 = "Estou esperando vocês. Continuem dirigindo esse barco para mim.",--I'm waiting for you. Keep driving that boat to me.
	loc_jr2_21_01 = "Meus olhos já não são mais como antes. Ajudem um velho e acendam um sinalizador, yeah?",--My eyes aren't what they were. Help an old man out and light a flare, yeah?
	loc_jr2_42_02 = "Bem, parece que temos uns ladrõezinhos espertos, tentando roubar nosso dinheiro. Derrubem eles.",--Well, looks like we have some crafty litte thieves, trying to steal our money. Put them down.
	loc_jr2_13_01 = "Boa. Esse é o primeiro. Agora achem o segundo.",--Good. That's the first. Now find the second.
	loc_jr2_22_02 = "Estou chegando. Não atirem se virem um helicóptero gigante sobrevoando vocês, certo?",--I'm flying in. Don't shoot if you see a big fucking helicopter flying at you, right?
	loc_jr2_12_03 = "Não parem de procurar, seus merdas. Eu disse a vocês que a carga está aí em algum lugar.",--Don't stop looking, you kaks. I tell you the pallet is there somewhere.
	loc_jr2_02_03 = "Vamos lá, saiam daí!",--Out of there, come on!
	loc_jr2_01_05 = "Locke para Gangue PAYDAY, na escuta. Certo, então, o avião está se aproximando do ponto de pouso! Vamos não ficar perdendo tempo no escuro, vamos subir!",--Locke to Payday Gang, come in. Okay, so, the plane is nearing the drop point! Let's not dilly-dally here in the dark, let us rise!
	loc_jr2_44_03 = "Amigos, esse foi um ótimo trabalho. Teve de tudo. Excitação, ação - como um filme! E o melhor de tudo, um final feliz.",--That was a fucking great job, friends. It had it all. Excitement, action - like a movie! And best of all, a happy ending. 
	loc_jr2_16_01 = "Vamos lá, parem de brincar com seus amigos policiais de pinto pequeno. Achem a terceira carga, seus bucetas.",--Come on, stop playing with your little dick cop friends. Find the third pallet, you poes.
	loc_jr2_21_03 = "Amigos, vamos lá. Não percam tempo. Acendam aquele sinalizador para mim!",--Come on, chums. No dawdling. Light that flare for me!
	loc_jr2_15_02 = "Já foram achados duas cargas. Agora achem o terceiro. Vamos lá, lindos amigos. Continuem procurando.",--There's two pallets found. Now the third. Come on, beautiful friends. Keep looking.
	loc_jr2_08_01 = "Ótimo. O dinheiro está nos céus! Caindo exatamente onde eu quero. Como um floco de neve de um milhão de dólares. Oh, e peguem os paraquedas!",--Great. The money is in the sky! Drifting down exactly where I want it to. Like a million-dollar snowflake. Oh, and grab the parachutes!
	loc_jr2_37_03 = "Não esqueçam de olhar nos telhados dos prédios. Procurem por uma escada.",--Don't forget to check the roofs of the buildings. Look for a ladder. 
	loc_jr2_03_04 = "Sim, bom - agora abram as portas. A alavanca está alí!",--Yes, good - now open the doors. The switch there!
	loc_jr2_20_03 = "Boa. Isso deve ajudar. E falando de ajuda, acender um sinalizador seria bom. Pegaram minha dica, amigos?",--Nice. That should help. And speaking of help, so would lighting a flare. You get my hint, friends?
	loc_jr2_03_01 = "Primeiro, acionem a alavanca para abrir o portão de carga!",--First, hit the switch to open the cargo doors!
	loc_jr2_36_01 = "A carga caiu no telhado, huh? Beleza, então subam no telhado. Procurem por uma escada.",--The pallet fell on the roof, huh? All right, so get on the roof. Look for a ladder.
	pln_jr2_06_03 = "Como ele irá tirar vocês disso?",--How's he going to get you out of this?
	loc_jr2_26_03 = "Estou vendo um monte de vans da SWAT chegando. Essas merdas podem derrubar o helicóptero. Não poderei pegá-los. Mas eu tenho um plano...",--Seeing a lot of SWAT vans rolling in. Those kaks can bring this chopper down. I can't pick you up here. But I have a plan...
	loc_jr2_36_03 = "Procurem por uma escada. Tenho certeza que com uma energia devidamente aplicada na busca vocês irão lucrar. Com certeza.",--Look around for a ladder. I'm sure that with energy properly applied to a search you will profit. For sure.
	loc_jr2_34_01 = "Isso aí. Bom! Estou esperando vocês.",--That's it. Good! I'm waiting for you.
	loc_jr2_41_02 = "É como falar com um Francês. Se quiserem usar a escada de serviço no restaurante, precisarão do cartão. Mon dieu!",--It's like talking to a fucking Frenchman. Listen. If you want to use the service ladder in the diner, you need the keycard. Mon dieu!
	loc_jr2_34_03 = "Está bem. Continuem indo. Quase lá, meus amigos!",--That's right. Keep going. Almost here, my friends!
	loc_jr2_02_01 = "Subam! Subam! Subam, subam, subam!",--Up! Up! Up, up, up!
	loc_jr2_35_02 = "Vamos lá. Subam a bordo! Fizeram muito bem, meus amigos!",--Come on. Climb aboard! Well fucking done, my friends!
	loc_jr2_10_03 = "O ponto de pouso vai desaparecer se não se apressarem. Pulem!",--The dropzone will be long gone if you don't hurry. Jump!
	loc_jr2_11_03 = "Todos aterrissaram, sim? Sem tornozelos quebrados? Boa. Agoram achem a primeira carga de dinheiro. Eles estão aí em algum lugar. Achem-nos, e acendam um sinalizador.",--You're all down, yes? No broken ankles? Good. Now find the first money pallet. They're there somewhere. Find em, and light a flare. 
	loc_jr2_08_02 = "Sim, bom... pegando a telemetria do dinheiro agora. Bem no alvo. Oh, por que não pegam aqueles paraquedas aí.",--Yes, good...picking up telemetry from the money now. Right on target. Oh, why don't you grab those parachutes there.
	loc_jr2_16_03 = "Vocês são tão burros que a terceiro carga - a porra de um objeto inanimado - pode se esconder de vocês? Achem aquela merda.",--Are you so dumb that the third pallet - a fucking inanimated object - can hide from you? Find that cunt.
	loc_jr2_25_01 = "Vamos lá, seus merdas! Prendam o dinheiro ao helicóptero para que eu possa levá-lo!",--Come on, you kaks! Strap the money to the chopper so I can take it away!
	loc_jr2_28_03 = "Talvez tenham grades nos esgotos, então eu deixei um presentinho a vocês - algumas pastas de Térmite. Sou ou não bom para vocês?",--There might be grates in the sewer, so I left you a little present - some thermite paste. Aren't I nice to you?
	pln_jr2_intro_01_03 = "Beleza, pessoal. Aqui é o Locke... cuidado aí em cima.",--All right, guys. Here's Locke... Be careful up there.
	loc_jr2_45_02 = "Quase lá. Apressem-se! Seus lindos bastardos!",--Almost here. Hurry! You beautiful bastards!
	loc_jr2_26_02 = "Estou ouvindo que a polícia está enviando mais turrets da SWAT para derrubar meu helicóptero. Não poderei pegá-los na cidade. Mas me preparei para isso.",--I'm hearing that the kerel are sending more SWAT turrets to take out my helicopter. I can't pick you up in town. But I prepared for this.
	loc_jr2_35_01 = "Subam a bordo! Meus amigos, esse foi um trabalho excelente!",--Get aboard! That was a fucking excellent job, my friends!
	loc_jr2_20_02 = "Isso deve facilitar as coisas. Digo, por que um de vocês não acende um sinalizador para mim.",--That should make things easier. Say, why don't one of you guys light a flare for me too.
	loc_jr2_01_03 = "Queridos amigos! Aproveitando o voo até o momento, sim? Vocês estão quase no local que selecionei para cairem. Então...",--Dear friends! Enjoying the flight so far, yes? You're almost at the location I have selected as a drop point. So...
	loc_jr2_29_02 = "Olhem, eu preciso dizer tudo a vocês? Usem a pasta de Térmite para derreter as grades.",--Look, do I need to tell you everything. Use the thermal paste to burn through the grate.
	loc_jr2_07_01 = "Apenas apertem o botão. Vocês conseguem entender isso, não é?",--Just press the button. You can understand that, yeah?
	pln_jr2_04_01 = "Equipe, acendam o sinalizador para o Locke.",--Light that flare for Locke, crew.
	loc_jr2_38_01 = "Não se esqueçam. Procurem pela escada, queridos amigos.",--Don't forget. Look for the ladder, dear friends.
	loc_jr2_16_02 = "Eu não ligo se tiverem que subir uma parede que nem o Homem Aranha. Procurem em todos os lugares pela terceira carga.",--I don't care if you gotta shinny up a wall like fucking Spiderman. Look everywhere for that third pallet.
	loc_jr2_03_03 = "Amigos, acionem a alavanca da porta de carga!",--Hit the cargo door switch, friends!
	loc_jr2_35_03 = "Queridos amigos, subam a bordo! Isto foi muito bem feito!",--Get aboard, dear friends! That was fucking beautifully done! 
	loc_jr2_02_04 = "Saiam desse compartimento!",--Out of that compartment!
	pln_jr2_02_01 = "Vocês terão que abrir caminho até o final do avião, subir as escadas e abrir caminho novamente. É o único jeito de chegar nos controles de carga.",--You're going to have to fight your way to the end of the plane, get up the stairs and then fight back along. Only way to reach the cargo controls.
	loc_jr2_42_03 = "Olhem alí. Policiaiszinhos de merda estão roubando o dinheiro. No que este mundo está se tornando! Matem eles!",--Look over there. Little cop shits are stealing the money. The fuck is the world coming to! Kill them!
	loc_jr2_30_02 = "Outra grade, apenas lidem com ela como fizeram antes. Derretam ela com a pasta de Térmite.",--Another grate, so just treat it like you did before. Burn through with the thermal paste.
	loc_jr2_24_02 = "Amigos! Estou aqui e em posição! Por favor, quando a oportunidade permitir, peguem as cintas e conectem elas a aquele belo monte de dinheiro.",--Friends! I am here and in position! Please, when the opportunity allows, take the straps and attach them to that wonderful stack of money.
	loc_jr2_02_02 = "Saiam daí! Para dentro do porão de carga!",--Get out of there! Into the cargo hold!
	loc_jr2_03_02 = "A alavanca irá abrir o portão de carga!",--The switch there will open the cargo doors!
	loc_jr2_01_01 = "Meus amigos! Estamos nos aproximando do local que escolhi para cairmos. Então, sem mais delongas...",--My friends! We are approaching the location I have selected for the drop point. So, without further ado...
	loc_jr2_40_02 = "Aquela lanchonete tem uma escada de serviço levando ao telhado, mas vocês precisarão de um cartão para isso. Procurem em volta por um.",--That diner has a service ladder leading up to the roof, but you'll need a keycard to get to it. Look around for one.
	loc_jr2_06_02 = "Agora, apenas mexam nos controles de logística. É um trabalho simples. Até um samango retardado pode fazê-lo. E de vez em quando eles fazem, esses merdinhas.",--Now, just have a go at those logistics controls. It's a simple job. Even a retarded samango could do it. And sometimes they do, the little shits.
	loc_jr2_09_02 = "Para os céus, amigos!",--Out into the sky, friends!
	loc_jr2_04_01 = "Queridos amigos, eu faria daqui se pudesse, mas não posso. Então por favor abram a porra do portão de carga.",--I would do it from here if I could, dear friends, but I can't. So please open the fucking cargo doors.
	loc_jr2_04_03 = "Queridos amigos, não esqueçam - vocês precisam abrir o portão da baía de carga.",--Don't forget, dear friends - you need to open the cargo bay doors.
	loc_jr2_25_03 = "Vocês são burros? Eu disse prendam o dinheiro ao helicóptero!",--Are you fucking stupid? I said strap the money to the chopper!
	loc_jr2_09_03 = "Não hesitem - apenas pulem!",--Don't hesitate - just jump!
	loc_jr2_28_01 = "Vocês verão um pouco de pasta de Térmite aí em baixo. Caso os esgotos tenham quaisquer obstruções, vocês sabem.",--You'll see a bit of thermal paste down there. Just in case those sewers have any obstructions, you know.
	loc_jr2_14_01 = "Vamos lá, continuem procurando. Existem tantos lugares onde isso pode estar.",--Come on, keep looking. There's only so many places it can be.
	loc_jr2_22_01 = "Beleza. Estou chegando. Vocês verão um helicóptero grande e preto, este sou eu. A não ser que estejamos falando do que está escondido na gaveta da sua mãe.",--All right. I'm coming in. You see a big black fucking chopper, that's me. Unless we're talking about what's hidden in your mums knicker drawer.
	loc_jr2_06_01 = "Bravo! Agora, simplesmente operem os controles do oficial. É um trabalho tier-7, trabalho de macaco, qualquer um pode fazê-lo.",--Bravo! Now, simply operate the officer's controls. It is a tier-7 job, monkey work, anyone can do it.
	loc_jr2_13_02 = "Estão indo bem, meus amigos. Mas este foi apenas o primeiro. Achem a segunda carga.",--You're doing good, my friends. But that's just the first. Find the second pallet.
	loc_jr2_04_04 = "Parem de ficar parados. Abram as portas. Puta merda, o que há de errado com vocês.",--Stop standing around. Open the doors. Fuck me, what's wrong with you.
	loc_jr2_33_03 = "Vamos lá, apenas entrem na droga do bote. Puta merda, o que há de errado com vocês?",--Come on, just get into the fucking boat. Fuck me, what's wrong with you people?
	loc_jr2_31_01 = "Pelo amor de Deus! Vocês já fizeram isso. Apenas coloquem a pasta na grade!",--For the sake of a good fuck! You've done this already. Just put paste on the grate!
	loc_jr2_07_03 = "Seja um bom pequeno criminoso, e aperte aquele maldito botão!",--Be a good little criminal, and press that fucking button!
	loc_jr2_21_02 = "Tivemos um problema no rádio mais cedo? Amigos, preciso de um sinalizador aceso, yeah?",--Was there a radio problem earlier? Need a flare lit, friends, yeah?
	loc_jr2_31_02 = "Vocês estão muito próximos de terminar para ferrar com tudo agora. Apenas coloquem a pasta na grade e derretam ela!",--You're too close to finishing to fuck up now. Just slap the paste onto the grate and burn through!
	loc_jr2_20_01 = "Certo. Bom. Isso facilita as coisas. Direi a vocês o que mais facilitaria - acender um sinalizador para me guiar.",--Okay. Good. Makes things easier. Tell you what else would make it easier - lighting a flare to guide me in.
	loc_jr2_45_01 = "Agora, todos para o helicóptero! Vamos lá!",--Now, everyone to the chopper! Come on!
	loc_jr2_09_01 = "E pela porta vocês vão!",--And out the door you go!
	loc_jr2_10_01 = "O ponto de pouso está diretamente abaixo! Pulem agora!",--Dropzone is directly below! Jump now!
	loc_jr2_14_03 = "Lembrem-se do que estão procurando. Uma grande pilha de dinheiro. Grande pra porra.",--Remember what you're looking for. Big pile of cash. Shit big pile.
	loc_jr2_17_02 = "Jesus Magabe. Olhem isso. A porra da carga quebrou! Vocês terão que ensacar todo o dinheiro espalhado, e colocá-lo de volta no .",--Jesus fucking Mugabe. Look at this. Fucking pallet broke! You're going to have to bag all the spilled loot, get it back to the pallet.
	loc_jr2_17_03 = "Ah merda, esse aqui quebrou no impacto. Nós temos pacotes de dinheiro espalhados. Vocês precisarão achá-los, ensacá-los e trazê-los de volta aqui.",--Ah shit, this one broke on impact. We got bundles of cash scattered about. You're going to have to find them, bag them and get them back here.
	loc_jr2_18_01 = "Vamos lá, o que há de errado com vocês. Aqueles pacotes não podem ter ido muito longe.",--Come on, what's fucking wrong with you. Those bundles can't have gone too far.
	loc_jr2_19_03 = "Boa, boa. Agora acendam um sinalizador aí perto. Me mostrem aonde irei voar.",--Nice, nice. Now spark a flare close by. Show me where I'm flying.
	loc_jr2_23_03 = "O sinalizador está queimando bem. Aí vou eu. Se puder pedir outro favor, vocês se importariam de conectar a carga ao helicóptero quando eu estiver em posição?",--The flare is burning nicely. Here I come. If I may crave another boon, would you mind attaching the pallet to the helicopter when I am in position? 
	loc_jr2_28_02 = "Eu deixei uma maleta com pasta de Térmite aí em baixo para vocês. Tenham certeza de pegá-la.",--I left a case of thermal paste for you down there. Make sure you grab it. 
	loc_jr2_39_02 = "Uma das cargas acertou o telhado da lanchonete. Aposto que isso fez os Ianques cagarem em seus cafés, não é. Com certeza.",--One of the pallets hit the roof of the diner. I bet that had those Yanks shitting in their coffee, yeah. For sure.
	pln_jr2_01_01 = "Pessoal, apressem-se! Para dentro do porão!",--Hurry, guys! Into the hold!
	pln_jr2_03_01 = "Apressem-se, gangue. Vocês precisam cair perto do dinheiro.",--Hustle it, guys. You need to get on the ground near the money.
	pln_jr2_05_01 = "Aquele dinheiro precisa ser assegurado bem apertado pelas alças antes que o Locke possa decolar.",--That money needs to be tightly secured by the straps before Locke can take off.
	pln_jr2_05_03 = "Tenham certeza que todas as alças estão presas. Não deem ao Locke uma desculpa por acidentalmente derrubar o dinheiro.",--Ensure all of the straps are secure. Don't give Locke an excuse to accidentally drop the money.
	pln_jr2_06_01 = "Mas o que diabos ele tem em mente?",--The hell he have in mind?
	pln_jr2_06_02 = "O que ele está pensando?",--What's he thinking?
	pln_jr2_07_03 = "Pessoal, vocês ouviram o que o Locke disse. Subam no bote e vamos sair daí.",--You heard what Locke said, guys. Into the boat and let's get out of here.
	pln_jr2_intro_01_02 = "Equipe, espero que estejam bem aí em cima. Aqui é o Locke.",--Hope you're okay up there, crew. Here's Locke.
	
	-- Objetivos
	hud_heist_jerry_plane_06 = "Pule para fora do portão de carga.",--Jump out of the cargo doors.
	hud_heist_jerry_plane_05 = "Seus paraquedas estão armazenados perto. Peguem eles. Você irá precisar deles.",--Your parachutes are stored close by. Get them. You will need them.
	hud_heist_jerry_plane_02_hl = "Abra o Portão da Baía de Carga",--Open the cargo bay doors
	hud_heist_jerry_plane_03 = "Siga pelo avião para chegar no painel de controle do convés superior.",--Make your way along the plane to reach the control panel on the upper deck.
	hud_heist_jerry_plane_01 = "Suba a escada e entre no porão desse avião de carga da Murkywater.",--Climb up the ladder and enter the hold of this Murkywater cargo plane.
	hud_heist_jerry_plane_04 = "Use o controle de carga para soltar as cargas de dinheiro.",--Use the cargo controls to release the money pallets.
	hud_heist_jerry_plane_01_hl = "Apareça no Porão de Carga",--Emerge into the cargo hold
	hud_heist_jerry_plane_03_hl = "Alcance os Controles de Carga",--Reach the cargo controls
	hud_heist_jerry_plane_02 = "Tudo e todos irão sair pelo porão de carga. Abra as portas!",--Everything and everyone will be leaving through the cargo hold. Open the doors!
	hud_heist_jerry_plane_06_hl = "Pule fora do Avião com o Paraquedas",--Parachute out of the plane
	hud_heist_jerry_plane_04_hl = "Descarte as Cargas de Dinheiro",--Jettison the money pallets
	hud_heist_jerry_plane_05_hl = "Pegue o Paraquedas",--Get the parachutes
	hud_heist_jerry02_airdrop_gather_hl = "Junte o Dinheiro Espalhado",--Gather the scattered money
	hud_heist_jerry02_airdrop_reignite = "Os policiais apagaram o sinalizador. Acenda ele novamente.",--The cops have extinguished the flare. Get it lit again.
	hud_heist_jerry02_airdrop_signal = "O helicóptero do Locke está esperando para coletar as cargas de dinheiro. Acenda o sinalizador para trazê-lo.",--Locke's helicopter is waiting to collect the pallets. Ignite the flare to bring him in.
	hud_heist_jerry02_06 = "Dirija o bote através dos esgotos para chegar ao Locke e o helicóptero.",--Drive the rubber boat along the sewers to reach Locke and the helicopter.
	hud_heist_jerry02_airdrop_gather = "Uma das cargas de dinheiro quebrou e o dinheiro está espalhado pela cidade. Colete e junte-as na carga.",--One of the money pallets has broken and cash is scattered about the town. Collect them and put them back on the pallet.
	hud_heist_jerry02_02_hl = "Encontre a Segunda Carga de Dinheiro",--Find the second money pallet
	hud_heist_jerry02_airdrop_signal_hl = "Sinalize ao Helicóptero do Locke",--Signal Locke's helicopter
	hud_heist_jerry02_airdrop_attach = "Vá para a carga de dinheiro e conecte-o ao helicóptero.",--Go to the money pallet and attach it to the helicopter.
	hud_heist_jerry02_03_hl = "Encontre a Terceira Carga de Dinheiro",--Find the third money pallet
	hud_heist_jerry02_airdrop_attach_hl = "Conecte a Carga de Dinheiro",--Attach the money pallet
	hud_heist_jerry02_03 = "Localize a carga de dinheiro que caiu em algum lugar da cidade. Procure nos telhados e interiores.",--Locate the money pallet that has landed somewhere in the town. Check the roofs and interiors.
	hud_heist_jerry02_06_hl = "Fuja com o Helicóptero",--Escape with the helicopter
	hud_heist_jerry02_airdrop_wait = "Proteja o sinalizador. Policiais tentarão apagá-lo.",--Protect the flare. Cops will attempt to extinguish it.
	hud_heist_jerry02_04_hl = "Fuja pelos Esgotos",--Escape through the sewers
	hud_heist_jerry02_01 = "Localize a carga de dinheiro que caiu em algum lugar da cidade. Procure nos telhados e interiores.",--Locate the money pallet that has landed somewhere in the town. Check the roofs and interiors.
	hud_heist_jerry02_airdrop_reignite_hl = "Acenda novamente o Sinalizador",--Reignite the flare
	hud_heist_jerry02_05 = "Coloque toda a equipe no bote de borracha!",--Get all of the crew into the rubber boat!
	hud_heist_jerry02_airdrop_wait_hl = "Aguarde a Retirada",--Wait for the pickup
	hud_heist_jerry02_02 = "Localize a carga de dinheiro que caiu em algum lugar na cidade. Verifique os telhados e interiores.",--Locate the money pallet that has landed somewhere in the town. Check the roofs and interiors.
	hud_heist_jerry02_04 = "Ache uma das entradas dos esgotos na cidade. Desça, e lute até a saída.",--Find one of the sewer entrances in the town. Climb down, and fight to the exit.
	hud_heist_jerry02_01_hl = "Encontre a Primeira Carga de Dinheiro",--Find the first money pallet
	hud_heist_jerry02_05_hl = "Entre no bote de Borracha",--Get inside the rubber boat
		}