return {
	-- Nomes e Descrições
	--heist_tag = "Breakin' Feds",--Breakin' Feds
	--heist_tag_hl = "Breakin' Feds",--Breakin' Feds
	heist_tag_crimenet = "O FBI prendeu o Elefante só para pegar um objeto de sua posse, para trocar ele com o Kataru para o Comissário Garrett ficar com o crédito por acabar com o Bain. A troca vai ser hoje à noite, mas vamos invadir o FBI e pegar esse item primeiro.$NL;$NL;» Abra Caminho pela Segurança$NL;» Localize o Escritório do Garrett$NL;» Distraia o Garrett$NL;» Tome o Objeto de sua Posse e fuja",--The FBI have arrested the Elephant only to get an object in his possession, in order to trade it to the Kataru so that Commissioner Garrett can take the credit for ending Bain. The deal is taking place tonight, but we're going to break into the FBI and get the item first. $NL;$NL;» Make your way past security$NL;» Locate Garrett's office$NL;» Distract Garrett$NL;» Take the object from his possession and escape
	heist_tag_briefing = "Olha, não sabemos exatamente o que estamos procurando, além de ser um objeto, é bem provável que seja uma daquelas coisas que você vai saber quando for ver. É quase certo que o Garrett pegou ele da sala de evidência e guardou em algum lugar do seu Escritório. Meu informante disse que ele está lá e parece... distraído, então o encontro deve estar perto. Temos que se esgueirar lá agora se temos uma chance de roubar o item debaixo do nariz dele. É importante que entremos quietos. E não vá matando o Garrett, pois provavelmente vamos precisar desse otário depois.",--Now, we don't know exactly what we're after, beyond it being an object- it's probably one of those know-it-when-you-see it type things, but it's likely that Garrett has already taken it from Evidence and stashed it somewhere in his office. My contact inside said he's there and seems... distracted, so the meeting is definitely close. We've got to sneak in there now if we're going to have a chance of stealing the item from under him. It's important that we go in and stay quiet. And don't go killing Garrett- we're probably going to need that chop later.
	
	-- Legendas
	loc_tag_intro_01a = "Acho que isso vai ser legalzinho, né? Brincar um pouco com o Comissário...",--Guess this will be a bit of fun, yeah? Messing about with the Commissioner...
	loc_tag_intro_01b = "Tô impressionado que o Hoxton não está tendo um ataque nervoso voltando pra esse lugar.",--I'm impressed Hoxton isn't having a nervous breakdown coming back to this place.
	loc_tag_intro_01c = "Cara, se sairmos dessa, nunca mais vou querer ver o interior de outro prédio comercial.",--Man, if we get out of this one, I never want to see the inside of another office building.
	loc_tag_intro_01d = "Queria que tivéssemos uma ideia melhor do que estamos procurando.",--Wish we had a better idea of exactly what we're looking for.
	loc_tag_intro_01e = "Cuidado!",--Careful!
	loc_tag_intro_01f = "Ok, entrando.",--Okay, going in.
	loc_tag_intro_02a = "Bom, você tem que pegar a temperatura certa do óleo",--Well, you have to get the oil temperature just right.
	loc_tag_intro_02b = "Todo mundo sabe que o segredo está no glacê?",--Everybody knows the secret's in the glaze?
	loc_tag_intro_02c = "Não amigo, está na massa, yeah?",--Nah, friend it's in the batter, yeah?
	loc_tag_intro_02d = "Ei, eu sei como fazer um donut adequado.",--Hey, I know how to make a proper donut.
	loc_tag_intro_02e = "É essa merda mesmo que queremos ficar conversando?",--This shit really what we want to be talking about?
	loc_tag_intro_02f = "Achei que vocês de Nova Iorque só gostavam de rosquinhas, não é?",--Thought you New York guys were all about the bagels, yeah?
	loc_tag_intro_02g = "Você está certo velhote, mas fazemos donuts também.",--Right you are old chum, but we do donuts too.
	loc_tag_intro_02h = "Foda-se isso, por que estamos falando de donuts? Federais comem tortas.",--Fuck this, why are we talking about donuts? Feds eat pie.
	loc_tag_intro_03a = "Não acredito que estamos voltando pra esse lugar.",--Can't believe we're going back to this place.
	loc_tag_intro_03b = "É inapropriado pensar que isso pode ser divertido?",--Is it inappropriate of me to think this might be kind of fun?
	loc_tag_intro_03c = "Lembrem-se amigos, faremos isso pelo Bain. Mesmo que seja legal fazer o Garrett ficar putinho, temos que acabar com os planos dele.",--Remember friends, we're doing this for Bain. Even if it's fun making Garrett go bossies, we've got to take down his plans.
	loc_tag_intro_03d = "Queria que tivéssemos uma ideia melhor do que estamos procurando.",--Wish we had a better idea of exactly what we're looking for.
	loc_tag_intro_03e = "Vai logo, vai logo!",--Come on already, come on!
	loc_tag_intro_03f = "Isso, hora de ir.",--Yeah, it's go time.
	loc_tag_28_06 = "Não podem sair até achar aquele cofre.",--You can't leave without finding that safe.
	loc_tag_45_03 = "Sem perambular, amigos. Garrett pode estar voltando a qualquer momento.",--No snoozing, friends. Garrett could be heading back at any time.
	loc_tag_75_05 = "Nada mais pra fazer a não ser sair quietinhos, yeah?",--Nothing left to do but make like a bush, yeah?
	loc_tag_10_01 = "Ótimo, agora vão rápido para o portão e abram ele, yeah?",--Good, now hurry back to the gate and open it up, yeah?
	loc_tag_24_05 = "Procurem as caixas de segurança.",--Get to those security boxes.
	loc_tag_05_03 = "Uma velha... amiga minha no FBI me devia um favor, eu mandei ela deixar um laptop para nós. Ela ia esconder seu local em um quadro branco em algum lugar aí.",--An old... friend of mine in the FBI owed me a favor, so I got her to set up a laptop for us. She was going to hide its location on a whiteboard somewhere around there.
	loc_tag_81_07 = "Levem todo o loot pela tirolesa.",--Get all the loot onto the zipline.
	loc_tag_46_03 = "Rápido, amigos! O Garrett está vindo!",--Quickly, friends! Garrett's coming!
	loc_tag_75_04 = "Hora de ir pra casa, amigos.",--Time to go home, friends.
	loc_tag_81_02 = "Assegure o loot",--Secure the loot.
	loc_tag_25_02 = "Só mais um, yeah?",--Just one more, yeah?
	loc_tag_07_03 = "Ótimo, agora encontrem o laptop e comecem a hackear.",--Good, now locate that laptop and get hacking.
	loc_tag_26_02 = "Bom, agora só precisa desligar o teclado.",--Good, now you just got to kill the keypad.
	loc_tag_69_03 = "Tenho quase certeza que está em outra parte do prédio.",--I'm pretty sure it's in another part of the building.
	loc_tag_51_01 = "Talvez se mandarmos para ele um 'email urgente'? Tem um outro computador comprometido perto que podemos usar. Vão achá-lo.",--Maybe if we send him an 'urgent email'? There's another compromised computer near you we can use. Go find it.
	loc_tag_91_03 = "O código começa com zero, de acordo com a minha fonte.",--The code begins with a zero, according to my source.
	loc_tag_49_05 = "Vocês precisam desligar as luzes, amigos.",--You need to shut off the lights, friends.
	loc_tag_86_03 = "O código começa com cinco, de acordo com a minha fonte.",--The code begins with a five, according to my source.
	loc_tag_38_01 = "Ele não pode ser otário a ponto de colocar ele em um bilhete, poderia?",--He can't be chop enough to put it on a post-it, could he?
	loc_tag_24_02 = "Ainda precisam desativar a caixa de segurança.",--Still need to disable those security boxes.
	loc_tag_05_02 = "Achei uma velha amiga no FBI que me devia um favor para arrumar um laptop para nós. Ela disse que ia marcar o local em um quadro branco por aí, então procurem.",--Got an old maat in the FBI who owed me a favor to fix up a laptop for us. Said she would mark it's location on a whiteboard somewhere, so go find it.
	loc_tag_45_01 = "Fiquem de olho no Garrett, yeah? Ele deve estar voltando agora.",--Keep an eye out for Garrett, yeah? He must be on his way back by now.
	loc_tag_65_04 = "Não fiquem por mais tempo do que necessário... apenas peguem e vão embora, yeah?",--Don't stay around longer than you have to... just take it and get out, yeah?
	loc_tag_39_01 = "Continuem procurando por algo muito óbvio.",--Keep looking for something too obvious.
	loc_tag_44_02 = "Aweh! É isso! Eita, desculpa amigos... me empolguei um pouco.",--Aweh! That's it! Oh, sorry friends... got a bit carried away. 
	loc_tag_81_03 = "Já asseguraram todo o contrabando?",--Have you secure all the contraband yet?
	loc_tag_30_03 = "Porra, não vai dar pra arrombar isso a tempo. Precisaremos de um código.",--Blerrie, we're not cracking that in time. Going to need a code.
	loc_tag_09_03 = "Não parece o certo, precisam continuar procurando.",--Not the right one it seems, you got to keep looking.
	loc_tag_81_04 = "Ainda tem loot pra ser assegurado.",--There is still loot to be secured.
	loc_tag_66_02 = "Hmm, nada. Suponho que seria muito fácil pra acharmos nosso prêmio aqui. Bem provável que ainda esteja na Sala de Evidências.",--Hmm, nothing. I suppose it would have been too easy for us to find our prize here. It's probably still locked in the evidence room.
	loc_tag_65_01 = "Vamos amigos, peguem essa porra e saiam daí!",--C'mon friends, grab the donnerse and get out of there!
	loc_tag_29_02 = "Não se esqueçam do Garrett, yeah? Ele não vai ficar longe por muito tempo.",--Don't forget about Garrett, yeah? He's not going to be gone long.
	loc_tag_01_03 = "Antes de mais nada, vocês devem passar pelo portão de segurança, então vão dar uma olhada com o que estamos lidando, yeah?",--Before we do anything else, we gotta get you past the security gate, so go have a look at what we're dealing with, yeah?
	loc_tag_64_03 = "Quê!? É disso que aqueles Kataru estão atrás? Rápido, peguem isso e saiam daí o mais rápido possível.",--What!? That's what those Kataru are after? Quickly now, grab it and get out of there ASAP.
	loc_tag_35_02 = "Encontrou algo sobre a esposa do Garrett?",--Find anything with Garrett's wife?
	loc_tag_16_03 = "Certo, é o Escritório dele. Vamos para a próxima fase.",--Alright, that's his office. Now we move to the next stage.
	loc_tag_71_01 = "Voltem para a clarabóia, amigos.",--Get back to the skylight, friends.
	loc_tag_03_04 = "Não se esqueçam de olhar o portão da segurança, yeah?",--Don't forget to take a look at the security checkpoint, yeah?
	loc_tag_15_02 = "Talvez estejam vindo mais alguns guardas, amigos.",--You might be having a few more kerels coming soon, friends.
	loc_tag_64_04 = "Eita, não previ essa. O Elefante tinha uma também? Só peguem e caiam fora, vamos ver isso depois, yeah?",--Eish, didn't see that one coming. The Elephant had one too? Just take it and get out, we'll figure this out later, yeah?
	loc_tag_90_03 = "O código começa com nove, de acordo com minha fonte.",--The code begins with a nine, according to my source.
	loc_tag_28_04 = "Vamos lá pessoal, encontrem aquele cofre.",--C'mon guys, find that safe.
	loc_tag_50_01 = "Ótimo, agora voltem lá dentro.",--Good, now get back in there.
	loc_tag_24_04 = "Garrett não vai ficar fora pra sempre, então vão procurando essas caixas.",--Garrett's not going to be gone forever, so get to finding those boxes.
	loc_tag_38_03 = "Não me surpreenderia se o Garrett, tentando ser esperto, colocou em algum lugar estupidamente óbvio.",--Wouldn't surprise me if Garrett, trying to be clever, put it somewhere stupidly obvious.
	loc_tag_03_06 = "Ainda não olhou as barreiras?",--Had a look at the barries yet?
	loc_tag_15_01 = "A rotação dos guardas estão mudando, talvez tenham mais vindo em breve. Fiquem de olho, yeah?",--The guard rotation is changing, so there might be more coming soon. Keep a lookout, yeah?
	loc_tag_91_02 = "Procurem um código que comece com zero.",--Look for a code that starts with zero.
	loc_tag_61_05 = "Já deram um jeito naquela comida?",--Take care of that food yet?
	loc_tag_18_02 = "Encontrem um telefone por aí que eu vou tentar fazer o Sr. Garrett sair pra dar uma caminhada ou sei lá.",--Find me a telephone around there and I'll try to get Mr. Garrett to take a little walk or something.
	loc_tag_03_01 = "Já acharam o portão, amigos?",--Have you found the gate yet, friends?
	loc_tag_06_06 = "Vocês devem achar o quadro branco enquanto ainda temos tempo, amigos.",--You have to find the whiteboard while we still have time, friends.
	loc_tag_08_01 = "Vocês deviam achar o laptop, amigos.",--You need to find the laptop, friends.
	loc_tag_09_01 = "Nada aconteceu? Deve ser o errado. Continuem procurando.",--Nothing happened? Must be the wrong one. Keep looking.
	loc_tag_13_04 = "Escritório do Garrett, yeah?",--Garrett's office, yeah?
	loc_tag_25_03 = "Desativar mais uma caixa deve bastar.",--Disabling one more box should be enough.
	loc_tag_58_01 = "Encontrem o computador da Chloe.",--Find Chloe's desk and computer.
	loc_tag_08_03 = "Então pessoal, cadê aquele laptop?",--So guys, where's that laptop?
	loc_tag_33_02 = "Veem algo com alguma importância histórica?",--See anything with historical significance?
	loc_tag_75_01 = "Bora amigos, saiam daí.",--C'mon friends, get out of there.
	loc_tag_72_01 = "Bom trabalho amigos, agora só arrastem isso pra fora daí.",--Good job friends, now just hoist it out of there.
	loc_tag_33_01 = "Talvez algo histórico, yeah?",--Maybe something historical, yeah?
	loc_tag_60_02 = "Bosta, esse cara é insistente. Certo, hora da nossa maior arma. Policiais não recusam comida. Se acharem alguma coisa por aí, coloquem bem na frente do Escritório dele, yeah?",--Blerrie, this guy is persistent. Alright, time to bring in the big guns. Kerels can't say no to food. If you can find some around there, stick it in front of his office, yeah?
	loc_tag_91_01 = "O código deve ter um zero no começo.",--The code should have a zero at the beginning.
	loc_tag_60_03 = "Ah porra, de novo não. Talvez um lanchinho da meia-noite sirva. Encontrem alguma comida e coloquem na frente da porta do Garrett.",--Ah kek, not again. Maybe a midnight snack will do it. Find some food and set it outside Garrett's door.
	loc_tag_06_02 = "O quadro branco gente, encontrem ele, yeah?",--The whiteboard guys, find it, yeah?
	loc_tag_21_01 = "Foi. Ele está se mexendo?",--There we go. Is he moving?
	loc_tag_16_01 = "Ai está. Muito bom.",--There you go. Nicely done.
	loc_tag_17_03 = "Lembrem-se gangue, precisamos que o Garrett continue respirando... por enquanto.",--Remember gang, we need Garrett to keep breathing... for now.
	loc_tag_34_01 = "Garrett é casado, talvez o aniversário da esposa dele?",--Garrett is married, so maybe his wife's birthday or anniversary?
	loc_tag_56_03 = "O computador do Taylor deve estar perto.",--Taylor's computer should be nearby.
	loc_tag_13_06 = "O Escritório do Garrett está aí em algum lugar.",--Garrett's office is around there somewhere.
	loc_tag_81_06 = "Usem a tirolesa para assegurar o loot.",--Use the zipline to secure the loot.
	loc_tag_39_02 = "Deve estar bem debaixo de seus narizes, amigos.",--It's probably right under your noses, friends.
	loc_tag_71_05 = "Rápido agora, pra clarabóia.",--Quickly now, to the skylight.
	loc_tag_57_01 = "Encontrem o computador da Valentine.",--Find Valentine's desk and computer.
	loc_tag_37_01 = "Procurem números conectados com a Crimenet.",--Look for numbers in connection with Crimenet.
	loc_tag_56_02 = "Vocês vão precisar encontrar o computador do Taylor.",--You need to find Taylor's computer.
	loc_tag_42_03 = "Como conseguiu tão rápido? Talvez eu vá tomar um cafézinho e deixar vocês trabalharem sozinhos, yeah?",--How did you get that so quick? Maybe I can just go have a coffee and let you sort things alone, yeah?
	loc_tag_37_02 = "Veem alguns numeros conectados a nós?",--See any numbers connected to us?
	loc_tag_26_01 = "Agora vão dar um curto no teclado da porta do Garrett.",--Now go and short out the pad by Garrett's door.
	loc_tag_85_01 = "O código deve ter um quatro no começo.",--The code should have a four at the beginning.
	loc_tag_77_03 = "Vá em frente e ative, Twitch. Tapem as orelhas, amigos.",--Go ahead and light it up, Twitch. Hold your ears, friends.
	loc_tag_19_02 = "Me coloquem naquele telefone, yeah?",--Hook me up to that phone, yeah?
	loc_tag_50_02 = "Ai está amigos, agora corram pra dentro!",--There you go friends, now hurry back in!
	loc_tag_59_03 = "O computador do Brown deve estar por perto.",--Brown's computer should be nearby.
	loc_tag_65_06 = "Não precisam ficar mais aí. Peguem a caixa e façam a extração.",--No need to stay there longer. Take the box and make for extraction.
	loc_tag_87_01 = "O código deve ter um seis no começo.",--The code should have a six at the beginning.
	loc_tag_58_03 = "O computador da Chloe deve estar perto.",--Chloe's computer should be nearby.
	loc_tag_83_02 = "Encontrem um código que comece com dois.",--Look for a code that starts with two.
	loc_tag_74_02 = "Arranjei o Twitch para esperarem vocês no porão. Peguem o elevador, e não esqueçam a caixa!",--I've got Twitch waiting for you in the basement. Take the elevator, and don't forget the box!
	loc_tag_17_05 = "Ah, só imaginem botar uma bala bem no meio do cabeção velho do Garrett, mas não hoje amigos. Jogos longos e essas coisas, yeah?",--Ah, just imagine putting a slug right in the middle of old Garrett's gob. But not tonight, friends. Long game and all that, yeah? 
	loc_tag_76_03 = "Lembram daquele filme aonde um cara no elevador fica puto e eviscera todo mundo?",--Remember that movie where one person in the lift goes bossies and just eviscerates everyone?
	loc_tag_13_01 = "Encontrem o Escritório do Comissário, pessoal.",--Find the Commissioner's office, guys.
	loc_tag_20_03 = "Beleza amigos, me deem um minuto para conectar.",--Alright friends, just give me some time to connect.
	loc_tag_38_02 = "Talvez ele colocou em algum lugar muito óbvio, yeah?",--Maybe he put it somewhere really obvious, yeah?
	loc_tag_39_03 = "Deve estar aí em plena vista.",--Maybe it's right there in plain sight.
	loc_tag_84_01 = "O código deve ter um três no começo.",--The code should have a three at the beginning.
	loc_tag_73_03 = "Não precisam ficar mais aí, amigos. Se estiverem prontos, vão direto para a extração.",--No need to stay any longer, friends. If you're ready, go for extraction.
	loc_tag_28_03 = "Precisam achar o cofre do Garrett.",--You got to find Garrett's safe.
	loc_tag_72_02 = "Muito bem, amigos. Única coisa que falta é levar pra longe daí.",--Well done, friends. Only thing left is to zip it out of there.
	loc_tag_78_03 = "O Garrett não vai gostar de explicar isso, com certeza. Agora assegurem essa caixa e saiam antes que a polícia chegue.",--Garrett's going to have a fun time explaining that one for sure. Now get that box secured and get out before the kerels arrive.
	loc_tag_04_03 = "Ah, bosta. Eles têm esses novos detectores modernos instalados. Vamos ter que tomar medidas diferentes.",--Ah, blerrie. They've got those new ultra-fine detectors installed. Got to take a different approach.
	loc_tag_78_02 = "Sempre saiam de uma reunião social com um pouco de talento. Agora assegurem essa caixa e vamos.",--Always exit a social gathering with a bit of flair, friends. Now, secure that box and go.
	loc_tag_05_01 = "Uma velha conhecida minha no FBI que me devia um favor arranjou um laptop pra vocês usarem. Ela disse que marcaria qual que era em um quadro branco. Vejam se conseguem achar, yeah?",--My old acquaintance in the FBI that owed me a favor has doctored a laptop for you to use. She said she would mark which one on a whiteboard. See if you can find it, yeah?
	loc_tag_90_01 = "O código deve ter um nove no começo.",--The code should have a nine at the beginning.
	loc_tag_83_01 = "O código deve ter um dois no começo.",--The code should have a two at the beginning.
	loc_tag_28_01 = "Continuem procurando esse cofre, yeah?",--Keep looking for that safe, yeah?
	loc_tag_01_01 = "Ótimo, amigos. rápido e quietos, yeah? Primeira coisa é passar pela segurança. Vão para o portão e olhem as barreiras.",--Right, friends. Nice and quiet, yeah? First thing you gotta do is get past security. Go to the gate and have a look at the barriers.
	loc_tag_29_04 = "Devem prestar atenção no Garrett caso ele volte.",--You have to keep tabs on Garrett in case he comes back.
	loc_tag_92_02 = "Muito bom, amigos!",--Well done, friends!
	loc_tag_90_02 = "Procurem um código que comece com nove.",--Look for a code that starts with nine.
	loc_tag_08_02 = "Quero que vocês hackeiem aquele laptop, yeh?",--Get to hacking that laptop, yeah?
	loc_tag_87_03 = "O código começa com seis, de acordo com a minha fonte.",--The code begins with a six, according to my source.
	loc_tag_76_04 = "Me pergunto quantos problemas será que o Comissário vai ter por perder essa caixa.",--I wonder how much trouble the Commissioner will get into for losing the box.
	loc_tag_84_02 = "Procurem um código que comece com três.",--Look for a code that starts with three.
	loc_tag_35_03 = "Procurem por pistas conectadas com a esposa do Comissário.",--Look for clues connected to the Commissioner's wife.
	loc_tag_11_02 = "Demoraram muito. Vão ter que voltar e hackear de novo.",--You took too long.  Gotta go back and hack it again.
	loc_tag_31_03 = "Vejam se o Garrett é trouxa o bastante de deixar o código em plena vista.",--See if Garrett is chop enough to have the code in plain sight.
	loc_tag_14_01 = "Deve ter muita coisa boa que podemos usar ou vender por aqui, então fiquem de olhos abertos para qualquer coisa que pode ser boa para levarmos.",--There's got to be lot's of good stuff we can use or sell around here, so keep your eyes peeled for anything that might be good to take along.
	loc_tag_08_05 = "Laptops... são muito úteis, mas vocês vão ter que... achá-los.",--Laptops... can be very useful but you got to... find them.
	loc_tag_41_02 = "Código errado, amigos. Esperem até resetar, aí podem tentar de novo.",--Wrong code, friends. Wait until it resets, then have another go.
	loc_tag_92_01 = "Ótimo trabalho, amigos!",--Good job, friends!
	loc_tag_22_02 = "Ai está amigos.",--There you go friends.
	loc_tag_21_02 = "Certo, vamos ver se ele mordeu a isca.",--Right, now let's see if he took the bait.
	loc_tag_02_01 = "Ainda deve ter gente trabalho aí, então fiquem de olhos abertos, yeah?",--There could still be office personnel working, so keep your eyes open, yeah?
	loc_tag_08_06 = "Estou igual a uma vovó sonolenta aqui... então encontrem esse laptop.",--Starting to feel like a nagging nanny here... so find that laptop.
	loc_tag_71_04 = "Precisam ir para a clarabóia.",--You need to move to the skylight.
	loc_tag_70_03 = "Levem a caixa de volta para a clarabóia de onde entraram, yeah?",--Carry the box back to the skylight where you entered, yeah?
	loc_tag_47_02 = "Ah, cú. Ele está no Escritório de novo. Temos que tirá-lo de lá.",--Ah, kak. He's in his office again. We've got to get him out of there.
	loc_tag_47_03 = "Garrett voltou pro Escritório. Precisamos manter ele longe de lá!",--Garrett is back in his office. We need to keep him out of there!
	loc_tag_19_04 = "Estou esperando me colocarem no telefone.",--Still waiting on that phone hookup.
	loc_tag_59_01 = "Encontrem o computador do Brown.",--Find Brown's desk and computer.
	loc_tag_51_03 = "Podemos tentar um email pra tirar ele de lá. Encontrem um computador comprometido por perto.",--We can try to get him out with an email. Find a compromised computer nearby.
	loc_tag_71_03 = "Não fiquem aí, vão para a clarabóia.",--Don't stay there, get to the skylight.
	loc_tag_14_03 = "Se tiverem a chance, peguem um pouco de loot que podemos vender. Não é sempre que podemos passear pela Sala de Evidências do FBI!",--If you get the chance, maybe grab some loot that might be useful to sell. It's not every day you got free reign in the the FBI's evidence lockup!
	loc_tag_57_02 = "Vocês precisam achar o computador da Valentine.",--You need to find Valentine's computer.
	loc_tag_45_02 = "Não esqueçam que o Garrett vai voltar logo.",--Don't forget that Garrett will be back soon.
	loc_tag_03_03 = "Vocês ainda precisam olhar o portão de segurança.",--You still gotta have a look at the security gate.
	loc_tag_29_01 = "De olho no Garrett. Ele não vai ficar fora pra sempre.",--Keep an eye out for Garrett. He won't be gone forever.
	loc_tag_35_01 = "Vejam se conseguem encontrar algo relacionado à esposa do Garrett.",--See if you can find something related to Garrett's wife.
	loc_tag_19_01 = "Me conectem a um telefone, amigos.",--Connect me to a telephone, friends
	loc_tag_58_02 = "Vocês precisam encontrar o computador da Chloe.",--You need to find Chloe's computer.
	loc_tag_67_02 = "Mas olhem... um Cartão de Acesso.",--But look... the keycard.
	loc_tag_48_01 = "Talvez desligar a energia possa servir. Procurem uma caixa de energia.",--Maybe killing the lights will do it. Have a look around for a circuit box.
	loc_tag_79_02 = "Não fiquem de bobeira, yeah? Guardas estão vindo.",--No standing around, yeah? Kerels are on the way.
	loc_tag_17_02 = "Matar esse otário ia ser tão bom, mas precisamos dele vivo, então dedos fora dos gatilhos, yeah?",--Capping that dwankie would feel right good, but we need him alive, so hands off the triggers, yeah?
	loc_tag_81_01 = "Precisam assegurar todo o loot pela tirolesa.",--You need to secure all the loot with the zipline.
	loc_tag_23_02 = "Deve dar pra passar pelo teclado desativando algumas caixas de segurança por aí.",--You should be able to get past the code lock by disabling a few security boxes around there.
	loc_tag_25_01 = "Ai está, mais uma deve bastar.",--There you go, one more should do it.
	loc_tag_49_04 = "Façam o Comissário ficar mais sombrio do que ele já é. Ha, Locke é bom das piadas, né?",--Make the Commissioner's mood darker than it already is. Ha, Locke is no joker, eh?
	loc_tag_48_02 = "Vejam se conseguem cortar a energia do Escritório dele através de um disjuntor aí perto.",--See if you can cut the lights in his office through a nearby circuit breaker.
	loc_tag_81_08 = "Tudo que vocês pegaram vão precisar passar pela tirolesa.",--Everything you've taken needs to go out on the zip.
	loc_tag_66_01 = "Vazio? Caralho, o Garrett ainda não deve ter pego das evidências.",--Empty? Blerrie, Garrett must not have gotten it from Evidence yet.
	loc_tag_62_01 = "Retardados! Não era pra matar ele!",--Dompkops! You weren't supposed to kill him!
	loc_tag_23_01 = "A porta do Escritório do Garrett está trancada, vejam se conseguem burlar através de umas caixas de segurança.",--The door to Garrett's office is locked, but see if you can bypass it through nearby security boxes. 
	loc_tag_27_01 = "Ai está, amigos. Agora entrem e vejam se conseguem achar a coisa que nós viemos buscar. Provavelmente está em um cofre.",--There we go, friends. Now get inside and see if you can find the dinges we can here for. It's probably in a safe.
	loc_tag_82_02 = "Procurem um código que comece com um.",--Look for a code that starts with one.
	loc_tag_03_02 = "Já localizaram o portão de segurança?",--Have you located the security gate yet?
	loc_tag_18_01 = "Me coloquem em um telefone em algum lugar e vou ver se consigo tirar o Comissário do Escritório dele.",--Hook me up to a phone somewhere and I'll see about getting the dear Commissioner out of his office.
	loc_tag_34_03 = "Pode estar ligado com sua esposa... uma data ou algo assim?",--Could be linked to his wife... a date or something?
	loc_tag_42_01 = "Ei, como fizeram isso tão rápido, amigos? O Velho Locke se sente quase desnecessário...",--Hey, how did you do that so quickly, friends? Old Locke almost feels unnecessary...
	loc_tag_40_03 = "Vamos torcer que seja o que estamos procurando.",--Let's hope that's what we're looking for.
	loc_tag_11_01 = "Muito lento, pessoal. Voltem e tentem novamente.",--Too slow, guys. Go back and try again.
	loc_tag_10_04 = "Deu certo, mas não tem muito tempo até que o sistema reinicie, então voltem para o portão!",--That's done it, but you don't have much time before the system restarts, so get back to the gate!
	loc_tag_57_03 = "O computador da Valentine deve estar aí por perto.",--Valentine's computer should be nearby.
	loc_tag_75_03 = "Não há necessidade de ficar mais tempo aí.",--No need to stay there any longer.
	loc_tag_32_02 = "Talvez tenha algo histórico no código?",--Maybe there's something historical to the code?
	loc_tag_83_03 = "O código começa com dois, de acordo com a minha fonte.",--The code begins with a two, according to my source.
	loc_tag_15_05 = "Porra, vocês vão ter mais guardas para lidar logo logo.",--Blerrie, you're going to have more guards to deal with shortly.
	loc_tag_26_03 = "Perfeito, agora só falta desconectar o teclado na porta do Garrett.",--Perfect, all you got to do now is disconnect the keypad on Garrett's door.
	loc_tag_67_03 = "Mas esse Cartão de Acesso pode ser útil.",--But that keycard could be useful.
	loc_tag_07_01 = "É isso, sim. Agora vão encontrar aquele laptop e hackeiem ele.",--That's it, yeah. Now go find that laptop and hack into it.
	loc_tag_11_04 = "Porra! Voltem e hackeiem de novo.",--Blerrie! Go back and redo the hack.
	loc_tag_32_01 = "Garrett gosta de história, então talvez seja algo... histórico?",--Garrett likes history, so maybe something... historical?
	loc_tag_36_01 = "Talvez o código esteja ligado a Crimenet?",--Maybe the code has to do with Crimenet?
	loc_tag_87_02 = "Procurem um código que comece com seis.",--Look for a code that starts with six.
	loc_tag_63_01 = "Funcionou melhor do que eu esperava. Não fizeram nada com ele, fizeram?",--That worked better than I anticipated. You didn't do anything to it, by any chance?
	loc_tag_40_02 = "Não tenho certeza, mas deve ser o certo.",--Not sure, but it's probably the right one.
	loc_tag_15_03 = "Parece que mais guardas estão vindo, então fiquem atentos, yeah?",--Looks like more guards are on the way, so stick some toothpicks in your eyes, yeah?
	loc_tag_24_01 = "Encontrem as caixas de segurança, amigos.",--Find those security boxes, friends.
	loc_tag_43_03 = "Deu certo, amigos!",--That did it, friends!
	loc_tag_68_02 = "Talvez irá destrancar a Sala de Evidências. Peguem e vão achá-la.",--Maybe it will unlock the evidence room. Take it and go find it.
	loc_tag_65_05 = "Vocês podem ser descobertos a qualquer momento se não sairem. Peguem a caixa e voltem pra saída, amigos.",--You could be discovered any minute if you don't leave. Grab the box and make your way out, friends.
	loc_tag_28_05 = "Ainda precisam achar o cofre, amigos.",--You still need to find the safe, friends.
	loc_tag_06_01 = "Pessoal, achem aquele quadro branco.",--Find that whiteboard, guys.
	loc_tag_22_03 = "Ok, ele saiu.",--OK, he's off.
	loc_tag_13_03 = "Vocês precisam achar o Escritório do Garrett.",--You need to find Garrett's office.
	loc_tag_61_04 = "Já deram um jeito na comida?",--Have you taken care of the food yet?
	loc_tag_86_01 = "O código deve ter um cinco no começo.",--The code should have a five at the beginning.
	loc_tag_77_02 = "Twitch, tudo limpo pra você.",--Twitch, you are good to go.
	loc_tag_62_03 = "Seus otários! Precisávamos do Garrett vivo!",--You dwankies! We needed Garrett alive!
	loc_tag_04_02 = "Caramba, eles atualizaram para os detectores Mark 7. Isso vai ser um pouco mais difícil.",--Damn, they've upgraded to the Mark 7 detectors. Going to be a bit more difficult.
	loc_tag_10_03 = "É isso amigos, voltem e passem pelo portão, yeah?",--That's it friends, hurry back and get through the gate, yeah?
	loc_tag_74_03 = "Entrem no elevador com a caixa. O Twitch está esperando vocês no porão.",--Get into the elevator with the box. Twitch is waiting for you in the basement.
	loc_tag_60_01 = "Ele voltou de novo? Certo. vamos tentar mais uma coisa. Federais não resistem a comida. Vejam se alguém está fazendo um lanchinho e coloquem um pouco no Escritório dele.",--He's back again? Alright, let's try one more thing. Feds can't resist food. See if anyone is having a late snack and put some by his office.
	loc_tag_61_03 = "Alimentem o policial, amigos.",--Feed the Fed, friends.
	loc_tag_49_02 = "Não batam na cabeça dele, só encontrem os disjuntores!",--Don't klock him in the head, just find the circuit box!
	loc_tag_12_01 = "Certo, agora devem achar o Escritório do Garrett.",--Right, now you gotta find Garrett's office.
	loc_tag_23_03 = "Para passar pela tranca do Garrett, vão precisar desativar umas caixas de seguranças pela área.",--To get past Garrett's code lock, you'll have to disable a few security boxes in the area.
	loc_tag_89_01 = "O código deve ter um oito no começo.",--The code should have an eight at the beginning.
	loc_tag_49_06 = "Desliguem a energia do Garrett, rápido.",--Kill Garrett's lights, quickly now.
	loc_tag_17_01 = "Sei que querem por uma bala na cara dele, mas precisam ficar focados, yeah?",--I know you want to put a bullet in his face, but you got to stay focused, yeah?
	loc_tag_63_02 = "Deve bastar. Ele não vai voltar logo. Obrigado aos espíritos culinários pelo chili ruim, yeah?",--That should do it. He won't be back soon. Thank the culinary spirits for bad chili, yeah?
	loc_tag_69_01 = "Última informação que recebi foi de que está no outro lado do prédio, yeah?",--The last intel I got put it on the other side of the building, yeah?
	loc_tag_80_01 = "Agora só achar um jeito de entrar no Escritório dele.",--Now you just have to find a way into his office.
	loc_tag_02_02 = "Devem ter zeladores e outros civis nesse edifício, então tomem cuidado.",--There might be janitors and other civvies in the building, so take extra care.
	loc_tag_18_03 = "Se me colocar em um telefone, posso tentar fazer o Comissário ter algo pra fazer em outro lugar.",--If you patch me into a phone, I can try to give the dear Commissioner something to do elsewhere. 
	loc_tag_64_01 = "Puta que pariu! É disso que viemos atrás? Peguem e dê o fora daí, yeah?",--Donnerse! That's what we came for? Grab it and get out of there, yeah?
	loc_tag_12_03 = "Agora, vamos nos divertir com o Comissário. Encontrem o Escritório dele, yeah?",--Now, we have a little jol with the Commissioner. Go find his office, yeah?
	loc_tag_29_05 = "Não querem ficar presos aí com o Garrett, então não percam ele de vista.",--Don't want to get stuck in there with Garrett, so make sure you don't lose him.
	loc_tag_71_06 = "Vão para a clarabóia com a caixa.",--Go to the skylight with the box.
	loc_tag_43_02 = "Muito bom, amigos.",--Nicely done, friends.
	loc_tag_66_03 = "Ah, o negócio não está aqui, o que quer que seja, Garrett provavelmente não pegou da Sala de Evidências ainda.",--Ah, the donnerse isn't here, whatever it is. Garrett probably hasn't picked it up from the evidence room yet.
	loc_tag_30_02 = "Parece que os federais tiveram o orçamento melhor esse ano. Esse é um novo modelo K, não da pra abrir de forma silenciosa sem o código.",--Looks like the Feds got a better budget this year. That's a new model K, no way to get in quietly without the code.
	loc_tag_89_02 = "Procurem um código que comece com oito.",--Look for a code that starts with eight.
	loc_tag_22_01 = "Ótimo, agora vocês devem achar um jeito de entrar no Escritório dele.",--Good, now you just have to find a way into his office.
	loc_tag_85_03 = "O código começa com quatro, de acordo com a minha fonte.",--The code begins with a four, according to my source.
	loc_tag_48_03 = "Ele deve sair se desligarmos a energia. Veem disjuntores por perto?",--He might leave if we turn off the lights. Do you see a circuit box nearby?
	loc_tag_69_02 = "Está do outro lado do prédio.",--It's on the other side of the building.
	loc_tag_36_02 = "Pode ser que o código esteja relacionado com a jornada do Garrett contra nós, yeah?",--Could be that the code is related to Garrett's crusade against us, yeah?
	loc_tag_72_03 = "Boa. agora só temos que tirar daí.",--There we go. Now you just got to send it out of there.
	loc_tag_29_03 = "Garrett pode voltar a qualquer segundo, não o percam de vista.",--Garrett could come back any time, so don't lose track of him.
	loc_tag_41_03 = "Não era esse. Deem um tempo para resetar, e depois tentem de novo.",--That wasn't it. Got to give it some time to reset, then try again.
	loc_tag_06_05 = "Vamos gente, encontrem o quadro branco logo, yeah?",--Come on guys, find the whiteboard already, yeah?
	loc_tag_63_03 = "Quase me sinto culpado pelo babacão. Ele vai ficar longe por um bom tempo agora, não precisam se preocupar.",--Almost feel sorry for the chop. He'll be gone for a good while now, no need to worry.
	loc_tag_64_02 = "Que... era isso que o Elefante tinha? Isso não é... Não, não parece né? Só peguem e deem o fora daí.",--What... that's what the Elephant had? Isn't that... No, not quite eh? Just take it and get out of there.
	loc_tag_62_02 = "Porra! Toda a operação foi pro caralho!",--Blerrie! This whole operation just went to kak!
	loc_tag_06_04 = "Algum quadro branco aí perto?",--Any whiteboards nearby?
	loc_tag_76_01 = "Em tempos assim, sempre me pergunto: Que tipo de pessoa escreve músicas de elevador, né?",--Times like these, I always wonder; What kind of person writes elevator music, eh?
	loc_tag_85_02 = "Procurem um código que comece com quatro.",--Look for a code that starts with four.
	loc_tag_80_02 = "Agora vocês devem achar uma maneira de entrar.",--Now you got to find a way inside.
	loc_tag_17_04 = "Sem dar tiros no Garrett essa noite, Ok amigos?",--No bullets with Garrett's name on them tonight, OK friends?
	loc_tag_80_03 = "Hora de achar um jeito de entrar lá.",--Time to find a way in there.
	loc_tag_27_02 = "Rápido amigos, entrem no Escritório e peguem o que viemos atrás. Garrett deve ter colocado em um cofre.",--Quickly friends, get inside the office and get what we're here for. Garrett's bound to have it in a safe.
	loc_tag_46_02 = "Rápido amigos, saiam daí.",--Hurry friends, get out of there.
	loc_tag_67_01 = "Mas esse Cartão de Acesso... pode ser o que precisamos.",--But that keycard... might be just what we need.
	loc_tag_76_05 = "Quase devemos nos sentir culpados pelo Comissários depois de uma noite dessas. Quase.",--You almost gotta feel sorry for the Commissioner after a night like this. Almost.
	loc_tag_03_07 = "E aquela segurança, amigos?",--How about that security, friends?
	loc_tag_49_01 = "Desliguem as luzes do Garrett, amigos.",--Turn off Garrett's lights, friends.
	loc_tag_86_02 = "Procurem um código que comece com cinco.",--Look for a code that starts with five.
	loc_tag_15_04 = "Mais guardas estão vindo, então sem correr por aí.",--You got more guards incoming, so no dozing off.
	loc_tag_06_03 = "Ainda precisam encontrar o quadro branco.",--Still gotta find the whiteboard.
	loc_tag_52_01 = 'Procurem pelo nome "Taylor" em uma escrivaninha.',--Look for the name "Taylor" on the desk.
	loc_tag_81_05 = "Qualquer loot que quiserem levar precisará ser assegurado.",--Any loot you want to take back needs to be secured.
	loc_tag_51_02 = "Ok, vamos tirar ele de lá com um email 'urgente'. Tem um outro computador comprometido que podemos usar perto de vocês.",--Ok, let's get him out with an 'urgent' email. You've got another compromised computer near you we can use.
	loc_tag_89_03 = "O código começa com oito, de acordo com a minha fonte.",--The code begins with an eight, according to my source.
	loc_tag_30_01 = "Aí. Hmm, é um novo Yaeger modelo K. Não tem como abrir rápido sem o código.",--There. Hmm, that's the new Yaeger model K. No way to get into in fast without the code.
	loc_tag_56_01 = "Achem o computador do Taylor.",--Find Taylor's desk and computer.
	loc_tag_33_03 = "Garrett gosta de história, amigos.",--Garrett likes history, friends.
	loc_tag_07_02 = "Ai está, agora encontrem o laptop e hackeiem ele.",--There you go, now find that laptop and hack it.
	loc_tag_65_02 = "Rápido amigos, peguem a caixa.",--Quickly friends, grab the box.
	loc_tag_44_01 = "BINGO!",--JACKPOT!
	loc_tag_77_01 = "Certo, Twitch... sua vez. Talvez queiram cobrir as orelhas, amigos.",--Right, Twitch... you're up. Might want to cover your ears, friends.
	loc_tag_36_03 = "O código pode estar conectado a nós e a Crimenet de alguma forma?",--The code might be connected to us and Crimenet, in some way?
	loc_tag_13_05 = "O que estão fazendo? Deveriam estar procurando o Escritório do Garrett.",--What are you doing? You should be looking for Garrett's office.
	loc_tag_88_02 = "Procurem um código que comece com sete.",--Look for a code that starts with seven.
	loc_tag_59_02 = "Precisam encontrar o computador do Brown.",--You need to find Brown's computer.
	loc_tag_31_01 = "Olhem mais um pouco em volta. Talvez o Garrett tenha o código escrito.",--Have another look around. Maybe Garrett has the code written down.
	loc_tag_16_02 = "É isso amigos, bom trabalho.",--That's it friends, good work.
	loc_tag_33_04 = "Procurem algo a ver com história.",--Look for something to do with history.
	loc_tag_42_02 = "Trabalho rápido, amigos. Estão a frente do Velho Locke, yeah?",--Quick work, friends. You got ahead of old Locke, yeah?
	loc_tag_79_04 = "Possuem pouco tempo até os policiais acharem vocês.",--You've only got a small bit of time before the kerels find you.
	loc_tag_73_02 = "Pegamos o que viemos atrás, então podem sair quando estiverem prontos.",--We got what we came for, so you can get out whenever you are ready.
	loc_tag_02_03 = "Lembrem-se que pode ter o pessoal da limpeza e outros não-policiais andando por aí.",--Keep in mind that there might be cleaning personnel and other non-kerels moving about.
	loc_tag_03_05 = "Deveriam dar uma olhada na situação da segurança, pessoal.",--You gotta take a look at the security situation, guys.
	loc_tag_61_02 = "Vamos amigos, coloquem comida na porta do Garrett.",--C'mon friends, put some food by Garrett's door.
	loc_tag_24_03 = "Vamos amigos. Não demorem tanto. Desativem as caixas.",--C'mon, friends. Don't take too long. Disable those boxes.
	loc_tag_49_03 = "Deve ter um disjuntor bem próximo daí.",--There should be a circuit box nearby.
	loc_tag_75_02 = "Por que ainda estão aí?",--Why are you still there?
	loc_tag_37_03 = "Procurem pistas na investigação do Garrett, yeah?",--Look for clues in Garrett's investigation, yeah?
	loc_tag_88_03 = "O código começa com sete, de acordo com a minha fonte.",--The code begins with a seven, according to my source.
	loc_tag_08_04 = "Vamos gente, vocês não tem a noite inteira. Encontrem o laptop.",--C'mon guys, you haven't got all night. Find that laptop.
	loc_tag_46_01 = "Saiam daí, um problemão está vindo com tudo!",--Get out of there, kakspul of trouble is coming!
	loc_tag_44_03 = "ISSO AMIGOS! Oh, desculpa... não estou acostumado com essa furtividade, yeah?",--YES FRIENDS! Oh, sorry... I'm not used to this sneaking about, yeah?
	loc_tag_92_03 = "Ai está!",--There we go!
	loc_tag_53_01 = 'Encontrem a escrivaninha de "A. Valentine".',--Find the desk of "A. Valentine".
	loc_tag_76_02 = "Amigos, vocês sentem que as paredes estão fechando quando estão descendo em um elevador?",--Friends, do you guys ever feel the walls closing in when you're going down in an elevator? 
	loc_tag_74_01 = "Twitch está esperando por vocês no porão. Só um caminho de elevador, e depois todos vamos pra um lanchinho, yeah?",--Twitch is waiting for you in the basement. Just a short elevator ride, then we all go for a bite, yeah?
	loc_tag_65_03 = "Rápido agora. Peguem e saiam daí.",--Hurry up now. Take it and get out.
	loc_tag_27_03 = "Rápido amigos, entrem lá e peguem o que viemos buscar. Garrett provavelmente colocou dentro de um cofre ou algo assim.",--Now hurry up friends, get in there and find the thing we came here for. Garrett probably has it in a safe or something.
	loc_tag_40_01 = "Não pode ser 100%, mas acho deve estar certo.",--Can't be 100%, but I think that's right.
	loc_tag_10_02 = "Deu certo amigos, agora voltem e abram o portão.",--There you go friends, now go back and open up the gate.
	loc_tag_79_03 = "Policiais chegando em breve.",--Kerels will be coming soon.
	loc_tag_68_01 = "Peguem e achem a Sala de Evidências. Talvez conseguiremos entrar lá.",--Take it and find the evidence lockup. Maybe we can get in there.
	loc_tag_78_01 = "Haha! Isso vai deixar o Garrett tremendo na base quando for encontrar a Kataru de mãos abanando. Agora assegurem a caixa e saiam daí.",--Haha! That should rustle Garrett's nerves a bit for when he goes to meet the Kataru empty-handed. Now secure the box and get out of there. 
	loc_tag_69_04 = "Vão para o lado oposto do prédio.",--Head towards the opposite side of the building.
	loc_tag_79_01 = "Rápido, amigos.",--Hurry up, friends.
	loc_tag_49_07 = "Vamos amigos, desliguem as luzes.",--C'mon friends, get to those lights.
	loc_tag_31_02 = "Não me supreenderia se Garrett tiver o código por aí em algum lugar.",--Wouldn't be surprised if Garrett has the code around there somewhere.
	loc_tag_55_01 = '"Brown" é o nome da escrivaninha que vocês devem procurar.',--"Brown" is the desk name you should be looking for.
	loc_tag_28_02 = "Procurem o cofre do Garrett, amigos.",--Find Garrett's safe, friends.
	loc_tag_47_01 = "Merda! Ele voltou pro Escritório. Precisamos tirar ele de novo.",--Blerrie! He's back in his office. Need to get him out again.
	loc_tag_43_01 = "Aweh! Deu certo.",--Aweh! There we go.
	loc_tag_70_02 = "Voltem para a clarabóia por onde entraram e levem a caixa.",--Head back to the skylight where you came in and bring the box.
	loc_tag_19_05 = "Qual é, parem de perambular e achem o telefone.",--C'mon, stop loitering about and get to finding that phone.
	loc_tag_01_02 = "Ok, amigos. Vamos acabar com isso, rápido e quieto. Primeira coisa é passar da entrada de segurança. Não deve ser difícil, mas deem uma olhada nos portões.",--Ok, friends. Let's get this over with, nice and easy. First thing to do is get past the security entrance. Shouldn't be too hard, but go have a look at the gates.
	loc_tag_09_02 = "Pegaram o laptop errado, amigos. Encontrem o certo.",--You got the wrong laptop, friends. find the right one.
	loc_tag_50_03 = "Certo ele saiu de novo, voltem no Escritório dele, yeah?",--Alright he's gone again, so get back in his office, yeah?
	loc_tag_04_01 = "Ok, parece que eles atualizaram não faz muito tempo atrás. Vai ficar um pouco mais difícil.",--OK, looks like they've upgraded not too long ago. Makes this a little bit harder.
	loc_tag_11_03 = "Acabou o tempo, amigos. Precisam hackear de novo.",--Time is up, friends. You need to redo the hack.
	loc_tag_12_02 = "Hora de encontrar o Escritório do Garrett, amigos. Se divirtam um pouco com ele.",--Time to find Garrett's office, friends. Have a little fun with the guy.
	loc_tag_13_02 = "Rápido amigos, temos horário pra cumprir.",--Come on friends, we have a schedule to keep.
	loc_tag_14_02 = "Esses federais otários têm coisas mais interessantes do que donuts e tortas dando sopa - coisas que podemos ganhar uma grana para nos manter, então se virem algo legal, vão lá e peguem.",--These Federal Kerels have got more interesting things than donuts and pie lying around- things we could get a pretty penny for to keep us going, so if you see something nice, go ahead and rop it. 
	loc_tag_19_03 = "Encontraram o telefone?",--Found a phone yet?
	loc_tag_20_01 = "Ok, estou ligando agora. Fiquem abaixados e quietos.",--Ok, I'm dialing now. Stay low and wait.
	loc_tag_20_02 = "Deu certo. Está tocando.",--There we go. It's ringing.
	loc_tag_21_03 = "Não acredito que ele é tão burro assim.",--Can't believe what a domkop he is.
	loc_tag_32_03 = "Garrett é um velhote... atenção no que ele gosta. Coisas como história.",--Garrett is old school... sticks to what he knows. Things like history.
	loc_tag_34_02 = "Talvez algo ligado à sua esposa... aniversário ou algo assim?",--Maybe something to do with his wife... an anniversary or something?
	loc_tag_41_01 = "Não, está errado. Merda! Tentem de novo quando resetar.",--No, that's not it. Blerrie! Try again when it resets.
	loc_tag_54_01 = 'Usem o computador pertencido a uma tal "Chloe".',--Use the one owned by "Chloe".
	loc_tag_61_01 = "Já acharam alguma comida?",--Find any food, yet?
	loc_tag_61_06 = "Vocês precisam tirar o Garrett de lá de novo. Encontrem um lanchinho.",--You've got to get Garrett out of there again. Find some food.
	loc_tag_68_03 = "Com sorte, isso vai nos deixar entrar na Sala de Evidências. Rápido, peguem e vão.",--With a bit of luck, that will get us into the evidence room. Quickly, take it and go.
	loc_tag_70_01 = "Levem a caixa pra clarabóia de onde entraram, yeah?",--Take the box back to the skylight where you came in, yeah?
	loc_tag_71_02 = "Devem voltar pra clarabóia.",--You gotta get back to the skylight.
	loc_tag_73_01 = "Se estiverem prontos, podem sair do complexo.",--If you're feeling ready, go ahead and leave the facility.
	loc_tag_82_01 = "O código deve ter um no começo.",--The code should have a one at the beginning.
	loc_tag_82_03 = "O código começa com um, de acordo com a minha fonte.",--The code begins with a one, according to my source.
	loc_tag_84_03 = "O código começa com três, de acordo com a minha fonte.",--The code begins with a three, according to my source.
	loc_tag_88_01 = "O código deve ter sete no começo.",--The code should have a seven at the beginning.
	loc_tag_cbf_01 = "Caro amigos. O Comissário Garrett prendeu o Elefante com acusações falsas só pra pegar um item que ele possui, que os donos da Murkywater - aquele pessoal do Kataru quer. Ele está fazendo um acordo para trocar com eles pelo, parece que é, o corpo do Bain, agora que acabaram com ele. O item é obviamente muito importante para eles arriscarem se expor e eu não duvido que seja tudo sobre aqueles negócio sagrados do Bain. Não sabemos ainda o que o Elefante está fazendo nisso tudo, isso se ele ainda estiver com a gente, e não poderiamos ajudar ele agora mesmo se nós quisessemos, mas o Garrett vai estar no QG do FBI essa noite se preparando para a troca, Então vamos arruinar seus planos.",--Dear friends. Commissioner Garrett has arrested the Elephant on trumped-up charges in order to get an item he has, that the owners of Murkywater- these Kataru people, want. He's making a deal to give it to them in exchange for what we can only guess is the body of Bain, now that they're done with him. The item obviously very important for them to risk exposing themselves and I wouldn't bet against the whole thing being about Bain's Grail-Dinges. We don't know yet what the Elephant's doing in all of this, if he's still solid with us, and we couldn't help him right now even if we wanted to, but Garrett will be in his FBI headquarters tonight preparing for the exchange, so we're going to ruin his plans.
	loc_tag_end_01 = "Muito bom, amigos. Tiramos o tapete bem debaixo do Comissário Garrett e eu acho que as próximas horas dele não vão ser muito legais. Oh, e quando ele chegar na troca de mãos vazias, yeah? Bain ficaria orgulhoso. Assim que voltarem para a casa segura, o Duke deve começar a abrir e examinar a caixa do Elefante. Temos que saber como ela se conecta com a outra coletada em Las Vegas, as coisas sagradas do Bain e esses cuzões do Kataru. Ai planejaremos nossa próxima jogada.",--Well done, friends. We pulled the rug from right under Commissioner Garrett and I expect his next few hours won't be very pleasant. Oh, to be there when he goes to his meeting empty-handed, yeah? Bain would be proud. As soon as you get back to the safehouse, Duke should get cracking on examining the Elephant's box. We've got to know how it connects to the one you acquired in Las Vegas, to Bain's grail-dinges and these Kataru chops. Then we plan our next move.
	
	-- Objetivos
	hud_heist_tag16_hl = "Fuja",--Escape
	hud_heist_tag15_hl = "Assegure a Caixa",--Secure the box
	hud_heist_tag12_hl = "Use o Cartão de Acesso",--Use the keycard
	hud_heist_tag03 = "Hackeie o laptop correto para acessar o painel da barreira de segurança. Você irá ter um tempo limitado para abrir depois disso, então corra!",--Hack the correct laptop to access the securty barrier panel. You will have a limited time to open the barrier afterward, so hurry!
	hud_heist_tag03_hl = "Hackeie a Segurança",--Hack security
	hud_heist_tag01_hl = "Inspecione a Barreira de Segurança",--Inspect the security barrier
	hud_heist_tag04 = "Localize o Escritório do Garrett no coração do edifício. Cuidado com guardas e câmeras!",--Locate Garrett's office in the heart of the building. Watch out for guards and cameras!
	hud_heist_tag09 = "Vasculhe o Escritório do Garrett pelo código correto do cofre!",--Search Garrett's office for the correct code to the safe!
	hud_heist_tag10 = "Pegue o Cartão de Acesso do cofre e vá para a Sala de Evidências!",--Take the keycard from the safe and head to the evidence room!
	hud_heist_tag09_hl = "Insira o Código Correto",--Enter the correct code
	hud_heist_tag01 = "Abra caminho para a barreira de segurança e inspecione-a. Tome cuidado com os agentes do turno da noite.",--Make your way to the security barrier and inspect it. Watch out for late-working agents.
	hud_heist_tag16 = "Fuga Disponível!",--Escape available!
	hud_heist_tag12 = "Encontre um uso para o Cartão de Acesso dentro da Sala de Evidências!",--Find a use for the keycard inside the evidence room!
	hud_heist_tag08_hl = "Localize o Cofre",--Locate the safe
	hud_heist_tag11_hl = "Encontre e Entre na Sala de Evidências",--Find and enter the evidence room
	hud_heist_tag11 = "Encontre a Sala de Evidências localizada no lado oposto do edifício.",--Find the evidence room located on the opposite side of the building.
	hud_heist_tag10_hl = "Pegue o Cartão de Acesso",--Take the keycard
	hud_heist_tag14_hl = "Pegue o Elevador",--Take the elevator
	hud_heist_tag13 = "Pegue a caixa do Elefante e saia daí!",--Grab the Elephant Box and get out of there!
	hud_heist_tag07 = "Entre no Escritório do Garrett desativando o painel de segurança em sua porta!",--Enter Garrett's office by disabling the security panel by his door!
	hud_heist_tag04_hl = "Encontre o Escritório do Garrett",--Find Garrett's office
	hud_heist_tag02 = "Encontre um quadro branco nessa parte do prédio. Ela contém informações cruciais.",--Look for a whiteboard in this part of the office. It contains important information.
	hud_heist_tag02_hl = "Encontre o Quadro Branco",--Find the whiteboard
	hud_heist_tag05 = "Siga as instruções de Locke para distrair Garrett para fora do Escritório dele.",--Follow Locke's instructions to lure Garrett out of his office.
	hud_heist_tag05_hl = "Distraia Garrett para fora",--Lure Garrett out
	hud_heist_tag06 = "Encontre e desative as caixas de segurança que controlam o painel de segurança do Garrett.",--Find and disable the security boxes which control Garrett's security panel.
	hud_heist_tag06_hl = "Desative as Caixas de Segurança",--Disable security boxes
	hud_heist_tag07_hl = "Desative o Painel de Segurança do Garrett",--Disable Garrett's security panel
	hud_heist_tag08 = "Encontre o cofre no Escritório do Garrett.",--Find the safe in Garrett's office.
	hud_heist_tag13_hl = "Pegue a Caixa",--Take the box
	hud_heist_tag14 = "Abra caminho para o porão. Certifique-se de que seu time e a caixa estejam dentro do elevador!",--Make your way to the basement. Make sure everyone in your team, and the box, are inside the elevator!
	hud_heist_tag15 = "Assegure a caixa e mais loot adicional!",--Secure the box plus any additional loot!
		}