return {
	-- Nomes e Descrições
	--heist_brb = "Brooklyn Bank",--Brooklyn Bank
	--heist_brb_hl = "Brooklyn Bank",--Brooklyn Bank
	heist_brb_crimenet = "O Bain estava atrás de um objeto enterrado na fundação do velho banco no Brooklyn. Nós precisamos abrir caminho de maneira bem barulhenta, e retirar esse objeto de lá.$NL;$NL;» A Van de Controle Remoto do Locke bate dentro do Banco$NL;» Entre no Banco$NL;» Ganhe acesso à Pré-Sala do Cofre$NL;» Arrombe o Cofre$NL;» Plante o C4 no chão$NL;» Retire o Objeto escondido em baixo do Cofre$NL;» Saqueie mais ou Fuja",--Bain was after an object that is buried in the foundation of the old bank in Brooklyn. We need to smash our way in loudly, and retrieve this object.$NL;$NL;»Locke's remote controlled van crashes into the bank$NL;»Get into the bank$NL;»Gain access to the pre-vault room$NL;»Crack the vault$NL;»Plant C4 on the floor$NL;»Retrieve the object hidden under the vault$NL;»Loot more or escape
	heist_brb_briefing = "Parece que alguém na Murkywater talvez esteja atrás da nossa situação atual. Eles fecharam todos os canais de comunicação comigo. Ainda tenho uns amigos lá, mas parece que estou oficialmente... expulso. O Sr. Lindenhurst foi gentil o bastante para desencriptar algumas anotações que um ancestral imprimiu na traseira de uma pintura: A Vista do Monte Vernon. Bain possuia a coisa real sabem; vocês devem se perguntar como ele conseguiu isso, yeah? Tanto faz, as anotações detalham que dentro do cofre do Banco Brooklyn, existe algo enterrado na fundação; algo que o Bain precisa, colocado lá quando o concreto foi derramado. Não tenho ideia do que seja, e como isso tudo se encaixa, mas quem chegou nele colocou muitos recursos, então provavelmente não é nenhuma velharia. Nós vamos pegá-lo antes que alguém descubra, yeah?",--It looks like someone at Murkywater might be behind our current predicament. They have closed all communication channels with me.  Still got a couple friends there, but it looks like I am officially... ousted. Mr. Lindenhurst was kind enough to decrypt some notes an ancestor had printed on the back of a painting:The View of Mount Vernon. Bain owned the real thing you know; you have to wonder how he pulled that one off, yeah? Watookal, the notes detail that inside the vault of the Brooklyn Bank, there's something buried in the foundation; something that Bain needed, put there when the concrete was poured. I've no idea what it is, and how all this fits together, but whoever got to him put in a lot of resources, so it's probably not any old dinges. We're going in to get it before anyone else finds out, yeah?
	
	-- Legendas
	loc_brb_intro_01 = "Amigos, sei que isso é sério mas vocês ainda precisam se divertir um pouco, yeah? Agora tomem cuidado!",--Friends, I know this is serious but you still have to have a bit of fun, yeah? Watch now!
	loc_brb_intro_01a = "Um pouco pra esquerda... aí vamos nós... ACH, maldito civil! Uau, quase conseguimos esse também. Um pouco mais rápido.",--Left a bit.. there we go... ACH, bekakin' civvie! Whoa, almost got that one too. A little faster.
	loc_brb_intro_01b = "Quase lá... eeeee....",--Almost there... aaaand....
	loc_brb_intro_01c = "Hahaha isso foi maravilhoso! Agora continuem, amigos!",--Hahaha that was kiff! Now get going, friends!
	loc_brb_intro_02 = "Tenho que admitir que faz um tempo que invadi um lugar desses fazendo tanto barulho. Isso vai ser divertido!",--I gotta admit it's been awhile since I broke into a place this loudly. It's gonna be jol!
	loc_brb_intro_03 = "Certo amigos, vocês irão gostar disso! É um pequeno quebrar e pegar no inverno, yeah?",--Ok friends, you're going to like this! A little smash and grab in the dead of winter, yeah?
	loc_brb_58_01 = "Arranjei o Twitch vindo com uma van para vocês, yeah?",--I've got twitch coming with the van for you, yeah?
	loc_brb_24_03 = "Se estiverem ficando sem equipamento, vão dar uma outra olhada no ponto de entrega.",--If you run short of equipment, go take another look at the drop site.
	loc_brb_47_02 = "Se precisarem de mais equipamento, voltem e verifiquem o estoque lá fora, yeah?",--If you need more equipment, go back and check the stash outside, yeah?
	loc_brb_58_03 = "Amigos, vão lá pra fora! o Twitch está chegando com a van!",--Get outside, friends! Twitch is incoming with the van!
	loc_brb_14_03 = "Amigos, vocês vão precisar explodir o chão!",--You gotta blow the floor, friends!
	loc_brb_32_03 = "Vocês terão o guincho num minuto, yeah?",--You'll have your winch in about a minute, yeah?
	loc_brb_52_02 = "Como estão indo com esse andar?",--How are you coming along with that floor?
	loc_brb_55_03 = "...Estou vendo muita conversa no rádio da Murkywater, não fiquem por muito tempo. Talvez eles estejam querendo se juntar a nós, e nós não queremos isso, yeah?",--...I'm seeing a lot of talk on Murkywater comms, so don't stay long. They might be wanting to join us, and we don't want that, yeah?
	loc_brb_39_02 = "Agora liguem o guincho. E mantenham os policiais bem longe dele!",--...Now start up the winch. And keep the coppers away from it!
	loc_brb_40_01 = "Amigos, não esqueçam o guincho!",--Don't forget the winch, friends!
	loc_brb_50_03 = "Agora vocês precisam explodir um buraco no chão, yeah? O que nós viemos buscar está na fundação do prédio.",--Now you gotta blow a hole into the floor, yeah? What we're after is in the foundation of the building.
	loc_brb_55_01 = "...Não demorem muito. Tenho um pressentimento de que meus velhos amigos na Murky estão rastreando nossos movimentos.",--....Don't take too long. Got a feeling my old friends at Murky have been tracking our movements.
	loc_brb_39_03 = "...Hora de arrancar aquela porta, yeah? Iniciem o guincho e mantenham os policiais longe dele!",--...Time to pull that door off, yeah? Start the winch and keep the kerels from getting to it!
	loc_brb_30_02 = "A termite terminou de queimar, yeah? Hora de montar aquele guincho.",--Thermite has burned through, yeah? Time to get that winch set up.
	loc_brb_08_01 = "Maldição! Todas as portas estão seladas. Vocês terão que achar outra maneira de entrar na sala do cofre. Vão para o segundo andar e procurem por uma fraqueza no chão ou algo parecido, yeah?",--Blerrie! All the doors are sealed. You're going to have to find another way into the vault room. Get up to the second floor and look for a weakness in the floor or something, yeah?
	loc_brb_04_01 = "Maldição! Vocês terão que atravessar a porta usando uma serra, yeah?",--Blerrie! You'll have to go through the back door with a saw, yeah?
	loc_brb_41_05 = "Policiais pararam o guincho! Mantenham eles longe dele, yeah?",--Coppers have stopped the winch! Keep them away from it, yeah?
	loc_brb_14_04 = "Amigos, nenhum polícial gordo irá cair através daquele buraco e aumentá-lo. Vocês precisam explodi-lo, yeah?",--No fat copper is going to fall through that floor and make it bigger, friends. You gotta blow it, yeah?
	loc_brb_50_01 = "A coisa que viemos buscar está no meio daquele chão. Explodam um buraco com alguns C4 para que possamos tirá-lo dali, yeah?",--The thing we're after is in the middle of that floor. Gotta blow a hole in it with some c4 so we can get it out of there, yeah?
	loc_brb_12_05 = "Não podemos deixar aquela serra ali amigos, tirem ela, yeah?",--Can't go having that saw there friends, get it off, yeah? 
	loc_brb_53_02 = "Bastante bonito, yeah? Escrita velha e tudo mais, igual a coisa que nos enviou aqui. O que quer que seja.",--Rather beautiful, yeah? Old writing and all, just like the stuff that sent us here. Whatever it is.
	loc_brb_06_01 = "Maldição! O primeiro andar está bloqueado. Vão para o segundo pelo andaime lá fora. Deve haver uma porta que vocês possam cortar com uma serra.",--Blerrie! First floor is blocked off. Get up to the 2nd by the scaffolding outside. Should be a door you can hack through with a saw.
	loc_brb_28_01 = "Maldição! Esse é um cofre velho! É quase uma pena ter que explodir ele, yeah?",--Blerrie that's an OLD vault! Almost a shame to blow it open, yeah?
	loc_brb_04_02 = "Amigos, não iremos entrar por esse caminho. Saiam e achem uma porta dos fundos para arrombar com uma serra.",--Not going to get in that way, friends. Go outside and find a back door to crack open with a saw.
	loc_brb_29_04 = "Amigos, coloquem algumas pastas de termites na porta do cofre, yeah?",--Friends, get some thermite on that vault door, yeah?
	loc_brb_25_03 = "Amigos, vocês terão que trazer aquela furadeira para a sala do cofre.",--Friends, you're going to need to bring that drill into the vault room.
	loc_brb_12_02 = "Certo, amigos, removam a serra agora.",--OK, friends, now remove that saw.
	loc_brb_25_02 = "Vocês precisam trazer aquela furadeira térmica pra dentro da sala do cofre, yeah?",--You need to bring that thermal drill into the vault room, yeah?
	loc_brb_49_02 = "Amigos, parece que estamos no lugar certo!",--Looks like we're in the right place, friends!
	loc_brb_06_03 = "Selado, puta que pariu! Certo, tem um andaime lá fora, usem ele para subir no segundo andar. Encontrem uma porta que pode ser arrombada com uma serra, para entrar na sala do cofre.",--Sealed up, donnerse! OK, there's a scaffolding outside, use it to get up to the second floor. Find a door to crack open with a saw, to get into the vault room.
	loc_brb_26_01 = "Amigos, como estão indo com aquela furadeira?",--How are you coming along with that drill, friends?
	loc_brb_25_01 = "Amigos, levem aquela furadeira para dentro da sala do cofre!",--Take that drill inside to the vault room, friends!
	loc_brb_42_01 = "Enquanto estão esperando pela porta do cofre, talvez também seja bom tentarem abrir as caixas de depósito. Elas são Titans, então não conseguirão cortar elas com as serras.",--While you're waiting on that vault door, might as well have a go at those safe deposit boxes. They're Titans, so you will not be able to just cut through.
	loc_brb_27_04 = "Religuem a furadeira, yeah?",--Restart the drill, yeah?
	loc_brb_29_02 = "Amigos, usem o termite que enviei para enfraquecer a porta do cofre.",--Use the thermite I sent to weaken that vault door, friends.
	loc_brb_52_04 = "Amigos, não posso tirá-los daí até que vocês tenham passado por aquele chão.",--I can't pull you out of there until you've got through that floor, friends.
	loc_brb_55_02 = "Não fiquem muito tempo, amigos. Estou vendo muitas conversas nos canais da Murkywater. Parece que eles estão nos rastreando.",--Don't stray too long though, friends. I'm seeing a lot of chatter in Murkywater channels. Looks like they're tracking us.
	loc_brb_21_02 = "...Desculpe amigos, mas tive que colocá-lo no sky-rocket [Banheiro Portátil] lá fora no Canteiro de Obras... vocês podem chamá-los de porta-pinico, yeah?",--...sorry friends, but I had to put it in the sky-rocket [portable toilet] out by the construction site... you call them porta-potties, yeah?
	loc_brb_02_03 = "...Policiais estão logo ali virando a esquina, amigos.",--...Kerels right around the corner, friends.
	loc_brb_46_03 = "Ah! Entrem na sala do cofre, amigos! Quase acabamos aqui!",--Ah! Get inside that vault, friends! Almost done here!
	loc_brb_15_01 = "Certo, agora entrem na sala do cofre.",--OK, now get into the vault room.
	loc_brb_34_01 = "Achhh! Mais idiotices! O entregador derrubou as partes do guincho por todo o lugar. Vocês precisarão procurar elas amigos.",--Achhh! MORE domkops! Courier dropped the winch parts all around. You'll need to look for them friends.
	loc_brb_36_03 = "...Vocês precisam que levar todas as partes do guincho na sala do cofre e montá-la.",--...you gotta take all those winch parts into the vault room and assemble it.
	loc_brb_52_03 = "Aquele chão precisa ser explodido, yeah?",--That floor needs to be blown open, yeah?
	loc_brb_34_02 = "O maldito entregador jogou as partes por todo o lugar. Desculpe amigos, mas vocês terão que juntá-las.",--Blerrie courier threw the winch parts all around. Sorry, friends but you'll have to round them up.
	loc_brb_01_01 = "...Vocês tem um minuto até os policiais chegarem aí. Mantenham aqueles civis sob controle, yeah?",--...You got about a minute until the kerels get there. Keep those civvis under control, yeah?
	loc_brb_10_03 = "Esse parece um bom lugar para cortar, yeah?",--Looks like a good spot to cut, yeah?
	loc_brb_60_01 = "Vocês precisam ir, amigos!",--You need to leave, friends!
	loc_brb_20_03 = "O Velho Locke preparou para vocês um estoque com seus equipamentos, amigos.",--Old Locke has arranged a stash of gear for you,friends.
	loc_brb_49_03 = "Sem dúvidas, o Bain nos enviou ao banco certo, yeah?",--No question, Bain sent us to the right bank, yeah?
	loc_brb_56_02 = "Puta merda! Operadores da Murky estão na área. Cuidado com eles, amigos!",--Bliksem! Operatives from Murky are in the area. Watch out for them, friends!
	loc_brb_43_02 = "...Talvez alguém tenha esquecido um Cartão de Acesso ou algo assim.",--...Maybe someone forgot a keycard or something.
	loc_brb_57_02 = "Desculpe amigos, mas preciso tirá-los daí via esgotos. Levem eles para fora... e vocês irão precisar de um pouco de termite para derreter as grades.",--Sorry about this friends, but I've got to pull you out via the sewers. Get to them outside... and you'll need some thermite to burn through the grating.
	loc_brb_29_01 = "Certo, vocês precisam usar um pouco do termite que enviei nas dobradiças do cofre, yeah?",--Right, you need to use some of the thermite I sent on those vault hinges, yeah?
	loc_brb_05_02 = "A porta dos fundos parece boa. Arrombem ela com uma serra, amigos.",--Back door looks good. Crack it open with a saw, friends.
	loc_brb_15_03 = "Pefeito amigos! Agora entrem na sala do cofre.",--Perfect friends! Get into the vault room now.
	loc_brb_38_03 = "...Vocês precisam colocar aquele gancho no cofre.",--...You gotta get that hook onto the vault.
	loc_brb_60_04 = "Os policiais não irão parar de vir, então saiam daí, amigos!",--Kerels aren't going to stop coming, so get out of there, friends!
	loc_brb_53_03 = "É isso aí, yeah? Não consigo ver o que há de tão especial, mas é por isso que estamos aqui. Mesma escrita que o Lindenhurst achou.",--That's it, yeah? Can't see what's so special, but it's why we're here. Same writing that Lindenhurst found.
	loc_brb_20_01 = "Eu preparei para deixarem uns equipamentos para vocês, amigos.",--I've made arrangements to drop off some equipment for you, friends.
	loc_brb_54_01 = "Hora de partir daí. Peguem qualquer loot que conseguirem na saída.",--Time to get you out of there. Grab whatever loot you can on the way out.
	loc_brb_50_02 = "Esse belo piso de mármore precisará ter um grande buraco aberto nele. Nosso prêmio está debaixo dele, amigos.",--That nice marble floor has got to have a big hole blown into it. Our prize is right under there, friends. 
	loc_brb_11_03 = "Amigos, vocês precisam reiniciar a serra.",--You gotta restart the saw, friends.
	loc_brb_22_01 = "...Deem uma olhada nos cagadores no Canteiro de Obras lá fora, yeah?",--...have a look in the dumpers at the construction site outside, yeah?
	loc_brb_11_01 = "Amigos, vocês precisam reiniciar a serra.",--Friends, you need to restart the saw.
	loc_brb_11_02 = "A serra parou, reiniciem ela, yeah?",--The saw stopped, restart it, yeah?
	loc_brb_41_03 = "Os policiais desligaram o guincho!",--The coppers have taken the winch offline! 
	loc_brb_51_01 = "Talvez tenha mais C4 no estoque lá fora, amigos.",--There might be more c4 outside in the stash, friends.
	loc_brb_45_03 = "Vocês deveriam esconder aquele loot extra em algum lugar seguro, para que possam levá-lo com vocês quando sairem, yeah?",--You should probably stash that extra loot somewhere safe, so you can take it with you when you leave, yeah?
	loc_brb_31_02 = "Achhh! O entregador idiota esqueceu o guincho! Terei que levar um de trem a vocês. Fiquem olhando pra cima, yeah?",--Achhh! The paw-paw courier forgot the winch! I'll have to get one to you by train. Keep looking up, yeah?
	loc_brb_36_02 = "...Vocês precisam mover todas as partes do guincho para dentro do banco.",--...you need to move all parts of the winch into the bank.
	loc_brb_45_01 = "Amigos, vocês devem empilhar todo o loot em algum lugar próximo, para que possam movê-los mais tarde, yeah?",--Friends, you should pile all your loot somewhere close, so that you can move it later, yeah?
	loc_brb_14_01 = "Não esqueçam de explodir aquele chão, yeah?",--Don't' forget to blow up that floor, yeah?
	loc_brb_36_01 = "...Tragam todas as partes do guincho até a sala do cofre.",--...bring all the winch parts into the vault room.
	loc_brb_37_01 = "...Parafusem os parafusos no chão, yeah.",--...screw the bolts into the floor, yeah.
	loc_brb_07_03 = "Amigos, coloquem uma serra para funcionar em uma das portas nesse andar, yeah?",--Friends, get a saw going through one of the doors on this floor, yeah?
	loc_brb_28_03 = "Tem um pouco de charme nesses velhos cofres, né? Naquela época vocês não tinham porradas de coisas para entrar, apenas habilidade.",--There's a bit of charm in those old vaults, eh? Back then you didn't need loads of dingeses to get in, just craftsmanship.
	loc_brb_43_01 = "...Se acharem um Cartão de Acesso, será bem fácil abrir uma delas.",--...If you find a keycard, opening one up would be pretty easy
	loc_brb_23_02 = "...Vocês irão achá-lo no contêiner de lixo pelo estacionamento, amigos.",--...you'll find it in a trash contêiner by the parking lot, friends.
	loc_brb_27_01 = "Policiais chegaram até a furadeira!",--Coppers got to the drill!
	loc_brb_09_03 = "Vejam se conseguem achar um ponto fraco no segundo andar, yeah? Usem o andaime.",--See if you can find weak spot on the second floor, yeah? Use the scaffolding.
	loc_brb_35_01 = "Amigos, continuem procurando aquelas partes do guincho.",--Keep looking for those winch parts, friends.
	loc_brb_15_02 = "Maravilhoso! Agora, entrem na sala do cofre!",--Kiff! Now, get into that vault room!
	loc_brb_cnc_02 = "O Banco Brooklyn tem algo que precisamos, e pela primeira vez não é só o dinheiro!",--The Brooklyn Bank has got something we need, and for once it isn't just cash!
	loc_brb_01_03 = "...Mantenham aqueles civis sob controle, carros de polícia estão a cerca de um minuto, amigos.",--...Get those civvies under control, cop cars are about one minute out, friends.
	loc_brb_26_04 = "A furadeira não irá se mover sozinha, amigos.",--That drill isn't going to move itself, friends.
	loc_brb_54_03 = "Amigos, vocês podem começar a coletar loot extra se quiserem, é quase hora de vocês sairem daí, yeah?",--Start collecting extra loot if you want to friends, it's time to get you out of there, yeah?
	loc_brb_41_01 = "Caralho! Os policiais chegaram no guincho!",--Blerrie! The kerels got to the winch!
	loc_brb_42_03 = "Poderiam essas caixas de depósito ter alguns itens extra de valor que possamos usar, yeah? Talvez vocês possam mexer nelas enquanto esperam pela porta do cofre abrir?",--Could be those safe deposit boxes have some extra valuables we can use, yeah? Maybe you can get into them while you wait for the vault to open?
	loc_brb_cnc_03 = "Queridos amigos, nós iremos para Nova York para um trabalho rápido de banco.",--Dear friends, we're going to New York for a quick bank job. 
	loc_brb_14_02 = "O buraco no chão não vai aumentar sozinho, amigos!",--The hole in that floor isn't going to get bigger, by itself friends!
	loc_brb_37_02 = "...parafusos precisam ir no chão.",--...bolts need to go into the floor.
	loc_brb_00_03 = "Essa batida provavelmente acordou os mortos, yeah? Apressem-se e entrem naquele banco.",--That crash probably woke the dead, yeah? Hurry up and get inside that bank.
	loc_brb_15_04 = "Aí está. Agora deem uma olhada na sala do cofre, yeah?",--There you go. Now take a look inside the vault room,  yeah?
	loc_brb_20_02 = "Tem uma porrada de equipamentos esperando por vocês, amigos.",--There's a load of equipment waiting for you, friends.
	loc_brb_17_06 = "Vamos lá amigos, vocês realmente precisam abrir aquela porta.",--Come on friends, you really must get that door open.
	loc_brb_51_02 = "Vocês precisam de mais C4, deem uma olhada no estoque lá fora, yeah?",--If you need more c4, take a look in the stash outside again, yeah?
	loc_brb_57_01 = "Tenho alguém esperando por vocês lá fora nos esgotos. Vocês precisarão de um pouco de termite para passar.",--I've got someone waiting for you ouside in the sewers. You'll need some thermite to get through.
	loc_brb_02_01 = "...Policiais chegarão a qualquer momento.",--...Kerels will be there any second.
	loc_brb_17_03 = "Vocês precisam arrombar aquela porta, amigos.",--You gotta crack that door open, friends.
	loc_brb_41_04 = "Vocês precisam religar o guincho, amigos!",--You need to restart the winch, friends! 
	loc_brb_48_01 = "...Amigos se puderem peguem um pouco daquele ouro, mas lembrem-se que o dinheiro é secundário, yeah?",--...grab some of that gold if you can friends, but remember that money is secondary, yeah? 
	loc_brb_16_02 = "Talvez se livrar dessa lona, yeah?",--Maybe get rid of that tarp, yeah?
	loc_brb_28_02 = "Aquele cofre é uma coisa bonita, yeah?",--That vault is a thing of beauty, yeah? 
	loc_brb_19_03 = "Esse alarme irá trazer mais reforços porcos. Desliguem-no, yeah?",--That alarm is bringing in more porky reinforcements. Shut it down, yeah?
	loc_brb_cnc_01 = "Amigos, nós precisamos fazer um roubo a banco um pouco estranho, yeah?",--Friends, we need to do a bit of an unusual bank robbery, yeah?
	loc_brb_58_02 = "Amigos, o Twitch estará aí em breve com a van!",--Friends, Twitch will be there shortly with the van!
	loc_brb_33_02 = "O trem está quase chegando. 30 segundos.",--Train is almost there. 30 seconds.
	loc_brb_56_01 = "Porra! Operadores da Murkywater estão tentando bloquear a área, fiquem longe deles, yeah?",--Blerrie! Murkywater operatives are trying to block off the area, keep away from them, yeah?
	loc_brb_34_03 = "O entregador teve que jogar fora as partes, então vocês terão que andar em volta e achá-las, yeah?",--The courier had to throw out the parts, so you will have to go round and find them, yeah?
	loc_brb_40_04 = "Vocês deixaram o guincho quase pronto?",--You almost got that winch ready?
	loc_brb_23_03 = "...Meu entregador escondeu ele numa lixeira no estacionamento lá fora.",--...my courier hid it in a dumpster on the parking lot outside.
	loc_brb_51_03 = "Vocês podem pegar mais C4 lá fora se precisarem, yeah?",--You can go get more C4 outside if you need it, yeah?
	loc_brb_13_01 = "Agora explodam um belo buraquinho para poderem entrar na sala do cofre, yeah?",--Now you gotta blow a nice little hole to get into the vault room, yeah?
	loc_brb_03_02 = "Certo amigos, entrem na sala do cofre cortando aquela porta do bancário com uma serra.",--OK  friends, get into the vault room by cutting open that teller door with a saw.
	loc_brb_29_03 = "Um pouco de termite naquele cofre irá enfraquecer as dobradiças, yeah?",--Some thermite on that vault will weaken the hinges, yeah?
	loc_brb_05_03 = "Arrombem a porta dos fundos com uma serra e passem por lá, yeah?",--Crack open the back door with a saw and go through there, yeah?
	loc_brb_40_03 = "Como estão indo com esse guincho, amigos?",--How are you coming along with that winch, friends?
	loc_brb_10_01 = "Ótimo! Esse é o lugar. Cortem a camada de cima com uma serra, yeah?",--Lekker! That's the spot. Cut through the top layer with a saw, yeah?
	loc_brb_03_01 = "Parece que um bom ponto de entrada será a porta do bancário. Usem uma serra.",--Looks like a good entry point will be the teller door. Use a saw.
	loc_brb_27_02 = "Porra, os policiais pararam a furadeira, vocês precisam religá-la!",--Blerrie kerels stopped the drill, you gotta restart it!
	loc_brb_02_02 = "...Amigos, os policiais chegarão a qualquer momento agora.",--...Coppers incoming any second now, friends.
	loc_brb_44_02 = "...Talvez vocês possam abri-las com um computador, yeah?",--...Could maybe open them up with a computer, yeah?
	loc_brb_26_03 = "Vocês ainda precisam trazer a furadeira pra dentro, yeah?",--You still need to bring the drill inside, yeah?
	loc_brb_48_03 = "...O objeto no chão é a nossa prioridade principal, mas seria uma pena deixar todo esse belo ouro aí. Tragam um pouco se puderem, yeah?",--...the object in the floor is our main priority, but it's a shame to leave all that pretty gold here. Bring some with you if you can, yeah?
	loc_brb_13_03 = "Ótimo, agora vocês apenas precisam aumentar esse buraco para podermos entrar na sala do cofre.",--Kiff, now you just gotta make that hole bigger to get into the vault room.
	loc_brb_47_04 = "Se estiverem com pouco equipamento, voltem e verifiquem o ponto de entrega lá fora, yeah?",--If you're low on gear, go back and check the drop point outside, yeah?
	loc_brb_53_01 = "Isso é o que viemos buscar, amigos. Huh... tem um tipo de escrita que Lindenhurst desencriptou...",--That's what we're here for, friends. Huh.. same kind of writing that Lindenhurst decrypted...
	loc_brb_16_01 = "Tirem a lona daí, yeah?",--Take that tarp off there, yeah?
	loc_brb_09_01 = "Subam no segundo andar e procurem por uma fraqueza no chão ou algo parecido, yeah?",--Get up to the second floor and look for a weakness in the floor or something, yeah?
	loc_brb_10_02 = "Aí está, amigos. Esse é um bom lugar para cortar.",--There we go, friends. That's a good spot to cut through.
	loc_brb_60_03 = "Não esperem muito tempo, yeah?",--Don't wait around too long, yeah?
	loc_brb_17_04 = "Não esqueçam a porta, yeah?",--Don't' forget the door, yeah?
	loc_brb_11_04 = "A serra não está funcionando, vocês precisam ligá-la novamente.",--The saw isn't working, you need to get it going again.
	loc_brb_47_03 = "Pode ter mais equipamento no ponto lá fora, amigos.",--There could be more equipment in the drop outside, friends.
	loc_brb_33_01 = "30 segundos até o trem chegar, amigos.",--30 seconds until the train arrives, friends.
	loc_brb_07_02 = "Vocês provavelmente podem cortar umas das portas nesse andar com uma serra, yeah?",--You can probably hack through one of the doors on this floor with a saw, yeah?
	loc_brb_31_03 = "O entregador idiota não escondeu o guincho! Ele vai ter o dele depois. Certo amigos, terei um chegando em breve de trem.",--Domkop courier didn't stash the winch! He's gonna get it later. Ok friends, I'll have one coming shortly by train. 
	loc_brb_24_01 = "Se precisarem de mais equipamento, deem outra olhada no ponto de entrega, amigos.",--If you need more gear, have another look at the drop site, friends.
	loc_brb_19_01 = "Mais policiais chegarão a não ser que desliguem aquele alarme.",--More coppers are going to arrive unless you shut that alarm off.
	loc_brb_48_02 = "...Aquele ouro faria um bom bônus. Amigos tragam alguns com vocês se puderem, mas lembrem-se do porque viemos aqui.",--...that gold would make a nice bonus. Bring some with you if you can friends, but remember why we're here.
	loc_brb_18_03 = "Aquele alarme precisa ser silenciado. Encontrem a chave dele por aí, yeah?",--That alarm needs to go quiet. Find the switch for it around there, yeah?
	loc_brb_05_01 = "Amigos, provavelmente será melhor entrarmos pela porta dos fundos com uma serra, yeah?",--Friends, it's probably best to go in through the back door with a saw, yeah?
	loc_brb_18_01 = "Provavelmente é uma boa ideia desligar o alarme. Tem um botão para isso em algum lugar.",--Probably a good idea to shut off that alarm. There's a button for it somewhere.
	loc_brb_cbf_01 = "Queridos amigos, nós iremos voltar para Nova York. Tem algo enterrado na fundação do velho Banco Brooklyn que o Bain estava atrás. Pode ter uma maneira de sairmos dessa fria que entramos. Enquanto estamos aqui, talvez seja uma boa ideia pegar um dinheiro extra para nos manter funcionando. Posso dizer que substituir todo o equipamento do Bain não será barato, e a coisa que tenho rodando como backup não irá segurar muito tempo, yeah? No momento, somos alvo fácil.",--Dear Friends, we're going back to New York. Theres something buried in the foundation of the old Brooklyn Bank that Bain was after. Could be a way out of this current predicament we're in. While we're there, it might be a good idea to pick up some extra operating cash to keep us going. Replacing all of Bain's equipment isn't going to be cheap I can tell you, and the stuff I've got running as backup isn't going to hold up for long, yeah? At the moment, we're open targets.
	loc_brb_45_02 = "Coloquem o loot que vocês acharem em algum lugar perto, para que vocês possam coletá-lo mais tarde, yeah?",--Put all the loot you find somewhere close, so you can collect it later, yeah?
	loc_brb_33_03 = "Não vai demorar muito agora amigos. O trem chegará em meio minuto.",--Not long now friends. Train will be there in half a minute.
	loc_brb_19_02 = "Desativem o alarme, amigos.",--Take down the alarm, friends. 
	loc_brb_59_03 = "Amigos, tirem essa merda de veículo do caminho, yeah?",--Friends, get that blerrie vehicle out of the way, yeah?
	loc_brb_18_02 = "Vocês precisam desligar o alarme. Encontrem o botão, yeah?",--You guys need to shut that alarm down. Find the button, yeah?
	loc_brb_38_02 = "...O gancho precisa ir no cofre, yeah?",--...The hook needs to go on the vault, yeah?
	loc_brb_01_02 = "...Policiais estão a caminho em carros de patrulha, então não percam tempo, e mantenham esses civis fora do caminho, yeah?",--...Kerels are on route in squad cars, so don't dawdle, and keep those civvies out of your way, yeah?
	loc_brb_32_01 = "O guincho chegará em um minuto, amigos.",--The winch will be there in one minute, friends.
	loc_brb_60_02 = "Saiam daí, yeah?",--Get out of there, yeah?
	loc_brb_12_01 = "Tirem essa serra daí, amigos.",--Get that saw off there, friends.
	loc_brb_26_02 = "Não esqueçam a furadeira, amigos.",--Don't forget the drill, friends.
	loc_brb_06_02 = "Não podemos entrar por esse caminho, yeah? Tem um andaime lá fora. Deve ter uma porta no segundo andar que vocês possam cortar com uma serra.",--Not getting in that way, yeah? There's scaffolding on the outside. Should be a door on the 2nd floor you can hack through with a saw. 
	loc_brb_54_02 = "Certo, amigos, é hora de partir. Levem um pouco de loot extra com vocês se puderem.",--OK, friends, it's time for you to leave. Take some extra loot with you if you can.
	loc_brb_49_01 = "Hora de pegar o que viemos buscar, yeah?",--Time to get what we came here for, yeah?
	loc_brb_03_03 = "Arrombem essa porta com uma serra, amigos.",--Crack open that door with a saw, friends.
	loc_brb_12_03 = "Boa, agora tirem a serra.",--Good, now take the saw off.
	loc_brb_39_01 = "...Liguem o guincho e deixem ele trabalhar. Mantenham os policiais longe, yeah?",--...Start the winch and let it work. Keep the kerels away, yeah?
	loc_brb_04_03 = "Parece que vocês terão que ir pela porta dos fundos. Usem uma serra para arrombá-la, yeah?",--Looks like you're going to have to go in through the back door. Use a saw to crack it open, yeah?
	loc_brb_07_01 = "Este andar deve ter uma porta acessível.... se vocês usarem uma serra, yeah?",--This floor should have an accessible door... if you use a saw, yeah?
	loc_brb_17_01 = "Vocês precisam atravessar aquela porta.",--You gotta get through that door.
	loc_brb_56_03 = "Amigos, operadores da Murkywater estão na área. Como eles encontraram a gente?",--Friends, Murkywater operatives are in the area. How did they find us? 
	loc_brb_59_02 = "Achh! Aquele veículo precisa ser removido!",--Achh! That vehicle has got to be removed!
	loc_brb_46_01 = "Maravilha! Agora vão dar uma olhada dentro, yeah?",--Kiff! Now go and have a look inside, yeah?
	loc_brb_end_01 = "Bem feito, queridos amigos. Ainda estamos com muitos problemas mas o velho Locke irá cuidar de vocês, yeah? Sei que fiz umas promessas, e ainda estou trabalhando em pegar as respostas. Estou cobrando todos os meus favores para esse aqui. Tenho que pagar a Butcher também - não queremos ela no nosso pé depois do Alaska. Deem uma respirada, enquanto o Sr. Lindenhurst tenta descobrir o que há de tão especial sobre esse medalhão. Tenho o pressentimento de que isso é só a ponta do iceberg, yeah?",--Nicely done, dear friends. We're still in a lot of trouble but old Locke is going to take care of you, yeah? I know I made some promises, and I'm still working on getting answers. Calling in all my favors for this one. Gotta pay off the Butcher too- don't want her nipping at our heels after Alaska. Have a short breather, lay low for a bit, while Mr Lindenhurst tries to figure out what's so special about this medallion dinges. I got a feeling that we haven't even cut through the frosting on this cake, yeah?
	loc_brb_22_02 = "...Ele foi deixado nos recipientes no Canteiro de Obras. Vão lá e peguem-no.",--...it got dumped in the contêiners at the construction site. Go out and get it.
	loc_brb_42_02 = "Essas caixas de depósito talvez contenham um belo bônus. Por que não dão uma olhada enquanto esperam? Entretanto são portas Titan, então vocês não podem apenas cortas elas.",--Those safe deposit boxes might contain a nice bonus. Why not have a look while you're waiting? Titan doors though, so you can't just cut them open.
	loc_brb_17_05 = "Ei, vocês podem atirar nos policiais depois. Arrombem aquele porta.",--Hey, you can shoot coppers later. Get that door cracked.
	loc_brb_35_02 = "Não esqueçam de nenhuma parte daquele guincho, yeah?",--Don't forget any parts of that winch, yeah?
	loc_brb_35_03 = "Amigos, vocês precisam pegar todas as partes do guincho.",--You need to get all the winch parts, friends.
	loc_brb_46_02 = "Aí está, amigos! Agora deem uma olhada dentro daquele cofre!",--There you go, friends! Now have a look inside that vault!
	loc_brb_32_02 = "Tenho o seu guincho chegando em volta de 60 segundos.",--Got your winch incoming in about 60 seconds.
	loc_brb_57_03 = "Façam o caminho de vocês para fora e desçam para os esgotos. Vocês precisarão de um pouco de termite para cortar as grades, yeah?",--Make your way outside and go down into the sewers. You'll need a bit of thermite to cut through the grating, yeah?
	loc_brb_47_01 = "Se precisarem de mais suprimentos, ainda deve ter mais lá fora.",--If you need more supplies, there should still be more outside.
	loc_brb_12_04 = "Vocês precisam remover a serra, yeah?",--You gotta remove that saw, yeah?
	loc_brb_31_01 = "Idiota filho da puta! O entregador esqueceu o guincho! Certo amigos, em breve enviarei esse de trem.",--Blerrie paw-paw! The courier forgot the winch! Ok friends, I'll have one coming by train shortly.
	loc_brb_59_01 = "Porra! Vocês vão ter que tirar esse veículo do caminho!",--Blerrie! You gotta get that vehicle out of the way!
	loc_brb_44_03 = "...Computadores do banco devem ser capaz de abri-los, yeah?",--...Bank computers should be able to open them up, yeah?
	loc_brb_38_01 = "Agora, vocês precisam conectar o gancho na porta do cofre.",--...Now, you gotta connect the hook to the vault door.
	loc_brb_37_03 = "...Apertem bem aqueles parafusos amigos.",--...tighten those bolts down friends.
	loc_brb_30_01 = "A termite acabou. Queimou bem através daquilo, yeah? Agora sigam com o guincho.",--Thermite is done. Burned right through that nicely, yeah? Now get going with the winch.
	loc_brb_27_05 = "Amigos, a furadeira precisa de atenção!",--The drill needs some attention, friends!
	loc_brb_16_03 = "Talvez seja uma boa ideia tirar aquela lona.",--Might be a good idea to get that tarp off.
	loc_brb_43_03 = "...Um Cartão de Acesso poderia abrir um.",--...A keycard could probably open one.
	loc_brb_40_02 = "Vocês precisam montar aquele guincho.",--You gotta get that winch assembled.
	loc_brb_23_01 = "...Ele está esperando por vocês em uma lixeira no estacionamento.",--...it's waiting for you in a dumpster out by the parking lot.
	loc_brb_13_02 = "Pronto, agora é hora de explodir um buracão no chão antigo, yeah?",--There, now it's time to blow a big hole in that antique floor, yeah?
	loc_brb_21_01 = "...Deem uma olhada lá fora no banheiro portátil no Canteiro de Obras.",--... take a look outside in the portable toilet at the construction site.
	loc_brb_30_03 = "Certo, o termite acabou. Lindo mas nojento. Agora montem o guincho, yeah?",--OK, the thermite is through. Nasty but beautiful. Now set up the winch, yeah?
	loc_brb_00_02 = "Pegaram todo o dinheiro daquele veículo, yeah? Hora de dar uma olhada dentro do banco. Sejam rápidos, amigos.",--Got your money's worth out of that vehicle, yeah? Time to go have a look inside the bank. Make it quick, friends.
	loc_brb_52_01 = "Amigos, vocês precisam abrir aquele andar!",--You gotta get that floor open, friends!
	loc_brb_22_03 = "...Vocês irão achar ele em uma lixeira lá fora pelo Canteiro de Obras, amigos.",--...you will find it in a dumpster out by the construction site, friends.
	loc_brb_24_02 = "Amigos, tem mais equipamento lá fora se precisarem.",--There's more gear outside if you need it, friends.
	loc_brb_00_01 = "Certo, amigos não temos muito tempo até os policiais chegarem aí. Então vão dar uma olhada dentro do banco.",--OK, friends not much time until the coppers get there. Go have a look inside the bank.
	loc_brb_08_02 = "Amigos, não temos como passar por aquela porta, yeah? Subam para o segundo andar usando o andaime lá fora. Vejam se conseguem achar uma área fraca no andar ou algo assim.",--Friends, there's no going through that door, yeah? Get up to the second floor using the scaffolding outside. See if there's a weak area in the floor or something.
	loc_brb_08_03 = "Não passaremos por essa coisa aqui. Tem um andaime lá fora. Vejam se conseguem achar um ponto fraco no segundo andar, yeah?",--No getting through that donnerse here. There's a scaffolding outside. See if you can find weak spot on the second floor, yeah?
	loc_brb_09_02 = "Subam para o segundo andar usando o andaime. Vejam se conseguem achar um ponto fraco no andar ou algo parecido.",--Get up to the second floor using the scaffolding. See if there's a weak area in the floor or something.
	loc_brb_17_02 = "Não esperem muito tempo com essa porta, amigos.",--Don't wait too long with that door, friends.
	loc_brb_21_03 = "...Por algum motivo, meu entregador achou que seria melhor esconder ele nos banheiros portáteis no Canteiro de Obras aí perto.",--...for some reason, my courier thought it best to hide it in the portable toilets at the construction site nearby.
	loc_brb_27_03 = "A furadeira parou amigos, vocês precisam religá-la.",--Drill has been stopped friends, you gotta restart it.
	loc_brb_41_02 = "O guincho foi parado pelos policiais! Religuem ele, yeah?",--Winch has been stopped by kerels! Restart it, yeah?
	loc_brb_44_01 = "...Talvez seja possível hackeá-los com os computadores do banco, yeah?",--...Might be able to hack them with bank computers, yeah?
	
	-- Objetivos
	hud_heist_brb_27 = "A serra terminou. Remova-a!",--The saw has finished. Remove it!
	hud_heist_brb_13 = "Leve todas as partes do guincho para o cofre e monte-as!",--Take all the winch parts to the vault and set them up!
	hud_heist_brb_15 = "Conecte o gancho do guincho na porta do cofre!",--Connect the winch hook to the vault door!
	hud_heist_brb_13_hl = "Monte o Guincho",--Set up the winch
	hud_heist_brb_33 = "Mantenha a polícia longe do cortador ou eles irão para-lo!",--Keep police away from the cutter or they will stop it!
	hud_heist_brb_29_hl = "Reinicie o Cortador",--Restart the cutter
	hud_heist_brb_03_hl = "Serre a Porta",--Saw open the door
	hud_heist_brb_30 = "A furadeira parou. Religue-a!",--The drill has stopped. Restart it!
	hud_heist_brb_11_hl = "Coloque a Furadeira no Cofre",--Place the drill on the vault
	hud_heist_brb_07_hl = "Entre na Sala do Cofre",--Enter the vault room
	hud_heist_brb_16_hl = "Inicie o Guincho",--Start the winch
	hud_heist_brb_23_hl = "Pegue o Medalhão",--Take the medallion
	hud_heist_brb_11 = "Perfure através da porta do cofre usando a Furadeira Térmica.",--Drill through the vault door using the Thermal Drill.
	hud_heist_brb_20 = "Impessa os policiais de pararem a furadeira.",--Keep the cops from stopping the drill.
	hud_heist_brb_23 = "Pegue o medalhão da caixa dentro do chão.",--Take the medallion from the box inside the floor.
	hud_heist_brb_21_hl = "Inspecione o Cofre",--Inspect the vault
	hud_heist_brb_22_hl = "Exploda o Chão",--Blow up the floor
	hud_heist_brb_10 = "Coloque a termite no cofre para derreter as dobradiças da porta.",--Put thermite on the vault to melt the door hinges.
	hud_heist_brb_22 = "Hora de pegar aquilo que viemos buscar; coloque alguns C4 e exploda aquele chão!",--Time to get what we came for; place some C4 and blow open that floor!
	hud_heist_brb_27_hl = "Remova a Serra",--Remove the saw
	hud_heist_brb_19 = "Mantenha os policiais longe do cofre!",--Keep the cops away from the vault!
	hud_heist_brb_26_hl = "Pegue mais Loot ou Fuja",--Loot more or escape
	hud_heist_brb_04_hl = "Corte um Buraco no Chão",--Cut a hole in the floor
	hud_heist_brb_26 = "Fique por aí e pegue mais objetos de valor ou fuja!",--Hang around and gather more valuables or escape!
	hud_heist_brb_06_hl = "Exploda o Chão",--Blow open the floor
	hud_heist_brb_08 = "Desative a segurança para abrir as persianas!",--Disable the security to open up the shutters!
	hud_heist_brb_30_hl = "Religue a Furadeira",--Restart the drill
	hud_heist_brb_20_hl = "Defenda a Furadeira",--Defend the drill
	hud_heist_brb_19_hl = "Defenda o Cofre",--Defend the vault
	hud_heist_brb_28 = "A serra parou. Religue-a!",--The saw has stopped. Restart it!
	hud_heist_brb_32_hl = "Espere pelas Partes do Guincho",--Wait for the winch parts
	hud_heist_brb_29 = "O cortador parou. Religue-o!",--The cutter has stopped. Restart it!
	hud_heist_brb_05_hl = "Remova o Cortador",--Remove the cutter
	hud_heist_brb_08_hl = "Desative as Persianas de Segurança",--Disable the security shutters
	hud_heist_brb_33_hl = "Defenda o Cortador",--Defend the cutter
	hud_heist_brb_12_hl = "Colete as Partes do Guincho",--Collect the winch parts
	hud_heist_brb_09 = "Retire o equipamento que o Locke arranjou.",--Retrieve the equipment Locke has arranged.
	hud_heist_brb_01 = "Entre no Banco Brooklyn.",--Get inside the Brooklyn Bank.
	hud_heist_brb_07 = "Entre na sala do cofre!",--Go inside the vault room!
	hud_heist_brb_25_hl = "Espere pela Van",--Wait for the van
	hud_heist_brb_12 = "Procure próximo a ponte do trem pelas partes do guincho.",--Look around outside near the train bridge for winch parts.
	hud_heist_brb_01_hl = "Entre no Banco",--Enter the bank
	hud_heist_brb_15_hl = "Conecte o Guincho ao Cofre",--Connect the winch to the vault
	hud_heist_brb_17_hl = "Defenda o Guincho",--Defend the winch
	hud_heist_brb_10_hl = "Coloque o termite no Cofre",--Place the thermite on the vault
	hud_heist_brb_14 = "Parafuse o guincho no chão!",--Screw the winch down to the floor!
	hud_heist_brb_21 = "Entre e inspecione o cofre.",--Go inside and inspect the vault.
	hud_heist_brb_04 = "Use a serra para cortar um buraco na parte fraca do chão!",--Use the saw to cut a hole at the weak spot of the floor!
	hud_heist_brb_24_hl = "Abra os Esgotos",--Open the sewers
	hud_heist_brb_18_hl = "Defenda a Serra",--Defend the saw
	hud_heist_brb_25 = "Espere o Twitch chegar e pegá-los com a van.",--Wait for Twitch to come and pick you up with the van.
	hud_heist_brb_05 = "Pegue o cortador do chão para continuar!",--Take the cutter from the floor to continue!
	hud_heist_brb_32 = "As partes do guincho estão vindo de trem; elas chegarão em breve!",--The winch parts are coming by train; they will be there soon!
	hud_heist_brb_16 = "Inicie o motor do guincho para arrancar a porta do cofre.",--Start the winch motor to pull open the vault door.
	hud_heist_brb_14_hl = "Proteja o Guincho",--Secure the winch
	hud_heist_brb_18 = "Mantenha os policiais longe da serra!",--Keep the cops away from the saw!
	hud_heist_brb_06 = "Use o C4 para criar um buraco no chão fraco!",--Use the C4 to blow a hole in the weakened floor!
	hud_heist_brb_02 = "Use o andaime exterior para chegar ao segundo andar.",--Use the exterior scaffolding to reach the second floor.
	hud_heist_brb_31_hl = "Religue o Guincho",--Restart the winch
	hud_heist_brb_24 = "Use a termite para derreter as grades dos esgotos.",--Use thermite to melt through the sewer grating.
	hud_heist_brb_09_hl = "Retire o Equipamento",--Retrieve the equipment
	hud_heist_brb_17 = "Impessa os policiais de pararem o guincho.",--Keep the cops from stopping the winch.
	hud_heist_brb_31 = "O guincho parou. Religue-o!",--The winch has stopped. Restart it!
	hud_heist_brb_02_hl = "Inspecione o Segundo Andar",--Inspect the second floor
	hud_heist_brb_03 = "Use a serra para cortar a porta.",--Use the saw to cut the door open.
	hud_heist_brb_28_hl = "Religue a Serra",--Restart the saw
		}