Hooks:Add("LocalizationManagerPostInit", "mercadonegro", function(loc)
	LocalizationManager:add_localized_strings({
	-- ARMADURAS
	bm_menu_skill_locked_level_7 = "Requer a Habilidade Iron Man",
	
	-- INVENTÁRIO GERAL
	menu_sort_alphabetic = "Alfabético",
	steam_inventory_quality = "Qualidade:",
	steam_inventory_rarity = "Raridade:",
	steam_inventory_mods_included = "Modificações inclusas",
	bm_global_value_pd2_clan = "Comunidade",
	bm_menu_global_event = "Evento",
	bm_global_value_collaboration = "Colaboração",
	bm_menu_page = "Página $page",
	st_menu_value = "Valor",
	dialog_bm_purchase_mod = "Você realmente deseja comprar $item?",--Do you really want to buy $item;?
	dialog_bm_purchase_coins = "Isso irá custar para você $money Moedas Continentais.",--It will cost you $money; Continental Coins.
	dialog_blackmarket_mod_remove = "Você está prestes a remover a modificação $mod de sua arma.",--You are about to remove modification $mod; from your weapon.
	dialog_blackmarket_lost_mods_warning = "(Suas modificações removidas serão colocadas no seu inventário)",--(Your removed modifications will be placed in the inventory)
	dialog_weapon_cosmetics_add = "Você está prestes a aplicar a skin de arma $cosmetic em sua arma.",--You are about to apply weapon skin $cosmetic; to your weapon.
	dialog_weapon_cosmetics_replace = "Isso irá trocar a sua atual skin de arma $cosmetic.",--This will replace your current weapon skin $cosmetic;.
	dialog_blackmarket_mod_add = "Você está prestes a adicionar a modificação $mod em sua arma.",--You are about to add modification $mod; to your weapon.
	dialog_blackmarket_mod_cost = "Isso irá custar para você $money.",--This will cost you $money;.
	menu_locked = "BLOQUEADO",--LOCKED
	
	-- ARMAS
	bm_menu_blackmarket_title = "Mercado Negro: $item",--Blackmarket: $item;
	bm_menu_item_amount = "Em Estoque: $amount",--In stock: $amount;
	bm_menu_chosen = "Marcado",--Selected
	bm_menu_preview_mods = "Visualizar os Mods",--Preview Mods
	bm_menu_mod_preview = "Visualizar Mod",--Mod Preview
	bm_menu_cannot_buy_weapon_slot = "Fundos Insuficientes",--Insufficient funds
	bm_menu_locked_weapon_slot_desc = "Esse slot de arma precisará ser desbloqueado antes que você possa colocar qualquer arma aqui!",--This weapon slot needs to be unlocked before you can place any weapons here!
	bm_menu_customizable_weapon_color = "Cor Customizada",
	bm_menu_btn_customize_weapon_color = "Customizar Cor",
	bm_menu_customizable_weapon_color_desc = "Adiciona uma Cor Customizada em sua arma.",--Add a custom color to your weapon
	bm_menu_weapon_cosmetics = "Skin da Arma",
	bm_menu_ammo = "Munição",--Ammunition
	bm_menu_barrel = "Cano",--Barrel
	bm_menu_barrel_ext = "Ext. de Cano",--Barrel Ext
	bm_menu_custom = "Modo de Tiro",--Custom
	bm_menu_foregrip = "Punho da Frente",--Foregrip
	bm_menu_bipod = "Bipé",--Bipod
	bm_menu_grip = "Punho",--Grip
	bm_menu_sight = "Mira",--Sight
	bm_menu_stock = "Coronha",--Stock
	bm_menu_upper_reciever = "Receptor Superior",--Upper Receiver
	bm_menu_lower_reciever = "Receptor Inferior",--Lower Receiver
	menu_assault_rifle = "Rifle de Assalto",--Assault Rifle
	menu_akimbo_pistol = "Akimbo Pistola",--Akimbo Pistol
	menu_wpn_special = "Especial",--Special
	bm_menu_btn_craft_mod = "Adicionar Modificação",--Craft modification
	bm_menu_btn_remove_mod = "Remover Modificação",--Remove modification
	bm_menu_btn_equip_weapon_cosmetic = "Aplicar Skin",--Apply Skin
	bm_menu_btn_remove_weapon_cosmetic = "Remover Skin",--Remove skin
	bm_menu_item_unlocked = "Disponível",--Available
	bm_menu_btn_buy_mod = "Comprar com Moedas Continentais",
	bm_wp_upg_a_custom_desc = "Grandes projéteis com muito mais poder de impacto.",--Bigger pellets with more impact.
	bm_wp_upg_a_explosive_desc = "Dispara um projétil explosivo que mata ou atordoa os alvos. Esse tipo de munição é raro de se encontrar.",--Fires one explosive charge that kills or stuns targets. This ammo type is harder to find.
	bm_wp_upg_a_piercing_desc = "Perfuração de armadura de longo alcance.",--Long range armor piercing.
	bm_wp_upg_a_slug_desc = "Dispara um único projétil que penetra a armadura corporal, inimigos, escudos e paredes.",--Fires a single lead slug that penetrates body armor, enemies, shields and walls.
	bm_wp_upg_a_slug2_desc = "Dispara um único projétil que penetra a armadura corporal, inimigos, escudos e paredes. Esse tipo de munição é raro de se encontrar.",--Fires a single lead slug that penetrates body armor, enemies, shields and walls. This ammo type is harder to find.
	bm_wp_upg_a_dragons_breath_desc = "Incendeia os projéteis que se espalham em faíscas e chamas. Queima através de escudos e armaduras corporais.",--Fires pellets that go up in sparks and flames. Burns through shields and body armor.
	bm_wp_upg_a_grenade_launcher_incendiary_desc = "Dispara um projétil que causa um verdadeiro incêndio no ponto de impacto.",--Fires a round that causes a fire at point of impact.
	bm_wpn_fps_upg_a_bow_explosion_desc = "Flecha com a ponta explosiva que detona no impacto.",--Arrow with an explosive tip that detonates on impact.
	bm_wp_ecp_m_arrows_explosive_desc = "Flecha com a ponta explosiva que detona no impacto.",--Arrow with an explosive tip that detonates on impact.
	bm_wp_elastic_m_explosive_desc = "Flecha com a ponta explosiva que detona no impacto.",
	bm_wp_bow_long_explosion_desc = "Flecha com a ponta explosiva que detona no impacto.",--Arrow with an explosive tip that detonates on impact.
	bm_wp_bow_long_poison_desc = "Flecha com a ponta envenenada que causa dano ao longo do tempo e ainda possui chance de interromper os inimigos.",--Arrow with a poison tip that does damage over time and has a chance to interrupt enemies.
	bm_wp_upg_a_bow_poison_desc = "Flecha com a ponta envenenada que causa dano ao longo do tempo e ainda possui chance de interromper os inimigos.",--Arrow with a poison tip that does damage over time and has a chance to interrupt enemies.
	bm_wp_ecp_m_arrows_poison_desc = "Flecha com a ponta envenenada que causa dano ao longo do tempo e ainda possui chance de interromper os inimigos.",--Arrow with a poison tip that does damage over time and has a chance to interrupt enemies.
	bm_wp_elastic_m_poison_desc = "Flecha com a ponta envenenada que causa dano ao longo do tempo e ainda possui chance de interromper os inimigos.",
	bm_wp_upg_a_crossbow_explosion_desc = "Dardo com a ponta explosiva que detona no impacto.",--Bolt with an explosive tip that detonates on impact.
	bm_wp_upg_a_arblast_explosion_desc = "Dardo com a ponta explosiva que detona no impacto.",--Bolt with an explosive tip that detonates on impact.
	bm_wp_upg_a_frankish_explosion_desc = "Dardo com a ponta explosiva que detona no impacto.",--Bolt with an explosive tip that detonates on impact.
	bm_wp_upg_a_arblast_poison_desc = "Dardo com a ponta envenenada que causa dano ao longo do tempo e ainda possui a chance de interromper os inimigos.",--Bolt with a poison tip that does damage over time and has a chance to interrupt enemies.
	bm_wp_upg_a_frankish_poison_desc = "Dardo com a ponta envenenada que causa dano ao longo do tempo e ainda possui a chance de interromper os inimigos.",--Bolt with a poison tip that does damage over time and has a chance to interrupt enemies.
	bm_wp_upg_a_crossbow_poison_desc = "Dardo com a ponta envenenada que causa dano ao longo do tempo e ainda possui a chance de interromper os inimigos.",--Bolt with a poison tip that does damage over time and has a chance to interrupt enemies.
	bm_wp_upg_lmg_lionbipod_desc_pc = "Implanta/Retira pressionando o botão $BTN_BIPOD.",--Deploy/Undeploy by pressing $BTN_BIPOD;.
	bm_mod_incompatibilities = "Esse mod é incompatível com: $quantifier $category!",--This mod is incompatible with $quantifier; $category;!
	bm_menu_disables_cosmetic_bonus = "Os Boosts desse Mod irá substituir os boosts das skins de armas.",--Boosts from this mod overwrite boosts from weapon skins.
	bm_wp_upg_bonus_team_exp_money_p3_desc = "+3% de Experiência & Dinheiro para você e o seu grupo.",--+3% Experience & money reward for you and your crew.
	bm_menu_conflict = "Essa modificação é incompatível com o(a) atual $conflict",--This modification is incompatible with your current $conflict;
	bm_wskn_tam_desc = "Essa skin de arma é uma recompensa de conquista, sendo assim não poderá ser trocada ou vendida.",--This weapon skin is an Achievement Reward, it cannot be traded or sold.
	bm_mod_equip_remove = "Equipar esse mod irá remover o seu $mod equipado!",--Equipping this mod will remove your equipped $mod;!
	bm_menu_wcc_not_owned = "NÃO POSSUI$NL;Para usar essa skin de arma você precisará encontrá-la no $safe, ou comprá-la no mercado da comunidade.",--NOT OWNED$NL;To use this weapon skin you must find it in a $safe;, or purchase it from the community marketplace.
	bm_wp_upg_fl_ass_laser_desc = "Ligue ou desligue pressionando o botão $BTN_GADGET.",--Turn it on/off by pressing $BTN_GADGET;.
	bm_wp_upg_fl_crimson_desc = "Ligue ou desligue pressionando o botão $BTN_GADGET.",--Turn it on/off by pressing $BTN_GADGET;.
	bm_wp_upg_fl_ass_peq15_desc = "Ligue ou desligue pressionando o botão $BTN_GADGET.",--Turn it on/off by pressing $BTN_GADGET;.
	bm_wpn_fps_upg_o_xpsg33_magnifier_desc = "Ligue ou desligue pressionando o botão $BTN_GADGET.",--Turn it on/off by pressing $BTN_GADGET;.
	bm_wp_pis_g_laser_desc = "Ligue ou desligue pressionando o botão $BTN_GADGET.",--Turn it on/off by pressing $BTN_GADGET;.
	bm_wp_upg_fl_ass_smg_sho_peqbox_desc = "Ligue ou desligue pressionando o botão $BTN_GADGET.",--Turn it on/off by pressing $BTN_GADGET;.
	bm_wp_upg_fl_ass_smg_sho_surefire_desc = "Ligue ou desligue pressionando o botão $BTN_GADGET.",--Turn it on/off by pressing $BTN_GADGET;.
	bm_wp_mp5_fg_flash_desc = "Ligue ou desligue pressionando o botão $BTN_GADGET.",--Turn it on/off by pressing $BTN_GADGET;.
	bm_wpn_fps_upg_o_45iron_desc = "Ligue ou desligue pressionando o botão $BTN_GADGET.",--Turn it on/off by pressing $BTN_GADGET;.
	bm_wpn_fps_upg_o_45rds_desc = "Ligue ou desligue pressionando o botão $BTN_GADGET.",--Turn it on/off by pressing $BTN_GADGET;.
	bm_wpn_fps_upg_o_45rds_v2_desc = "Ligue ou desligue pressionando o botão $BTN_GADGET.",--Turn it on/off by pressing $BTN_GADGET;.
	bm_wp_pis_ppk_g_laser_desc = "Ligue ou desligue pressionando o botão $BTN_GADGET.",--Turn it on/off by pressing $BTN_GADGET;.
	bm_wp_schakal_vg_surefire_desc = "Ligue ou desligue pressionando o botão $BTN_GADGET.",--Turn it on/off by pressing $BTN_GADGET;.
	bm_wp_upg_fl_ass_utg_desc = "Ligue ou desligue pressionando o botão $BTN_GADGET.",--Turn it on/off by pressing $BTN_GADGET;.
	bm_wp_upg_fl_pis_laser_desc = "Ligue ou desligue pressionando o botão $BTN_GADGET.",--Turn it on/off by pressing $BTN_GADGET;.
	bm_wp_upg_fl_pis_m3x_desc = "Ligue ou desligue pressionando o botão $BTN_GADGET.",--Turn it on/off by pressing $BTN_GADGET;.
	bm_wp_upg_fl_pis_tlr1_desc = "Ligue ou desligue pressionando o botão $BTN_GADGET.",--Turn it on/off by pressing $BTN_GADGET;.
	bm_wp_upg_fl_x400v_desc = "Ligue ou desligue pressionando o botão $BTN_GADGET.",--Turn it on/off by pressing $BTN_GADGET;.
	bm_wpn_fps_upg_o_45steel_desc = "Ligue ou desligue pressionando o botão $BTN_GADGET.",
	bm_wpn_fps_upg_o_sig_desc = "Ligue ou desligue pressionando o botão $BTN_GADGET.",
	bm_menu_btn_switch_reticle = "Trocar Retículo",--Switch reticle
	bm_menu_btn_customize_gadget = "Customizar Gadget",--Customize Gadget
	bm_menu_laser_hue = "Laser Matiz",--Laser Hue
	bm_menu_laser_sat = "Laser Saturação",--Laser Saturation
	bm_menu_laser_val = "Laser Valor",--Laser Value
	menu_reticle_type = "Tipo",
	menu_reticle_1_s = "Ponto 1",
	menu_reticle_1_m = "Ponto 2",
	menu_reticle_1_l = "Ponto 3",
	menu_reticle_2 = "Cruz 1",
	menu_reticle_3 = "Cruz 2",
	menu_reticle_4 = "Cruz 3",
	menu_reticle_5 = "Círculo 1",
	menu_reticle_6 = "Círculo 2",
	menu_reticle_7 = "Círculo 3",
	menu_reticle_8 = "Círculo 4",
	menu_reticle_9 = "Ângulo 1",
	menu_reticle_10 = "Ângulo 2",
	menu_reticle_11 = "Primeiro Círculo",
	menu_reticle_12 = "Plano",
	menu_reticle_13 = "Sol",
	menu_reticle_14 = "Caçador",
	menu_reticle_15 = "On/Off",
	menu_reticle_16 = "Cruz",
	menu_reticle_17 = "Insira Aqui",
	menu_reticle_18 = "Hashtag",
	menu_reticle_19 = "OVERKILL",
	menu_reticle_20 = "Starbreeze",
	menu_reticle_21 = "Vá se Fuder",
	menu_reticle_22 = "RocknRoll",
	menu_reticle_color = "Cor",
	menu_recticle_color_red = "Vermelho",
	menu_recticle_color_blue = "Azul",
	menu_recticle_color_green = "Verde",
	menu_recticle_color_yellow = "Amarelo",
	bm_menu_buy_weapon_title = "Comprar $weapon_category",--Buy $weapon_category;
	bm_menu_btn_buy_selected_weapon = "Comprar Arma",--Buy weapon
	bm_menu_locked_weapon_slot = "Slot de Arma Trancado",--Locked weapon slot
	bm_menu_level_req = "Trancado até o Level de Reputação $level",--Locked to reputation level $level;
	bm_menu_not_enough_cash = "Dinheiro Insuficiente",--Not enough cash
	bm_cs_not_enough_coins = "Moedas Continentais Insuficientes",--Not Enough Continental Coins
	bm_wp_upg_a_frankish_explosion = "Dardo Explosivo",--Explosive Bolt
	bm_wp_upg_a_arblast_explosion = "Dardo Explosivo",--Explosive Bolt
	bm_wp_upg_a_crossbow_explosion = "Dardos Explosivos",--Explosive Bolts
	bm_wp_upg_a_arblast_poison = "Dardo Envenenado",--Poison Bolt
	bm_wp_upg_a_frankish_poison = "Dardo Envenenado",--Poison Bolt
	bm_wp_ecp_m_arrows_explosive = "Flechas Explosivas",--Explosive Arrows
	bm_wpn_fps_upg_a_bow_explosion = "Flechas Explosivas",--Explosive Arrows
	bm_wp_elastic_m_explosive = "Flecha Explosiva",--Explosive Arrow
	bm_wp_bow_long_poison = "Flechas Envenenadas",--Poison Arrow
	bm_wp_ecp_m_arrows_poison = "Flechas Envenenadas",--Poison Arrow
	bm_wp_elastic_m_poison = "Flechas Envenenadas",--Poison Arrow
	bm_wp_upg_a_bow_poison = "Flecha Envenenada",--Poisoned Arrows
	bm_menu_bonus_recoil = "Estabilidade",--Stability
	bm_menu_bonus_spread = "Precisão",--Accuracy
	bm_wp_upg_bonus_team_exp_money_p3 = "Boost de Equipe",--Team Boost
	bm_menu_bonus_total_ammo = "Munição Total",--Total Ammo
	-- CUSTOM COLOR (COR CUSTOMIZADA)
	dialog_abort_weapon_color_customize = "Você tem certeza de que deseja voltar sem aplicar a sua configuração?",
	bm_global_value_collectable = "Coletável",
	menu_weapon_color_group_all = "Todas",
	menu_weapon_color_index_title = "Plano de Pintura",
	menu_weapon_color_index_1 = "Tático",
	menu_weapon_color_index_2 = "Núcleo",
	menu_weapon_color_index_3 = "Metal",
	menu_weapon_color_index_4 = "Orgânico",
	menu_weapon_color_index_5 = "Clássico",
	menu_weapon_color_index_6 = "Moderno",
	menu_weapon_color_index_7 = "Invertido",
	menu_weapon_color_index_8 = "Assalto",
	menu_weapon_color_index_9 = "Detalhado",
	menu_weapon_color_index_10 = "Mergulhado",
	menu_weapon_color_pattern_scale = "Tamanho do Desenho",
	menu_pattern_scale_small = "Pequeno",
	menu_pattern_scale_medium = "Médio",
	menu_pattern_scale_large = "Grande",
	menu_weapon_color_quality = "Qualidade",
	bm_menu_weapon_color_index = "Plano de Pintura: ##$variation##",
	bm_menu_weapon_color_quality = "Qualidade: ##$quality##",
	dialog_apply = "Aplicar",
	bm_menu_btn_clear_mod_preview = "Limpar Visualização",
	bm_menu_btn_stop_preview_weapon_cosmetic = "Parar Visualização da Skin de Arma",
	bm_menu_skirmish_content_reward = "Poderá ser desbloqueado jogando o modo de jogo Holdout",
	bm_menu_crimespree_content_reward = "Poderá ser desbloqueado jogando o modo de jogo Crimespree",
	
	-- MÁSCARAS
	bm_msk_character_locked = "Máscara do Personagem",--Character's Mask
	bm_msk_character_locked_desc = "Equipar esse Slot de Máscara vai fazer com que você use a máscara padrão do seu personagem favorito.",--Equipping this mask slot will make you wear your preferred character's mask.
	bm_menu_locked_mask_slot = "Slot de Máscara Trancado",--Locked mask slot
	bm_menu_cannot_buy_mask_slot = "Fundos Insuficientes",--Insufficient funds
	bm_menu_locked_mask_slot_desc = "Esse slot de máscara precisará ser desbloqueado antes que você possa colocar qualquer máscara aqui!",--This mask slot needs to be unlocked before you can place any masks here!
	bm_menu_customize_mask_title = "Customizar Máscara: $mask_name",
	bm_menu_color_a = "Cor Primária",
	bm_menu_color_b = "Cor Secundária",
	bm_menu_colors = "Cor",
	bm_menu_mask_colors = "Cores",
	menu_bm_not_selected = "Não Selecionado",
	bm_txt_no_color_full_material = "Apenas Material",
	menu_bm_total_cost = "Custo Total: $cost",
	bm_menu_missing_to_finalize_mask = "Você tem que escolher um(a) $missed_mods para finalizar a customização",
	bm_menu_dlc_locked = "Sem Acesso",
	menu_bm_highlighted = "Marcado",
	bm_menu_btn_choose_mask_mod = "Escolher $type",
	bm_menu_btn_customize_mask = "Finalizar Máscara",
	dialog_blackmarket_assemble_item = "Você realmente gostaria de pegar a máscara $item e colocá-la em seu inventário?",
	dialog_blackmarket_mask_sell_mod_readded = "$mod irá retornar para o seu inventário.",
	dialog_blackmarket_abort_mask_warning = "Sua máscara não foi finalizada. Voltar irá deixar a máscara inalterada.",
	dialog_blackmarket_slot_mask_remove = "Retornar a Máscara de volta para a loja? $suffix",
	bm_menu_btn_choose_color_a = "Escolher Cor Primária",
	bm_menu_btn_choose_color_b = "Escolher Cor Secundária",
	bm_menu_buy_mask_title = "Loja de Máscaras",
	
	-- DESCRIÇÃO DAS MÁSCARAS + EASTER EGGs (Descrições de Máscaras + Homenagens a jogadores participantes desse projeto e de outras lendas)
	bm_msk_lycanwulf_desc = '"Lycanwulf, Lycanwulf, Lycanwulf!" gritaram eles, os aldeões assustados, ao colocarem os olhos nessa abominação conhecida como Lycanwulf. Os humanos mesquinhos eram agora prisioneiros da besta, em uma prisão sem paredes, tetos ou chave, e tendo como única saída possível a morte.\n\n~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\n\nA Máscara mais utilizada pelo guerreiro lendário, HimuraBR, cujo poder não pode ser calculado.\nAgora é sério, galera.. sendo dono de uma vasta experiência em PAYDAY 2 e também o criador dessa tradução atual para o jogo, eu gostaria de agradecer a todos por estarem usando a tradução! <3\n\n- HimuraBR',--HimuraBR
	bm_msk_chico_desc = "Scarface veio para os Estados Unidos com nada mais nada menos do que as mãos vazias e uma péssima postura, a escuridão em seu coração correspondia ao brilho de sua mente criminosa. Sua máscara conta a história, completa com o rastro de sangue que ele deixou pelo caminho e que acabou por ser a sua marca.\n\n~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\n\nUso essa marca grandiosa do Scarface em meu perfil da Steam por muitos e muitos anos.. essa máscara dele tão épica que marcou minha história dentro do jogo também. Melhor DLC ever! :D\n\n- HimuraBR",--HimuraBR
	bm_msk_smo_01_desc = "Se você ver um assaltante vestindo essa máscara no meio da rua, saiba que ele não tem medo de nada. Nove vidas é o caralho!\n\n~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\n\nGatos são chatos as vezes, mas esse aqui, assalta bancos e mata policiais... e tem sangue na cara, é estilo mesmo!\n\n- gabsF",--gabsF
	bm_msk_card_joker_desc = "Um clássico transformado em máscara. O baralho de 52 cartas padrão é o mais utilizado hoje em dia e, independente se você for um novato ou um profissional, você irá reconhecer provavelmente essa face. Uma máscara facial de Pôquer apropriada.\n\n~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\n\nSenta que lá vem história, tinha acabado de lançar a Casa Branca, lá no Twitter, a tradução tava bem no comecinho, um dos moderadores notou a minha tradução pro Payday e me deu essa máscara. Obrigado, Tuffcooke. <3\n\n- gabsF",--gabsF
	bm_msk_msk_grizel_desc = "A Máscara da Clover representa o que ela mais tem medo e mais odeia - vestir uma máscara como se este fosse o seu rosto normal. O nariz defeituoso, os lábios de botox e essa expressão consumista e obsessora são todos símbolos de seus medos e fraquezas, misturadas em uma paródia de horror.\n\n~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\n\nMáscara e personagem utilizados por um grande mestre do Payday, moderador da comunidade e tradutor, que de dia era técnico do Liverpool e a tarde era técnico do Manchester City.\n\n- Lucas, the Klopp",--LucasKlopp
	bm_mega_clover_desc = "A Mega Clover Mask é uma versão evoluída da máscara original. Simboliza a transcendência e a catarse.$NL;$NL;Obrigado pelo seu apoio!$NL;$NL;OVERKILL saúda você!\n\n~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\n\nRelíquia do grande mestre do Payday que treinava o Liverpool e o Manchester City, que, utilizando esta máscara, um dia clamou pela contratação de Cantillo. Desde então, jaz a pergunta na humanidade: QUEM É CANTILLO?\n\n- Lucas, the Klopp",--LucasKlopp
	bm_cop_mega_skull_desc = "Nós nunca vamos entender a razão dos assaltantes hardcore não se autodenominarem Desejadores da Morte. Talvez seja algo bem legal.$NL;$NL;Obrigado pelo seu apoio!$NL;$NL;OVERKILL saúda você!\n\n~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\n\nPRESSIONE [F] PARA USAR O SACO DO DOUTOR\n\n- Kisuke",--Kisuke
	bm_msk_plague_desc = 'Uma máscara de médico da Peste Negra para o Mastermind.$NL;$NL;Nas palavras de Bhagavad-Gita: "Agora eu me tornei a Morte, destruidor de mundos."$NL;$NL;Ou pelo menos, essa era a direção de arte.$NL;$NL;Essa Máscara é uma recompensa da árvore de Infamy, por tanto não poderá ser recebida na tela de PAYDAY ou até mesmo ser vendida. Em vez disso, ela poderá ser devolvida ao seu estoque de máscaras gratuitamente, mas qualquer desenho, cor ou material que estiver na Máscara será perdido.\n\n~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\n\n"A obediência gera a disciplina, a disciplina gera a unidade e a unidade gera o poder, o poder é a própria vida. Se não lhe obedecerem, tire o poder deles, tire as suas vidas. Seja a morte, o destruidor de mundos!"\n\n- MrUmbrella',--MrUmbrella
	bm_msk_hoxton_glow_desc = 'A Mega Hoxton Mask é uma versão evoluída da máscara original. Simboliza a transcendência e a catarse.$NL;$NL;Obrigado pelo seu apoio!$NL;$NL;OVERKILL saúda você!\n\n~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\n\n"Mulher sem pau não é mulher"\n\n- DarkWubi',--DarkWubi
	bm_msk_hoxton_desc = "A Máscara do Hoxton.\n\n~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\n\nDarK odeia o HOUSTON!! :o\n\n- DarK",--DarK
	bm_msk_skm_08_desc = "Dizem que esse capacete foi encontrado em uma instalação nuclear russa abandonada, e quem a usar, iria ganhar super poderes com o tempo. Mas isso é apenas um boato.\n\n~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\n\nKatyusha ficaria orgulhosa se você fosse pra linha de frente do combate usando ela\n\n- EX Spetsnaz Hurêr",--Hurêr
	bm_mr_pickle_desc = "Máquina assassina enxuta, média e verde. A máscara perfeita para se usar quando estiver em apuros e para se dividir feito uma banana. Seja a água, meu amigo.\n\n~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\n\nDizem que essa máscara já foi utilizada por batatas de todas as gerações.. mas que agora virou um PEPINO!\n\n- BaTaTa",--BaTaTa
	bm_msk_aviator_desc = "Todo mundo adora um bom par de óculos de sol.$NL;$NL;Mas só os policiais mais arrogantes e mais procurados, malditos filhos da puta, são loucos o suficiente para roubar um maldito banco com eles.$NL;$NL;Essa Máscara é uma recompensa da árvore de Infamy, por tanto não poderá ser recebida na tela de PAYDAY ou até mesmo ser vendida. Em vez disso, ela poderá ser devolvida ao seu estoque de máscaras gratuitamente, mas qualquer desenho, cor ou material que estiver na Máscara será perdido.\n\n~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\n\nUma maneira de avisar que o pai tá ON.\n\n- Biel1421",--Biel1421
	
	-- ACHIEVEMENTS (CONQUISTAS REQUISITOS)
	bm_menu_milestone_reward_unlock = "Complete $NUM conquistas para desbloquear.",
	achievement_eng_1_desc = "Na Bank Heist ou na Jewelry Store, encontre e pegue o Bullet Trophy escondido cinco vezes.",
	achievement_eng_2_desc = "Na Shadow Raid ou na First World Bank, encontre e pegue o Robot Trophy escondido cinco vezes.",
	achievement_eng_3_desc = "Na GO Bank ou na Four Stores, encontre e pegue a Marine Trophy escondido cinco vezes.",
	achievement_eng_4_desc = "Na Diamond Store ou no dia 1 da Hoxton Breakout, encontre e pegue o Cultist Trophy escondido cinco vezes.",
	
		})
end)