Hooks:Add("LocalizationManagerPostInit", "SAYHELLOTOMYLITTLEFRIEND", function(loc)
	LocalizationManager:add_localized_strings({
	-- Nome e Descrição
	heist_friend_crimenet = "Tenho traficado armas no Caribe por um tempo. Tem sido muito lucrativo, mas alguns dos velhos traficantes da região não aprovam minha presença no mercado local. O Cartel Boliviano dos Sosa especificamente. Como eles não conseguem competir comigo em termos de qualidade, eles decidiram atacar minha operação, afundando um de meus navios, roubando minha mercadoria e matando meus operadores. Foi muito imprudente. Agora eles devem pagar! E vocês é quem vão cobrar o pagamento.. em sangue.$NL;$NL;» Ganhe Acesso à Mansão$NL;» Atraia Ernesto Sosa para fora e Mate-o$NL;» Abra o Cofre Escondido$NL;» Fuja com os ganhos",--I have been running guns in the Caribbean for a while. It's been very profitable, but some of the old movers in the region don't approve of my presence on the local market. The Bolivian Sosa Cartel specifically. As they could not compete with me on level terms, they decided to attack my operation - sinking one of my ships, stealing my merchandise and killing my operatives. That was very unwise. Now they must pay. You will collect that payment, in blood.$NL;$NL;» Gain access to the house$NL;» Draw Ernesto Sosa out and kill him$NL;» Open the hidden safe$NL;» Escape with the loot
	heist_friend_hl = "Scarface Mansion",
	heist_friend = "Scarface Mansion",
	heist_friend_hl_briefing = "Ernesto Sosa é o chefe local do Cartel Sosa em Miami, e a Butcher quer ele morto. Vocês vão adorar isso: Ele vive na antiga mansão de Tony Montana em Miami Beach. Isso mesmo - Scarface, o lendário traficante dos anos 80. Enfim, vocês precisam entrar na mansão, achar um caminho lá dentro e depois matar Ernesto Sosa. Não vai ser fácil, o lugar é tipo uma fortaleza, mas vocês conseguem. Ah sim, quase me esqueci - deve ter muito dinheiro e outras coisas naquela casa. Roubem tudo, limpem o lugar, mas o mais importante - Matem o Ernesto Sosa.",--Ernesto Sosa is the local boss in Miami for the Sosa Cartel, and The Butcher wants him dead. You're gonna love this: he lives in Tony Montana's old mansion in Miami Beach. Yeah that's right - Scarface, the legendary 80's drug lord. Anyway, you've got to hit the mansion, find a way in and then kill Ernesto Sosa. It won't be easy, the place is like a fortress. But you can do it. Oh yeah, I almost forgot - there should be a lot of money and other loot in that house. Steal it. Wipe them clean. But above all - kill Ernesto Sosa.
	
	-- Legendas
	pln_fri_intro_01 = "Ok time, vamos indo. A Butcher quer a coisa feita... lembrem-se, vocês precisam matar o Ernesto Sosa, e roubar o loot.",--Ok team, lets get a move on. The Butcher means business here... remember, you've got to kill Ernesto Sosa, and steal the loot.
	pln_fri_intro_02 = "Vamos logo pessoal. A Butcher quer esse cara morto, mas não se esqueçam, o lugar é cheio de riquezas também.",--Come on guys. The Butcher wants this guy dead, but don't forget, the house is full of riches too.
	pln_fri_intro_03 = "Poderia dizer que o Ernesto Sosa é sortudo de ter essa bela casa em Miami Beach. Mas sua sorte está pra mudar...",--You could say Ernesto Sosa is lucky to have this beautiful house in Miami Beach. But his luck is about to change...
	pln_fri_30_03 = "Ok! Hora da grana, pessoal. Vamos roubar o cofre de chão do Ernesto. Acoplem os guinchos no chão.",--Ok, time for the money, guys. We're gonna loot Ernesto's floor safe. Hook those winches up to the floor.
	pln_fri_51_01 = "Muito bem, bonito e silencioso. Assegure tudo o que conseguir, mas vamos precisar de pelo menos algumas bolsas pra valer a pena.",--Well done, nice and quiet. Secure everything if you can, but we need at least a few bags to make this worthwhile. 
	pln_fri_24_01 = "É suficiente. Agora coloque a Gasolina em cima e atire para acender!",--That's enough. Now put a gas can on it and shoot it to light it up!
	pln_fri_03_02 = "Precisamos daquele Pen Drive. Deve estar com o Chefe da segurança.",--We gotta get the USB stick. The head of security should have it.
	pln_fri_40_02 = "Ei, ali está ele. Parece que ele está no jardim.",--Hey, there he is. Looks like he's in the garden area.
	pln_fri_52_02 = "Se quiser levar as bolsas mais rápido, pode colocar uma tirolesa.",--If you want to move the bags faster, you can set up a zipline.
	pln_fri_34_01 = "Estamos perdendo tempo aqui! Coloque o guincho pra funcionar de novo!",--We're wasting time here! Get that winch going again!
	pln_fri_29_02 = "Ele vai ficar bem. Vamos roubar o lugar. Vamos pegar o cofre de chão dele. Tem alguns guinchos colocados perto da entrada da propriedade. Peguem eles e enganchem.",--This guy is doing well. Let's loot the place. We're gonna go for his floor safe. You've got some winches stashed near the entrance to the property. Get them and hook 'em up.
	pln_fri_35_01 = "Ok, agora proteja-os.",--Ok, protect them now.
	pln_fri_44_01 = "Esse é o Chefe da segurança. Ele parece estar nas escadas.",--That's the head of security. He seems to be at the stairs.
	pln_fri_54_01 = "Ei pessoal, mais alguns bandidos do Sosa estão vindo pra mansão! Vão chegar a qualquer minuto, espero que vocês não tenham largado corpos por aí.",--Hey guys, more Sosa thugs are on their way to the mansion! They'll be here any minute, I hope you don't have bodies lying around in the open.
	pln_fri_31_02 = "Vamos logo, acoplem esses guinchos! ",--Come on, get those winches hooked up!
	pln_fri_27_02 = "Bile? preciso que voe até aqui para mover alguns carros pra mim.",--Bile? I need you to fly in and move some cars for me.
	pln_fri_48_06 = "Três moscas na bunda do burro.",--Three flies are on the donkey's ass.
	pln_fri_45_02 = "Ei, ali está ele. Parece estar perto da entrada de automóveis.",--Hey, there he is. Looks like he's by the driveway.
	pln_fri_54_02 = "Acabei de ser informado que mais alguns bandidos do Sosa estão chegando na mansão para reforçar a segurança. É melhor o lugar estar limpo, ou vão percebê-lo quando chegarem.",--I just got some intel about another bunch of Sosa thugs arriving at the mansion to reinforce security. The area better be clean, or they'll be onto you when they arrive.
	pln_fri_50_03 = "Deve ter um mecanismo ou um botão para abrir o cofre em algum lugar. Veja se consegue encontrá-lo.",--There should be a mechanism or button to open the safe somewhere. See if you can find it.
	pln_fri_21_01 = "Ok, ele tem muitas artes bonitas por aqui. Devem valer uma fortuna. Vamos juntá-las em uma pilha e queimá-las, isso deve trazer ele pra fora.",--Ok, he's got a lot of fancy art around here. Must be worth a fortune. We'll gather 'em in a pile and burn 'em, that should draw him out.
	pln_fri_09_02 = "Espera... hmm... esse sistema é mais avançado do que pensei. Deve ter um quadro de energia em algum lugar - vocês tem que achar e religar ele.",--Wait... hmm... this system is more advanced than I thought. There should be a security switchboard somewhere - you gotta find it and rewire it.
	pln_fri_41_02 = "Ei, ali está ele. Parece que ele está perto das docas.",--Hey, there he is. Looks like he's by the docks.
	pln_fri_43_02 = "Ei, ali está ele. Parece que ele está perto das piscinas.",--Hey, there he is. Looks like he's by the pools.
	pln_fri_04_01 = "Lembrem-se, vocês estão atrás do Chefe da segurança. Nós precisamos do Pen Drive dele.",--Remember guys, you're looking for the head of security. We need his USB stick.
	pln_fri_10_01 = "Mas que... Outro? pessoal, tem outro quadro de energia, religuem aquele também.",--What the... Another one? Guys, there's another switchbox, rewire that one too.
	pln_fri_50_01 = "Deve ter um botão ou algo que abra o cofre. Olhem em volta.",--There should be a button or something that opens the safe. Look around.
	pln_fri_34_03 = "Vamos pessoal! Lembrem-se de deixar aquele guincho funcionando de novo!",--Come on guys! Remember to get that winch up and running again!
	pln_fri_10_03 = "Hm... Parece ter outro quadro de energia. Achem ele e religuem, igual ao outro. ",--Hmm... there seems to be another switchbox. Find it and rewire it, same as the other one.
	pln_fri_08_02 = "Eles interromperam o computador. Vocês precisam protegê-lo, pessoal!",--They interrupted the computer. You gotta protect it, guys!
	pln_fri_39_01 = "Ei pessoal, não sobrou nada. Saiam daí!",--Hey guys, there's nothing left. Get out of there!
	pln_fri_51_03 = "Boa! Agora peguem as coisas. O máximo que conseguirem, mas pelo menos algumas bolsas.",--Great. Now get the stuff. As much as you can, but at least a few bags.
	pln_fri_52_03 = "Usem a tirolesa se quiserem. Vai ser de grande ajuda para mover as bolsas.",--Get a zipline up if you want. It'd be great for moving the bags.
	pln_fri_06_02 = "Já olharam a casa de ferramentas pelo laptop?",--Have you checked the tool shed for the laptop?
	pln_fri_32_01 = "Isso vai levar um tempo. Certifiquem-se de proteger os guinchos enquanto eles fazem a mágica.",--This is gonna take a while. Make sure to protect the winches while they are working their magic.
	pln_fri_05_01 = "Bom, agora conecte o Pen Drive no computador. Procure por um laptop, deve estar perto da casa.",--Great, now plug the usb into the computer. Look for a laptop, it should be near the house.
	pln_fri_03_03 = "O Chefe da segurança vai ter aquele Pen Drive",--The head of security will have that USB stick.
	pln_fri_56_02 = "Ernesto é sempre paranóico, assim que começar a fazer a ligação é melhor terminar. Igual um Pager.",--Ernesto is always paranoid, so once you start making that call you better finish it. Treat it like a pager
	pln_fri_06_03 = "O Laptop deve estar perto da casa, talvez em alguma das casas pequenas?",--The laptop should be near the house, maybe in one of the smaller buildings?
	pln_fri_31_03 = "Acoplem os guinchos no chão!",--Hook the winches up to the floor!
	pln_fri_46_01 = "Procurem pelos pacotes de cocaína, pessoal.",--Search those bags of coke, guys.
	pln_fri_52_01 = "Vocês poderiam pegar uma tirolesa para mover as bolsas.",--You could get a zipline up to move the bags.
	pln_fri_30_01 = "Não vamos sair daqui de mãos vazias. Ernesto tem um cofre de chão aonde ele guarda suas coisas. Usem os ganchos que pegaram mais cedo, acomplem-os ao chão.",--We're not leaving this place without some loot. Ernesto has floor safe where he keeps his stuff. Use the winches you picked up earlier, hook them up to the floor.
	pln_fri_48_08 = "As partes de metal foram guardadas com os pepinos em conserva.",--The metal links were stored with the preserved cucumbers.
	pln_fri_18_01 = "Precisamos de um novo plano... esse cara realmente se trancou... hmm...",--We need a new plan... this guy has really burrowed in... hmm...
	pln_fri_28_03 = "Cuidado com as turrets, pessoal!",--Watch out for those turrets, guys!
	pln_fri_48b_01 = "Você desligou! É o alarme!",--You hung up! That's the alarm!
	pln_fri_23_03 = "Bom! Coloque mais um pouco, queremos uma chama decente.",--Great! Add a few more, we want a proper blaze.
	pln_fri_54_03 = "Os Sosas estão enviando mais homens para reforçar a segurança, e parece que estão chegando agora! Tenha certeza de que não deixou corpos dando sopa em plena vista, ou vão saber que estão aqui!",--The Sosas were sending more men in to reinforce security, and it seems they're about to arrive now! Make sure you haven't left any bodies lying around in plain view, or they'll find out you're here.
	pln_fri_40_01 = "Esse é o Chefe da segurança. Parece que ele está no jardim.",--That's the head of security. He seems to be in the garden.
	pln_fri_33_02 = "Parece que o guincho emperrou. Faça ele voltar a funcionar!",--The winch seems to have jammed. Get it up and running again!
	pln_fri_45_01 = "Esse é o Chefe da segurança. Parece que ele está perto da entrada de carros.",--That's the head of security. He seems to be by the driveway.
	pln_fri_12_02 = "Boa. O computador está funcionando novamente.",--Good. The computer is working again without interruption.
	pln_fri_49_03 = "Chefe, tenho algo para te mostrar. Você vai querer ver isso por você mesmo.",--I got something to show you, boss. You'll want to see it for yourself.
	pln_fri_21_03 = "Vamos queimar os quadros. Coloque-os em uma pilha primeiro.",--Let's burn his paintings. Gather them in a pile first.
	pln_fri_14_02 = "Abrimos a Fortaleza! Entrem!",--We've breached the fortress! Get inside!
	pln_fri_11_02 = "Ok, isso deve bastar. Agora inicie o computador de novo.",--Ok, that should do it. Now start the computer again.
	pln_fri_17_01 = "Espera... não podemos entrar no escritório do Sosa. Deve ser um sistema à parte.",--Wait... we can't get into the lobby or Sosa's office. It must run on a separate system.
	pln_fri_35_02 = "Muito bom. Agora proteja-os.",--That's great. Now protect them.
	pln_fri_01_02 = "Que casarão! Dá pra ver que os Sosa fazem uma boa grana. Vamos roubar o lugar - sileciosamente ou com muito barulho, A Butcher não se importa com a forma de completar o trabalho, contanto que matem o cara.",--What a house! You can tell the Sosas are making money. Let's hit this place - quiet or loud, the Butcher doesn't care how as long as you kill the guy.
	pln_fri_07_02 = "Ok, hackeando o sistema agora...",--Okay, hacking the system now...
	pln_fri_09_01 = "Espera.. que... eles tem segurança adicional. Você precisa desativá-las! Encontre o quadro de energia e religue o sistema.",--Wait.. what... they've got additional security blocks. You gotta disable them. Find a security switchboard and rewire the system.
	pln_fri_11_01 = "Ótimo, isso deve bastar. Agora tente iniciar o computador de novo.",--Great, that should do it. Now try starting the computer again.
	pln_fri_26_01 = "Ok, vamos ver como ele reage a isso.",--Ok, let's see how he reacts to this.
	pln_fri_32_02 = "Agora esperem os guinchos trabalharem. E certifique-se que ninguém interfira neles.",--Now wait for the winches to work. And make sure they're not interfered with.
	pln_fri_37_01 = "É uma grande quantidade de coisas. Mas se quiser pegar mais, fique à vontade.",--That's a good amount of bling. But if you want to grab some more, you can.
	pln_fri_29_03 = "Ok gangue, agora vamos roubar o cofre de chão do Ernesto. Aposto que deve estar cheio de coisas maravilhosas. Tem alguns guinchos perto do lugar por onde entrou - vão pegá-los e os acoplem.",--Ok gang, now we're gonna loot Ernesto's floor safe. I bet it's full of wonderful things. There are some winches stashed near the place where you entered the property - go get them and hook them up.
	pln_fri_22_03 = "Esse é um ótimo lugar para queimar algumas artes inestimáveis.",--That's a great place to burn some priceless art.
	pln_fri_42_03 = "Esse é o Chefe da segurança. Hmm... parece que ele está atrás da casa.",--That's the head of security. Hmm... looks like he's at the back of the house.
	pln_fri_22_01 = "Isso é bom, juntem elas ali.",--That's great, pile them up there.
	pln_fri_35_03 = "Ótimo, você arrumou. Agora proteja-os.",--Great, you fixed it. Now guard them.
	pln_fri_46_02 = "Bom. Agora procurem as bolsas de cocaína.",--Good. Now search the coke bags.
	pln_fri_48_03 = "A barba é verde, mas não grande.",--The beard is green but not long.
	pln_fri_04_03 = "Pegue o Pen Drive do Chefe da segurança.",--Get the USB stick from the head of security.
	pln_fri_19_03 = "Como... eh... preciso pensar em algo... como entrar...",--How... eh... gotta think of something... how to get inside...
	pln_fri_51_02 = "Ótimo. Pegue o máximo que conseguir, mas pelo menos algumas bolsas.",--Good. Get as much loot as you can, but at least a few bags.
	pln_fri_32_03 = "Ok! Só proteja os guinchos enquanto eles trabalham.",--Ok! Just protect the winches now while they're working.
	pln_fri_42_01 = "Esse é o Chefe da segurança. Ele parece estar atrás da casa.",--That's the head of security. He seems to be at the back of the house.
	pln_fri_38_01 = "Ok, vocês limparam o lugar! Hora de sair daqui.",--Ok, you've cleared the place out! Time to get out of here.
	pln_fri_30_02 = "Ok, é hora de saquear a casa do Ernesto. Ele tem um cofre de chão no seu escritório. Acoplem os guinchos e vamos ergue-lo.",--Ok, it's time to loot Ernesto's place. He's got a floor safe in his office. Hook those winches up to the floor and let's lift it.
	pln_fri_48_04 = "A Cabra peluda está infeliz com suas facas.",--The shaggy goat is unhappy with the knives.
	pln_fri_50_02 = "O Cofre provavelmente abre com um botão ou interruptor em algum lugar. Você precisa achá-lo.",--The safe is probably opened by a button or switch somewhere. You need to find it.
	pln_fri_40_03 = "Esse é o Chefe da segurança. Hmm... ele está no jardim eu acho.",--That's the head of security. Hmm... he's in the garden I think.
	pln_fri_24_02 = "Ok! Agora encontre gasolina e atire nela para acender. Vamos queimar umas artes!",--Ok! Now find a gas can and shoot it to set it all alight. Let's burn some art!
	pln_fri_48_01 = "O homem sem cabeça cavalga à Santa Cruz por tomates.",--The headless man rides to Santa Cruz for tomatoes.
	pln_fri_22_02 = "Esse é um ótimo lugar. Juntem elas.",--That's a spot as good as any. Pile 'em up.
	pln_fri_53_03 = "Não se esqueçam de levar as bolsas!",--Don't forget to get the bags out!
	pln_fri_39_02 = "Já foi tudo, gangue. Não tem porque ficar passeando por ai!",--It's all gone, gang. No point in hanging around! 
	pln_fri_05_03 = "Encontre um laptop e conecte o Pen Drive. Deve estar por perto.",--Find a laptop and plug the USB in. It should be nearby.
	pln_fri_08_03 = "Interromperam o computador. Vocês tem que defendê-lo melhor!",--The computer got interrupted. You have to defend it better!
	pln_fri_15_02 = "Precisamos abrir o resto da casa. Deve ter um interruptor em algum lugar.",--We need to open up the rest of the house. There must be a switch somewhere.
	pln_fri_25_03 = "Coloque a gasolina nos quadros, pessoal. Depois atirem nela.",--Put a gas can on the paintings, guys. Then shoot it.
	pln_fri_01_03 = "Ok pessoal. Vamos entrar. Silenciosamente ou com muito barulho, podem matar o cara como quiserem.",--Ok guys. Let's go in. Quiet or loud, you can kill this guy any way you want.
	pln_fri_24_03 = "Ok! Agora encontrem gasolina. Atirem nela para colocar fogo nos quadros.",--Okay! Now go find a gas can. Shoot it to set the paintings on fire.
	pln_fri_17_03 = "Hmm... o escritório do Sosa parece estar trancado em um sistema à parte... esperem aí...",--Hmm... Sosa's office seems to be locked up behind a separate security system.... hang on...
	pln_fri_02_01 = "Ok, o primeiro passo é achar o Chefe da segurança - ele vai ter o Pen Drive com os códigos de acesso para a casa. Ele sempre veste uma jaqueta verde.",--Ok, the first step is to find the head of security - he'll have a USB stick with access codes for the house. He always wears a green jacket.
	pln_fri_28_02 = "Ele tem turrets também! Cuidado!",--He's got turrets too! Watch it!
	pln_fri_20_02 = "Hmm... ela está certa, gangue. Vamos destruir um pouco das coisas dele para provocá-lo.",--Hmm... she's right, gang. Let's destroy some of his stuff and see if we can provoke him.
	pln_fri_17_02 = "Ei pessoal... uuh... parece que não dá pra entrar no escritório dele assim. Está em um sistema à parte.",--Hey guys.. uuh... it seems we can't get into Sosa's office this way. It's on a separate system.
	pln_fri_37_02 = "Isso é ótimo. Mas se quiser pegar um pouco mais, vá em frente!",--That's great. But if you want to grab some more, do so!
	pln_fri_55_03 = "Escutem, os guardas de dentro provavelmente possuem rádios. Tenha cuidado.",--Listen, the guards inside the house are likely to have pagers. Be careful.
	pln_fri_25_01 = "Pessoal, coloquem gasolina nos quadros e atirem nela.",--Guys, put a gas can on the paintings and shoot it.
	pln_fri_49_06 = "Consegui novas armas, chefe. Quer vê-las?",--Got some new guns in, boss. You wanna see them?
	pln_fri_12_01 = "Ok, o computador está funcionando sem problemas de novo, hackeando o sistema.",--Ok, the computer is working nice and steady again, hacking the system.
	pln_fri_53_02 = "Levem essas bolsas, pessoal!",--Get those bags out, guys!
	pln_fri_14_01 = "Vamos entrar, pessoal!",--Let's get inside, guys!
	pln_fri_46_03 = "Ok, agora você precisa procurar essas cocaínas.",--Ok, now you gotta search those bags of coke.
	pln_fri_49_04 = "Ei chefe, os caras do México te mandaram um pouco de tequila. Você vai querer?",--Hey boss, the guys in Mexico sent you some tequila. You want it?
	pln_fri_16_03 = "Ótimo pessoal! Ninguém segura vocês!",--Great guys! No one keeps you out!
	pln_fri_01_01 = "Porra, olha esse lugar. O cara vive no estilo. Você pode fazer isso de forma furtiva ou com um BOOM, você escolhe.",--Damn, look at this place. This guy rides in style. You can do this quietly or with a bang, it's your choice.
	pln_fri_02_02 = "Vamos encontrar o Chefe da segurança. Ele deve ter o necessário para entrar - Pen Drive com códigos de segurança. Ele veste uma jaqueta verde.",--Let's find the head of security. He should have what you need to get in - USB stick with security codes. He'll be wearing a green jacket.
	pln_fri_02_03 = "Encontre o Chefe da segurança dos Sosa - ele vai ter o Pen Drive com os códigos. Ele é um homem de hábito - sempre veste uma jaqueta verde.",--Find Sosa's head of security - he'll have a USB stick with security codes. He's a man of habit - always wears a green jacket.
	pln_fri_03_01 = "Precisamos do Pen Drive do Chefe da segurança.",--We need the USB stick from the head of security.
	pln_fri_04_02 = "Ache o Chefe da segurança e pegue o Pen Drive dele.",--Find the head of security and get his USB stick.
	pln_fri_05_02 = "Deve ter um laptop em algum lugar perto da casa. Conecte o Pen Drive nele.",--There should be a laptop somewhere near the house. Plug the USB stick into it.
	pln_fri_06_01 = "Não consegue encontrar o laptop? Olhe em volta da casa - talvez na garagem?",--Can't find the laptop? Check around the house - the garage maybe?
	pln_fri_07_01 = "Ok, estou tentando hackear o sistema de segurança agora...",--Okay, I'm trying to hack the security system now...
	pln_fri_07_03 = "Espera enquanto eu tento hackear o sistema de segurança...",--Wait while I try to hack the security system...
	pln_fri_08_01 = "O que... pessoal, protejam o computador!",--What... guys, protect the computer! 
	pln_fri_09_03 = "Espera... oh... eles tem segurança adicional aqui. Vocês tem que achar o quadro de energia e religá-lo.",--Hang on... oh... they've got additional security blocks here. You gotta find a security switchboard and rewire it.
	pln_fri_10_02 = "Eu deveria saber... Tem outro quadro. Vocês tem que religar esse também.",--I should've know... there's another switchbox. You've got to rewire that one too.
	pln_fri_11_03 = "Ok, arrumamos os quadros. Pode iniciar o computador de novo.",--Ok, got the switchboards fixed. You can start the computer again.
	pln_fri_12_03 = "Estamos indo bem, estou hackeando o sistema pelo computador.",--We're good and going, I'm hacking the system through the computer
	pln_fri_13_01 = "Foi mais difícil do que pensei, mas ai está! Podem entrar na casa agora.",--That was harder than expected but we're go! You can enter the house now.
	pln_fri_13_02 = "Ok, está feito! Foi difícil, mas consegui abrir uma das portas da casa.",--Ok, it's done! That was hard but I managed to open some of the shutters on the house.
	pln_fri_13_03 = "Abre-te sésamo! Consegui abrir alguma das portas.",--Open sesame! I got some of the house's shutters to open.
	pln_fri_14_03 = "Vamos pessoal! Entrem agora!",--Come on guys! Get inside now!
	pln_fri_15_01 = "Se vamos entrar no escritório do chefe, precisamos abrir o resto da casa. Procure por um interruptor ou algo.",--If we're gonna get into the boss' office, we need to open the rest of the house. Look for a switch or something.
	pln_fri_15_03 = "Deve ter um interruptor ou algo que abra o resto da casa. Tente encontrar.",--There must be a switch or something that opens up the rest of the house. Try to find it.
	pln_fri_16_01 = "Ok pessoal, deu certo! A casa está aberta!",--Ok guys, that did it! The house is open!
	pln_fri_16_02 = "Ótimo! Estamos dentro!",--Great! We're in!
	pln_fri_18_02 = "Estou pensando. Não sei como vamos entrar...",--I'm thinking here. I don't know how we're gonna get in...
	pln_fri_18_03 = "Ok, vamos ver... hmm... precisamos de um plano pra isso...",--Ok, let's see... hmm... we need a plan for this...
	pln_fri_19_01 = "Precisamos entrar. Uma furadeira não vai dar conta.",--We gotta get in. A drill won't do it.
	pln_fri_19_02 = "Hmm, explosivos não vão funcionar, muito perigoso... deixe-me ver...",--Hmm, explosives won't work, it's too dangerous... let me see...
	pln_fri_20_01 = "Hmm... ok, destruir coisas. Entendido.",--Umm... ok, destroy stuff. Got it.
	pln_fri_20_03 = "Ok, destruir coisas. O que devemos pegar...",--Ok, destroy things. What should we go for...
	pln_fri_21_02 = "Dá pra ver que o Ernesto Sosa gosta de colecionar quadros. Vamos queimar todos, isso deve deixar ele bem puto. Juntem elas em uma pilha.",--I can see that Ernesto Sosa likes to collect paintings. We'll burn them all, that should make him angry. Gather them in a pile.
	pln_fri_23_01 = "Continuem empilhando. Façam uma bela fogueira.",--Kepe piling 'em up. Make a nice bonfire.
	pln_fri_23_02 = "Coloque mais alguns quadros. Um pouco mais.",--Add some more paintings. A few more.
	pln_fri_25_02 = "Lembrem-se, vocês precisam de gasolina para botar fogo nos quadros. Atirem na gasolina.",--Remember, you need a gas can to set the paintings on fire. Shoot the gas can.
	pln_fri_26_02 = "Está tudo virando fumaça. Isso deve chamar a atenção dele.",--It's all going up in smoke. This should get his attention.
	pln_fri_26_03 = "Agora só esperar a reação dele.",--Now just wait for his reaction.
	pln_fri_27_01 = "Ei Bile, tá ai? Temos uns carro que precisam ser levados!",--Hey Bile, you there? We got some cars that need picking up and dropping off!
	pln_fri_27_03 = "Bile? Tenho um transporte aéreo para você. Pegar e levar, podemos dizer.",--Bile? I got an airlift job for you. A grab and drop, you could say.
	pln_fri_28_01 = "Não apenas guardas, mas turrets também! Esse cara leva segurança a sério!",--Not just guards, but turrets too! This guy takes security seriously!
	pln_fri_29_01 = "Ok, vamos saquear um pouco enquanto estamos aqui. Ernesto tem um cofre de chão no seu escritório. Tem uns guinchos perto da entrada - peguem-nos e os acoplem.",--Ok, let's get some loot while we're here. Ernesto has a floor safe in his office. There are some winches near the driveway where you entered - grab them and hook them up.
	pln_fri_31_01 = "Conectem esses guinchos agora!",--Attach those winches now!
	pln_fri_33_01 = "Que? O guincho parou, façam funcionar de novo!",--What? The winch has stopped, get it going again!
	pln_fri_33_03 = "Aquele guincho parou de funcionar. Veja se consegue arrumá-lo!",--That winch has stopped working. See if you can fix it!
	pln_fri_34_02 = "Não esqueçam de fazer aquele guincho funcionar novamente!",--Don't forget to get that winch running again!
	pln_fri_36_01 = "Terminou. Olha esse tanto de coisa! Agora peguem tudo que conseguirem antes de fugir!",--It's done. Look at all that loot! Now grab as much as you can before you escape!
	pln_fri_36_02 = "Ótimo pessoal! Olhem isso! Peguem tudo o que conseguirem antes de fugir.",--Great guys! Look at that! Grab all that you can before you escape.
	pln_fri_36_03 = "Muita grana, pessoal! Façam valer a pena pegando tudo que conseguirem!",--Sweet money, guys! Now make this worth it by grabbing as much loot as you can!
	pln_fri_37_03 = "Ótimo, pessoal! Vocês podem pegar mais um pouco ou fugir, a escolha é de vocês.",--Great, guys! Now you can grab some more loot or take the escape, the choice is yours.
	pln_fri_38_02 = "Foi tudo, cada centavo! Agora é hora de ir pra casa!",--That's all of it, every single dime! Now it's time to go home!
	pln_fri_38_03 = "Vocês pegaram tudo que eles tinham! Hora de partir para o pôr do sol, pessoal!",--You took everything they have! Time to ride off into the sunset, guys!
	pln_fri_39_03 = "Pessoal, pegamos toda a grana. Vocês deviam sair daí!",--Guys, we got all the money. You should get out of there!
	pln_fri_41_01 = "Esse é o Chefe da segurança. Parece que ele está na doca.",--That's the head of security. He seems to be at the dock.
	pln_fri_41_03 = "Esse é o Chefe da segurança. Perto da água, na doca.",--That's the head of security. Down by the water, at the dock.
	pln_fri_42_02 = "Ali está ele. Parece que tá na parte de trás.",--There he is. Looks like he's at the back.
	pln_fri_43_01 = "Esse é o Chefe da segurança. Ele está perto das piscinas.",--That's the head of security. He's by the pools.
	pln_fri_43_03 = "Esse é o Chefe da segurança. Nas piscinas, ele está perto das piscinas.",--That's the head of security. The pools, he's by the pools.
	pln_fri_44_02 = "Ei, ali está ele. Parece que está perto das escadas.",--Hey, there he is. Looks like he's around the stairs.
	pln_fri_44_03 = "Esse é o Chefe da segurança. Perto das escadas.",--That's the head of security. He's by the stairs.
	pln_fri_45_03 = "Esse é o Chefe da segurança. Hmm... ele está perto da entrada eu acho.",--That's the head of security. Hmm... he's by the driveway I think.
	pln_fri_47_01 = "Achem aquele gravador, pessoal.",--Find that mic recorder, guys.
	pln_fri_47_02 = "Lembrem-se, precisam encontrar aquele gravador.",--Remember, you gotta find that mic recorder.
	pln_fri_47_03 = "Achem o gravador. Tem que estar aí.",--Find the mic recorder. It's gotta be there.
	pln_fri_48_02 = "Maria quer uma guerra de dedões, mas ela não tem polegares.",--Maria wants to hitch-hike but has no thumbs.
	pln_fri_48_05 = "Montezuma quer três laranjas para o café da manhã.",--Montezuma wants three oranges for breakfast.
	pln_fri_48_07 = "O gato preto comeu suas próprias bolas.",--The black cat ate its own balls.
	pln_fri_49_01 = "Ei Chefe, tenho uma carta fechada aqui. Diz que é apenas pra você.",--Hey boss, I got a sealed letter for you here. Says for your eyes only.
	pln_fri_49_02 = "Ei Chefe, temos um pacote para você. É do QG na Bolívia.",--Hey boss, got a package for you here. It's from the HQ in Bolivia.
	pln_fri_49_05 = "Ei Chefe. tem uma mulher aqui, ela diz que tem informações importantes para você.",--Hey boss. There's some woman here, says she has some important information for you.
	pln_fri_49_07 = "Chefe, tem algo errado com essa cocaína. Você tem que ver.",--Boss, there's something strange with this coke. You gotta see it.
	pln_fri_53_01 = "Vamos pessoal, levem as bolsas!",--Come on guys, move those bags!
	pln_fri_55_01 = "Pessoal, tenham cuidado. Os guardas de dentro provavelmente terão rádios.",--Guys, be careful. The guards inside will probably carry pagers.
	pln_fri_55_02 = "Os guardas de dentro provavelmente terão rádios. Vocês devem ter calma.",--The guards inside will probably have pagers. You should be careful.
	pln_fri_56_01 = "Pessoal escutem com atenção. Assim que começarem a ligação, vocês não podem desligar. É bem provável que ele irá soar o alarme, ele é paranóico acima de tudo.",--Guys listen carefully. Once you start making the call, you can't hang up. He will most likely sound the alarm, he is a paranoid one after all.
	pln_fri_56_03 = "Eu te garanto, que se você desligar no meio da ligação ele vai soar o alarme. Então tenha certeza que está seguro antes de começar.",--I guarantee you, that if you hang up while making the call he will sound the alarm. So make sure the coast is clear before starting it.
	
	-- Legenda de Outros
	btc_fri_04_01 = "Então o Ernesto Sosa está se escondendo atrás de seus seguranças. Vocês poderão lidar com isso, tenho certeza.",--So Ernesto Sosa is hiding behind his guards. You can handle it, I'm sure.
	btc_fri_07_02 = "Tem um sistema de trava estranho para o escritório do Ernesto Sosa, usando uma frase chave. Meu pessoal colocou um pacote especial de cocaína, com um gravador de microfone escondido. Encontrem-o.",--There's an unusual lock system for Ernesto Sosa's office, using a spoken pass phrase. But my people have smuggled in a special cocaine package, with a hidden microphone recorder. Find it.
	btc_fri_cbf_01 = "Tenho traficado armas no Caribe por um bom tempo. Tem sido muito lucrativo, mas alguns dos velhos traficantes da região não aprovam minha presença no mercado local. O Cartel Boliviano dos Sosa especificamente. Como eles não conseguem competir comigo em termos de qualidade, eles decidiram atacar minha operação, afundando um de meus navios, roubando minha mercadoria e matando meus operadores. Foi muito imprudente. Agora eles devem pagar! E vocês é quem vão cobrar o pagamento.. em sangue.",--I have been running guns in the Caribbean for a while. It's been very profitable, but some of the old movers in the region don't approve of my presence on the local market. The Bolivian Sosa Cartel specifically. As they could not compete with me on level terms, they decided to attack my operation - sinking one of my ships, stealing my merchandise and killing my operatives. That was very unwise. Now they must pay. You will collect that payment, in blood.
	btc_fri_06_01 = "Ótimo trabalho não disparando o alarme. Continuem assim.",--Good job on not raising the alarm. Keep it up.
	btc_fri_12_01 = "O Sr. Sosa não irá mais atrapalhar minhas operações. Nem os seus amigos, eu acho.",--Mr. Sosa will not disrupt my operations again. Nor will his friends, I think.
	btc_fri_06_02 = "Muito bom. Mexam-se silenciosamente.",--Well done. You move silently.
	btc_fri_cnc_01 = "Tenho tido alguns problemas com piratas no Caribe. Preciso que vão para Miami e resolvam esses problemas para mim.",--I've had some problems with pirates in the Caribbean. I need you to go to Miami and solve these problems for me.
	btc_fri_end_a_02 = "Vão se perguntar como aconteceu, mas saberão quem foi. Assim irão aprender a não se meter mais comigo.",--They will wonder how this happened, but they will know who did it. And they will learn not to fuck with me.
	btc_fri_07_03 = "O escritório tem um sistema de trava especial. Usando uma frase chave. Mas eu tinha um pacote especial de cocaína que contrabandiei por uma negociação de drogas. Tem um gravador de microfone escondido nele. Encontrem esse pacote.",--The office has a special lock system. It uses a spoken pass phrase. But I had a special cocaine package smuggled in through a drugs deal. It has a hidden microphone recorder in it. Find this package.
	btc_fri_cnc_03 = "Preciso que entreguem uma mensagem para o Cartel Sosa. Mensagem escrita em sangue.",--I need you to deliver a message to the Sosa Cartel. A message written in blood.
	btc_fri_end_b_02 = "A operação dos Sosa em Miami tá fudida. Não acho que vão me dar mais problemas. Graças a vocês.",--The Sosa's Miami operation is fucked. I don't think they will be giving me more problems. Thanks to you.
	btc_fri_10_02 = "Enganaram ele. Excelente. Agora matem-o.",--You tricked him. Excellent. Now kill him.
	btc_fri_09_02 = "Bain fará a ligação.",--Bain will make the call.
	btc_fri_05_02 = "Isso é uma lição a todos: Não mexam com a Butcher. Obrigada pela ajuda, meus amigos.",--This will be a lesson to all: Don't fuck with The Butcher. Thank you for your help, my friends.
	btc_fri_06_03 = "São infiltradores habilidosos. Deveríamos trabalhar juntos mais vezes.",--You are skilled and silent infiltrators. We should work together more often.
	btc_fri_10_03 = "Ele acreditou. Hora de matar o Sr. Sosa. Mandem meus cumprimentos.",--He bought it. The time has come to kill Mr. Sosa. Give him my regards.
	btc_fri_02_01 = "Parece que só os quadros não são o suficiente. Devemos atacar mais forte.",--Seems the paintings are not enough. We must hit him harder.
	btc_fri_10_01 = "O idiota acreditou. Entrem lá e matem-o",--The bastard bought it. Get in there and kill him.
	btc_fri_02_02 = "Obviamente ele não ligou para esses quadros. Precisam achar outra coisa.",--He obviously didn't care enough about those paintings. You need to find something else.
	btc_fri_02_03 = "Destruir sua coleção de arte não funcionou. Então tentaremos outra coisa.",--So destroying his art collection didn't hurt enough. Let's try something else then.
	btc_fri_09_01 = "Bain fará a ligação com a frase chave.",--Bain will make the call with the pass phrase.
	btc_fri_end_a_03 = "Aplaudo suas habilidades. Punição silenciosa ao Ernesto Sosa, mas com convicção mortal. Vão aprender a temer a Butcher.",--I applaud your skills. Punishment came to Ernesto Sosa silently, but with deadly certainty. They will learn to fear The Butcher.
	btc_fri_01_01 = "Bain, não temos o dia todo. Se a cobra se esconde na toca, devemos fazer ela querer sair. Talvez devessem destruir algumas coisinhas preciosas dele.",--Bain, we don't have all day here. If the snake hides in its hole, we must goad it into sticking its head out. Maybe you should try to destroy some of his precious things.
	btc_fri_end_a_01 = "O Ernesto Sosa nem viu chegando. Com ele morto, a operação dos Sosa em Miami cairão em ruínas. Meu ponto está feito.",--Ernesto Sosa never saw it coming. With him dead, the Sosa's Miami operations lie in ruins. My point has been made.
	btc_fri_03_02 = "Então ele é louco por carros. Bom... logo será um morto louco por carros.",--So he's a car freak. Well... soon he will be a dead car freak.
	btc_fri_09_03 = "Bain - pode fazer a ligação?",--Bain - can you make the call?
	btc_fri_07_01 = "O Ernesto Sosa tem uma trava especial para o seu escritório, com uma frase chave. Mas eu planejei isso - Fiz meu pessoal vender uma cocaína especial para ele, com um gravador de microfone escondido no pacote. Vejam se conseguem achar.",--Ernesto Sosa has a special lock system for his office, with a spoken pass phrase. But I have planned for it - I had my people sell some special cocaine to him, with a microphone recorder hidden in the package. See if you can find it.
	btc_fri_08_01 = "Precisam de uma frase chave para quando ligar pro Ernesto Sosa. A frase deve estar aí.",--You need a pass phrase when you call Ernesto Sosa. The phrase should be on there.
	btc_fri_11_01 = "Muito bom, uma morte silenciosa. É o que acontece com quem cruza meu caminho.",--Very good, a silent kill. This is what happens to those who cross me.
	btc_fri_12_02 = "A mensagem foi entregue. O trabalho está feito, eu lhes agradeço.",--The message has been delivered. The job is done, I thank you.
	btc_fri_01_03 = "Se ele não vai sair pra fora, teremos que tirar ele de lá. Comecem destruindo suas coisas pra ver se isso o deixa bravo o suficiente para vir lutar.",--If he's not going to stick his head out, we'll have to draw him out. Start destroying his things and see if that makes him mad enough to come out and fight.
	btc_fri_08_03 = "Vocês devem achar a frase chave aí. Vão precisar para ligar para ele.",--You should find a pass phrase there. You'll need it when you call him.
	btc_fri_03_03 = "O que homens têm com carros? Esquece, estão dentro. Matem-o.",--What is it with some men and cars? Nevermind, you are in now. Kill him.
	btc_fri_05_01 = "Bom trabalho. Ernesto Sosa está morto. Meu ponto está feito.",--Good job. Ernesto Sosa is dead. My point has been made.
	btc_fri_cnc_02 = "O Cartel Sosa atacou um de meus carregamentos no Caribe. Vão pagar, e vocês é quem irão coletar esse pagamento.",--The Sosa Cartel has attacked one of my shipments in the Caribbean. They must pay, and you will collect this payment.
	btc_fri_05_03 = "A mensagem foi entregue. Ernesto Sosa está morto. Seu trabalho aqui acabou.",--The message has been delivered. Ernesto Sosa is dead. Your work here is done.
	btc_fri_end_b_01 = "Acredito que o Cartel Sosa devem estar se arrependendo de tentar me intimidar. A operaçao deles em Miami está em ruínas, e posso fazer negócios em paz novamente. Obrigada por entregar minha mensagem.",--I believe the Sosa Cartel may now be regretting their decision to try to intimidate me. Their Miami operation now lies in ruins, and I can do business in peace again. Thank you for delivering my message.
	btc_fri_04_02 = "Matem os guardas. Depois poderão matar o Ernesto Sosa.",--Kill the guards. Then you can kill Ernesto Sosa.
	btc_fri_04_03 = "Se matarem seus guardas, irão chegar nele.",--If you kill his guards, you will get to him.
	btc_fri_end_b_03 = "Demonstraram que o Cartel Sosa não possui o Caribe. Com ênfase suficiente, acredito eu.",--You have demonstrated that the Sosa Cartel does not own the Caribbean. With sufficient emphasis, I believe.
	btc_fri_03_01 = "A chave do seu coração eram os carros. Agora coloquem uma bala no meio dele.",--The key to his heart was in the cars. Now go put a bullet through it.
	btc_fri_08_02 = "É preciso da frase chave para ligar para o Ernesto Sosa. Devem estar aí.",--The pass phrase is needed when you call Ernesto Sosa. It should be there.
	btc_fri_01_02 = "Se ele vai se esconder, vamos arrastá-lo para fora. Poderiam começar destruindo seus pertences valiosos e ver no que dá.",--If he's going to hide away, we'll have to draw him out. You could start destroying his treasured possessions and see if that does it.
	pt1_fri_01_01 = "Carros? Uh ok, posso fazer isso. Aonde?",--Cars? Uh ok, yeah I can do that. Where is it?
	pt1_fri_03_01 = "Ok pessoal, estou aqui. Precisamos destruir esses carros, certo? Bora jogar essa porcaria na água. Coloquem o imã!",--Ok guys, I'm here. So we need to wreck these cars, right? Let's drop this sucker in the water. Attach the magnet!
	pt1_fri_03_02 = "Ok pessoal. Ouvi que querem arrebentar os carros. Coloquem o imã - Esse aqui vai nadar!",--Ok guys. Busting cars I hear. Attach the magnet - this one's going for a swim!
	pt1_fri_04_02 = "E... lá vamos nós!",--And... off we go!
	pt1_fri_07_01 = "Conectem logo pessoal.",--Hook it up guys.
	pt1_fri_05_03 = "Ei gente, vocês viram a pancada na água que fez?",--Hey guys - did you see the splash it made?
	pt1_fri_01_03 = "Carros... ok, posso ir. Qual a sua posição?",--Cars... okay, can do. What's your position?
	pt1_fri_05_01 = "Eu com certeza ficaria puto se fosse meu carro.",--I sure would be pissed off if that was my ride.
	pt1_fri_08_03 = "Bola de canhão! Eita porra, essa foi forte! Yeah!",--Bombs away! Oh man, that hit hard! Yeah!
	pt1_fri_07_02 = "Ok... coloquem o imã por favor.",--Ok... attach the magnet please.
	pt1_fri_02_02 = "Estarei aí em alguns minutos. Esperem.",--Be there in a few minutes. Stand by.
	pt1_fri_05_02 = "Lá vai ela!",--There she blows!
	pt1_fri_02_03 = "Estou bem perto. Só mais uns minutos.",--I'm pretty close. Just give me a few minutes.
	pt1_fri_08_02 = "E... boom!",--And... bam! 
	pt1_fri_08_01 = "Pronto, isso deve dar.",--Here we go, this should do it.
	pt1_fri_01_02 = "Nem quero saber o que estão fazendo agora. Me dê as coordenadas.",--I don't even wanna know what you guys are up to this time. Just give me the coordinates.
	pt1_fri_02_01 = "Estou a caminho galera, me dê só mais alguns minutos.",--I'm on my way guys, give me a few minutes.
	pt1_fri_03_03 = "Eii! Então vamos jogar carros no mar, é? Vai ser legal - só colocar o imã e estamos prontos!",--Heey! So, we're dropping cars in the sea, huh? This'll be fun - just attach the magnet and we're go!
	pt1_fri_04_01 = "Ok, vou levar essa bosta pra fora!",--Ok, I'm flying this sucker out!
	pt1_fri_04_03 = "Consegui! Sempre gostei de brincar com carros quando criança...",--Got it! I always liked to play with cars as a kid...
	pt1_fri_06_01 = "Ok, vamos jogar esse dentro do salão. Dando meia volta.",--Ok, let's drop the next one right into the lobby. Circling back.
	pt1_fri_06_02 = "Voltando para mais um. Bora jogar esse na casa, beleza?",--Coming back for another one. Let's drop this one on the house, ok?
	pt1_fri_06_03 = "Ok, voltando para o próximo. Poderíamos jogar esse dentro da casa.",--Ok, I'm coming back again for the next one. We could just drop it right on the house.
	pt1_fri_07_03 = "Ok pessoal, coloquem o próximo.",--Ok guys, attach the next one.
	bos_fri_07_01 = "Sim?",--Yes?
	bos_fri_07_02 = "O que foi?",--What is it?
	bos_fri_07_03 = "O que você quer?",--What do you want?
	bos_fri_08_01 = "Tá, vou abrir.",--Ok, I'll open up.
	bos_fri_08_02 = "Ok, pode entrar.",--Ok, come in.
	bos_fri_08_03 = "Beleza, só um segundo.",--Alright, just a second.
	bos_fri_09_01 = "Mas o que..?",--What the..?
	bos_fri_09_02 = "Ei! Quem..?",--Hey! Who the..?
	bos_fri_09_03 = "Mas que merda?",--What the fuck?
	bos_fri_09_04 = "Ah, porra!",--Oh fuck!
	
	-- Objetivos
	hud_heist_friend_stealth_04_hl = "Entre no Escritório",--Enter the office
	hud_heist_friend_anger_1b = "Fixe os carros no imã do helicóptero para que Bile os leve.",--Attach the cars to the helicopter's magnet so that Bile can lift them up.
	hud_heist_friend_loud_04_hl = "Entre na Casa",--Enter the house
	hud_heist_friend_anger_0_hl = "Espere pelo Plano do Bain",--Wait for Bain's plan
	hud_heist_friend_stealth_03_hl = "Faça a Ligação",--Make the call
	hud_heist_friend_anger_3 = "Ache um pouco de thermite e coloque na banheira para fazer um buraco. Com certeza vai deixar ele puto!",--Find some thermite and place it in the bathtub to create a hole. That should surely piss him off!
	hud_heist_friend_loud_02_hl = "Hackeie o Laptop",--Hack the laptop
	hud_heist_friend_anger_2_hl = "Junte os Quadros",--Gather the paintings
	hud_heist_friend_loud_07_hl = "Abra o Cofre de Chão",--Open the floor safe
	hud_heist_friend_loud_11 = "Vocês podem ir embora ou ficar para pegar mais Loot, é com vocês.",--You can leave now or stay and get more loot, it is up to you.
	hud_heist_friend_stealth_06 = "Deve ter um botão por perto para abrir o cofre. Vai estar escondido, então tente mover ou girar vasos ou outros objetos.",--There should be a button somewhere to open the hidden safe. It'll be hidden, so try moving or rotating vases or other obejcts.
	hud_heist_friend_stealth_05_hl = "Mate o Ernesto Sosa",--Kill Ernesto Sosa
	hud_heist_friend_loud_05 = "Mate os seguranças de Sosa no salão principal.",--Defeat Sosa's security in the main hall
	hud_heist_friend_loud_04 = "Entre na casa.",--Enter the house.
	hud_heist_friend_loud_03_hl = "Religue o Quadro de Energia",--Rewire the circuit box
	hud_heist_friend_loud_08 = "Leve as bolsas para o veículo de fuga.",--Bring the loot to the escape vehicle
	hud_heist_friend_stealth_04 = "Não dá pra bater ou ir andando, então abra caminho até o escritório e abra a fechadura da porta.",--You can't just knock and walk in, so make your way to the office and pick the lock on the door.
	hud_heist_friend_anger_2 = "Juntem as quadros em uma pilha. Vão fazer uma bela fogueira.",--Gather the paintings in a pile. They will make a nice bonfire.
	hud_heist_friend_loud_03 = "O Hack foi interrompido. Eles possuem um sistema externo. Encontre e corte-o.",--The hacking was interupted. They have an external override. Find it and cut it.
	hud_heist_friend_anger_2b = "Coloque a gasolina na pilha de arte e queime todas elas.",--Put a gas can on the pile of paintings and burn them all.
	hud_heist_friend_loud_08_hl = "Assegure as Bolsas",--Secure the loot
	hud_heist_friend_loud_01_hl = "Pegue o Pen Drive do Chefe da Segurança",--Get the USB stick from the head of security
	hud_heist_friend_loud_02 = "Tem um laptop por aí em algum lugar. Use o Pen Drive e o hackeie.",--There's a laptop somewhere on the grounds. Use the USB stick and hack it.
	hud_heist_friend_loud_05_hl = "Mate os Seguranças de Sosa",--Defeat Sosa's security
	hud_heist_friend_stealth_05 = "Mate o Ernesto Sosa.",--Kill Ernesto Sosa.
	hud_heist_friend_loud_12_hl = "Fuja!",--Escape
	hud_heist_friend_loud_04b = "Vocês precisam abrir a casa. Achem o interruptor que controla as portas e janelas.",--You need to open the house up. Find the switch that controls the doors and windows.
	hud_heist_friend_loud_06 = "Mate Ernesto Sosa e seus capangas.",--Kill Ernesto Sosa and his goons.
	hud_heist_friend_stealth_02_hl = "Conecte o Gravador no Telefone",--Connect the mic recorder to the phone
	hud_heist_friend_anger_1b_hl = "Fixe os Carros no imã",--Attach the cars to the magnet
	hud_heist_friend_loud_12 = "Vocês limparam o lugar, é hora de dar o fora daí.",--You've cleared the place out, it's time to get out of here.
	hud_heist_friend_anger_1a = "Espere o Bile chegar e pegar o carro com o helicóptero.",--Wait for Bile to come and pick the car up with his helicopter.
	hud_heist_friend_loud_06_hl = "Mate o Ernesto Sosa",--Kill Ernesto Sosa
	hud_heist_friend_loud_04b_hl = "Encontre o Interruptor",--Find the switch
	hud_heist_friend_anger_3_hl = "Destrua a Banheira",--Destroy the bathtub
	hud_heist_friend_stealth_06_hl = "Abra o Cofre",--Open the safe
	hud_heist_friend_stealth_02 = "Pegamos a escuta da cocaína, agora conecte no telefone.",--We've got the bug from the yayo stash, now hook it up with the phone.
	hud_heist_friend_anger_1a_hl = "Espere por Bile",--Wait for Bile
	hud_heist_friend_loud_11_hl = "Assegure mais Bolsas ou Fuja!",--Secure more loot or escape
	hud_heist_friend_stealth_03 = "O Gravador está conectado. Ligue pro Ernesto Sosa no seu escritório.",--The mic recorder is hooked up. Call Ernesto Sosa in his office.
	hud_heist_friend_anger_0 = "Estamos trancados pra fora do escritório de Ernesto Sosa. Espere pelo plano de Bain.",--We are locked out of Ernesto Sosa's room. Wait for Bain to come up with a plan
	hud_heist_friend_anger_2b_hl = "Queime os Quadros",--Burn the paintings
	hud_heist_friend_loud_01 = "O Chefe da segurança tem o Pen Drive preciso para hackear o sistema. Encontre-o, mate-o e pegue o Pen Drive.",--The head of security has a USB stick needed to hack the lock system. Find him, kill him and get the usb stick.
	hud_heist_friend_loud_07 = "Os Sosas tem um cofre abaixo do piso do escritório. Vocês vão querer abrir esse cofre. Acoplem os guinchos, um em cada lado.",--The Sosas have a hidden safe under the floor of the office. You want to open that safe. Hook the winches up, one on each side.
	hud_heist_friend_stealth_01 = "Temos uma escuta plantada na cocaína. Abram todas que acharem.",--We have a bug planted in the yayo. Rip open all you find.
	hud_heist_friend_stealth_01_hl = "Procure as Cocaínas",--Search through the yayo
		})
end)