Hooks:Add("LocalizationManagerPostInit", "aversaoflorestaehapior", function(loc)
	LocalizationManager:add_localized_strings({
	-- Nome e Descrição
	heist_crojob2_hl = "The Bomb: Dockyard",
	heist_crojob1 = "The Bomb: Dockyard",
	heist_crojob1_crimenet = "Meus contatos na divisa me informaram que um navio de carga, a Moretta, deve atracar em Washington dentro de alguns dias. Ela está carregando uma grande quantidade de explosivos termobáricos. Eu quero uma equipe especializada para recuperá-los. A discrição é desejada.\n\n» Abra o Portão da Doca\n» Mova o Navio para a Doca 3B\n» Embarque no Navio e procure os Contêineres\n» Pegue a Bomba e fuja",--My contacts in Split has informed me that a cargo ship, the Moretta, is due to dock in Washington within the next few days. It is carrying a large amount of thermobaric explosive. I require a skilled team to recover these. Discretion is desired.\n\n» Open the dock gate\n» Move the ship to Loading Dock 3B\n» Get on the ship and search the containers\n» Take the bomb and escape
	heist_crojob2_briefing = "A Moretta está estacionada em uma doca fechada, esperando a alfândega liberá-lo. É ai que você entra. Assim que chegarem ao estaleiro, vocês vão movê-la para o ancoradouro aonde vocês consigam embarcar. Da 2B para 3B. Abra o portão da doca, e deixem o capitão saber que ele pode ir. Assim que a Moretta ancorar na 3B, você vai poder embarcar e pegar os explosivos. Simples? Bom, nem tanto. A segurança é muito forte para um navio carregado de produtos agrícolas dos Bálcãs. Tô achando que um monte de coisa obscura deve vir por essa rota. Então tenha cuidado.",--The Moretta is sitting in a sealed dock, awaiting customs clearance. This is where you come in. Once you're in the dockyard, you're going to get it moved to a berth from where you can get aboard. From 2B to 3B. Open the dock gates, and let the Captain know he can move. Once the Moretta is berthed in 3B, you can get aboard and boost the explosives. Simple? Well, maybe not so simple. Security's too tight for a ship loaded with Balkan farm produce. Starting to guess a lot of shady stuff comes through that route. So be careful.
	
	-- Legendas
	pln_cr2_intro_01_01 = "Faça a Moretta sair da doca. Quando ele ancorar, entre, pegue os explosivos e saia. Entendido?",--Get the Moretta out of the dock. When it's berth, get aboard, get the explosives, get out. Got it?
	pln_cr2_intro_01_02 = "Faça com que o navio saia da doca e ancore. Pra você poder entrar e pegar as bombas. Fiquem quietinhos.",--See that the ship gets out of the dock and berth. Then you can board it and get the explosives. Keep it quiet.
	pln_cr2_intro_01_03 = "Você vai fazer aquele navio Croata sair da doca e ancorar. Tentem deixar o volume bem baixo.",--You're gonna get that Croatian ship out of the dock and berth. Gonna try and keep the volume low.
	pln_cr2_31_01 = "É isso aí, gente. Isso vai demorar um pouco. Só deixem a energia ligada.",--That's it, guys. This will take some time. Just make sure the power stays on.
	pln_cr2_38_03 = "E... Bingo! Todas as informações da Moretta incluindo as frequências de rádio. Bom trabalho! Agora procure o rádio mais próximo, e vamos ter uma conversa com o Capitão.",--And... Jackpot! Moretta specs including comm frequencies. Great work! Now look for the nearest radio, and let's talk to the Captain.
	pln_cr2_102_01 = "O guarda tá morto. Não vão mais ter que se preocupar com câmeras.",--That's the guard down. Don't have to worry about the cameras anymore.
	pln_cr2_66_02 = "Ainda não sabem que tão aí. Procurem pelo cartão de acesso.",--Still don't know you're there. Look for the keycard.
	pln_cr2_07_01 = "Foi o painel direito. Agora procurem outro cartão de acesso, e ativem o outro painel.",--That's the right panel. Now search for the other keycard. Get the other panel activated.
	pln_cr2_07_02 = "Painel direito ativado. Agora peguem outro cartão de acesso, e vamos terminar com o segundo painel. ",--Right panel's activated. Now get the other keycard, and let's get the second panel done.
	pln_cr2_33_02 = "Beleza. Vamos tentar de novo.",--Alright. Let's try this again.
	pln_cr2_40_01 = "Procure aqueles terminais, pessoal. Precisamos da frequência do rádio.",--Get on those terminals, gang. We need the comm frequency.
	pln_cr2_117_01 = "Moretta. Aqui é a rádio Porto Washington. Livre para ancorar na doca 3B. Aguardando pelos dados no GPS. Câmbio.",--Moretta. This is Port Washington radio. Free to clear dock and berth at 3B. Stand by for GPS data. Over.
	pln_cr2_13_01 = "Precisamos na frequência de rádio da Moretta. Vai estar em um desses terminais. Procurem.",--We need the Moretta's comm frequency. It'll be on one of those terminals. Get checking.
	pln_cr2_100_01 = "Olha gente, é uma péssima ideia fazer metanfetamina num lugar pequeno e fechado como esse contêiner.",--See guys, it's a bad idea to cook meth in a small, closed space like a container.
	pln_cr2_67_01 = "Eles nem sabem que estão aí. Continue olhando pelos cartões de acesso.",--They've got no clue you're there. Keep looking for those keycards.
	pln_cr2_37_02 = "Deixem a furadeira fazer seu trabalho. Vocês fazem os seus.",--Let the drill do it's job. You do yours.
	pln_cr2_80_03 = "Temos que mover aquele navio. Tenho uma ideia. Se vocês hackearem o terminal de controle do navio e manter o problema longe, talvez eu consiga mover ele remotamente.",--Got to move that ship. I have an idea. If you can hack the ship control terminal and keep the fuzz off it, should be able to guide it remotely.
	pln_cr2_01_03 = "As docas estão bem aí. Entrem, e cuidado com os guardas.",--Docks are right there. Head in. And watch for guards. 
	pln_cr2_78_03 = "O C4 é pra explodir o portão. Posicionem logo.",--The C4 is for blowing the gate. Get it placed.
	pln_cr2_77_02 = "O C4 está esperando vocês. Tão esperando o que?",--C4 is waiting for you. What are you waiting for?
	pln_cr2_24_02 = "Agora plantem no portão da doca.",--Now plant it on the dock gate.
	pln_cr2_45_02 = "De volta às docas. Cada cartão de acesso vai abrir um portão. Um em cada painel.",--Back to the dock. Each keycard will open a gate. One for each control.
	pln_cr2_41_02 = "Esse é o primeiro painel do portão. O outro tá bem ali, conseguem ver?",--This is the first control room for the gate. Other one is over the way there, see?
	pln_cr2_66_03 = "Estão bem quietinhos. Perfeito. Lembrem - vocês precisam dos cartões de acesso.",--You're keeping it quiet. Great. Remember - you need the keycard.
	pln_cr2_73_01 = "Nenhum alarme ainda. Subam a bordo do navio.",--Still no alarms. Now get on the ship.
	pln_cr2_81_03 = "Tem um terminal de controle do navio por aí. Hackeiem!",--There's a control terminal for the ship around there. Hack it!
	pln_cr2_20_03 = "Fodões a bordo! Ótimo trabalho se esgueirando. Contêineres destrancados. Abram eles!",--Badasses on deck! Great job stealthing it. Containers are unlocked. Go for it!
	pln_cr2_109_01 = "Esse portão vai abrir sozinho assim que o navio chegar na Doca 3B.",--This gate will open automatically once the ship moves to Dock 3B.
	pln_cr2_80_02 = "Ainda precisamos levar esse navio ao ancoradouro. Hmmm... Ok, já sei. Hackeiem o terminal de controle do navio. E deixem os policiais longe.",--We still need to get that ship to the berth. Ummm... OK, I got it. Hack the ship control terminal. Keep the cops off it.
	pln_cr2_07_03 = "Portão direito ativado. Agora procure outro cartão de acesso, e vamos abrir o outro portão.",--Right gate activated. Now find another keycard, and let's get the other gate open.
	pln_cr2_123_03 = "Porra, nada da frequência do rádio. Acho que vai estar na sala de controle do outro lado das docas.",--Damn, no sign of the comm frequency. My guess is it'll be at the control room across the dock.
	pln_cr2_92_02 = "O helicóptero está esperando vocês. Acelerem!",--Chopper's waiting for you. Hurry!
	pln_cr2_22_03 = "Esperem - mandando por helicóptero.",--Stand by - sending it in by chopper.
	pln_cr2_53_01 = "Vamos, gente. Me coloquem no rádio.",--Come on, gang. Patch me into the radio. 
	pln_cr2_19_03 = "Vocês já pegaram as frequências. Mantenham o foco!",--You got the frequency already. Stay focused!
	pln_cr2_69_02 = "Ainda sem alarmes. Ótimo. Achem as frequências do rádio.",--Still no sign of an alarm. Great. Find the comm frequency.
	pln_cr2_49_03 = "Os cartões vão abrir os portões. Use um em cada sala de controle.",--Them keycards open the dock gates. Use one in each control room. 
	pln_cr2_96_02 = "Olha o que temos aqui. Nada mais que o manifesto da Moretta. Agora sabemos quais contêineres podem ter loot. Ótimo achado.",--Well, what have we here. Only the Maretto's cargo manifest. Now we know which containers may hold loot. Good find.
	pln_cr2_81_02 = "Hackeie o terminal de controle do navio!",--Hack the ship control terminal!
	pln_cr2_58_01 = "Os contêineres esperam por vocês. Procurem.",--The containers are ready for you. Get searching.
	pln_cr2_47_01 = "Lembrem-se de checar dentro dos edifícios pelos cartões restantes.",--Remember to check inside the buildings for the remaining keycard.
	pln_cr2_76_03 = "Porra! É o alarme. Bem, as coisas ficaram mais diretas agora. Esqueçam o cartões. Vamos abrir o nosso próprio caminho. Acenda um sinalizador. Bile vai te levar um pouco de C4.",--Damn! It's the alarm. Well, this just got more straightforward. Forget keycards. We're blowing our way through. Light a flare and drop it. Bile will drop you some C4.
	pln_cr2_74_01 = "A segurança continua quietinha. Agora encontre a bomba.",--Security is still quiet. Now find the bomb.
	pln_cr2_88_03 = "Aquele manifesto que você pegou vai nos mostrar os contêineres certos.",--That manifest you picked up will point us to the right containers.
	pln_cr2_03_03 = "E aí está o segundo cartão de acesso. Bom trabalho!",--And that's the second keycard. Nice job!
	pln_cr2_41_01 = "O portão tem duas salas de controles. Uma em cada lado. Essa é uma.",--The gate has two control rooms. One on each side. This is the first.
	pln_cr2_94_01 = "Vão para o barco!",--Get to the boat!
	pln_cr2_50_01 = "Vocês precisam sair de perto do portão antes dele abrir. Questão de saúde e segurança.. essas merdas!",--You have to get off the gate before it will open. Health and safety bullshit!
	pln_cr2_68_03 = "Ninguém os viu. Continuem assim. Agora o portão.",--No-one's seen you. Keep it that way. Now, the gate.
	pln_cr2_27_03 = "Terceiro já foi. Mais um.",--Third placed. One more.
	pln_cr2_95_03 = "Pro barco, pessoal. Rápido!",--To the boat, gang. Come on!
	pln_cr2_80_01 = "Precisamos mover esse navio! Deixe-me pensar... Certo, hackeie o terminal de controle do navio e deixem ligado.",--We gotta get the ship moving! Lemme think... Alright, just hack the ship control terminal and make sure it stays on.
	pln_cr2_118_02 = "Os peixes daqui devem engordar com esses cadáveres.",--Fish in this town grow fat on corpses.
	pln_cr2_103_02 = "E já era o guarda. Camêras não vão mais ser um problema.",--And that's the guards dealt with. Cameras are no longer a problem.
	pln_cr2_85_02 = "Deixem a polícia longe dos disjuntores.",--Keep the heat away from the circuit breakers.
	pln_cr2_85_03 = "Não deixem desligar a energia de novo!",--Don't let them turn the power off again!
	pln_cr2_25_01 = "Um colocado.",--One in place.
	pln_cr2_40_02 = "Precisamos da frequência da Moretta, gente. Procurem os terminais.",--Need the Moretta's frequency, guys. Get searching terminals.
	pln_cr2_83_03 = "Liguem aquele terminal de novo, gente. Vamos mover esse navio.",--Switch that terminal back on, gang. Let's get this ship moved.
	pln_cr2_32_02 = "Mas que...? Sem energia. Religuem!",--What the..? Power's out. Get it on!
	pln_cr2_101_01 = "Os policiais abriram o portão de entrada!",--The cops opened the entrance gate!
	pln_cr2_115_03 = "O navio tá ali. Subam a bordo! Talvez coloquem uma tirolesa - pode acelerar o processo.",--Ship's there. Get on it! Maybe deploy the zip-line - might speed things up.
	pln_cr2_13_02 = "A frequência da Moretta vai estar em um dos computadores. Procurem por eles.",--Moretta's comm frequency will be on one of the computers. Check them out.
	pln_cr2_59_03 = "Ah caralho! A segurança trancou os contêineres quando o alarme disparou. Parece que vamos ter usar furadeiras.",--Ah crap! Security locked the containers when the alarm was triggered. Looks like we're drilling.
	pln_cr2_17_01 = "Lá vai. Lembrem, isso não é uma lancha. Vai demorar um pouco. Continuem quietos. Cuidado para não acionar o $NL; alarme. Ou procurem por loot extra. Escolha de vocês, pessoal.",--There it goes. Remember, this isn't a speed boat. Going to take a while. Keep a low profile. Be careful not to trigger $NL;the alarm. Or search for extra loot. Your choice, guys.
	pln_cr2_52_03 = "Portões abertos. Ótimo! Hora de mover o navio. Eu sabia que aquela frequência que vocês acharam ia ser útil. Só procurem por um rádio agora, e eu faço o resto.",--Gate's are open. Great. Time to move the ship. I knew that comm frequency you found earlier would come in useful. Now just find a radio, and let me do the rest.
	pln_cr2_121_02 = "Pode parar de olhar as caixas - vocês já acharam a bomba!",--You can quit searching those cases - you found the bomb!
	pln_cr2_100_03 = "Um laboratório de metanfetamina no mar? Esperto. Um laboratório num contêiner? Não tão esperto...",--An off-shore methlab? Clever. A methlab in a metal box? Not so clever...
	pln_cr2_83_01 = "Ok, agora religuem o computador.",--OK, now reactivate the computer. 
	pln_cr2_86_03 = "É pedir muito que deixem os policiais longe da energia?",--Is it too much to ask that you keep the cops away from the power?
	pln_cr2_71_01 = "Vocês parecem uns fantasmas. Agora vão até o computador.",--You guys are professional ghosts. Now get to the computer.
	pln_cr2_42_02 = "Aqui está o segundo painel de controle. Com os dois, podemos abrir o portão.",--Here's the second control room. Between the two, we can open the gate.
	pln_cr2_62_03 = "Deu em nada. Continuem procurando.",--It's a blank. Keep searching.
	pln_cr2_03_02 = "O segundo cartão de acesso. Bom trabalho!",--The second keycard. Great work.
	pln_cr2_38_02 = "Banco de dados do navio. Deve ter... Consegui! Frequência da Moretta. Agora achem um rádio. Vamos ligar para o Capitão.",--Ship database. Should have... Got it! Comm frequency for the Moretta. This is it! Now find a radio. Let's call the Captain.
	pln_cr2_24_03 = "Coloquem esse C4 no portão da doca.",--Get that C4 on the dock gate.
	pln_cr2_29_02 = "BOOM!",--Boom! 
	pln_cr2_104_03 = "Pé na tábua, gente. Eles vão vir com tudo nessa operação.",--Better haul ass, gang. They're putting everything they have in to this assault.
	pln_cr2_43_02 = "Esses vagões podem ter algo valioso dentro. Poderiam olhar eles?",--These wagons might have something valuable in them. Maybe check them out? 
	pln_cr2_91_01 = "Pessoal! A van!",--Guys! The van!
	pln_cr2_94_03 = "Tem um barco esperando por vocês.",--There's a boat waiting to pick you up.
	pln_cr2_48_02 = "Podem usar esse cartão de acesso no painel de controle. Só deslizar que abre a doca.",--You can use that keycard in the control room. Just swipe it, open the dock.
	pln_cr2_75_01 = "Eles não tem ideia que vocês estão aí. Agora saiam.",--They have no clue you are there. Now get out of there.
	pln_cr2_65_02 = "O barco não pode esperar pra sempre, pessoal.",--The boat can't wait forever, gang.
	pln_cr2_62_01 = "Ah, vazio! Achem outro.",--Ah, it's empty! Find another one.
	pln_cr2_31_03 = "E... dentro! Ótimo. Mantenham a conexão segura. Indo o mais rápido possível.",--And... In! Great. Now keep the connection secure. Going as fast as can.
	pln_cr2_99_03 = "Ótimo! loot extra... Adoro!",--Great! Extra loot... Love it!
	pln_cr2_111_01 = "Escritório do administrador geral. Um terminal aqui pode conter a frequência da Moretta. Boa chance de um cartão de acesso ou um rádio $NL;também.",--General admin office. A terminal here might hold the Moretta's comm frequency. Good chance of a keycard or radio $NL;too.
	pln_cr2_11_01 = "Ai! Esses terminais provavelmente têm a frequência da Moretta. Vamos precisar em breve.",--Hey! These terminals likely have the comm frequency for the Moretta. We're gonna need it before long.
	pln_cr2_90_03 = "Abram caminho até a van, gente.",--Fight your way back to the van, clowns.
	pln_cr2_54_01 = "Pessoal, vão ate o computador. Enviem as coordenadas para o navio.",--Gang, get to the computer. Get those coordinates to the ship.
	pln_cr2_61_02 = "O que será que tem nessa caixa. Pode ser a bomba da Butcher. Dê uma olhada.",--Wonder what's in the case. Could be The Butcher's explosives. Have a look.
	pln_cr2_66_01 = "Eles não têm ideia de que vocês estão aí. Agora procurem os cartões.",--They have no clue you are there. Now keep looking for those keycard.
	pln_cr2_77_01 = "Peguem aquela C4, pessoal.",--Grab that C4, guys.
	pln_cr2_25_02 = "Foi o primeiro.",--That's the first.
	pln_cr2_30_03 = "Pode esquecer o capitão movendo o barco pra nós. Dá pra mover sem ele. Hackeie o terminal de controle do navio. E não deixe os policiais atrapalhar.",--We can scratch the Captain moving his ship for us now. Nevermind. We can move the ship without him. Hack into the ship control terminal. And don't let the cops interfere with it.
	pln_cr2_87_02 = "Falta pouco... Falta bem pouco.",--Almost got it... Almost got it.
	pln_cr2_18_02 = "Beleza, tá ancorada! Subam a bordo e comecem a procurar os contêineres.",--Alright, she's berthed! Get up on deck and start searching the containers.
	pln_cr2_12_01 = "Lembrem-se, estamos procurando por cartões de acesso. Olhem nos edifícios.",--Remember, you're looking for keycards. Check the buildings.
	pln_cr2_03_01 = "Esse é o segundo cartão de acesso. Bom trabalho, pessoal!",--That's keycard two. Good job, guys!
	pln_cr2_56_02 = "Esperem, pessoal. A Moretta tá quase ancorando.",--Stand by, gang. Moretta's almost berthed.
	pln_cr2_121_03 = "Abrir essas caixas é inútil. Vocês já têm a bomba, esqueceram?",--Searching the cases is pointless. You got the bomb, remember?
	pln_cr2_46_03 = "Ótimo. Agora o segundo cartão no outro painel, e a Moretta vai estar livre.",--Great. Now the second card in the other panel, and the Moretta will be free.
	pln_cr2_63_01 = "Ai está! Leve a bomba pro ponto de entrega!",--Here it is! Take the bomb parts to the drop-off point!
	pln_cr2_38_01 = "Aha! Dados do navio, incluindo as frequências de rádio. Perfeito! É o que precisamos. Agora dê uma buzinada pro nosso capitão.",--Aha! Ship database, including comm frequencies. Great! That's what we need. Now get on the horn to the Captain.
	pln_cr2_29_03 = "Igualzinho o St Nazaire!",--Just like St Nazaire! 
	pln_cr2_53_02 = "Pessoal, me coloquem no rádio. Deixem eu falar com a Moretta.",--Guys, patch into the radio. Let me speak to the Moretta.
	pln_cr2_14_01 = "A Moretta tá ancorado na Doca 2B. Não tem como acessar ali.",--Moretta is moored at Dock 2B. Can't access it there.
	pln_cr2_75_03 = "Continuem quietos enquanto vocês saem daí, e esse foi um belo trabalho invisível.",--Keep quiet while you bug out of there, and this is a perfect piece of shadow work.
	pln_cr2_45_01 = "Agora usem os cartões para abrir o portão. Não importa qual primeiro.",--Now use those keycards to open the gate. Doesn't matter which does which.
	pln_cr2_04_02 = "Bom! Agora usem o outro cartão de acesso no outro painel de controle.",--Good. Now use the other keycard on the panel in the other control room. 
	pln_cr2_88_02 = "Graças à aquele manifesto que achou, sabemos aonde abrir.",--Thanks to that manifest you found, we know where to drill.
	pln_cr2_123_01 = "A frequência de rádio não está ai. Olhem os computadores do outro lado do estaleiro.",--The comm frequency ain't here. Check the computer's in the control room across the dockyard.
	pln_cr2_61_03 = "Essa caixa talvez tenha a bomba. Olhem ela!",--The case might have the explosives. Check it!
	pln_cr2_59_02 = "Puta que pariu! Trancaram os contêineres! Deve ter sido os alarmes. Beleza, vamos quebrar as trancas.",--God damn it! They locked the containers! Must've been the alarms. Alright, we break through.
	pln_cr2_69_03 = "Tudo em silêncio. Perfeito. Procurem as frequências de rádio.",--Everything's quiet. Nice. Track down the comm frequency.
	pln_cr2_16_03 = "Ótimo. Agora vamos mandar esses dados de GPS. Encontrem um computador para enviar.",--Great. Now let's get her that GPS data. Find the computer to upload.
	pln_cr2_103_01 = "Deram um jeito nos dois guardas. Não precisam se preocupar mais com as câmeras.",--You took care of both guards. Don't have to worry about the cameras anymore.
	pln_cr2_119_03 = "Virou apenas comida de rato.",--Just food for the rats now.
	pln_cr2_47_03 = "O segundo cartão de acesso não deve estar longe. Tem que estar por aí. Continuem procurando.",--Second keycard can't be far. Gotta be nearby. Keep looking.
	pln_cr2_101_03 = "Os policias passaram pelo portão da frente. Preparem-se.",--Cops are through the front gate. Get ready.
	pln_cr2_95_01 = "Gente! Vão para o barco!",--Guys! Get to the boat!
	pln_cr2_82_01 = "Religuem a energia.",--Get the power back on.
	pln_cr2_65_01 = "Vamos logo, para o barco.",--Come on, get to the boat.
	pln_cr2_08_01 = "Bem, portão da frente trancado. Que surpresa. Procurem por uma outra entrada.",--Well, the front door's closed.  No surprise. Look for another way in.
	pln_cr2_16_01 = "OK, vocês ouviram o capitão. Achem o computador. Enviem as coordenadas do GPS. Vamos movê-lo.",--OK, you heard the Captain. Find the computer. Enter the GPS coordinates. Let's get her moving.
	pln_cr2_102_02 = "Guarda morto. Câmeras fora de ação.",--Guard is down. That's the cameras out of action.
	pln_cr2_06_03 = "Portão esquerdo ativado. Agora ache outro cartão de acesso, e vamos abrir o outro portão.",--Left gate activated. Now find another keycard, and let's get the other gate open.
	pln_cr2_104_02 = "É isso ai, gente. Tão jogando tudo o que eles têm nisso. Saiam daí!",--This is it, gang. They're throwing everything they have in to this. Get out of there!
	pln_cr2_43_01 = "Os trens estão pronto para o carregamento. Olhem os vagões. Com certeza estão carregados. Talvez achem algo valioso.",--The train's ready for the cargo. Check the wagons. Probably loaded. Might find something worthwhile.
	pln_cr2_44_03 = "Bom, é um cartão de acesso, e inútil pra caralho agora. Se você tivesse achado isso antes...",--Well, it's a keycard, and pretty damn useless now. Maybe if you'd found it earlier...
	pln_cr2_24_01 = "Ok, plantem o C4 nos portões.",--OK, place the C4 on the gate. 
	pln_cr2_35_03 = "O Navio tá ali. A bordo!",--Ship's there. Get on it!
	pln_cr2_79_02 = "Longe do portão! Rápido!",--Away from the gate! Hustle it!
	pln_cr2_12_03 = "Precisam achar cartões de acesso. Acho que nos edifícios é sua melhor aposta.",--You need to find keycards. My guess is that the buildings are your best chance.
	pln_cr2_21_01 = "Boa! Frequências de rádio da Moretta. Vai ser útil depois, continuem focados.",--Nice! Comm frequencies for the Moretta. This will be useful later on, but stay focused.
	pln_cr2_122_03 = "Vocês já acharam a bomba. Podem deixar os contêineres em paz!",--You already found the bomb. You can leave the containers alone!
	pln_cr2_23_02 = "O C4 tá no chão. Peguem ele!",--C4 is on the ground. Grab it!
	pln_cr2_51_03 = "Ok, a Moretta está pronta pra ir, mas precisamos convencer o capitão. Encontrem a frequência de rádio. Aposto que um dos computadores ai deve tê-las. Vou convencer a esse bom capitão a ligar os motores.",--OK, the Moretta is free to move but we gotta convince the Captain. Find the comm frequencies. I'm betting one of the computers there has it. I'll convince the good Captain to fire up the engines.
	pln_cr2_112_01 = "Esse é o armazém. Procurem por um cartão de acesso. Talvez tenha um rádio aqui também.",--This is the Storage Room. Check for a keycard. Might be a radio here too.
	pln_cr2_44_01 = "É um cartão de acesso, não vai ajudar agora. Poderia ter nos ajudado a não disparar o alarme, mas foquem no agora!",--It's the keycard, for all the good it will do you now. Might have helped us avoid the alarm, but stay focused!
	pln_cr2_65_03 = "O barco está esperando por vocês, pessoal.",--Boat's standing by to get you out, guys.
	pln_cr2_89_02 = "Pessoal, não esqueçam de arrombar esses contêineres. Abram eles!",--Gang, don't forget to crack those containers. Drill 'em!
	pln_cr2_36_01 = "Caralho! Os contêineres trancaram quando o alarme foi disparado. Vão precisar arrombá-los.",--Damn! The containers got locked when the alarm was triggered. Gonna have to drill them.
	pln_cr2_120_03 = "A polícia tá nas caixas de energia, gente. Mantenham a energia ligada!",--Pigs are all over the powerboxes, gang. Keep the power on!
	pln_cr2_64_02 = "Corram para o barco.",--Make your way to the boat.        
	pln_cr2_70_02 = "Ainda em silêncio. Ótimo. Agora o rádio.",--You're keeping it quiet. Great. Now, the radio.
	pln_cr2_72_03 = "Tudo continua quieto. Bom trabalho! Fiquem escondidos enquanto a Moretta atraca.",--All's quiet still. Good work. Stay hidden while the Moretta docks.
	pln_cr2_37_03 = "Mantenham a polícia ocupada que a furadeira vai terminar rapidinho.",--Keep the cops busy and the drill will be through in no time.
	pln_cr2_35_01 = "Navio em posição! Vamos fazer igual o Barba Negra!",--Ship's in position! Going to hit it like Blackbeard!
	pln_cr2_81_01 = "Vá para o terminal de controle e hackeie-o!",--Get to the ship control terminal and hack it!
	pln_cr2_84_03 = "Estou cego até vocês reativerem esse terminal, pessoal.",--Blind here til you get that terminal back on, guys.
	pln_cr2_115_02 = "A Moretta tá no atracadouro. Hora de uma abordagem mais agressiva. Uma tirolesa pode acelerar as coisas.",--Moretta's at the berth. Time for a hostile boarding. The zip-line could speed things up.
	pln_cr2_15_03 = "Contratos e despesas. Inútil. Continuem procurando.",--Personel contracts and expenses. Useless. Keep checking.
	pln_cr2_106_01 = "Precisamos abrir o portão da doca para a Moretta ir pra Doca 3B.",--We gotta open this dock gate to get the Moretta to Dock 3B.
	pln_cr2_54_03 = "Precisam achar o computador e enviar as coordenadas do GPS para o navio.",--You need to find the computer and upload the GPS coordinates to the ship.
	pln_cr2_12_05 = "Achem cartões de acesso, pessoal. Procurem nos edifícios.",--Find keycards, gang. Check the buildings.
	pln_cr2_11_02 = "Eu acho que esses terminais devem ter a frequência de rádio da Moretta. Pode valer a pena olhar.",--I'm guessing these terminals contain the Moretta's comm frequency. Might be worth a look.
	pln_cr2_88_01 = "Sorte que vocês acharam esse manifesto. Agora sabemos quais contêineres arrombar!",--Lucky that you found the manifest. Now we know which containers to drill!
	pln_cr2_46_01 = "Bom. Agora use o cartão de acesso no painel da outra sala de controle.",--Good. Now use the keycard on the panel in the other control room. 
	pln_cr2_104_01 = "Gente, eles tão botando tudo em cima de vocês. Melhor sair daí, rápido!",--Guys, they're throwing everything they have at you. Better make it out, fast!
	pln_cr2_90_01 = "Vão pra van!",--Get to the van!
	pln_cr2_114_01 = "Essa é uma das salas de controle do navio. Computadores podem ser usados para a enviar coordenadas do GPS. Pode ter um cartão de acesso ou rádio por aqui.",--This is one of the ship Control Rooms. Computers can be used for entering GPS targets. There could also be a keycard or radio here.
	pln_cr2_26_03 = "Segundo. Continuem.",--Second. Keep going.
	pln_cr2_17_02 = "Ela está indo, mas não tão rápido. Vai levar um tempo. Fiquem escondidos, pessoal. Esperem. Ou, se quiserem, podem olhar por um pouco de loot extra.",--She's moving. But not fast. This will take some time. Stay hidden, guys. Lie low. Or, if you want, look around for extra loot.
	pln_cr2_46_02 = "Agora passe o cartão de acesso no painel da outra sala de controle. Abram esse portão.",--Now swipe the card on the panel in the other control room. Get that gate open.
	pln_cr2_09_02 = "Estão dentro. Agora procurem por cartões de acesso - dois deles. Acho que os escritórios é o melhor lugar.",--You're in. Now hunt down keycards - two of 'em. I'd guess offices are your best bet. 
	pln_cr2_54_02 = "Achem o computador. Enviem os dados do GPS para a Moretta.",--Find the computer. Send Moretta the GPS data.
	pln_cr2_47_02 = "Só mais um cartão de acesso. Tem que estar em algum lugar.",--Just one more keycard. Gotta be around here somewhere.
	pln_cr2_123_02 = "A frequência não tá aqui. A sala de controle é do outro lado da doca - talvez esteja lá.",--The frequency ain't here. The control room is across the dock - maybe check there.
	pln_cr2_15_02 = "Só regulações marítimas e remessas. Continue olhando.",--Just maritime regulations and shipping forecasts. Keep looking.
	pln_cr2_100_02 = "Que retardado teve a ideia de montar um laboratório de metanfetamina numa caixa de metal sem ventilação?",--Whose bright idea was it to set up a methlab in an unventilated tin box?
	pln_cr2_86_02 = "Pessoal, não preciso dizer o quão importante é a eletricidade para os computadores!",--Gang, I can't stress how important electricity is to computers!
	pln_cr2_26_02 = "Metade do caminho, gente.",--Halfway done, gang.
	pln_cr2_124_03 = "Porra, sem frequência de rádio aqui. Beleza, tem um escritório do outro lado. Olhem lá.",--Damn it, no comm frequency here. Alright, there's an office across the dock. Check there.
	pln_cr2_79_03 = "Isolem o portão!",--Clear the gate!
	pln_cr2_68_01 = "Ainda sem alarmes. Incrível. Agora abram o portão.",--Still no alarm. Outstanding. Now open the gate.
	pln_cr2_16_02 = "Ouviram o capitão. Peguem os dados do GPS para a Moretta. Encontrem o computador para enviar.",--You heard the Cap'n. Get the GPS data to the Moretta. Find the computer to upload.
	pln_cr2_04_03 = "Ótimo. Agora usem o cartão de acesso no outro portão. Rápido!",--Great. Now get that other keycard working on the opposite gate. Hurry!
	pln_cr2_125_02 = "Ai está ela. A Moretta. Embora sem acesso por aqui. Mandem ela pra Doca 3B.",--There she is. The Moretta. No access here, though. Get it to dock 3B.
	pln_cr2_02_01 = "Ótimo. Primeiro cartão de acesso. Precisamos achar mais um.",--Great. That's keycard one. We need to find one more.
	pln_cr2_20_01 = "Nenhum alarme disparado, então você pode simplesmente andar pelos contêineres. Incrível.",--No alarm was triggered, so you can simply walk into the containers. Outstanding!
	pln_cr2_97_01 = "Vamos ver o que temos aqui.",--Lets see what we have here.
	pln_cr2_34_01 = "E... feito! Navio em movimento. Esperem um pouco pessoal, isso vai demorar um pouco! Tentem não morrer.",--And... Done! Ship's moving. Sit tight guys, this will take some time! Try not to get killed.
	pln_cr2_55_01 = "Lá se vai o alarme. E nosso plano furtivo. Não se preocupem. O navio tá se movendo.",--There's goes the alarm. And our stealth plan. Don't sweat it. The ship is moving.
	pln_cr2_10_02 = "Pras docas, pessoal, rápido.",--Into the docks, gang, c'mon.
	pln_cr2_39_02 = "Esse pé-de-cabra vai ser útil com todas essas caixas.",--That crowbar will be useful with all these shipping crates.
	pln_cr2_67_02 = "Ainda não sabem que tão ai. Procurem os cartões de acesso.",--Still don't know you're there. Look for the keycards.
	pln_cr2_122_01 = "Vocês já têm a bomba. Não precisa ficar abrindo os contêineres.",--You guys have the bomb. No need to keep opening the containers!
	pln_cr2_82_02 = "Preciso da energia de volta, pessoal.",--Need the power back, guys.
	pln_cr2_36_02 = "Mas que? Ah porr... Os contêineres fecharam quando o alarme disparou. Arrombem eles!",--What the? Ah fuuu... Containers were locked when the alarm tripped. Drill them!
	pln_cr2_77_03 = "O C4 entrou no jogo, gente. Peguem ela.",--The C4 is in play, gang. Grab it.
	pln_cr2_118_01 = "Alimentando os peixinhos, é?",--Feeding the fish, eh?
	pln_cr2_107_01 = "Essa é a sala de controle do portão direito. Usem o cartão de acesso aqui.",--This is the Right Control Room for the Dock Gate. Use the Keycard here.
	pln_cr2_25_03 = "É um começo.",--That's a start.
	pln_cr2_33_03 = "A energia voltou. Vamos tentar de novo.",--Power's back. Now let's try this once more.
	pln_cr2_121_01 = "Vocês já acharam a bomba. Não tem mais motivo pra ficar abrindo as caixas!",--You've found the bomb. No need to keep checking the bomb cases!
	pln_cr2_70_03 = "Ainda em silêncio. Boa. Achem o rádio.",--Still silent. Nice. Find the radio.
	pln_cr2_71_03 = "Ainda em modo silencioso. Boa, boa. Agora achem o computador.",--Still in whisper mode. Good, good. Now find the computer.
	pln_cr2_86_01 = "Gente! A energia! Deixem ligada!",--Guys! The power! Keep it on!
	pln_cr2_72_01 = "Ha, ainda não suspeitam de nada. Fiquem seguros enquanto o navio se move.",--Ha, they still suspect nothing. Just stay careful while the ship is moving.
	pln_cr2_116_01 = "Moretta. Aqui é o rádio do Porto Washington. Um zero um E. Câmbio.",--Moretta. This is Port Washington radio. One zero one E. Over.
	pln_cr2_21_03 = "Aha! A frequência de rádio da Moretta. Vamos usar isso depois, continuem focados agora.",--Aha! The Moretta comm frequencies. We can use these later, but stay focused.
	pln_cr2_63_03 = "Isso aí. Agora tirem essas partes daí.",--That's it. Now haul those parts out of there.
	pln_cr2_82_03 = "Não esqueçam de religar a energia. Tô cego aqui.",--Don't forget to turn the power back on. Blind here.
	pln_cr2_15_01 = "Recibos de combustível, reivindicações de seguro. Nada útil aqui. Continuem olhando os terminais.",--Fuel receipts, insurance claims. Nothing useful here. Keep checking the terminals.
	pln_cr2_42_03 = "Segunda sala de controle. Controla esse portão. A outra tá do outro lado, consegue ver?",--Second control room. Controls the gate here. Other one is over the way, see?
	pln_cr2_53_03 = "Pessoal. Usem o rádio. Deixe-me falar com o nosso navio.",--Gang. Use the radio. Let me speak to our ship.
	pln_cr2_37_01 = "Perfura bebê, perfura!",--Drill baby, drill!
	pln_cr2_74_03 = "E ninguém ainda sabe que estão ai. Continuem assim. Achem esses explosivos.",--And still no-one knows you're there. Keep it that way. Find those explosives.
	pln_cr2_70_01 = "Eles não têm ideia de que estão aí. Agora pro rádio.",--They've no clue you're there. Now get to that radio.
	pln_cr2_115_01 = "Navio em posiçao! Vamos roubar igual ao Barba Negra! Tirolesa pode ser um bom atalho.",--Ship's in position! Going to hit it like Blackbeard! Zip-line could be a shortcut.
	pln_cr2_94_02 = "O barco tá esperando vocês. Vão lá!",--Boat's waiting for you. Get there!
	pln_cr2_48_03 = "Esse cartão de acesso abre o portão da doca. Use-o em uma sala de controle.",--That keycard opens the dock gate. Use it in the control room. 
	pln_cr2_32_03 = "Perdi conexão! Religuem a energia, rápido!",--Lost it! Get the power back, quick!
	pln_cr2_96_03 = "Aha, o manifesto da carga. Uma informaçãozinha sobre os contêineres é sempre bem-vinda. Ainda tem bastante coisa, mas diminui o trabalho. Ótimo trabalho!",--Aha, the cargo manifest. A little intel on the containers is always useful. It's still general, but it narrows the field. Nice job!
	pln_cr2_95_02 = "O barco não vai ficar de boa por muito tempo. Vão pra lá, agora!",--The boat won't escape the cops' attention forever. Get there, now!
	pln_cr2_57_01 = "O que estão esperando? Subam a bordo do navio!",--What are you waiting for? Get on the ship!
	pln_cr2_89_01 = "Comecem a arrombar esses contêineres!",--Get drilling those containers!
	pln_cr2_22_01 = "Ele tá vindo com o C4. Esperem um pouco aí, pessoal.",--He's en route now with C4. Just hang in there, gang.
	pln_cr2_110_01 = "É o vestiário dos trabalhadores. Procurem por um cartão de acesso aí.",--This is the workers' locker room. Check for a keycard here.
	pln_cr2_58_03 = "A bomba da Butcher está em um desses contêineres.",--The Butcher's explosives are in one of these containers.
	pln_cr2_12_06 = "Aposto minha grana que os edifícios vão ter os cartões. Procurem eles.",--My money would be on the buildings having the keycards. Search 'em.
	pln_cr2_64_03 = "Tem um barco pronto pra vocês. Vão lá.",--There's a boat ready for you. Head there.        
	pln_cr2_04_01 = "Agora usem o outro cartão de acesso na outra sala de controle. Vamos abrir o portão e deixar a Moretta sair.",--Now use the other keycard in the other control room. Let's open the gate and get the Moretta out!
	pln_cr2_99_01 = "Bom trabalho! Achar loot extra sempre me deixa feliz.",--Good job! Finding extra loot always makes me happy.
	pln_cr2_17_03 = "A Moretta tá indo. Vai demorar um pouco até que ela ancore, então você pode descansar quietinho, ou passar o tempo procurando loot extra. É com você.",--Moretta is on the move. Going to take a while before she is berthed, so you can stay low and quiet, or use the time to hunt down any extra loot. Up to you.
	pln_cr2_06_01 = "Foi o painel esquerdo. Agora procurem outro cartão de acesso. Ativem o outro painel.",--That's the left panel. Now search for the other keycard. Get the other panel activated.
	pln_cr2_87_03 = "Só mais... uns... segundos.",--Just a few... More... Seconds.
	pln_cr2_96_01 = "Parece o manifesto da carga. Bom trabalho! Adianta umas coisas. Vai deixar nosso trabalho mais fácil.",--That looks like the cargo manifest. Good job! It narrows things down. This will make our job easier.
	pln_cr2_28_01 = "C4 posicionado. Saiam do portão agora!",--All C4 in place. Get off of the gate now!
	pln_cr2_76_02 = "É o alarme. Foda-se os cartões - vamos explodir o portão. O Bile tá perto. Acendam um sinalizador, e ele vai deixar o C4.",--That's the alarm. Screw the keycards - we're blowing the gate. Bile is close by. Drop a signal flare, and he'll drop the C4.
	pln_cr2_31_02 = "Estamos dentro. Beleza, deixem os policiais longe. Pode demorar um pouco.",--We're in. Alright, keep the cops off it. Might take some time.
	pln_cr2_113_01 = "Essa é uma sala de controle do navio. Computadores podem ser usados para enviar coordenadas do GPS, ou você pode achar a frequência de rádio da Moretta. Pode ter um cartão de acesso ou rádio aqui.",--This is one of the ship Control Rooms. Computers can be used for entering GPS targets, or you might find Moretta's comm frequency. There could also be a keycard or radio here.
	pln_cr2_56_01 = "Fiquem prontos, pessoal. A Moretta tá quase ancorando.",--Get ready, guys. Moretta's almost at her berth.
	pln_cr2_11_03 = "Esses terminais podem ter informação da Moretta. Podem procurar eles se quiserem. Informações são sempre bem-vindas.",--These terminals likely have info on the Moretta. You can search it if you want. Intel's always useful.
	pln_cr2_97_02 = "Vamos lá, vamos ver o que vocês têm.",--Come on, let's see what you got.
	pln_cr2_101_02 = "Inimigos nos portões, pessoal.",--The enemy are at the gates, gang.
	pln_cr2_28_02 = "C4 posicionado. Limpem o portão!",--That's the C4 done. Clear the gate!
	pln_cr2_83_02 = "Reativem o terminal. Vamos terminar isso.",--Reactivate the terminal. Let's get this finished.
	pln_cr2_34_02 = "Tá feito. A Moretta tá se mexendo! Pode demorar um pouco, então segurem. Tentem não morrer aí.",--It's done. The Moretta is on the move! Might take a while, so bunker down. Try not to die.
	pln_cr2_27_01 = "Só falta um.",--Only one left.
	pln_cr2_36_03 = "Tinha receio disso. Os contêineres se trancaram. Vão ter que arrombá-los.",--I was afraid of this. The containers are shut and locked. Gonna have to drill them.
	pln_cr2_76_01 = "É o alarme e... Porra! Tudo desligou. Ok, esqueçam os cartões de acesso. Vamos explodir o portão. Eu disse que tinha um plano B. Bile vai largar o C4 pra vocês, só acender um sinalizador aonde vocês querem que ele jogue a bolsa com o C4.",--There's the alarm and... Damn! Everything shut down. OK, forget the keycards. We're blowing the gate. I told you I had a plan B. Bile will drop the C4 charges for you, just light a flare to signal him where you want the C4 bag to be dropped.
	pln_cr2_48_01 = "Pessoal! Usem o cartão de acesso na sala de controle da doca. Vamos abrir esse portão.",--Guys! Use the keycard in the dock control room. Get the dock gate open.
	pln_cr2_18_01 = "Ela parou! Subam a bordo e procurem os contêineres!",--She stopped! Get on deck and and search the containers!
	pln_cr2_55_02 = "O alarme! O Stealth já era, gente. Mas o navio tá se movendo, e ela não vai parar agora.",--The alarm! Stealth is out of the window, gang. But the ship is moving, and she ain't gonna stop now.
	pln_cr2_19_01 = "Vocês já acharam as frequências de rádio da Moretta. Não tem porquê ficar olhando os computadores.",--You already found the comm frequencies for the Moretta. No need to keep checking the computers.
	pln_cr2_120_01 = "Tão abrindo as caixas de energia. Não deixem cortar a energia!",--They're opening the powerboxes. Make sure they don't cut the power!
	pln_cr2_08_03 = "A frente ta fechada pra caralho. Deem uma volta. Achem outra entrada.",--The front is shut tight. Take a walk around. Find another way in.
	pln_cr2_108_01 = "Essa é a sala de controle do portão esquerdo. Usem o cartão de acesso aqui.",--This is the Left Control Room for the Dock Gate. Use the Keycard here.
	pln_cr2_102_03 = "O guarda já era. Não precisam se preocupar com câmeras agora.",--That's the guard dealt with. No need to worry about the cameras now.
	pln_cr2_45_03 = "Usem os cartões de acesso nos portões. Deixem a Moretta sair.",--Now use the keycards on the dock gates. Let the Moretta out.
	pln_cr2_124_02 = "Sem frequência aqui. Porra! Então deve estar do outro lado da doca - procurem lá.",--No frequency here. Damn! Then the best bet is the office across the dock - check it out.
	pln_cr2_59_01 = "Caralho! Fecharam os contêineres quando o alarme disparou. Arrombem eles!",--Damn. They locked the containers when the alarm went off. Break through!
	pln_cr2_09_03 = "Finalmente estamos dentro. Ótimo. Agora precisaremos de dois cartões de acesso. Aposto que estarão dentro de algum lugar.",--We're inside. Good. Next, gonna need a couple of keycards. Smart money would be on them being indoors.
	pln_cr2_30_02 = "Com certeza o capitão ouviu isso, então ele não vai mais cooperar. Não temos tempo para forçar ele também, então vamos passar por ele. Hackeie o terminal de controle do navio. Deixem ligado.",--Sure the Captain heard that, so we can rule out him cooperating. No time to turn the screw on him either, so we bypass him. Hack the ship control terminal. Keep it running.
	pln_cr2_90_02 = "A van tá pronta e esperando, pessoal. Movam-se!",--Van's ready and waiting, gang. Move it!
	pln_cr2_02_02 = "Bom trabalho. Só precisam achar mais um cartão de acesso.",--Good work. Just need to find one more keycard.
	pln_cr2_84_02 = "Pessoal, não se esqueçam de religar aquele terminal.",--Guys, don't forget to get that terminal back on.
	pln_cr2_10_03 = "Tão esperando o que? Entrem nas docas.",--What are you waiting for? Into the docks.
	pln_cr2_93_03 = "Precisam voltar pro helicóptero. Rápido!",--You need to get back to the chopper. Hurry!
	pln_cr2_12_02 = "Estão procurando por cartões de acesso. As construções são o melhor lugar.",--You're looking for keycards. The buildings are your best bet.
	pln_cr2_74_02 = "Segurança do navio não sabe de nada. Procurem os explosivos.",--Ship security knows nothing. Track down the explosives.
	pln_cr2_18_03 = "A Moretta tá em posição. Subam a bordo e procurem pelos explosivos. Rápido!",--Moretta is in position. Get on deck and look for the explosives. Move!
	pln_cr2_13_03 = "Precisamos da frequência de rádio do navio. Provavelmente estão em um desses terminais. Procurem por eles!",--We need the ship's comm frequency. Likely on one of these terminals. Search them!
	pln_cr2_64_01 = "O barco já está pronto pra vocês.",--Boat's ready for you.        
	pln_cr2_50_03 = "Os portões não vão abrir com alguém neles. Então cai fora!",--Those gates are rigged to stay locked if someone's on them. So get off!
	pln_cr2_93_01 = "Pessoal! O helicóptero!",--Guys! The chopper! 
	pln_cr2_93_02 = "O helicóptero não pode esperar pra sempre, pessoal. Vão lá, vão embora!",--Chopper can't hang around forever, gang. Get there, get out!
	pln_cr2_72_02 = "E eles ainda não sabem que estão ai. Continuem assim enquanto a Moretta ancora.",--And they still don't know you're there. Keep it that way while the Moretta docks.
	pln_cr2_73_02 = "Tudo quieto. Continuem assim. Agora embarquem no navio.",--All's still quiet. Keep it that way. 	.
	pln_cr2_78_02 = "Precisamos explodir aquele portão. Plantem o C4 nele.",--We have to blow that gate. Get the C4 on it.
	pln_cr2_68_02 = "Tudo quieto ainda. Fantástico! Agora abra aquele portão.",--It's all quiet still. Fantastic. Now open the gate.
	pln_cr2_41_03 = "Primeira sala de controle. A outra está do outro lado da doca. Conseguem ver?",--First control room. The other is across the dock. You see it?
	pln_cr2_55_03 = "É o alarme. Beleza, peguem as armas! Não se preocupem com a Moretta. Ela não vai parar de andar.",--That's the alarm. Alright, weapons hot! Don't worry about the Moretta. She's moving and is gonna keep moving.
	pln_cr2_29_01 = "Isso foi muito louco, gente!",--That was crazy guys!
	pln_cr2_71_02 = "Monitorando o rádio deles - ninguém suspeita de nada. Agora vão para o computador.",--Monitoring their comms - no-one suspects a thing. Now get to the computer.
	pln_cr2_22_02 = "O Plano B tá chegando. O C4 vai fazer um barulhão.",--Plan B is en route, though. C4 can do the job loudly.
	pln_cr2_60_03 = "Sem explosivos. Próximo contêiner!",--No explosives. Next container!
	pln_cr2_62_02 = "Nada. Porra! Tem mais por aí?",--Nothing. Damn! Are there more around?
	pln_cr2_119_01 = "Botando o lixo pra fora né?",--Taking out the trash, eh?
	pln_cr2_01_01 = "Ai está o estaleiro, bem à frente. Entrem. Cuidado com os seguranças.",--There's the dockyard, right ahead. Get inside. Watch the security though.
	pln_cr2_56_03 = "O navio tá quase lá, pessoal. Estejam prontos.",--The ship is almost there, gang. Be ready.
	pln_cr2_61_01 = "Uma caixa. Pode ser a bomba da nossa garota. Agora olhem dentro!",--A case. Could be our girl's explosives. Check what's inside, now!
	pln_cr2_01_02 = "Entrem no estaleiro, gente. Fiquem de olho nos seguranças e nas câmeras. Vão.",--Into the dockyard, gang. Keep an eye out for security and cameras. Go.
	pln_cr2_02_03 = "Um cartão de acesso pro portão. Vamos precisar de outro.",--A keycard for the gate. Gonna need another, though.
	pln_cr2_06_02 = "Painel esquerdo ativado. Agora peguem outro cartão de acesso e vamos ativar o segundo painel.",--Left panel's activated. Now get another keycard, and let's get the second panel done.
	pln_cr2_08_02 = "Acharam que só iam sair andando pelo portão principal? Procurem por outra entrada.",--You thought you were just going to stroll in through the main entrance? Look around for another way in.
	pln_cr2_09_01 = "Ótimo. Certo. Próximo passo é achar dois cartões de acesso. Provavelmente dentro dos prédios.",--Great. Alright. Next step is to find two keycards. Most likely indoors.
	pln_cr2_103_03 = "Guardas abatidos! Não precisam se preocupar mais com as câmeras.",--Guards are down. Don't worry about the cameras now. 
	pln_cr2_105_01 = "A Moretta vai ser movida até a Doca 3B... Assim que você executar o plano.",--Moretta will be moved to Dock 3B... Once you execute all the necessary steps.
	pln_cr2_10_01 = "Pessoal, precisam entrar no estaleiro.",--Guys, you gotta get into the dockyard.
	pln_cr2_118_03 = "Hora da janta, peixinhos.",--Dinner time, little fishies.
	pln_cr2_119_02 = "Ninguém vai ver isso ai.",--No one'll see that there.
	pln_cr2_120_02 = "Policiais estão nas caixas de energia. Não deixem desligá-las.",--Cops are at the powerboxes. Don't let them cut the juice.
	pln_cr2_122_02 = "Por que ainda estão olhando os contêineres? Já possuem a bomba!",--Why're you still searching containers? You got the bomb!
	pln_cr2_124_01 = "A frequência de rádio não tá aqui. Beleza, procurem nos terminais do outro lado do estaleiro.",--The comm frequency ain't here. Alright, then check the terminals in the office across the dockyard.
	pln_cr2_125_01 = "É nosso navio. A Moretta. Mas não da pra acessar daqui. Precisamos movê-la pra Doca 3B.",--That's our ship. The Moretta. But we can't get on it from here. You gotta move it to dock 3B.
	pln_cr2_125_03 = "A Moretta - É a nossa garota, mas não da pra embarcar daqui. Precisam mover ela até a Doca 3B.",--The Moretta - That's our girl. But we can't get on board here. You have to see her moved to dock 3B.
	pln_cr2_12_04 = "Talvez nos edifícios tenham cartões de acesso.",--Maybe the buildings are your best chance for finding keycards.
	pln_cr2_19_02 = "O que tem de errado com você? Já possuem as frequências!",--What's wrong with you? You have the frequencies!
	pln_cr2_20_02 = "Ótimo trabalho ficando quieto. Eles não suspeitam de você, então os contêineres estão destrancados. Divirtam-se!",--Great job keeping it quiet. They don't suspect you, so the containers are unlocked. Have at it!
	pln_cr2_21_02 = "Essas frequências vão ser úteis depois. Por enquanto continuem focados no trabalho.",--These frequencies will be useful later on. For now, though, stay focused on the job.
	pln_cr2_23_01 = "Aí, o helicóptero deixou a bolsa. Vão pegar o C4, pessoal.",--There, chopper dropped the bag. Go pick up the C4, guys.
	pln_cr2_23_03 = "Ok, ai está o C4. Fiquem à vontade!",--OK, there's the C4. Help yourself!
	pln_cr2_26_01 = "Meio caminho andado.",--Halfway there.
	pln_cr2_27_02 = "Só mais um.",--Just one more.
	pln_cr2_28_03 = "C4 posicionada! Agora vamos explodir o portão.",--C4's all done. Now let's blow the gate.
	pln_cr2_30_01 = "Bom, o capitão não vai colaborar com a gente agora, mas ainda precisamos mover o navio. Hackeiem o terminal de controle do navio e mantenham ligado.",--Well, we're not getting the Captain's cooperation now, but we still need that ship moved. Just hack the ship control terminal and make sure it stays on.
	pln_cr2_32_01 = "Cortaram a energia. Religuem ela.",--They cut the power. Get it back on.
	pln_cr2_33_01 = "Ótimo. Posso continuar o trabalho agora.",--Good. I can get on with the work now.
	pln_cr2_34_03 = "A Moretta tá ligando. Deixem ela ir ancorar. Guardem as armas.",--Moretta is powering up. Let it move to its berth. Weapons free.
	pln_cr2_35_02 = "A Moretta ancorou. Hora de uma embarcagem hostil.",--Moretta's at the berth. Time for a hostile boarding.
	pln_cr2_39_01 = "Podem usar o pé-de-cabra para abrir as caixas.",--You can use the crowbar to open up shipping crates.
	pln_cr2_39_03 = "Um pé-de-cabra. Ótimo achado. Sempre útil.",--A crowbar. Good find. Always useful.
	pln_cr2_40_03 = "Precisaremos ligar para a Moretta, e pra isso vamos precisar das frequências de rádio. Procurem por elas.",--Gonna need to call the Moretta, and for that we need the comm frequencies. Search for it.
	pln_cr2_42_01 = "Aqui é a segunda sala de controle do portão.",--And here's the second control room for the gate.
	pln_cr2_43_03 = "Os vagões no trem podem estar carregados. E talvez tenham loot. Podem vê-los?",--The wagons on the train might be loaded. And might have loot. Check 'em out?
	pln_cr2_44_02 = "Um cartão de acesso, mas inútil pra caralho agora. O alarme disparou. Foquem no objetivo.",--A keycard, but no damn good right now. Alarm's been sounded. Stay focused on the task.
	pln_cr2_49_01 = "Gente! Usem os cartõs de acesso nas salas de controle das docas. Abram esse portão.",--Guys! Use the keycards in the dock control rooms. Get the dock gate open.
	pln_cr2_49_02 = "Podem usar esses cartões de acesso na sala de controle. Só deslizar eles e abrir a doca.",--You can use those keycards in the control rooms. Just swipe 'em, open the dock.
	pln_cr2_50_02 = "O portão não vai abrir com você em cima, gênio. Limpem a área!",--Gate won't open with you standing on it, genius. Clear the area!
	pln_cr2_51_01 = "Beleza, doca aberta. Agora precisamos chamar a Moretta e mover ela. Frequências de rádio devem estar em um dos computadores nos escritórios. Encontre-as. Eu vou improvisar e conversar.",--Alright, dock's opened. Now we gotta call the Moretta. Get her moving. Comm frequencies should be on one of the computers in the offices. Find it. I'll patch in and do the talking.
	pln_cr2_51_02 = "Boa! A doca tá abrindo. Próximo passo: fazer a Moretta andar até o ancoradouro. Preciso conversar com ela diretamente. Achem a frequência de rádio - bem provável que esteja em um computador nos escritórios. Encontre-as.",--Nice! Dock is opening. Next step: get the Moretta moving to her berth. I need to talk to her directly. Find me the comm frequency - most likely on a computer in the offices there. Find it.
	pln_cr2_52_01 = "É isso ai. Portão da doca abereto. Agora vamos mover esse navio. Temos a frequência de rádio. Achem um rádio e me coloquem pra falar.",--That's it. Dock gate's opened. Now let's get the ship moving. We have the comm frequency. Just find the radio and patch me in.
	pln_cr2_52_02 = "Acabou a parte do portão. Agora só precisamos mover o navio. A frequência que acharam antes vai servir. Encontrem um rádio e me deixem falar com a Moretta.",--That's it for the gate. Now we just got to get the ship moving. That frequency you found earlier will do it. Find a radio and let me talk to the Moretta
	pln_cr2_57_02 = "Eu não quero deixar uma pessoa que a chamam de Butcher esperando. Embarquem no navio!",--I don't want to keep someone who calls herself the Butcher waiting. Get onto the ship!
	pln_cr2_57_03 = "A Moretta tá ancorada e pronta pra vocês, palhaços.",--Moretta is berthed and ready for you, clowns.
	pln_cr2_58_02 = "Vamos, olhem esses contêineres.",--Come on, check those containers.
	pln_cr2_60_01 = "Nada aqui. Continuem olhando!",--Nothing in here. Keep looking!
	pln_cr2_60_02 = "Vazio! Próximo.",--Empty! Move on.
	pln_cr2_63_02 = "Bingo! Agora assegurem as partes da bomba.",--Bingo! Now secure the bomb-parts.
	pln_cr2_67_03 = "Tudo continua quieto. Ótimo. Lembrem-se - precisam de cartões de acesso.",--You're keeping it quiet. Great. Remember - you need keycards.
	pln_cr2_69_01 = "Acho que ninguém sabe que estão aí. Agora peguem a frequência de rádio.",--Don't think anyone knows you're there. Now get the comm frequency.
	pln_cr2_73_03 = "Ainda não sabem da sua presença. Embarquem no navio. Continuem quietos.",--They still don't know you're there. Get on the ship. Keep it quiet.
	pln_cr2_75_02 = "Agora saiam daí sem disparar o alarme, e isso vai ter sido um trabalho stealth perfeito!",--Now get out of there without triggering the alarm, and this is a perfect stealth job.
	pln_cr2_78_01 = "Plantem o C4 no portão!",--Place the C4 on the gate!
	pln_cr2_79_01 = "Se afastem do portão! Rápido!",--Get away from the gate! Fast!
	pln_cr2_84_01 = "Religuem o computador, gente.",--Reactivate the computer, gang.
	pln_cr2_85_01 = "Não deixem eles chegar perto das caixas de energia.",--Don't let them get close to the power boxes.
	pln_cr2_87_01 = "Quase... pronto. Só um momento, pessoal.",--Almost... Done. Just a moment now, guys.
	pln_cr2_89_03 = "Coloquem suas furadeiras nesses contêineres, palhaços.",--Get your drills on those containers, clowns.
	pln_cr2_91_02 = "A van é sua fuga desse lugar. Cheguem nela!",--The van is your way out of there. Get to it!
	pln_cr2_91_03 = "Seu motorista de fuga já estacionou. Vão pra lá, agora!",--Your escape driver's parked up. Get back there - now!
	pln_cr2_92_01 = "Vão para o helicóptero!",--Get to the chopper!
	pln_cr2_92_03 = "Voltem essas bundas para o helicóptero, palhaços.",--Haul ass back to the chopper, clowns.
	pln_cr2_97_03 = "Espero que tenha algo valiso aqui.",--Hope there's something worthwhile in here.
	pln_cr2_99_02 = "Boa! Podemos levar isso e fazer um dinheirinho extra.",--Nice! We can shift that, make a little extra dollar.
	pt1_cr2_02_03 = "Acabei de jogar a carga. Espero que vocês usem bem.",--Dropped the cargo. Hope you guys use it well.
	pt1_cr2_02_01 = "Pacote no chão. boa sorte lá fora!",--Package on the ground. Good luck out there!
	pt1_cr2_01_03 = "OK. Eu estou aqui e totalmente pronto para fazer a sua entrega.",--OK. I'm here and ready to drop your delivery.
	pt1_cr2_01_01 = "Cuidado aí em baixo. Estou jogando o pacote.",--Look out below. I'm dropping the package.
	pt1_cr2_01_02 = "Atenção. Entreguei o seu pedido.",--Heads up. Dropping your order.
	pt1_cr2_02_02 = "Pacote entregue. Fique vivo.",--Package dropped. Stay alive.
	cpn_cr2_01_01 = "Rádio do Porto de Washington um zero um E. Aqui é a Moretta. Câmbio.",--Port of Washington Radio one zero one E. This is Moretta. Over.
	cpn_cr2_02_01 = "Rádio do Porto de Washington. Aqui é Moretta. Aguardando pelo recebimento dos dados do GPS. Câmbio.",--Port of Washington radio. This is Moretta. Standing by to receive GPS data. Over.
	
	-- Objetivos
	hud_heist_crojob1_mission8_b = "Pegue as partes da bomba do contêiner e leve-as até o helicóptero.",--Take the bomb parts from the containers and take them to the helicopter.
	hud_heist_crojob1_mission9_a_hl = "Fuga da Van Disponível",--Van escape available
	hud_heist_crojob1_mission3_01 = "Procure pela Frequência de Rádio da Moretta nos computadores.",--Search for the Moretta's Comm Frequency on the computers.
	hud_heist_crojob1_mission6_02_b_hl = "Suba a bordo do Navio",--Get on the ship
	hud_heist_crojob1_mission2_b_00_hl = "Acenda um dos Sinalizadores",--Light one of the flares
	hud_heist_crojob1_mission2_b_02 = "Pegue o C4 da bolsa que foi deixada pelo helicóptero.",--Collect the C4 from the bag that was dropped by the chopper.
	hud_heist_crojob1_mission5_a = "Use o computador na sala de controle de navio e insira as coordenadas do GPS.",--Use the computer in the ship control room and enter the GPS coordinates.
	hud_heist_crojob1_mission6_01_hl = "Espere o Navio se mover",--Wait for the ship to move
	hud_heist_crojob1_mission5_b_02 = "Espere o hack terminar e mantenha a energia ligada.",--Wait for the hack to finish and make sure the power stays on.
	hud_heist_crojob1_mission1_01_hl = "Entre no Estaleiro",--Enter the Dockyard
	hud_heist_crojob1_mission3_01_hl = "Encontre a Frequência de Rádio da Moretta",--Find the Moretta's Comm Frequency
	hud_heist_crojob1_mission6_02_a_hl = "Suba a bordo do Navio",--Get on the ship
	hud_heist_crojob1_mission2_b_00 = "Acenda o Sinalizador para o piloto do helicóptero saber aonde você quer que ele jogue o C4.",--Light the flare to signal to the chopper pilot where you want him to drop the C4
	hud_heist_crojob1_mission8_b_hl = "Leve as partes da Bomba até o Helicóptero",--Take the bomb parts to the helicopter
	hud_heist_crojob1_mission5_b_01_hl = "Hackeie o Terminal de Controle do Navio",--Hack the ship control terminal
	hud_heist_crojob1_mission7_a_hl = "Abra os Contêineres",--Open the containers
	hud_heist_crojob1_mission1_02 = "Procure por cartões de acesso, você precisa de 2 deles para abrir o portão da doca. Procure por eles dentro de edifícios. Olhe perto das mesas com computadores. Verifique o vestiário também. Não perca tempo procurando eles na parte de fora.",--Look for the keycards, you need 2 of them to open the dock gate. Check inside the buildings for them. Look on the tables and near computers. Check the locker room, too. Don't waste your time looking for them outside.
	hud_heist_crojob1_mission5_b_01 = "Hackeie o terminal de controle do navio para iniciar o procedimento de movimentação do navio.",--Hack the ship control terminal to start the ship moving procedure.
	hud_heist_crojob1_mission5_b_04_hl = "Reative o Computador",--Reactivate the computer
	hud_heist_crojob1_mission10 = "Pegue as partes da bomba da caixa.",--Take the bomb parts from the case.
	hud_heist_crojob1_mission3_02_hl = "Chame o Capitão",--Call the captain
	hud_heist_crojob1_mission9_b_hl = "Fuga de Helicóptero Disponível",--Helicopter escape is available
	hud_heist_crojob1_mission5_b_04 = "Use o teclado para reativar o computador e continuar hackeando.",--Use the keyboard to reactivate the computer and continue the hacking.
	hud_heist_crojob1_mission9_b = "Fuga disponível. O helicóptero espera por você. Pode ir embora ou ficar para mais loot.",--The escape is now available. The helicopter is waiting for you. You can leave or stay for more loot.
	hud_heist_crojob1_mission2_b_01 = "Espere o helicóptero chegar com o C4 e largar para você. Isso vai levar um tempo.",--Wait for the chopper to arrive with the C4 and drop it for you. This will take some time.
	hud_heist_crojob1_mission5_b_03_hl = "Ligue a Energia de volta",--Turn the power back on
	hud_heist_crojob1_mission5_b_02_hl = "Espere o Hack terminar",--Wait for the hack to finish
	hud_heist_crojob1_mission3_02 = "Use o rádio dentro de uma das construções e ligue para o capitão da Moretta. Bain vai convencê-lo a mover o navio.",--Use the radio inside one of the buildings and call the Moretta's captain. Bain will talk with him and convince him to move the ship.
	hud_heist_crojob1_mission8_c_hl = "Leve as partes da Bomba até o Barco",--Take the bomb parts to the boat
	hud_heist_crojob1_mission9_c = "Fuga disponível. O barco espera por você. Pode ir embora ou ficar para mais loot.",--The escape is now available. The boat is waiting for you. You can leave or stay for more loot.
	hud_heist_crojob1_mission8_a = "Pegue as partes da bomba do contêiner e leve-as até a van.",--Take the bomb parts from the containers and take them to the van.
	hud_heist_crojob1_mission2_b_03 = "Posicione o C4 no portão da doca.",--Place the C4 on the dock gate.
	hud_heist_crojob1_mission1_02_hl = "Encontre 2 Cartões de Acesso",--Find 2 keycards
	hud_heist_crojob1_mission10_hl = "Pegue a Bomba",--Take the bomb
	hud_heist_crojob1_mission8_a_hl = "Leve as partes da Bomba até a Van",--Take the bomb parts to the van
	hud_heist_crojob1_mission9_c_hl = "Fuga de Barco Disponível",--Boat escape available
	hud_heist_crojob1_mission2_b_02_hl = "Pegue o C4",--Collect the C4
	hud_heist_crojob1_mission1_01 = "Entre no Estaleiro e procure por 2 cartõs de acesso.",--Enter the Dockyard and start looking for the 2 keycards.
	hud_heist_crojob1_mission6_01 = "Espere o navio se mover até a Doca 3B.",--Wait for the ship to move to Loading Dock 3B.
	hud_heist_crojob1_mission2_b_04_hl = "Exploda o Portão da Doca",--Blow up the dock gate
	hud_heist_crojob1_mission7_b_hl = "Perfure os Contêineres",--Drill into the containers
	hud_heist_crojob1_mission7_b = "Os contêineres foram trancados quando o alarme disparou. Perfure os contêineres e procure pela caixa da bomba.",--The containers were locked when the alarm went off. Drill into the containers and look for the bomb case.
	hud_heist_crojob1_mission2_a = "Use os cartões de acesso que achou para abrir o portão da doca. Insira-os no painel dentro da sala de controle perto do portão.",--Use the keycards you found to open the dock gate. Insert them into a panel located inside the dock control room close to the gate.
	hud_heist_crojob1_mission7_a = "Abra os contêineres e procure pela caixa da bomba.",--Open the containers and look for the bomb case.
	hud_heist_crojob1_mission2_a_hl = "Abra o Portão da Doca",--Open the dock gate
	hud_heist_crojob1_mission6_02_b = "Embarque no navio e comece a perfurar os contêineres.",--Get on the ship and start drilling the containers.
	hud_heist_crojob1_mission9_a = "Fuga disponível. A Van espera por você. Pode ir embora ou ficar para mais loot.",--The escape is now available. The van is waiting for you. You can leave or stay for more loot.
	hud_heist_crojob1_mission2_b_03_hl = "Plante o C4",--Place the C4
	hud_heist_crojob1_mission5_a_hl = "Insira as Coordenadas do GPS",--Enter GPS coordinates
	hud_heist_crojob1_mission2_b_04 = "Saia do portão e exploda-o.",--Get off the dock gate and blow it up.
	hud_heist_crojob1_mission6_02_a = "Embarque no navio e comece a abrir os contêineres.",--Get on the ship and start opening the containers.
	hud_heist_crojob1_mission5_b_03 = "Encontre o disjuntor e religue a energia para continuar hackeando.",--Find the circuit breaker to turn the power back on and continue the hacking.
	hud_heist_crojob1_mission2_b_01_hl = "Espere pelo Helicóptero",--Wait for the chopper
	hud_heist_crojob1_mission8_c = "Pegue as partes da bomba do contêiner e leve-as até o barco.",--Take the bomb parts from the containers and take them to the boat.
		})
end)