Hooks:Add("LocalizationManagerPostInit", "covercharon", function(loc)
	LocalizationManager:add_localized_strings({
	-- Nomes e Descrições
	heist_spa = "Brooklyn 10-10",--Brooklyn 10-10
	heist_spa_hl = "Brooklyn 10-10",--Brooklyn 10-10
	heist_spa_crimenet = "Vocês vão para Nova Iorque hoje a noite. O Continental nos chamou - um dos principais agentes dele foi capturado e está sendo mantido preso por um bando de mercenários desconhecidos em um lugar do Brooklyn. Nós conseguimos a localização por meio de uma chamada que o próprio cara fez quando foi sequestrado. O nome dele é Charon. Nós precisamos chegar lá rápido, matar quem quer que tenha o sequestrado e levem-o de volta ao Continental sem que ele se machuque.$NL;$NL;» Localize o Charon$NL;» Resgate-o e o Proteja dos Mafiosos$NL;» Pegue de volta aquilo que foi Roubado$NL;» Fuja",--You're going to New York tonight. The Continental called - one of their key staff has been ambushed and is being held by unknown assailants at an address in Brooklyn. We have the location from a call he made just as they took him. The target's name is Charon. We need to get there fast, take out whoever's got him and send him back to the Continental safe and sound.$NL;$NL;» Locate Charon$NL;» Rescue Charon and protect him from the attackers$NL;» Get back what was stolen$NL;» Escape
	heist_spa_hl_briefing = "Okay... Vamos resgatar o Charon. Isso para mim é pessoal, então vamos nos manter focados.",--Okay... Let's get Charon out. This is personal for me, so let's stay sharp.
	
	-- Legendas (Bain)
	pln_spa_intro_01 = "Ok, vamos encontrar esse cara, ele deve estar por aqui em algum lugar.",--Ok, let's find this guy. He should be around here somewhere.
	pln_spa_intro_02 = "Certifiquem-se de encontrar ele rápido. Vocês não sabem o que vão fazer com ele.",--Make sure you find the target quickly. You don't know what they'll do to him.
	pln_spa_intro_03 = "Ok, pessoal. Encontrem ele e tirem-o daí",--Ok, guys. Find the target and get him out of there.
	pln_spa_08_01 = "Porra, são os policiais! Tudo que a gente precisava!",--Damn, it's the cops! Just what we need!
	pln_spa_16_03 = "Vocês vão precisar perfurar essa grade para pegar a maleta.",--You'll need to drill that gate to get the briefcase!
	pln_spa_19_02 = "Vejamos... se vocês cruzarem a rua, vocês devem conseguir vazar daí.",--Let's see... if you cross the street you should be able to get out of here.
	pln_spa_12_06 = "Mexam-se para o outro prédio. Andem!",--Move to the next building. Come on!
	pln_spa_12_02 = "Pessoal, mexam-se! O Charon vai encontrar vocês no outro prédio.",--Guys, move! Charon will meet you in the other building.
	pln_spa_18_03 = "O Charon está esperando lá em baixo. Desçam pelo alçapão do elevador!",--Charon is waiting down there! Get down the elevator shaft!
	pln_spa_06_03 = "Snipers! Vocês precisam acabar com eles.",--Snipers! You gotta take 'em out!
	pln_spa_15_02 = "Essa grade vai queimar igual manteiga quando vocês aplicarem a thermite. Vão pegar a maleta!",--That gate will melt like butter when you apply the thermite. Go get the briefcase!
	pln_spa_16_02 = "Perfurem essa grade! Peguem a maleta!",--Drill that gate! Get the briefcase!
	pln_spa_20_01 = "O Twitch vai chegar aí com uma van em mais ou menos um minuto. Aguentem aí.",--Twitch will be there with the van in about a minute. Hold on.
	pln_spa_05_08 = "Limpem a rua para o Charon.",--Clear the street for Charon!
	pln_spa_07_06 = "Ah não - mais Snipers!",--Oh no - more snipers!
	pln_spa_10_02 = "Mais policiais. Mostrem o inferno para eles!",--More cops! Give 'em hell!
	pln_spa_14_01 = "Aí está a maleta! Mas vocês não podem furar essa grade. Vejam se encontram um pouco de thermite.",--There's the briefcase! But you can't drill that gate. See if you can find some thermite.
	pln_spa_19_03 = "Vocês devem conseguir encontrar uma rota de fuga se sairem e cruzarem a rua.",--You should be able to find an escape route if you get out and cross the street.
	pln_spa_03_03 = "Matem esse Sniper!",--Get that sniper!
	pln_spa_12_08 = "O Charon está esperando por vocês, pessoal! Movam-se!",--Charon is waiting for you, guys! Get moving!
	pln_spa_05_02 = "Ajudem o Charon! Matem-os!",--Help Charon! Take 'em out!
	pln_spa_19_01 = "Aguentem aí pessoal, eu estou procurando por uma rota de fuga. Se vocês cruzarem a rua, vocês devem conseguir vazar daí.",--Hold on guys, I'm looking for a way out. If you cross the street you should be able to get out of here.
	pln_spa_25_02 = "Lembrem-se de ajudar o Charon lá fora!",--Remember to help Charon out of here!
	pln_spa_cnc_03 = "Vocês precisam acelerar aí, pessoal. O Continental acabou de chamar, vocês estão indo para Nova Iorque em uma missão de resgate.",--Gotta hurry, guys. The Continental just called, you're going to New York on a rescue mission.
	pln_spa_25_04 = "Certifiquem-se de resgatar o Charon ainda vivo!",--Make sure you get Charon out of here alive!
	pln_spa_18_02 = "Desçam pelo alçapão do elevador e encontrem com o Charon.",--Go down the elevator shaft and meet up with Charon!
	pln_spa_12_01 = "Andem logo pessoal, vocês precisam ir para o outro prédio.",--Hurry up guys, you need to move to the other building.
	pln_spa_07_01 = "Mais Snipers vindo!",--More snipers incoming!
	pln_spa_26_03 = "Tem mais deles lá na rua! Matem-os!",--There are more of them down in the street! Take 'em out!
	pln_spa_04_01 = "Rápido pessoal, encontrem ele e matem-o!",--Quickly guys, find him and take him out!
	pln_spa_08_03 = "Parece que alguém chamou a polícia! Protejam o Charon pessoal!",--Looks like someone called the cops! Guys, protect Charon!
	pln_spa_04_07 = "Matem o Sniper, pessoal!",--Take the sniper out, guys!
	pln_spa_01_01 = "Esse cara é realmente foda! Parece que ele se salvou sozinho! Mas vocês ainda precisam ajudar ele!",--This guy's something else! Looks like he broke free on his own! But you gotta help him!
	pln_spa_28_05 = "Andem pessoal, peguem a maleta.",--Come on guys - the briefcase!
	pln_spa_01_02 = "Parece que o Charon conseguiu se safar sozinho! Agora ajudem ele a sair daí vivo!",--Looks like Charon freed himself! Now help him get out of here alive!
	pln_spa_28_01 = "Pessoal! Vocês precisam pegar essa maleta!",--Guys! You need to get that briefcase!
	pln_spa_14_03 = "Vocês precisam abrir essa grade para pegar a maleta. Vejam se encontram um pouco de thermite.",--You need to open that gate to get the briefcase. See if you can find some thermite.
	pln_spa_28_03 = "A maleta! Não a deixem para trás!",--The briefcase! Don't leave it behind!
	pln_spa_15_01 = "Peguem a maleta! A thermite vai derreter as barras dessa grade.",--Get the briefcase! The thermite will burn right through that gate.
	pln_spa_13_01 = "Mais Snipers! Protejam o Charon!",--More snipers! Protect Charon!
	pln_spa_09_02 = "Ótimo trabalho, pessoal - mas a polícia de NY não vai desistir tão fácil assim.",--Good work, gang - but the NYPD won't give up so easily.
	pln_spa_28_04 = "Peguem a maleta, pessoal!",--Get that briefcase, guys!
	pln_spa_08_02 = "São os policiais! Deem um jeito neles, pessoal! Protejam o Charon!",--It's the cops! Gang, deal with them! Protect Charon!
	pln_spa_12_03 = "Continuem em frente, pessoal. Vocês precisam chegar no próximo prédio.",--Keep moving, guys. You gotta go to the next building.
	pln_spa_21_01 = "Charon? Você está bem?",--Charon? Are you ok?
	pln_spa_04_05 = "Vocês precisam matar aquele Sniper!",--You gotta take the sniper out!
	pln_spa_05_01 = "Vocês precisam ajudar o Charon! Limpem a rua!",--You gotta help Charon! Clear the street!
	pln_spa_23_01 = "Vão para as janelas, que aí vocês vão conseguir ter uma visão da rua.",--Move up to the windows so you get a view of the street!
	pln_spa_23_02 = "Vão para as janelas, vejam o que está acontecendo!",--Move up to the windows, see what's going on!
	pln_spa_04_06 = "Não deem nem chance para esse Sniper!",--Don't give that sniper time!
	pln_spa_05_05 = "Limpem a rua!",--Clear the street!
	pln_spa_24_02 = "O veículo de fuga não vai conseguir chegar em vocês a menos que vocês movam esse carros da polícia.",--The escape van won't be able to get through unless you move those police cars!
	pln_spa_07_04 = "Fiquem atentos, mais Snipers!",--Watch out, more snipers!
	pln_spa_20_03 = "A van deve chegar aí em um minuto.",--The van should be there in a minute. 
	pln_spa_28_07 = "Não esqueçam a maleta do Charon!",--Don't forget Charon's briefcase!
	pln_spa_17_01 = "Ótimo! Agora peguem essa maleta!",--Great! Not gew the briefcase!
	pln_spa_07_02 = "Eles estão mandando outro grupo de Snipers!",--They're deploying another group of snipers!
	pln_spa_01_03 = "Parece que ele mesmo se salvou e conseguiu uma arma! Vocês precisam ajudá-lo!",--Looks like he broke free and took a gun! You gotta help him!
	pln_spa_02_01 = "Fiquem de olho nessas janelas, talvez tenham Snipers.",--Watch those windows, there might be snipers.
	pln_spa_02_02 = "Tem algo estranho aqui - eu acho que devem ter Snipers nessas janelas.",--Something's fishy here - I think there might be snipers in those windows.
	pln_spa_02_03 = "Fiquem atentos, pessoal, esse lugar inteiro cheira a Snipers.",--Stay sharp, guys, this whole place smells of sniper.
	pln_spa_03_01 = "Encontrem esse Sniper e matem-o antes que ele atire.",--Find the sniper and take him out before he takes the shot!
	pln_spa_03_02 = "Encontrem esse Sniper e matem-o",--Find that sniper and take him out!
	pln_spa_04_02 = "Matem esse Sniper, pessoal.",--Take out that sniper, guys!
	pln_spa_04_03 = "Matem o Sniper, pessoal.",--Get the sniper guys!
	pln_spa_04_04 = "Matem o Sniper!",--Take the sniper out!
	pln_spa_04_08 = "Pessoal! O Sniper! Matem-o!",--Guys! The sniper! Get him!
	pln_spa_05_03 = "Tem uns caras na rua - matem-os!",--The guys in the street - take 'em out!
	pln_spa_05_04 = "Vocês precisam limpar a rua!",--You gotta clear the street!
	pln_spa_05_06 = "Matem esses caras que estão na rua!",--Take those guys in the street out!
	pln_spa_05_07 = "Limpem a rua para o Charon poder prosseguir!",--Clear the street so Charon can move!
	pln_spa_06_01 = "Fiquem de olho, eles estão mandando mais Snipers!",--Watch out, they're deploying more snipers!
	pln_spa_06_02 = "Snipers! Matem-os, pessoal!",--Snipers! Take 'em out, gang!
	pln_spa_07_03 = "Mais Snipers!",--More snipers!
	pln_spa_07_05 = "Eles estão mandando mais Snipers!",--They got more snipers incoming!
	pln_spa_07_07 = "Mais Snipers a caminho! Fiquem de olho!",--More snipers incoming! Watch out!
	pln_spa_07_08 = "Mais Snipers? Esses caras realmente não estão de brincadeira!",--More snipers? These guys mean business!
	pln_spa_09_01 = "Vocês mostraram mesmo para polícia de NY como se dança. E eu tenho um pressentimento de que eles que eles vão mandar mais dançarinos.",--You really showed the NYPD how to dance. And I have a feeling they'll send more dancers.
	pln_spa_09_03 = "Um dia tenso para a polícia de NY. E vai ficar mais tenso ainda - Tenho certeza que eles vão mandar mais reforços.",--A rough day for the NYPD. And it'll get rougher - I'm sure they'll send more reinforcements.
	pln_spa_10_01 = "Mais policiais chegando!",--More cops are arriving!
	pln_spa_10_03 = "Mais policiais a caminho, pessoal!",--More cops incoming, guys!
	pln_spa_10_04 = "Porra, tem mais policiais vindo!",--Damn, there are more cops incoming!
	pln_spa_11_01 = "Vocês ouviram ele pessoal, continuem em frente!",--You heard him guys, get going!
	pln_spa_11_02 = "Ok pessoal, cruzem o telhado.",--Ok guys, go across the roof!
	pln_spa_11_03 = "Vão para o telhado pessoal. Mexam-se!",--It's the roof, guys. Get moving!
	pln_spa_12_04 = "Andem logo! Vão para o outro prédio.",--Hurry up! Move to the next building.
	pln_spa_12_05 = "Andem logo, pessoal. Vão para o próximo prédio.",--Come on guys! Move to the next building.
	pln_spa_12_07 = "Vão para o outro prédio. Vocês precisam se encontrar com o Charon!",--Move into the other building. You gotta rendezvous with Charon!
	pln_spa_13_02 = "Mais Snipers vindo! Matem-os!",--More snipers! Take 'em out!
	pln_spa_13_03 = "Snipers de novo! Matem-os!",--Snipers again! Take 'em out!
	pln_spa_14_02 = "Essa grade parece bem forte. Vejam se vocês conseguem encontrar thermite ou algo assim. Vocês precisam pegar aquela maleta.",--That gate looks tough. See if you can find some thermite or something. You have to get that briefcase.
	pln_spa_15_03 = "Aquela thermite vai abrir essa grade alguma hora. Peguem a maleta!",--That thermite will open the gate for you in no time. Get the briefcase!
	pln_spa_16_01 = "Peguem aquela maleta! Vocês vão precisar perfurar a grade.",--Get the briefcase! You'll need to drill the gate.
	pln_spa_17_02 = "Ok! Peguem a maleta!",--Ok! Get the briefcase!
	pln_spa_17_03 = "Ótimo trabalho! Agora peguem a maleta!",--Great job! Now get that briefcase!
	pln_spa_18_01 = "Desçam pelo alçapão do elevador para se encontrarem com o Charon!",--Get down that elevator shaft so you can meet up with Charon!
	pln_spa_20_02 = "O Twitch está a caminho com a van. Um minuto.",--Twitch is on his way with the van. One minute.
	pln_spa_21_02 = "O que houve Charon? Vocês está bem?",--What's wrong, Charon? You ok?
	pln_spa_21_03 = "Charon? O que houve, você está bem?",--Charon? What's up, you ok?
	pln_spa_22_01 = "É melhor você encontrar cobertura e se certificar que não é nada grave.",--You'd better find some cover and make sure it's nothing bad.
	pln_spa_22_02 = "Você devia se cobrir em algum lugar e certificar que está tudo bem.",--You should get in cover for a moment and make sure it's ok.
	pln_spa_22_03 = "Você tem certeza? Melhor se abaixar e certificar que está tudo bem.",--You sure? Better duck down and make sure it's ok.
	pln_spa_23_03 = "Vão até as janelas para conseguir uma boa visão das coisas!",--Move up to those windows so you get a good view of things!
	pln_spa_24_01 = "Vocês precisam tirar esses carros de polícia do caminho para a van poder chegar em vocês.",--You gotta get those police cars out of the way so the escape van can move in!
	pln_spa_24_03 = "Abram espaço para a van de fuga - tirem esses carros de polícia do caminho!",--Make space for the escape van - get those police cars out of the way!
	pln_spa_25_01 = "Pessoal! Não esqueçam do Charon!",--Guys! Don't forget Charon!
	pln_spa_25_03 = "Lembrem-se do Charon, pessoal! Não o deixem para trás!",--Remember Charon, guys! Don't leave him behind!
	pln_spa_25_05 = "Não deixem o Charon para trás!",--Don't leave Charon behind!
	pln_spa_25_06 = "Certifiquem-se de não deixar o Charon para trás!",--Make sure you don't leave Charon behind!
	pln_spa_25_07 = "Certifiquem-se de que o Charon chegue na van!",--Make sure Charon gets to the van!
	pln_spa_25_08 = "Pessoal, certifiquem-se de que o Charon chegue na van!",--Guys, make sure Charon gets to the van!
	pln_spa_25_09 = "Ajudem o Charon a chegar na van de fuga!",--Help Charon get to the escape van!
	pln_spa_26_01 = "Fiquem de olho - tem mais deles lá em baixo!",--Watch out - there's more of them down there!
	pln_spa_26_02 = "Tem mais mafiosos lá em baixo na rua!",--There are more of the attackers down in the street!
	pln_spa_27_01 = "Vocês vão precisar de um pé de cabra para abrir essas portas do elevador!",--You'll need a crowbar to get those elevator doors open!
	pln_spa_27_02 = "Vocês vão precisar passar por essas portas! Talvez tenha algum pé de cabra ou algo do gênero por aí.",--You'll need to break through those doors! Maybe there's a crowbar around here somewhere?
	pln_spa_27_03 = "Vocês vão precisar passar pelo alçapão do elevador! Vejam se conseguem encontrar um pé de cabra ou alguma coisa!",--You'll need to break into the elevator shaft! See if you can find a crowbar!
	pln_spa_28_02 = "Não se esqueçam de pegar a maleta!",--Don't forget to get the briefcase!
	pln_spa_28_06 = "Vocês vão precisar pegar essa maleta, lembrem-se!",--You need to get that briefcase, remember!
	pln_spa_28_08 = "Lembrem-se de pegar a maleta do Charon!",--Remember to bring Charon's briefcase!
	pln_spa_brf_01 = "Vocês vão para Nova Iorque hoje a noite. O Continental nos chamou - um dos principais agentes dele foi capturado e está sendo mantido preso por um bando de mercenários desconhecidos em um lugar do Brooklyn. Nós conseguimos a localização por meio de uma chamada que o próprio cara fez quando foi sequestrado. O nome dele é Charon. Nós precisamos chegar lá rápido, matar quem quer que tenha o sequestrado e levem-o de volta ao Continental sem que ele se machuque.",--You're going to New York tonight. The Continental called - one of their key staff has been ambushed and is being held by unknown assailants at an address in Brooklyn. We have the location from a call he made just as they took him. The target's name is Charon. We need to get there fast, take out whoever's got him and send him back to the Continental safe and sound.
	pln_spa_cnc_01 = "Vocês estão indo para Nova Iorque em uma missão de resgate do Continental.",--You're going to New York on a rescue mission for the Continental.
	pln_spa_cnc_02 = "O Continental precisa que vocês salvem um cara dele em Nova Iorque. Eles pagam bem.",--The Continental in New York need you to rescue one of their own. They pay well.
	
	-- Legendas (Charon)
	cha_spa_09_03 = "Vamos nos encontrar no outro prédio. Vocês provavelmente conseguem entrar pelo telhado.",--Let's meet in the building next door. You can probably enter from the roof.
	cha_spa_10_02 = "Esses caras não vão desistir. Vamos mostrar para eles como fazemos, bora?",--These people don't give up! Let's show them, shall we?
	cha_spa_08_08 = "Nós os matamos! Obrigado, meus anjos da guarda.",--We got them. Thank you, my guardian angels.
	cha_spa_18_01 = "Eles me acertaram. Mas está tudo bem, só arrancaram um pouco de carne.",--They got me. But it's ok, just a minor flesh wound.
	cha_spa_08_02 = "Obrigado. É ótimo trabalhar com profisionais.",--Thanks, it's good to work with professionals.
	cha_spa_16_03b = "Que situação confusa. Vamos vazar daqui.",--What a messy situation. Let's get out of here.
	cha_spa_16_02b = "Vamos vazar daqui. Primeiro vocês, por favor...",--Let's get out of here. After you, please...
	cha_spa_03_03 = "Os Snipers estão comigo na mira!",--The snipers have me pinned down!
	cha_spa_end_01 = "Obrigado. Eu estou impressionado que vocês vieram tão rápido! Devo uma para vocês.",--Thank you. I'm impressed that you showed up so quickly. I'm in your debt.
	cha_spa_19_05 = "Vocês sabem que eu trabalho para o Continental?",--Do you know I work for the Continental?
	cha_spa_14_03b = "Nós realmente precisamos do veículo de fuga agora! Quanto tempo você acha que vai demorar?",--We really need that escape car now! How long do you think it will be?
	cha_spa_11_02 = "Vocês precisam matar os Snipers. Eu estou encurralado aqui!",--You have to take the snipers out. I'm stuck here!
	cha_spa_06_04 = "Eu agradeceria um pouco de proteção em quanto eu trabalho na porta!",--I'd appreciate some protection while I work on the gate!
	cha_spa_15_01 = "Eu fico tão feliz de ouvir isso!",--I am so glad to hear that!
	cha_spa_04_02 = "Esperem só um minuto. Eu tenho que abrir essa grade.",--Just a minute.  I have to open the gate!
	cha_spa_13_01 = "Eles estão por todo lado da entrada principal. Nós não podemos escapar por lá.",--They are all over the main entrance. We can't get out that way.
	cha_spa_02_03 = "Seria ótimo se vocês pudessem ajudar com esses Snipers? Não seria?",--It'd be very helpful if you could deal with those snipers. Yes?
	cha_spa_07_06 = "Eu preciso de cobertura para abrir essa porta!",--I need covering fire to get the door open!
	cha_spa_14_02 = "E quanto a fuga? O motorista de vocês está vindo?",--How about that escape? Is your driver coming?
	cha_spa_09_01 = "Se vocês cruzarem o telhado para o próximo prédio, eu posso encontrar vocês lá.",--If you move across the roof into the next building, I can meet you there.
	cha_spa_19_01 = "Porque vocês estão demorando tanto?",--What took you so long?
	cha_spa_19_13 = "Eu acho que vocês me subestimaram!",--I think you underestimate me!
	cha_spa_14_03 = "Nós realmente precisamos do veículo de fuga agora! Quanto tempo você acha que vai demorar?",--We really need that escape car now! How long do you think it will be?
	cha_spa_01_03 = "A Gangue PAYDAY! Bem-vindos! Precisamos ensinar a esses caras uma lição, não é?",--The Payday Gang! Welcome! Let's teach these guys a lesson, yes?
	cha_spa_16_02 = "Precisamos vazar daqui. Vocês primeiro, por favor...",--Let's get out of here. After you, please...
	cha_spa_15_01b = "Eu fico tão feliz de ouvir isso!",--I am so glad to hear that!
	cha_spa_19_12 = "É inútil tentar roubar algo do Continental!",--It is foolish to steal from the Continental!
	cha_spa_15_03b = "Eu acho que vamos sair daqui vivos depois de tudo! Mas é claro, eu nunca duvidei!",--I think we will come out of this alive after all! Of course, I never doubted it!
	cha_spa_16_03 = "Que situação confusa hein. Vamos vazar daqui.",--What a messy situation. Let's get out of here.
	cha_spa_11_03 = "Eu não posso matar os Snipers! Vocês poderiam me ajudar, não é?",--I can't take the snipers out! Help me, yes?
	cha_spa_10_01 = "Mais inimigos! Eu agradeceria uma ajuda...",--More enemies! I'd appreciate some help...
	cha_spa_03_05 = "Eu realmente agradeceria uma ajudinha com esses Snipers!",--I would really appreciate some help with those snipers!
	cha_spa_12_01 = "Ok, eu já estou dentro - mas parece que o elevador não está funcionando. Ouçam - Eu preciso de algo importante que eles tiraram de mim. É uma maleta de metal. Vocês conseguem recuperá-la para mim?",--Ok, I'm inside - but it seems the elevator isn't working. Listen - I need to get something important that they took from me. It's in a metal briefcase. Can you get it for me?
	cha_spa_19_03 = "Quando eu descobrir quem fez isso, eles vão pagar!",--When I find out who did this, they will pay!
	cha_spa_08_07 = "Eu confesso que estava um pouco preocupado aqui. Obrigado.",--I confess I was a little worried there. Thank you.
	cha_spa_19_10 = "Vocês não sabem com quem estão lidando!",--You don't know who you're dealing with!
	cha_spa_08_01 = "Obrigado. Isso estava ficando um pouco... desconfortável.",--Thank you. That was getting a little... uncomfortable.
	cha_spa_07_05 = "Eu não consigo abrir essa porta a menos que vocês me cubram!",--I can't get the door open if you don't cover me!
	cha_spa_16_01b = "Eu acho que é hora da gente vazar, não acham?",--I think it's time we leave, don't you?
	cha_spa_19_06 = "Parem com essa loucura e abaixem suas armas!",--Stop this madness and lay down your weapons!
	cha_spa_05_03 = "Me cubram enquanto eu abro essas portas!",--Cover me while I open the door!
	cha_spa_06_05 = "Eu não consigo abrir essa porta a menos que vocês me protejam!",--I can't get the gate open if you don't cover me!
	cha_spa_04_03 = "Me protejam enquanto eu abro essa porta!",--Cover me while I open the gate!
	cha_spa_18_01b = "Eles me acertaram. Mas está tudo bem, só arrancaram um pedacinho de carne.",--They got me. But it's ok, just a minor flesh wound.
	cha_spa_18_02 = "Eu fui acertado. Mas foi só de respão. Estou bem.",--I'm hit. But it just grazed me, I'm fine.
	cha_spa_12_03 = "Ah, o elevador está quebrado! Que inconveniente! Ouçam - Já que eu não posso subir, preciso que vocês procurem por algo importante que eles tiraram de mim. É uma maleta de metal. Eu preciso dela de volta! ",--Ah, the elevator is broken! How inconvenient! Listen - since I can't get up, I need you to search for something important that they took from me. It's a metal briefcase. I must have it back!
	cha_spa_03_01 = "Vocês podem matar os Snipers?",--Can you take the snipers out?!
	cha_spa_05_01 = "Eu preciso abrir essa porta. Me deem um minuto!",--I need to open this door. Give me a minute!
	cha_spa_14_01 = "O veículo de fuga está vindo? Isso aqui tá ficando quente!",--Is the pickup coming? This is getting pretty hot!
	cha_spa_06_03 = "Vocês precisam me protejer enquanto eu abro essa porta!",--You need to cover me while open the gate!
	cha_spa_06_02 = "Eu não posso abrir a porta enquanto eles estiverem atirando em mim!",--I can't open the gate while they are firing at me!
	cha_spa_07_04 = "Eu agradeceria um pouco de proteção enquanto trabalho na porta!",--I'd appreciate some protection while I work on the door!
	cha_spa_06_08 = "Me cubram para eu poder abrir a porta!",--Cover me so I can get the gate open!
	cha_spa_19_08 = "Vocês realmente pensaram que poderiam me capturar?",--Did you really think you could capture me?
	cha_spa_02_02 = "Eu estou me cagando aqui com esses Snipers. Vocês podem fazer alguma coisa?",--I'm a sitting duck here with those snipers. Can you do something?
	cha_spa_18_03b = "Eles me acertaram, mas foi só de raspão. Nem machucou.",--They shot me, but it's only a minor one. Barely hurts.
	cha_spa_06_06 = "Eu preciso de cobertura para poder abrir essa porta!",--I need covering fire to get the gate open!
	cha_spa_end_03 = "Obrigado, meus amigos. Eu nunca vou esquecer desse dia.",--Thank you, my friends. I will not forget this day.
	cha_spa_07_03 = "Vocês precisam me cobrir enquanto eu abro essa porta!",--You need to cover me while open the door !
	cha_spa_19_02 = "Vamos!",--Let's go!
	cha_spa_07_08 = "Me cubram para eu poder abrir essa porta!",--Cover me so I can get the door open!
	cha_spa_13_03b = "Nós não podemos sair pela entrada principal. Muito quente lá.",--We cannot use the main entrance. Too much heat.
	cha_spa_15_02b = "Ótimo! Mas vai ser um minuto bem longo!",--Good! But it will be a long minute!
	cha_spa_07_07 = "Continuem atirando e eu conseguirei abrir a porta!",--Keep firing and I can get the door open!
	cha_spa_18_02b = "Eu fui acertado. Mas foi só de raspão, estou bem.",--I'm hit. But it just grazed me, I'm fine.
	cha_spa_04_01 = "Eu preciso abrir essa porta. Me deem um minuto!",--I need to open this gate. Give me a minute!
	cha_spa_12_02 = "O elevador não está funcionando, eu não consigo subir! Ouçam - eu preciso que vocês peguem uma coisa para mim aí em cima - é uma maleta de metal que eles tiraram de mim. É muito importante!",--The elevator isn't working, I can't get up! Listen - I need you to find something for me up there -  it's a metal briefcase that they took from me. It's very important!
	cha_spa_08_04 = "Quem quer que eles sejam, fizeram uma escolha horrível em tentar me sequestrar.",--Whoever they are, it seems they chose poorly in ambushing me.
	cha_spa_07_02 = "Eu não consigo abrir a porta enqunato eles estiverem atirando em mim!",--I can't open the door while they are firing at me!
	cha_spa_03_06 = "Eu preciso de vocês para matar esses Snipers!",--I need you to take those snipers out!
	cha_spa_03_08 = "Cuidem desses Snipers, por favor!",--Take care of the snipers, please!
	cha_spa_07_01 = "Eles estão comigo na mira - Não consigo abrir a porta assim!",--They have me pinned down - I can't get the door open!
	cha_spa_01_01 = "Estou feliz que vocês apareceram! Como vocês podem ver, preciso de uma ajuda aqui.",--I'm glad you showed up! As you can see, I need some help here.
	cha_spa_18_03 = "Eles me acertaram. Mas foi só de raspão. Nem machucou.",--They shot me, but it's only a minor one. Barely hurts.
	cha_spa_19_11 = "A Gangue PAYDAY está aqui para me ajudar! Vocês deviam correr!",--The Payday Gang is here to help me! You should run!
	cha_spa_16_01 = "Eu acho que é hora de vazarmos, não acham?",--I think it's time we leave, don't you?
	cha_spa_19_04 = "O Winston não vai ficar feliz!",--Winston won't be happy!
	cha_spa_03_04 = "Esses Snipers vão acabar me acertando se vocês não os matarem!",--Those snipers will get me soon if you don't take them out!
	cha_spa_13_02b = "Eu temo que ea entrada principal não seja uma opção. Eles estão em todo lugar lá.",--I fear the main entrance is not an option. They are all over it.
	cha_spa_08_03 = "Obrigado, é bom ter poder de fogo atrás de mim.",--Thanks, it's good to have some firepower behind me.
	cha_spa_01_02 = "Ah! Então o Winston chamou vocês. Vocês podem me ajudar aqui?",--Ah! So Winston called you. Can you help me out here?
	cha_spa_08_06 = "Obrigado. Eu vou sair daqui ainda.",--Thank you. I'll get out of this yet.
	cha_spa_14_02b = "E quanto a fuga? O motorista de vocês está vindo?",--How about that escape? Is your driver coming?
	cha_spa_14_01b = "A fuga está a caminho? Isso aqui está ficando bem quente.",--Is the pickup coming? This is getting pretty hot!
	cha_spa_end_02 = "Isso foi incrível. Vocês provavelmente salvaram minha vida. Devo uma para vocês.",--That was very impressive. And you probably saved my life. I owe you one for this. 
	cha_spa_19_07 = "Foi uma péssima ideia tentar me sequestrar!",--It was a bad move to ambush me!
	cha_spa_08_05 = "Eu acho que eles estão todos mortos. Obrigado, meus amigos.",--I think they are all dead. Thanks to you, my friends.
	cha_spa_15_03 = "Eu acho que nós vamos sair daqui vivos depois de tudo isso! Mas é claro, eu nunca duvidei!",--I think we will come out of this alive after all! Of course, I never doubted it!
	cha_spa_05_02 = "Só um minuto. Eu tenho que abrir essa porta!",--Just a minute.  I have to open the door!
	cha_spa_06_07 = "Continuem atirando para eu poder abrir a porta!",--Keep firing and I can get the gate open!
	cha_spa_09_02 = "Eu vou até o prédio ao lado. Entrem nele pelo telhado e vocês podem me encontrar lá.",--I will move to the building next door. Enter across the roof and you can meet me there.
	cha_spa_11_01 = "Os Snipers estão comigo na mira. Eu não posso me mover enquanto vocês não os matarem!",--The snipers have me pinned down. I can't move until you clear them out!
	cha_spa_10_03 = "Tem mais deles aí! Se vocês não se importarem, podem dar uma ajudinha?",--There's more of them! If you don't mind - some help please?
	cha_spa_03_02 = "Eu não posso me mover enquanto vocês não derem um jeito nesses Snipers!",--I can't move until you deal with the snipers!
	cha_spa_15_02 = "Ótimo! Mas vai ser um minuto bem longo.",--Good! But it will be a long minute!
	cha_spa_03_07 = "Eu não consigo nenhum ângulo bom nesses Snipers. Vocês precisam matá-los!",--I can't get a good angle on those snipers! You need to take them out!
	cha_spa_02_01 = "Esses Snipers estão comigo na mira. Vocês conseguem matá-los?",--Those snipers have me pinned down. Can you take them out?
	cha_spa_13_01b = "Eles estão cercando toda a entrada principal. Não tem como escaparmos por lá.",--They are all over the main entrance. We can't get out that way.
	cha_spa_19_09 = "Movimento estúpido, bem estúpido.",--Unwise move, very unwise!
	
	-- Objetivos
	hud_heist_spa_20 = "Faça com que o Charon chegue na van de fuga.",--Make sure Charon makes it to the escape van.
	hud_heist_spa_12 = "Mexa-se para a área anterior e espere por instruções do Bain.",--Make it back to the previous courtyard and wait for Bain's instructions
	hud_heist_spa_08 = "Mate os snipers para o Charon poder ir até você.",--Take down the snipers so that Charon can move to your location.
	hud_heist_spa_22 = "Espere pela van de fuga chegar.",--Wait until the van arrives
	hud_heist_spa_07 = "Há mais mafiosos nessa área, mate-os.",--More gangsters in this area clear them out.
	hud_heist_spa_20_hl = "Escolte o Charon para a Van de Fuga",--Escort Charon to the Escape Van
	hud_heist_spa_03_hl = "Elimine o Sniper",--Eliminate the Sniper
	hud_heist_spa_21_hl = "Localize o VIP",--Locate the VIP
	hud_heist_spa_02 = "Parece que o Charon está com problemas, procure por qualquer atividade suspeita.",--Looks like Charon is in trouble look for suspicious activity.
	hud_heist_spa_11 = "Procure e encontre a maleta que o Charon mencionou.",--Find and grab the briefcase Charon mentioned.
	hud_heist_spa_06 = "Cruze o telhado e acesse o outro prédio.",--Move through the roof and access the new building.
	hud_heist_spa_10_hl = "Abra a Grade",--Open the gate
	hud_heist_spa_17_hl = "Mova os Carros de Polícia",--Move the police cars
	hud_heist_spa_05 = "Cubra o Charon enquanto ele destranca a porta.",--Cover Charon while he lockpicks the gate.
	hud_heist_spa_19_hl = "Espere pelo VIP no Elevador",--Wait by the elevator for the VIP
	hud_heist_spa_02_hl = "Dê uma olhada no Pátio",--Overlook the courtyard
	hud_heist_spa_13 = "O Charon está com problemas. Dê um jeito de descer até o porão e encontre com ele.",--Charon is in trouble. Find a way down to the basement and meet up with him.
	hud_heist_spa_08_hl = "Mate os Snipers",--Take down the snipers
	hud_heist_spa_07_hl = "Mate os Mafiosos que sobraram",--Clear out the remaining gangsters
	hud_heist_spa_13_hl = "Encontre-se com o Charon",--Rendezvous with Charon
	hud_heist_spa_05_hl = "Cubra o Charon",--Cover Charon
	hud_heist_spa_09 = "Espere enquanto o Charon encontra alguma maneira de subir pelo prédio.",--Wait until Charon finds a way up the building.
	hud_heist_spa_22_hl = "Espere pela Van",--Wait for the Van
	hud_heist_spa_04 = "Ajude o Charon a matar todos os mafiosos no pátio.",--Help Charon kill all the gangsters on the courtyard.
	hud_heist_spa_11_hl = "Pegue a Maleta",--Get the briefcase
	hud_heist_spa_04_hl = "Limpe o Pátio",--Clear out the courtyard
	hud_heist_spa_01 = "O Charon deve estar no pátio - Procure por um bom ponto de vantagem.",--Charon should be on the courtyard - look for a good vantage point.
	hud_heist_spa_16_hl = "Espere pelo Veículo de Fuga",--Wait for the Escape
	hud_heist_spa_03 = "Eles colocaram um sniper em um dos apartamentos do pátio.",--They got a sniper in one of the apartments over the courtyard.
	hud_heist_spa_10 = "Coloque uma furadeira e abra a porta.",--Place down a drill and get that gate open.
	hud_heist_spa_14_hl = "Escolte o Charon até o Local da Fuga",--Escort Charon to the Escape location
	hud_heist_spa_23_hl = "Fuja",--Escape
	hud_heist_spa_12_hl = "Vá para o Local de Fuga",--Move to the escape location
	hud_heist_spa_09_hl = "Espere pelo Charon",--Wait for Charon
	hud_heist_spa_01_hl = "Localize o Charon",--Locate Charon
	hud_heist_spa_06_hl = "Acesse o Outro Prédio",--Access the other building
	hud_heist_spa_14 = "O Charon está ferido. Ajude-o a chegar no local da fuga.",--Charon is hurt. Help him back to the Escape zone.
	hud_heist_spa_15 = "Espere enquanto o Bain encontra uma rota de fuga.",--Wait until Bain find a way out of there.
	hud_heist_spa_15_hl = "Espere por Instruções do Bain",--Wait for Bain's instructions
	hud_heist_spa_16 = "Espere pelo veículo de fuga chegar.",--Wait for the escape vehicle to arrive.
	hud_heist_spa_17 = "A van de fuga não pode se aproximar em quanto você não tirar os carros da polícia do caminho.",--The escape van can't arrive until you move the police cars out of the way.
	hud_heist_spa_18_hl = "Cubra o Charon",--Cover Charon
	hud_heist_spa_23 = "Vá até o veículo de fuga marcado e vaze daí.",--Go to the marked escape vehicle and get out of there.
		})
end)