return {
	-- Nomes e Descrições
	--heist_mad = "Boiling Point",--Boiling Point
	--heist_mad_hl = "Boiling Point",--Boiling Point
	heist_mad_crimenet = "Essa organização ilegal russa está conduzindo vários experimentos perturbadores em um laboratório escondido na Rússia. Você não vai acreditar nas merdas que eles estão fazendo lá dentro. Nós precisamos impedir esse merda do Akan de colocar as mãos nessas informações, certo? É fazer ou morrer, senhoras e senhores.$NL;$NL;» Entre na Fortaleza$NL;» Obtenha acesso ao Laboratório$NL;» Obtenha as Informações$NL;» Fuja",--This dirty Russian organization is conducting some very disturbing experiments from a hidden laboratory in Russia. You won't believe what shit they're doing over there. We need to fuckin' stop Akan from getting his hands on the data, yeah? It's do or die, boys and girls.$NL;$NL;» Enter the compound$NL;» Gain access to the lab$NL;» Obtain the data$NL;» Escape
	heist_mad_briefing = "De qualquer hora pra ter uma consciência, você decide agora? Não posso dizer que gosto disso, mas também não posso dizer que você esteja cometendo um erro. Baseado no que esse tal de Jimmy está nos falando, Akan realmente precisa ser impedido. Seu destino é uma madeireira no meio do nada, que secretamente é um laboratório de uma estranha organização Russa. Jimmy me disse que estão fazendo experimentos que envolvem coisas fora dessa realidade. Invada o laboratório e obtenha a informação que o Akan está atrás. Boa sorte, pessoal.",--Of all the times to grow a conscience, you decide now is the time? I can't say I like it, but I can't say you are making a mistake either. Based on what this Jimmy character is telling us, Akan really needs to be stopped. Your destination is a lumber mill in the middle of nowhere, that is secretly a laboratory run by a strange Russian organization. Jimmy tells me they are conducting some experiments that involve things out of this reality. Break into the lab and get the data Akan is after. Good luck, gang.
	pln_mad_brf_01_01 = "De qualquer hora pra ter uma consciência, você decide agora? Não posso dizer que gosto disso, mas também não posso dizer que você esteja cometendo um erro. Baseado no que esse tal de Jimmy está nos falando, Akan realmente precisa ser impedido. Seu destino é uma madeireira no meio do nada, que secretamente é um laboratório de uma estranha organização Russa. Jimmy me disse que estão fazendo experimentos que envolvem coisas fora dessa realidade. Invada o laboratório e obtenha a informação que o Akan está atrás. Boa sorte, pessoal.",--Of all the times to grow a conscience, you decide now is the time? I can't say I like it, but I can't say you are making a mistake either. Based on what this Jimmy character is telling us, Akan really needs to be stopped. Your destination is a lumber mill in the middle of nowhere, that is secretly a laboratory run by a strange Russian organization. Jimmy tells me they are conducting some experiments that involve things out of this reality. Break into the lab and get the data Akan is after. Good luck, gang.

	-- Legendas
	pln_mad_intro_01_01 = "Droga! Eles possuem defesas anti-aéreas posicionadas em toda a fábrica. Mude o avião de direção, Bile! Galera, vocês precisam usar os paraquedas e vazar! Agora!",--Damn! They have anti-air defenses set up around the whole factory. Turn the plane around, Bile! Gang, you need to use the parachutes and get out! Right now!
	pln_mad_intro_01_02 = "Merda! Esses desgraçados tem defesas anti-aéreas posicionadas! Bile, mude a direção do avião imediatamente! Galera, usem os paraquedas e deem o fora! Nós pensaremos em algo!",--Shit! These bastards have anti-air defenses set up! Bile, turn the plane around immediately! Guys, use the parachutes and get out! We'll figure something out!
	pln_mad_intro_01_03 = "Defesa anti-aérea?! Tá de brincadeira comigo?! Vire o avião, Bile! Agora! Galera, peguem os paraquedas e pulem fora!",--Anti-air defenses?! Are you shitting me?! Turn the plane around, Bile! Do it now! Guys, take the parachutes and jump out!
	pln_mad_40_03 = "Droga, eles cortaram a energia do escaneador!",--Damn, they got the power for the scanner!
	pln_mad_35_03 = "É isso. Agora podemos começar a escaneador.",--That's it. Now we can start the scanning.
	pln_mad_54_03 = "Conseguiu os explosivos? Ótimo. Vão para o radar e plante-os para que possamos explodí-los.",--You got the explosives? Great. Get over to the radar and plant them so we can blow it up.
	pln_mad_37_01 = "Eles pararam o escaneador! Liguem-o de novo!",--They stopped the scan! Start it again!
	pln_mad_21_03 = "O EMP tá quase pronto, então atenção! Esse bebê é poderoso então não fiquem surpresos se quebrar nossa comunicação entre outras coisas.",--The EMP is almost done, so listen up! This baby is powerful so don't be surprised if it breaks our communication among other things.
	pln_mad_46_03 = "É isso! Quase esqueci: tem uma maleta no laboratório. Vou precisar que vocês peguem, galera. É importante.",--That's right! I almost forgot: there is a briefcase in the laboratory. I'm gonna need you to get it, guys. It's important.
	pln_mad_28_01 = "Galera, vocês precisam achar o líder cientista.",--Gang, you need to find the lead scientist.
	pln_mad_51_03 = "Terminamos, galera. Hora de ir.",--We are done, gang. Time to go.
	pln_mad_12_02 = "Mas que droga, Bile... a EMP caiu pelo telhado e agora está dentro da madeireira em vez de fora.",--God dammit, Bile... The EMP fell through the roof and is now inside the lumber mill instead of outside.
	pln_mad_60_01 = "Ali está a arma AA. Explodir isso significaria nos explodir. Precisamos hackeá-la, me dê acesso àquele laptop.",--There's the AA gun. Blowing this up would mean blowing ourselves up. We need to hack it, get me access to that laptop.
	pln_mad_21_01 = "Galera, atenção! Quando a EMP explodir eu provavelmente não conseguirei me comunicar com vocês por um tempo. Vocês vão precisar entrar no laboratório pela escotilha.",--Guys, listen! When the EMP goes off I most likely won't be able to communicate with you for a while. You need to get down to the hidden laboratory via the hatch.
	pln_mad_47_03 = "É isso? A maleta? Perfeito! Agora podemos dar o fora daqui!",--That's it? The briefcase? Perfect! Now we can get outta here!
	pln_mad_34_02 = "Okay, essa deve ser uma das cobaias. Levem o corpo para o escaneador para que possamos pegar a informação que precisamos.",--Okay, that must be one of the test subjects. Get the body to the scanner so we can get the information we need.
	pln_mad_31_02 = "Parece que funcionou. Vocês podem iniciar o processo de escaneamento agora.",--It seems to have worked. You should be able to start the scanning-process now.
	pln_mad_58_03 = "Coloquem os mísseis no radar e ative-os. Isso deve servir.",--Place the missiles by the radar and activate them. That should do the trick.
	pln_mad_16_01 = "Okay, galera. Precisamos carregar essa belezinha antes de usar. Vai demorar um pouco.",--Okay, gang. We need to charge this baby up before it can be used. Gonna take a little while.
	pln_mad_01_03 = "Caraca... essa foi por pouco! Esses russos realmente não querem ninguém acabando com a festa deles.",--Holy... that was close! These Russians really don't want anyone to crash their party. 
	pln_mad_36_02 = "Não deixem os mercenários pararem com o processo de escaneamento!",--Don't let the mercenaries stop the scanning process!
	pln_mad_50_02 = "Bom trabalho, galera. O servidor está seguro e o Jimmy ficará bem feliz.",--Good job, gang. The server has been secured and Jimmy will be happy.
	pln_mad_01_02 = "Isso é a Rússia, galera! Esses caras não brincam em serviço!",--That's Russia for you, gang! These guys do not mess around!
	pln_mad_28_02 = "Ei, se não achar o cientista chefe, vocês não vão passar por aquela porta.",--Hey, if you don't find the lead scientist, you're not getting through that door.
	pln_mad_05_01 = "Okay, já podem ir. Comecem a hackear.",--Okay, you're good to go. Start the hack.
	pln_mad_44_01 = "Foram todos! Nenhum corpo mais para escanear. Agora precisamos pegar o servidor ou teremos feito tudo isso a toa.",--That's all of them! No more bodies to scan. Now we need to get the server or we did it all for nothin'.
	pln_mad_50_03 = "Ótimo, o servidor está assegurado. Agora o Jimmy já pode calar a boca. Fizemos nossa parte.",--Great, the server has been secured. Now Jimmy can shut up about it. We did our part. 
	pln_mad_18_03 = "Droga, os mercenários chegaram na EMP e interromperam o carregamento.",--Damn, the mercenaries got to the EMP and stopped the charging.
	pln_mad_19_02 = "Merda, os mercenários interromperam o carregamento da EMP! Está começando a descarregar!",--Shit, the mercenaries stopped the EMP charge! It's beginning to discharge!
	pln_mad_03_03 = "Se vocês acharem um laptop na estação de computadores, eu poderia usá-lo para ajudar vocês.",--If you find a laptop at the computer station, I could use it to help you.
	pln_mad_04_02 = "Preparem o laptop na arma anti-aérea. Talvez eu possa fazer minha magia.",--Set up the laptop to the anti-aircraft gun. Maybe I can work my magic.
	pln_mad_12_03 = "Sério, Bile? Galera, a EMP caiu dentro da madeireira em vez de fora. Vamos precisar entrar lá.",--Really, Bile? Gang, the EMP ended up inside the lumber mill instead of outside.Need to get in there now.
	pln_mad_55_01 = "Galera, vocês ainda precisam explodir aquele radar.",--Gang, you still need to blow up that radar.
	pln_mad_02_01 = "Enquanto essas defesas anti-aéreas estiverem em funcionamento, o Fedor não vai conseguir trazer a EMP. Encontrem uma forma de desativá-las, galera.",--As long as those anti-air defenses are functional, Fedor won't be able to drop the EMP. Find a way to disable them, gang.
	pln_mad_21_01a = "A EMP já deve ter soltado a trava magnética. Quando vocês entrarem, achem o escaneador e as cobaias.",--The EMP should have released the magnetic lock. Once you're down there, find the scanner and the test-subjects.
	pln_mad_22_02 = "A EMP tomou conta da trava magnética, vocês já podem entrar no laboratório. Vamos!",--The EMP took care of the magnetic lock, so you have free passage to the laboratory.Let's go!
	pln_mad_53_01 = "Bile deixou uns explosivos para vocês. Eles devem estar onde vocês pousaram, vão buscar.",--Bile managed to drop some explosives for you. They should be near where you landed, so grab 'em.
	pln_mad_38_02 = "Certo, o escaneador está em andamento novamente.",--Good, the scan is under way again.
	pln_mad_54_02 = "Ótimo, você achou os explosivos. Vão para o radar e exploda-o.",--Good, you found the explosives. Head over to the radar and blow it up.
	pln_mad_62_01 = "O Elefante me disse especificamente para não esquecer da maleta! Ache-a!",--The elephant specifically told me not to forget the briefcase! Find it!
	pln_mad_08_03 = "Esses mercenários devem ter alguma C4 ou algo do tipo por aqui para usarmos.",--These mercenaries must have some C4 or something around here that we could use.
	pln_mad_34_01 = "Essa deve ser uma das cobaias que o Jimmy falou sobre. Levem o corpo para o escaneador para que possamos obter a informação necessária.",--That must be one of the test subjects that Jimmy talked about. Get the body to the scanner so we can get the information we need.
	pln_mad_30_03 = "Você cortou a mão dele? Que bizarro, mas um trabalho é um trabalho. Coloque-a no escaneador e abram a porta.",--You cut off his hand? That's some dark stuff, but a job is a job. Place it on the scanner and get the door opened.
	pln_mad_04_03 = "Traga o laptop para a arma anti-aérea. Vejam se vocês conseguem ligá-lo.",--Bring the laptop to the AA gun. See if you can hook it up.
	pln_mad_51_02 = "O que vocês estão esperando? Vamos embora.",--What are you waiting for? Let's leave.
	pln_mad_07_03 = "Okay, desabilitei essa, mas ainda falta mais uma!",--Okay, I got this one disabled, but there's still one more to go!
	pln_mad_14_02 = "Precisaremos achar uma entrada para a madeireira. Talvez usar a arma anti-aérea para abrir um buraco na parede?",--We are going to need to find a way inside the lumber mill. Maybe we can blow a hole through the wall using the AA gun we hacked?
	pln_mad_47_02 = "Conseguiu a maleta? Excelente! Hora de ir, então!",--You got the briefcase? Excellent! Time to go then!
	pln_mad_63_02 = "Que tipo de animal faria algo desse tipo? E agora teremos que decepar a mão dele...",--What kind of animal would do a thing like this? And now we need to chop off his hand... 
	pln_mad_15_03 = "Usar os brinquedos deles contra eles - adoro isso. Agora entrem na madeireira.",--Use their own toys against them - I love it. Now get inside the lumber mill.
	pln_mad_13_02 = "Okay, galera. O Bile deixou a EMP cair próximo da madeireira. Vão pegar!",--Okay, guys. Bile dropped the EMP just outside the lumber mill.Go get it!
	pln_mad_48_01 = "Que? Vocês leem mentes? Sim, eu quero essa maleta. Como vocês sabiam?",--What, are you mind readers? Yes, I do want that briefcase. How did you know?
	pln_mad_25_02 = "Galera, procurem por um jeito de desligar o gás!",--Guys, look for a way to shut off the gas!
	pln_mad_47_01 = "Vocês conseguiram? A maleta? Ótimo! Agora deem o fora daí.",--You got it? The briefcase? Good! Now let's get out of there.
	pln_mad_06_03 = "O hackeamento foi interrompido. Reinicie-o!",--The hacking has been stopped. Get it up and running again!
	pln_mad_45_03 = "Excelente, o servidor está assegurado. Agora, vamos dar o fora daqui.",--Excellent, the server is secured. Now, let's get out of here.
	pln_mad_36_01 = "Okay, escaneamento em andamento. Agora tenham certeza de que ninguém interrompa o processo.",--Okay, scanning is under way. Now make sure it gets to finish without getting interrupted.
	pln_mad_23_01 = "Cara, parece que a EMP desligou a fábrica inteira... Usem suas lanternas e achem o dispositivo de raio-X.",--Man, the EMP took out the whole factory it seems... Use your flashlights and find the X-ray device.
	pln_mad_03_02 = "Aquela rede de computadores deve ter um laptop sobrando. Vejam se vocês conseguem encontrar um.",--That computer station should have a laptop laying around. See if you can find one.
	pln_mad_20_03 = "A EMP está recarregando de novo.",--The EMP is charging again.
	pln_mad_08_01 = "Cara, esses mercenários se prepararam para uma guerra. Deve ter alguns explosivos por aí que possamos usar.",--Man, these mercenaries have set up for war. There should be some explosives laying around that we could use.
	pln_mad_11_03 = "Boom! Bom trabalho, galera.",--Boom! Great job, gang.
	pln_mad_39_01 = "É isso! O escaneamento foi completo. Bom trabalho, pessoal.",--That's it! Scan has been completed.Good job, guys.
	pln_mad_03_01 = "Galera, a rede de computadores ali pode ser útil. Vejam se vocês conseguem achar um laptop ou algo do tipo.",--Gang, the computer station there could be useful. See if you can find me a laptop or something.
	pln_mad_46_02 = "Droga! Eu esqueci da maleta. Galera, atenção. Tem uma maleta em algum lugar do laboratório.",--Damn! I forgot about the briefcase. Gang, listen up. There is a briefcase somewhere in the laboratory.
	pln_mad_54_01 = "Excelente, vocês pegaram os explosivos. Agora, plante-os no radar.",--Excellent, you got the explosives. Now, plant them on the radar.
	pln_mad_61_03 = "A EMP vai nos providenciar uma entrada mas sua função primária é cuidar das cobaias. Se as histórias são verdadeiras, não vamos querer mexer com esses caras.",--The emp will give us a way in but it's primary function is to take care of the test subjects for us. If the stories are true, we don't want to take these guys on.
	pln_mad_50_01 = "Excelente, galera. É bom saber que fizemos uma boa ação. Mas não fiquem animados, da próxima vez, roubaremos um banco ou algo do tipo.",--Excellent, guys. It actually feels nice knowing we did something good. But don't get any ideas, we're robbing a bank or something next. 
	pln_mad_16_02 = "Galera, a EMP precisa ser carregada antes de podermos usar. Vai levar um tempo.",--Gang, the EMP needs to charge up before we can use it. It will take some time.
	pln_mad_52_02 = "Esse radar está controlando a arma anti-aérea. Precisamos explodi-lo.",--That radar is controlling the anti-air gun. Need to blow it up. 
	pln_mad_37_02 = "Droga, eles interromperam o escaneamento! Reinicie-o!",--Damn, they interrupted the scan! Restart it!
	pln_mad_17_01 = "Os mercenários vão avançar pra cima de vocês! Proteja a EMP, galera!",--The mercenaries are gonna come at you hard! Protect the EMP, gang!
	pln_mad_19_03 = "Pessoal! Cada vez que os mercenários mexerem com a EMP, o processo de recarga diminui! Não deixem eles tocarem nela!",--Guys! Every time the mercenaries mess with the EMP, the charging process decreases! Don't let them touch it!
	pln_mad_59_03 = "Excelente, galera. Com as defesas anti-aéreas desligadas, o Bile vai poder enviar a EMP próximo da madeireira.",--Excellent, gang. With the anti-air defenses gone, Bile can now drop the EMP close to the lumber mill.
	pln_mad_43_01 = "Boa escolha, galera. O que mais importa é o dia do pagamento quando ele chegar. Vocês conhecem o procedimento, continuem escaneando mais corpos para mais informações.",--Good choice, gang. It's all about the payday when it comes down to it. You know the drill, keep scanning them bodies for more data.
	pln_mad_12_01 = "Droga, a EMP caiu e quebrou o telhado da madeireira.",--Damn, the EMP crashed right through the roof of the lumber mill.
	pln_mad_49_01 = "Galera, o Fedor está esperando perto do lago. É hora de ir embora.",--Guys, Fedor is waiting over at the lake. It's time to leave.
	pln_mad_16_03 = "Okay, precisamos carregar a EMP antes de usá-la. Paciência é uma virtude.",--Okay, we need to charge the EMP before can we use it.Patience is a virtue.
	pln_mad_27_03 = "Oh, eu não sabia que estávamos em um filme de ficção científica. Bom, okay então. Vocês terão que localizar o cientista chefe para conseguir a autorização por impressão digital. Procurem o lugar onde ele está se escondendo.",--Oh, I didn't know we were in a Sci-Fi movie. Well, okay then. You're gonna need to find the lead scientist for some kind of hand print authorization.See where he's hiding.
	pln_mad_58_01 = "Posicionem os mísseis perto do radar e acione-os. Facinho.",--Place the missiles next to the radar and activate them. Easy peasy. 
	pln_mad_44_03 = "O Jimmy vai amar se conseguirmos toda a informação possível, estaríamos ferrando com o Akan.",--Jimmy will love it if we get all the data we can, really sticking it to Akan.
	pln_mad_36_03 = "Protejam o dispositivo de raio-X! Não deixem os mercenários chegarem nele!",--Protect the X-ray device! Don't let the mercenaries get to it!
	pln_mad_23_02 = "Vamos precisar de um dispositivo de raio-X para conseguir a informação que o Elefante precisa.",--We're going to need an X-ray device to get the data the Elephant needs.
	pln_mad_05_02 = "Perfeito, deixa comigo. Começando a hackear.",--Perfect, I can do this. Beginning hacking.
	pln_mad_63_03 = "Que conveniente, agora ele não vai escapar. Corte a mão dele e traga-a ao escaneador.",--How convenient, he won't run away now. Cut off his hand and bring it to the scanner.
	pln_mad_53_03 = "Pessoal, procurem pelo lugar que vocês pousaram. O Bile deixou alguns explosivos para vocês.",--Guys, search the spot where you landed. Bile has dropped some explosives for you.
	pln_mad_61_02 = "A EMP não vai só nos dar uma entrada, mas também nocautear as cobaias. Acredite em mim, você não vai querer mexer com elas.",--The EMP will not only give us a way in, but also knock out the test subjects. Trust me you don't want to deal with these guys.
	pln_mad_46_01 = "Espere! Eu esqueci da maleta... Deve ter uma maleta em algum lugar do laboratório. Vocês precisam pegar antes de sair. Não se importem com o conteúdo dela, apenas pegue-a.",--Wait! I forgot about the briefcase... There should be a briefcase somewhere in the laboratory. You need to get it before you leave. Don't mind what's in it, just do it.
	pln_mad_21_02 = "Galera, a EMP provavelmente vai desligar nossos meios de comunicação. Mas vocês já sabem o que fazer, entrem no laboratório pela escotilha e procurem pelas cobaias.",--Guys, the EMP will most likely take out our communication when it goes off. But you know what to do, enter the laboratory via the hatch and look for the test subjects.
	pln_mad_09_01 = "Vocês sabem o que fazer. Preparem os explosivos e deixem eles tomar conta do recado.",--You know what to do. Set the C4 up and let it take care of the rest.
	pln_mad_41_03 = "Energia religada! Voltem para o processo de escaneamento.",--Power is back! Get back to scanning the test-subjects.
	pln_mad_59_01 = "Bom trabalho, galera. O Bile está a caminho com a EMP e vai deixar perto da madeireira.",--Great job, gang. Bile is on his way with the EMP now and will drop it close to the lumber mill.
	pln_mad_11_01 = "É isso, galera!",--That's it, gang!
	pln_mad_29_03 = "O cientista chefe está morto? Merda. Sem ele não podemos passar pela segurança... Bom, acho que tecnicamente não precisamos dele, mas sim da mão dele...",--The lead scientist is dead? Shit. Without him we aren't getting past security... Well, I guess technically we don't need HIM, but rather HIS hand...
	pln_mad_06_02 = "Droga, eles interromperam o hackeamento. Reinicie-o!",--Damn, they interrupted the hacking.Get it started again!
	pln_mad_14_03 = "Precisamos entrar na madeireira. Por que não usar a arma anti-aérea que hackeamos antes e redirecionar sua posição? Não custa nada tentar.",--We need to get inside the lumber mill. Why not see if you could use the anti-air gun we hacked earlier and redirect its position? Might be worth a shot.
	pln_mad_20_01 = "Ok, boa. O carregamento foi reiniciado.",--Ok, good. The charging has been restarted.
	pln_mad_62_02 = "Não podemos sair sem aquela maleta!",--We can not leave without that briefcase! 
	pln_mad_43_02 = "Essa é a escolha certa, pessoal. Continuem escaneando. Não percorremos todo esse caminho até a Rússia por um pagamento pequeno, certo?",--That's the right choice, guys. Keep scanning away. We didn't come all the way to Russia for a small payout, now did we?
	pln_mad_07_01 = "A arma anti-aérea foi desabilitada! Agora, peguem o laptop e vão para a próxima!",--The AA gun has been disabled! Now, grab the laptop and head over to the next one!
	pln_mad_27_01 = "Okay, os cientistas trabalhando aqui estão usando uma parada de outro nível. Vocês vão precisar do cientista chefe para autorização de impressão digital. Procure-o.",--Okay, the scientists working here are using some next level shit. You're gonna need the lead scientist for handprint authorization. See where he's hiding.
	pln_mad_49_03 = "Temos o que precisamos. Agora, vão para o lago. O Fedor está esperando por vocês.",--We got everything we came for. Now, head for the lake. Fedor is waiting for you.
	pln_mad_44_02 = "Excelente, galera. Todos os corpos escaneados. Agora precisamos do servidor em que as informações estão.",--Excellent, gang. That's all the bodies scanned. Now we need to get our hands on that server storing the data.
	pln_mad_06_01 = "Eles interromperam o hackeamento! Reinicie-o!",--They interrupted the hack! Restart it!
	pln_mad_45_01 = "Ótimo trabalho, pessoal! O servidor vale muito dinheiro agora. Não o derrubem.",--Great job, guys! That server is worth a lot of cash right now. Don't drop it.
	pln_mad_62_03 = "Galera o que tá rolando? Não podemos ir embora sem a maleta.",--Gang what's going on? We are not leaving without the briefcase.
	pln_mad_32_02 = "Boa, parece que a energia voltou.",--Nice, seems the power is back. 
	pln_mad_57_03 = "É isso aí. Esses mísseis são perfeitos. Levem-os para o radar.",--Hell yeah. Those missiles are perfect. Take them to the radar. 
	pln_mad_01_01 = "Bem vindos à Rússia, galera! Uma ótima festa de boas vindas, né?",--Welcome to Russia, gang! Nice welcoming party, right? 
	pln_mad_18_02 = "O carregamento foi interrompido! Reinicie-o!",--The charging has been interrupted! Get it started again!
	pln_mad_46_02a = "Eu preciso que vocês encontrem e tragam com vocês. Eu não pediria se não fosse importante.",--I need you to find and it and bring it with you. I wouldn't ask if it wasn't important.
	pln_mad_35_01 = "Okay, estamos preparados para começar o processo de escaneamento.",--Okay, we're all set to begin the scanning.
	pln_mad_60_03 = "Mesmo se explodirmos o radar, eles ainda podem controlar isso pelo laptop. Precisamos hackeá-lo.",--Even if we blow up the radar, they can still control this from the laptop. We need to hack it.
	pln_mad_24_01 = "Droga! Eles devem ter enchido o lugar com gás no momento em que entramos. Encontrem de onde está vindo e desligue-o!",--Damn! They must have filled the room with gas the second we entered the lab. Find out where it's dispensed from and shut it off!
	pln_mad_49_02 = "Vocês ouviram o Fedor. Voltem para o lago.",--You heard Fedor. Get your asses to the lake.
	pln_mad_26_02 = "É isso, galera. Isso deve cuidar do gás na sala de escaneamento.",--That's it, gang. That should take care of the gas in the scanning room.
	pln_mad_23_03 = "Vejam se vocês conseguem achar o dispositivo de raio-X que precisamos para conseguir a informação. Sem ele não podemos fazer muita coisa.",--See if you can find the X-ray device we need to get the data. Without it we can't do much.
	pln_mad_59_02 = "Com as defesas anti-aéreas fora do caminho, o Bile terá uma passagem livre para deixar a EMP perto da madeireira.",--With the anti-air defenses out of the way, Bile has free passage to drop the EMP close to the lumber mill.
	pln_mad_07_02 = "É isso, galera. A arma anti-aérea foi desabilitada. Mas ainda falta uma.",--That's it, guys. The AA gun has been disabled. But there's still one more.
	pln_mad_29_01 = "Espera, o que? O cientista chefe está morto? Bom, o único jeito de passar pela porta é com a mão dele... Acho que vocês vão ter que sujar as mãos...",--Wait, what? The lead scientist is dead? Well, the only way we're getting past that door is with the help of his hand...I guess you're gonna have to do some dirty work...
	pln_mad_02_02 = "Vocês precisam destruir ou desabilitar as defesas anti-aéreas. Encontrem um jeito, ou estamos fudidos.",--You need to disable or destroy the anti-air defenses. Find a way, otherwise we're screwed.
	pln_mad_02_03 = "Galera, vocês precisam cuidar das armas anti-aéreas o mais rápido possível. Descubram um jeito!",--Gang, you need to take care of those anti-air guns ASAP. Find a way!
	pln_mad_04_01 = "Liguem o laptop com a arma anti-aérea!",--Hook up the laptop to the anti-aircraft gun!
	pln_mad_05_03 = "Okay, me dê um minuto. Vou desabilitar essa arma anti-aérea.",--Okay, give me a minute or two. I'll disable this AA gun.
	pln_mad_08_02 = "Aposto que tem uns explosivos por aí. Vejam se vocês conseguem achar algum.",--I bet you there are some explosives laying around here. See if you can find any.
	pln_mad_09_02 = "Plantem os explosivos e curta o momento.",--Plant the C4 and enjoy the moment.
	pln_mad_09_03 = "Plantem os explosivos.",--Place the C4.
	pln_mad_10_01 = "Para trás, galera!",--Stand back, gang!
	pln_mad_10_02 = "Protejam-se!",--Take cover!
	pln_mad_10_03 = "Estão prestes a explodir, protejam-se!",--They are about to blow, stand back!
	pln_mad_11_02 = "Perfeito! Não vão mais poder usar aquilo.",--Perfect! They won't be able to use that anymore.
	pln_mad_13_01 = "Boa mira, Bile! Galera, a EMP está no campo perto da madeireira.",--Nice drop, Bile! Gang, the EMP is in the yard outside the lumber mill.
	pln_mad_13_03 = "A EMP foi enviada. Vão para perto da madeireira e pegue-a.",--The EMP has been dropped. Head over just outside the lumber mill and pick it up.
	pln_mad_14_01 = "Certo, galera. Precisamos achar uma entrada para a madeireira. Isso pode parecer loucura, mas talvez podemos usar as armas anti-aéreas que hackeamos antes. Apenas redirecione a posição delas e exploda a parede!",--Ok, gang. We need to find a way into the lumber mill. This might be crazy, but maybe we could use the anti-air gun we hacked earlier? Just redirect its position and blow the wall up?
	pln_mad_15_01 = "É isso aí! Isso foi insano, galera! Agora entrem.",--Hell yeah! That was crazy, gang! Now get in there.
	pln_mad_15_02 = "É assim que se faz! Bom trabalho, pessoal. Entrem na madeireira agora.",--That's how we do it! Good job, guys. Get inside the mill now.
	pln_mad_17_02 = "Protejam a EMP! Os mercenários vão fazer de tudo para interromper vocês!",--Protect the EMP! The mercenaries will do anything to stop you!
	pln_mad_17_03 = "Galera, vocês precisam proteger a EMP equanto ela carrega! Preparem-se para a batalha!",--Gang, you need to protect the EMP while it charges! Prepare to fight!
	pln_mad_18_01 = "Droga, eles interromperam o carregamento!",--Damn it, they stopped the charge!
	pln_mad_19_01 = "Os mercenários interromperam o carregamento da EMP! Toda vez que isso acontece, ela descarrega um pouco!",--The mercenaries interrupted the EMP charge! Every time that happens, the EMP is slowly discharged!
	pln_mad_20_02 = "Ótimo, a EKP está recarregando.",--Good, the EMP is charging again.
	pln_mad_21_03a = "Mas apenas sigam o plano e estaremos bem. Entrem no laboratório pela escotilha e achem o escanedor e as cobaias.",--But just stick to the plan and we should be good. Get inside the laboratory through the hatch and find the scanner and the test-subjects.
	pln_mad_22_01 = "Galera? Não tenho certeza se vocês conseguem me ouvir, mas vocês sabem o que precisa ser feito: Entrar no laboratório pela escotilha.",--Gang? I'm not sure you can hear me, but you know what you're supposed to do: enter the laboratory via the hatchet.
	pln_mad_22_03 = "É isso! A EMP fez seu trabalho! Agora entrem no laboratório pela escotilha.",--That's it! The EMP did its job! Now enter the laboratory via the hatch.
	pln_mad_22_04 = "Galera, vocês conseguem me ouvir? Alô? Entrem no laboratório pela escotilha. Deve estar aberta.",--Guys, can you hear me? Hello? Enter the laboratory via the hatch. It should be open.
	pln_mad_24_02 = "Mas que merda! O lugar inteiro está cheio de gás. Rápido! Descubram de onde está vindo e achem um jeito de desligá-lo!",--What the hell! The whole room is filled with gas. Quickly! Find out where it's coming from and find a way to shut it off!
	pln_mad_24_03 = "Droga! Os desgraçados encheram o lugar com gás para nos parar. Galera, sejam rápidos e descubram um jeito de desligá-lo!",--Damn it! The bastards have filled the room with gas to stop us. Gang, be quick and find a way to shut it off!
	pln_mad_25_01 = "Vocês precisam achar um jeito de desligar o gás.",--You need to find a way to shut off the gas.
	pln_mad_25_03 = "Deve ter algum jeito de desligar essa porra de gás!",--There must be some way to shut off the gas!
	pln_mad_26_01 = "Bom trabalho, galera. Isso deve dar conta do gás na sala de escaneamento.",--Good job, guys. That should get rid of the gas in the scanning room.
	pln_mad_26_03 = "Boa, isso dá conta do gás. Acho que já é seguro entrar na sala.",--Good, that should get rid of the gas. You can most likely enter the room now.
	pln_mad_27_02 = "Mas que caralho! Qual o problema de usar uma porta de segurança tradicional em que você pode usar uma furadeira? Parece que vocês vão precisar do cientista chefe para a autorização por impressão digital.",--Damn it to hell! What is wrong with a traditional security door that you can drill? Looks like you're gonna need the actual lead scientist for hand print authorization. Find him.
	pln_mad_28_03 = "Procurem pelo cientista chefe e leve-o à porta de segurança.",--Look for the lead scientist and get him to the security door. 
	pln_mad_29_02 = "Droga! Eles mataram o cientista chefe? Sei lá, pessoal. A gente ainda precisa da mão dele para a autorização... Façam o que for necessário fazer...",--Damn! They killed the lead scientist? I don't know, guys. We still need his hand for authorization...Do what you have to do...
	pln_mad_30_01 = "Jesus, isso é desagradável. Bom, vocês tem o que precisamos. Talvez... colocar no escaneador?",--Jesus, that's nasty. Well, you got what we need. Place it on the scanner, I guess?
	pln_mad_30_02 = "Wow, vocês fizeram isso mesmo... Vocês são frios. Leve-a para o escaneador e vamos esquecer que isso aconteceu.",--Wow, you really did it... You guys are cold. Bring it to the scanner and let's forget this ever happened.
	pln_mad_31_01 = "Sim, funcionou. Parece que não importa se o cientista estava morto. A tecnologia é cruel. Bom, comecem o escaneamento.",--Yes, it worked. It doesn't seem to matter that the scientist was dead. Technology is cruel. Well, get started with the scanner.
	pln_mad_31_03 = "Okay, a autorização funcionou. Comecem a trabalhar no escaneador.",--Okay, the authorization worked. Get the scanner working now.
	pln_mad_32_01 = "Parece que a energia voltou, galera.",--Look like the power is back, gang. 
	pln_mad_32_03 = "Parece que a energia está voltando.",--Looks like the power is coming back.
	pln_mad_33_01 = "Certo, galera. Vocês vão precisar procurar pelas cobaias e levá-las ao escaneador. Elas devem parecer todas iguais.",--Alright, gang. You need to look for the test-subjects and get them to the scanner. They are supposed to look pretty much the same.
	pln_mad_33_02 = "Se a inteligência está correta as cobaias que vocês precisam escanear são idênticas.",--If the intel is correct the test subjects that you need to scan are identical.
	pln_mad_33_03 = "Certo. Agora achem as cobaias, e leve-as ao escaneador. São homens carecas.",--Alright. Now find the test-subjects, and get them to the scanner. You are looking for some bald guys.
	pln_mad_34_03 = "Levem esse corpo para o escaneador.",--Get that body over to the scanner.
	pln_mad_35_02 = "O corpo está em posição para começar o escaneamento, galera.",--Body is in place so start scanning, gang.
	pln_mad_37_03 = "Galera, esses idiotas interromperam o escaneamento! Religue-o!",--Guys, the bastards stopped the scan! Get it working again!
	pln_mad_38_01 = "Ótimo, o processo de escaneamento está funcionando novamente.",--Great, the scanning is up and running again.
	pln_mad_38_03 = "O escaneamento voltou à ativa. Mantenha assim.",--The scan is back in progress. Now keep it that way.
	pln_mad_39_02 = "Bom trabalho, o escaneamento foi completo.",--Great job, gang. The scan is complete.
	pln_mad_39_03 = "O escaneamento está completo. Bom trabalho, galera.",--The scan has been completed.Well done, gang.
	pln_mad_40_01 = "Eles desligaram a energia!",--They pulled the power!
	pln_mad_40_02 = "Argh, eles desligaram a energia do escaneador!",--Argh, they pulled the power for the scanner!
	pln_mad_41_01 = "Ótimo! A energia voltou. Liguem o escaneador de novo.",--Great! Power is back. Get the scanner working again.
	pln_mad_41_02 = "Okay, ótimo. Vocês religaram a energia. Voltem para o processo de escaneamento.",--Okay, good. You got the power back. Return to the scanning process.
	pln_mad_42_01 = "Okay, a informação está sendo transferida para o servidor na outra sala. Vocês podem pegá-lo ou ficar e escanear mais corpos. Tenho certeza que o Jimmy vai achar um uso pra isso e isso significa mais dinheiro pra gente.",--Okay, the data is being transferred to the server in the other room. You can either go and get it or stay and scan more bodies. I'm sure Jimmy can find use for it and that means more cash for us.
	pln_mad_42_02 = "A informação do escaneamento está sendo coletada naquele servidor da outra sala. Vocês podem ficar e conseguir mais informação, ou podem sair. Mas tenho certeza que o Jimmy pagará bem por mais trabalho.",--The data from the scanning is being collected on that server in the other room. You can stay and get more data, or you can leave. But I'm sure Jimmy would pay us for the trouble. 
	pln_mad_42_03 = "A informação está sendo armazenada no servidor da outra sala. Vocês podem pegá-lo e dar o fora daqui, ou podem ficar e escanear mais corpos. Tenho certeza que o Jimmy vai fazer valer o tempo.",--The data is being stored on the server in the other room. You can get it and get the hell outta here, or you can stay and scan more bodies. I'm positive Jimmy will make it worth your while.
	pln_mad_43_03 = "Excelente decisão, galera. Se vocês escanearem todos os corpos o Jimmy vai nos pagar muito bem. Dinheiro não parece ser problema para ele.",--Excellent decision, guys. If you scan all the bodies Jimmy will pay us good for it. Money doesn't seem to a an issue for him.
	pln_mad_45_02 = "É isso! Agora garantem que vocês vão sair daí com vida.",--That's it! Now make sure you get out of there alive.
	pln_mad_48_02 = "Haha, vocês leram minha mente, pessoal. Sim, eu quero essa maleta.",--Haha, you read my mind, guys. I do want that briefcase.
	pln_mad_48_03 = "Como vocês sabiam que eu queria essa maleta? Não importa, bom trabalho!",--How did you know I wanted that briefcase? It doesn't matter, good job!
	pln_mad_51_01 = "Não há nada mais para se fazer aqui, vamos embora.",--Nothing more to do here. Let's go.
	pln_mad_52_01 = "Certo, esse é o radar controlando a arma anti-aérea. Exploda-o!",--Alright, that's the radar controlling the anti-air gun. Blow it to hell. 
	pln_mad_52_03 = "Parece que esse radar está controlando a arma anti-aérea. Vocês precisam explodí-lo.",--Seems that radar is controlling the anti-air gun. You need to blow it up. 
	pln_mad_53_02 = "O Bile deixou alguns explosivos perto da zona de pouso. Encontre-os.",--Bile dropped some explosives close to your landing spot. Find them.
	pln_mad_55_02 = "O radar ainda está funcionando. Usem os explosivos e destrua-o.",--The radar is still operational. Use the explosives and blow it up.
	pln_mad_55_03 = "Galera, o radar ainda está funcionando? Vocês precisam destruí-lo. Usem os explosivos que o Bile deixou aí pra vocês.",--Guys, the radar is still operational? You need to destroy it. Use the explosives Bile dropped!
	pln_mad_56_01 = "Aquele radar precisa ser destruído de algum jeito. Vejam se vocês conseguem usar a arma anti-aérea para explodí-lo.",--That radar needs to be taken down somehow. See if you can use the anti-air gun to blow it up.
	pln_mad_56_02 = "Precisamos tirar o radar de funcionamento. Os mísseis da arma anti-aérea vão servir. Vejam se vocês conseguem usá-lo.",--We need to take that radar out of action. The missiles from the anti-air gun should do the work. See if you can use it.
	pln_mad_56_03 = "O radar precisa ser destruído o mais rápido possível. Vocês conseguem redirecionar a arma anti-aérea e explodí-lo?",--The radar needs to be taken down ASAP. Maybe you could redirect the anti-air gun and blow it up? 
	pln_mad_57_01 = "Tragam os mísseis para o radar!",--Bring those missiles over to the radar!
	pln_mad_57_02 = "Esses mísseis vão funcionar. Traga-os para o radar.",--Those missiles will do the work. Get them over to the radar!
	pln_mad_58_02 = "Tragam os mísseis para perto do radar e ative-os. Isso vai literalmente bombar.",--Get the missiles close to the radar and activate them. Things are about to go BOOM.
	pln_mad_60_02 = "Para desativar, nós precisamos hackear o laptop que está ligado à isso.",--To disable this we need to hack the laptop that is hooked up to it. 
	pln_mad_61_01 = "A EMP vai fazer duas coisas: Abrir um caminho para o laboratório. Mas o mais importante: Vai nocautear quem quer que seja que estão experimentando, pelo que eu ouvi brigar com eles não é uma opção.",--The EMP will do two things:  It will get us a way in to the hidden lab. But more importantly: It will knock out whoever they are doing tests on, from what I heard fighting them is not an option.
	pln_mad_63_01 = "Mas que merda aconteceu com esse cara?! Tanto faz, precisamos da mão dele.",--What the hell happened to this guy?! Whatever, we need this guys hand.
	
	-- Linhas de Texto do Piloto
	
	plt_mad_intro_01 = "Droga! Eles possuem defesas anti-aéreas posicionadas na fábrica toda. Preciso mudar o avião de direção! Camaradas, vocês precisam usar o paraquedas e pular! Agora!",--Damn! They have anti-air defenses set up around the whole factory. I need to turn the plane around! Comrads, you need to use the parachutes and get out! Right now!
	plt_mad_intro_02 = "Merda! Esses malditos tem defesas anti-aéreas posicionadas! Vou virar o avião! Camaradas, usem os paraquedas e pulem! Vamos pensar em outra coisa!",--Shit! These bastards have anti-air defenses set up! I will turn the plane around! Comrads, use the parachutes and get out! We'll figure something out!
	plt_mad_intro_03 = "Defesas anti-aéreas?! Tá de sacanagem comigo?! Não posso continuar voando! Peguem os paraquedas e pulem!",--Anti-air defenses?! Are you shitting me?! I can't fly any further! Take the parachutes and jump out!
	plt_mad_06_01 = "Huh, certo está do lado de fora. Vai funcionar do mesmo jeito, certo?",--Huh, well it's on the outside. Should work anyway right?
	plt_mad_06_03 = "Caiu bem no meio do campo aberto. Belezinha!",--It landed right out in the open. Zalupa!
	plt_mad_02_01 = "Camaradas! Consegui jogar alguns explosivos para vocês, melhor estarem preparados.",--Comrads! I managed to throw out some explosives for you, better to be prepared.
	plt_mad_06_04 = "Caiu bem no meio do campo aberto.",--It landed right out in the open. 
	plt_mad_04_02 = "Me dê 30 segundos e eu vou enviar a EMP.",--Give me 30 seconds and I will drop that EMP.
	plt_mad_06_02 = "Oh droga, eu errei o lugar por uns 20 metros, desculpa aí galera.",--Oh damn I missed the spot by 20 meters, sorry comrads.
	plt_mad_03_02 = "A EMP é pesada e meu combustível limitado. Preciso soltar ele logo!",--The EMP is heavy and my fuel is limited. I need to drop it soon!
	plt_mad_03_03 = "As defesas já estão desabilitadas, colegas?",--Are those anti-airs disabled yet comrads? 
	plt_mad_04_03 = "Chegando com a EMP.",--Flying in with the EMP right now.
	plt_mad_02_02 = "Deixei uns explosivos na pressa, procurem em volta por eles.",--I dropped some C4 in a rush, look around for them.
	plt_mad_02_03 = "Tem um presentinho lá embaixo para vocês, camaradas. Uma mala cheia de explosivos.",--There is a present down there for you comrads. A nice bag of C4.
	plt_mad_03_01 = "Tempo é dinheiro, colegas. Derrubem as defesas anti-aéreas.",--Time is precious comrads. Get those anti-airs down.
	plt_mad_04_01 = "Vejo que vocês desativaram as armas! Segurem um pouco, estou chegando com a EMP.",--I see that you have disabled the guns! Hold on, I'm coming with the EMP.
	plt_mad_05_01 = "Ha ha. Certeiro na madeireira, isso foi lindo.",--HA HA. Right in the lumber mill, that was beautiful.
	plt_mad_05_02 = "Caiu bem no lugar como planejado.",--Dropped it right on spot.
	plt_mad_05_03 = "Diretamente através do telhado. BOOM!",--Straight through the roof. BOOM!
	plt_mad_07_01 = "Tudo concluído né? Vou pousar perto do lago, preparem-se para a extração.",--All done huh? I will land by the lake, prepare to extract.
	plt_mad_07_02 = "Colegas, venham logo, soldados por toda a parte. Hora de ir embora!",--Comrads get over here, soldiers everywhere. Time to leave!
	plt_mad_07_03 = "No seu tempo, camaradas. O avião está esperando por vocês.",--Take your time comrads. The plane is waiting for you.
	
	-- Objetivos
	
	hud_heist_mad_07 = "Os mercenários não querem você escaneando as cobaias. Mantenha-os longe!",--The mercs don't want you to scan those test subjects. Keep them off it!
	hud_heist_mad_16 = "A parede está bloqueando nossa entrada. Use os mísseis anti-aéreos que hackeamos e exploda-a!",--The wall is blocking our way in. Use the anti-air missiles that we hacked and blow it up!
	hud_heist_mad_02_hl = "Entre na Madeireira",--Enter the lumber mill
	hud_heist_mad_02 = "Entre no campo da madeireira onde a EMP caiu.",--Get into the lumber yard where the EMP has been dropped.
	hud_heist_mad_01 = "Desabilite o sistema anti-aéreo para que o avião possa voar e enviar a EMP.",--Disable the anti air system so that the plane can fly in and drop the EMP.
	hud_heist_mad_08 = "Nós temos algumas informações, mas se você aguentar, seria melhor ter mais. Escaneie mais ou pegue o servidor e fuja.",--We have some information, but if you can handle it, we could use more. So scan more or grab the server and leave.
	hud_heist_mad_05 = "Deve ter um escaneador em algum lugar que podemos usar para escanear as cobaias, encontre-o.",--There should be a scanner that we can use to scan the test subjects somewhere, find it
	hud_heist_mad_08_hl = "Escaneie mais ou Pegue o Servidor",--Scan more or grab the server
	hud_heist_mad_11_hl = "Assegure o Servidor",--Secure the server
	hud_heist_mad_07_hl = "Proteja o Escaneador",--Protect the scanner
	hud_heist_mad_12_hl = "Fuja",--Escape
	hud_heist_mad_01_hl = "Encontre e Desabilite o Sistema Anti-Aéreo",--Find and disable the anti-air system
	hud_heist_mad_04 = "A EMP abriu a entrada para os laboratórios, entre lá!",--The EMP has opened the way down to the labs, get down there!
	hud_heist_mad_13 = "Encontre de onde o gás está sendo liberado e pare-o.",--Find wherever the gas is being dispenesed from and stop it
	hud_heist_mad_03 = "Ative e proteja a EMP, vai levar um tempo para carregar.",--Activate and protect the emp, it will take some time to charge
	hud_heist_mad_16_hl = "Exploda a Parede",--Blow up the wall
	hud_heist_mad_06 = "A EMP nocauteou as cobaias, ache-as e leve-as para o escaneador. Provavelmente estarão vestindo azul.",--The EMP knocked out the test subjects, find them and get them to the scanner. They should be dressed in blue.
	hud_heist_mad_04_hl = "Entre no Laboratório",--Get down into the labs
	hud_heist_mad_09_hl = "Pegue o Servidor",--Grab the server
	hud_heist_mad_14_hl = "Pegue a Autorização na Mão do Cientista Chefe",--Get hand confirmation from the lead scientist
	hud_heist_mad_13_hl = "Pare o Gás",--Stop the gas
	hud_heist_mad_09 = "Temos a informação que precisamos, pegue o servidor e vamos embora!",--We have all the information we need, grab the server and let's go!
	hud_heist_mad_10 = "Ok, galera, também precisamos de uma maleta que deve estar por aqui. Encontre-a!",--Ok guys we also need a briefcase that is supposed to be down here. Find it!
	hud_heist_mad_12 = "Saia do local e vá para o avião!",--Get out of here and head to the plane!
	hud_heist_mad_05_hl = "Encontre o Escaneador",--Find the scanner
	hud_heist_mad_03_hl = "Ative a EMP",--Activate the EMP
	hud_heist_mad_06_hl = "Encontre e Escaneie uma Cobaia",--Find and scan a test subject
	hud_heist_mad_10_hl = "Encontre a Maleta",--Find the briefcase
	hud_heist_mad_11 = "Traga o servidor e a maleta para o avião.",--Bring the server and the briefcase to the plane
	hud_heist_mad_14 = "O escaneador tem uma etapa extra de segurança. Nós precisamos de confirmação usando a mão do cientista chefe. Encontre-o!",--The scanner has an extra security step. We need confirmation by using the lead scientist hand. Find him!	
}