return {
	-- Nomes e Descrições
	--heist_dark = "Murky Station",--Murky Station
	--heist_dark_hl = "Murky Station",--Murky Station
	heist_dark_crimenet = "Para conseguirmos a bomba de EMP, vamos ter que mexer com os caras da Murkywater. Eles estão transportando mercadorias por trem, e estarão fazendo uma parada agendada em um pátio de trens escondido. Eu preferia fazer isso com a boa e velha troca de tiros, mas isso seria muito arriscado, certo? Então precisaremos fazer isso no sigilo, gente.$NL;$NL;» Encontre os Trens$NL;» Localize as Partes da Bomba de EMP$NL;» Tire-as de lá e Fuja",--To get our hands on the EMP bomb, we're gonna have to mess with Murkywater. They are transporting a bunch of goods via train, and will be making a scheduled stop at a hidden train yard. I would prefer to do it guns blazing, but that's too risky, yeah? So we need to this the stealthy way, lads.$NL;$NL;» Find the trains$NL;» Locate the EMP bomb parts$NL;» Get them out of there and escape
	heist_dark_briefing = "Não vou mentir, estamos nos arriscando bastante traindo o Akan, mas acredito ser a escolha certa. O primeiro passo é conseguir a bomba de EMP que está sendo transportada pela Murkywater. Estarão fazendo uma parada agendada. Esta será a nossa chance. Entre silenciosamente, pegue a EMP, e depois saia de lá. Você precisa fazer isso no sigilo, então vista-se como tal.",--I'm not gonna lie; we are taking a huge risk by double-crossing Akan, but I believe this is the right choice. First thing is getting the EMP bomb that is being transported by Murkywater. They will be making a scheduled stop. That will be our chance. Get in quietly, find the EMP, then get out of there. You need to do this by stealth, so dress the part.
	pln_drk_brf_01_01 = "Não vou mentir, estamos nos arriscando bastante traindo o Akan, mas acredito ser a escolha certa. O primeiro passo é conseguir a bomba de EMP que está sendo transportada pela Murkywater. Estarão fazendo uma parada agendada. Esta será a nossa chance. Entre silenciosamente, pegue a EMP, e depois saia de lá. Você precisa fazer isso no sigilo, então vista-se como tal.",--I'm not gonna lie; we are taking a huge risk by double-crossing Akan, but I believe this is the right choice. First thing is getting the EMP bomb that is being transported by Murkywater. They will be making a scheduled stop. That will be our chance. Get in quietly, find the EMP, then get out of there. You need to do this by stealth, so dress the part.
	
	-- Legendas
	pln_drk_intro_01_01a = "Mais dinheiro em nossos bolsos e devemos ganhar um favor do Locke.",--More money in our pockets and it should also win us some favor with Locke.
	pln_drk_intro_01_01 = "A informação que temos nos diz que a bomba de EMP possui duas partes, e é disso que estamos atrás. Mas dito isso: Se tiverem a oportunidade de garantir um pouco de loot extra, vão em frente.",--Intel tells us the EMP bomb will be two parts, and that's what we're here for. But with that said; if you see an opportunity to grab other valuable loot you should do it.
	pln_drk_25_01 = "A Murkywater gosta de tecnologia, então eles devem ter um centro de comando móvel por perto. Vejam se conseguem achar.",--Murkywater like their technology, so they should have some kind of mobile command center nearby. See what you can find.
	pln_drk_42_03 = "Não sejam preguiçosos, galera. Procurem o pátio de trens inteiro se necessário.",--Don't get lazy, gang. Search the whole train yard if needed.
	pln_drk_35_01 = "Okay, a EMP está segura, que é o que precisávamos. Mas ainda temos tempo para voltar e saquear mais coisas se você quiser.",--Okay, the EMP has been secured, which is what we came for. But there is still time to head back and get additional loot if you feel up for it.
	pln_drk_12_02 = "Esse é o cartão de acesso que precisamos. Voltem para o pátio de trens e abram a porta.",--That's the keycard we needed. Get back to the train and open the door.
	pln_drk_16_02 = "Vamos lá, galera. Achem um maçarico.",--Come on, gang. Find a blowtorch.
	pln_drk_40_02 = "Drones com câmeras, sério? A Murkywater está mesmo querendo estar um passo à frente. Tenham cuidado para não serem avistados.",--Drones with cameras, really? Murkywater are stepping up their game. Be careful that you don't get spotted.
	pln_drk_06_02 = "Estamos dentro. Agora procurem pelas partes da EMP.",--We're in. Now look for the EMP parts.
	pln_drk_28_01 = "Tragam o disco rígido para o cofre e plugue-o.",--Bring the hard drive back to the vault and plug it in.
	pln_drk_03_01 = "Pessoal, achem os trens da Murkywater.",--Guys, find the Murkywater trains.
	pln_drk_11_01 = "Galera, sem um cartão de acesso não vamos passar daquela porta. Procurem-no.",--Gang, without a keycard we're not getting past that door. Look for it.
	pln_drk_09_01 = "Parece que precisaremos de um cartão de acesso para passar por isso...",--... looks like we're going to need a keycard to get past this...
	pln_drk_35_02 = "Excelente, já asseguramos a EMP. Não os culpo se vocês quiserem uns loots adicionais antes de escapar. Cabe a vocês.",--Excellent, we got the EMP secured. I won't blame you if you want to get some extra loot before you escape. Up to you.
	pln_drk_26_01 = "Galera, sem algo pra hackear o sistema do cofre, não conseguiremos abrí-lo. Continuem procurando!",--Gang, without something to hack the vault system, we're not getting it open. Keep looking!
	pln_drk_19_01 = "... pelo que parece, essas barras são bem grossas. Vamos precisar de algo pra passar.",--... by the looks of it, these bars are pretty thick. We're going to need something to help get through.
	pln_drk_29_01 = "Talvez esse equipamento pode vir a ser útil, fiquem com ele.",--Maybe that equipment will come in handy later, so hold on to it.
	pln_drk_27_01 = "Esse disco rígido vai servir perfeitamente! Após inserí-lo, vou poder acessar o sistema deles e abrir o cofre.",--That hard drive will be perfect! Once you plug it in, I should be able to access their system and get the vault open.
	pln_drk_05_03 = "Encontrem o painel de segurança para que possamos abrir aquela porta.",--Find the security panel so we can get that door open.
	pln_drk_39_01 = "Se vocês matarem um dos guardas, poderão esconder o corpo dele embaixo do trem para que não seja visto.",--If you happen to drop one of the guards, you should be able to hide the body under the train so it doesn't get detected.
	pln_drk_39_02 = "Tentem não matar ninguém, mas se for necessário, esconder o corpo embaixo do trem pode ser uma boa opção.",--Try not killing anyone, but if it has to be done, then hiding the body under the train should be safe.
	pln_drk_34_02 = "Deixe a EMP na área de fuga. Não podemos arriscar.",--Leave the EMP at the escape area. We don't wanna risk it.
	pln_drk_36_01 = "Atenção, galera. Estou mandando um barco pra buscar vocês. Procurem pelo acesso de água perto do rio.",--Listen up, gang. I'm sending in a boat to pick you up. Look for the small water access near the river.
	pln_drk_04_02 = "Os trens da Murkywater vão estar trancados por um painel de segurança. Teremos que hackeá-los para abrir as portas.",--The Murkywater trains will be locked by some kind of security panel. We'll most likely have to hack them to get the doors open.
	pln_drk_26_03 = "Deve ter algo que podemos usar para passar pelo sistema de segurança do cofre.",--There must be something we can use to get past the vault security system.
	pln_drk_17_02 = "Ótimo, vocês acharam mesmo um maçarico. Voltem para o trem e passem pela porta.",--Great, you actually found a blowtorch. Head back to the train and get through that door.
	pln_drk_07_03 = "Gangue, vocês estão procurando pelas partes da EMP?",--Gang, are you looking for the EMP parts?
	pln_drk_23_03 = "Voltem para o portão de segurança e derretam as barras. Deve funcionar.",--Return to the security gate and melt those bars. It should work.
	pln_drk_29_03 = "Não poderia dar errado com isso, eu acho. Podemos usá-lo depois.",--Could never go wrong with that, I guess. Might be somewhere it can be useful later.
	pln_drk_14_01 = "... não tem um caminho direto para passaar por isso. Vamos precisar de um maçarico ou algo do tipo.",--... there is no direct way to get past this. We're gonna need a blowtorch or something.
	pln_drk_10_01 = "Aposto que um dos guardas deixou um cartão de acesso em algum lugar. Procurem aí em volta.",--I bet one of the guards has left a keycard somewhere. Look around.
	pln_drk_12_01 = "Excelente, vocês encontraram um cartão de acesso. Agora, voltem para o trem e abram aquela merda.",--Excellent, you found a keycard. Now, head back to the train and open that sucker.
	pln_drk_24_01 = "... podemos esquecer a ideia de usar a furadeira nisso. Faria muito barulho. Talvez achar um jeito de hackear?",--... we can forget about drilling our way through this. It would cause too much noise. Maybe we can find a way to hack it?
	pln_drk_32_03 = "Nada nos impede de pegar a EMP. Voltem para os trens.",--Nothing stopping us from getting our hands on the EMP. Get back to the trains.
	pln_drk_16_03 = "Ainda precisamos de um maçarico, gangue.",--We still need to find a blowtorch, gang.
	pln_drk_33_03 = "Bom trabalho! Voltem para a zona de fuga e deixem a bomba de EMP lá.",--Great job! Head over to the escape area and drop off the EMP bomb.
	pln_drk_36_03 = "O motorista de fuga está chegando de barco para extrair vocês. Tenham certeza de que vocês estarão perto do acesso de água perto do rio.",--The escape driver is coming in by boat to pick you up. Make sure you are over by the small water access near the river.
	pln_drk_20_01 = "Tem muita construção nessa área. Vejam se vocês conseguem achar algo para nos ajudar a passar pelo portão.",--There is a lot of construction in this area. Check it out and see if you can find something to help us tackle that steel gate.
	pln_drk_34_01 = "Pessoal, vocês ainda precisam assegurar a EMP na área de fuga.",--Guys, you still need to secure the EMP at the escape area.
	pln_drk_43_03 = "Pode valer a pena verificar os túneis de manutenção.",--It might be worth to check the maintenance tunnels.
	pln_drk_03_03 = "Se vocês não acharem os trens da Murkywater, não conseguiremos a nossa bomba de EMP.",--If you don't find the Murkywater trains, we're not getting the EMP bomb.
	pln_drk_06_03 = "Bom trabalho. Olhem por perto e vejam se conseguem achar as partes da EMP.",--Good job. Look around and see if you can find the EMP parts.
	pln_drk_32_02 = "Voltem para os trens e peguem a EMP.",--Get back to the trains and get the EMP.
	pln_drk_16_01 = "Pessoal, vocês precisam achar um maçarico, se não estaremos fudidos.",--Guys, you need to find a blowtorch otherwise we're screwed.
	pln_drk_02_02a = "Lembrem-se de que a bomba de EMP possui duas partes e não preciso lembrá-los de que precisamos das duas.",--Remember that the EMP bomb is two parts and I don't have to remind you we need both.
	pln_drk_02_01 = "Achem um caminho para dentro do perímetro e localizem os trens da Murkywater. As partes da EMP provavelmente estarão em vagões diferentes.",--Find your way inside and locate the Murkywater trains. The EMP parts will most likely be in different wagons.
	pln_drk_22_02 = "Ótimo, vocês encontraram um pouco de Térmite. Agora podemos derreter o portão de aço.",--Great, you found some thermite. Now we can melt our way through that steel gate.
	pln_drk_03_02 = "Os trens da Murkywater devem estar fáceis de avistar. Encontre-os.",--The trains belonging to Murkywater should be easy to spot. Find them.
	pln_drk_41_02 = "Bom trabalho, aquele drone não vai estar aqui para ser testemunha da revolução dos robôs. Mas tenham certeza de que vocês esconderam a pilha de lixo. Não podemos deixar os guardas verem isso.",--Good job, that drone won't be here to witness the robot revolution. But make sure you hide the pile of junk. We can't have one of the guards finding it.
	pln_drk_11_04 = "Vocês precisam achar um cartão de acesso para abrir aquela porta. Vamos.",--You really need to find a keycard to get that door open. Come on.
	pln_drk_11_02 = "Pessoal, a gente ainda precisa de um cartão de acesso.",--Guys, we still need a keycard.
	pln_drk_31_01 = "Okay, temos tudo o que precisamos para roubar as partes da EMP. Voltem para os trens.",--Okay, now we got all we need to steal the EMP parts. Head back to the trains.
	pln_drk_22_03 = "Agora que vocês já possuem um pouco de Térmite, podemos facilmente derreter as barras do portão.",--Now that you got your hands on some thermite, we can easily melt the bars on the gate.
	pln_drk_33_02 = "Bom trabalho. Agora, assegurem a EMP na área de fuga antes de saquear mais coisas.",--Good job. Now, secure the EMP at the escape area before grabbing any additional loot.
	pln_drk_28_03 = "Voltem para a porta do cofre e insiram o HD. Eu cuido do resto.",--Head back to the vault door and plug in the hard drive. I'll take care of the rest.
	pln_drk_46_01 = "Galera, eu quero uma varredura da área inteira. Isso significa checar todos os cantos do pátio de trens. Não deixem passar nada.",--Gang, I want a sweep of the whole area. That means checking all corners of the train yard. Don't leave any stone unturned.
	pln_drk_17_03 = "Ótimo, vocês conseguiram o maçarico. Nada nos impede de passar pelo portão agora.",--Good, you got your hands on a blowtorch. Nothing stopping us from getting through that door now.
	pln_drk_45_03 = "Vocês já procuraram nos trens?",--Have you checked between the actual trains?
	pln_drk_13_02 = "Tragam o cartão de acesso de volta para a porta.",--Bring the keycard back to the door.
	pln_drk_11_03 = "Deve ter um cartão de acesso por aqui em algum lugar.",--There must be a keycard somewhere.
	pln_drk_40_01 = "Droga, são drones? Estamos vivendo no futuro mesmo, né? Eles parecem ter uma câmera, então fiquem fora do campo de visão.",--Damn, are those drones? We're really living in the future, aren't we? They seem to have a camera so stay out of sight.
	pln_drk_05_02 = "O único jeito de abrir as portas é hackeando o painel. Ache-o.",--Only way to get the doors open is by hacking the panel. Find it.
	pln_drk_18_03 = "Voltem para a porta de segurança e abra-a usando o maçarico.",--Get back to the security door and get it open using the blowtorch.
	pln_drk_32_01 = "Galera, a gente ainda precisa pegar a EMP.",--Gang, we still need to get the EMP.
	pln_drk_38_01 = "Ei, esses dutos são perfeitos para esconder um corpo ou transferir os loots.",--Hey, these vents should be perfect if you need hide a body or transfer loot through.
	pln_drk_17_01 = "Macacos me mordam, você achou um maçarico. Agora podemos abrir caminho pela porta.",--Well, I'll be damned, you found a blowtorch. Now we can burn our way through the door.
	pln_drk_37_03 = "Enviando a van pra aí. O Twitch vai vir pela ponte de cima.",--Sending the van your way. Twitch will come from the upper bridge side.
	pln_drk_05_01 = "Procurem pelo painel de segurança, galera. É o único jeito de entrar.",--Look for the security panel, gang. That's the only way in.
	pln_drk_23_01 = "Voltem para o portão de segurança e usem a Térmite.",--Get back to the security gate and use the thermite.
	pln_drk_22_01 = "Vocês encontraram a Térmite? Excelente! Voltem para o portão e derretam as barras de aço.",--You found thermite? Excellent! Head back to the steel gate and melt those bars.
	pln_drk_15_01 = "Estamos em um pátio de trens, devem ter ferramentas por aqui. Vejam o que vocês podem achar. Um maçarico seria perfeito.",--We're in a train yard, there should be tools laying around somewhere. See what you can find. A blowtorch would be perfect.
	pln_drk_36_02 = "Ei, o motorista de fuga está vindo de barco. Vão lá para o pequeno acesso de água perto do rio.",--Hey, I got your escape driver coming in by boat. Head over to the small water access area near the river.
	pln_drk_30_01 = "Esse pé de cabra vai aumentar nossas chances de conseguir loots adicionais antes de ir embora.",--That crowbar will increase our chances of getting additional loot before we leave.
	pln_drk_42_01 = "Pessoal, vocês não procuraram tudo ainda. Devem tá esquecendo alguma coisa.",--Guys, you can't have searched the whole train yard. You must be missing something.
	pln_drk_04_01 = "Okay, agora vocês vão precisar procurar pelos trens da Murkywater.",--Okay, now you need to look for the actual Murkywater trains.
	pln_drk_02_02 = "Entrem lá dentro e procurem pelos trens da Murkywater. Vai ser bem fácil de achá-los.",--Get in and look for the Murkywater trains. You should be able to spot them fairly easy.
	pln_drk_08_02 = "Mas que merda é essa? Os informantes do Elefante não mencionaram uma porta de segurança adicional.",--What the hell? Elephant's sources didn't mention an additional security door...
	pln_drk_07_02 = "Procurem pelas partes da EMP. Isso é prioridade máxima.",--Look for the EMP parts. That's top priority.
	pln_drk_31_02 = "É isso, galera. Agora voltem para os trens e peguem a bomba de EMP.",--That's it, gang. Now get back to the trains and get your hands on the EMP bomb.
	pln_drk_43_02 = "Os túneis de manutenção podem ter o que vocês procuram, procurem por lá.",--The maintenance tunnels could have what you're looking for. Search it.
	pln_drk_01_01a = "Lembrem-se, nós temos que fazer isso no Stealth. Se o alarme disparar, estaremos fudidos.",--Remember, we are doing this silent. If the alarm goes off we're screwed.
	pln_drk_31_03 = "Okay. Hora de voltar para os trens e colocar a EMP na bolsa.",--Okay. Time to head back to the trains and get that EMP in the bag.
	pln_drk_34_03 = "Assegurem a EMP na área de fuga. Melhor prevenir do que remediar.",--Secure the EMP over by the escape area. Better to be safe than sorry.
	pln_drk_27_03 = "Disso que precisamos! Insira esse HD e eu tomo conta do resto. Esse cofre vai tá aberto em poucos segundos.",--Just what we needed! Plug that hard drive in and I'll take care of it. That vault should be opened in no time.
	pln_drk_47_02 = "Parece que a EMP não tá aqui, mas ainda tem uns loots valiosos pra gente. Vocês podem checar agora ou voltar depois.",--Looks like the EMP isn't here, but there might be some other valuable loot for us. You can either check it now or come back later.
	pln_drk_18_02 = "Vocês encontraram um maçarico, e agora precisam usá-lo.",--You found a blowtorch, and now you need to actually use it.
	pln_drk_37_02 = "O Twitch está chegando com a van para pegar vocês. Ele vai esperar na ponte de cima.",--Twitch is arriving with the van to pick you up. He'll wait by the upper bridge side.
	pln_drk_42_02 = "Vocês já procuraram pelo pátio de trens inteiro?",--Have you searched through the whole train yard?
	pln_drk_35_03a = "Por que não voltam para pegar um pouco dos valiosos loots? Isso vai valer o nosso tempo.",--Why not go back and get some of that juicy loot? I'll make it worth your time.
	pln_drk_08_01 = "Droga! Eles tem uma porta de segurança adicional...",--Damn! They have set up an additional security door...
	pln_drk_23_02 = "Vocês precisam usar a Térmite para passar pela porta de segurança.",--You need to use the thermite to get past that security gate.
	pln_drk_26_02 = "Veja se vocês conseguem achar algo para hackear o sistema do cofre.",--See if you can find something we can use to hack the vault system.
	pln_drk_01_02 = "Okay, pessoal, esse é um bom lugar. Vocês quase tem uma visão completa do pátio de trens. Mantenham os rastros dos guardas e das câmeras.",--Okay, guys, this is a good spot. You almost have a clear view of the train yard. Keep track of the patrolling guards and cameras.
	pln_drk_18_01 = "Pessoal, voltem para a porta de segurança e usem o maçarico.",--Guys, head back to the security door and use the blowtorch.
	pln_drk_44_02 = "Tem um monte de salas nos túneis de manutenção. Verifiquem todas.",--There's a bunch of rooms in the maintenance tunnels. Check all of them.
	pln_drk_44_03 = "Vocês já checaram todas as salas do túnel de manutenção?",--Have you checked all the rooms in the maintenance tunnels?
	pln_drk_33_01 = "Excelente, temos o que precisamos. Vão para a área de fuga e assegurem a EMP.",--Excellent, we got what we came for. Get over to the escape area and secure the EMP.
	pln_drk_13_01 = "Com aquele cartão de acesso, nós poderemos abrir a porta.",--With that keycard we should be able to get the door opened.
	pln_drk_02_03 = "Foquem em achar os trens que contenham as partes da bomba de EMP. Essa é a nossa prioridade.",--Focus on finding the trains containing the EMP bomb parts. That's our main priority.
	pln_drk_06_01 = "Excelente, vocês entraram. As partes da EMP devem estar por aí. Encontre-as.",--Excellent, you got in. The EMP parts should be there somewhere. Find it.
	pln_drk_01_01 = "Okay, gangue. O pátio de trens está logo em frente. Devem ter vários jeitos de se infiltrar no lugar, então escolham sabiamente.",--Okay, gang. The train yard is right in front of you. There should be several ways you can infiltrate the place, so make your choices wisely.
	pln_drk_01_02a = "Essa é a chance de vocês planejarem suas escolhas.",--This is your chance to plan your course of action.
	pln_drk_01_03 = "É isso, o pátio escondido de trens. Usem essa oportunidade para vigiar a área. O lugar está patrulhado por guardas e câmeras de forma rígida, então não podemos cometer nenhum erro.",--That's it, the hidden train yard. Use this opportunity to scout the area. The place is heavily guarded by Murkies and cameras, so we can't afford to make any mistakes.
	pln_drk_04_01a = "Eles devem ter algum tipo de painel dos lados.",--They should have some kind of panels on the side.
	pln_drk_04_03 = "Os trens da Murkywater vão ter um painel de segurança dos lados, então teremos que hackeá-los.",--The Murkywater trains will have a security panel on the side, so we'll have to hack them open.
	pln_drk_07_01 = "Abram os olhos e achem a EMP. Vamos.",--Open your eyes and find the EMP. Come on.
	pln_drk_08_03 = "Droga, de onde veio essa porta? Desculpa, galera. Eu não fazia ideia de que ela estaria aqui.",--Damn, where did this door come from? Sorry, gang. I had no information this would be here...
	pln_drk_13_03 = "Vocês precisam usar o cartão de acesso, sabiam?",--You need to actually use the keycard, you know?
	pln_drk_21_01 = "Galera, ainda precisamos achar um jeito de passar pelo portão de aço. Vocês precisam achar algo que possamos usar.",--Gang, we still need a way to get through that steel gate . You need to find something that we can use.
	pln_drk_21_02 = "Vocês ainda precisam achar algo em que podemos usar para passar pelas barras.",--You still need to find something we can use to get through those bars.
	pln_drk_21_03 = "Pessoal, encontrem algo em que podemos usar nas barras. Algo que não faça muito barulho.",--Guys, find something we can use on those bars. Something that doesn't give off too much noise.
	pln_drk_25_02 = "Se pudermos achar um disco rígido, talvez poderemos hackear o sistema para o cofre.",--If we could get our hands on a hard drive, we might be able to hack the system to the vault.
	pln_drk_27_02 = "Com esse disco rígido eu poderei invadir o sistema de segurança e abrir o cofre.",--With this hard drive I should be able to override their security and get the vault open.
	pln_drk_28_02 = "Voltem para o trem e usem o disco rígido. Eu devo conseguir passar pela segurança.",--Get back to the train and use the hard drive. I should be able to override the security.
	pln_drk_29_02 = "Claro, por que não? Podemos achar um uso para ele depois.",--Sure, why not? We might find use for it later.
	pln_drk_30_02 = "Ótimo, agora podemos abrir mais rapidamente os caixotes que estão pelo pátio. Aposto que tem vários coisas valiosas.",--Great, now we can open the crates laying around much faster. I bet you they contain some good stuff.
	pln_drk_30_03 = "Se vocês planejam ficar e saquear mais, esse pé de cabra vai servir.",--If you're planning on sticking around for extra loot, that crowbar will do the trick.
	pln_drk_35_03 = "Com a EMP assegurada, temos um tempinho de sobra até que a van de fuga chegue.",--With the EMP secured, there is some time to kill before the escape vehicle arrives.
	pln_drk_37_01 = "Atenção, gangue. O Twitch vai chegar com a van. Ele vai chegar pela ponte de cima.",--Listen up, gang. Twitch is coming in with the van. He will come from the upper bridge side.
	pln_drk_38_02 = "Esse sistema de ventilação pode ser usado para nossa vantagem, sabe, para esconder um corpo ou transferir nossos loots.",--This ventilation system could be used to our advantage, you know, to hide a body or transfer some of the extra through.
	pln_drk_41_01 = "Boa, vocês acabaram com o desgraçado. Mas escondam essa bagunça. Os guardas vão reagir se descobrirem que você destruiu um dos drones.",--Nice, you took that sucker out. But hide the mess. The guards will react if they find out you destroyed one of their drones.
	pln_drk_43_01 = "Galera, os túneis de manutenção podem ser o que estamos procurando.",--Guys, the maintenance tunnels could have what we're looking for.
	pln_drk_44_01 = "Tem várias salas nos túneis de manutenção. Já verificaram todas elas?",--There's several rooms in the maintenance tunnels. Have you checked all of them?
	pln_drk_45_01 = "Verifiquem entre os trens também, pessoal. Não sejam desleixados.",--Check between the trains too, guys. Don't get sloppy.
	pln_drk_45_02 = "Tem um espaço entre os trens também. Vale a pena olhar.",--There's space between the trains too. It's worth a look.
	pln_drk_46_02 = "A área não é tão grande. Vocês devem conseguir se mover e procurar todos os cantos de todo o pátio de trens.",--The area isn't too big. You should be able to move around and search all corners of the whole train yard.
	pln_drk_46_03 = "Tem quatro de vocês, galera. Espalhem-se caso necessário e chequem todos os cantos do pátio de trens",--There's four of you, guys. Spread out if needed and check all corners of the train yard.
	pln_drk_47_01 = "Droga, parece que a EMP não está nesse vagão. Ainda devem ter loots valiosos por aqui, então peguem agora ou voltem depois para pegar. A escolha é de vocês.",--Damn, looks like the EMP isn't in this train car. There could still be some valuable loot here, so either grab it now or come back for it later. Your choice.
	pln_drk_48_01 = "Merda! O alarme!",--Damn it! That's the alarm!
	
	-- Objetivos
	hud_heist_dark_02_hl = "Hackeie os Trens da Murkywater",--Hack open the Murky trains
	hud_heist_dark_07 = "Agora que você tem todas as partes da EMP, você poderá fugir ou saquear mais loots.",--Now that you have all EMP parts, you can escape or secure more loot.
	hud_heist_dark_03_hl = "Localize as partes da EMP",--Locate the EMP parts 
	hud_heist_dark_07_hl = "Fuga Disponível",--Escape Available
	hud_heist_dark_06 = "Assegure as partes da EMP na área de fuga.",--Secure the EMP parts at the escape area.
	hud_heist_dark_05_hl = "Ensaqueie as partes da EMP",--Bag the EMP parts
	hud_heist_dark_06_hl = "Assegure as partes da EMP",--Secure the EMP parts
	hud_heist_dark_02 = "Hackeie um painel de segurança do lado dos trens para abrir as portas principais.",--Hack into a security panel on the side of the trains to open the main doors.
	hud_heist_dark_04_hl = "Encontre o Equipamento",--Find Equipment
	hud_heist_dark_01_hl = "Encontre os Trens da Murkywater",--Find the Murky Trains
	hud_heist_dark_05 = "Ensaqueie as partes da EMP escondidas nos trens da Murkywater.",--Bag up the EMP parts hidden in the Murkywater Trains
	hud_heist_dark_01 = "Invada o pátio de trens e localize os trens da Murkywater dentro dele.",--Breach the trainyard and locate the Murkywater Trains inside.
	hud_heist_dark_04 = "Você vai precisar de mais equipamento para passar pela última porta do trem.",--You will need new equipment in order to breach the final train door.
	hud_heist_dark_03 = "Localize todas as partes diferentes da bomba de EMP.",--Locate all of the different parts of the EMP bomb.
		}