return {
    --heist_chca_hl = "",--Black Cat
    --heist_chca
    heist_chca_briefing = 'Vamos ter que ajudar o Vlad a ter sua vingança e fazer um bocado de dinheiro limpando o Black Cat logo que ele entrar em águas internacionais. Jiu Feng tem um infiltrado ajudando a gente e sabemos que Xun Kang, e outro babaca chamado Li Deng estão liderando essa operação. Eles vão ter as chaves para abrir o cofre. Mantenham a operação firme, porque a guarda costeira vai encher o navio de policiais antes mesmo que possamos falar "Olha, um texugo nadando!", então sem brincadeiras, certo?',
--[[ We're going to help Vlad get some payback and make a kakspul of cash doing it by cleaning out the Black Cat as soon as it enters international waters. Jiu Feng has an insider helping us and we've learned that Xun Kang, and another dwankie named Li Deng are running the operation. They will have the keys to opening the vault. Keep a tight operation, because the coast guard will fill the ship with kerels before you can say "Look, a blerrie swimming badger!", so no messing around, yeah?]]

    heist_chca_crimenet = "Meus amigos, tá na hora de se vingar daqueles filhas da puta da Tríade. Com ajuda de Jiu Feng, eu descobri que a Tríade está mantendo a maior parte do dinheiro deles em um cofre de Casino em seu navio cruzeiro, o Black Cat. O fudido que me torturou está até comandando o lugar! Vamos fazer aqueles arrombados sentir come se estivessem no Titanic, e varrer eles do mapa! Parece bom?\n\n» Embarque no Black Cat\n» Obtenha a Informação, Código e a Digital para o Cofre\n» Encontre e Abra o Cofre\n» Assegure o Loot e Fuja",
--[[ My Friends, it's time to get back at those Golden Toothpick motherfuckers. With the help of Jiu Feng, I found out that The triad is keeping most of it's money in a casino vault on their cruise ship, The Black Cat. The fucker that tortured me is even running the place! Let's make those noodle-suckers feel like they are on the Titanic, and clean them out! Sound good?

    » Board the Black Cat
    » Obtain the insider info, code and the handprint for the vault
    » Locate and open the vault
    » Secure the loot and Escape]]

    -- Intros
    loc_chca_intro_01_01 = "Então, você se lembra do Hajrudin, o meu cunhado?",--So, you remember Hajrudin, my brother-in law?
    loc_chca_intro_01_02 = "Um pouco, o que tem ele?",--Vaguely. What about him?
    loc_chca_intro_01_03 = "O idiota do caralho tava ajudando com a padaria, começou a falar com um policial que tava lá tomando café, disse umas coisas bem idiotas. Agora tô com problemas com esse policial que tá sabendo das coisas.",--Stupid motherfucker was helping in the bakery the other day, starting talking to a cop who was sitting there drinking coffee, saying some very stupid things. Now I have this problem with the cop who knows shit.
    loc_chca_intro_01_04 = "O que isso tem a ver com o assalto?",--What does this have to do with the heist?
    loc_chca_intro_01_05 = "Eu sei lá! A gente tá sentado aqui esperando. Só queria quebrar o gelo.",--I don't know! We're just sitting here waiting. I was just making conversation.
    loc_chca_intro_01_07 = "Então, o que você acha que deveria fazer?",--So what do you think I should do?
    loc_chca_intro_01_08 = "Como eu deveria saber, seu burro do caralho!",--How the blerrie hell should I know, you dwankie!
    loc_chca_intro_01_09 = "Não consigo decidir, deveria matar ele ou mandar um bolo cheio de dinheiro. O que acha?",--I can't decide if I should have him killed, or send him a big fucking cake full of money. Whaddayouthink?
    loc_chca_intro_01_10 = "Vai ser um daqueles dias... com certeza.",--It's going to be one of those days... for sure.
    loc_chca_intro_02_01 = "Ei, Locky, diga pro pessoal que se eles encontrarem o desgraçado filho da puta que tentou me matar com a porra de uma bateria de carro, que eu quero que eles cortem o nariz e traguem de volta!",--Hey, Locky! Tell the guys that if they see that motherfucking noodle-sucking piece of shit that tried to kill me with the fucking car battery, I want them to cut off his fucking nose and bring it back!
    loc_chca_intro_02_02 = "A gente tá aqui pelo dinheiro, seu idiota. Não temos tempo pra cortar narizes.",--We're here for the cash, you chop. There's no time for cutting off any noses.
    loc_chca_intro_02_03 = "Pô, aí não tem graça. Qual sentindo de roubar todo esse dinheiro sem ter um pouco de diversão, hm?",--Pah! You're no fun. What's the point of stealing all that fucking money if we can't have a little fun, too eh?
    loc_chca_intro_02_04 = "Tá bom... talvez. SE tivermos tempo pra isso.",--Ok, well... maybe. IF, there's time.
    loc_chca_intro_03_01 = "Então, a gente vai no estilo Titanic nessa merda ou o que?",--So, are we going to go all Titanic on this motherfucker, or what?
    loc_chca_intro_03_02 = "Não, seu idiota, o iate tá cheio de civis. A gente só vai pegar o dinheiro.",--No, you chop, the ship is full of civvies. We're just taking the money.
    loc_chca_intro_03_03 = "Que tal foder um pouco as coisas deles?",--What about fucking their shit up a little?
    loc_chca_intro_03_04 = "Bom, isso é com o meu pessoal, yeah?",--Well, that usually comes with the territory for my guys, yeah?
    loc_chca_intro_04_01 = "Esses filhas da puta... ouvi dizer que o cuzão da bateria de carro está no iate.",--These motherfuckers... I heard the car-battery asshole is on the boat.
    loc_chca_intro_04_02 = "Bom, foi o que ouvimos dizer, yeah.",--That's what we heard, yeah.
    loc_chca_intro_04_03 = "Eu quero ele morto. Eu quero que atirem nos joelhos dele, aí cortem as tripas dele e joguem ele no mar.",--I want him dead. I want bullets in his kneecaps, then I want him cut open and fed to the fish.
    loc_chca_intro_04_04 = "Deu pra entender. Talvez se a oportunidade aparecer, o pessoal vai cuidar disso.",--Completely understandable. Maybe if the opportunity presents itself, the guys'll take care of it.
    loc_chca_intro_04_05 = "Eu espero. Eu realmente espero, porra. Ninguém coloca o Vlad numa situação de merda e sai vivo. O mundo precisa saber! Vlad aqui tem uma reputação pra representar, sabe.",--I hope so. I really fucking hope so. No one puts Vlad through that shit and lives. The world has to know! Vlad has a reputation to uphold, you know.
    loc_chca_intro_05_01 = "Então, Vlad... sabe falar Chinês?",--So, Vlad.... do you know any Chinese?
    loc_chca_intro_05_02 = "Sei porra nenhuma.",--Not a fucking word.
    loc_chca_intro_05_03 = "O que você acha que isso significa? Meio que se aplica pro cara do Wang, Ching-wah TSAO duh liou mahnge.",--What do you think this means? It kind of applies to that Wang-guy, Ching-wah TSAO duh liou mahnge
    loc_chca_intro_05_04 = "Seja lá o que isso for, eu acho que você falou tudo errado. Parecia o Hajrudin bêbado depois de ter bebido duas garrafas de rum uma vez.",--Whatever that was, I don't think you said it right. Sounded like Hajrudin after he drank two bottles of rum that one time.
    loc_chca_intro_05_05 = "Foi o que Jiu Feng disse.",--That's pretty much what Jiu Feng said.
    loc_chca_intro_05_06 = "Ué, ele conhece o meu cunhado?",--What, he knows my brother-in-law?
    loc_chca_intro_05_07 = "Não, seu idiota, foi um sentimento da coisa, sabe?",--No you chop, it was the sentiment of the thing, yeah?

    -- [mesmo texto que o de cima, a única diferença é a entrada que o jogador escolhe]

    loc_chca_intro_loud_01_01 = "Então, você se lembra do Hajrudin, o meu cunhado?",--So, you remember Hajrudin, my brother-in law?
    loc_chca_intro_loud_01_02 = "Um pouco, o que tem ele?",--Vaguely. What about him?
    loc_chca_intro_loud_01_03 = "O idiota do caralho tava ajudando com a padaria, começou a falar com um policial que tava lá tomando café, disse umas coisas bem idiotas. Agora tô com problemas com esse policial que tá sabendo das coisas.",--Stupid motherfucker was helping in the bakery the other day, starting talking to a cop who was sitting there drinking coffee, saying some very stupid things. Now I have this problem with the cop who knows shit.
    loc_chca_intro_loud_01_04 = "O que isso tem a ver com o assalto?",--What does this have to do with the heist?
    loc_chca_intro_loud_01_05 = "Eu sei lá! A gente tá sentado aqui esperando. Só queria quebrar o gelo.",--I don't know! We're just sitting here waiting. I was just making conversation.
    loc_chca_intro_loud_01_07 = "Então, o que você acha que deveria fazer?",--So what do you think I should do?
    loc_chca_intro_loud_01_08 = "Como eu deveria saber, seu burro do caralho!",--How the blerrie hell should I know, you dwankie!
    loc_chca_intro_loud_01_09 = "Não consigo decidir, deveria matar ele ou mandar um bolo cheio de dinheiro. O que acha?",--I can't decide if I should have him killed, or send him a big fucking cake full of money. Whaddayouthink?
    loc_chca_intro_loud_01_10 = "Vai ser um daqueles dias... com certeza.",--It's going to be one of those days... for sure.
    loc_chca_intro_loud_02_01 = "Ei, Locky, diga pro pessoal que se eles encontrarem o desgraçado filho da puta que tentou me matar com a porra de uma bateria de carro, que eu quero que eles cortem o nariz e traguem de volta!",--Hey, Locky! Tell the guys that if they see that motherfucking noodle-sucking piece of shit that tried to kill me with the fucking car battery, I want them to cut off his fucking nose and bring it back!
    loc_chca_intro_loud_02_02 = "A gente tá aqui pelo dinheiro, seu idiota. Não temos tempo pra cortar narizes.",--We're here for the cash, you chop. There's no time for cutting off any noses.
    loc_chca_intro_loud_02_03 = "Pô, aí não tem graça. Qual sentindo de roubar todo esse dinheiro sem ter um pouco de diversão, hm?",--Pah! You're no fun. What's the point of stealing all that fucking money if we can't have a little fun, too eh?
    loc_chca_intro_loud_02_04 = "Tá bom... talvez. SE tivermos tempo pra isso.",--Ok, well... maybe. IF, there's time.
    loc_chca_intro_loud_03_01 = "Então, a gente vai no estilo Titanic nessa merda ou o que?",--So, are we going to go all Titanic on this motherfucker, or what?
    loc_chca_intro_loud_03_02 = "Não, seu idiota, o iate tá cheio de civis. A gente só vai pegar o dinheiro.",--No, you chop, the ship is full of civvies. We're just taking the money.
    loc_chca_intro_loud_03_03 = "Que tal foder um pouco as coisas deles?",--What about fucking their shit up a little?
    loc_chca_intro_loud_03_04 = "Bom, isso é com o meu pessoal, sim?",--Well, that usually comes with the territory for my guys, yeah?
    loc_chca_intro_loud_04_01 = "Esses filhas da puta... ouvi dizer que o cuzão da bateria de carro está no iate.",--These motherfuckers... I heard the car-battery asshole is on the boat.
    loc_chca_intro_loud_04_02 = "Bom, foi o que ouvimos dizer, sim.",--That's what we heard, yeah.
    loc_chca_intro_loud_04_03 = "Eu quero ele morto. Eu quero que atirem nos joelhos dele, aí cortem as tripas dele e joguem ele no mar.",--I want him dead. I want bullets in his kneecaps, then I want him cut open and fed to the fish.
    loc_chca_intro_loud_04_04 = "Deu pra entender. Talvez se a oportunidade aparecer, o pessoal poderá cuidar disso.",--Completely understandable. Maybe if the opportunity presents itself, the guys'll take care of it.
    loc_chca_intro_loud_04_05 = "Eu espero. Eu realmente espero, porra. Ninguém coloca o Vlad numa situação de merda e sai vivo. O mundo precisa saber! Vlad aqui tem uma reputação pra representar, sabe.",--I hope so. I really fucking hope so. No one puts Vlad through that shit and lives. The world has to know! Vlad has a reputation to uphold, you know.
    loc_chca_intro_loud_05_01 = "Então, Vlad... sabe falar Chinês?",--So, Vlad.... do you know any Chinese?
    loc_chca_intro_loud_05_02 = "Sei porra nenhuma.",--Not a fucking word.
    loc_chca_intro_loud_05_03 = "O que você acha que isso significa? Meio que se aplica pro cara do Wang, Ching-wah TSAO duh liou mahnge.",--What do you think this means? It kind of applies to that Wang-guy, Ching-wah TSAO duh liou mahnge
    loc_chca_intro_loud_05_04 = "Seja lá o que isso for, eu acho que você falou tudo errado. Parecia o Hajrudin bêbado depois de ter bebido duas garrafas de rum uma vez.",--Whatever that was, I don't think you said it right. Sounded like Hajrudin after he drank two bottles of rum that one time.
    loc_chca_intro_loud_05_05 = "Foi o que Jiu Feng disse.",--That's pretty much what Jiu Feng said.
    loc_chca_intro_loud_05_06 = "Ué, ele conhece o meu cunhado?",--What, he knows my brother-in-law?
    loc_chca_intro_loud_05_07 = "Não, seu idiota, foi um sentimento da coisa, sabe?",--No you chop, it was the sentiment of the thing, yeah?

    -- Legendas
    vld_chca_14_01 = "É ele! É o filho da puta que tentou me matar!",--That's him! That's the motherfucker that got me! [Tô rezando que só tem três variações, eu vou ficar puto se tiver mais.]
    bar_chca_01_01 = "Eu estive esperando. Seu equipamento está esperando em um dos banheiros, mas tem um pequeno problema. A segurança do cofre mudou. Li Deng ainda tem o código, mas vocês vão precisar pegar a digital de Xun Kang também para abri-lo. Eu deixei uma cera de impressão nas suas coisas. Boa Sorte.",--I've been waiting. Your equipment is waiting in one of the cabin lavatories, but there is a small complication. Vault security has been changed. Li Deng still has the code, but you will need Xun Kang's hand print as well to open it. I was able to acquire some impression wax and store it with your gear. Good luck.
    loc_chca_001_01 = "OK, amigos. Deem uma olhada em volta.",--OK, friends. Have a look around.
    loc_chca_001_02 = "Deem uma olhada cuidadosa em volta. Fiquem longe dos guardas de Wang.",--Have a careful look around. Stay clear of Wang's guards.
    loc_chca_001_03 = "Muitos civis em volta e a Tríade tem mais guardas do que esperavamos.",--Lots of civvies around and the triad have more guards than we hoped for.
    loc_chca_002_01 = "O cara do Jiu Feng está atendendo um bar em algum lugar, vamos achá-lo e ver o que ele tem a dizer.",--Jiu Feng's man is tending bar somewhere, let's go find him and see what he has to say.
    loc_chca_002_02 = "Tem um barman esperando por nós com algumas informações, vamos encontrá-lo.",--There's a barman waiting for us with some insider info, let's find him.
    loc_chca_002_03 = "OK, temos um infiltrado atendendo em um bar. Vão falar com ele.",--OK, we've got an insider tending bar. Go talk to him.
    loc_chca_003_01 = "Encontrem o barman infiltrado, amigos.",--Find the barman insider, friends.
    loc_chca_003_02 = "Já acharam o barman?",--Have you found the barman?
    loc_chca_003_03 = "Vocês precisam ir até o barman.",--You need to get to the barman.
    loc_chca_004_01 = "OK, agora vamos encontrar seus equipamentos, yeah?",--Kif, now let's go find your gear, yeah?
    loc_chca_004_02 = "Vamos pegar aqueles equipamentos.",--Let's get that gear.
    loc_chca_004_03 = "Encontrem os seus equipamentos.",--Go find your gear.
    loc_chca_005_01 = "Encontrem o banheiro com seus equipamentos, amigos.",--Find the bathroom with your gear, friends.
    loc_chca_005_02 = "Já acharam o armário d'água? ",--Have you found that water-closet yet?
    loc_chca_005_03 = "Vocês ainda precisam pegar seus equipamentos.",--You still need to collect your gear.
    loc_chca_005a_01 = "Uma boa entrada silenciosa, yeah? Eles nunca vão perceber a chegada de vocês. Então vão lá.",--A nice quiet entrance, yeah? They never heard you coming. So get to it.
    loc_chca_005a_02 = "Quieto como um gato dormindo e que não ronca! Vamos nessa, yeah?",--Quiet like a sleeping cat that doesn't snore! Let's do this, yeah?
    loc_chca_005a_03 = "Bom e quieto. Vamos continuar.",--Nice and quiet. Let's get going.
    loc_chca_006_01 = "O cara do Jiu Feng iria colocar umas informações atualizadas em uma maleta e esconder ela em um dos banheiros, então vamos encontrá-la, yeah?",--Jiu Feng's man was supposed to put some updated information in a briefcase and hide it in one of the cabin bathrooms, so let's go find it, yeah?
    loc_chca_006_02 = "Nós precisamos pegar a informação atualizada em uma maleta escondida no banheiro. Procurem por ela.",--We were supposed to get updated intel in a briefcase hidden in a cabin bathroom. Go look for it.
    loc_chca_006_03 = "Tem uma maleta com informação atualizada esperando por vocês em um dos banheiros. Melhor ir achá-la, yeah?",--There's a briefcase with updated intel waiting for you in a cabin bathroom. Better go find it, yeah?
    loc_chca_007_01 = "Sem tempo para bater papo com os turistas bêbados. Encontrem o loo com a maleta.",--No time for chatting up the drunk tourists. Find the loo with the briefcase.
    loc_chca_007_02 = "Já acharam a maleta? Ela tá em um dos banheiros.",--Have you found the briefcase yet? It's in a cabin bathroom.
    loc_chca_007_03 = "Precisamos daquela informação atualizada. Encontrem o banheiro com a maleta.",--We need that updated intel. Find the bathroom with the briefcase.
    loc_chca_008_01 = "Ok, então eles tentaram dividir a responsabilidade da segurança do cofre. Vocês vão ter que pegar o código de Li Deng e usar aquela coisa grudenta na maleta para pegar a digital de Xun Kang.",--OK, so they've split security responsibility for the vault. You will need to get the code from Li Deng, and use that sticky wax stuff in the briefcase to get Xun Kang's handprint.
    loc_chca_008_02 = "Segurança do cofre foi dividida. Vocês precisam do código do Deng, e a digital de Kang.",--Vault security has been divided. You need to get the code from Deng, and take a casting of Kang's handprint.
    loc_chca_008_03 = "Para entrar no cofre, vamos precisar do código de Deng e a digital de Kang.",--To get into the vault, we will need Deng's code and Kang's handprint.
    loc_chca_009_01 = "Pelo que sabemos, Li Deng fica a maior parte de seu tempo no Spa, enquanto Xun Kang fica no Casino.",--From what we know, Li Deng spends most of his time in the spa, while Xun Kang watches over the casino.
    loc_chca_009_02 = "Deng deve estar no Spa, e vocês provavelmente vão achar o Kang pelo Casino.",--Deng should be in the spa, and you'll probably find Kang around the casino.
    loc_chca_009_03 = "Kang está observando o Casino e Deng está provavelmente no Spa.",--Kang is overseeing the casino and Deng is probably in the spa.
    loc_chca_010_01 = "Droga, não tem como chegar nele sem causar um problema. Vamos pegar um pouco de informação. Plantem uma escuta perto do escritório para ouvir o que ele está falando.",--Blerrie, there's no way to get to him without causing a ruckus. Let's gather some more info. Plant a bug near the office so we can hear what he's saying.
    loc_chca_010_02 = "Porra! Não da pra chegar nele sem atrair suspeitas. Vamos ver o que ele está fazendo. Plantem um dispositivo de escuta.",--Ach! Can't get to him quietly. Let's see what he's up to. Plant a listening device.
    loc_chca_010_03 = "Não tem como chegar nele no momento. Coloquem uma escuta perto da sala para podermos encontrar o que ele ta fazendo, yeah?",--No way to get to him at the moment. Stick a bug near the room so we can find out what he's up to, yeah?
    loc_chca_011_01 = "Talvez um armário perto da sala de conferência fosse um lugar bom para a escuta, yeah?",--Maybe a storage closet near the meeting room would be a good place for the bug, yeah?
    loc_chca_011_02 = "Um armário seria um bom lugar para colocar o dispositivo de escuta.",--A storage closet would be a good place to put the listening device.
    loc_chca_011_03 = "Já plantaram a escuta?",--Have you planted the bug yet?
    loc_chca_012_01 = "Se conseguirem um dos cartões do quarto de Xun Kang, acho que poderiamos fazer uma chamada e tirar ele dali, yeah? Vejam se conseguem achar o número de seu quarto. ",--If you can get one of those cards out of Xun Kang's cabin, I reckon I could bluff a phone call and get him out of there, yeah? See if you can find out his cabin number.
    loc_chca_012_02 = "Nós provavelmente poderiamos atrair o Kang para fora se conseguirem achar seu número de telefone em um dos cartões que eles mencionaram. Encontrem o número de seu quarto e vão até lá.",--We could probably lure Kang out of there if you can get his phone number from the cards they mentioned. Find his cabin number and make your way there.
    loc_chca_012_03 = "Tem uma boa chance de podermos enganar Kang para fora dali se acharmos o número de seu quarto. Vão até lá e peguem um daqueles cartões de número de telefone.",--There's a good chance we can trick Kang out of there if you can find his cabin number. Go there and pick up one of those burner phone number cards.
    loc_chca_013_01 = "Eles podem ter o quarto listado em um computador no convés.",--They might have his cabin listed in a computer on the crew deck.
    loc_chca_013_02 = "Vocês não podem correr por ai abrindo portas aleatórias. Talvez esteja listado em algum lugar?",--You can't run around opening random doors. Maybe it's listed somewhere?
    loc_chca_013_03 = "Continuem procurando pelo quarto de Kang.",--Keep looking for Kang's cabin.
    loc_chca_014_01 = "OK, vamos ver se não conseguimos achar aquele número de telefone.",--OK, now let's see if we can't find that phone number.
    loc_chca_014_02 = "Agora encontrem aquele cartão de negócios com o número de Kang.",--Now go find that business card with Kang's number.
    loc_chca_014_03 = "Hora  de achar o número de telefone do Kang.",--Time to find Kang's phone number.
    loc_chca_015_01 = "Vamos lá, amigos. Encontrem o número de telefone no quarto de Xun Kang.",--Come on, friends. Find the phone number in Xun Kang's cabin.
    loc_chca_015_02 = "Já acharam aquele cartão de negócios?",--Have you found that business card yet?
    loc_chca_015_03 = "Ainda precisam achar aquele número de telefone, yeah?",--Still need to find that phone number, yeah?
    loc_chca_016_01 = "Número do quarto de Xun Kang: Anotem isso. Pode ser útil.",--Xun Kang's cabin number: Make a note of that. Might come in handy.
    loc_chca_016_02 = "Aquele é o quarto de Kang. Vamos lembrar isso, yeah?",--That's Kang's cabin. Let's remember that, yeah?
    loc_chca_016_03 = "Esse quarto pertence a Kang. Bom saber.",--This cabin belongs to Kang. Good to know.
    loc_chca_017_01 = "Vou apostar minha boina, aquele número de contato é do Xun Kang.",--I'll wager my beret, that's a burner contact number for Xun Kang.
    loc_chca_017_02 = "Aquele é provavelmente o número de Kang ou algo assim.",--That's probably a burner number for Kang or something.
    loc_chca_017_03 = "Isso pode ser útil. Vamos lembrar disso, amigos.",--That might come in handy. Let's remember it, friends.
    loc_chca_018_01 = "Droga, ele ta bem seguro ali, com certeza. Talvez eu possa usar aquele número que acharam antes e fazer ele sair. Vale a pena tentar, yeah?",--Blerrie, he's pretty secure in there, for sure. Maybe I can use that number you found before and get him to leave. Worth a try, yeah?
    loc_chca_018_02 = "Não podemos chegar nele ali. Talvez tenha uma maneira de enganar o infeliz a sair. Vamos dar uma ligada.",--We can't get to him in there. Maybe there's a way to trick the dwankie into coming out. Let's give him a ring.
    loc_chca_018_03 = "Vamos atrair o babaca para fora de algum jeito. Eu tenho uma ideia.",--We're going to have to lure the dwankie out of there somehow. I have an idea.
    loc_chca_019_01 = "Se eu conseguir fazer ele sair, vocês vão precisar seguir ele e pegar uma impressão de sua digital.",--If I get him to leave, you need to follow him and get an impression of his handprint.
    loc_chca_019_02 = "Vou tirar ele dali, então vocês podem pegar sua digital, yeah?",--I'll get him out of there, then you can get his hand print, yeah?
    loc_chca_019_03 = "Assim que ele estiver no aberto, vocês podem pegar sua digital.",--As soon as he's in the open, you can get his handprint.
    loc_chca_020_01 = "Vamos lá, seu imbecil, atende!",--Come on, you kak, pick it up!
    loc_chca_020_02 = "Ok, Vlad... Prepare-se.",--Ok, Vlad... get ready.
    loc_chca_021_01 = "Vocês precisam pegar sua digital, rápido! Bem, eu não digo que precisam arrancar a mão dele, só peguem a digital. Apressem-se, amigos.",--You need to get his hand print, chop chop! Well, I don't mean you need to chop it off, just get the print. Go get it, friends.
    loc_chca_021_02 = "Já pegaram a digital?",--Have you got the hand print yet?
    loc_chca_021_03 = "Não podem entrar no cofre sem a digital de Kang, amigos.",--Can't get into the vault without Kang's handprint, friends.
    loc_chca_022_01 = "Vocês tem o código, agora precisam da digital.",--You have the code, now we need the hand print.
    loc_chca_022_02 = "Ok, vocês tem o código mas temos que pegar a digital de Kang também.",--Ok, you got the code but we have to get Kang's hand print as well.
    loc_chca_022_03 = "Temos o código de Deng, mas vocês tem que pegar a digital de Kang.",--We've got Deng's code, but you have to get the hand print from Kang.
    loc_chca_023_01 = "Sabemos que Xun Kang fica de olho no Casino pela sua Sala de Conferência.",--We know Xun Kang keeps an eye on the casino from the meeting room overlook.
    loc_chca_023_02 = "Nossa informação diz que Kang geralmente está vigiando o Casino.",--Our intel says Kang is usually watching over the casino.
    loc_chca_023_03 = "Vocês provavelmente vão encontrar o Xun Kang no Casino.",--You will likely find Xun Kang in the casino.
    loc_chca_024_01 = "Pela descrição, aquele deve ser Li Deng. Babaca imundo. Ele tem um cofre em sua sala de massagem privada, lá que vocês irão encontrar o código.",--From the description, that's got to be Li Deng. Nasty dwankie. He keeps a safe in his private massage room, so that's where we'll find the code.
    loc_chca_024_02 = "OK, aquele deve ser Deng. Que tipo de imbecil faria aquilo com os dentes? Encontrem o cofre em sua sala de massagem privada e peguem o código.",--OK, that's got to be Deng. What kind of laanie kek would do that to his teeth? Find the safe in his private massage chamber and get the code.
    loc_chca_024_03 = "Aposto que aquele é Li Deng. Vão até sua câmara de massagem, encontrem seu cofre e abram-o. O código que precisamos está dentro.",--I reckon that's Li Deng. Go to his massage chamber, find his safe and open it. The code we need is inside.
    loc_chca_025_01 = "Hora de pegar o código de Li Deng. Sabemos que ele pode geralmente ser encontrado perto do Spa.",--Time to get that code from Li Deng. We know he can usually be found near the spa.
    loc_chca_025_02 = "Deng geralmente fica por volta do Spa. O babaca é conhecido por assediar moças...",--Deng usually hangs around the spa. The dwankie is known for harassing the ladies...
    loc_chca_025_03 = "Vão até o Spa e vejam se o Deng está lá.",--Get to the spa and see if Deng is there.
    loc_chca_026_01 = "Tem um cofre dentro de sua sala privada de massagem. Vocês pegarão o código lá.",--There is a safe inside his private massage room. You'll find the code in there.
    loc_chca_026_02 = "Precisamos pegar o código na câmara de Deng.",--You need to find the safe in Deng's massage chamber.
    loc_chca_026_03 = "O código fica no cofre na sala de massagem de Deng.",--The code is kept in a safe in Deng's massage room.
    loc_chca_027_01 = "Eu vejo duas opções. Vocês podem furar o cofre e arriscar fazer muito barulho, ou tentar pegar a chave de Li Deng de algum outro jeito.",--I see two options. Either you drill the safe and risk making a kakspul of noise, or try to get the key from Li Deng somehow.
    loc_chca_027_02 = "Vocês podem furar o cofre e correr riscos de alguém escutar, ou pegar a chave de Li Deng.",--You can drill the safe and cause a minor ruckus, or get the key from Li Deng.
    loc_chca_027_03 = "Vocês podem pegar a chave do cofre do Li Deng ou arriscar furá-lo.",--You can get the key to the safe from Li Deng or risk drilling it instead.
    loc_chca_028_01 = "Nosso infiltrado já deve ter alterado a bebida de Li Deng. Esperem ele ter alguma reação, então sigam ele e peguem a chave, ou se estiverem com pressa, vocês podem furar o cofre.",--Our inside man will have spiked Li Deng's drink by now. Either wait for him to have a reaction, then follow and take his key, or if you're in a hurry, you can drill the safe.
    loc_chca_028_02 = "Ok, nosso garçom já deve ter drogado o Li Deng. Deve ser fácil pegar a chave dele agora, ao invés de perfurar o cofre.",--Ok, the bartender should have drugged Li Deng by now. Should be easy enough to get the key from him unless you want to drill.
    loc_chca_028_03 = "Deng já deve estar sentindo o efeito das drogas do barman. Escolham agora se vão querer perfurar o cofre ou peguem a chave dele.",--Deng should be feeling the effects of the barman's drug by now. Unless you feel like drilling, get the key off him.
    loc_chca_029_01 = "Fiquem de olho nos guardas. Essas paredes são bem à prova de som, e os motores do navio vão disfarçar a furadeira, mas ainda é arriscado.",--Keep a lookout for guards. There's fairly good soundproofing in those walls, and the ships engine noise will mask some of the drill, but it's still risky.
    loc_chca_029_02 = "Pode valer a pena arriscar e furar, mas fiquem bem atentos.",--Might be worth risking a drill, but keep a close watch.
    loc_chca_029_03 = "Tem muito barulho no navio que vai esconder o barulho da furadeira, mas continuem de olho, yeah?",--There's a lot of noise on a ship that will hide the noise from the drill, but keep your wits about you, yeah?
    loc_chca_029a_01 = "Talvez ele vá sair para fumar ou algo em breve. Vocês podem pegar ele.",--Maybe he'll go out for a smoke or something soon. You can grab him then.
    loc_chca_029a_02 = "Vejam se podem pegar ele sozinho.",--See if you can catch him alone.
    loc_chca_029a_03 = "Se conseguirem deixar ele sozinho, ele será um alvo fácil.",--If you can get him alone, he'll be an easy target.
    loc_chca_030_01 = "Certo, seus idiotas. Hora de ir pro cofre.",--Right, you chops. Time to get to the vault.
    loc_chca_030_02 = "Vamos ir pro cofre.",--Let's get to the vault.
    loc_chca_030_03 = "OK, amigos. Vão até o cofre.",--OK, friends. Make your way to the vault.
    loc_chca_031_01 = "Vão até o cofre no Casino.",--Make your way to the vault in the casino.
    loc_chca_031_02 = "O cofre ta no Casino.",--The vault is in the casino.
    loc_chca_031_03 = "Vamos seus idiotas, vão até o cofre do Casino.",--Come on you chops, get to the casino vault.
    loc_chca_032_01 = "Precisamos tirar aqueles guardas de merda do caminho. Talvez uma distração, yeah?",--Need to get those dwankie guards out of the way. Maybe a distraction, yeah?
    loc_chca_032_02 = "Precisamos achar uma maneira de distrair os guardas.",--We should find a way to distract those guards.
    loc_chca_032_03 = "Acho que precisamos distrair aqueles guardas de alguma forma.",--I think we need to distract those guards somehow.
    loc_chca_033_01 = "Podemos mexer com os caça-níqueis. Encontrem a sala de controle e hackeiem o sistema.",--We could have a tinker with the slot machines. Find their control room and hack the system.
    loc_chca_033_02 = "Esses caça-níqueis funcionam em rede. Hackeando eles deve funcionar. Encontrem a sala de controle.",--These slot machines are networked. Hacking them would work. Find the control room.
    loc_chca_033_03 = "Encontrem a sala de controle e hackeiem a rede de caça-níqueis. Deve fazer algum barulho, com certeza!",--Find the control room and hack the slot machine network. That should make some noise, for sure!
    loc_chca_034_01 = "Agora precisamos lidar com aqueles alarmes lasers.",--Next we need to take care of that laser alarm.
    loc_chca_034_02 = "Temos que desligar o sistema de lasers.",--Gotta take that laser system offline.
    loc_chca_034_03 = "Aquele sistema de lasers vai ser um problema. Desliguem-o.",--That laser alarm system will be a problem. Take it down.
    loc_chca_035_01 = "O cara do Jiu Feng conseguiu abrir uma caixa de manutenção em algum lugar no Casino, deixando um fio exposto para cortarmos.",--Jiu Feng's guy has arranged to open a maintenance box somewhere in the casino, leaving an exposed wire for us to cut.
    loc_chca_035_02 = "Era pro barman deixar uma caixa de manutenção aberta em algum lugar. Encontrem-a. ",--The bartender was supposed to leave a maintenance box open somewhere. Find it.
    loc_chca_035_03 = "Nosso infiltrado deve ter deixado uma caixa de fios aberta. Encontrem-a e cortem a fiação.",--Our inside guy should have left the wiring box for it open. Find it and cut the wiring.
    loc_chca_036_01 = "Hora de abrir aquele cofre. Vão até lá, rápido.",--Time to get that vault open. Get to it, chop chop.
    loc_chca_036_02 = "Agora para o cofre!",--Now for the vault!
    loc_chca_036_03 = "Vamos abrir aquele cofre, amigos!",--Let's open that vault, friends!
    loc_chca_037_01 = "Vamos, amigos. Abram aquele cofre.",--Come on, friends. Get the vault open.
    loc_chca_037_02 = "O cofre!",--The vault!
    loc_chca_037_03 = "O que tão esperando? Cuidem do cofre.",--What are you waiting for? Take care of the vault.
    loc_chca_038_01 = "Ai sim. Vamos limpar essa merda toda. Só joguem as malas no mar e vou arranjar alguém para buscá-las.",--There we go. Let's clean these dwankies out. Just toss those bags overboard and I'll have them picked up, right away.
    loc_chca_038_02 = "Agora limpem esses babacas. Joguem as malas no oceano e daremos um jeito de pegá-las depois.",--Now clean these kaks out. Throw the bags into the ocean and I'll have them picked up.
    loc_chca_038_03 = "Peguem todo o dinheiro que puderem e joguem as malas no mar. Tenho uma pessoa esperando para pegá-las.",--Take all the money you can and throw the bags overboard. I've got someone waiting to pick them up.
    loc_chca_039_01 = "Rápido, amigos. Continuem pegando. Queremos limpar esses idiotas e fazer eles sofrerem.",--Hurry, friends. Keep taking. We want to clean these kaks out and make them suffer.
    loc_chca_039_02 = "Limpem esses desgraçados, seus idiotas!",--Clean these dwankies out, you chops!
    loc_chca_039_03 = "Continuem esvaziando aquele cofre!",--Keep emptying that vault!
    loc_chca_040_01 = "Se acharem que acabaram de roubar, talvez possamos mandar uma mensagem. Ativando uma bomba de tinta no resto do dinheiro seria um bom dedo do meio para a Golden Dagger, com certeza!",--If you feel like you're done looting, maybe we can make a little statement. Setting off an ink bomb on the rest of that cash would be a nice middle finger to the Golden Dagger, for sure!
    loc_chca_040_02 = "Enquanto ficarmos machucando esses idiotas, devemos colocar um insulto, colocando uma bomba de tinta no resto do dinheiro seria um golpe duplo, né?",--As long as we're hurting these kaks, we might as well add a little insult, putting an ink bomb on the rest of that money would be a double-whammy, yeah?
    loc_chca_040_03 = "Se não quiserem carregar mais, ativem uma bomba de tinta no resto para estragar pra Tríade. É uma ótima forma de mostrar como nos sentimos também.",--If you don't want to carry any more, set off an ink bomb on the rest to ruin it for the triad. It's a nice way to show them how we feel, too.
    loc_chca_041_01 = "Vamos lá, rapazes. Decidam como querem fazer, para podermos tirar vocês daí logo.",--Let's go lads. Decide how you want to play it so we can get you out of there.
    loc_chca_041_02 = "Vamos amigos, façam sua escolha e vamos.",--Come one friends, make your choice and let's go.
    loc_chca_041_03 = "Não precisam esperar, decidam o que querem fazer.",--No need to hang around, just decide what you want to do.
    loc_chca_042_01 = "Normalmente, eu diria que é uma vergonha jogar fora dinheiro assim, mas o sinal que isso vai mandar vale a pena, yeah?",--Normally, I'd say it's a shame wasting good money like that, but the signal this is going to send makes it all worth it, yeah?
    loc_chca_042_02 = "Isso vai machucá-los em dobro, amigos!",--This is going to hurt them doubly, friends!
    loc_chca_042_03 = "Eles vão estar arruinados depois disso.",--They are going to be ruined after this.
    loc_chca_043_01 = "Kif! Yufu Wang vai ficar muito puto quando ver isso.",--Kif! Yufu Wang is going to go bossies when he sees that.
    loc_chca_043_02 = "Eu queria ver o rosto do Wang quando ele ver isso",--I'd like to see Wang's face when he sees this.
    loc_chca_043_03 = "Essa é a maneira Payday de falar 'vai cagar' enquanto estragam o dia de alguém!",--That's the Payday way of saying 'piss off' while your ruining someone's day!
    loc_chca_044_01 = "OK, hora de sair. Vão pro convés e peguem um dos botes salva vidas. ",--OK, time to leave. Get on deck and commandeer one of the lifeboats.
    loc_chca_044_02 = "Vamos tirar vocês daí. Usem um dos bote salva vidas.",--Let's get you out of there. Use one of the lifeboats.
    loc_chca_044_03 = "Agora, vão até o convés e peguem um bote salva vidas para fugirem.",--Now, get up on deck and use a lifeboat to make your escape.
    loc_chca_045_01 = "Vocês precisam ativar a manivela para baixar os botes.",--You need to activate the pulley system to lower the lifeboat.
    loc_chca_045_02 = "Ativem a manivela para trazer ele para baixo.",--Activate the pulley system to bring one down.
    loc_chca_045_03 = "Os botes são abaixados com uma manivela.",--The lifeboats are lowered with a pulley system.
    loc_chca_046_01 = "Agora embarquem e saiam daí, seus idiotas!",--Now hop onboard and get out of there, you chops!
    loc_chca_046_02 = "Todos à bordo!",--Get onboard!
    loc_chca_046_03 = "Hora de embarcar e sair!",--Time to get aboard and leave!
    loc_chca_047_01 = "O que tão esperando? Procurando por mais para roubar?",--What are you waiting for? Looking for more to steal?
    loc_chca_047_02 = "Sem tempo a perder.",--No time to stand around.
    loc_chca_047_03 = "Vamos tirar vocês daí, amigos.",--Let's get you out of there, friends.
    loc_chca_048_01 = "Droga! Eu consigo ouvir aquele alarme aqui da terra firme! Saquem suas armas antes da chegada da guarda costeira!",--Blerrie! I can hear that alarm from here on land! Break out the guns before the coast guard arrives!
    loc_chca_048_02 = "Lá se vai essa porra, com certeza! Armas preparadas, seus idiotas!",-- There goes the neighborhood, for sure! Weapons free, you chops!
    loc_chca_048_03 = "Não precisa mais ficar na ponta dos pés. Vamos fazer isso do jeito clássico, yeah?",--No need to tippytoe. Let's do this loud and fast, yeah?
    loc_chca_049_01 = "Ok, seus idiotas! Sejam rápidos com isso. Estejam com as Armas em mãos logo quando chegarem no convés. Sejam rápidos, pois a guarda costeira não vai demorar para responder!",--Ok, you chops! Be quick about this. Weapons free as soon as you hit the deck. Get it done fast, because the coast guard will not take long to respond with kerels!
    loc_chca_049_02 = "Vamos fazer isso rápido e eficiente. Não precisa esperar a guarda costeira nos esmagar.",--Let's do this fast and efficient. No need to wait for the coast guard to overwhelm us.
    loc_chca_049_03 = "A guarda costeira vai estar aqui bem antes com policiais, então vamos fazer isso rápido.",--The coast guard will be here before long with kerels, so let's do this quickly.
    loc_chca_050_01 = "O cara do Jiu Feng deve ter deixado algum equipamento extra na despensa de compartimento no convés. Vão lá pegar, vai vai!",--Jiu Feng's man should have left you some extra equipment in the storage compartment on the crew deck. Go pick it up, chop chop!
    loc_chca_050_02 = "Nosso infiltrado deixou alguns equipamentos para vocês na despensa do convés.",--Our inside man will have left you some equipment in a storage space on the crew deck.
    loc_chca_050_03 = "Vão até a despensa no convés e coletem seus equipamentos que o infiltrado deixou para vocês.",--Get to the storage space on the crew deck and collect the gear our insider has left for you.
    loc_chca_051_01 = "Procurem nas despensas no convés.",--Look for the storage room on the crew deck.
    loc_chca_051_02 = "Vocês deviam procurar no convés por seus equipamentos.",--You should look on the crew deck for your gear.
    loc_chca_051_03 = "Já acharam aquele depósito?",--Have you found that storage space yet?
    loc_chca_052_01 = "Sabemos que o cofre está sendo controlado por dois superiores de Yufu Wang. Li Deng tem o código, vocês vão precisar da digital de Xun Kang também.",--We know the vault is controlled by Yufu Wang's two top men. Li Deng has the code, and you need Xun Kang's handprint as well.
    loc_chca_052_02 = "Vamos precisar do código de Li Deng e a digital de Xun Kang para abrir o cofre.",--We'll need the code from Li Deng and Xun Kang's handprint to open the vault.
    loc_chca_052_03 = "Vocês vão ter que pegar o código de Deng e a digital de Kang para abrir o cofre, yeah?",--You will have to get Deng's code and Kang's handprint in order to open the vault, yeah?
    loc_chca_053_01 = "Vamos lá amigos. Vão até o Spa ou até o Casino.",--Come on friends. Get to the spa and the casino.
    loc_chca_053_02 = "Rápido amigos, aquele cofre não vai se abrir sozinho.",--Hurry friends, that vault isn't going to open itself.
    loc_chca_053_03 = "Já acharam Deng ou Kang?",--Have you found Deng or Kang yet?
    loc_chca_054_01 = "Parece que aquele tal de Kang se trancou na sala de conferência. Quebrem essa porra até chegar lá dentro.",--Looks like that Kang-dwankie has locked himself in the meeting room. Smash your way inside.
    loc_chca_054_02 = "Kang está na sala de conferência. Estorem ela.",--Kang is in the meeting room. Smash it open.
    loc_chca_054_03 = "Vocês vão ter que detonar a entrada para chegar até o Kang!",--You'll have to crash your way in to get Kang!
    loc_chca_055_01 = "Joguem algumas balas naquele vidro, talvez vá rachá-lo, yeah?",--Put some bullets in that glass, maybe that will crack it, yeah?
    loc_chca_055_02 = "Amigos, atirem na janela. Atirem. No. Vidro!",--Friends, shoot the window. Shoot. The. Glass!
    loc_chca_055_03 = "Tentem atirar na entrada.",--Try shooting your way in.
    loc_chca_056_01 = "Bem, isso não funcionou. Precisam de algo maior. Aquele candelabro pode servir... Derretam um dos cabos com um pouco de Térmite!",--Well, that didn't work. You need something bigger. That chandelier might do... melt one of the cables with some thermite!
    loc_chca_056_02 = "OK, aquilo não funcionou. Talvez aquele candelabro... derretam o cabo com um pouco de Térmite!",--OK, that didn't work. Maybe that chandelier... melt the cable with some thermite!
    loc_chca_056_03 = "Droga, vamos tentar usar o candelabro. Usem um Térmite em um dos cabos que está segurando-o.",--Ach, let's try using the chandelier. Use some thermite on one of the cables holding it.
    loc_chca_057_01 = "Peguem o Térmite e outros equipamentos na despensa do convés.",--Get the thermite and other equipment from the storage room on the crew deck!
    loc_chca_057_02 = "Vocês irão encontrar Térmite e outros equipamentos esperando na despensa do convés.",--You'll find thermite and other equipment waiting in the storage room on the crew deck!
    loc_chca_057_03 = "No depósito no convés vocês poderão encontrar Térmite e outras coisas.",--In the storage area of the crew deck you will find thermite and other gear.
    loc_chca_058_01 = "Usem o Térmite naquele cabo do candelabro para balançar ele e fazê-lo quebrar a janela.",--Use the thermite on the chandelier cable to swing it loose and smash the window.
    loc_chca_058_02 = "Façam os cabos daquele candelabro queimar com o Térmite.",--Set the cable of that chandelier to melting with thermite.
    loc_chca_058_03 = "Queimem aquele cabo segurando o candelabro com Térmite para ele bater no vidro.",--Burn loose the cable holding the chandelier with thermite and crash it into the window.
    loc_chca_059_01 = "O que tão esperando, seus idiotas! Façam aquele Térmite queimar!",--What are you waiting for, you chops! Get that thermite burning!
    loc_chca_059_02 = "Vamo lá, derretam aquele cabo, vai vai!",--Come on, melt that cable, chop chop!
    loc_chca_059_03 = "Já colocaram o Térmite naquele cabo?",--Have you set the thermite on that cable yet?
    loc_chca_060_01 = "Boa, o infiltrado do Jiu Feng colocou o equipamento onde ele deveria. Parece um cara confiável.",--Good, Jiu Feng's insider put this equipment right where he was supposed to. Seems like a reliable chop.
    loc_chca_060_02 = "Parece que o cara do Feng entregou.",--Looks like Feng's guy delivered.
    loc_chca_060_03 = "Essa é uma coisa a menos para se preocupar.",--That's one less thing to worry about.
    loc_chca_061_01 = "Aquele vidro é muito grosso para tiros, mas talvez aquele candelabro seja pesado o suficiente para quebrar. Usem o Térmite para queimar um dos cabos para soltá-lo! ",--That glass is too thick for shooting, but maybe that chandelier is heavy enough to crack it. Use some of your thermite to burn through one of the cables to let it rip!
    loc_chca_061_02 = "Vidro reforçado. Droga. Talvez possamos estourá-lo. Tentem queimar um dos cabos segurando aquele candelabro com um pouco de Térmite e vejam o que acontece.",--Armored glass. Blerrie. Maybe we can smash it. Try burning through a cable holding that chandelier with some thermite and see what happens.
    loc_chca_061_03 = "OK, não podemos atirar por aquele vidro. Tentem quebrar com o candelabro. Usem algum Térmite em um dos cabos segurando-o, yeah?",--OK, we can't shoot through that glass. Try breaking it with the chandelier. Use some thermite on one of the cables holding it, yeah?
    loc_chca_062_01 = "Vão até o Kang e peguem a digital de sua mão!",--Get to Kang and take a print of his hand!
    loc_chca_062_02 = "Agora peguem a digital de Kang!",--Now go get Kang's handprint!
    loc_chca_062_03 = "Aí sim! Hora de pegar aquela digital de Xun Kang!",--There you go! Time to get that handprint off Xun Kang!
    loc_chca_063_01 = "Vocês precisam daquela impressão de mão para o cofre.",--You need that hand impression to get into the vault.
    loc_chca_063_02 = "Já pegaram aquela digital?",--Have you got that handprint yet?
    loc_chca_063_03 = "Não dá pra entrar no cofre sem a digital de Kang.",--Can't get into the vault without Kang's handprint
    loc_chca_064_01 = "Agora vocês só precisam da digital de Kang.",--Now you just need to get that handprint off Kang.
    loc_chca_064_02 = "Já pegaram a digital?",--Have you got the handprint yet?
    loc_chca_064_03 = "Onde vocês estarão conseguindo essa digital?",--Where are you on getting that handprint?
    loc_chca_065_01 = "Kang geralmente está observando o Casino pela sua sala de conferência. Vejam se ele está por lá.",--Kang is usually overlooking the casino from a meeting room. See if he's there.
    loc_chca_065_02 = "Pelo que sabemos, Kang geralmente fica perto do Casino.",--From what we know, Kang usually stays near the casino.
    loc_chca_065_03 = "Tem uma sala de conferência no Casino que Xun Kang fica por muito tempo.",--There's a conference room in the casino where Xun Kang spends a lot of time.
    loc_chca_066_01 = "Sabemos que Deng tem um cofre em sua sala de massagem privada. Sem dúvidas que é lá que ele deixa seu código pro cofre.",--We know Deng keeps a safe in his private massage room. No doubt that's where he keeps the code to the vault.
    loc_chca_066_02 = "Tem um cofre na câmara privada de Deng. Lá que ele deixa seu código.",--There's a safe in Deng's private massage chamber. That's where he keeps the vault code.
    loc_chca_066_03 = "O código pro cofre é mantido em um pequeno cofre na sala privada de massagem de Deng.",--The code to the vault is kept in a safe in Deng's private massage parlor.
    loc_chca_067_01 = "Vão na sala de massagem do Li Deng e encontrem seu cofre.",--Get to Li Deng's massage room and find his safe.
    loc_chca_067_02 = "Já localizaram aquele cofre?",--Have you found that safe yet?
    loc_chca_067_03 = "O cofre tá no lugar de massagem do Deng!",--The safe is in Deng's massage parlor!
    loc_chca_068_01 = "Sistema de segurança automática trancou a chave. Vocês vão precisar furá-lo.",--Automated security has locked out the key. You've got to drill it.
    loc_chca_068_02 = "Travas de segurança ativaram. Parece que vocês vão precisar furar.",--Security lockouts are in place. Looks like you'll have to drill it.
    loc_chca_068_03 = "A chave não funciona mais. A Segurança automática ativou. Quebrem com uma furadeira, amigos.",--The key no longer works. Automatic security is in place. Break out a drill, friends.
    loc_chca_069_01 = "Vão lá e furem aquele cofre, amigos.",--Get to drilling the safe, friends.
    loc_chca_069_02 = "Furem aquele cofre, rápido!",--Drill that safe, chop chop!
    loc_chca_069_03 = "Já colocaram a furadeira pra funcionar?",--Have you got the drill going yet?
    loc_chca_070_01 = "Boa! Agora vão até o cofre e abram-o!",--Grootste! Now get to that vault and open it up!
    loc_chca_070_02 = "Boa! Hora de abrir aquele cofre!",--Nice! Time to open that vault!
    loc_chca_070_03 = "Ai está! Agora, vamos abrir aquele cofre!",--There you go! Now, let's open that vault!
    loc_chca_071_01 = "Apressem-se, o cofre tá no Casino!",--Get moving, the vault is in the casino!
    loc_chca_071_02 = "O cofre está no coração do Casino.",--The vault is in the heart of the casino.
    loc_chca_071_03 = "Vão em direção ao cofre.",--Get to the vault.
    loc_chca_072_01 = "O Sistema de segurança desligou o acesso do cofre. Vocês precisam mudar isso. Deve ter um painel perto com controles que vocês podem hackear para entrar.",--The security system has shut down vault access. You need to override it. There should be a panel nearby with controls that you can hack to get inside.
    loc_chca_072_02 = "O acesso do cofre foi desligado. Vocês precisarão hackear o painel de controle para entrar. Deve estar por perto.",--Vault access has been disabled. You'll need to hack the control panel to get in. Should be nearby.
    loc_chca_072_03 = "Ah! Desligamento de segurança no cofre. Hackeiem o painel de controle para entrar. Está aqui em algum lugar.",--Ach! Security shutdown on the vault. Hack the control panel to get inside. It's around there somewhere.
    loc_chca_073_01 = "O painel deve estar em uma das paredes de trás.",--The panel has got to be on one of the back walls.
    loc_chca_073_02 = "Já olharam as paredes traseiras?",--Have you checked the back walls?
    loc_chca_073_03 = "Já acharam aquele painel de controle?",--Did you find that control panel yet?
    loc_chca_074_01 = "Ah! A Segurança eletrônica deles é forte. Tem um firewall separado instalado, provavelmente controlado por um computador crítico. Xun Kang tinha um computador na sala de conferência, vejam se é o que estamos procurando.",--Ach! Their cybersecurity is tight. There's a separate firewall installed, most likely controlled from a critical computer. Xun Kang had a laptop in the meeting room, see if that's the one we're looking for.
    loc_chca_074_02 = "Eles tem um firewall externo. Talvez vocês possam desligar ele no computador do Xun Kang na sala de conferência.",--They've got an external firewall. Maybe you can shut it down with Xun Kang's computer in the meeting room.
    loc_chca_074_03 = "Esses caras manjam de segurança, preciso dar os créditos a eles. Vocês precisam desligar o firewall externo. Está provavelmente controlado pelo computador de Kang na sala de conferência.",--These guys know their security, I'll give them that. You gotta disable the external firewall. It's likely controlled via Kang's computer in the conference room!
    loc_chca_075_01 = "Encontrem o Laptop do Kang!",--Get to finding Kang's laptop!
    loc_chca_075_02 = "Já acessaram o laptop do Kang?",--Have you accessed Kang's laptop yet?
    loc_chca_075_03 = "Como estão indo as coisas com o desligamento do firewall?",--Where are you on shutting down that firewall?
    loc_chca_076_01 = "É isso. O cofre deverá estar desprotegido para que vocês possam retomar o hack.",--That was it, nicely done. The vault should be unprotected so you can resume the hack.
    loc_chca_076_02 = "Boa, agora vocês podem voltar e tentar hackear denovo.",--Nice, you should be able to go back and try the hack again.
    loc_chca_076_03 = "Boa, Agora voltem e reiniciem o hack.",--Good, now get back and restart the hacking subroutine.
    loc_chca_077_01 = "Vão para o cofre e abram-o, rápido amigos!",--Get to the vault and open it, quickly friends!
    loc_chca_077_02 = "Abram o cofre, rápido!",--Open up the vault, chop chop!
    loc_chca_077_03 = "Vocês precisam abrir o cofre antes que toda a guarda costeira do Pacífico comam o rabo de vocês! ",--You need to open up the vault before the whole Pacific coast guard is on top of you!
    loc_chca_078_01 = "Usem a mão e o código para abrir o cofre!",--Use the hand and code to open up the vault!
    loc_chca_078_02 = "Vamos lá, amigos! Usem a mão protética do Kang para abrir o cofre!",--Come on, friends! Use Kang's prosthetic hand to open that vault!
    loc_chca_078_03 = "Já abriram o cofre?",--Have you got that vault open yet?
    loc_chca_079_01 = "Essa é a maneira certa de se fazer, com certeza! Agora vamos limpar essa grana dos idiotas. Joguem as malas no mar para que eu possa pegá-las o mais rápido possível!",--That's the way to do it, for sure! Now let's clean these kaks out of all their money. Toss the bags overboard and I'll have someone come and pick them up in a jiffy!
    loc_chca_079_02 = "Ceeeeeeerto, agora vamos sangrar eles até ficarem secos. Joguem as malas de dinheiro no oceano para que eu vá pegá-las!",--Riiiiiiight, now let's bleed these dwankies dry. Throw the money bags into the ocean and I'll have them picked up!
    loc_chca_079_03 = "Isso aí! Agora encham essas malas de dinheiro, joguem no mar e Jiu Feng vai pegá-las para nós.",--There you go! Now fill those money bags, throw them overboard and Jiu Feng will pick them up for us.
    loc_chca_080_01 = "Continuem andando idiotas. Esvaziem mais dinheiro. Queremos arruinar esses filhos da puta, yeah?",--Keep going you chops. Empty out more cash. We want to ruin these dwankies, yeah?
    loc_chca_080_02 = "Sem tempo para descansar, esvaziem aquele cofre!",--No time to rest, empty that vault!
    loc_chca_080_03 = "Peguem tudo o que puderem daquele cofre. Vamos deixar esses idiotas em ruinas, com certeza!",--Take everything you can out of that vault. We're going to run these keks to ruin, for sure!
    loc_chca_081_01 = "Se acharem que temos o suficiente, vamos mandar um grande dedo do meio para a Tríade. Coloquem fogo no resto quando estiverem prontos!",--If you think we've got enough, let's send the triad a big blerrie middle finger. Torch the rest of it if you're done!
    loc_chca_081_02 = "Quando sentirem que temos o suficiente, coloquem fogo no resto. Não queremos deixar nada para o Wang.",--When you feel like we've got enough, torch the rest. We don't want to leave anything for Wang.
    loc_chca_081_03 = "Queimem tudo que não querem levar com vocês, não precisam deixar nada para a Tríade usar.",--Burn whatever you don't want to take with you, no need to leave anything for the triad to use.
    loc_chca_082_01 = "Escolham logo, esvaziem o cofre ou coloquem fogo no que sobrou.",--Make up your minds, either empty the vault or set fire to what's left.
    loc_chca_082_02 = "Vamos amigos, peguem o resto ou queimem!",--Come on friends, take the rest or burn it!
    loc_chca_082_03 = "Vocês precisam decidir se vão querer queimar o resto ou pegar.",--You gotta decide if you want to burn the rest or take it.
    loc_chca_083_01 = "Alguns idiotas gostam de assistir dinheiro queimar, mas eu não. Mesmo assim, Yufu Wang vai ficar puto quando descobrir, e o Vlad vai amar!",--Some dwankies like watching money burn, but not me. Still, Yufu Wang is going to go bossies when he finds out, and Vlad will love it!
    loc_chca_083_02 = "Que pena que não pudemos pegar tudo, mas pelo menos desse jeito a Tríade não vai ter nada também.",--It's a shame we couldn't get it all, but at least this way the triad won't have it either.
    loc_chca_083_03 = "Não é todo dia que você pode queimar uma pilha de dinheiro assim tão grande em boa consciência, yeah?",--It's not every day you get to burn a pile of cash that big in good conscience, yeah?
    loc_chca_084_01 = "Isso vai envergonhar aquele tal de Wang pra sempre! Temos um pouco mais no banco e o Vlad vai ter sua vingança bem merecida.",--That's going to embarrass that Wang-dwankie to no end! We get a little more in the bank and Vlad gets some well-deserved payback.
    loc_chca_084_02 = "Isso vai levar o Golden Dagger para a ruina da maneira mais vergonhosa possível!",--This will push the Golden Dagger to the brink of ruin in the most embarrassing way possible!
    loc_chca_084_03 = "Não tem como os arrombados do Golden se recuperarem disso.",--There's no way the Golden Dwankies will recover from this.
    loc_chca_085_01 = "Agora que estão prontos, vão para o heliporto e sinalizem por seu transporte.",--Now that you're done, get to the helipad and signal your ride out.
    loc_chca_085_02 = "OK, vão para o heliporto e sinalizem para a fuga.",--OK, get to the helipad and signal for your ride.
    loc_chca_085_03 = "Hora de ir. Sinalizem pelo seu transporte no heliporto",--Time to leave. Signal your ride from the helipad.
    loc_chca_086_01 = "Encontrem um galão de combustível e usem para fazer um sinal no convés!",--Find a can of fuel and use it to make a signal fire on deck!
    loc_chca_086_02 = "Vejam se podem achar um galão de combustível ou algo para queimar.",--See if you can find a can of fuel or something to burn.
    loc_chca_086_03 = "Acendam fogo no convés, vejam se conseguem encontrar um galão de combustível.",--Light a fire on the deck, see if you can find a can of fuel.
    loc_chca_087_01 = "Ah! Vocês nunca vão sair com os bote salva vidas agora. São muito Lentos. Vão para o heliporto, vejam se conseguem achar combustível e acender um sinal. Eu tinha um helicóptero esperando caso isso acontecesse.",--Ach! You'll never get out in the lifeboats now. Too slow. Get up to the helipad, see if you can find some fuel and light a signal fire. I had a chopper on standby just in case.
    loc_chca_087_02 = "OK. Botes salva vidas estão fora de escolha. Eu tinha um helicóptero esperando, mesmo sendo mais arriscado. Mas vocês precisam sinalizar para ele com fogo.",--OK, lifeboats are off the table. I had a chopper waiting just in case, even though it's more risky. But you need to signal it with some fire.
    loc_chca_087_03 = "Esqueçam os botes. Eu tinha um helicóptero esperando caso isso acontecesse, mas vocês precisam acender um fogo para sinalizar.",--Forget the lifeboats. There's a helicopter standing by in case this happened, but you need to start a fire to signal for pickup.
    loc_chca_088_01 = "Aquele galão de combustível pode ser útil.",--That can of fuel might come in handy.
    loc_chca_088_02 = "Boa ideia, nunca sabemos quando isso poderá ser útil.",--Good call, never know when that might be useful.
    loc_chca_088_03 = "Combustível é sempre útil ter.",--Fuel is always useful to have around.
    loc_chca_089_01 = "Bem, eu acho que isso é uma maneira de mandar uma mensagem...",--Well, I suppose that's one way to send a message...
    loc_chca_089_02 = "Sem dúvidas sobre quem estava aqui, com certeza!",--No question about who was blerrie here, for sure!
    loc_chca_089_03 = "Um bom cartão de visitas como nenhum outro, eu acho.",--As good a calling card as anything, I suppose.
    loc_chca_090_01 = "Esperem amigos, só mais um pouco.",--Hang on friends, just a little longer.
    loc_chca_090_02 = "Só mais um pouco.",--Just a little longer.
    loc_chca_090_03 = "Quase lá. Vocês só precisam esperar um pouco mais.",--Almost there. You only need to hold out a short while longer.
    loc_chca_091_01 = "Entrem no helicóptero, amigos!",--Get into the chopper, friends!
    loc_chca_091_02 = "Ok seus idiotas, entrem no nosso passarinho!",--Ok you chops, get into that bird!
    loc_chca_091_03 = "Para o helicóptero!",--Into the helicopter!
    loc_chca_092_01 = "Eu assumo que estão prontos, yeah?",--I'm assuming you're done and ready, yeah?
    loc_chca_092_02 = "Estão esperando por algo?",--Are you waiting for something?
    loc_chca_092_03 = "Vocês precisam de algo daquele buffet? Hora de ir!",--Did you need something from the buffet? Time to go!
    loc_chca_093_01 = "Sabe, nada faz uma mensagem melhor do que arrancar um cofre de sua fundação, e ainda em um navio! ",--You know, nothing makes a statement like ripping a vault from its foundation, in a ship no less!
    loc_chca_093_02 = "É assim que a gente faz, yeah?",--That's how we do it, yeah?
    loc_chca_093_03 = "Não precisamos ser sutis quando estamos preparados pra boa luta.",--No need to be subtle when loud will do.
    loc_chca_094_01 = "Eu fiz o cara do Jiu Feng deixar uma surpresa de C4. Vamos usar para pegar o cofre inteiro pra nós. Vai ser bom, com certeza!",--I had Jiu Feng's guy leave you a C4 surprise. Let's use it to blow out the entire vault and take it with us. It'll be kif, for sure!
    loc_chca_094_02 = "Infiltrado do Feng deixou um presente para vocês! Um pouco de C4 para usar no cofre. Podemos estourar o negócio inteiro e pegar tudo pra nós!",--Feng's insider left you a little gift! Some nice C4 to use on the vault. We can blast the whole thing and take it!
    loc_chca_094_03 = "O barman deixou um pouco de C4. Vamos explodir o cofre e levar tudo conosco.",--The barman left us a C4 cocktail. Let's blow the vault and take it with us.
    loc_chca_095_01 = "Coloquem C4 em volta do cofre e libertem-o!",--Get some C4 around that vault and let's blow it free!
    loc_chca_095_02 = "Explodam aquele cofre com o C4!",--Blow the vault free with C4!
    loc_chca_095_03 = "Usem C4 naquele cofre e libertem-o, amigos!",--Use some C4 on that vault and blast it loose, friends!
    loc_chca_096_01 = "Agora cortem aqueles suportes e libertem o cofre.",--Now cut those beams to free the vault.
    loc_chca_096_02 = "Cortem os suportes para liberar o cofre.",--Cut the beams to loosen the vault.
    loc_chca_096_03 = "Cortar os suportes vai liberar o cofre.",--Cutting those beams will release the vault.
    loc_chca_097_01 = "Fiquem de olho nas serras, elas tão quebrando com mais frequência.",--Keep a close eye on those buzzsaws, they're been more prone to jamming than usual, lately.
    loc_chca_097_02 = "Tenham certeza que as serras continuam cortando.",--Make sure those saws keep cutting.
    loc_chca_097_03 = "Não deixem as serras pararem de funcionar.",--Don't let the saws stop working.
    loc_chca_098_01 = "Estou mandando um guincho. Quando for largado pelo helicóptero, peguem as partes e montem no pátio.",--I'm sending you a winch. When it drops from the helicopter, take the parts and assemble it in the courtyard.
    loc_chca_098_02 = "Tem um guincho a caminho. Quando chegar, montem no pátio.",--There's a winch on the way. As soon as it arrives, assemble it in the courtyard.
    loc_chca_098_03 = "Em alguns momentos vou fazer um guincho ser largado do helicóptero em partes. Juntem-as no pátio.",--In a few moments I'm having a winch dropped from the chopper in parts. Put it together in the courtyard.
    loc_chca_099_01 = "Coloquem o guincho no pátio!",--Put the winch together in the courtyard!
    loc_chca_099_02 = "Peguem o guincho e montem-o!",--Gather the winch and assemble it!
    loc_chca_099_03 = "Estão tendo problemas com o guincho?",--Are you having trouble with the winch?
    loc_chca_100_01 = "Coloquem o cabo no cofre. Mantenham a policia longe dele.",--Hook the cable up to the vault. Keep the kerels away from it.
    loc_chca_100_02 = "Peguem o cabo e coloquem no cofre.",--Take the cable and attach it to the vault.
    loc_chca_100_03 = "Se levarem o cabo até o cofre, podemos puxá-lo.",--If you take the cable and hook it up to the vault, we can pull it out.
    loc_chca_101_01 = "Mantenham os imbecis longe do guincho!",--Keep those domkoppers away from the winch!
    loc_chca_101_02 = "Não deixem a polícia interferir com o guincho!",--Don't let the kerels interfere with the winch!
    loc_chca_101_03 = "Protejam o guincho da policia!",--Protect the winch from the coppers!
    loc_chca_102_01 = "A guarda costeira está mandando suporte aéreo. Vocês têm que lidar com eles antes que possamos puxar o cofre.",--The coast guard is sending in air support. You've got to take care of them before we can pull out the vault.
    loc_chca_102_02 = "Mais problemas. A policia tá mandando suporte aéreo. Vocês precisam derrubar eles.",--More trouble. Kerels are sending air support. You gotta take them out.
    loc_chca_102_03 = "Droga! Vocês tem companhia, amigos. Lidem com esses helicópteros dos policiais!",--Blerrie! You got company, friends. Take care of those kerel choppers!
    loc_chca_103_01 = "Parece que a guarda costeira está mandando suporte de helicótero. Não dá pra arriscar pegar o cofre até vocês limparem o ar.",--Looks like the coast guard are sending in helicopter support. Can't risk taking the vault until you've cleared the air.
    loc_chca_103_02 = "Tem um helicóptero da polícia chegando. Vocês precisam lidar com ele.",--There's a police chopper incoming. You need to deal with it.
    loc_chca_103_03 = "Problema no ar, amigos. Helicóptero da Guarda Costeira. Derrubem-o.",--Trouble in the air, friends. Coast Guard helicopter. Take it out.
    loc_chca_104_01 = "Lidem com aquele suporte aéreo, amigos!",--Get rid of that air support, friends!
    loc_chca_104_02 = "Se livrem daquele suporte aéreo, rápido!",--Take out that air support, chop chop!
    loc_chca_104_03 = "Vocês precisam limpar o céu para fugir.",--You need clear sky to make your escape.
    loc_chca_104a_01 = "OK, eles se foram.",--OK, they're gone.
    loc_chca_104a_02 = "Boa, muito bem. Céu limpo.",--Good, well done. Sky is clear.
    loc_chca_104a_03 = "É isso, vocês tão limpos.",--That's it, you're clear.
    loc_chca_105_01 = "Não posso sinalizar o helicóptero sem que ele seja localizado pela guarda costeira. Coloquem um sinalizador para chamar ele para pegar o cofre!",--I can't radio our helicopter without it being located by the coast guard. Set up a flare to call it in and take the vault!
    loc_chca_105_02 = "Não dá para arriscar chamar o helicóptero com a polícia triangulando ele, vocês vão ter que chamar com um sinalizador.",--Can't risk calling in our chopper without the kerels triangulating it, so you'll have to call it in with a flare.
    loc_chca_105_03 = "Coloquem um sinalizador para chamar o helicóptero para pegar o cofre.",--Set up a flare to call in the chopper to pick up the vault.
    loc_chca_106_01 = "Acendam o sinalizador perto do guincho!",--Light the flare near the winch!
    loc_chca_106_02 = "Coloquem o sinalizador perto do guincho!",--Put the flare close to the winch!
    loc_chca_106_03 = "É melhor se vocês acenderem perto do guincho",--It's best if you light it up near the winch.
    loc_chca_107_01 = "Conectem o imã no cofre.",--Connect the magnet to the vault.
    loc_chca_107_02 = "Coloquem o imã no cofre.",--Set the magnet on the vault.
    loc_chca_107_03 = "Vocês vão precisar colocar o imã no cofre.",--You gotta put the magnet onto the vault.
    loc_chca_108_01 = "Vamo lá, conectem aquele imã!",--Come on, get that magnet attached!
    loc_chca_108_02 = "Conectem o imã!",--Attach the magnet!
    loc_chca_108_03 = "Tem algo errado? Porque o imã não tá conectado?",--Is there something wrong? Why isn't the magnet attached?
    loc_chca_109_01 = "O helicóptero não pode voltar para vocês então terão que arriscar usando os botes salva vidas. Vão até um e baixem ele. Estamos quase lá!",--The helicopter can't come back for you so you'll have to risk using a lifeboat. Get over to one and lower it. We're almost done!
    loc_chca_109_02 = "Sem combustível suficiente para o helicóptero voltar. Usem os botes!",--Not enough fuel in the chopper for a return trip. Use the lifeboats!
    loc_chca_109_03 = "Eu não posso mandar o helicóptero de volta, é muito arriscado. Os botes salva vidas devem adiantar, yeah?",--I can't send the chopper back again, it's too risky. The lifeboats will have to do, yeah?
    loc_chca_110_01 = "Vão para o bote salva vidas e abaixem-o para fugirem!",--Get to a life boat and lower it so that you can escape!
    loc_chca_110_02 = "Baixem o bote salva vidas e saiam daí!",--Lower a lifeboat and get out of there!
    loc_chca_110_03 = "Rápido idiotas! Entrem no bote salva vidas e saiam!",--Hurry you chops! Get in a lifeboat and leave!
    loc_chca_111_01 = "Agora subam à bordo!",--Now get onboard!
    loc_chca_111_02 = "À bordo, rápido!",--Onboard, hurry!
    loc_chca_111_03 = "Entrem, prometo que não vou afundar!",--Hop in, I promise you won't sink!
    loc_chca_112_01 = "Se acharam que estão prontos, façam sua fuga.",--If you feel done, make your escape.
    loc_chca_112_02 = "Se estiverem prontos, saiam dai.",--If you're ready, get out of there.
    loc_chca_112_03 = "Vocês tão prontos pra ir?",--You lot ready to go?
    loc_chca_113_01 = "Jiu Feng está esperando por perto com um barco para pegar vocês. Vão para a varanda perto das escadas e desçam a corda! Não atrasem, a guarda costeira vai mandar lanchas em breve!",--Jiu Feng is waiting nearby with a boat to come get you. Get to the balcony by the staircase and lower a rope ladder to climb down on! Don't dally, the coast guard will no doubt be sending dinghys soon!
    loc_chca_113_02 = "Feng está esperando para pegar vocês em seu barco. Desçam a corda na varanda das escadas.",--Feng is waiting to pick you up in his boat. Climb down a rope ladder from the balcony stairs.
    loc_chca_113_03 = "Eu tenho o Jiu Feng esperando por vocês em seu barco mas vocês vão ter que descer a escada de corda na varanda das escadas para subir à bordo!",--I've got Jiu Feng waiting for you in his boat but you'll have to climb down a rope ladder from the balcony stairs to get onboard!
    loc_chca_114_01 = "Se apressem e joguem aquela escada para vocês chegarem no barco do Jiu Feng.",--Hurry up and drop that ladder so you can climb down to Jiu Feng's boat.
    loc_chca_114_02 = "Joguem a escada e desçam para Feng! Ele tá esperando!",--Drop the ladder and climb down to Feng! He's waiting!
    loc_chca_114_03 = "Saiam daí, desçam a escada para o barco do Feng!",--Get out of there, climb down into Feng's boat!
    loc_chca_115_01 = "Vlad, você podia ter mencionado que o cara tinha uma mão protética!",--Vlad, you could've mentioned the guy had a prosthetic hand!
    loc_chca_115_02 = "Sabem, seria útil saber que o idiota tinha uma mão protética, yeah?",--You know, it would've been helpful to know the dwankie had a prosthetic hand, yeah?
    loc_chca_116_01 = "Aquele é Xun Kang! Ali, na sala de conferência.",--That's Xun Kang! There, in the conference room.
    loc_chca_116_02 = "Olhem, aquele deve ser aquele Kang idiota! Ele tá na sala de conferência!",--Look, that must be that dwankie Kang! He's in the conference room!
    loc_chca_117_01 = "Aquele é Xun Kang! Ali, na sala de conferêncis.",--That's Xun Kang! There, in the conference room.
    loc_chca_117_02 = "Olha, deve ser aquele Kang! Ele ta na sala de conferência!",--Look, that must be that dwankie Kang! He's in the conference room!
    loc_chca_118_01 = "Vlad, você poderia ter mencionado que o cara tinha uma mão protética!",--Vlad, you could've mentioned the guy had a prosthetic hand!
    loc_chca_118_02 = "Sabe, uma mão protética é o tipo de detalhe que seria bom saber quando estávamos planejando isso.",--You know, a prosthetic hand is the kind of detail that would have been good to know when we were planning this.
    loc_chca_119_01 = "Um pouco de combustível vai acender aquilo, yeah?",--Some fuel will light that up right and proper, yeah?
    loc_chca_119_02 = "Joguem um pouco de combustível nele e acendam!",--Throw some fuel on it and light it up!
    loc_chca_119_03 = "Um galão de gasolina definiria isso muito bem!",--A can of fuel would set that ablaze rather nicely!
    loc_chca_120_01 = "Acho que Xun Kang poderia abrir aquele cofre.",--I reckon Xun Kang could open that safe.
    loc_chca_120_02 = "Sem dúvidas Kang poderia abrir aquele cofre em um instante.",--No doubt Kang could open that safe in a jiffy.
    loc_chca_120_03 = "Talvez tenhamos que 'persuadir' Kang a abrir aquilo para nós.",--We might need to 'persuade' Kang to open that for us.
    loc_chca_121_01 = "Acho que o Xun Kang poderia abrir aquele cofre.",--I reckon Xun Kang could open that safe.
    loc_chca_121_02 = "Sem dúvidas Kang poderia abrir aquele cofre em um instante.",--No doubt Kang could open that safe in a jiffy.
    loc_chca_121_03 = "Talvez precisaremos 'persuadir' Kang a abrir aquilo para nós.",--We might need to 'persuade' Kang to open that for us.
    --loc_chca_brf_01 = "OK idiotas, hora de conseguir uma vingança para Vlad e fazer um bocado de dinheiro. O Black Cat vai estar em águas internacionais em algumas horas e vamos limpá-lo. Jiu Feng tem um infiltrado trabalhando como barman, e ele conseguiu nos ajudar com equipamentos e inteligência sobre as operações do navio. Sabemos que eles colocaram Xun Kang, o pedaço de bosta que torturou o Vlad, no navio porque a Tríade é extremamente vúnerável e ele é um de seus melhores. Também sabemos que o casino no barco é cuidado por um cara chamado Li Deng, que é aparentemente um pouco desleixadoe não é bem importante entre a Golden Dagger. Os dois provavelmente compartilham a segurança. Quando estiverem no navio, vocês vão ter que conduzir uma operação firme pois a guarda costeira está patrulhando a área e vão colocar polícia no barco antes que consigam falar "Olhe, a porra de um texuga nadando!" então não brinquem, tá?",--OK you chops, time to get some payback for Vlad and make a kakspul of cash doing it. The Black Cat will be in international waters in a few hours and we're going to clean it out. Jiu Feng has an insider working as a barman, and has arranged to help us with gear and intel on shipboard operations. We know that they have put Xun Kang, the piece of kak who tortured Vlad, on the ship because the triad is extra vulnerable and he's one of their best. We also know the casino onboard is being run by a dwankie named Li Deng, who is apparently a bit of a boisterous buffoon and not held in high regard within the Golden Dagger. Both of them likely share security clearance. Once you're on the ship, you will need to conduct a tight operation because the coast guard is patrolling the area and they'll have kerels onboard before you can say "Look, a blerrie swimming badger!", so no messing around, yeah?
    loc_chca_end_loud_01 = "Muito bem, seus idiotas! Yufu Wang e a Golden Dagger estão lamentando o dia que ouviram sobre a Gangue PAYDAY. Colocamos eles na borda da ruína, com certeza!",--Nicely done, you chops! Yufu Wang and the Golden Dagger are rueing the day they ever heard of the Payday Gang. We've put them on the edge of ruin, for sure!
    loc_chca_end_stealth_01 = "Bom trabalho, amigos. Essa foi boa. Os caras da Golden Dagger vão pensar duas vezes antes de causar mais problemas, com certeza!",--Well done, friends. That was a good one. Those Golden Dagger keks will think twice about causing us any more trouble, for sure!
    xuk_chca_08_01 = "Eu conheço você! Quantas vezes ja viajou conosco agora?",--I recognize you! How many times have you traveled with us now?
    xuk_chca_08_02 = "Você, e seu dinheiro, são sempre bem-vindos aqui.",--You, and your money, are always welcome here.
    xuk_chca_08_03 = "Ah, eu conheço vários rostos aqui, De volta para mais diversão!",--Ah, I know a lot of faces here, back again for more enjoyment!
    xuk_chca_08_04 = "Apostas no mar, não é uma das melhores coisas na vida?",--Is gambling at sea, not one of the best things in life?
    xuk_chca_08_05 = "Vocês estão todos aqui para uma boa viagem, cortesia do Sr. Wang.",-- You are all in for an enjoyable voyage, courtesy of Mr Wang.
    xuk_chca_09_01 = "Todo mundo já viu nosso lustre novo? Bem antigo. Comprei um especial de Hong Kong.",--Has everyone seen our new chandelier? An antique. I brought it in special from Hong Kong.
    xuk_chca_09_02 = "Vocês ocidentais entenderam errado em muitas maneiras. Gatos pretos trazem boa sorte, não o contrário!",--You westerners have it all wrong in so many things. Black cats are good luck, not bad!
    xuk_chca_10_01 = "Arrumem alguém para limpar essa bagunça.",--Get someone to clean up this mess.
    xuk_chca_10_02 = "Um belo dinheiro chegando hoje.",--Good money coming in today.
    xuk_chca_10_03 = "Alguém viu Wan Cheng?",--Has anyone seen Wan Cheng?
    xuk_chca_10_04 = "Cadê aquele idiota, Li Deng?",--Where is that idiot, Li Deng?
    xuk_chca_10_05 = "Se Li Deng vir me procurar, falem pra ele que não devo ser perturbado!",--If Li Deng comes looking for me, tell him I am not to be disturbed!
    xuk_chca_10_06 = "É hora de rodar os negócios.",--It's time to rotate the dealers.
    xuk_chca_10_07 = "Ouviu o que aconteceu com o conta-cartas que pegamos semana passada? Ele ficou tão envergonhado que se jogou no mar... tentou nadar para terra-firme!",--Did you hear what happened to the card-counter we caught last week? He was so ashamed that he threw himself overboard... tried to swim to the mainland!
    xuk_chca_11_01 = "Eu nunca devia ter saído de Hong Kong",--I should have never left Hong Kong.
    xuk_chca_11_02 = "Porque essas pessoas patéticas continuam me perguntando coisas?",--Why do these pathetic people keep asking me things?
    xuk_chca_11_03 = "Eu me pareço como a porra de um garçom?",--Do I look like a fucking waiter?
    xuk_chca_11_04 = "Sim... apostem tudo, como pequenos papagaios.",--Yes... gamble away, like little parrots.
    xuk_chca_12_01 = "Ei! O que tá acontecendo?",--Hey! What is going on?
    xuk_chca_12_02 = "Tragam alguém aqui pra consertar isso!",--Get someone out here to fix this!
    xuk_chca_12_03 = "É a Gangue PAYDAY! Atirem neles!",--It's the Payday gang! Shoot them!
    xuk_chca_12_04 = "Chamem mais guardas!",--Call more guards!
    xuk_chca_12_05 = "Vocês não vão sair desse navio vivos, palhaços!",--You will not get off this ship alive, clowns!
    yuw_chca_01_01 = "O que tá acontecendo? Xun Kang?!",--What's Going on? Xun Kang?!
    yuw_chca_02_01 = "Seus... fudidos! Eu vou jogar vocês em um container no fundo do oceano!",--You... Fuckers! I will drop you in a container at the bottom of the ocean!

    -- Objetivos [SÓ COLOCA PONTO FINAL NAS DESCRIÇÕES!!! OS "_hl" NÃO DEVEM TER PONTO FINAL!!!]
    hud_heist_chca01_hl = "Encontre-se com o Infiltrado",--Meet with the inside man
    hud_heist_chca01 = "Nosso infiltrado está esperando para dar algumas informações.",--Our inside man is waiting to give you some more info.
    hud_heist_chca02_hl = "Pegue seu Equipamento",--Get your equipment
    hud_heist_chca02 = "Nosso infiltrado deixou seu equipamento escondido em um dos banheiros.",--Our inside helper left your equipment hidden in one of the bathrooms.
    hud_heist_chca03_hl = "Pegue a Informação",--Fetch the insider info
    hud_heist_chca03 = "Nosso infiltrado deixou algumas informações para você.",--Our inside man left you some info.
    hud_heist_chca04_hl = "Encontre Xun Kang ou Li Deng",--Find Xun Kang or Li Deng
    hud_heist_chca04 = "Nossa informação diz que Xun Kang tem sua digital no cofre e Li Deng tem o código para abri-lo. Encontre eles!",--Our intel says that Xun Kang has his handprint on the vault reader and Li Deng has the code to open it. Find them!
    hud_heist_chca05_hl = "Encontre Xun Kang",--Find Xun Kang
    hud_heist_chca05 = "Encontre Xun Kang. Ele deve estar no Casino.",--Locate Xun Kang. He is supposed to be in the casino.
    hud_heist_chca06_hl = "Plante uma Escuta e Ouça a Conferência da Tríade",--Plant a bug and listen to the Triad meeting
    hud_heist_chca06 = "A conferência entre Xun Kang, Yufu Wang e Shayu com certeza nos traz informações importantes. Plante uma escuta e descubra.",--The meeting between Xun Kang, Yufu Wang and Shayu surely has some important info. Plant a bug and eavesdrop.
    hud_heist_chca07_hl = "Encontre o Número de Telefone do Xun Kang",--Find Xun Kang's private phone number
    hud_heist_chca07 = "Xun Kang deve ter seu número de telefone em algum lugar. Veja se consegue encontrá-lo.",--Xun Kang should have his private phone number laying around somewhere. See if you can find it.
    hud_heist_chca08_hl = "Pegue a Digital de Xun Kang",--Get Xun Kang's handprint
    hud_heist_chca08 = "Siga Xun Kang e pegue sua digital para abrir o cofre.",--Follow Xun Kang and get his handprint to help open the vault.
    hud_heist_chca09_hl = "Encontre o Cofre Pessoal de Li Deng",--Find Li Deng's private safe
    hud_heist_chca09 = "Encontre o cofre privado de Li Deng. Li Deng geralmente fica pelo Spa e seu cofre deve estar em algum lugar por perto.",--Locate Li Deng's private safe. Li Deng usually hangs around the spa and his safe is certainly somewhere close.
    hud_heist_chca10_hl = "Abra o Cofre e Pegue o Código do Cofre",--Open the safe and get the vault code
    hud_heist_chca10 = "Pegue o código do cofre do Li Deng. Coloque a furadeira no cofre do Li Deng ou use o cartão de acesso para uma tentativa furtiva. Li Deng deve ter um.",--Get the vault code from Li Deng's safe. Drill it open or use the key for a silent approach. Li Deng has it on him.
    hud_heist_chca11_hl = "Vá até o Cofre",--Get to the vault
    hud_heist_chca11 = "O cofre é acessado pelo Casino. Vá para lá.",--The vault is accessible from the casino. Go there.
    hud_heist_chca12_hl = "Hackeie os Caça-Níqueis para Distrair os Guardas",--Hack the slot machines to distract the guards
    hud_heist_chca12 = "Crie um pouco de caos com os caça-níqueis para distrair os gangsters da Tríade vigiando o cofre.",--Create a bit of chaos with the slot machines to distract the triad gangsters guarding the vault.
    hud_heist_chca13_hl = "Desabilite os Lasers",--Disable the lasers
    hud_heist_chca13 = "A entrada do cofre está limpa. Desligue os lasers agora.",--Vault entrance is clear. Disable the lasers now.
    hud_heist_chca14_hl = "Abra o Cofre",--Open the vault
    hud_heist_chca14 = "Use a digital e o código para abrir o cofre.",--Use the handprint mold and the code to open the vault.
    hud_heist_chca15_hl = "Assegure o Loot",--Secure the loot
    hud_heist_chca15 = "Assegure um pouco de dinheiro para você!",--Secure some cash for yourself!
    hud_heist_chca16_hl = "Assegure o resto do Dinheiro ou Deixe-o Inutilizável",--Secure the rest of the cash or render it unusable
    hud_heist_chca16 = "Esvazie o cofre: Pegue o dinheiro restante ou deixe-o inutilizável.",--Empty the vault: take the remaining cash or render it useless.
    hud_heist_chca17_hl = "Abaixe um dos Bote Salva Vidas",--Lower one of the lifeboats
    hud_heist_chca17 = "Pegue um dos bote salva vidas emprestado e fuja.",--Borrow one of the lifeboats and take your leave.
    hud_heist_chca18_hl = "Fuga Disponível",--Escape available
    hud_heist_chca18 = "O trabalho acabou. Fuja ou pegue mais loot.",--The job is done. Escape or take more loot.
    hud_heist_chca19_hl = "Pegue o Equipamento Escondido",--Get the hidden equipment
    hud_heist_chca19 = "Nosso infiltrado deixou algumas coisas úteis para você.",--Our inside man left you some useful gear.
    hud_heist_chca20_hl = "Quebre o vidro da sala de Conferência",--Break the conference room glass
    hud_heist_chca20 = "Quebre a janela da sala de conferência para chegar em Xun Kang.",--Break the conference room window to be able to reach Xun Kang.
    hud_heist_chca21_hl = "Queime o cabo para quebrar o vidro",--Burn the cable to smash the glass
    hud_heist_chca21 = "O vidro é à prova de balas. Use o Térmite para queimar o cabo segurando o candelabro para ele balançar e esmagar o vidro!",--The glass is bulletproof. Use the thermite to burn the cable holding the chandelier so it swings and crushes the window!
    hud_heist_chca22_hl = "Pegue a Digital de Xun Kang",--Get Xun Kang's handprint
    hud_heist_chca22 = "Entre na sala de conferência e use o silicone para pegar a digital.",--Get inside the meeting room and use the silicone to take his handprint mold.
    hud_heist_chca23_hl = "Fure o Cofre e Pegue o Código do Cofre",--Drill the safe and get the vault code
    hud_heist_chca23 = "O sistema de segurança trancou o mecanismo da chave. Fure-o com a Furadeira!",--The security system locked the key mechanism. Drill it open!
    hud_heist_chca24_hl = "Reverta o Confinamento do Cofre",--Override the vault lockdown
    hud_heist_chca24 = "O sistema de segurança está prevenindo o cofre de abrir. Reinicie-o!",--The security system is preventing the vault from opening. Reboot it!
    hud_heist_chca25_hl = "Encontre o Laptop e Desligue o Firewall",--Find the laptop and disable the firewall
    hud_heist_chca25 = "Um firewall externo está bloqueando o hack. O laptop de Xun Kang controla ele. Encontre o laptop e desligue o firewall.",--An external firewall is blocking the hack. Xun Kang's laptop controls it. Find the laptop and disable the firewall.
    hud_heist_chca26_hl = "Sinalize para o Helicóptero de Fuga",--Signal the escape helicopter
    hud_heist_chca26 = "Encontre uma maneira de sinalizar para o helicópetro de fuga.",--Find a way to signal the escape helicopter.
    hud_heist_chca27_hl = "Espere pela Extração",--Wait for extraction
    hud_heist_chca27 = "Bile viu a mensagem e está a caminho. Aguente firme!",--Bile saw the message and he's on his way. Hang on!
    hud_heist_chca28_hl = "Fuga Disponível",--Escape available
    hud_heist_chca28 = "O trabalho acabou. Fuja pelo helicóptero.",--The job is done. Escape in the helicopter.
    hud_heist_chca29_hl = "Exploda a Parede do Cofre",--Blow the vault walls
    hud_heist_chca29 = "Use o C4 para criar um buraco na parede do cofre.",--Use C4 to blow a hole in the vault wall.
    hud_heist_chca30_hl = "Corte os Suportes",--Cut the beams
    hud_heist_chca30 = "Use as serras para cortar os suportes que seguram o cofre no navio",--Use saws to cut the beams that attach the vault to the ship.
    hud_heist_chca31_hl = "Espere pelo Guincho e Monte-o no lado de fora",--Wait for the winch and assemble it outside
    hud_heist_chca31 = "Bile vai largar o guincho para você. Espere por ele e monte-o.",--Bile is going to drop the winch for you. Wait for it and then assemble it.
    hud_heist_chca32_hl = "Conecte o Cabo no Cofre e Puxe-o para o Aberto",--Attach the cable to the vault and pull it out in the open
    hud_heist_chca32 = "Use o guincho para puxar o cofre para o lado de fora.",--Use the winch to pull the vault outside.
    hud_heist_chca33_hl = "Livre-se do Helicóptero da Polícia",--Get rid of the police helicopter
    hud_heist_chca33 = "Os policiais chamaram suporte aéreo. Bile não pode chegar perto do barco enquanto aquele helicóptero com torreta estiver em volta.",--The cops have called for air support. Bile can't get near the boat while that turret-carrying helicopter is around.
    hud_heist_chca34_hl = "Livre-se dos Helicópteros da Polícia",--Get rid of the police helicopters
    hud_heist_chca34 = "Os policiais chamaram helicópteros de reforço. Bile não pode chegar perto do barco enquanto eles estiverem em volta.",--The cops have called helicopter reinforcements. Bile can't get near the boat while they are around.
    hud_heist_chca35_hl = "Acenda o Sinalizador e espere pelo Helicóptero",--Light the flare and wait for the helicopter
    hud_heist_chca35 = "Sinalize para o Bile e ele irá pegar o cofre.",--Signal Bile and he'll come to pick up the vault.
    hud_heist_chca36_hl = "Assegure o Cofre",--Secure the vault
    hud_heist_chca36 = "Conecte o imã no cofre e deixe o Bile levá-lo.",--Connect the magnet to the vault and let Bile take it away.
    hud_heist_chca37_hl = "Espere por Jiu Feng e Desenrole a Escada de Corda",--Wait for Jiu Feng and unroll the rope ladder
    hud_heist_chca37 = "Use a escada de corda para fugir quando o Jiu Feng chegar.",--Use a rope ladder to escape when Jiu Feng comes.
    hud_heist_chca38_hl = "Fuga Disponível",--Escape available
    hud_heist_chca38 = "A fuga está disponível, opcionalmente, assegure mais loot.",--Escape is available, optionally, secure more loot.

--[[hud_heist_chca39_hl = "ERROR: hud_heist_chca39_hl",
hud_heist_chca39 = "ERROR: hud_heist_chca39",

hud_heist_chca40_hl = "ERROR: hud_heist_chca40_hl",
hud_heist_chca40 = "ERROR: hud_heist_chca40",

hud_heist_chca41_hl = "ERROR: hud_heist_chca41_hl",
hud_heist_chca41 = "ERROR: hud_heist_chca41",

hud_heist_chca42_hl = "ERROR: hud_heist_chca42_hl",
hud_heist_chca42 = "ERROR: hud_heist_chca42",

hud_heist_chca43_hl = "ERROR: hud_heist_chca43_hl",
hud_heist_chca43 = "ERROR: hud_heist_chca43",

hud_heist_chca44_hl = "ERROR: hud_heist_chca44_hl",
hud_heist_chca44 = "ERROR: hud_heist_chca44",

hud_heist_chca45_hl = "ERROR: hud_heist_chca45_hl",
hud_heist_chca45 = "ERROR: hud_heist_chca45",

hud_heist_chca46_hl = "ERROR: hud_heist_chca46_hl",
hud_heist_chca46 = "ERROR: hud_heist_chca46",]]
}