return {
	-- Nomes e Descrições
	--heist_peta = "Goat Simulator",--Goat Simulator
	--heist_peta2 = "Goat Simulator",--Goat Simulator
	heist_peta_crimenet = "A morte do Hector deixou um vácuo no tráfico de cocaína. A natureza abomina o vácuo. Abomina pra caralho! Tem uns fudidos vindo de todos os lugares. Um monte de Hondurenhos estão tentando se espalhar. Vamos bater neles antes deles se espalharem ainda mais. Quebrem o seu círculo de tráfico. Roubem os seus produtos. O que pode dar errado?$NL;$NL;» Encontre as Cabras$NL;» Obtenha as Cabras$NL;» Fuja",--Hector's death left a vacuum in the powder trade. Nature abhors a vacuum. Fucking abhors it! There's muck-fuckers crawling in from everywhere. Bunch of Hondurans are trying to spread. Let's hit them before they can take root. Break up their smuggling ring. Steal their product. What can go wrong?$NL;$NL;» Locate the goats$NL;» Secure the goats$NL;» Escape
	--heist_peta_hl = "This was not the deal",--This was not the deal
	heist_peta_briefing = "Essa facção de Hondurenhos tem um caminhão movendo seus produtos por Downtown. Vlad arrumou uma maneira de pará-los. Nós vamos limpar. Vamos entrar depois, tenham certeza de que o produto vai sair. Botas no chão, sabe?",--This Honduran cartel has a truck moving its product through Downtown. Vlad has arranged to have it hit. We're on clean-up. We go in afterwards, make sure the product gets out. Boots on the ground, you know? 
	--heist_peta2_hl = "Dirty work",--Dirty work
	heist_peta2_briefing = "Ok, eu acho que o pior já ficou pra trás. O motorista do Vlad levou as Cabras para fora da cidade, pronto para fazer a extração do produto. Fiquem por ali. Vigiem o perímetro. Trabalho fácil, certo?",--Okay, I think the worst is behind us. Vlad's driver got the goats to a farm outside the city, ready to perform the extraction of the packages. Stick around. Watch the perimeter. Easy work, right?
	
	-- Legendas (Vlad - Dia 1)
	vld_pt1_intro_01 = "Tudo bem, hora de... honestidade. A Cocaína está em... Cabras. Sim, Cabras. E elas fugiram. Haha, Cabras complicadas, né?! Encontrem elas!",--Okay, time for...honesty. The coke is packed in...goats. Yes, goats. And they've escaped. Haha, tricky goats, huh?! Find them!
	vld_pt1_intro_02 = 'É, meus amigos. Então, os "burros", sabe... bem, eles são na realidade Cabras. E elas... ééé, fugiram. Encontrem elas para mim.',--Ah, my friends. So, the "mules", you see...well, they're actually goats. And they've..errr, escaped. Find them for me.
	vld_pt1_intro_03 = "Ahhh, ouçam. A Cocaína está sendo traficada em Cabras. Sim, Cabras. C. A. B. R. A. S. E elas fugiram. Encontrem todas elas.",--Ahhh, listen. The coke is being smuggled in goats. Yes, goats. G. O. T's. And they've escaped. Find them all.
	vld_pt1_05_03 = "E não se mexam. Cabras do caralho...",--And don't fucking move. Fucking goat prick...
	vld_pt1_05_07 = "Continuem trazendo Cabras!",--Keep bringing goats!
	vld_pt1_05_01 = "Sim! Venham aqui, seus merdinhas cabeludos!",--Yes! Get in there, you hairy little bastard!
	vld_pt1_03_03 = "Eu tenho um homem a caminho. Boris?",--I have a man on the way for you. Boris?
	vld_pt1_05_20 = "Sim! Boa! Cabras!!",--Yes! Good! Goats!!
	vld_pt1_05_16 = "Sem mais corridinhas para você, menininho.",--No more runny-run for you, goat-boy.
	vld_pt1_05_14 = "Não se mexa. Ou eu vou lentamente te assar.",--Don't move. Or I'll slow-fucking-roast you.
	vld_pt1_05_13 = "Não pense em fugir denovo, ou é Panela para você!",--Don't think about running again, or it's the stewpot for you!
	vld_pt1_07_03 = "Ótimo trabalho, amigos, mas vocês estão apenas na metade. Sigam o Boris. Ele vai guiar vocês até a fazenda fora da cidade, onde ele pode... sabe... extrair a Cocaína. Protejam ele.",--Nice job, friends, but you're only halfway there. Follow Boris. He'll lead you to a farm outside the city, where he can..you know...extract the coke. Protect him.
	vld_pt1_05_11 = "Não corra denovo, cabrinha.",--Don't run away again, little goat.
	vld_pt1_cnc_02 = "Uns fudidos estão tentando fazer um tráfico de Cocaína em DC. Peguem os produtos deles. Quebrem-os. Só um pequeno detalhe...",--Some fucks are trying to develop a coke operation in DC. Get their product. Break it up. Just one small detail...
	vld_pt1_05_19 = "Sua aventura acabou, sua Cabra fudida.",--Your adventure is over, you goat-fuck.
	vld_pt1_05_10 = "Fiquem ai, ou é Açougue para vocês.",--Stay there, or it's the halal butcher for you.
	vld_pt1_01_02 = "Ouçam as Cabras. Elas vão estar fazendo... sons de Cabra.",--Listen out for the goats. They'll be making...goat noises.
	vld_pt1_05_06 = "Outra. Boa!",--Another one. Good!
	vld_pt1_07_01 = "Boa. Ótimo! Agora, o Boris vai guiar vocês até uma fazenda fora da cidade. Lá ele pode... extrair a Cocaína.",--Nice. Good! Now, Boris is going to lead you to a farm outside the city. There he can...extract the coke. 
	vld_pt1_01_01 = "Mantenham seus olhos abertos, mas principalmente seus ouvidos.",--Keep your eyes open, yes, but especially your ears. 
	vld_pt1_01_03 = "Continuem escutando. Escutem por...",--Keep listening. Listen for...
	vld_pt1_02_01 = 'Só... "sons" de Cabra! Berrando. Bem, vocês não iriam com toneladas de Cocaína enfiadas na bunda de vocês?',--Just....goat "noises"! Screaming. Well, wouldn't you with 5lbs of coke up your ass?
	vld_pt1_02_02 = "Não é o Senhor David Attenborough! Ou Igor o Croata, Só... sons de Cabra.",--I ain't Sir David Attenborough! Or Igor the Croat. Just....goat noises!
	vld_pt1_02_03 = "Seja qual barulho você esperar de um animal de fazenda com uma bolsa de cocaína enterrada em seu cano de merda.",--Whatever noise you expect from a farm animal with a bag of coke buried in it's shitpipe.
	vld_pt1_03_01 = "Boris, o meu motorista, virá buscar vocês.",--Boris, my driver, will come and pick you guys up.
	vld_pt1_03_02 = "Boris está a caminho. Não é, Boris?",--Boris is on his way. Isn't that right, Boris?
	vld_pt1_04_01 = "Parece que tem uma Cabra naquele Apartamento. Subam lá!",--Looks like one of the goats is up in that apartment. Get up there!
	vld_pt1_04_02 = "Uma Cabra entrou no Apartamento ali. Atrás dela! Procurem por uma entrada.",--A goat got into an apartment up there. Get after it! Look for a way in.
	vld_pt1_04_03 = 'Alguém tentou pegar uma Cabra. Fazer dela um animal de estimação, né? Igual o Igor o Sérvio e seus animaizinhos "especiais". Entrem naquele Apartamento e resgatem ela.',--Someone tried to take a goat. Make special pet, yeah? Like Igor the Serb and his "special" pets. "Special". Get into that apartment and rescue it.
	vld_pt1_05_02 = "E fique aí, seu merdinha!",--And stay there, you little shit!
	vld_pt1_05_04 = "E fique... sua masca-grama, chifruda, olhuda, FILHA DA PUTA!",--And stay...you grass-chewin', horn-growin', freaky-eyed MOTHERFUCKER!
	vld_pt1_05_05 = "Mexa-se e é Igor para você, cuzona.",--You move and it is Igor time for you, asshole.
	vld_pt1_05_08 = "Continuem com o bagulho de pegar Cabra!",--Keep on with the goat catching thing!
	vld_pt1_05_09 = "Fique! Em pé!",--Stay! Heel! 
	vld_pt1_05_12 = "Outra Cabra presa.",--Another goat secured.
	vld_pt1_05_15 = 'Mexa-se denovo, e estará na cama do Igor antes que você consiga dizer "Fudeu".',--You move, and you'll be in Igors bed before you can say "oh shit".
	vld_pt1_05_17 = "Entra aí, sua feia fudida.",--Get in there, ya ugly little fuck!
	vld_pt1_05_18 = "Sem mais aventuras para você, amiguinha.",--No more adventures for you, little friend.
	vld_pt1_06_01 = "Um negócio de verdade, né?",--A real bargain, yes?
	vld_pt1_06_02 = "Encontrei a merdinha complicada.",--Found the tricksy little shit!
	vld_pt1_06_03 = "Aí está você, sua fudidinha!",--There you are, you little fucker!
	vld_pt1_07_02 = "Eu tenho uma linda fazendinha fora da cidade. Boris vai guiar vocês até lá. Ele pode remover os pacotes de Cocaína.",--I have a pleasant little farm outside the city. Boris will lead you there. He can remove those packets of coke. 
	vld_pt1_cbf_01 = "A morte de Hector deixou um vácuo no tráfico de Cocaína. A natureza abomina o vácuo. Abomina pra caralho! Tem uns fudidos vindo de todos os lugares. Um monte de Hondurenhos estão tentando se espalhar. Vamos bater neles antes deles poderem se espalhar mais. Quebrem o seu círculo de tráfico. Roubem seus produtos. O que pode dar errado?",--Hector's death left a vacuum in the powder trade. Nature abhors a vacuum. Fucking abhors it! There's muck-fuckers crawling in from everywhere. Bunch of Hondurans are trying to spread. Let's hit them before they can take root. Break up their smuggling ring. Steal their product. What can go wrong?
	vld_pt1_cnc_01 = "Eu preciso que vocês quebrem uma operação de tráfico. Peguem a Cocaína. Tem só uma pequena complicação...",--I need you to break up a smuggling operation. Get the coke. There's just one small complication....
	vld_pt1_cnc_03 = "Uma facção de Hondurenhos está tentando se estabelecer em DC. Usando burros. Exceto que não são burros. Vocês verão...",--A Honduran cartel are trying to set up in DC. Using mules. Except not mules. You'll see....
	
	-- Legendas (Bain - Dia 1)
	pln_pt1_05_02 = "Levem as Cabras até o carro. Só não deixem elas cagarem no estofado.",--Haul the goats in the car. Just don't let 'em crap on the upholstery.
	pln_pt1_22_03 = "Aquela loja parece um bom lugar para procurar. Arrombem a porta, gangue!",--That store looks like a good spot to search. Drill the door, gang!
	pln_pt1_28_02 = "Um polícial está tentando mover uma Cabra pra longe.",--Cop is trying to move a goat out of the AO.
	pln_pt1_01_01 = "Okay. Bem, vocês ouviram ele. O produto está DENTRO das Cabras, e as Cabras estão por toda Downtown. Amarrem elas.",--Okay. Well, you heard the man. The product is IN the goats, and the goats are all over Downtown. Round 'em up.
	pln_pt1_15_02 = "Isso não funcionou. Tentem um diferente.",--That didn't do it. Try a different one.
	pln_pt1_16_01 = "A energia caiu! Peguem a Cabra!",--Power's down! Get that goat!
	pln_pt1_02_01 = "Bem, como é o barulho de uma Cabra?",--Well, what does a goat sound like?
	pln_pt1_19_02 = "Ainda tem uma Cabra no andaime.",--There's still a goat in the scaffold.
	pln_pt1_27_01 = "O poste caiu. Peguem a Cabra!",--Streetlight is down. Grab the goat!
	pln_pt1_03_03 = "Essas são todas. Entrem no carro e vazem!",--That's all of them. Get in the car and scoot!
	pln_pt1_12_02 = "A caixa de energia está provavelmente do lado de fora. Hackeando ela deve parar o ventilador.",--Circuit box is likely outside. Hacking it will stop the fan.
	pln_pt1_23_01 = "Tenho quase certeza que vai ter uma Cabra dentro da loja. Coloquem uma furadeira na porta!",--Pretty sure there will be a goat inside the store. Get a drill on the door!
	pln_pt1_02_02 = "Que barulho que uma Cabra faz?",--What noise does a goat make?
	pln_pt1_08_03 = "Encontrem as válvulas. Precisamos fazer os sprinklers funcionarem.",--Find those valves. We need the sprinklers working.
	pln_pt1_08_01 = "Ali está uma válvula que controla os sprinklers, liguem ela!",--There's valves that control the sprinklers, turn them on!
	pln_pt1_21_02 = "A escada está eletrificada. Desliquem a energia!",--Ladder's electrified. Disable it at the power box!
	pln_pt1_26_01 = "Pessoal, tem uma Cabra presa no poste! Serrem ele.",--Guys, there's a goat stuck in the streetlight! Saw it down.
	pln_pt1_06_03 = "Ainda tem uma Cabra no Apartamento ali.",--There's still a goat in the apartment building there.
	pln_pt1_07_01 = "O Apartamento tem um sistema de sprinklers. Deve ter uma válvula em algum lugar.",--The apartment has a sprinkler system, so there's got to be a valve somewhere.
	pln_pt1_13_03 = "Essa Cabra tem uma corrente viva nela! Desliguem a energia!",--That goat has live current running through it! Disable the power!
	pln_pt1_26_02 = "Não esqueçam a Cabra no poste. Serrem o poste para derrubá-la.",--Don't forget the goat in the streetlight. Saw it to bring him down.
	pln_pt1_27_03 = "Certo! O poste é história. Peguem a Cabra",--All right! Streetlight is history. Grab the goat!
	pln_pt1_15_01 = "Não, foi o errado. Tentem outro.",--Nope, wrong one. Try another.
	pln_pt1_21_01 = "Não toquem na escada! Desliguem a energia!",--Don't touch the ladder! Disable the powerboxes!
	pln_pt1_01_03 = "Vlad, seu louco... Okay, pessoal. Esse é o negócio. As vezes são Ogivas, as vezes são Cabras. Comecem a procurar.",--Vlad, you crazy...okay, guys. That's the deal. Sometimes it's nukes, sometimes it's goats. Get looking.
	pln_pt1_17_06 = "Como ela subiu ali é um mistério.",--How it got up there is a mystery.
	pln_pt1_17_01 = "Como que...?",--How did it even...?
	pln_pt1_12_01 = "Hackeiem a caixa de energia, isso vai parar o ventilador.",--Hacking the circuit box will stop the fan.
	pln_pt1_24_03 = "Entramos. Agora peguem a Cabra!",--We're in. Now get after that goat!
	pln_pt1_25_03 = "Coloquem uma serra naquele poste. É o único jeito de fazer essa Cabra descer.",--Get a saw on that streetlight. It's the only way to bring the goat down.
	pln_pt1_12_03 = "Encontrem a caixa de energia, gangue. Vocês precisam hackear pra parar o ventilador",--Find the circuit box, crew. You need to hack it to halt the fan.
	pln_pt1_17_04 = "Tá, mas como que ela...?",--Okay, but how did it....?
	pln_pt1_23_03 = "Não esqueçam da loja. Furem a porta. Eu aposto minha parte que tem uma Cabra lá dentro.",--Don't forget the store. Drill the door. I bet my cut there's a goat inside.
	pln_pt1_01_02 = "Bem, como o Vlad falou... a Cocaína está nas Cabras, e as Cabras estão... bem, por toda Downtown. Encontrem elas.",--Well, as Vlad said...the coke is in the goats, and the goats are...well, all over Downtown. Track 'em down.
	pln_pt1_02_03 = "Que tipo de barulho?",--What sort of noise?
	pln_pt1_03_01 = "Isso devem ser todas! Hora de cair fora. Subam no carro e vamos dar o fora daqui.",--That should be all of them! Time to ride out. Get in the wheels and get out of there. 
	pln_pt1_03_02 = "Essas são todas as Cabras. Agora peguem o carro e desapareçam daí.",--That's all the goats secured. Now get in your car and high tail it out of there.
	pln_pt1_04_01 = "Gangue, é hora de vazar. Entrem no carro!",--Gang, it's time to bug. Get in the car!
	pln_pt1_04_02 = "Grupo, vocês pegaram as Cabras, agora pisem no volante!",--Crew, you got the goats, now hit the gas!
	pln_pt1_04_03 = "O Trabalho está pronto, pessoal. Hora de vazar! Para o carro!",--Job's done here, guys. Time to roll! Into the car!
	pln_pt1_05_01 = "Vocês vão acabar isso mais rápido se usarem o carro para mover essas Cabras.",--You'll close this out quicker if you use the car to move the goats.
	pln_pt1_05_03 = "Vocês precisam pegar essas Cabras mais rápido. Usem o carro!",--Gotta get them goats back quickly. Use the car!
	pln_pt1_06_01 = "Gangue, não esqueçam que uma Cabra está no Apartamento.",--Gang, don't forget one of those goats is up in the apartment.
	pln_pt1_06_02 = "Não esqueçam da Cabra no Apartamento.",--Don't forget the goat in that apartment block. 
	pln_pt1_07_02 = "Todos esses Apartamentos possuem sistemas de sprinklers, Só procurem pela válvula.",--All these apartments have sprinkler systems. Just look for the valve.
	pln_pt1_07_03 = "Esses lugares são obrigados a terem sistemas de sprinklers. Encontrem a válvula.",--These places are required to have sprinkler systems. Find the valve!
	pln_pt1_08_02 = "Procurem as válvulas. Liguem os sprinklers!",--Look for the valves. Get the sprinklers going!
	pln_pt1_09_01 = "Ótimo, esses sprinklers vão apagar o fogo.",--Great, those sprinklers will put out the fire.
	pln_pt1_09_02 = "Que faça chover!",--Let it rain!
	pln_pt1_09_03 = "Ótimo. Está funcionando!",--Great. It's working! 
	pln_pt1_10_01 = "Excepcional! O fogo está morrendo.",--Outstanding! Fire's dying down.
	pln_pt1_10_02 = "O Fogo se apagou. E as pessoas ainda acham que tudo o que fazemos é causar o caos.",--Fire's out. And people think all we do is cause chaos!
	pln_pt1_10_03 = "Lidamos com o fogo. Vocês são heróis civis!",--That's the fire dealt with. You guys are civil heroes!
	pln_pt1_11_01 = "Como uma Cabra subiu ali? Tanto faz... procurem pela caixa de energia para parar o ventilador.",--How did the goat get up there? Whatever...look for the circuit box to stop the fan.
	pln_pt1_11_02 = "Uma Cabra no ventilador? Esse dia está ficando cada vez mais estranho. Encontrem a caixa de energia para parar o ventilador.",--A goat in a fan? This day gets weirder. Find the circuit box to halt the fan.
	pln_pt1_11_03 = "Com certeza deve ter um bom motivo para aquela Cabra estar nesse ventilador. Só encontrem a caixa de energia. Parem o ventilador.",--Sure there's gotta be a good reason that goat is up in the fan. Just find the circuit box. Stop the fan.
	pln_pt1_13_01 = "Aquela Cabra está carregando uma carga viva. Desliguem a energia.",--That goat is carrying a live charge. Disable the power.
	pln_pt1_13_02 = "Cabras são boas condutoras de eletricidade. Desliguem a energia.",--Goats are great conductors of electricity. Turn off the power.
	pln_pt1_14_01 = "Cuidado com a Cabra! Pessoal, vocês precisam desligar a energia primeiro!",--Beware the goat! Guys, you need to disable the power first!
	pln_pt1_14_02 = "A Cabra é mortal! Matem a eletricidade primeiro!",--The goat is deadly! Kill the electricity first!
	pln_pt1_14_03 = "A Cabra está eletrificada! Desliguem a energia!",--The goat is electrictrified! Turn off the power!
	pln_pt1_15_03 = "Uhhh... não, isso não funcionou. Tentem outro.",--Uhhh...no, that didn't work. Try another one.
	pln_pt1_16_02 = "Ótimo. Vocês podem pegar a Cabra com segurança agora!",--Great. You can safely grab the goat now!
	pln_pt1_16_03 = "Tudo certo, ótimo. Agora peguem a Cabra!",--All right, nice. Now fetch the goat!
	pln_pt1_17_02 = "Eu não consigo descobrir como ela...",--I can't work out how it...
	pln_pt1_17_03 = "O que ela estava fazendo ali em cima...?",--What was it doing up...?
	pln_pt1_17_05 = "Ainda não consigo descobrir como.",--I still can't figure out how.
	pln_pt1_18_01 = "Ali tem outra! Presa no andaime! Cuidado! Parece que está eletrocutado! Desliguem a energia!",--There's another one! Caught in the scaffolding! Watch out! Looks like it's electrocuted! Disable the power!
	pln_pt1_18_02 = "Gangue, conseguem ver? Outra Cabra no andaime! Mas - esperem, tenham cuidado! Parece que a escada está eletrocutada.",--Gang, you see it? Another goat in the scaffolds! But - woah, be careful! Looks like that ladder is electrocuted!
	pln_pt1_18_03 = "Olhem para cima, no andaime! Outra Cabra. Mas, esperem! Parece que a escada está eletrocutada. Desliguem a energia.",--Look, up in the scaffold! Another goat. But, hold up! It looks like that ladder is electrocuted. Disable power!
	pln_pt1_19_01 = "Não se esqueçam da Cabra no andaime.",--Don't forget the goat in the scaffold.
	pln_pt1_19_03 = "Lembrem-se - Tem uma Cabra presa no andaime.",--Remember - there's a goat stuck in the scaffolds.
	pln_pt1_20_01 = "Parece que uma Cabra conseguiu se prender nos cabos de energia. A escada está eletrocutada. Desliguem a energia!",--Looks like the goat managed to nibble through the power. Ladder's electrocuted. Disable the power!
	pln_pt1_20_02 = "Aquela Cabra é problemática. Ela de algum jeito ligou a energia. Desliguem-na na caixa de energia.",--That goat's a trouble maker. He somehow turned on the power. Disable it at the power box.
	pln_pt1_20_03 = "A Cabra conseguiu eletrificar a escada. Procurem por uma caixa de energia para desligá-la.",--The goat managed to electrify the ladder. Look for the power box to turn it off.
	pln_pt1_21_03 = "Vocês precisam lidar com a energia para usar a escada!",--You need to deal with the power box to use the ladder!
	pln_pt1_22_01 = "Olhem dentro daquela loja. Uma das Cabras provavelmente foi por ali. Furem a porta!",--Check inside that store. Likely one of our goats wandered in. Drill it open!
	pln_pt1_22_02 = "Aparentemente uma Cabra conseguiu entrar na loja. Furem aquela porta!",--I'm guessing a goat managed to get into the store. Drill the door!
	pln_pt1_23_02 = "Cabras amam comprar! Furem o caminho até a loja.",--Goats love shopping! Drill your way into the store.
	pln_pt1_24_01 = "Aberto para negócios! O negócio é encontrar Cabras!",--Open for business! The business of finding goats!
	pln_pt1_24_02 = "A loja está aberta! Encontrem a Cabra!",--Store is open! Find that goat!
	pln_pt1_25_01 = "Aquela Cabra subiu ali. Ficou presa. Precisamos derrubar ela. Serrem o poste.",--That goat climbed up there. Got stuck. We need him down. Saw the streetlight!
	pln_pt1_25_02 = "Vocês não vão conseguir derrubar aquela Cabra conversando com ela. Serrem o poste!",--You're not going to tempt that goat down with nice words and treats. Saw the streetlight!
	pln_pt1_26_03 = "Lembrem-se, vocês precisam serrar o poste para derrubar aquela Cabra.",--Remember, you need to get a saw on the streetlight to bring down the goat.
	pln_pt1_27_02 = "Esse é o poste. Agora peguem aquela Cabra!",--That's the streetlight done. Now grab that goat!
	pln_pt1_28_01 = "A polícia está pegando nossas Cabras! Peguem elas de volta!",--The cops are taking our goats! Get them back!
	pln_pt1_28_03 = "A polícia está resgatando as Cabras! É pra isso que o dinheiro de impostos pagam!?",--Cops are rescuing the goats! Is this what tax money pays for!?
	
	-- Legendas (Outros - Dia 1)
	brs_pt1_03_02 = "Três minutos... esses motoristas do caralho!",--Three minutes...fucking Prius drivers!
	brs_pt1_01x_02 = "Só me dê...",--Just give me...
	brs_pt1_01_02 = "Um minuto. Estou quase.",--One minute. So close.
	brs_pt1_04_02 = "Pode demorar um tempo. Era esquerda na União ou...?",--Could be a while. Was it left at the Union or....?
	brs_pt1_02_03 = "Dois minutos. Ei, cara de bosta!",--Two minutes. Hey, fuckface!
	brs_pt1_03_03 = "Três minutos. Ciclistas! Vou cortar suas gargantas!",--Three minutes. Cyclists! I'll cut your throat!
	brs_pt1_05_02 = "Tudo certo, estou aqui. Agora coloquem as Cabras aqui.",--All right, I'm here. Now get the goats in!
	brs_pt1_01x_03 = "Quase lá...",--Almost there....
	brs_pt1_03_01 = "Três minutos... tráfico de Downtown!",--Three minutes...Downtown traffic!
	brs_pt1_01_03 = "Um minuto... quase lá.",--One minute...almost there.
	brs_pt1_05_03 = "Na cena! Me tragam as Cabras!",--On the scene! Bring me the goats!
	brs_pt1_05_01 = "Estou aqui! Tragam as Cabras!",--I'm here! Bring the goats!
	brs_pt1_02_02 = "Dois minutos. Saia da rua, seu velhote!",--Two minutes. Get off the road, old cunt!
	brs_pt1_01_01 = "Um minuto. Ei, Mova sua bunda daí.",--One minute. Hey, move your ass.
	brs_pt1_04_01 = "Pode demorar um pouco. Era na avenida Maryland ou Massachussetts?",--Could be a while. Was it Maryland or Massachussetts Ave?
	brs_pt1_02_01 = "Dois minutos. Aprenda a dirigir, cuzão.",--Two minutes. Learn to drive, asshole.
	brs_pt1_01x_01 = "Eu chego em...",--There in....
	
	-- Legendas (Bain - Dia 2)
	pln_pt2_12_03 = "Estamos prontos. Está vendo o balão?",--We're ready. You seeing the balloon?
	pln_pt2_13_02 = "Grupo, ouviram isso? O piloto está vindo, Protejam as Cabras.",--Crew, you copy that? Pilot is inbound. Protect the goats.
	pln_pt2_14_03 = "Como antes, gangue. Preparem a jaula.",--As before, gang. Get that cage prepared.
	pln_pt2_10_01 = "É isso! Agora coloquem todas as Cabras ali!",--That's it! Now put all the goats in it!
	pln_pt2_18_03 = "Fiquem no carro, droga!",--Stay in the car, dammit!
	pln_pt2_21_03 = "Certo. Ok. A ponte está virando agora. Mas vai demorar alguns minutos. Fiquem vivos, gangue!",--Right. Okay. Bridge is turning back now. But it'll take a few minutes. Stay alive, gang!
	pln_pt2_23_02 = "A Sala de Controle pode mover a ponte, Usem os botões ali dentro!",--The control room manages the bridge. Use the buttons in there!
	pln_pt2_17_02 = "Todos! Pro carro! Agora!",--Everyone! In the car! Now!
	pln_pt2_08_03 = "Muita ação aqui. Vou fazer com que nossos caras montem a jaula na ponte.",--Too much action here. I'll have the guys build the cage at the bridge.
	pln_pt2_24_02 = "Tudo certo! A ponte está de volta! Agora, subam no carro e deem o fora daí!",--All right! Bridge is back! Now, into the car and get the hell out of there!
	pln_pt2_19_03 = "Tudo certo, ouçam. Aqui está a nossa fuga. Passem pela ponte ali na frente, vocês verão um caminhão no túnel. É o Twitch. Só estacionem o carro no caminhão. E podemos acabar esse livro.",--All right, listen up. Here's the getaway. Get past the bridge up ahead, and you'll see a truck in a tunnel. That's Twitch. Just park straight up into the truck, and we can close the book on this one.
	pln_pt2_22_02 = "Droga! A polícia parou a ponte. Um de vocês - Entrem ali, continuem o processo!",--Godammit! Cops halted the bridge. One of you - get in there, restart it!
	pln_pt2_04_01 = "A polícia chegou! Se preparem!",--Cops are here! Brace yourselves!
	pln_pt2_04_02 = "A polícia está aqui. Se preparem, gente!",--Here's the cops. Get ready, crew!
	pln_pt2_11_02 = "Quando estiverem prontos, subam o balão e o piloto vai passar ai pra coletar ele.",--When you're ready, raise the balloon and the pilot will swing by and collect.
	pln_pt2_22_03 = "Merda, a polícia parou a ponte. Precisa ser reiniciada. Um de vocês entrem ali!",--Ah crap, cops stopped turning the bridge. It needs to be restarted. One of you, get on that!
	pln_pt2_25_02 = "Vocês verão o caminhão a qualquer momento. Só dirijam até ali. E estaremos acabados!",--You'll see the truck any second. Just drive up into it, and we're done!
	pln_pt2_02_03 = "Isso vai com certeza trair os federais. Precisamos achar uma maneira de tirar as Cabras daí.",--That'll surely bring the feds. Gotta think of a way to get the goats out of here.
	pln_pt2_08_01 = "Está muito pesado aqui. Meu pessoal vai montar na ponte.",--It's too damned heavy here. The guys will set up at the bridge.
	pln_pt2_20_03 = "Ah! A polícia virou a ponte! Certo, um de vocês entrem naquela Sala de Controle e virem ela de volta. Precisamos chegar no outro lado.",--Ah! Cops have turned the bridge! All right, one of you get into that control room and turn it back. We need to get on the other side!
	pln_pt2_21_01 = "Ok, a ponte está virando. Droga, é lenta! Só segurem a polícia!",--Okay, the bridge is turning back. Damn, it's slow! Just hold off the cops!
	pln_pt2_07_03 = "A polícia tem isso sob controle. Vamos montar no silo.",--Cops have this locked down. We're going to assemble at the silo.
	pln_pt2_22_01 = "A polícia parou a ponte. Usem os controles para continuar virando!",--The cops stopped the bridge. Use the controls to keep it turning!
	pln_pt2_20_01 = "Os policiais fecharam a ponte. Vão até a Sala de Controle e virem ela de volta.",--The crafty cops have closed off the bridge. Go to the control room to turn it back.
	pln_pt2_05_03 = "Aquele Celeiro deve ter algo que possa ser colocado nas janelas.",--That barn must have something lying around you can nail across the windows.
	pln_pt2_09_01 = "Acho que o melhor lugar para vocês montarem a jaula é na rua.",--Reckon the best place for the guys to build the cage is on the road.
	pln_pt2_10_03 = "Bom trabalho, gangue. Agora comecem a mover as Cabras.",--Nice job, gang. Now start getting the goats in.
	pln_pt2_21_02 = "Certo, a ponte está virando. Vai demorar alguns minutos. Segurem a polícia, gangue!",--All right, bridge is turning back. Gonna take a few minutes though. Hold off the cops, gang!
	pln_pt2_12_02 = "O balão está pronto. Vocês estão vendo?",--Balloon is up. Are you seeing it?
	pln_pt2_13_03 = "O piloto está vindo com tudo, pessoal. Não deixem a polícia pegar essas Cabras.",--Pilot is coming in hot, guys. don't let the cops grab any goats.
	pln_pt2_18_01 = "Ei, pra onde estão indo? De volta ao carro!",--Hey, where you going? Back in the car!
	pln_pt2_05_01 = "Deve ter tábuas em volta do Celeiro. Usem elas para bloquear as janelas.",--There's gotta be boards around that barn. Use 'em to block the windows.
	pln_pt2_19_01 = "A fuga está pronta. Tem uma ponte no fim da rua, e o Twitch está no outro lado com um caminhão. Só dirijam até o caminhão e estaremos finalizados!",--You're getaway is all ready. There's a bridge just down the road, and Twitch is on the other side, with a truck. Just drive right up into the truck and we are done!
	pln_pt2_04_03 = "São os policiais! Segurem as pontas!",--It's the cops! Hold the line!
	pln_pt2_01_01 = "Peguem eles, grupo!",--Drop them, crew!
	pln_pt2_01_02 = "Não deixem eles chegarem perto, gangue!",--Don't let them close, gang!
	pln_pt2_01_03 = "Derrubem eles!",--Take them out!
	pln_pt2_02_01 = "Esse tiroteio vai atrair a polícia. Não podemos deixar eles pegarem as Cabras.",--That gunfire will bring the cops. We can't let them get the goats.
	pln_pt2_02_02 = "O tiroteio vai atrair todos os policiais. Precisamos tirar as Cabras daí.",--The shooting's bound to draw the cops. We need to get the goats away.
	pln_pt2_03_01 = "Ah, essa voz é familiar. Espere que ele não bata.",--Oh, that voice is familiar. Just hope he doesn't crash.
	pln_pt2_03_02 = "Espero que ele não bata em um morro. Mantenham a polícia longe.",--Hope he doesn't hit a hill. Keep the cops at bay.
	pln_pt2_03_03 = "Vamos esperar que ele fique no ar dessa vez. Segurem os policiais.",--Let's hope he stays in the air this time. Hold the cops off.
	pln_pt2_05_02 = "Tenho certeza que vocês vão encontrar algo naquele Celeiro para fechar as janelas.",--I'm sure you'll find something in that barn to close off the windows.
	pln_pt2_06_01 = "Vocês sabem o que fazer pessoal. Vão para fora, peguem a jaula e montem ela.",--You know what to do guys. Go out there, grab the cage parts and assemble it.
	pln_pt2_06_02 = "Ok gangue - Agora saiam daí e montem a jaula!",--Okay gang - now get out there and assemble the cage!
	pln_pt2_06_03 = "Não percam tempo, gente. Montem aquela jaula!",--Don't dawdle, crew. Assemble that cage!
	pln_pt2_07_01 = "Está muito quente aqui. Vou fazer meu pessoal montarem a jaula no silo.",--There's way too much heat here. I'll have my guys assemble the cage at the silo.
	pln_pt2_07_02 = "Muito tiroteio aqui. Vamos montar no silo!",--Too much fire here. We'll assemble at the silo!
	pln_pt2_08_02 = "Ah, tem muita troca de tiros aqui! Os caras vão montar a jaula na ponte.",--Oh, there's a lot of firepower here! The guys will assemble the cage at the bridge.
	pln_pt2_09_02 = "Ok, vou fazer meu pessoal montar a jaula na rua.",--Okay, I'll have the guys put the cage together on the road.
	pln_pt2_09_03 = "Muita coisa acontecendo aqui. A rua parece o melhor lugar para vocês montarem a jaula.",--Too much going on here. The road looks best for the guys to assemble the cage.
	pln_pt2_10_02 = "Boa! Agora peguem as Cabras e joguem elas alí!",--Good! Now grab the goats and throw them in!
	pln_pt2_11_01 = "Ok. Quando estiverem prontos, subam o balão e o piloto vai coletar a jaula.",--Okay. When you're ready, raise the balloon and the pilot will collect the cage.
	pln_pt2_11_03 = "Agora só levantem o balão e deixem o piloto fazer o resto.",--Now just raise the balloon and let the pilot do the rest.
	pln_pt2_12_01 = "Tem um balão. Ei, você está vendo, cara?",--There's the balloon. Hey, you see it, guy?
	pln_pt2_13_01 = "Ouviram ele, gangue. Só tirem o calor das Cabras.",--You heard him, gang. Just keep the heat off the goats.
	pln_pt2_14_01 = "Vocês sabem o que fazer. Saiam daí. Montem a jaula!",--You know what to do. Get out there. Assemble the cage!
	pln_pt2_14_02 = "Ok, gente. Mesma coisa. Saiam daí e montem a jaula.",--Okay crew. Same thing. Get out there, and get the cage built.
	pln_pt2_15_01 = "Excelente! Agora saiam daí! Peguem o carro dentro do caminhão!",--Excellent! Now get outta there! Grab your car from the truck!
	pln_pt2_15_02 = "Fantástico! Hora de sair. Peguem o carro, gente!",--Fantastic! Time to leave. Grab the car, crew!
	pln_pt2_15_03 = "Excepcional! São todas as Cabras! Agora pé na estrada, gangue!",--Outstanding! That's all the goats! Now time to hit the road, gang!
	pln_pt2_16_01 = "Vamos lá, gente. Não fodam tudo agora. Entrem no carro e pé na estrada!",--Come on, crew. Don't fuck up now. Get the car, and hit the road!
	pln_pt2_16_02 = "Pessoal! Estamos prontos aqui. Peguem suas rodas e queimem a borracha!",--Guys! We're done here. Grab your wheels and burn rubber!
	pln_pt2_16_03 = "Por que vocês ainda estão ai? Vamos lá, parem o carro e saiam!",--Why you still there? Come on, into the car and floor it!
	pln_pt2_17_01 = "Wow, espere até todos estiverem no carro!",--Woah, wait til everyone is in the car!
	pln_pt2_17_03 = "Esperem, esperem - Esperem até todos estiverem no carro.",--Hold it, hold it - wait til everyone's in the car.
	pln_pt2_18_02 = "De volta pro carro! Hora de ir!",--Back in the car! Time to ride!
	pln_pt2_19_02 = "Ok, ouçam. O Twitch está esperando vocês logo a frente, do outro lado da ponte. Ele tem um caminhão. Dirijam até lá, e poderemos acabar isso.",--Okay, listen. Twitch is waiting for you up ahead, just on the other side of the bridge. He's got a truck. Just drive straight up on into it, and this caper is closed.
	pln_pt2_20_02 = "Droga, os policiais viraram a ponte! Entrem na Sala de Controle ali, e virem ela. Vocês precisam estar do outro lado!",--Damn, the cops turned the bridge! Get into the control room there, and turn it back. You need to be on the other side!
	pln_pt2_23_01 = "Usem o botão na Sala de Controle para reiniciar a ponte.",--Use the button in the control room to reset the bridge.
	pln_pt2_23_03 = "Estão vendo aquela Sala de Controle? Ali é onde vocês podem reiniciar a ponte.",--See that control room? That is where you can reset the bridge.
	pln_pt2_24_01 = "A ponte voltou! Finalmente. Agora, todo mundo - De volta ao carro e fujam!",--Bridge is back! Finally. Now, everyone - back in the car and bail!
	pln_pt2_24_03 = "Ótimo! Agora a ponte está consertada! Para o carro, pessoal! Hora de deixar isso tudo pra trás!",--Sweet! The bridge is fixed! Now into the car, people! Time to leave this behind!
	pln_pt2_25_01 = "O caminhão do Twitch está logo a frente. Só dirijam até ele!",--Twitch's truck is ahead. Just drive straight up into the back!
	pln_pt2_25_03 = "O caminhão está chegando. Coloquem o pé no acelerador a dirijam até ele!",--The truck is coming up. Just hit the gas and drive into it!
	
	-- Legendas (Vlad - Dia 2)
	vld_pt2_02_01 = "Meu cunhado - você lembra aquele velho - ele vai vir com a jaula. ",--My brother-in-law - you remember that old soak - will be coming in with a skyhook cage.
	vld_pt2_03_02 = "Ei, está faltando algumas Cabras. Isso vai deixar o Vlad triste. Confiem em mim, vocês vão querer um Vlad feliz.",--Hey, we're missing some of the goats. This makes Vlad sad. Trust me, you want a happy Vlad.
	vld_pt2_03_01 = "Espere, vocês não pegaram TODAS as Cabras. Por um acaso o meu cu é o brinquedinho de vocês? eu quero TODAS as Cabras.",--Wait, you didn't get ALL of the goats. Is my asshole your plaything? I want ALL the goats. 
	vld_pt2_04_03 = "Que bela maneira de começar o ano. Com uma montanha de Cocaína para transportar! Parabéns, caros amigos.",--What a great way to start the year. With a mountain of fucking coke to move! Congratulations, dear friends. 
	vld_pt2_01_03 = "Fiquem frios, meus amigos. Vlad tem uma ideia. Vocês gostam das ideias do Vlad, não é?",--Stay cool, my friends. Vlad has an idea. You like Vlad's ideas, yeah?
	vld_pt2_01_01 = "Felizmente, vocês tem a mente criminosa do Vlad ao lado de vocês. Eu tenho uma ideia.",--Fortunately, you have the criminal mind of Vlad on your side. I have an idea.
	vld_pt2_01_02 = "Vocês acham que o tio Vlad iria deixar vocês aí sem nenhuma ajuda? Acharam errado!",--You think your Uncle Vlad would leave you there and not have support? Shame on you!
	vld_pt2_02_02 = "Estou mandando meu cunhado. Ele vai largar uma jaula. Se ele conseguir não bater.",--I'm sending in my brother-in-law. He'll drop a skyhook cage. If he can avoid crashing.
	vld_pt2_02_03 = "Meu cunhado está a caminho. Ele vai largar uma jaula para vocês",--My brother-in-law is on his way. He will drop a skyhook cage for you. 
	vld_pt2_03_03 = "Espere, algumas Cabras estão faltando. Por que tem Cabras faltando?!",--Wait, some of the goats are missing. Why are some of the goats missing?!
	vld_pt2_04_01 = "É isso! Pegamos as Cabras, pegamos a Cocaína! Ka-ching-ching, meus amigos! Agora, quem quer vir aqui comer curry?",--That's it! We got the goats, we got the coke! Ka-ching-fucking-ching, my friends! Now, who wants to come over for a curry?
	vld_pt2_04_02 = "Bom trabalho, queridos amigos. Eu amo todos vocês! Não tanto quanto eu amo toda essa Cocaína, mas ainda amo muito!",--Well done, dear friends. I fucking love you all. Not as much as I love all of this coke, but still quite a lot!
	
	
	-- Legendas (Outros - Dia 2)
	plt_pt2_02_01 = "Dois minutos.",--Two minutes.
	plt_pt2_17_01 = "Tudo certo, voltando! Me dê 30 segundos.",--All right, swinging around again! Gimme just 30 seconds.
	plt_pt2_25_01 = "Peguei! Peguei as Cabras!",--Got it! I got the goats!
	plt_pt2_09_01 = "Ok, sensei. Me diga quando estiverem prontos.",--Okay sensei. Just let me know when you're ready.
	plt_pt2_20_03 = "Vindo denovo. Vou deixar isso na rua para vocês",--Coming around again. Going to leave this on the road for you.
	plt_pt2_09_02 = "Ouvi, irmão. Me digam quando estiverem prontos.",--I hear ya, brother. Let me know when it's ready.
	plt_pt2_12_02 = "Entendi. Eu não fudi tudo! Eu não fudi.",--I got it. I didn't fuck up! I didn't fuck up.
	plt_pt2_19_03 = "A ponte parece boa. Jogando a jaula ali.",--The bridge looks good. Dropping the cage there.
	plt_pt2_17_03 = "Entendido. Voltando. Preciso de meio minuto!",--Copy that. Returning for another drop. I need half a minute!
	plt_pt2_13_03 = "Porra! Achei que eu tinha pego. Não peguei. Estou voltando novamente.",--Fuck! Thought I had it. Didn't have it. Coming about again.
	plt_pt2_06_02 = "Estão vendo aquela ponte? Jogando a jaula ali.",--You see that bridge? I'm dropping the cage over there.
	plt_pt2_22_01 = "Mandem o balão quando estiverem prontos, amiguinhos.",--Just send the balloon when you're ready, buddies.
	plt_pt2_25_02 = "Boom! Peguei!",--Boom! I caught it!
	plt_pt2_03_02 = "Um minuto.",--One minute.
	plt_pt2_24_02 = "Ok, tenho os olhos na jaula. Estou indo!",--Okay, got eyes on the cage. Here I come!
	plt_pt2_02_02 = "Só mais dois minutos.",--Just two minutes.
	plt_pt2_16_03 = "Desculpem... calculei errado. Vou voltar e tentar de novo.",--Sorry...slight miscalculation. I'm going to come around and try again.
	plt_pt2_14_03 = "Lá vamos nós. Mãos firmes. Fique reto, quase lá...",--Here we go. Hands steady. Just keep it straight. Almost there....
	plt_pt2_17_02 = "Ok, indo largar de novo. 30 segundos!",--Okay. Banking for another drop. 30 seconds!
	plt_pt2_08_03 = "Jaula está onde eu queria. Igual a porra do Esquadrão 633!",--Cage is right where I put it. Like fucking 633 Squadron!
	plt_pt2_13_02 = "Uh, porra... reportando um quase erro. Vindo denovo.",--Uh, fuck....reporting a near miss. Coming around again.
	plt_pt2_16_02 = "É... abortando devido a... droga. Dando meia volta",--Uh...aborting due to...geese. Coming around again.
	plt_pt2_09_03 = "Entendi, segurando até vocês me darem permissão.",--Copy that, In holding pattern til you give clearance.
	plt_pt2_07_02 = "Ok, alinhando na rua. Vou largar a jaula ali.",--Okay, lining up on the road. Gonna drop the cage there.
	plt_pt2_21_03 = "Jaula entregue!",--Cage delivered!
	plt_pt2_07_03 = "A rua é uma zona de drop perfeita. Mandando a jaula ali.",--The road is a perfect drop-zone. Putting your cage there.
	plt_pt2_06_03 = "Consegui uma boa corrida na ponte. Ali é onde a jaula vai estar.",--Got a nice clear run at the bridge. That's where the cage'll be.
	plt_pt2_01x_01 = "Olá denovo, pessoal. Aqui é... uh, Motoqueiro Fantasma. Me esperem em...",--Hello again, guys. This is...uh, Ghost Rider. Expect me in...
	plt_pt2_01x_02 = "Whisky Tango Foxtrot Um na cena. Vou estar aí em...",--Whisky Tango Foxtrot One on the scene. Be there in...
	plt_pt2_01x_03 = "Ei gente. Aqui é... uh, o Asa Noturna. Só me deem...",--Hey fellas. This is...uh, Night Wing One. Gimme just...
	plt_pt2_01_01 = "Três minutos.",--Three minutes.
	plt_pt2_01_02 = "Apenas três minutos.",--Just three minutes.
	plt_pt2_01_03 = "Mais ou menos três minutos.",--About three minutes.
	plt_pt2_02_03 = "Mais ou menos dois minutos.",--About two minutes.
	plt_pt2_03_01 = "Um minuto.",--A minute.
	plt_pt2_03_03 = "60 segundos. Um minuto.",--About 60 seconds. AKA a minute.
	plt_pt2_04_01 = "Só mais trinta segundos",--Just thirty more seconds.
	plt_pt2_04_02 = "Só mais meio minuto.",--Just half a minute.
	plt_pt2_04_03 = "Vou estar aí em menos de um minuto.",--Be there in under a minute.
	plt_pt2_05_01 = "Eu vejo o local. Largando a jaula no silo.",--I see the drop zone. Putting the cage by the silo.
	plt_pt2_05_02 = "Tudo certo, eu vejo vocês. Largando a jaula no silo.",--All right, I see you. Dropping the cage by the silo.
	plt_pt2_05_03 = "Aquele silo parece um bom lugar. Largando ela ali.",--That silo looks like a good drop zone. Putting it there.
	plt_pt2_06_01 = "Aquela ponte parece perfeita. Largando o pacote ali.",--That bridge looks perfect. Dropping the package there.
	plt_pt2_07_01 = "Estou vendo a rua. É onde a jaula vai estar!",--Got a line on that road. That's where your cage will be!
	plt_pt2_08_01 = "A jaula está no chão!",--The skyhook cage is on the ground!
	plt_pt2_08_02 = "Estão no chão! Jaula entregue.",--It's down! Skyhook cage is delivered.
	plt_pt2_10_01 = "A coisa branca voando no céu? Entendi! Dois minutos!",--The white thing floating in the sky? Got it! Two minutes, tops!
	plt_pt2_10_02 = "É aquela coisa redonda flutuante? Estou indo. Me dê dois minutos.",--Is it that white floaty round thing? I'm after it. Gimme two minutes!
	plt_pt2_10_03 = "QUE PORRA É AQUELA...ah, o balão. Certo. Chegando em dois minutos!",--WHAT THE FUCK IS THAT...oh, the balloon. Right. Coming in two minutes!
	plt_pt2_11_01 = "Alvo em frente. Oooh, São muitos políciais. Tentando... fazer.......",--Target in sight. Oooh, that's a lot of cops. Attempting...to........
	plt_pt2_11_02 = "Alinhando no alvo. Foda-se, isso é mais tenso que Khe Sanh!",--Lining up on the target. Fuck me, it's hotter than Khe Sanh!
	plt_pt2_11_03 = "Estou indo. Puta merda. Vocês tem muitos porcos vindo até vocês!",--Here I come. Hot fucking diggity fellas, you have a lot of pigs headed your way!
	plt_pt2_12_01 = "E... peguei. Eu peguei! Não acredito que eu peguei.",--And....got it. I got it! I can't believe I got it.
	plt_pt2_12_03 = "Eu peguei? Caralho, eu peguei pra caralho! Ha! Pau no seu cu F.A.A.!!",--I got it? Holy shit, I fucking got it. Ha! Fuck you F.A.A.!!
	plt_pt2_13_01 = "Eu errei! Merda! Certo, eu consigo. Só preciso de cobertura.",--I missed! Crapola! All right, I can do this. Just need Dutch courage.
	plt_pt2_14_01 = "Ok. Lá vamos nós denovo. Isso é pelo dinheiro, baby!",--Okay. Here we go again. This is for the money, baby!
	plt_pt2_14_02 = "Certo. Alinhando. Tudo certo. Você consegue!",--Right. Lining up. Flaps looking good. You can do this!
	plt_pt2_15_01 = "Peguei! Talvez eu consigo meu trabalho em Delta de volta.",--Got it! Maybe I can get my job at Delta back.
	plt_pt2_15_02 = "Peguei. Igual um chefão!",--I caught it. Like a fucking boss!
	plt_pt2_15_03 = "E... peguei! Pessoal, eu peguei! As vezes eu fico sem acreditar.",--And....got it! Guys, I got it! Sometimes I amaze even myself.
	plt_pt2_16_01 = "Uh, controle, eu caguei na cama denovo. Repito: Caguei na cama, tentando de novo.",--Uh, control, I shat the bed again. Repeat: shat the bed. Trying again.
	plt_pt2_18_01 = "Largando isso no silo!",--Dropping this one at the silo!
	plt_pt2_18_02 = "Vou deixar esse no silo!",--Going to leave this one at the silo! 
	plt_pt2_18_03 = "Essa daqui vai estar no silo, ouviram?",--This one will be down by the silo, y'hear?
	plt_pt2_19_01 = "Essa daqui vai estar na ponte.",--This one's coming down at the bridge.
	plt_pt2_19_02 = "Ok, acho que a ponte é um bom lugar para largar.",--Okay, think the bridge is looking good for a drop point.
	plt_pt2_20_01 = "Tudo certo, palhaços - Mantenham seus olhos na rua.",--All right, clowns - keep your eyes on the road.
	plt_pt2_20_02 = "Vou largar ela na rua. Esperem só um pouco.",--I'm going to drop it on the road. Stand by.
	plt_pt2_21_01 = "Está no chão agora.",--It's on the ground now.
	plt_pt2_21_02 = "Ok, o pacote está no chão.",--Okay, package is on the floor.
	plt_pt2_22_02 = "Vocês sabem o que fazer quando estiverem prontos. Mandem o balão!",--You know what to do when you're ready. Send that balloon up!
	plt_pt2_22_03 = "Só levantem o balão quando estiverem prontos, festeiros!",--Just raise the balloon when you're done, groovers!
	plt_pt2_23_01 = "Ok, voltando agora. Vou estar aí em 60 segundos.",--Okay, coming back around. There in 60 seconds.
	plt_pt2_23_02 = "No caminho de volta. Me dê uns 60 segundos.",--On my way back. Give me 60 seconds.
	plt_pt2_23_03 = "Virando essa caixa. Me dê 60 segundos.",--Turning this crate around. Just gimme 60 seconds.
	plt_pt2_24_01 = "Eu vejo a jaula. Tentando pegá-la.",--I see the cage. Attempting the pick-up.
	plt_pt2_24_03 = "Eu vejo o alvo. Me aproximando!",--I see the target. On approach!
	plt_pt2_25_03 = "Boa! Peguei a filha da puta!",--Ah yeah! Grabbed that motherfucker!
	brs_pt2_intro_01 = "Me ajudem a levar as Cabras até o Celeiro.",--Help me get the goats into the barn.
	brs_pt2_intro_02 = "Vocês podem me ajudar a levar as Cabras ali.",--Can you guys help me get the goats in here.
	brs_pt2_intro_03 = "Vamos levar as Cabras ali.",--Let's get the goats in here.
	brs_pt2_01_01 = "Ok. Eu tenho tudo? Pé de Cabra, algemas, lubrificante. Tudo certo! Colocando as luvas para um trabalho bem sujo.",--Okay. Do I have everything? Crowbar, zipties, lube. All ready! Gloves on for some really dirty work.
	brs_pt2_03_08 = "Eles ja foram embora? É seguro sair?",--Are they gone yet? Is it safe to come out?
	brs_pt2_02_03 = "Porra! os Hondurenhos! Estão aqui! Eles vão nos matar!",--Fuck! The Hondurans! They're here! They're going to kill us!
	brs_pt2_03_12 = "A Sra. Shevchenko rolaria em seu túmulo para ver seu garotinho agora.",--Mrs Shevchenko would roll in her grave to see her little boy now.
	brs_pt2_03_04 = "É seguro sair? Esses estouros são fogos de artifício?",--Is it safe to come out yet? Are those loud bangs firecrackers?
	brs_pt2_03_11 = "Eu não acho que essa lixeira foi esvaziada desde que o Bush estava no poder. Bush senhor!",--I don't think this trash can has been emptied since Bush was in power. Bush senior!
	brs_pt2_03_02 = "Ei, é seguro sair? Esse lugar tem um cheiro de bunda velha.",--Hey, is it safe out there yet? It's smells like old ass in here.
	brs_pt2_02_01 = "São os hondurenhos! Eles nos seguiram! Merda!",--It's the Hondurans! They fucking followed us! Shit!
	brs_pt2_02_02 = "A porra dos Hondurenhos nos encontraram! Como eles nos seguiram?!",--The fucking Hondurans found us! How did they follow us?!
	brs_pt2_03_05 = "Posso sair? Eles se foram?",--Can I come out yet? Are they gone?
	brs_pt2_03_06 = "As Cabras estão seguras? Por favor, Deus, alguem pense nas Cabras!",--Are the goats safe? Please, God, someone think of the goats!
	brs_pt2_01_03 = "Essa próxima parte é barulhenta. Barulhenta, nojenta e fedida. Eu não posso esperar. Vamos lá, né?",--This next part is noisy. Noisy, and dirty and smelly. I can't wait. Let's do this, huh?
	brs_pt2_03_01 = "Caralho, o que que está acontecendo aí fora? Ah, ta quente aqui.",--Holy shit, what's going on outside? Oh, it's hot in here.
	brs_pt2_01_02 = "Agora, hora do trabalho sujo real. Eu costumava trabalhar na alfândega em Mariupol. Coloquem as luvas.",--Now, time for the real dirty work. I used to work as a customs officer in Mariupol. Snap the gloves on. 
	brs_pt2_03_03 = "Pessoal, é seguro sair? Eu engoli uma barata.",--Guys, safe to come out yet? I swallowed a cockroach.
	brs_pt2_03_10 = "Tem mais algo vivo aqui.",--There's something else alive in here.
	brs_pt2_03_09 = "Podemos voltar ao trabalho? Eu ja perdi 5% do meu celular.",--Can we get back to work yet? I'm down to 5% on my cell.
	brs_pt2_03_07 = "Tem metade de um doce aqui. Mmmmm delicia. Ah.... não era um doce.",--There's a half-eaten candy bar here. Mmmmm nutty. Oh....wasn't a candy bar.
	
	-- Objetivos (Dia 1)
	hud_heist_pet1_3 = "Fuja no caminhão, porém você vai precisar do seu carro.",--Escape in the truck, but you must need your car.
	hud_heist_pet1_2_hl = "Mova as Cabras até o Caminhão",--Move the goats to the truck
	hud_heist_pet1_2 = "Mova todas as Cabras até o caminhão e coloque elas na jaula.",--Move all the goats to the truck and load them into the cage.
	hud_heist_pet1_1 = "Encontre e colete todas as Cabras.",--Find and collect all the goats.
	hud_heist_pet1_1_hl = "Colete as Cabras",--Collect the goats
	hud_heist_pet1_3_hl = "Fuga com o Carro Disponivel",--Escape with car available
	
	-- Objetivos (Dia 2)
	hud_heist_pet2_4 = "Levante o balão na jaula que você montou.",--Fire up the balloon at the cage you assembled.
	hud_heist_pet2_1 = "Se defenda dos membros da gangue. Use as tábuas para bloquear as janelas.",--Defend yourself from the gang members. Use wood to board the windows.
	hud_heist_pet2_10_hl = "Fuja para o Novo Caminhão",--Escape into the new truck
	hud_heist_pet2_7_hl = "Saia da Área",--Leave the area
	hud_heist_pet2_5 = "Não deixe os policiais pegarem as Cabras de sua jaula.",--Don't let the cops take the goats from your cage.
	hud_heist_pet2_8 = "Dirija até a ponte para chegar no caminhão de fuga.",--Drive over the bridge to reach the escape truck.
	hud_heist_pet2_9_hl = "Vire a Ponte",--Close the bridge
	hud_heist_pet2_4_hl = "Levante o Balão quando estiver Pronto",--Fire up the balloon when ready
	hud_heist_pet2_2 = "Pegue as partes da jaula que o piloto largou, e monte a jaula no local designado.",--Pick up the cage parts the pilot dropped, then assemble the cage at designated area.
	hud_heist_pet2_10 = "O Twitch está esperando por você com um caminhão. Dirija até ele para fugir.",--Twitch is waiting for you with a truck. Drive into it to escape.
	hud_heist_pet2_6_hl = "Vá para o seu Carro",--Go to your car
	hud_heist_pet2_5_hl = "Defenda as Cabras",--Defend the goats
	hud_heist_pet2_2_hl = "Monte a Jaula",--Assemble the cage
	hud_heist_pet2_3 = "Coloque todas as Cabras do Celeiro na jaula que você montou.",--Put all the goats from the barn in the cage you assembled.
	hud_heist_pet2_9 = "Vá até a Sala de Controle e vire a ponte.",--Go to the control room and close the bridge.
	hud_heist_pet2_3_hl = "Coloque as Cabras na Jaula",--Put the goats in the cage
	hud_heist_pet2_6 = "O carro está dentro do caminhão em que você veio.",--The car is inside the truck you came with.
	hud_heist_pet2_7 = "Saia da área com o seu carro.",--Leave the area with your car.
	hud_heist_pet2_1_hl = "Defenda o Celeiro",--Defend the barn
	hud_heist_pet2_8_hl = "Dirija até a Ponte",--Drive over the bridge
		}