return {
	-- Nomes e Descrições
	--heist_bex = "San Martín Bank",
	--heist_bex_hl = "San Martín Bank",
	heist_bex_crimenet = "Vlad está exigindo que você o ajude a recuperar alguns itens importantes para recompensá-lo por toda a sua ajuda.\n\n» Encontre uma maneira de Entrar nas Áreas Seguras do Banco San Martín\n» Localize e Arrombe o Cofre\n» Recupere o Loot 'precioso' do Vlad",--Vlad is demanding that you help him recover some important loot to repay him for all his help.\n\n» Find a way into the secure areas of San Martín bank\n» Locate and crack open the vault\n» Recover Vlad's "precious" loot
	heist_bex_briefing = "Certo, amigos. Nós teremos que ajudar o Vlad nesse aqui. Suponho que nós devemos a ele, embora isso tire muito do foco das nossas operações atuais em Washington. Ele quer que a gente invada o Banco San Martín, numa cidade rústica no sul da Cidade do México. Estou um pouco preocupado que ele esteja sendo tão sigiloso sobre o que extamente iremos roubar, mas ele diz que vocês saberão quando verem. É sempre uma charada com aquele idiota, mas tenho um plano astuto para ajudá-los. Agora, o cartel Coyopa opera nesse banco, e do que li sobre esse personagem 'Buluc', ele é um velho maldito. Mas em termos de operação deve ser bem padrão. Famosas últimas palavras, com certeza!",--OK, friends. We're going to have to help Vlad with this one. I suppose we owe him, even though it will take a lot of focus off our current operations in Washington. He wants us to break into the San Martín bank, in a little rustic town just south of Mexico City. I'm a bit worried that he's being so secretive about what exactly we're stealing, but he says you'll know it when you see it. It's always a riddle with that chop, but I've got a cunning plan to see you through. Now, the Coyopa cartel operates this bank, and from what I've read about this "Buluc" character, he's a right old bastard. But operations-wise it should be pretty standard. Famous last words, for sure!
	
	-- Legendas (Locke)
	loc_bex_intro_01_00a = "Beleza, seus idiotas. Vamos...",--Right you chops. Lets get you-
	loc_bex_intro_01_00 = "Ei! Ei! Ei Eeeei! Locky!",--Hey! Heey! Hey Hey Heeey! Locky!
	loc_bex_intro_01_01 = "Ghaa! Mas que merda!? Vlad, seu bêbado idiota, o que...!? Saia daí!",--Ghaa! What the blerrie!? Vlad, you dronkie chop,what...!? Get out of here!
	loc_bex_intro_01_02 = "Nós temos isso sob controle e você vai fazer o trabalho todo ir pro caralho se ferrar com meu pessoal.",--We've got this under control and you're just going to make the entire job go to kak if you mess with my guys.
	loc_bex_intro_01_03 = "Por que isso não enche minha cabeça de confiança? Se você vai ficar, então sente lá atrás e fique quieto.",--Why does that not fill my head with confidence? If you're going to stay, then sit back and be quiet.
	loc_bex_intro_02_01 = "Maldição! Ghaaa, seu mendigo Russo!",--Blerrie! Ghaaa, you Russian mendicant!
	loc_bex_intro_02_02 = "O que você quer?",--What do you want?
	loc_bex_intro_02_03 = "Bem, caso queira sua mercadoria de volta melhor não interferir com a minha operação. O Velho Locke não precisa de nenhum copiloto!",--Well, if you want your mechandise back you will not interfere with the operation. Old Locke doesn't need any backseat drivers!
	alm_bex_01_01 = "Ei, Vlad! Estou a caminho. Muitos policiais por aqui!",--Hey, Vlad! I'm on my way. Lots of cops around here!
	alm_bex_01_02 = "Para qual lado esse GPS vai? É o norte ou sul do Texas? Acho que estou na rua certa.",--Which way does this GPS go? Is Texas north or south? I think I'm on the right street.
	alm_bex_02_01 = "É esse o lugar certo? Vaaaaamos!",--Is this the right place? Mooooove!
	alm_bex_02_02 = "Saiam do caminho! Hiyaaaaa!",--Out of my way! Hiyaaaaa!
	loc_bex_01_01 = "Beleza, seus idiotas. Vamos fazer vocês vagarem pelo banco.",--Right, you chops. Let's get you ambling into the bank.
	loc_bex_01_02 = "Certo, amigos. Bora fazer isso. Sigam para o banco.",--OK, friends. Let's do this. Make your way into the bank.
	loc_bex_01_03 = "Fiquem tranquilos. Hora de uma caminhada casual para dentro do banco, yeah?",--Nice and easy. Time for a casual stroll into the bank, yeah?
	loc_bex_02_01 = "Vai ser um longo dia, não é.",--Going to be a long day, isn't it.
	loc_bex_02_02 = "Vocês irão continuar assim o dia todo?",--You going to keep this up all day?
	loc_bex_03_01 = "Que barulho horrível.",--What an awful noise.
	loc_bex_04_01 = "Então, Vlad. Já te contei sobre o meu encontro com uma cobra-tigre Australiana?",--So, Vlad. Did I ever tell you about my run-in with an Australian tiger-snake?
	loc_bex_04_02 = "Vlad, você sabe... Uma vez encontrei um Wolverine Russo...",--Vlad, you know... I encountered a Russian wolverine once...
	loc_bex_05_01 = "Vocês sabem que, a termite é mais ou menos um equipamento padrão pra gente.",--You do realize, thermite is more or less standard equipment for us.
	loc_bex_06_01 = "Mexam-se, amigos.",--Get moving, friends.
	loc_bex_06_02 = "O banco não vai se roubar sozinho.",--The bank is not going to heist itself.
	loc_bex_06_03 = "Meio que estamos no ponto aqui. Também temos muitas outras coisas para cuidarmos, yeah?",--We're kind of on the clock here. A lotta other things to take care of too, yeah?
	loc_bex_06_04 = "É um dia meio agitado amigos, nós temos que cuidar desse grande prédio branco, então não percam tempo.",--Kind of a busy day friends, we have that big white building to take care of, so don't dally.
	loc_bex_07_01 = "Vocês precisam achar uma maneira de passar pelos portões.",--You've got to find a way past the gates.
	loc_bex_07_02 = "Encontrem uma maneira de passar pelos portões sem levantar suspeitas.",--Find some way past the gates without raising any suspicions.
	loc_bex_07_03 = "Passem pelos portões, mas não sejam descobertos.",--Get past the gates, but don't get spotted.
	loc_bex_08_01 = "Vocês estão com medo dos recepcionistas ou algo assim? Entrem lá.",--Are you afraid of the receptionists or something? Get in there.
    loc_bex_08_02 = "Vamos logo amigos. Andalé ou qualquer outra merda assim que os latinos dizem.",--Come on friends. Andalé or whatever they say down there.
    loc_bex_08_03 = "Façam como aquele pequeno rato dos desenhos animados antigos e passem pelo saguão.",--Make like that little mouse in those old cartoons and get moving past the lobby.
	loc_bex_09_01 = "Bem feito, amigos. Agora, tem um portão de segurança que precisamos atravessar antes de chegarmos no cofre.",--Nicely done, friends. Now, there's a security gate you need to get past before you can reach the vault.
	loc_bex_09_02 = "Aí está. O cofre com a mercadoria do Vlad está atrás do portão de segurança.",--There you go. The vault with Vlad's merchandise is behind a security gate.
	loc_bex_09_03 = "Agora, o próximo passo é passar pelo portão de segurança para que possamos acessar o cofre.",--Now, the next thing is to get past the security gate so you can access the vault.
	loc_bex_10_01 = "Bem pensado, amigos. Agora vocês precisam passar pelo portão de segurança.",--Kiff thinking, friends. Now you gotta get past the security gate.
    loc_bex_10_02 = "Ótima ideia, agora nós precisamos ver como passar pelo portão de segurança e chegar até o cofre.",--Good call, now we have to see about getting you past the security gate to the vault.
    loc_bex_10_03 = "Certo, agora o cofre está atrás de um portão de segurança e vocês vão precisar passar por ele.",--Right, now the vault itself is behind a security gate and you'll need to get past it.
	loc_bex_11_01 = "Então, parece que vocês precisam achar um Escritório específico.",--Looks like you need to find a specific office, then.
	loc_bex_11_02 = "Beleza, seus idiotas. vão e encontrem o Escritório dele!",--Alright you chops, go and find his office!
	loc_bex_11_03 = "Bem, a lógica sugere que ele mantém a coisa em seu Escritório, com certeza.",--Well, logic would suggest he keeps the thing in his office, for sure.
	loc_bex_12_01 = "Já acharam o cofre, amigos?",--Found that safe, yet friends?
	loc_bex_12_02 = "Vocês precisam achar esse cofre, yeah?",--You gotta find that safe, yeah?
	loc_bex_12_03 = "Não esqueçam o cofre.",--Don't forget the safe.
	loc_bex_13_01 = "Essa coisa não vai ser arrombada sem fazer barulho.",--That dinges is not going to crack without causing a racket.
	loc_bex_13_02 = "Oh céus. Vocês não irão arrombar isso sem fazer uma puta barulheira.",--Oh, dear. You're not going to break that open without making a lotta noise.
	loc_bex_13_03 = "Ach, isso não é bom. Não temos como arrombar isso silenciosamente, amigos.",--Ach, that's not good. No way to break that open silently, friends.
	loc_bex_14_01 = "Talvez possamos passar pelo scanner se usarmos um pedaço de fita para tirar as digitais do gerente de algo?",--Maybe we can get past that scanner if you used a piece of tape to lift the manager's fingerprints off something?
	loc_bex_14_02 = "Que tal tirarmos a digital do gerente de algo com um pedaço de fita, para que possamos enganar o scanner silenciosamente?",--What about taking the manager's fingerprints off something with a piece of tape, so we can bypass the scanner quietly?
	loc_bex_14_03 = "Leitor de impressão digital de merda. OK, quem aí tem uma fita? Vocês podem usá-lo para retirar as impressões digitais do gerente de um objeto e abrir essa porra sem fazer barulho.",--Blerrie fingerprint scanner. OK, who's got some tape? Does anyone have any tape? You can use it to lift the manager's fingerprints off an object and open that dinges without making a lot of noise.
	loc_bex_15_01 = "Procurem por uma xícara de café. Todos os gerentes bebem café. É algo que ouvi.",--Look for a coffee cup. All managers drink coffee. So I've heard.
	loc_bex_15_02 = "Pode ser que ele tenha uma xícara de café em algum lugar por aí.",--Could be he's got a coffe cup sitting around there somewhere.
	loc_bex_15_03 = "Vejam se o gerente deixou alguma xícara ou algo assim espalhado.",--See if the manager has left a cup or something lying around.
	loc_bex_16_01 = "Deve ter uma xícara usada por aí em algum lugar.",--There must be a used cup around there somewhere.
	loc_bex_16_02 = "O gerente pode ter esquecido de colocar sua xícara na máquina de lavar louça e deixado fora...",--The manager might have forgotten to put his cup in the dishwasher and left it out...
	loc_bex_16_03 = "Vejam se conseguem achar um copo com digitais.",--See if you can find a cup with prints.
	loc_bex_17_01 = "Certo, agora retirem essa impressão!",--That looks right, now lift the print!
    loc_bex_17_02 = "Agora vão, vejam se conseguem uma impressão.",--There you go, see if you can pull a print.
    loc_bex_17_03 = "Certo, provavelmente é isso. Peguem uma impressão, yeah?",--Right, that's probably it. Take a print off it, yeah?
    loc_bex_18_01 = "Esse portão levará vocês para uma área mais segura do banco.",--That gate will get you into the more secure areas of the bank.
    loc_bex_18_02 = "Vocês vão ter que passar, eventualmente, daquele portão, já que ele nos leva diretamente para áreas mais seguras.",--You're eventually going to have to get past that gate, since it leads into the more secure areas.
    loc_bex_18_03 = "Esse portão irá levar vocês para áreas mais protegidas do banco.",--That gate will take you into the more guarded areas of the bank.
    loc_bex_19_01 = "Agora usem a impressão para abrir o cofre e pegar a chave.",--Now use the print to open the safe and get the key.
	loc_bex_19_02 = "Vejam se essa digital irá abrir o cofre para que possam pegar a chave.",--See if that print will get the safe open so you can reach the key.
	loc_bex_19_03 = "Tentem essa digital no cofre e vejam se funciona, yeah? Depois peguem a chave.",--Try that print on the safe and see if it works, yeah? Then get the key.
	loc_bex_20_01 = "O cofre, amigos. Usem a digital.",--The safe, friends. Use the print.
	loc_bex_20_02 = "Usem a digital para abrir o cofre.",--Use the print to open the safe.
	loc_bex_20_03 = "Ainda precisamos abrir aquele cofre. Usem a digital.",--Still need to get that safe open. Use the print.
	loc_bex_21_01 = "Puta que pariu! Isso... funcionou? Ha! Ok, agora usem isso para passar pelos portões.",--Blerrie! It... worked? Ha! Ok, now use it to get past the gates.
    loc_bex_21_02 = "Ha, funcionou! Pelo menos uma vez a TV foi boa para algo, yeah? Agora, usem isso para passar pela segurança.",--Ha, it worked! For once, TV is good for something, yeah? Now, use it to get past security. 
    loc_bex_21_03 = "Certo, agora usem essa coisa para passar pelo portão de segurança.",--Ok, now use that thing to get past the security gate.
    loc_bex_22_01 = "Vocês sabem, pode haver uma maneira melhor de entrar do que atravessar o portão.",--You know, there may be a better way in than going through the gate.
    loc_bex_22_02 = "Hmm. Quem sabe.. pode haver um jeito melhor de entrar do que por meio da segurança.",--Hmm. Maybe there's a better way in than via security.
    loc_bex_22_03 = "Claro, pode haver uma outra maneira de passar pela segurança...",--Of course, there could be another way past security...
    loc_bex_23_01 = "Vocês devem conseguir acessar o cofre em algum lugar por aí.",--You should be able to access the vault somewhere around there.
	loc_bex_24_01 = "Vocês precisam abrir as travas de segurança. Arrombem o leitor de cartões perto delas.",--You gotta get the security bars open. Crack open the card reader near it.
	loc_bex_24_02 = "Deem uma olhada no leitor de cartão perto das travas de segurança. Abram ele, yeah?",--Have a look at the card reader by the security bars. Get it open, yeah?
	loc_bex_24_03 = "Tem um leitor de cartão pelas travas de segurança. Abram ele.",--There's a card reader by the security bars. Open it up.
	loc_bex_25_01 = "Ach, eles atualizaram dos planos que o Vlad nos deu. Talvez vocês possam encontrar um manual ou diagrama em algum lugar po aí.",--Ach, they've upgraded from the plans Vlad gave us. Maybe you can find a manual or schematic somewhere around there.
	loc_bex_25_02 = "Hmm, não estou familiarizado com esse design. Deve ser bem incomum. Deem uma olhada nos armários de utilidades próximos e vejam se conseguem achar um diagrama.",--Hmm, I'm not familiar with that design. Must be very unusual. Have a look in the nearby utility rooms and see of you can find a schematic.
	loc_bex_25_03 = "Huh. Nunca vi um desses antes. Talvez tenha um manual em um dos armários de utilidades.",--Huh. Haven't seen one like that before. Maybe there's a manual in one of the utility closets.
	loc_bex_26_01 = "Já acharam o diagrama?",--Found a schematic yet?
	loc_bex_26_02 = "Continuem procurando por um manual ou algo assim.",--Keep looking for a manual or something.
	loc_bex_26_03 = "Deve ter algum tipo de manual de instruções por aí.",--There must be some kind of instruction manual around there.
	loc_bex_27_01 = "Ah, apesar de tudo não é tão complicado. Vocês devem ser capazes de atravessar acessando as caixas de cabos em volta e cortando os cabos certos.",--Good! Ah, not so complicated after all. You should be able to get through by accessing the wire boxes around there and cutting the right cables.
	loc_bex_27_02 = "Aí está. Enganosamente simples, yeah? Vocês podem passar pela trava eletrônica cortando os fios certos nas caixas de cabos.",--There we go. Deceptively simple, yeah? You can get past the electronic lock by cutting the right wires in the cable boxes there.
	loc_bex_27_03 = "Então é isso, yeah? Beleza amigos. Vocês precisam cortar os fios certos nas caixas de cabos para quebrar a trava.",--So, that's it, yeah? Alright, friends. You need to cut the correct wires in the cable boxes to break the lock.
	loc_bex_28_01 = "Verifiquem o diagrama e encontrem os cabos certos!",--Check the schematic and find the right wires!
	loc_bex_28_02 = "Usem o manual para achar qual cabo cortar, yeah?",--Use the manual to find which cable to cut, yeah?
	loc_bex_28_03 = "Vamos lá amigos, o manual deve mostrar quais cabos precisam ser cortados.",--C'mon friends, the manual should show what wires you need to cut.
	loc_bex_29_01 = "Boa, agora vamos para o cofre!",--Good, now get to the vault!
	loc_bex_29_02 = "Aí está! Apressem-se para o cofre.",--There you go! Hurry over to the vault.
	loc_bex_29_03 = "Certo, agora sigam para o cofre, yeah?",--Ok, now make your way to the vault, yeah?
	loc_bex_30_01 = "O que estão esperando, seus mendigos?",--What are you waiting for, you mendicants?
	loc_bex_30_02 = "Parem de perder tempo e vão para o cofre!",--Stop loitering and get over to the vault!
	loc_bex_30_03 = "O cofre não vai se abrir sozinho...",--The vault's not going to open itself...
	loc_bex_31_01 = "Iremos precisar desse código. Vasculhem os arredores um pouco e vejam se conseguem achar alguma pista. Talvez tentar uma das estações de trabalho? Mas fiquem quietos, amigos.",--We're going to need that code. Rummage 'round a bit and see of you can find any clues. Maybe try one of the workstations? But stay quiet, friends.
	loc_bex_31_02 = "Vocês precisam achar o código do cofre. Talvez tenha algo aí que possa ajudar. Provavelmente as estações de trabalho? Deem uma olhada em volta mas fiquem quietos.",--You need to find the code to the vault. Maybe there's something around there that can help. The workstations perhaps? Have a look around but stay quiet.
	loc_bex_31_03 = "Deem uma olhada nos arredores e vejam se conseguem achar uma pista daquele código. Verifiquem as estações de trabalho.",--Take a look around and see if you can find a clue on how to crack that code. Check the workstations.
	loc_bex_32_01 = "Vocês deveriam estar procurando, não perdendo tempo.",--You should be searching, not dawdling.
	loc_bex_32_02 = "Amigos, Vlad está ficando um pouco impaciente aqui...",--Friends, Vlad here is getting a bit impatient...
	loc_bex_32_03 = "Se não se mexerem logo, acho que o Vlad vai ficar bem puto!",--If you don'get moving soon, I think Vlad's going to go bossies!
	loc_bex_33_01 = "Talvez se eu invadir o sistema e fazê-lo executar um ping na workstation certa. Continuem olhando.",--Maybe if I hack into the system and get it to ping the right workstation. Keep looking.
    loc_bex_33_02 = "Deixe-me ver se consigo acessar o sistema deles daqui e indicar a workstation certa.",--Let me see if I can get into their system from here and point you to the right workstation.
    loc_bex_33_03 = "Se eu conseguir encontrar, eu posso mostrar remotamente qual workstation vocês vão precisar acessar para consertar isso.",--If I can find it, I can show you remotely which workstation you need to access to fix this.
	loc_bex_34_01 = "Certo, esse é o código. Lembrem-se.",--Ok, that's the code. Remember it.
	loc_bex_34_02 = "Bom, esse deve ser o código. Anotem ele.",--Good, that should be the code. Make a note of it.
	loc_bex_34_03 = "Beleza, agora memorizem o código, rápido rápido.",--Right, now memorize that code, chop chop.
	loc_bex_35_01 = "Abre-te Sésamo, amigos!",--Open sesame, friends!
	loc_bex_35_02 = "Boooa. Aí vamos nós.",--Niiiice. There we go.
	loc_bex_35_03 = "Boom, funcionou!",--Groot, it worked!
	loc_bex_36_01 = "Cofres lentos aí em baixo, yeah?",--Slow vaults down there, yeah?
    loc_bex_36_02 = "Demorando um pouco, não é?",--Taking a bit of time, isn't it?
    loc_bex_36_03 = "Vlad, pare de chutar a porra da minha cadeira. Você não está ajudando.",--Vlad, stop kicking my blerrie chair. You're not helping.
	loc_bex_37_01 = "Ach, cuidado amigos! Mas é claro. Eles tem lasers no banco que supostamente teria uma velha e primitiva segurança. Deixe-me verificar algo... sim... vocês devem ser capazes de desligá-los do telhado!",--Ach, watch it, friends! Of course. They have lasers in the bank that's supposed to only have older, primitive security. Let me check something... yes... you should be able to shut them off from the roof!
	loc_bex_37_02 = "Merda! Não pertubem esses lasers! Não consigo achar nada sobre eles nas plantas. Provavelmente adicionaram depois. Esse tipo de sistema geralmente pode ser desativado do telhado.",--Bliksem! Don't disturb those lasers! Can't find anything in the blueprints about them. Probably added later. That kind of system can usually be disabled via the roof.
	loc_bex_37_03 = "Cuidado com os lasers! Provavelmente vocês terão que desativá-los no telhado do prédio. Façam alguns movimentos de Lucha Libre e subam lá, yeah?",--Look out for the lasers! You're probably going to have to disable them via the roof of the building. Do some lucha libre moves and get up there, yeah?
	loc_bex_38_01 = "Cuidem desses lasers, yeah? Chop chop!",--Take care of those lasers, yeah? Chop chop!
    loc_bex_38_02 = "A menos que vocês estejam esperando por um chupacabra dando cambalhotas em um macacão para ajudar, vocês vão precisar chegar até o telhado e desligar os lasers, yeah?",--Unless you're waiting for a somersaulting chupacabra in a catsuit to help, you need to get to the roof and shut down those lasers, yeah?
    loc_bex_38_03 = "Amigos, o Batman não vai vir pulando na janela para ajudar. Vocês mesmos que precisam cuidar desses lasers.",--Friends, some Batmanuel is not going to come jumping in the window to help. You gotta take care of those lasers yourselves!
    loc_bex_38_04 = "Os lasers já foram desligados?",--The lasers turned off yet?
	loc_bex_39_01 = "Caralho! O que é isso?",-- Blerrie! What is that?
	loc_bex_39_02 = "Não é apenas QUALQUER coisa...",-- Not just ANY things...
	loc_bex_39_03 = "Ok, Vlad... Ok...",--OK, Vlad... OK....
	loc_bex_40_01a = "É aquele brasão... Romanov?",--Is that crest... Romanov?
	loc_bex_40_01b = "Eu já vi isso antes... isso é... Romanov? O império russo?",--I've seen that before... is that... Romanov? The Russian empire?
	loc_bex_40_02 = "Estou começando a entender o porquê isso é tão importante, yeah?",--I'm starting to understand why it's so important, yeah?
	loc_bex_41_01 = "Agora peguem o máximo da mercadoria do Vlad que vocês puderem, mas continuem quietos!",--Now grab as much of Vlad's merchandise as you can, but stay quiet!
	loc_bex_41_02 = "Certo, vocês podem pegar todo o loot especial do Vlad, mas não façam muito barulho.",--OK, now you can take all of Vlad's special loot, but don't make too much noise.
	loc_bex_41_03 = "Beleza, agora fiquem quietos e coletem todo o loot 'precioso' do Vlad.",--Right, now stay quiet and collect all of Vlad's "precious" loot.
	loc_bex_42_01 = "Certo, Vlad parece feliz. Vocês podem sair quando quiserem, amigos.",--OK, Vlad seems happy. You can leave at your discretion, friends.
	loc_bex_42_02 = "Beleza, seus idiotas, isso é o bastante para o Vlad. Saiam daí quando se sentirem prontos.",--Alright you chops, that's enough for Vlad. Get out of there when you feel ready.
	loc_bex_42_03 = "Quando estiverem prontos, vão em frente e saiam.",--When you feel ready, go ahead and make your way out.
	loc_bex_43_01 = "Certo, então é assim que querem fazer? Vamos ao Plano B!",--Ok, so that's how you want to do it? Let's go to plan B!
	loc_bex_43_02 = "Não precisamos mais ficar quietos agora. Vão rápido e forte.",--No need to keep quiet now. Go fast and hard.
	loc_bex_43_03 = "Beleza, vamos fazer a outra coisa então. Toquem alto, amigos.",--Alright, let's do the other thing then. Play it loud, friends.
	loc_bex_44_01a = "Estou quase com medo de perguntar...",--I'm almost afraid to ask...
	loc_bex_44_01b = "O que você está tramando, Vlad?",--What are you up to, Vlad?
	loc_bex_44_01c = "Você o que?",--You what?
	loc_bex_44_02a = "Oh, merda...",--Oh, blerrie...
	loc_bex_44_02b = "Soa como uma porrada de problemas...",--Sounds like a kakspul of trouble...
	loc_bex_44_02c = "Aquele idiota?",--That dwankie?
	loc_bex_45_01 = "Amigos, peguem a corrente do caminhão e prendam na janela do caixa!",--Friends, get the chain from the truck and attach it to the teller window!
	loc_bex_45_02 = "Levem a corrente do gancho e conectem ela na janela do bancário!",--Take the winch chain and hook it to the teller window!
	loc_bex_45_03 = "O guincho! Peguem a corrente e leve-a na cabine do bancário! ",--The winch! Take the chain and get it on the teller booth!
	loc_bex_46_01 = "Usem a corrente do guincho. Prenda-a no portão!",--Use the winch chain. Hook it up to the gate!
    loc_bex_46_02 = "O portão.. vocês podem puxá-lo com a corrente do guincho se prendê-lo.",--The gate... you can pull it off with the winch chain if you attach it.
    loc_bex_46_03 = "Prendam a corrente do caminhão ao portão!",--Hook up the chain from the truck to the gate!
	loc_bex_47_01 = "Melhor ficarem para trás, amigos. Isso pode ficar feio!",--Better stand clear, friends. This could get messy!
	loc_bex_47_02 = "Deem um passo para trás, isso vai causar um tumulto.",--Take a step back, this is going to cause a ruckus.
	loc_bex_47_03 = "Certo, seus idiotas! Cuidado com tijolos voadores...",--OK, you chops! Watch out for flying brickwork...
	loc_bex_48_01 = "OK, agora vão em frente!",--OK, now get going!
    loc_bex_48_02 = "Agora entrem no banco!",--Now get in the bank!
    loc_bex_48_03 = "Entrem no banco agora, amigos!",--Get inside the bank now, friends!
	loc_bex_49_01 = "Abram esses portões.",--Get those gates open.
	loc_bex_49_02 = "Vocês precisam chegar na área segura. Abram um desses portões.",--You need to get to the secure area. Open up one of those gates.
	loc_bex_49_03 = "Apressem-se e abram um desses portões, rápido rápido.",--Hurry and get one of those gates open, chop chop.
	loc_bex_50_01 = "Não fiquem aí parados, yeah?",--No standing around, yeah?
    loc_bex_50_02 = "Vamos amigos, esse lugar estará infestado de babacas bem irritados logo logo.",--Get going friends, the place is going to be crawling with kerels soon.
    loc_bex_50_03 = "Melhor se apressarem, os filhos das putas foram alertados e estão a caminho daí.",--Better hurry, kerels have been alerted and are on the way.
    loc_bex_51_01 = "Muito bom, agora vejam como obter acesso ao cofre.",--Nicely done, now see about getting access to the vault.
    loc_bex_51_02 = "Agora vejam como vocês podem conseguir acesso ao cofre.",--Now see how you can get access to the vault.
    loc_bex_51_03 = "A seguir, encontrem uma maneira de entrar na área do cofre.",--Next, find a way into the vault area.
	loc_bex_52_01 = "Certo, os portões de segurança precisam ser abertos.",--Ok, the security gate needs to be opened.
	loc_bex_52_02 = "Os portões de segurança precisam ser desativados para que possamos entrar.",--The security gate needs to be bypassed so that you can get inside.
	loc_bex_52_03 = "Para chegar no cofre, vocês terão que passar pela segurança.",--Get at the vault, you'll need to get past security.
	loc_bex_53_01 = "Encontrem a Sala do Servidor. Nós teremos que anular o bloqueio de segurança.",--Find the server room. We'll try to override the security lock.
	loc_bex_53_02 = "Se acharem a Sala do Servidor, nós provavelmente poderemos desativar a trava.",--If you find the server room, we can probably bypass the lock.
	loc_bex_53_03 = "Amigos, deve ter uma Sala do Servidor por aí. Achem-na e poderemos abrir aquele portão.",--Friends, there must be a server room around there. Find it and we can open that gate.
	loc_bex_54_01 = "Deve estar no andar de baixo.",--It should be on the bottom floor.
	loc_bex_54_02 = "Meu diagrama diz que está no andar de baixo.",--My schematics say it's on the bottom floor.
	loc_bex_54_03 = "Provavelmente está no andar de baixo.",--It's probably on the bottom floor.
	loc_bex_55_01 = "Sala do Servidor, yeah? Talvez se vocês encontrarem a pessoa responsável por isso, consigam fazê-la passar por essa fechadura.",--Server room, yeah? Maybe if you find the person in charge of it, you can get him to bypass the lock.
    loc_bex_55_02 = "Parece que vocês encontraram a Sala do Servidor, amigos. Se vocês encontrarem um técnico de suporte de TI, poderá obrigá-lo a desativar essa trava de segurança.",--Looks like you found the server room, friends. If you can find an IT support tech, you could make him disable the security lock.
    loc_bex_55_03 = "Oha só, o que é isso? Sala do Servidor? Encontrem um técnico de TI e façam ele desativar o bloqueio de segurança para vocês.",--Hello, what's this? Server room? Find an IT person and make them override the lock for you.
	loc_bex_56_01 = "Deixe-me cuidar disso, yeah?",--Let me handle this, yeah?
	loc_bex_57_01 = "Esses são os servidores corretos, mas se vocês acharem o cara da TI, nós poderemos entrar ainda mais rápido.",--Those are the right servers, but if you find the IT guy, we can get in faster.
	loc_bex_57_02 = "Hmm, certo... vocês terão que achar o cara da TI para que ele possa abrí-los para vocês.",--Hmm, OK... you're going to have to find the IT guy so he can open them up for you.
	loc_bex_57_03 = "Beleza, parece que iremos precisar do cara da TI. Encontrem ele, rápido rápido!",--Right, looks like we're going to need the IT guy. Find him, chop chop!
	loc_bex_58_01 = "Talvez vocês tenham que verificar o andar de cima.",--You might have to check the upper floor.
	loc_bex_58_02 = "Talvez dar uma olhada no andar de cima.",--Maybe have a look upstairs.
	loc_bex_58_03 = "Se vocês não conseguirem encontrá-lo, verifiquem todos os andares desse edifício.",--If you can't find him, make sure to check all floors of the building.
	loc_bex_59_01 = "Aquele homem ali... parece um cara de TI, se é que eu já vi um. Leve-o para a Sala do Servidor e faça-o desativar a trava de segurança.",--That man there... looks like an IT guy if ever I saw one. Take him to the server room and make him bypass the lock on the security bars.
    loc_bex_59_02 = "Aí... essa pessoa tem cara de quem passa o dia inteiro ligando servidores. Faça-o desativar a trava de segurança para nós.",--There... that person has the look of someone who spends all day hooking up servers. Get him to open up the lock on the security bars.
    loc_bex_59_03 = "Conheço bem um verme de TI quando vejo um, mesmo no México. Leve esse cara para a Sala do Servidor e faça-o abrir as grades de segurança.",--I know an IT dwankie when I see one, even in Mexico. Take that man to the server room and make him open up the security bars.
    loc_bex_60_01 = "Onde está o cara de TI? Eles estão sempre se escondendo quando se precisa deles, yeah?",--Where's the IT guy? They're always hiding when you need them, yeah?
    loc_bex_60_02 = "Estão procurando pelo arrombado do técnico de TI?",--Are you looking for the IT dwankie?
    loc_bex_60_03 = "Vamos logo idiotas! Encontrem o cara da TI.",--Hurry up you chops! Find the IT guy.
	loc_bex_61_01 = "Agora tragam ele para a Sala do Servidor!",--Now get him to the server room!
	loc_bex_61_02 = "Certo, certifiquem-se de que ele chegará na Sala do Servidor.",--OK, make sure he gets to the server room.
	loc_bex_61_03 = "Escoltem esse filho da puta para a Sala do Servidor!",--Escort the dwankie to the server room!
	loc_bex_62_01 = "Ou talvez não façam isso, yeah?",--Or maybe don't do that, yeah?
	loc_bex_63_01 = "Não precisamos que ele fale, apenas hackeie.",--We don't need him to talk, just to hack.
	loc_bex_64_01 = "Vamos lá amigos, coloquem ele para andar.",--Come on friends, get him moving.
	loc_bex_64_02 = "Apressem-se agora, levem esse idiota para a Sala do Servidor.",--Hurry now, get that dwankie to the server room.
	loc_bex_64_03 = "Não percam tempo, apenas mantenham ele se movendo.",--Don't waste any time, just keep him moving.
	loc_bex_65_01 = "Agora mantenham os policiais longe enquanto ele faz seu trabalho!",--Now keep the kerels away while he does his job!
	loc_bex_65_02 = "Certifiquem-se de que a polícia não interfira.",--Make sure the police don't interfere.
	loc_bex_65_03 = 'Vocês não podem deixar os "Federales" interromper o processo, yeah?',--You gotta see that the kerels don't interrupt, yeah?
	loc_bex_66_01 = "Vocês deixaram os policiais de merda interromperem o cara da TI! Deem um jeito nessa situação!",--You let the dwankie kerels stop the IT guy! Clear them out!
	loc_bex_66_02 = "Policiais chegaram no cara da TI, vão lá e parem eles!",--Kerels got to the IT guy, get in there and stop them!
	loc_bex_66_03 = 'O cara da TI parou de abrir a trava. "Federales Chiques" chegaram nele!',--The IT guy has stopped opening the lock. Laanie federales got to him!
	loc_bex_66_04 = "Maldita polícia alcançou o cara da TI e fez ele parar de anular a bloqueio. Entrem lá e façam ele terminar isso!",--Blerrie police reached the IT guy and made him stop overriding the lock. Get in there and make him finish!
	loc_bex_66_05 = "O anulamento foi interrompido! Eles chegaram no cara da TI, façam ele retomar!",--The override has been interrupted! They got to the IT guy, make him resume!
	loc_bex_67_01 = "Ach! Eles cortaram a energia! Liguem ela novamente, yeah?",--Ach! They cut the power! Get it up again, yeah?
	loc_bex_67_02 = "Policiais idiotas desligaram a energia. Vocês precisam ligá-la novamente!",--Dwankie kerels turned off the power. You gotta get it going again!
	loc_bex_67_03 = "Parece que eles desligaram a energia, amigos. Vocês precisam religá-la.",--Looks like they switched off the power, friends. You need to restart it.
	loc_bex_67_04 = "A energia caiu! Malditos policiais! Liguem ela novamente!",--The power is down! Blerrie kerels! Turn it back on!
	loc_bex_67_05 = "Eles desligaram a eletricidade, coloquem a energia para funcionar novamente, yeah?",--They turned off the electricity, get the juice flowing again, yeah?
	loc_bex_68_01 = "E agora o que? Parece que um backup do firewall está em execução. Encontrem um computador para finalizá-lo.",--Now what? Looks like a firewall backup is running. Find a computer to terminate it with.
    loc_bex_68_02 = "O banco possui um backup de firewall. Vocês terão que encontrar o computador certo para terminá-lo, yeah?",--The bank has a backup software firewall. You'll have to find the right computer to kill it, yeah?
    loc_bex_68_03 = "Um pouco fora do meu jogo hoje amigos. Temos um backup do firewall aqui. Vocês conseguem localizar o computador correto para desligá-lo?",--A bit off my game today friends. Missed the software firewall backup. Can you find the correct computer and turn it off? 
    loc_bex_69_01 = "Encontrem o computador.",--Find that computer.
    loc_bex_69_02 = "Vocês já encontraram o computador?",--Have you found the computer yet?
    loc_bex_69_03 = "O computador certo tem que estar por aí.",--The right computer has to be around there somewhere.
    loc_bex_69_04 = "Vocês precisam parar esse firewall.",--You need to stop that firewall.
	loc_bex_70_01 = "Bom, isso funcionou! Agora cheguem até o cofre!",--Good, that did it! Now get to the vault!
	loc_bex_70_02 = "Ótimo! Agora, corram até o cofre. Chop chop!",--Nice! Now, hurry over to the vault. Chop chop!
	loc_bex_70_03 = "Certo, agora sigam para o cofre, yeah?",--Ok, now make your way to the vault, yeah?
	loc_bex_71_01 = "O que estão esperando?",--What are you waiting for?
	loc_bex_71_02 = "Parem de vadiar e sigam para o cofre!",--Stop loitering and get over to the vault!
	loc_bex_71_03 = "O cofre não vai se abrir sozinho...",--The vault's not going to open itself...
	loc_bex_71_04 = "Vocês estão perdendo tempo amigos.",--You're wasting time friends.
	loc_bex_71_05 = "Sem tempo para uma pausa para tortilla, yeah?",--No time for a tortilla break, yeah?
	loc_bex_71_06 = "O que há de errado com vocês seus idiotas? Beberam muito na noite passada? Mexam-se!",--What's wrong with you chops? Too much to drink last night? Get moving!
	loc_bex_72_01 = "Ach, esse cofre não vai abrir fácil!",--Ach, that vault is not going to open easily!
	loc_bex_72_02 = "Vlad, seu merda! Você disse que o cofre seria fácil!",--Vlad, you chop! You said the vault was going to be easy!
	loc_bex_72_03 = "Oh céus... isso não vai ser como quebrar um ovo, yeah?",--Oh, dear... that's not going to be like cracking an egg, yeah?
	loc_bex_73_01 = "O Cofre está totalmente bloqueado.",--The Vault is fully locked down.
	loc_bex_73_02 = "Vocês causaram muito tumulto, o cofre está completamente bloqueado.",--You made too much of a ruckus, the vault is completely locked down.
	loc_bex_73_03 = "Eles tem o cofre protegido até o último parafuso.",--They've got the vault secured to the last bolt.
	loc_bex_74_01 = "Hora de trazer a Besta! Vão para fora e limpem a praça!",--Time to bring in the Beast! Get outside and clear the square!
	loc_bex_74_02 = "Mas o Velho Locke tem uma bela coisinha para vocês. Saiam e limpem a praça!",--But old Locke has a nice little dinges coming for you. Go out and clear the square!
	loc_bex_74_03 = "Se vocês se apressarem para fora e limpar a praça, consegui uma coisinha para vocês. Hora de enviar a Besta!",--If you hurry outside and clear the square, I've got a little something for you. Time to send in the Beast!
	loc_bex_75_01 = "Saem daí e vão limpar aquela praça, yeah?",--Get out there and clear the square, yeah?
    loc_bex_75_02 = "Não vou poder cuidar disso até que a praça esteja limpa.",--Can't take care of this until the square is clear.
    loc_bex_75_03 = "Nós precisamos limpar a praça, chop chop!",--We need the square cleared, chop chop!
    loc_bex_75_04 = "Ainda estão bloqueando bem a praça, limpem tudo!",--Still too much blocking the square, get it cleared!
	loc_bex_76_01 = "Agora coloquem um pouco de fumaça para que o piloto saiba onde jogar o equipamento.",--Now, pop some smoke out there so the pilot knows where to drop the equipment.
	loc_bex_76_02 = "O piloto precisará de um sinal de onde jogará a Besta. Joguem um pouco de fumaça!",--The pilot will need a signal where to drop the Beast. Drop some smoke!
	loc_bex_76_03 = "Coloquem um sinal de fumaça para o piloto ver!",--Set out a smoke signal for the pilot to zero in on!
	loc_bex_77_01 = "Não posso jogar o equipamento até vocês prepararem a fumaça!",--Can't drop the equipment until you arrange the smoke!
	loc_bex_77_02 = "Não se esqueçam do sinal de fumaça, amigos.",--Dont' forget that smoke signal, friends.
	loc_bex_77_03 = "O piloto não pode circular para sempre, coloquem essa fumaça!",--The pilot can't circle around there forever, get that smoke out! 
	loc_bex_78_01 = "Certo, esperem um pouco.",--Ok, hold on for a while.
	loc_bex_78_02 = "Apenas me deem um segundo...",--Just give me a second...
	loc_bex_78_03 = "Bom, agora apenas esperem um minuto...",--Good, now just wait a minute...
	loc_bex_79_01 = "Atenção idiotas! Entrega chegando!",--Heads-up you chops! Incoming Delivery!
	loc_bex_79_02 = "Cuidado de cima, amigos! A Besta vem do alto!",--Look out above, friends! The beast cometh from on high!
	loc_bex_79_03 = "Está a caminho, vai chegar a qualquer momento!",--It's on the way, any second now!
	loc_bex_80_01 = "Não é o melhor local, mas foi bom o bastante, yeah?",--Not the best drop, but good enough, yeah?
	loc_bex_80_02 = "A mira estava um pouco fora, mas não foi tão mal.",--The aim was a little off, but not too bad.
	loc_bex_80_03 = "Não foi perfeito, mas sete pontos pelo esforço!",--Not perfect, but seven points for effort!
	loc_bex_81_01 = "Agora coletem as bolsas, e montem a Besta!",--Now collect those bags, and get to assembling the Beast!
	loc_bex_81_02 = "Hora de montar essa furadeira. Peguem essas bolsas.",--Time to put that drill together. Get those bags.
	loc_bex_81_03 = "Peguem essas bolsas de equipamentos e preparem a Besta para a ação!",--Take those equipment bags and set the Beast up for action!
	loc_bex_82_01 = "Peguem as bolsas com equipamento!",--Get the equipment bags!
	loc_bex_82_02 = "Vocês precisam montar a furadeira!",--You gotta set up the drill!
	loc_bex_82_03 = "Nunca entraremos nesse cofre sem a Besta. Montem tudo!",--Never going to get in that vault without the Beast. Set it up!
	loc_bex_83_01 = "É um belo conjunto de equipamento, yeah?",--It's a nice piece of kit, yeah?
	loc_bex_84_01 = "Agore liguem ela. E mantenham os policiais longe!",--Now start it up. And keep the kerels away!
	loc_bex_84_02 = 'Certo, agora liguem ela e mantenham os "Fedelares" estúpidos longe dela!',--OK, now turn it on and keep those dwankie federales away from it!
	loc_bex_84_03 = "Booooooooa. É adoravel, yeah? Coloquem para funcionar e certifiquem-se de que os policiais não irão interferir!",--Niiiiiiice. It's lovely, yeah? Get it going and make sure the kerels don't interfere!
	loc_bex_85_01 = "Liguem a Besta!",--Start the Beast!
	loc_bex_85_02 = "Vocês precisam ligar a furadeira.",--You gotta start the drill.
	loc_bex_85_03 = "Vocês precisam começar a furar.",--You need to start drilling.
	loc_bex_85_04 = "Vocês estão tendo problemas para ligar a Besta?",--Are you having trouble getting the Beast to run?
	loc_bex_86_01 = "Protejam a furadeira dos policiais.",--Protect the drill from the kerels.
	loc_bex_86_02 = 'Esses "Federales" irão querer parar a Besta. Não deixem!',--Those federales are going to want to stop the Beast. Don't let them!
	loc_bex_86_03 = "Tenham certeza de que a polícia idiota não chegue perto da furadeira!",--Make sure those domkop police don't get near the drill!
	loc_bex_87_01 = "Vocês precisam proteger a Besta!",--You gotta protect the Beast!
	loc_bex_87_02 = "Mantenham a polícia longe da furadeira.",--Keep the police away from the drill.
	loc_bex_87_03 = "Esses merdas irão destruir a Besta se vocês deixarem se aproximar muito!",--Those kerels will kill the Beast if you let them get too close!
	loc_bex_87_04 = "Continuem protegendo a furadeira.",--Keep protecting the drill.
	loc_bex_88_01 = "Ach! Essa coisa quebrou. Peguem algumas peças sobressalentes e reparem ela!",--Ach! The dinges has broken down. Get some spare parts and repair it!
	loc_bex_88_02 = "Tem um problema com a Besta. Rust falou que havia arrumado! Peguem umas peças e cuidem disso, yeah?",--There's a problem with the Beast. Rust said he fixed it! Get some parts and take care of it, yeah?
	loc_bex_88_03 = "Tem algo errado com a furadeira. Vocês precisam consertá-la.",--There's something wrong with the drill. You gotta repair it.
	loc_bex_89_01 = "A furadeira já está ligada novamente?",--Is the drill up again?
	loc_bex_89_02 = "Vocês ainda estão tendo problemas com a Besta?",--Are you still having problems with the Beast?
	loc_bex_89_03 = "Vocês precisam ligar a furadeira.",--You need to get the drill going.
	loc_bex_89_04 = "Vamos lá amigos, só mais um pouco. Coloquem essa coisa para funcionar de novo!",--Come on friends, just a little more. Get that dinges running again!
	loc_bex_90_01 = "Há muita gente ao redor da área do banco, vocês vão precisar limpar o caminho para que a van possa chegar até vocês.",--There's a lot of commotion in the area around the bank, you should clear it up for the van to be able to reach you.
    loc_bex_90_02 = "A Van terá muitos problemas para se aproximar se vocês não limparem a área ao redor do banco.",--The van will have trouble getting through if you don't clear out the area around the bank.
    loc_bex_90_03 = "Muitas pessoas e carros bloqueando o acesso ao banco. Limpem a área para a van de fuga poder passar.",--Lots of people and cars blocking access to the bank. Clear out the area so the escape van can get through.
    loc_bex_91_01 = "Vocês precisam limpar a área externa do banco.",--You need to clear the area outside the bank.
    loc_bex_91_02 = "A van não vai poder passar até que vocês limpem a área.",--The van can't get through unless you clear the area.
    loc_bex_91_03 = "Limpem a praça e as ruas ao redor do banco.",--Clean up the square and streets around the bank.
    loc_bex_91_04 = "Tenho uma van esperando, mas não poderão passar até que toda a área esteja limpa desses merdas.",--I have a van waiting, but it can't get through until the area is clear.
    loc_bex_92_01 = "Porra! Gás no cofre! Usem o sistema de ventilação para limpar isso.",--Blerrie! Gas in the vault! Use the ventilation system to clear it.
    loc_bex_92_02 = "Uma coisa de cada vez, yeah? Liberem a ventilação para limpar esse gás.",--One thing after another, yeah? Turn up the ventilation to clear out that gas.
    loc_bex_92_03 = "Se vocês ligarem o sistema de ventilação para o máximo, vocês poderão eliminar todo esse gás.",--If you turn the ventilation system to full, you should be able to clear out that gas.
    loc_bex_93_01 = "Limpem essa porra de gás.",--Clear out the gas.
    loc_bex_93_02 = "Ainda tem gás no cofre.",--There's still gas in the vault.
    loc_bex_93_03 = "Não é nada bom respirar aquele gás, por tanto limpem isso, yeah?",--Not too good breathing that gas, so clear it out, yeah?
    loc_bex_93_04 = "Ainda estão com problemas com o gás?",--Still having trouble with the gas?
	loc_bex_94_01 = "Agora peguem o quanto da mercadoria do Vlad vocês puderem carregar e levem-na para a van!",--Now grab as much of Vlad's merchandise as you can carry and get it out to the van!
	loc_bex_94_02 = "Certo, agora vocês podem levar todo o loot especial do Vlad e trazê-los para a van.",--OK, now you can take all of Vlad's special loot and bring it out to the van.
	loc_bex_94_03 = "Certo, agora apressem-se e coletem todo o loot 'precioso' do Vlad e levem eles para fora, rápido rápido!",--Right, now hurry and collect all of Vlad's "precious" loot and take it outside, chop chop!
	loc_bex_95_01 = "Continuem coletando coisas para o Vlad!",--Keep collecting things for Vlad!
    loc_bex_95_02 = "Peguem a mercadoria do Vlad!",--Get Vlad's merchandise!
    loc_bex_95_03 = "Se apressem e peguem o máximo que vocês puderem!",--Hurry up and take all you can!
    loc_bex_95_04 = "Continuem, peguem o máximo que puderem!",--Keep going, get as much as you can!
	loc_bex_96_01 = "Certo, Vlad parece feliz. Vocês podem sair quando quiserem, amigos!",--OK, Vlad seems happy. You can leave at your discretion, friends!
	loc_bex_96_02 = "Beleza idiotas, isso é o bastante para o Vlad. Saiam daí assim que estiverem prontos!",--Alright you chops, that's enough for Vlad. Get out of there as soon as you're ready!
	loc_bex_96_03 = "Quando se sentirem prontos, fujam!",--When you feel ready, make your escape!
	loc_bex_97_01 = "Tudo pronto, amigos!",--You're all done, friends!
    loc_bex_97_02 = "É hora de fugir!",--Time to make a run for it!
    loc_bex_97_03 = "Vocês precisam ir, seus idiotas, antes que todos os filhos das putas do México caiam em cima de vocês!",--You need to leave, you chops, before all the kerels in Mexico come down on you!
    loc_bex_97_04 = "Vamos lá amigos... VAMOS!",--Come on friends... GO!
    loc_bex_98_01 = "Ah, vocês cruzaram os lasers! Precisam encontrar um jeito de desligar esse sistema.",--Ach, you crossed the lasers! You gotta find a way to shut that system off.
	loc_bex_98_02 = "Os lasers foram acionados. Vocês precisam desativar o sistema de segurança, yeah?",--The lasers have been triggered. You need to shut the security system down, yeah?
	loc_bex_98_03 = "Cuidado, amigos! O sistema de laser disparou. Vocês precisam desligá-lo de alguma forma.",--Look out, friends! The laser system has gone off. You'll need to shut it down somehow.
	loc_bex_99_01 = "Cuidem desse sistema de segurança ou não poderão passar.",--Take care of that security system or you won't be able to get past.
	loc_bex_99_02 = "Vocês precisam desativar esse sistema de lasers.",--You need to bypass that laser system.
	loc_bex_99_03 = "Vocês ainda não conseguiram desativar o sistema?",--Have you not been able shut down the sytem yet?
	loc_bex_100_01 = "Merda! Eles estão inundando o cofre com gás tóxico! Esperem até ele limpar!",--Blerrie! They're flooding the vault with toxic gas! Wait until it clears!
	loc_bex_100_02 = "Eles estão inundando o cofre com gás! Isso nunca vai suave, yeah? Vocês terão que esperar até que esteja limpo.",--They're flooding the vault with gas! It never goes smoothly, yeah? You'll have to wait until it's clear.
	loc_bex_100_03 = "Cuidado com o gás, amigos! Esperem até ele se dissipar!",--Look out for the gas, friends! Wait until it dissipates!
	loc_bex_101_01 = "Esperem até que esteja tudo limpo.",--Just wait until it's clear.
    loc_bex_101_02 = "Deve estar limpo logo logo.",--Should be clear soon.
    loc_bex_101_03 = "O gás deve se dissipar em 1 minuto.",--The gas should be gone in a minute.
    loc_bex_102_01 = "Agora peguem o máximo da mercadoria do Vlad que puderem carregar e levem até o caminhão de lixo!",--Now grab as much of Vlad's merchandise as you can carry and get it out to the garbage truck!
    loc_bex_102_02 = "OK, agora vocês podem pegar todas as joias do Vlad. O caminhão que vocês queriam já está esperando lá fora!",--OK, now you can take all of Vlad's jewelry. The truck you wanted is waiting outside!
    loc_bex_102_03 = 'Colete todos os loots "preciosos" do Vlad e levem tudo para o caminhão de lixo, rápido!',--Collect all of Vlad's \"precious\" loot and take it to the garbage truck, chop chop!
    loc_bex_103_01 = "Vocês pediram o caminhão, agora peguem todo o loot para levar até ele!",--You ordered the truck, so get the loot to it!
    loc_bex_103_02 = "Comprei um caminhão de lixo para vocês, agora basta apenas enchê-lo de loots preciosos!",--I got you a garbage truck, now you just gotta fill it with loot!
    loc_bex_103_03 = "Levem as joias do Vlad até o caminhão de lixo!",--Get Vlad's jewelry to the garbage truck!
    loc_bex_104_01 = "Caralho! Os federais latinos estão derrubando as paredes!",--Ach! The federales are breaching walls!
    loc_bex_104_02 = "Isso não é nada que minha gangue não consiga lidar, yeah?",--It's nothing my crew can't handle, yeah?
    loc_bex_105_01 = "Os federais latinos estão usando cargas de explosivos para abrir outra parede!",--The federales are using shape charges to open up another wall!
    loc_bex_105_02 = "Eu acho que vocês farão um pouco mais, yeah?",--I think they'll do a bit more, yeah?
    loc_bex_106_01 = "Esses arrombados latinos estão vindo do telhado!",--Federales are coming in from the roof!
    loc_bex_107_01 = "Os federais latinos estão bombeando o gás pelo sistema de ventilação! Fiquem longe dele até que se dissipe!",--The Federales are pumping gas through the ventilation system! Stay away from it until it dissipates!
    loc_bex_107_02 = "Os arrombados encheram o lugar com gás! Esperem um pouco até que tudo fique limpo antes de entrar.",--Dwankie kerels have filled the place with gas! Wait until it clears before going in.
    loc_bex_107_03 = "Tenham cuidado, amigos! Esses policiais mexicanos estão espalhando gás no sistema de ventilação. Irá se dissipar logo logo, então fiquem longe até que isso aconteça!",--Watch it, friends! Those laanie Mexican police are spreading gas in the vent system. It will clear soon, so stay away until it does!
    loc_bex_108_01 = "Vocês devem ter acionado algum sistema de segurança. Usem uma furadeira para sair de novo!",--You must have triggered a failsafe. Use a drill to get out again!
    loc_bex_108_02 = "Porra, outra segurança à prova de falhas. Vocês vão precisar da furadeira.",--Ach, another security failsafe. You're going to need to drill yourselves out.
    loc_bex_108_03 = "Um portão reserva foi ativado, usem a furadeira para abri-lo!	",--A backup gate has been activated, use a drill to open it up!
    loc_bex_109_01 = "Vocês não conseguirão sair a menos que usem uma furadeira!",--You're not getting out of there unless you use a drill!
    loc_bex_109_02 = "Preparem uma furadeira para que possam fugir.",--Set up a drill so that you can escape.
    loc_bex_109_03 = "Esse portão não irá abrir sem um grande buraco nele.",--That gate is not opening without a big drill hole in it.
	loc_bex_110_01 = "Se vocês usarem a tirolesa, vocês vão poder acelerar um pouco o processo, yeah?",--If you use ziplines, you can speed it up a bit, yeah?
    loc_bex_110_02 = "Usem a tirolesa se quiserem agilizar todo o processo.",--Use ziplines if you want to speed it up.
    loc_bex_110_03 = "Boa hora para a tirolesa, talvez.",--Good time for ziplines, maybe.
    loc_bex_111_01 = "OK, bundões. É hora de trazer a Besta!",--OK, you chops. Time to bring in the Beast!
    loc_bex_111_02 = "Preparados para uma surpresa maravilhosa, cortesia do Velho Locke?",--Ready for a nice surprise, courtesy of old Locke?
    loc_bex_111_03 = "Tenho algo a caminho para vocês que será um pesadelo para esse cofre!",--Got something on the way for you that's going to be a kakspul of trouble for that vault!

	-- Legendas (Vlad)
	vld_bex_07_01 = "Ainda bem que Vlad enviou esta termite para usarem, né?",--Good thing Vlad sent you that thermite to use, eh!",
	vld_bex_19_01 = "Ele morreu? Cace... a minha esposa vai me dar uma bronca se ele estiver.",--Is he dead? Oh sh... my wife will give me an earful at dinner if he is.",
	vld_bex_07_02 = "Não esta coisa, esta coisa é nano-termite! Foi roubado da Suécia para mim. Bem forte.",--Not this stuff, this shit is nano-thermite! Was smuggled out of Sweden for me. Extra strong.",
	vld_bex_10_01a = "Nojento, correndo por aí com coisas e copinhos de café usados!",--Disgusting, running around with used coffee cups and things!",
	vld_bex_18_01 = "Eita, eu achei que iria funcionar!",--Oh wow, I really thought that would work!",
	vld_bex_05_01 = "Coisa pra caralho está acontecendo em Washington agora.",--Lot's of shit happening in Washington right now.",
	vld_bex_10_01b = "Nojento, correndo por aí com coisas e copinhos de café usados!",--Disgusting, running around with used coffee cups and things!",
	vld_bex_12_01a = "Merda, esqueci de uma coisa. Se vocês acharem qualquer fita dentro daquele cofre, peguem ele, por favor... hã, eu... eu sei lá, talvez... queime aquilo em algum lugar depois, ok?",--Shit, I forgot something. If you find any tapes in that vault, take them too please... uh I.. I don't know, maybe... maybe burn them somewhere later, OK?",
	vld_bex_11_01 = "Isto é que nem quando Vlad era jovem, mas menos tiroteio. Incrível, ninguém morreu até agora.",--This is like when Vlad was younger, but much less shooting. Incredible, no one is dead yet.",
	vld_bex_02_01 = "Em México, eles têm um instrumento músical que você toca num maxilar de uma mula! Dar pra acreditar nisso!? Eu amo este país!",--In Mexico, they have a musical instrument where you play on the jawbone of a mule! Can you believe it!? Ha! I fucking love that country!",
	vld_bex_03_01 = "Vou ficar de olho em vocês. Isso é importante pro Vlad.",--I'm gonna keep my eye on you. This one is important to Vlad.",
	vld_bex_08_01c = "Eu já estive nesse banco uma vez, uns anos atrás. O gerente deste bando é um idiota. Ele manteve o seu cartão de acesso em um cofre pessoal, não me lembro aonde.",--I have been in the bank one time, a few years ago. The bank manager is an idiot. He keeps his access key in a personal safe, but I don't remember where.",
	vld_bex_10_01c = "Nojento, correndo por aí com coisas e copinhos de café usados!",--Disgusting, running around with used coffee cups and things!",
	vld_bex_11_02 = "No meu velho bairro, a gente atirávamos no ar e as ruas ficavam vazias. Bem efetivo.",--In my old neighborhood, we just shoot in the air and all the streets empty. Very effective.",
	vld_bex_12_01b = "Oh, merda, esqueci de uma coisa. Escutem, se alguns de vocês acharem uma fita, peguem ele, por favor... Eu sei lá, talvez queimar aquilo em algum lugar depois, ok?",--Oh, shit, shit, I forgot something. Listen, If you find any tapes, take them too please... I don't know maybe burn them somewhere later, OK?",
	vld_bex_12_01c = "Oh, merda! merda! esqueci de uma coisa. Escutem, se vocês acharem qualquer fita naquele cofre, peguem eles, por favor... Eu, hâ... talvez queime aquilo em algum lugar depois, ok?",--Oh, shit! shit! I forgot something. Listen, If you find any tapes in that vault, take them too please... I umm... maybe burn them somewhere later, OK?",
	vld_bex_18_02 = "Eita... isso não... ohoyoyoyo... isso não parece nada bem.",--Oh...That looks... Ohoyoyoyo... That looks, not very good.",
	vld_bex_19_02 = "Ei, filha da puta! Acorda. Sai daí antes que o cartel rouba a caminhonete!",--Hey, you fucker! Wake up. Get out of there before the cartels steal the truck!",
	vld_bex_21_02 = "Nah, ele vai ficar bem.",--Naaah, He'll be fine.",
	vld_bex_28_01 = "Eu... tô te dizendo. Ucrânia sabe fazer as melhores furadeiras. Na próxima vez, Locky, compra um de lá que não vai quebrar.",--I... I'm telling you. Ukraine makes the best drills. Next time Locky, buy one from there and it will not break.",
	vld_bex_intro_01_01 = "Bem, eu, eu, eu estou aqui para ajudar. Essa merda é muito importante e preciso ter certeza de que farão isso certo.",--Well, I, I, I am here to help. This shit is too important and I have to make sure you do it right.
	vld_bex_intro_01_02 = "Não se preocupe Locky, Vlad ficará quieto como um rato bebendo Sputniks!",--Don't worry Locky, Vlad will be quiet as mouse drinking Sputniks!
	vld_bex_intro_02_01 = "Ei! Ei! Ei Ei Eeeei! Locky!",--Hey! Heey! Hey Hey Heeey! Locky!
	vld_bex_intro_02_02 = "Ei, Vlad é da Ucrânia, não Rússia!",--Hey, Vlad is from Ukraine, not Russia!
	vld_bex_intro_02_03 = "Isso é muito importante para mim. Estou aqui para ter certeza de que não irão fuder com isso, sim?",--This one is very important to me. I'm here to make sure you don't screw it up, yes?
	vld_bex_intro_02_04 = "Que piloto? Do que está falando, estou apenas dando uns conselhos.",--What driver? What are you talking about, I'm just giving some advice.
	vld_bex_01_01 = "Você precisa dizer essa merda para eles? O que são eles, você os trata como bebês?",--You need to tell them that shit? What are they, you treat them like babies?
	vld_bex_01_02 = "Quando terminarem, tragam umas tortillas e faremos um churrasco ou algo assim. Vlad fará os Sputniks!",--When you're finished, bring back some tortillas and we'll have a barbecue or something. Vlad will make the Sputniks!
	vld_bex_01_03 = "E tragam umas chimichangas ou algo assim!",--And bring me back some chimichangas or something!
	vld_bex_04_01 = "Vocês acham que eles tem muitas cabras no México?",--You think they have lots of goats in Mexico?
	vld_bex_06_01 = "De novo com os animais? O que há com você e animais? Quem liga?",--Again with the animals? What is it with you and animals? Who gives a shit?
	vld_bex_08_01a = "Estive nesse banco uma vez, uns anos atrás. O gerente é um idiota. Ele mantém seu Cartão de Acesso em um cofre pessoal, mas na verdade não me lembro onde.",--I have been in the bank one time, a few years ago. The bank manager is an idiot. He keeps his access key in a personal safe, but I don't actually remember where.
	vld_bex_08_01b = "Estive nesse banco uma vez, uns anos atrás. O gerente é um idiota. Ele mantém seu Cartão de Acesso em um cofre pessoal, mas não me lembro onde.",--I have been in the bank one time, a few years ago. The bank manager is an idiot. He keeps his access key in a personal safe, but I don't remember where.
	vld_bex_09_01 = "O que está demorando tanto?",--What is taking so much time?
	vld_bex_09_01a = "O que é isso, alguma merda de cena criminal de TV?",--What is this, some kind of crime scene tv shit?
	vld_bex_09_01b = "O que é isso, alguma merda de cena criminal de TV?",--What is this, some kind of crime scene tv shit?
	vld_bex_09_01c = "O que é isso, alguma merda de cena criminal de TV?",--What is this, some kind of crime scene tv shit?
	vld_bex_13_01a = "Apressem-se, eu quero ver se a minha mercadoria está bem.",--Hurry up, I want to see that my merchandise is OK.
	vld_bex_13_01b = "Apressem-se, eu quero ver se a minha mercadoria está bem.",--Hurry up, I want to see that my merchandise is OK.
	vld_bex_13_01c = "Apressem-se, Apressem-se, eu quero ver se a minha mercadoria está bem.",--Hurry up, Hurry up, I want to see that my merchandise is OK.
	vld_bex_14_01a = "Ah, aí está minha bela mercadoria! Peguem, peguem!",--Ah, there is my beautiful merchandise! Take it, Take it!
	vld_bex_14_02 = "Ah, é... apenas... vocês sabem, algumas joias e outras coisas.",--Ah, Is... just... you know, some jewels and things.
	vld_bex_14_03 = "É, pertenceu a uns velhos parentes, herança de família, vocês sabem?",--Eh, It belonged to old relatives, family heirlooms, you know?
	vld_bex_15_01 = "Ah, aí estão minhas preciosidades! Rápido, Rápido, peguem-nos!",--Ah, There are my precious things! Hurry, Hurry, take them!
	vld_bex_15_02 = "Vocês conhecem os Romanovs, né?",--You know the Romanovs, eh?
	vld_bex_15_03 = "Vocês têm... É coisa antiga de família. Não se importem... apenas tirem isso daí!",--You got... Is old family thing. Don't you mind... just get it out of there!
	vld_bex_16_01 = "Essa é uma boa pergunta, Locky...",--That is a very good question, Locky....
	vld_bex_16_01a = "Não se preocupem meus amigos, Vlad conseguiu uma ajuda!",--Don't worry my friends, Vlad has arranged some help!
	vld_bex_16_01b = "Certo pessoal, Vlad arranjou um jeito de entrarem no banco.",--OK, guys, Vlad has arranged a way into the bank for you.
	vld_bex_16_02 = "Isso é... coisa velha e família. Não liguem para isso...",--It's... Is old family things. Don't you pay attention to it...
	vld_bex_16_02a = "Meu cunhando. Se lembram dele, sim? Ele veio de uma festa em Chihuahua para ajudar!",--My brother-in-law. You remember him, yes? He came down from a party in Chihuahua to help!
	vld_bex_16_02b = "Se lembram do meu cunhado? Bem, ele está vindo de Chihuahua para lhes dar uma mão.",--You remember my Brother-in-law? Well, he's coming down from Chihuahua to give you a hand.
	vld_bex_17_01 = "Isso vai ser ótimo... Ele chegará em breve.",--It's going to be great... He will be there soon.
	vld_bex_17_02 = "Não se preocupem, tudo vai ficar bem. AH! Olha ele ali!",--Don't worry, it will be fine. Ah! Here he comes!
	vld_bex_20_01a = "Pessoal, melhor dizer para o meu cunhado pisar fundo!",--Guys, you better tell my brother-in-law to step on it!
	vld_bex_20_01b = "Hey hey hey pessoal, Pessoal! É melhor dizer ao meu cunhado para pisar fundo nisso!",--Hey hey hey guys, Guys! you better tell my brother-in-law to step on it!
	vld_bex_20_01c = "Ei pessoal, melhor dizerem para o meu cunhado pisar fundo!",--Hey guys, you better tell my brother-in-law to step on it!
	vld_bex_21_01 = "Ah, aí vai ele. Hahaha, ótimo.",--Ah, there he goes. Hahaha, Good.
	vld_bex_22_01 = "Eu, eu não entendo, por que vocês apenas não hackeiam os computadores?",--I, I don't understand, why don't you just hack the computers?
	vld_bex_23_01 = "Se ele der trabalho, quebrem alguns dedos.",--If he gives you any trouble, break some fingers.
	vld_bex_23_02 = "Por que não? É eficaz!",--Why not? It's effective!
	vld_bex_24_01 = "O que estão fazendo dando voltas com ele? Apenas batam na cabeça dele com umas maracas ou algo assim e ele irá falar.",--What are you doing leading him around? Just hit him in the head with a maracas or something and he will talk.
	vld_bex_24_02 = "Acho que ele irá fazer melhor com uma porrada na cabeça.",--I still think he will do better with a hit in the head.
	vld_bex_25_01 = "Ugh, o quão lerdo é esse cara?",--Ugh, How slow is this guy?
	vld_bex_26_01 = "Isso é uma grande... furadeira.",--That's one big...drill.
	vld_bex_27_01a = "Por que isso está demorando tanto?",--Why is it taking so long?
	vld_bex_27_01b = "Ugh, por que isso está demorando tanto?",--Ugh, Why is it taking so long?
	vld_bex_29_01 = "Apenas comecem a atirar, isso move as pessoas!",--Just start shooting, that gets people moving!
	
	-- Objetivos
	hud_heist_bex1 = "Vá para dentro do banco.",--Get inside the bank
	hud_heist_bex1_hl = "Entre no Banco",--Enter the bank
	hud_heist_bex10 = "Monte 'A Besta' no cofre.",--Assemble "The Beast" by the vault.
	hud_heist_bex10_hl = "Monte a Furadeira",--Assemble the drill
	hud_heist_bex11 = "Proteja a furaderia dos policiais.",--Protect the drill from the incoming cops.
	hud_heist_bex11_hl = "Proteja a Furadeira",--Protect the drill
	hud_heist_bex12 = "Colete todas as partes necessárias e repare a furadeira.",--Collect the needed parts and repair the drill.
	hud_heist_bex12_hl = "Repare a Furadeira",--Repair the drill
	hud_heist_bex14 = "Digite o código correto para acessar o cofre.",--Enter the correct code to access the vault.
	hud_heist_bex14_hl = "Abra o Cofre",--Open the vault
	hud_heist_bex15 = "Roube todo o loot e assegure-o na van.",--Steal all the loot and secure it in the van.
	hud_heist_bex15_hl = "Assegure o Loot",--Secure the loot
	hud_heist_bex16 = "Fuja na van!",--Escape in the van!
	hud_heist_bex16_hl = "Fuga Disponível",--Escape available
	hud_heist_bex17 = "Conecte a corrente em ambos: o portão e a caminhonete.",--Attach the chain to both the gate and to the truck.
	hud_heist_bex17_hl = "Conecte a Corrente",--Attach the chain
	hud_heist_bex18 = "Restaure a energia para que o técnico de TI possa continuar trabalhando.",--Restore power so the IT technician can continue working.
	hud_heist_bex18_hl = "Restaure a Energia",--Restore power
	hud_heist_bex19 = "Corte os cabos certos para abrir a porta eletrônicamente bloqueada.",--Cut the correct wires to open the electronically sealed door.
	hud_heist_bex19_hl = "Corte os Cabos",--Cut the wires
	hud_heist_bex2 = "Encontre uma maneira de passar pelos portões para ganhar acesso as salas internas do banco.",--Find a way past the gates to gain access to the bank's inner rooms
	hud_heist_bex2_hl = "Passe pelos Portões",--Get past the gates
	hud_heist_bex20 = "Encontre uma maneira de abrir o cofre.",--Find a way to open the vault.
	hud_heist_bex20_hl = "Abra o Cofre",--Open the vault
	hud_heist_bex21 = "Procure nos escritórios e encontre o cofre do gerente.",--Search the offices and find the manager's safe.
	hud_heist_bex21_hl = "Encontre o Cofre",--Find the safe
	hud_heist_bex22 = "Tente achar um objeto para copiar a digital do gerente.",--Try to find an object to copy the manager's fingerprint from.
	hud_heist_bex22_hl = "Encontre as Digitais do Gerente",--Find the manager's fingerprints
	hud_heist_bex23 = "Abra o cofre usando a digital do gerente e pegue a chave.",--Open the safe using the manager's fingerprint and take the key.
	hud_heist_bex23_hl = "Pegue a Chave",--Get the key
	hud_heist_bex24 = "Acesse o interior do banco abrindo o portão de segurança com a chave.",--Access the bank's interior by opening the security gate with the key.
	hud_heist_bex24_hl = "Abra o Portão",--Open the gate
	hud_heist_bex25 = "Encontre o manual de instrução para o sistema de segurança do banco.",--Find the instruction manual for the bank's security system.
	hud_heist_bex25_hl = "Encontre o Manual",--Find the manual
	hud_heist_bex26 = "Tente achar o diagrama do circuito do sistema de segurança do banco.",--Try to find the circuit diagram of the bank's security system.
	hud_heist_bex26_hl = "Encontre o Diagrama do Circuito",--Find the circuit diagram
	hud_heist_bex27 = "Tenha certeza que a praça da cidade está livre de policiais.",--Make sure the town square is cleared of cops.
	hud_heist_bex27_hl = "Limpe a Praça",--Clear the square
	hud_heist_bex28 = "Joguem a fumaça vermelha para sinalizar ao piloto do helicóptero para retirada.",--Deploy red smoke to signal the helicopter pilot for pickup.
	hud_heist_bex28_hl = "Sinalize ao Piloto",--Signal the pilot
	hud_heist_bex29 = "Ative o sistema de ventilação para limpar o gás.",--Activate the ventilation system to clear the air of gas.
	hud_heist_bex29_hl = "Limpe o Gás",--Clear out the gas
	hud_heist_bex3 = "Encontre uma maneira de abrir a barreira bloqueada eletrônicamente.",--Find a way to open the electronically sealed security barrier.
	hud_heist_bex3_hl = "Abra a Barreira de Segurança",--Open the security barrier
	hud_heist_bex30 = "Desative os lasers de segurança para evitar que acionem o alarme.",--Shut down the security lasers to avoid triggering the alarm.
	hud_heist_bex30_hl = "Desligue os Lasers",--Shut down the lasers
	hud_heist_bex31 = "Mova qualquer carro fora do caminho para liberar acesso para a van de fuga.",--Move any cars out of the way to clear access for the escape van.
	hud_heist_bex31_hl = "Limpe a Rua",--Clear the street
	hud_heist_bex32 = "Espere até o cunhado do Vlad chegar.",--Wait at the bank until Vlad's brother-in-law arrives.
	hud_heist_bex32_hl = "Espere no Banco",--Wait at the bank
	hud_heist_bex33 = "Conecte a corrente em ambos: o caminhão e a janela do bancário.",--Attach the chain to both the truck and the teller windows.
	hud_heist_bex33_hl = "Conecte a Corrente",--Attach the chain
	hud_heist_bex34 = "Sinalize ao motorista que é hora de começar a puxar.",--Signal to the driver that it's time to start pulling.
	hud_heist_bex34_hl = "Sinalize ao Motorista",--Signal the driver
	hud_heist_bex35 = "Comece a furar a porta do cofre.",--Start drilling through the vault door.
	hud_heist_bex35_hl = "Ligue a Furadeira",--Start the drill
	hud_heist_bex36 = "Use a furadeira para quebrar a parede e fugir.",--Use the drill to break through the wall and escape.
	hud_heist_bex36_hl = "Saia",--Get out
	hud_heist_bex37 = "Diga ao técnico de TI para retomar o anulamento do bloqueio de segurança.",--Tell the IT technician to resume the security lockdown override.
	hud_heist_bex37_hl = "Retome o Anulamento",--Resume the override
	hud_heist_bex38 = "Encontre um pedaço de fita para usar para copiar a digital do gerente do banco.",--Find a piece of tape to use for copying the bank manager's fingerprint.
	hud_heist_bex38_hl = "Encontre uma Fita",--Find some tape
	hud_heist_bex4 = "Localize a Sala do Servidor dentro do banco.",--Locate the server room inside the bank.
	hud_heist_bex4_hl = "Encontre a Sala do Servidor",--Find the server room
	hud_heist_bex5 = "Encontre a pessoa responsável pelo departamento de TI do banco. Ele deve estar por volta dos escritórios no andar de cima.",--Find the person in charge of the bank's IT department. He should be around the offices on the upper floor.
	hud_heist_bex5_hl = "Encontre o cara da TI no Andar de Cima",--Find the IT guy on the upper floor
	hud_heist_bex6 = "Traga o técnico de TI para a Sala do Servidor para que ele possa anular o bloqueio de segurança.",--Bring the IT technician to the server room so that he can override the security lockdown.
	hud_heist_bex6_hl = "Leve o cara da TI até a Sala do Servidor",--Get the IT guy to the server room
	hud_heist_bex7 = "Mantenha os policiais longe da Sala do Servidor enquanto o técnico de TI está fazendo o anulamento da segurança.",--Keep the cops away from the server room while the IT technician is performing the security override.
	hud_heist_bex7_hl = "Afaste os Policiais",--Hold off the cops
	hud_heist_bex8 = "Encontre o código para o cofre do banco.",--Find the code to the bank's vault.
	hud_heist_bex8_hl = "Encontre o Código",--Find the code
	hud_heist_bex9 = "Espere até todas as partes da furadeira terem chegado.",--Wait until all the drill parts have arrived.
	hud_heist_bex9_hl = "Espere pelas Partes da Furadeira",--Wait for the drill parts
		}