Hooks:Add("LocalizationManagerPostInit", "areia_vai_se_foder", function(loc)
	LocalizationManager:add_localized_strings({
        --heist_sand_hl = "The Ukrainian Prisoner",
        --heist_sand = "The Ukrainian Prisoner",
        heist_sand_crimenet = "Eu tenho algo pra vocês, né? O meu velho chefe, Yufu Wang tá atrás de vocês e a tríade sequestraram o seu associado, Vlad Kozak. Eles vão torturar ele para abrir o bico e revelar a sua localização. Eles chamaram um dos profissionais para cuidar da interrogação, um filho da puta chamado Xun Kang, frio como um gelo, o cara que anda gerenciando os negócios naquele lado do lago. Eles prenderam o seu amigo dentro de um container nas docas do São Francisco. Vocês tem sorte que eu tenho um contato lá, né?\n\n» Infiltre nas docas\n» Resgate Vlad e fuja",--I've got something for you, right? My old boss Yufu Wang is coming after you and the triad has grabbed your associate, Vlad Kozak. Going to force your location out of him. They've brought back one of their top guys from Hong Kong to handle the interrogation, a piece of shit named Xun Kang, ruthless motherfucker, who has been running things on that side of the pond. They've got your man inside a shipping container in the San Francisco docklands. You're lucky I have a man inside, right?\n\n» Infiltrate the docklands\n» Find Vlad and escape
        heist_sand_briefing = "Beleza, idiotas, precisamos fazer isso rápido. A lealdade do Vlad para nós tá indo bem longe e se eles torturarem demais, vai deixar a gente numa situação de merda. Nós recebemos muita informações pelo contato do Jiu Feng nas docas. O lugar é cheio de segurança, que nós podemos usar para nossa vantagem. Assim que acharem Vlad, o nosso contato irá nos ajudar a tirar ele daqui. Jiu Feng vai te tirar pessoalmente com um barco. Depois disso, esse Ucraniano desgraçado vai estar nós devendo, com certeza!",--Ok you chops, we have to move quickly. Vlad's loyalty to us will only go so far, and if they break him it will leave us in a kakspul of trouble. Jiu Feng's insider at the docklands facility gave us a lot of intel. The place is set up for major surveillance, which we can use to our advantage. Once you find Vlad, our insider will help you move him. Jiu Feng has volunteered to get you out personally by boat. After we do this, that dwankie Ukranian will owe us one, for sure!

        -- Introduções
        loc_sand_intro1a_01 = "Tá, tá, tenho mais uma.",--OK, ok I've got another one.
        jfe_sand_intro1b_01 = "Me manda mais uma dessas frases que você acha que sabe.",--Hit me with another one of those phrases you think you know.
        loc_sand_intro1b_01 = "Nós temos tempo pra isso?",--Do we really have time for this?
        jfe_sand_intro1b_02 = "Bom, não é que vai fazer essa van ir mais lenta, me ajuda a concentrar um pouco, né?",--Well, not like it's going to make this van go any slower! It helps me concentrate, right?
        loc_sand_intro1b_02 = "Tá, lá vem... Wuh duh ma huh tah duh fong kwong duh wai shung!",--Right, here goes... Wuh duh ma huh tah duh fong kwong duh wai shung!
        jfe_sand_intro1b_03 = "Ainda Mandarim, cara. Fez menos sentindo do que o último.",--Still Mandarin, Chief. Made even less sense than the last one.
        loc_sand_intro1b_03 = "Ah, sérião?",--Aw, for sure?
        jfe_sand_intro1b_04 = "Sim. hã... Quem foi o idiota que te ensinou isso?",--Yeah. Uuh... What moron taught you these?
        jfe_sand_intro4a_01 = "Ando ouvindo humores sobre os meus contatos em Golden Dagger.",--Been hearing rumors from my contacts in the Golden Dagger. 
        loc_sand_intro4a_01 = "O que houve?",--What've you heard?
        jfe_sand_intro4a_02 = "A sua proeza contra eles está quebrando a fé em liderança. Vocês devem ter deixado o dragão proverbial bem puto enquanto ele estava cagando.",--Your hit against them is breaking faith in the leadership. You really pissed off the proverbial dragon while he was on the toilet.
        loc_sand_intro4a_02 = "É por isso que esse tal de Wang tá bem ancioso para achar a gente?",--That's why this Wang-dwankie is so adamant about paying us a visit?
        jfe_sand_intro4a_03 = "E ele está levando isso muito sério, né?",--And he's taking it rather seriously, right?
        jfe_sand_intro3a_01 = "Vocês realmente deixaram Yufu Wang puto. Espero que o seu amigo Vlad não sabe o seu segredo, né?",--You guys really pissed Yufu Wang off. I hope your guy Vlad doesn't know what you keep in the icebox, right?
        loc_sand_intro3a_01 = "Esse idiota sabe o suficiente, com certeza.",--The dwankie chop knows enough, for sure.
        jfe_sand_intro3a_02 = "O quão durão ele é?",--How tough is he?
        loc_sand_intro3a_02 = "Sinto que vamos descobrir agora.",--I have a blerrie feeling we're going to find out.
        loc_sand_intro2a_01 = "Tráfico de merda. Estamos quase lá. Então, tem certeza que consegue cuidar do barco enquanto a gente entra lá?",--Ach, blerrie traffic. We're almost there. So, you sure you can handle the boat when we get there? 
        jfe_sand_intro2a_01 = "É claro, chefe, nunca pilotei onde eu não posso ver, né?",--Sure chief, I never drive further than I can see, right?
        loc_sand_intro2a_02 = "O que é isso?",--What's that?
        jfe_sand_intro2a_02 = "Um provérbio velho Chinês.",--Old Chinese proverb.
        loc_sand_intro2a_03 = "Que, é sério?",--What, for real?
        jfe_sand_intro2a_03 = "Não, seu idiota.",--No, you fool.
        loc_sand_intro2a_04 = "Sérião, o que significa?",--Seriously, what does it mean?
        jfe_sand_intro2a_04 = "Deixa pra lá, chefe.",--Never mind, chief.
        --loc_sand_intro1a_01 = "",--OK, ok I've got another one.
        jfe_sand_intro1a_01 = "A gente tem tempo pra isso?",--Do we really have time for this?
        loc_sand_intro1a_02 = "Relaxa, a van não vai ir mais rápido! Me ajuda a concentrar, sabe?",--No worries, the van doesn't go any faster! Helps me concentrate, yeah?
        jfe_sand_intro1a_02 = "Tá, manda, chefe. EI, CUIDADO!",--Alright, go ahead Chief. HEY, watch it!!
        loc_sand_intro1a_03 = "Ah! Porra. Tá... Wuh duh ma huh tah duh fong kwong duh wai shung.",--Ach! Dwankie. Right... Wuh duh ma huh tah duh fong kwong duh wai shung!
        jfe_sand_intro1a_03 = "Ainda é Mandarim, chefe. Fez menos sentindo do que o último, né?",--Still Mandarin, Chief. Made even less sense than the last one, right?
        loc_sand_intro1a_04 = "Ah, sérião?",--Aw, for sure?
        jfe_sand_intro1a_04 = "Sim. Que idiota te ensinou isso?",--Yeah. What moron taught you these?

        -- Legendas (yuw)
        yuw_sand_01_01a = "Meu nome é Yufu Wung. Vocês não me conhecem.",--My name is Yufu Wang. You don't know me.
        yuw_sand_01_01b = "Em interesse de poupar dos problemas no futuro, irei lhe dá uma oportunidade de retornar algo que me pertence e pagar as reparações da minha organização.",--In the interest of saving us all a lot of trouble, I will give you an opportunity to return what you have taken and pay reparations to my organization.
        yuw_sand_01_01c = "UMA oportunidade. Só isso.",--One, opportunity. No more.
        yuw_sand_01_02a = "Então, vocês recuperaram o seu amigo. Não importa, eu provei o meu ponto.",--So, you got your man back. No matter, I've proven my point.
        yuw_sand_01_02b = "Vocês vão retornar algo que me pertence, depois enviar uma mensagem de desculpas sinceras e talvez ficamos quites.",--You will return what you have taken from me, then send a message of sincere apology, and maybe our business will be done.

        -- Legendas
        loc_sand_143_02 = "Eu já disse isso. Mas ele é bem durão como uma pedra, nosso Vlad.",--That's kind of what I said. But he's tough like an old shoe, our Vlad.",
        jfe_sand_01_01 = "Tô indo aí. Tô vendo os fogos. Aguentem aí, beleza?",--On my way. I see the fire. Hold on for a while, right?", [FOGOS DE ARTIFICIO]
        jfe_sand_01_02 = "Quase aí. Preciso tomar cuidado ou eles vão ficar bem agitados.",--Almost there. I need to be careful or they'll start raising hell. ",
        jfe_sand_01_03 = "Eles tem muitas pessoas nas docas agora. Vou ter que ir com calma. Me dá um minuto, tá?",--They have lots of people on the docks at the moment. Have to move slowly. Gimme a minute, right?",
        jfe_sand_02_01 = "Vamos, bora te tirar daqui. Eita, ele ainda tá vivo?",--C'mon, let's get you out of here. Oh how is he even still alive?",
        jfe_sand_03_01 = "Vamos, bora te tirar daqui. Eita, ele ainda tá vivo?",--C'mon, let's get you out of here. Oh how is he even still alive?",
        jfe_sand_04_01 = "Cheguei, pessoal, venham logo pra cá pra irmos embora.",--I'm here guys, get your asses on the boat so we can leave.",
        jfe_sand_04_02 = "Tô esperando aqui, pessoal. Bora dá o fora daqui.",--Ready whenever you are guys. Let's Miami-Vice-it out of here.",
        jfe_sand_04_03 = "Ok, gente, bora dá o fora daqui. Todos a bordo!",--Ok chiefs, let's get your guy out of here. Get onboard!",
        jfe_sand_05_01 = "Porra, eu acho que eles me viram. Rápido!",--Fuck, I think they got me in their sights. Hurry!",
        jfe_sand_05_02 = "O que vocês tão esperando, seus iditoas?",--What are you waiting for idiots?",
        jfe_sand_05_03 = "Vou ficar sem gasolina aqui...",--I'm going to run out of gas soon...",
        loc_sand_01_01 = "Amigos, bora fazer isso logo. Achem a sala do servidor e acessem as imagens das câmeras de segurança para acharem qual container o Vlad está preso. Se vocês conseguem achar empresa correta com o manifesto de entrega na sala de controle, nós iremos saber pra onde termos que ir.",--Friends, let's get to this, chop-chop. Find the compounds server room and access the camera feed to find the container they've got Vlad in. If you can match it up to the right company with a shipping manifest in the control room, we'll know where to go.",
        loc_sand_01_02 = "Ok, idiotas, vamos fazer isso logo. Tem uma transmissão de câmeras de segurança na sala do servidor que vocês podem usar para localizar qual container o Vlad está preso. Para acharem, dêem uma olhada na sala de controle para acharem o manifesto de entrega correto.",--OK you chops, let's do this. There's a camera feed in the server room that you can use to locate which container Vlad is in. To find it in the compound, look in the control room for a shipping manifest that matches up.",
        loc_sand_01_03 = "Nós precisamos achar qual container o Vlad está preso. Usem o sistema de câmeras na sala do servidor para acharem o container correto, depois tentem achar o manifesto de entrega que bate com a empresa na sala de controle.",--We need to find exactly which container Vlad is in. Use the camera system in the server room to find the right containter, then try to get hold of a shipping manifest in the control room so that you can match it to a company.",
        loc_sand_02_01 = "Bora, seus idiotas, cada segundo que passa, o Vlad pode estar morto. Entrem lá e descobrem onde estão mantendo ele.",--Come on you dwankies, every second is one more Vlad might spill his guts. Get in there and find out where they're keeping him.",
        loc_sand_02_02 = "Bora, pessoal. Não sei por quanto tempo o Vlad consegue aguentar. Descobrem onde ele está.",--Hurry up friends. No telling how long Vlad can hold out. Find out where he is.",
        loc_sand_02_03 = "Vocês tem que achar onde o Vlad está preso. Rápido!",--You gotta find out where Vlad is being held. Quickly, now!",
        loc_sand_03_01 = "Agora acessem a transmissão das câmeras.",--Now get access to the camera feed.",
        loc_sand_03_02 = "Hackeiem o servidor para acessarem o sistema de câmera.",--Hack into the server so we can access the camera system.",
        loc_sand_03_03 = "Hackeiem a transmissão das câmeras de segurança em um dos servidores.",--Get me hacked into the camera feed via one of the servers.",
        loc_sand_04_01 = "Chequem a transmissão das câmeras de segurança para localizarem o Vlad. Pode estar no andar de cima.",--Check the camera feed so that you can locate Vlad. It should be upstairs.",
        loc_sand_04_02 = "Onde vocês tão acessando a transmissão das câmeras?",--Where are you on accessing that camera feed?",
        loc_sand_04_03 = "Ainda tô esperando vocês acessarem a transmissão das câmeras.",--Still waiting for you to access that camera feed.",
        loc_sand_05_01 = "Boa. A informação estava certo, ele tá dentro de um container.",--There. Our intel was right, he's inside a shipping container.",
        loc_sand_05_02 = "Parece que o contato do Jiu Feng estava certo. Vlad está dentro de um container. Não consigo ver se ele tá bem.",--Looks like Jiu Feng's man was right. Vlad's in a container. Can't see how bad he's off.",
        loc_sand_05_03 = "Boa, parece ser o Vlad ali. Não consigo ver se ele tá bem.",--There, that's Vlad alright. Can't make out his status.",
        loc_sand_06_01 = "Agora, vão para a sala de controle e achem o manifesto de entrega para achar a empresa do depósito que o container está sendo guardado.",--Now, get to the control room and find a shipping manifest so we know which company's warehouse the container is in.",
        loc_sand_06_02 = "Certo, agora achem o depósito que o container está guardado. Procurem o manifesto de entrega na sala de controle.",--Right, now let's find the warehouse with that container. Look for the shipping manifests in the control room.",
        loc_sand_06_03 = "Entrem na sala de controle, achem o manifesto de entrega para acharem o depósito com o container, tá bom?",--Get inside the control room, find a shipping manifest so we can match the container to a warehouse, yeah?",
        loc_sand_07_01 = "Vocês tem que achar a sala de controle.",--You gotta get into that control room.",
        loc_sand_07_02 = "Já acharam o manifesto de entrega?",--Have you found a shipping manifest yet?",
        loc_sand_07_03 = "Hackeiem o leitor de cartão da sala de controle para entrarem e acharem o manifesto.",--Hack the tag reader to the control room so you can get inside and find the manifest.",
        loc_sand_08_01 = "O manifesto tá em um computador, provavelmente.",--The manifest is probably kept on a computer.",
        loc_sand_08_02 = "Acessem o computador da sala de controle para acharem o manifesto.",--Access a control room computer to find the manifest.",
        loc_sand_08_03 = "Vocês vão provavelmente achar o manifesto de entrega no computador da sala de controle.",--You will likely find the shipping manifest on a control room computer.",
        loc_sand_09_01 = "Nós precisamos hackear esse computador, amigos, para acharem o manifesto. Andem logo.",--We need to hack that computer, friends, in order to find the manifests. Chop-chop.",
        loc_sand_09_02 = "Hackeie o computador, amigos.",--Hack into that computer, friends.",
        loc_sand_09_03 = "Andem logo. Hackeiem o computador.",--Quickly, now. Get into that computer.",
        loc_sand_100_01 = "Vocês precisam entrar naquele depósito. Não sei por quanto tempo o Vlad consegue aguentar.",--You need to get inside that warehouse. No telling what state Vlad is in!",
        loc_sand_100_02 = "Não enrolem e entrem no depósito.",--Stop wasting time and get into the warehouse.",
        loc_sand_100_03 = "A gente vai deixar o Vlad morrer, vocês precisam entrar no depósito!",--We're letting Vlad down, you need to get to him in the warehouse!",
        loc_sand_101_01 = "Vai precisar cortar para abrir o container. Vejam se conseguem achar um maçarico.",--The container will need to be cut open. See if you can find a blowtorch.",
        loc_sand_101_02 = "Vocês precisam achar um maçarico para abrir o container. Procurem e achem um.",--You'll need a welding torch to burn open that container door. Look around and see if you can find one.",
        loc_sand_101_03 = "Vai precisar cortar com um maçarico para abrir esse container. Esses lugares sempre tem ferramentas para reparar metal, então, vejam se conseguem achar.",--That container needs to be cut open with a blowtorch. Those places always have tools for metal repair, so see if you can find one.",
        loc_sand_102_01 = "Abrem o container. Rápido, amigos!",--Get that container open. Hurry, friends!",
        loc_sand_102_02 = "Abrem o container, andem logo!",--Crack open that container, chop-chop!",
        loc_sand_102_03 = "Tá tão difícil em abrir o container? Dêem um chute nesse troço enquanto corta.",--Is the container being difficult? Give it a good kick while you're cutting.",
        loc_sand_103_01 = "Porra, o que fizeram com ele? Libertem ele, rápido!",--Ach, what have they done to him? Get him free, quickly!",
        loc_sand_103_02 = "Cacete, ele não tá nada bem. Libertem ele!",--Blerrie, he looks bad. Cut him loose!",
        loc_sand_103_03 = "Meu Deus, ele tá quase morto. Libertem ele, rápido!",--Oh dear, he's in sy moer in. Help him free, fast!",
        loc_sand_103a_01 = "Libertem Vlad!",--Release Vlad!",
        loc_sand_103a_02 = "Tirem o Vlad daí!",--Get Vlad out of those restraints!",
        loc_sand_103a_03 = "Vocês vão deixar Vlad pendurado aí?",--Are you just going to leave him there?",
        loc_sand_104_01 = "Ele parece que tá pronto pra morrer. Vocês vão ter que dá uma mão pro coração dele para manter o Vlad vivo. Peguem o desfibrilador e ressuscitem ele.",--He looks about ready to give up. You're going to have to give his ticker some help in order to move him safely. Grab those defibrillator paddles and give him a good jolt!",
        loc_sand_104_02 = "Vlad não vai conseguir nesse estado. Eu vi um desfibrilador ali... Usem para ressuscitar ele.",--Vlad won't make it in his state. I saw a defibrillator there... use it to give him a jolt. ",
        loc_sand_104_03 = "Conseguimos achar ele na hora, mas ele vai precisar de uma ajuda do desfibrilador para manter ele vivo. Ressuscitem ele, rápido!",--We got to him just in time, but he's going to need a kick from that defibrillator there to stabilize. Use it on him, quickly!",
        loc_sand_105_01 = "Rápido, amigos. Vlad não vai durar por muito tempo!",--Hurry, friends. Vlad will not last long without help!",
        loc_sand_105_02 = "Vlad tá ficando sem tempo, andem logo.",--Vlad is running out of time, get to it.",
        loc_sand_105_03 = "Vocês tem que dá um chute o coração dele com o desfibrilador.",--You gotta give his heart a good skop with that defibrillator. ",
        loc_sand_105a_01 = "Vocês vão precisar recarregar o desfibrilador antes de cada uso.",
        loc_sand_105a_02 = "O Desfibrilador precisa de uma recarga, ta?",
        loc_sand_105a_03 = "Recarreguem o desfibrilador e deem ou choque nele!",
        loc_sand_106_01 = "Choque nele!",
        loc_sand_106_02 = "Ok, Pronto!",
        loc_sand_106_03 = "Sacudam ele, AGORA!",
        loc_sand_107_01 = "OK, parece que isso ajudou. Ele parece instável suficiente para se mover, então ajudem ele a sair daqui. O homem Jiu Feng está esperando por vocês com o carregador de skid lá fora. Vou ter um doutor esperando por vocês quando sairem daqui.",
        loc_sand_107_02 = "Bem, aquilo basta. Não como ele geralmente é, mas não tão diferente. Nosso infiltrado está esperando lá fora com um carregador de skid. Coloquem o vlad na pá. ",
        loc_sand_107_03 = "Boa, Vocês podem mover ele agora. Ajudem o Vlad lá fora. O contato do Jiu Feng está esperando por vocês com um carregador de skid para mover ele.",
        loc_sand_108_01 = "Ajude o Vlad até o carregador de skid.",
        loc_sand_108_02 = "Vlad está bem fraco, vocês precisam ajudar ele lá fora.",
        loc_sand_108_03 = "Coloquem o Vlad na pá do carregador de skid.",
        loc_sand_109_01 = "A segurança nesse local apenas permite um portão por vez abir, então vocês precisam se juntar para passar por eles.",
        loc_sand_109_02 = "Segurança é forte aqui, apenas um portão pode ser aberto. Juntem-se para que o próximo seja aberto e ninguem seja deixado para trás.",
        loc_sand_109_03 = "Juntem-se no portão. Segurança aqui não permite que mais de um abra.",
        loc_sand_10_01 = "Vão até o depósito de libertem nosso amigo ucrâniano.",
        loc_sand_10_02 = "Se apressem e vão até o depósito para libertar Vlad.",
        loc_sand_10_03 = "Agora, vão até os depósitos e libertem Vlad, ta?",
        loc_sand_110_01 = "Juntem-se no portão de segurança, ta?",
        loc_sand_110_02 = "Vamo lá rapazes, fiquem pertos e confortáveis.",
        loc_sand_110_03 = "Hora de um círculo de roubo fechado, ta?",
        loc_sand_110_04 = "Amigos, 'vocês devem reunir o grupo antes de se aventurar mais!'",
        loc_sand_113_01 = "Jiu Feng disse que vocês podem ir pra esquerda ou direita aqui, então escolham uma linha e sigam-a. ",
        loc_sand_113_02 = "Vocês podem pegar qualquer caminho, aqui. É com vocês, amigos.",
        loc_sand_113_03 = "Qualquer direção vai levar vocês pra onde precisam, então vão em frente. Sem volta agora.",
        loc_sand_114_01 = "Não é uma decisão dificil amigos. Escolham uma direção e vão!",
        loc_sand_114_02 = "Vamos gente, Uni, duni, tê... vocês sabem como funciona .",
        loc_sand_114_03 = "Escolham uma direção gente. Pedra, Papel, Lagarto... tanto faz... qualquer um funciona.",
        loc_sand_115_01 = "Aquele portão está nos bloqueando, abram-o, ta?",
        loc_sand_115_02 = "Precisamos passar daquele portão.",
        loc_sand_115_03 = "Outro portão bloqueando vocês. Abram-o.",
        loc_sand_116_01 = "Vamos-la, abram aquele portão. Vocês ja viram esse tipo antes, com certeza.",
        loc_sand_116_02 = "Estão tendo problemas com aquele portão?",
        loc_sand_116_03 = "Tem algo especial com aquele portão? Porque vocês não passaram dele?",
        loc_sand_117_01 = "Amigos, vocês vão ter que mover aquele contêiner para o carregador de skid passar. Procurem uma maneira de movê-lo.",
        loc_sand_117_02 = "O carregador de skid não consegue passar desse contêiner. Encontrem uma maneira de movê-lo.",
        loc_sand_117_03 = "Aquele contêiner está bloqueando o carregador de skid. Tirem ele do caminho.",
        loc_sand_118_01 = "Essa é uma doca... então acho que tenha equipamento aqui para mover aquele contêiner!",
        loc_sand_118_02 = "Se tiver uma coisa aqui, é maneiras de mover o contêiner!",
        loc_sand_118_03 = "Aquele contêiner ainda está causando problemas a vocês?",
        loc_sand_119_01 = "Amigos, antes de passarem por aquelas barricadas... Acabei de ter noção. ",
        loc_sand_119_02 = "Espera um minutinho antes de abaixar aquelas barricadas. Velho Locker pensou em algo.",
        loc_sand_119_03 = "Acabei de pensar em algo que Jiu Feng mencionou... algo que devemos fazer antes de passar pelas barricadas.",
        loc_sand_119b_01 = "Ah, esquece, amigos. Só hackeiem até a sala do servidor. ",
        loc_sand_119b_02 = "Ok, isso muda as coisas. Parem de procurar e hackeiem o servidor.",
        loc_sand_119b_03 = "Esqueçam. Entrem na sala do servidor e hackeiem o sistema.",
        loc_sand_11_01 = "O contêiner pertence a companhia Lán Tàiyáng. Entrem no depósito deles e libertem nosso ucrâniano.",
        loc_sand_11_02 = "Estamos procurando pelo depósito da companhia de carga Lán Tàiyáng. Vão lá.",
        loc_sand_11_03 = "O depósito da companhia de carga Lán Tàiyán é onde Vlad está. Sem tempo a perder.",
        loc_sand_121_01 = "revistem o sistema do computador do escritório office e vejam se podem encontrar algo útil.",
        loc_sand_121_02 = "Vão em frente, procurem pelo sistema do computador do escritório do porto.",
        loc_sand_121_03 = "Olhem pelo escritório do porto, vejam se podem achar seu sistema de armazenamento.",
        loc_sand_122_01 = "Olhem no computador. Vejam o que funciona, ta?",
        loc_sand_122_02 = "Aquele computador... deem uma olhadinha dentro. ",
        loc_sand_122_03 = "Procurem no computador por algo útil.",
        loc_sand_123_01 = "Vocês olharam no computador?",
        loc_sand_123_02 = "Como estão indo com o computador?",
        loc_sand_123_03 = "Já checaram o computador?",
        loc_sand_124_01 = "Vocês vão ter que manter a policia longe enquanto o hack funciona.",
        loc_sand_124_02 = "Não deixem os mocinhos interferir.",
        loc_sand_124_03 = "Tenha certeza que os mocinhos não interfiram.",
        loc_sand_125_01 = "Droga de mocinhos chegaram no computador. Vocês precisam reinicar o computador.",
        loc_sand_125_02 = "Eles chegaram no computador. Reiniciam a rotina de hack.",
        loc_sand_125_03 = "O hack foi cortado. Façam ele funcionar denovo.",
        loc_sand_126_01 = "Façam a rotina de hack funcionar denovo, ta?",
        loc_sand_126_02 = "o hack não vai reiniciar sozinho, ta?",
        loc_sand_126_03 = "Reiniciem o hack, seus idiotas.",
        loc_sand_127_01 = "OK, peguem o disco rígido e levem com vocês.",
        loc_sand_127_02 = "Peguem o disco rígido e voltem para as barricadas.",
        loc_sand_127_03 = "Ai, Agora só tirem o disco rígido e peguem-o. E então lidaremos com as barricadas.",
        loc_sand_128_01 = "Certo... consegui. Vão em frente e peguem o disco rígido.",
        loc_sand_128_02 = "O disco, amigos... peguem-o.",
        loc_sand_128_03 = "Vocês pegaram aquele disco?",
        loc_sand_129_01 = "Derrubem aquelas barricadas com a alavanca ali perto.",
        loc_sand_129_02 = "Tem uma alavanca que controla as barricadas perto. Puxem-a e continuem em frente.",
        loc_sand_129_03 = "As barricadas vão cair se vocês puxaram a alavanca próxima.",
        loc_sand_12_01 = "O contêiner pertence a companhia de carga Lao Che. Entrem no seu depósito e libertem nosso ucrâniano.",
        loc_sand_12_02 = "Estamos procurando pelo depósito da companhia de carga Lao Che. Vão até lá.",
        loc_sand_12_03 = "O depósito da companhia de carga Lao Che é a localização do Vlad. Sem tempo a perder.",
        loc_sand_130_01 = "Vocês ativaram aquela alavanca?",
        loc_sand_130_02 = "Vocês acharam aquela alavanca?",
        loc_sand_130_03 = "Vamos lá, Derrubem aquelas barricadas.",
        loc_sand_131_01 = "Movam aquele caminhão ou abram aquele depósito. Movam-se, amigos. ",
        loc_sand_131_02 = "Vocês podem tirar aquele caminhão do caminho ou irem pelo depósito.",
        loc_sand_131_03 = "Ah, Outra rua prestes a ser escolhida. Passem pelo caminhão ou pelo depósito.",
        loc_sand_131a_01 = "Não fiquem parados. Caminhão ou depósito, qualquer um basta.",
        loc_sand_131a_02 = "Tendo problemas escolhendo a direção?",
        loc_sand_131a_03 = "Vamos... passar pelo caminhão ou pelo edifício.",
        loc_sand_132_01 = "Vocês vão ter que passar pelo convés do navio. Vamos ter que colocar o carregador de skid a bordo de alguma forma.",
        loc_sand_132_02 = "Colocar o carregador de skid no convés do navio pode ser um problema.",
        loc_sand_132_03 = "Passar pelo convés daquele navio pode ser um problema para o carregador de skid.",
        loc_sand_133_01 = "O controle da pista de aterrissagem deve estar perto da rampa. Ativem-o para o carregador de skid poder subir a bordo do navio, tá?",
        loc_sand_133_02 = "Manobrem a rampa de aterrisagem para que o carregador de skid embarcar o navio.",
        loc_sand_133_03 = "Usem o controle da rampa para movê-la na posição correta, tá?",
        loc_sand_134_01 = "Movam a rampa para fora do navio. Sujem suas mãos, amigos.",
        loc_sand_134_02 = "Vocês tem que extender a rampa para aterrissar. ",
        loc_sand_134_03 = "Coloquem a rampa nas docas. ",
        loc_sand_135_01 = "Vocês estão quase prontos, amigos. Movam aquela rampa!",
        loc_sand_135_02 = "Não tão longe. Só cuidem daquela rampa.",
        loc_sand_135_03 = "A rampa, amigos!",
        loc_sand_135a_01 = "Tirem aquela tralha do caminho!",
        loc_sand_135a_02 = "Vocês precisam mover aquela paleteira do caminho!",
        loc_sand_135a_03 = "Movam aquela paleteira do caminho.",
        loc_sand_135b_01 = "Tendo problemas com a paleteira?",
        loc_sand_135b_02 = "A paleteira, amigos...",
        loc_sand_135b_03 = "Paleteira sendo problemática?",
        loc_sand_136_01 = "Estou tendo problemas mantendo contato com Jiu Feng. Muita interferência no rádio, pode ser aquele Wang ainda mexendo nas coisas. Vocês vão ter que sinalizar pela fuga. The tríade trafica bastante fogos de artifício por aqui, talvez vocês podem achar alguns.",
        loc_sand_136_02 = "Muita interferência. Não consigo sinalizar Jiu Feng então vocÊs vão ter que sinalizar pra ele. Eu vi algo na nossa intel sobre o envio de fogos de artíficio ilegais . Se puderem achá-los, Eles fariam um baita sinal!",
        loc_sand_136_03 = "Eu perdi a conexão Jiu Feng. A tríade pode estar nos sabotando. Eles recentemente tiverem uma entrega de fogos de artíficio ilegais. Se conseguir ativá-los, eles fariam um grande sinal para ele vir pegar vocês!",
        loc_sand_137_01 = "Encontrem o contêiner com os fogos de artíficio e usem eles para sinalizar ao Jiu Feng buscar vocês!",
        loc_sand_137_02 = "Vocês ja acharam aqueles fogos de artíficio?",
        loc_sand_137_03 = "Vocês precisam ativar os fogos de artíficio para sinalizar ao Jiu Feng!",
        loc_sand_139_01 = "Vamos Gente, ativem aqueles fogos de artíficio.",
        loc_sand_139_02 = "Acendam aqueles fogos de artíficio.",
        loc_sand_139_03 = "Acendam aqueles foguetinhos, tá?",
        loc_sand_13_01 = "O Contêiner pertence a companhia de carga Lo Pan. Entrem no depósito deles e libertem nosso Ucrâniano.",
        loc_sand_13_02 = "Estamos procurando pelo depósito da companhia de carga Lo Pan. Vão até lá.",
        loc_sand_13_03 = "Eles estão mantendo Vlad no depósito de Lo Pan. Corram, amigos.",
        loc_sand_14_01 = "Eles estão usando carácteres Hanzi naquele teclado. Revistem o prédio principal e vejam se conseguem encontrar o código ou algo que combine.",
        loc_sand_14_02 = "Aquele teclado... caracteres hanzi. Vão no prédio principal, Vejam se conseguem achar um código que combina.",
        loc_sand_14_03 = "Chequem o prédio principal para achar um código ou algo que combina com os caracteres naquele teclado, ta?",
        loc_sand_15_01 = "VocÊs precisam passar por aquele teclado. Chequem o prédio principal para achar algo que combina. ",
        loc_sand_15_02 = "Chequem o prédio principal e vejam se conseguem achar algo que corresponde aquele teclado.",
        loc_sand_15_03 = "Deem uma olhada no prédio principal por algo que pode ser um código para aquele teclado.",
        loc_sand_16_01 = "É um código em um cronômetro rotativo. Chquem o prédio principal por algo que combine.",
        loc_sand_16_02 = "Um código em um cronômetro rotativo. Procurem por algo que combine.",
        loc_sand_16_03 = "Vocês deviam checar o prédio principal pelo código atual para aquela trava.",
        loc_sand_17_01 = "Vocês precisam achar o código que está sendo usado, amigos.",
        loc_sand_17_02 = "Já acharam aquele código?",
        loc_sand_17_03 = "O que, ainda estão procurando por aquele código?",
        loc_sand_18_01 = "O capataz mantêm o cartão mestre em seu escritório. Encontrem-o e peguem o cartão.",
        loc_sand_18_02 = "Tem um cartão mestre que sempre fica no escritório do capataz. Peguem-o.",
        loc_sand_18_03 = "Eles aparentemente mantêm o cartão mestre no escritório do capataz. Vão pegá-lo, amigos.",
        loc_sand_19_01 = "Vocês precisam do cartão mestre no escritório do capataz.",
        loc_sand_19_02 = "Ja acharam o cartão mestre?",
        loc_sand_19_03 = "Vocês já tem o cartão mestre?",
        loc_sand_20_01 = "Ach, um espertinho está tendo um cafézinho. Precisamos enganar ela a sair dali.",
        loc_sand_20_02 = "Droga, tem um idiota no escritório. Vocês tem que tirar ele dali.",
        loc_sand_20_03 = "Parece que alguem decifiu dar uma pausa pro café no escritório. Vamos tirar ele dali, ta?",
        loc_sand_21_01 = "Vocês sabe,, acho que vi um bolo pela câmera da cozinha. Vamos fermentá-lo com alguns produtos de limpeza, e então chamar o escritório do capataz e enganar atrair o idiota para comer e vomitar.",
        loc_sand_21_02 = "Eu vi um bolo na cozinha quando vocês olharam na câmera. Vamos fermentá-lo com algum produto de limpeza, e então chamar o escritório e enganar o babaca a comê-lo, ta?",
        loc_sand_21_03 = "Vamos fazer uma brincadeirinha, ta? Eu vi um bolo pelo vídeo da cozinha. Encontrem algo para fermentá-lo, então vamos chamar o escritório do capataz e enganar o idiota em comê-lo.",
        loc_sand_22_01 = "Vejam se conseguem achar um produto químico de limpeza por aqui, então fermentem o bolo.",
        loc_sand_22_02 = "Deve ter algum produto de limpeza por aqui.",
        loc_sand_22_03 = "Vamos, amigos. Todo mundo fica com produtos de limpeza em mãos, até idiotas do tríade!",
        loc_sand_23_01 = "Liguem para a extensão certa para o escritório do capataz pelo interfone.",
        loc_sand_23_02 = "Usem o interfone para ligar ao escritório do capataz.",
        loc_sand_23_03 = "Vocês podem usar o interfone para ligar para o escritório do capataz.",
        loc_sand_24_01 = "O número da extensão está visível dentro do escritório.",
        loc_sand_24_02 = "O número certo está visível no escritório.",
        loc_sand_24_03 = "Vocês podem ver o número do capataz dentro do escritório",
        loc_sand_25_01 = "'Ei amigo, É o aniversário de Han Chan e guardamos um pouco de bolo para você na cozinha. Melhor correr e pegá-lo antes de Wu vê-lo- você sabe como ele é!'",
        loc_sand_25_02 = "'Vamo caraaaa. Tem bolo pra você na cozinha! Aquela boa..uh... nova recepcionista Doris deixou pra você!'",
        loc_sand_26_01 = "Hora de abrir aquelas portas do depósito e tirar Vlad dali.",
        loc_sand_26_02 = "Agora, vamos abrir aquelas portas do depósito para que póssamos chegar no Vlad.",
        loc_sand_26_03 = "Certo, agora abram aquelas portas do depósito e vão até Vlad.",
        loc_sand_27_01 = "Vão para o depósito, amigos. rapidinho.",
        loc_sand_27_02 = "Para o depósito!",
        loc_sand_27_03 = "Vocês precisam entrar no depósito.",
        loc_sand_28_01 = "Droga, Parece que tem fortes travas nesses contêineres. Se um que prende o Vlad está fechado assim, vocês vão ter que achar um maçarico ou algo para cortá-los.",
        loc_sand_28_02 = "Ach, os contêineres parecem bem fechados. Se eles tiverem trancado Vlad assim, vocês vão ter que cortar a trava com alguma tocha de soldagem ou algo assim.",
        loc_sand_28_03 = "Se o contêiner prendendo Vlad estiver trancado como os outros, vai precisar ser cortado. Vocês provavelmente podem achar um maçarico ou algo por ai. Docas sempre tem esses tipos de ferramentas, né?",
        loc_sand_29_01 = "Ainda estão procurando algo para corat? Procurem mais, seus idiotas!",
        loc_sand_29_02 = "Procurem por um maçarico ou algo assim. ",
        loc_sand_29_03 = "Estamos com um pouco de pressa, amigos. Encontrem algo para cortar os contêineres.",
        loc_sand_30_01 = "Oh... velho Locke viu algumas coisas em seus dias jovens, mas isso...",
        loc_sand_30_02 = "Ach! droga! Estamos atrasados?",
        loc_sand_30_03 = "Vlad, esse pobre idiota. Ele ainda ta respirando?",
        loc_sand_32_01 = "Desengate Vlad de suas correntes, né?",
        loc_sand_32_02 = "Vamos lá amigos, tirem Vlad daquela parede.",
        loc_sand_32_03 = "O que estão fazendo? Ajudem Vlad sair daquela repressão!",
        loc_sand_33_01 = "Ele vai precisar de atenção médica antes de mover ele. Deve ter algum produto médico para manter ele vivo por todo aquele dano. Vejam se conseguem achar algo.",
        loc_sand_33_02 = "Não precisa der um doutor pra saber que ele vai precisar de uma empurrada para estabilizá-lo. Lugares como esse são geralmente bem equipados com medicamentos. Vejam se podem achar um kid de primeiros socorros com uma adrenalina.",
        loc_sand_33_03 = "Vlad precisa ser estabilizado antes de vocês poderem mover ele. Procurem em volta por algum kid médico e dêem a ele uma picada de atrenalina se possível.",
        loc_sand_34_01 = "Sem tempo a perder, Encontrem medicamentos pro Vlad. Rápido, amigos!",
        loc_sand_34_02 = "Encontrem um medicamento para Vlad!",
        loc_sand_34_03 = "Vlad Precisa da adrenalina!",
        loc_sand_36_01 = "OK, Ele parece meio tonto , mas temos que arriscar a mover ele. O contato do Jiu Feng está esperando lá fora com um carregador de skid. Escorte o Vlad até ele, chop-chop.",
        loc_sand_36_02 = "Not too bad. He can be safely moved a little bit. Our inside guy has a skid loader waiting. Get Vlad to it and put him in the scoop.",
        loc_sand_36_03 = "Isso basta. Tem um carregador de skid próxima sendo dirigido pelo homem de Jiu Feng. Ajude Vlad a entrar no balde.",
        loc_sand_37_01 = "Levem Vlad até o carregador de skid.",
        loc_sand_37_02 = "Vlad está estável suficiente para caminhar, então levem ele para o carregador.",
        loc_sand_37_03 = "Vocês precisam levar Vlad até o carregador de skid.",
        loc_sand_38_01 = "Estão usando um sistema de represa para os portões aqui, apenas um pode ser aberto por vez por motivos de segurança então vocês vão ter que se juntar para ir as docas.",
        loc_sand_38_02 = "Vocês vão ter que se juntar para entrar nas docas. Segurança aqui deuxa apenas um portão abrir por vez.",
        loc_sand_38_03 = "Segurança aqui é forte, eles deixam apenas um portão abrir por vez, então vocês vão ter que ficar perto para ir as docas.",
        loc_sand_39_01 = "Vamos amigos, fiquem confortáveis no portão para entrar nas docas.",
        loc_sand_39_02 = "Vamos, agora. Juntem-se perto do portão e entrem nas docas.",
        loc_sand_39_03 = "VocÊs precisam se juntar perto do portão, amigos!",
        loc_sand_39_04 = "Amigos! Vocês precisam juntar seu grupo antes de se aventurar mais.",
        loc_sand_40_01 = "Jiu Feng disse que podem escolher qualquer caminho. Os dois vão os levar ao fim das docas.",
        loc_sand_40_02 = "É com vocês em qual caminho pegar. Qualquer um vai levar vocês ao fim das docas.",
        loc_sand_40_03 = "Qualquer caminho vai levar vocês até o fim das docas.",
        loc_sand_41_01 = "Vamos amigos. Esquerda ou Direita, façam uma escolha e continuem andando.",
        loc_sand_41_02 = "Façam uma escolha e continuem em frente.",
        loc_sand_41_03 = "Vamos lá, vamos indo rapazes. Escolham e vamos. ",
        loc_sand_41a_01 = "Mantenham o olho naquele carregador de skid. 'Carga prciosa', né?",
        loc_sand_41a_02 = "Tenha certeza que o carregador de skid não é interferido.",
        loc_sand_41a_03 = "Não deixem nada acontecer com o carregador de skid.",
        loc_sand_42_01 = "Aquele portão está bloqueando vocês, abram-o, tá?",
        loc_sand_42_02 = "Abram aquele portão.",
        loc_sand_42_03 = "Vamos abrir aquele portão.",
        loc_sand_43_01 = "Vamos lá, abram aquele portão. Vocês ja viram esse tipo antes, com certeza.",
        loc_sand_43_02 = "O portão, amigos.",
        loc_sand_43_03 = "Vão em frente... abra de sésamo seus idiotas.",
        loc_sand_44_01 = "Não tem volta agora, os membros da tríade vão provavelmente ver que Vlad sumiu a qualquer momento agora. Encontrem um caminho de mover aquele contêiner para que possamos passar o carregador de skid. ",
        loc_sand_44_02 = "Sem volta agora. Só daria problemas. Tirem aquele contêiner do caminho.",
        loc_sand_44_03 = "O carregador de skid não vai passar daquele contêiner ao menos que vocês tirem ele do caminho.",
        loc_sand_45_01 = "Encontrem algo por aqui para mover o contêiner.",
        loc_sand_45_02 = "Vejam se tem uma maneira de movê-lo.",
        loc_sand_45_03 = "Se é uma coisa que tiverem aqui, é equipamento para mover os contêineres. Então vão em frente, ta?",
        loc_sand_46_01 = "Amigos, precisamos passar pelas barricadas, mas antes, tenho uma ídeia.",
        loc_sand_46_02 = "Ok, antes temos que tomar conta daquelas barricadas, vamos fazer um desvio.",
        loc_sand_46_03 = "Acho que temos tempo para um pequeno desvio antes de passar por aquelas barricadas, né?",
        loc_sand_49_01 = "Vejam se podem achar algo útil no escritório do porto.",
        loc_sand_49_02 = "Tinha algo útil no escritório do porto?",
        loc_sand_49_03 = "Acharam algo útil pelo escritório?",
        loc_sand_50_01 = "OK, agora puxem aquela alavanca que controla as barricadas para poderem passar.",
        loc_sand_50_02 = "Ótimo! Vamos em frente. As barricadas estão sendo controladas por uma alavanca. ",
        loc_sand_50_03 = "Ai está. Isso vai ser útil. Agora, tem uma alavanca que controla aquelas barricadas. Baixe elas e continuem indo, tá?",
        loc_sand_51_01 = "Já acharam aquela alavanca?",
        loc_sand_51_02 = "E as barricadas?",
        loc_sand_51_03 = "Puxem a alavanca para baixar aquelas barricadas.",
        loc_sand_52_01 = "Movam o caminhão ou abrar o depósito, qualquer direção vai levar vocês pra onde precisam.",
        loc_sand_52_02 = "OK, agora vão pelo depósito ou movam aquele caminhão do caminho para poderem passar.",
        loc_sand_52_03 = "Vocês podem ir pelo depósito ou movendo o caminhão",
        loc_sand_53_01 = "Vamos pessoal, façam uma escolha. Caminhão ou depósito!",
        loc_sand_53_02 = "Vamos lá, rapazes. Façam uma escolha. ",
        loc_sand_53_03 = "Estão tendo dificuldade escolhendo qual caminho ir?",
        loc_sand_54_01 = "Vocês tem que passar pelos contêineres. Talvez façam um desvio pelo navio?",
        loc_sand_54_02 = "Melhor passar pelo convés do nacvio para passar dos contêineres. Deve fazer uma boa cobertura. ",
        loc_sand_54_03 = "Vamos atravessar o convés do navio para passar dos contêineres.",
        loc_sand_55_01 = "Ativem a rampa de bordo.",
        loc_sand_55_02 = "Ativem os controles da rampa de bordo.",
        loc_sand_55_03 = "Usem os controles da rampa de bordo.",
        loc_sand_56_01 = "Ok, aquela rampa precisa ser baixada.",
        loc_sand_56_02 = "Baixem aquela rampa.",
        loc_sand_56_03 = "Vocês precisam baixar aquela rampa.",
        loc_sand_57_01 = "Estão quase lá, amigos. Movam aquela rampa!",
        loc_sand_57_02 = "A rampa está presa ou algo assim?",
        loc_sand_57_03 = "Ja arrumaram a rampa?",
        loc_sand_58_01 = "Ok amigos, vocês estão quase em casa. Só mais um pouco...",
        loc_sand_59_01 = "Encontre uma maneira de distrair aqueles trabalhadores e movem a paleteira do caminho.",
        loc_sand_59_02 = "Vejam se podem limpar aqueles trabalhadores e mover aquela coisa.",
        loc_sand_59_03 = "Aqueles mãos de docas... tirem eles dali para mover a paleteira.",
        loc_sand_59a_01 = "Façam eles pensar que é hora do lanche ou algo assim?",
        loc_sand_59a_02 = "Que tal tocar o sino do lanche?",
        loc_sand_59a_03 = "Engane eles a dar uma pausa.",
        loc_sand_60_01 = "Amigos? Amigos? Tão ouvindo? Droga, o que foi isso? Tanto faz...",
        loc_sand_61_01 = "Não consigo alcançar Jiu Feng. Alguma interferência. Sabiamos que isso poderia acontecer, então ele está esperando por um sinal. Encontrem algo inflamável, petróleo ou algo assim ... façam um sinal de fogo.",
        loc_sand_61_02 = "Bastante interferência no momento. Não consigo alcançar Jiu Feng para a fuga então vocês vão precisar sinalizar para ele. Encontrem algo para acender um fogo.",
        loc_sand_61_03 = "Minha conexão de rádio com Jiu Feng caiu no momento então vocês vão ter que sinalizar para ele com um fogo. Vejam o que podem encontrar para usar.",
        loc_sand_62_01 = "Encontre gasolina e acendam um fogo. Jiu Feng ta esperando!",
        loc_sand_62_02 = "Deve ter algo inflamável por aqui em algum lugar.",
        loc_sand_62_03 = "Eu ainda não consigo alcançar Jiu Feng, então vocès vão ter que acender aquele fogo.",
        loc_sand_63_01 = " ",
        loc_sand_64_01 = " ",
        loc_sand_66_01 = "Gente, Vlad não está parecendo tão estável, esérem até Jiu Feng chegar.",
        loc_sand_66_02 = "Jiu Feng deve estar a caminho agora, mas Vlad não parece estar bem. Esperam um pouco até o barco chegar. ",
        loc_sand_66_03 = "Como ta o Vlad? Aquela adrenalina não vai manter ele estável por muito tempo, mas Jiu Feng deve chegar em breve, então só esperem.",
        loc_sand_68_01 = "OK amigos... hora de ir embora.",
        loc_sand_68_02 = "Aquele é o barco do Jiu Feng? Boa, agora a bordo, chop-chop!",
        loc_sand_68_03 = "Hora de entrar no barco.",
        loc_sand_69_01 = "O que tão esperando? Entrem no barco. ",
        loc_sand_69_02 = "Vocês preferem nadar?",
        loc_sand_69_03 = "Para o barco. Vocês não vão ter um maior...",
        loc_sand_70_01 = "Bem, Aquilo acabou. Eles sabem que estamos aqui. Peguem as armas e tragam pra casa nosso Ucrâniano.",
        loc_sand_70_02 = "É isso, estão atrás de nós. Armas Altas, né?",
        loc_sand_70_03 = "Tudo bem, vocês podem chegar a Vlad mais rápido!",
        loc_sand_71_01 = "Entrem no prédio principal.",
        loc_sand_71_02 = "Vamos amigos, entrem no prédio.",
        loc_sand_71_03 = "OK, agora entrem no prédio principal, seus idiotas!",
        loc_sand_72_01 = "Desliguem a caixa elétrica.",
        loc_sand_72_02 = "Cortem a energia do portão. ",
        loc_sand_72_03 = "Quebrem a caixa elétrica para abrir o portão.",
        loc_sand_72a_01 = "O que estão esperando? Entrem!",
        loc_sand_72a_02 = "Sem perder tempo, se movam!",
        loc_sand_72a_03 = "Isso não é um churrasco, né? Continuem!",
        loc_sand_73_01 = "Se puderem entrar no prédio pricipal tem uma sala do servidor no primeiro andar onde podem hackear as câmeras e localizar Vlada.",
        loc_sand_73_02 = "O primeiro andar do prédio principal tem uma sala do servidor em que podem acessar as câmeras e achar Vlad.",
        loc_sand_73_03 = "Entrem na sala do servidor no primeiro andar do prédio principal e hackeiem as câmeras.",
        loc_sand_74_01 = "Vocês precisam entrar no sistema de câmeras para achar nosso amigo Ucrâniano sequestrado.",
        loc_sand_74_02 = "Precisamos olhar naquelas câmeras de segurança, ta?",
        loc_sand_74_03 = "Usem as câmeras para achar Vlad.",
        loc_sand_75_01 = "Parece que Jiu Feng estava certo. Estão mantendo ele em um contêiner.",
        loc_sand_75_02 = "Nossa intel ta correta, ele ta em um contêiner. ",
        loc_sand_75_03 = "Ai... certo. Ele está sendo mantido em um contêiner.",
        loc_sand_76_01 = "Abra a porta da sala de controle e procure por um manifesto de envio. Podemos combinar a companhia do contêiner com o depósito que está sendo guardado.",
        loc_sand_76_02 = "Vocês devem conseguir achar documentações de entrega na sala de controle. Usem-a para achar qual depósito Vlad está.",
        loc_sand_76_03 = "Precisamos achar qual depósito aquele contêiner está. Encontre o manifesto da companhia na sala de controle e combine com os contêineres.",
        loc_sand_77_01 = "Acessem a sala de controle.",
        loc_sand_77_02 = "Vocês precisam hackear a porta da sala de controle.",
        loc_sand_77_03 = "Já estão abrindo aquela porta?",
        loc_sand_78_01 = "Agora achem a documentação da companhia. Com isso, vocês vão poder achar o contêiner que guarda Vlad.",
        loc_sand_78_02 = "Vejam se podem achar os documentos certos da companhia oara ajudar a localizar o contêiner.",
        loc_sand_78_03 = "Comece a procurar por documentos para combinar a companhia e o contêiner.",
        loc_sand_79_01 = "Comece o hack para encontrarmos o manifesto de entregas.",
        loc_sand_79_02 = "Comecem o hack. ",
        loc_sand_79_03 = "Comecem a hackear para pegarmos aqueles documentos, tá?",
        loc_sand_80_01 = "Vão até o depósito e libertem nosso amigo Ucrâniano.",
        loc_sand_80_02 = "Agora vamos libertar nosso cara antes que ele deixe algo vazar, ta?",
        loc_sand_80_03 = "Hora de tirar nosso Ucrâniano daquele contêiner!",
        loc_sand_81_01 = "O contêiner pertence a companhia de carga Lán Taiyáng. Entrem em seu depósito e libertem nosso Ucrâniano.",
        loc_sand_81_02 = "Aquele é um contêiner de Lán Tàiyáng. ",
        loc_sand_81_03 = "OK, vocês tão procurando pelo depósito Lán Tàiyáng. Vlad está em um de seus contêineres.",
        loc_sand_82_01 = "Os contêineres pertencem a companhia de carga Lao Che. Entrem dentro de seu depósito e libertem nosso Ucrâniano.",
        loc_sand_82_02 = "Aquele é um dos contêineres Lao Che. ",
        loc_sand_82_03 = "OK, vocês estão procurando pelo depósito de Lao Che. Vlad está em um de seus contêineres.",
        loc_sand_83_01 = "O Contêiner pertence a companhia de cargas Lo Pany. Entrem no depósito deles e libertem nosso Ucrâniano.",
        loc_sand_83_02 = "Aquele é um contêiner de Lo Pan. ",
        loc_sand_83_03 = "OK, Vocês estão procurando pelo depósito de Lo Pan. Vlad está em um de seus contêineres.",
        loc_sand_84_01 = "Hackeiem o computador para que possamos sobrecarregar o teclado e acessar o depósito.",
        loc_sand_84_02 = "Comecem um hack no computador. Podemos começar uma sobrecarga no teclado e entrar no depósito.",
        loc_sand_84_03 = "Precisamos sobrecarregar o teclado. Hackeie o computador para criar um pico na voltagem.",
        loc_sand_85_01 = "Precisamos entrar no depósito, então iniciem o hack no computador.",
        loc_sand_85_02 = "Precisamos entrar ali rápido, então iniciem o hack.",
        loc_sand_85_03 = "Ja começaram o hack?",
        loc_sand_86_01 = "Alguem chegou no computador. Reinicie a rotina de hack!",
        loc_sand_86_02 = "Vocês precisam reiniciar o hack.",
        loc_sand_86_03 = "Façam o hack voltar a funcionar, ta?",
        loc_sand_87_01 = "Vocês precisam reiniciar a sequência do hack.",
        loc_sand_87_02 = "A sequência de hack foi interrompida. Reiniciem, amigos.",
        loc_sand_87_03 = "Vocês precisam fazer o hack voltar a funcionar denovo!",
        loc_sand_87a_01 = "Os babacas cortaram a energia!",
        loc_sand_87a_02 = "Os policiais cortaram a energia, liguem-a denovo!",
        loc_sand_87a_03 = "Vocês precisam ligar a energia, amigos!",
        loc_sand_88_01 = "Agora puxem a alavanca da energia e um pico de carga vai acontecer.",
        loc_sand_88_02 = "Puxar a alavanca da energia vai causar uma sobrecarga.",
        loc_sand_88_03 = "Agora vocês podem sobrecarregar puxando a alavanca da energia.",
        loc_sand_89_01 = "Vamos lá amigos, puxem a alavanca para queimar o teclado, ta?",
        loc_sand_89_02 = "Puxem a alavanca, seus idiotas.",
        loc_sand_89_03 = "Comecem a sobrecarga. Puxem a alavanca!",
        loc_sand_90_01 = "Precisamos encontrar o cartão mestre no escritório do capataz. Vão.",
        loc_sand_90_02 = "Precisamos do cartão mestre. Estão no escritório do capataz.",
        loc_sand_90_03 = "Precisamso pegar o cartão mestre do escritório do capataz.",
        loc_sand_91_01 = "Procurem por ele no escritório do capataz.",
        loc_sand_91_02 = "Entrem no escritório do capataz e encontrem aquele cartão.",
        loc_sand_91_03 = "Sem atraso, entrem no escritório do capataz.",
        loc_sand_92_01 = "Ach, algum idiota está dentro e trancou a porta. vamos tirar ele com fumaça. Vão ver se podem 'pegar emprestado' um gás em algum lugar. ",
        loc_sand_92_02 = "OK, algum idiota foi e se trancou ali. Se puderem achar um tubo de gás ou algo assim, podemos sufocar ele.",
        loc_sand_92_03 = "Vamos ter que tirar aquele idiota trancado no escritório. Procurem por um contêiner de gás ou algo que pode se usado para contaminar o ar e forçar ele a sair.",
        loc_sand_93_01 = "Encontrem um contêiner de gás para podermos tirar aquele idiota do escritório com fumaça.",
        loc_sand_93_02 = "Procurem por um tubo de gás.",
        loc_sand_93_03 = "Deve ter um cilíndro com algum tipo de gás por aqui que podem usar.",
        loc_sand_94_01 = "Boa, agora tirem aquele idiota dali. Vou ter certeza de manda um dinheiro pra policia pelo gás depois. Quando porcos vão velejar , né?",
        loc_sand_94_02 = "Façam o idiota engasgar e tossir. ",
        loc_sand_94_03 = "Usem o contêiner de gás e sufoquem aquele cara pra fora dali, tá?",
        loc_sand_95_01 = "Liguem o gás com a ventilação do escritório.",
        loc_sand_95_02 = "Usem os dutos de ventilação.",
        loc_sand_95_03 = "Mandem o gás pela ventilação do prédio. ",
        loc_sand_98_01 = "E o cartão? Já acharam?",
        loc_sand_98_02 = "Como foi com o cartão?",
        loc_sand_98_03 = "Já pegaram o cartão?",
        loc_sand_99_01 = "Abram aquela porta do depósito e vão até Vlad.",
        loc_sand_99_02 = "Abram a porta do depósito. Vlad precisa de nós, chop-chop!",
        loc_sand_99_03 = "Precisam abrir a porta do depósito. O tempo do Vlad pode tar acabando.",

        -- Objetivos
        hud_heist_sand1_hl = "Infiltre-se no complexo",
        hud_heist_sand1 = "Encontre uma maneira de entrar no complexo da Tríade.",
        
        hud_heist_sand2_hl = "Accesse as câmeras",
        hud_heist_sand2 = "Use as câmeras para achar a localização de Vlad.",
        
        hud_heist_sand3_hl = "Hackeie o controle da porta",
        hud_heist_sand3 = "Entre na sala de controle hackeando o sistema de segurança da porta.",
        
        hud_heist_sand4_hl = "Encontre o manifesto da companhia",
        hud_heist_sand4 = "Localize o manifesto da companhia para achar o contêiner que Vlad está sendo mantido.",
        
        hud_heist_sand5_hl = "Vá até o depósito",
        hud_heist_sand5 = "Sabemos onde Vlad está. Entre lá e liberte-o!",
        
        hud_heist_sand6_hl = "Encontre o código",
        hud_heist_sand6 = "O código está escrito em em Hanzis Chineses. Encontre uma maneira de traduzi-los.",
        
        hud_heist_sand7_hl = "Encontre e use o código rotatório",
        hud_heist_sand7 = "O código está sendo atualizado em uma rotina rotatória. Encontre o código atual.",
        
        hud_heist_sand8_hl = "Pegue o cartão",
        hud_heist_sand8 = "O cartão é necessário para passar pelo portão. Procure no prédio principal.",
        
        hud_heist_sand9_hl = "Encontre algo para colocar no bolo",
        hud_heist_sand9 = "Precisamos de algo que 'faça vomitar' para envenenar o bolo.",
        
        hud_heist_sand10_hl = "hud_heist_sand10_hl",
        hud_heist_sand10 = "hud_heist_sand10",
        
        hud_heist_sand11_hl = "Ligue para o interfone do escritório do capataz",
        hud_heist_sand11 = "O ocupante do escritório deve ser atraido para a cozinha com a ajuda do número de interfone correto.",
        
        hud_heist_sand12_hl = "Abra o depósito ",
        hud_heist_sand12 = "Pegue o cartão e use-o para abrir o portão do depósito.",
        
        hud_heist_sand13_hl = "Encontre Vlad",
        hud_heist_sand13 = "Encontre um maçarico e abra o contêiner até encontrar Vlad.",
        
        hud_heist_sand14_hl = "Liberte Vlad",
        hud_heist_sand14 = "Tire Vlad de suas correntes.",
        
        hud_heist_sand15_hl = "Dê a Vlad uma injeção de adrenalina",
        hud_heist_sand15 = "Localize um kit de primeiros socorros com alguma adrenalina dentro e use no Vlad.",
        
        hud_heist_sand16_hl = "Escorte Vlad",
        hud_heist_sand16 = "Escorte Vlad até o carregador de skid lá fora.",
        
        hud_heist_sand17_hl = "Juntem-se no portão de segurança",
        hud_heist_sand17 = "Vocês precisam se juntar no portão de segurança antes de prosseguir.",
        
        hud_heist_sand18_hl = "Escorte o carregador de skid",
        hud_heist_sand18 = "Escorte Vlad e o carregador de skid até o fim das docas.",
        
        hud_heist_sand19_hl = "Roube a documentação da tríade",
        hud_heist_sand19 = "Infiltre-se no escritório e roube documentos contendo informação das negociações da tríade.",
        
        hud_heist_sand20_hl = "Mova o contêiner",
        hud_heist_sand20 = "Tire o contêiner do caminho para o carregador de skid continuar se movendo.",
        
        hud_heist_sand21_hl = "Fuga Disponível",
        hud_heist_sand21 = "O barco de fuga do Vlad está esperando.",
        
        hud_heist_sand22_hl = "Escolha um caminho",
        hud_heist_sand22 = "Abra qualquer caminho pra instruir o infiltrado do Jiu Feng qual caminho levar o carregador de skid.",
        
        hud_heist_sand23_hl = "Suba a rampa do navio",
        hud_heist_sand23 = "Encontre uma maneira de subir a rampa do navio para o carregador de skid subir e atravessar.",
        
        hud_heist_sand24_hl = "Encontre e use o cartão",
        hud_heist_sand24 = "Vocês precisam de um cartão para passar por esse portão. Procurem dentro do prédio principal.",
        
        hud_heist_sand25_hl = "Roube um recipiente de gás da van da SWAT",
        hud_heist_sand25 = "Os policiais tem um recipiente de gás dentro da van da SWAT. Vá e pegue uma.",
        
        hud_heist_sand26_hl = "Ligue O recipiente de gás",
        hud_heist_sand26 = "Conecte o recipiente de gás na ventilação da sala e tire o trabalhador dali.",
        
        hud_heist_sand27_hl = "Espere pelo gás limpar a sala",
        hud_heist_sand27 = "O gás vai eventualmente sufocar o trabalhador, forçando ele a sair da sala. Só espere.",
        
        hud_heist_sand28_hl = "Hackeie o computador",
        hud_heist_sand28 = "O computador precisa ser hackeado para sobrecarregar a energia do teclado.",
        
        hud_heist_sand29_hl = "Resuma o hack",
        hud_heist_sand29 = "Os policiais interferiram com o hack. Reiniciem-o e continuem.",
        
        hud_heist_sand30_hl = "Vire a alavanca da energia",
        hud_heist_sand30 = "Vocês precisam virar a alavanca da energia para sobrecarregar os eletrônicos do teclado.",
        
        hud_heist_sand31_hl = "Encontre e ligue o nitrogênio líquido",
        hud_heist_sand31 = "O teclado deve ficar duro que nem gelo pra quebrar. Encontre um líquido nitrogênio e coloque nele.",
        
        hud_heist_sand32_hl = "Use uma ferramenta para abrir o contêiner",
        hud_heist_sand32 = "Algum tipo de ferramenta é necessário para entrar no contêiner.",
        
        hud_heist_sand33_hl = "Ressucite Vlad",
        hud_heist_sand33 = "Vlad está inconsciente e precisa se ressucitado!",
        
        hud_heist_sand34_hl = "Pegue o disco rígido da tríade",
        hud_heist_sand34 = "O disco rígido contendo as informações da tríade precisa ser roubado.",
        
        hud_heist_sand35_hl = "Chame pelo barco de fuga",
        hud_heist_sand35 = "O barco de resgate deve ser sinalizado de alguma forma. Procure por algo 'explosivo' para atrair sua atenção.",
        
        hud_heist_sand36_hl = "Abra o portão",
        hud_heist_sand36 = "O caminho está bloqueado. Vocês precisam abrir o portão para o carregador de skid poder continuar.",
        
        hud_heist_sand37_hl = "Recoloque o nitrogênio líquido",
        hud_heist_sand37 = "A policia removeu o nitrogênio líquido. Recoloque-o.",
        
        hud_heist_sand38_hl = "Proteja o nitrogênio líquido",
        hud_heist_sand38 = "Proteja o nitrogênio líquido da polícia.",
        
        hud_heist_sand39_hl = "Encontre a sala do servidor",
        hud_heist_sand39 = "Localize a sala do servidor e veja se tem algo que vale a pena roubar.",
        
        hud_heist_sand40_hl = "Hackeie o computador",
        hud_heist_sand40 = "Hackeie os dados para determinar qual servidor tem a informação que precisam.",
        
        hud_heist_sand41_hl = "Encontre uma maneira de sinalizar por extração",
        hud_heist_sand41 = "Procure pelas docas por algo que pode ser usado para sinalizar extração.",
        
        hud_heist_sand42_hl = "Sinalize por extração",
        hud_heist_sand42 = "Acenda os fogos de artíficio para Jiu Feng saber que tem que vir.",
        
        hud_heist_sand43_hl = "Espere pela extração",
        hud_heist_sand43 = "Vai demorar um tempo para Jiu Feng pegar vocês. Segurem firme!",
        
        hud_heist_sand44_hl = "Vá ao depósito B",
        hud_heist_sand44 = "Sabemos onde Vlad está agora. Entrem lá e libertem-o!",
        
        hud_heist_sand45_hl = "Vá ao depósito C",
        hud_heist_sand45 = "Sabemos onde Vlad está agora. Entrem lá e libertem-o!",
        
        hud_heist_sand46_hl = "Abaixe as barricadas",
        hud_heist_sand46 = "As barricadas precisam ser abaixadas para o carregador de skid continuar andando.",
        
        hud_heist_sand47_hl = "Escolha um segundo caminho",
        hud_heist_sand47 = "Escolha um caminho entre mover o caminhão e abrir o portão do depósito.",
        
        hud_heist_sand48_hl = "Resuma o hack",
        hud_heist_sand48 = "A polícia interferiu com o hack. Reiniciem-o para continuar.",
        
        hud_heist_sand49_hl = "Mova a rampa",
        hud_heist_sand49 = "A rampa precisa ser movida para descer no lado do navio para as docas.",
        
        hud_heist_sand50_hl = "Assegure o servidor",
        hud_heist_sand50 = "O servidor precisa ser assegurado no barco antes que possam escapar.",
        
        hud_heist_sand51_hl = "Encontre gasolina para começar um fogo",
        hud_heist_sand51 = "Para sinalizar ao Jiu Feng no barco, comece um fogo perto da borda da doca.",
        
        hud_heist_sand52_hl = "Mova a paleteira",
        hud_heist_sand52 = "Uma paleteira está bloqueando o caminho, livrem-se dela.",
        
        --hud_heist_sand53_hl = "hud_heist_sand53_hl",
        --hud_heist_sand53 = "hud_heist_sand53",
        --
        --hud_heist_sand54_hl = "hud_heist_sand54_hl",
        --hud_heist_sand54 = "hud_heist_sand54",
        --
        --hud_heist_sand55_hl = "hud_heist_sand55_hl",
        --hud_heist_sand55 = "hud_heist_sand55",

        -- Pre-Planning
        menu_pp_asset_sand_broken_wall = "Parede Quebrada",--Broken Wall
        menu_pp_asset_sand_broken_wall_desc = "Nosso contato fez a nossa entrada mais fácil.",--Our inside man has made our infiltration easier.
        menu_pp_asset_sand_extra_dumpsters = "Depósitos de Lixo Extras",--Extra Dumpsters
        menu_pp_asset_sand_extra_dumpsters_desc = "Um jeito mais fácil de se livrar das bolsas, use os depósitos.",--For an easier time getting rid of bags, use the dumpsters.
        menu_pp_asset_sand_ladder_bridge = "Ponte de Escada",--Ladder Bridge
        menu_pp_asset_sand_ladder_bridge_desc = "Infiltre-se furtivamente no prédio principal com a ajuda de uma escada.",--Sneak into the main building with the help of a ladder.
        menu_pp_asset_sand_less_camera_drones = "Menos Drones",--Less Drones
        menu_pp_asset_sand_less_camera_drones_desc = "Alguns drones estão em manuntenção.",--Some of the drones have been tampered with.
        menu_pp_sand_bpr_loc_a = "Térreo",--Ground Level
        menu_pp_sand_bpr_loc_b = "Primeiro Andar",--First floor
        menu_pp_sand_broken_wall = "Rua",--Street
        menu_pp_sand_sniper001 = "Depósitos",--Warehouses
        menu_pp_sand_sniper002 = "Guindaste Pequeno",--Small Crane
        menu_pp_sand_sniper003 = "Guindaste Grande",--Large Crane
        menu_pp_sand_ladder = "Beco de trás",--Back alley
        menu_pp_sand_drones = "Porto",--Harbor
        menu_pp_sand_dumpster001 = "Área de Carregamento",--Loading Area
        menu_pp_sand_dumpster002 = "Portão de Segurança",--Security Gate
        menu_pp_sand_dumpster003 = "Escritório do Porto",--Harbor Office
    })
end)