Hooks:Add("LocalizationManagerPostInit", "qualbuildeuusoprodsod", function(loc)
	LocalizationManager:add_localized_strings({
	-- Generic
	st_menu_point = "$points ponto",
	st_menu_point_plural = "$points pontos",
	st_menu_skill_owned = "Obtido",
	st_menu_skill_cost_singular = "BÁSICO: $basic ponto / AVANÇADO: $aced pontos.",
	st_menu_skill_maxed = "AVAN.",
	st_menu_skill_cost = "BÁSICO: $basic pontos / AVANÇADO: $aced pontos.",
	menu_st_skilltree = "Habilidades",
	menu_st_points_unlock_tier = "Cam. $tier",
	menu_st_points_total = "Total de pontos",
	menu_st_points_unlock = "Pont. para conquistar",
	menu_st_points_unspent_skill_switch = "$points Pontos restantes",
	menu_st_points_all_spent_skill_switch = "Nenhum ponto sobrando",
	menu_st_switch_skillset = "[S] para trocar as Habilidades",
	skill_tree_reset_all_skills_button = "[R] para resetar tudo",
	skill_tree_reset_skills_button = "[F] para resetar só essas habilidades ",
	menu_skillpoints = "Pontos restantes",
	menu_st_locked_skill_switch = "Bloqueado",
	menu_st_skill_switch_title_name = "Habilidades: ",
	menu_st_make_active_skill_switch = "Usar",
	menu_st_active_skill_switch = "Em uso",
	menu_st_unlock_skill_switch = "Desbloquear",
	menu_st_req_offshore_skill_switch = "Conta Secundária $offshore",
	menu_st_req_achievement_skill_switch = 'Conquista "$achievement"',
	menu_st_requires_skill_switch = "Requisitos: $reasons",
	menu_st_skill_switch_title = "Trocar de Habilidades e Perk Deck",
	menu_mouse_refund = "Tirar ponto",
	menu_mouse_invest = "Adcionar ponto",
	dialog_unlock_skill_switch = "Tem certeza que deseja comprar um novo set de habilidade salva? \n\nIsso vai lhe-custar $30,000,000 da sua conta Secundária",
	dialog_unlock_skill_switch_title = "Tem certeza?",
	menu_st_skill_switch_1 = "Habilidade salva #1",
	menu_st_skill_switch_2 = "Habilidade salva #2",
	menu_st_skill_switch_3 = "Habilidade salva #3",
	menu_st_skill_switch_4 = "Habilidade salva #4",
	menu_st_skill_switch_5 = "Habilidade salva #5",
	menu_st_skill_switch_6 = "Habilidade salva #6",
	menu_st_skill_switch_7 = "Habilidade salva #7",
	menu_st_skill_switch_8 = "Habilidade salva #8",
	menu_st_skill_switch_9 = "Habilidade salva #9",
	menu_st_skill_switch_10 = "Habilidade salva #10",
	menu_st_skill_switch_11 = "Habilidade salva #11",
	menu_st_skill_switch_12 = "Habilidade salva #12",
	menu_st_skill_switch_13 = "Habilidade salva #13",
	menu_st_skill_switch_14 = "Habilidade salva #14",
	menu_st_skill_switch_15 = "Habilidade salva #15",
	
	-- Mastermind
	-- First Tree (Medic)
	--st_menu_mastermind_inspire = "Médico",
	--menu_combat_medic_beta = "Médico de Combate",
	menu_combat_medic_beta_desc = "BÁSICO: ##$basic##\nVocê ganha uma resistência de dano de ##30%## por ##5## segundos quando reviver alguém ou enquanto estiver revivendo. \n\nAVANÇADO: ##$pro##\nDepois de reviver alguém, isso dará a ele ##30%## a mais de vida.",
	--menu_tea_time_beta = "Médico Rápido",
	menu_tea_time_beta_desc = "BÁSICO: ##$basic##\nAumenta a sua velocidade de interação com os seus Equipamentos de Médico. \n\nAVANÇADO: ##$pro##\nMembros da Equipe que usarem os seus Equipamentos de Médico vão ter resistência de dano de ##10%## por ##120## segundos.",
	--menu_fast_learner_beta = "Nem vai doer",
	menu_fast_learner_beta_desc = "BÁSICO: ##$basic##\nSe você reviver alguém da sua Equipe, ele terá uma resistência de dano de ##30%## por ##5## segundos. \n\nAVANÇADO: ##$pro##\nA resistência de dano é aumentada por ##50%##.",
	--menu_medic_2x_beta = "Médico de Guerra",
	menu_medic_2x_beta_desc = "BÁSICO: ##$basic##\nPode ter duas ##Doctor Bags## invés de uma.  \n\nAVANÇADO: ##$pro##\nAs suas ##Doctor Bags## terão mais dois usos.",
	--menu_tea_cookies_beta = "Preguiçoso",
	menu_tea_cookies_beta_desc = "BÁSICO: ##$basic##\nAdiciona mais ##7 First Aid Kits## no seu inventário \n\nAVANÇADO: ##$pro##\nAdiciona mais ##3 First Aid Kits## no seu inventário. A sua ##First Aid Kit## colocada no chão irá automaticamante ajudar você, ou os seus companheiros, se você cair dentro de ##5## metros do seu ##First Aid Kit##. ISSO NÃO PODE OCORRER MAIS DE UMA VEZ DURANTE ##20## SEGUNDOS.",
	--menu_inspire_beta = "Ídolo",
	menu_inspire_beta_desc = "BÁSICO: ##$basic##\nVocê vai reviver os seus companheiros de Equipe ##100%## mais rápido. Se gritar, que nem uma mãe brava com um chinelo, nos seus companheiros irá dá a eles um aumento de ##20%## para velocidade do movimento e de recarregar a arma por ##10## segundos. \n\nAVANÇADO: ##$pro##\nTem uma chance de ##100%## que você vai reviver os seus companheiros se gritar, de novo que nem uma mãe brava com um chinelo, em uma distância de ##9## metros. ISSO NÃO PODE OCORRER MAIS DE UMA VEZ DURANTE ##20## SEGUNDOS.",
	
	-- Second Tree (Controller)
	--st_menu_mastermind_dominate = "Sedutor",
	--menu_triathlete_beta = "Pedido de Amizade",
	menu_triathlete_beta_desc = "BÁSICO: ##$basic##\nAumenta a quantidade das suas abraçadeiras por ##4##. Você pode prender os reféns ##75%## mais rápido. \n\nAVANÇADO: ##$pro##\nVocê e a sua Equipe ganham ##0.5## de absorção de dano para cada refém que você tem. Esse efeito só vai até ter ##8## reféns. \n\nNota: Esse efeito não soma com os outros jogadores que tiverem essa habilidade.",
	--menu_cable_guy_beta = "Confiante",
	menu_cable_guy_beta_desc = "BÁSICO: ##$basic##\nO alcance e o medo da sua íntimidação é aumentada por ##50%## \n\nAVANÇADO: ##$pro##\nAgora pode ter ##2## políciais convertidos.",
	--menu_joker_beta = "Coringa",
	menu_joker_beta_desc = "BÁSICO: ##$basic##\nVocê pode converter um policial, não os especiais, para lutarem no seu lado. \nNão pode ser feito durante o Stealth e o policial deve está rendido para poder ser convertido. \n\nVocê só pode ter um policial convertido de uma vez. \n\nAVANÇADO: ##$pro##\nO seu convertido dá ##35%## de dano a mais. O tempo pra converter o policial é diminuida por ##65%##.",
	--menu_control_freak_beta = "Amigos do Peito",
	menu_control_freak_beta_desc = "BÁSICO: ##$basic##\nTendo um convertido irá aumentar a sua velocidade do movimento por ##10%## \n\nO seu convertido terá uma resistência de dano de ##45%## \n\nAVANÇADO: ##$pro##\nTendo um convertido irá aumentar a sua vida por ##30%## \n\nO seu convertido terá mais resistência de dano de ##54%##.",
	--menu_stockholm_syndrome_beta = "Síndrome de Estocol.",
	menu_stockholm_syndrome_beta_desc = 'BÁSICO: ##$basic##\nCivis são íntimidados pelo barulho que você faz e ficam mais quietos por ##50%##. \n\nAVANÇADO: ##$pro##\nOs seus reféns não irão fugir quando são resgatados pela policia. Quando você for preso, o seu refém irá "salvar" você. Esse efeito só pode ocorrer durante as ondas, só ##UMA## vez por Golpe.',
	--menu_black_marketeer_beta = "Domador de Refém",
	menu_black_marketeer_beta_desc = "BÁSICO: ##$basic##\nTendo pelo menos um refém ou um policial convertido, irá ter uma cura de ##1.5%## todo ##5## segundos. \n\nAVANÇADO: ##$pro##\nTendo pelo menos um refém ou um policial convertido, irá ter uma cura de ##4.5%## todo ##5## segundos.",
	
	-- Third Tree (Sharpshooter)
	--st_menu_mastermind_single_shot = "Mira Certeira",
	--menu_stable_shot_beta = "Firme",
	menu_stable_shot_beta_desc = "BÁSICO: ##$basic##\nVocê ganha ##8## de Estabilidade para todas as armas. \n\nAVANÇADO: ##$pro##\nVocê tem mais ##16## de Precisão enquanto fica parado.",
	--menu_rifleman_beta = "Rifleiro",
	menu_rifleman_beta_desc = "BÁSICO: ##$basic##\nO seu zoom é ##100%## mais rápido com todas as armas. \n\nA sua velocidade do movimento não é afetada enquanto mira. \n\nAVANÇADO: ##$pro##\nO nível do seu zoom é aumentada por ##25%## para todas as armas. A Precisão da sua arma aumenta por ##16## enquanto se move.",
	--menu_sharpshooter_beta = "Um tiro por vez",
	menu_sharpshooter_beta_desc = "BÁSICO: ##$basic##\nVocê ganha ##8## de Precisão para Submetralhadoras, Rifles de Assalto e Rifles de Sniper com o modo de um tiro. \n\nAVANÇADO: ##$pro##\n Você ganha ##20%## de Precisão a mais enquanto mira com todas as Submetralhadoras, Rifles de Assalto e Rifles de Sniper com o modo de um tiro.",
	--menu_speedy_reload_beta = "Velocidade Agressiva",
	menu_speedy_reload_beta_desc = "BÁSICO: ##$basic##\nAumenta a sua velocidade de recarregar todas as Submetralhadoras, Rifles de Assalto e Rifles de Sniper por ##15%## \n\nAVANÇADO: ##$pro##\nQualquer tiro na cabeça irá aumentar a sua velocidade de recarregar a sua arma por ##100%## por ##4## segundos. Só pode ser ativado por Submetralhadoras, Rifles de Assalto e Rifles de Sniper com o modo de um tiro.",
	--menu_single_shot_ammo_return_beta = "Munição Grátis",
	menu_single_shot_ammo_return_beta_desc = "BÁSICO: ##$basic##\nTendo ##3## tiros na cabeça em menos de ##6## segundos, você ganha ##1## bala para a sua arma equipada. Só pode ser ativado com Submetralhadoras, Rifles de Assalto e Rifles de Sniper com o modo de um tiro. \n\nAVANÇADO: ##$pro##\nA quantidade de tiros na cabeça necessária é reduzida para ##2##.",
	--menu_sniper_graze_damage = "Raspada",
	menu_sniper_graze_damage_desc = "BÁSICO: ##$basic##\n##Snipers## que acertarem o alvo irá dá ##20%## do dano em um raio de ##100cm## da trajetória da bala. \n\nAVANÇADO: ##$pro##\nSe acertar um tiro na cabeça, a habilidade ##Graze## irá dá ##100%## do dano da arma invés de ##20%##.",
	
	-- Enforcer
	-- First Tree (Shotgunner)
	--st_menu_enforce_shotgun = "Doze",
	--menu_underdog_beta = "Abaixado",
	menu_underdog_beta_desc = "BÁSICO: ##$basic##\nQuando tiver três ou mais inimigos em um raio de ##18## metros mirando em você, receberá ##15%## de dano bônus que dura ##7## segundos. \n\nAVANÇADO: ##$pro##\nQuando tiver três ou mais inimigos em um raio de ##18## metros mirando em você, receberá ##15%## de resistência a dano que dura ##7## segundos. \n\nNota: Isso não aplica a dano da arma corpo-a-corpo, granadas, lança-granadas ou RPGs.",
	--menu_shotgun_cqb_beta = "Pertinho",
	menu_shotgun_cqb_beta_desc = "BÁSICO: ##$basic##\nVocê recarrega a sua Espinguarda ##15%## mais rápido. \n\nAVANÇADO: ##$pro##\nVocê recarrega a sua Espinguarda ##25%## mais rápido. Você consegue mirar com a Espinguarda ##125%## mais rápido.",
	--menu_shotgun_impact_beta = "Chumbo Grosso",
	menu_shotgun_impact_beta_desc = "BÁSICO: ##$basic##\nA sua estabilidade com as Espinguardas é aumentada por ##8##. Você dá ##5%## a mais de dano com as Espinguardas. \n\nAVANÇADO: ##$pro##\nVocê dá ##10%## a mais de dano com as Espinguardas.",
	--menu_close_by_beta = "Corre Locaço",
	menu_close_by_beta_desc = "BÁSICO: ##$basic##\nAgora você pode fazer correr e atirar ao mesmo tempo com as Espinguardas. \n\nAVANÇADO: ##$pro##\nVocê atira ##35%## mais rápido enquanto não mira e com o modo de um tiro com as Espinguardas. Espinguardas com carregadores terão mais ##15## balas.",
	--menu_far_away_beta = "Bem Longe",
	menu_far_away_beta_desc = "BÁSICO: ##$basic##\nA sua precisão com as suas Espinguardas é aumentada por ##40%## enquanto mira. \n\nAVANÇADO: ##$pro##\nVocê ganha um alcance effetivo de ##50%## enquanto mira com as Espinguardas.",
	--menu_overkill_beta = "Exagero",
	menu_overkill_beta_desc = "BÁSICO: ##$basic##\nQuando você mata alguém com uma Espinguarda ou com a ##OVE9000 Saw##, você recebe um bônus ##75%## a mais de dano por ##20## segundos. \n\nAVANÇADO: ##$pro##\nO bônus do dano será aplicado para todas as armas, mas o bônus ainda precisa ser ativada usando uma Espinguarda ou a serra. A sua velocidade de trocar as armas é aumentada por ##80%## \n\nNota: Isso não aplica a dano da arma corpo-a-corpo, granadas, lança-granadas ou RPGs.",
	
	-- Second Tree (Tank)
	--st_menu_enforcer_armor = "Tanque",
	--menu_oppressor_beta = "Resistência",
	menu_oppressor_beta_desc = "BÁSICO: ##$basic##\nAumenta a velocidade do seu colete para se recuperar em ##15%##. \n\nAVANÇADO: ##$pro##\nReduz o tempo da ##Flashbang## que explodiu na sua cara por ##75%##.",
	--menu_show_of_force_beta = "Duro de Matar",
	menu_show_of_force_beta_desc = "BÁSICO: ##$basic##\nVocê ganha uma resistência de dano por ##50%## enquanto faz interação com objetos. \n\nAVANÇADO: ##$pro##\nAumenta todos os coletes por ##20##. Não conta o terno.",
	--menu_pack_mule_beta = "Mula",
	menu_pack_mule_beta_desc = "BÁSICO: ##$basic##\nVocê pode jogar as bolsas ##50%## mais longe. \n\nAVANÇADO: ##$pro##\nPara cada ##10## pontos de colete, a penalidade de movimento das bolsas é reduzida por ##1%##.",
	--menu_prison_wife_beta = "Na Mosca",
	menu_prison_wife_beta_desc = "BÁSICO: ##$basic##\nVocê regenera ##5## de colete para cada tiro na cabeça que você faz. Não pode ocorrer mais do que uma vez todo ##2## segundos. \n\nAVANÇADO: ##$pro##\nVocê regenera mais ##20## de colete para cada tiro na cabeça.",
	--menu_iron_man_beta = "Em Shock",
	menu_iron_man_beta_desc = "BÁSICO: ##$basic##\nAumenta a velocidade do seu colete, e da sua equipe, para se recuperar em ##25%##. \n\nAVANÇADO: ##$pro##\nAs suas armas agora pode atordoar os ##Shields##. Quanto maior o dano da arma, maior a chance de atordoar. A chance de atordoar com as armas corpo-a-corpo é aumentada para ##100%##.",
	--menu_juggernaut_beta = "Não é água com músculo",
	menu_juggernaut_beta_desc = "BÁSICO: ##$basic##\nA quantidade do seu colete é aumentada por ##30%##. \n\nAVANÇADO: ##$pro##\nDesbloqueia o ##Improved Combined Tactical Vest##.",
	
	-- Third Tree (Ammo Specialist)
	--st_menu_enforcer_ammo = "Expert em Munição",
	--menu_scavenging_beta = "Procurando",
	menu_scavenging_beta_desc = "BÁSICO: ##$basic##\nO seu alcance da munição dropada aumenta em ##50%##. \n\nAVANÇADO: ##$pro##\nTodo sexto inimigo que matar, irá dropar munição extra.",
	--menu_ammo_reservoir_beta = "Munição Infinita",
	menu_ammo_reservoir_beta_desc = "BÁSICO: ##$basic##\nAs ##Ammo Bags## que foram colocados por você e serem usados pelo os outros (ou por você) terá munição infinita por ##5## segundos. Quanto mais munição recuperar, mais tempo dura o efeito. \n\nAVANÇADO: ##$pro##\nA duração aumenta pra ##15## segundos.",
	--menu_portable_saw_beta = "Serra Portátil",
	menu_portable_saw_beta_desc = "BÁSICO: ##$basic##\nDesbloqueia a ##OVE9000 Saw## para ser usada como sua arma secundária. \n\nAVANÇADO: ##$pro##\nVocê ganha ##1## serra extra para ##OVE9000 Saw##. Além disso, as serras são substituídas por serras de carbono, aumentando a eficiência da serra por ##40%##.",
	--menu_carbon_blade_beta = "Leatherface",
	menu_carbon_blade_beta_desc = "BÁSICO: ##$basic##\nReduz o desgaste da serra enquanto você usa nos políciais por ##50%## \n\nAVANÇADO: ##$pro##\nVocê pode serrar através dos escudos das ##Shields## com a ##OVE9000 Saw##. Quando você mata alguém com ##OVE9000 Saw##, tem uma chance de ##50%## de causar pânico aos políciais que estiverem em um raio de ##10## metros de você. O pânico irá fazer o policial lembrar dos seus pesadelos e ficará descomfortável.",
	--menu_ammo_2x_beta = "Munição Extra",
	menu_ammo_2x_beta_desc = "BÁSICO: ##$basic##\nAgora você pode ter ##2 Ammo Bags## invés de uma. \n\nAVANÇADO: ##$pro##\nCada ##Ammo Bag## que você tiver terá ##50%## a mais de munição.",
	--menu_bandoliers_beta = "Bem Preparado",
	menu_bandoliers_beta_desc = 'BÁSICO: ##$basic##\nAumenta a munição que você pega das munições dropadas por ##25%##. \n\nAVANÇADO: ##$pro##\nVocê também ganha uma base de ##5%## de conseguir uma granada das munições dropadas. Se não conseguir uma granada, a base aumenta por ##1%##. Quando conseguir uma granada, a base reseta. \n\nNota: Isso não soma com o Perk Deck "Walk-In Closet".',
	
	-- Technician
	-- First Tree (Engineer)
	--st_menu_technician_sentry = "Engenhoca",
	--menu_defense_up_beta = "Terceira Lei",
	menu_defense_up_beta_desc = "BÁSICO: ##$basic##\nO tempo para colocar uma ##Sentry## é reduzida por ##5%##. \n\nAVANÇADO: ##$pro##\nSuas ##Sentries## agora tem um escudo que proteje ele.",
	--menu_sentry_targeting_package_beta = "Sentinela de Alvo",
	menu_sentry_targeting_package_beta_desc = "BÁSICO: ##$basic##\nSuas ##Sentries## ficam mais ##100%## mais precisas. \n\nAVANÇADO: ##$pro##\nA velocidade da rotação das suas ##Sentries## é aumentada por ##150%##. As suas ##Sentries## também tem ##50%## mais de munição.",
	--menu_eco_sentry_beta = "Eco Sistema",
	menu_eco_sentry_beta_desc = "BÁSICO: ##$basic##\nO tempo para colocar uma ##Sentry## é reduzida por ##5%##. \n\nAVANÇADO: ##$pro##\nA vida das suas ##Sentries## é aumentada por ##150%##.",
	--menu_jack_of_all_trades_beta = "Pau pra toda obra",
	menu_jack_of_all_trades_beta_desc = "BÁSICO: ##$basic##\nA velocidade das suas interações e de colocar todos os Equipamentos é aumentada por ##100%##. \n\nAVANÇADO: ##$pro##\nAgora você pode equipar um Equipamento secundário. Se um Equipamento for equipado como secundário, você apenas poderá levar a metade do que você levaria se fosse primária. \n\nAperte  para trocar de Equipamentos.",
	--menu_engineering_beta = "Ignorado",
	menu_engineering_beta_desc = "BÁSICO: ##$basic##\nVocê pode equipar uma ##Sentry## que faz menos barulho, fazendo ter menos atenção dos policiais. \n\nAVANÇADO: ##$pro##\nAgora você pode mudar o tipo de munição das suas ##Sentries##, as ##AP##, abaixando a velocidade de tiro por ##75%##, mas aumenta o dano por ##250%## e permitindo que a bala atravesa os escudos dos ##Shields## e os coletes de alguns inimigos.",
	--menu_tower_defense_beta = "Defensivo",
	menu_tower_defense_beta_desc = "BÁSICO: ##$basic##\nAgora você pode carregar uma ##Sentry## extra. \n\nAVANÇADO: ##$pro##\nVocê pode carregar mais ##duas Sentries##.",
	
	-- Second Tree (Breacher)
	--st_menu_technician_breaching = "Arrombador",
	--menu_hardware_expert_beta = "Expert em Hardware",
	menu_hardware_expert_beta_desc = "BÁSICO: ##$basic##\nVocê pode consertar as brocas e serras ##25%## mais rápido. Reduz o tempo de colocar as ##Trip Mines## por ##20%##. Brocas e serras agora são silênciosas. Civis e guardas agora devem ver a sua broca ou serra para ficarem alertados. \n\nAVANÇADO: ##$pro##\nSua broca ou serra ganham uma chance de ##10%## para se consertarem depois de quebrarem. \n\nNota: esse efeito não se aplica ao ##OVE9000 Saw##.",
	--menu_combat_engineering = "Campo Minado",
	menu_combat_engineering_desc = "BÁSICO: ##$basic##\nO raio da explosão da sua ##Trip Mines## é aumentada ##30%##. \n\nAVANÇADO: ##$pro##\nO dano da sua mina é aumentada por ##50%##", --https://i.imgur.com/8EI9oRa.png
	--menu_drill_expert_beta = "Profissa em Broca",
	menu_drill_expert_beta_desc = "BÁSICO: ##$basic##\nO timer da sua broca ou serra é diminuida por ##15%##. \n\nAVANÇADO: ##$pro##\nO timer da sua broca ou serra é diminuida ainda mais por ##15%##. \n\nNota: esse efetio não aplica ao ##OVE9000 Saw##.",
	--menu_kick_starter_beta = "Ponta-pé",
	menu_kick_starter_beta_desc = "BÁSICO: ##$basic##\nAs suas brocas e serras ganham ##20%## a mais de chance de se consertar assim que quebra. \n\nAVANÇADO: ##$pro##\nAgora pode consertar as suas brocas ou serras com um ataque de alguma arma corpo-a-corpo. Tem ##50%## de chance de consertar a broca ou serra. Só pode ser usada uma vez por broca ou serra quebrada. \n\nNota: esse efeito não aplica ao ##OVE9000 Saw##.",
	--menu_more_fire_power = "Mais fogo",
	menu_more_fire_power_desc = "BÁSICO: ##$basic##\nVocê ganha mais um ##Shaped Charge## e mais quatro ##Trip Mines##. \n\nAVANÇADO: ##$pro##\nGanha mais dois ##Shaped Charges## e mais sete ##Trip Mines##.",
	--menu_fire_trap_beta = "Fogo no rabo",
	menu_fire_trap_beta_desc = "BÁSICO: ##$basic##\nAs suas ##Trip Mines## agora espalhem fogo na área de ##4## metros por ##10## segundos. \n\nAVANÇADO: ##$pro##\nAumenta a duração do fogo por ##10## segundos e aumenta a área do fogo espalhado por ##50%##.",
	
	-- Third Tree (Oppressor)
	--st_menu_technician_auto = "Tirano",
	--menu_steady_grip_beta = "Focado",
	menu_steady_grip_beta_desc = "BÁSICO: ##$basic##\nGanha ##8## de precisão para todas as armas. \n\nAVANÇADO: ##$pro##\nGanha ##16## de estabilidade para todas as armas.",
	--menu_heavy_impact_beta = "Soco na cara",
	menu_heavy_impact_beta_desc = "BÁSICO: ##$basic##\nOs seus tiro tem uma chance de ##5%## de atordoar todos os inimigos, exceto os ##Bulldozers## e os ##Captains Winters##. \n\nAVANÇADO: ##$pro##\nA chance aumenta até ##20%##.",
	--menu_fire_control_beta = "Controle de tiro",
	menu_fire_control_beta_desc = "BÁSICO: ##$basic##\nGanha ##12## de precisão quando atira sem mirar. \n\nAVANÇADO: ##$pro##\nA sua penalidade de precisão, enquanto se move, é diminuida por ##20%##",
	--menu_fast_fire_beta = "Bala extra",
	menu_fast_fire_beta_desc = 'BÁSICO: ##$basic##\nSuas Submetralhadoras, Rifles de Assalto e Armas Pesadas ganham ##15## balas nos seus carregadores. Isso não afeta a habilidade avançada do "Carregar e Atira". \n\nAVANÇADO: ##$pro##\nOs seus Rifles de Assalto podem dá dano no colete de alguns inimigos. \n\nNota: Isso não aplica a as armas que você joga.',
	--menu_shock_and_awe_beta = "Carregar e Atirar",
	menu_shock_and_awe_beta_desc = "BÁSICO: ##$basic##\nVocê pode correr e atirar ao mesmo tempo com as suas armas. \n\nAVANÇADO: ##$pro##\nMatando ##2## inimigos com Submetralhadoras, Rifles de Assalto, Armas Pesadas ou Armas Especiais, com o modo automático, vai aumentar a velocidade de recarregar a arma até ##100%##. Esse bônus é reduzido por ##1%## para cada bala dentro do carregador, acima de ##20##, o mínimo é ##40%## de velocidade de recarregar a arma.",
	--menu_body_expertise_beta = "Especialista em corpo",
	menu_body_expertise_beta_desc = "BÁSICO: ##$basic##\nOs ##30%## de bônus do dano do tiro da cabeça é permanente aplicada quando atira no qualquer parte do corpo. Isso só aplica nas Submetralhadoras, Rifles de Assalto, Armas Pesadas ou Armas Especiais, com o modo automático. \n\nAVANÇADO: ##$pro##\nOs ##90%## de bônus do dano do tiro da cabeça é permanente aplicada quando atira no qualquer parte do corpo. Isso só aplica nas Submetralhadoras, Rifles de Assalto, Armas Pesadas ou Armas Especiais, com o modo automático.",
	
	-- Ghost
	-- First Tree (Shinobi)
	--st_menu_ghost_stealth = "Shinobi",
	--menu_jail_workout_beta = "Despercebido",
	menu_jail_workout_beta_desc = "BÁSICO: ##$basic##\nAumenta o tempo necessário que você pode ser detectado por ##25%## enquanto estiver em modo de revestimento. \n\nAVANÇADO: ##$pro##\nVocê pode pegar itens enquanto estiver em modo de revestimento. Também ganha um bônus de ##30%## para todo item de valor que você pegar.",
	--menu_cleaner_beta = "Zelador",
	menu_cleaner_beta_desc = "BÁSICO: ##$basic##\nVocê ganha mais uma ##Body Bag##. Também aumenta o seu espeço de ##Body Bags## pra ##3##. \n\nAVANÇADO: ##$pro##\nGanha a abilidade de ter ##2 Body Bag Cases##.",
	--menu_chameleon_beta = "Bicho parado",
	menu_chameleon_beta_desc = "BÁSICO: ##$basic##\nGanha a abilidade de automaticamante marcar os guardas dentro de ##10## metros de você depois de ficar parado por ##3.5## segundos, só funciona no Stealth. \n\nAVANÇADO: ##$pro##\nGanha acesso ao todos os preparos de contatos. Os custos para matar um civil diminuí por ##75%##.",
	--menu_ecm_booster_beta = "Boost de ECM",
	menu_ecm_booster_beta_desc = "BÁSICO: ##$basic##\nA duração de desativar os alarmes e o ##feedback## do ##ECM## é aumentada por ##25%##. \n\nAVANÇADO: ##$pro##\nO seu ##ECM## pode ser usado para abrir certas portas.",
	--menu_second_chances_beta = "Ágil",
	menu_second_chances_beta_desc = "BÁSICO: ##$basic##\nTem a abilidade de desativar ##1## câmera de segurança de detectar você e os seus companheiros. O efeito dura até ##25## segundos. \n\nAVANÇADO: ##$pro##\nO tempo do seu seu ##Lockpicking## é ##100%## mais rápido.",
	--menu_ecm_2x_beta = "Especialista em ECM",
	menu_ecm_2x_beta_desc = "BÁSICO: ##$basic##\nAgora você pode colocar ##2 ECMs## invés de uma. \n\nAVANÇADO: ##$pro##\nA duração de desativar os alarmes é aumentada por ##25%## e a duração do ##feedback## dura ##25%## mais longo. chamadas de Pagers são bloqueados pelo ##ECM##.",
	
	-- Second Tree (Artful Dodger)
	--st_menu_ghost_concealed = "Xitado",
	--menu_sprinter_beta = "Agachar e Cobertura",
	menu_sprinter_beta_desc = "BÁSICO: ##$basic##\nO seu vigor começa a se regenerar ##25%## antes e mais rápido. Também você corre ##25%## mais rápido. \n\nAVANÇADO: ##$pro##\nVocê ganha uma chance de ##10%## de desviar enquanto corre. Você tem uma chance de ##15%## enquanto tá a zip-line.",
	--menu_awareness_beta = "Parkoureiro",
	menu_awareness_beta_desc = "BÁSICO: ##$basic##\nGanha mais ##10%## de velocidade de movimento e mais ##20%## de velocidade para subir as escadas. \n\nAVANÇADO: ##$pro##\nGanha a abilidade de correr para qualquer direção. \n\nCorre e recarrega ao mesmo tempo.",
	--menu_thick_skin_beta = "Bolso mágico",
	menu_thick_skin_beta_desc = "BÁSICO: ##$basic##\nGanha ##2## de Discrição para todas as armas de corpo-a-corpo. \n\nAVANÇADO: ##$pro##\nGanha ##4## de Discrição para todos os coletes. Terno não conta.",
	--menu_insulation_beta = "À prova de choque",
	menu_insulation_beta_desc = "BÁSICO: ##$basic##\nQuando um ##Taser## te prende, tem uma chance de ##30%## do efeito retornar para ele, fazendo ele ficar atordoado. \n\nAVANÇADO: ##$pro##\nQuando um ##Taser## te prende, você vai poder se libertar do choque por spottar o ##Taser## que te prendeu em dentro de ##2## segundos.",
	--menu_dire_need_beta = "Necessi. Medonha",
	menu_dire_need_beta_desc = "BÁSICO: ##$basic##\nQuando o seu colete acaba, o inimigo que atirar primeiro em você, irá fazer ele ficar atordoado. Esse efeito acaba quando o seu colete se restaura. \n\nAVANÇADO: ##$pro##\nO efeito continua por ##6## segundos, assim que seu colete se restaura.",
	--menu_jail_diet_beta = "Explica essa jogada",
	menu_jail_diet_beta_desc = "BÁSICO: ##$basic##\nGanha uma chance de ##1%## de desviar para todo ##3## pontos de detecção abaixo de ##35%##, tendo o máximo de ##10%##. \n\nAVANÇADO: ##$pro##\nGanha uma chance de ##1%## de desviar para todo ##1## ponto de detecção abaixo de ##35##, tendo o máxido de ##10%##.",
	
	-- Third Tree (Silent Killer)
	--st_menu_ghost_silencer = "Silêncioso",
	--menu_scavenger_beta = "Segunda chance",
	menu_scavenger_beta_desc = "BÁSICO: ##$basic##\nQuando o seu colete acaba, a velocidade do seu movimento aumenta por ##30%## por ##5## segundos. \n\nAVANÇADO: ##$pro##\nEsse efeito aplica ao seus companheiros.",
	--menu_optic_illusions = "Você não viu nada",
	menu_optic_illusions_desc = "BÁSICO: ##$basic##\nTem uma chance de ##35%## de ser menos mirado pelo os inimigos. \n\nAVANÇADO: ##$pro##\nGanha ##1## de Discrição para cada arma com uma silenciadora equipada e reduz a penalidade de Discrição das armas por ##2##.",
	--menu_silence_expert_beta = "O Profissional",
	menu_silence_expert_beta_desc = "BÁSICO: ##$basic##\nGanha ##8## de estabilidade e ##100%## de velocidade de mirar a arma com a silenciadora. \n\nAVANÇADO: ##$pro##\nGanha ##12## de precisão para as armas com silenciadora.",
	--menu_spotter_teamwork_beta = "Alvo de alto valor",
	menu_spotter_teamwork_beta_desc = "BÁSICO: ##$basic##\nOs inimigos que você spottar vão tomar ##25%## mais de dano. \n\nAVANÇADO: ##$pro##\nOs inimigos que você marcar vão tomar mais ##50%## de dano quando estiverem longe mais do que ##10## metros de você. Aumenta a duração do inimigo está marcado por ##100%## e você pode spottar inimigos especiais enquanto estiver mirando.",
	--menu_backstab_beta = "Trapaça",
	menu_backstab_beta_desc = "BÁSICO: ##$basic##\nGanha uma chance de ##3%## dano crítico para todo ##3## pontos de detecção abaixo de ##35##, tendo o máxido de ##35%##. \n\nAVANÇADO: ##$pro##\nGanha uma chance de ##3%## dano crítico para todo ##1## ponto de detecção abaixo de ##35##, tendo o máxido de ##35%##. \n\nNota: Isso não aplica a lança-granadas.",
	--menu_unseen_strike_beta = "Tiro pela culatra",
	menu_unseen_strike_beta_desc = "BÁSICO: ##$basic##\nSe você não perdeu o seu colete ou vida por ##4## segundos, você ganha uma chance de ##35%## de dano crítico por ##6## segundos. \n\nAVANÇADO: ##$pro##\nA duração do dano crítico é aumentada até ##18## segundos. \n\nSe tomar dano, o efeito é cancelado.",
	
	-- Fugitive
	-- First Tree (Gunslinger)
	--st_menu_fugitive_pistol_akimbo = "Pistoleiro",
	--menu_equilibrium_beta = "Equilíbrio",
	menu_equilibrium_beta_desc = "BÁSICO: ##$basic##\nDiminuí o tempo de trocar para a pistola por ##33%##. \n\nAVANÇADO: ##$pro##\nGanha ##8## precisão para todas as pistolas.",
	--menu_dance_instructor = "Pistola grande",
	menu_dance_instructor_desc = "BÁSICO: ##$basic##\nO tamanho de carregador da pistola é aumentada por ##5## balas. \n\nAVANÇADO: ##$pro##\nAumenta o ritmo de tiro de todas as pistolas por ##50%##",
	--menu_akimbo_skill_beta = "Duas mãos",
	menu_akimbo_skill_beta_desc = "BÁSICO: ##$basic##\nA penalidade de estabilidade das armas de ##Akimbo## é diminuida por ##8##. \n\nAVANÇADO: ##$pro##\nA penalidade de estabilidade das armas de ##Akimbo## é diminuida mais ainda por ##8## e a munição total é aumentada por ##50%##.",
	--menu_expert_handling = "Desespero",
	menu_expert_handling_desc = "BÁSICO: ##$basic##\nPara cada tiro de pistola que você conseguir acertar irá te dar um bônus de ##10%## a mais de precisão e pode multiplicar por ##4##. \n\nAVANÇADO: ##$pro##\nVocê recarrega as pistolas ##50%%## mais rápido.",
	--menu_gun_fighter_beta = "Uma mão rápida",
	menu_gun_fighter_beta_desc = "BÁSICO: ##$basic##\nO dano base das pistolas é aumentada por ##5##. \n\nAVANÇADO: ##$pro##\nO dano base das pistolas aumenta mais ##10##.",
	--menu_trigger_happy_beta = "Gatilho Foda",
	menu_trigger_happy_beta_desc = "BÁSICO: ##$basic##\nPara cada acerto que você fizer com a pistola ganha um bônus de dano para a pistola de ##120%## que dura por ##2## segundos. Aumenta até ##1## vez. \n\nAVANÇADO: ##$pro##\nA duração do bônus de dano aumenta até ##4## segundos.",
	
	-- Second Tree (Revenant)
	--st_menu_fugitive_undead = "Morto-vivo",
	--menu_nine_lives_beta = "Mais sangue",
	menu_nine_lives_beta_desc = "BÁSICO: ##$basic##\nAumenta mais ##50%## da sua vida perdendo sangue. \n\nAVANÇADO: ##$pro##\nVocê tem mais ##uma## queda antes de ir pra custódia",
	--menu_running_from_death_beta = "Engana a morte",
	menu_running_from_death_beta_desc = "BÁSICO: ##$basic##\nVocê recarrega e troca de armas ##100%## mais rápido por ##10## segundos depois de ser ajudado. \n\nAVANÇADO: ##$pro##\nVocê corre ##30%## por ##10## segundos depois de ser ajudado.",
	--menu_up_you_go_beta = "Sai da cova",
	menu_up_you_go_beta_desc = "BÁSICO: ##$basic##\nVocê leva ##30%## menos de dano por ##10## segundos depois de ser ajudado. \n\nAVANÇADO: ##$pro##\nVocê recebe ##40%## mais de vida depois de ser ajudado.",
	--menu_feign_death = "Finge de Morto",
	menu_feign_death_desc = "BÁSICO: ##$basic##\nQuando você cai, tem uma chance de ##15%## que você vai levantar sozinho. \n\nAVANÇADO: ##$pro##\nA chance de ser levantado sozinho é aumentado por mais ##30%##.",
	--menu_perseverance_beta = "Música Poética",
	menu_perseverance_beta_desc = "BÁSICO: ##$basic##\nInvés de cair na hora, você ganha a abilidade de continuar em pé por ##3## segundos com uma penalidade de movimento de ##60%## antes de cair. \n\nNota: Esse efeito não ativa com dano de queda. \n\nAVANÇADO: ##$pro##\nAumenta a duração da ##Música Poética## por ##3## segundos. A munição é infinita. enquanto o efeito é ativado.",
	--menu_pistol_beta_messiah = "Messia",
	menu_pistol_beta_messiah_desc = "BÁSICO: ##$basic##\nNo momento que estiver caindo, você pode se reviver se conseguir matar um inimigo. Mas só tem ##UMA## chance. \n\nAVANÇADO: ##$pro##\nO seu ##Messia## é recuperado quando você consome a ##Doctor Bag##.",
	
	-- Third Tree (Brawler)
	--st_menu_fugitive_berserker = "Mete porrada",
	--menu_martial_arts_beta = "Artes Marciais",
	menu_martial_arts_beta_desc = "BÁSICO: ##$basic##\nVocê leva ##50%## menos de dano das armas corpo-a-corpo dos inimigos. Por causa de treino. ##(Because of training.)## \n\nAVANÇADO: ##$pro##\nTerá uma chance de ##50%## para atordoar um inimigo com uma pancada de alguma arma de corpo-a-corpo.",
	--menu_bloodthirst = "Sede de Sangue",
	menu_bloodthirst_desc = "BÁSICO: ##$basic##\nToda vítima que você matar com uma arma, que não seja de corpo-a-corpo, o seu dano da arma corpo-a-corpo aumenta por ##100%##, o máximo é ##1600%##. Esse efeito só reseta quando você mata alguém com a arma corpo-a-corpo. \n\nAVANÇADO: ##$pro##\nAssim que você mata alguém com a arma corpo-a-corpo, a sua velocidade de recarrega a arma aumenta por ##50%## por ##10## segundos.",
	--menu_steroids_beta = "Bomba de Ferro",
	menu_steroids_beta_desc = "BÁSICO: ##$basic##\nOs seus ataques de armas corpo-a-corpo vão fazer ##100%## mais de dano contra inimigos que não são especiais. \n\nAVANÇADO: ##$pro##\nOs seus ataques de armas corpo-a-corpo vão fazer ##100%## mais de dano contra inimigos especiais.",
	--menu_wolverine_beta = "Berserker",
	menu_wolverine_beta_desc = "BÁSICO: ##$basic##\nQuanto mais baixo a sua vida, mais dano você fará. Quando a sua vida estiver ##50%##, o máximo de dano da arma corpo-a-corpo e da serra que você fará é ##250%## \n\nAVANÇADO: ##$pro##\nO efeito irá se aplicar a armas de rifle. \n\nNota: Isso não aplica a granadas, lança-granadas ou RPGs. \n\nCom efeito de ##Berserker## negativa os efeitos de regeneração do terceiro.",
	--menu_drop_soap_beta = "Contra-Ataque",
	menu_drop_soap_beta_desc = "BÁSICO: ##$basic##\nQuando segura a arma de corpo-a-corpo, você vai contra-atacar o inimigo que vai tentar te bater com algum ataque corpo-a-corpo. O atordoamento não vai dá dano. \n\nAVANÇADO: ##$pro##\nGanha a habilidade de contra-atacar o chute de ##Cloaker##.",
	--menu_frenzy = "Delírio",
	menu_frenzy_desc = "BÁSICO: ##$basic##\nVocê só consegue ##30%## da sua vida e não pode se curar mais do que isso, mas você leva ##10%## menos de dano e a cura recebida é diminuida por ##75%##. \n\nAVANÇADO: ##$pro##\nO dano que você recebe é diminuido por ##25%## e a cura recebida é diminuida por ##0%##.",
	-- pls, ovk, dont change the skills values, thx
		})
end)