return {
    --[[
    -- CRÉDITOS --
    Extração das strings: gabsF
    Tradução: MrUmbrella (talvez o google tradutor fez o serviço pra ele)
    Revisão: gabsF
    ]]

    -- Nomes e descrições
    --"heist_deep_hl = "Crude Awakening",
    --"heist_deep = "Crude Awakening",
    heist_deep_briefing = "Este trabalho é perigoso, mas quando começamos alguma coisa, vamos até o fim. \nAssim que acessarmos o suprimento de petróleo, iremos redirecioná-lo de volta para nosso navio-tanque. Então, para explodir a plataforma, devemos causar um mau funcionamento da broca principal, mas precisaremos do cartão de acesso do Gabriel para acessar os controles de pressão. Este ex-mercenário sabe que fomos nós que roubamos seu irmão, então esteja pronto para eliminá-lo.\nÚltima coisa: vocês podem roubar o dinheiro escondido do Rainey ou deixá-lo queimar. É tudo a mesma coisa para Keegan. Agora, vamos sair em uma explosão de glória!",--This job's dangerous, but when we start something, we see it through to the blerrie end.$NL;Once we access the oil supply, we'll reroute it back to our tanker ship. Then to blow up the rig, we should cause a malfunction with the main drill, but we need Gabriel's keycard to access the pressure controls. This ex-merc knows we're the ones who ripped off his brother, so be ready to take him out.$NL;Last thing: You can steal Rainey's hidden cash, or let it burn. It's all the same to Keegan. Now, let's go out in a blaze of glory!",
    heist_deep_crimenet = "Alice Rainey assumiu o controle da principal plataforma de petróleo do SERA, para usar como alavanca contra a empresa e para esconder dinheiro dos federais. Se vocês conseguirem roubar um pouco de petróleo e depois destruir a plataforma, Rainey estará acabado. Não será fácil. O lugar é uma fortaleza, e o irmão do Esteban, Gabriel Santiago, está comandando o show. Mas se conseguirem, serão lendas do Texas!\n\n»Roubem o petróleo mais puro\n»Eliminem Gabriel Santiago\n»Destruam a plataforma de petróleo",--Alice Rainey took control of SERA's main oil rig, to use as leverage against the company, and to hide cash from the Feds. If you can steal some petroleum and then destroy the rig, Rainey will be finished. Won't be easy. The place is a fortress, and Esteban's brother Gabriel Santiago is running the show. But if you pull this off, you'll be Texas legends!\n\n»Steal the purest petroleum\n»Eliminate Gabriel Santiago\n»Destroy the oil rig",

    -- Legendas
    deep_intro_03_01 = "Todo esse rolê e caos, só pra queimar a Alice Rainey. Não acha isso um exagero?",--All this trouble and destruction, just to burn Alice Rainey. Doesn't feel excessive to you?",
	deep_intro_02_01 = "E tu tem certeza que o Gabriel sabe que foi a gente que invadiu o Rancho Midland?",--And you're sure Gabriel knows it was us that hit Midland Ranch?",
	deep_intro_01_03 = "Bom, Vernon, quando você vê quanto dinheiro que a gente sugou dessa porra, é que nem cheirar as rosas.",--Well Vernon, when you see how much money we make off the stuff, it's gonna smell like roses.",
	deep_intro_03_02 = "Eu faria isso dez vezes pior pra vê se a Rainey aprendesse, mas não é só ela. Destruindo esta plataforma de óleo, vai fazer a SERA ficar fora de cena por um bom tempo. Um belo dum buraco dum tamanho do petróleo Keegan na indústria.",--I'd do ten times worse to stick it to Rainey, but it's not just about her. Destroying this rig will take SERA outta the game for a long time. Gonna leave a nice, Keegan Oil-sized hole in the industry.",
	deep_intro_02_03 = "Beleza, toma cuidado com o quê deseja, maluco do caralho.",--Alright then. Careful what you blerrie wish for.",
	deep_intro_02_02 = "Claro que sim, porra. Ele descobriu qual rancho tava nas mãos do contato da Gemma, torturou o coitado até abrir o bico. Cê ouviu a mensagem da Rainey. Gabriel quer nada além de matar vocês.",--Sure as shit. He figured out which of the ranch hands was Gemma's insider, messed him up 'til he spilled the beans. You heard Rainey's voicemail. Gabriel wants nothing more than to take y'all on.",
	deep_intro_01_02 = "Pra ser honesto, não sou muito fã do cheiro do petróleo.",--To be honest, the smell of oil always made me nauseous.",
	deep_intro_03_03 = "Ah, entendi. Matando dois coelhos numa cajadada só.",--Ah, I see. Killing two birds with one stone. I like the way you think, Keegan.",
	deep_intro_01_01 = "Hmm, sente o cheiro disso? Petróleo da SERA top de linha. A cereja do bolo!",--Mmm, smell that? Top-shelf SERA petroleum. Cream of the crop!                ",
    gab_deep_05_01 = "Não há transferência programada para este intervalo de tempo. O que diabos está acontecendo?",--There's no transfer scheduled for this timeslot. What the hell's going on?
    gab_deep_05_02 = "Adição atrasada, Sr. Santiago. Deve estar no calendário atualizado.",--Late addition, Mr. Santiago. Should be on the updated calendar.
    gab_deep_05_03 = "Hmm... Tudo bem, eu vi isso. De volta ao trabalho.",--Hmm...Alright, I see it. Back to work.
    loc_deep_01_01 = "Está na hora, amigos. Naveguem até a doca de emergência abaixo da plataforma.",--It's time, friends. Sail to the emergency dock beneath the platform.
    loc_deep_01_02 = "Há uma doca de emergência na base da plataforma. Sigam nessa direção.",--There's an emergency dock at the base of the platform. Head that way.
    loc_deep_01_03 = "Nenhum guarda na doca de emergência da plataforma. É o local perfeito para entrarem.",--No guards on the rig's emergency dock. It's the perfect place to make port.
    loc_deep_02_01 = "Vocês podem ir até a plataforma com as tirolesas a partir daqui. Há seguranças particulares lá em cima, então fiquem alerta.",--You can zipline to the rig from here. There's a private security force topside, so stay alert.
    loc_deep_02_02 = "Usem suas tirolesas para chegarem à superfície. Cuidado com os seguranças.",--Use your ziplines to get topside. Watch out for the security team.
    loc_deep_02_03 = "Usem as tirolesas até a plataforma e não deixem que a equipe de segurança os peguem desprevenidos.",--Zipline up to the platform, and don't let the security team catch you off guard.
    loc_deep_03_01 = "Não percam a confiança em mim agora! Montem essas tirolesas.",--Don't get cold feet on me now! Set up those ziplines.
    loc_deep_03_02 = "Algo de errado? Você esqueceu como montar a tirolesa?",--What's wrong? You forget how to set up the zipline?
    loc_deep_03_03 = "Nada para nós fazermos aqui. Vão para cima.",--Nothing for us to do down here. Get topside.
    loc_deep_04_01 = "Antes de fazermos mais alguma coisa, preciso de acesso à rede central da plataforma. Encontrem a sala do servidor.",--Before we can do anything else, I need access to the rig's central network. Find the server room.
    loc_deep_04_02 = "A primeira coisa que precisamos fazer é encontrar a sala do servidor. Tenho que invadir a rede da SERA antes de prosseguirmos.",--First thing we need to do is find the server room. I have to crack SERA's network before we can move forward.
    loc_deep_04_03 = "Uma rede de segurança executa tudo nesta plataforma e está bem travada. Eu cuido disso se vocês me colocarem na sala do servidor.",--A security network runs everything on this rig, and it's locked tight. I'll handle it if you patch me into the server room.
    loc_deep_05_01 = "A segurança é apertada, amigos. Não iremos longe a menos que vocês me conectem ao servidor.",--Security's tight, friends. We won't get far unless you hook me into the server.
    loc_deep_05_02 = "Conectem-me aos servidores. É a única maneira de continuarem com a missão.",--Patch me in to the servers. It's the only way to move forward.
    loc_deep_05_03 = "Vão para a sala do servidor e me conectem.",--Get to that server room and hook me in.
    loc_deep_06_01 = "Se arrombar a porta parece muito arriscado, vocês podem encontrar o cartão de acesso com um dos funcionários. Vocês decidem.",--If forcing the door open feels too risky, you can find the keycard on one of the workers. Up to you.
    loc_deep_06_02 = "Adoro um bom exercício tanto quanto qualquer outro, mas isso chama atenção. Talvez devam procurar por um cartão de acesso.",--I love a good drill as much as the next guy, but it's a bit conspicuous. Maybe look for the keycard instead.
    loc_deep_06_03 = "Um funcionário provavelmente tem o cartão de acesso da sala do servidor. Vejam se vocês podem encontrá-lo. Caso contrário... Sabem o que fazer.",--A worker probably has the server room keycard. See if you can find it. And if you can't...You know the drill.
    loc_deep_07_01 = "Antes de fazermos mais alguma coisa, preciso de acesso à rede central da plataforma. Um dos funcionários do laboratório devem ter o cartão de acesso da sala do servidor.",--Before we can do anything else, I need access to the rig's central network. One of the lab workers should have the server room keycard.
    loc_deep_07_02 = "A primeira coisa que precisamos fazer é acessar a sala do servidor. Temos informações dizendo que um funcionário do laboratório tem o cartão de acesso.",--First thing we need to do is access the server room. We've got intel saying that a lab worker has the keycard.
    loc_deep_07_03 = "Precisamos quebrar a rede de segurança da plataforma. O cartão de acesso da sala do servidor deve estar com um dos funcionários do laboratório.",--We need to crack the rig's security network. The server room keycard should be on one of the lab workers.
    loc_deep_08_01 = "Antes de fazermos mais alguma coisa, preciso de acesso à rede central da plataforma. Um dos funcionários do escritório deve ter o cartão de acesso da sala do servidor.",--Before we can do anything else, I need access to the rig's central network. One of the office workers should have the server room keycard.
    loc_deep_08_02 = "A primeira coisa que precisamos fazer é acessar a sala do servidor. Temos informações dizendo que um funcionário de escritório tem o cartão de acesso.",--First thing we need to do is access the server room. We've got intel saying that an office worker has the keycard.
    loc_deep_08_03 = "Precisamos quebrar a rede de segurança da plataforma. O cartão de acesso da sala do servidor deve estar com um dos funcionários do escritório.",--We need to crack the rig's security network. The server room keycard should be on one of the office workers.
    loc_deep_09_01 = "Antes de fazermos mais alguma coisa, preciso de acesso à rede central da plataforma. Nosso informante diz que o cara com o cartão de acesso da sala do servidor está trabalhando perto do heliporto.",--Before we can do anything else, I need access to the rig's central network. Our intel says the guy with the server room keycard is working near the helipad.
    loc_deep_09_02 = "A primeira coisa que precisamos fazer é acessar a sala do servidor. Temos informações dizendo que um trabalhador perto do heliporto está com um cartão de acesso.",--First thing we need to do is access the server room. We've got intel saying that a worker near the helipad is in possession of the keycard.
    loc_deep_09_03 = "Precisamos quebrar a rede de segurança da plataforma. O cartão de acesso da sala do servidor deve estar com um trabalhador no heliporto.",--We need to crack the rig's security network. The server room keycard should be on a worker by the helipad.
    loc_deep_100_01 = "Este idiota quer uma luta? Então, bora lutar!",--This chop wants a fight? We'll give him a fight!
    loc_deep_100_02 = "Não acho que você consiga sair dessa com conversa.",--Don't think we can talk our way out of this one!
    loc_deep_100_03 = "É ele ou vocês, amigos! Matem ele!",--It's him or you, friends! Take him out!
    loc_deep_101A_01 = "O calor afetou sua armadura! Atirem agora!",--The heat messed with his armor! Shoot now!
    loc_deep_101A_02 = "O fogo enfraqueceu sua armadura! Exploda ele!",--The fire weakened his armor! Blast him!
    loc_deep_101A_03 = "Está funcionando! Atirem nele enquanto ele está pegando fogo!",--It's working! Shoot him while he's on fire!
    loc_deep_101_01 = "Eu já vi essa armadura. Muito resistente, exceto em calor extremo. Vocês podem derramar óleo nesses poços, atraia-o para baixo... Essa é sua chance de queimar o filho da puta.",--I've seen that armor. Blerrie tough, except in extreme heat. If you can spill oil into those pits, then lure him down...That's your chance to burn the fucker.
    loc_deep_101_02 = "Esperem! Essa armadura é um protótipo de Murkywater! Um defeito o torna mais fraco para balas quando exposto ao calor. Despeje um pouco de óleo naqueles poços, leve-o até lá e acenda-o!",--Wait! That armor's a Murkywater prototype! A defect makes it weaker to bullets when exposed to heat. Spill some oil into those pits, get him down there, then light him up!
    loc_deep_101_03 = "Ele tem um velho traje de combate Murky! Paramos de fabricá-los porque não podem bloquear fogo e balas ao mesmo tempo. Vocês devem derramar um pouco de óleo em um poço e aquecer as coisas!",--He's got himself an old Murky combat suit! We stopped making them because it can't block fire and bullets at the same time. You should leak some oil into a pit and heat things up!
    loc_deep_102_01 = "Esse fogo é o truque! Queimem ele novamente!",--Oh-ho! That fire did the trick! Light him up again!
    loc_deep_102_02 = "A estratégia de fogo funcionou! Enxaguem e repitem, amigos!",--The fire strategy worked! Rinse and repeat, friends!
    loc_deep_102_03 = "Façam isso novamente! Queimem e atirem nele! Queimear e atirar!",--Do it again! Burn him, shoot him! Burn! shoot!
    loc_deep_103_01 = "Ele não parece muito bem! Continuem!",--He's not looking too good! Keep it up!
    loc_deep_103_02 = "Ele está quase morto!",--He's almost finished!
    loc_deep_103_03 = "Você está quase pegando ele!",--You've nearly got him!
    loc_deep_104_01 = "Brinde do Gabriel! Agora, entre na sala de controle e desabilite a proteção contra explosão. É a nossa vez de quebrar uma furadeira!",--Gabriel's toast! Now, enter the control room and disable the blowout preventer. It's our turn to fuck up a drill!
    loc_deep_104_02 = "Não foi pessoal, Gabriel. Use seu cartão de acesso para acessar a sala de controle e, em seguida, desative a proteção contra explosão.",--Wasn't personal, Gabriel. Use his keycard to access the control room, then disable the blowout preventer.
    loc_deep_104_03 = "E é o fim dos Irmãos Santiago! Agora vão para a sala de controle e desative a proteção contra explosão.",--And that's the end of the Santiago Brothers! Now head to the control room and kill the blowout preventer.
    loc_deep_105_01 = "Vocês podem acessar a sala de controle com o cartão de acesso do Gabriel!",--You can access the control room with Gabriel's keycard!
    loc_deep_105_02 = "Vocês podem desativar a proteção contra explosão na sala de controle.",--You can disable the blowout preventer from the control room.
    loc_deep_105_03 = "Precisamos desabilitar a proteção contra explosão da furadeira.",--We need to disable the drill's blowout preventer.
    loc_deep_106_01 = "Precisamos colocar a quantidade certa de pressão, ou você não terá tempo de escapar. Eu direi as válvulas, e vocês giram elas!",--We need to build the right amount of pressure, or you won't have time to escape. I'll call out the valves, you turn them!
    loc_deep_106_02 = "A menos que você queira ser pego pela explosão, precisamos criar a quantidade certa de pressão aqui. Girem as válvulas conforme eu as digo.",--Unless you want to get caught in the blast, we need to build just the right amount of pressure here. Turn the valves as I call them out.
    loc_deep_106_03 = "Precisamos girar as válvulas de pressão em uma ordem específica, então ouça com atenção.",--We need to turn the pressure valves in a specific order, so listen carefully.
    loc_deep_107_01 = "Agh! Válvula errada! Do topo!",--Agh! Wrong valve! From the top!
    loc_deep_107_02 = "Não era aquele! Vamos começar novamente.",--Not that one! Let's start again.
    loc_deep_107_03 = "Não é tão difícil, idiota! De novo...",--It's not that hard, chops! Again...
    loc_deep_108_01 = "Depois de puxarem a alavanca, a contagem regressiva começa. Então esteja pronto para correr!",--Once you fire up that drill, the countdown begins. So be ready to run!
    loc_deep_108_02 = "As coisas vão ficar complicadas quando vocês puxarem a alavanca. Quanto mais cedo você voltar para o barco, melhor.",--Things are going to get dicey when you start the drill. Sooner you get back to the boat, the better.
    loc_deep_108_03 = "Puxem a alavanca e voltem pro barco o mais rápido que puderem.",--Start the drill, then get back to the boat as fast as you can.
    loc_deep_109_01 = "O equipamento está pronto para explodir. Só têm que puxarem a alavanca!",--The rig's set to blow. Just gotta start the drill!
    loc_deep_109_02 = "Tá na hora de irmos! Liguem a máquina!",--It's go time! Fire up the drill!
    loc_deep_109_03 = "Pelo amor de Deus! Liguem a broca!",--For crying out loud! Turn on the drill!
    loc_deep_10_01 = "Talvez o cara do cartão esteja no heliporto.",--Maybe our keycard guy's up at the helipad.
    loc_deep_10_02 = "Talvez um dos funcionários do laboratório tenha o cartão de acesso.",--Maybe one of the lab workers has the keycard.
    loc_deep_10_03 = "Talvez nosso cartão de acesso esteja no escritório administrativo.",--Maybe our keycard's in the Admin Office.
    loc_deep_110_01 = "Isso deve servir! De volta ao barco, seus idiotas!",--That'll do it! Back to the boat, you chops!
    loc_deep_110_02 = "Ela vai explodir! Saiam daí!",--She's gonna blow! Get out of there!
    loc_deep_110_03 = "Hora de irmos, amigos! Vão para o barco antes que ficam em pedacinhos!",--Time to go, friends! Get to the boat before this whole place goes up!
    loc_deep_111_01 = "Vocês querem morrer?! De volta pro barco!",--You got a blerrie death wish?! Back to the boat!
    loc_deep_111_02 = "Vocês estão ficando sem tempo! Saiam da plataforma!",--You're running out of time! Get off the platform!
    loc_deep_111_03 = "Voltem pro barco!",--Get back to the boat!
    loc_deep_112_01 = "Vão para o tanque! Não é longe!",--Get to the tanker! It's not far!
    loc_deep_112_02 = "Naveguem para fora da zona de explosão!",--Sail out of the blast zone!
    loc_deep_112_03 = "Quase em casa! Naveguem até o petroleiro!",--Almost home free! Sail to the tanker!
    loc_deep_113_01 = "Vocês ainda estão na zona de explosão! Vão para o tanque!",--You're still in the blast zone! Get to the tanker!
    loc_deep_113_02 = "A explosão parecerá muito mais legal fora da zona de explosão!",--The explosion will look a lot cooler outside the blast zone!
    loc_deep_113_03 = "Parem de enrolar! Saiam daí!",--Quit messing around! Get out of there!
    loc_deep_114_01 = "Boom! Destruição máxima! Eu não esperava nada menos. Subam a bordo, amigos. Amanhã é outro assalto!",--Boom! Maximum destruction! I expected nothing less. Hop aboard, friends. Tomorrow's another heist!
    loc_deep_114_02 = "Haha! Vocês fazem a destruição parecer uma puta de uma arte. E algo me diz que seu melhor trabalho está à sua frente. Vamos para casa.",--Haha! You make destruction look like a blerrie artform. And something tells me your best work is ahead of you. Let's head home.      
    loc_deep_114_03 = "Incrível! Aposto que vocês podem ver essa beleza do continente. Vamos dar o fora daqui, amigos. Temos lugares para estar. Coisas para roubar.",--Amazing! Bet you can see that beauty from the mainland. Let's clear out friends. We got places to be. Things to steal.               
    loc_deep_115_01 = "Vamos lá, seu queima-rosca! Parem de olhar para o fogo e entrem no navio!",--Come on, ya blerrie pyro! Quit staring at the fire and get on the ship!
    loc_deep_115_02 = "A guarda costeira provavelmente está a caminho. Vamos embora.",--Coast guard's probably on their way. Let's move out.
    loc_deep_115_03 = "Vamos nessa, gente.",--Let's ship out, gang.
    loc_deep_116_01 = "Oof. Parece que Gabriel levou muito a sério a morte do irmão. Eu me sentiria mal, mas... Esteban era um idiota, sabe?",--Oof. Looks like Gabriel took his brother's death pretty hard. I'd feel bad, but...Esteban was such a doos, you know?
    loc_deep_116_02 = "Um santuário? Realmente? Olha, eu entendo que Gabriel está de luto por seu irmão, mas isso aí... já é demais. E olha esse terno!",--A shrine? Really? Look, I get that Gabriel's mourning his brother, but this is...It's blerrie absurd.  And look at that suit!
    loc_deep_116_03 = "Por que diabos eles colocaram o memorial de Esteban na plataforma de petróleo? Isso é estranho, não é? Acho que o Gabriel se tornou o chefe.",--Why the hell did they put Esteban's memorial on the blerrie oil rig? That's weird, right? I think Gabriel's gone bossies.
    loc_deep_117_01 = "Este painel foi marcado naquele projeto que você roubou do escritório da SERA. Muito interessante.",--This panel was marked on that blueprint you snagged from the SERA office. Very interesting.
    loc_deep_117_02 = "Essas plantas da QG do SERA fizeram este painel parecer muito importante.",--Those blueprints from the SERA HQ made this panel seem pretty important.
    loc_deep_117_03 = "Essas plantas do escritório da SERA destacaram este painel, mas não o que ele faz. Misterioso demais, devo dizer.",--Those blueprints from the SERA office highlighted this panel, but not what it does. Blerrie mysterious if you ask me.
    loc_deep_11_01 = "Não podemos fazer muito até que vocês me coloquem na sala do servidor. Vão para o laboratório de testes e encontrem o idiota com o cartão de acesso!",--We can't do much until you hook me into the server room. Get to the testing lab and find the chop with the keycard!
    loc_deep_11_02 = "Preciso de acesso à sala do servidor. Alguém no laboratório de testes tem o cartão de acesso.",--I need access to the server room. Some chop in the testing lab has the keycard.
    loc_deep_11_03 = "o cara com o cartão de acesso da sala do servidor está no laboratório de testes.",--The guy with the server room keycard is in the testing lab.
    loc_deep_12_01 = "Não podemos fazer muito até que vocês me coloquem na sala do servidor. Vão para o escritório administrativo e encontrem o idiota com o cartão de acesso!",--We can't do much until you hook me into the server room. Get to the admin office and find the chop with the keycard!
    loc_deep_12_02 = "Preciso de acesso à sala do servidor. Algum idiota no escritório de administração tem o cartão de acesso.",--I need access to the server room. Some chop in the admin office has the keycard.
    loc_deep_12_03 = "O cara com o cartão de acesso da sala do servidor está no escritório administrativo.",--The guy with the server room keycard is in the admin office.
    loc_deep_13_01 = "Não podemos fazer muito até que vocês me coloquem na sala do servidor. Vão para o heliporto e encontre o idiota com o cartão de acesso!",--We can't do much until you hook me into the server room. Get to the helipad and find the chop with the keycard!
    loc_deep_13_02 = "Preciso de acesso à sala do servidor. Algum idiota perto do heliporto tem o cartão de acesso.",--I need access to the server room. Some chop near the helipad has the keycard.
    loc_deep_13_03 = "O cara com o cartão de acesso da sala do servidor está no heliporto.",--The guy with the server room keycard is out by the helipad.
    loc_deep_14_01 = "Se alterarmos o cronograma de transferência da plataforma, podemos pegar todo o petróleo que quisermos sem levantar suspeitas. A rede está desbloqueada, mas precisamos de um pen-drive para acessar os computadores. Deve estar trancado em um armário em algum lugar.",--If we alter the rig's transfer schedule, we can take all the oil we want without raising suspicion. The network's unlocked, but we need a USB drive to access the computers. Should be locked up in a cabinet somewhere.
    loc_deep_14_02 = "Agora que a rede está desbloqueada, podemos adicionar nossa transferência de óleo de última hora ao cronograma de remessa. Os computadores administrativos precisam de um pen-drive para funcionarem. Encontrem o armário onde eles estão guardando.",--Now that the network's unlocked, we can add our last-minute oil transfer to the shipping schedule. The admin computers need a USB key to work. Find the cabinet where they're storing it.
    loc_deep_14_03 = "Podemos editar a programação de envio da plataforma agora. É assim que faremos a transferência de óleo parecer rotineira. Vocês só precisam de um pen-drive para desbloquear os computadores administrativos. Aposto que eles guardam em um armário ou algo assim.",--We can edit the rig's shipping schedule now. That's how we'll make the oil transfer look routine. You just need a USB drive to unlock the admin computers. Bet they keep it in a cabinet or something.
    loc_deep_15_01 = "Eles provavelmente guardaram o pen-drive, então já preparem pra destrancar à mão.",--They probably got this USB locked up, so keep your lockpick handy.
    loc_deep_15_02 = "Se vocês encontrarem algum armário trancado, meu dinheiro me disse que o pen-drive está lá.",--If you find any locked cabinets, my money says the USB is in there.
    loc_deep_15_03 = "Se eu fosse um pen-drive, onde me esconderia? Talvez em um armário? Parece aconchegante.",--If I were a USB, where would I hide? Maybe in a cabinet? Sounds cozy.
    loc_deep_16_01 = "Bom, vocês encontraram o pen-drive. Vão para o escritório administrativo e adicionarei nosso navio ao cronograma de transferência.",--Good, you found the drive. Get to the admin office, and I'll add our ship to the transfer schedule.
    loc_deep_16_02 = "Agora, conectem-me a um dos computadores administrativos e farei nossa transferência de óleo parecer normal.",--Now, connect me to one of  the admin computers, and I'll make our oil transfer look like business as usual.
    loc_deep_16_03 = "Bem feito! Agora temos acesso ao cronograma de envio. Podemos alterá-lo no escritório administrativo.",--Nicely done! Now we have access to the shipping schedule. We can alter it from the admin office.
    loc_deep_17_01 = "O escritório administrativo fica no andar inferior, perto das passarelas. Desça lá.",--The admin office is on the lower deck, near the catwalks. Get down there.
    loc_deep_17_02 = "Vocês se perderam? Parece que o escritório administrativo fica no andar inferior.",--You lost? It looks like the admin office is on the lower deck.
    loc_deep_17_03 = "Escritório administrativo, amigos. Convés inferior. Vão logo.",--Administrative Office, friends. Lower deck. Get a move on.
    loc_deep_18_01 = "Estou atualizando a programação agora. Aguentem aí.",--I'm updating the schedule now. Hang tight.
    loc_deep_18_02 = "Acessamos a programação. Fiquem escondidos enquanto faço minha mágica.",--We've accessed the schedule. Keep hidden while I work my magic.
    loc_deep_18_03 = "Alteração do cronograma. Espere.",--Altering the schedule. Stand by.
    loc_deep_19_01 = "Aqui é onde as coisas ficam complicadas. A plataforma tem alguns lotes de óleo, mas queremos apenas o mais puro. Vocês podem pegar uma amostra de cada estoque na Sala de Extração. Peguem um agora.",--Here's where things get tricky. The rig has a few batches of oil, but we only want the purest one. You can take a sample of each stock in the Extraction Room. Go grab one now.
    loc_deep_19_02 = "Eu sei que tudo parece uma gosma preta fedorenta, mas alguns dos lotes de óleo aqui são mais puros do que outros. Queremos o mais puro que eles têm. Vocês podem testar cada lote coletando amostras da Sala de Extração.",--I know it all looks like stinky black goop, but some of the oil batches here are purer than others. We want the purest they have. You can test each batch by taking samples from the Extraction Room.
    loc_deep_19_03 = "Se vocês irem à Sala de Extração, poderão coletar amostras de cada lote de petróleo para testar a pureza. Quanto melhor o petróleo, mais dinheiro ganhamos com Keegan.",--If you head to the Extraction Room, you can take samples from each batch of petroleum to test for purity. The better the oil, the more money we make with Keegan.
    loc_deep_20_01 = "Peguem uma amostra de óleo de um dos canos na Sala de Extração.",--Grab an oil sample from one of the pipes in the Extraction Room.
    loc_deep_20_02 = "Vão para a Sala de Extração e peguem uma amostra de óleo.",--Get to the Extraction Room and grab an oil sample.
    loc_deep_20_03 = "A Sala de Extração é o melhor local para coletarem amostras de óleo.",--The Extraction Room is the best place to collect oil samples.
    loc_deep_21_01 = "Agora, passe essa amostra por uma máquina de teste no laboratório. Isso vai mostrar o quão puro esse lote está.",--Now, run that sample through a testing machine down in the laboratory. It'll tell us if this batch is pure.
    loc_deep_21_02 = "Há uma máquina no laboratório para analisar as amostras de óleo. Apenas o que precisamos.",--There's a machine in the laboratory for analyzing oil samples. Just what we need.
    loc_deep_21_03 = "Levem essa amostra para o laboratório. Há uma máquina que detecta a pureza do óleo.",--Take that sample to the laboratory. There's a machine that can detect the oil's purity.
    loc_deep_22_01 = "Há uma máquina no laboratório para testar a pureza do óleo. Use-o na amostra que vocês acabaram de tirar.",--There's a machine in the lab for testing oil purity. Use it on the sample you just took.
    loc_deep_22_02 = "Passem esse lote pelo negócio que analisa a... pureza do óleo. Sei lá a porra do nome desse troço.",--Run that oil sample through the purity...analyzer...o'tron. Whatever it's blerrie called.
    loc_deep_22_03 = "Levem essa amostra para o laboratório.",--Take that sample down to the lab.
    loc_deep_23_01 = "Cacete! Essa amostra não é pura o suficiente. Tentem outro lote.",--Kak! That sample isn't pure enough. Try another batch.
    loc_deep_23_02 = "Parece que este lote não está certo. Testem outra amostra.",--Looks like this batch isn't quite right. Test another sample.
    loc_deep_23_03 = "Precisamos encontrar uma amostra melhor. Peguem outro na Sala de Extração.",--We need to find a better sample. Grab another from the Extraction Room.
    loc_deep_24A_01 = "Uau! Este deve ser o lote mais puro que eles têm.",--Whoa! This must be the purest batch they have.
    loc_deep_24A_02 = "Vocês encontraram as coisas boas! Esta amostra é perfeita.",--You found the good stuff! This sample is perfect.
    loc_deep_24A_03 = "Sim! Este lote vale uma fortuna!",--Yes! This batch is worth a kakspul!
    loc_deep_24_01 = "Porra! Esse é o óleo que Keegan quer.",--Kiff! That's the oil Keegan wants.
    loc_deep_24_02 = "Agora que é um bom petróleo!",--Now that's some good petroleum!
    loc_deep_24_03 = "Este óleo vai servir bem!",--This oil will work fine!
    loc_deep_25_01 = "Sabemos de qual suprimento de petróleo retirar agora. Encontrem a mangueira de transferência e abaixem-a para o nosso navio-tanque.",--We know which oil supply to pull from now. Find the transfer hose and lower it down for our tanker ship.
    loc_deep_25_02 = "Estamos prontos para roubar um pouco de petróleo. Abaixem a mangueira de transferência da plataforma para o nosso navio-tanque.",--We're ready to steal some oil. Lower the rig's transfer hose for our tanker ship.
    loc_deep_25_03 = "Encontrem a mangueira de transferência da plataforma. Vocês precisão abaixá-lo para que nosso petroleiro possa sugar o óleo.",--Find the rig's transfer hose. You need to lower it down so our tanker can siphon the oil.
    loc_deep_26A_01 = "Usem esse guindaste para abaixar a mangueira de transferência.",--Use that crane to lower the transfer hose.
    loc_deep_26A_02 = "Está vendo aquele guindaste? Vocês podem usar isso para soltar a mangueira de transferência.",--See that crane? You can use it to drop the transfer hose.
    loc_deep_26A_03 = "Abram a mangueira de transferência ativando o guindaste.",--Deploy the transfer hose by activating that crane.
    loc_deep_26_01 = "A mangueira de transferência deve estar na Área de Processamento, com todos os tanques de óleo.",--The transfer hose should be in the Processing Area, with all the oil tanks.
    loc_deep_26_02 = "Encontrem a área de processamento e vocês encontrarão a mangueira de transferência.",--Find the Processing Area, and you'll find the transfer hose.
    loc_deep_26_03 = "Levem a mangueira de transferência para o nosso navio. Vocês encontrarão na área de processamento.",--Get the transfer hose down to our ship. You'll find it in the Processing Area.
    loc_deep_27_01 = "Vejam aqueles tanques coloridos? Precisamos conectar esses tubos ao que corresponde à nossa amostra de óleo. Preparem e puxem a alavanca no tanque. Colocarei nosso navio em posição.",--See those colored tanks? We need to connect these pipes to the one matching our oil sample. Set it up, then pull the lever on the tank. I'll get our ship into position.
    loc_deep_27_02 = "Estão vendo todos aqueles canos? Vocês precisam conectar aquilo ao tanque que corresponde à nossa amostra de óleo. Quando tudo estiver pronto, puxem a alavanca no tanque apropriado.",--See all those pipes? You need to link them up to the tank that matches our oil sample. When everything's set, pull the lever on the proper tank.
    loc_deep_27_03 = "Um desses tanques de óleo deve corresponder à nossa amostra. Alinhem os canos, ativem a bomba e o nosso navio fará o resto.",--One of those oil tanks should match our sample. Line up the pipes, activate the pump, and our ship will take care of the rest.
    loc_deep_28A_01 = "Bom! Agora, liguem o gerador da bomba.",--Good! Now, fire up the pump generator.
    loc_deep_28A_02 = "O tanque está aberto. Ativem o gerador da bomba.",--The tank's open. Activate the pump generator.
    loc_deep_28A_03 = "Tudo está pronto. Liguem o gerador da bomba.",--Everything's set. Turn on the pump generator.
    loc_deep_28_01 = "Vocês precisam conectar os tubos do gerador ao estoque de óleo correto. Puxem a alavanca no tanque quando estiver pronto.",--You need to link the pipes from the generator to the right oil stock. Pull the lever on the tank when you're set.
    loc_deep_28_02 = "Precisamos conectar o gerador da bomba ao lote de óleo correto. Quando os tubos estiverem ajustados, puxem a alavanca no tanque.",--We need to link the pump generator to the right oil batch. When the pipes are set, pull the lever on the tank.
    loc_deep_28_03 = "Quando esses tubos estiverem conectados ao nosso tanque de escolha, puxem a alavanca e ativem o gerador da bomba.",--When these pipes are connected to our tank of choice, pull the lever and activate the pump generator.
    loc_deep_29_01 = "O óleo não está passando. Os tubos estão alinhados corretamente?",--The oil isn't getting through. Are the pipes lined up correctly?
    loc_deep_29_02 = "Tem algo de errado. Podem checar os canos?",--Something's wrong. Double check those pipes.
    loc_deep_29_03 = "Não está funcionando. Deem outra olhada nos canos.",--It's not working. Take another look at the pipes.
    loc_deep_30_01 = "Boa! Fiquem escondidos enquanto nosso navio extrai o óleo.",--Nice going! Stay out of sight while our ship siphons the oil.
    loc_deep_30_02 = "O óleo está passando! Fiquem escondidos enquanto nosso navio faz seu trabalho.",--The oil's coming through! Keep hidden while our ship does its thing.
    loc_deep_30_03 = "Você conseguiram! Sifonando o óleo enquanto falamos. Fiquem escondidos.",--You got it! Siphoning the oil as we speak. Stay out of sight.
    loc_deep_31_01 = "Alguém está checando. Atendam o telefone, ou eles vão ficar desconfiados.",--Someone's checking in. Answer the phone, or they'll get suspicious.
    loc_deep_31_02 = "Maldito telefone! Se não queremos ninguém fazendo check-in, devemos atender.",--Blerrie phone! If we don't want anyone checking in, we should answer it.
    loc_deep_31_03 = "Eles estão atrás de nós. Peguem o telefone para que eu possa respondê-los.",--They're onto us. Pick up the phone so I can put them at ease.
    loc_deep_32_01 = "Se vocês não atenderem o telefone, eles mandarão um guarda para cá!",--If you don't pick up the phone, they'll send a guard this way!
    loc_deep_32_02 = "Atendam o telefone, ou um guarda pode vir bisbilhotar!",--Answer that phone, or a guard might come poking around!
    loc_deep_32_03 = "Eles saberão que algo está errado se vocês não atenderem o telefone!",--They'll know something's wrong if you don't answer the phone!
    loc_deep_33_01 = "Um maldito firewall pegou meu hack de servidor! Encontrem um computador para desativar isso.",--A blerrie firewall caught my server hack! Find a computer to disable it.
    loc_deep_33_02 = "Meu hack de servidor acionou um firewall. Usem um computador para contornar a segurança.",--My server hack triggered a firewall. Use a computer to bypass it.
    loc_deep_33_03 = "O firewall do sistema foi acionado. Vão até um computador e desligue-o.",--The system's firewall caught up with us. Get to a computer, shut it down.
    loc_deep_34_01 = "Desliguem o firewall, ou o óleo não vai a lugar nenhum!",--Disable the firewall, or the oil's not going anywhere!
    loc_deep_34_02 = "A transferência de óleo não pode continuar enquanto o firewall estiver ativo.",--The oil transfer can't continue while the firewall's active.
    loc_deep_34_03 = "A transferência de óleo está travada. Desliguem esse firewall.",--The oil transfer is frozen. Shut down that firewall.
    loc_deep_35_01 = "Roubar o óleo: confere! Hora de ir para a Torre de Perfuração. Vão com calma, amigos. Esse é o território de Gabriel.",--Steal the oil: check! Time to head for the Drilling Tower. Tread lightly, friends. That's Gabriel's territory.
    loc_deep_35_02 = "Nós sugamos o melhor. Hora de queimar o resto. Dirija-se à Torre de Perfuração.",--We siphoned the best. Time to burn the rest. Head to the Drilling Tower.
    loc_deep_35_03 = "Excelente trabalho! Hora da fase 2. Vão para a Torre de Perfuração e evitem de serem vistos. Gabriel está de olho.",--Excellent work! Time for Phase 2. Get to the Drilling Tower, and be extra sneaky about it. Gabriel's watching.
    loc_deep_36_01 = "Vão logo. Esta plataforma de petróleo não vai explodir em pedacinhos!",--Get a move on. This oil rig's not going to blow itself to smithereens!
    loc_deep_36_02 = "Precisamos chegar à Torre de Perfuração se quisermos explodir esta plataforma de petróleo.",--We need to get to the Drilling Tower if we want to blow up this oil rig.
    loc_deep_36_03 = "Não demorem, idiotas. Vão para a Torre de Perfuração.",--Don't dawdle, you chops. Get to the Drilling Tower.
    loc_deep_37_01 = "Nosso plano para obter o cartão de acesso do Gabriel é bastante desagradável, mas, novamente, ele é um babaca. Para começar, desliguem os lasers de segurança fora de seu centro de comando.",--Our plan to get Gabriel's keycard is pretty nasty, but then again, he's a nasty guy. To start, turn off the security lasers outside his command center.
    loc_deep_37_02 = "Precisamos do cartão de acesso do Gabriel. Tentem pedir educadamente, se quiserem, mas prefiro apenas levá-lo para fora. Para fazerem isso, desliguem os lasers fora de seu centro de comando.",--We need Gabriel's keycard. Try asking nicely if you want, but I'd sooner just take him out. To do that, shut down the lasers outside his command center.
    loc_deep_37_03 = "Para obter o cartão de acesso do Gabriel, precisamos transformar seu centro de comando em uma armadilha mortal. Desliguem os lasers de segurança e partiremos daí.",--To get Gabriel's keycard, we need to turn his command center into a death trap. Power down the security lasers, then we'll go from there.
    loc_deep_38A_01 = "Em seguida, vocês precisam bloquear a ventilação do centro de comando. Um homem interno do Keegan escondeu algumas ferramentas para ajudar a fazer o trabalho.",--Next, you need to jam the command center's ventilation. Keegan's inside man stashed some tools to help get the job done.
    loc_deep_38A_02 = "O informante do Keegan deixou algum equipamento para te ajudarem a travar o fluxo de ar do centro de comando. Deve ser fácil de encontrar.",--Keegan's insider left some gear to help you cut the command center's airflow. Should be easy enough to find.
    loc_deep_38A_03 = "Keegan subornou um dos funcionários. Ele deixou uma ferramenta para nos ajudar a bloquear o ventilador do quarto do Gabriel. Encontrem aí.",--One of the workers here is on Keegan's payroll. He left a tool to help us jam the ventilation fan to Gabriel's room. Find it now.
    loc_deep_38B_01 = "A ferramenta para travar aquele ventilador está por aqui em algum lugar.",--The tool for jamming that fan is around here somewhere.
    loc_deep_38B_02 = "Um ventilador próximo controla o fluxo de ar para o quarto do Gabriel. Vocês podem travar aquilo com alguma coisa?",--A nearby fan controls the airflow to Gabriel's room. Can you jam it with something?
    loc_deep_38B_03 = "Nosso informante disse que a ferramenta de que precisamos está escondida em algum lugar da Torre de Perfuração.",--Our man says the tool we need is stashed somewhere in the Drilling Tower.
    loc_deep_38_01 = "Esses lasers estão conectados a uma fonte de energia. Encontrem e desliguem.",--Those lasers are connected to a power source. Find it and shut it down.
    loc_deep_38_02 = "Não podemos chegar ao Gabriel até cortarem a energia dos lasers de segurança.",--We can't get to Gabriel until you cut the power to his security lasers.
    loc_deep_38_03 = "Cortem a energia desses lasers de segurança.",--Cut the power to those security lasers.
    loc_deep_39_01 = "Eles mantêm amostras das emissões de gás natural da plataforma para teste. Nosso informante conseguiu uma lata para nós. Conectem isso ao sistema de ventilação do Gabriel.",--They keep samples of the rig's natural gas emissions for testing. Our man snagged us a canister. Hook it up to Gabriel's vent system.
    loc_deep_39_02 = "Nosso informante pegou um tanque com as emissões tóxicas da plataforma de petróleo. Se ligarem isso à conduta de ventilação do Gabriel, podemos enviar o gás pro imbecil.",--Our insider grabbed us a tank of the oil rig's toxic emissions. If you hook it up to Gabriel's ventilation duct, we can gas the chop.
    loc_deep_39_03 = "Tiram amostras das emissões de gás da plataforma e são tóxicas. Botem a lata que o nosso homem nos deixou à saída de ar do Gabriel.",--They take samples of the rig's gas emissions, and they're blerrie toxic. Connect the canister our man left us to Gabriel's air vent.
    loc_deep_40_01 = "Tudo bem. Botem essa garrafa em um filtro de ventilação, abrem e acabem com esse idiota.",--Alrighty. Hook that canister to a ventilation filter, open it up, and gas the chop.
    loc_deep_40_02 = "Vamos levar esse gás venenoso para seu novo lar. Conectem o recipiente a um dos dutos de ventilação do Gabriel.",--Let's get this poisonous gas to its new home. Connect the canister to one of Gabriel's ventilation ducts.
    loc_deep_40_03 = "Hora de tirarem o fôlego do Gabriel. Prendam sua garrafa ao sistema de ventilação da sala de comando.",--Time to take Gabriel's breath away. Hook your canister to the command room's vent system.
    loc_deep_41_01 = "Ufa! Isso deve servir. Arranquem o cartão de acesso das mãos frias e mortas do Gabriel. Mas não esquecem de desligar o gás primeiro!",--Oof! That outta do it. Pry the keycard from Gabriel's cold, dead hands. But make sure to turn off the gas first!
    loc_deep_41_02 = "Tudo bem, Gabriel morreu. Desliguem o gás e vão buscar o cartão de acesso dele. Nessa ordem.",--Alright, Gabriel's down. Turn off the gas, then go collect his keycard. In that order.
    loc_deep_41_03 = "E é o fim dos Irmãos Santiago. Agora desliguem o gás e vão pegar o cartão de acesso.",--And that's the end of the Santiago Brothers. Now turn off the gas and go claim that keycard.
    loc_deep_42_01 = "OK. Vão para a sala de controle e quebrem o protetor de explosão da furadeira. Heh, quebrem a furadeira... Isso é um pouco irônico, hein?",--Okay. Get to the control room and disable the drill's blowout preventer. Heh, disable the drill...Shoe's on the other foot now, eh?
    loc_deep_42_02 = "Em uma maldita reviravolta irônica, agora temos que sabotar uma furadeira. Há um protetor de explosão instalado na sala de controle. Desativem isso.",--In a blerrie ironic turn of events, we now have to sabotage a drill. There's a blowout preventer set up in the control room. Disable it.
    loc_deep_42_03 = "Queremos causar uma explosão na broca principal, mas a sonda tem uma proteção contra isso. Vocês podem desativar isso na sala de controle.",--We want to cause a blowout in the main drill, but the rig has a safeguard against that very thing. You can disable it from the control room.
    loc_deep_43_01 = "Encontrem a sala de controle! Não podemos sobrecarregar a pressão enquanto a proteção estiver ativa.",--Find the control room! We can't overload the pressure while the preventer's active.
    loc_deep_43_02 = "Vocês podem desligar o protetor anti-explosões na sala de controle.",--You can turn off the blowout preventer in the control room.
    loc_deep_43_03 = "Nada explode até que vocês desliguem o protetor de explosão.",--Nothing explodes until you shut off the blowout preventer.
    loc_deep_44_01 = "Precisamos juntar a quantidade certa de pressão. O suficiente para explodir a broca, mas não muito, ou vocês não terão tempo de escapar.",--We need to build just the right amount of pressure. Enough to blow up the drill, but not too much, or you won't have time to escape.
    loc_deep_44_02 = "Se conseguirmos encontrar o ponto ideal para aumentar a pressão, vocês terão tempo suficiente para escaparem antes que os fogos de artifício comecem.",--If we can find the sweet spot in building up pressure, you'll have just enough time to clear out before the fireworks start.
    loc_deep_44_03 = "Este é um processo delicado. Pouca pressão e nada explode. Muita pressão e tudo explode muito rápido. Tem que estar no ponto certo.",--This is a delicate process. Too little pressure, and nothing explodes. Too much pressure, and everything explodes too fast. Has to be just right.
    loc_deep_45_01 = "Existem quatro válvulas no topo e quatro abaixo. Vou avisar aqueles que vocês precisam ativar. Se vocês estragarem tudo, teremos que começar de novo.",--There are four valves up top, and four below. I'll call the ones you need to turn. If you screw up, we have to start over.
    loc_deep_45_02 = "Existem oito válvulas ao redor da Torre de Perfuração. Virem apenas os que eu avisar, ou precisaremos começar de novo.",--There are eight valves around the Drilling Tower. Only turn the ones I call out, or we'll need to start again.
    loc_deep_45_03 = "Eu vou te dizer quais válvulas girar. Não estraguem tudo.",--I'll tell you which valves to turn. Don't mess it up.
    loc_deep_46_01 = "Girem H1!",--Turn H1!
    loc_deep_47_01 = "H2!",--H2!
    loc_deep_48_01 = "Achem H3!",--Find H3!
    loc_deep_49_01 = "Rodem H4!",--Spin H4!
    loc_deep_50_01 = "Usem L1!",--Do L1!
    loc_deep_51_01 = "Fechem L2!",--Close L2!
    loc_deep_52_01 = "Rodem L3!",--Rotate L3!
    loc_deep_53_01 = "Vão ao L4!",--Get to L4!
    loc_deep_54_01 = "Prestem atenção! Válvula H1!",--Pay attention! Valve H1 !
    loc_deep_55_01 = "Está ouvindo? H2!",--You listening? H2!
    loc_deep_56_01 = "Novamente: Achem H3!",--Again: Find H3!
    loc_deep_57_01 = "H4! Vão logo!",--H4! On the double!
    loc_deep_58_01 = "Bora, seu idiota! L1!",--Pick it up, you chops! L1!
    loc_deep_59_01 = "Repetindo: Válvula L2",--I repeat: Valve L2!
    loc_deep_60_01 = "O que você está esperando? L3!",--What's the hold up? L3!
    loc_deep_61_01 = "Vocês precisam achar a Válvula L4!",--You got to find Valve L4!
    loc_deep_62_01 = "Eca! Válvula errada, idiota. Vamos começar novamente.",--Ugh! Wrong valve, chops. Let's start again.
    loc_deep_62_02 = "Não aquele! Do começo, tá bom?",--Not that one! From the top, alright?
    loc_deep_62_03 = "Você está ouvindo mesmo? Temos que recomeçar agora.",--Are you even listening? We have to start over now.
    loc_deep_63_01 = "Agora, para o gran finale! Ligue a furadeira e volte para o barco.",--Now, for the grand finale! Start up the drill, then get the hell back to the boat.
    loc_deep_63_02 = "Terminamos. Assim que vocês ativarem a broca, voltem para o barco o mais rápido que puder.",--This is it. Soon as you active the drill, return to the boat as fast as you can.
    loc_deep_63_03 = "Tudo pronto. Acenda o fusível ligando a furadeira e deem o fora daí.",--All set. Light the fuse by turning on the drill, then get the hell out of there.
    loc_deep_64_01 = "Vamos, liguem a broca! O suspense está me matando!",--Come on, start the drill! The suspense is killing me!
    loc_deep_64_02 = "Não chegamos tão longe para recuarem agora. Liguem a furadeira!",--We didn't come this far to back out now. Turn on the drill!
    loc_deep_64_03 = "Por que a demora? Ativem a furadeira!",--What's the hold up? Activate the drill!
    loc_deep_65_01 = "Ela vai explodir! Para o barco, amigos!",--She's gonna blow! To the boat, friends!
    loc_deep_65_02 = "Essa é a nossa deixa! Voltem para o barco!",--That's our cue! Get back to the boat!
    loc_deep_65_03 = "Está acontecendo! Saia da plataforma!",--It's happening! Get off the rig!
    loc_deep_66_01 = "Vão! Barco! Agora!",--Go! Boat! Now!
    loc_deep_66_02 = "Vocês têm que se mover mais rápido do que isso!",--You got to move faster than that!
    loc_deep_66_03 = "Corram pela sua vida de merda!",--Run for your blerrie life!
    loc_deep_67_01 = "Ainda não está fora de perigo! Naveguem para o petroleiro!",--Not out of the woods yet! Set sail for the tanker!
    loc_deep_67_02 = "Quase em casa! Corram de volta para o petroleiro!",--Almost home free! Hurry back to the tanker!
    loc_deep_67_03 = "Naveguem para fora da zona de explosão!",--Sail out of the blast zone!
    loc_deep_68_01 = "Não parem agora! Você está tão perto!",--Don't stop now! You're so close!
    loc_deep_68_02 = "O que você está fazendo?! Saiam daí!",--What're you doing?! Get out of there!
    loc_deep_68_03 = "De volta ao petroleiro, seus malucos!",--Back to the tanker, you crazy chops!
    loc_deep_69_01 = "Melhores fogos de artifício que já vi! Não sei como vamos superar isso, mas sempre achamos um jeito. Sempre. Vamos para casa.",--Best fireworks I ever saw!  Don't know how we're gonna top this, but we will. We always do. Let's head home.                          
    loc_deep_69_02 = "Lindo! Este pode ser apenas o nosso melhor trabalho. Heh, melhor trabalho até agora, pelo menos. Feito com maestria, amigos. Hora de irmos.",--Beautiful! This might just be our best work. Heh, best work so far, at least. Masterfully done, friends. Time to go.                  
    loc_deep_69_03 = "E é assim que se faz! Ninguém explode como a gangue Payday. Bom trabalho, amigos. Sobem a bordo.",--And THAT is how it's done! No one blows shit up like the Payday Gang. Good job, friends. Climb aboard.
    loc_deep_70_01 = "Em vez de ficarem enrolando, por que não destruir a sala de segurança enquanto o óleo está drenando? Deve estar por perto.",--Instead of twiddling your thumbs, why not take out the security room while the oil's draining? Should be nearby.
    loc_deep_70_02 = "Acho que a sala de segurança está em algum lugar aí. Podem desligar as câmeras se quiserem. Temos tempo para matar.",--I think the security room's somewhere nearby. Could take it down if you want. We've got time to kill.
    loc_deep_70_03 = "Se vocês gostam de multitarefa, agora seria um bom momento para desligarem a sala de segurança.",--If you're up for some multitasking, now would be a good time to take out the security room.
    loc_deep_71_01 = "As câmeras estão desligadas. Deve facilitar nossa vida.",--Cameras are down. Should make our lives easier.
    loc_deep_71_02 = "Legal! As câmeras não será mais um problema.",--Nice! Camera won't be a problem anymore.
    loc_deep_71_03 = "Chega de câmeras! Graças a Deus por isso.",--No more cameras! Thank god for that.
    loc_deep_72_01 = "Estamos no meio do oceano, então não tem ninguém para pegar essas malas. Vocês mesmos terão que pegar as bolsas na saída.",--We're in the middle of the ocean, so there's no one to pick up those bags. You'll have to snag them yourself on the way out.
    loc_deep_72_02 = "Navegamos longe demais para trazer nossa equipe de extração. Vocês terão que pegar aquelas bolsas valiosas na saída. Não se esqueçam.",--We sailed out too far to bring our extraction team. You'll have to get those loot bags on the way out. Don't forget.
    loc_deep_72_03 = "Assim que saírem, não esquecem de levar as bolsas com os espólios. Nós estamos longe demais pra chamar a nossa equipe de fuga.",--On your way out, make sure to scoop up those loot bags. We're too far from the mainland to call our extraction team.
    loc_deep_73_01 = "Lembrem de pegar as bolsas com o dinheiro!",--Remember to grab those loot bags!
    loc_deep_73_02 = "Não esqueçam das bolsas com o dinheiro!",--Don't forget those loot bags!
    loc_deep_73_03 = "Peguem as bolsas com o dinheiro antes da gente ir.",--Get the loot bags before we leave.
    loc_deep_74_01 = "Cacete! Eles estão atrás de nós!",--Kak! They're onto us!
    loc_deep_74_02 = "Espero que vocês tenham trazido as grandes armas!",--Hope you brought the big guns!
    loc_deep_74_03 = "Tudo certo, idiotas! Alto e orgulhoso!",--Alright, chops! Loud and proud!
    loc_deep_75_01 = "Naveguem até a doca de emergência sob a plataforma!",--Sail to the emergency dock under the platform!
    loc_deep_75_02 = "Podemos acessar a plataforma pela doca de emergência!",--We can access the rig from the emergency dock!
    loc_deep_75_03 = "Vão para a doca de emergência sob a plataforma!",--Get to the emergency dock under the platform!
    loc_deep_76_01 = "Montem as suas tirolesas e vão para a superfície!",--Set up your ziplines and get topside!
    loc_deep_76_02 = "Usem a tirolesa até a plataforma!",--Zipline up to the platform!
    loc_deep_76_03 = "Hora da tirolesa, amigos! Vamos para cima!",--Zipline time, friends! Up we go!
    loc_deep_77_01 = "Não dá para fazer muito daqui!",--Can't do much from down here!
    loc_deep_77_02 = "Vamos! Usem a tirolesa!",--Come on! Get ziplining!
    loc_deep_77_03 = "Vocês precisam chegar ao topo!",--You need to get topside!
    loc_deep_78A_01 = "Precisamos acabar com a rede de segurança deles. Encontrem a sala do servidor.",--We need to take out their security network. Find the server room.
    loc_deep_78A_02 = "Começaremos pelo início. Vão para a sala do servidor.",--First thing's first. Get to the server room.
    loc_deep_78A_03 = "Antes de prepararmos a transferência de óleo, precisamos encontrar a sala do servidor.",--Before we set up the oil transfer, we need to find the server room.
    loc_deep_78B_01 = "A sala do servidor deve estar acima das passarelas!",--The server room should be above the catwalks!
    loc_deep_78B_02 = "Encontrem a sala do servidor!",--Find that server room!
    loc_deep_78B_03 = "Vocês encontrarão a sala do servidor no nível intermediário da plataforma!",--You'll find the server room up on the rig's mid-level!
    loc_deep_78_01 = "Rainey transformou este equipamento em uma fortaleza? Então vamos invadir como se fosse um! Vão até lá e limpem este lugar do mapa!",--Rainey turned this rig into a fortress? Then we'll attack it like one! Get down there and wipe this place off the map!
    loc_deep_78_02 = 'Isto é como um maldito filme de guerra! "Vamos, seus vermes! Vocês querem viver para sempre? Vão! Vão! Vão!"',--This is like a blerrie war movie! "Come on you maggots! You wanna live forever? Go! Go! Go!"
    loc_deep_78_03 = "Esquecem o plano A! Eles sabem que estamos chegando, então vamos meter bala nessas idiotas com estilo!",--No sense beating around the bush! They know we're coming, so let's take these chops out in style!
    loc_deep_79_01 = "O sistema de transferência de óleo está bloqueado por um firewall. Destruam o servidor e o firewall.",--The oil transfer system is locked behind a firewall. Destroy the server, destroy the firewall.
    loc_deep_79_02 = "O servidor está travado, o que está bloqueando o sistema de transferência de óleo da plataforma. Acho que é hora de uma reinicialização forçada.",--The server's on lockdown, which is blocking the rig's oil transfer system. I think it's time for a hard reboot.
    loc_deep_79_03 = "Eles desligaram o sistema de transferência de óleo, mas se vocês tirarem o servidor, tudo será redefinido.",--They've shut down the oil transfer system, but if you take out the server, everything will reset.
    loc_deep_80_01 = "O que está demorando tanto? Acabem com o servidor!",--What's taking so long? Bash the server!
    loc_deep_80_02 = "Precisamos desse servidor fora de serviço!",--We need that server out of commission!
    loc_deep_80_03 = "Entrem lá e acabem com o servidor!",--Get in there and take out the server!
    loc_deep_81_01 = "Hora de colocarem nossa transferência no sistema. O servidor está desbloqueado, mas precisamos de um pen-drive para usar os computadores. Nossa inteligência diz que deve estar trancado em um armário em algum lugar.",--Time to put our transfer into the system. The server's unlocked, but we need a USB drive to use the computers. Our intel says it should be locked in a cabinet somewhere.
    loc_deep_81_02 = "O sistema de transferência voltou a funcionar! Só precisamos de um pen-drive para usar os computadores administrativos. Descubram onde eles guardaram.",--The transfer system's back up and running! We just need a USB drive to use the admin computers. Find where they're keeping it locked up.
    loc_deep_81_03 = "O firewall caiu! Só precisam encontrar um pen-drive para desbloquear os computadores administrativos. Vejam eles guardaram em um armário ou algo assim.",--Firewall's down! Just need to find a USB drive to unlock the admin computers. See if they've locked in a cabinet or something.
    loc_deep_82_01 = "Eles deixam o pen-drive em algum lugar seguro. Olhem em volta.",--They keep the USB stick somewhere secure. Look around.
    loc_deep_82_02 = "Nosso informante diz que o pen-drive está trancado em um armário.",--Our intel says the USB drive's locked up in a cabinet.
    loc_deep_82_03 = "Continuem procurando, amigos. Precisamos desse pen-drive.",--Keep looking, friends. We need that USB.
    loc_deep_83_01 = "Eles têm alguns lotes de óleo armazenados aqui. Queremos o mais puro. Vão para a Sala de Extração e peguem uma amostra que podemos testar.",--They've got a few oil batches stored here. We want the purest one. Go to the Extraction Room and grab a sample we can test.
    loc_deep_83_02 = "Keegan não quer qualquer lote de óleo. É tudo sobre pureza. Vocês podem pegar uma amostra de teste na Sala de Extração.",--Keegan doesn't want just any batch of oil. It's all about purity. You can snag a testing sample from the Extraction Room.
    loc_deep_83_03 = "Precisamos testar os lotes de óleo da SERA para ver qual é o mais puro. Peguem uma amostra da Sala de Extração.",--We need to test SERA's oil batches to see which one's the purest. Take a sample from the Extraction Room.
    loc_deep_84_01 = "Vocês podem coletar amostras de óleo dos canos na Sala de Extração.",--You can grab oil samples from the pipes in the Extraction Room.
    loc_deep_84_02 = "A Sala de Extração é o melhor lugar para obter uma amostra de óleo.",--The Extraction Room is the best place to get an oil sample.
    loc_deep_84_03 = "Precisamos dessa amostra de óleo! Vão para a Sala de Extração!",--We need that oil sample! Go to the Extraction Room!
    loc_deep_85_01 = "Agora, vão ao laboratório e testem a pureza da amostra.",--Now, get to the lab and test the sample's purity.
    loc_deep_85_02 = "Passem essa amostra pelo laboratório de testes.",--Run that sample through the testing lab.
    loc_deep_85_03 = "Há uma máquina no laboratório para testar a pureza do óleo.",--There's a machine in the lab for testing oil purity.
    loc_deep_86_01 = "Vão para o laboratório! Não temos a noite toda!",--Get to the lab! We haven't got all night!
    loc_deep_86_02 = "Se vocês não tenham levado o seu kit de química, usem o laboratório!",--Unless you brought your chemistry set, use the laboratory!
    loc_deep_86_03 = "Testem essa amostra no laboratório!",--Test that sample in the laboratory!
    loc_deep_87_01 = "Essa amostra não é pura o suficiente. Tentem outro!",--That sample isn't pure enough. Try another!
    loc_deep_87_02 = "Não é isso. Peguem outra amostra!",--That's not it. Take another sample!
    loc_deep_87_03 = "Esse lote não vai servir. Experimentem outro!",--That batch won't cut it. Sample another!
    loc_deep_88A_01 = "As leituras dessa amostra são excelentes! Puro como pode ser!",--The readings on that sample are excellent! Pure as can be!
    loc_deep_88A_02 = "Falou a minha língua! Essa amostra é perfeita. Além da perfeição.",--Now we're talking! That sample's perfect. Beyond perfect.
    loc_deep_88A_03 = "Vocês encontraram o lote premium deles! Vamos ganhar muito dinheiro com esse petróleo!",--You found their premium batch! We're going to make a lot of money off this oil!
    loc_deep_88_01 = "Essa amostra deve funcionar bem!",--That sample should work fine!
    loc_deep_88_02 = "Isso deve servir! Esta amostra é exatamente o que precisamos.",--That'll do it! This sample's just what we need.
    loc_deep_88_03 = "Sim! Esse é o óleo que o Keegan quer!",--Yes! That's the oil Keegan wants!
    loc_deep_89_01 = "Os policiais interromperam o teste! Quão mesquinho é isso? Reinicie a máquina!",--The kerels stopped the test! How petty is that? Restart the machine!
    loc_deep_89_02 = "Eles mexeram com a máquina de testes! Consertem!",--They messed with the testing machine! Fix it!
    loc_deep_89_03 = "Malditos policiais interromperam o teste!",--Damn kerels interrupted the test!
    loc_deep_90_01 = "Agora, encontrem a mangueira de transferência e abaixem-a.",--Now, find the transfer hose and lower it down.
    loc_deep_90_02 = "Sabemos qual óleo roubar. Soltem a mangueira de transferência para o nosso navio-tanque.",--We know which oil to steal. Drop the transfer hose to our tanker ship.
    loc_deep_90_03 = "Vamos drenar esta plataforma de petróleo até secar! Abram a mangueira de transferência.",--Let's drain this oil rig dry! Deploy the transfer hose.
    loc_deep_91A_01 = "Ali está o guindaste com a mangueira de transferência!",--There's the crane with the transfer hose!
    loc_deep_91A_02 = "Soltem a mangueira com aquele guindaste!",--Drop the hose with that crane!
    loc_deep_91A_03 = "Ativem o guindaste de transferência!",--Activate the transfer crane!
    loc_deep_91_01 = "Não há tempo a perder, idiotas! Abaixem a mangueira de transferência!",--No time to waste, chops! Lower the transfer hose!
    loc_deep_91_02 = "Soltem a mangueira de transferência!",--Drop the transfer hose!
    loc_deep_91_03 = "Encontrem a mangueira de transferência e abaixem-a!",--Find the transfer hose and lower it down!
    loc_deep_92_01 = "Precisamos conectar esses tubos ao tanque que corresponde à nossa amostra de óleo. Quando estiverem prontos, puxem a alavanca do tanque. Vou certificar que o navio estará em posição.",--We need to connect these pipes to the tank that matches our oil sample. When they're ready, pull the lever on the tank. I'll make sure the ship's in position.
    loc_deep_92_02 = "Enquanto nosso navio se prepara, conectem os tubos de transferência ao tanque de óleo certo. Puxem a alavanca de liberação quando estiverem ajustados.",--While our ship's getting ready, connect the transfer pipes to the right oil tank. Pull the release lever when they're set.
    loc_deep_92_03 = "Um desses tanques deve corresponder à nossa amostra de óleo. Conectem-o aos canos e puxem a alavanca.",--One of these tanks should match our oil sample. Link it up to the pipes, then pull the lever.
    loc_deep_93A_01 = "Bom trabalho. Agora liguem o gerador da bomba.",--Good work. Now turn on the pump generator.
    loc_deep_93A_02 = "Quase lá. Liguem o gerador da bomba.",--Almost there. Fire up the pump generator.
    loc_deep_93A_03 = "Tudo pronto. Só precisam ligar o gerador da bomba.",--All set. Just need to turn on the pump generator.
    loc_deep_93_01 = "Alinhem os canos e puxem a alavanca do nosso tanque.",--Line up the pipes, then pull the lever on our tank.
    loc_deep_93_02 = "Quando os canos estiverem prontos, puxem a alavanca do nosso tanque.",--When the pipes are ready, pull the lever on our tank.
    loc_deep_93_03 = "Há uma alavanca no tanque de óleo. Puxem-o quando os tubos estiverem ajustados.",--There's a lever on the oil tank. Pull it when the pipes are set.
    loc_deep_94_01 = "Algo está errado com a porra dos canos!",--Something's wrong with the blerrie pipes!
    loc_deep_94_02 = "O óleo não está saindo!",--The oil's not coming through!
    loc_deep_94_03 = "Deem outra olhada naqueles canos!",--Take another look at those pipes!
    loc_deep_95_01 = "Perfeito! Nosso petroleiro está extraindo o óleo. Tentem não morrer antes de terminar!",--Perfect! Our tanker's siphoning the oil. Try not to die before it's finished!
    loc_deep_95_02 = "Transferência de óleo em andamento. Protejam o forte!",--Oil transfer in progress. Hold down the fort!
    loc_deep_95_03 = "Sifonando o óleo agora. Só não deixam que os policiais interfiram!",--Siphoning the oil now. Make sure the kerels don't interfere!
    loc_deep_96_01 = "O gerador parou! Consertem e mantenham os policiais longe!",--Pump generators down! Fix it, and keep those kerels back!
    loc_deep_96_02 = "Os policiais bagunçaram o gerador da bomba de oléo!",--The kerels messed up the pump generator!
    loc_deep_96_03 = "Consertem o gerador da bomba de oléo! Esses policiais são implacáveis!",--Fix the pump generator! These kerels are relentless!
    loc_deep_97A_01 = "Merda! A bomba está parada. Girem as válvulas de pressão para fluir novamente.",--Kak! The pump's backed up. Turn the pressure valves to get it flowing again.
    loc_deep_97A_02 = "Parece que forçamos demais a bomba de transferência. Acionem as válvulas de pressão para corrigir.",--Looks like we pushed the transfer pump too hard. Crank the pressure valves to fix it.
    loc_deep_97A_03 = "Algo deu errado com a bomba! Usem as válvulas de pressão para fazer as coisas se moverem.",--Something's gone screwy with the pump! Use the pressure valves to get things moving.
    loc_deep_97B_01 = "Girar as válvulas de pressão fará com que a bomba se mova novamente.",--Turning the pressure valves will get the pump moving again.
    loc_deep_97B_02 = "As válvulas de pressão devem estar espalhadas pela Área de Processamento.",--The pressure valves should be scattered around the Processing Area.
    loc_deep_97B_03 = "A pressão está forte, seus idiotas! Girem essas válvulas!",--Pressure's on, you chops! Turn those valves!
    loc_deep_97C_01 = "Tudo bem, estamos nos movendo novamente. Não deixem que os policiais estraguem nada.",--Alright, we're moving again. Make sure the kerels don't screw anything up.
    loc_deep_97C_02 = "A bomba está consertada! Protejam o gerador enquanto terminamos aqui.",--The pump's fixed! Protect the generator while we finish up here.
    loc_deep_97C_03 = "Indo bem! Mas acho que os policiais estão mirando no gerador da bomba. Fiquem de olho nisto.",--Nice going! But I think the kerels are targeting the pump generator. Keep an eye on it.
    loc_deep_97_01 = "Os policiais mexeram com a alavanca do nosso tanque!",--The kerels messed with the lever on our tank!
    loc_deep_97_02 = "Eles desligaram a transferência! Verifiquem a alavanca no tanque de óleo!",--They shut off the transfer! Check the lever on the oil tank!
    loc_deep_97_03 = "O que aconteceu?! Eles mexeram na alavanca do tanque de óleo?",--What happened?! Did they mess with the oil tank lever?
    loc_deep_98_01 = "Keegan tem seu óleo! Agora, vão para a torre de perfuração. Temos uma plataforma para destruir!",--Keegan's got his oil! Now, head for the Drilling Tower. We've got a rig to destroy!
    loc_deep_98_02 = "O óleo está seguro! Agora podemos explodir a merda toda para o inferno! Vão para a torre de perfuração!",--The oil's secure! Now we can blow this rig to hell! Get to the Drilling Tower!
    loc_deep_98_03 = "Excelente! Agora podemos explodir este lugar! Vamos para a torre de perfuração.",--Excellent! Now we can blow this place sky high! Let's head to the Drilling Tower.
    loc_deep_99_01 = "Vão para a torre, rápido! Não quero deixar Gabriel esperando.",--Get to the Tower, pronto! Don't want to keep Gabriel waiting.
    loc_deep_99_02 = "Gabriel está esperando por você na torre de perfuração, então preparem suas armas!",--Gabriel's waiting for you in the Drilling Tower, so get those guns ready!
    loc_deep_99_03 = "A torre de perfuração é nossa próxima parada!",--The Drilling Tower's our next stop!
    loc_deep_end_loud_01 = "Não se preocupe, Keegan. Tenho certeza de que estaremos de volta. Se houver dinheiro a ser ganho, estaremos lá para roubar!",--Don't worry, Keegan. I'm sure we'll be back around. If there's money to be made, we'll be there to steal it!
    loc_deep_end_stealth_01 = "Prazer em trabalhar com você, Keegan. Da próxima vez que tivermos negócios no Lone Star State, saberemos para quem ligar.",--Pleasure working with you, Keegan. Next time we've got business in the Lone Star State, we'll know who to call.

    -- Objetivos
    hud_heist_deep01_hl = "Embarque na plataforma de petróleo",--Board the Oil Rig
    hud_heist_deep01 = "Avance para a plataforma de petróleo. Você receberá mais instruções à medida que avança.",--Make your way to the oil platform. You'll receive further instructions as you go.
    hud_heist_deep02_hl = "Invada o servidor",--Hack the server
    hud_heist_deep02 = "Locke precisa substituir a rede de segurança antes que possamos alterar o cronograma de transferência. A sala do servidor requer um cartão de acesso para abrir. Um dos funcionários da SERA deve tê-lo.",--Locke needs to override the security network before we can alter the transfer schedule. The server room requires a keycard to open. One of the SERA employees should have it.
    hud_heist_deep03_hl = "Agende uma transferência de óleo",--Schedule an oil transfer
    hud_heist_deep03 = "Um computador no escritório administrativo nos dará acesso ao cronograma de transferência de óleo. Coloque nosso navio-tanque no sistema para não levantar suspeitas.",--A computer in the admin office will give us access to the oil transfer schedule. Put our tanker ship in the system so we don't raise suspicion.
    hud_heist_deep04_hl = "Encontre a amostra de óleo mais pura",--Find the purest oil sample
    hud_heist_deep04 = "A plataforma possui vários lotes de óleo em diferentes níveis de pureza. Pegue uma amostra da Sala de Extração no andar superior e teste-a no Laboratório.",--The rig has several batches of oil at different purity levels. Take a sample from the Extraction Room on the upper deck and test it in the Laboratory.
    hud_heist_deep05_hl = "Abaixe a mangueira de transferência",--Lower the transfer hose
    hud_heist_deep05 = "Vá até a Área de Processamento e abaixe a mangueira de transferência até nosso navio-tanque.",--Make your way to the Processing Area and lower the transfer hose down to our tanker ship.
    hud_heist_deep06_hl = "Configure os tubos de transferência",--Set up the transfer pipes
    hud_heist_deep06 = "Precisamos conectar esses tubos de transferência do gerador da bomba ao tanque que corresponde à nossa amostra de óleo. Uma vez que a conexão esteja boa, puxe a alavanca no tanque e acione o gerador.",--We need to link these transfer pipes from the pump generator to the tank that matches our oil sample. Once the connection is good, pull the lever on the tank and then activate the generator.
    hud_heist_deep07_hl = "Encontre um computador para desativar o firewall",--Find a computer to disable the firewall
    hud_heist_deep07 = "Um firewall interrompeu nossa transferência de óleo! Encontre um laptop para desativá-lo.",--A firewall has halted our oil transfer! Find a laptop to disable it.
    hud_heist_deep08_hl = "Atenda o telefone",--Answer the phone
    hud_heist_deep08 = "A segurança está ligando para checar nossa transferência! Coloque o Locke no telefone, ou um guarda virá investigar.",--Security's calling to check on our transfer! Patch Locke into the phone, or a guard will come to investigate.
    hud_heist_deep09_hl = "Chegue à Torre de Perfuração",--Get to the Drilling Tower
    hud_heist_deep09 = "Reconecte a porta do hangar e prossiga para a torre que abriga a torre de perfuração.",--Rewire the hangar door and progress to the tower housing the drill derrick.
    hud_heist_deep10_hl = "Desative os lasers de segurança",--Disable the security lasers
    hud_heist_deep10 = "Existem lasers de segurança bloqueando a entrada do centro de comando de Gabriel. Nossa inteligência diz que eles podem ser desabilitados na sala elétrica da torre.",--There are security lasers blocking the entrance to Gabriel's command center. Our intel says they can be disabled from the tower's Electrical Room.
    hud_heist_deep11_hl = "Elimine Gabriel Santiago",--Eliminate Gabriel Santiago
    hud_heist_deep11 = "Gabriel está vestindo um traje de combate à prova de balas que enfraquece quando exposto ao fogo. Use o ambiente para torná-lo vulnerável.",--Gabriel's wearing a bulletproof combat suit that weakens when exposed to fire. Use your environment to render him vulnerable.
    hud_heist_deep12_hl = "Desative a proteção contra explosão",--Disable the blowout preventer
    hud_heist_deep12 = "Use o cartão de acesso de Gabriel para acessar a sala de controle e, em seguida, desligue a válvula anti-explosão da furadeira.",--Use Gabriel's keycard to access the control room, then shut off the drill's blowout preventer.
    hud_heist_deep13_hl = "Feche as válvulas de pressão",--Close the pressure valves
    hud_heist_deep13 = "Para criar a quantidade certa de pressão, gire as válvulas ao redor da torre de perfuração conforme Locke as diz.",--In order to build the right amount of pressure, turn the valves around the drill derrick as Locke calls them out.
    hud_heist_deep14_hl = "Inicie a furadeira",--Start the drill
    hud_heist_deep14 = "Os níveis de pressão estão definidos. Volte para a sala de controle e ligue a furadeira.",--The pressure levels are set. Get back to the control room and fire up the drill.
    hud_heist_deep15_hl = "Vote para o barco",--Return to the boat
    hud_heist_deep15 = "A broca vai explodir! Volte para o seu barco o mais rápido que puder!",--The drill's going to blow! Get back to your boat as fast as you can!
    hud_heist_deep16_hl = "Saia do raio de explosão",--Get out of the blast radius
    hud_heist_deep16 = "Afaste-se da plataforma de petróleo!",--Drive away from the oil rig!
    hud_heist_deep17_hl = "Fuga disponível",--Escape Available
    hud_heist_deep17 = "Trabalho concluído. Suba a bordo do navio-tanque.",--Job well done. Climb aboard the tanker ship.
    hud_heist_deep18_hl = "Destrua o server",--Destroy the server
    hud_heist_deep18 = "Um servidor está bloqueando todos os sistemas da plataforma de petróleo. Destrua-o.",--A network server is blocking all systems on the oil rig. Destroy it.
    hud_heist_deep19_hl = "Defenda o gerador da bomba de oléo",--Defend the pump generator
    hud_heist_deep19 = "Não deixe nenhum policial desligar o gerador!",--Don't let any cops turn off the pump generator!
    hud_heist_deep20_hl = "Abaixe a pressão da bomba",--Lower the pump pressure
    hud_heist_deep20 = "A pressão da bomba é instável! Gire as três válvulas de pressão para continuar a transferência de óleo.",--The pump pressure is unstable! Turn the three pressure valves in order to continue the oil transfer.
    hud_heist_deep21_hl = "Chegue ao heliporto",--Get to the helipad
    hud_heist_deep21 = "-O helicóptero está a caminho. Vá para o heliporto da plataforma de petróleo.",--The helicopter is on its way. Go to the oil rig's helipad.
    hud_heist_deep22_hl = "Queime Gabriel",--Burn Gabriel
    hud_heist_deep22 = "O fogo enfraquece o traje de combate de Gabriel. Use as válvulas para liberar óleo nos poços de petróleo e, em seguida, atire para incendiar as poças quando ele passar. Ele ficará vulnerável a balas enquanto estiver queimando.",--Fire weakens Gabriel's combat suit. Use the valves to release oil into the petroleum pits, then shoot to ignite the pools when he walks through. He'll be vulnerable to bullets while he's burning.
    hud_heist_deep23_hl = "Aguarde a transferência do óleo",--Wait for the oil transfer
    hud_heist_deep23 = "Fique fora de vista enquanto nosso petroleiro extrai o óleo. Alguém pode suspeitar da transferência de última hora, então esteja preparado para qualquer coisa.",--Stay out of sight while our tanker siphons the oil. Someone might get suspicious about the last-minute transfer, so be ready for anything.
    hud_heist_deep24_hl = "Coloque o gás tóxico",--Deploy the toxic gas
    hud_heist_deep24 = "Nosso homem de dentro escondeu um tanque de emissões de gás natural que a SERA coleta para teste. Podemos usá-lo para envenenar Gabriel silenciosamente. Quando ele estiver morto, desligue o gás e pegue seu cartão de acesso.",--Our inside man stashed a tank of natural gas emissions that SERA collects for testing. We can use it to poison Gabriel silently. When he's dead, shut off the gas and take his keycard.
    hud_heist_deep25_hl = "Ache o pen-drive",--Find the USB key
    hud_heist_deep25 = "Os computadores administrativos só podem ser acessados com uma chave USB. Nossa inteligência diz que está trancado em algum lugar seguro.",--The admin computers can only be accessed with a USB key. Our intel says that it's locked up somewhere secure.
    hud_heist_deep26_hl = "Ache a sala do server",--Locate the server room
    hud_heist_deep26 = "Infiltre-se na sala do servidor para que Locke possa passar pela rede de segurança.",--Infiltrate the server room so Locke can override the security network.
    hud_heist_deep27_hl = "Vá aos tanques de óleo",--Reach the Oil Tanks
    hud_heist_deep27 = "Siga em direção à ponte e suba a escada até a área de processamento.",--Head out towards the bridge, then take the staircase up to the Processing Area.
    hud_heist_deep28_hl = "Bloquear o Sistema de Ventilação",--Jam the Ventilation System
    hud_heist_deep28 = "Um ventilador próximo controla o fluxo de ar para o centro de comando de Gabriel. Use a ferramenta que nosso informante escondeu para bloqueá-lo.",--A nearby fan controls the airflow to Gabriel's command center. Use the tool our insider stashed to jam it.
    --hud_heist_deep29_hl = "TEXTO TRADUZIDO AQUI",--ERROR: hud_heist_deep29_hl
    --hud_heist_deep29 = "TEXTO TRADUZIDO AQUI",--ERROR: hud_heist_deep29
    --hud_heist_deep30_hl = "TEXTO TRADUZIDO AQUI",--ERROR: hud_heist_deep30_hl
    --hud_heist_deep30 = "TEXTO TRADUZIDO AQUI",--ERROR: hud_heist_deep30

    -- Pre-Planning
	menu_pp_deep_bpr_loc_a = "Doca de emergência",--Emergency Dock",
	menu_pp_deep_bpr_loc_d = "Level C",--Level C",
	menu_pp_deep_bpr_loc_c = "Level B",--Level B",
	menu_pp_deep_bpr_loc_b = "Level A",--Level A",
	menu_pp_deep_bpr_loc_e = "Level D",--Level D",
    menu_pp_asset_deep_uninterruptable_gen_loud_desc = "O especialista da Keegan inspecionará o mecanismo da bomba na Área de Processamento e ajustará os níveis de pressão, eliminando o risco de mau funcionamento enquanto você estiver roubando óleo.",",--Keegan's insider will inspect the pump mechanism in the Processing Area and adjust the pressure levels, eliminating the risk of a malfunction while you're stealing oil.",
	menu_pp_asset_deep_extra_boss_loot = "Dinheiro Extra",--Extra Cash",
	menu_pp_asset_deep_keycard_holder = "Marcar Cartão de acesso",--Keycard Intel",
	menu_pp_asset_deep_select_bridge = "Selecionar ponte",--Bridge Selection",
	menu_pp_asset_deep_boat_entrance_desc = "Use um barco para acessar a plataforma de petróleo pela doca de emergência.",--Use a boat to access the oil rig via the emergency dock.",
	menu_pp_asset_deep_boat_entrance = "Chegada de barco",--Boat Arrival",
	menu_pp_asset_deep_extra_boss_loot_desc = "Gabriel decidiu dar a si mesmo um aumento e reservou uma grande parte do dinheiro de Rainey para si. Você o encontrará escondido em seu centro de comando.",--Gabriel decided to give himself a raise, and he set aside a large chunk of Rainey's money for himself. You'll find it stashed in his command center.",
	menu_pp_asset_deep_select_bridge_desc = "Planeje com antecedência qual ponte usará para chegar na Área de Processamento e na Torre de Perfuração",",--Plan in advance which bridge to take to the Processing Area and Drilling Tower",
	menu_pp_asset_deep_parachute_entrance_desc = "Desça de um helicóptero para acessar a plataforma de petróleo mais rapidamente. Esteja avisado: Gabriel vai soar o alarme assim que você pousar.",--Descend from a helicopter to access the oil rig faster. Be warned: Gabriel will sound the alarm as soon as you land.",
	menu_pp_asset_deep_parachute_entrance = "Entrada de paraquedas",--Parachute Arrival",
	menu_pp_asset_deep_keycard_holder_desc = "Nosso informante nos informou qual trabalhador está carregando o cartão de acesso da sala do servidor.",--Our insider tipped us off to which worker is carrying the server room keycard.",
	menu_pp_asset_deep_uninterruptable_gen_loud = "Controle de Pressão da Bomba",--Pump Pressure Control (LOUD)",
}