return {
	-- Nomes e Descrições
	--heist_born = "The Biker Heist",--The Biker Heist
	heist_born_crimenet = "A decisão do Rust de entrar na Gangue PAYDAY não veio de graça. Seus ex-irmãos no OVERKILL MC estão com sede de sangue. Nosso sangue, para ser mais específico. Nós vamos caminhar direto na armadilha deles, mas vai valer a pena. Confiem em mim.$NL;$NL;» Entre na Casa do Clube$NL;» Encontre o Mecânico$NL;» Monte a Moto e fuja",--Rust's decision to join the Payday Gang did not come free of cost. His former brothers in the OVERKILL MC are out for blood. Our blood, to be more specific. We're walking straight into a trap, but it'll be worth it. Trust me.$NL;$NL;» Enter the clubhouse$NL;» Find the mechanic$NL;» Assemble the bike and escape
	--heist_born_hl = "Lion's Den",--Lion's Den
	heist_born_briefing = "Nós sabiamos que a lealdade do Rust seria meio instável, então o Dallas fez um plano para assegurar isso pegando a moto antiga da Casa do Clube. Uma coisa rápida e sorrateira, sabe? Infelizmente, as coisas ficaram mais complicadas. O OVERKILL MC pegaram o amigo mecânico do Rust, Mike como refém. Vejam, a razão que o Rust foi recrutado para começar, foi que ele sabe sobre um novo tipo de armamento avançado que o Bain quer. Mas o Rust decidiu que não vai nos contar merda nenhuma até seu amigo e sua moto forem asseguradas. Não temos outra escolha além de ir até a cova do leão e ajudá-lo, cavalheiros. Boa sorte. ",--We knew Rust's loyalty would be shaky at best, so Dallas came up with a plan to secure it by retaking the old biker's custom ride from the clubhouse. A quick and sneaky thing, you know? Unfortunately, things just got more complicated. The OVERKILL MC have taken Rust's mechanic friend, Mike, hostage. You see, the reason Rust was recruited to begin with, is that he has intel about a new type of advanced weaponry that Bain is after. But Rust has decided to not tell us shit until his friend and his bike are secured. No other choice than to walk straight into the lion's den and help him out, gentlemen. Good luck.
	--heist_chew = "Interception",--Interception
	--heist_chew_hl = "Interception",--Interception
	heist_chew_briefing = "Tudo certo, isso é o que sabemos: De algum jeito o OVERKILL MC colocaram suas mãos em um novo tipo de tecnologia chamado BCI. E acreditem em mim, cavalheiros; isso é o futuro. Essa tecnologia BCI permite a você controlar um drone militar usando o seu cérebro e como você pode imaginar, é bem valioso. O Bain tem um contato que pode oferecer uma grande quantia de dinheiro por ele. O Capacete BCI está sendo movido por um trem, felizmente o Bile está pronto para deixarem vocês agora. Agora, vamos ao trabalho.",--All right, this is what we know: Somehow the OVERKILL MC got their hands on a new type of technology called brain-computer interface. and believe me, gentlemen; this is the future. This BCI technology lets you control a military drone by only using your brain and as you can imagine, it's very valuable. Bain is in contact with a potential buyer that is offering a large amount of cash to get his hands on it. The BCI headset and computer software is already on the move on a freight train, fortunately Bile is ready to drop you off. Now get to work.
	
	-- Legendas (Bain - Dia 1)
	pln_brn_01_02 = "Aquilo poderia ter ido muito pior. Agora libertem ele e vamos indo.",--That could have gone a lot worse. Now untie him and let's get going.
	pln_brn_01_01 = "Essa passou perto. Agora, não temos tempo a perder, gangue. Tirem ele daquela cadeira para acabar logo com isso.",--That was too damn close. Now, we don't have time to stand around, gang. Get him off that chair so we can get this over with.
	pln_brn_05_02 = "Caveira Cromada? Tanto faz, só façam o que o mecânico pede. Vão até a Casa do Clube e usem o maçarico que ele deu a vocês.",--Chrome skull? Whatever, just do as the mechanic says. Go to the clubhouse and use the blowtorch he gave you.
	pln_brn_06_03 = "Lembrem-se: O mecânico disse algo sobre um Bunker, e que vocês precisam encontrar um assento para a moto ali.",--Remember: the mechanic said something about a Bunker, and that you would find a seat for the bike there.
	pln_brn_10_03 = "Ele conseguiu, gangue. Vocês podem pegar mais loot ou peguem as motos e fujam!",--He did it, gang. You can grab more loot if you want or you get on those bikes and escape!
	pln_brn_09_02 = "Ah, Vocês sabem que a gente não vai embora sem algumas armas. Só precisamos nos livrar delas.",--Oh, you know we aren't leaving without some of those weapons. We just need to get them out of here some way...
	pln_brn_11_01 = "Agora ouçam: A policia vai cercar o lugar inteiro em minutos. O tempo está passando! Usem a rota do canal, e rápido!",--Now listen: The police will have the entire site surrounded any minute. The clock is ticking! Take the canal route, quick!
	pln_brn_03_01 = "O mecânico falou que ele precisa de uma de suas ferramentas da Oficina. Vão lá.",--The mechanic said he needs his tools from the workshop. Get over there.
	pln_brn_03_03 = "A Oficina é onde vocês encontrarão as ferramentas. É isso o que o mecânico falou.",--The workshop is where you'll find the tools. That's what the mechanic said.
	pln_brn_05_03 = "Só peguem a Caveira Cromada que o mecânico pediu. Entrem na Casa do Clube e usem o maçarico.",--Just get the chrome skull the mechanic is asking for. Go inside the clubhouse and use the blowtorch he gave you.
	pln_brn_12_01 = "Continuem dirigindo!",--Just keep driving straight!
	pln_brn_14_03 = "Parando pra pensar, estou com sede também. Já volto!",--Come to think of it, I'm kinda thirsty too. Be right back!
	pln_brn_03_02 = "O mecânico disse que vocês levassem a ele ferramentas especiais da Oficina. Sejam rápidos.",--The mechanic said he wants you to bring him some kind of special tools from the workshop. Hurry up.
	pln_brn_08_06 = "Excelente, Essa é a parte. Levem de volta ao mecânico.",--Excellent, that's a part in the bag. Bring it back to the mechanic.
	pln_brn_07_03 = "Não ouviram o cara, gangue? Ele precisa de um tanque de gasolina e tubos de escape da Oficina. Vão lá e entreguem-as",--Didn't you hear the man, gang? He needs a gas tank and exhaust pipes from the workshop. Get over there and deliver.
	pln_brn_11_03 = "Droga, a policia está jogando tudo o que eles tem em vocês, e vocês vão estar cercados se não sairem agora. Se apressem e fujam pela rota do canal. Agora!",--Damn, the cops are bringing everything they have to get you, and you're gonna be surrounded if you don't leave now. Hurry up and escape via the canal route. Now!
	pln_brn_11_02 = "Pessoal, vocês precisam dar o fora daí, e rápido. A SWAT vai inundar esse lugar e essa é a nossa única chance de fugir!",--Guys, you need to get the hell out of there, and you need to do it fast. SWATS are gonna swarm the place and this is your only chance to get out!
	pln_brn_10_01 = "O mecânico acabou. Se quiserem pegar mais loot podem pegar agora, caso contrário, saiam daí.",--The mechanic's done. If you want more loot you get it now, otherwise you ride out of there. 
	pln_brn_07_01 = "Um tanque de gasolina, gangue. É isso que o mecânico disse que precisava, e vocês vão encontrar eles na Oficina.",--A gas tank and exhaust pipes, gang. That's what the mechanic said he needed, and you'll find them in the workshop.
	pln_brn_08_01 = "É esse, levem de volta ao mecânico!",--That's the one, bring it back to the mechanic!
	pln_brn_08_07 = "Uma parte coletada. Levem ao mecânico.",--One part collected. Get it to the mechanic.
	pln_brn_07_02 = "O mecânico disse que precisava de um tanque de gasolina e tubos de escape da Oficina.",--The mechanic said he needed a gas tank and exhaust pipes from the workshop.
	pln_brn_10_02 = "Ouviram o cara! Vocês podem roubar mais coisas ou pegar a moto e fugir! Dirijam como o vento!",--You heard the man! You can either steal more things or you get on that bike and ride! Ride like the wind!
	pln_brn_13_02 = "Dirijam até a grade e vocês estarão seguros!",--Ride through the gate and you'll be safe!
	pln_brn_14_02 = "Acho que o cara realmente quer um refrigerante...",--I guess the man really wanted a soda...
	pln_brn_09_01 = "Aquilo é um ótimo loot que eles tem, mas agora é nosso. Como vamos tirar eles?",--That's some fine loot they stashed in there, but it's ours now. How do we get it out?
	pln_brn_01_03 = "Vocês salvaram o mecânico a tempo. Agora ajudem ele a sair da cadeira e montar a moto.",--You saved the mechanic just in time. Now help him off the chair and make him assemble the bike.
	pln_brn_05_01 = "Rust quer muito uma Caveira Cromada para sua moto, não temos tempo para reclamar. Usem o maçarico que o mecânico os deu quando chegarem na Casa do Clube.",--Rust really wants a chrome skull for his bike, and we have no time to argue. Use the blowtorch the mechanic gave you when you reach the clubhouse.
	pln_brn_08_03 = "Ótimo, essa é a parte que ele precisa.",--Great, that's the part he needed.
	pln_brn_13_03 = "Aquele portão é a fuga de vocês!",--That gate is your escape!
	pln_brn_02_03 = "Precisamos do mecânico para nos ajudar a montar a moto do Rust. Sigam ele.",--We need the mechanic's help to put together Rust's bike. Follow his lead.
	pln_brn_12_02 = "É isso! Continuem andando!",--That's it! Keep going!
	pln_brn_14_01 = "Uhh.. Ok então.",--Umm... Okay then.
	pln_brn_13_01 = "Ali está a fuga de vocês! Dirijam pelo portão e vocês estarão seguros!",--There's the escape! Ride through the gate and you'll be safe!
	pln_brn_09_03 = "Vamos pegar essas armas para nós. Mas como, essa é a questão...",--We're taking some of these nice weapons with us. But how, that's the question...
	pln_brn_04_02 = "A moto não vai funcionar sem um motor. O mecânico disse que viu algum dentro da Casa do Clube.",--The bike isn't going to function without an engine. The mechanic said he saw some inside the clubhouse.
	pln_brn_04_03 = "O mecânico mencionou que ele viu os motores dentro da Casa do Clube. Deem uma olhada.",--The mechanic mentioned he saw them store engines inside the clubhouse. Go have a look.
	pln_brn_02_02 = "Levem o mecânico para ajudar vocês a montar a moto do Rust. Vocês vão ter que seguir ele.",--Get the mechanic to help you assemble Rust's bike. You're gonna have to follow his lead on this one.
	pln_brn_02_01 = "Façam o mecânico começar a trabalhar na moto do Rust. Só façam o que ele pede e dê a ele o que ele pede.",--Get the mechanic to start working on Rust's bike. Just do as he says and get him what he needs.
	pln_brn_04_01 = "A moto do Rust não vai andar sem um motor, e o mecânico disse para olhar dentro da Casa do Clube. Movam-se.",--Rust's bike isn't going to roll without an engine, and the mechanic said to check inside the clubhouse. Get a move on.
	pln_brn_06_01 = "Os motoqueiros estão aparentemente guardando coisas em um Bunker antigo. O mecânico disse que vocês podem encontrar um assento da moto ali.",--The bikers are apparently storing stuff in an old Bunker. The mechanic said you would find a seat for the bike in there.
	pln_brn_06_02 = "O mecânico falou para vocês irem ao Bunker e pegar um assento para ele.",--The mechanic told you to go to the Bunker and get the seat for him. 
	pln_brn_08_02 = "Perfeito, agora entreguem a parte para o mecânico para ele trabalhar!",--Perfect, now deliver the part to the mechanic so he can work!
	pln_brn_08_04 = "Vocês pegaram o que ele pediu, agora levem para ele.",--You got what he asked for, now you need to bring it to him.
	pln_brn_08_05 = "Essa é a parte que ele pediu. Um passo mais perto gangue.",--That's the part he asked for. One step closer gang.
	pln_brn_12_03 = "Vão, garotos e garotas, vão!",--Ride, boys and girls, ride!
	
	-- Legendas (Outros - Dia 1)
	bkl_brn_intro_01 = "Olhem para vocês filhas da puta vindo aqui com suas máscaras estúpidas. Eu não consigo acreditar que Rust quer ser um de vocês. De qualquer jeito, duas coisas vão cair agora.",--Look at you motherfuckers just walking in here with your stupid ass-masks. I can't fucking believe Rust wants to be one of you freaks. Regardless, two things are gonna go down now. 
	bkl_brn_intro_02 = "Eu não sei o que fez Rust nos trair, mas eu não ligo, assim como eu nunca me importava para aquele cabelo prateado fudido. Mas vocês são um bando de tolos do caralho por virem aqui, me ouviran?",--I don't know what made Rust stab us in the back, but I really don't give a shit, as I never cared for that silver-haired fucker. But you are a couple of fucking fools for coming here, you hear me?
	bkl_brn_intro_01b = "Vou começar estourando a cabeça desse mecânico de merda, e depois vamos pintar essa sala com o seu sangue de palhaço. E a melhor parte é que vocês não podem fazer porra nenhuma sobre isso.",--I'll start by blowin' off the head of this piece of shit mechanic, and after that we're gonna paint this room with your clown-blood as well. And the best part is that there's jack shit you can do about it.
	bkl_brn_intro_02b = "Não tem chance alguma que vocês vão sair daqui vivos. Primeiramente, vocês vão me assistir colocar uma bala na cabeça desse mecânico, e depois a minha gangue vai fuder muito vocês.",--There's no chance in hell you're getting out alive. Firstly, you're gonna witness me put a bullet through this mechanic's head, and after that my crew is gonna fuck you up good.
	bkl_brn_intro_03 = "Eu não fiquei surpreso com a traição do Rust, sabe? Ele sempre foi um velho ganancioso. Mas sangue precisa ser pago com sangue, e vocês cometeram um puta erro vindo aqui.",--I wasn't really surprised by Rust's betrayal, you know? He was always an old and greedy fuck. But blood needs to be paid with blood, and you made a big-ass mistake by coming here.
	bkl_brn_intro_03b = "Vocês acharam que isso seria um resgate ou o quê? Não, não vai ser assim. Seus tolos vão testemunhar nós matando esse pedaço de merda de mecânico primeiro, e vocês vão encontrar ele lá no inferno.",--You thought this was a rescue mission or what? Nah, it's not gonna play out like that. You fools are gonna witness me kill this piece of shit mechanic first, and then you're gonna join him in the afterlife.
	bkl_brn_01_03 = "Me testemunhem!",--Witness me!
	bkl_brn_01_01 = "Vingança!",--Payback!
	bkl_brn_01_02 = "Hora da retribuição!",--Retribution time!
	mch_brn_20_02b = "Pessoal, por favor. Um profissional precisa de um lanchinho quando estiver trabalhando. Me tragam aquela Coca e façam o mecânico um homem feliz.",--Guys, please. A professional man needs his snack when working. Get me that coke and make the mechanic a happy man.
	mch_brn_07_01b = "Caralho! Socorro!",--Holy shit! Help!
	mch_brn_06_03b = "Olá? Não vão sem mim!",--Hello? Don't go without me!
	mch_brn_23_07b = "Eu deveria só ter pego um trabalho de escritório de merda...",--I should just have gotten a shitty office job instead...
	mch_brn_16_02b = "Eu preciso entrar na garagem e vocês precisam de proteger. Vamos lá, venham.",--I need to get into the garage and you need to protect me. Let's go, come on.
	mch_brn_12_01b = "Ah, quase esqueci. Vocês precisam de um maçarico para entrar.",--Oh, almost forgot. You'll need to use a blowtorch to get inside.
	mch_brn_08_03b = "Porra, cara... Eu não quero morrer por essa merda... Vou manter minha promessa e montar a moto para vocês, mas vou ficar aqui. Encontrem as partes e me tragam aqui.",--Fuck me, man... I don't wanna die over this shit... I'll keep my promise and assemble the bike for ya, but I'm staying right here. Find the parts and bring them back here.
	mch_brn_16_03b = "Ei, palhaços! Eu realmente quero ir pra casa, ok? Então por favor me levem até a garagem para eu pegar o que eu preciso. Preciso que me protejam enquanto eu trabalho.",--Hey! Clowns! I really want to go home, okay? So please take me to the garage so I can get the stuff I need. Kinda need you to protect me while I work...
	mch_brn_20_03b = "Vamos lá, onde está a coca? Estou com sede!",--Come on, where's that coke? I'm thirsty!
	mch_brn_22_02b = "Ow! Que porra é essa! Eu não posso trabalhar se tiver todos esses policiais na minha cara.",--Yo! What the fuck! I can't work if I have these cops right in my fucking face!
	mch_brn_10_03b = "Um motor. Isso é o que precisamos. Eu acho que vi alguns dentro da Casa do Clube antes deles começarem a me bater pra caralho.",--An engine. That's what we need. I think I saw some inside the clubhouse before they started beating the livin' shit out of me.
	mch_brn_02_01b = "Graças a Deus vocês vieram! Esses malucos iam me matar, e por qual causa? Eu só vim aqui pegar a moto... Jesus Cristo...",--Thank fucking god you're here! These bastards were going to kill me, and for what? I just came here to get the bike... Jesus Christ...
	mch_brn_15_03b = "Hmm... Ok, Não tem como evitar. Eu vou ter que ir na garagem e tirar as partes da moto lá. Única maneira de pegar as coisas de que preciso. Me levem lá e me deem cobertura.",--Hmm... Yup, there's no way around it. I'm gonna need to get into the garage and take apart one of the bikes there. Only way to get the stuff I need. Take me there and cover my ass while I work.
	mch_brn_05_08b = "Porra! Eu não quero morrer hoje!",--Fuck! I don't wanna die today!
	mch_brn_14_03b = "Hmm... Ah, ok! Eu preciso de alguns tubos de escape e um tanque de gasolina. Tem um suspensor na Oficina. Eles guardam isso lá. Me tragam os dois e vou ficar feliz.",--Hmm... Ah, okay! I need some exhaust pipes and a gas tank. There's a ceiling lift in the workshop. They store them up there. Get me both and I'm all happy.
	mch_brn_23_03b = "Jesus Cristinho me proteja...",--Sweet baby Jesus protect me...
	mch_brn_09_02b = "Minhas ferramentas especiais. Sim, eu definitivamente preciso das minhas ferramentas especiais, vocês vão achar isso na Oficina. Procurem nas caixas de ferramentas.",--My special tools. Yes, I definitely need my special tools, and you'll find those in the workshop. Look out for toolboxes.
	mch_brn_17_01b = "Ok, estou aqui. Me deem cobertura enquanto eu trabalho!",--Okay, I'm here. Just watch my back while I work!
	mch_brn_13_02b = "Ok, ouçam - tem um Bunker no quintal, sim? Não me perguntem o motivo. Vão lá e encontrem um lindo assento.",--Okay, listen up - there's a Bunker in the backyard, yeah? Don't ask me why. Get in there, and you'll find a fancy lookin' seat.
	mch_brn_19_01b = "Eu não sei vocês, mas to morrendo de sede. Alguns dos docinhos ai pode me pegar uma coca na máquina de vendas?",--I don't know about you guys, but I'm dying of thirst. Would any of you be a sweetheart and grab me a coke from the vending machine?
	mch_brn_23_05b = "Jesus... como caralhos eu fiquei envolvido nessa merda...",--Jesus... how the fuck did I get involved in this bullshit...
	mch_brn_05_03b = "Eu deveria ter corrido quando eu ainda podia...",--I should just have ran when I had the chance...
	mch_brn_05_07b = "Puta merda!",--Holy fuck!
	mch_brn_22_03b = "Wow, ei! Como que vou fazer minhas coisas assim? Lidem com eles!",--Wow, hey! How am I supposed to do my thing like this? Take care of 'em!
	mch_brn_15_02b = "Ok, ouçam. Esse vai ser complicado. Eu preciso pegar umas merdas especiais de outra moto. Isso significa que vocês vão ter que me levar até a garagem para eu fazer minha mágica.",--Okay, listen up. This one's tricky. I need to take apart a bike and get some special shit. This means you need to take me to the garage so I can work my magic.
	mch_brn_06_05b = "Ei! Volte!",--Hey! Come back!
	mch_brn_18_01b = "Ufa, estou pronto. Peguei o que precisava. Me levem de volta ao caminhão.",--Whew, I'm done. I got what I needed. Take me back to the truck.
	mch_brn_07_04b = "Ah, merda!",--Oh, shit! 
	mch_brn_21_02b = "Ok, isso deve servir! O que vem agora?",--Okay, that should do! What's next?
	mch_brn_18_02b = "Ok, eu peguei o que eu queria! Me levem de volta ao caminhão para que eu consiga juntar essa merda toda.",--Okay, I got what I came for! Get me back to the truck so I can put the shit together.
	mch_brn_13_03b = "Ok, esse bebê vai precisar de um trono e eu sei como conseguir um. Estão vendo aquele quintal? Eles tem uma caralhada de coisas lá no Bunker. Me tragam um assento bonito.",--Okay, this baby is gonna need a throne and I know where to get one. See that backyard over there? They have a shitload of stuff stored in the Bunker there. So go and bring me a fancy seat.
	mch_brn_11_02b = "Lindas motos são tudo sobre detalhes, e sei que o Rust quer o melhor desse bebê. Eles tem uma Caveira Cromada especial dentro da Casa do Clube. Vão pegar.",--Beautiful bikes are all about the details, and I know Rust wants the best for his baby. They have a special made chrome skull inside the clubhouse. Go fetch.
	mch_brn_22_04b = "Como é que eu supostamente vou trabalhar desse jeito?!",--How am I supposed to work like this?!
	mch_brn_05_01b = "Assim não, assim não...",--Not like this, not like this...
	mch_brn_22_05b = "Que porra é essa! Mantenham eles longe de mim!",--What the hell! Keep 'em off of me!
	mch_brn_08_01b = "Puta merda, é que nem um campo de guerra aqui! Vou ficar aqui por um tempo e vocês vão fazer o que devem. Encontrem as partes e me tragam elas.",--Holy shit, it's like a god damn warzone out here! I'm gonna stay here while you go around and do whatever you do. Find the parts and bring them back here.
	mch_brn_06_02b = "Que porra é essa! Não fujam de mim!",--What the hell! Don't run away from me!
	mch_brn_04_01b = "Ah, cara, lá vem eles!",--O'boy, here they come!
	mch_brn_06_04b = "Que porra! Não me deixem aqui!",--What the fuck! Don't leave me here!
	mch_brn_12_03b = "Ei, se segurem. Peguem esse maçarico. Vocês vão precisar para entrar lá.",--Hey, hold your horses. Take this blowtorch. You're gonna need it to get inside.
	mch_brn_25_03b = "Joguem no caminhão, vamos cuidar disso depois!",--Throw it into the truck, we'll deal with it later!
	mch_brn_11_03b = "Quando montamos uma moto, os detalhes são importantes, baby. O que é mais foda do que uma caveira prateada do caralho? Eu estou certo ou não? Eu vi uma especial dentro da Casa do Clube. Vão pegar para mim.",--When building a custom bike, it's all about the details, baby. And what's more bad-ass than a chrome fucking skull? Am I right or am I right? I saw a special made one inside the clubhouse. Get it for me.
	mch_brn_06_07b = "Que diabos vocês estão fazendo? Não me deixem aqui!",--What the hell are you doin'? Don't leave me!
	mch_brn_22_01b = "Ei! Que porra é essa! Tire esse policiais de merda de perto!",--Hey! What the fuck! Get these fucking cops off my ass!
	mch_brn_10_01b = "Ok, então vamos precisar de um coração para esse bebê. Um motor. É isso que eu quero dizer. Acho que eles guardam eles dentro da Casa do Clube.",--Okay, so we're gonna need a heart for this baby. An engine. That's what I mean. I think they store them inside the clubhouse.
	mch_brn_21_03b = "Pronto! Me deem a próxima peça!",--Done! Get me the next piece!
	mch_brn_04_02b = "Porra, porra, porra! Tem mais deles!",--Fuck, fuck, fuck! There's more of 'em!
	mch_brn_08_02b = "Jesus Cristo, que porra está acontecendo? Todo essa merda é porque o Rust quer sua moto de volta? Bem, foda-se. Vocês vão e peguem as partes e me tragam aqui.",--Jesus Christ, what the fuck is going on here? All this shit just because Rust wants his bike back? Well, fuck it. You go and get the parts and bring them here.
	mch_brn_09_03b = "Certo, vou precisar das minhas ferramentas especiais para montar a moto. Eles devem estar no lugar de sempre na Oficina dentro das caixas de ferramentas.",--All right, I'm gonna need my special tools to put the bike together. They should be in their usual place in the workshop inside one of the toolboxes.
	mch_brn_07_02b = "Socorro!",--Help me!
	mch_brn_25_02b = "O que vocês tem aí? Quer saber, não ligo. Só joguem no caminhão que eu vou dirigir depois.",--What you got there? You know what, I really don't care. Just throw it in the truck and I'll take it with me as I drive off.
	mch_brn_07_07b = "Ei! Me protejam!",--Hey! Protect me!
	mch_brn_05_04b = "Porque eu me ofereci para consertar essa moto...",--Why did I offer to fix the bike...
	mch_brn_14_01b = "Certo, vou precisar de duas coisas: Um tanque de gasolina e alguns tubos de escape. Vão até a Oficina e encontrem o suspensor. É lá onde ficam as coisas. Me tragam os dois.",--All right, I'm gonna need two things: a gas tank and some exhaust pipes. Go into the workshop and find a ceiling lift. That's where they store them. Get it down and bring both to me.
	mch_brn_22_06b = "Caralho, gente! Me deem cobertura!",--God dammit, people! Cover me!
	mch_brn_23_02b = "Mãezinha querida, por favor me deixe viver mais um dia... eu sou um bom garoto, não sou?",--Sweet Mother Mary, please let me live another day... I'm a good boy, aren't I?
	mch_brn_05_02b = "Mas que merda foi essa que eu me meti...",--What the hell have I gotten myself into...
	mch_brn_18_03b = "Certo, tudo certo. Peguei o que eu precisava. Me levem de volta ao caminhão para eu acabar logo com isso.",--All right, all right. I got what we needed. Take me back to the truck so I can finish this up.
	mch_brn_06_06b = "Que caralho! Voltem aqui!",--What the hell! Come back here!
	mch_brn_22_07b = "Cadê minha proteção?!",--Where's my god damn protection?!
	mch_brn_23_01b = "Jesus Cristo... essa passou perto.",--Jesus fucking Christ... That was too close.
	mch_brn_23_04b = "Puta merda... eu só quero que essa merda acabe...",--Holy shit... I just wanna get this crap over with...
	mch_brn_23_06b = "Perto demais... muito perto...",--Too fucking close... Too fucking close...
	mch_brn_04_03b = "Merda, lá vem eles!",--Shit on a stick, here they come!
	mch_brn_07_06b = "Ow! Me ajudem!",--Yo! Help!
	mch_brn_14_02b = "Ok, eu preciso de um tanque de gasolina e alguns tubos de escape. Tem um suspensor dentro da Oficina e é lá que os motoqueiros guardam as coisas. Peguem as coisas e tragam pra mim.",--Okay, I need a gas tank and some exhaust pipes. There's a ceiling lift inside the workshop and that's where the bikers store them. Get the stuff down and toss them to me.
	mch_brn_05_05b = "Ei! Que porra é essa!",--Hey! What the fuck!
	mch_brn_11_01b = "Rust vai me matar se eu esquecer dos detalhes, então preciso que vocês peguem uma linda Caveira Cromada dentro da Casa do Clube. Eu não faço coisas de qualquer jeito, e queremos o melhor pra esse bebê.",--Rust's gonna kill me if I miss the sexy details, so I need you to grab a beautiful chrome skull from inside the clubhouse. I don't do things half-assed, and we want the best for this baby.
	mch_brn_23_08b = "Todo mundo me atirando... que merda...",--Everybody fucking shooting at me... Bullshit...
	mch_brn_03_02b = "É, é, não me olhem assim. Não sou burro pra pensar que vocês vieram aqui só para me salvar. Eu conheço o Rust também, lembram? E sei que ele quer realmente esse bebê de volta. Bem, vocês vão precisar pegar algumas partes se quiserem que isso aconteça.",--Yeah, yeah, don't give me that look. I'm not dumb enough to think you just came here to save my life. I know Rust too, remember? And I know he really wants his baby back. Well, you're gonna have to get me the parts if that's gonna happen.
	mch_brn_09_01b = "Ok, deixe eu pensar... O que precisamos? Ah, a Oficina. Sim. Vão para a Oficina, vocês vão encontrar as ferramentas especiais em umas caixas de ferramentas.",--Okay, let me think... What do we need? Ah, the workshop. Yes. Go to the workshop, you'll find the special tools in some toolboxes.
	mch_brn_05_06b = "Ah, merda!",--Oh, shit!
	mch_brn_03_01b = "Não digam nada. Eu sei que vocês não vieram aqui só para salvar a minha bunda. Rust ainda quer sua moto de volta, certo? Bem, para isso vou precisar de todas as partes, e elas estão por todo o lugar.",--Don't say a word. I'm well aware you're not only here to save my ass. Rust still wants his bike back, right? Well, to do that I'm gonna need all the parts, and they're spread all over the place.
	mch_brn_15_01b = "Porra, isso vai ser complicado... É, vocês não podem fazer por conta própria. Me levem até a garagem onde posso desmontar uma moto para coletar algumas merdas especiais para esse bebê.",--Fuck, this is gonna be tricky... Yeah, you can't do it yourselves. Take me to the garage where I can take a bike apart to collect some special shit for this babe.
	mch_brn_24_02b = "É isso senhoras e senhores. ESTÁ PRONTO. Agora, preciso meter o pé daqui!",--That's it ladies and gentlemen. IT. IS. DONE. Now, I need to get the fuck outta here!
	mch_brn_22_08b = "Não deixem eles chegarem perto de mim!",--Don't let 'em come this fucking close to me!
	mch_brn_07_05b = "Assim não, assim não!",--Not like this, not like this!
	mch_brn_16_01b = "Eu vou ser fuzilado se eu for sozinho, então vocês precisam me levar até a garagem. Eu não sei nada sobre vocês, mas eu quero que essa merda acabe logo.",--I'll get blasted if I go alone, so you need to take me to the garage. I don't know about y'all, but I want to get this shit done and over with. 
	mch_brn_24_01b = "E... acabou! Novinha em folha... adeus, querida... vou sentir sua falta... eu te amo.",--Aaaand it's done! Looks just like new... goodbye, darling... I'll miss ya... I love you.
	mch_brn_06_01b = "Ei! Não me deixem aqui!",--Hey! Don't leave me!
	mch_brn_24_03b = "Finalmente: Estamos prontos! Peguem a moto e deem o fora daqui. Não quero ficar um momento a mais se quer aqui!",--Fuck me back and forth: We are done! Take this bike and get the hell outta here. I'm not staying a moment longer!
	mch_brn_19_03b = "Não são apenas motos que precisam de líquidos para funcionar, sabe o que to falando? Não? Droga, só me tragam uma coca da máquina de vendas, ok?",--Not only bikes needs juice to get going, if you get what I'm sayin'? No? Dammit, just get me a coke from the vending machine, will ya?
	mch_brn_17_02b = "Tudo certo, estou aqui. Agora me cubram.",--All right, I'm here. Now cover me.
	mch_brn_17_03b = "Vocês vão me cobrir, certo?",--You guys got me covered, right?
	mch_brn_21_01b = "Ah, isso vai ser Fan-fucking-tástico! Me vejam a próxima parte!",--Oh, this is gonna be fan-fucking-tastic! Get me the next part!
	mch_brn_20_01b = "Eu não quero ser um cuzão, realmente não quero, mas a coca não vai vir aqui por conta própria, sabe?",--I don't want to be a douche, I really don't, but that coke ain't getting here itself, you know?
	mch_brn_02_02b = "Jesus... Porque isso tem que acontecer comigo? O que eu fiz para irritar esses merdinhas? Eu só vim aqui pegar a moto do Rust.",--Sweet Jesus . . . Why does this happen to me? What did I ever do to upset these shitbags? I was only here to get Rust's bike...
	mch_brn_02_03b = "Ahh, cara... eu achei que eu tava frito... Não posso dizer que esperava um bando de palhaços salvarem a minha bunda.",--Aw, man... I thought I was toast for sure... Can't say I expected a group of clowns to suddenly save my ass.
	mch_brn_03_03b = "Eh, vou dizer isso a vocês: Vocês não vieram aqui me salvar, né? Não, vocês vieram pela moto personalizada, eu estou certo ou não estou certo? Eu vou ajudar vocês. Eu devo a vocês tanto assim, mas vocês vão ter que me trazer as partes que preciso.",--Eh, I'll say it for you: you didn't come here only to save me, now did ya? No, you're here for the custom built bike, am I right or am I right? I'll help you. I owe you that much, but you'll have to get me the parts I need.
	mch_brn_07_03b = "Porra! Eu não quero morrer hoje!",--Fuck! I don't wanna die today!
	mch_brn_10_02b = "Tudo certo, vamos precisar de um motor para fazer esse bebê funcionar. Estou certo de que vi algum dentro da Casa do Clube.",--All right, we're gonna need an engine to get this baby going. I'm almost positive I saw them store some inside the clubhouse.
	mch_brn_12_02b = "Ah, é. Espere. Vocês vão precisar desse maçarico para entrar.",--Oh, yeah. Wait. You're gonna need this blowtorch to get inside.
	mch_brn_13_01b = "Ok, vamos precisar de um lindo assento para uma linda moto do Rust, né? Tem um Bunker velho no quintal. Vão ali e vocês vão encontrar o que precisamos.",--Okay, we're gonna need a fancy seat for Rust's fancy ass, don't we? There's an old Bunker in the backyard. Get in there and you'll find what we need.
	mch_brn_19_02b = "Ah! Quase esqueci! Eu preciso de mais um... ingrediente especial. É, certo. O mecânico precisa de uma coca da máquina de vendas. Bora, bora, porfavorzinho.",--Oh! I almost forgot! I need one more... special ingredient. Yeah, that's right. The mechanic needs a coke from the vending machine. Chop chop, pretty please.
	mch_brn_25_01b = "Oooh, roubando umas merdas, né? Gostei. Qualquer coisa que façam a vida desses motoqueiros fudidos um inferno. Coloquem isso no caminhão e vou levar comigo depois. Vamos deixar os detalhes para depois!",--Oooh, stealing some shit, are we? I like it. Anything to make these fucking bikers' lives miserable. Put it in the trunk and I'll take it with me as I drive off. We'll deal with the details later!
	
	-- Legendas (Bain - Dia 2)
	pln_chw_05_02 = "Procurem naquelas caixas. Não quero perder nenhuma chance nisso.",--Search those boxes. I'm not willing to take any chances on this one.
	pln_chw_15_03 = "Ouçam! A policia está trazendo muita gente para bloquear os trilhos a frente, então vocês realmente precisam ir. Tragam o BCI e voltem pro Bile!",--Listen up! The cops are bringing in a lot of people to block the tracks up ahead, so you really need to go. Bring the BCI tech and head back to Bile!
	pln_chw_03_01 = "Continuem em frente, gangue!",--Keep pushing forward, gang!
	pln_chw_20_01 = "Vocês vão ter que usar o maçarico para passar por isso. Sejam rápidos.",--You'll have to use the blowtorch to get through this gate. Make it quick.
	pln_chw_03_06 = "Continuem em frente!",--Keep going forward!
	pln_chw_02_02 = "De acordo com o Rust, o OVERKILL MC tem uma tecnologia em um dos carros da frente. Vão lá o mais rápido possivel e não parem. Não temos tanto tempo.",--According to Rust, the OVERKILL MC have the tech in one of the cars in the front. Get over there as fast as you can and don't stop. We don't have much time.
	pln_chw_07_02 = "Não deixem essa porta parar vocês. Eu quero que procurem nessas caixas.",--Don't let that gate stop you. I want those boxes searched.
	pln_chw_10_02 = "Vocês pegaram. Excelente. Hora de trazer o helicóptero. Bile está esperando, andem!",--You got it. Excellent. Time to bring it all to the helicopter. Bile's waiting, get going!
	pln_chw_14_01 = "Gangue! Fora daí! Que diabos vocês estão fazendo!?",--Gang! Get out of there! What the hell are you doing?
	pln_chw_03_04 = "Na frente do trem, gangue!",--The front of the train, gang!
	pln_chw_21_02 = "Droga, a porta deve estar trancada por fora. Talvez tenha outro jeito.",--Damn, the door must be locked from the outside. Maybe there's another way out.
	pln_chw_19_02 = "Droga! Esses barris estão no caminho. Vejam se vocês conseguem soltar as alças, sejam rápidos.",--Damn it! Those oil barrels are in the way. See if you can release the straps, and do it quickly.
	pln_chw_18_01 = "Trinta segundos, gangue! Vocês estão puxando isso!",--Thirty seconds, gang! You're pushing it!
	pln_chw_15_02 = "Ei! A policia está tentando parar o trem, peguem o BCI e deem o fora daí!",--Hey! The cops are gonna stop the train further down the tracks, so you need to get the BCI tech and get the hell out of there!
	pln_chw_09_03 = "Não fiquem parados! Abram a porta e peguem o BCI.",--Don't just stand around! Get the gate open and secure the BCI tech.
	pln_chw_02_03 = "O BCI é para estar nesse carro na frente do trem, esse é o lugar.",--The BCI tech is supposed to be in a car in the front of the train, so that's your destination.
	pln_chw_22_03 = "Jesus, aquela miserável não estava brincando, né? Peguem o cartão que ela largou.",--Jesus, that bastard wasn't playing around, was she? Take the keycard she dropped.
	pln_chw_17_03 = "Um minuto, gangue! Um minuto.",--One minute, gang! One minute.
	pln_chw_04_01 = "Se não tiver uma porta, façam uma. Usem o maçarico.",--If you don't have a door, you make one. Time to use the blowtorch.
	pln_chw_17_01 = "Droga, gangue! Vocês tem menos de um minuto agora!",--Damn it, gang! You have less than a minute now!
	pln_chw_15_01 = "Droga! A policia bloqueou os trilhos na frente. Peguem o BCI e corram de volta para o helicóptero.",--Damn! The cops have blocked the tracks up ahead, which means you need to be gone before you reach that point. Get the BCI tech and run back to the chopper!
	pln_chw_11_01 = "O que estão esperando? Voltem para o helicóptero e assegurem o loot!",--What are you waiting for? Run back to the helicopter and secure the loot!
	pln_chw_16_01 = "O trem está chegando na barricada da polícia. Vocês tem dois minutos para assegurar o loot.",--The train is rapidly approaching the cop barricade. I give you a maximum of two minutes to secure the loot and get out.
	pln_chw_12_01 = "Certo, o BCI está em mãos seguras agora. Vocês ainda tem a oportunidade de voltar e pegar mais loot. Tudo vale a pena.",--All right, the BCI tech is in safe hands now. You still have the opportunity to go back to the wagon and get more loot. It's all worth good cash.
	pln_chw_04_02 = "Usem o maçarico para criar um novo caminho.",--Use the blowtorch to create a way through that car.
	pln_chw_01_01 = "Ok, gangue. O Elefante lhes deu a informação, vocês já sabem o que fazer. Precisamos achar o Capacete BCI e o computador. Vocês conseguem isso e teremos muita grana.",--Okay, gang. Elephant gave you the briefing, so you know what we're after. We need to find the BCI headset and the computer software. You manage this, we'll make a lot of money.
	pln_chw_09_02 = "Vamos lá! Abram a porta logo e peguem o que viemos buscar!",--Come on! Open the gate already and get the stuff we came for.
	pln_chw_14_02 = "Hora de irmos! Vamos!",--Time to go! Come on!
	pln_chw_17_02 = "Pessoal! Vocês tem um minuto!",--Guys! You got one minute!
	pln_chw_03_05 = "Vão até a frente, pessoal. Vamos lá!",--Make your way to the front, guys. Come on!
	pln_chw_03_07 = "O carro que estamos procurando está na frente, gangue!",--The car we're after is in the front, gang!
	pln_chw_12_02 = "Excelente! Com a tecnologia BCI em nossas mãos, vocês tem tempo para pegar mais loot se quiserem para fazer ainda mais dinheiro.",--Excellent! With the BCI tech in safe possession, you have time to get more of the loot if you want to make some good money.
	pln_chw_01_03 = "O Elefante nos deu a informação sobre o BCI, certo? Nós vamos atrás do headset de alta tecnologia e o software que permite o usuário controlar um drone com o cérebro. Confiem em mim, eu não acredito também. De qualquer jeito, de acordo com o Rust, as duas coisas estão nesse trem. ",--The Elephant briefed you about the Brain-Computer Interface, right? We're after a high-tech headset and a software that allows you to control a drone using your brain. Trust me, I can barely believe it myself. Anyhow, according to Rust, both things are currently being transported on this train.
	pln_chw_06_01 = "Droga, eles colocaram C4 nas caixas! Desarmem elas!",--Damn, they rigged the boxes with C4! Defuse them! 
	pln_chw_20_03 = "Vocês tem um maçarico, não tem? Usem na porta.",--You got a blowtorch, don't you? Use it on that gate.
	pln_chw_11_02 = "Voltem pro helicóptero e assegurem o BCI!",--Get back to the helicopter and secure the BCI tech! 
	pln_chw_13_02 = "Bom trabalho. Mais dinheiro sempre é bom. Agora voltem ao helicóptero e saiam daí.",--Good job. More cash is always welcome. Now, run back to the helicopter and get out of there.
	pln_chw_13_03 = "Vocês limparam o lugar. Bom trabalho. Hora de dar o fora daí.",--You cleaned the place out. Good job. Time to get the hell out of there.
	pln_chw_16_03 = "Com a velocidade que esse trem está indo, vocês vão ter dois minutos antes de chegar na barricada. Isso significa dois minutos para assegurar tudo.",--With the speed this train is going, you'll have about two minutes before you reach the barricade. That means two minutes to secure everything and leave!
	pln_chw_22_02 = "Caralho! Não estava esperando aquilo. Vejam se ela tinha algo para a porta.",--Holy! Was not expecting that. See if she had something for the gate.
	pln_chw_07_03 = "Abram a porta e procurem pelas caixas.",--Get that gate open and search the boxes.
	pln_chw_11_03 = "Se apressem e voltem ao helicóptero para podermos assegurar o BCI.",--Hurry up and get back to the chopper so we can secure the BCI tech.
	pln_chw_13_01 = "Isso é tudo! Vamos fazer um bom dinheiro com essas coisas. Voltem ao helicóptero e saiam daí agora.",--That's all of it. We'll make some good money from all this fancy stuff. Head back to the chopper and get out of there now.
	pln_chw_01_02 = "Usando seu cérebro para controlar um drone? Jesus, eu to ficando velho mesmo. De qualquer jeito, essa tecnologia vale muito dinheiro, então precisamos roubar tudo.",--Using your brain to control a drone? Jesus, I'm getting old. Anyway, this technology is worth a lot of cash, so we need to steal it from these bikers.
	pln_chw_18_03 = "Trinta segundos, gente! Vão rápido!",--Thirty sec, guys! Hurry the hell up!
	pln_chw_05_01 = "Não quero perder nenhuma chance, gangue. Procurem nas caixas que vocês olharem. No pior caso vocês vão achar outras coisas valiosas.",--I'm not taking any chances, gang. Search any boxes you see. Worst case scenario is you find other valuables.
	pln_chw_22_01 = "Droga, eles realmente salvaram suas armas pesadas por último. E parece que ela tinha um cartão.",--Damn, they really saved their big guns for last. And it looks like she had a keycard.
	pln_chw_16_02 = "Vocês tem aproximadamente dois minutos antes do trem chegar na barricada. Me ouviram? Dois minutos",--You have approximately two minutes before the train reaches the barricade. You hear me? Two minutes.
	pln_chw_12_03 = "Eu prefiro que saiam antes que algo dê errado, mas entendo se quiserem ficar para pegar mais loot.",--I would prefer it if you just left before anything goes wrong, but I understand if you wanna go back to get more of the loot.
	pln_chw_10_01 = "Ok, vocês pegaram essa merda. Isso é o importante. Hora de trazer todos ao helicóptero. Mexam-se, o Bile está esperando.",--Okay, you got the stuff. That's the important thing. Time to bring it all to the helicopter. Get a move on, Bile's waiting.
	pln_chw_19_01 = "Aqueles barris estão bloqueando. Encontrem as alças e libertem eles. Não temos outra maneira.",--Those oil barrels are blocking your path. Find the straps and release them. We don't have time to find another way.
	pln_chw_18_02 = "Vocês tem trinta segundos para sair daí!",--You got thirty seconds to make it out of there!
	pln_chw_06_02 = "As caixas estão armadas com C4! Defusem elas rapidamente! ",--The boxes are rigged with C4! Defuse them quick!
	pln_chw_10_03 = "A tecnologia está em nossas mãos! Hora de voltar ao helicóptero! o Bile está esperando vocês.",--The tech is in our hands! Time to head back to the helicopter! Don't keep Bile waiting.
	pln_chw_08_01 = "Jackpot! A informação do Rust estava certa. Agora, passem pelas portas e peguem o Capacete BCI e o software.",--Jackpot! Rust's info was correct. Now, get through the gate and grab the BCI headset and the software.
	pln_chw_02_01 = "Rust me falou que os motoqueiros tem um carro na frente que tem as coisas que estamos procurando. Vão até lá e não parem por nada.",--Rust told me the bikers have one of the cars in the front where they guard the stuff we're after. Make your way there and don't let anything stop you.
	pln_chw_03_02 = "Vocês precisam ir para frente!",--You need to get to the front!
	pln_chw_03_03 = "Vão em frente e não parem!",--Go forward and don't stop!
	pln_chw_03_08 = "Precisamos colocar nossas mãos no BCI, gangue. Vão em frente!",--We need to get our hands on the BCI tech, gang. Go forward!
	pln_chw_04_03 = "Esse carro não tem uma porta. Então usem o maçarico para fazer uma.",--This car doesn't have a door, so you'll have to use a blowtorch to make one.
	pln_chw_05_03 = "Procurem todas as caixas que encontrarem. Não quero correr riscos de perder o BCI porque a informação do Rust estava errada.",--Search all boxes you find. I won't risk missing the BCI tech because Rust's information was wrong.
	pln_chw_06_03 = "Caralho...! Eles colocaram C4 nas caixas! Defusem!",--Holy...! They rigged the boxes with C4! Defuse them!
	pln_chw_07_01 = "Não quero perder essa chance com essas caixas. Procurem nelas.",--I'm not taking any chances with these boxes. Search 'em.
	pln_chw_08_02 = "Ali está! Passem pela porta e peguem o Capacete BCI e o software.",--There it is! Get through the gate and secure both the BCI headset and the software.
	pln_chw_08_03 = "Ah, é, ali está. Abram a porta e peguem o Capacete BCI e o software.",--Oh yeah, there it is. Get the gate open and secure the BCI headset and the software.
	pln_chw_09_01 = "O que estão esperando? Passem pela porta!",--What are you waiting for? Get through that gate!
	pln_chw_14_03 = "Eu disse que é hora de irmos!",--I said it's time to go!
	pln_chw_19_03 = "Vocês precisam remover os barris, e rápido. Liberem as alças.",--You'll need to remove those barrels, and you need to do it fast. Just release the straps or something.
	pln_chw_20_02 = "Usem o maçarico para passar pela porta!",--Use the blowtorch to get through the gate!
	pln_chw_21_01 = "A porta está trancada. Vejam se conseguem encontrar outra maneira.",--The door's locked. See if you can find another way out so we can keep going forward.
	pln_chw_21_03 = "A porta parece trancada por fora. Vejam se conseguem achar outra maneira de passar.",--The door appears to be locked from the outside. Look around and see if you can find another way to get out.
	
	-- Legendas (Outros - Dia 2)
	plt_chw_intro_01 = "Certo Cowboys, Vou largar vocês aqui, e vou circular pela área até vocês me chamarem para pegar o loot.",--All right Cowboys, I'm dropping you off here, and I'll circle around until you call me back to pick up the goods.
	plt_chw_intro_02 = "Isso parece algo de um filme de cowboy e o Bile gosta disso, Cavalheiros! De qualquer jeito, aqui é onde deixo vocês. Vou esperar até vocês me darem o sinal para voltar e pegar o loot.",--This feels like something out from a cowboy movie and Bile likes it, gentlemen! Anyhow, here's where I drop you off. I'll be on standby until you give me the signal to come back and pick up the loot.
	plt_chw_intro_03 = "Yihaaaa! Aqui estamos! Vou circular até vocês pegarem o que quiserem. Só me deem o sinal e eu volto para pegar o loot. Boa sorte!",--Yihaaaa! Here we are! I'll circle around until you get whatever you came for. Just give me the signal and I'll be back to pick the loot up. Good luck!
	plt_chw_01_02 = "Ei, pessoal, estou vindo por um pequeno período de tempo, então me tragam todo o loot que quiserem.",--Hey, guys, I'm coming in for a short period of time, so bring me any loot you want to secure.
	plt_chw_01_03 = "Vindo por trás, meus amigos mascarados. Vou ficar apenas por um pequeno período de tempo então me tragam tudo o que quiserem, e sejam rápidos.",--Coming in at the back, my masked friends. I'll only stay a short while so bring me anything you want to secure, and do it fast.
	plt_chw_01_01 = "Cavalheiros, eu achei uma abertura para que eu possa entrar por um curto período de tempo. Se tiverem algum loot para assegurar, agora é a hora. Vou estar atrás do trem.",--Gentlemen, I see an opening for me to come in a short period of time. If you have any loot to secure, now is the time. I'll be at the back of the train.
	plt_chw_02_01 = "Estou aqui. Me tragam o loot logo, porque não posso ficar por muito tempo.",--I'm here. Bring me the loot pronto, because I can't stay too long.
	plt_chw_02_02 = "Ei, estou aqui atrás. Se apressem e me tragam o loot que quiserem assegurar.",--Hey, I'm here in the back now. Hurry up and get me any loot you want secured.
	plt_chw_02_03 = "Ei, estou aqui atrás. Se apressem e me tragam o loot que quiserem assegurar.",--Hey, I'm here in the back now. Hurry up and get me any loot you want secured.
	
	-- Objetivos (Dia 1)
	hud_heist_born_01 = "Encontre uma maneira de passar pela entrada da Casa do Clube dos Motoqueiros.",--Find a way through the entrance into the Bikers clubhouse.
	hud_heist_born_03_hl = "Siga o Mecânico até o Caminhão",--Follow the mechanic to the truck
	hud_heist_born_06 = "O mecânico precisa de uma parte especial para a moto localizada dentro da garagem. Abra a garagem para abrir caminho ao mecânico. Escolte ele até o objetivo. Depois que ele pegar as partes, leve ele de volta ao caminhão.",--The mechanic needs a special part from a bike located inside the garage. Open the garage to make way for our friendly mechanic. Escort and guard him to the objective. Once he got his parts, get back to the truck with him.
	hud_heist_born_05 = "O mecânico quer que vocês coletem ferramentas específicas na Oficina. Procure pelas caixas de ferramentas e leve-as até ele.",--The mechanic wants you to collect specific tools from the workshop. Search through the toolboxes and bring it to him!
	hud_heist_born_12_hl = "Colete o Assento",--Collect the seat
	hud_heist_born_09 = "Tem caixas guardadas na Casa do Clube. Abra elas, procure por um motor e entregue ao mecânico!",--There are shipping crates stored in the clubhouse. Open them, search for an engine and deliver it to the mechanic!
	hud_heist_born_01_hl = "Entre na Casa do Clube",--Enter the clubhouse
	hud_heist_born_19 = "O mecânico está aguardardando você pegar seu equipamento!",--The mechanic waits for you to grab his equipment!
	hud_heist_born_18_hl = "Entregue as Partes",--Deliver the parts
	hud_heist_born_18 = "Jogue as partes que você encontrou no caminhão do mecânico!",--Throw the parts you've found into the mechanic's truck!
	hud_heist_born_13_hl = "Colete os Ingredientes Especiais",--Collect the special ingredient
	hud_heist_born_08_hl = "Colete a Caveira Cromada",--Collect the chrome skull
	hud_heist_born_19_hl = "Pegue o Equipamento do Mecânico",--Take the mechanics equipment
	hud_heist_born_12 = "Entre no Bunker localizado no quintal. Colete o assento e traga-o para o mecânico!",--Enter the Bunker located in the backyard. Collect the seat and bring it to the mechanic!
	hud_heist_born_14 = "Espere pelo mecânico terminar de montar a moto. Ele vai nos dizer o que fazer.",--Wait for the mechanic to complete assembling the bike part you collected for him. He will tell you what to do next.
	hud_heist_born_05_hl = "Colete as Ferramentas",--Collect the tools
	hud_heist_born_14_hl = "Defenda o Mecânico",--Defend the mechanic
	hud_heist_born_02_hl = "Liberte o Mecânico",--Untie the mechanic
	hud_heist_born_15_hl = "Colete mais Loot ou Pegue a Moto",--Collect more loot or take the bike
	hud_heist_born_02 = "Ajude o mecânico e liberte ele da fita!",--Help the mechanic and set him free off the tape!
	hud_heist_born_03 = "Escolte o mecânico até seu caminhão para que ele comece a montar a moto.",--Escort the mechanic to his truck so he can start assembling the bike
	hud_heist_born_09_hl = "Colete o Motor",--Collect the engine
	hud_heist_born_08 = "O mecânico precisa que vocês coletem uma Caveira Cromada no depósito da Casa do Clube. Um maçarico é necessário. Entre no depósito, pegue e devolva a ele.",--The mechanic requires you to collect a chrome skull from a storage room inside the clubhouse. You're gonna need a blowtorch from the mechanic. Get inside the storage room, grab it and deliver it to him!
	hud_heist_born_16 = "Fuja pela rota do canal, rápido!",--Escape through the canal route, quick!
	hud_heist_born_13 = "Pegue o refrigerante da máquina de vendas e entregue ao mecânico.",--Grab the soda from the vending machine and deliver it to the mechanic.
	hud_heist_born_06_hl = "Ajude o Mecânico a Coletar as Partes Especiais",--Help the mechanic collect special parts
	hud_heist_born_17_hl = "Entregue a Parte",--Deliver the part
	hud_heist_born_16_hl = "Fuja com a Moto do Rust",--Escape with Rust's bike
	hud_heist_born_11_hl = "Colete o Tanque e os Tubos de Escape",--Collect the tank and exhaust pipes
	hud_heist_born_17 = "Jogue a parte que você achou no caminhão do mecânico!",--Throw the part you've found into the mechanic's truck!
	hud_heist_born_11 = "Localize o suspensor dentro da Oficina. Plugue-o na tomada e ligue-o. Colete as duas partes e entregue ao mecânico!",--Locate a ceiling lift inside the workshop. Plug it into the outlet and turn it on. Collect both parts and deliver them to the mechanic!
	hud_heist_born_15 = "Procure pela área por mais loot e jogue-os no caminhão ou pegue a moto e fuja!",--Search the area for more loot and throw it into the van or take the bike and leave!
	
	-- Objetivos (Dia 2)
	hud_heist_chew_container_03_hl = "Sinalize ao Helicóptero",--Signal the helicopter
	hud_heist_chew_landing_01_hl = "Vá para a Área de Pouso",--Get to the landing area
	hud_heist_chew_train_03_hl = "Assegure o Capacete BCI",--Secure the BCI Helmet
	hud_heist_chew_landing_06_hl = "Fuga Disponível",--Escape available
	hud_heist_chew_container_04 = "Espere pelo helicóptero.",--Wait for the helicopter
	hud_heist_chew_landing_01 = "Vá para a Área de pouso.",--Get to the landing area
	hud_heist_chew_train_07 = "Espere até o Bain achar uma rota de fuga.",--Hold out until Bain finds an escape
	hud_heist_chew_train_04_hl = "Assegure mais Loot ou Fuja",--Secure more loot or escape
	hud_heist_chew_landing_06 = "Fuga disponível.",--Escape available
	hud_heist_chew_train_01_hl = "Vá para a Frente",--Get to the front
	hud_heist_chew_train_04 = "Se você quiser, pegue qualquer coisa de valor e jogue no helicóptero, ou fuja.",--If you want, grab anything of value and throw it into the helicopter, or escape.
	hud_heist_chew_container_06 = "Fuga disponível.",--Escape available
	hud_heist_chew_container_01_hl = "Encontre um Contêiner Vazio",--Find an empty container
	hud_heist_chew_train_02_hl = "Abra a Grade",--Open the gate
	hud_heist_chew_container_02 = "Assegure o loot no contêiner.",--Secure loot in the container
	hud_heist_chew_train_06 = "Entre no trem.",--Get out of the train
	hud_heist_chew_container_05 = "Prenda o contêiner.",--Attach the container
	hud_heist_chew_container_03 = "Sinalize para o helicóptero.",--Signal the helicopter
	hud_heist_chew_train_06_hl = "Saia do Trem",--Get out of the train
	hud_heist_chew_train_03 = "Assegure o Capacete BCI no helicóptero.",--Secure the BCI Helmet in the helicopter
	hud_heist_chew_landing_03 = "Sinalize para o helicóptero.",--Signal the helicopter
	hud_heist_chew_train_05 = "Nós temos tudo que precisamos. Saia agora.",--We have everything we came for. Get out of here now.
	hud_heist_chew_landing_05 = "Assegure o loot no helicóptero.",--Secure the loot in the helicopter
	hud_heist_chew_container_01 = "Encontre um contêiner vazio.",--Find an empty container
	hud_heist_chew_landing_02 = "Tire os obstáculos na área de pouso.",--Clear obstacles in the landing area
	hud_heist_chew_train_07_hl = "Espere até o Bain achar uma Fuga",--Hold out until Bain finds an escape
	hud_heist_chew_landing_02_hl = "Limpe os Obstáculos na Área de Pouso",--Clear obstacles in the landing area
	hud_heist_chew_train_01 = "Eles devem ter o BCI na frente do trem. Vá até lá.",--They should have the BCI in the front of the train. Make your way there!
	hud_heist_chew_container_04_hl = "Espere pelo Helicóptero",--Wait for the helicopter
	hud_heist_chew_container_06_hl = "Fuga Disponível",--Escape available
	hud_heist_chew_landing_05_hl = "Assegure o Loot no Helicóptero",--Secure the loot in the helicopter
	hud_heist_chew_container_05_hl = "Prenda o Contêiner",--Attach the container
	hud_heist_chew_train_02 = "Precisamos passar pela grade, o BCI está do outro lado.",--We need to get through that gate, the BCI is on the other side.
	hud_heist_chew_landing_04_hl = "Espere pelo Helicóptero",--Wait for the helicopter
	hud_heist_chew_container_02_hl = "Assegure o Loot no Contêiner",--Secure loot in the container
	hud_heist_chew_landing_03_hl = "Sinalize ao Helicóptero",--Signal the helicopter
	hud_heist_chew_landing_04 = "Espere pelo helicóptero.",--Wait for the helicopter
	hud_heist_chew_train_05_hl = "Fuja",--Escape
		}