return {
	-- Nomes e Descrições
	--heist_alex = "Rats",--Rats
	--heist_alex_2_hl = "Code for Meth",--Code for Meth
	--heist_alex_3_hl = "Bus Stop",--Bus Stop
	heist_alex_crimenet = "Ajude o Hector a eliminar os líderes Mendoza.$NL;$NL;» Obtenha Metanfetamina do Laboratório dos Mendoza$NL;» Troque a Metanfetamina por Informação com os Cobras$NL;» Elimine os Líderes do Cartel Mendoza",--Help Hector wipe out the Mendoza leaders.$NL;$NL;» Retrieve meth from the Mendoza lab$NL;» Trade meth for info with the Cobras$NL;» Eliminate the Mendoza cartel leaders
	heist_alex_1_briefing = "Bom, vocês ouviram o Hector. Sem tempo para enrolação. Entraremos no Laboratório de Metanfetamina e vamos assegurar as drogas. Tenho certeza de que não vai demorar para a polícia chegar, o que faz sentido devido à incrível má sorte que estamos tendo ultimamente.",--Well, you heard Hector. No time to piss around. We go into the meth lab and secure the goods. I'm sure we don't have long before the law shows, either, which is in keeping with this spectacular run of bad luck we've been having.
	heist_alex_2_briefing = "OK, galera, falei com o Hector. Os chefões Mendoza estão fugindo do país mas o Hector não está preparado para deixar eles fugirem. Ele quer saber para onde estão indo. Um traidor no meio deles vendeu a informação para a gangue de rua Cobras - uns merdas perversos que nem mesmo os caras do Hector negociam com eles. E é aí que vocês entram... troquem a metanfetamina pela informação.",--OK folks, I spoke to Hector. The Mendoza higher ups are fleeing the country but Hector isn't quite ready to let them leave. He wants to know where they're headed. A rat in their midst has sold them out to the Cobras street gang - vicious pricks that even Hector's people don't deal with. Which is where you come in... Trade the meth with them for the info.
	heist_alex_3_briefing = "Bom, parece que o FBI está escoltando os Mendozas para fora do país. Talvez eles tenham um acordo, talvez não. Francamente, não dou a mínima se eles estão de acordo ou não. Todos os caras estão no ônibus, com dinheiro e tudo. Peguem o dinheiro, eliminem os chefões dos Mendozas, e acabem com essa história. Iremos de helicóptero.",--Well, turns out the FBI are escorting the Mendozas out of the country. Maybe they have a deal, maybe they don't. Frankly, I don't give a crap whether they're renditioning them or whatever. All the heads are on that bus, money and all. Get the money, eliminate the Mendoza top guys, and end this story. We'll go in by chopper.

	-- Legendas (Dia 1)
	pln_rat_stage1_intro_a_01 = "Seguindo reto e depois à direita, vocês verão uma velha casa. Surpresa, surpresa, é a Central da Cozinha de metanfetamina.",--Straight ahead and to the right, you'll see an old two story house. Surprise, surprise, this is cook central. 
	pln_rat_stage1_intro_a_01b = "Entrem lá, salvem os cozinheiros do Hector e peguem as drogas antes de alguma coisa dar errado.",--Get in, save Hector's cooks and get the drugs out of there before anything else goes wrong.
	pln_rat_stage1_intro_a_02 = "É o Laboratório, isso se for possível chamar esse muquifo de Laboratório, logo à frente. Entrem e cuidado com os soldados dos Mendoza.",--The lab, if you can call an rundown dump like this a lab, is straight ahead. Get in and watch for Mendoza's soldiers. 
	pln_rat_stage1_intro_a_02b = "Ah sim, tirem a metanfetamina daí antes do FBI chegar - eles foram notificados, caso vocês tenham começado a se achar sortudos.",--Oh yeah, get the meth out before the FBI arrives - they've been tipped off, as if you weren't feeling lucky already.
	pln_rat_stage1_intro_a_03 = "O pessoal dos Mendoza estão em cena cozinhando - Mate-os e peguem a metanfetamina do Hector de volta. Vocês podem sair quando tiverem a parada. Vão lá.",--Mendoza's people are on the scene doing the cook - get them clear and reclaim Hector's meth. You can leave right here when you have the stuff. Go for it.
	pln_rat_stage1_intro_a_04 = "Cara, juro que consigo sentir o cheiro horrível daqui. Estamos no Laboratório de metanfetamina. Entrem e consigam três bolsas do produto antes do FBI chegar. O que o Hector quer, o Hector consegue. Por agora, pelo menos.",--Man, I swear I can smell that skel bait from here. We're at the meth lab. Go in and snag three sacks of the product before the FBI gets here. What Hector wants, Hector gets. For now, anyway.
	pln_rat_stage1_30_any_01 = "Bom trabalho. Quatro bolsas é o suficiente para a troca.",--Good job. Four bags is good enough to go and do the trade.
	pln_rat_stage1_13_any_01 = "SWAT a caminho pela Floresta perto da estrada, tomem cuidado!",--SWATs are incoming from the forest next to the road, be careful!
	pln_rat_stage1_04_any_01 = "Que?! O cartel Mendoza ainda está lá dentro! Cuidem deles!",--What!? The Mendoza cartel is still there! Take care of them!
	pln_rat_stage1_01_any_01 = "Entrem na casa e vejam se vocês conseguem achar os cozinheiros do Hector.",--Get into the house and see if you can find Hector's cooks.
	pln_rat_stage1_28_any_01 = "O processo está pronto! Ensacolem, e vamos cozinhar mais.",--The process is done! Bag it up, and lets do another round.
	pln_rat_stage1_end_a_01 = "Bom trabalho pegando a metanfetamina. Não foi exatamente fácil. Tenho certeza de quem dedurou a localização do Laboratório vai ter a atenção do Hector.",--Good work getting the meth out. That was not exactly an easy gig. I'm sure whoever ratted out the lab is going to get Hector's full attention. 
	pln_rat_stage1_31_any_01 = "Incrível! Com tudo isso de bolsas, a troca vai ser tranquila.",--Awesome! With all those bags, the trade should be smooth.
	pln_rat_stage1_end_c_02 = "Estamos sem o produto então é melhor o Hector não saber. Talvez podemos resolver o problema de outro jeito.",--We're short on product so for now I think we're best keeping Hector in the dark. Maybe we can solve the issue another way. 
	pln_rat_stage1_13_any_02 = "Eles estão vindo da Floresta perto da estrada! Mantenha-os longe!",--They are coming in from the forest next to the road! Keep them away!
	pln_rat_stage1_21_any_01 = "Vocês precisam adicionar a Soda Cáustica para continuar o processo!",--You need to add the caustic soda to keep the process going!
	pln_rat_stage1_15_any_02 = "Bom trabalho! Voltem a cozinhar. Usem a pausa entre os assaltos para achar mais ingredientes.",--Good work! Get back to the cooking. Use the time between waves to find more ingredients.
	pln_rat_stage1_02_any_01 = "Entrem na casa.",--Get into the house.
	pln_rat_stage1_05_any_01 = "Tenham certeza de que ninguém mais está lá.",--Make sure no one else is there.
	pln_rat_stage1_25_any_01 = "Bom, está em continuação. Fiquem de olho, e continuem defendendo...",--Good, it's continuing. Keep an eye out, and keep defending...
	pln_rat_stage1_06_any_01 = "Parece que os cozinheiros do Hector morreram. Vamos ter que cozinhar a metanfetamina nós mesmos!",--Looks like Hector's cooks are dead. We have to make the meth ourselves!
	pln_rat_stage1_end_c_01 = "Droga. Não temos o suficiente para a troca, entramos numa roubada. Vamos manter o silêncio e ir até o Hector. Vamos ver o que acontece.",--Damn. We don't have enough product to trade, which means we're in a tough spot. Let's keep it quiet and go to Hector. We'll see how it goes.
	pln_rat_stage1_07_any_01 = "Precisamos nos apressar! O rádio da polícia está disparando loucamente. Eles já estão a caminho!",--We have to hurry! The cop's radio is buzzing like crazy. They're already on their way!
	pln_rat_stage1_09_any_01 = "Tenham certeza de que nenhum SWAT entre no Laboratório. Mantenha-os longe a qualquer custo!",--Make shure no SWATs get in to the lab. Keep them away at all costs!
	pln_rat_stage1_26_any_01 = "Wow! Pessoal? Vocês estão bem? Eu falei pra serem cuidadosos!",--Wow! Guys? Are you OK? I told you to be careful!
	pln_rat_stage1_12_any_01 = "Eles estão vindo da ponte da ferrovia! Tomem cuidado!",--They are coming from the railway bridge! Watch out!
	pln_rat_stage1_end_a_02 = "Essa casa está em chamas. Vamos levar o produto para o Hector e pegar o pagamento. Quanto será que ele cobra pelo cristal azul?",--That house is going up in flames. Let's get the product to Hector and get paid. I wonder how much he pays for the blue. 
	pln_rat_stage1_23_any_01 = "Vocês precisam adicionar o Cloreto de Hidrôgenio para continuar o processo!",--You need to add the hydrogen chloride to keep the process going!
	pln_rat_stage1_11_any_02 = "Estão vindo! Da madeireira! Tomem cuidado!",--Incoming! From the lumber mill! Stay on your toes!
	pln_rat_stage1_end_b_01 = "Vocês cozinham muito bem! Quem de vocês é o Heisenberg, o Hector quer saber.",--You guys can cook! Which one of you is Heisenberg, Hector wants to know.  
	pln_rat_stage1_11_any_03 = "Eles estão vindo da madeireira, fiquem de olho!",--They are coming in from the lumber mill, watch out!
	pln_rat_stage1_08_any_01 = "Certo, o processo está em andamento, está cozinhando. Tenho contato com um especialista pelo Hector. Vou guiar vocês.",--Alright, the process is on, It's cooking. I have a contact with a specialist through Hector. I will guide you guys through it.
	pln_rat_stage1_15_any_01 = "Vocês mantiveram eles longes. Bom trabalho! Mas eles não estão recuando, então preparem-se pra mais.",--You kept them away. Good stuff! They aren't backing though, so get ready for more of them.
	pln_rat_stage1_03_any_01 = "Lembrem-se que vamos precisar de pelo menos quatro bolsas de metanfetamina.",--Remember we will need at least four bags of meth.
	pln_rat_stage1_10_any_01 = "Lá vem eles galera. Helicópteros e vans da SWAT em volta do local. Tomem cuidado!",--Here they come guys. Choppers and SWAT vans all over the place around you. Stay on your toes!
	pln_rat_stage1_11_any_01 = "SWAT vindo pela madeireira. Mantenha-os longe!",--SWAT incoming from the lumber mill. Keep them away!
	pln_rat_stage1_12_any_02 = "A ponte da ferrovia! Eles estão vindo da ponte da ferrovia, mantenha-os longe.",--The rail way bridge! They are coming in from the railway bridge, keep them away.
	pln_rat_stage1_12_any_03 = "SWAT vindo da madeireira, mantenha-os longe!",--SWATs incoming from the lumber mill, keep them away!
	pln_rat_stage1_14_any_01 = "Tomem cuidado! Snipers a caminho.",--Be careful! They have snipers incoming!
	pln_rat_stage1_16_any_01 = "Vamos precisar dos ingredientes, procurem pelo lugar e vejam o que vocês conseguem encontrar.",--We are going to need ingredients, so scout the place and see what you can find.
	pln_rat_stage1_17_any_01 = "Vocês precisam adicionar um ingrediente. Tenham certeza de que vocês não vão colocar o errado. Um passo em falso e o Laboratório vai pegar fogo e iluminar tudo igual uma árvore de Natal.",--You need to add an ingredient, make sure you don't use the wrong thing. One wrong step and the lab will torch up like a christmas tree.
	pln_rat_stage1_18_any_01 = "Lembrem-se de serem cuidadosos! Não podemos usar o ingrediente errado. Vocês precisam ser cuidadosos!",--Remember to be careful! We can not use the wrong ingredient. You need to be careful!
	pln_rat_stage1_19_any_01 = "Vocês precisam adicionar o Ácido Muriático para continuar o processo!",--You need to add the muriatic acid to keep the process going!
	pln_rat_stage1_20_any_01 = "Adicionem Ácido Muriático, para continuar o processo!",--Add muriatic acid, to continue the process!
	pln_rat_stage1_22_any_01 = "Adicionem Soda Cáustica, para continuar o processo!",--Add caustic soda, to continue the process!
	pln_rat_stage1_24_any_01 = "Adicionem Cloreto de Hidrogênio, para continuar o processo!",--Add hydrogen chloride, to continue the process!
	pln_rat_stage1_26_any_02 = "Ah, quê?! Pessoal, vocês tem que ser cuidadosos com essa parada, eu avisei!",--Ah, what!? Guys, you have to be careful with that stuff, I told you!
	pln_rat_stage1_27_any_01 = "Não podemos mais usar o Laboratório, já era. Peguem o que vocês já fizeram e vamos embora.",--We can't use the lab any more, it's gone, take what you have and lets leave.
	pln_rat_stage1_29_any_01 = "Levem as bolsas para a van para assegurá-las. Não deixem os policiais fugirem com a metanfetamina.",--Get the bags to the van to secure them. Don't let the cops run away with your hard earned meth!
	pln_rat_stage1_32_any_01 = "Pessoal, são menos bolsas do que esperávamos, mas ainda podemos fazer a troca com a esperença de que eles nos darão a informação.",--Guys, it's fewer bags than we expected, but we can still do the trade and hope they agree to give us the information.
	pln_rat_stage1_33_any_01 = "Nenhuma bolsa?! A troca não vai ser boa pra gente. Espero que vocês tenham um truque na manga.",--No bags!? The trade will not be good to us. Hope you guys has some tricks up your sleeve for the trade.
	pln_rat_stage1_34_any_01 = "Bem pensado! Usem as tábuas para barricar mais janelas.",--Good thinking! Use those boards to barricade more windows.
	pln_rat_stage1_end_a_03 = "Se não aguenta, não desce pro play ein? Bom trabalho. Temos o bastante de metanfetamina para o acordo com o Hector. Vamos voltar para lá.",--If you can't stand the heat get out of the kitchen eh? Well done. We got enough meth to deal with Hector. Let's get back in town. 
	pln_rat_stage1_end_b_02 = "Minha gangue, todos mestres químicos. Vocês tiraram tanto produto que poderíamos todos fazer isso o tempo inteiro, ao estilo Breaking Bad.",--My crew, all master chefs. You got so much product out of that cook we should all break bad and do this full time!
	pln_rat_stage1_end_b_03 = "O acordo é nosso. Vocês fizeram cristal o suficiente para agradar a realeza. O Hector vai beijar nosso rabo com todo esse cristal que ele vai ficar doidão. Bom trabalho.",--Deal's on, people. You made enough crystal to make royalty blush. Hector's going to be singing your praises if he isn't high as a kite. Well done.
	pln_rat_stage1_end_c_03 = "Viemos sem muitas bolsas. Deixar rolar naturalmente e tentar resolver o problema do traidor de outro jeito. Temos uma boa imaginação.",--We came up a little short. Let's just play along and try to solve the Rat problem for Hector another way. We're inventive...
	pln_rats_stage1_32_any_01 = "Galera, são menos bolsas do que esperávamos, mas ainda podemos fazer a troca e esperar que eles aceitem nos dar a informação do traidor.",--Guys, it's fewer bags than we expected, but we can still do the trade and hope they agree to give us the information.
	pln_rats_stage1_27_any_01 = "Não podemos mais usar o Laboratório, já era. Peguem o que vocês já fizeram e vamos embora.",--We can't use the lab anymore, it's gone. Take what you have and let's leave.
	pln_rats_stage1_21_any_01 = "Vocês precisam adicionar Soda Cáustica para continuar o processo!",--You need to add the caustic soda to keep the process going!
	pln_rats_stage1_09_any_01 = "Tenham certeza de que nenhum SWAT entre no Laboratório. Mantenha-os longe a qualquer custo!",--Make shure no SWATs get in to the lab. Keep them away at all costs!
	pln_rats_stage1_06_any_01 = "Parece que os cozinheiros do Hector estão mortos. Nós que teremos que cozinhar!",--Looks like Hector's cooks are dead. We have to make the meth ourselves!
	pln_rats_stage1_31_any_01 = "Caraca! Com todas essas bolsas, a troca vai ser suave.",--Awesome! With all those bags, the trade should be smooth.
	pln_rats_stage1_03_any_01 = "Lembrem-se, precisamos de pelo menos quatro bolsas de metanfetamina.",--Remember we will need at least four bags of meth.
	pln_rats_stage1_04_any_01 = "Quê?! O cartel Mendoza ainda está lá dentro! Tomem cuidado!",--What!? The Mendoza cartel is still there! Take care of them!
	pln_rats_stage1_22_any_01 = "Adicionem Soda Cáustica para continuar o processo!",--Add caustic soda to continue the process!
	pln_rats_stage1_17_any_01 = "Vocês precisam adicionar um ingrediente, tenham certeza de que não usam o errado. Um passo em falso e o Laboratório vai se iluminar como uma árvore de Natal.",--You need to add an ingredient, make sure you don't use the wrong thing. One wrong step and the lab will torch up like a christmas tree.
	pln_rats_stage1_01_any_01 = "Entrem na casa e veja se você consegue encontar os cozinheiros do Hector.",--Get into the house and see if you can find Hector's cooks.
	pln_rats_stage1_02_any_01 = "Entrem na casa.",--Get into the house.
	pln_rats_stage1_05_any_01 = "Tenham certeza de que ninguém mais está lá.",--Make sure no one else is there.
	pln_rats_stage1_08_any_01 = "Certo, o processo está ligado, está cozinhando. Tenho um contato com um especialista através do Hector. Eu vou guiar vocês, pessoal.",--Alright, the process is on, it's cooking. I have a contact with a specialist through Hector. I will guide you guys through it.
	pln_rats_stage1_15_any_01 = "Você os manteve afastados. Coisa boa! Mas eles não estão voltando, então se preparem para mais deles.",--You kept them away. Good stuff! They aren't backing though, so get ready for more of them.
	pln_rats_stage1_15_any_02 = "Bom trabalho! Voltem para a cozinha. Usem o tempo entre as ondas para encontrar mais ingredientes.",--Good work! Get back to the cooking. Use the time between waves to find more ingredients.
	pln_rats_stage1_19_any_01 = "Vocês precisam adicionar o Ácido Muriático para manter o processo funcionando!",--You need to add the muriatic acid to keep the process going!
	pln_rats_stage1_20_any_01 = "Adicionem Ácido Muriático para continuar o processo!",--Add muriatic acid, to continue the process!
	pln_rats_stage1_23_any_01 = "Vocês precisam adicionar o Cloreto de Hidrogênio para manter o processo funcionando!",--You need to add the hydrogen chloride to keep the process going!
	pln_rats_stage1_24_any_01 = "Adicionem Cloreto de Hidrogênio para continuar o processo!",--Add hydrogen chloride to continue the process!
	pln_rats_stage1_25_any_01 = "Bom, está continuando. Fiquem atentos e continuem defendendo...",--Good, it's continuing. Keep an eye out, and keep defending...
	pln_rats_stage1_26_any_01 = "Uau! Pessoal? Vocês estão bem? Eu disse para tomarem cuidado!",--Wow! Guys? Are you OK? I told you to be careful!
	pln_rats_stage1_30_any_01 = "Bom trabalho. Quatro bolsas é bom o suficiente para ir e fazer essa troca.",--Good job. Four bags is good enough to go and do the trade.
	pln_rats_stage1_33_any_01 = "Sem bolsas!? A troca não será boa para nós. Espero que vocês tenham alguns truques na manga para a troca.",--No bags!? The trade will not be good to us. Hope you guys has some tricks up your sleeve for the trade.
	pln_rats_stage1_34_any_01 = "Bem pensado! Usem essas tábuas para bloquear mais janelas.",--Good thinking! Use those boards to barricade more windows.
	pln_rt1_05_any_01 = "Entrem na casa e vejam se conseguem encontrar os cozinheiros do Hector.",--Get into the house and see if you can find Hector's cooks.
	pln_rt1_03_any_02 = "Nós temos companhia! Os Mendozas provavelmente estão por aqui.",--We got company! The Mendozas' probably here.
	pln_rt1_05_any_02 = "Entrem - Precisamos cozinhar.",--Get inside - we need those cooks.
	pln_rt1_10_any_02 = "Os cozinheiros do Hector estão mortos. Nós teremos que cozinhar nós mesmos... OK...",--Hectors cooks are dead. We need to do the cooking ourselves... OK...
	pln_rt1_09_any_01 = "Certifiquem-se de que não há mais ninguém lá.",--Make sure noone else is there.
	pln_rt1_10_any_01 = "Então... Se os cozinheiros estão mortos... Então nós... Precisamos cozinhar nós mesmos.",--So... If the cooks are dead... Then we... Need to do the cooking ourselves.
	pln_rt1_15_any_02 = "Varanda - Agora!",--Balcony - now!
	pln_rt1_08_any_01 = "Puta merda! Alguém chegou aqui primeiro... Cuidado...",--Goddammit! Someone got here first... Careful...
	pln_rt1_08_any_02 = "Cuidado! Esses caras ainda não foram embora, peguem eles!",--Watch out! Their guys haven't left yet, waste 'em!
	pln_rt1_09_any_02 = "Verifiquem o lugar da concorrência.",--Check that place for the competition.
	pln_rt1_14_any_01 = "Eles estão entrando no prédio!",--They are climbing into the building!
	pln_rt1_25_07 = "É isso o que você ganha ao confiar na Internet, eu acho.",--That's what you get for trusting the internet, I guess.
	pln_rt1_25_18 = "É, meu pressentimento me disse que não era o ingrediente certo...",--Yeah my gut feeling told me that wasn't the right ingredient...
	pln_rt1_22_any_04 = "Soda Cáustica - Sim, é isso. Vá em frente.",--Caustic soda - yep, thats it. Go for it.
	pln_rt1_02_any_02 = "Temos que ligar essas luzes de volta. Façam isso!",--We gotta turn those lights back. Get on it!
	pln_rt1_20_any_04 = "Mu... Ácido Muriático - precisamos de um pouco disso.",--Mu... Muriatic acid - we need some more in there.
	pln_rt1_25_02 = "Eu realmente deveria ler a respeito dessas coisas, não deveria?",--I should really read up on this stuff, shouldn't I?
	pln_rt1_13_any_03 = "Eles estão invadindo a casa!",--They're breaching the house!
	pln_rt1_22_any_06 = "Eu apenas estou supondo que nesse ponto... Essas descrições da internet são duvidosas.",--I'm just guessing at this point... These internet descriptions are iffy.
	pln_rt1_24_any_02 = "Cloreto Cáustico. Diz aqui que é uma forma sólida... Espere... Deve ser aquele Hidrogênio, certo?",--Caustic chloride. Says it is some solid form... Wait a... Should be that hydrogen, right?
	pln_rt1_25_13 = "Vocês ouviram esse barulhão? pessoal?",--Did you hear that loud bang? Guys?
	pln_rt1_13_any_02 = "Eles já estão dentro!",--They're inside!
	pln_rt1_15_any_03 = "SWAT, SWAT na varanda!",--SWAT, SWAT on the balcony!
	pln_rt1_07_any_02 = "Pessoal, três bolsas já devem ser o suficiente para a troca.",--Guys, three bags should be enough to do the trade.
	pln_rt1_07_any_01 = "Lembrem-se de que iremos precisar de pelo menos 3 bolsas de metanfetamina.",--Remember we will need at least 3 bags of meth.
	pln_rt1_25_09 = "Woops. Essa é por minha conta, presumo.",--Woops. That one's on me I assume.
	pln_rt1_25_20 = "Acontece que, nós somos realmente bons em fazer algumas bombas...",--Turns out, we're really good at making bombs...
	pln_rt1_25_12 = "Woah, mas que azar.",--Woah, that's a whammy.
	pln_rt1_24_any_09 = "Vá pro caralho, nós precisávamos desses cozinheiros de merda. Eu iria com Soda Cáustica.",--Fuck me, we needed those damn cooks. I'm going with caustic soda.
	pln_rt1_24_any_06 = "Precisa de Cloreto de Hidrogênio, certeza... Não, não espere... Yeah, OK.",--It needs hydrogen chloride, for sure... No, no wait... Yeah, OK.
	pln_rt1_20_any_06 = "Ácido, pessoal, ácido. Peguem um pouco e coloquem aí.",--Acid, guys, acid. Get some and pour it in there.
	pln_rt1_22_any_05 = "Cloreto Cáustico. Diz aqui que é uma forma líquida... Espere um minuto... Deve ser Soda, não é?",--Caustic chloride. Says it is liquid form... Wait a minute... Should be soda, right ?
	pln_rt1_11_any_02 = "Continuem cozinhando, gente.",--Keep cooking people. Tempo!
	pln_rt1_24_any_08 = "Vá pro caralho, nós precisávamos desses cozinheiros. Eu iria com Cloreto.",--Fuck me, we needed those cooks. I'm going with chloride.
	pln_rt1_22_any_03 = "A reação Cáustica básica foi acrescentada. OK, vocês tem alguma Soda por aí? Adicionem ela.",--Caustic basic reaction is now added. OK you got any soda around? Add it.
	pln_rt1_25_21 = "Esperem pessoal, eu acho que estou confundindo esses números de registro CAS. ...pessoal?",--Wait guys, I think I'm confusing these CAS registry numbers. ...guys?
	pln_rt1_24_any_03 = "Hidrogênio... Isso é um gás... Não pode ser sólido... diz para adicioná-lo. Vocês possuem aí um tanque de gás, pessoal?",--Hydrogen... Is that a gas... Can't be a solid... Says add it. You guys got a gas tank?
	pln_rt1_02_any_01 = "Religuem essa luz de volta ou a coisa vai ficar bem feia num piscar de olhos.",--Get that power back or this turns ugly in a flash.
	pln_rt1_13_any_01 = "Eles estão dentro da casa!",--They're in the house!
	pln_rt1_14_any_02 = "Os policiais estão escalando no lado de fora. Vão para as janelas!",--Cops climbing the outside. Get to the windows!
	pln_rt1_15_any_01 = "Eles estão vindo da varanda!",--They are coming up on the balcony!
	pln_rt1_20_any_02 = "Ah, OK... Muri, Ácido Muriático. Coloquem.",--Ah, OK... Muria, muriatic acid. Add more.
	pln_rt1_20_any_03 = "OK, adicionem Cáustica... Não, esperem, adicionem Ácido - Ácido Muriático.",--OK, so add caustic... No, wait, add acid - muriatic acid.
	pln_rt1_20_any_05 = "Vocês estão cozinhando bem - mas precisa de um pouco mais de ácido.",--Cooking away fine - needs more acid though.
	pln_rt1_20_any_07 = "Olhando nesse site... está dizendo que o Ácido é o próximo... Nós temos Ácido Muriático, certo?",--Looking at this site... Says acid is used in this step... We got muriatic, right?
	pln_rt1_20_any_08 = "Hm, sim.. não é Soda Cáustica... É, deve ser Ácido. Claro, certeza que é isso.",--Hm, yeah it is not caustic soda... Yeah. It should be acid. Yep, sure that is it.
	pln_rt1_20_any_09 = "Tenho 100% de certeza de que é Ácido Muriático agora. Apenas adicionem.",--I'm 100% it is muriatic acid now. Just add it.
	pln_rt1_22_any_02 = "Aqui ta dizendo que precisa de Soda pra aumentar um pouco mais a temperatura... estranho. O que vocês pegaram?",--Says we need club soda to get this temperature up... Sounds odd. What can you get?
	pln_rt1_22_any_07 = "Tentem Soda Cáustica... Ou Hidrogênio... Não não, esperem, Soda... Acho que é isso.",--Try caustic soda... Or hydrogen... No no, wait, soda... Go for that. Yeah.
	pln_rt1_22_any_08 = "Precisa de Cloreto de Hidrogênio, certeza... OK esperem, Soda... Sim, é Soda Cáustica!",--It needs hydrogen chloride, for sure... OK wait, soda... Yeah, caustic soda!
	pln_rt1_22_any_09 = "100% de certeza que é Soda Cáustica pra incluir agora. Coloquem um pouco.",--I'm 100% it is some caustic soda needed here. Drop some in.
	pln_rt1_24_any_04 = "Esse site está dizendo algo... Uma mistura de Cloreto de Hidrogênio com Soda. Eu não sei, coloquem aí - alguma coisa.",--This site says something else... Chloride soda hydrogen mix. I don't know, go for it - something.
	pln_rt1_24_any_05 = "Precisamos de Cloreto de Hidrogênio - Certeza.",--It needs hydrogen chloride - for sure.
	pln_rt1_24_any_07 = "Vá pro caralho, nós precisávamos desses cozinheiros. Eu iria com Hidrogênio.",--Fuck me, we needed those cooks. I'm going with hydrogen.
	pln_rt1_24_any_10 = "Não tenho 100% de certeza mas eu acho que é Cloreto de Hidrogênio agora. Sim, deve ser.",--I'm not 100% but I think it is hydrogen chloride now. Yep, should be.
	pln_rt1_25_03 = "Eu acho que não é isso.",--I guess that wasn't it.
	pln_rt1_25_04 = "Negativo. Não, não está certo...",--Nope. No, that wasn't right...
	pln_rt1_25_06 = "Oh, esse não era o ingrediente certo afinal.",--Oh, that wasn't the right ingredient after all.
	pln_rt1_25_08 = "Woah. Quais são as alternativas? Talvez elas não são tão boas...",--Woah. What are the odds? Yeah maybe they weren't that good...
	pln_rt1_25_10 = "De vez enquando não confiem no que eu digo, pessoal.",--Every now and then, just don't trust me, guys.
	pln_rt1_25_11 = "Nah, não.. não está certo...",--Nah, no... that wasn't right...
	pln_rt1_25_14 = "Morto por metanfetamina...",--Death by meth...
	pln_rt1_25_15 = "Então Ácido Clorídrico era a mesma coisa... huh, você realmente aprende algo novo todo dia.",--So hydrochloric acid was the same thing... huh, you learn something new every day.
	pln_rt1_25_16 = "Então Hidróxido de Sódio era a mesma coisa... huh, você realmente aprende algo novo todo dia.",--So sodium hydroxide was the same thing... huh, you learn something new every day.
	pln_rt1_25_17 = "Merda.. Mas que.. merda.",--Shit. Just... shit.
	pln_rt1_25_19 = "Eu tenho a sensação de que é a coisa errada...",--I had a feeling that was the wrong stuff...
	
	-- Legendas (Dia 2)
	pln_rat_stage2_intro_a_01 = "Ok, lembrem-se, isso deve permanecer pacífico. Troquem a metanfetamina pela informação, e a metanfetamina excedente por dinheiro. Fácil e limpo, vão embora sem derramar sangue.",--OK, remember, this should stay peaceful. Trade the meth for the info, surplus meth for cash. Easy and clean, walk away without bloodshed.
	pln_rat_stage2_intro_a_02 = "Os Mendozas estão prestes a partir em um avião a jato. Precisamos trocar esse produto por infomações deles. Esses caras são uma escória, mas vocês não querem mexer com eles.",--The Mendozas are about to leave on a jet plane. We need to trade this product for info on them. These guys are scum, but you don't wanna mess with them.
	pln_rat_stage2_intro_a_03 = "A informação que eles têm estarão em uma pasta ou algo parecido. Façam a troca e peça que lhe entreguem as informações. Esses caras são a escória, então mantenham os olhos bem abertos.",--The info they have will be in a briefcase or something like that. Make the trade and have them hand over the info to you. These guys are scum so keep your eyes open.
	pln_rat_stage2_intro_a_01b = "Precisamos alcançar os Mendozas antes que eles deixem esse país.",--We need to catch up with the Mendozas before they jet out of this country.
	pln_rat_stage2_intro_a_02b = "Apenas tentem manter isso na calça dessa vez e façam a troca quietos. OK? OK.",--Just try to keep it in your pants this once and do the trade quiet. OK? OK.
	pln_rat_stage2_intro_a_03b = "Vamos acabar logo com isso e, com sorte, sem derramamento de sangue. Temos o suficiente disso pela frente.",--Let's just get it over with and hopefully without bloodshed. We have enough of that ahead of us.
	pln_rat_stage2_end_e_01 = "Isso é... muito dinheiro. Acho que estamos no mercado de metanfetamina agora. Mas nós realmente precisávamos dessa informação. Lembram? Preparem-se e vamos pegar esses merdas - com ou sem a informação.",--That's... A lot of money. I guess we're in the meth trade now. We really needed that information, though. Remember?  Saddle up and let's get those pricks - with or without the information.
	pln_rat_stage2_end_a_02b = "É. Então teremos um trabalho bem difícil...",--Yeah. So we have our work cut out for us...
	pln_rat_stage2_end_d_02 = "Sem dinheiro e sem informação. Eu chamaria isso aqui de fracasso. Hector vai ficar muito infeliz, a menos que vocês tirem minha bunda do fogo. Eu sei que é muito para pedir.",--No cash and no info. I'd call this one a miss. Hector's going to be very unhappy unless you guys pull my ass out of the fire. I know it's a lot to ask.
	pln_rat_stage2_end_c_01 = "Aqueles traidores... Bom, vocês mostraram para eles que a reviravolta normalmente é muito ruim para quem quer que seja contra nós.",--Those backstabbing... Well you showed them turnaround's generally very bad for whoever we turn around on.
	pln_rat_stage2_end_a_01 = "Isso foi fácil. Ótimo trabalho. Infelizmente o Hector acabou de me contar que o FBI prendeu os remanescentes dos Mendoza e estão escoltando eles até o aeroporto em um comboio. O que significa que nós não temos muito tempo.",--That was easy. Nice work. Unfortunately Hector just told me the FBI has nabbed the remaining Mendoza and are escorting them to the airport in a convoy. Which means we don't have much time.
	pln_rat_stage2_end_b_01 = "Pessoal... Pessoal... Pessoal. Nós deveríamos conseguir informações... Não apenas dinheiro. Hector vai me esfolar vivo.",--Guys... Guys... Guys. We were supposed to get info... Not just cash. Hector's going to skin me alive.
	pln_rat_stage2_end_b_01b = "Agora vocês precisam entrar às cegas e apenas tirar os Mendozas no caminho para o aeroporto, OK? Eu diria por favor, mas eu não digo isso.",--Now you need to go in blind and just take out the Mendozas on the way to the airport, OK? I'd say please but I don't say please.
	pln_rat_stage2_end_a_02 = "Eu acho que eles ligavam mais para a correção deles do que para a informação. Os viciados não são muito bons com abstração. Enquanto isso, os Mendozas estão saindo para o aeroporto em um ônibus alugado, escoltados pelo FBI disfarçado.",--I guess they cared more about their fix than information. Junkies aren't great with abstraction. Meanwhile the Mendozas are leaving for the airport in a rented bus, escorted by undercover FBI.
	pln_rat_stage2_end_c_01b = "Os Mendozas estão indo para o aeroporto. Tragam a pasta. Aposto que podemos descobrir alguma coisa para fazer com isso.",--Mendozas are headed for the airport. Bring that briefcase. I bet we can figure out something to do with it.
	pln_rat_stage2_end_d_01 = "Isso foi como em Bagdá de novo. Vocês precisam arrasar. Hector conseguiu uma pista dos Mendozas a caminho do aeroporto. Vamos atingir o comboio deles como um martelo de dez toneladas.",--That was like Baghdad all over again. You need to roll. Hector's got a line on the Mendozas on their way to the airport. We're gonna hit their convoy like a ten ton hammer.
	pln_rats_stage2_14_any_01 = "Malditos traidores! Façam eles se arrependerem da decisão e encontrem a informação! Procurem por cofres!",--Goddamn backstabbers! Make them regret the decision and find the information! Look for safes!
	pln_rats_stage2_13_any_01 = "Federais ou não, precisamos dessa informação! Vocês terão que procurar os apartamentos! Procurem por cofres!",--Feds or no feds, we need that intel! You'll have to search the apartments! Look for safes!
	pln_rats_stage2_03_any_01 = "Vão até o apartamento e peguem o que viemos buscar aqui.",--Go to the apartment and get what we came here for.
	pln_rats_stage2_04_any_01 = "Ok, temos o que precisamos. Hora de cair fora daqui.",--OK, we've got what we need. Time to get out of there.
	pln_rats_stage2_12_any_01 = "A polícia foi alertada e está se aproximando. Eles vão chegar a qualquer segundo.",--The police have been alerted and are closing in. They'll be there any second.
	pln_rats_stage2_06_any_01 = "Não há tempo a perder. Vão para a van!",--There's no time to waste. Get to the van!
	pln_rats_stage2_05_any_01 = "Ok, peguem a informação e mexam-se.",--OK, grab the intel and move.
	pln_rats_stage2_07_any_01 = "Parece que faremos isso do jeito difícil. Fiquem abaixados e procurem nesses apartamentos pela informação! Procurem por cofres!",--Looks like we'll be doing this the hard way. Stay low and search those apartments for the info! Look for safes!
	pln_rats_stage2_01_any_01 = "Os gangsters devem estar esperando logo à frente. Mantenham seus dedos fora do gatilho a menos que vocês queiram que isso vire uma bagunça. Fiquem de olho em qualquer coisa suspeita.",--The gangsters should be waiting up ahead. Keep your fingers off the triggers unless you want this to get messy. Keep your eyes open for anything suspicious.
	pln_rats_stage2_02_any_01 = "Ok, hora de dar a matanfetamina para eles.",--OK, time to give them the meth.
	pln_rats_stage2_08_any_01 = "Não podemos prosseguir com a troca sem a metanfetamina. Vocês terão que olhar nos apartamentos próximos e obter a informação por conta própria.",--We can't go through with the trade without the meth. You'll have to scout the nearby apartments and take the information yourselves.
	pln_rats_stage2_08_any_01b = "Mas cuidado. Se vocês forem pegos, eles provavelmente tentarão destruir a informação.",--Watch out though. If you get caught, they'll likely try to destroy the intel.
	pln_rats_stage2_09_any_01 = "Embora não trouxemos a quantidade de matanfetamina prometida, ainda podemos prosseguir com o acordo. Mas estejam preparados caso as coisas piorem.",--Although we didn't bring the amount of meth that we promised, we can still go ahead with the deal. But be prepared in case things go south.
	pln_rats_stage2_09_any_01b = "Eles provavelmente tentarão destruir as informações caso as coisas esquentem.",--They'll likely try to destroy the intel if things get heated.
	pln_rats_stage2_10_any_01 = "Rápido, eles podem destruir a informação antes que você tenham tempo de alcançá-la!",--Hurry, they might destroy the intelligence before you have time to reach it!
	pln_rats_stage2_11_any_01 = "Parece que eles queimaram a informação, iremos sair de mãos vazias!",--Looks like they burned the intelligence, we'll have to leave empty-handed!
	
	-- Legendas (Dia 3)
	pln_rat_stage3_intro_a_01 = "Grupo, somos nós terminando as operações dos Mendoza na capital aqui e agora. Atinjam aquele ônibus com força e peguem o dinheiro deles. Hector só quer acabar com esses palhaços para que o dinheiro seja nosso. Pousando em 3, 2, 1, vai!",--Crew, this is us ending Mendoza ops in DC right here and right now. Hit that bus hard and take their money. Hector just wants these clowns ended so the money is ours. Set down in 3, 2, 1, go!
	pln_rat_stage3_intro_a_02 = "Ok, o helicóptero está protegendo o comboio agora, estamos em uma ponte - muito bem Alex... Pela primeira vez... Acerte-os e acabem com isso. O dinheiro é nosso não importa o quê. Façam.",--OK, the chopper's coming over the convoy now, we're on a bridge - well done Alex... For once...  Hit 'em and finish it. The money's ours no matter what. Get it done.
	pln_rat_stage3_intro_a_03 = "Ok, o ônibus dos Mendoza está na ponte, o que significa que pousamos para pegá-lo em dez minutos. Acertem o ônibus, acabem com o pessoal deles e peguem o dinheiro. Simples.",--OK, the Mendoza bus is on the bridge, which means we land to take it out in ten minutes. Hit the bus, finish off their people, take the money. Simple.
	pln_rat_stage3_05_any_01 = "O dinheiro é nosso. Se vocês tiverem os códigos, poderão desarmar os explosivos plantados.",--The money is yours to take. If you have the codes you will be able to defuse the planted C4s.
	pln_rat_stage3_02_any_01 = "Lembrem-se, estamos atrás do traidor. Vão para o ônibus, mantenham as cabeças abaixadas e movam-se de cobertura para cobertura.",--Remember, we are after the rat, Head for the bus, keep your heads low and move from cover to cover.
	pln_rat_stage3_end_b_02 = "O churrasco dos Mendoza foi um tremendo sucesso. Hora de ver o Hector.",--The Mendoza BBQ was a roaring success. Time to see Hector.
	pln_rat_stage3_09_any_01 = "O helicóptero está aqui, joguem as bolsas no helicóptero.",--Chopper is there, throw the bags into the chopper.
	pln_rat_stage3_end_b_01 = "Ninguém vai perder essa mensagem. O FBI vão procurar vocês por toda parte. mas não se preocupem... Eu vou cuidar disso. Ótimo trabalho.",--No one is going to miss this message. The FBI's going to search high and low for you but don't worry... I'll take care of it. Great work.
	pln_rat_stage3_08_any_01 = "O ônibus explodiu! Tenham cuidado e fique fora do fogo!",--The bus blew up! Be careful and stay out of that fire!
	pln_rat_stage3_end_a_01 = "Vocês acabaram com aquele ônibus dos Mendozas. Um verdadeiro funeral Viking em chamas com seus pertences e tudo mais.",--You swept that bus clean of Mendozas. A true Viking funeral in flames with their possessions and all. 
	pln_rat_stage3_10_any_01 = "Bom trabalho, o traidor está morto, o helicóptero de fuga está esperando a menos que vocês queiram tentar ir atrás de dinheiro naquele ônibus, vão até o helicóptero e vamos tirar vocês daí.",--Good job, the rat is dead, escape helicopter is waiting, unless you want to try to go for the money in that bus, get to the chopper and we´ll get you the hell out of there.
	pln_rat_stage3_end_a_03 = "Dinheiro e Mendozas em chamas. Vocês fizeram uma declaração e Hector vai gostar disso. Dia de pagamento chegando.",--Money and Mendozas up in flames. You made a statement and Hector's going to like it. Payday coming up.
	pln_rat_stage3_03_any_01 = "Existem unidades pesadas do FBI por todo o lugar, tenham cuidado.",--There are Heavy FBI units all over the place, be careful.
	pln_rat_stage3_07_any_01 = "Tenham cuidado com os explosivos, pessoal.",--Be careful around that C4 guys.
	pln_rat_stage3_01_any_01 = "O comboio parou, andem em direção ao ônibus.",--The convoy's stopped, move toward the bus.
	pln_rat_stage3_04_any_01 = "É esse o ônibus, acabem com todos eles.",--That's the bus, take them all out.
	pln_rat_stage3_06_any_01 = "Estou enviando um helicóptero para vocês descarregarem o loot. Está perto daí, não deve demorar muito. Aguentem firme.",--I'm sending a chopper in for you guys to unload the loot. It's close by, shouldn't take too long. Stay tight.
	pln_rat_stage3_08_any_02 = "Ah não! Explodiu, cuidado! Fiquem fora do fogo!",--Oh no! It exploded, watch out! Stay out of that fire!
	pln_rat_stage3_11_any_01 = "Eu ouço a rádio polícial, os policiais estão a caminho, vão chegar em 30 segundos.",--I hear the cop radio, law enforcers are on the way, they arrive in 30 seconds.
	pln_rat_stage3_12_any_01 = "Policiais e a SWAT chegaram, tomem cuidado!",--Cops and SWATs have arrived, be careful!
	pln_rat_stage3_13_any_01 = "Cuidado com o helicóptero, está perto o suficiente para os policiais causarem um bom dano nele.",--Watch out for that chopper, it's close enough for the cops to do him some good damage.
	pln_rat_stage3_end_a_02 = "Sem mais Mendozas. Vocês deram a eles um verdadeiro funeral Viking, exceto que eles não são Vikings. Triste.",--No more Mendozas. You gave them a true Viking funeral, except they're not Vikings. Sad. 
	pln_rat_stage3_end_c_01 = "Ótimo trabalho, pessoal. Os Mendozas estão fora dos negócios e sua liquidez está aumentando em nosso helicóptero. Legal.",--Great job, people. The Mendozas are out of business and their liquidity is riding shotgun in our chopper. Sweet.
	pln_rat_stage3_end_c_02 = "É um alívio, vocês acertaram esse aqui. Qualquer má reputação que tivemos com o Hector está de boa agora. Me sinto relaxado o suficiente para fumar um cigarro da vitória, na verdade.",--That's a relief, you aced this one. Whatever bad rep we had with Hector is all good now. I feel relaxed enough to smoke a victory cigar, in fact.
	pln_rat_stage3_end_c_03 = "Ótima pontuação, pessoal. Vamos ver se Hector vai nos dar uma festa, está bem?",--Great score, folks. Let's see if Hector's going to throw us a party, shall we?
	pln_rats_stage3_05_any_01 = "O dinheiro é de vocês. Se vocês têm os códigos, poderão desarmar os explosivos plantados.",--The money is yours to take. If you have the codes you will be able to defuse the planted C4s.
	pln_rats_stage3_03_any_01 = "Tem unidades pesadas do FBI por todo o lugar, tenham cuidado.",--There are Heavy FBI units all over the place, be careful.
	pln_rats_stage3_01_any_01 = "O comboio parou, vão em direção ao ônibus.",--The convoy's stopped, move toward the bus.
	pln_rats_stage3_11_any_01 = "Eu ouço a rádio polícial, os policiais estão a caminho, vão chegar em 30 segundos.",--I hear the cop radio, law enforcers are on the way, they arrive in 30 seconds.
	pln_rats_stage3_02_any_01 = "Lembre-se, estamos atrás do traidor, vão para o ônibus, mantenham as cabeças abaixadas e movam-se de cobertura para cobertura. ",--Remember, we are after the rat, Head for the bus, keep your heads low and move from cover to cover.
	pln_rats_stage3_08_any_01 = "O ônibus explodiu! Tenham cuidado e fiquem fora do fogo!",--The bus blew up! Be careful and stay out of that fire!
	pln_rats_stage3_09_any_01 = "O helicóptero está aqui, jogue as bolsas no helicóptero.",--Chopper is there, throw the bags into the chopper.
	pln_rats_stage3_04_any_01 = "É esse o ônibus, tirem todos para fora.",--That's the bus, take them all out.
	pln_rats_stage3_06_any_01 = "Estou enviando um helicóptero para vocês descarregarem o loot. Está perto, não deve demorar. Fiquem firme.",--I'm sending a chopper in for you guys to unload the loot. It's close by, shouldn't take too long. Stay tight.
	pln_rats_stage3_07_any_01 = "Tenham cuidado com os explosivos, pessoal.",--Be careful around that C4 guys.
	pln_rats_stage3_08_any_02 = "Ah não! Explodiu, cuidado! Fiquem fora do fogo!",--Oh no! It exploded, watch out! Stay out of that fire!
	pln_rats_stage3_10_any_01 = "Bom trabalho, o traidor está morto, o helicóptero de fuga está esperando, a menos que queiram tentar ir atrás de dinheiro naquele ônibus, vão até o helicóptero e nós vamos tirar vocês daqui.",--Good job, the rat is dead, escape helicopter is waiting, unless you want to try to go for the money in that bus, get to the chopper and we'll get you the hell out of there.
	pln_rats_stage3_12_any_01 = "Policiais e a SWAT chegaram, tenham cuidado!",--Cops and SWATs have arrived, be careful!
	pln_rats_stage3_13_any_01 = "Cuidado com o helicóptero, está perto o suficiente para os policiais causarem um bom dano nele.",--Watch out for that chopper, it's close enough for the cops to do him some good damage.
	pln_rt3_07_any_02 = "Olhem esses C4 - Eles equiparam o ônibus inteiro.",--Watch that C4 - they rigged the whole bus.
	pln_rt3_14_any_05 = "Outra C4 - desarmem!",--Another C4 - defuse it!
	pln_rt3_17_any_03 = "Deem o fora daí!",--Get the fuck out!
	pln_rt3_17_any_01 = "Saiam daí!",--Get out of there!
	pln_rt3_18_any_02 = "O ônibus. Cheguem lá e detonem com eles. Os Mendozas estão todos lá!",--That bus. Get up there and hose it with bullets. The Mendozas are all there!
	pln_rt3_16_any_02 = "Acelerem!",--Speed up!
	pln_rt3_17_any_04 = "Fora! Vazem desse ônibus agora!",--Out! Out of the bus now!
	pln_rt3_14_any_03 = "Essas C4, usem os códigos nelas!",--Those C4 bombs, use the code on them!
	pln_rt3_16_any_01 = "Depressa!",--Hurry!
	pln_rt3_14_any_01 = "Usem os códigos para desarmar as C4!",--Use the codes to defuse the C4!
	pln_rt3_18_any_01 = "Matem esses traidores desse ônibus. o Hector não quer ver se quer um único vivo na próxima estação.",--Kill all the rats on that bus. Hector wants no one to step off at the next station.
	pln_rt3_14_any_04 = "O código vai desarmar essa C4!",--Code will defuse that C4!
	pln_rt3_17_any_02 = "Vai explodir! Corram!",--It's going to blow! Run!
	pln_rt3_13_any_02 = "Vão para aquele helicóptero, pessoal. Queremos vazar dessa ponte também.",--Get to that chopper people. We want to get off this bridge too.
	pln_rt3_14_any_02 = "Usem o código - desarmem as C4!",--Use your code - defuse the C4!
	pln_rt3_15_any_01 = "Boa! Foram todas.",--Great! That is all of them.
	pln_rt3_15_any_02 = "Ótimo, vocês pegaram todas - eu acho.",--Awesome you got them all - I think.
	pln_rt3_19_any_01 = "Tudo limpo agora. Todos os Mendozas viraram história. Voltem para o helicóptero ou peguem o dinheiro que eles deixaram no ônibus.",--That's a clean sweep. All the Mendozas are history. Get to the chopper or go for the money they got on that bus.
	
	-- Objetivos (Dia 1)
	hud_h_alex_stage1_mission1 = "Entre na casa e encontre os cozinheiros do Hector.",--Get into the house and meet Hector's cooks
	hud_h_alex_stage1_mission2 = "Defenda os cozinheiros e prepare a metanfetamina.",--Defend the cooks and cook the meth
	hud_h_alex_stage1_mission1_hl = "Encontre os Cozinheiros",--Meet the cooks
	hud_h_alex_stage1_mission4 = "Vá para o veículo de fuga.",--Get to the escape vehicle
	hud_h_alex_stage1_mission4_hl = "Fuga Disponível",--Escape is available
	hud_h_alex_stage1_mission3_hl = "Proteja a Metanfetamina",--Secure the meth
	hud_h_alex_stage1_mission2_hl = "Defenda e Prepare a Metanfetamina",--Defend and cook meth
	hud_h_alex_stage1_mission3 = "Proteja a metanfetamina e leve as bolsas para a van.",--Secure the meth and get the bags into the van
	
	-- Objetivos (Dia 2)
	hud_h_alex_stage2_mission4_hl = "Pegue a Informação",--Pick up the information
	hud_h_alex_stage2_mission3alt = "Procure nos apartamentos próximos pela informação.",--Search the nearby apartments for the information
	hud_h_alex_stage2_mission2_hl = "Entregue a Metanfetamina",--Deliver the meth
	hud_h_alex_stage2_mission3_hl = "Recupere a Informação",--Retrieve the information
	hud_h_alex_stage2_mission3alt_hl = "Encontre a Informação",--Find the information
	hud_h_alex_stage2_mission5 = "Vá para o veículo de fuga.",--Get to the escape vehicle
	hud_h_alex_stage2_mission4 = "Pegue a informação sobre os Mendoza.",--Pick up the information about Mendoza
	hud_h_alex_stage2_mission1 = "Encontre-se com os gangsters no beco.",--Meet with the gansters in the alley
	hud_h_alex_stage2_mission1_hl = "Encontre-se com os Gangsters",--Meet with the gangsters
	hud_h_alex_stage2_mission2 = "Troque a metanfetamina por informação.",--Trade the meth for the information
	hud_h_alex_stage2_mission3 = "Recupere a informação dos gangsters.",--Retrieve the information from the gangsters
	hud_h_alex_stage2_mission5_hl = "Fuga Disponível",--Escape is available
	
	-- Objetivos (Dia 3)
	hud_h_alex_stage3_mission2 = "Vá até o veículo de fuga.",--Get to the escape vehicle
	hud_h_alex_stage3_mission1 = "Encontre os traidores e mate-os.",--Find the rats and kill them
	hud_h_alex_stage3_mission1_hl = "Mate os Traidores",--Kill the rats
	hud_h_alex_stage3_mission2_hl = "Fuga Disponível",--Escape is available
		}