return {
	-- Nomes e Descrições
	--heist_cage = "Car Shop",--Car Shop
	--heist_cage_hl = "Car Shop",--Car Shop
	heist_cage_crimenet = "Estamos indo para a Concessionária Teuer. Estamos atrás dos novos carros de alta performance dessa vez. Tire-os de lá. Não queremos eles arranhados, então mantenham o sigilo.$NL;$NL;» Encontre a Despensa com as Chaves$NL;» Obtenha acesso a Despensa$NL;» Abra um Buraco na Estrada$NL;» Assegure os Carros no Estaleiro",--We're headed down to the Teuer showroom. We're after new high-performance sports cars this time. Get them out of there. We don't want them scratched, so keep it quiet.$NL;$NL;» Find the storage room with the keys$NL;» Get access to the keyroom$NL;» Blow a hole in the road$NL;» Secure the cars at the docks
	heist_cage_briefing = "Concessionária Teuer é o nosso objetivo aqui. Iremos invadir a Concessionária tarde da noite. Deverá estar quieto por lá, sem muitos civis. Eles são de classe alta. Trabalham importando supercarros de alta performance vindo da Europa e Japão. Esses carros são resultado de uma ótima engenharia. E são caros - estamos falando do preço de uma casa em Georgetown.",--Teuer autos is our objective here. We're going to hit their dealership late in the evening. Should be quiet, not many civilians. They're a high-end joint. Deal in importing high-performance supercars from Europe and Japan. Those cars are a work of engineering beauty. And they're expensive - we're talking the price of a house in Georgetown here.
	
	-- Legendas
	pln_ch1_intro_01_01 = "OK, chegamos. Hora de trabalhar.",--OK, we're here. Time to go to work.
	pln_ch1_intro_01_02 = "Encosta aqui. Beleza, gangue. Bora fazer isso.",--Pull over here. Alright gang. Let's do this.
	pln_ch1_intro_01_03 = "OK, hora de roubar uns carros.",--OK, time to steal some cars.
	pln_ch1_intro_01_04 = "Entramos com essa sucata, mas saíremos com muito estilo.",--We arrived in this piece of junk, but we're gonna leave in style.
	pln_ch1_intro_01_06 = "Estaciona aqui. Beleza. Está logo ali. Vamos lá.",--Park up here. Alright. There it is. Let's do this.
	pln_ch1_intro_01_05 = "Para o carro. É aqui. Automóveis Teuer.",--Pull over. This is it. Teuer Automotives.
	pln_ch1_04_02 = "Com um lugar chique desses, eles vão deixar as chaves num local seguro. Procure por uma Despensa.",--Fancy place like this will keep the keys secure. Look for a storage room.
	pln_ch1_29_01 = "Droga! PC errado! Policiais estão a caminho. Você não tem muito tempo.",--Damn! This was the wrong pc! Cops are on their way. You don't have much time now.
	pln_ch1_14_03 = "Loguei. Beleza, vou abrir essa trava em breve. Voltem para a van e peguem o explosivo C4. Melhor já preparar a fuga.",--Logged in. Alright, I'll have that lock open soon. Head back to the van and grab the C4. Might as well get the escape ready.
	pln_ch1_28_01 = "Quase lá galera! Estou indo o mais rápido que posso!",--Almost there guys! I'm trying as fast as I can!
	pln_ch1_34_01 = "Agora caiam fora daí!",--Now get the hell out of there!
	pln_ch1_13_02 = "Olhem em volta do Escritório, descubram quem é o nosso cara do TI. E então hackeiem o seu PC.",--Look around the office, find who our IT guy is. Then hack his pc.
	pln_ch1_23_02 = "OK, agora dirijam. Vai, vai, vai!",--OK, now drive. Go, go, go!
	pln_ch1_01_04 = "Lembrem-se, nós precisamos manter esses carros em perfeitas condições. Sem arranhões, e definitivamente sem buracos de bala. Isso significa sem polícia. Então mantenham a discrição.",--Remember, we need to keep these cars in pristine condition. No scratches, and definitely no bullet holes. Which means no cops. So keep it quiet.
	pln_ch1_13_01 = "Procurem pelo Escritório do gerente para ver quem é o novato do TI. E então localizem o seu computador, e o hackeiem.",--Search the manager's office to see who this new IT guy is. Then locate his computer, and hack it.
	pln_ch1_25_02 = "Entrei. Me dê um minuto.",--I'm in. Just gimme a minute.
	pln_ch1_25_03 = "Hackeando agora. Preciso de uns minutos.",--Hacking now. Need a minute or two.
	pln_ch1_02_02 = "A segurança parece rígida pela frente. Talvez outros meios de entrada?",--Security looks pretty tight at the front. Maybe look for other ways in.
	pln_ch1_20_01 = "*assovio* Ali está. Que belezinha.",--*whistles* There it is. What a beauty.
	pln_ch1_end_01_01 = "Excelente trabalho! Esses lindos motores estarão nas mãos de um sheik Árabe em menos de uma semana. Bom trabalho!",--Outstanding work! These sweet motors will be in the hands of Arabian sheikhs within the week. Good job!
	pln_ch1_10_01 = "Ele tem um cartão de acesso. Não é para a Despensa, então provavelmente é para o Escritório dele. Vejam o que tem lá.",--He's got a keycard. It's not for the storage room,so likely for his office. See what's in there.
	pln_ch1_brf_01_01 = "Concessionária Teuer é o nosso objetivo aqui. Nós vamos invadir a Concessionária tarde da noite. Deve estar quieto por lá, sem muitos civis. Eles são de classe alta. Trabalham importando supercarros de alta performance vindo da Europa e Japão. Esses carros são resultado de uma ótima engenharia. E são caros - estamos falando do preço de uma casa em Georgetown.",--Teuer autos is our objective here. We're going to hit their dealership late in the evening. Should be quiet, not many civilians. They're a high-end joint. Deal in importing high-performance supercars from Europe and Japan. Those cars are a work of engineering beauty. And they're expensive - we're talking the price of a house in Georgetown here.
	pln_ch1_11_03 = "O Escritório do gerente é o seu próximo objetivo",--The manager's office is your next stop.
	pln_ch1_14_02 = "Entrei! Certo, preciso de um momento para chegar na tranca. Enquanto vocês esperam, voltem lá pra fora e peguem o C4.",--In! Right, need a few moments to get the lock. While you're waiting, head back out and fetch some C4. Let's get our escape ready.
	pln_ch1_06_03 = "E... está trancada. Droga! OK. Permaneçam em silêncio. O gerente deve estar em algum lugar por aí. Pegue-o como refém. Ele deve conseguir fazer a gente entrar lá.",--And... it's locked. Damn! OK. Stay quiet. The manager must be around there somewhere. Take him hostage. He should be able to get us in.
	pln_ch1_cbf_01_01 = "A Concessionária Teuer é uma das poucas da Costa Leste que vende carros Falcogini. Eles acabaram de lançar um modelo - o La Troienne. Eu conheço um pessoal fora do país que está disposto a pagar muito por essa belezinha. Entre lá, pegue os carros e dê o fora. Simples, certo?",--The Teuer dealership is one of the few East Coast showrooms that sells Falcogini cars. They just got the hot new model in - the La Troienne. I got some people overseas who are willing to pay big for this little beauty. Get in there, get to the wheels and get them out. Simple, right?
	pln_ch1_cnc_01_03 = "Isso aqui é um roubo na Concessionária Teuer. Estabelecimento de classe alta.",--This one is a hit on the Teuer dealership. High class joint.
	pln_ch1_cnc_01_01 = "Esse aqui é um roubo em um dos estabelecimentos de classe alta da cidade. A Concessionária Teuer.",--This one is a hit on one of the high-class auto joints in town. The Teuer car dealership.
	pln_ch1_17_01 = "Boa! Vou detoná-los assim que a hora chegar. Volte para a Despensa. Consegui abrir!",--Nice! I'll detonate these when the time comes. Get back to that storage room. I got it open!
	pln_ch1_09_03 = "O gerente está de terno preto, cabelo caindo. Ache-o e amarre-o - ele pode ser bem útil.",--Manager's got a black suit, thinning hair. Find him, tie him - that might make him more helpful.
	pln_ch1_16_03 = "Tenho acesso. Enquanto você me espera, peguem o C4 da van e plante-a na rua.",--I have access. While you're waiting for me, grab the C4 from the van and get it planted in the street.
	pln_ch1_04_01 = "Agora achem a Despensa. É lá que estarão as chaves.",--Now find the storage room. That's where the keys'll be.
	pln_ch1_26_03 = "Espera um pouco, galera.",--Stand by, gang.
	pln_ch1_32_01 = "Dirija através do buraco no meio da rua!",--Drive through the hole on the street!
	pln_ch1_06_01 = "Droga. Está trancada. Hmmm. Certo. O gerente ainda tá ali. Pegue-o como refém. Veja se ele tem alguma informação sobre a trava.",--Damn. It's locked. Hmmm. Alright. The manager's still there. Take him as hostage. See if he has any information about the lock.
	pln_ch1_cnc_02_01 = "Um trabalho de alto nível. Roube a Concessionária Teuer. Peguem os novos modelos.",--A rare job. Hit the Teuer dealership. Boost the new models.
	pln_ch1_05_01 = "A Despensa galera. Entre lá e peguem as chaves dos carros.",--The storage room guys. Get in there and get the car keys.
	pln_ch1_12_03 = "Eles contrataram um novato do TI. Se você achar o nome dele e hackear seu PC, posso conseguir abrir aquela porta pra você.",--They got a new IT guy on the books. If you can find his name and hack his pc, I should be able to open that door for you.
	pln_ch1_end_01_02 = "Você conseguiu. Tem uns russos playboys do ramo do petróleo que vão pagar acima do preço por essas máquinas. Bom trabalho!",--You did it. Got a couple of Russian oil playboys that'll pay over the odds for these wheels. Nicely done!
	pln_ch1_34_03 = "Hora de fugir, galera!",--Time to bounce, gang!
	pln_ch1_02_03 = "A frente tem seguranças. Chequem os lados e atrás.",--Front is secure. Check around the sides and back.
	pln_ch1_12_02 = "Eles contrataram um novato do TI recentemente. Se chegarmos no computador dele, posso conseguir abrir aquela porta. Procure por pistas sobre quem é esse cara, e ache seu PC.",--They recently hired a new IT guy. If we can get into his computer, I should be able to get that door open. Look for some clue to who this guy is, and find his PC.
	pln_ch1_12_01 = "Parece que eles contrataram um especialista em TI. Vejam se conseguem achar pistas sobre ele no Escritório do gerente, e então hackeiem o seu computador. Quando hackeado, abrirei a porta para vocês.",--Looks like they hired a new IT specialist. See if you can find any clues in the manager's office about him, then hack his computer. Once in, I'll get the lock open for you.
	pln_ch1_18_02 = "E... consegui! A Despensa está aberta. Peguem as chaves.",--And... got it! Storage room is open. Get the keys.
	pln_ch1_03_01 = "Essa caixa elétrica controla o portão. Certeza que vocês conseguem abrir em segundos.",--That electric box controls the gate. Sure you could have it open in seconds.
	pln_ch1_01_06 = "As compras desses carros exigem que estejam em perfeitas condições. Mantenha o silêncio, e a polícia manterá a distância. O que significa sem buracos de bala.",--The market for these cars demands they are in perfect condition. Keep it quiet, and you'll keep the cops away. Which means no bullet holes.
	pln_ch1_21_01 = "Agora a parte divertida - Roubem um carro! Vou explodir a rua - Protejam-se!",--Now the fun part - steal a car! I'll blast the road - take cover!
	pln_ch1_11_02 = "Usem esse cartão de acesso no Escritório do gerente.",--Use that keycard on the manager's office.
	pln_ch1_16_01 = "Consegui! Entrei no sistema. Enquanto eu acabo aqui, vão para a van e peguem os explosivos. Plantem na rua.",--Got it! I'm in the system. While I finish this, get out to the van and grab the C4. Plant it in the street.
	pln_ch1_24_03 = "Policiais estão a caminho. Mais rápido!",--Cops are en route. Move faster!
	pln_ch1_32_02 = "Vê esse buraco enorme? Dirija através dele, e pé no acelerador!",--See that nice big hole? Drive through it, and hit the gas!
	pln_ch1_01_02 = "Mantenha a discrição até você pegar os carros. Os policiais não podem atirar neles. Eu falo quando for para plantar os explosivos.",--Keep it quiet til you get the cars. We can't afford to have cops shooting them up. I'll tell you when to plant the C4.
	pln_ch1_32_03 = "Entrem no buraco, cabeça de buxa!",--Into the hole, petrolhead!
	pln_ch1_23_01 = "Wow, que puta explosão! Policiais estão a caminho agora, então dirija rápido!",--Wow, that was one hell of an explosion! Cops are on their way now, so drive fast!
	pln_ch1_21_03 = "Ótimo, agora entra no Falcogini. Vou abrir caminho. Toma cuidado!",--Great, now get into that Falcogini. I'll clear the road. Heads down!
	pln_ch1_05_03 = "A Despensa é o seu objetivo. É lá que você encontrará as chaves.",--The storage room is your target. That's where we'll find the keys.
	pln_ch1_30_03 = "Olhem pelo Escritório do gerente. Procure pelo nome do cara do TI. Bora, bora!",--Check the manager's office. Look for the IT guys name. Come on, come on!
	pln_ch1_21_02 = "Agora pulem pra dentro do carro. Ah, e cabeça abaixada - é hora de *explodir* essa joça.",--Now jump into the car. Oh, and keep your head down - it's time to *blow* the joint.
	pln_ch1_34_02 = "Agora vazem daí!",--Now bail out of there!
	pln_ch1_09_02 = "Achem o gerente. Ele está vestindo um terno preto, ficando calvo. Amarre-o e veja se ele pode ajudar.",--Find the manager. He's wearing a black suit, going bald. Tie him up and see if he can help.
	pln_ch1_33_02 = "Agora coloquem o carro dentro do contêiner, sai fora dele e poderemos concluir essa.",--Now put the car in the container, get out and we can close this caper.
	pln_ch1_31_02 = "Agora vão!",--Now drive!
	pln_ch1_09_01 = "Procurem pelo gerente. Calvo, Terno preto. Amarre-o e vejam se ele tem informações.",--Look for the manager. Balding, black suit. Tie him down and see if he has more information.
	pln_ch1_07_02 = "Consegui o arquivo do gerente. Parece que o cara nasceu pra usar esse terno.",--I got the manager's file here. Looks like the guy was born to wear this black suit.
	pln_ch1_10_02 = "Ele deixou cair o cartão de acesso. Provavelmente para o seu Escritório. Talvez algo lá dentro vá ajudar.",--He dropped a keycard. Probably for his office. Maybe something there will help.
	pln_ch1_16_02 = "Certo, tô dentro. Vou acabar com essa tranca em um segundo. Agora preciso que vocês vão lá fora, peguem os explosivos e plante-os na rua.",--Alright, I'm in. I'll pop that lock for you in a sec. Right now I need you to get back out front, grab the C4 and get it on the street.
	pln_ch1_29_02 = "Ah, droga. PC errado. Os alarmes dispararam. Policiais a caminho. Vocês estão sem tempo.",--Ah hell. Wrong pc. Alarms are tripped. Cops are en-route. Not much time now.
	pln_ch1_02_01 = "Hmm, a entrada parece bem segura. Sugiro que tentem outros meios de entrada.",--Hmm, the entrance looks secured. I suggest you try to find another way in.
	pln_ch1_08_01 = "Vejo também que ele é calvo. Entendeu? Procurem pelo cara velho, com o cabelo caindo.",--I can also see that he's balding. You copy that? Look for the old, balding guy.
	pln_ch1_27_03 = "Não temos muito tempo. Espero que esse seja o certo.",--Not much time. Hope this is the right one.
	pln_ch1_15_01 = "Vão para a van lá fora e peguem o C4. Plante-o na rua.",--Go out to the van and pick up the C4. Plant it on the street.
	pln_ch1_23_03 = "Agora queimem o pneu!",--Now burn some rubber!
	pln_ch1_27_01 = "É melhor que esse seja o certo! Não temos muito tempo.",--This better be the right one! Don't have much time now.
	pln_ch1_10_03 = "Ei, ele deixou cair um cartão de acesso. Não para a Despensa, seria muito fácil. Vá para o Escritório dele.",--Hey, he dropped a keycard. Not for the storage room, that'd be too easy. Head to his office.
	pln_ch1_25_01 = "OK. Me dê um minuto mais ou menos.",--OK. Give me a minute or so.
	pln_ch1_24_01 = "Droga! Policiais estão vindo. Temos pouco tempo.",--Damn it! Cops are on their way. Not much time now.
	pln_ch1_17_02 = "OK, vou acioná-los manualmente. Agora voltem para a Despensa. Está aberta!",--OK, I'll set these off remotely. Now get back to the storage room. It's open!
	pln_ch1_04_03 = "Aposto que as chaves estão trancadas em algum lugar. Achem a Despensa.",--I'm betting the keys are locked away somewhere. Find the storage.
	pln_ch1_03_02 = "Essa caixa de luz controla o portão. Alguns cortes, um pouco de religamento... e abra-te sésamo!",--That box there controls the gate. A few snips, a bit of rewiring... and open sesame!
	pln_ch1_30_02 = "Procurem pelo Escritório! Peguem o nome do cara! Não temos muito tempo.",--Search the office! Get the guys name! Not much time.
	pln_ch1_19_03 = "As chaves estão na Despensa. Pegue-as!",--The keys are in the storage room. Grab 'em!
	pln_ch1_24_02 = "Os policiais estão a caminho. Isso é importante, apressem-se!",--Cops are on the way. Time is important, so hustle!
	pln_ch1_22_02 = "Galera, protejam-se dentro da Concessionária. Vocês não vão querer estar perto da explosão.",--Guys, take cover in the dealership. You don't want to be near this bang!
	pln_ch1_17_03 = "Certo. Papai Bain vai cuidar disso. Agora, retorne para a Despensa para as chaves.",--Great. Poppa Bain will take care of these. Now, return to the key storage room.
	pln_ch1_20_03 = "Estou com inveja de você que vai dirigir esse monstro.",--I'm jealous you're going to get to drive this beast.
	pln_ch1_31_03 = "Dirige pra fora daí!",--Drive out of there!
	pln_ch1_31_01 = "Vai vai vai!",--Go go go!
	pln_ch1_20_02 = "850 cavalos de pura beleza.",--850 horse power of pure sexy badass.
	pln_ch1_18_01 = "Beleza, consegui! A Despensa está destrancada. Peguem as chaves.",--Alright, I got it! The storage room is now unlocked. Go get the car keys.
	pln_ch1_03_03 = "Essa caixa de luz controla o portão. Um pouco de criatividade pode fazê-lo abrir.",--That box controls the gate. A little creativity should get them open.
	pln_ch1_01_05 = "Nossos compradores querem os carros em perfeitas condições. Isso significa que você não pode alertar os policiais. Eles não se importam no que vão atirar. Então dessa vez mantenha o sigilo.",--Our buyers only want cars in great condition. That means you can't alert the cops. They won't care what they shoot up. So keep this a quiet one.
	pln_ch1_22_03 = "Galera, entrem na Concessionária. Protejam-se. Vou explodir a rua.",--Gang, into the dealership. Take cover. I'm blasting the road.
	pln_ch1_28_02 = "Quase consegui. Vamos, vamos.",--Nearly got it. Come on, come on.
	pln_ch1_30_01 = "As pistas pro computador certo estão no Escritório. Vamos, vai logo!",--Clues to the right computer are in the office. Come on, hustle!
	pln_ch1_26_01 = "Quase lá galera!",--Almost there guys!
	pln_ch1_08_02 = "Parece que o gerente está perdendo o cabelo. Procurem pelo homem calvo.",--Looks like the manager is losing a bit on top. Look for the balding guy.
	pln_ch1_01_03 = "Danos colaterais irão nos ferrar. Então sem polícia. Isso significa manter o sigilo. Eu aviso quando for para plantar o C4.",--Collateral damage will screw us. So no cops. That means keep it quiet. I'll let you know when you need to plant the C4.
	pln_ch1_13_03 = "Procurem o Escritório do gerente. Você deve conseguir descobrir quem é o cara do TI. Daí você pode hackear seu PC.",--Scope out the manager's office. You should be able to find who the IT guy is. Then you can hack his pc.
	pln_ch1_28_03 = "Quase consegui. Mais rápido, mais rápido.",--Almost got it. Faster, faster, faster.
	pln_ch1_01_01 = "Lembre-se, não podemos vender carros danificados então sem polícia. Mantenham o sigilo. Eu aviso quando vocês puderem plantar a C4 na rua.",--Remember, we can't sell damaged cars so no cops. Keep it quiet. I'll let you know when you can plant the C4 on the road.
	pln_ch1_33_03 = "Deixem o carro no contêiner e dê o fora. Estamos quase lá.",--Just leave the car in the container and mosey on out. We're nearly done.
	pln_ch1_cnc_01_02 = "Estamos indo para a Concessionária Teuer. É um lugar de classe alta.",--We're going to the Teuer dealership. It's a high-end place.
	pln_ch1_05_02 = "Encontrem a Despensa, galera. As chaves estarão lá.",--Find that storage room, gang. The keys will be there.
	pln_ch1_06_02 = "Trancada. Droga! Beleza, mantenham a calma. Achem o gerente. Faça-o de refém. Tenho certeza que ele pode nos ajudar a entrar.",--Locked. Damn it! Alright, stay cool. Find the manager. Take him hostage. I'm sure he can help us get in.
	pln_ch1_07_01 = "Estou vendo o perfil do gerente. Parece que ele está usando um terno preto.",--I'm looking at the manager's file. Chances are he's wearing a black suit.
	pln_ch1_07_03 = "Acessei o arquivo do gerente. Ele está usando um terno preto.",--I've accessed the manager's file. He'll be wearing a suit.
	pln_ch1_08_03 = "O cabelo do gerente está caindo. Isso pode ajudar na sua busca.",--The manager's hair is thinning. That might narrow your search.
	pln_ch1_11_01 = "Usem o cartão de acesso do gerente para abrir seu Escritório.",--Use the manager's keycard to open his office.
	pln_ch1_14_01 = "Entrei. Preciso de um tempo para abrir aquela trava. Em vez de ficar sentado aí coçando a bunda, vão lá pra fora e peguem um pouco de C4. Hora de preparar a fuga.",--I'm in. Need some time to open that lock. Instead of sitting there scratching your ass, head out to the van and get some C4. Time to prepare your escape.
	pln_ch1_15_02 = "Galera, peguem os explosivos da van. Coloque-os na rua.",--Guys, grab the C4 from the van. Get it on the street.
	pln_ch1_15_03 = "Galera, a C4 está na van. Pegue-a, e plante-a.",--Gang, the C4 is in the van. Get it, and plant it.
	pln_ch1_18_03 = "E... a Despensa está aberta. As chaves estão prontas.",--And... storage room is open. The keys are ready for you.
	pln_ch1_19_01 = "Peguem as chaves dos carros na Despensa!",--Get the car keys in the storage room!
	pln_ch1_19_02 = "Galera, vocês precisam pegar as chaves.",--Gang, you need to grab the car keys.
	pln_ch1_22_01 = "Todos vocês precisam estar dentro da Concessionária para que eu possa explodir o C4.",--All of you need to be inside the dealership so I can blow up the C4!
	pln_ch1_26_02 = "Quase lá.",--Nearly got it.
	pln_ch1_27_02 = "Espero que esse seja o certo.",--Hope this is the right one.
	pln_ch1_29_03 = "Droga, computador errado. Policiais estão a caminho. Vocês não tem muito tempo agora.",--Crap, wrong computer. Cops are incoming. You don't have much time now.
	pln_ch1_33_01 = "Certo, estacionem o carro naquele contêiner, e vá embora!",--Alright, just park the car in that container, and walk away!
	pln_ch1_35_01 = "Certo, vou detoná-los quando a hora chegar. Vocês precisam estar preparado com os carros.",--Nice, I'll detonate these. You just be ready with the cars.
	pln_ch1_35_02 = "Ok, eu vou detoná-los manualmente. Foque nos carros.",--Ok, I'll set these off remotely. You focus on the cars.
	pln_ch1_35_03 = "Ótimo. Papai Bain vai cuidar disso. Agora, voltem para as chaves.",--Great. Poppa Bain will take care of these. Now, back to the keys.
	pln_ch1_end_01_03 = "Ótimo trabalho! Essas belezinhas vão rasgar as estradas do Leste Europeu muito em breve.",--Great job! These beauties will be tearing up the streets of Eastern Europe in no time.
	
	-- Objetivos
	hud_heist_cag1_7 = "Entre na Concessionária para se abrigar da explosão, e pegue as chaves.",--Enter the car shop to take shelter from the blast, and get the car keys
	hud_heist_cag1_9 = "Vá para o estaleiro o mais rápido possível!",--Drive to the dock yard as fast as possible!
	hud_heist_cag1_12 = "Tenha certeza de que ninguém veja o computador.",--Make sure nobody sees the computer.
	hud_heist_cag1_4_hl = "Investigue o Escritório do Gerente",--Investigate the manager's office
	hud_heist_cag1_10 = "Estacione o carro em um dos contêineres.",--Park the car in one of the containers.
	hud_heist_cag1_11 = "Vá para a van de fuga.",--Go to the escape van.
	hud_heist_cag1_7_hl = "Abrigue-se da Explosão e Pegue as Chaves",--Hide from the blast and get the keys
	hud_heist_cag1_6_hl = "Plante o C4",--Plant the C4
	hud_heist_cag1_5_hl = "Hackeie o Computador do Técnico de TI",--Hack the IT technicians's computer
	hud_heist_cag1_8 = "Roube o Carro.",--Steal the car
	hud_heist_cag1_6 = "Volte para a van e pegue os explosivos. Plante na rua para preparar a fuga.",--Go back to the van and pick up C4. Place it on the street outside to prepare the escape.
	hud_heist_cag1_3 = "Ache o cartão de acesso do gerente. Provavelmente está com ele.",--Find the manager's keycard. He's probably carrying it on him.
	hud_heist_cag1_2 = "Investigue a Despensa, supostamente as chaves estão lá. Vamos ver o nível de segurança que eles possuem.",--Investigate the storage room, it's supposed to have the car keys. Let's see what security they have.
	hud_heist_cag1_1_hl = "Entre na Concessionária",--Get into the car shop
	hud_heist_cag1_1 = "Encontre um caminho para entrar na Concessionária sem ser detectado.",--Find a way into the car shop without getting detected.
	hud_heist_cag1_8_hl = "Roube o Carro",--Steal the car
	hud_heist_cag1_12_hl = "Proteja o Computador",--Protect the computer
	hud_heist_cag1_11_hl = "Fuja!",--Escape!
	hud_heist_cag1_5 = "Veja o nome do técnico de TI no quadro branco no Escritório do gerente. Então localize a mesa do técnico e hackeie seu computador.",--Check the name of the IT technician on the white board in the manager's office. Then locate the IT technician's desk and hack their computer.
	hud_heist_cag1_2_hl = "Investigue a Despensa",--Investigate the storage room
	hud_heist_cag1_9_hl = "Fuja com o Carro",--Escape with the car
	hud_heist_cag1_3_hl = "Pegue o Cartão de Acesso do Gerente",--Get keycard from the manager
	hud_heist_cag1_4 = "Entre no Escritório do gerente usando seu cartão de acesso. Veja se tem algo lá dentro que nos ajude a abrir a Despensa.",--Enter the manager's office using his keycard. See if there's anything in there that can lead us into opening the storage.
	hud_heist_cag1_10_hl = "Estacione o Carro",--Park the car
		}