return {
    -- Descrições
    heist_escape_street_briefing = "Eles perseguiram a gente... Trocar de carro não deu certo, todos aí segurem-se!",--...They tailed us from the scene, switch car failed, everyone batten down the hatches!
	heist_escape_cafe_briefing = "Caralho, eles estão muito na nossa cola, estão na nossa cola! Vocês precisam fugir com o loot!",--...Damn it to hell they're onto us, they're onto us! You gotta escape with the loot!
	heist_escape_park_briefing = "Merda, temos policiais na nossa cola, não vou conseguir despistar eles!",--...Shit we picked up a tail folks, no shaking 'em now!
	heist_escape_overpass_briefing = "Meu Deus, eles estão em cima de vocês, se preparem pra bater!",--...Jesus they're right on top of you, prepare to get hit!
	heist_escape_garage_briefing = "Despistem eles... Despistem eles, Caralho... CARALHO! Vocês vão tem que resistir!",--...Lose 'em... Lose 'em... Dammit... DAMMMIT! You gotta stand and fight!

    -- Legendas
    -- Piloto de Fuga
	dr1_a01d_any_18 = "Nós vamos bater nessa porra!",--We're gonna fucking crash!
	dr1_a01d_any_24 = "Eita, eita, eita, eita!",--Woah-woah-woah-woah!
	dr1_a01b_any_14 = "Os policiais estão na nossa cola feito a porra de um rabo de cavalo!",--The police is on our back like a fucking pony tail!
	dr1_a01c_any_03 = "Esses caras sabem dirigir!",--These guys can drive!
	dr1_a01a_any_16 = "Mas que porra!",--Fuck me sideways!
	dr1_a01b_any_25 = "A policia tá atrás da gente que nem doidos!",--WPD's on our tail like a bad date!
	dr1_a01a_any_05 = "Filho da puta!",--Son of a bitch!
	dr1_a01c_any_13 = "Esses caras sabem dirigir!",--These guys can drive!
	dr1_a01b_any_20 = "Os policiais estão na nossa cola feito a porra de um rabo de cavalo!",--The police is on our back like a fucking pony tail here!
	dr1_a01c_any_18 = "Pensei que a gente ia despistar o helicóptero no túnel!",--I thought we lost that damn helicopter in the tunnel!
	dr1_a01b_any_21 = "Os policiais estão bem em cima da gente!",--The cops are right on top of us!
	dr1_a01b_any_19 = "Nós temos um comboio da policia atrás da gente!",--We got a fucking police caravan on our ass!
	dr1_a01c_any_22 = "Mas que merda vocês roubaram!?",--What the fuck did you guys steal!?
	dr1_a01a_any_24 = "Isso não estava nos planos, pessoal!",--This didn't go as planned, guys!
	dr1_a01d_any_10 = "Eles atiraram nos pneus!",--They're shooting at our tires!
	dr1_a01c_any_09 = "Esses filhos das putas aprenderam a dirigir, vou te contar viu!",--These fuckers went to driving school - I'll tell you that much!
	dr1_a01d_any_08 = "Espero que essa merda tenha air bags!",--I hope this hunk o' metal has air bags!
	dr1_a01c_any_08 = "Pensei que a gente ia despistar o helicóptero naquele túnel!",--I thought we lost that damn helicopter in the tunnel!
	dr1_a01b_any_06 = "Nós temos a porra de um comboio polícial na nossa cola!",--We got a fucking police caravan on our ass!
	dr1_a01a_any_10 = "Puta que pariu!",--God damn!
	dr1_a01b_any_08 = "Metade da força polícial na nossa cola!",--Half the fucking police force is on our ass!
	dr1_a01c_any_20 = "Mas que merda vocês roubaram!?",--What the fuck did you guys steal!?
	dr1_a01d_any_25 = "POOOOOORRAAAAAAAA!",--Fuuuuuuuuuck!
	dr1_a01d_any_15 = "Se preparem pro impacto!",--Brace for impact!
	dr1_a01d_any_19 = "Se segurem em algo!",--Hold on for dear life!
	dr1_a01a_any_08 = "Más noticías, gente!",--Bad news, guys!
	dr1_a01c_any_21 = "Eles não estão deixando a gente ir!",--They're not letting us go!
	dr1_a01d_any_21 = "Ah, meeeeeeerdaaaa!",--Oh shiiiiiit!
	dr1_a01a_any_07 = "Não, não, não, não, não!",--No-no-no-no-no!
	dr1_a01b_any_13 = "Temos a porra de um comboio polícial na nossa cola!",--We got a fucking police caravan on our ass!
	dr1_a01a_any_26 = "Puta que pariu!",--God damnit!
	dr1_a01b_any_01 = "Metade da força polícial na nossa cola!",--Half the fucking police force is on our ass!
	dr1_a01a_any_14 = "Porra, merda, caralho!",--Damn damn damn!
	dr1_a01d_any_07 = "Se segurem em algo!",--Hold on for dear life!
	dr1_a01a_any_11 = "Porra!",--Fuck!
	dr1_a01b_any_02 = "Os policiais estão na nossa cola!",--The cops are on our tail!
	dr1_a01c_any_15 = "Eles estão grudados na nossa cola!",--They're on us like fucking flies on a turd!
	dr1_a01d_any_02 = "Comecem a rezar e sejam rápidos!",--Say your prayers and say 'em fast!
	dr1_a01c_any_02 = "Essa é uma perseguição que tá foda!",--This is one tail I can't lose!
	dr1_a01a_any_23 = "Tenho más noticías!",--I got real bad news!
	dr1_a01d_any_14 = "Peguem as - oh, merda! As alças!",--Grab the oh-shit handles!
	dr1_a01b_any_18 = "Estão na nossa cola e estão chegando bem perto!",--We got a tail - and they're getting closer!
	dr1_a01a_any_04 = "Mas que merda, caralho!",--Damn damn damn!
	dr1_a01a_any_01 = "Porra!",--Fuck!
	dr1_a01b_any_15 = "Metade das forças policiais estão na porra do nosso rabo!",--Half the fucking police force is on our ass!
	dr1_a01d_any_06 = "A gente vai bater!",--We're gonna fucking crash!
	dr1_a01a_any_22 = "Essa merda tá ficando bem séria, pessoal!",--Shit is getting real, guys!
	dr1_a01c_any_01 = "Não consigo despistar eles!",--I can't shake 'em!
	dr1_a01b_any_11 = "É a polícia! estão na nossa cola!",--It's the police! They're tailing us!
	dr1_a01c_any_23 = "Esses policiais são os mais persistentes que já vi, puta que pariu!",--This has to be the most persistent fucking cops I've ever seen!
	dr1_a01a_any_21 = "Tenho más noticías, gente!",--I've got bad fucking news, guys!
	dr1_a01d_any_16 = "Estou perdendo o controle!",--I'm losing control!
	dr1_a01d_any_09 = "OH, MEEEERDAAAAA!",--Oh shiiiiiit!
	dr1_a01b_any_09 = "Os policiais estão na nossa cola!",--The cops are on our tail!
	dr1_a01a_any_09 = "Não acredito nessa merda!",--I can't believe this shit!
	dr1_a01d_any_05 = "Eles estão atirando nos pneus!",--They're fucking firing at the tires!
	dr1_a01c_any_17 = "Deveríamos trocar de van!",--We should've fucking switched cars!
	dr1_a01d_any_01 = "Isso não é nada bom, pessoal, nada bom!",--It doesn't look good, guys - it doesn't look good!
	dr1_a01c_any_04 = "Estão na nossa cola que tá difícil!",--They're on to us like a fucking sticker!
	dr1_a01a_any_15 = "Filho da puta!",--Son of a bitch!
	dr1_a01b_any_24 = "Nós temos a porra de um comboio da polícia no nosso rabo!",--We got a fucking police caravan on our ass!
	dr1_a01d_any_12 = "Eita, eita, eita, eita!",--Woah-woah-woah-woah!
	dr1_a01c_any_19 = "Esses filhos da puta sabem mesmo dirigir, vou te contar!",--These fuckers went to driving school - I'll tell you that much!
	dr1_a01a_any_17 = "Não, não, não, não, não!",--No-no-no-no-no!
	dr1_a01b_any_22 = "Eles estão na nossa cola e estão chegando perto!",--We got a tail - and they're getting closer!
	dr1_a01a_any_18 = "Más noticías, pessoal!",--Bad news, guys!
	dr1_a01b_any_10 = "É a polícia! estão perseguindo a gente!",--It's the cops! They're following us!
	dr1_a01a_any_02 = "Filhos da puta!",--Motherfuckers!
	dr1_a01c_any_16 = "Esses policiais são bem determinados, caralho!",--These are some determined fucking law enforcers!
	dr1_a01a_any_25 = "Não posso acreditar numa merda dessas!",--I can not fucking believe this shit!
	dr1_a01b_any_26 = "Os policiais estão na nossa cola que não querem sair!",--The police are on our back like a fucking pony tail!
	dr1_a01b_any_23 = "É, tem um excército de policiais no nosso rabo!",--Yeah, that's small army of police cars on our fucking tail!
	dr1_a01c_any_07 = "Deveríamos ter trocado a van!",--We should've switched fucking cars!
	dr1_a01c_any_14 = "Estão na nossa cola que tá foda, hein!",--They're on to us like a fucking sticker!
    dr1_a01d_any_03 = "Se preparem pro impacto!",--Brace for impact!
    dr1_a01c_any_12 = "Não consigo despistar esses policiais!",--This is one tail I can't lose!
    dr1_a01b_any_05 = "Estão na nossa cola e chegando cada vez mais perto ainda!",--We got a tail - and they're getting closer!
    dr1_a01a_any_19 = "Não acredito nessa merda!",--I can't believe this shit!
    dr1_a01d_any_17 = "Eles atiraram nos pneus!",--They're firing at the tires!
    dr1_a01b_any_16 = "Os policiais estão na nossa cola!",--The cops are on our tail!
    dr1_a01d_any_04 = "Eu estou perdendo o controle!",--I'm losing control!
    dr1_a01c_any_10 = "Mas que porra vocês roubaram, pessoal!?",--What the fuck did you guys steal!?
    dr1_a01b_any_03 = "São os policiais! Estão nos seguindo ferrenhamente!",--It's the cops! They're following us!
    dr1_a01a_any_12 = "Filhas da puta!",--Motherfuckers!
    dr1_a01d_any_13 = "Isso não é bom, pessoal, nadinha bom!",--It doesn't look good, guys - it doesn't look good!
    dr1_a01c_any_05 = "Eles querem pegar a gente de jeito!",--They're on us like fucking flies on a turd!
    dr1_a01b_any_17 = "É a polícia! Eles estão na nossa cola!",--It's the police! They're tailing us!
    dr1_a01a_any_06 = "Mas que caralho!",--Fuck me sideways!
    dr1_a01b_any_07 = "A polícia está na nossa cola e não querem sair por nada!",--The police is on our back like a fucking pony tail!
    dr1_a01a_any_20 = "Vai tomar no cu!",--God damn!
    dr1_a01d_any_11 = "Aaaaahhh!",--Aaaargh!
    dr1_a01c_any_11 = "Não consigo despistar eles!",--I can't shake 'em!
    dr1_a01b_any_04 = "É a polícia! estão bem na nossa cola!",--It's the police! They're tailing us!
    dr1_a01a_any_13 = "Merda!",--Shit!
    dr1_a01d_any_20 = "Espero que esse lixo tenha air bags!",--I hope this hunk o' metal has air bags!
    dr1_a01c_any_06 = "Esses policiais são bem determinados, puta merda!",--These are some determined fucking law enforcers!
    dr1_a01b_any_12 = "Estão na nossa cola e cada vez mais pertos!",--We got a tail - and they're getting closer!
    dr1_a01a_any_03 = "Merda!",--Shit!
	
    -- Bain
	pln_esc_06_to_arrival = "O veículo de fuga vai estar aí em seis minutos.",--The escape will be there in six minutes.
	pln_esc_park_escape_location_02 = "A van vai estar próximo ao parque.",--The van will be coming in near the park.
	pln_esc_09_to_departure = "O veículo de fuga vai ir embora em nove minutos.",--The escape vehicle is leaving in nine minutes.
	pln_esc_cafe_01_to_arrival_subway_01 = "Ok, nosso contato vai conseguir abrir e entrar no metrô em um minuto. Preparem-se...",--OK, our contact will be able to open the subway entrance in a minute. Be ready...
	pln_esc_street_swats_deployed_02 = "Os policiais sabem que os Snipers não vão conseguir parar isso. Eles estão se preparando para mandar nos telhados!",--The cops know the snipers wont be able to finsh this. They're prepairing to send in the troops!
	pln_esc_street_lookout_sniper_02 = "Esses Snipers não vão deixá-los em paz. Um de vocês devem ficar de olho nos telhados!",--Those snipers wont leave you alone anytime soon. One of you should keep an eye on those roofs at all times!
	pln_esc_overpass_sniper_on_rooftop_01 = "Um Sniper está indo pro telhado do outro lado da rodovia. Não deixem que eles te parem.",--A sniper is moving in to deploy on a rooftop on the other side of the highway. Don't let him stop you.
	pln_esc_park_suggest_park_02 = "Vocês devem conseguir aguentar dentro do parque.",--You should be able to hold your ground inside the park.
	pln_esc_06_to_departure = "O veículo de fuga vai chegar em seis minutos.",--The escape vehicle is leaving in six minutes.
	pln_esc_street_snipers_nearby_01 = "Cuidado! Snipers mataram o piloto! Eles devem estar próximos.",--Stay low! Snipers took out your driver! They must be deployed near by.
	pln_esc_arrival_heli = "O helicóptero chegou. Andem logo!",--The choppers ready. Get moving!
	pln_esc_cafe_03_to_departure_01 = "Beleza, pessoal, nós temos três minutos aqui. Apressem-se!",--Alright guys, we've got a three minute window here. Get moving!
	pln_esc_cafe_30secs_to_arrival_subway_01 = "A entrada do metrô vai abrir em 30 segundos, Aguentem um pouco aí.",--The subway entrance will be open in 30 seconds, just hold on.
	pln_esc_overpass_more_snipers_01 = "O rádio da polícia confirmou os Snipers. Fiquem de olho nos telhados!",--Police chatter has confirmed the presence of snipers. Keep your eyes on those rooftops!
	pln_esc_requirement_08_bags = "Lembrem-se pessoal, nós precisamos de oito bolsas para fugir.",--Remember guys, we need eight bags to escape.
	pln_esc_10_to_arrival = "O veículo de fuga vai chegar aí em dez minutos.",--The escape vehicle will be there in ten minutes.
	pln_esc_park_suggest_park_01 = "Tem um parque próximo daí, ele deve lhes oferecer alguma cobertura...",--There's a park nearby that should offer some cover...
	pln_esc_garage_01_any_02 = "Mas que merda aconteceu?! Só peguem o loot e fiquem vivos! Os policiais estão chegando com tudo.",--What the hell just happened?! Just grab the loot and look alive! The cops are moving in.
	pln_esc_requirement_04_bags = "Lembrem-se pessoal, nós precisamos de quatro bolsas para fugir.",--Remember guys, we need four bags to escape.
	pln_esc_park_suggest_park_03 = "O parque deve oferecer uma posição boa de defesa.",--The park should offer a good defensive position.
	pln_esc_park_marksmen_rooftop_02 = "Atenção, os policiais estão no telhado próximo!",--Heads up, the cops are deploying on a nearby rooftop!
	pln_esc_cafe_02_to_departure_01 = "Preparem-se, vocês tem exatamente dois minutos para darem o fora!",--Step it up, you've got two minutes to get out of there!
	pln_esc_street_more_snipers_deployed_02 = "Snipers chegaram!",--Snipers are inbound!
	pln_esc_street_chopper_arrived_02 = "O helicóptero já está pronto. Cuidado! Esses snipers não querem que vocês saiam.",--The chopper's ready. Watch out! Those snipers dont want you to leave.
	pln_esc_overpass_sniper_on_rooftop_02 = "Um Sniper está se preparando em uma posição do lado oposto da rodovia. Preparem-se...",--A sniper is about to set up a position on the opposite side of the highway. Be ready...
	pln_esc_garage_02_any_02 = "Vão até o nível da rua, tem uma van esperando por vocês.",--Work your way up to street level, I have a van ready to get you guys out of there!
	pln_esc_cafe_fixed_subway_01 = "Ok, prestem atenção, um contato meu vai pegar vocês em uma estação de metrô próxima.",--OK, listen up, a contact will get you out through a nearby subway station.
	pln_esc_requirement_01_bags = "Lembrem-se pessoal, nós precisamos de uma bolsa para fugir.",--Remember guys, we need at least one bag to escape.
	pln_esc_requirement_02_bags = "Lembrem-se pessoal, nós precisamos de duas bolsas para fugir.",--Remember guys, we need at least two bags to escape.
	pln_esc_warn_timelimit_heli = "Vocês vão ter que ir rápido quando o helicóptero chegar. Não vão conseguir resistir a pressão dos policiais.",--You'll have to move fast when the chopper arrives. It can't stay long with this amount of heat.
	pln_esc_01_to_departure_heli = "Rápido! Só falta um minuto!",--Hurry up! It's just one minute until take off!
	pln_esc_garage_02_any_01 = "Subam a garagem, a van está pronta pra levar vocês!",--Move up through the garage, a van is ready to get you out of there!
	pln_esc_overpass_swat_heli_incoming_01 = "Os policiais mandaram um helicóptero com a SWAT. Se preparem quando chegar.",--The cops have sent in a chopper carrying heavy SWATs. You better be ready when it arrives.
	pln_esc_cafe_warn_timelimit_subway_01 = "Vocês não tem muito tempo para fugir, então se preparem para ir pra estação do metrô.",--You won't have much time to escape, so be ready to move towards the subway station.
	pln_esc_requirement_06_bags = "Lembrem-se pessoal, nós precisamos de seis bolsas para fugir.",--Remember guys, we need six bags to escape.
	pln_esc_requirement_10_bags = "Lembrem-se pessoal, nós precisamos de dez bolsas para fugir.",--Remember guys, we need ten bags to escape.
	pln_esc_street_full_force_02 = "Os policiais estão bem putos depois de vocês terem matados os seus Snipers. Eles vão enviar a cavaleria toda!",--The cops are pissed that you just bagged their snipers. They're getting ready to send in the cavalry!
	pln_esc_street_snipers_nearby_03 = "Cuidado! Snipers estão cercando vocês aí!",--Stay low! Snipers have got you pinned!
	pln_esc_park_marksmen_rooftop_01 = "As SWATs estão no telhados, cuidado!",--SWATs are assuming positions on a nearby rooftop, watch out!
	pln_esc_street_swats_deployed_01 = "Os policiais estão percebendo que os Snipers não vão ser suficientes. Eles vão mandar a SWAT. Se preparem!",--The cops are realizing those snipers wont be enough to take you down. They're prepairing to send in SWATs. Get ready!
	pln_esc_08_to_departure = "O veículo de fuga vai ir embora em oito minutos.",--The escape vehicle is leaving in eight minutes.
	pln_esc_04_to_arrival = "Quatro minutos, pessoal.",--Four minutes left, guys.
	pln_esc_03_to_arrival = "Faltam três minutos.",--ETA is three minutes.
	pln_esc_garage_03_any_01 = "Ok, deem uma olhada em volta - Encontrem a van!",--OK look around - find the escape van!
	pln_esc_overpass_swat_heli_incoming_02 = "O helicóptero da SWAT está vindo. Se preparem para o fogo pesado.",--SWAT helicopter incoming. Get ready to face some heavy firepower.
	pln_esc_park_marksmen_building_02 = "Eles estão nos telhados dos prédios próximos... Fiquem de olho.",--They're taking up positions in a nearby building... Keep your eyes open.
	pln_esc_cafe_arrival_subway_01 = "Ok, a porta está aberta, entrem no metrô.",--OK, the gate is open, get to that subway entrance.
	pln_esc_street_snipers_deployed_02 = "Cuidado! Eles estão trazendo um Sniper pelo helicóptero!",--Watch out! They are bringing in a sniper team by chopper!
	pln_esc_30secs_to_arrival_heli = "O helicóptero vai chegar em 30 segundos. Preparem-se!",--The chopper touches ground in 30 seconds. Get ready to move!
	pln_esc_requirement_07_bags = "Lembrem-se pessoal, nós precisamos de sete bolsas para fugir.",--Remember guys, we need seven bags to escape.
	pln_esc_09_to_arrival = "O veículo de fuga vai chegar em nove minutos.",--The escape will be there in nine minutes.
	pln_esc_street_more_snipers_deployed_04 = "Os policiais estão mandando mais Snipers!",--The cops are deploying more snipers!
	pln_esc_street_more_snipers_deployed_05 = "Mais Snipers vindo!",--Additional snipers are entering the area!
	pln_esc_cafe_30secs_to_departure_subway_01 = "30 segundos, vão para entrada!",--30 seconds, get to the entrance!
	pln_esc_cafe_01_to_departure_01 = "Vocês só tem mais um minuto. Levem o loot para a entrada do metrô e caiam fora daí!",--You've only got one more minute. Get the loot to the subway entrance and get the hell out of there!
	pln_esc_04_to_departure = "Andem logo! O veículo de fuga vai ir embora em quatro minutos.",--Step it up! The escape vehicle is leaving in four minutes.
	pln_esc_05_to_arrival = "A sua carona vai estar aí em cinco minutos.",--Your ride will be there in about five minutes.
	pln_esc_05_to_departure = "Rápido, pessoal! O veículo de fuga vai ir embora em cinco minutos.",--Hurry up, guys! The escape vehicle is leaving in five minutes.
	pln_esc_07_to_arrival = "O veículo de fuga vai chegar aí em sete minutos.",--The escape will be there in seven minutes.
	pln_esc_07_to_departure = "O veículo de fuga vai ir embora em sete minutos.",--The escape vehicle is leaving in seven minutes.
	pln_esc_08_to_arrival = "O veículo de fuga vai chegar em oito minutos.",--The escape will be there in eight minutes.
	pln_esc_10_to_departure = "O veículo de fuga vai ir embora em dez minutos.",--Escape vehicle is leaving in ten minutes.
	pln_esc_30secs_to_departure_heli = "Vocês tem 30 segundos para entrarem nessa merda de helicóptero.",--You have 30 seconds to get your ass on that chopper.
	pln_esc_garage_01_any_01 = "Essa batida foi feia. Os policiais não vão desistir de vocês tão fácil, então andem logo!",--That was one hell of a crash. The cops aren't gonna give you a break though, so get on your feet!
	pln_esc_park_escape_location_01 = "A van deve chegar aí próximo ao parque.",--The van should arrive on a street near the park.
	pln_esc_park_marksmen_building_01 = "Cuidado, eles estão mandando a SWAT dentro do prédio próximo.",--Watch out, they are deploying SWATs inside a nearby building.
	pln_esc_requirement_03_bags = "Lembrem-se pessoal, nós precisamos de três bolsas para fugir.",--Remember guys, we need three bags to escape.
	pln_esc_requirement_05_bags = "Lembrem-se pessoal, nós precisamos de cinco bolsas para fugir.",--Remember guys, we need five bags to escape.
	pln_esc_requirement_09_bags = "Lembrem-se pessoal, nós precisamos de nove bolsas para fugir.",--Remember guys, we need nine bags to escape.
	pln_esc_street_chopper_arrived_01 = "O helicóptero chegou! Cuidado com os Snipers quando vocês estiverem movendo as bolsas!",--The chopper's here! Watch out for snipers when you're moving the loot!
	pln_esc_street_full_force_01 = "Esses Snipers não conseguiram parar vocês, então os policiais estão se preparando para atacar com força. Estejam preparados aó!",--Those snipers couldn't stop you, so the cops are prapairing to move in with force. Get ready!
	pln_esc_street_lookout_sniper_01 = "Um de vocês devem ficar de olho nesses Snipers a todo momento!",--One of you should keep an eye out for those snipers at all times!
	pln_esc_street_more_snipers_deployed_01 = "Mais Snipers chegando!",--More snipers are coming in!
	pln_esc_street_more_snipers_deployed_03 = "Uma equipe de Snipers está chegando!",--A sniper team is moving in!
	pln_esc_street_snipers_deployed_01 = "Um helicóptero chegando para colocar os Snipers no telhado.",--A police chopper is coming in to drop of sniper on a nearby building.
	pln_esc_street_snipers_nearby_02 = "Cuidado! Eles têm Snipers na área!",--Keep your heads down! They've got snipers in the area!
	pln_esc_street_swats_deployed_03 = "Cuidado, a SWAT está chegando aí para acabar com isso.",--Heads up, SWATs are moving in to try to finish this.
    pln_esc_01_to_arrival_heli = "O helicóptero vai chegar aí em um minuto.",--The chopper is one minute away.
    pln_esc_fixed_heli = "Pessoal, eu consegui um helicóptero para buscar vocês. Aguentem um pouco mais!",--Guys, I've secured a chopper to get you out. Stay put!
    pln_esc_pep = "Fiquem juntos! Vocês não podem se separar!",--Keep it together! You can't fall apart now!
    pln_esc_plan_b = "Vou tirar vocês daí. Só mantenham o loot seguro!",--I'll get you out of there. Just keep the loot safe!
    pln_esc_overpass_more_snipers_02 = "Os policiais estão mandando Snipers na área, tomem cuidado.",--The cops are deploying snipers in the area, don't walk into their sights.
    pln_esc_02_to_arrival = "Dois minutos até vocês cairem fora daí.",--Two minutes until you can get the hell out of there.
    pln_esc_start = "Cuidado, pessoal! Os policiais estão cercando vocês!",--Watch out, guys! The cops are surrounding you!
    pln_esc_fixed_van = "Beleza, pessoal! Uma van está chegando aí para buscarem vocês!",--Alright, guys! A van is coming in to get you out!
    pln_esc_03_to_departure = "Assegurem o loot se possível. O veículo de fuga vai ir embora em três minutos.",--Secure as much loot as you can. The escape vehicle is leaving in three minutes.
    pln_esc_02_to_departure = "O veículo de fuga vai sair em dois minutos, com ou sem você lá.",--The escape vehicle is leaving in two minutes, with or without you.
    pln_esc_01_to_arrival_van = "A van está logo na esquina. Vou estar aí em um minuto.",--The van is right around the corner. I'll be there in one minute.
    pln_esc_warn_timelimit_van = "A van não vai conseguir ficar por aí por muito tempo. Vocês vão ter que ir rápido quando ela chegar!",--The van won't be able to stay long. You gotta move fast when it arrives!
    pln_esc_30secs_to_arrival_van = "A van vai chegar em 30 segundos, estejam preparados desde já!",--The van will be there in 30 seconds - get ready!
    pln_esc_10secs_to_arrival = "Dez segundos.",--Ten seconds.
    pln_esc_arrival_van = "Beleza, a van chegou. Mexam-se!",--Alright the van is there. Move!
    pln_esc_01_to_departure_van = "A van vai ir embora em um minuto. Sejam rápidos!",--The van leaves in one minute. Wrap it up!
    pln_esc_30secs_to_departure_van = "30 segundos. Entrem na van ou vão ser deixados pra trás.",--30 seconds left. Get in the van or you'll be left behind.
    pln_esc_10secs_to_departure = "Dez segundos! Vai! Vai! Vai!",--Ten seconds! Move! Move! Move!

    -- Objetivos
	hud_pd2_garage_escape_hl = "Leve as Bolsas para a Van",--Get the loot to the van
	hud_pd2_garage_escape = "Leve as bolsas para van na rua.",--Get the loot into the escape van up on the street
	hud_pd2_park_escape = "Vá até o veículo de fuga.",--Get to the escape vehicle
	hud_pd2_park_secure = "Assegure as bolsas no veículo de fuga.",--Secure the loot in the escape vehicle
	hud_pd2_park_escape_only = "Vá até o veículo de fuga.",--Get to the escape vehicle
	hud_pd2_park_defend = "Bain está enviando um novo veículo de fuga que irá chegar em pouco tempo.",--Bain is sending you a new escape vehicle that will arrive shortly
	hud_pd2_park_escape_only_hl = "Fuga Disponível",--Escape available
	hud_pd2_park_defend_hl = "Sobreviva até que o Novo Veículo de Fuga Chegue",--Stay alive until the new escape vehicle arrives
	hud_pd2_park_escape_hl = "Fuga Disponível",--Escape available
	hud_pd2_park_secure_hl = "Assegure as Bolsas",--Secure the loot
    }