return {
	-- Nomes e Descrições
	--heist_arm_for = "Transport: Train Heist",--Transport: Train Heist
	--heist_arm_for_hl = "Transport: Train Heist",--Transport: Train Heist
	heist_arm_for_crimenet = "Aquele projeto que vocês encontraram no último trabalho era para um protótipo de uma arma de infantaria, um novo tipo de Turret. Também com muita munição que vocês podem roubar. $NL;$NL;» Encontre e entre no Vagão Correto$NL;» Pegue o Protótipo da Turret$NL;» Desmonte e Assegure os Componentes da Turret$NL;» Adquira a quantidade necessária de Munição$NL;» Assegure tudo no Veículo de Fuga",--That blueprint you found in the last job was for a prototype infantry weapon, a new kind of Turret. It's also carrying significant amounts of ammunition, which you can also try to retrieve. $NL;$NL;» Find and break into the correct railcar$NL;» Recover the prototype Turret$NL;» Dismantle and secure the Turret components$NL;» Acquire the required amounts of ammunition$NL;» Secure all items in the waiting vehicle
	heist_arm_for_briefing = "Aquele projeto que vocês encontraram era de um novo tipo de Turret de infantaria - nomeada RC1. Uma merda de próxima geração. Cavando mais fundo, ouvi falar de um trem carregado, indo direto ao Pentágono. Eu hackeei o sistema dos trilhos, e acho que eles pararam por causa de um erro no sistema. Três vagões. Um tem o nosso hardware. Os outros dois tem a sua munição. Tudo se vende, mas a nossa prioridade é a Turret. Eles não vão estar esperando por vocês.",--That blueprint you found was for a new type of infantry Turret - codenamed RC1. Real next-gen shit. Digging a little deeper, I got word of a specially chartered train, headed in to the Pentagon. I've hacked the rail network, and they think they've stopped due to a glitch in the switches. Three railcars. One has the hardware. The other two have its ammo. It all sells, but your priority is the Turret. They won't be expecting you.
	--heist_arm_par = "Transport: Park",--Transport: Park
	--heist_arm_par_hl = "Transport: Park",--Transport: Park
	heist_arm_par_crimenet = "O Bain interceptou um comboio de carros-fortes da GenSec. Eles estão transportando itens de alto valor e vocês precisam roubar tudo, e rápido.$NL;$NL;» Entre nos Carros-Fortes$NL;» Abra os Cofres$NL;» Leve o espólio para o nosso Veículo de Fuga",--Bain has intercepted a convoy of armored GenSec trucks. They're carrying high-value cargo and you need to get in fast and steal it.$NL;$NL;» Break into the immobilized trucks$NL;» Crack open the strongboxes$NL;» Get the loot to the getaway vehicle
	heist_arm_par_briefing = "O pessoal da hora do almoço no Sherping Memorial Park geralmente não vê nada mais emocionante do que um pombo dando uma cagada, então façam um belo show para eles, cavalheiros. Vocês tem carros-fortes da GenSec e seus cofres dentro deles para lidar.",--The lunch-time crowd at Sherping Memorial Park usually don't see anything more exciting than a pigeon taking a crap, so put a good show on for them, gentlemen. You got GenSec trucks and the strongboxes inside to deal with.
	--heist_arm_fac = "Transport: Harbor",--Transport: Harbor
	--heist_arm_fac_hl = "Transport: Harbor",--Transport: Harbor
	heist_arm_fac_crimenet = "O Bain interceptou um comboio de carros-fortes da GenSec. Eles estão transportando itens de alto valor e vocês precisam roubar tudo, e rápido.$NL;$NL;» Entre nos Carros-Fortes$NL;» Abra os Cofres$NL;» Leve o espólio para o nosso Veículo de Fuga",--Bain has intercepted a convoy of armored GenSec trucks. They're carrying high-value cargo and you need to get in fast and steal it.$NL;$NL;» Break into the immobilized trucks$NL;» Crack open the strongboxes$NL;» Get the loot to the getaway vehicle
	heist_arm_fac_briefing = "Nós usaremos um guindaste com um imã para largar um presente no caminho do comboio da GenSec - um contêiner cheio de profissionais. Roubem os carros-fortes, e tragam os espólios para o nosso veículo. Essas Docas tem uma rica história com roubos, cavalheiros - Façam o seu melhor.",--We're using a magnetic crane to drop a little present in the path of the GenSec convoy - a steel contêiner of professional badasses. Hit the trucks, and get the loot to the getaway. These docks have a rich history of heistery, gentlemen - do it proud.
	--heist_arm_cro = "Transport: Crossroads",--Transport: Crossroads
	--heist_arm_cro_hl = "Transport: Crossroads",--Transport: Crossroads
	heist_arm_cro_crimenet = "O Bain interceptou um comboio de carros-fortes da GenSec. Eles estão transportando itens de alto valor e vocês precisam roubar tudo, e rápido.$NL;$NL;» Entre nos Carros-Fortes$NL;» Abra os Cofres$NL;» Leve o espólio para o nosso Veículo de Fuga",--Bain has intercepted a convoy of armored GenSec trucks. They're carrying high-value cargo and you need to get in fast and steal it.$NL;$NL;» Break into the immobilized trucks$NL;» Crack open the strongboxes$NL;» Get the loot to the getaway vehicle
	heist_arm_cro_briefing = "Nós forçamos os carros-fortes da GenSec para fora da rua no cruzamento da McCarty e James. Claro que tem aqueles hipsters do Time Out cagando em seus latte macchiatos. Vocês vão precisar entrar nos carros-fortes e abrir os cofres dentro. Seja o que eles estejam carregando. peguem e fujam.",--We've forced the GenSec trucks off the road at the corner of McCarty and James. Sure it had those Time Out hipsters shitting into their latte macchiatos. You're going to need to get into the trucks, and then break open the strongboxes inside. Whatever they're carrying, get it, and get out.
	--heist_arm_hcm = "Transport: Downtown",--Transport: Downtown
	--heist_arm_hcm_hl = "Transport: Downtown",--Transport: Downtown
	heist_arm_hcm_crimenet = "O Bain interceptou um comboio de carros-fortes da GenSec. Eles estão transportando itens de alto valor e vocês precisam roubar tudo, e rápido.$NL;$NL;» Entre nos Carros-Fortes$NL;» Abra os Cofres$NL;» Leve o espólio para o nosso Veículo de Fuga",--Bain has intercepted a convoy of armored GenSec trucks. They're carrying high-value cargo and you need to get in fast and steal it.$NL;$NL;» Break into the immobilized trucks$NL;» Crack open the strongboxes$NL;» Get the loot to the getaway vehicle
	heist_arm_hcm_briefing = "Uma passarela em Downtown, dois quilos de C4 estrategicamente colocados e um timing impecável nos deu um comboio de carros-fortes da GenSec. Derrubem eles enquanto eles estiverem desorientados. Roubem os carros-fortes e os cofres, e retornem tudo ao nosso veículo de fuga.",--One downtown skyway, five pounds of strategically placed C-4 and impeccable timing has given us a stranded convoy of GenSec trucks. Hit them hard while they're still disoriented. Break into the trucks and the strongboxes, and return the goodies to the escape driver.
	--heist_arm_und = "Transport: Underpass",--Transport: Underpass
	--heist_arm_und_hl = "Transport: Underpass",--Transport: Underpass
	heist_arm_und_crimenet = "O Bain interceptou um comboio de carros-fortes da GenSec. Eles estão transportando itens de alto valor e vocês precisam roubar tudo, e rápido.$NL;$NL;» Entre nos Carros-Fortes$NL;» Abra os Cofres$NL;» Leve o espólio para o nosso Veículo de Fuga",--Bain has intercepted a convoy of armored GenSec trucks. They're carrying high-value cargo and you need to get in fast and steal it.$NL;$NL;» Break into the immobilized trucks$NL;» Crack open the strongboxes$NL;» Get the loot to the getaway vehicle
	heist_arm_und_briefing = "Nós vamos roubar o comboio da Gensec de baixo de uma ponte, em rota de Dulles até o depósito em McLean, então espere achar coisa valiosa. Peguem o que tiver no comboio e levem pro seu piloto de fuga. Estamos em uma região mais agressiva, então esperem a polícia mais rápida da D.C.",--We hit the Gensec convoy at the underpass, en-route from Dulles to their depot in McLean, so expect rich pickings. Get whatever's in the trucks to your escape driver. We're deep in Indian country here, gentlemen, so expect a fast response from D.C.'s finest.
	
	-- Legendas (Transport: Train Heist)
	pln_tr1_intro_01_01 = "Encontrem o vagão com a Turret. Vocês podem tentar um Cartão de Acesso em algum lugar para acelerar as coisas.",--Find the railcar with the Turret. You might be able to find an access card somewhere to speed things up.
	pln_tr1_intro_01_02 = "Vocês precisam chegar mais perto e encontrar o vagão correto. Quando acharem, deem uma olhada em volta - vocês podem acabar achando um Cartão de Acesso para os vagões.",--You need to get close and locate the right railcar. Once you've ID'd it, look around - you might be able to find an access card for the railcars
	pln_tr1_11_01 = "É isso, Pegamos a Turret. Vou chamar um veículo para vocês.",--That's it. We got the Turret. Im sending your pick-up ASAP.
	pln_tr1_11_03 = "Ótimo. É isso que viemos buscar. Estou trazendo o veículo de fuga. Apenas fiquem vivos por mais um pouco.",--Great. That's what we came for. I'm sending your getaway. Just stay alive a little longer.
	pln_tr1_20_01 = "A furadeira está na área. Peguem, e comecem a trabalhar naquele cofre.",--The drill is in the area. Get it, and get it to work on that vault.
	pln_tr1_17_01 = "Bom achado. Esse cartão vai nos deixar entrar nos vagões.",--Good find. This keycard will get you into the railcars. 
	pln_tr1_16_02 = "O helicóptero largou a furadeira, gangue. Peguem ela e coloquem no cofre.",--The chopper just dropped off the drill, gang. You need to fetch it and get it to those vaults.
	pln_tr1_06_01 = "Quase abrindo a porta. Se preparem.",--Almost through the vault door. Get ready.
	pln_tr1_19_02 = "Gangue, vocês precisam localizar aquela Turret.",--Gang, you need to locate that Turret.
	pln_tr1_22_02 = "Movam as peças do canhão para o veículo, gangue.",--Move the pieces of the cannon to the pick-up, gang.
	pln_tr1_25_02 = "O piloto sinalizou que está largando a furadeira. Ele fez seu trabalho, agora façam o de vocês.",--The pilot just signaled that he's deploying the lance. He's done his job, now you do yours. 
	pln_tr1_14_03 = "Tenham cuidado com aquelas bolsas, gangue. Elas não lidam tão bem com a ação.",--Be very careful with those bags, gang. They don't take the rough stuff well.
	pln_tr1_09_03 = "Droga. Os canais locais estão acendendo! Esperem companhia.",--Damn it. Local channels just lit up! Expect company.
	pln_tr1_03_01 = "É isso! É o que estavamos procurando. Vou mandar a furadeira agora.",--That's it! That's what we're looking for. I'm sending the drill now.
	pln_tr1_05_01 = "Bom trabalho. Aquela munição vai ser um ótimo prêmio.",--Good work. That ammo will fetch a nice price.
	pln_tr1_13_03 = "Ok, entramos no vagão. Usem a câmera para ver o que tem dentro.",--OK, we're into the railcar. Use the camera to see what's inside.
	pln_tr1_24_01 = "Piloto na cena com a furadeira. Vão pegar.",--Pilot is on the scene with the lance. Go get it.
	pln_tr1_17_02 = "É um Cartão de Acesso para os vagões. Isso deve acelerar as coisas.",--It's a security keycard for the railcars. That should speed things up.
	pln_tr1_01_03 = "Um Cartão de Acesso. Ótimo! Isso vai ajudar a entrar silenciosamente no vagão.",--An access card. Great! That will help you get silent access to a railcar.
	pln_tr1_03_02 = "Belo dia! Isso é o que viemos pegar, gangue. A furadeira está a caminho daí.",--Paydirt! That's what we came for, gang. The drill is on its way.
	pln_tr1_21_02 = "Pessoal, a Turret - desmontem-a.",--Guys, the Turret - take it apart.
	pln_tr1_end_01_02 = "É assim que os profissionais fazem! Pagar tudo. Gangue PAYDAY 1, Polícia de Armadillo 0.",--That's how the pros do it! Chalk it up. Payday Gang one, Armadillo corp zero.
	pln_tr1_30_01 = "Podemos pegar a munição, mas só quando tivermos pego todas as peças da Turret. Escondam a munição por enquanto.",--We can get the ammo out, but only when the Turret pieces are safely gathered in. Hide that ammo for now.
	pln_tr1_13_01 = "Verifiquem a câmera para ver o que tem no cofre.",--Check the camera and see what's in the vault.
	pln_tr1_10_03 = "Droga! Certo, vou mandar a furadeira. Vocês vão ter que abrir cada cofre até achar a Turret.",--Damn! Alright, I'm sending the drill. You'll have to open each vault til you find the Turret.
	pln_tr1_12_01 = "Ali está. Desmonte-a e tirem todas as peças daí.",--There it is. Break that down and get each piece out.
	pln_tr1_26_01 = "Ok, o piloto está a caminho com outra furadeira. Vocês são mesquinhos. Eu respeito isso.",--OK, the pilot is on the way with another lance. You guys are greedy. I respect that.
	pln_tr1_01_01 = "Esse cartão deve nos dar acesso a um dos vagões",--That card should get you entry to one of the train railcars.
	pln_tr1_17_03 = "Bom. Esse é o cartão para os vagões",--Nice. That's the keycard for the railcars. 
	pln_tr1_15_03 = "Prestem atenção no helicóptero.",--Keep an eye out for the chopper.
	pln_tr1_29_01 = "É isso! É isso que estavamos procurando.",--That's it! That's what we're looking for.
	pln_tr1_16_03 = "A furadeira foi entregue. Encontrem-a e levem ao cofre.",--The drill has been delivered. Find it and get it to those vaults.
	pln_tr1_15_02 = "O helicóptero está na área. Olhem pro céu.",--The chopper is in the area. Watch the skies.
	pln_tr1_end_02_01 = "Foi uma bagunça, mas vocês conseguiram. Bom trabalho!",--It was messy but you got the job done. Nice work!
	pln_tr1_end_02_02 = "Isso foi um negócio bem sangrento, mas as vezes é assim. mesmo assim, o trabalho foi feito. Bom trabalho!",--That was a bit of bloody business, but sometimes it gets like that. Still, job done. Great work!
	pln_tr1_02_02 = "Esses são os materiais, mas não a Turret. Peguem se puderem mas continuem olhando.",--That's the ordnance, but it's not the Turret. Get it out if you can, but keep looking.
	pln_tr1_28_02 = "Eles estão usando o C4 para estourar as portas. Acho que eles não sabem da munição que o vagão carrega.",--They're using C4 to blast those doors. Guess they don't know about all the live ammo that train is carrying.
	pln_tr1_01_02 = "Aqueles vagões estão trancados. O cartão deve ajudar.",--Those railcars are locked down. That card should help with that.
	pln_tr1_02_01 = "Podemos vender aquelas balas, se quiserem carregar. Mas foquem na Turret.",--We can sell those shells, if you can carry them out. But focus on the Turret.
	pln_tr1_02_03 = "É a munição. Tentem tirar daí, mas não percam o foco no nosso objetivo.",--That's volatile stuff. Try and get it out, but don't lose sight of the goal.
	pln_tr1_03_03 = "Uma tecnologia, de alto valor militar bem foda logo ali. Perfurem e entrem.",--One high-tech, high-value piece of military badass right there. Drill en-route.
	pln_tr1_04_01 = "Ótimo. Mexam-se!",--Great. Get it moving!
	pln_tr1_04_02 = "Essa é a coisa. Continuem se movendo!",--That's the stuff. Keep going!
	pln_tr1_04_03 = "Bom trablho. Agora levem ao veículo.",--Good job. Now get it to the pick-up.
	pln_tr1_05_02 = "Ótimo. Não tem limite de compradores para aquelas balas militares.",--Great. There's no shortage of buyers for these military rounds.
	pln_tr1_05_03 = "Muito bom. É tudo dinheiro extra, graças ao exército.",--Well done. It's all extra gravy, thanks to the US Army.
	pln_tr1_06_02 = "A furadeira está quase pronta. Esperem um pouco, gangue.",--The drill is almost done. Stand by, gang.
	pln_tr1_07_01 = "A Fuga de vocês já está pronta, peguem o máximo de munição que puderem, e então saiam daí.",--Your getaway is ready Get as much ammo as you can, and then get yourselves out.
	pln_tr1_07_02 = "Ok, o veículo de fuga está pronto. Ele pode carregar tanta munição quanto puderem levar, caso queiram um bônus. Vocês decidem.",--OK, your pick-up is ready. It can carry as much ammo as you can get to it, if you want a bonus. Up to you.
	pln_tr1_07_03 = "Ok, a fuga de vocês está esperando. Saiam agora, ou peguem a munição. A escolha é de vocês, pessoal.",--OK, your getaway is standing by. Bail now, or use it to clear out the ammo. Your call.
	pln_tr1_08_01 = "Isso é uma munição explosiva, tenham cuidado.",--That's live high explosive, so be gentle.
	pln_tr1_08_02 = "Lidem com essas coisas com muito cuidado.",--Handle that stuff with great care.
	pln_tr1_08_03 = "Cuidado. Muito cuidado.",--Gently does it. Very gently.
	pln_tr1_09_01 = "É o Alarme, pessoal. Esperem uma reação rápida!",--That's the alarm, guys. Expect a fast response!
	pln_tr1_09_02 = "Merda, é o alarme. Preparem-se para a ação!",--Damn, that's the alarm. Get ready for action!
	pln_tr1_10_01 = "Nada de ir furtivos agora. Vou mandar um helicóptero com a furadeira.",--No need for tip-toeing now. I'm sending the chopper with the drill.
	pln_tr1_10_02 = "É o Alarme. As câmeras cairam. Perfurem o cofre até acharem a Turret.",--There's the alarm. Camera feeds are down. Drill the vaults till you find the Turret.
	pln_tr1_11_02 = "Esse é a Turret recuperada. Me dê só um momento. O veículo de fuga está quase chegando.",--That's the Turret recovered. Give me a moment. Your pick-up is on its way.
	pln_tr1_12_02 = "Ótimo. Ali está. Desmontem e tirem as peças daí.",--Great. There it is. Disassemble it and then move the pieces out.
	pln_tr1_13_02 = "Passamos pela primeira fechadura. Vejam o que tem dentro.",--We're past the first lock. Now let's see what's inside.
	pln_tr1_14_01 = "Wow! Tenham cuidado com isso. É munição militar explosiva que vocês estão jogando.",--Woah! Be careful with that stuff. That's military grade explosives you're throwing around.
	pln_tr1_14_02 = "Essas balas são bem temperamentais. E bem valiosas. Tenham cuidado.",--Those shells have an angry temper. And a dollar value. Be careful with them.
	pln_tr1_15_01 = "Ok, o helicóptero está quase chegando. Esperem um pouco.",--OK, the chopper is almost there. Stand by.
	pln_tr1_16_01 = "Ok, a furadeira está no chão. Peguem e abram aqueles cofres.",--OK, the drill is on the ground. Get it and get those vaults open.
	pln_tr1_18_01 = "Fiquem atentos por um Cartão de Acesso.",--Keep your eyes open for a keycard. 
	pln_tr1_18_02 = "Talvez esses trabalhadores possuem um Cartão de Acesso para os vagões.",--Maybe some of those workers have a keycard for the railcars.
	pln_tr1_18_03 = "Agitem os trabalhadores. Talvez um deles tenha o cartão.",--Shake those workers down. Maybe one of them has a keycard.
	pln_tr1_19_01 = "Pessoal, entrem nos vagões e encontrem o que tem a Turret.",--Guys, get into those cars and find the one with the Turret.
	pln_tr1_20_02 = "Furadeira na área. Façam ela trabalhar no cofre.",--Drill is dropped. Get it working on the vault.
	pln_tr1_21_01 = "Vocês precisam desmontar a Turret.",--You need to dismantle that Turret.
	pln_tr1_22_01 = "Pessoal, vocês precisam levar as peças para o veículo de fuga.",--Guys, you need to get those pieces to the pick-up.
	pln_tr1_24_02 = "Aquele é o nosso piloto com a furadeira. Peguem.",--That's the pilot with the lance. Get it.
	pln_tr1_25_01 = "Nosso piloto está largando a furadeira. E largando que eu digo é jogar da janela.",--Our pilot's deploying the lance. And by deploying I mean kicking out of the window.
	pln_tr1_26_02 = "Helicóptero a caminho com outra furadeira.",--Chopper is on its way with another lance. 
	pln_tr1_27_01 = "Essas são as balas da Turret. Valiosas, mas não é o nosso prêmio principal. Peguem a Turret, e poderão voltar para pegar as munições.",--These are the shells for the Turret. Valuable, but not the main prize. Get the Turret, and then come back for this ordnance.
	pln_tr1_27_02 = "Essa é a munição da Turret. Podemos pegar depois, mas achem a Turret.",--That's the Turret ammo. We can take that later, but keep after the Turret.
	pln_tr1_28_01 = "Eles estão arrombando as portas com C4. Eles não querem vocês aí.",--They're blasting the train doors with demo charges. They really don't want you guys in there!
	pln_tr1_28_03 = "Eles estão explodindo as portas dos vagões. Vocês vão ficar expostos a Snipers, tenham cuidado.",--They're blowing the doors off the railcars. You're going to be exposed to sniper fire in there, so be careful.
	pln_tr1_29_02 = "Que recompensa! É isso que viemos pegar, gangue.",--Paydirt! That's what we came for, gang.
	pln_tr1_29_03 = "Uma tecnologia, de alto valor militar bem foda bem aí.",--One high-tech, high-value piece of military badass right there.
	pln_tr1_30_02 = "Não podemos tirar a munição até todas as partes da Turret estiverem no veículo. Guardem a munição para depois. Foquem em assegurar a Turret.",--We can't get the ammo out until all those Turret pieces are in the vehicle. Stash the ammo for later. Focus on securing the Turret.
	pln_tr1_end_01_01 = "Trabalho absolutamente incrível! Vai ter muitas cabeças rolando pelos corredores do Pentágono quando esse trem chegar.",--Absolutely outstanding work! There's going to be heads rolling down the corridors of the Pentagon when this train arrives.
	pln_tr1b_01_02 = "Lá se vai o alarme. E as camêras também.",--There's goes the alarm. And our camera feeds with it.
	pln_tr1b_cnc_01_02 = "O trem que está transportando o protótipo foi parado um pouco antes da cidade. Vão lá, peguem a Turret.",--We got the train moving the prototype Turret stopped at signals outside the city. Get there, get that Turret.
	pln_tr1b_07_01 = "Estou reconectado. Obrigado.",--I'm reconnected. Thanks.
	pln_tr1b_05_03 = "Ótimo, vamos dar uma olhada nisso. Hmmm, bom. Boa segurança, mas nada que eu não possa lidar.",--Great, lets take a peek under the hood. Hmmm, nice. Good security, but nothing I can't handle.
	pln_tr1b_cbf_01_01 = "A planta que vocês encontraram era para um novo tipo de Turret. Parece que o governo vai transportar isso em breve. Se agirmos rápido, podemos pegar eles de surpresa e roubar sem ninguem notar.",--The blueprint you found was for a new Type of Turret. It looks like the government is transporting it soon. If we act fast, we can catch them off guard and steal it without anyone noticing.
	pln_tr1b_01_03 = "Droga! Certo! Estou mandando a furadeira.",--Damn! Alright, I'm sending the drill.
	pln_tr1b_cnc_01_03 = "Nós vamos roubar um protótipo da Turret do Governo. Vão até o trem fora da cidade, abram eles e peguem a Turret.",--We're going to steal a prototype Turret from the Government. Get to the train outside the city, crack it open and get it.
	pln_tr1b_07_02 = "Estou de volta. *susurro* Não tem colher.",--I'm back in. *whispers* There is no spoon.
	pln_tr1b_02_01 = "É isso. Pegamos a Turret. Agora precisamos da munição.",--That's it. We got the Turret. Now all we need is some ammo.
	pln_tr1b_04_02 = "Cada cofre tem um sistema de segurança, e aquele drive vai hackear eles. Vai ser útil.",--Each vault door has a security system, and that drive will hack it open. Should be useful.
	pln_tr1b_02_03 = "Ótimo! É isso que viemos pegar. Quando o motorista descarregar, ele vai voltar para a coleta da munição.",--Great! That's what we came for. Once the driver drops 'em off, he'll return for the ammo.
	pln_tr1b_03_03 = "As balas estão escondidas agora. Bom trabalho, vou mandar a fuga de vocês até aí.",--The shells are tucked away. Nice work, I'm sending your getaway.
	pln_tr1b_cnc_01_01 = "O governo nos deve dinheiro do almoço. Parece que vamos pegar a Turret e algumas bolsas de munição deles como compensação.",--The government owes us lunch money. Looks like we'll be taking their Turret and a few bags of ammo as compensation.
	pln_tr1b_04_01 = "Coloquem aquele HD no cofre do trem, eu devo poder hackear e abrir.",--Plug that hard-drive into one of the train vault security systems, I should be able to hack it open.
	pln_tr1b_01_01 = "Não há necessidade de andar na ponta dos pés. Estou mandando a furadeira.",--No need for tip-toeing now. I'm sending the drill.
	pln_tr1b_02_02 = "Essa é a Turret recuperada. O motorista vai voltar pela munição.",--That's the Turret recovered. The driver will be back for the ammo.
	pln_tr1b_03_01 = "Parece que pegamos tudo, gangue, a fuga de vocês está a caminho.",--Looks like we got everything, gang, Your pick-up is on its way.
	pln_tr1b_03_02 = "Munição assegurada, estou mandando o veículo de fuga pra vocês agora. Preparem-se!",--Ammo secured, I'm sending your pick-up ASAP. Be ready!
	pln_tr1b_04_03 = "Poderemos hackear o cofre do trem se colocarem aquele HD no painel de segurança do trem.",--We can hack open a train vault if you plug that hard-drive into its security panel.
	pln_tr1b_05_01 = "Bom, eu entrei. Wow, sistema bem seguro. Quem são esses caras, setor 9?",--Nice, I'm in. Wow, pretty nifty security. Who are these guys, section 9?
	pln_tr1b_05_02 = "Certo, entrei! *assobio* Esses caras não estão brincando. Muitos firewalls adicionais.",--Alright I'm in! *whistles, impressed* These guys aren't messing around. Lots of additional firewalls.
	pln_tr1b_06_01 = "Me bloquearam. Preciso que desconectem o buffer de segurança.",--They've blocked me. I need you to disconnect their security buffer.
	pln_tr1b_06_02 = "Um dos buffers de segurança deles ativou. Desconectem!",--One of their security buffers just kicked in. Disconnect it!
	pln_tr1b_06_03 = "Outro buffer de segurança apareceu. Vocês vão precisar desconectar manualmente.",--Another security buffer kicked in.Need to be disconnected manually.
	pln_tr1b_07_03 = "Ok, estou de volta.",--Alright, I'm back in.
	
	-- Legendas (Outras Transport)
	pln_at1_dow_04_01 = "Boom! Não poderia ser melhor. Todos os quatro carros-forte pararam e estão prontos para vocês. Vão pegar!",--Boom! That couldn't have gone better. All four trucks are stopped and ready for your attention. At 'em, gang!
	pln_at1_gen_13_01 = "Ótimo trabalho! Eu já chamei o helicóptero, continuem roubando!",--Great job! I'm sending the helicopter, keep looting!
	pln_at1_end_03b_01 = "Eu tenho pessoas interessantes que podem pegar o ouro. Eu também vou ver sobre o que era aquele projeto.",--I've already got interested parties lined up to take the bullion. I'll also dig up what I can regarding this blueprint.
	pln_at1_cnc_05_01 = "O viaduto é um local vulnerável ao comboio. Mandem ver.",--The underpass is a vulnerable spot for the convoy. Hit it hard.
	pln_at1_gen_12_01 = "Ótimo trabalho! Estou mandando uma lancha, continuem roubando!",--Great job! I'm sending the boat, keep looting!
	pln_at1_cbf_01_01 = "Eu sei que vocês ja mexeram com a GenSec antes. Eles são a principal empresa de segurança da Costa Leste. Mas deixando isso de lado, esses caras são sérios. Hoje, a gente pega eles.",--I'm sure you guys have tangled with GenSec before. They're the East Coast's premier provider of security solutions, if you believe their brochure. But, PR aside, these guys are serious. Today, we hit them.
	pln_at1_intro_02_01 = "Nosso cara está em posição, e o alvo virou McCarty. Quase lá. Quase lá...",--Our man is in position, and the target just turned on to McCarty. Almost there. Almost there...
	pln_at1_gen_14_02 = "Está aberto! Abram as caixas de depósito!",--It's open! Open those deposit boxes!
	pln_at1_intro_06_02 = "GenSec se aproximando. Vamos começar. Ok, acertem.",--GenSec on approach. Let's get this jam started. OK, hit it.
	pln_at1_end_03_02 = "Isso deve valer uma fortuna! Ótimo trabalho!",--That's gonna be worth a fortune! Great job!
	pln_at1_gen_07_01 = "Enquanto estão ai, vejam se vocês conseguem achar algo nessas lojas que valem algo.",--While you're at it, see if you can find anything in those stores that's worth some cash.
	pln_at1_gen_19_01 = "Vocês abriram o primeiro carro-forte. Agora abram as caixas e peguem os espólios. Cinco bolsas, então mexam-se, pessoal!",--You're through the first truck. Now start cracking boxes and bagging loot. Five bags, so move it, guys!
	pln_at1_gen_09_03 = "Eita, perdemos alguns espólios nessa explosão! Sem tempo a perder! Olhem o resto das caixas de depósito.",--Woah, we lost some loot in that explosion! Well, no time to waste! Look trough the rest of the deposit boxes.
	pln_at1_intro_04_02 = "Ok, pessoal, lá vem eles. Movam o guindaste!",--OK, guys, here they come. Get that crane moving!
	pln_at1_gen_06_02 = "Vocês provavelmente devem conseguir um pouco de cobertura vindo de algum dos telhados.",--You could probably get some good covering fire going from one of those roof tops.
	pln_at1_end_01b_01 = "Ótimo trabalho. Vou chamar meus contatos para pegar as bolsas. E ver de perto esse projeto que vocês acharam. Fiquem espertos.",--Great job. I'll get my contacts fencing the shinies. And see what I can find out about that blueprint. Stay tuned.
	pln_at1_gen_15_02 = "Certo, ele está aqui! Tragam os espólios pra cá!",--Alright he's here! Get the loot over there!
	pln_at1_end_01_02 = "Ótimo trabalho cavalheiros!",--Great job gentlemen!
	pln_at1_gen_14_03 = "Está aberto! Peguem os espólios na caixa de depósito!",--It's open! Get the stuff out of the deposit boxes!
	pln_at1_intro_04_01 = "Alvo avistado. Só preciso colocar vocês na posição e...",--The target is spotted. Just need to get you into position and...
	pln_at1_cnc_04_01 = "É um lindo dia para um piquenique no parque. E um roubo armado.",--It's a beautiful day for a picnic at the park. And an armed robbery. 
	pln_at1_gen_01_01 = "Polícia a caminho! Vamos lá!",--Cops on the way! Let's go!
	pln_at1_cro_02_01 = "Mas que tiro! Ele pegou eles mesmo! Agora, vamos fazer a nossa parte. Peguem os espólios!",--That's one hell of a shooter! He got 'em good! Now, let's do our part. Let's get our loot!
	pln_at1_gen_08_01 = "Usem aqueles escritórios para uma breve vantagem!",--Use those offices as your advantage!
	pln_at1_intro_06_01 = "Nosso motorista pegou uma ambulância e correu com ela. E agora lá vem o alvo, bem na hora...",--Our driver has pulled the ambulance over and ran for it. And here comes the target, right on schedule...
	pln_at1_gen_11_03 = "Certo! A van deve estar a caminho!",--Alright! The van should be coming in soon!
	pln_at1_par_04_01 = "Isso é um sonho realizado, gangue. Cada um dos carros-forte estão prontinhos para serem pegos. Ao trabalho!",--That's a Royal Flush, gang. Every God damn truck is ready for the picking. Get to work!
	pln_at1_gen_08_02 = "Comecem o tiroteio!",--Get some cross fire going!
	pln_at1_gen_20_01 = "Bem, o que temos aqui? Projetos militares! Deixe-me investigar isso.",--Well, what do have we here? Military blueprints! Let me investigate this. 
	pln_at1_gen_02_01 = "Usem qualquer coisa que vocês tiverem para abrir essas merdas!",--Use whatever you got to open that sucker up!
	pln_at1_gen_15_01 = "Ele chegou, Joguem essas coisas!",--He's here, throw in the stuff!
	pln_at1_und_02_01 = "A barricada funcionou e dois transportes pararam. Vão ao trabalho, e abram tudo.",--The roadblock worked and two transports have stopped. Get to work, and get 'em open!
	pln_at1_gen_05_03 = "Levem as bolsas para a van!",--Get the bags to the van!
	pln_at1_gen_13_03 = "Certo! O helicóptero deve estar chegando!",--Alright! The helicopter should be coming in soon!
	pln_at1_har_03_01 = "Espero que vocês estajam bem aí. Três carros-forte apareceram. Quando as portas abrirem, peguem eles!",--Hope you guys are holding up in there. Three trucks have pulled over. When the doors open, get at them!
	pln_at1_gen_07_02 = "Verifiquem as lojas se quiserem mais dinheiro.",--Check the stores if you want some extra money.
	pln_at1_intro_01_01 = "Certo! Paramos o comboio, agora abram eles e peguem os espólios!",--Alright! We stopped the convoy, now get it open and secure the loot!
	pln_at1_intro_02_02 = "Os carros-forte da GenSec apareceram em nossa mira. Esperem... Esperem...",--The GenSec trucks just turned into our guy's sight. Wait for it... Wait for it...
	pln_at1_gen_11_01 = "Bom trabalho! Estou mandando a van, continuem pegando os espólios!",--Great job! I'm sending the van, keep looting!
	pln_at1_und_04_01 = "Excelente trabalho! Todos os quatro carros-forte pararam. Façam chover, pessoal!",--Outstanding work! All four trucks are stopped and ready. Make it rain, guys!
	pln_at1_gen_05_01 = "Bom trabalho, agora levem as bolsas até a van para que possamos sair daqui!",--Good job, now get the bags to the van so we can get the hell out of here!
	pln_at1_har_02_01 = "Desculpe pelas acomodações, mas vai valer a pena. Dois carros-forte ali fora. Quando as portas abrirem, acertem eles!",--Sorry about the accommodations, but it will be worth it. We got two trucks out there. As soon as the doors open, hit them hard!
	pln_at1_gen_02_02 = "Abram, e peguem o que estiver dentro!",--Get that open, and get whatever is in there!
	pln_at1_gen_12_02 = "Estou mandando a lancha, continuem pegando as coisas!",--I'm sending the boat, keep bagging the stuff!
	pln_at1_gen_11_02 = "Estou mandando a van, continuem pegando as coisas!",--I'm sending the van, keep bagging the stuff!
	pln_at1_gen_12_03 = "Certo! A lancha deve estar vindo!",--Alright! The boat should be coming in soon!
	pln_at1_cro_03_01 = "Ótima mira. Três carros-forte cairam. Eles estão aqui, gangue - vão lá.",--Outstanding marksmanship. Three trucks got it. They're ready, gang - get out there.
	pln_at1_gen_09_01 = "Wow, um pouco do espólio foi perdido na explosão. Sorte a nossa que tem mais ali.",--Woah, some of the loot got caught in that explosion. Lucky for us, there is more in there.
	pln_at1_dow_01_01 = "Bem, sem volta agora! Que batida incrível! Vão para aquele carro-forte e façam o trabalho de vocês.",--Well, no turning back now! That was a hell of a bang! Get into that truck and do your part of the job!
	pln_at1_intro_03_01 = "C4 no lugar. Só apertar esse botão e...",--C4 is in place. Just need to press this button and...
	pln_at1_gen_01_02 = "Vai Vai Vai! A polícia chegará a qualquer minuto!",--Go Go Go! Cops will be here any minute!
	pln_at1_gen_10_01 = "Woah! Bulldozer no carro-forte! Derrubem ele! Parace que eles estavam nos esperando aqui.",--Woah! Bulldozer in the truck! Take him out! I guess they were expecting trouble.
	pln_at1_gen_04_03 = "Defendam a furadeira. Deve demorar alguns minutos.",--Defend the drill. Should be through in a couple of minutes.
	pln_at1_gen_10_02 = "Cuidado! Bulldozer no transporte!",--Watch out! Bulldozer in the transport!
	pln_at1_gen_01_03 = "Rápido! A polícia está vindo ao nosso encontro!",--Hurry! Cops are already on their way!
	pln_at1_intro_01_03 = "Ótimo, carro-forte servido no prato. Agora abram e peguem o espólio.",--There you go, armored transport served on a silver platter, just open her up and secure the loot.
	pln_at1_gen_04_01 = "Mantenham esses policiais longe da furadeira.",--Keep the cops off the drill.
	pln_at1_har_01_01 = "Isso vai ser complicado, se segurem! Apenas um carro-forte para lidar. Quando as portas abrirem, ataquem ele!",--This is going to be bumpy, so brace yourselves! Only one truck to deal with. As soon as the doors open, hit it hard!
	pln_at1_har_04_01 = "Odeio ver vocês presos assim, mas pegamos quatro carros-forte. Saiam daí, e peguem-os!",--Hate to see you guys cooped up like that, but we snagged four trucks. Get out there, and get at them!
	pln_at1_gen_05_02 = "Levem para a van!",--Get it to the van!
	pln_at1_und_01_01 = "Deve ser o primeiro dia daquele idiota. Ele parou por uma ambulância. Agora é a vez de vocês. Saiam e façam o trabalho de vocês.",--Must be that drivers first day. The dumbass stopped for the ambulance! Now it's your turn, gang. Get out there and do your job!
	pln_at1_par_03_01 = "Caralho! Nós derrubamos três carros-forte. Façam valer a pena!",--Holy crap! We knocked all three trucks off the road. Make it count!
	pln_at1_end_02_02 = "Bom trabalho, cavalheiros! Um dinheiro super bem merecido!",--Well done gentlemen! Some hard-earned cash!
	pln_at1_par_02_01 = "Na mosca! Vocês estão bem? Essa foi uma puta colisão! Comecem a trabalhar nesses transportes!",--Bullseye! You guys OK? That was one hell of a collision! Get to work on those transports!
	pln_at1_intro_03_02 = "Explosivos colocados. GenSec se aproximando. Quase lá...",--Explosives are placed. GenSec transports on approach. Almost there...
	pln_at1_gen_09_02 = "Parece que o C4 pegou um pouco dos espólios. Peguem o que sobrou!",--Looks like that shape charge got the best of some of the loot. Get the rest!
	pln_at1_cnc_03_01 = "Vamos interceptar os carros-forte da GenSec que vão descarregar nas Docas.",--We're intercepting GenSec trucks about to unload at the docks.
	pln_at1_intro_01_02 = "O transporte parou! Abram-o, peguem os espólios e fujam. Simples.",--The transport is stopped! Open it, bag the loot, escape. Simple.
	pln_at1_gen_20_03 = "Projetos Militares em um carro-forte? Vamos ver o que consigo encontrar.",--Military blueprints in a high security transport? I'll see what I can find.
	pln_at1_cro_04_01 = "Nunca vi tiros assim. Quatro tiros, quatro transportes. Façam valer a pena.",--I've never seen shooting like that. Four shots, and four transports are taken out. Make it count.
	pln_at1_cbf_01_02 = "GenSec é uma grande companhia de segurança na Costa Leste. Tem uma boa reputação com bancos e políticos, mas hoje vamos ver o que podemos fazer. Consegui uma informação sobre um comboio indo para a cidade. Vamos atrás dele.",--GenSec are a big security company on the East Coast. Got a great reputation with the banks and politicians, but today we're going to see what we can do about that. Got a tip-off about a convoy coming into the city. We're going after it.
	pln_at1_gen_02_03 = "Abram!",--Get it open!
	pln_at1_gen_13_02 = "Estou mandando o helicóptero, continuem pegando as coisas!",--I'm sending the helicopter, keep bagging the stuff!
	pln_at1_dow_02_01 = "Bem, explosivos entregues. Dois transportes pararam. Ao trabalho!",--Well, our explosives guy delivered. Two transports have stopped. Get to work!
	pln_at1_brf_05_01 = "Nós temos uma ambulância roubada preparada para fazer uma barricada, e um comboio da GenSec em rota para Dulles. É um truque velho, mas um clássico. Peguem o que estiver no carro-forte e fujam. Nós estamos no interior de um país indiano aqui, cavalheiros, então esperem uma resposta rápida da polícia.",--We have a stolen ambulance all ready to set up a roadblock, and a GenSec convoy en-route from Dulles. It's an old trick, but a classic. Get whatever's in the trucks to your escape driver. We're deep in Indian country here, gentlemen, so expect a fast response from D.C.'s finest.
	pln_at1_cbf_01_03 = "Os comboios da GenSec contratam muitos ex-militares, providenciando poder de fogo e músculo, e eles estão por todo o lugar, do Cartão de Baseball favorito do Jimmy até Crown Jewels. Temos um comboio se movendo por D.C. Vamos ver o que é que nós podemos fazer.",--GenSec's overland armored convoys employ a lot of ex-military types, providing firepower and muscle, and they move everything from little Jimmy's favorite baseball card to the Crown Jewels. We got a line on a convoy moving into D.C. Let's see what we can get.
	pln_at1_cnc_01_01 = "Temos carros-forte da GenSec se movendo pelos subúrbios. Acertem eles.",--We got GenSec trucks moving through the suburbs. Go hit 'em.
	pln_at1_cnc_02_01 = "Temos um carro-forte fazendo uma parada forçada em Downtown.",--We've got an armored transport making an unscheduled stop downtown.
	pln_at1_cro_01_01 = "Eu sabia que podiamos confiar naquele Sniper! Ele entregou. Não percam tempo - Comecem a trabalhar nesse transporte!",--I knew we could trust that sniper! He delivers. Don't waste time - get to work on that transport!
	pln_at1_dow_03_01 = "Caralho! Três carros-forte pararam. Seus grupos estão nas ruas. Acertem eles!",--Hot damn! Three trucks are pulled over. Their crews are on the street. Hit them hard!
	pln_at1_end_01_01 = "Haha! Vocês conseguiram! Essas joias devem custar um bom dinheiro, não acham?",--Haha! You did it! This jewelry should be worth a few bucks don't you think?
	pln_at1_end_02b_01 = "Excelente trabalho. Vocês pegaram todo o dinheiro. Vou ver o que consigo encontrar com aquele projeto.",--Outstanding work. You guys spend blow through some of that cash. I'll see what I can find on this blueprint.
	pln_at1_end_02_01 = "Quanto dinheiro! Bom trabalho!",--That's a lot of cash! Nice job!
	pln_at1_end_03_01 = "Doce, doce ouro! Ótimo trabalho pessoal!",--Sweet, sweet gold! Great job everyone!
	pln_at1_gen_04_02 = "Isso não deve demorar, segurem-se.",--This shouldn't take long, hold your ground.
	pln_at1_gen_06_01 = "Usem os telhados para tomar vantagem!",--Use those roofs to your advantage!
	pln_at1_gen_14_01 = "Está aberto! Vamos ver o que temos aqui!",--It's open! Let's see what we got!
	pln_at1_gen_16_01 = "Está aberto. Entrem e abram as caixas de depósito. Precisamos de pelo menos duas bolsas.",--The truck's open. Get in there and crack the safeboxes. We need at least two bags of loot.
	pln_at1_gen_17_01 = "Entramos, mas vocês ainda tem que lidar com as caixas de depósito. Vocês precisam levar três bolsas até o veículo. Rápido!",--We're in, but you still got to deal with the deposit boxes. You got to get three bags back to the pick-up. Hustle!
	pln_at1_gen_18_01 = "Está aberto! Abrem essas caixas de depósito, e peguem os espólios. Quatro bolsas no mínimo.",--It's open! Deal with the deposit boxes, and grab the loot. Four bags is our minimum.
	pln_at1_gen_20_02 = "Isso é interessante. Projetos Militares no transporte da GenSec. Vou dar uma olhada nisso.",--This is interesting. Military blueprints in a GenSec transport. I'll look into it.
	pln_at1_intro_05_01 = "Ok, GenSec se aproximando. Atirem naquele motor. Vão! Vão!",--OK, GenSec is approaching. Gun that engine. Move! Move!
	pln_at1_intro_05_02 = "GenSec na mira. Comecem a se mover. Vão! Vão! Vão!",--GenSec in sight. Get those rigs moving. Go! Go! Go!
	pln_at1_par_01_01 = "Wow, que sorte! Acertamos bem na mosca! Aquele carro-forte já está fora da jogada. Ao trabalho!",--Woah, jackpot! We hit 'em good! That truck is out of action. Get to work!
	pln_at1_und_03_01 = "Eles cairam. Três transportes. Os grupos estão nas ruas, tentando descobrir o que aconteceu. Peguem eles!",--They fell for it. Three transports. Crews are on the street, trying to figure out what's happening. Hit them hard!
	
	-- Objetivos
	hud_arm_forest3_hl = "Fuga Disponível",--Escape is available
	hud_arm_forest6_hl = "Assegure Doze Bolsas de Munição da Turret",--Secure twelve Turret ammo bags
	hud_arm_forest1 = "Encontre qual o vagão que contém o protótipo da Turret e entre nele.",--Find out which railcar contains the prototype Turret and break into it.
	hud_arm_forest6 = "Vamos precisar de um pouco de munição para acompanhar a Turret. Doze bolsas devem servir. Mesmo local de asseguramento.",--We're going to need some ammo to go with the Turret. Twelve bags should do it. Same drop off point.
	hud_arm_mission2 = "Abra o carro-forte da GenSec e roube o ouro.",--Open up the GenSec truck and steal the gold
	hud_arm_mission1 = "Abra o carro-forte da GenSec e roube o que tiver dentro.",--Open up the GenSec truck and steal its contents
	hud_arm_forest7_hl = "Assegure Vinte Bolsas de Munição da Turret",--Secure twenty Turret ammo bags
	hud_arm_forest7 = "Vamos precisar de um pouco de munição para acompanhar a Turret. Vinte bolsas devem servir. Mesmo local de asseguramento.",--We're going to need some ammo to go with the Turret. Twenty bags should do it. Same drop off point.
	hud_arm_mission5_hl = "Fuga Disponível",--Escape is available
	hud_arm_forest2_hl = "Carregue as Partes da Turret para o Veículo",--Carry the prototype Turret parts to the drop off
	hud_arm_forest4_hl = "Assegure Quatro Bolsas de Munição da Turret",--Secure four Turret ammo bags
	hud_arm_mission3_hl = "Roube o Dinheiro",--Steal the cash
	hud_arm_forest3 = "Vá até o veículo de fuga.",--Get to the escape vehicle
	hud_arm_mission5 = "Vá até o veículo de fuga.",--Get to the escape vehicle
	hud_arm_forest5 = "Vamos precisar de um pouco de munição para acompanhar a Turret. Oito bolsas devem servir. Mesmo local de asseguramento.",--We're going to need some ammo to go with the Turret. Eight bags should do it. Same drop off point.
	hud_arm_forest4 = "Vamos precisar de um pouco de munição para acompanhar a Turret. Quatro bolsas devem servir. Mesmo local de asseguramento.",--We're going to need some ammo to go with the Turret. Four bags should do it. Same drop off point.
	hud_arm_mission3 = "Abra o carro-forte da GenSec e roube o dinheiro.",--Open up the GenSec truck and steal the cash
	hud_arm_forest1_hl = "Encontre e Entre no Vagão Correto",--Find and break into the correct railcar 
	hud_arm_forest2 = "Assegure as partes da Turret carregando elas até o local de asseguramento.",--Recover the prototype Turret parts by carrying them to the drop off location.
	hud_arm_mission4_hl = "Roube a Arte",--Steal the art
	hud_arm_forest5_hl = "Assegure Oito bolsas de Munição da Turret",--Secure eight Turret ammo bags
	hud_arm_mission4 = "Abra o carro-forte da GenSec e roube as pinturas.",--Open up the GenSec truck and steal the paintings
	hud_arm_mission1_hl = "Roube os Itens de Valor",--Steal the valuables
	hud_arm_mission2_hl = "Roube o Ouro",--Steal the gold
	}