return {
	-- Nomes e Descrições
	--heist_crojob2 = "The Bomb: Forest",--The Bomb: Forest
	--heist_crojob3_hl = "The Bomb: Forest",--The Bomb: Forest
	heist_crojob2_crimenet = "Uma quantidade considerável de explosivos termobáricos serão levados para um trem seguro, e depois a uma planta onde será desativado. Eu vou precisar de uma equipe experiente para conseguir esses explosivos. Mandem um recado a eles. Façam do nosso jeito.$NL;$NL;» Encontre o Vagão Correto$NL;» Encha o Vagão de Água$NL;» Encontre os Explosivos e use-os para Abrir o Vagão$NL;» Pegue a Bomba e Fuja!",--A large amount of thermobaric explosive is due to be taken by a secure train, to a plant where it will be decommissioned. I require a skilled team to recover these explosives. Send a message. Do it loud.$NL;$NL;» Find the correct wagon$NL;» Fill the wagon with water$NL;» Find C4 and use it to open the wagon$NL;» Take the bomb and escape
	heist_crojob3_briefing = "Esses explosivos termobáricos foram carregados em um trem de carga essa manhã. Com destino a Norfolk. Talvez serão vendidos, talvez descomissionados - não importa, por que nunca vai chegar lá. Um trem em movimento é difícil de parar, então faremos isso no melhor estilo do Velho Oeste. Exploda uma parte da ponte e tudo vai por água abaixo. Será bem barulhento e desleixado, porém efetivo. Os vagões vão se espalhar por toda a parte. Um deles tem um cofre onde estarão os nossos explosivos - Procure por cada um deles até encontrarem.",--Those thermobaric explosives were loaded onto a freight train this morning. It's heading down to Norfolk. Maybe to be sold on, maybe to be decommissioned - it doesn't matter, because it won't reach there. A moving train is tough to stop, so we're doing this Old West style. Blow a section of bridge and the whole thing comes tumbling down. It's loud and messy, but effective. The wagons will be scattered to hell. One of them has a vault where our explosives are - search each of 'em til you find it.

	-- Legendas
	pln_cr3_intro_01_01 = "Oh... Nossa. Espero que os vagões tenham sobrevivido.",--Oh... Wow. Hope those wagons survived.
	pln_cr3_29_02 = "Procurem as caixas. Devem ter explosivos em alguma delas.",--Search those crates. Should be some C4 in one of them.
	pln_cr3_32_01 = "Posicionem os explosivos dentro do cofre! Deixe-os já prontos.",--Deploy C4 inside the vault! Then get ready.
	pln_cr3_34_01 = "Eles estão bloqueando a estrada com vans! E... hã... Unidades fortemente armadas se aproximando!",--They're blocking the road with vans! And... Uh... Heavy units approaching!
	pln_cr3_44_01 = "Touch down! Agora encham o caminhão com o loot!",--Touch down! Now load the plane with loot!
	pln_cr3_03_01 = "Vagão errado. Droga! Continuem procurando!",--Wrong wagon. Crap! Keep looking!
	pln_cr3_28_01 = "Preparem-se. O Bile está quase de volta. Conectem a mangueira!",--Get ready. Bile's almost back. Connect the hose!
	pln_cr3_06_02 = "Certo, agora conectem essa mangueira no cofre.",--Alright, now hook that hose to the vault.
	pln_cr3_31_02 = "Ótimo. Podemos achar uma utilidade para esses explosivos mais tarde.",--Great. Sure we can find a use for a little C4 later.
	pln_cr3_54_01 = "Bombeamento pronto! O cofre está cheio e pronto para a ação!",--Pump's done! Vault is full and ready for blasting!
	pln_cr3_45_02 = "O helicóptero está quase chegando. Aguentem mais um pouco!",--Chopper's nearly there. Just hold on!
	pln_cr3_15_01 = "Esse é o vagão! Agora plantem a Térmite lá no topo. Vamos abrir esse desgraçado!",--That's the wagon! Now plant the thermite on the top. We'll open that sucker up!
	pln_cr3_23_01 = "Ótimo. A mangueira está pronta. Vamos aumentar a pressão. Iniciem o bombeamento.",--Good. Hose is OK. Let's get that pressure back. Start the pump.
	pln_cr3_17_01 = "Deixem a Térmite queimar. Não vai demorar para derreter tudo.",--Let the thermite burn through. Won't take long to eat through.
	pln_cr3_21_01 = "A Térmite fez o seu trabalho. Podemos usar a bomba de água por perto para encher os vagões. Conectem a mangueira ao cofre.",--Thermite's done. We can use water pump nearby to fill the wagons. Connect that hose to the vault.
	pln_cr3_52_01 = "Estamos quase lá, galera. Está enchendo direitinho! Continuem assim por mais um tempinho. Quando estiver cheio, nós explodimos e desfrutamos do show!",--We're almost there, gang. It's filling up nicely! Just keep things going a little more. Once it's full, we rig it and enjoy the show!
	pln_cr3_03_04 = "Não era esse. Continuem procurando. O cofre está por aqui em algum lugar.",--Wasn't this one. Keep going. Vault is here somewhere.
	pln_cr3_20_02 = "O melhor jeito para o cofre é a quebra de água. Nós enchemos de água, detonamos e boom! A pressão abre a porta à força. É o único jeito de acabar não ativando os explosivos.",--Best way in to this vault is water-cracking. We fill it with water, detonate it and, boom! Pressure busts the door open. Only way to insure we don't ignite those explosives.
	pln_cr3_24_02 = "Ali está o helicóptero! Bile, abaixe a mangueira. Galera, preparem-se.",--There's the chopper! Bile, lower the hose. Gang, get ready.
	pln_cr3_25_02 = "OK, estamos bombeando! Deixem encher o cofre.",--OK, we're pumping! Let it fill the vault.
	pln_cr3_36_02 = "Tem um barco no lago. Uma tirolesa poderia ajudar a atravessar.",--There's a boat on the lake. A zip-line can get you across.
	pln_cr3_18_03 = "Os vagões estão por todo o caminho. Devem ter loot dentro deles. Talvez uns explosivos. Se tiver, pegue-os. Vocês vão precisar.",--The wagons are all over the place. Could be loot in 'em. Might also be C4. If there is, grab it. You're gonna need it.
	pln_cr3_30_03 = "Fiquei sabendo que tem explosivos em um dos vagões. Vão procurar!",--I know there's C4 in one of the wagons. Check 'em out!
	pln_cr3_37_01 = "Ótimo. Agora vão até a tirolesa e o trabalho estará feito.",--Great. Now get to the zip-line and you're job is done.
	pln_cr3_05_02 = "Pegue a Térmite. Não temos tempo para uma furadeira, então vamos derreter o vagão.",--Grab the thermite. No time to drill so we're burning through the wagon itself.
	pln_cr3_18_02 = "A explosão espalhou os vagões para todos os lados. Devem ter loot em alguns deles. Procurem também por explosivos. Vocês vão precisar.",--Blast blew wagons everywhere. Might be loot in some of 'em. And check 'em for any C4. You'll need it soon.
	pln_cr3_02_01 = "Procurem em volta por uma escada. Vocês irão precisar dela para subir nos vagões.",--Search around for a ladder. You'll need it for the wagons.
	pln_cr3_35_01 = "Eles estão bloqueando a estrada! Merda, não sei se o avião vai conseguir pousar.",--They are cutting off the road! Shit, not sure if the plane is gonna be able to land.
	pln_cr3_53_02 = "A mangueira não vai se consertar sozinha. Algum de vocês palhaços precisam fazer isso!",--The hose won't fix itself. One of you clowns get it done!
	pln_cr3_34_02 = "Eles posicionaram um bloqueio de estrada. E reforço pesado a caminho também.",--They set up a roadblock. And heavy reinforcements are on the way too.
	pln_cr3_51_02 = "Peguem os explosivos aí dentro, e fiquem preparados!",--Get the C4 in there, and get ready!
	pln_cr3_44_02 = "O avião está no chão. Agora levem o loot para ele.",--Plane is on the ground. Now get the loot into it.
	pln_cr3_52_02 = "Está enchendo rápido, grupo. Continuem assim. Quando estiver cheio, plantem a carga e desfrutem do show.",--It's filling up fast, crew. Just keep it going. When it's full, plant the charge and enjoy the show.
	pln_cr3_52_03 = "Continue com o bombeamento de água, gangue. Só mais um pouco. Aí é só explodir, e deixar a hidrodinâmica fazer seu trabalho.",--Keep the water flowing, gang. Just a little more. Then just rig it, and let hydrodynamics do its job.
	pln_cr3_09_02 = "Boa. Agora levem isso para o local de entrega de loot.",--Nice. Now get it back to the loot drop. 
	pln_cr3_41_02 = "Abram caminho. Cortem as árvores!",--Clear the path. Clear the trees!
	pln_cr3_30_01 = "Devem ter explosivos em um dos vagões. Procurem por eles!",--There's gotta be explosives in one of the wagons. Search for them!
	pln_cr3_04_01 = "A Térmite está pronta. A Água está fluindo. Quando o helicóptero chegar, vocês devem conectá-lo ao cofre.",--Thermite's done. Water's on its way. When the chopper arrives, you need to connect it to the vault.
	pln_cr3_43_02 = "Boa. A carona está pousando.",--Good. Your ride is coming down now.
	pln_cr3_03_03 = "O cofre não está aqui. OK, continuem procurando.",--Vault's not here. OK, keep searching.
	pln_cr3_19_02 = "Certeza que deve ter loot nos vagões. Procurem neles. E qualquer explosivo que vocês acharem, peguem também.",--Sure there's gotta be loot in the wagons. Search 'em. And any C4 you can scrounge too.
	pln_cr3_19_01 = "Procurem nos outros vagões para um loot extra. E explosivos. Procurem por isso também.",--Check other wagons for extra loot. And C4. Look for that too.
	pln_cr3_30_02 = "Esses vagões estão destinados à descomissão militar. Um deles deve ter explosivos.",--Those wagons are bound for military decommissioning. One of 'em's gotta have C4.
	pln_cr3_10_02 = "A escada e a Térmite estão bem ali. Não se esqueçam.",--The ladder and thermite are right there. Don't forget them. 
	pln_cr3_21_02 = "A Térmite fez seu trabalho. Agora conectem a bomba de água no cofre.",--Thermite's done its job. Now hook that water pump up to the vault.
	pln_cr3_53_01 = "Qual é a da demora? Reconectem a mangueira logo!",--What's the hold-up?! Get that hose re-attached already!
	pln_cr3_46_02 = "O helicóptero está bem em cima de vocês. Conseguem ver?",--Chopper's right on top of you. Can you see it?
	pln_cr3_40_03 = "Fantástico! Não há tempo a perder. Liguem e comecem a derrubar as árvores.",--Fantastic! No time to lose, though. Fire it up and get felling those trees.
	pln_cr3_09_01 = "Levem isso de volta para o local.",--Get that back to the drop.
	pln_cr3_25_01 = "Olhos abertos nessa mangueira. Deixe-a encher o cofre.",--Keep an eye on that hose. Let it fill the vault. 
	pln_cr3_02_02 = "Os vagões devem ter uma escada. Procurem por ela.",--The wagons would have had a ladder. Look for it.
	pln_cr3_40_01 = "Vocês encontraram! Hora de derrubar umas árvores!",--You found it! Time to bring some trees down!
	pln_cr3_33_01 = "OK. A qualquer... segundo...",--OK. Any... Second...
	pln_cr3_11_01 = "Vocês vão precisar de Térmite para abrir o vagão.",--You're gonna need the thermite to pop the wagon open. Get back and grab it.
	pln_cr3_22_01 = "A mangueira parece segura. Comecem a bombear a água.",--Hose looks secure. Start the pump.
	pln_cr3_41_01 = "Derrubem essas árvores!",--Bring those trees down!
	pln_cr3_24_01 = "O helicóptero já está em cena! Bile, derrube essa mangueira para a gangue.",--Chopper's on the scene! Bile, get that hose down to the gang.
	pln_cr3_55_01 = "O vagão não vai se abrir sozinho. Enfiem esses explosivos lá!",--Wagon's not gonna crack itself open. Dip that C4 in!
	pln_cr3_01_01 = "Os policiais vão invadir a qualquer segundo! Mais rápido! Procurem nos vagões pelo cofre.",--Cops are gonna be swarming through here any second! Move fast! Check the wagons for the vault.
	pln_cr3_26_01 = "A mangueira se soltou. Reconecte-a!",--The hose has come loose. Reconnect it!
	pln_cr3_39_03 = "Olhem só pra toda essa madeira. Deve ter alguma serra por aqui em algum lugar - continuem procurando.",--Look at all this timber. There's got to be a saw somewhere - keep looking.
	pln_cr3_39_02 = "Deve ter uma serra aqui perto. Procurem pelas toras de madeira.",--Got to be a saw here somewhere. Check the timber logs.
	pln_cr3_45_01 = "O helicóptero está a caminho. Aguentem, pessoal.",--The chopper is en-route. Hold on, guys.
	pln_cr3_22_02 = "OK, tudo ótimo com a mangueira. Agora comecem a bombear essa água.",--OK, hose looks good. Now get the pump started.
	pln_cr3_13_01 = "Lembrem-se, a escada irá ajudar a subir nos vagões.",--Remember, the ladder will let you get up onto the wagons.
	pln_cr3_36_01 = "O barco está esperando por vocês no lago. Atravessem pela tirolesa.",--The boat's waiting for you at the lake. You can zip-line aboard.
	pln_cr3_54_03 = "A bomba de água terminou. O vagão está cheio e preparado! Muito bem!",--Pump's finished. That wagon is bloated and ready! Nicely done.
	pln_cr3_54_02 = "E o bombeamento de água está pronto. Bom trabalho!",--That's the pump done. Great work!.
	pln_cr3_03_02 = "Não, sem cofre. Continuem a busca!",--Nope, no vault. Move on, keep looking!
	pln_cr3_01_02 = "Comecem a procurar os vagões. Esperem por uma resposta rápida da polícia. Lembrem-se, vocês estarão procurando por um vagão com o cofre!",--Get searching the wagons. You can expect a fast response from the cops. Remember, you're looking for the wagon with the vault!
	pln_cr3_47_02 = "O helicóptero está aí, pessoal. Assegurem o loot e vão embora!",--The chopper's there, guys. Stow the loot and bug out!
	pln_cr3_38_03 = "O Bile está a caminho para vocês, mas ele não pode pousar com essas árvores no caminho. Encontrem uma serra, abram caminho para ele, e marquem com sinalizadores.",--Bile's on his way to you, but he can't land with those trees in the way. Find a saw, and clear a way for him, then mark it with flares.
	pln_cr3_38_01 = "Tem um avião a caminho para extrair vocês, mas ele não poderá pousar com essas árvores bloqueando o caminho. Encontrem uma serra, cortem as árvores e marquem o pouso com sinalizadores. Não se preocupem, a CIA faz isso há muito tempo.",--Got a plane en route to pick you up, but it can't land with trees blocking it's path. Find a saw, clear the trees and mark the landing with flares. Don't worry, CIA been doing this for years.
	pln_cr3_48_01 = "Um deles contém um cofre. Encontrem-no.",--One of 'em contains the vault. Find it.
	pln_cr3_55_02 = "Vamos lá, assistimos ao show e vocês já sabem o que precisa ser feito. Posicionem os explosivos!",--Come on, we watched the show and you know how to do it. Set the C4!
	pln_cr3_46_01 = "Quase lá. Vocês vão conseguir ouvir.",--Almost there. You should be able to hear it.
	pln_cr3_29_01 = "Procurem os outros vagões pelo explosivo! Deve estar em uma das caixas.",--Search the other wagons for C4! It should be inside one of the crates.
	pln_cr3_35_02 = "Eles estão bloqueando a estrada. Droga. Ainda tem espaço para o avião?",--They're blocking the road. Damn. Is there still room for the plane?
	pln_cr3_31_01 = "Bom achado. Isso vai ser bastante útil.",--Nice find. This'll come in handy later.
	pln_cr3_07_01 = "Droga, esse cofre é grande. Precisa de mais água ainda. Esperem o helicóptero reabastecer. Aguentem mais um pouco!",--Damn, that vault is big. Need more water. Let the chopper refill. Hold tight!
	pln_cr3_42_02 = "O avião está quase chegando. Ativem os sinalizadores e marquem o local de pouso.",--Plane's nearly there. Pop the flares and mark the strip.
	pln_cr3_32_02 = "Levem esses explosivos para o cofre. E mantenham a distância!",--Get that C4 into the vault. And stand back!
	pln_cr3_18_01 = "Vocês vão querer procurar os vagões por loot extra. E olhos abertos para os explosivos. Vocês com certeza vão precisar. Devem estar em uma das caixas.",--You might wanna scout the wagons for some extra loot. And keep your eyes open for C4. You're gonna need it later. Should be in one of the crates.
	pln_cr3_47_01 = "O helicóptero pousou. Levem o loot, e vão embora!",--Chopper is down. Get the loot in, and get out!
	pln_cr3_33_02 = "Explosivos acionados. E...",--Explosive's in. And...
	pln_cr3_23_02 = "OK, a mangueira parece segura. Agora vamos começar a bombear a água de novo.",--OK, hose looks secure. Now let's get that pump pumping again!
	pln_cr3_17_02 = "Esses vagões são da pesada, mas a Térmite vai derretê-los facilmente.",--These cars are tough stuff, but the thermite will melt through easy.
	pln_cr3_11_02 = "Vocês só vão poder derreter o vagão com a Térmite, então é melhor voltar e pegá-la.",--You can only melt through that wagon with the thermite, so you better head back and fetch it.
	pln_cr3_27_02 = "Os policiais ferraram com a mangueira. Consertem!",--Cops pulled the hose. Get it back on!
	pln_cr3_19_03 = "Aposto que tem loot nesses vagões. Chequem-no. Olhos abertos para explosivos também.",--I bet those wagons have loot. Check 'em out. Keep an eye open for C4 too.
	pln_cr3_20_01 = "Vamos abrir o cofre com água, pessoal. Encha-o com bastante água, e detone-o. Vai explodir a porta sem danificar o conteúdo do vagão.",--We're going to water crack this vault, guys. Fill it with water, and detonate it. It'll blow the door right off without damaging the contents.
	pln_cr3_16_02 = "Procurem em volta por uma escada. Vocês vão precisar dela para procurar os vagões. Talvez ainda esteja conectada a eles.",--Look around for a ladder. You need it to search the wagons. Maybe it's still attached to one of them.
	pln_cr3_39_01 = "Encontrem a serra! Deve estar em algum lugar. Procurem em volta pelas toras de madeira.",--Find that saw! It has to be around here somewhere. Try looking around timber logs.
	pln_cr3_08_01 = "Agora!",--Now!
	pln_cr3_38_02 = "Enviando um pequeno avião para te buscar. Mas o piloto não pode pousar com essas árvores no caminho. Vocês precisam achar uma serra, cortar algumas árvores e marcar a zona de pouso para ele.",--Sending a small plane to pick you up. Pilot can't land with those trees though. You gotta find a saw, clear a few and then mark the strip for him.
	pln_cr3_07_02 = "Precisamos de mais água! O helicóptero vai reabastecer o tanque. Guardem o cofre!",--We need more water! Chopper's going to fill her tank. Hold the vault!
	pln_cr3_14_02 = "Continuem procurando pelo vagão. Lembrem-se, estamos procurando pelo vagão com um cofre.",--Keep looking for the wagon. Remember, we're looking for the one with the vault.
	pln_cr3_05_01 = "Peguem aquela Térmite, acreditem em mim, você vão precisar dela.",--Pick up that thermite, trust me, you're going to need it.
	pln_cr3_53_03 = "Vocês precisam reconectar a mangueira, pessoal. Vamos!",--You need to get that hose reconnected, guys. Come on!
	pln_cr3_14_01 = "Pessoal, vocês precisam achar aquele vagão - o que tem um cofre dentro.",--Guys, you need to find that wagon - the one with the vault.
	pln_cr3_37_02 = "Agora vão para aquela mesma tirolesa para dar o fora daí.",--Now get to that same zip-line to get your good selves out of there. 
	pln_cr3_40_02 = "Ótimo! Agora comecem a cortar essas árvores!",--Great! Now get it working on those trees!
	pln_cr3_04_02 = "OK, a Térmite derreteu. Um helicóptero está trazendo a água. Conectem a mangueira quando ele chegar.",--OK, thermite's through. A chopper is bringing the water. Connect it when it arrives.
	pln_cr3_06_01 = "Ali está a mangueira! Conectem no cofre.",--There's the hose! Connect it to the vault.
	pln_cr3_08_02 = "Boom!",--Boom!
	pln_cr3_10_01 = "Ali está a escada e a Térmite. Peguem-nos. Vocês vão precisar depois.",--There's the ladder and thermite. Grab 'em. You'll need them later.
	pln_cr3_12_01 = "Aqui está a escada. Vocês podem usá-la para subir nos vagões.",--Here's the ladder. You can use it to get on top of the wagons.
	pln_cr3_12_02 = "Ótimo! Vocês podem usar essa escada para subir nos vagões.",--Great! You can use this ladder to get up on the wagons.
	pln_cr3_13_02 = "Usem aquela escada para subir nos vagões.",--Use that ladder to climb onto the wagons.
	pln_cr3_15_02 = "Ali está o cofre! Ótimo! Agora usem a Térmite no topo do vagão e derreta-o para entrar.",--There's the vault! Great! Now use the thermite on the top and burn your way through. 
	pln_cr3_16_01 = "Encontrem uma escada. E Então vocês poderão subir nesses vagões.",--Find a ladder. Then you can climb the wagons.
	pln_cr3_26_02 = "Reconectem aquela mangueira!",--Get that hose re-attached!
	pln_cr3_27_01 = "Os policiais desconectaram a mangueira. Reconecte-a!",--The cops have disconnected the hose. Reconnect it!
	pln_cr3_27_03 = "Droga! Eles ferraram com a mangueira. Voltem lá, e consertem essa merda!",--Dammit! They yanked the hose. Get there, get it back on.
	pln_cr3_28_02 = "OK, o helicóptero está de volta. Comecem a bombear a água!",--OK, chopper is back. Get pumping again!
	pln_cr3_37_03 = "Aquela tirolesa é o caminho de fuga de vocês - vão direto para lá!",--That zip-line is your way out - get there!
	pln_cr3_42_01 = "O avião está próximo. Marquem a zona de pouso com alguns sinalizadores.",--The plane is close. Mark the landing strip with flares.
	pln_cr3_43_01 = "Ótimo! Avião se aproximando...",--Great! Plane on approach now..
	pln_cr3_49_01 = "Uma pasta com Térmite de alta temperatura vai estar esperando por vocês ali.",--Briefcase with high-temperature thermite paste will be waiting for you here.
	pln_cr3_50_01 = "Bomba de água industrial, de alta pressão usada pela madeireira. Se estivermos com sorte, e o vagão certo cair perto dela, podemos usar para encher o cofre.",--Industrial, high-pressure water pump used by nearby timber mill. If we're lucky, and the right wagon lands near it, we can use it to fill the vault.
	pln_cr3_51_01 = "Agora posicionem essa carga e mantenha a distância!",--Now dip that charge in and stand back!
	pln_cr3_55_03 = "Todo esse vagão está esperando por um pouquinho de explosivos. Vão logo!",--All that wagon is waiting for is a nice bit of C4. Get to it!
	
	-- Legendas do Capanga
	pt1_cr3_01_03 = "Igual o padre disse à freira, estou mandando a mangueira.",--Like the priest said to the nun, I'm droppin' you a hose.
	pt1_cr3_01_01 = "Os palhaços estão prontos? A mangueira está descendo.",--You clowns ready? Hose is coming down.
	pt1_cr3_02_03 = "Preciso reabastecer. Volto daqui a pouco.",--Need a refill. Be back shortly.
	pt1_cr3_02_01 = "Acabou a água. Vou reabastecer.",--Tank's dry. Going to refill. 
	pt1_cr3_01_02 = "Estão prontos? Vou enviar a mangueira.",--You ready for it? I'm dropping the hose.
	pt1_cr3_03_03 = "Acabou a água, vou dar o fora daqui.",--I'm dry, and I'm outta here.
	pt1_cr3_02_02 = "Vou reabastecer o tanque. Já volto.",--Going to refill the tank. Back soon.
	pt1_cr3_03_01 = "Meu trabalho aqui está feito! Vou vazar.",--My job's done here! I'm out.
	pt1_cr3_03_02 = "Isso é tudo que eu tenho. Vou dar o fora daqui.",--That's all I got. I'm outta here!
	
	-- Objetivos
	hud_heist_crojob2_mission15 = "O barco de fuga estará no lago esperando por você em alguns minutos.",--The escape boat will be waiting for you at the lake in a couple of minutes.
	hud_heist_crojob2_mission16 = "A van de fuga estará esperando por você na estrada principal em alguns minutos. Fique vivo até lá!",--The escape van will be waiting for you at the main road in a couple of minutes. Stay alive until then!
	hud_heist_crojob2_mission13_hl = "Espere pelo Helicóptero",--Wait for the helicopter
	hud_heist_crojob2_mission3_hl = "Conecte a Mangueira ao Vagão",--Connect hose with the wagon
	hud_heist_crojob2_mission17_hl = "Pegue o Loot",--Take the loot
	hud_heist_crojob2_mission15_hl = "Espere pelo Barco",--Wait for the boat
	hud_heist_crojob2_mission18_hl = "Fuga Disponível",--Escape available
	hud_heist_crojob2_mission3 = "Para começar a encher o vagão com água, você precisa conectar a mangueira ao vagão.",--In order to start filling up the wagon with water, you need to connect the hose with a wagon.
	hud_heist_crojob2_mission21 = "Uma bomba de água próxima vai encher facilmente o vagão. Primeiro conecte a mangueira com a bomba e então continue esticando até alcançar o vagão!",--Water pump nearby will easily fill the wagon. Connect the hose with pump first and then keep extending it until you reach the wagon!
	hud_heist_crojob2_mission25_hl = "Reinicie o Gerador",--Restart the generator
	hud_heist_crojob2_mission18 = "A fuga está disponível agora. Você poderá sair ou ficar por mais loot.",--Escape is now available. You can leave or stay for more loot.
	hud_heist_crojob2_mission23_hl = "Espere a Água encher o Vagão",--Wait for the water to fill the wagon
	hud_heist_crojob2_mission28 = "Afaste-se e aproveite o show!",--Stand back and enjoy the show!
	hud_heist_crojob2_mission20 = "Deixe a pasta de Térmite fazer sua mágica. Está corroendo o aço, mas não vai demorar muito.",--Let the thermite paste do its magic. It's chewing through thick metal but it shouldn't take too long.
	hud_heist_crojob2_mission24 = "A mangueira se soltou, reconecte-a para voltar a bombear.",--The hose has come loose, reconnect it to start pumping again.
	hud_heist_crojob2_mission23 = "Paciência é uma virtude! Vai levar alguns minutos para encher, então prepare-se e fique vivo.",--Patience is a virtue! It's gonna take a couple of minutes to fill it up so dig in and stay alive.
	hud_heist_crojob2_mission14_hl = "Espere pelo Helicóptero",--Wait for the helicopter
	hud_heist_crojob2_mission22 = "Ligue o gerador para começar a bombear água.",--Start the generator to start pumping the water.
	hud_heist_crojob2_mission12_hl = "Espere pelo Avião",--Wait for plane
	hud_heist_crojob2_mission8 = "O avião está esperando por você na estrada.",--The plane is waiting for you on the road.
	hud_heist_crojob2_mission7a = "Para que o avião pouse na estrada, você precisa cortar as árvores que estão ao redor.",--In order for a plane to land on the road, you need to cut the surrounding trees down.
	hud_heist_crojob2_mission14 = "O helicóptero de fuga deve chegar em alguns minutos. Prepare-se e fique vivo até lá!",--The escape helicopter should arrive in a couple of minutes. Dig in and stay alive until then!
	hud_heist_crojob2_mission28_hl = "Afaste-se",--Stand back
	hud_heist_crojob2_mission6 = "O helicóptero estará esperando por você na vigia.",--The helicopter will be waiting for you at the lookout.
	hud_heist_crojob2_mission20_hl = "Espere a Pasta de Térmite queimar",--Wait for thermite paste to burn through
	hud_heist_crojob2_mission8_hl = "Leve o loot para o Avião",--Carry the loot to the plane
	hud_heist_crojob2_mission7b_hl = "Corte as Árvores que Restaram",--Cut the remaining trees
	hud_heist_crojob2_mission21_hl = "Conecte a Mangueira ao Vagão",--Connect the hose to the wagon
	hud_heist_crojob2_mission25 = "O gerador parou devido à perda de pressão, vá até lá e o reinicie-o!",--Generator stopped due to loss of pressure, get there and restart it!
	hud_heist_crojob2_mission4_hl = "Proteja o Helicóptero",--Protect the helicopter
	hud_heist_crojob2_mission17 = "Pegue o loot e levo-o na fuga.",--Pick up the loot and take it to the escape.
	hud_heist_crojob2_mission19 = "O helicóptero está enchendo o vagão com água. Vai levar alguns minutos até o helicóptero esvaziar o reservatório de água.",--The helicopter is filling the wagon with water. It's gonna take a couple of minutes until the helicopter empties its water container.
	hud_heist_crojob2_mission1_hl = "Encontre o Vagão-Cofre",--Find the vault wagon
	hud_heist_crojob2_mission7b = "Para o avião pousar na estrada, você precisará cortar as árvores que sobraram.",--In order for a plane to land on the road, you need to cut the remaining trees down.
	hud_heist_crojob2_mission9_hl = "Leve o loot para o Barco",--Carry the loot to the boat
	hud_heist_crojob2_mission2 = "Esse é o vagão que estávamos procurando. Use a pasta de Térmite para abrir um buraco em cima dele. Assim o helicóptero poderá enchê-lo com água.",--That is the wagon we were looking for. Use thermite paste to burn a hole on top of it so that the helicopter can fill it up with water.
	hud_heist_crojob2_mission12 = "O avião deve chegar em alguns minutos. Espere até ele pousar.",--The plane should be here in a couple of minutes. Wait for it until it lands.
	hud_heist_crojob2_mission5_hl = "Leve o loot para a Van",--Carry the loot to the van
	hud_heist_crojob2_mission6_hl = "Leve o loot para o Helicóptero",--Carry the loot to the helicopter
	hud_heist_crojob2_mission24_hl = "Reconecte a Mangueira",--Reconnect the hose
	hud_heist_crojob2_mission13 = "O helicóptero deve pousar a qualquer momento. Ele carrega uma mangueira que precisa ser conectada ao vagão.",--The helicopter should arrive in a few moments. It carries a hose which needs to be connected with a wagon.
	hud_heist_crojob2_mission29_hl = "Encontre uma Motosserra",--Find chainsaw
	hud_heist_crojob2_mission10 = "O helicóptero precisa reabastecer, ele deve voltar em alguns minutos. Aguente firme até ele voltar.",--The helicopter needs to refill, it should come back in a couple of minutes. Stand your ground until it comes back.
	hud_heist_crojob2_mission2_hl = "Abra um Buraco no Vagão",--Burn a hole into the wagon
	hud_heist_crojob2_mission10_hl = "Espere pelo Helicóptero",--Wait for the helicopter
	hud_heist_crojob2_mission9 = "Tem uma tirolesa na beira do lago que você pode usar para levar o loot até o barco.",--There is a zip-line just by the lake which you can use to get the loot on the boat.
	hud_heist_crojob2_mission22_hl = "Ligue o Gerador",--Start the generator
	hud_heist_crojob2_mission27 = "Um dos vagões está transportando explosivos, procure a caixa com explosivos.",--One of the wagons was transporting C4, look for the crate with explosives.
	hud_heist_crojob2_mission11_hl = "Marque a Estrada com Sinalizadores",--Mark the road with signal flares
	hud_heist_crojob2_mission11 = "Faça uma pista improvisada para um avião marcando a estrada com sinalizadores.",--Make an improvised runway for a plane by marking the road with signal flares.
	hud_heist_crojob2_mission16_hl = "Espere pela Van",--Wait for the van
	hud_heist_crojob2_mission26_hl = "Plante a Carga Explosiva",--Deploy the explosive charge
	hud_heist_crojob2_mission1 = "A explosão espalhou os vagões por toda a floresta. Entre na floresta e procure pelo vagão-cofre, você terá que abrir as portas de cada vagão para encontrar o que contém o cofre.",--Explosion has scattered the wagons all around the forest. Move into the forest and look for the vault wagon, you will have to open the doors on each one of them until you find the one with the vault.
	hud_heist_crojob2_mission5 = "A van estará esperando por você na estrada principal.",--The van will be waiting for you just by the main road.
	hud_heist_crojob2_mission29 = "Tem uma motosserra por aqui, encontre-a!",--There's a chainsaw somewhere around, find it!
	hud_heist_crojob2_mission27_hl = "Encontre os Explosivos",--Find the explosives
	hud_heist_crojob2_mission19_hl = "Espere até o Helicóptero encher o Vagão com Água",--Wait until the helicopter fills the wagon with water
	hud_heist_crojob2_mission26 = "Jogue o explosivo e aproveite o show! Melhor se afastar um pouco.",--Dip the explosive in and enjoy the show! You might want stand back a bit though.
	hud_heist_crojob2_mission4 = "Proteja o piloto e o helicóptero dos tiros inimigos enquanto o vagão é enchido com água.",--Protect the pilot and the helicopter from incoming enemy fire while it fills the vault with water.
	hud_heist_crojob2_mission7a_hl = "Corte as Árvores",--Cut the trees
		}