Hooks:Add("LocalizationManagerPostInit", "terremotosnaosaolegais", function(loc)
	LocalizationManager:add_localized_strings({
	-- Nomes e Descrições
	heist_jolly = "Aftershock",--Aftershock
	heist_jolly_hl = "Aftershock",--Aftershock
	heist_jolly_crimenet = "Eu fiz um trato com o maior sindicato da Costa Oeste, vendendo os seus cofres. Infelizmente, o primeiro carregamento dos cofres tiveram um pequeno problema - Uma Porra de um TERREMOTO! Podem acreditar nisso!? Vão pra lá, e recuperem esses cofres. Que se foda a Califórnia!\n\n» Encontre os Caminhões do Vlad\n» Abra os Caminhões\n» Leve os Cofres",--I've struck a deal with the biggest syndicate on the West Coast, selling their safes on the east Coast. Unfortunately, first shipment of safes ran into a little trouble - a fucking earthquake! Can you believe that!? Get out there, ensure those safes are recovered. Fuck California.$NL;$NL;» Find Vlad's trucks$NL;» Open the trucks$NL;» Get the safes out
	heist_jolly_briefing = "Ei, vocês viram as notícias?! Teve um terremoto na Costa Oeste! Los Angeles está uma bagunça completa e é aí onde vocês vão entrar.\n\nParece que o Vlad fez um trato para mover uns cofres de Seattle até DC. Os carregadores estava em Los Angeles quando o terremoto aconteceu - acho que iriam sair de Long Beach. o Vlad quer a sua carga em total segurança. Não temos tempo para planejar qualquer plano. Los Angeles foi completamente detonada e as estradas estão todas bloqueadas. E é por isso que deixaremos vocês lá de Helicóptero.",--Hey, you guys see the news?! Big quake just hit the West Coast! LA is completely messed up. And that's where you're headed.$NL;$NL;Seems Vlad has set up some big deal to move some freight from Seattle to DC. The shippers he contracted were in LA when the quake hit - I guess they were going to ship out of Long Beach. Vlad wants his freight secured safely. No time for planning on this one. LA is wrecked, and the roads are messed up so we're going to drop you in by chopper.
	
	-- Legendas (Bain)
	pln_as1_11_01 = "Beleza. Os cofres estão dentro. Vamos dar o fora daqui. Garantem que o caminhão está aí!",--All right. Safes are in. We're getting out through the yard. Make sure the truck is there!
	pln_as1_20_03 = "Grupo, eu estou achando que essa Área de Construção é a melhor aposta de caírem o fora. Eles tem um caminhão. Vou estar enviando alguns C4 para explodir a parede.",--Crew, I'm guessing that that construction yard across the way is your best bet for getting out. They have a truck. Sending you some C4 to bring the wall down now.
	pln_as1_04_01 = "Vamos lá, encontrem o segundo caminhão.",--Come on, find that second truck.
	pln_as1_04_03 = "Cadê o segundo caminhão? Tem que estar por aqui em algum lugar.",--Where's that second truck? Gotta be around here somewhere.
	pln_as1_18_03 = "Os cofres são muitos pesados e esses caminhões estão quebrados. Vamos precisar de outro transporte. Vou achar algo, só um segundo.",--The safes are way too heavy to carry, and those trucks are screwed. Gonna need another transport. I'll find something - hang tight.
	pln_as1_05_02 = "Agora, abram esses caminhões. Vamos entrar.",--Now, get those trucks opened. Let's get inside them.
	pln_as1_05_03 = "Ótimo. Podemos abrir os caminhões e ver o que esse Ivan doido estava levando.",--Good. Now we can open the trucks up and see what that crazy Ivan was shipping.
	pln_as1_17_03 = "Encontrem esses caminhões! E não matem os guardas do Vlad, se eles estiverem ainda aí.",--Find those trucks! And don't shoot Vlad's guys if any of them are still around.
	pln_as1_02_03 = "Vlad está bem chateado a respeito desses cofres. Quer ter uma palavra com vocês.",--Vlad's pretty upset about these safes. Wants to talk to you.
	pln_as1_14_03 = "Entrem no caminhão! O helicóptero vai levar a merda inteira!",--Get inside the truck! The chopper is going to airlift the whole damn thing out!
	pln_as1_08_02 = "Uma C4-zinha deve servir. Estou mandando agora. Aguentem aí.",--A little C4 will deal with that. I'm sending some now. Hold on.
	pln_as1_15_03 = "Voando que nem anjos em cima... de uma cidade arruinada. Bom trabalho!",--Flying like angels over...that ruin of a city. Great job!
	pln_as1_15_02 = "Espero que essa corda aguente. Esperem, eu contei o peso dos cofres?",--Hope that cable holds. Wait, did I add the weight of the safes...?
	pln_as1_03_01 = "Vocês ouviram ele. Os caminhões estão próximos em algum lugar.",--You heard him. The trucks are around here somewhere.
	pln_as1_09_02 = "Chegou o C4, pessoal. Alguém deverá pegar.",--There's the C4, gang. Someone grab it.
	pln_as1_15_01 = "E... lá vamos nós! Excelente trabalho, grupo!",--And....lift off! Outstanding work, crew!
	pln_as1_13_02 = "Gangue, o piloto não consegue ver vocês. Vocês precisam acender o sinalizador.",--Gang, the pilot can't see you. You need to light that flare.
	pln_as1_01_01 = "Meu Deus, olha só pra esse lugar!",--Christ, look at this place!
	pln_as1_14_02 = "Não vai dar tempo pra levar isso pro helicóptero.",--No time to load the chopper. It's just going to grab the truck, so you need to be inside!
	pln_as1_12_02 = "Pessoal, preciso que vocês vão para a Área de Construção. É o único de jeito de sairem daí.",--Guys, I need you in the construction yard. It's the only way out.
	pln_as1_12_01 = "Pessoal, vão pra Área de Construção! Rápido!",--Gang, get into the construction yard! Hurry!
	pln_as1_19_01 = "Porra, esse lugar está detonado. Ainda procurando aqui. Aguentem aí.",--Damn, place is wrecked. Still looking. Hang in there.
	pln_as1_17_02 = "Os caminhões estão próximos. Fiquem de olho nos guardas do Vlad também. Não matem eles!",--The trucks are somewhere near. Keep an eye out for Vlad's couriers too. Don't drop them!
	pln_as1_20_02 = "Gangue, tem uma Área de Construção depois do rio! Tem um caminhão estacionado lá. Acho que esse seria o nosso melhor jeito de dar o fora daqui. Mandando o C4 agora. Protejam os cofres!",--Gang, there's a construction yard across the river! Got a truck parked up. Reckon it's our best way out. Sending you C4 now. Protect the safes!
	pln_as1_18_02 = "Vocês nunca vão conseguir carregar isso. Vão precisar de um transporte e de um plano de fuga. Me dê só um minuto, vou achar algo.",--You'll never carry those out. Gonna need a transport, and a way out. Give me a minute, I'll find something.
	pln_as1_06_02 = "Podem apostar que eles são importantes, se o Vlad nos enviou pra casa do caralho somente por causa desses cofres.",--You can bet they're important if Vlad sent us to this hellhole for them.
	pln_as1_10_03 = "Agora deem um jeito no muro pra área ali. Vocês vão sair a partir de lá.",--Now go deal with obstruction to the yard over there. You're getting out that way.
	pln_as1_07_01 = "Eu sei que não é o charme de Hollywood, mas alguém tem que levar esses cofres pra fora.",--I know it's not Hollywood glamour, but someone better gets those safes outta there.
	pln_as1_21_03 = "Levem os cofres no caminhão!",--Get the safes loaded onto that truck!
	pln_as1_02_01 = "Eu estou com Vlad na chamada aqui.",--I got Vlad on the line.
	pln_as1_06_01 = "Bom, pelo menos não são ogivas dessa vez.",--Well, at least it isn't nukes this time.
	pln_as1_08_01 = "Vão ter que passar por essa. Estou enviando o C4.",--Gonna have to get through there. I'm sending you C4.
	pln_as1_09_03 = "Peguem o C4, grupo. Isso vai cuidar do muro da Área de Construção.",--Take the C4, crew. That will deal with the construction yard wall.
	pln_as1_19_03 = "Ainda estou procurando. Caralho, Los Angeles está um verdadeiro caos. Aguentem aí.",--I'm still looking. Damn, LA is smoked. Hold them off.
	pln_as1_10_02 = "Bom. Agora, explodam esse muro. É a nossa saída.",--Great. Now go blast that obstruction. It's your way out.
	pln_as1_07_02 = "Vamos, pessoal. Levem os cofres. Não fiquem enrolando.",--Come on, crew. Get the safes out. Put your back into it.
	pln_as1_07_03 = "Levem os cofres, gente. É, eu sei que está um puta calor, mas vocês tem que fazer.",--Get the safes out, gang. Yeah, I know it's over a hundred degrees, but get to it.
	pln_as1_06_03 = "Tiaras, Ogivas nucleares e Cofres. Só mais um trabalho normal para o Vlad.",--Tiaras, nuclear warheads, and safes. Just another job for Vlad.
	pln_as1_09_01 = "Beleza, o C4 chegou. Vão lá pegar!",--All right, the C4's on the ground. Grab it!
	pln_as1_16_02 = "Cara, a cidade está uma ruína. As ruas, os prédios... tudo detonado.",--Man, the city's a ruin. Roads, buildings...everything's screwed.
	pln_as1_05_01 = "Ótimo. Agora abram esses caminhões. Vamos ver o que o Vlad está levando.",--Great. Now crack those trucks open. Let's see what Vlad was shipping.
	pln_as1_21_01 = "Esse caminhão parece perfeito. Coloquem os cofres a bordo, todos eles.",--That truck looks perfect. Now get the safes loaded on board - all of them.
	pln_as1_03_03 = "Vocês ouviram ele. Vamos achar esses caminhões.",--You heard the man. Let's find those trucks.
	pln_as1_19_02 = "Isso seria mais fácil se a cidade não estivesse nessa merda. Só esperem um pouco.",--This would be easier if the city wasn't a ruin. Just hold on.
	pln_as1_17_01 = "Esses caminhões estão aqui em algum lugar. Os guardas do Vlad estão aqui também, então não matem eles.",--The trucks are here somewhere. Vlad's guys will be too, so watch your fire.
	pln_as1_08_03 = "Vou avisar o piloto para retornar com o C4 para ajudarem vocês. Só esperem aí.",--Telling the pilot to return with the C4 to bust you through there. Just hang in there.
	pln_as1_03_02 = "Ok, os caminhões estão em algum lugar nessa rodovia.",--Okay, trucks are somewhere on this freeway.
	pln_as1_20_01 = "Consegui! A Área de Construção, com um caminhão. Parece que é o melhor jeito de sairem daí, mas vocês vão precisar de C4 para derrubar esse muro. Estou enviando agora. Cuidem dos cofres!",--Got it! Construction yard, with a truck. Looks like the best way out of here, but you'll need C4 to bust that wall. Sending it now. Mind the safes!
	pln_as1_16_03 = "Gente, está tudo detonado. Tá bloqueando tudo.",--Guys, the wreckage is incredible. Rubble blocking everything.
	pln_as1_02_02 = "Vlad está querendo falar com vocês aqui.",--Vlad's very keen on talking to you on this one.
	pln_as1_12_03 = "Vão para a Área de Construção! Rápido!",--Get to the construction yard! Hurry!
	pln_as1_13_03 = "Acendem o sinalizador, gangue. o Piloto não consegue ver sem ele.",--Light the flare, gang. Pilot is blind without it.
	pln_as1_10_01 = "Beleza. Agora, coloquem o C4 no muro. Vamos dar o fora.",--All right. Now slap the C4 on there. We're busting our way out.
	pln_as1_01_03 = "Cidade dos Anjos. Parece que o terremoto detonou mais um pouco...",--City of Angeles. Looks like the quake made a few more...
	pln_as1_01_02 = "Jesus, parace ainda pior que nas notícias, mas...",--Jesus, it looked bad on the news, but...
	pln_as1_04_02 = "Segundo caminhão não pode estar longe do primeiro. Encontrem ele.",--Second truck can't be too far from the first. Find it.
	pln_as1_11_02 = "E já era os cofres. Agora eu quero esse caminhão na Área de Construção. Estamos quase lá!",--And that's it for the safes. Now I want that truck in the yard. We're closing this one!
	pln_as1_11_03 = "Bom. Todos os cofres estão dentro. Agora levem o caminhão de volta pra construção, gangue - Rápido!",--Great. All the safes are in. Now let's see the truck back at the yard, gang - hustle!
	pln_as1_13_01 = "Pessoal, o piloto está rodando em círculos! Coloquem esse sinalizador!",--Guys, the pilot is circling! Drop the flare!
	pln_as1_14_01 = "Não temos tempo de carregar e descarregar os cofres. O helicóptero vai carregar o caminhão todo logo. Ele consegue carregar. Vocês só precisam entrar!",--We don't have time to load and unload the safes. The chopper's just going to carry the truck. It can do it. You just need to get in!
	pln_as1_16_01 = "Meu Deus, Los Angeles está uma bagunça. Bloqueando tudo.",--Christ, LA's wrecked. Rubble everywhere.
	pln_as1_18_01 = "Não vai ter outro jeito de vocês sairem carregando isso nas suas costas. Esperem aí, eu vou achar um transporte.",--There's no way you're hauling those out on your backs. Hold on, I'm going to find you a transport.
	pln_as1_21_02 = "Isso deve servir! Comecem a carregar os cofres e coloquem dentro do caminhão!",--That will do! Start getting them out and into the truck!
	
	-- Legendas (Vlad)
	vld_as1_08_04 = "Esses Californianos são tão rudes. Ensinem a eles alguns modos de DC.",--These Californians are so rude. Teach them some DC manners.
	vld_as1_08_13 = "Quantos esqueletos vão ser enterrados nesse terremoto.",--How many skeletons will be getting thrown up with this earthquake.
	vld_as1_08_05 = "Eles vão estar cavando pedaços de policiais por semanas!",--They'll be digging chunks of cop out of the rubble for weeks!
	vld_as1_08_03 = "Califórnia está afogando no Pacífico. E esses cofres não flutuam.",--California is sinking into the Pacific. And those safes don't float.
	vld_as1_10_03 = "Vocês não vão deixar uma coisinha como um muro parar vocês, vão?",--You're not going to let a little thing like a wall stand in your way, are you?
	vld_as1_16_03 = "Entrem no caminhão, todo mundo. Tem biscoitos e doces aí dentro, eu prometo.",--Get in the truck, all of you. There's cookies and candy inside, I promise.
	vld_as1_05_01 = "Sim! Bom, aí estão os meus cofres. Meus bebês. Meus bebês que pesam 180 quilos. Eles vão quebrar as suas colunas se tentarem carregar eles. Procurem por um transporte.",--Yes! Good, there are the safes. My babies. My 400lb babies. They'll break your backs if you try to carry them away. Look for a transport.
	vld_as1_02_01 = "Esse contrato é importante. Os cofres estão nesses caminhões, vocês precisam tirar eles daí... hã, em segurança. Escutaram?",--This job is important. The safes in those trucks, you need to get them out...uh, safely. You hear?
	vld_as1_01_03 = "Os celulares estão tudo fudidos, porra. Ah, meus amigos!",--Fucking phones are fucked. Ah, my friends!
	vld_as1_08_10 = "Vocês já sabem as suas falas. As falas que eu sei. Sim, a porra do sputnik! Haha",--You guys know your lines. The lines I know.  Yeah, fucking sputnik! Haha!
	vld_as1_08_12 = "Olhem só pra esse concreto todo fudido. O fogo, os gritos, qualquer coisa, eu gosto desse lugar!",--Look at all this fucked up concrete. The fires. The screaming. If anything, I like the place more! Haha!
	vld_as1_13_02 = "Não fiquem enrolando, sim?",--Don't slacken off now, yes? 
	vld_as1_12_01 = "Quantos cofres tem aí? Um quarto? Continuem.",--How many safes is that? A quarter? Keep going.
	vld_as1_05_02 = "Aí estão os cofres. Que bonitos! Vocês vão precisar de um transporte para levarem eles com segurança. Procurem aí.",--There are the safes. How beautiful they are. You will need transport to get them out safely. Look around.
	vld_as1_12_02 = "Eu sei que os seus músculos estão uma merda, mas continuem carregando os cofres.",--I know you're muscles are aching, but keep lifting those safes.
	vld_as1_15_03 = "Esses cofres são bem preciosos para arriscar nessas ruas, então, eu estou mandando um helicóptero. O problema é que o piloto não consegue ver. Vocês precisam soltar um sinalizador pra ele.",--Those safes are too precious to risk on these roads, so I'm sending in a chopper. Thing is, pilot can't see a damn thing. You need to drop a flare for him.
	vld_as1_10_01 = "Esse C4? Finge que é um bebê perdido. Ame-o, alimente-o... depois coloque-o no muro para explodir tudo! Sim.",--That C4? Pretend it is poor lost baby. Love it, nurture it....then put it on wall and blow it up! Yes.
	vld_as1_01_01 = "Isso está ligado? Olá... onde estão esses palhaços de mer- ah, aí vocês estão!",--Is this on? Hello...where are those fucking clow - oh, there you are!
	vld_as1_01_02 = "Testando, testando... um, dois... Mary transou com um cordeiro. Oh, aí vocês estão!",--Testing, testing...One, two...Mary fucked a little lamb. Oh, you there!
	vld_as1_02_02 = "Prestem atenção. Cada um desses cofres precisam ser recuperados. Vocês não podem deixar aí.",--Listen closely. Every single one of those safes needs to be recovered. You can't let me down on.
	vld_as1_02_03 = "Abram os ouvidos. Os cofres estão nos caminhões. Eu preciso de cada um deles. Em segurança. Agora, fechem os ouvidos. Peguem os cofres.",--Open ears. The safes are in the trucks. I need every single one to come out. Safely. Now, close ears. Get safes.
	vld_as1_03_01 = "Vamos, seus palhaços! Encontrem os caminhões! Grande, verde, rodas... o caminhão inteiro!",--Come on, clowns! Find the trucks! Big, green, wheels..the whole thing!
	vld_as1_03_02 = "Parem de admirar as vistas e encontrem os caminhões!",--Stop admiring the sights and find those trucks!
	vld_as1_03_03 = "Ei, vocês idiotas estão tomando banho de sol? Os caminhões, se lembram?!",--Hey, you assholes taking some sun? The trucks, remember?!
	vld_as1_04_01 = "Abram os caminhões! Estão com o dedo no cu?!",--Pop those trucks open! Get fingers out of assholes!
	vld_as1_04_02 = "Abram os caminhões, meus amigos.",--Slice those trucks open, my friends.
	vld_as1_04_03 = "Vamos, seus palhaços, abram os caminhões!",--Come on, clowns, get the trucks open!
	vld_as1_05_03 = "Ah, os cofres. Meus preciosos. Levem eles com segurança. Achem um transporte.",--Ahhh, the safes. My precious little. Bring them safely out. Find a transport.
	vld_as1_08_01 = "Ah, Los Angeles! Piscinas, estrelas dos filmes... hábitos de cozinhar, sonhos na merda. Eu amei.",--Ahhh! LA! Swimming pools, movie stars...coke habits, shattered dreams. I love it.
	vld_as1_08_02 = "Eles tão dizendo como um dos maiores. 8.8 magnitude. Eu não estou cientista, mas eu acho que o Los Angeles está bem fudida!",--They're saying it was the Big One. 8.8 magnitude. I'm not a scientist, but I think that means LA's fucked. Haha!
	vld_as1_08_06 = "Quem tem a coluna mais forte? Vamos, mostrem pro Tio Vlad o quão forte vocês são!",--Who has the strongest back? Come on, show your Uncle Vlad how well you can carry!
	vld_as1_08_07 = "Eu quero esses cofres pra fora daí. E se tiver um outro tremor de terra?",--I want those safes out of here. What if there is an aftershock? 
	vld_as1_08_08 = "Levando os cofres da Costa Oeste até os meus amigos da Costa Leste!",--Bringing west coast safes to my east coast players!
	vld_as1_08_09 = "Vocês vão ser as estrelas de Los Angeles. Bonitão, perigoso e vocês nem precisam de dublês!",--You guys are going to be LA's latest superstars. Good-looking, dangerous..and even do your own stunts!
	vld_as1_08_11 = "Vocês estão concorrendo ao oscar de Melhor Grupo de Fodões.",--You guys are in the running for a Best Performance By A Crew Of Badasses oscar.
	vld_as1_08_14 = "Esse grupo da Costa Oeste especializa em mandar grande número de customizações, guardados em cofres. Eles me contrataram para ser o cara da Costa Leste. É um bom negócio!",--This West Coast crew specialises in shifting huge numbers of customisations, stored in safes. They made me their man on the East Coast. It's a big deal! My way in!
	vld_as1_09_01 = "Não sejam tímido com os explosivos, amigos. C4 bom. C4 é amiguinho, tá?",--Don't be shy of the explosives, friends. C4 good. C4 is friend, yes?
	vld_as1_09_02 = "Porque ninguém está pegando o C4? Não está fazendo sentindo nenhum pro Vlad.",--Why is no-one getting the C4? Makes no sense to Vlad. 
	vld_as1_09_03 = "Não fiquem com medo do C4. Não vai explodir. Bom, agora não. Vlad é engraçado...",--Don't be afraid of the C4. It won't explode. Well, not yet. Vlad is funny..
	vld_as1_10_02 = "Alguns muros estão de pé depois do terremoto... tinha que ser esses. Explodam essa porra toda.",--Few walls left standing after the earthquake...had to be these ones. Blow the fucking things.
	vld_as1_11_01 = "Boa. Esse primeiro caminhão vazio. Como as suas colunas estão indo?",--Great. That's the first truck emptied. How are your backs feeling?
	vld_as1_11_02 = "Ah, o primeiro caminhão vazio. Vista bonita. Cofres não são tão pesados, são?",--Ah, the first truck to be emptied. Beautiful sight. Safes aren't too heavy, are they?
	vld_as1_12_03 = "Os cofres são pesados, eu sei, mas será um bom exercício.",--The safes are heavy, yes I know, but this is good exercise.
	vld_as1_13_01 = "É a metade de cofres fora dos caminhões. Peguem a outra metada!",--That's half of the safes out of the trucks. Half way there!
	vld_as1_13_03 = "Bom, bom.",--Good, good.
	vld_as1_14_01 = "As suas colunas devem estar doendo agora. Mas não quando vocês pararem de carregar esses cofres.",--Your limbs must be screaming now. But not as much as if you stop grabbing those safes.
	vld_as1_14_02 = "Tão perto, agora. Parece que tem três-quarto dos cofres dentro do caminhão. Andem logo! Acredito em vocês!",--So close now. That looks like three-quarters of the safes out of the truck. Keep going! I believe in you!
	vld_as1_14_03 = "Bom, bom. Não desistem agora.",--Good, good. Don't surrender now. 
	vld_as1_15_01 = "Não vão arriscar dirigir sem eles. Chamei o piloto de volta, mas ele não pode ver vocês por causa da poeira e a fumaça. Acendam um sinalizadora pra ele!",--Not going to risk driving them out. Got the pilot headed back, but he can't see you cos of all the dust and smoke. Light a flare for him!
	vld_as1_15_02 = "As ruas estão bem detonadas com coisas inúteis como a ambulâncias e essas merdas aí. Acendam um sinalizador pro piloto conseguir ver vocês.",--The roads are too damned jammed with useless things like ambulances, and other shit like that. We're flying you out. Light a flare so the pilot can see you.
	vld_as1_16_01 = "Vamos, vocês estão esperando pelo o que, porra? Entrem no caminhão!",--Come on, what the fuck are you waiting for? Get in the truck!
	vld_as1_16_02 = "Os cofres estão dentro, mas vocês não. Isso faz o Vlad triste e Vlad triste é Vlad puto!",--The safes are loaded but you're not. This makes Vlad sad, and sad Vlad's getting mad!
	vld_as1_17_01 = "Eu sabia que podia confiar em vocês, amigos!",--I knew I could count on you, my friends! 
	vld_as1_17_02 = "Sonho de Califórnia, meus amigos! Sonho de dinheiro, joias, armas e.... esse foi um grande dia!",--California dreaming, my friends! Dreaming of money, and loot, and guns, and....it's a great day!
	vld_as1_17_03 = "Até mesmo a Mãe Natuzera não conseguiu parar o Vlad ou a Gangue PAYDAY!",--Even Mother Nature couldn't stop Vlad Or the Payday Gang! 
	
	-- Legendas (Outros)
	plt_as1_intro_01_01 = "Vou deixar vocês bem aqui. Estejam prontos!",--I'm putting you down here. Get ready to clear!
	plt_as1_intro_01_02 = "Chegamos. Aguardem!",--Here's the dropzone. Stand by!
	plt_as1_intro_01_03 = "Vocês estão prontos? É aqui onde vocês vão sair.",--You guys ready? This is where you get out.
	plt_as1_04_01 = "Ok. Tô vendo o sinalizador. Chegando aí.",--Okay. I see the flare. Starting descent.
	plt_as1_04_02 = "Vejo o sinalizador! Estou chegando.",--I see the flare! I'm coming in.
	plt_as1_04_03 = "Beleza, aí está o sinalizador. Descendo.",--All right, there's the flare. Beginning descent.
	plt_as1_03_03 = "Vai levar anos pra reconstruir isso. Só me dá um minuto, estejam prontos.",--It'll take years to rebuild this. Just one minute, be ready.
	plt_as1_02_01 = "Os serviços de emergência estão tentando tirar o meu helicóptero para evacuação. Vou chegar aí em 2 minutos.",--Emergency services are trying to commandeer my chopper for evacs. I'll be there in 2.
	plt_as1_02_03 = "As autoridades estão tentando tirar o meu helicóptero. Mas civis feridos não pagam muito bem. Vou chegar em 2 minutos.",--Authorities are trying to boost my bird. But injured civs don't pay so well. I'll be with you in 2.
	plt_as1_03_01 = "A poeira está foda. Difícil de ver. Um minuto eu chego.",--Dust is thick. Hard to see shit. I'm one minute out.
	plt_as1_01_02 = "Três minutos chegando aí. Vocês deveriam ver coisas daqui em cima.",--Three minutes out. You should see things from up here.
	plt_as1_02_02 = "Sob pressão aqui para virar o helicóptero para evacuação médica. Mas eles não pagam muito bem. Vou estar aí em 2 minutos.",--Under pressure here to turn the chopper over to medical evac. But they pay shit. I'll be there in 2.
	plt_as1_01_01 = "Jesus, a devastação... chego aí em 3 minutos.",--Jesus, the devastation....with you in 3.
	plt_as1_01_03 = "Ah, cara. A cidade está toda fudida. Estou indo aí, em três minutos.",--Oh man. City is fucked. On my way, three minutes.
	plt_as1_03_02 = "Está foda a detonação. Falta um minuto.",--The wreckage is incredible. I'm a minute away from you.
	
	-- Objetivos
	hud_escape_jolly_mission9 = "Use o sinalizador para marcar a localização.",--Use a flare to mark the pick up location.
	hud_escape_jolly_mission5 = "Use o C4 para derrubar o muro da construção. Dentro tem um caminhão que podemos usar para transporte dos cofres.",--Use C4 to breach the construction site walls. Inside is a truck we can use to transport the safes.
	hud_escape_jolly_mission1 = "Os transportes do Vlad estão presos pelo terremoto. Precisamo localizar eles.",--Vlad's transport vans have been tossed about by the earthquake. We need to locate them.
	hud_escape_jolly_mission1_hl = "Localize as Vans de Transporte",--Locate the transport vans
	hud_escape_jolly_mission3_hl = "Espere pelo C4",--Wait for the C4
	hud_escape_jolly_mission4 = "Pegue a C4 e Use no Muro da Construção.",--Grab the C4 and use it on the construction site wall.
	hud_escape_jolly_mission10 = "O helicóptero está chegando, aguentem até que chegue.",--The helicopter is on its way, hold out until it arrives.
	hud_escape_jolly_mission6 = "Roubem o caminhão e use-o para recuperar os cofres.",--Steal the truck and use it to retrieve the safes.
	hud_escape_jolly_mission6_hl = "Roube o Caminhão",--Steal the truck
	hud_escape_jolly_mission7_hl = "Assegure os Cofres dentro do Caminhão",--Secure the safes inside the truck
	hud_escape_jolly_mission5_hl = "Plante o C4 para Derrubar o Muro",--Use C4 to breach the wall
	hud_escape_jolly_mission2_hl = "Arrombe as Vans",--Break into the vans
	hud_escape_jolly_mission2 = "Agora que você encontrou as vans, está na hora de arrombar as vans e pegar os cofres.",--Now that you've found the vans, it's time to break into them and grab those safes.
	hud_escape_jolly_mission12 = "Mantenha os cofres protegido enquanto o Bain procura por uma rota de fuga e um transporte.",--Keep the safes protected while Bain looks for a way out and a transport vehicle
	hud_escape_jolly_mission12_hl = "Aguarde pelo Bain",--Wait for Bain
	hud_escape_jolly_mission9_hl = "Marque a Localização de Fuga",--Mark the escape location
	hud_escape_jolly_mission4_hl = "Pegue o C4",--Pick up the C4
	hud_escape_jolly_mission8_hl = "Dirija até a zona da coleta",--Drive to the pick up zone
	hud_escape_jolly_mission11 = "O helicóptero está saindo, todo mundo precisa estar dentro do caminhão!",--The helicopter is taking off, everyone needs to be inside the truck!
	hud_escape_jolly_mission11_hl = "Entre no Caminhão",--Get in the truck
	hud_escape_jolly_mission10_hl = "Espere pelo Helicóptero",--Wait for the Helicopter
	hud_escape_jolly_mission8 = "Com toda essa destruição, vamos precisar de uma evacuação da cidade.",--With all of the destruction, we will need an evac out of the city.
	hud_escape_jolly_mission3 = "Um helicóptero vai soltar o C4 que vamos precisar para derrubar o muro.",--A helicopter will drop off the C4 needed to breach the construction site wall.
	hud_escape_jolly_mission7 = "Nós vamos precisar de um caminhão que pode servir de transporte para os cofres. Joguem os cofres aí atrás.",--We can use the truck for transporting the safes. Toss the safes in the back.	
		})
end)