Hooks:Add("LocalizationManagerPostInit", "Ogivasnucleares", function(loc)
	LocalizationManager:add_localized_strings({
	-- Nomes e Descrições
	heist_shoutout_raid = "Meltdown",--Meltdown
	heist_shoutout_raid_hl = "Meltdown",--Meltdown
	heist_shoutout_raid_crimenet = "Escutei sobre o trabalho excepcional que vocês fizeram se esgueirando no Armazém da Murkywater. Muito impressionante! Preciso que vocês voltem lá. Aqueles mercenários tem 'uma coisinha' escondida. Algo que eu gostaria. Os Murkies estão de saída, então preciso disso antes que isso suma numa toca de coelho. $NL;$NL; » Acesse o Complexo da Murkywater  $NL; » Localize o Cofre $NL; » Trave o Ventilador do Cofre $NL; » Transporte o Loot para o Trem",--I heard about the outstanding job you did sneaking into that Murkywater warehouse. Most impressive. I need you to go back there. Those mercenaries've got a 'little something' tucked away. A little something I would like. The Murkies are pulling out, and I need this before it disappears down some rabbit-hole.$NL;$NL; » Access the Murkywater compound $NL; » Locate the vault $NL; » Jam the vault vent  $NL; » Transport the loot to the train
	heist_shoutout_raid_briefing = "Nós estamos atacando o Armazém da Murkywater para o Vlad. Não sei qual é o alvo, ou o que tem lá, mas está escondido em um cofre, que está num contêiner marcado deles. Entrem lá, encontrem o cofre e tirem o que quer que aquele Russo louco queira. Murkies estarão super alerta quando vocês chegarem lá, e os policiais serão rápido na resposta, então precisam entrar lá e terminar o trabalho rapidamente. Rápido significa: BARULHO. Sem furtividade dessa vez. Travas desativadas desde o começo. E, não se esqueçam, tem loot por todo o lugar. Vejam o que conseguem pegar.",--We're hitting the Murkywater warehouse for Vlad. Don't know what the target is, or where it is, but it's tucked away in a vault, which itself is in one of their branded shipping containers. Get in there, find the vault and get out whatever it is that crazy Russki wants. $NL;$NL;Murkies will be on high alert when you get there, and the cops'll be quick to respond, so you gotta get in there and do the job fast. Fast means loud. No tiptoeing this one. It's safeties off from the get-go. And, don't forget, there's loot all around. See what you can grab.

	-- Legendas (Bain)
	pln_ko1b_intro_01_01 = "Como nos velhos tempos, huh?",--Feels like old times, huh?
	pln_ko1b_intro_01_02 = "Tenho lembranças desse lugar às 4:00am...",--Got memories of this place at 4am...
	pln_ko1b_intro_01_03 = "Muita atividade. Fiquem calmos.",--Lot of activity. Stay frosty.
	pln_ko1b_13_03 = "Você está louco, Vlad? Isso são Ogivas ativas!",--Are you nuts, Vlad? These are live nukes!
	pln_ko1b_07_03 = "Provavelmente há pés de cabra dentro do Armazém. Verifiquem-no.",--Crowbars are probably inside the warehouse. Check it.
	pln_ko1b_08_01 = "Beleza. Esse foi o primeiro. O calor está se acumulando. Desativar mais ventiladores irá acelerar isso.",--All right. That's the first. Heat is building. Disabling more fans will speed this up.
	pln_ko1b_02_01 = "O cofre estará em um desses contêineres de envio da Murkywater. Verifiquem eles!",--The vault is going to be in one of these Murkywater shipping containers. Check them!
	pln_ko1b_01_01 = "Beleza. Segurança desligada. Desçam lá!",--All right. Safeties off. Get down there!
	pln_ko1b_06_03 = "Vocês precisam encontrar os pés de cabra. Eles provavelmente estarão no Armazém. Emperrem eles nos ventiladores do cofre. O calor irá se acumular dentro, e... voila!",--You need to find crowbars. They are most likely in the warehouse. Jam them into the vault fans. The heat builds inside, and... voila!
	pln_ko1b_09_03 = "Ótimo. Olhem a temperatura subindo. Sheesh, deve ter algo quente pra cacete lá dentro.",--Great. Look at that temperature climb. Sheesh, must be something hotter than hell in there.
	pln_ko1b_01_03 = "Esse é um Armazém da Murky. Beleza, peguem eles!",--That's the Murky warehouse. All right, get at 'em!
	pln_ko1b_02_03 = "O cofre estará embalado para transporte, então verifiquem aqueles contêineres.",--The vault will be packed for transport, so check those Murky shipping containers.
	pln_ko1b_12_01 = "Aquilo é... uma Ogiva nuclear!? Eu... não... olhem, apenas peguem isso. Com cuidado!",--Is that... a nuclear warhead!? I... don't... look, just grab it. Carefully!
	pln_ko1b_02_02 = "Acho que o cofre estará dentro de um contêiner da Murky. Abram eles.",--Guess the vault is gonna be in a Murky shipping container. Get opening them.
	pln_ko1b_04_02 = "Conectando o Vlad...",--Patching in Vlad...
	pln_ko1b_10_03 = "Último ventilador desativado. A temperatura está fora dos limites. O conteúdo deve estar assando!",--Last fan disabled. Temperature is off the hook. The contents must be scorching!
	pln_ko1b_05_01 = "Próximo passo - Abrir o cofre. Achem alguns pés de cabra dentro do Armazém e emperrem eles nos ventiladores de refrigeração na parte de trás. Isso irá aumentar a temperatura dentro, e acionar o sistema anti-falhas.",--Next step - open the vault. Find some crowbars inside the warehouse and jam them into the cooling fans at the back. That'll raise the temperature within, and engage the failsafe.
	pln_ko1b_09_02 = "Boa. A temperatura está subindo mais rápido. Deve ter algo quente lá dentro.",--Good. Temperature is climbing faster. Must be something hot in there.
	pln_ko1b_15_01 = "Aquele trem está um pouco longe. Eu não quero vocês manuseando essas Ogivas por muito tempo. Vejam se conseguem achar um carro.",--That train is some distance away. I don't want you handling those nukes for long. See if you can find a car.
	pln_ko1b_12_02 = "Não pode ser... a porra de uma Ogiva!? Vlad!",--That can't be... a goddamn nuke!? Vlad! 
	pln_ko1b_18_01 = "Isso aí. Agora deem o fora daí!",--That's it. Now get the hell out of there!
	pln_ko1b_01_02 = "Certo, aí está. Derrubem a porta!",--Okay, there it is. Kick the door down!
	pln_ko1b_17_03 = "Nós conseguimos a armadura quando fizemos isso sorrateiramente, se lembram?",--We got the armor from here when we did it quiet, you recall?
	pln_ko1b_04_01 = "Vlad quer uma palavra...",--Vlad wants a word...
	pln_ko1b_13_01 = "Vlad, você está maluco! Ogivas!?",--Vlad, are you crazy! Nukes!?
	pln_ko1b_17_02 = "Se lembram de quando levamos a armadura samurai daí? Ahhh, bons tempos!",--You remember when we hauled the samurai armor out of here? Ahhh, good times!
	pln_ko1b_14_03 = "Droga, essas Ogivas são pesadas. Talvez usar as empilhadeiras.",--Damn, those warheads are heavy. Maybe use the forklifts.
	pln_ko1b_17_01 = "Aqui é onde vocês levaram a armadura samurai. Se lembram?",--This is where you boosted the samurai armor. Remember?
	pln_ko1b_11_02 = "Essa é a porta. Agora peguem as coisas.",--That's the door. Now grab the stuff.
	pln_ko1b_15_03 = "Vejam se tem um carro por aí. O mais breve que puderem levar essas Ogivas suspeitas para o trem do Vlad, melhor!",--See if there's a car around there. Sooner you get those shady Russian nukes to Vlad's train the better!
	pln_ko1b_06_01 = "Lembrem-se: vocês precisam achar pés de cabra e emperrá-los nos ventiladores do cofre. Eles provavelmente estão dentro do Armazém.",--Remember: you need to find crowbars and jam them into the vault's fans. They are most likely inside the warehouse.
	pln_ko1b_08_03 = "Esse é o primeiro ventilador. A temperatura está aumentando. Emperrem mais ventiladores para acelerar as coisas.",--That's the first fan. Temperature's rising. Jam more fans to speed things up.
	pln_ko1b_09_01 = "Boa. Está ficando quente. O que diabos tem aí dentro?",--Nice. It's getting hotter. What the hell is in there?
	pln_ko1b_11_03 = "Cofre aberto. Gangue, peguem o que tiver dentro!",--Vault's open. Grab whatever's inside, gang!
	pln_ko1b_05_03 = "Esse cofre tem um Calcanhar de Aquiles. É controlado por temperatura. Emperrem os ventiladores na parte de trás com pés de cabra. A temperatura subirá e o sistema anti-falhas abrirá as portas. Fácil.",--This vault's got an Achilles Heel. It's temperature controlled. Jam the vent fans at the back with crowbars. The temperature rises and the failsafe opens the door. Easy. 
	pln_ko1b_11_01 = "A porta do cofre está aberta. Entrem e peguem o loot!",--Vault door's open. Get in and grab the loot!
	pln_ko1b_04_04 = "Vlad quer conversar com vocês...",--Vlad wants to speak with you...
	pln_ko1b_03_01 = "Lembrem-se, procurem pelo cofre dentro dos contêineres da Murkywater.",--Remember, check the Murkywater shipping containers for the vault.
	pln_ko1b_03_02 = "Gangue, encontrem o cofre. Deverá estar dentro de um contêiner. Provavelmente aquelas da Murkywater.",--Gang, find that vault. It'll be in a shipping container. Probably those Murkywater ones.
	pln_ko1b_03_03 = "Pessoal, o cofre - Encontrem ele! Verifiquem os contêineres da Murkywater.",--Guys, the vault - find it! Check the Murkywater containers.
	pln_ko1b_04_03 = "Vlad quer falar com vocês...",--Vlad wants to talk to you...
	pln_ko1b_05_02 = "Esses cofres tem uma fraqueza. Um sistema anti-falhas abrirá a porta se a temperatura ficar muito alta. Procurem em volta do Armazém por pés de cabra, e coloquem eles nos ventiladores de trás.",--These vaults have one weakness. A failsafe will open the door if the temperature inside gets too high. Look around for crowbars in the warehouse, and jam them into the rear fans.
	pln_ko1b_06_02 = "Procurem por pés de cabra no Armazém. Coloquem eles nos ventiladores do cofre, e esperem a termodinâmica fazer o resto.",--Look around for crowbars in the warehouse. Stick them into the vault's fans, and wait for thermodynamics to do the rest.
	pln_ko1b_07_01 = "Meu palpite seriam os pés de cabra dentro do Armazém.",--My guess would be the crowbars are inside the warehouse.
	pln_ko1b_07_02 = "O Armazém é onde vocês terão mais chance de achar um pé de cabra.",--The warehouse is where you're most likely to find a crowbar.
	pln_ko1b_08_02 = "Certo, ótimo. A temperatura está subindo. Só aguardar, mas emperrar mais ventiladores irá acelerar isso.",--Okay, great. The temperature is climbing. Wait it out, but jamming more fans will speed it up.
	pln_ko1b_10_01 = "É isso aí para os ventiladores. A temperatura está aumentando rapidamente. O que diabos tem lá dentro?",--That's it for the fans. Temperature is spiking fast. What the hell is in there?
	pln_ko1b_10_02 = "Esse é o último ventilador. Cara, olhem só a temperatura subindo. Tenho um mal pressentimento sobre isso.",--That's the last fan. Man, look at that temperature climb. I got a bad feeling about this.
	pln_ko1b_12_03 = "Eu... uh... beleza. Então nós levaremos as Ogivas nucleares. Pessoal, sejam muito, muito gentis com essas coisas.",--I... uh... okay. So we're boosting nuclear warheads. Guys, be very, very gentle with those things.
	pln_ko1b_13_02 = "Vlad, quebrar shoppings é uma coisa. Roubar tiaras é uma coisa. Mas Ogivas!?",--Vlad, smashing malls is one thing. Stealing tiaras is one thing. But nukes!?
	pln_ko1b_14_01 = "Essas Ogivas são muito pesadas. Usem as empilhadeiras para mover elas.",--Those warheads are damned heavy. Use the forklifts to shift them.
	pln_ko1b_14_02 = "Aquelas empilhadeiras serão úteis para mover as Ogivas.",--Those forklifts will be useful for moving the warheads.
	pln_ko1b_15_02 = "Procurem por uma maneira de chegar mais rápido no trem. Não queremos vocês lidando com essas velhas Ogivas Russas mais tempo do que o necessário. ",--Look for a way to get to the train quickly. Don't want you guys handling those old Russian nukes longer than you need to.
	pln_ko1b_16_01 = "Isso aí. Agora vocês podem sair daí, ou voltar e roubar mais loot da Murky.",--That's it. Now you can get the hell out of there, or head back and snag more Murky loot.
	pln_ko1b_16_02 = "Terminamos. Vocês podem deixar aquele Ivan louco com suas Ogivas, ou voltar e pegar mais um pouco de loot.",--We're done. You can leave that crazy Ivan with his nukes, or head back and grab more loot.
	pln_ko1b_16_03 = "Esse foi o último. Agora vocês podem ir bem longe, ou voltar para o Armazém para mais loot.",--That's the last one. Now you can get far away, or return to the warehouse for more loot.
	pln_ko1b_18_02 = "Acabamos. Agora sumam! Deixem o Vlad com seus novos brinquedos nucleares.",--We're done. Now bail! Leave Vlad with his nukes.
	pln_ko1b_18_03 = "Esse foi o último. Meu conselho? Ir bem longe, o mais rápido que puderem!",--That's the last one. My advice? Get far away, as fast as you can!.
	
	-- Legendas (Vlad)
	vld_ko1b_05_09 = "Todo mundo se sentindo bem, sim? Alguem com, não sei, pele descascando e mostrando o osso?",--Everyone feeling good, yes? Anyone with, I don't know, skin peeling away and showing bone?
	vld_ko1b_02_03 = "Sim. O cofre! Isso é bom. Isso é muito bom!",--Yes. The vault! This is good. This is very good!
	vld_ko1b_02_02 = "Vocês acharam. Bom! Bom. Sabia que podia depender de vocês.",--You found it. Good! Good. I knew I could depend on you.
	vld_ko1b_cbf_01_01 = "Escutei sobre o trabalho excepcional que vocês fizeram se esgueirando no Armazém da Murkywater. Muito impressionante. Preciso que vocês voltem lá. Aqueles mercenários tem 'uma coisinha' escondida. Algo que eu gostaria. Os Murkies estão de saída, então preciso disso antes que isso suma numa toca de coelho.",--I heard about the outstanding job you did sneaking into that Murkywater warehouse. Most impressive. I need you to go back there. Those mercenaries've got a 'little something' tucked away. A little something I would like. The Murkies are pulling out, and I need this before it disappears down some rabbit-hole.
	vld_ko1b_03_01 = "Ah, não molhe as calças, Bain! Eu tenho um comprador. Muito distante. Está tudo bem.",--Ah, don't wet your knickers, Bain! I have buyer. Very far away. Is all good. 
	vld_ko1b_01_03 = "Aqueles Murkies desgraçados irão tentar enviar as mercadorias por navio, então verifiquem os contêineres!",--Those Murky bastards are going to be trying to ship the goodies out, so check their containers!
	vld_ko1b_03_03 = "Bain, não chore. Está tudo bem. O comprador pagará bem por elas. Eles estão bem longe.",--Don't cry, Bain. It's all fine. Buyer pays big for them. They're very far away.
	vld_ko1b_05_07 = "Espero que vocês não estejam ficando doentes. Maldito resfriado passando por aí. É, vocês provavelmente só tem um resfriado.",--Hope you're not getting sick. Nasty cold going around. Yeah, you probably just have cold.
	vld_ko1b_01_01 = "Por que vocês palhaços estão demorando tanto? Procurem pelo cofre nos contêineres da Murkyweater.",--What's taking you clowns so long? Check the Murkywater containers for the vault.
	vld_ko1b_05_02 = "Me digam se estiverem se sentindo mal. Ou se cair o cabelo. Ou se cair as bolas.",--Tell me if you are feeling sick. Or if hair fall out. Or balls fall off.
	vld_ko1b_05_04 = "Tenho certeza de que elas são muito seguras. Mas, independentemente, tenham certeza de aproveitar todos os dias do que restar de suas vidas.",--I am sure that they are very safe. But, regardless, make sure you enjoy every day of what life remains to you.
	vld_ko1b_06_01 = "Veem aquele carro potente? Aquele é um Gadaffi 1965 original Longfellow. É a carona de vocês agora.",--You see that muscle car? That's Gaddafi's 1965 original Longfellow. It's your ride now.
	vld_ko1b_08_01 = "Bom! Peguem o resto e nós iremos tirá-los daí. Espero que esse maldito trem seja um passeio suave.",--Good! Get the rest and we will get them out of here. I hope this fucking train is a smooth ride.
	vld_ko1b_01_02 = "Vamos lá, dedos fora do cu. O cofre estará em um contêiner da Murkywater.",--Come on, fingers out of assholes. The vault will be in a Murkywater container.
	vld_ko1b_02_01 = "Ahhh! O cofre. Posso até (respiração profunda) cheirar a mágica!",--Ahhh! The vault. I can almost (deep breath) smell the magic!
	vld_ko1b_03_02 = "Fiquem calmos, seus bebezões. Comprador distante. Provavelmente nem irá usar.",--Keep calm, you big baby. Buyer very far away. Probably won't even use.
	vld_ko1b_04_01 = "Aprontei um trem. Não muito longe. Tragam as Ogivas. Rápido!",--I got a train ready. Not too far away. Bring the warheads. Hurry!
	vld_ko1b_04_02 = "Agora tragam elas para o pátio de trens. Vocês estarão bem longe antes deles saberem.",--Now bring them to the train yard. You'll be far away before they know it.
	vld_ko1b_04_03 = "Eu tenho um trem esperando por elas. Está perto. Tragam as Ogivas. Rápido!",--I have a train waiting for them. It's close by. Bring the nukes. Hurry!
	vld_ko1b_05_01 = "Se sentindo bem? Algum sangramento retal? Olhem os buracos de cocô.",--Feeling okay? Any rectal bleeding? Check poop holes.
	vld_ko1b_05_03 = "Eles devem ser seguros, mas... algum de vocês sentem como se pequenos dentes se alimentassem da sua medula óssea?",--They should be safe, but... any of you feel like little teeth feeding on your bone marrow?
	vld_ko1b_05_05 = "Se sentem bem? Se o seu mijo brilhar no escuro, consultem um médico.",--Feeling good? If your piss glows in the dark, consult a doctor.
	vld_ko1b_05_06 = "Vocês estão se sentindo bem? Se sofrerem de envenenamento por radiação, enviarei flores e uvas a vocês.",--Are you all feeling okay? If you suffer radiation poisoning, I send you flowers and grapes.
	vld_ko1b_05_08 = "Espero que a radiação não chegue a vocês. Mas, pelo lado bom, talvez vocês desenvolvam superpoderes, sim?",--Hope the radiation isn't getting to you. But, on bright side, maybe you develop super-powers, yes?
	vld_ko1b_06_02 = "É aquele um Gaddafi vintage 1965 Longfellow? Vocês conseguem pensar em um jeito mais perfeito de trazer as Ogivas pra mim?",--Is that Gaddafi's vintage 1965 Longfellow? Can you think of a more perfect way to bring the nukes to me?
	vld_ko1b_06_03 = "Ah, ali! Um Longfellow! 1965, 4.7 litros V8. Vocês gostam de rodar com estilo, certo?",--Ah, over there! A Longfellow! 1965, 4.7 litre V8. You guys like to ride in style, right?
	vld_ko1b_07_01 = "Veem aquele carro potente? Aquele é um Gadaffi 1965 original. É a carona de vocês agora.",--You see that muscle car? That's Gaddafi's 1965 original. It's your ride now.
	vld_ko1b_07_02 = "É aquele carro potente Gaddafi vintage 1965? Vocês conseguem pensar em um jeito mais perfeito de trazer as Ogivas pra mim?",--Is that Gaddafi's vintage 1965 muscle car? Can you think of a more perfect way to bring the nukes to me?
	vld_ko1b_07_03 = "Ah, ali! 1965, 4.7 litros V8. Segunda melhor coisa feita naquele ano, sim?",--Ah, over there! 1965, 4.7 litre V8. Second best thing made that year, yes?
	vld_ko1b_08_02 = "Esse é o primeiro. Ah, tão pequeno, mas é o bastante para varrer Washington.",--That's the first.  Ah, such a small thing, but enough to wipe out Washington.
	vld_ko1b_08_03 = "Isso aí. Ahhhh, quase tentado. Para ver dois sóis no pôr do sol. (suspiro) Zavorazhivayushiy.",--That's it. Ahhhhh, almost tempted. To see two suns in the sunset.  (sighs) Zavorazhivayushiy.
	vld_ko1b_09_01 = "Sejam cuidadosos com eles. Não temos a intenção de transformar Washington em vidro derretido. Hoje não.",--Be careful with them. No intention to turn Washington into molten glass. Not today.
	vld_ko1b_09_02 = "Bom, bom. Continuem trazendo eles. Sejam gentis com minhas pequenas babushkas.",--Good, good. Keep bringing them. Be gentle with my little babushkas.
	vld_ko1b_09_03 = "Cada um irá trazer o resgate de um Rei. Isso é literalmente verdade (risos)!",--Each one will bring a King's ransom. That's literally true (laughs)!
	vld_ko1b_cnc_01_01 = "Meus queridos amigos. Apenas façam um trabalho rápido. Peguem 'uma coisinha' para mim do Armazém da Murkywater.",--My dear friends. Just a quick pick-up job. Fetch me a 'little something' from the Murkywater warehouse.
	vld_ko1b_cnc_01_02 = "Tem 'uma 'coisinha' que eu preciso que vocês peguem para mim do Armazém da Murkywater. Um rápido entrar e pegar.",--There's a 'little something' I need you to fetch me from the Murkywater warehouse. Quick smash and grab.
	vld_ko1b_cnc_01_03 = "Tem algo no Armazém da Murkywater, descendo o rio. Algo que eu gostaria.",--There's something at the Murkywater warehouse, down by the river. Something I would like.
	vld_ko1b_end_01_01 = "Ótimo trabalho, meus amigos. Novamente, vocês me serviram bem. Não se preocupem sobre as Ogivas. Aproveitem o dinheiro.",--Great job, my friends. Again, you have served me well. Don't worry about the nukes. Enjoy your money.
	vld_ko1b_end_01_02 = "Maravilhoso! Estou feliz que vocês sairam dessa sem colocar fogo na Costa Leste.",--Outstanding! Glad you got out of that one without setting the Eastern Seaboard on fire.
	vld_ko1b_end_01_03 = "Belo trabalho, meus amigos! Mal posso esperar para ver como os desgraçados da Murky irão explicar isso.",--Good work, my friends! Can't wait to see how those Murky bastards explain that one.
	
	-- Objetivos
	hud_heist_shoutout_raid2 = "Um dos contêineres especialmente marcados da Murkywater será o que tem o nosso cofre. Encontre-o.",--One of the specially marked Murkywater containers will be the one that holds our vault. Find it.
	hud_heist_shoutout_raid5 = "Transporte as Ogivas nucleares para o trem do Vlad no velho estaleiro.",--Transport the nuclear warheads to Vlad's train in the old dockyard.
	hud_heist_shoutout_raid2_hl = "Encontre o Cofre no Contêiner da Murkywater",--Find the vault in a Murkywater container
	hud_heist_shoutout_raid3_hl = "Use o Pé de Cabra para travar a Ventilação do Cofre",--Use crowbars to jam the vault ventilation
	hud_heist_shoutout_raid4 = "O calor irá aumentar lá dentro do cofre. Espere pelo sistema automático de segurança abrir a porta.",--The heat is rising inside the vault. Wait for the automatic failsafe to open the door.
	hud_heist_shoutout_raid_hl = "Se lembram daquele velho Armazém suspeito nas docas? Onde a Murkywater estava contrabandeando loot? Bem, nós estamos voltando para lá.",--You guys remember that sketchy old warehouse on the docks? Where Murkywater were smuggling in loot? Well, we're headed back there.
	hud_heist_shoutout_raid6 = "Pule no trem para fugir. Também tem mais loot no Armazém.",--Jump into the train to escape. There is also more loot back in the warehouse.
	hud_heist_shoutout_raid6_hl = "Fuja, ou Pegue mais Loot",--Escape, or pick up more loot
	hud_heist_shoutout_raid3 = "Encontre uma maneira de abrir o cofre. Pés de cabra podem ser emperrados nos ventiladores, o que afetará o sistema de refrigeração e acionará o sistema automático anti-falhas. Pés de cabra podem ser encontrados dentro do Armazém.",--Find a way to get the vault open. Crowbars can be jammed into the ventilation fans, which will affect the cooling system and engage the automatic failsafe. Crowbars can be found inside the warehouse.
	hud_heist_shoutout_raid1_hl = "Entre na Área do Armazém",--Get inside the warehouse area
	hud_heist_shoutout_raid1 = "Ganhe acesso ao complexo Murkywater. Desça dos telhados, ou use a tirolesa.",--Gain access to the Murkywater compound. Descend from the roofs, or use the ziplines.
	hud_heist_shoutout_raid4_hl = "Espere o Cofre Superaquecer",--Wait for the vault to overheat
	hud_heist_shoutout_raid5_hl = "Entregue as Ogivas no Trem",--Deliver warheads to the train
	hud_heist_shoutout_raid7 = "Pule dentro do Trem e Fuja.",--Jump into the train and escape.
	hud_heist_shoutout_raid7_hl = "Fuja!",--Escape!
		})
end)