Hooks:Add("LocalizationManagerPostInit", "roubandococainacomvrtafodaalemdebaternopapaaaaaaaaaaaaaaaaaaaaaaaaaaaaainoel", function(loc)
	LocalizationManager:add_localized_strings({
	-- Nomes e Descrições
	heist_moon_hl = "Roubo Natalino (Stealing Xmas)",
	heist_moon = "Roubo Natalino (Stealing Xmas)",
	heist_moon_hl_briefing = "O cunhado do Vlad se escondeu dos policiais na baía de carregamento do shopping. Parece que ele escondeu a cocaína em várias caixas, caixas que agora foram distribuídas para lojas em todo o shopping.  Ele também se disfaçou de Papai Noel roubou umas vodkas e ficou bêbado. Que bagunça. Os policiais desconfiaram do Noel bêbado e prenderam ele. Vocês precisarão libertá-lo e perguntar a ele se ele se lembra em quais caixas ele colocou a cocaína.",--Vlad's brother-in-law hid from the cops in the mall's loading bay. It seems he hid the coke in various boxes, boxes that have now been distributed to shops all over the mall. He also disguised himself in a Santa Claus costume and stole some vodka and got drunk. What a mess. The cops got suspicious of the drunk Santa and apprehended him. You'll need to free him and ask him if he remembers what boxes he put the coke in.
	heist_moon_crimenet = "Meu cunhado, aquele lixo inútil, estava transportando umas neves para mim - neve Colombiana, vocês sabem, para o Natal. Mas ele ferrou com tudo e foi seguido pela polícia. Ele estava se escondendo no Shopping Midtown, mas acho que os policiais pegaram ele. Malditos policiais Americanos, não há espírito Natalino nesse país! Eu sou um cara amigável, e o Natal é tudo sobre perdão, mas isso não é certo. Não é certo! Meus amigos, vocês tem que me ajudar. \n\n» Resgatem o Noel \n» Recuperem a cocaína do Vlad \n» Roubem a árvore de Natal e fujam",--My brother-in-law, that useless piece of trash, was transporting some snow for me - Colombian snow, you know, for Christmas. But he fucked up and was followed by the cops. He was hiding at the Midtown Mall, but I think the cops got him. Fucking American cops, there's no Christmas spirit in this country! I'm a friendly guy, and Christmas is about forgiving, but this is not ok. Not ok! You have to help me, my friends. \n\n» Rescue Santa\n» Recover Vlad's coke \n» Steal the Christmas tree and escape	
	
	-- Legendas
	vld_moon_intro_03 = "Vou começar a chamá-lo de Rudolph, aquele bêbado fodido de nariz vermelho! Achem ele, e achem minha cocaína!",--I'll start calling him Rudolph, that red-nosed drunk fuck! Find him, and find my coke!
	vld_moon_intro_02 = "Eu não desejava ter esse tipo de problemas. Hoje em dia é muito difícil achar uma ajuda que preste.",--I wish I didn't have these kinds of problems. It's so hard to find good help these days.
	vld_moon_intro_01 = "Dizem que é lindo ter uma família mas as vezes eu fico na dúvida. Agora achem aquele fodido estúpido e libertem ele - espero que ele não esteja bêbado demais para se lembrar em quais caixas escondeu minha cocaína.",--They say having family is beautiful but sometimes I don't know. Now find that stupid fuck and free him - hopefully he's not too drunk to remember in which boxes he hid the cocaine.
	vld_moon_15_02 = "O Garoto de lata está entupido de cocaína!",--Tin Boy is all coked up!
	vld_moon_24_03 = "VR - Vlad está pulando de alegria. Isso é o que importa para mim.",--VR - Vlad's Rejoicing. That's what this means to me.
	vld_moon_20_02 = "Peguem aqueles sapatos com a minha cocaína!",--Get the shoes with my cocaine!
	vld_moon_37_03 = "Isso foi divertido, sim? Mas é hora de partirmos!",--This was fun, yes? But it's time to go!
	vld_moon_19_02 = "Furem aquela porta, achem os sapatos, peguem a minha cocaína!",--Drill that door open, find the shoes, get my cocaine!
	vld_moon_03_01 = "Libertem meu cunhado, por favor. Ele é um idiota, mas é da família.",--Please free my brother-in-law. He's an idiot, but he's family.
	vld_moon_16_03 = "Garoto de Lata, onde estáaa você?",--Tin Boy - where aaare you?
	vld_moon_34_03 = "A árvore está partindo, coloquem o Noel a bordo!",--Tree is leaving - get Santa aboard!
	vld_moon_18_01 = "O quão difícil pode ser achar a merda de uma caixa de sapatos?",--How hard can it be to find a fucking shoe box?
	vld_moon_01_02 = "Irei dar a vocês uns belos presentes de Natal se resolverem isso para mim.",--I'll get you some nice Christmas presents if you solve this thing for me.
	vld_moon_05_03 = "Pedras e cocaína. Lindo!",--Stones and coke. Beautiful!
	vld_moon_25_01 = "Ah um cofre! Interessante!",--Ah a safe! How interesting!
	vld_moon_13_01 = "Mas que porra. Cocaína em presentes? É brilhante! Terei que me lembrar disso.",--What the fuck. Cocaine in toys? It's brilliant! I have to remember this.
	vld_moon_37_02 = "Feliz Natal! Vamos sair daqui!",--Merry Christmas! Let's get out of here!
	vld_moon_10_02 = "Peguem umas pedras preciosas para mim!",--Pick up some precious stones for me!
	vld_moon_05_01 = "Joalheria! Meu lugar favorito!",--Jewelry store! My favorite place!
	vld_moon_34_02 = "Meus amigos, não fiquem plantados aí que nem uma árvore. Hora de partir. ",--Let's make like a tree and leave, my friends!
	vld_moon_15_01 = "Ei Garoto de Lata! Você tem um problema com drogas!",--Hey Tin Boy! You got a drug problem!
	vld_moon_39_06 = "Ei, eu tenho planos para aquela árvore! Não a destruam!",--Hey, I have plans for that tree! Don't destroy it!
	vld_moon_20_03 = "Peguem minha cocaína!",--Get my cocaine!
	vld_moon_15_03 = "O Garoto de Lata conseguiu uma alma branca de neve! Hahaha!",--Tin Boy's got a snow-white soul! Hahaha!
	vld_moon_29_03 = "Meus amigos, em breve o resgate virá de cima!",--Rescue from above is coming soon, my friends!
	vld_moon_04_03 = "Eu aposto que vocês sempre quiseram socar aquele Papai Noel bastardo julgamental! Agora é a sua chance!",--I bet you've always wanted to punch that judgemental bastard Santa Claus! Now is your chance!
	vld_moon_04_02 = "Batam nesse idiota para que ele acorde!",--Smack that asshole so he wakes up!
	vld_moon_03_02 = "Espero que meu cunhado se lembre de onde ele colocou a cocaína.",--I hope my brother-in-law remembers where he put the cocaine.
	vld_moon_13_02 = "O bastardo estúpido escondeu a cocaína numa caixa de brinquedos!",--Stupid bastard hid the coke in a toy box!
	vld_moon_04_05 = "Deem um belo soco nele! Acordem-no, ensinem uma lição a ele!",--Give him a good punch! Wake him up, teach him a lesson!
	vld_moon_26_02 = "Vamos lá, o que estão esperando?",--Come on, what are you waiting for?
	vld_moon_17_03 = "Que idiota! Achem os sapatos!",--What an idiot! Find the shoes!
	vld_moon_21_03 = "Então, onde eles estão?!",--So where are they?!
	vld_moon_28_02 = "Talvez eu também devesse começar a importar vinho! Vinhos do Vlad! Eu gosto de como isso soa.",--Maybe I should start importing wine too! Vlad's Wines! I like the sound of it.
	vld_moon_22_03 = "Malditas caixas estão em todo o lugar. É como um video game...",--Fucking boxes everywhere. It's like that video game...
	vld_moon_35_02 = "Talvez ele se perca andando esses 2 metros para a árvore.",--Maybe he'll get lost walking those 2 meters to the tree.
	vld_moon_36_02 = "Que tal fazerem umas compras enquanto esperam?",--Maybe do some shopping while you wait?
	vld_moon_30_02 = "Façam a árvore ganhar vida, com neve!",--Make the tree come alive, with snow!
	vld_moon_23_01 = "VR? Mas que porra é essa?",--VR? What the fuck is that?
	vld_moon_38_01 = "Todo ano por volta do Natal eu fico um pouco nostálgico sabem. Velhos tempos, velhos inimigos.",--Every year around christmas I get a little nostalgic you know. Old times, old enemies.
	vld_moon_22_01 = "Não consigo acreditar que esse lugar é tão bagunçado.",--I can't believe this place is so messy.
	vld_moon_14_01 = "O que! Algum filha da puta está andando com minha cocaína! Achem ele!",--What! Some shopper asshole is walking around with my cocaine! Find it!
	vld_moon_19_01 = "Beleza, isso deve estar no depósito. Furem a porra da porta.",--Alright, it should be in the storage. Drill the fucking door.
	vld_moon_35_03 = "Espero que ele não desmaie novamente no último minuto.",--I hope he doesn't pass out again at the last moment.
	vld_moon_10_03 = "Isso aí! Agora peguem as jóias com cocaína!",--That's it! Now get the Jewels with the cocaine!
	vld_moon_23_03 = "Cocaína e VR - que mistura interessante.",--Cocaine and VR - what an interesting mix.
	vld_moon_25_03 = "Eu também teria escondido isso no cofre. Mas eu sou um homem cínico.",--I would have hid it in the safe too. But I'm a cynical man.
	vld_moon_29_01 = "Nosso amigo Bile em breve estará aqui para o pós festa. Tenham certeza de recebê-lo.",--Our friend Bile will soon be around for the afterparty. Make sure you welcome him.
	vld_moon_24_01 = "Onde eles esconderam aquele set VR? Numa realidade alternativa?",--Where did they hide that fucking VR set? In an alternate reality?
	vld_moon_02_02 = "Se eu perder essa cocaína, isso vai foder o meu orçamento de Natal. Achem ela para mim!",--If I lose this coke it's gonna fuck up my Christmas budget. Find it for me!
	vld_moon_38_04 = "Esperdo que esses malditos policiais vão para casa e reconsiderem suas ações. Eles não trataram o Noel muito bem, então esse ano ficarão sem presentes.",--I hope these fucking cops go home and reconsider their actions. They didn't treat Santa very well, so there will be no presents this year.
	vld_moon_18_02 = "Sinto saudades dos velhos sapatos Soviéticos. Não haviam muitos modelos estúpidos para escolher!",--I miss the old Soviet shoes. Not so many stupid models to choose from!
	vld_moon_05_02 = "Diamantes são para sempre, mas uma boa coca desaparesse rápido. Vão pegá-la!",--Diamonds are forever, but good coke disappears fast. Go get it!
	vld_moon_30_03 = "Eu quero uma bela árvore de Natal com presentes nela!",--I want a beautiful Christmas tree with presents in it!
	vld_moon_14_03 = "Vendido? Porra, alguém acabou de fazer um belo negócio em um kilo de cocaína.",--Sold out? Fuck, someone just got a great deal on a pound of coke.
	vld_moon_09_02 = "Teclados, mágica eletrônica. Ah, vocês podem fazê-la! ",--Keypads, electronic magic. Ah you can do it!
	vld_moon_27_01 = "Eu amo um bom vinho com meu borscht! Gostoso!",--I love a good wine with my borscht! Tasty!
	vld_moon_39_02 = "Deixem a árvore em paz! Eu gosto dela!",--Leave the tree alone! I like it!
	vld_moon_38_09 = "Eles sempre dizem para tratar os outros comos eles tratam você. E várias vezes eu fui tratado muito mal.",--They say always treat others like they treat you. And I've been treated very badly, many times.
	vld_moon_26_01 = "Eu amo abrir presentes de Natal!",--I love opening Christmas presents!
	vld_moon_33_01 = "Certo, precisamos levar esse bebezinho.",--Ok, we need to lift this little baby out.
	vld_moon_38_06 = "Eles dizem que você deve trabalhar com a família pois pode confiar neles. Mas esse cara, eu só posso confiar nele para ser um idiota e foder com tudo.",--They say you should work with family because you can trust them. But this guy, I can only trust him to be an idiot and to fuck up.
	vld_moon_01_01 = "Meus amigos, vocês irão salvar meu Natal.",--My friends, you will save my Christmas.
	vld_moon_01_03 = "Vão achar Noel, meus pequenos ajudantes. E nós ainda poderemos ter um Natal branco.",--Go find Santa, my little helpers. We can still have a white Christmas.
	vld_moon_02_01 = "Um Noel bêbado - é uma aberração! E minha cocaína!",--A drunk Santa - it's a fucking abomination! And my coke!
	vld_moon_02_03 = "Como pode os policiais prenderem o Papai Noel? Isso não está certo!",--How can the cops arrest Santa Claus? It's not right!
	vld_moon_03_03 = "Só pode ter um Noel com cara de chapado guardado por policiais nesse shopping. Acredito eu.",--There can only be one shitfaced Santa guarded by cops in this mall. I hope.
	vld_moon_04_01 = "Ele está dormindo? Acordem ele!",--He's fucking asleep? Wake him up!
	vld_moon_04_04 = "Batam nesse idiota por mim!",--Smack that idiot from me!
	vld_moon_04_06 = "Não se segurem! Dêem uma boa porrada nele!",--Don't hold back! Give him a good smack!
	vld_moon_09_01 = "Vamos lá, me mostrem que podem ser hackers!",--Come on, show me you can be hackers!
	vld_moon_09_03 = "A vitrine está trancada! Veem o quão forte esses idiotas guardam seus tesouros! Como os dragões nas histórias!",--The display is locked! See how tighly these assholes guard their treasures! Like dragon in stories!
	vld_moon_10_01 = "Perfeito! Agora peguem a caixa de jóias!",--Perfect! Now get the Jewelry box!
	vld_moon_13_03 = "Peguem aquela cocaína antes que uma criança roube ela e eu perca dinheiro!",--Get that cocaine before some little kid steals it and I lose money!
	vld_moon_14_02 = "Que? Não! Eles venderam todos o Garotos de Lata!",--What? No! They sold all the Tin Boys!
	vld_moon_16_01 = "Que se fodam os outros brinquedos - peguem o Garoto de Lata!",--Fuck the other toys - get Tin Boy!
	vld_moon_16_02 = "Peguem aquele Garoto de Lata com a minha cocaina!",--Get that Tin Boy with my cocaine!
	vld_moon_17_01 = "10? Esse é meu tamanho! E não quero dizer de sapatos...",--10? That's my size! And I don't mean shoes...
	vld_moon_17_02 = "Peguem aqueles malditos sapatos!",--Get those fucking shoes!
	vld_moon_18_03 = "Vamos lá, computem com o computador!",--Come on, compute with the computer!
	vld_moon_19_03 = "Furem a porta e peguem a minha caixa de sapatos de cocaína!",--Drill the door open and get my cocaine shoe box!
	vld_moon_20_01 = "Peguem aqueles malditos sapatos!",--Get those fucking shoes!
	vld_moon_21_01 = "Tem caixas demais aqui!",--There are too many fucking boxes here!
	vld_moon_21_02 = "Onde. Estão. Os. Sapatos? Onde?!",--Where. Are. The. Shoes? Where?!
	vld_moon_22_02 = "O que há nessas caixas?",--What's in these boxes?
	vld_moon_23_02 = "VR. Realidade... muito.... aumentada. Que besteira.",--VR. Very... enhanced... reality. What bullshit.
	vld_moon_24_02 = "O set VR virtualmente não está aqui. Ou deveria ser realmente? Não sei - qual é o certo?",--The VR set is virtually not here. Or should that be actually? I don't know - which is it?
	vld_moon_25_02 = "Eu tenho certeza que esse cofrinho não será problema para vocês.",--I'm sure a tiny little safe is not a problem for you.
	vld_moon_26_03 = "Meus amigos, peguem as coisas!",--Get the stuff, my friends!
	vld_moon_27_02 = "Peguem o vinho! Mas não começem a beber - já basta um Noel bêbado!",--Get the wine! But don't start drinking  - it's enough with one drunk Santa!
	vld_moon_27_03 = "Vinho e cocaína! Vocês poderiam vender isso como um pacote de festa!",--Wine and cocaine! We could just sell it as a party pack!
	vld_moon_28_01 = "Peguem aquele Red Red Resurrection ou qualquer que seja o nome dele!",--Get that Red Red Resurrection or whatever it was called!
	vld_moon_28_03 = "Vinho, mulheres e canções! E cocaína! Feliz Natal!",--Wine, women and song! And cocaine! Merry Christmas!
	vld_moon_29_02 = "Esperem pelo helicóptero. Nós levaremos essas coisas pelos céus.",--Watch for the helicopter. We're taking this stuff to the sky.
	vld_moon_30_01 = "Agora decorem a árvore com essas belezinhas!",--Now decorate the tree with these fine things!
	vld_moon_31_01 = "Meus amigos escutem... Estava pensando... aquela é uma árvore de Natal muito boa. Eu acho que irei levá-la. Irei enviar o helicóptero para pegá-la.",--Listen my friends... I've been thinking... that's a very nice Christmas tree. I think I'll take it. I will send the helicopter to pick it up.
	vld_moon_31_02 = "Eu quero a árvore. Ela deverá voar pelos céus como um grande foguete Natalino! Hahaha!",--I want the tree. It shall fly into the sky like a big Christmas rocket! Hahaha!
	vld_moon_31_03 = "Essa árvore é muito boa. Devemos roubá-la.",--That tree is very nice. We will steal it.
	vld_moon_32_01 = "Senhoras e senhores, vocês poderiam por favor plantar uns explosivos.",--Ladies and gentlemen, can you place some explosives please?
	vld_moon_32_02 = "Escutem... Eu preciso que vocês me façam uma grande explosão.,",--Listen...I need you to make me a big bang.
	vld_moon_32_03 = "Acho que seria bom explodir o teto desse shopping!",--I think it would be nice to blow the roof off this mall!
	vld_moon_33_02 = "Meus amigos, essa árvore vai voar!",--This tree is going to fly, my friends!
	vld_moon_33_03 = "É uma boa árvore, e nós iremos levá-la. Não a danifiquem!",--It's a nice tree, and we will take it. Don't damage it!
	vld_moon_34_01 = "A árvore está partindo. O Noel também!",--This tree is leaving. So is Santa!
	vld_moon_35_01 = "É melhor ele segurar firme. Seria uma pena se ele caísse dos céus e morresse.",--He'd better hold on tight. It'd be a shame if he fell out of the sky and died.
	vld_moon_36_01 = "Bile voltará em breve. Meus amigos segurem o ponto.",--Bile will be back soon. Hold on my friends!
	vld_moon_36_03 = "Apenas esperem aí, a sua carona chegará em breve. Eu prometo!",--Just wait there, you'll be picked up soon. I promise!
	vld_moon_37_01 = "Meus amigos aí vamos nós!",--And off we go my friends!
	vld_moon_38_02 = "Um dos meus melhores Natais foi quando eu matei um dedo duro sujo na manhã de Natal. Amarrei ele numa árvore de Natal na frente de sua família e taquei fogo. Foi lindo.",--One of my best Christmases was that one time when I killed a dirty snitch on Christmas morning. Tied him to a Christmas tree in front of his family and set him on fire. It was beautiful.
	vld_moon_38_03 = "Eu amo fazer compras. Só não gosto de pagá-las. Vlad não paga, ele leva o que ele quiser.",--I love shopping. I just don't like to pay. Vlad doesn't pay, he takes what he wants.
	vld_moon_38_05 = "Eu sempre faço bons negócios por volta do Natal. As pessoas gastam muito dinheiro. É o estresse, elas precisam das minhas coisas.",--I always do good business around Christmas. People spend a lot of money. It's the stress, they need my stuff.
	vld_moon_38_07 = "Minha esposa disse que talvez faria compras aí amanhã. Eu devia avisá-la que aí provavelmente estará fechado. (risadas)",--My wife said she might go shopping here tomorrow. I should warn her that it'll probably be closed. (laughs)
	vld_moon_38_08 = "Tem algo que acho muito prazeroso sobre o som de janelas de lojas quebrando. Mas não sei porquê.",--There is something about the sound of shattering shop windows that I find very pleasing. I don't know why.
	vld_moon_38_10 = "Aposto que esses policiais não acrediam em Papai Noel. Mas eu acredito! E ele é um pé no saco.",--I bet these cops don't believe in Santa Claus. But I do! And he's a fucking pain in the ass!
	vld_moon_39_01 = "Ei! Não destruam a árvore!",--Hey! Don't destroy the tree!
	vld_moon_39_03 = "Essa é uma linda árvore! Parem com isso, seus bárbaros!",--That's a beautiful tree! Stop it, you barbarians!
	vld_moon_39_04 = "Vocês podem destruir qualquer coisa que quiserem, e matar quem vocês quiserem, mas deixem a árvore em paz!",--You can destroy anything you want, and kill anyone you want, but leave the tree alone!
	vld_moon_39_05 = "Não atirem na árvore! Vocês irão arruinar o Natal!",--Don't shoot the tree! You'll ruin Christmas!
	vld_moon_39_07 = "A árvore não! Parem de atirar nela!",--Not the tree! Stop shooting at it!
	vld_moon_39_08 = "Não atirem na árvore! É uma espécie em extinção!",--Don't shoot the tree! It's an endangered species!
	vld_moon_39_09 = "Não atirem na árvore de Natal!",--Don't shoot the Christmas tree!
	vld_moon_39_10 = "Mas o que diabos a árvore fez para vocês? Huh?",--What the fuck did that tree do to you? Huh?
	pln_moon_11_03 = "Verifiquem o estoque da loja de sapatos no computador.",--Check the shoe store's stock in the computer.
	pln_moon_15_01 = "Pessoal, é melhor vocês olharem dentro das caixas! ",--You better look in the boxes, guys!
	pln_moon_35_01 = "Esperem o helicóptero.",--Wait for the helicopter.
	pln_moon_01_01 = "Vocês precisam libertar o cunhado do Vlad primeiro!",--You've got to free Vlad's brother-in-law first!
	pln_moon_14_03 = "Os sapatos estão na gaiola de armazenamento. Abram ela! ",--The shoes should be in the storage cage. Open it!
	pln_moon_23_02 = "Joguem o saque na árvore!",--Throw the loot into the tree!
	pln_moon_17_01 = "Abram a porta para o escritório dos fundos!",--Open the door to the back office!
	pln_moon_33_03 = "Tenham certeza de que o Noel está na árvore antes dela ser levada!",--Make sure Santa is in the tree before it's airlifted out!
	pln_moon_08_01 = "Vocês tem que roubar o Garoto de Lata!",--You have to steal Tin Boy!
	pln_moon_21_03 = "Onde está aquele vinho? Achem-no!",--Where is that wine? Find it!
	pln_moon_11_02 = "Verifiquem o computador. Temos que achar os sapatos!",--Check the computer. Got to find the shoes!
	pln_moon_18_03 = "O negócio deve estar no cofre. Abram ele!",--The stuff must be in the safe. Open it!
	pln_moon_14_02 = "Abram a gaiola de armazenamento para pegar os sapatos!",--Open the storage cage to get the shoes!
	pln_moon_20_01 = "Certo, vocês sabem qual vinho estamos procurando! Achem-no!",--Ok, you know which wine we're looking for! Find it!
	pln_moon_22_02 = "O helicóptero chegará aqui em um minuto.",--Helicopter will be here in one minute.
	pln_moon_28_02 = "Gente, plantem esse C4.",--Get that C4 placed guys.
	pln_moon_23_03 = "A árvore de Natal - é onde o saque irá!",--The Christmas tree - that's where the loot goes!
	pln_moon_02_02 = "Sei que dizem que da azar bater no Noel, mas vocês precisam acordá-lo!",--I know they say it's bad luck to hit Santa, but you've got to wake him up!
	pln_moon_36_03 = "Saiam daí agora!",--Now get out of there!
	pln_moon_07_03 = "Alguém comprou o brinquedo e saiu com o negócio do Vlad. Vocês precisam recuperá-lo!",--Someone just bought the toy and walked off with Vlad's stuff. You need to get it back!
	pln_moon_21_02 = "Achem o vinho agora!",--Find the right wine now!
	pln_moon_04_03 = "Vocês precisam hackear o console! Nós precisamos entrar na vitrine!",--You've got to hack the console! We need to get inside the display cabinet!
	pln_moon_18_01 = "Certo, agora vocês terão que abrir aquele cofre!",--Ok, you'll have to open that safe now!
	pln_moon_35_02 = "Espere o Bile voltar e pegá-los junto do saque.",--Wait for Bile to come back and pick you up along with the loot.
	pln_moon_31_01 = "Conectem o quadro a árvore!",--Attach the frame to the tree!
	pln_moon_36_01 = "Certo, é hora de ir!",--Ok, it's time to go!
	pln_moon_32_02 = "Última chance de guardar mais saque na árvore!",--Last chance to secure any loot in the tree!
	pln_moon_34_01 = "Esperem o Noel subir na árvore!",--Wait for Santa to get into the tree!
	pln_moon_33_01 = "Vocês precisar levar o Noel para a árvore para que ele possa voar com ela!",--You need to get Santa up the tree so he can fly out with it!
	pln_moon_19_02 = "Esvaziem o cofre!",--Empty the safe!
	pln_moon_06_02 = "Certo, é a loja de brinquedos - Garoto de Lata!",--Ok it's the toy store - Tin Boy!
	pln_moon_06_01 = "Vocês precisam entrar na loja de brinquedos e achar a caixa do Garoto de Lata com a cocaína.",--You need to get to the toy store and find the Tin Boy toy box with the coke.
	pln_moon_29_01 = "Saiam daí! O C4 vai explodir!",--Get away from there! The C4's gonna blow!
	pln_moon_12_01 = "Furem a porta para o depósito.",--Drill the door to the storage room.
	pln_moon_36_02 = "Rapazes hora de partir!",--Time to go guys!
	pln_moon_25_02 = "Para tirar aquela árvore daí, vocês precisarão explodir o teto de vidro do shopping. Apenas acendam um sinalizador e esperem pelo Bile, ele trará alguns C4.",--To get that tree out, you need to blow the glass roof off the mall. Just light a flare and then wait for Bile, he'll be bringing in some C4.
	pln_moon_03_02 = "Está na joalheria.",--It's in the Jewelry store.
	pln_moon_29_03 = "Agora o C4 vai explodir! Saiam do caminho!",--C4's gonna explode now! Get out of the way!
	pln_moon_04_02 = "Hackeiem o console para abrir a vitrine.",--Hack the console to open the display cabinet.
	pln_moon_27_03 = "O helicóptero agora está vindo para árvore!",--The helicopter is coming for the tree now!
	pln_moon_28_03 = "Plantem o C4 em volta do domo.",--Plant that C4 around the glass dome.
	pln_moon_32_01 = "Se vocês conseguirem mais saque, guardem ele na árvore agora! Ou isso será deixado para trás!",--If you got any more loot, secure it in the tree now! Or it'll be left behind!
	pln_moon_05_03 = "Vocês precisam pegar aquela caixa de jóias!",--You need to get that Jewelry box!
	pln_moon_16_02 = "Headset VR. Achem-no, é la que estará a cocaína! Verifiquem a loja de eletrônicos!",--VR headset. Find it, that's where the coke is! Check the electronics store!
	pln_moon_08_03 = "Vocês precisam roubar aquele brinquedo!",--You've got to steal that toy!
	pln_moon_31_03 = "Conectem o quadro!",--Attach the frame!
	pln_moon_15_02 = "Vocês olharam as caixas?",--Did you check the boxes?
	pln_moon_09_03 = "Procurem ao redor pelo brinquedo Garoto de Lata!",--Search around for the Tin Boy toy!
	pln_moon_22_03 = "Falta um minuto para o helicóptero.",--Just a minute for the helicopter.
	pln_moon_02_01 = "Vocês precisam acordar o Noel. Batam nele!",--You need to wake Santa up. Hit him!
	pln_moon_07_01 = "Alguém comprou o último Garoto de Lata. Procurem em todas as sacolas da loja de brinquedos que acharem no shopping!",--Someone bought the last Tin Boy. Go search all toy store bags you can find in the mall!
	pln_moon_07_02 = "Encontrem quem comprou o Garoto de Lata! Deve ter uma sacola da loja de brinquedos.",--Go find who bought the Tin Boy! There should be a bag from the toy store.
	pln_moon_19_01 = "Peguem a coisa no cofre!",--Get the stuff from the safe!
	pln_moon_28_01 = "Plantem o C4 e explodam o telhado.",--Plant the C4 and blow the roof off.
	pln_moon_27_01 = "Vlad é realmente outra coisa! Ele quer roubar essa árvore de Natal gigante! Bile agora está vindo com um helicóptero, então estejam prontos!",--Vlad is really something else! He wants to steal that huge Christmas tree! Bile is coming in with the chopper now, so be ready!
	pln_moon_10_03 = "Vocês tem que achar esses sapatos!",--You got to find those shoes!
	pln_moon_17_02 = "Abram aquela porta do escritório dos fundos!",--Get that back office door open!
	pln_moon_01_02 = "Vamos libertar o Papai Noel!",--Let's free Santa Claus!
	pln_moon_01_03 = "Certo, achem o Noel e soltem ele!",--Ok, find Santa and free him!
	pln_moon_02_04 = "Desçam a lenha no Noel para que ele acorde!",--Whack Santa so he wakes up!
	pln_moon_02_05 = "Deem uma bela surra no Noel! Acordem ele!",--Give Santa a good thrashing! Wake him up!
	pln_moon_02_06 = "Eu acho que você terá que bater nele para acordá-lo.",--I think you'll have to hit him to wake him up.
	pln_moon_03_01 = "Certo, vocês tem que ir na Joalheria.",--Ok, you have to go to the Jewelry store.
	pln_moon_03_03 = "Um dos pacotes está na Joalheria. Vão!",--One of the packages is in the Jewelry store. Go!
	pln_moon_04_01 = "Certo gangue, vocês precisarão hackear o console.",--Ok gang, you need to hack the console.
	pln_moon_05_01 = "Peguem aquela caixa!",--Get that box!
	pln_moon_05_02 = "Peguem aquelas caixas de jóias!",--Get the Jewelry box!
	pln_moon_06_03 = "Certo, agora procurem por brinquedos Garoto de Lata na loja de binquedos.",--Ok, search for Tin Boy toys in the toy store.
	pln_moon_08_02 = "Certo, roubem o Garoto de Lata!",--Ok, steal the Tin Boy!
	pln_moon_09_01 = "A caixa do Garoto de Lata deve estar numa dessas pilhas de brinquedos!",--The Tin Boy box has got to be in one of those toy piles!
	pln_moon_09_02 = "Procurem nas pilhas e achem o Garoto de Lata!",--Search in the piles and find Tin Boy!
	pln_moon_10_01 = "Certo, peguem os sapatos!",--Ok get the shoes!
	pln_moon_10_02 = "Pessoal peguem aquela caixa de sapatos!",--Get that shoe box people!
	pln_moon_11_01 = "Verifiquem o inventário da loja e achem aqueles sapatos!",--Check the store inventory and find those shoes!
	pln_moon_12_02 = "Abram a porta do depósito.",--Get that storage room door open.
	pln_moon_12_03 = "Nós precisamos entrar no depósito.",--We need to get into the storage room.
	pln_moon_13_01 = "Gente, peguem aquela caixa de sapatos!",--Get that shoe box, guys!
	pln_moon_13_02 = "Peguem aqueles sapatos!",--Get those shoes!
	pln_moon_13_03 = "Vamos lá, nós temos que pegar os sapatos com a cocaína!",--Come on, we have to get the shoes with the cocaine!
	pln_moon_14_01 = "Vocês precisam abrir a gaiola de armazenamento!",--You've got to open the storage cage!
	pln_moon_15_03 = "Gangue, procurem nas caixas!",--Look in the boxes, gang!
	pln_moon_16_01 = "Vão para a loja de eletrônicos e achem o headset VR. A cocaína deve estar lá.",--Go to the tech store and find the VR headset. There coke should be there.
	pln_moon_16_03 = "Ele escondeu a cocaína com um headset VR. Achem-no, ele deve estar na loja de eletrônicos.",--He hid the coke with a VR headset. Find it, it should be in the electronics store.
	pln_moon_17_03 = "Escritório dos fundos! Abram a porta!",--Back office! Open the door!
	pln_moon_18_02 = "Abram o cofre e verifiquem dentro!",--Open the safe and check inside!
	pln_moon_19_03 = "Certo, peguem a mercadoria!",--Ok, get the goods!
	pln_moon_20_02 = "Ele disse Vermelho Vale Vermelho? Vão achá-lo na loja de vinhos!",--Did he say Red Valley Red? Go find it in the wine store!
	pln_moon_20_03 = "Vocês tem que achar aquele vinho na loja de vinhos!",--You have to find that wine in the wine store!
	pln_moon_21_01 = "Tenham certeza de acharem o vinho certo!",--Make sure you find the right wine!
	pln_moon_22_01 = "Vai demorar apenas um minuto.",--It'll just be one one minute.
	pln_moon_23_01 = "Coloquem o saque na árvore de Natal!",--Put the loot in the Christmas tree!
	pln_moon_24_01 = "Beleza, vocês conseguiram, agora coloquem isso na árvore.",--Alright you got it, now put it in the tree.
	pln_moon_24_02 = "Vocês pegaram o pacote, agora coloquem ele na árvore.",--You got the package, now stash it in the tree.
	pln_moon_24_03 = "Belo trabalho! Agora escondam o pacote na árvore de Natal.",--Nice job! Now hide the package in the christmas tree.
	pln_moon_25_01 = "Não há jeito fácil de tirar a árvore. Vocês terão que tirar o teto de vidro do shopping. Sinalizem Bile com um sinalizador e ele irá deixar um presentinho para vocês. Sim, C4.",--There's no easy way out for the tree. We'll have to take the glass roof off the mall. Signal Bile with a flare and he'll drop a little present for you. Yeah, C4.
	pln_moon_25_03 = "Esta árvore irá voar pelos céus. Acendam um sinalizador no telhado, e Bile irá trazer alguns C4 para que vocês possam explodir o telhado.",--This tree will fly in the sky. Light a flare on the roof, and Bile will bring in some C4 for you so you can blow the roof open.
	pln_moon_26_01 = "Ótimo. Agora segurem o ponto e esperem o Bile.",--That's great. Now just hold on and wait for Bile.
	pln_moon_26_02 = "Beleza, agora só esperar o Bile chegar. Espero que ele não demore.",--Alright, now you just gotta wait for Bile to arrive. I hope he won't be long.
	pln_moon_26_03 = "Certo, o sinalizador está acesso. Ótimo trabalho gente, agora esperem pelo Bile.",--Ok, the flare is lit. Great job guys, now just wait for Bile.
	pln_moon_27_02 = "Vlad quer a árvore de Natal. Bile agora está a caminho!",--Vlad wants the Christmas tree. Bile is on his way now!
	pln_moon_29_02 = "Se cubram gente! Vai explodir!",--Take cover guys! It's gonna blow!
	pln_moon_30_01 = "Conectem o cabo a árvore!",--Attach the wire to the tree!
	pln_moon_30_02 = "Conectem os cabos a árvore de Natal!",--Get that wire attached to the Christmas tree!
	pln_moon_30_03 = "Conectem o cabo!",--Attach the wire!
	pln_moon_31_02 = "Conectem aquele quadro a árvore de Natal!",--Get that frame attached to the Christmas tree!
	pln_moon_32_03 = "Mais algum saque? Vocês precisam guardá-lo na árvore agora, antes que o Bile voe daí!",--Any more loot? You gotta secure it in the tree now, before Bile flies it out of here!
	pln_moon_33_02 = "Vocês precisam salvar o Noel fazendo ele subir na árvore antes dela ser levada!",--You've got to save Santa by getting him into the tree before it's flown out!
	pln_moon_34_02 = "Apenas segurem o ponto até o Noel subir na árvore!",--Just hold on until Santa gets into the tree!
	pln_moon_34_03 = "Esperem até que ele esteja na árvore!",--Hold on until he's in the tree!
	pln_moon_35_03 = "Vocês precisam esperar a carona aqui.",--You've got to wait here for the pickup.
	pln_moon_36_04 = "Hora de fugir!",--Time to escape!
	
	-- Objetivos
	hud_heist_moon_03_hl = "Entrem na joalheria",--Enter the jewelry store
	hud_heist_moon_30_hl = "Achem e roubem o garoto de lata",--Find and steal Tin Boy
	hud_heist_moon_30 = "O Garoto de Lata está numa das caixas de presentes vermelhas localizadas dentro da loja de brinquedos. Vão achá-lo!",--The Tin Boy toy is in one of the red gift boxes located inside the toy store. Go find it!
	hud_heist_moon_22 = "Peguem o headset VR para o Vlad!",--Grab the VR headset for Vlad!
	hud_heist_moon_31_hl = "Batam no Noel",--Hit Santa
	hud_heist_moon_16_hl = "Conectem os cabos a árvore de Natal",--Attach the wires to the Christmas tree
	hud_heist_moon_28_hl = "Esperem Bile voltar",--Wait for Bile to return
	hud_heist_moon_08 = "Acendam um sinalizador para sinalizar o Bile para jogar uns C4 no telhado usando seu helicóptero.",--Light a flare on the roof to signal Bile to drop some C4 on the roof using his helicopter.
	hud_heist_moon_10_hl = "Procurem na base de dados da loja",--Search through the store database
	hud_heist_moon_17 = "Reúnam-se em volta da árvore de natal e fujam!",--Gather around the Christmas tree and escape!
	hud_heist_moon_27 = "O vinho que procuramos está numa das caixas de presentes vermelhas na loja. Abram elas e achem o vinho!",--The wine we're after is in one of the red gift boxes in the store. Open them and find the wine!
	hud_heist_moon_22_hl = "Roubem o headset VR",--Steal the VR headset
	hud_heist_moon_26_hl = "Entrem na loja de vinhos",--Enter the wine store
	hud_heist_moon_07 = "Procurem em todo o shopping pela sacola contendo o brinquedo de lata. Elas devem estar espalhadas em volta das lojas.",--Search through the mall for a shopping bag containing the tin toy. They should be scattered around the stores.
	hud_heist_moon_09 = "Achem e entrem na loja de sapatos no primeiro andar.",--Find and enter the shoe store on the first floor.
	hud_heist_moon_12_hl = "Roubem os sapatos",--Steal the shoes
	hud_heist_moon_04 = "Usem o computador para hackear o teclado para desabilitar o vidro blindado da vitrine.",--Use the computer to hack the keypad to disable the bulletproof glass display case.
	hud_heist_moon_09_hl = "Entrem na loja de sapatos",--Enter the shoe store
	hud_heist_moon_08_hl = "Sinalizem o piloto do helicóptero com um sinalizador",--Signal the helicopter pilot with a flare
	hud_heist_moon_14_hl = "Guardem os pacotes do Vlad embaixo da árvore",--Secure Vlad's packages under the tree
	hud_heist_moon_21_hl = "Abram o cofre",--Open the safe
	hud_heist_moon_15_hl = "Peguem o C4 e plantem ele em volta da cúpula",--Pick the C4 up and plant it around the dome
	hud_heist_moon_06 = "Localizem e entrem na loja de brinquedos no térreo.",--Locate and enter the toy store on the ground floor.
	hud_heist_moon_07_hl = "Localizem a sacola de compras com o brinquedo",--Locate the shopping bag with the toy
	hud_heist_moon_19_hl = "Entrem na loja de eletrônicos",--Enter the tech store
	hud_heist_moon_11_hl = "Entrem no escritório dos fundos",--Enter the back office
	hud_heist_moon_14 = "Joguem os pacotes embaixo da árvore para guardá-los!",--Throw the packages underneath the tree to secure them!
	hud_heist_moon_05 = "Peguem o colar de trás do vidro blindado e guardem ele para o Vlad!",--Take the necklace from behind the bullet proof glass and secure it for Vlad!
	hud_heist_moon_12 = "Peguem os sapatos e levem eles para a árvore de Natal!",--Grab the shoes and bring them back to the Christmas tree!
	hud_heist_moon_27_hl = "Achem e roubem a caixa de vinho",--Find and steal the wine box
	hud_heist_moon_04_hl = "Hackeiem o teclado",--Hack the keypad
	hud_heist_moon_19 = "Achem entrem na loja de eletrônicos no térreo.",--Find and enter the tech store on the ground floor.
	hud_heist_moon_10 = "Verifiquem o computador para ver se a loja tem os sapatos no estoque.",--Check the computer to see if the shop has the shoes in stock.
	hud_heist_moon_13_hl = "Esperem o C4 cair no telhado",--Wait for the C4 drop on the roof
	hud_heist_moon_16 = "Conectem os cabos a árvore para que o helicóptero possa levantá-la daí!",--Connect the wires to the tree so the helicopter can airlift it out!
	hud_heist_moon_26 = "Achem e entrem na loja de vinhos no primeiro andar.",--Find and enter the wine store on the first floor.
	hud_heist_moon_01_hl = "Libertem o Noel",--Free Santa
	hud_heist_moon_18_hl = "Vão para a área de depósito",--Go to the storage area
	hud_heist_moon_28 = "Segurem o ponto e esperem o Bile pegar a árvore.",--Hold out and wait for Bile to pick up the tree.
	hud_heist_moon_05_hl = "Roubem o colar",--Steal the necklace
	hud_heist_moon_11 = "Atravessem a porta e entrem no escritório dos fundos!",--Get through the door and into the back office!
	hud_heist_moon_06_hl = "Entrem na loja de brinquedos",--Enter the toy store
	hud_heist_moon_13 = "Esperem o helicóptero jogar o C4 no telhado!",--Wait for the helicopter to drop off the C4 on the roof!
	hud_heist_moon_01 = "Achem e libertem o Noel - o cunhado bêbado do Vlad. Ele deve estar em algum lugar dentro do Shopping.",--Find and free Santa - Vlads drunken brother in law. He should be inside the mall somewhere.
	hud_heist_moon_03 = "Localizem e entrem na joalheria no primeiro andar.",--Locate and enter the jewelry store on the first floor.
	hud_heist_moon_15 = "Plantem o C4 em volta da cúpula de vidro para que vocês possam explodí-la!",--Plant all the C4 around the glass dome so you can blow it away!
	hud_heist_moon_17_hl = "Fuga está disponível",--Escape available
	hud_heist_moon_18 = "Acessem a área de depósito atrás da loja de sapatos!",--Access the storage area behind the shoe store!
	hud_heist_moon_21 = "Abram o cofre no balcão para acessar o headset VR.",--Open the safe by the counter to access the VR headset.
	hud_heist_moon_31 = "Batam no Noel para acordá-lo!",--Hit Santa to wake him up!
		})
end)