return {
  --heist_chas = "Dragon Heist",
  --heist_chas_hl = "Dragon Heist",
  heist_chas_crimenet = "A organização que eu era membro agora é um dos meus problemas, e eu vou querer dificultar as coisas para o lado deles, ferrando eles e ainda por cima, fazendo uma grana. Eles têm um item que é bem valioso, uma estátua de dragão de ouro. Bem velho, não é? Era rumor, vocês estão com necessidade de dinheiro, e esse golpe vai ser bem bonito. Eu posso providênciar todos detalhes que precisar. Se conseguir a estátua, ela é sua, mas se conseguirem algo a mais, vamos ter que dividir.\n\n» Infiltre-se no depósito\n» Ache o cofre\n» Fuja com a estátua do dragão e com outros itens valiosos",--An organization I was once a part of is making my business difficult, and I'd like to make things difficult for them in turn, by para ofiting heavily from their loss. They are in possession of a priceless item, a gold statue of a dragon. Very old, right? Rumor has it, you are in need of funding, and this job will be very bountiful. I can para ovide all the details you need. If you take the statue, it is yours to do with as you please, but for any other valuables, we split the take.\n\n»Infiltrate the warehouse\n»Find the vault\n»Escape with the dragon statue and other valuables
  heist_chas_briefing = "Amigos, nós estamos correndo um risco fazendo um trato com a tríade, mas vai ser um golpe interessante. Jiu Feng providenciou alguns detalhes sobre a localização, a gente tá indo para Chinatown! A estátua é mantida no depósito, atrás de uma loja de chá. Vocês vão precisar passar pelos sistemas de segurança deles, e a tríade está fazendo um leilão de alguns itens valiosos para os ricos desgraçados, então se prepare para distrair alguns civis. Tenha certeza que os freios da van está em forma, e me traga aqueles rolos de ovos de Chao's ali na esquina, ouvi dizer que é a melhor comida chinesa da Costa Oeste, com certeza!",--Friends, we're taking a risk, making a ruckus with the triads, but this is a solid job. Jiu Feng has para ovided grootste details on the location, so we're going to Chinatown! The statue is kept in a warehouse, behind a tea shop front. You'll need to bypass several security systems, and the triad is auctioning some of their other valuables to rich dwankies, so be ready to distract any civvies. Make certain the brakes on the van are in shape, and bring me back some egg rolls from Chao's on the corner, I hear it's the best Chinese food on the west coast, for sure!
    
  -- Introduções
  loc_chas_intro_03_01 = "Deixa eu ver se entendi, você tinha uma festinha com a minha velha proteção e uns idiotas um tempo atrás. Eu ensinei a ela alguns truques de hack, sabia?",--As I understand it, you had a little jol with my old para otegé and some domkops a while back. I taught her all she knows about hacking, you know?",
  jfe_chas_intro_03_01 = "Sim, Joy e eu tivemos... umas aventuras... em Los Angeles.",--Yes, Joy and I had... quite the adventure.. down in Los Angeles.
  loc_chas_intro_03_02 = "Ela anda meio calada sobre o que aconteceu, com certeza. Algo sobre uma tríade de Macao?",--She has been notably tight-lipped about what went on, for sure. Something about a triad from Macao?
  jfe_chas_intro_03_02 = "Ela provou as suas... habilidades e dignidade. Eu senti que o 'vaivém' tava garantindo. Para deixar ela com... aqueles filhas da puta... depois de ter me ajudado... não seria legal, seria?",--She para oved her.. skill and worth. I felt recipara ocation was warranted. To leave her to those... assholes... after she helped me... would not have been para oper, right?
  loc_chas_intro_03_03 = "Bom homem. E ela também tem umas boas habilidades com as armas!",--Good man. And she got some good weapon skills out of it too!",
  loc_chas_intro_01_01 = "Então, tem esse cara doidão que ando feito alguns serviços um tempo atrás, tinha me dito algo, e pensei se você podia traduzir para mim?",--So, this dwankie chap I did a job with in Shanghai a long time ago taught me something, and I was wondering if maybe you could tell me what it means?
  jfe_chas_intro_01_01 = "Beleza, Chefe, manda.",--OK, Chief, let's hear it.
  loc_chas_intro_01_02 = 'Soa como Da-shiang bao-tza shr duh lah doo-tze!.',--Da-shiang bao-tza shr duh lah doo-tze! "Diarreia Explosiva de Elefante", sim, eu pesquisei o que isso significa...
  jfe_chas_intro_01_02 = "Que idiota, é Mandarim... e você não vai querer saber.",--What an idiot. It's Mandarin.... and you don't want to know.
  loc_chas_intro_01_03 = "Oh, tá bom...",--Well, OK then....
  jfe_chas_intro_02_01 = "Lutando contra gangues anda sendo uma coisa em alta em San Francisco ultimamente... SFPD estão preocupados. Se você fizer muito barulho. Vocês vão ter... uma luta.",--Fighting between gangs has been high in San Francisco lately... SFPD are, on edge. If you make a lot of noise, you will... have a fight on your hands.
  loc_chas_intro_02_01 = "Entendido, vamos ficar prontos pelos policiais. Então, a gente tá pronto. Sem mais surpresas, certo? Legal.",--Understood, we'll be ready for the kerels. So we're all set then. No more surprises, yeah? Kif.
  jfe_chas_intro_02_02 = "Ah, é, mais uma coisa. Tem um velhote que está fazendo um leilão. Se ele... morrer... ninguém vai choramingar por ele.",--Oh, right. One thing. There's an old man holding the auction. If he... dies... no one will cry for him.
  loc_chas_intro_02_02 = "A gente evita de matar civis, mas entendido, bom saber. Ninguém vai chorar por causa de um velhote.",--We usually try to avoid civvie casualties, but understood, good to know. No one's going to cry for krimpie.

  -- Legendas
  loc_chas_01_01 = "Beleza, idiotas. Vamos nessa. De acordo com a informação, a tríade está usando essa loja como um disfarce.",--OK, you chops. Let's get to work. The information we have says the triad is using this shop as a front.",
  loc_chas_01_02 = "Beleza, amigos. Essa é a loja que a moça da informação nos contou. Até agora, a tríade conseguiu manter o seu segredo sujo.",--Alright, friends. This must be the shop we were told about. So far, the triad has been able to keep the kerels from discovering its true purpose.",
  loc_chas_01_03 = "Lá vamos nós. Essa é a loja de chá que a moça das informações nos contou, que a tríade está usando como um disfarce.",--Here we go. This is the tea shop we were told about, that the triad is using a front.",
  loc_chas_02_01 = "Vamos, entrem lá e achem um jeito de entrar no porão. Fiquem atentos, vai ter alarmes.",--Let's get you in there and find a way down to the cellar. Keep your eyes open, there's got to be alarms.",
  loc_chas_02_02 = "Vejam se vocês conseguem achar um jeito de entrar no porão e tomem cuidado com os alarmes.",--See if you can find a way down to the basement and keep a lookout for the alarms.",
  loc_chas_02_03 = "Vocês precisam entrar no porão. Tentem achar um jeito e não se esqueçam que o lugar tem alarmes.",--You need to get down to the cellar. Try to find a way down, and don't forget the place has alarms.",
  loc_chas_03_01 = "'Tão com problemas para achar o porão?",--Having trouble finding the cellar?",
  loc_chas_03_02 = "Qual é, amigos, vocês fazem essa parada de turista depois. Vão para o porão.",--Come on friends, you can do the tourist thing later. Get into that cellar.",
  loc_chas_03_03 = "Vocês tão parecendo bem suspeitos só de estarem aí. Melhor entrarem no porão.",--You're looking pretty conspicuous just hanging around there. Best get into the basement.",
  loc_chas_03_04 = "O que vocês tão esperando, não vai ter uma parada hoje, tá bom?",--What are you waiting around for, there's not going to be a parade today, yeah?",
  loc_chas_04_01 = "Tem um alarme naquela porta. Procurem um jeito de desliga-lo.",--There's an alarm on that door. Look around for a way to turn it off, yeah?",
  loc_chas_04_02 = "Aquela porta tem um alarme. Achem um jeito de desliga-lo.",--That door has an alarm. Find a way to turn it off.",
  loc_chas_04_03 = "Vocês vão precisar desligar o alarme naquela porta.",--You'll have to disable the alarm on that door.",
  loc_chas_05_01 = "Tudo aqui está ligado ao alarme, vocês precisam desligá-lo.",--Everything here is hooked up to the alarm, you need to disable it.",
  loc_chas_05_02 = "Esse alarme está em toda parte, vocês precisam desligá-lo.",--That alarm is wide-reaching, you've got to shut it down.",
  loc_chas_05_03 = "Como estão indo em desligar o alarme?",--Where are you on killing that alarm?",
  loc_chas_05a_01 = "Bom trabalho, estou desligando o alarme.",--Good job, taking out that alarm.",
  loc_chas_05a_02 = "É bom saber que desligaram o alarme.",--It's good thing you took out that alarm.",
  loc_chas_05a_03 = "Pensando rápido, desligando o alarme.",--Quick thinking, disabling that alarm.",
  loc_chas_06_01 = "Vocês vão precisar achar um cartão de acesso para aquela porta.",--You're going to have to find the keycard for that door.",
  loc_chas_06_02 = "Aquela porta precisa de um cartão de acesso. Vão achar um.",--That door needs a keycard to open. Let's go find it.",
  loc_chas_06_03 = "Precisa de um cartão de acesso para abrir aquela porta, tá em algum lugar. Vocês vão precisar achá-lo.",--There's a keycard to open that door, somewhere. You'll need to locate it.
  loc_chas_07_01 = "Vocês acharam o cartão de acesso? Talvez esteja no escritório.",--Have you found that keycard yet? Maybe see if it's in the office.
  loc_chas_07_02 = "Aquela porta não vai abrir com mágica sem um cartão de acesso.",--That door is not going to open quietly without a keycard.
  loc_chas_07_03 = "Continuem procurando pelo cartão de acesso, andem. Mas... sabem... não façam merda.",--Keep looking for that keycard, chop chop. But... you know... quietly.
  loc_chas_07a_01 = "Certo, agora abram a porta.",--Right, now open it.
  loc_chas_07a_02 = "Boa, agora vão abrí-la.",--Good, now get it open.
  loc_chas_07a_03 = "Boa, agora abram a porta.",--There you go, now open it.
  loc_chas_08_01 = "Aquela porta de garagem vai até um local em construção. É lá onde temos que ir, procurem um jeito de abrí-la.",--That rolling shutter door leads into the adjacent building. That's where we want to go, so look for a way to open it.
  loc_chas_08_02 = "A entrada do depósito com o cofre está atrás daquela porta de garagem. Achem um jeito de abrí-la.",--The entrance to the warehouse with the vault is behind that rolling shutter. Find a way to get it open.
  loc_chas_08_03 = "Vocês precisam passar pela porta de garagem para entrarem no depósito. Achem um jeito de abrí-la, certo?",--You need to get past that rolling shutter to get into the warehouse. Open it up a bit, yeah?
  loc_chas_09_01 = "Vocês já conseguiram abrir aquela porta de garagem?",--Have you got that shutter door open yet?
  loc_chas_09_02 = "Talvez tenha alguma alavanca ou algo assim que vai abrir a porta. Continuem procurando.",--Maybe there's a lever or something that will open the shutter. Keep looking.
  loc_chas_09_03 = "Deve ter algum mecânismo ou algo do tipo para abrir aquela porta.",--There's got to be a mechanism or something to open that shutter.
  loc_chas_10_01 = "Agora vão procurar pelo cofre.",--Now go have a look for the vault.
  loc_chas_10_02 = "O cofre deve estar perto. Vamos achá-la, certo?",--The vault is pretty close by. Let's go find it, yeah?
  loc_chas_10_03 = "Achem o cofre, agora, andem.",--Let's get you to finding that vault, now.
  loc_chas_11_01 = "Vocês precisam achar o cofre no depósito.",--You need to find the vault in the warehouse.
  loc_chas_11_02 = "Continuem procurando pelo cofre.",--Keep looking for the vault.
  loc_chas_11_03 = "Ainda não acharam o cofre?",--Still haven't found the vault?
  loc_chas_12_01 = "Ok, o cofre tá trancado com um cartão de acesso e um código. Achem os dois.",--OK, the vault is locked with both a keycard and a code. Find them.
  loc_chas_12_02 = "Para abrir o cofre, vocês vão precisar de um cartão de acesso e um código. Achem os dois.",--To open the vault you'll need both a keycard and the code for it. Let's go find them, yeah?
  loc_chas_12_03 = "O cofre precisa de um código e um cartão de acesso para ser aberto. Vão procurar.",--The vault needs a code and a keycard to open. Start looking.
  loc_chas_13_01 = "Vocês precisam achar o cartão de acesso, amigos.",--Gotta find that keycard, friends.
  loc_chas_13_02 = "Talvez um dos guardas tenha um cartão?",--Maybe one of the guards has the card?
  loc_chas_13_03 = "O cartão deve estar perto.",--The card must be close by.
  loc_chas_14_01 = "Agora vocês precisam do código. Tem um escritório perto da sala onde está acontecendo o leilão. Lá deve ter o código.",--Now you need the code. There's some office space near the room where they're holding the auction. It's a good bet the code is kept there.
  loc_chas_14_02 = "Agora, o código. Talvez vocês possam encontrá-lo no escritório.",--Now, the code. Maybe you can find it in the office.
  loc_chas_14_03 = "Certo, agora o código. Jiu Feng indicou que eles sempre guardam informações importantes no escritório próximo.",--Right, now for the code. Jiu Feng indicated they keep important information in the nearby office.
  loc_chas_15_01 = "Vocês precisam achar o código.",--You need to find the code.
  loc_chas_15_02 = "Achem a sala de leilão, depois vão para o escritório que está perto.",--Find the auction room, then look in the nearby office.
  loc_chas_15_03 = "Não podemos fazer nada sem aquele código, amigos.",--Can't move on without that code, friends.
  loc_chas_16_01 = "Aquele quadro que vocês acharam... parece ser uma configuração de código. Viram qual está sendo usado agora?",--That whiteboard you found... certainly looked like a code configuration. Did you see which one is being used right now?
  loc_chas_16_02 = "Vi que vocês estão perto de um quadro. Agora que percebi... parece conter informações do código. Talvez vocês possam deduzir qual está sendo usado.",--I recall you passing a whiteboard before. Now that I think about it... looked like it had code-y information on it. Maybe you can deduce which one is being used.
  loc_chas_16_03 = "Tenho certeza que naquele quadro tem umas informações do código. Voltem e vejam se tem algo de útil.",--I'm pretty sure there was some code-like writing on a whiteboard you went by. Go back and see if it's useful.
  loc_chas_17_01 = "Talvez a gente devesse checar aquele quadro de novo?",--Maybe go check that whiteboard again?
  loc_chas_17_02 = "Eu botei os símbolos que estão no quadro na pesquisa e Hastaltavista... menciona algo com 'tempo interno do cofre'... hora atual... porra, por que ninguém inventou um tradutor universal.",--I've run the symbols on that whiteboard through the Hastaltavista search... they mention something about 'vault internal time'... current time... blerrie, why hasn't anyone made a universal translator yet.
  loc_chas_17_03 = "Se eles mudam o código muito, ele deve estar escrito em algo que é facilmante apagado... como... um quadro.",--If they change the code often, it's gotta be on something that's easily erased.. like... you know... a whiteboard.
  loc_chas_18_01 = "O leilão ainda não começou. Talvez o escritório esteja atrás do estágio principal. Distraiam os convidados, aí vão poder ir para lá.",--The auction hasn't started yet. Maybe the office is behind the stage. Distract the guests so you can get a look.
  loc_chas_18_02 = "Talvez seja uma boa ideia distrair os convidados, aí vocês vão poder entrar no escritório, não é?",--It might be a good idea to distract the guests so you can have a nice, quiet look in the office, yeah?
  loc_chas_18_03 = "Achem um jeito de distrairem os convidados aí, assim vão poder entrar no escritório sem que ninguém veja vocês.",--Find a way to get those civvies out of the way so you can get into the office unnoticed.
  loc_chas_19_01 = "Chequem as outras áreas e vejam se tem algo que possam usar.",--Check the other areas and see if there's something you can use.
  loc_chas_19_02 = "Dêem uma olhada nos outros cantos para ver se tem algo que possa distrair os convidados.",--Have a look in one of the other areas to see if you can distract the guests.
  loc_chas_19_03 = "Vocês precisam distrair os convidados. Tem que ter algo por perto que vocês possam usar.",--You need to distract the guests. There's got to be something nearby you can use or do.
  loc_chas_19a_01 = "Com esses convidados chiques fora, vocês vão poder entrar no escritório sem muita dificuldade, não é?",--With those laanie guests out of the way, you'll have an easier time of entering the office, yeah?
  loc_chas_19a_02 = "Agora com esses comparadores de merda distraídos, vocês devem ter mais facilidade para entrar.",--Now that those dwankie buyers are distracted, you should have an easier time of it.
  loc_chas_19a_03 = "Com essa distração, vocês vão ter uma boa oportunidade para entrar.",--Distracting those tonghua civvies will have given you some breathing room to move around.
  loc_chas_20_01 = "O código do cofre parace mudar de acordo com a hora atual. Achem um jeito de encontrar o correto, certo?",--The vault code seems to change according to the current time. Find a way to suss the right one, yeah?
  loc_chas_20_02 = "A hora atual do dia parece ter relação com o código. Vocês precisam achar o certo.",--The current time of day seems to have something to do with the code. You need to find the right one.
  loc_chas_20_03 = "Eu acho que o código ativo tem alguma relação com a hora atual, então vocês vão precisar achar o certo.",--I think the active code is connected to the time of day, so you'll need to find it.
  loc_chas_20_04 = "O código atual parece estar conectado com a hora atual, então vocês vão precisar achar o certo.",--The active code seems connected to the time of day, so you'll need to find it.
  loc_chas_21_01 = "Talvez vocês devam checar de novo o quadro?",--Maybe double-check the whiteboard?
  loc_chas_21_02 = "Se tem relação com a hora atual, vocês precisam lembrar disso.",--If it's tied to the current time, you need to take that into account.
  loc_chas_21_03 = "Talvez eles tenham notas dos códigos em algum lugar? Continuem procurando.",--Maybe they have notes regarding the code somewhere? Keep looking.
  loc_chas_22_01 = "Certo, agora temos que esperar um pouco. Não sejam vistos.",--Right, now we have to wait for a bit. Stay out of sight.
  loc_chas_22_02 = "Ok, agora relaxem, certo?",--OK, now just hang back for a bit, yeah?
  loc_chas_22_03 = "Relaxem agora, esperem um tempo até funcionar, depois só voltarem ao serviço.",--Hang back, give it a minute to work, then get back in character.
  loc_chas_22_04 = "Ok, agora descansem um pouco, certo?",--OK, now just rest on your haunches for a bit, yeah?
  loc_chas_23_01 = "Me pergunto se tem algo interessante aí...",--I wonder what other interesting things might by lying around there...
  loc_chas_23_02 = "Vocês podem sempre achar algo de lembrança para o seu amigo Locke, enquanto esperam.",--You could always find a souvenir for your friend Locke while you're waiting.
  loc_chas_23_03 = "Acho que a nossa casa ficaria bom com algo extra, caso vocês acham algo legal quando voltarem.",--I reckon the safehouse could do with an extra bob or two, in case you find something nice to bring back.
  loc_chas_24_01 = "Vocês precisam desativar os lasers ao redor daquela grade. Dêem uma olhada nos fios do painel RFID, depois achem a caixa de fios que tem a mesma cor, aí corta elas.",--You need to disable the lasers around that gate. Have a look at the wires in the RFID panel, then find the matching wire box, and cut them.
  loc_chas_24_02 = "Desliguem esses lasers daquela grade. Vocês precisam achar os fios que são iguais desse painel RFID e cortar elas.",--Take out the lasers by that gate. You need to match the wires in the RFID panel and cut their counterparts in a nearby wire box.
  loc_chas_24_03 = "Procurem pelos fios que são iguais no painel RFID perto da grade, achem as cores certas na caixa de fios, aí corta elas.",--Look at the wires in the RFID panel by the gate, find the corresponding colors in a wire box, then cut them.
  loc_chas_25_01 = "Devem ter caixas de fios no depósito. Dêem uma olhada lá.",--There should be wiring boxes in the warehouse. Have a look.
  loc_chas_25_02 = "Decorem as cores daquele painel RFID para cortarem as cores certas.",--Use the RFID tag to find out which wires to cut.
  loc_chas_25_03 = "Chequem o RFID para ver quais fios devem cortar.",--Check the RFID for which wires to cut, then find the right ones.
  loc_chas_26_01 = "A grade está trancada com uma chave de modelo antigo. Vocês vão precisar achá-la, amigos.",--The gate is locked with a good old-fashioned key. You're going to have to find it, friends.
  loc_chas_26_02 = "Vocês vão precisar achar a chave para aquela grade. Vejam se vocês conseguem encontrá-la.",--You will need to find the key to that gate. See if you can find it.
  loc_chas_26_03 = "Aquela grade precisa de uma chave velha. Procurem por um chaveiro ou algo assim.",--That gate needs an old manual key to open. Look around for a keychain or something.
  loc_chas_27_01 = "Talvez aquele velhote do leilão esteja carregando a chave ou algo assim, não é?",--Maybe that krimpie auctioneer is carrying it on a keychain or something, yeah?
  loc_chas_27_02 = "Aquele velhote da tríade que estava no leilão... talvez ele tenha a chave.",--That old triad guy holding the auction... maybe he has it.
  loc_chas_27_03 = "Vocês poderiam... 'perguntar' para o leiloeiro se ele tem a chave...",--You could go and.. 'ask' the auctioneer if he has it...
  loc_chas_28_01 = "O dragão está numa caixa, mas eles podem ter colocado alguma armadilha para o caso de a gente achar o certo.",--The dragon is in a crate, but they might be booby-trapped so let's find the right one. No need make a ruckus opening things that don't need opening. They para obably keep a manifest in their computer system.
  loc_chas_28_02 = "Jiu Feng disse que as caixas que coisas valiosas podem ter armadilhas, então tentem achar o certo. Supostamente deve ter um manifesto em um computador em algum lugar.",--Jiu Feng mentioned the crates holding the valuables might be rigged to explode, so find the right one just to be sure. There's supposedly a manifest on a computer somewhere.
  loc_chas_28_03 = "Vamos achar o correto antes de abrir o desnecessário. Jiu Feng avisou que as caixas podem ter armadilhas. Vocês devem identificar olhando em um manifesto, provavelmente em um computador em algum lugar.",--Let's find the correct crate before we open them. Jiu Feng indicated they might be trapped. You should be able to indentify it by looking at a manifest, para obably on a computer in the area.
  loc_chas_29_01 = "Vocês precisam achar a caixa certa.",--You need to find the right crate.
  loc_chas_29_02 = "Talvez eles tem essa informação em um computador.",--Maybe they have the information stored in a computer.
  loc_chas_29_03 = "Conseguiram descobrir qual caixa é a certa?",--Have you found which crate is the right one yet?
  loc_chas_30_01 = "Boa, agora abram.",--Grootste. Now go get it open.
  loc_chas_30_02 = "Aê, agora vamos abrir.",--There, now let's open it up.
  loc_chas_30_03 = "Hora de vocês abrirem e torcerem para que nada exploda na cara de vocês, não é?",--Time to open it up and hope it doesn't go 'boom' in your faces, yeah?
  loc_chas_31_01 = "Tinha um número no monitor do computador que vocês hackearam... talvez seja o número da caixa.",--There was a number on the monitor of the computer you hacked... I reckon it's para obably the crate number.
  loc_chas_31_02 = "Aquele computador estava mostrando um número. Deve ser a caixa que estamos atrás, com certeza!",--That computer you hacked was displaying a number. Must be the crate we want, for sure!
  loc_chas_31_03 = "O número daquele computador... talvez é o número da caixa certa?",--The number on that computer screen... maybe that's the correct crate?
  loc_chas_32_01 = "Vamos, seus idiotas. Vocês já devem saber qual caixa é a certa!",--Come on, you chops. You already know which crate to open!
  loc_chas_32_02 = "Rápido, pessoal. Vocês precisam saber qual caixa é a certa!",--Hurry up, guys. You know which crate we're looking for!
  loc_chas_32_03 = "Vocês tem o número certo, então abram a caixa!",--You have the right number, so open the crate!
  loc_chas_33_01 = "Legal, isso deve valer cada centavo. Agora, vocês precisam sair daí, sem que ninguém da tríade veja vocês.",--Nice. That's definitely worth a pretty penny. Now you need to sneak it out of there without making the triad guys go bossies.
  loc_chas_33_02 = "Isso é ouro puro, com certeza! Saiam daí, sem soar o alarme.",--That's a bit of gold there, for sure! Let's get you to sneaking it out of there.
  loc_chas_33_03 = "Ouro purissímo. Uma pena ter que vender, mas agora vocês têm que sair daí!",--Pretty shiny. Almost a shame to sell it, but we have to get it out of there first!
  loc_chas_34_01 = "Parece pesado, mas vocês vão precisar achar um jeito de sairem daí.",--Looks heavy, but you will find a way to get it out.
  loc_chas_34_02 = "Levem essa desgraça para van, beleza?",--Get that dinges out to the van, yeah?
  loc_chas_34_03 = "Não podemos vender se vocês não sairem daí, andem logo.",--We can't sell it if you don't get it out of there, chop chop.
  loc_chas_35_01 = "Tá, terminamos. Caiam fora daí quando estiverem prontos.",--Ok, that's all. Get out of there as soon as you are ready.
  loc_chas_35_02 = "Terminamos. Vocês podem ir embora assim que estiverem afim.",--We're done. You can leave as soon as you're ready.
  loc_chas_35_03 = "Vamos embora, amigos. Pegamos o que a gente queria.",--Time to leave, friends. We got what we came for.
  loc_chas_36_01 = "Não precisam ficar para comer uma carne, caiam fora daí.",--No need to stay for a braai, get out of there.
  loc_chas_36_02 = "O que vocês estão esperando?",--What are you waiting around for?
  loc_chas_36_03 = "Eu não acho que esses idiotas da tríade vão convidar vocês para um chá, então, você podem ir embora, beleza?",--I don't think the triad domkops are going to invite you for tea, so you might as well get out, yeah?
  loc_chas_37_01 = "Tá, bora fazer isso do jeito barulhento. Se preparem para a troca de tiros.",--Ok, then let's do this the loud way. Be ready for a fight.
  loc_chas_37_02 = "Bom, terminamos. Não há sentindo em ficar na moita agora. Hora de fazer do jeito difícil, não é?",--Well that's done it. No sense in being quiet now. Break out the hardware, yeah?
  loc_chas_37_03 = "E eu achando que a gente podia fazer isso sem soar o alarme, mas acho que não. Já já chega um bando de policiais no seu rabo, podem ter certeza!",--And I thought maybe we could just do this quiet-like, but I guess not. You'll soon have lots of kerels on top of you, for sure!
  loc_chas_38_01 = "Nós sabemos que a tríade está usando a loja de chá como um disfarce.",--We know that the triad is using the tea shop as a front.
  loc_chas_38_02 = "Que boas vindas maravilhosas a costa oeste. Jiu Feng disse que a loja de chá é apenas um disfarce da tríade.",--What a friendly welcome to the west coast. Jiu Feng said the tea shop is only a front for the triad.
  loc_chas_38_03 = "Essa é a loja de chá que a tríade está usando como um disfarce!",--That's the tea shop the triad is using as a front!
  loc_chas_39_01 = "Entrem lá rápido e achem um jeito de entrar no porão.",--Get in there quick and find a way into the cellar.
  loc_chas_39_02 = "Entrem e dêem um jeito de entrar no porão, andem logo.",--Make your way inside and go downstairs, chop chop.
  loc_chas_39_03 = "Entrem e vão para o porão!",--Go inside and make your way into the cellar!
  loc_chas_40_01 = "Vocês precisam entrar no porão.",--You need to get to the basement.
  loc_chas_40_02 = "Parem de tomar Keemun, vão para aquela loja e entrem no porão.",--No time for drinking Keemun, get into that shop and go downstairs. ["Keemun" é um chá preto que cresce em Keemun, China.]
  loc_chas_40_03 = "Parem de enrolar, vão para o porão!",--No standing around, get down into that cellar!
  loc_chas_41_01 = "O leitor de cartão foi bloqueado, vocês vão ter que hackear.",--The card reader has been locked, you'll have to hack it.
  loc_chas_41_02 = "Vocês precisam hackear o leitor de cartão.",--You need to hack that card reader.
  loc_chas_41_03 = "Hackeiem o leitor de cartão e tomem cuidado com os policiais!",--Get to hacking that card reader and watch for kerels!
  loc_chas_42_01 = "Usem o computador da loja para derrubar o sistema de segurança.",--Use the store computer to take the security system offline.
  loc_chas_42_02 = "Tem um computador da loja que vocês podem usar para derrubar o sistema de segurança.",--There's a computer in the store you can use to cut the security system.
  loc_chas_42_03 = "O sistema de segurança pode ser derrubado com o computador da loja.",--The security system can be neutralyzed in the store computer.
  loc_chas_43_01 = "Caralho, os policiais atrapalharam o hack.",--Blerrie domkops have interrupted your hack.
  loc_chas_43_02 = "O hack foi interrompido.",--Your hack has been interrupted.
  loc_chas_43_03 = "O hack parou de rodar.",--The hack is no longer running.
  loc_chas_44_01 = "Reiniciem o hack.",--Get the hack restarted.
  loc_chas_44_02 = "Rápido, reiniciem o hack.",--Quicky, restart the hacking routine.
  loc_chas_44_03 = "Andem logo, amigos, reiniciem o hack!",--Chop chop, friends. Restart the hack!
  loc_chas_45_01 = "Alguém cortou a energia, vocês precisam ligá-la de volta.",--Someone cut the juice, you need to get it back up again.
  loc_chas_45_02 = "A energia foi cortada. Restartem ela!",--The power has been disabled. Get it up!
  loc_chas_45_03 = "Vocês perderam a energia e vão ter que ligar ela de volta.",--You've lost power and will have to reconnect it.
  loc_chas_46_01 = "A energia, amigos. Restartem-a!",--The power, friends. Restart it!
  loc_chas_46_02 = "Vocês não podem proseeguir sem a energia.",--You can't para oceed unless you get that power up.
  loc_chas_46_03 = "Vocês precisam religar a energia!",--The power needs to be reconnected!
  loc_chas_47_01 = "Ok, o leitor de cartão está ligado e rodando de novo, agora vocês precisam achar o cartão de acesso.",--OK, the card reader is up and running again, now you need to find the keycard for it.
  loc_chas_47_02 = "Certo, vocês precisam achar o cartão de acesso.",--Right, now you need to find the para oper keycard.
  loc_chas_47_03 = "Agora o leitor está funcionando, vocês precisam achar o cartão de acesso.",--Now that the reader is working, you have to find the keycard.
  loc_chas_48_01 = "Continuem procurando pelo cartão de acesso. Talvez tá no escritório.",--Keep looking for that card. Maybe it's in the office.
  loc_chas_48_02 = "Já acharam? Talvez esteja no escritório.",--Have you found it yet? Maybe it's in the office?
  loc_chas_48_03 = "Procurem no escritório e vejam se tem algum cartão de acesso.",--Look in the office and see if the keycard is there.
  loc_chas_49_01 = "Qual é, amigos, vocês precisam abrir aquela porta.",--Come on friends, you need to get that door open.
  loc_chas_49_02 = "Estão com problemas só para abrir a maldita porta?",--Are you still having trouble with the door?
  loc_chas_49_03 = "É tão difícil assim para abrir aquela porta? Puta que me pariu, abram!",--Is that door still creating a para oblem? Blerrie open it!
  loc_chas_50_01 = "Agora entrem no depósito.",--Now make your way into the warehouse.
  loc_chas_50_02 = "Vão para o depósito.",--Move into the warehouse.
  loc_chas_50_03 = "Entrem no depósito.",--Get into the warehouse.
  loc_chas_51_01 = "Porra, boa sorte, vocês podem usar a empilhadeira para abrir a porta de garagem. Achem as chaves!",--Blerrie good luck, you can use that forklift to open the shutter door. Find the keys!
  loc_chas_51_02 = "Aquela empilhadeira... podemos usar para abrir a porta da garagem.",--That forklift... use it to open the shutter door.
  loc_chas_51_03 = "A porta de garagem... forcem com a empilhadeira!",--The shutter door... push it open with the forklift!
  loc_chas_52_01 = "As chaves provavelmente devem estar por perto.",--The keys are para obably close by.
  loc_chas_52_02 = "Vocês provavelmente devem achar as chaves por perto.",--You will para obably find the keys nearby.
  loc_chas_52_03 = "As chaves devem estar por perto, não é?",--The keys have to be close, yeah?
  loc_chas_53_01 = "Beleza, agora vão em frente e liguem-a, aí arrombem a porta!",--Alright, go ahead and start it up, then ram the door!
  loc_chas_53_02 = "Agora liguem-a e arrombem aquela porta!",--Now start it up and drive right into that door!
  loc_chas_53_03 = "Usem a empilhadeira para dá uma bela porrada naquela porta de garagem!",--Use the forklift to give that shutter a right hard smash!
  loc_chas_54_01 = "Rápido, seus imbecis, arrombem aquela porta!",--Hurry up you chops, smash that door open!
  loc_chas_54_02 = "Rápido, minha gente... arrombem aquela porta com a empilhadeira!",--Chop, chop guys... forklift into door!
  loc_chas_54_03 = "Dirijam direto naquela porta com a empilhadeira!",--Drive into the door with the forklift!
  loc_chas_55_01 = "Bora achar o cofre, andem logo.",--Let's find that vault, chop chop.
  loc_chas_55_02 = "Hora de achar o cofre.",--Time to find the vault.
  loc_chas_55_03 = "Localizem o cofre.",--Locate the vault.
  loc_chas_56_01 = "Procurem no depósito, o cofre está aqui, tá bem fácil de achar.",--Search the warehouse, the vault is there, you can't miss it.
  loc_chas_56_02 = "Está em algum lugar no depósito.",--It's somewhere in the warehouse.
  loc_chas_56_03 = "Deve ser fácil de achar. Está no depósito.",--Should be easy to find. It's in the warehouse.
  loc_chas_57_01 = "Porra, Jiu Feng não mencionou que o cofre seria difícil. Vocês vão ter que usar uma furadeira. Tenho um cara trazendo ela, logo logo ele chega aí!",--Ach, Jiu Feng didn't mention the vault being that solid. You'll have to drill it. I've got someone ready to deliver one outside, will only take a jiffy!
  loc_chas_57_02 = "Não esperava que o cofre iria seria essa dor de cabeça. Não tem outro jeito além de usar a furadeira. Tem uma chegando aí.",--I wasn't expecting the vault to be that thick. No way around it, you've gotta drill. I've got one standing by.
  loc_chas_57_03 = "Caralho, vocês vão ter que usar a furadeira. Tá, esperem aí, vou cuidar disso.",--Blerrie, you're going to have to drill it. OK, hang on, I'm on it.
  loc_chas_58_01 = "A furadeira está a caminho, esperem aí.",--The drill is on the way, just wait for it.
  loc_chas_58_02 = "Estou mandando o Bile com a furadeira, vocês precisam ir lá fora e esperar por ele.",--I've got Bile coming with the drill, you need to get outside and wait for it.
  loc_chas_58_03 = "Esperem lá fora até que a furadeira seja entregue, certo?",--Wait outside until the drill is delivered, yeah?
  loc_chas_58a_01 = "Bile está a caminho com um helicóptero, aguentem aí, beleza?",--Bile is on the way with the choppa, hang in there for a bit, yeah?
  loc_chas_58a_02 = "Mandei um helicóptero com a furadeira, esperem aí.",--I have a helicopter incoming with the drill, just hold on.
  loc_chas_58a_03 = "Esperem aí, a furadeira está chegando pelos ares.",--Stand by, the drill on on the way by air.
  loc_chas_58b_01 = "Quase... lá...",--Almost... there....
  loc_chas_58b_02 = "Só mais um pouco, amigos.",--Just a little longer, friends.
  loc_chas_58b_03 = "Não falta muito.",--Not too much longer.
  loc_chas_58c_01 = "Ok, chegou a furadeira!",--OK, the drill is dropped and waiting!
  loc_chas_58c_02 = "Aê, a furadeira chegou!",--There you go, the drill has arrived!
  loc_chas_58c_03 = "A furadeira chegou!",--The drill has been delivered!
  loc_chas_59_01 = "Porra, Jiu Feng não mencionou que o cofre seria difícil. Vocês vão precisar da furadeira. Vão para fora, tem uma a caminho!",--Blerrie, Jiu Feng didn't mention the vault door being that solid. It needs drilling. Get outside, I've got one standing by for delivery!
  loc_chas_59_02 = "Caralho, não estava esperando que o cofre seria uma dor de cabeça. Vamos precisar de uma furadeira. Vão para fora, tem uma a caminho.",--Ach, I wasn't expecting the vault to be that heavy. We need to drill. Get outside and I'll have one delivered.
  loc_chas_59_03 = "Ok, vamos ter que usar a furadeira no cofre. Estou enviando uma para vocês, então, vão para fora para pegá-la, rápido pessoal!",--OK, we're going to have to drill the vault. I'm sending you one, so get outside and collect it, quickly friends!
  loc_chas_60_01 = "Assim que saírem, o nosso 'entregador' vai chegar com a furadeira.",--As soon as you get out there, our 'delivery boy' will be coming with that drill.
  loc_chas_60_02 = "Caiam fora daí e esperem pela furadeira!",--Get out and wait for the drill to be delivered!
  loc_chas_60_03 = "Saiam e esperem pela furadeira!",--Outside and wait for the drill to come!
  loc_chas_61_01 = "Certo, a furadeira está a caminho. É melhor que vocês não percam essa!",--Right, the drill is on the way. You won't be able to miss it. Hah!
  loc_chas_61_02 = "A furadeira vai chegar a qualquer minuto, de um jeitinho bem foda!",--The drill will be there any minute now, it's going to be kif!
  loc_chas_61_03 = "Fiquem de olho pela furadeira, amigos. Está chegando via entrega especial do Locke!",--Keep a lookout for the drill, friends. It's coming via Locke special delivery!
  loc_chas_62_01 = "Atenção, seus idiotas!",--Heads-up you chops!
  loc_chas_62_02 = "Se preparem, amigos!",--Be ready for it, friends!
  loc_chas_62_03 = "Lá vem!",--Here it comes!
  loc_chas_62_04 = "Saiam do caminho... putas!",--Out of the way... pecks!
  loc_chas_63_01 = "A furadeira chegou, vão pegá-la!",--The drill has arrived, go get it!
  loc_chas_63_02 = "Peguem a furadeira!",--Get the drill!
  loc_chas_63_03 = "Isso foi foda, não foi? Agora peguem a furadeira!",--That was great, yeah? Now pick up the drill!
  loc_chas_64_01 = "Tragam a furadeira para o cofre e montem ela, beleza?",--Bring the drill to the vault and set it up, yeah?
  loc_chas_64_02 = "Levem a furadeira para o cofre e montem ela.",--Take it to the vault and put it together.
  loc_chas_64_03 = "Vocês precisam montar a furadeira no cofre.",--You need to set up the drill at the vault.
  loc_chas_65_01 = "Vocês precisam montar a furadeira.",--You need to set up the drill.
  loc_chas_65_02 = "Levem a furadeira para o cofre.",--Get the drill set up by the vault.
  loc_chas_65_03 = "Já montaram a furadeira?",--Have you got that drill set up yet?
  loc_chas_66_01 = "Agora, mantenham qualquer filha da puta longe da furadeira.",--Now keep any trouble-makers from mucking about with it.
  loc_chas_66_02 = "Não deixem ninguém tocar na furadeira.",--Don't let anyone touch the drill.
  loc_chas_66_03 = "Protejam a furadeira dos policiais.",--para otect the drill from the kerels.
  loc_chas_67_01 = "Não deixem ninguém parar a furadeira.",--Don't let anyone stop the drill.
  loc_chas_67_02 = "Se certifiquem que ninguém pare a furadeira.",--Make sure no one stops the drill.
  loc_chas_67_03 = "Vocês precisam proteger a furadeira e manter ela funcionando!",--You need to para otect the drill and keep it running!
  loc_chas_68_01 = "A furadeira parou de funcionar, consertem ela!",--The drill has stopped working, restart it!
  loc_chas_68_02 = "A furadeira parou de funcionar. Vejam se conseguem consertar ela.",--The drill is no longer working. See if you can get it running.
  loc_chas_68_03 = "Tá, a furadeira parou de funcionar. Consertem ela!",--That's it, the drill is offline. Start it again!
  loc_chas_69_01 = "A furadeira ainda tá quebrada. Parem de zoar. Consertem ela!",--The drill is standing still. Not funny. Get it running!
  loc_chas_69_02 = "A furadeira precisa de um pouco de atenção.",--The drill needs some love and attention.
  loc_chas_69_03 = "Consertem logo aquela porra de furadeira.",--Get that drill running.
  loc_chas_70_01 = "Merda! Tão colocando gás! Esperem ele sumir ou tentem cortar ele.",--Ach! They're deploying gas! Either find somewhere to wait it out or turn it off!
  loc_chas_70_02 = "Cuidado com o gás! Achem um jeito de cortá-lo ou esperem ele sumir.",--Look out for gas! Find somewhere to turn it off or wait it out.
  loc_chas_70_03 = "Eles tão usando gás! Vocês podem esperar ele sumir ou acharem um jeito de cortá-lo.",--They're using gas! You can wait it out or find a way to turn it off.
  loc_chas_71_01 = "Se livrem do gás, amigos.",--Get rid of that gas, friends.
  loc_chas_71_02 = "Não dá para trabalhar com todo esse gás, dêem um jeito de cortá-lo!",--No good working with all that gas, find a way to turn it off!
  loc_chas_71_03 = "Se o gás não vai sumir, vocês devem cortá-lo.",--If the gas doesn't dissipate you should shut it off.
  loc_chas_72_01 = "Legal. Merda, mas essas barreiras estão eletrificadas, vocês precisam dar um jeito de cortar a eletricidade ou queimá-las.",--Niiice. Ach, but those bars have quite a few amps running through them, so you'll need a way to cut them open. Maybe you can find something to cut or burn through with.
  loc_chas_72_02 = "Não toquem nessas barras caso vocês querem sair vivos. Tem muita eletricidade nelas. Vamos ver se tem algo que possa queimar isso.",--Don't touch those bars if you want to live. A lotta juice running through them. Let's see if we can burn through somehow.
  loc_chas_72_03 = "Esperem... essas barras estão eletrificadas. Talvez vocês possam cortar elas.",--Wait.. those bars are electrified. Maybe you can cut through them.
  loc_chas_73_01 = "Parece que esses tríades tem muitas coisas úteis por aí, talvez possam achar um maçarico ou algo do tipo.",--Those triad chops seem to have lots of things handy around there, maybe you can find a blowtorch or something.
  loc_chas_73_02 = "Talvez seja bom dar uma olhada no escritório. Sempre um bom lugar para manter um maçarico caso você precise queimar uns papeis, não é?",--Maybe have a look in the office. Always a good place to keep a blowtorch in case you need to burn some papers, yeah?
  loc_chas_73_03 = "Um maçarico cairia bem agora, se vocês conseguissem achar um em algum lugar. É algo que a tríade deve ter por aí!",--A blowtorch would do the trick if you can find one lying around somewhere. Seems like something the triads would have just lying around!
  loc_chas_74_01 = "Talvez eles estejam mantendo as ferramentas no escritório, mas vocês teriam que passar pela porta de garagem para entrar. provavelmente estaria conectado com o sistema de segurança, então vocês vão ter que hackeá-lo.",--Maybe they keep tools in the office but you'll have to get past that shutter door to access it. It's para obably tied into the security system, so you'll need to hack it.
  loc_chas_74_02 = "Se tivermos sorte, eles devem ter deixado as ferramentas no escritório, mas vai ter uma porta de garagem no seu caminho. Hackeiem o sistema de segurança para abrí-la.",--With any luck they'll have tools in the office, but there's a shutter door stopping you. Hack into the security system to open it.
  loc_chas_74_03 = "Além da porta de garagem, tem um escritório onde vocês possam achar algumas ferramentas, mas vocês teriam que hackear o sistema de segurança para passar.",--Beyond the shutter door is an office where you might find some tools, but you'll have to hack the security to get past it.
  loc_chas_75_01 = "Hackeiem o sistema e abram a porta.",--Hack into the system and open the shutter.
  loc_chas_75_02 = "Deve ter um jeito de hackear o sistema e abrir a porta.",--There must be a way to hack the system and open that door.
  loc_chas_75_03 = "Para abrir a porta de garagem, vocês precisam hackear o sistema!",--To get by the shutter door you need to hack the system!
  loc_chas_76_01 = "Tenham certeza que ninguém vai interromper.",--Make certain no one interferes.
  loc_chas_76_02 = "Falta só um pouco. Daqui a pouco vai abrir.",--Not too long now, friends. It will open soon.
  loc_chas_76_03 = "Esperem um pouco agora.",--Hang in there for just a bit.
  loc_chas_77_01 = "Alguém interrompeu o hack! Reiniciem.",--Someone got to the hack! Get it up again.
  loc_chas_77_02 = "O hack foi interrompido!",--The hack has been interrupted!
  loc_chas_77_03 = "O hack parou de funcionar.",--The hacking routine is no longer running.
  loc_chas_78_01 = "Reiniciem o hack.",--Reset the hacking routine.
  loc_chas_78_02 = "Não estou vendo nenhum hack em progresso, ele está funcionando?",--No para ogress on the hack, is it running?
  loc_chas_78_03 = "Reiniciem o hack.",--Get the hack restarted.
  loc_chas_78a_01 = "Esse terminal... provavelmente vai abrir aquela porta.",--That terminal... will para obably open that shutter.
  loc_chas_78a_02 = "Vocês podem provavelmente abrir a porta com aquele terminal!",--You can para obably open the shutter door with that terminal!
  loc_chas_78a_03 = "Talvez a porta de garagem possa ser aberta com aquele terminal.",--Maybe the shutter door could be opened with that terminal.
  loc_chas_79_01 = "Boa, agora cortem a grade.",--Good, now cut the gate open.
  loc_chas_79_02 = "Cortem a grade.",--Cut the gate open.
  loc_chas_79_03 = "Agora cortem a grade.",--Now get to cutting that gate.
  loc_chas_80_01 = "Rápido e cortem a grade, amigos!",--Hurry up and open those bars, friends!
  loc_chas_80_02 = "Usem o maçarico na grade.",--Use the torch on the gate.
  loc_chas_80_03 = "Vocês precisam usar o maçarico na grade, rápido!",--You need to blowtorch that gate, chop chop!
  loc_chas_80a_01 = "Puta que pariu hein! É para ouvir quando eu digo que as barras estão eletreficadas, beleza?",--You domkop! Better listen when Locke tells you the juice is on, yeah?
  loc_chas_80a_02 = "Caralho, você tá cheirando igual bacon agora, né?",--Blerrie, you're going to smell like bacon, yeah?
  loc_chas_80a_03 = "Seu... idiota! É para ouvir quando eu te dou algum aviso!",--You... chop! You gotta listen when Locke warns you!
  loc_chas_81_01 = "Certo, a estátua que nós estamos atrás deve estar em uma dessas caixas, vocês precisam de um pé-de-cabra para abrí-las. Cuidado, Jiu Feng disse que elas estão com armadilhas!",--Right, the statue we're after should be in one of those crates, but I reckon you'll need a crowbar to get them open. Be careful, Jiu Feng said they are often booby-trapped!
  loc_chas_81_02 = "Uma dessas caixas tem a estátua. Vejam se vocês conseguem achar um pé-de-cabra para abrí-las, mas elas vão estar com armadilhas, então, tome cuidado.",--One of those crates holds the statue. See if you can find a crowbar to open it with, but we were told they are para obably rigged, so be careful.
  loc_chas_81_03 = "Achem um pé-de-cabra e abram as caixas, mas tomem cuidado, Jiu Feng disse que elas estão com armadilhas!",--Find a crowbar and crack those crates open, but be careful - Jiu Feng said they are often trapped!
  loc_chas_82_01 = "Já acharam um pé-de-cabra?",--Have you found a crowbar yet?
  loc_chas_82_02 = "Vocês precisam abrir as caixas.",--You need to crack open those crates.
  loc_chas_82_03 = "Vocês precisam abrir as caixas!",--You gotta open the crates!
  loc_chas_83_01 = "Opa, olha que coisa bonita, não é? Caiam fora daí, andem logo!",--Oh, that's a lovely dinges, innit? Get it out of there, chop chop!
  loc_chas_83_02 = "É para isso que a gente veio. Brilhante! Hora de levá-lo para casa.",--That's what we came for. Shiny! Time to take it home.
  loc_chas_83_03 = "Aí está, isso vai dá uma bela grana, não é? Bora levá-lo para casa!",--There we go, that's a nice bit of loot, yeah? Let's get it back to the safehouse!
  loc_chas_84_01 = "Andem logo, seus idiotas!",--Move it, you chops!
  loc_chas_84_02 = "Mais policiais a caminho, caiam fora daí com a estátua!",--More kerels on the way, get out of there with that statue!
  loc_chas_84_03 = "Rápido e levem a estátua para fora!",--Hurry up and get that statue out of there!
  loc_chas_85_01 = "Amigos, lembram daquela C4 que vocês viram antes? Talvez possam usá-la para abrir nossa própria saída.",--Friends, was that C4 I saw you pass before? Maybe use it to open a faster way out of there.
  loc_chas_85_02 = "Talvez tenha um jeito mais rápido... tem C4 nas caixas... talvez possamos usá-las para fazer uma saída?",--Maybe there's a faster way... there was some C4 in there.. maybe use it to blow an extra exit?
  loc_chas_85_03 = "Vocês poderiam fazer a própria saída de vocês, se usarem aquela C4 que acharam nas caixas...",--You could speed up your exit if you use that C4 you found earlier...
  loc_chas_86_01 = "Acho que vocês vão precisar colocar três C4.",--I reckon you'll need to place three charges.
  loc_chas_86_02 = "Bora. Peguem as C4s.",--Let's move it. Get those charges set.
  loc_chas_86_03 = "Três C4s na parede já deve servir.",--Three charges on the wall should be enough.
  loc_chas_87_01 = "Se vocês mandarem mais coisas valiosas pelo esgoto, vou mandar Garth para pegar!",--If you drop some extra valuables down that sewer, I'll send Garth by to pick it up!
  loc_chas_87_02 = "Vou mandar o nosso amigo Garth esperar no esgoto, caso vocês mandam mais coisas valiosas por lá!",--I've got our little para ospect friend Garth waiting in the sewer in case you want to drop some extra loot down to him!
  loc_chas_87_03 = "Se tem mais alguma coisa valiosa que vocês queiram pegar, vocês podem mandar pelo esgoto e eu vou mandar o Garth pegar para gente!",--If there's any extra loot you want to grab, you can drop them into the sewer and I'll have Garth pick them up for us!
  loc_chas_88_01 = "Beleza, hora de vazar. Voltem para rua.",--Ok, time to go. Back onto the asphalt.
  loc_chas_88_02 = "Tá na hora de escapar, voltem para rua!",--It's time to leave, get back to the street!
  loc_chas_88_03 = "Voltem para rua, amigos, bora dar um fora!",--Back to the street friends, time to skedaddle!
  loc_chas_89_01 = "O veículo de fuga está a caminho, esperem um pouco.",--Extraction is on the way, just hang on for a bit.
  loc_chas_89_02 = "A sua carona está chegando, logo logo está aí!",--Your ride is coming, should be there soon!
  loc_chas_89_03 = "Mantenham a calma e continuem matando os policiais, a sua carona já já chega.",--Keep calm and keep stopping kerels, your ride out is on the way.
  loc_chas_90_01 = "Cuidado, amigos, esperem um pouco mais.",--Steady friends, just a bit longer.
  loc_chas_90_02 = "Quase lá...",--Almost there...
  loc_chas_90_03 = "A qualquer segundo, amigos. A qualquer segundo...",--Any second now, friends. Any second...
  loc_chas_91_01 = "A van chegou. Levem a estátua.",--The van has arrived. Get the statue inside.
  loc_chas_91_02 = "Ok, levem a estátua para van!",--OK, get to the van with the statue!
  loc_chas_91_03 = "Boa, agora levem a estátua para van!",--Good, now get the statue to the van!
  loc_chas_92_01 = "Rápido agora, assegurem a estátua.",--Quickly now, secure that statue.
  loc_chas_92_02 = "Por que vocês estão enrolando? Levem a estátua e caiam fora daí!",--Why are you loitering about? Stow that statue and get out!
  loc_chas_92_03 = "Parem de enrolar, seus idiotas e caiam fora daí!",--Stop meandering you chops and get out of there!
  loc_chas_93_01 = "É isso aí, terminamos.",--That's it, you're done.
  loc_chas_93_02 = "Entrem na van, amigos.",--Jump into the van, friends.
  loc_chas_93_03 = "Entrem na van, seus idiotas!",--Into the van you chops!
  loc_chas_94_01 = "O que vocês estão esperando?",--What are you waiting for?
  loc_chas_94_02 = "O bicho tá pegando e mais policiais estão chegando! Caiam fora daí!",--The meter is running and more kerels are coming! Get out of there!
  loc_chas_94_03 = "Fizemos a nossa parte, agora vazem daí!",--We've done our job, now get out of there!
  loc_chas_end_01 = "Isso foi bom, amigos. Esse Jiu Feng parece ser um cara de boa para fazer negócios. Só espero não ter acordado o mostro das montanhas depois dessa, se vocês entenderam.",--That was a good run, friends. This Jiu Feng fellow seems like a reliable source to do business with. I just hope we haven't woken up the monster-in-the-mountain with this one, if you take my meaning. But needs must when the gin is gone, yeah?

  -- Objetivos
  hud_heist_chas1_hl = "Entre na loja e ache a porta do porão",--Go inside and find the basement door",
  hud_heist_chas1 = "Entre na loja de chá, depois ache a porta que vai para o porão.",--Enter the tea shop, then find the door leading to the cellar.",
  hud_heist_chas2_hl = "Procure pela caixa de alarme no lado de fora",--Look for an alarm box outside",
  hud_heist_chas2 = "Para continuar, o sistema de alarmes da loja precisa ser desativado. A caixa de energia deve estar em algum lugar no lado de fora da loja.",--To para oceed, the shop alarm system must be disabled. The electric box for it should be located somewhere outside the store.",
  hud_heist_chas3_hl = "Ache o cartão de acesso para a porta de trás",--Find a keycard to the back door",
  hud_heist_chas3 = "Um cartão de acesso é preciso para abrir a porta que vai para o porão da loja.",--A keycard is needed to open the door to the shop cellar.",
  hud_heist_chas4_hl = "Ache um jeito de entrar no depósito",--Find a way into the warehouse",
  hud_heist_chas4 = "Para achar o cofre, vocês precisam entrar no depósito",--To reach the vault, you need to get inside the warehouse.",
  hud_heist_chas5_hl = "Localize o cofre",--Locate the vault",
  hud_heist_chas5 = "O cofre está localizado em algum lugar dentro do depósito. Ache-o.",--The vault is located somewhere inside the warehouse. Find it.",
  hud_heist_chas6_hl = "Ache um jeito de passar pela sala do leilão",--Find a way to get past the auction hall",
  hud_heist_chas6 = "Tem comparadores na sala do leilão. Ache um jeito de distrair eles para fora.",--There are buyers in the auction hall. Find a way to lure them away.",
  hud_heist_chas7_hl = "Ache o cartão de acesso do cofre e use-o",--Find the vault keycard and use it",
  hud_heist_chas7 = "Para abrir o cofre, vocês precisam achar o cartão de acesso.",--To open the vault, you need to find the keycard for it.",
  hud_heist_chas8_hl = "Espere pelo temporizador",--Wait out the time lock",
  hud_heist_chas8 = "O cofre tem um temporizador ativo. Vocês precisam esperar até o tempo acabar e abrir.",--The vault has an active time lock. You need to wait for it to expire and unlock.",
  hud_heist_chas9_hl = "Corte os fios para desativar o sistema de laser",--Cut the wires to disable the laser system",
  hud_heist_chas9 = "Para conseguir entrar no cofre, o sistema de laser precisa ser desativado.",--In order to get inside the vault, the security laser system must be shut down.",
  hud_heist_chas11_hl = "Hackeie o computador",--Hack the computer",
  hud_heist_chas11 = "Um PC próximo deve ter o manifesto das caixas. Hackeie para descobrir qual é.",--A nearby PC contains the shipping manifest. Hack it to find which crate to open.",
  hud_heist_chas12_hl = "Colete o artefato da caixa correta",--Collect the artifact from the correct crate",
  hud_heist_chas12 = "Achem um pé-de-cabra para abrir a caixa com a estátua.",--Find a crowbar to open the crate containing the statue.",
  hud_heist_chas13_hl = "A fuga está disponível",--Escape available",
  hud_heist_chas13 = "Levem o artefato e qualquer outro loot para van.",--Bring the artifact and any other loot to the escape van.",
  hud_heist_chas15_hl = "Hackeie o sistema do leitor de cartão",--Override the card reader system",
  hud_heist_chas15 = "A porta de trás está trancada e precisa ser hackeada para ser aberta.",--The back door is on lockdown and needs to be hacked open.",
  hud_heist_chas17_hl = "Localize as chaves da empilhadeira",--Locate the forklift keys",
  hud_heist_chas17 = "Para conseguirem usar a empilhadeira, achem as chaves para o veículo.",--In order to use the forklift, the keys to it needs to be found.",
  hud_heist_chas18_hl = "Entre no depósito",--Enter the warehouse",
  hud_heist_chas18 = "Entrem no depósito para continuar.",--Get inside the warehouse to para oceed.",
  hud_heist_chas20_hl = "Pegue a furadeira térmica",--Get the thermal drill",
  hud_heist_chas20 = "Vocês precisam pegar a furadeira térmica para abrir o cofre.",--You need to get your hands on the thermal drill to get inside that vault.",
  hud_heist_chas21_hl = "Prepare a furadeira no cofre",--Place the drill at the vault",
  hud_heist_chas21 = "Voltem para o cofre e preparem a furadeira.",--Return to the vault downstairs and set up the drill.",
  hud_heist_chas22_hl = "Proteja o cofre",--Defend the drill",
  hud_heist_chas22 = "Os policiais vão tentar parar a furadeira. Não deixem que isso aconteça.",--The cops will try to stop the drill. Prevent them from doing so.",
  hud_heist_chas23_hl = "Corte a grade",--Cut open the gate",
  hud_heist_chas23 = "Usem o maçarico para passar pela grade.",--Use a blowtorch to get inside the inner door.",
  hud_heist_chas25_hl = "Usem as C4 para criar uma nova saída",--Use C4 to create a new escape route",
  hud_heist_chas25 = "Vocês precisam explodir um buraco nas paredes, usando a C4 que vocês viram antes.",--You need to blow a hole in one of the walls in order to escape, using the C4 located nearby.",
  hud_heist_chas26_hl = "Espere pelo veículo de fuga",--Wait for extraction",
  hud_heist_chas26 = "O veículo de fuga ainda não chegou. Esperem até chegar.",--The escape van isn't here yet. Wait for it to arrive.",
  hud_heist_chas27_hl = "Fuja",--Escape",
  hud_heist_chas27 = "O veículo de fuga está aqui, vão até lá para fugir.",--The escape van is here, get to it in order to escape.",
  hud_heist_chas28_hl = "Descubra qual é o código do cofre e digite-o",--Figure out the vault code and enter it",
  hud_heist_chas28 = "O código está escondido em algum lugar no escritório do leilão, procurem e vejam o que acham.",--The code is hidden somewhere in the auction office, look around and see what you can find.",
  hud_heist_chas29_hl = "Hackeie o sistema de segurança do escritório",--Hack the security barrier to the office",
  hud_heist_chas29 = "A porta está trancada, hackeie o sistema de segurança.",--The door to the office is locked, bypass it by hacking its security.",
  hud_heist_chas31_hl = "Conserte a furadeira",--Restart the drill",
  hud_heist_chas31 = "A furadeira está quebrada, consertem ela.",--The drill has been interrupted, fix it to resume drilling.",
  hud_heist_chas32_hl = "Voltem para rua",--Get out to the street",
  hud_heist_chas32 = "Vocês roubaram o artefato, agora saiam da loja e esperem pelo veículo de fuga.",--You have taken the artifact, now leave the building and wait for the escape van.",
  hud_heist_chas33_hl = "Assegure a Estátua do Dragão",--Secure the dragon statue",
  hud_heist_chas33 = "Entregem a estátua ao veículo de fuga.",--Deliver the statue to its transport.",
  hud_heist_chas34_hl = "Destranque a porta dos fundos",--Unlock the back door",
  hud_heist_chas34 = "Destranque a porta que vai para o porão com o cartão de acesso.",--Unlock the door that leads to the cellar with the keycard.",
  hud_heist_chas36_hl = "Procure pelo maçarico",--Look for a blowtorch",
  hud_heist_chas36 = "Para passar pela grade, vocês vão precisar de um maçarico. Talvez tenha um abaixo da loja.",--To get past the gate you need a blowtorch. There might be one below the store.",
  hud_heist_chas37_hl = "Desligue o gás",--Turn off the gas",
  hud_heist_chas37 = "Removem o gás da ventilação do lado de fora do depósito.",--Remove the gas canister from the vent outside the warehouse.",
  hud_heist_chas38_hl = "Ache o artefato em uma das caixas",--Find the artifact in one of the crates",
  hud_heist_chas38 = "O artefato está em uma dessas caixas.",--The artifact should be in one of these crates.",
  hud_heist_chas39_hl = "Saia e espere pela furadeira térmica",--Go out and wait for the thermal drill",
  hud_heist_chas39 = "Locke está mandando a furadeira térmica, vão para fora e peguem ela.",--Locke is sending you the thermal drill, so go out and pick it up.",
  hud_heist_chas40_hl = "Abram a grade com as chaves",--Open the gate with the keychain",
  hud_heist_chas40 = "Achem a chave certa para abrir o cofre.",--Find the correct keychain to open the vault.",
  hud_heist_chas41_hl = "Achem o escritório do leilão",--Find the auction hall office",
  hud_heist_chas41 = "O cofre está trancado por uma senha, deve ter um jeito de descobrir qual é.",--The vault is locked by a password, there must be a way to find out what it is.",
  hud_heist_chas43_hl = "Restaure a energia",--Restore the power",
  hud_heist_chas43 = "Restaure a energia com o interruptor",--Restore the power with the power switch.",
  hud_heist_chas44_hl = "Conserte o hack",--Resume the hack",
  hud_heist_chas44 = "A energia voltou. Consertem o hack.",--The power is back on. Resume the hack.",
}