return {
	-- Nomes e Descrições
	--heist_fish = "The Yacht Heist",--The Yacht Heist
	--heist_fish_hl = "The Yacht Heist",--The Yacht Heist
	heist_fish_crimenet = "Eu sei que o prefeito McKendrick tem sido um tipo de... Obstáculo para a Gangue PAYDAY. Agora, eu recebi uma informação de que ele está movendo muito dinheiro ilegal pra o país para sua re-eleição. O suficiente para decidir a eleição, talvez. O dinheiro está escondido no Iate que pertence a um certo Ethan Powell, um aliado de McKendrick. O Iate está atualmente ancorado em Nova Iorque.$NL;$NL;» Encontre e Pegue os amontoados de Dinheiro$NL;» Localize e Pegue o Servidor$NL;» Fuja com o Loot",--I know that mayor McKendrick has been somewhat of an... obstacle for the Payday Gang. Now, I have very reliable information that he's moving a large amount of illegal cash into the country to use for his re-election campaign. Enough to decide the election, perhaps. The money is hidden on a yacht belonging to a certain Ethan Powell, an ally of McKendrick. The yacht is currently anchored in New York harbor.$NL;$NL;» Find the stashes and bag the money$NL;» Locate and retrieve the server$NL;» Escape with the loot
	heist_fish_hl_briefing = "Ok gente, vocês já sabem da parada aqui. McKendrick precisa do dinheiro para ganhar as eleições, e se vocês conseguirem roubá-los vocês vão tirar o tapete de baixo dele. Vamos detonar essa festa, chover em seu desfile - se igualar ao que aquele bosta fez. Então peguem o dinheiro. E tem mais uma coisa que eu encontrei.. um arquivo que o Charon nos deu - algum lugar no Iate tem um servidor com senhas para contas de banco ilegal, algumas que são usadas por McKendrick. Roubem aquele servidor, e poderemos pegar um bom dinheiro. $NL;Vai ter uma festa de angariação do McKendrick no Iate hoje a noite. Com TV e tudo. Mas a festa será principalmente no andar superior, então vocês vão poder entrar furtivamente e sair sem ninguém notar.",--Ok guys, you know what's at stake here. McKendrick needs that cash to win the elections, and if you can steal it you're pulling the rug out from under his feet. Let's spoil his party, rain on his parade - get even for what that ungrateful bastard did. So get that cash. And there's another thing I found in the file that Charon gave us - somewhere on the yacht there's a server which contains passwords for illicit foreign bank accounts, some of which are also used by McKendrick. Steal that server, and we can cash in nicely on it.$NL;There's a fundraising party for McKendrick on the yacht tonight. With TV and everything. But the party's mostly on the upper deck, so if you sneak in quietly you should be able to get in and out without anyone noticing.

	-- Legendas
	pln_fish_intro_01 = "Ok, piratas - Entrem no Navio e peguem o loot. E mantenham-se quietos.",--Okay, pirates - board the ship and get the loot. And keep it quiet.
	pln_fish_intro_02 = "Tomem cuidado, não deixem os guardas verem vocês. E encontrem o dinheiro.",--Be careful now, don't let the guards see you. And find that cash.
	pln_fish_intro_03 = "Boa sorte nessa caça ao tesouro, gente. E lembrem-se: Fiquem quietos.",--Good luck on your treasure hunt, guys. And remember, keep it quiet.
	pln_fish_32_02 = "Se vocês quiserem se livrar dos corpos no mar, vocês podem usar as janelas.",--If you want to dump bodies into the sea, you can use the windows.
	pln_fish_19_01 = "Ok, eu consigo abrir a porta. Mas ela não vai funcionar até o Bloqueador de ECM parar.",--Ok, I got the doors. But they won't open until the ECM jammer stops.
	pln_fish_21_02 = "Desliguem o sistema de refrigeramento. Isso deverá fazer os servidores secundários sobreaquecer.",--Turn off the flow of coolant. That should make the secondary servers overheat.
	pln_fish_26_02 = "Mais um deve servir.",--One more should do it.
	pln_fish_15_03 = "Usem a tirolesa para assegurar as bolsas.",--Use the zipline to secure the bags.
	pln_fish_03_08 = "Continuem procurando pelo Laptop.",--Just gotta keep looking until you find the laptop.
	pln_fish_end_01 = "Ótimo trabalho, gangue - Vocês realmente fuderam com o McKendrick dessa vez. Ele não ficará feliz quando descobrir que o dinheiro sumiu.",--Great job, gang - you really screwed McKendrick over this time. He won't be happy when he finds out all that money's gone.
	pln_fish_34_03 = "É ótimo que a festa se localize mais no andar superior. Assim nós podemos trabalhar em paz aqui.",--I'm sure glad most of the party is upstairs so we can work in peace and quiet down here.
	pln_fish_17_03 = "Me conectem e vou destrancar aquela porta em alguns momentos.",--Get me hooked up and I'll get that door unlocked in just a few moments.
	pln_fish_19_02 = "As portas devem abrir quando o Bloqueador de ECM parar.",--The doors should open once the ECM jammer stops.
	pln_fish_26_01 = "Só mais uma agora.",--Just one more now.
	pln_fish_25_02 = "Verifiquem duas anulações, mais duas para ir,",--Check two overrides, two more to go.
	pln_fish_08_03 = "Uma já foi, mais três para ir!",--One down, three to go!
	pln_fish_05_02 = "Agora coloquem a senha.",--Now you've got to enter the password.
	pln_fish_04_02 = "É, isso é o que estavamos procurando.",--Yeah, that's the one we're looking for.
	pln_fish_06_02 = "Parece uma lista de onde o dinheiro está escondido. Está em todo o Iate.",--Looks like a list of where the money is hidden. It's all over the yacht.
	pln_fish_29_03 = "Ok, não há mais nada mais pra roubar. Saiam daí.",--Ok, there's nothing left to steal. Get out of there.
	pln_fish_35_02 = "Aquilo parece uma equipe de jornalistas da TV. Se não quiserem aparecer na TV, fiquem fora da câmera.",--That looks like a television news crew. You don't want to be on TV guys, stay off their camera.
	pln_fish_15_02 = "Tem uma tirolesa que vocês podem usar para assegurar as bolsas.",--There's a zipline you can use to secure the bags of loot.
	pln_fish_15_01 = "Usem a tirolesa para assegurar o loot.",--Use the zipline to secure the loot.
	pln_fish_18_01 = "Ok, as portas estão abertas. Entrem.",--Ok, the doors are open. Get inside.
	pln_fish_19_03 = "As portas só vão abrir quando o Bloqueador de ECM parar.",--The doors will only open once the ECM jammer stops.
	pln_fish_23_01 = "Isso deve bastar. Eles vão sobreaquecer e causar um reboot.",--That should do it. They'll overheat now and cause that reboot.
	pln_fish_16_01 = "Ok, isso está ótimo. Agora para o servidor... se vocês voltarem e me conectarem ao laptop, eu devo conseguir abrir a sala onde o servidor está.",--Ok, that's great. Now for that server... If you get back to that laptop and hook me up, I should be able to open the room where the server is.
	pln_fish_07_03 = "Verde e doce! Peguem o dinheiro!",--Green and sweet! Bag that cash!
	pln_fish_24_03 = "Ok, eu posso sobrepor o painel principal agora.",--Ok. I can override the main panel now.
	pln_fish_02_03 = "Tem um laptop com a informação de onde o dinheiro está. Charon providenciou uma senha. Vejam se vocês conseguem localizar.",--There's a laptop with info on where the cash is stashed. Charon provided the password. See if you can find it!
	pln_fish_32_01 = "Vocês podem jogar os corpos no mar pelas janelas.",--You can dump bodies into the sea through the windows.
	pln_fish_28_02 = "Pode ter mais loot no Iate, mas vocês já conseguiram pegar o necessário. A escolha é de vocês.",--There might be more loot on the yacht, but you got what you came for. Your choice.
	pln_fish_12_02 = "Se vocês jogarem as bolsas no mar, vocês podem pegar quando formos embora.",--If you throw the loot bags into the sea, you can pick them up when it's time to leave.
	pln_fish_36_01 = "Um Bloqueador de ECM ativo vai provavelmente tornar mais dificil de abrir a porta da Sala do Servidor. Tenham isso em mente.",--An active ECM jammer will probably make it hard to open the server room security door. Keep that in mind.
	pln_fish_03_02 = "Lembrem-se de procurar pelo laptop!",--Remember to look for the laptop!
	pln_fish_14_02 = "Peguem mais bolsas e levem ao barco, ou joguem elas no mar. Podemos pegá-las quando formos embora.",--Either secure the bags in the motorboat, or chuck them in the sea. We can pick them up as we leave.
	pln_fish_07_01 = "Grandes e Benjamins. Lindo!",--Big ones and Benjamins. Beautiful!
	pln_fish_31_02 = "Nós quase conseguimos!",--We almost had it!
	pln_fish_31_03 = "Nós quase provamos aquele cigarro!",--We almost tasted that cigar!
	pln_fish_02_01 = "Deve ter um laptop com a informação de onde o dinheiro está. Temos a senha que o Charon nos deu. Então vocês só precisam encontrar essa coisa.",--There should be a laptop with information about where the cash is hidden. We got the password from Charon so all you gotta do is find the thing.
	pln_fish_16_03 = "Isso é todo o dinheiro assegurado. Agora para o servidor com as senhas do banco - Voltem para o laptop e me conectem para que eu possa abrir a porta da Sala do Servidor.",--That's all the cash secured. Now for the server with the bank passwords - get back to that laptop and hook me up so I can open the server room's security lock.
	pln_fish_37_03 = "Eu acho que essa é a Sala do Servidor. Não se esqueçam - Vocês tem que pegar o dinheiro primeiro.",--I guess that's the server room. Make note of it - you should find the cash first.
	pln_fish_09_02 = "Vocês pegaram o segundo amontoado. Continuem olhando, mais dois!",--You got the second stash. Keep looking, two more!
	pln_fish_16_02 = "Ok, agora para a Sala do Servidor... Aquele laptop que vocês encontraram antes deve me deixar entrar e conseguir acesso.",--Ok, now for the server room... That laptop you found earlier should enable me to give you access. Go back there and hook me up.
	pln_fish_10_02 = "Vocês pegaram o terceiro amontoado. Mais um agora!",--You got the third stash. One more now!
	pln_fish_26_03 = "Só mais um botão.",--Just one more override.
	pln_fish_18_03 = "Ok pessoal, vocês entraram.",--Ok guys, you're in.
	pln_fish_11_03 = "Esse é todo o dinheiro!",--That's all of the cash!
	pln_fish_10_03 = "Três já foram, só mais um para ir!",--Three down, just one to go!
	pln_fish_07_02 = "Doce dinheiro! Agora peguem!",--Sweet sweet cash! Now bag it!
	pln_fish_08_02 = "Vocês pegaram o primeiro amontoado. Continuem olhando!",--You got the first stash. Keep looking!
	pln_fish_13_02 = "Assegurem todo o loot no barco que vocês vieram.",--Secure the loot bags in the motorboat you arrived in.
	pln_fish_25_01 = "Metade já foi, faltam apenas mais dois.",--Halfway now, just two more overrides to go.
	pln_fish_08_01 = "Esse é o primeiro, Mais três para ir!",--That's the first stash. Three to go!
	pln_fish_06_03 = "Ótimo trabalho - Tem toda a informação de onde o dinheiro está escondido.",--Great job - it's got all the info on where the money's hidden.
	pln_fish_33_02 = "Vocês podem esconder os corpos jogando eles no mar atrás do barco.",--You could hide the bodies by throwing them into the sea at the back of the boat.
	pln_fish_05_03 = "Coloquem a senha e acessem os arquivos.",--Enter the password and access the files.
	pln_fish_28_03 = "Vocês podem procurar por mais loot ou sairem agora mesmo.",--You can either look for more loot or get out of there now.
	pln_fish_03_05 = "Vocês precisam achar o laptop se quiserem pegar o dinheiro.",--You gotta find the laptop if you want to get the money.
	pln_fish_35_03 = "Uma equipe de TV. Hmm... tentem ficar longe da câmera.",--A TV crew. Hmm... try to stay off their camera.
	pln_fish_35_01 = "Aqueles são caras da TV? Tentem ficar longe deles.",--Is that a TV news crew? Try to stay away from them.
	pln_fish_14_03 = "Vocês podem jogar as bolsas no mar e pegarem quando nós sairmos. Ou levem até o barco que viemos.",--You can throw the bags in the sea and pick them up when we leave. Or take them directly to the motorboat - your choice.
	pln_fish_18_02 = "Ok, essa é a Sala do Servidor aberta.",--Ok, that's the server room door opened.
	pln_fish_14_01 = "Vocês podem assegurar as bolsas no barco que vieram ou no mar para pegarmos mais tarde.",--You can secure the bags down in the motorboat or throw them in the sea and we'll pick them up later.
	pln_fish_36_03 = "Um Bloqueador de ECM ativo vai tornar mais dificil de acessar a Sala do Servidor. Use-os com cuidado.",--An active ECM jammer will make it harder to access the server room. So use them with caution.
	pln_fish_27_02 = "Ok, pegamos. Mal posso esperar para extrair essas senhas!",--Ok, we got it. Can't wait to extract those passwords!
	pln_fish_11_02 = "Ótimo - Essa é a última!",--Great - that's the last of 'em!
	pln_fish_01b_02 = "Fiquem quietos e mantenham os olhos abertos.",--Go quiet and keep your eyes open.
	pln_fish_29_01 = "Vocês fizeram a limpa. Hora de irmos.",--You cleaned it out. Time to leave.
	pln_fish_end_03 = "Esse é o fim do sonho de re-eleição do McKendrick - Vocês são verdadeiros influenciadores, pessoal! A Gangue PAYDAY pegou e levou embora.",--That's the end of McKendrick's re-election dreams - you're true kingmakers, guys! The Payday Gang giveth and it taketh away.
	pln_fish_11_01 = "É o último amontoado! Vocês pegaram todos!",--That's the last stash! You got'em all!
	pln_fish_34_02 = "McKendrick possui vários influenciadores que estão o ajudando. Eles estão esperando o dinheiro caso ele ganhe, tenho certeza.",--McKendrick sure has a lot of influential supporters up there. They're expecting to cash in if he wins, I'm sure.
	pln_fish_02_02 = "Charon nos deu as senhas para o laptop que tem a informação de onde o dinheiro está. Encontrem-o!",--Charon gave us a password for a laptop that contains data on where the money is. Find it!
	pln_fish_24_02 = "Ok, agora sobreponham o painel principal.",--Ok, now for overriding the main panel.
	pln_fish_25_03 = "Verifiquem mais duas sobreposições, mais dois para ir.",--Check two overrides, two more to go.
	pln_fish_17_01 = "Ok, me conectem ao laptop, isso não vai demorar.",--Ok, connect me to the laptop, this should only take a moment.
	pln_fish_31_01 = "Droga, muito perto!",--Damn it, so close!
	pln_fish_17_02 = "Ok, me conectem e vou acabar com isso em alguns segundos.",--Ok, connect me and I'll have this done in a few seconds.
	pln_fish_20_03 = "Vocês vão ter que fazer um reboot sobrepondo o sistema. Isso vai nos dar o controle para abrir o servidor.",--You'll need to induce a soft reboot by overheating the system. That'll get you access to the controls so you can grab the server.
	pln_fish_29_02 = "Vocês pegaram tudo. Hora de voltarmos pra casa.",--You got everything. Time to go home.
	pln_fish_30_02 = "É o alarme! A Sala do Servidor está trancada agora - Não podemos mais acessar!",--That's the alarm! The server room's locked down now - we can't access it!
	pln_fish_21_03 = "Os servidores secundários devem sobreaquecer se vocês desligarem o refrigeramento.",--The secondary servers should overheat if you turn off the flow of coolant.
	pln_fish_37_02 = "Aquilo parece a Sala do Servidor. Melhor deixar pra depois quando já tiverem pego o dinheiro. Lembrem-se disso.",--That looks like it might be the server room. Better save it for after you find the cash. Remember where it is.
	pln_fish_22_03 = "Desliguem as válvulas.",--Turn those valves off.
	pln_fish_04_01 = "Aí está.",--There it is.
	pln_fish_03_04 = "Cadê o laptop? Já encontraram?",--Where's that laptop? Found it yet?
	pln_fish_33_03 = "Na parte de trás, vocês podem jogar qualquer corpo no mar.",--At the back you can throw any bodies over the railing into the sea.
	pln_fish_01b_03 = "Cuidado. Espero que não tenham trazido pés de pato.",--Careful now. I hope you didn't bring your squeaky shoes.
	pln_fish_13_01 = "Vocês podem pegar mais loot e levar ao barco que vieram.",--You can secure the loot bags in the boat you came in on.
	pln_fish_10_01 = "Já é o terceiro amontoado. Só falta mais um!",--That's the third stash. Only one left!
	pln_fish_22_02 = "Vocês precisam desligar as válvulas embaixo da Sala do Servidor.",--You need to turn off those valves at the bottom of the server rack.
	pln_fish_03_01 = "Encontrem o laptop, pessoal!",--Find that laptop, guys!
	pln_fish_30_01 = "A Sala do Servidor está trancada. Não podemos entrar agora!",--The server room is locked down. We can't get in there now!
	pln_fish_20_02 = "Se vocês sobreaquecerem o sistema eu vou fazer um reboot. Dando acesso a vocês para pegar o servidor.",--If you overheat the system it'll do a soft reboot, giving you access to the controls. Then you can get the server.
	pln_fish_36_02 = "Só pra avisar: Com o sistema de segurança que eles usam vai ser dificil abrir a porta enquanto um Bloqueador de ECM estiver ligado.",--Just a heads up: the type of security they use for the server room will make it harder to open if there's an active ECM jammer nearby.
	pln_fish_27_03 = "Nós conseguimos!",--We got it!
	pln_fish_05_01 = "Agora coloquem a senha.",--Now enter the password.
	pln_fish_33_01 = "Vocês podem jogar os corpos no mar atrás do barco.",--You can throw bodies into the sea over the railing at the back of the boat.
	pln_fish_21_01 = "Vocês vão ter que sobreaquecer o sistema secundário. Desligar o sistema de resfriamento deverá funcionar.",--You'll need to overheat the secondary servers. Turning off the flow of coolant should do it.
	pln_fish_32_03 = "Usem as janelas para jogarem os corpos fora. O mar vai devorá-los.",--Use the windows to get rid of any bodies. The sea will swallow them.
	pln_fish_13_03 = "Vocês podem assegurar as bolsas no barco em que viemos.",--You can secure the bags down in the motorboat.
	pln_fish_24_01 = "Ótimo, agora eu devo conseguir sobrepor o painel principal.",--Great, now I should be able to override the main panel.
	pln_fish_01a_01 = "Wow, esse barco é caro. Esse Powell tem mesmo dinheiro, hein.",--Wow, this boat is expensive. This Powell guy's got money.
	pln_fish_01a_02 = "Heh, eu me pergunto se esse barco vale mais do que o que está escondido nele.",--Heh, I wonder if this boat is worth more than what's hidden on it.
	pln_fish_01a_03 = "Esse amigo do McKendrick, tem mesmo um baita de um brilho, pelo que parece.",--This friend of McKendrick's sure has the bling, by the looks of it.
	pln_fish_01b_01 = "Agora procurem no barco, mas tenham cuidado.",--Now search the boat, but be careful.
	pln_fish_03_03 = "Já encontraram o laptop?",--You find that laptop yet?
	pln_fish_03_06 = "Pessoal, o laptop. Já conseguiram encontrar?",--Guys, the laptop. Did you find it yet?
	pln_fish_03_07 = "O laptop deve estar em algum lugar. Encontrem-o",--The laptop must be there somewhere. Find it!
	pln_fish_04_03 = "Ok, esse é o laptop. Bom trabalho!",--Ok, that's the laptop. Good job!
	pln_fish_06_01 = "Esse é o ouro. Tem todas as localizações do dinheiro escondido.",--This is gold. It's got all the locations of the hidden cash.
	pln_fish_09_01 = "Esse é o segundo amontoado, mais dois para irmos!",--That's the second stash. Two to go!
	pln_fish_09_03 = "Dois já foram, precisamos de mais dois!",--Two down, two to go!
	pln_fish_12_01 = "Joguem as bolsas no mar. Vocês podem buscar quando forem embora.",--Throw the bags into the sea. You can pick them up when you leave.
	pln_fish_12_03 = "Joguem as bolsas no lado. Vocês podem pescar elas da água quando forem embora.",--Throw the bags over the side. You can fish them out of the water when you get out of there.
	pln_fish_20_01 = "Vocês vão ter que sobreaquecer o sistema para causar um reboot e ganhar acesso aos controles. E então vamos pegar esse servidor.",--You'll have to overheat the system to cause a soft reboot and gain access to the controls. Then we should be able to get that server.
	pln_fish_22_01 = "Desliguem as válvulas em baixo da Sala do Servidor.",--Turn off the valves at the bottom of the server rack.
	pln_fish_23_02 = "Bom trabalho, agora vejam eles sobreaquecendo. Vocês vão ter o reboot do sistema.",--Good work, now watch 'em overheat. You'll get that system reboot.
	pln_fish_23_03 = "Vejam o calor aumentar. Vocês vão conseguir o reboot.",--Watch the heat rise. You'll get that reboot.
	pln_fish_27_01 = "Vamos lá. Dinheiro na caixa!",--There we go. Money in a box!
	pln_fish_28_01 = "Vocês podem fugir agora, ou procurar por mais alguns itens valiosos. A escolha é de vocês.",--You can escape now, or maybe look for more valuables. Your choice.
	pln_fish_30_03 = "A Sala do Servidor está trancada. Não podemos entrar mais agora!",--The server room is in security lockdown. We can't access it now!
	pln_fish_34_01 = "Olhem isso. Muita gente rica por aqui, aproveitando a vida da melhor forma.",--Look at that. A lot of rich people up there, enjoying themselves.
	pln_fish_37_01 = "Essa é provavelmente a Sala do Servidor. Lembrem-se disso.",--That's probably the server room. Remember where it is.
	pln_fish_end_02 = "Me pergunto se o McKendrick irá descobrir quem fez isso. De qualquer jeito, ele não deveria mexer com a gente nunca.",--I wonder if McKendrick will ever figure out who did this. In any case, he shouldn't have messed with us.
	
	-- Objetivos
	--hud_heist_fish_10_hl = "xxx",--xxx
	hud_heist_fish_05 = "Desça até o fundo do Iate e ganhe acesso ao servidores.",--Head down to the bottom of the yacht and gain access to the server room
	hud_heist_fish_01_hl = "Hackeie o Laptop",--Hack the Laptop
	hud_heist_fish_05_hl = "Ganhe Acesso à Sala do Servidor",--Gain access to the server room
	hud_heist_fish_01 = "Use as senhas que o Charon nos deu para hackear o manifesto.",--Use the passwords Charon gave you and hack into the manifest.
	hud_heist_fish_06_hl = "Sobreaqueça os Servidores",--Overheat the Servers
	--hud_heist_fish_10 = "xxx",--xxx
	--hud_heist_fish_03_hl = "xxx",--xxx
	hud_heist_fish_08_hl = "Roube o Disco Rígido",--Steal the Hard drive
	hud_heist_fish_07 = "Use os botões para forçar os servidores a abrir.",--Use the override switches to force the main server open.
	hud_heist_fish_11 = "Eu vi alguns artefatos dando sopa por aí, temos sempre mais espaço para mais loot.",--I saw a few artifacts lying about, there's always more room for extra loot.
	hud_heist_fish_08 = "A porta principal dos servidores está aberta, roube o HD!",--The main server doors are now open, steal the hard drive!
	hud_heist_fish_02_hl = "Assegure o Dinheiro",--Secure Money Bundles
	hud_heist_fish_12_hl = "Fuja",--Escape
	hud_heist_fish_02 = "Usando a informação do manifesto, encontre os amontoados de dinheiro escondidos e assegure-os.",--Using info provided on the manifest, find the stashed away money bundles and secure them.
	--hud_heist_fish_09_hl = "xxx",--xxx
	hud_heist_fish_07_hl = "Use os Botões",--Use Override Switches
	--hud_heist_fish_09 = "xxx",--xxx
	hud_heist_fish_11_hl = "Assegure Loot Adicional ou Fuja",--Secure additional loot or Escape
	hud_heist_fish_04_hl = "Hackeie a porta da Sala do Servidor",--Hack the server room open
	hud_heist_fish_04 = "Usando o laptop, hackeie a porta da Sala do Servidor.",--Using the laptop, hack open the server room doors
	--hud_heist_fish_03 = "xxx",--xxx
	hud_heist_fish_06 = "Desative o sistema de refrigeramento do servidores. Isso deverá sobreaquecer eles.",--Turn off all coolent systems for the servers. That should overheat them.
	hud_heist_fish_12 = "Parece que limpamos o barco, é hora de fugir.",--Looks like we've cleaned the boat empty, time to escape.
		}