return {
	-- Nomes e Descrições
	--heist_dah = "Diamond Heist",--Diamond Heist
	--heist_dah_hl = "Diamond Heist",--Diamond Heist
	heist_dah_crimenet = "O Edifício Garnet Group abriga um cofre contendo milhões de dólares em diamantes. Também está cheio de sistemas de segurança de alta tecnologia e guardas bem espertos; Sorte a nossa, há uma festa de aniversário ocorrendo para mantê-los distraídos.$NL;$NL;» Encontre e Anule duas Caixas de Roteador para que o Bain possa Hackear o Sistema de Segurança$NL;» Encontre três Laptops e Adquira todas as peças do Código de Segurança$NL;» Pegue o Cartão de Acesso do filho do CEO$NL;» Abra o Cofre e Roube os Diamantes",--The Garnet Group Building houses a vault containing millions of dollars in diamonds. It's also full of high-tech security systems and trigger-happy guards; luckily for us there's a birthday party going on to keep them distracted.$NL;$NL;» Find and override two router boxes so that Bain can hack the security system$NL;» Find three laptops and acquire all pieces of the security code$NL;» Get the keycard from the CEOs son$NL;» Open the vault and steal the diamonds
	heist_dah_briefing = "Ok, escutem. Para entrar nesse cofre, vocês precisam passar do sistema de segurança. O Informante diz que Ralph, filho do Garnet, tem o Cartão de Acesso para isso, mas ele também é o aniversariante, então isso pode ser um problema. Também há um código de segurança de terceiros divididos em laptops diferentes porque alguém disse a eles que seria mais seguro. Seria ótimo se vocês pudessem colocar as mãos no Cartão de Acesso e no código sem disparar nenhum alarme, talvez lance uma silenciosa no Sr. Garnet.",--Ok, listen up. To get inside that vault you need to get by the security system. Intel says that Garnet's son Ralph has the key card for it, but he also happens to be the birthday boy so that could be a problem. There's also a three-part security code split up onto different laptops because someone told 'em it would be safer. It'd be great if you could get our hands on both the key card and code without raising any alarms, maybe pull a silent fast one on Mr. Garnet.
	
	-- Legendas
	pln_dah_intro_01 = "Certo, ponto de entrada. Sincronizem na minha marca... marca.",--All right, entry point. Synchronize on my mark... mark.
	pln_dah_intro_02 = "19... 20... 21... Todo esse dinheiro e Garnet é muito pão-duro para pagar um equipamento de lavagem de janela mais rápido! Ok é isso, 22º andar e... pronto.",--19... 20... 21... All that money and Garnet is too cheap to pay for a faster window washing rig! Ok that's it, 22nd floor and... go.
	pln_dah_intro_03 = "Certo, vocês estão quase no 22º andar. Continuem e não fiquem com nariz sangrando aí em cima.",--All right, you're almost on the 22nd. Get going and don't get a nose-bleed up there.
	pln_dah_79_02 = "Não vai demorar muito para pressionarem esse cara pelo código. Aguentem firme.",--Won't take long to squeeze this guy for the code. Hang tight.
	pln_dah_22_03 = "Há algo eletrônico e brilhante no Escritório da Administração.",--There's something electronic and glowing in the Admin Office.
	pln_dah_cbf_01 = "No 22º andar do edifício Garnet Group, propriedade de Nathan Garnet, há um cofre com diamantes que custam milhões. O edifício tem uma segurança de alta tecnologia e guardas alertas, mas sorte a nossa, tem uma festa de aniversário acontecendo para mantê-los distraídos.",--On the 22nd floor of the Garnet Group Building, owned by Nathan Garnet, there's a safe with millions worth of diamonds. The building has high-tech security and trigger-happy guards but luckily for us there's a birthday party going on to keep them distracted. 
	pln_dah_115_01 = "Acabei de ver o Ralph, vão pegá-lo!",--I just saw Ralph, go get him!
	pln_dah_68_02 = "Malditos policiais estão tentando cortar a energia das caixas de roteadores, detenham eles.",--Damn cops are trying to cut power to the router boxes! Stop them!
	pln_dah_104_02 = "Helicóptero está de volta, pessoal!",--Chopper is back guys! 
	pln_dah_31_03 = "As Salas de Reunião são uma boa aposta para encontrar um desses laptops.",--Meeting Rooms are a good bet for finding one of those laptops.
	pln_dah_36_06 = "Talvez se vocês assobiarem, o Ralph apareça.",--Maybe if you dog-whistle, Ralph will come out.
	pln_dah_82_01 = "Zero",--Zero
	pln_dah_27_01 = "Passe pelo Canteiro de Obras. Eles devem ter um laptop lá.",--Go by the construction site. They must have a laptop there.
	pln_dah_98_03 = "Peguem aquele diamante vermelho e será um pagamento duplo.",--Get that red diamond and this'll be a double payday.
	pln_dah_111_03 = "Continuem em silêncio. Não sejam vistos.",--Keep it quite. Don't get spotted.
	pln_dah_96_03 = "Mais de um cofre? Não esperava por essa.",--More than one vault? Didnt' see that one coming.
	pln_dah_49_06 = "Vocês estão arrumando essas coisas?",--You getting those things stowed?
	pln_dah_20_01 = "Encontrem o PC no Quarto Glitter, mas não parem para dançar.",--Go find the PC in the Quarto Glitter, but don't stop to dance.
	pln_dah_116_01 = "O CFO ainda está lá. Mantenham seus olhos abertos.",--The CFO is still there. Keep your eyes open.
	pln_dah_96_02 = "Um segundo cofre?",--A second vault?
	pln_dah_end_stealth_01 = "Muito bem, gangue. Um roubo clássico.",--Nicely done gang. A classic heist!
	pln_dah_102_01 = "Metade do caminho, pessoal, continuem!",--Halfway there guys, keep going!
	pln_dah_94_02 = "Se preparem para roubar!",--Be ready for a smash-and-grab!
	pln_dah_21_02 = "Há uma luz brilhando do lado de fora do Quarto Glitter, parece um monitor.",--There's a light shining outside the Quarto Glitter, looks like a monitor.
	pln_dah_end_stealth_02 = "Bom trabalho em manter tudo quieto. Quase vale a pena gritar dos telhados. ",--Great job keeping it quiet everyone. Almost worth shouting from the rooftops.
	pln_dah_49_08 = "Ensaquem e assegurem. Vocês já sabem como funciona.",--Bag and secure. You know the routine.
	pln_dah_29_02 = "Procurem um PC no Escritório de Vendas.",--Look in the Sales office for a PC.
	pln_dah_92_08 = "Não ferrem com tudo. O código é...",--Don't screw this up. The code's...
	pln_dah_26_01 = "O Escritório da Tiffany tem mais do que café da manhã, ao que parece. Um monitor LCD brilhante.",--The Tiffany Room has more than breakfast it seems. A glowing LCD monitor.
	pln_dah_49_02 = "Peguem essas pedras.",--Get those stones. 
	pln_dah_111_01 = "Fiquem escondidos até que eles saiam.",--Keep low until they've cleared out.
	pln_dah_59_02 = "OK, esqueçam de ficar escondido e quietos. Dê-me um momento para pensar em algo.",--OK, forget about staying low and quiet. Gimme a moment to think of something.
	pln_dah_30_02 = "O Escritório da Amber parece ter um laptop.",--The Amber room looks like it has a laptop.
	pln_dah_100_02 = "Ensaquem os diamantes e tragam eles para o jardim para extração na tirolesa.",--Bag the diamonds and bring them to the garden for tirolesa extraction.
	pln_dah_106_03 = "Bom trabalho, pessoal. Podem sinalizar para o helicóptero no telhado quando estiverem prontos.",--Great job guys, You can signal the chopper on the roof whenever you're ready.
	pln_dah_33_03 = "Segunda cor e número? Otimo!",--Second color and number? Great!
	pln_dah_10_02 = "Ambos os roteadores hackeados. Quase muito fácil.",--Both routers hacked. Almost too easy.
	pln_dah_12_06 = "Computadores portáteis. Vezes três.",--Portable computers. Times three.
	pln_dah_24_03 = "Há algo brilhando no Escritório da Velvet mas não é o fantasma do Elvis. Parece um laptop.",--There's something glowing in the Velvet Room but it's not the ghost of Elvis. More likely a laptop.
	pln_dah_78_01 = "Helicóptero chegando.",--Chopper coming in.
	pln_dah_03_03 = "Ei, vocês deveriam estar hackeando esses roteadores, lembram?",--Hey, you're supposed to be hacking those routers, remember?
	pln_dah_105_02 = "Só mais um e pronto!",--Just one more and you're done!
	pln_dah_109_04 = "O helicóptero não vai embora sem vocês.",--Chopper's not leaving without you.
	pln_dah_88_02 = "Seis",--Six
	pln_dah_40_06 = "Talvez vocês queiram pegar o ritmo. O Cartão de Acesso e o código são tudo que vocês precisam.",--Might want to pick up the pace gang.The keycard and code are all you need.
	pln_dah_68_03 = "Os policiais estão tentando nos ferrar. Certifiquem-se de que falhem.",--Blues are trying to pull the plug on us, make sure they fail!
	pln_dah_67_03 = "Perfeito! Agora me dê um segundo...",--Perfect! Now gimme a second...
	pln_dah_73_01 = "Precisamos do Cartão de Acesso do Ralph Garnet. Encontrem ele!",--We need Ralph Garnet's Keycard. Find him!
	pln_dah_end_loud_01 = "As coisas ficaram um pouco feias, mas vocês conseguiram completar o trabalho!",--Things got a little wild, but you got the job done!
	pln_dah_71_01 = "É isso, terminei!",--That's it, I'm done!
	pln_dah_39_03 = "Se vocês errarem a ordem do código, tudo isso vai pra casa do caralho.",--If you get the code order wrong, all hell will break loose.
	pln_dah_114_03 = "Vocês estão bloqueados. O sistema vai levar 30 segundos para reiniciar.",--You're locked out. The system is gonna take 30 seconds to reset.
	pln_dah_55_08 = "Vocês estão pensando em alugar um Escritório? Por quê a lerdeza?",--You looking to rent an office? What's the delay?
	pln_dah_51_01 = "Só mais uma bolsa.",--Just one more bag.
	pln_dah_92_04 = "Mais uma vez, o código é...",--Once more, the code is...
	pln_dah_46_02 = "É um pedaço brilhante de carbono.",--That's one shiny piece of carbon.
	pln_dah_17_02 = "Verifiquem se há um computador na cantina. Me traguem um cappucino enquanto estiverem lá.",--Check the cafeteria for a computer. Bring me a cappuccino while you're at it.
	pln_dah_65_01 = "Ei, pessoal, Eu não posso fazer nada até vocês encontrarem esses roteadores!",--Hey guys, I can't do anything until you find those routers!
	pln_dah_56_01 = "Eu posso transportar safiras também, se vocês pegarem alguma pelo caminho.",--I can move sapphires too, if you grab any along the way.
	pln_dah_75_01 = "O CFO tem o código mestre, pessoal. Encontrem-no!",--The CFO has the master code guys. Find him!
	pln_dah_33_01 = "Essa é a segunda cor e número.",--That's the second color and number.
	pln_dah_14_02 = "E mais uma.",--And another one.
	pln_dah_64_03 = "Continuem procurando por essas caixas de roteador, estou pensando em um Plano B.",--Keep looking for those router boxes, I'm working on a plan B.
	pln_dah_38_02 = "Vocês tem tudo necessário para abrir o cofre. Cartão de Acesso primeiro, então o código.",--You have everything to you need to open the vault. keycard first, then enter the code.
	pln_dah_71_03 = "E lá vamos nós!",--There we go!
	pln_dah_14_01 = "E aí vai a segunda.",--There's the second one.
	pln_dah_12_01 = "O código está divido em três laptops.",--The code is split onto three laptops.
	pln_dah_29_01 = "O pessoal de vendas sempre tem laptops.",--Sales-people always have laptops.
	pln_dah_12_02 = "Vocês precisam encontrar esses códigos.",--You need to find those code fragments.
	pln_dah_69_03 = "Eles estão tentando desligá-los!",--They're trying to shut them down!
	pln_dah_73_03 = "Ralph deve estar escondido em algum lugar. Encontrem-no e peguem o cartão!",--Ralph's got to be hiding somewhere. Find him and get that card!
	pln_dah_11_03 = "OK, que tal esses laptops?",--OK, now how about those laptops?
	pln_dah_108_01 = "Helicóptero a caminho! Tempo estimado de 2 minutos.",--Chopper is on the way! ETA 2 minutes.
	pln_dah_105_03 = "Quase lá!",--Almost there!
	pln_dah_55_04 = "O que vocês estão esperando?",--What are you waiting for?
	pln_dah_07_01 = "Enquanto isso, vejam como encontrar esses três laptops com os códigos.",--In the meantime, see about finding those three laptops with the code snippets. 
	pln_dah_26_02 = "Olhem fora do Escritório da Tiffany. Eu consigo ver uma tela de laptop no feed de segurança.",--Look outside the Tiffany Room. I can see a laptop display in the security feed.
	pln_dah_46_03 = "Da crosta terrestre às nossas contas bancárias. Maravilhoso.",--From the crust of the Earth to our bank accounts. Gorgeous.
	pln_dah_119_01 = "Se preparem para extração. Helicóptero a 4 minutos.",--Get ready for extraction. Chopper is 4 minutes out.
	pln_dah_34_01 = "Perfeito, foram todos.",--Perfect, that's all of them.
	pln_dah_91_02 = "Nove",--Nine
	pln_dah_19_02 = "Verifiquem fora do Escritório da Jade. Tem um monitor de PC lá.",--Check just outside the Jade Room. There's a PC monitor on there.
	pln_dah_30_03 = "Vale a pena checar no Escritório da Amber por um PC.",--Worth checking in the Amber Room for a PC.
	pln_dah_70_02 = "50%.",--50 percent done.
	pln_dah_76_03 = "Levem ele até o telhado e o coloquem no helicóptero. Eu vou fazê-lo falar.",--Bring him to the roof and put him on the chopper. I'll get him to sing.
	pln_dah_101_02 = "Vocês podem fazer isso mais rápido se usarem uma tirolesa.",--You can do it faster if you set up a tirolesa.
	pln_dah_63_01 = "Helicópteros da polícia na área!",--Cop choppers are inbound!
	pln_dah_63_02 = "Policiais a caminho em helicópteros, mantenham-se de olhos abertos!",--Blues are on the way in choppers so keep your eyes open!
	pln_dah_36_03 = "Assim que vocês pegarem o Cartão do Ralph, o pai dele vai renegá-lo.",--Once you get that card from Ralph, his dad's probably gonna disown him.
	pln_dah_69_01 = "Mantenham essas caixas de roteadores seguras.",--Keep those routers safe.
	pln_dah_27_02 = "Provavelmente há um laptop no Canteiro de Obras.",--There's probably a laptop at the contruction site.
	pln_dah_104_01 = "Ok, pessoal. Helicóptero está de volta então comecem a carregar novamente!",--Ok, guys. Chopper is back so get to loading again!
	pln_dah_06_01 = "Certo, dê-me um tempo para hackear o sistema.",--All right, give me some time to hack the system.
	pln_dah_90_01 = "Oito",--Eight
	pln_dah_70_01 = "Quase lá.",--Halfway there.
	pln_dah_109_07 = "O que vocês estão fazendo? Vão para o helicóptero!",--What're you still doing there? Get on the helicopter.
	pln_dah_41_03 = "Pronto! Quase livre.",--There you go! Almost home free.
	pln_dah_86_02 = "Quatro",--Four
	pln_dah_60_01 = "Vocês digitaram a sequência errada, agora o sistema está travado até vocês encontrarem o código mestre.",--That was the wrong sequence, now the system is locked unless you find the master code!
	pln_dah_79_01 = "Se preparem para o cofre. Eu vou ter o código para vocês em breve.",--Get ready for the vault. I'll have the code for you soon.
	pln_dah_01_01 = "Lembrem-se, continuem escondidos. E quietos. Lá vamos nós.",--Remember, stay low, stay dark. And stay quiet. Here we go.
	pln_dah_94_01 = "O cofre está abrindo, se preparem!",--Vault is opening. Get ready to move!
	pln_dah_62_01 = "OK, esqueçam a plataforma de lavagem de janela, vocês vão usar tirolesas para levar essas bolsas.",--OK, forget the window cleaning platform, you're going to have to use zipline to move the bags out!
	pln_dah_59_03 = "Não precisam ser furtivos mais. Novo plano chegando.",--No need to sneak around any longer. New plan incoming.
	pln_dah_59_01 = "Droga, não precisam mais ficarem quietos. Hora de um novo plano.",--Damn, no need to be quiet any longer. Time for a new plan.
	pln_dah_104_03 = "O helicóptero está de volta e esperando por mais bolsas!",--Chopper is back and waiting for more bags!
	pln_dah_19_01 = "Olhem fora do Escritório da Jade, parece um laptop.",--Look outside the Jade Room, looks like a laptop.
	pln_dah_56_03 = "Se vocês quiserem, peguem algumas safiras no caminho de saída.",--If you want, grab some sapphires on the way out.
	pln_dah_93_01 = "O Sr. CFO teve que dizer bye-bye. Pelo menos ele teve o privilégio de ver minha cara antes de partir.",--Mr. big-shot CFO had to go bye-bye. At least he had the priviledge of seeing my face before he went!
	pln_dah_99_03 = "Vocês vieram atrás dos que estão nas caixas, mas tudo ao redor é um bônus.",--You came for the ones in cases, but everything else is a bonus.
	pln_dah_72_03 = "Encontrem o Ralph Garnet e peguem o Cartão de Acesso daquele privilegiado.",--Go find Ralph Garnet and take that keycard from his priviledged-ass-self.
	pln_dah_82_02 = "Zero",--Zero
	pln_dah_05_01 = "Ótimo, agora vocês só precisam achar o segundo.",--Great, now you just need to find the second one.
	pln_dah_118_01 = "Segurem firme, rapazes. Chegando em 3 minutos.",--Hang on guys. Coming in. ETA 3 minutes
	pln_dah_77_02 = "CFO para o telhado, rápido!",--CFO to the roof, ASAP!
	pln_dah_15_01 = "Terceiro encontrado.",--Third one found.
	pln_dah_04_01 = "Um dos roteadores provavelmente está bem próximo.",--One of the routers is probably real close.
	pln_dah_96_01 = "Outro cofre?",--Another vault?
	pln_dah_23_01 = "Vocês provavelmente vão encontrar um PC no Escritório de relações públicas.",--You'll probably find a PC in the PR office. 
	pln_dah_106_01 = "É isso. Vão para o telhado e acendam um sinalizador para sinalizar a extração.",--That's it. Get up to the roof and light a flare to signal pickup. 
	pln_dah_80_01 = "Coloquem o Cartão do Ralph antes de colocarem o código.",--Swipe Ralph's card before entering the code.
	pln_dah_95_03 = "Tanto dinheiro em um pequeno espaço.",--So much value in such a small space.
	pln_dah_11_02 = "É hora de encontrar esses três laptops.",--It's high time to find those three laptops.
	pln_dah_36_02 = "O aniversariante Ralph provavelmente está escondido em algum lugar patético.",--Birthday boy Ralph is probably hiding somewhere pathetic.
	pln_dah_08_01 = "Quase terminando de hackear.",--Almost done hacking.
	pln_dah_112_02 = "Hmm, aquele computador tinha uma parte do código do cofre. Deve haver mais partes por aí.",--Hmm, that computer had a partial code to the vault. There must be more parts of it around there.
	pln_dah_99_01 = "As pedras nas caixas são de alta prioridade, mas peguem tudo o que vocês puderem.",--The stones in cases are top priority, but grab whatever else you can.
	pln_dah_31_02 = "Eu acho que vi um PC em uma das Salas de Reuniões através da câmera de segurança.",--I think I see a PC in one of the meeting rooms through the secruty camera. 
	pln_dah_84_02 = "Dois",--Two
	pln_dah_93_02 = "Bom, não fizemos nenhuma promessa sobre deixar ele viver após me ver.",--Well, we didn't make him any promises about letting him live after seeing me.
	pln_dah_98_02 = "Abram o segundo cofre e vocês terão um bônus bem suculento.",--Open that second vault and you'll get a juicy bonus.
	pln_dah_52_02 = "Isso é tudo de que precisamos. Vocês decidem se querem mais.",--That's all we need. Up to you if you want to go for more.
	pln_dah_69_02 = "Não deixem os policiais perto dos roteadores.",--Dont' let the cops near the routers.
	pln_dah_66_03 = "Só mais um para terminar.",--Just one more to go.
	pln_dah_55_07 = "Parem de brincar e saiam daí.",--Quit messing around and get out of there.
	pln_dah_06_03 = "Eu vou derrubar o sistema já.",--I'll have the system down in a bit.
	pln_dah_72_01 = "OK, agora vocês precisam do Cartão de Acesso. Encontrem nosso aniversariante Ralph, ele está provavelmente escondido em algum lugar!",--OK, now you need that keycard. Find our birthday boy Ralph, he's probably still hiding somewhere!
	pln_dah_51_02 = "Mais um e pronto.",--One more and you're done.
	pln_dah_03_04 = "Paredes e caixas de roteador. Eles andam juntos como problemas e emblemas.",--Walls and router boxes. They go together like trouble and badges.
	pln_dah_69_05 = "Mantenham eles longe dos roteadores.",--Keep them off the routers.
	pln_dah_32_01 = "Esse é um. Lembrem-se do número E da cor.",--That's one. Remember the number AND the color.
	pln_dah_13_03 = "Encontrei um laptop para vocês.",--Found a laptop for you guys.
	pln_dah_41_02 = "Perfeito, agora peguem essas pedras.",--Perfect, now grab those stones.
	pln_dah_01_03 = "Vamos manter esse sob o radar.",--Let's keep this one under the radar.
	pln_dah_24_02 = "O Escritório do Velvet. Procurem um PC o mais rápido possível.",--The Velvet Room. Search it for a PC ASAP.
	pln_dah_02_03 = "Duas caixas de roteador montadas na parede controlam o sistema de segurança do cofre e cada uma precisa ser hackeada separadamente. Assim que vocês entrarem, posso fazer o resto e desligar o sistema daqui.",--Two wall-mounted router boxes control the vault security system and each one needs to be hacked separately. Once you're in, I can do the rest and shut down the system from here.
	pln_dah_36_05 = "Eu não posso fazer mais nada até vocês encontrarem aquele Cartão de Acesso.",--I can't do any more until you find that keycard.
	pln_dah_92_07 = "Esqueceram do código? É...",--Forget the code? It's...
	pln_dah_16_03 = "Vão até a Academia, vocês devem encontrar um computador lá.",--Go by the fitness center, you should find a computer there.
	pln_dah_39_01 = "Coloquem o código errado e o alarme vai disparar, então sejam cuidadosos!",--Enter the wrong code and the alarm goes off, so be careful!
	pln_dah_114_01 = "Vocês colocaram o código errado! Sistema está travado por 30 segundos.",--You got the code wrong guys! System is locked for 30 seconds.
	pln_dah_113_02 = "Ei, ótimo. Vocês encontraram o Cartão de Acesso antes do previsto.",--Hey, great. You found the keycard ahead of schedule.
	pln_dah_38_03 = "Vão para o cofre e abram aquele bebê com o Cartão de Acesso e o código.",--Head for the vault and open that baby up with the keycard and code.
	pln_dah_08_02 = "Não deve demorar muito.",--Shouldn't be too much longer.
	pln_dah_72_02 = "OK gangue, hora de encontrar aquele Cartão de Acesso. O aniversariante provavelmente ainda está por aí, então encontrem-o!",--OK gang, time to find that keycard. Birthday Boy is probably still around, so go find him!
	pln_dah_109_05 = "Parem de brincar e subam a bordo.",--Stop messing around and get on board.
	pln_dah_42_02 = "Usem um Cortador de Vidro. E Não quebrem o vidro!",--Use a glass-cutter. Don't break the glass!
	pln_dah_112_01 = "Esse laptop tinha uma parte do código do cofre. Há mais dois por aí em algum lugar.",--That laptop had one part of the vault code. There are two more around there somewhere.
	pln_dah_end_loud_02 = "Não foi perfeito, mas quem se importa quando tudo dá certo no fim?",--Not exactly textbook perfection, but who cares when it all works out! 
	pln_dah_39_02 = "Não coloquem o código errado ou o alarme vai disparar!",--Don't get the code wrong or the alarm will go off.
	pln_dah_78_03 = "Helicóptero na área. Preparem-se!",--Chopper is inbound. Stand by!
	pln_dah_46_01 = "Isso provavelmente vale uma pequena fortuna.",--That's probably worth a small fortune.
	pln_dah_63_03 = "Ei gangue, vocês têm problemas vindo de helicóptero.",--Hey gang, you got trouble comin' by helicopter.
	pln_dah_65_06 = "O que há, pessoal? Encontrem esses roteadores!",--What's up guys? Find those routers!
	pln_dah_81_03 = "Estou com o código para vocês...",--Got the code for you...
	pln_dah_101_01 = "Preparem uma tirolesa para acelerar as coisas",--Set up a tirolesa to speed things up.
	pln_dah_18_02 = "Olhem o Escritório da Jade por um dos PCs.",--Take a look in the Jade Room for one of the PCs.
	pln_dah_53_03 = "Nada mais nos resta fazer.",--Nothing left to do but make like tree...
	pln_dah_54_02 = "De volta para a plataforma que vocês vieram.",--Back to the platform where you came in.
	pln_dah_21_03 = "Procurem fora do Quarto Glitter por um dos PCs.",--Look right outside the Quarto Glitter for one of the PCs. 
	pln_dah_86_01 = "Quatro",--Four
	pln_dah_61_01 = "Aí vai o alarme!",--There goes the alarm!
	pln_dah_115_03 = "Ei, Ralph ainda está aí. Estejam prontos para pegá-lo.",--Hey, Ralph is still there. Be ready to grab him.
	pln_dah_97_02 = "Bom, isso provavelmente vale muito.",--Well now, it's probably worth a hell of a lot.
	pln_dah_41_01 = "Bom trabalho, agora vamos ver aquele carbono brilhante.",--Great work, now let's see that glittering carbon.
	pln_dah_66_02 = "Foi um, encontrem o próximo!",--That's one, find the next!
	pln_dah_91_01 = "Nove",--Nine
	pln_dah_30_01 = "Passem pelo Escritório da Amber quando tiverem a chance e dê uma olhada no laptop.",--Pass by the Amber Room when you get a chance and have a look at the computer there.
	pln_dah_77_04 = "Vocês precisam se apressar.",--You need to hurry guys.
	pln_dah_47_03 = "Tentem abrir o segundo cofre se conseguirem.",--Try to get that second vault open if you can.
	pln_dah_84_01 = "Dois",--Two
	pln_dah_102_02 = "Metade deles carregados.",--Half of them loaded.
	pln_dah_35_02 = "Quase pronto. Tudo o que vocês precisam fazer agora é conseguir o Cartão de Acesso de Ralph Garnet. Encontrem-no e peguem.",--Almost done. All you gotta do now is get hold of the keycard from Ralph Garnet. Find him and get it.
	pln_dah_102_03 = "Está quase na metade.",--That's about halfway done.
	pln_dah_113_01 = "Não percam esse Cartão de Acesso, vocês vão precisar dele mais tarde.",--Don't loose that keycard, you're gonna need it later.
	pln_dah_117_01 = "Vocês têm as coordenadas - vão.",--You got the coordinates - go.
	pln_dah_50_03 = "Continuem. Bom trabalho até agora.",--Keep going. Good job so far.
	pln_dah_26_03 = "Ei, vocês deveriam ir para o Escritório da Tiffany, eu acabei de ver um PC no feed de segurança.",--Hey guys, you should run by the Tiffany Room, I just saw a PC in the security feed.
	pln_dah_15_03 = "O último está lá.",--Last one is there.
	pln_dah_48_03 = "Viemos para os casos, mas todo o resto é bom.",--We came for the ones in cases, but everything else is gravy.
	pln_dah_54_01 = "Vão para a plataforma.",--Get to the platform.
	pln_dah_44_02 = "Levem as bolsas para a plataforma.",--Get the bags to the platform.
	pln_dah_94_03 = "Muito bem! Agora peguem essas joias!",--There you go! Now get those gems!
	pln_dah_53_02 = "É hora de fazer uma retirada rápida, pessoal.",--Time to make a hasty retreat guys.
	pln_dah_25_01 = "Procurem um PC fora do Escritório da Velvet.",--Check outside the Velvet Room for a PC.
	pln_dah_74_02 = "OK, encontrem o CFO. Eles possuem o código mestre!",--OK, find the CFO. He's got the master code!
	pln_dah_60_03 = "Vocês colocaram errado, agora temos que encontrar o código mestre de alguma forma.",--You got it wrong, now we have to find the master code somehow.
	pln_dah_62_02 = "Mudança de planos! Vocês vão usar tirolesas para assegurar as bolsas!",--Change of plan! You have to use zipline instead to secure the bags!
	pln_dah_62_03 = "Não vai dar para usar a plataforma de limpeza de janela. Usem a tirolesa para assegurar as bolsas.",--The window cleaning platform is a no-go. Use zipline to get the bags out instead. 
	pln_dah_05_02 = "Uma caixa a menos, falta uma.",--That's one box down, one to go.
	pln_dah_end_loud_03 = "Foi tudo na adrenalina, mas com sucesso. Muito bem, pessoal.",--It was loud, but it was succesful. Outstanding people.
	pln_dah_10_01 = "Certo, o sistema foi hackeado.",--All right, system has been hacked.
	pln_dah_61_03 = "Alarme está ativado. Eles sabem que estão aí agora.",--Alarm is active. They know you're there now.
	pln_dah_37_03 = "Aquele Cartão de Acesso é uma coisa a menos que precisamos encontrar.",--That keycard is one less thing we need to find.
	pln_dah_57_01 = "Droga! Eles travaram o código. Precisamos de um plano de backup.",--Damn! They locked out the code. Need a backup plan.
	pln_dah_15_02 = "Foram todas.",--That's all of them.
	pln_dah_20_03 = "Vão olhar o Quarto Glitter, há um computador lá.",--Take a loot in the Quarto Glitter, there's a computer in there.
	pln_dah_40_03 = "Eu não posso fazer isso pra vocês, pessoal. Cartão de Acesso e código, naquela ordem.",--I can't do it for you people. keycard and code, in that order.
	pln_dah_45_02 = "Espera... um outro cofre?",--Wait... another vault?
	pln_dah_109_03 = "Hora de se mover!",--Time to move!
	pln_dah_120_03 = "Sinalizem ao helicóptero no telhado quando estiverem prontos.",--Signal the chopper on the roof whenever you're ready.
	pln_dah_49_01 = "Coloquem essas gemas na bolsa.",--Bag those gems.
	pln_dah_97_03 = "Isso vai valer muito.",--It's gotta be worth a lot.
	pln_dah_07_02 = "Enquanto hackeio o sistema, vocês deviam procurar essas partes do código. Lembrem-se, um por laptop.",--While I'm hacking the system, you should go ahead and find those code parts. Remember, one per laptop.
	pln_dah_23_03 = "Relações públicas seria um bom lugar para procurar por computadores.",--Public Relations would be a good place to search for computers.
	pln_dah_16_01 = "Talvez queiram dar uma olhada na Academia. Eu vi algo brilhando ali.",--Might want to look in the fitness center. I saw something glowing there.
	pln_dah_50_01 = "Já foi metade.",--That's half of 'em.
	pln_dah_32_03 = "OK, ótimo. Lembrem-se do número e cor.",--OK, great. Rember both the number and color.
	pln_dah_12_03 = "Computadores portáteis... três deles.",--Portable computers... three of them.
	pln_dah_36_01 = "Continue procurando por Ralph.",--Keep looking for Ralph.
	pln_dah_57_02 = "O código foi bloqueado, então esqueçam. Vamos precisar de outra solução.",--The code has been blocked, so forget about it. Going to need another solution.
	pln_dah_50_02 = "Continuem.",--Keep at it.
	pln_dah_49_03 = "Como estão indo?",--How are you coming along?
	pln_dah_09_01 = "Primeiro roteador foi hackeado.",--First router has been hacked.
	pln_dah_58_01 = "O código que vocês têm foi desabilitado, mas acho que o sistema tem um código mestre. Deixe-me fazer algumas pesquisas.",--The code you have has been disabled, but I think the system has a master code. Let me do some digging.
	pln_dah_37_02 = "Ei, ótimo. Vocês encontraram o Cartão de Acesso antes do previsto.",--Hey, great. You found the keycard ahead of schedule.
	pln_dah_10_03 = "É isso, caixas de roteador devidamente cuidadas.",--That's it, router boxes taken care of. 
	pln_dah_37_01 = "Não percam o Cartão de Acesso, vocês vão precisar dele mais tarde.",--Don't loose that keycard, you're gonna need it later.
	pln_dah_93_03 = "Bom, é isso. Ele olhou pra mim, então eu tive que... deixar ele ir.",--Well, that's that. He got a look at me, so I had to... let him go.
	pln_dah_44_03 = "Vão para a plataforma com as bolsas!",--Get to the platorm with the bags!
	pln_dah_120_01 = "Vão para o telhado e acendam um sinalizador para a extração.",--Get up to the roof and light a flare to signal pickup.
	pln_dah_43_03 = "Vocês precisam levar as bolsas de volta para a plataforma de lavagem de janelas.",--You need to get the bags back to the window-washing rig.
	pln_dah_38_01 = "OK é isso. Vão até o cofre e o abram com o Cartão de Acesso e o código.",--OK, that's it. Get to the vault and open it with the keycard and code.
	pln_dah_13_01 = "Parece que encontrei uma para vocês.",--Looks like I found one for you.
	pln_dah_70_03 = "Não muito agora.",--No too long now.
	pln_dah_09_03 = "Terminei a primeira caixa.",--I'm done with the first box.
	pln_dah_107_03 = ".. ou fiquem, se estão se sentindo gananciosos.",--.. or stay, if you're feeling greedy.
	pln_dah_49_04 = "Continuem trabalhando, pessoal.",--Keep working guys.
	pln_dah_114_02 = "Droga, o sistema está travado. Vocês têm que esperar 30 segundos até que possam tentar novamente.",--Damn, the system is locked. You have to wait 30 seconds until you can try again.
	pln_dah_18_03 = "Eu acho que há algo no Escritório da Jade.",--I think there's something in the Jade Room.
	pln_dah_04_02 = "Caixa de segurança logo à frente. Mantenham seus olhos abertos.",--Security box up head. Keep your eyes peeled.
	pln_dah_92_06 = "Mais uma vez.",--One more time
	pln_dah_88_01 = "Seis",--Six
	pln_dah_55_06 = "Hora de sair, gangue.",--Time to pull out gang.
	pln_dah_113_03 = "Esse Cartão de Acesso é uma coisa a menos que precisamos para abrir o cofre.",--That keycard is one less thing we need to open the vault.
	pln_dah_25_02 = "Fora do Escritório da Velvet, eu vejo uma tela brilhante. Vão lá ver o que é.",--Outside the Velvet Room, I see a lit display screen. Go have a look.
	pln_dah_14_03 = "Ah, tem um também.",--Ah, there's one too.
	pln_dah_08_03 = "Só um pouco mais.",--Just a little longer.
	pln_dah_116_02 = "Acabei de ver o CFO pelo feed de câmera, ele ainda está aí, bem perto.",--I just saw the CFO through a camera feed, he's still there, neaby.
	pln_dah_100_01 = "Ensacolem essas pedras e leve-as para o jardim. Usem a tirolesa.",--Bag those stones and get them to the garden. Get them out with zipline.
	pln_dah_112_03 = "OK, aquele computador tinha um pedaço do código para o cofre, mas para poder usá-lo, vocês precisam das outras partes também. Elas provavelmente estão por aí em algum lugar.",--OK, that computer had a piece of code to the vault on it, but to be able to use it, you need the other parts as well. They're probably around there somewhere. 
	pln_dah_66_01 = "Um roteador a menos!",--One router down!
	pln_dah_40_05 = "A que distância vocês estão do cofre? Usem o cartão primeiro e depois insiram o código.",--How far along are you on the vault? Use the card first, then enter the code.
	pln_dah_25_03 = "Deve haver algo no Escritório da Velvet. Há um monitor ligado.",--Should be something just by the Velvet Room. There's a monitor on.
	pln_dah_95_01 = "Várias pedras.",--That's a lot of stones.
	pln_dah_81_01 = "Certo, o código é...",--All right, the code is...
	pln_dah_69_07 = "Mantenham os policiais longe dos roteadores!",--Keep the cops away from the routers! 
	pln_dah_21_01 = "Há algo lá. Fora do Quarto Glitter.",--Something there. Right outside the Quarto Glitter.
	pln_dah_24_01 = "Vão procurar um laptop no Escritório da Velvet. Só não grude nas paredes.",--Go check the Velvet Room for a laptop. Just don't stick to the walls.
	pln_dah_103_01 = "As coisas estão ficando feias, preciso tirar o helicóptero até que tudo se acalme.",--Things are getting too hot, I have to pull the chopper out until it calms down.
	pln_dah_60_02 = "Que merda que aconteceu? Código errado? Vocês vão precisar do código mestre agora.",--What the hell happened? Wrong code? You're going to need the master code now.
	pln_dah_40_04 = "O cofre não vai sair do lugar. Está esperando pelo Cartão de Acesso e o código.",--The vault isn't going anywhere. It's waiting for tha keycard and code.
	pln_dah_02_01 = "Para contornar o sistema de segurança e entrar no cofre, apliquem um patch nos dispositivos que vocês possuem diretamente nas duas caixas de controle, elas devem estar por aí em algum lugar. Então, vou hackear remotamente e fazer o resto.",--To bypass the security system and get into the vault, patch the devices you have directly into the two control boxes, they should be around there somewhere. Then I'll hack in remotely and do the rest. 
	pln_dah_44_01 = "Assegurem as bolsas na plataforma por onde vocês entraram.",--Secure the bags on the plaform where you came in.
	pln_dah_18_01 = "Procure no Escritório da Jade, vi um monitor brilhante lá.",--Search the Jade Room, I saw a glowing monitor there.
	pln_dah_76_02 = "Ele está mentindo, eu mesmo vou cuidar dele. Tragam-no para o helicóptero no telhado!",--He's lying, I'll take care of him myself. Bring him to the chopper on the roof!
	pln_dah_65_04 = "Ainda esperando nesses roteadores.",--Still waiting on those routers.
	pln_dah_22_02 = "Dêem uma olhada no Escritório de Administração, deve haver um PC lá.",--Have a look in the Admin Office, there's bound to be a PC there.
	pln_dah_69_04 = "Parem os policiais.",--Stop the cops!
	pln_dah_31_01 = "As pessoas sempre esquecem seus computadores nas Salas de Reuniões. Vão ver se vocês conseguem ter um pouco mais de sorte lá.",--People always forget computers in Meeting Rooms. Go see if you can get lucky there.
	pln_dah_65_02 = "Não há tempo para parar e festejar, encontrem esses roteadores agora!",--No time to stop and party, find those routers ASAP!
	pln_dah_87_02 = "Cinco",--Five
	pln_dah_116_03 = "O CFO acha que é inteligente e que vai escapar, mas eu vejo ele.",--The CFO thinks he's clever and that he can get away, but I see him.
	pln_dah_13_02 = "Posso ver um laptop em uma das câmeras.",--I can see a laptop in one of the cameras.
	pln_dah_cnc_01 = "Ok gangue, parece que estamos atrás de uns diamantes.",--Ok gang, looks like we're going after some diamonds.
	pln_dah_110_02 = "A festa pode ter acabado. Várias pessoas saindo.",--Party might be over. Lots of people leaving.
	pln_dah_36_04 = "Continuem procurando. Ele está por aí em algum lugar.",--Keep looking. He's around there somewhere.
	pln_dah_45_03 = "Outro cofre. Não esperava por essa.",--Another vault. Didn't expect that.
	pln_dah_28_03 = "A Gerência seria um bom lugar para procurar um laptop.",--Management would be a good place to look for a laptop.
	pln_dah_75_02 = "Vocês precisam encontrar o CFO. Ele tem o código mestre. Vocês *precisam* do código mestre.",--You need to find the CFO. He's got the master code. You *need* the master code.
	pln_dah_03_02 = "Bora pessoal, encontrem essas caixas de roteador. Procurem pelas paredes.",--C'mon guys, find me those security boxes. Check the walls.
	pln_dah_64_01 = "Vocês ainda precisam passar pela segurança, então achem esses dois roteadores!",--You still need to bypass security, so find those two routers!
	pln_dah_07_03 = "Enquanto estou fazendo isso, vocês devem ir em frente e encontrar os três laptops com as partes do código.",--While I'm doing this, you should go ahead and find those three laptops with the code fragments.
	pln_dah_54_03 = "Fora daí, rapazes. Pela plataforma.",--Out of there guys, via the platform.
	pln_dah_56_02 = "Peguem algumas safiras se tiverem tempo.",--Grab some sapphires if you have time.
	pln_dah_111_02 = "Apenas deixe-os ir quietos.",--Just let them go quietly.
	pln_dah_106_02 = "Tudo terminado. Vão para o telhado e sinalizem ao helicóptero se vocês estiverem prontos pra fugir.",--You're all done. Get to the roof and signal the chopper if you're ready to leave!
	pln_dah_23_02 = "Eles tem um Escritório de Relações públicas aqui. Talvez a gente deveria ter uma dessas. Provavelmente tem um laptop.",--They've got a PR office here. Maybe we should have one of those. They probably have a laptop. 
	pln_dah_01_02 = "Vocês são gatos se escondendo de cachorros. Estúpidos, e ricos.",--You're cats hiding from dogs. Stupid, rich ones. 
	pln_dah_03_05 = "Eu realmente preciso que vocês comecem a hackear as caixas de segurança.",--I really need you to hack me into those security boxes ASAP.
	pln_dah_34_02 = "Vocês já possuem todas as partes do código agora.",--You now have all parts of the code.
	pln_dah_92_03 = "Me deixe repetir",--Let me repeat
	pln_dah_49_07 = "Ei, pessoal, qual é o seu status?",--Hey guys, what's your status?
	pln_dah_04_03 = "Há uma caixa de roteador próximo a vocês.",--There's a router box right near you.
	pln_dah_69_06 = "Protejam os roteadores",--Protect the routers.
	pln_dah_77_03 = "Se apressem, gangue.",--Need to hurry gang.
	pln_dah_92_01 = "Repetindo, o código é...",--Repeat, the code is...
	pln_dah_78_02 = "Helicóptero está quase aí, tenham esse cara pronto.",--Heli is almost there, have that guy ready.
	pln_dah_28_02 = "Vejam se alguém na Gerência esqueceu o computador.",--See if someone in Management forgot their computer.
	pln_dah_47_02 = "Eu abriria esse segundo cofre se fosse vocês.",--I'd get that second vault open if I were you.
	pln_dah_80_03 = "Coloquem o Cartão de Acesso do Ralph e então o código.",--Swipe Ralph's keycard, then punch in the code.
	pln_dah_45_01 = "Vocês acharam um segundo cofre?",--You found a second vault?
	pln_dah_98_01 = "Peguem isso e terá um belo bônus.",--Grab it and there'll be a nice bonus.
	pln_dah_65_05 = "Preciso de vocês para chegar a esses roteadores.",--Need you to get to those routers.
	pln_dah_02_02 = "O cofre tem dois roteadores de segurança protegendo-o e vocês precisam desligá-los. Será fácil fazer se vocês me colocarem neles diretamente. Procure-os pelas paredes.",--The vault has two security routers protecting it and you need to shut them both down. Easily done if you patch me into them directly. Look for them mounted on the walls. 
	pln_dah_03_01 = "Procurem nas paredes por caixas de roteador.",--Look on the walls for the router boxes.
	pln_dah_05_03 = "OK, bom. Agora tomem conta do outro roteador.",--OK, good. Now take care of the other router.
	pln_dah_06_02 = "Vai me levar um tempo para desligar isso.",--It's going to take me a while to shut this down.
	pln_dah_09_02 = "Uma caixa de segurança a menos.",--That's one security box taken care of.
	pln_dah_100_03 = "Use a tirolesa para levar as bolsas pelo jardim.",--Use zipline to get the bags out via the garden.
	pln_dah_101_03 = "Uma tirolesa vai fazer vocês terminarem bem mais rápido!",--A tirolesa will get you done a lot faster!
	pln_dah_103_02 = "Pessoal, preciso tirar o helicóptero até as coisas esfriarem.",--Guys, I have to pull the chopper out until things cool down.
	pln_dah_103_03 = "Aguardem pessoal, o helicóptero tem que fazer um pequeno desvio até as coisas se acalmarem.",--Stand by guys, the chopper has to do a little detour until things calm down.
	pln_dah_105_01 = "Mais uma bolsa e podem sair.",--One more bag, then you get leave.
	pln_dah_107_01 = ".. ou fiquem e roubem um pouco mais. Vocês decidem!",--.. or stay and bag a little more. Up to you!
	pln_dah_107_02 = ".. ou peguem um pouco mais.",--.. or take a little more.
	pln_dah_109_01 = "Helicóptero está esperando.",--Helicopter is waiting.
	pln_dah_109_02 = "O quê vocês estão esperando?",--What're you waiting for?
	pln_dah_109_06 = "Chop-chop, para o helicóptero.",--Chop-chop. To the chopper.
	pln_dah_109_08 = "Trabalho finalizado, rapazes. Hora de partir.",--Job is over guys. Time to go.
	pln_dah_110_01 = "Parece que a festa acabou. As pessoas estão saindo!",--The party seems to have stopped. People are leaving!
	pln_dah_110_03 = "Sem mais festa, pessoal. Eles estão saindo.",--No more party people, they're all heading out.
	pln_dah_115_02 = "Ralph apareceu. Olhos abertos!",--Ralph just showed himself. Keep you eyes open!
	pln_dah_11_01 = "Vocês ainda precisam encontrar esses três laptops para pegar as partes do código.",--You still need to find the three laptops to get the code fragments.
	pln_dah_120_02 = "Vão para o telhado sinalizar ao helicóptero se vocês estiverem prontos pra sair!",--Get to the roof and signal the chopper if you're ready to leave!
	pln_dah_12_04 = "Encontraram os laptops?",--Found those laptops yet?
	pln_dah_12_05 = "Lembrem-se, encontrem esses laptops.",--Remember, find those laptops.
	pln_dah_16_02 = "Eu acho que há um PC na Academia.",--I think there's a PC in the fitness center.
	pln_dah_17_01 = "Tem algo na cantina e não é o Jeff Vader. Se parece com uma tela LCD brilhante.",--Something in the cafeteria and it isn't Jeff Vader. It looks like a glowing LCD display. 
	pln_dah_17_03 = "Vão verificar na Cantina. Eu vejo um monitor de PC lá.",--Might want to check out the cafeteria. I can see a PC monitor there.
	pln_dah_19_03 = "Ao lado do Escritório da Jade, parece um computador.",--Right by the Jade Room, looks like a computer.
	pln_dah_20_02 = "Pode valer a pena verificar se há um laptop no Quarto Glitter.",--The Quarto Glitter might be worth checking for a laptop.
	pln_dah_22_01 = "Vocês provavelmente vão achar um computador na Administração.",--You'll probably find a computer in Administration.
	pln_dah_27_03 = "Vocês podem verificar se há um computador no Canteiro de Obras.",--Might want to check the contruction site for a computer.
	pln_dah_28_01 = "Sala de Administração, eles sempre têm computadores portáteis.",--Management Office, they always have portable computers.
	pln_dah_29_03 = "Acho que há um computador em Vendas. Vão dar uma olhada.",--I think there's a computer in Sales. Go take a look.
	pln_dah_32_02 = "Estou pensando que tanto o número quanto a cor são importantes.",--I'm thinkin' that both number and color are important.
	pln_dah_33_02 = "Bom trabalho. Apenas mais um conjunto de número-cor para terminar.",--Good going. Only one more color-number set to go.
	pln_dah_34_03 = "Esse foi o último pedaço do código.",--That's the last piece of the code.
	pln_dah_35_01 = "Ok, agora vocês precisam de um Cartão de Acesso. Encontre o Ralph Garnet e tirem dele. Ele deve estar por aí em algum lugar.",--Ok, now you need a keycard. Find Ralph Garnet and take it from him. He should be around there somewhere.
	pln_dah_35_03 = "Ralph Garnet tem a última peça do quebra-cabeça. Encontrem-no e peguem seu Cartão de Acesso. Ele está por aí em algum lugar.",--Ralph Garnet has the last piece of the puzzle. Find him and take his keycard. He's around there somewhere.
	pln_dah_40_01 = "Isso não vai se abrir sozinho. Usem o Cartão de Acesso e o código.",--It ain't gonna open itself. Use the keycard and code.
	pln_dah_40_02 = "Esse cofre está só esperando para ser esvaziado, pessoal. Usem o Cartão de Acesso e coloquem o código.",--That vault is just waiting to be emptied guys. Use the keycard, then enter the code.
	pln_dah_42_01 = "Não quebre os vidros ou o alarme vai disparar. Usem um Cortador de Vidro.",--Don't smash the glass or the alarm will go off. Use a glass-cutter.
	pln_dah_42_03 = "Cuidado com o vidro. Cortem ao invés de quebrar se não o alarme irá disparar.",--Watch the glass. Cut through it instead of smashing or the alarm will go.
	pln_dah_43_01 = "Vocês precisam levar as bolsas para a plataforma de que vieram.",--You need to get the bags to the platform where you came in. 
	pln_dah_43_02 = "Levem as bolsas para a plataforma de lavagem de janela.",--Get the bags to the window-washing platform.
	pln_dah_47_01 = "Há um bônus suculento para nós se vocês abrirem o segundo cofre.",--There's a juicy bonus waiting for us if you crack that second vault.
	pln_dah_48_01 = "As pedras nas caixas são de alta prioridade, mas pegue tudo o que puder.",--The stones in cases are top priority, but grab whatever else you can.
	pln_dah_48_02 = "Cada pouquinho ajuda, mas as pedras nas caixas são as mais importantes.",--Every little bit helps, but the rocks in cases are most important.
	pln_dah_49_05 = "Sem tempo pra relaxar ainda.",--No time to relax yet.
	pln_dah_51_03 = "Quase lá.",--Almost there.
	pln_dah_52_01 = "OK, esse é o nosso mínimo. Peguem mais se vocês quiserem, ou saiam daí!",--OK, that's our minimum. Grab more if you want, or get out of there.
	pln_dah_52_03 = "É isso. Fiquem e peguem mais ou saiam. Vocês que mandam.",--That's it. Stay and grab more of get out. Your call.
	pln_dah_53_01 = "Ótimo, isso é tudo, agora saiam daí.",--Great, that's everything, now get out of there!
	pln_dah_55_01 = "OK, é isso. Hora de partir.",--OK, that's it. Time to go.
	pln_dah_55_02 = "Não há mais tempo para festa, apenas saiam.",--No more time to party, just get out.
	pln_dah_55_03 = "Hora de partir, pessoal.",--It's time to leave guys.
	pln_dah_55_05 = "Sem tempo para biscoitos. Saiam, agora.",--No time for snacks. Get out, ASAP.
	pln_dah_57_03 = "Precisamos de uma mudança de planos, o código foi desativado.",--We need a change of plan, the code has been shut down!
	pln_dah_58_02 = "Droga, parece que a única coisa que vai funcionar agora é o código mestre. Deixe-me ver se consigo descobrir quem o tem.",--Damn, looks like the only thing that will work now is the master code. Let me see if I can find out who has it.
	pln_dah_58_03 = "Eles desativaram o código de vocês. Pode haver outro - um código mestre, mas terei que descobrir quem o possui.",--They just disabled your code. There might be another- a master code, but I'll have to find out who has it.
	pln_dah_61_02 = "Droga, eles sabem que vocês estão aí agora.",--Damn, they know you're there now for sure.
	pln_dah_64_02 = "Eu tenho um plano B, apenas encontrem esses roteadores!",--I've come up with a plan B, just find those routers!
	pln_dah_65_03 = "Vocês precisam achar esses roteadores!",--You need to find those routers!
	pln_dah_67_01 = "Ótimo! Estou dentro.",--Great! I'm in.
	pln_dah_67_02 = "Ok, deixe-me ver...",--Ok, let me see...
	pln_dah_68_01 = "Os policiais estão tentando nos parar. Defendam esses roteadores enquanto eu trabalho!",--Cops are trying to stop us. Defend those routers while I work!
	pln_dah_69_08 = "Derrubem qualquer policial que se aproxime.",--Drop any cop that gets close!
	pln_dah_71_02 = "OK, terminei aqui!",--OK,I'm done here!
	pln_dah_73_02 = "Estamos presos sem aquele Cartão de Acesso. Encontrem o Ralph Garnet!",--We're stuck without that keycard. Find Ralph garnet!
	pln_dah_74_01 = "Certo, é hora de pegar o código mestre. O CFO vai ter.",--Right, time to get the master code. The CFO will have it.
	pln_dah_74_03 = "Chutem essa merda da escada executiva. Encontrem o CFO e peguem seu código mestre.",--Kick the shit out of the exacutive ladder. Find the CFO and get his master code!
	pln_dah_75_03 = "Vocês ainda precisam encontrar o código mestre.",--You still need to find the master code!
	pln_dah_76_01 = "Ele está mentindo. Coloquem ele no helicóptero, vou tirar o código dele.",--He's lying through his teeth. Get him to the chopper, I'll get the code out of him.
	pln_dah_77_01 = "Vamos, pessoal. Levem esse cara para o telhado.",--C'mon guys, get that guy to the roof.
	pln_dah_79_03 = "Eu vou quebrar esse cara como se fosse um ovo e pegar o código pra vocês bem rápido.",--I'll crack this guy like an egg and have that code for you shortly.
	pln_dah_80_02 = "Vocês precisam colocar o Cartão de Acesso do Ralph antes do código.",--You need to swipe Ralph's card before the code.
	pln_dah_81_02 = "Escutem, o código é...",--Listen up, the code is...
	pln_dah_83_01 = "Um",--One
	pln_dah_83_02 = "Um",--One
	pln_dah_85_01 = "Três",--Three
	pln_dah_85_02 = "Três",--Three
	pln_dah_87_01 = "Cinco",--Five
	pln_dah_89_01 = "Sete",--Seven
	pln_dah_89_02 = "Sete",--Seven
	pln_dah_90_02 = "Oito",--Eight
	pln_dah_92_02 = "Escutaram? O código é...",--You get that? The code is...
	pln_dah_92_05 = "Aqui está de novo.",--Here it is again.
	pln_dah_95_02 = "Loot é para ser levado...",--Loot for the taking...
	pln_dah_97_01 = "Provavelmente vale uma fortuna.",--Probably worth a fortune.
	pln_dah_99_02 = "Cada pouquinho ajuda, mas as pedras nas caixas são as mais importantes.",--Every little bit helps, but the rocks in cases are most important.
	pln_dah_end_stealth_03 = "Ótima execução, pessoal.",--Textbook execution people. 
	
	-- Objetivos
	hud_heist_dah_06_hl = "Aguarde o Bain",--Wait for Bain
	hud_heist_dah_07 = "Acenda um sinalizador para sinalizar o Bile para a fuga.",--Light a flare to signal Bile for the escape.
	hud_heist_dah_05_hl = "Escolte o CFO até o Telhado",--Escort the CFO to the roof
	hud_heist_dah_02_hl = "Aguarde até que o Hackeamento Termine",--Wait for the hacking to finish
	hud_heist_dah_09_hl = "Pegue o Cartão de Acesso",--Get the Keycard
	hud_heist_dah_04_hl = "Encontre o CFO",--Find the CFO
	hud_heist_dah_03_hl = "Encontre os Laptops com o Código do Cofre",--Find the laptops with the vault codes
	hud_heist_dah_01_hl = "Encontre e comece a Hackear o Sistema de Segurança",--Find and start hacking the security system
	hud_heist_dah_05 = "Escolte o CFO até o telhado para que o Bain possa pegá-lo e extorqui-lo.",--Escort the CFO to the roof so that Bain can pick him up and extort him.
	hud_heist_dah_10 = "Coloque o código correto e entre no cofre.",--Enter the correct code and open the vault.
	hud_heist_dah_11_hl = "Roube e Assegure os Diamantes",--Steal and secure the diamonds
	hud_heist_dah_07_hl = "Sinalize a Fuga",--Signal the escape
	hud_heist_dah_01 = "Encontre as caixas do roteador para o sistema de segurança e coloque os dispositivos de hackeamento.",--Find the router boxes for the security system and place the hacking devices.
	hud_heist_dah_08 = "Aguarde até o helicóptero chegar.",--Hold out until the helicopter arrives.
	hud_heist_dah_03 = "Encontre os laptops que contém as partes do código da porta do cofre.",--Find the laptops that each contain a part of the vault door code.
	hud_heist_dah_10_hl = "Abra o Cofre",--Open the vault
	hud_heist_dah_08_hl = "Espere pelo Helicóptero",--Wait for the helicopter
	hud_heist_dah_02 = "Aguarde para que os dispositivos termine o hackeamento.",--Wait for devices to finish hacking.
	hud_heist_dah_09 = "Domine o Ralph e pegue o Cartão de Acesso dele.",--Subdue Ralph and get the keycard from him.
	hud_heist_dah_12 = "Suba para o telhado e fuja!",--Get to the roof and escape!
	hud_heist_dah_11 = "Roube e assegure os diamantes.",--Steal and secure the diamonds.
	hud_heist_dah_12_hl = "Fuja",--Escape
	hud_heist_dah_06 = "Espere até que o Bain obtenha o código do CFO.",--Wait for Bain to get the code from the CFO.
	hud_heist_dah_04 = "Eles acionaram o alarme que travou o cofre, encontre o CFO para que possamos ver se podemos descobrir como cancelar o travamento.",--They triggered the alarm which locked down the vault, find the CFO so that we can see if we can find out how to override the lockdown.
		}