Hooks:Add("LocalizationManagerPostInit", "chavesdooito", function(loc)
	LocalizationManager:add_localized_strings({
	-- Nomes e Descrições
	heist_flat = "Panic Room",
	heist_flat_hl = "Panic Room",
	heist_flat_hl_briefing = "Lá no fundo dos projetos existe um edifício fortificado, o Quartel-General de uma gangue com uma operação lucrativa de drogas. Nessa edifício, existe uma Sala do Pânico grudada ao chão e dentro dessa sala tem uma enorme fortuna em dinheiro.\n\nEntrar no prédio será fácil, mas abrir a Sala do Pânico vai dar um pouco de trabalho. Vai demorar dias até abrir. Então, se vocês não podem entrar, como vamos fazer para sair com o dinheiro? Ora, simples: Roubar a Sala inteira.",
	heist_flat_crimenet = "As vezes você precisa levar as coisas ao extremo para receber um bom pagamento, e é exatamente isso que vamos fazer dessa vez. Entrem no prédio, encontrem a Sala do Pânico e roubem a sala toda com um helicóptero.\n\n» Entre no Prédio\n» Localize e Desmonte a Sala do Pânico\n» Roube a Sala e Fuja",
	
	-- Introduções
	pln_flt_intro_01 = "Se conseguirmos fazer esse serviço, nós vamos ter todo o sub-mundo do crime falando sobre isso pra sempre. Senhoras e senhores, é desse jeito que iremos fazer história.",
	pln_flt_intro_02 = "Vocês estão pronto para se tornarem lendas?",
	pln_flt_intro_03 = "Tô ansioso pra isso, gente. Chavez não tem a menor ideia sobre o que lhe espera.",
	
	-- Legendas
	plt_flt_01_03 = "Beleza, eu tô perto agora, mas tem Snipers em todo canto. Vou precisar que vocês cuidem deles antes de soltar o C4.",
	plt_flt_02_01 = "Ei! Cadê a ajuda que preciso? Eu tô encurralado aqui!",
	plt_flt_02_03 = "Ei! Eu tô sendo pipocado aqui! Desde que esses Snipers continuem vivos, eu não posso chegar perto e fazer a entrega!",
	plt_flt_05_02 = "Oh, puts, eu errei... Gente, o C4 caiu na varanda. Eu sinto muito.",
	plt_flt_07_03 = "Eu tô aqui, pessoal, mas eu não posso chegar perto com o telhado lotado de policiais.",
	plt_flt_09_01 = "Parece que o telhado tá limpo. Bom trabalho. Estou indo aí agora.",
	plt_flt_09_02 = "Ótimo. estou indo aí.",
	plt_flt_10_02 = "Eu estou descendo o imã.",
	plt_flt_11_01 = "Ok, o imã tá no lugar, só preciso que vocês conectem ele no topo da Sala do Pânico.",
	plt_flt_14_02 = "Beleza! Tô dando fora!",
	plt_flt_14_01 = "Ok, eu tô dando o fora dessa merda. Vocês continuem distraindo os policiais!",
	plt_flt_10_01 = "Ok, descendo o imã.",
	plt_flt_05_03 = "Sinto muito, cavalheiros. Eu acidentalmente soltei a C4 na varanda... Me desculpem.",
	plt_flt_02_02 = "Pessoal, me protejam! Esses Snipers estão sendo um pé no saco pra eu chegar perto. Vocês precisam matar todos eles!",
	plt_flt_01_02 = "Tô chegando, gente. Mas os policiais trouxeram muitos Snipers nos telhados próximos do prédio. Vou precisar que vocês cuidem deles antes de eu fazer a entrega.",
	plt_flt_05_01 = "Varanda! A C4 caiu na varanda. Eu errei o telhado. Sinto muito por isso.",
	plt_flt_06_02 = "Yihaa! A C4 caiu no telhado como planejado.",
	plt_flt_06_01 = "Cavalheiros, a C4 está no telhado.",
	plt_flt_06_03 = "Tudo certo! A C4 caiu no telhado.",
	plt_flt_01_01 = "Ok, estou na área, mas os policiais trouxeram muitos Snipers nos telhados próximos do prédio. Vocês precisam se livrar deles antes que eu possa soltar a C4.",
	plt_flt_07_01 = "Ok, estou de volta, mas não posso fazer nada com tantos policiais por aí. Vocês precisam limpar o telhado.",
	plt_flt_07_02 = "Meu Deus, tem muita polícia aí! Não posso fazer nada, vocês vão ter que dar um jeito nisso.",
	plt_flt_09_03 = "Beleza, isso deve servir! Entrando.",
	plt_flt_10_03 = "Descendo o imã agora.",
	plt_flt_11_02 = "Desci o imã, mas preciso que vocês conectem.",
	plt_flt_11_03 = "O imã está onde deveria estar, mas vou precisar da ajuda de vocês para conectar.",
	plt_flt_14_03 = "É isso! Tô dando fora!",
	pln_flt_01_03 = "Chegamos, gente. Logo ali é o prédio do Chavez.",
	pln_flt_01_02 = "Aqui estamos, gente. Prédio do Chavez.",
	pln_flt_02_01 = "Entrem lá.",
	pln_flt_04_03 = "Entrem lá e continuem o acordo.",--Get in there and get the deal started.
	pln_flt_11_03 = "Mas que caralho é isso? Uma enorme escova de dentes? Eu poderia realmente usar algo assim.",--What the hell is that? An enormous toothbrush? I could really use something like that.
	pln_flt_44_03 = "Nós já podemos decolar!",--We have a lift-off!
	pln_flt_27_03 = "Nós precisamos de mais um pouco de C4 no quarto andar, gangue.",--We still need more C4 on the fourth floor, gang.
	pln_flt_26_02 = "Ok, vão buscar o C4 e plantem logo acima da Sala do Pânico.",--Ok, go pick up the C4 and then plant it right above the panic room.
	pln_flt_07_03 = "É a hora. Coloquem a Máscara e vamos começar.",--It's time. Put on the masks and let's do this.
	pln_flt_03_06 = "Apressem-se e vão pra dentro.",--Hurry up and go inside.
	pln_flt_06_01 = "Fique de olhos abertos. Algo está acontecendo.",--Keep your eyes peeled. Something's up.
	pln_flt_37_02 = "Afastem-se do raio da explosão, gangue.",--Stand clear from the blast radius, gang.
	pln_flt_50_01 = "Quem é que já fez isso que estamos fazendo? Ninguém! Essa merda vai ficar na história, como eu havia dito.",--Who the hell can do what we just did? No one! This will go down in history, just like I said.
	pln_flt_09_01 = "Vão pra Sala do Pânico, ela está no terceiro andar.",
	pln_flt_03_07 = "Você precisam passar por essas portas.",--You need to walk through those doors. Chop-chop.
	pln_flt_08_02 = "Ok, vocês precisam limpar esse lugar.. tem muitos bandidos restantes ainda. Encontrem-os.",--Okay, you need to clear the joint from the remaining thugs. Find them.
	pln_flt_11_02 = "Ei, é uma escova de dentes gigante! Posso ficar com ela?",--Hey now, that's a big toothbrush... Can I have it?
	pln_flt_07_02 = "Ok, hora de irmos. Coloquem as máscaras e vamos nessa!",--Okay, time for our move. Get the masks on and let's go!
	pln_flt_16_03 = "Ok, nós vamos precisar usar as serras para cortar a Sala do Pânico e deixá-la livre do andar.",--Okay, we'll need to use the saws to cut the room free from the floor.
	pln_flt_06_03 = "Fiquem na ponta dos pés. Isso vai ser bem tenso.",--Stay on your toes. This's gonna be tense.
	pln_flt_26_03 = "Hora de pegar a C4 e plantar nos andares acima da Sala do Pânico.",--Time to pick up the C4 and then plant it on the floors above the panic room.
	pln_flt_03_08 = "Pessoal, não nos deixem esperando. Entrem lá.",--Guys, don't keep them waiting. Get in there.
	pln_flt_13_03 = "Isso foi intenso, mas vocês fizeram o que era preciso. Peguem a chave e voltem para a Sala do Pânico.",--That was intense, but you did what was needed. Pick up the key and head back to the panic room.
	pln_flt_08_03 = "Ainda tem bandidos pelo prédio. Vocês precisam lidar com eles.",--There's still thugs in the building. You need to deal with them.
	pln_flt_08_01 = "Ainda tem bandidos por todo o prédio, gangue. Elimine-os!",--There's thugs all around the building, gang. Take 'em out!
	pln_flt_cnc_01 = "Chavez possui uma Sala do Pânico lotada de grana e nós iremos roubar a sala inteira. Sim, vocês me ouviram certo.",--Chavez has a panic room filled with cash and we're gonna steal the whole room. Yes, you heard me correctly.
	pln_flt_25_02 = "Porra, Bile, que merda é essa? Foi mal por isso, gente, vocês vão ter que pegar o C4 e colocá-los nos andares acima da Sala do Pânico.",--Come on, Bile, what the hell? Sorry about that, guys, you'll still have to pick up the C4 and place them all around the floors above the panic room.
	pln_flt_16_02 = "Hora de cortar esse bebê. Coloquem as serras.",--Time to cut out this baby. Place the saws.
	pln_flt_35_02 = "Bom. Nós já terminamos com o quarto andar.",--Good. We're done with the fourth floor.
	pln_flt_25_03 = "Sério, Bile? Eu esperaria isso do Alex, não de você... De qualquer forma, gangue, peguem o C4 e plantem pelos andares acima da Sala do Pânico.",--Really, Bile? I might have expected that from Alex, but not you... Anyhow, gang, go pick up the C4 and plant it around the floors right above the panic room.
	pln_flt_48_03 = "Vazem daí! Corram!",--Get out of there! Run!
	pln_flt_32_01 = "Ainda precisamos de mais explosivos no quarto andar e no quinto.. Vamos lá.",--We still need more explosives on the fourth and fifth floor. Let's go.
	pln_flt_46_03 = "Desçam até a porta do porão do beco dos fundos!",--Go down to the basement door in the back alley!
	pln_flt_16_01 = "Certo, primeiro passo do plano: Preparar as serras.",--All right, first things first: set up the saws.
	pln_flt_34_02 = "Bom. Quinto andar já foi.",--Good. Fifth floor is done.
	pln_flt_33_01 = "Excelente. É o suficiente para o telhado.",--Excellent. That's enough for the roof.
	pln_flt_06_02 = "Estou tendo um mal pressentimento sobre isso.",--I've got a bad feeling about this.
	pln_flt_35_01 = "É isso aí, gangue. Quarto andar completo.",--That's it, gang. Fourth floor complete.
	pln_flt_24_01 = "Bom trabalho, pessoal. Com os Snipers fora, o Bile vai poder fazer a entrega.",--Good job, gang. With the snipers gone, Bile will be able to make the drop.
	pln_flt_07_01 = "Certo, eu diria que é a hora da destruição! Coloquem suas máscaras!",--Alright, I'd say it's time to get blastin'. Put your masks on!
	pln_flt_21_01 = "Ok, gangue, os policiais já estão aqui - como esperado. Seria mais fácil pegá-los logo na rua antes que eles comecem a invadir o prédio.",--Okay, gang, cops are here - as expected. It's easier to take them out on street level before they actually storm the building.
	pln_flt_03_03 = "O segurança vai ficar desconfiado se vocês não entrarem.",--The bouncer will get suspicious if you don't walk in
	pln_flt_50_03 = "Nós fizemos algo que as pessoas diriam ser impossível de ser feito. Não há nada que não possamos fazer, gangue. Os melhores dos melhores.",--We just did something people would have said was impossible. There's nothing we can't do, gang. Best of the best.
	pln_flt_39_03 = "Agora temos um lindo buraco bem aqui!",--Now that's a beautiful hole right there!
	pln_flt_03_01 = "O que vocês estão esperando? Entrem.",--What are you waiting for? Get inside.
	pln_flt_03_05 = "Gangue, por que a demora? Entrem no prédio.",--Gang, what's the hold up? Get inside the building.
	pln_flt_33_03 = "Ótimo, isso deve servir para o telhado.",--Nice, that should do it for the roof.
	pln_flt_24_03 = "Boa noite snipers! Bom trabalho, pessoal. Agora, hora de pegar o C4.",--Good night snipers! Good job, guys. Now, time to get that C4.
	pln_flt_27_01 = "Bom trabalho, mas ainda precisamos de um pouco mais no quarto andar.",--Good job, but we need some more on the fourth floor.
	pln_flt_04_01 = "Entrem na sala e prossigam com o acordo.",--Head inside the room and go through with the drug deal.
	pln_flt_38_03 = "Estão vendo isso? é assim que fazemos as coisas.",--Did you see that? That's how we do things.
	pln_flt_50_02 = "Agora se isso não fizer as pessoas falarem sobre, eu não sei o que irá. Isso foi incrível, gangue, e nós ainda iremos receber um ótimo pagamento por isso.",--Now if that won't get people talking, I don't know what will. That was amazing, gang, and we're getting a juicy payday out of it.
	pln_flt_26_01 = "Peguem o C4 e plantem no chão acima da Sala do Pânico.",--Pick up the C4 and then plant it on the floor right above the panic room.
	pln_flt_03_04 = "Vamos. Entrem logo.",--Come on. Get inside.
	pln_flt_49_03 = "Mais rápido, pessoal!",--Faster guys!
	pln_flt_43_02 = "É isso. Estou pronto pra tirar esse bebê daqui.",--That's it. I'm ready to lift this baby out of here.
	pln_flt_03_02 = "Não fiquem parados, entrem lá.",--Don't just stand around, get in there.
	pln_flt_33_02 = "Já está bom o suficiente para o telhado.",--That's good enough for the roof.
	pln_flt_42_03 = "Os policiais estão pelos andares de cima, vocês vão precisar ir até lá e encontrarem um ponto para defender!",--The cops are coming in from the upper floors, you gotta move up and find a bottleneck to defend!
	pln_flt_34_03 = "É o suficiente para o quinto andar. Excelente.",--That's it for the fifth floor. Excellent.
	pln_flt_05_02 = "Não levantem suspeitas. Façam o que eles dizem.",--Don't raise suspicion. Do what they tell you.
	pln_flt_43_01 = "OK, o imã está seguro. Vamos puxar o pacote pra fora daí!",--OK, the winch is secured. Let's pull this package out of here!
	pln_flt_21_02 = "A Polícia está aqui. Eles vão invadir o prédio na primeira chance que tiverem, então talvez seja melhor pará-los antes que eles consigam.",--The police are here. They'll storm the building if they get the chance, so maybe stop them before they can.
	pln_flt_48_01 = "Certo, vocês já passaram do ponto sem volta. ... Corram! Corram! Não olhem pra trás!",--All right, you're past the point of no return. ... Run! Run! Don't look back!
	pln_flt_31_01 = "Quase lá, gangue. Apenas mais alguns no telhado e estaremos bem.",--Almost there, gang. Just some more on the roof and we're good.
	pln_flt_21_03 = "Policiais chegando. Eu sugiro que vocês desçam e peguem-nos na frente da entrada. Dessa forma, vocês vão conseguir detê-los antes que invadam o prédio inteiro.",--Cops incoming. I suggest you head down and take them heads-on by the front entrance. That way you can stop them before they flood the building.
	pln_flt_42_02 = "Ok, gangue, lá vem eles! Encontrem uma boa posição para se defenderem! Estamos quase terminando!",--Okay, gang, here they come! Find a good position to defend yourselves! We're almost done!
	pln_flt_04_02 = "Vocês precisam agir como se estivessem lá para concluir o acordo.",--You need to act like you're there to go through with the drug deal.
	pln_flt_05_01 = "Esses caras não estão pra brincadeira. Não sejam burros e vão até a sala.",--These guys aren't kidding around. Don't act dumb and go in the room.
	pln_flt_05_03 = "Parem de ficar andando por aí e entrem na sala.",--Stop walking around and go inside the room.
	pln_flt_11_01 = "Whoah, isso é uma escova de dentes bem grande... Eu quero!",--Whoah, that's a big toothbrush... I want it.
	pln_flt_13_01 = "Vocês pegaram esse filho da puta maluco. Agora, peguem a chave dele e retornem para a Sala do Pânico.",--You got that crazy bastard. Now, get the key from him and return to the panic room.
	pln_flt_13_02 = "Bem, ele teve o que mereceu. Peguem a chave e voltem novamente para a Sala do Pânico.",--Well, that takes care of Chavez. Pick up the key and get back to the panic room.
	pln_flt_24_02 = "Finalmente pegamos todos os Snipers, gangue. Ninguém vai parar o Bile na entrega desse C4 agora.",--That's it for the snipers, gang. Nothing will stop Bile from dropping the C4 now.
	pln_flt_25_01 = "Puta que pariu, Ale... Bile! Como pôde ter errado o telhado? Gangue, ainda precisamos daquele C4 então vocês vão precisar buscá-lo. Lembrem-se: queremos os explosivos plantados nos andares acima da Sala do Pânico.",--God damn it, Ale... Bile! How could you miss the roof? Gang, we still need that C4 so you'll just need to pick it up. Remember, we want the explosives placed around the floors above the panic room.
	pln_flt_27_02 = "É isso aí, gangue. Falta só o quarto andar.",--That's it, gang. Only the fourth floor left
	pln_flt_31_02 = "Coloquem o último C4 no telhado e devemos estar prontos.",--Plant the last C4 on the roof and we should be good to go.
	pln_flt_32_02 = "Boa. Agora, plante o resto no quarto e quinto andar.",--Good. Now, plant the rest on the fourth and the fifth floor.
	pln_flt_35_03 = "Quarto andar já foi. Bom.",--Fourth floor is done. Good.
	pln_flt_36_02 = "Excelente! Agora voltem novamente, por que as coisas estão prestes a explodir.",--Excellent! Now get back, because things are about to blow.
	pln_flt_36_03 = "Bom trabalho. agora se afastem antes que algo dê errado.",--Good job, now get the hell away from there before it goes off.
	pln_flt_37_03 = "Vamos, pessoal. Eu não posso detonar os explosivos com vocês tão perto.",--Come on, gang, I can't detonate the explosives as long as you are close.
	pln_flt_38_02 = "Whoo! Isso foi louco.",--Whoo! That was crazy.
	pln_flt_40_01 = "Ok, pessoal. Hora de segurarmos o forte até o Bile voltar. Mande-os pro inferno.",--Okay, guys, time to hold the fort until Bile returns. Give 'em hell
	pln_flt_41_03 = "Bile, você acordou! Quanto tempo até você estar aqui?",--Bile, you're up! How long before you're here?
	pln_flt_42_01 = "O prédio está se abrindo igual a um queijo suiço! Eu sugiro que vocês subam alguns andares para pegar uma melhor posição tática.",--The building is opening up like a swiss cheese! I suggest you go up a few floors to get a better tactical position.
	pln_flt_43_03 = "O imã está posicionado. Hora de puxar essa coisa pra fora daí.",--The magnet is in place. Time to pull it out of here.
	pln_flt_44_01 = "Olha pra essa sala, vai! Nós conseguimos fazer isso, caralho!",--Look at that room go! We god damn did it!
	pln_flt_44_02 = "Vocês estão vendo isso? Nós conseguimos, gangue. Nós realmente conseguimos.",--Would you look at that!? We did it, gang. We did it.
	pln_flt_45_01 = "Excelente trabalho, gangue! Absolutamente EXTRAORDINÁRIO. Mas agora vocês precisam cair fora daí antes que o lugar acabe desmoronando.",--Excellent work, gang! Absolutely amazing. But now you need to get out of there before the place collapses.
	pln_flt_45_03 = "Um trabalho bem feito! Agora, vamos cair fora daqui rápido. Esse prédio não vai ficar de pé por muito mais tempo.",--A job well done! Now, get the hell out of there fast. That building won't keep standing for long.
	pln_flt_46_02 = "Vão para o porão, pessoal!",--Get down to the basement guys!
	pln_flt_48_02 = "Corram! Apenas corram!",--Run! Just run!
	pln_flt_49_01 = "Rápido! Rápido! Para a esquerda!",--Hurry! Hurry! To the left!
	pln_flt_49_02 = "Vai! Vai! Vai! Apenas corram!",--Go! Go! Go! Just run!
	pln_flt_10_02 = "Achado não é roubado, gente. Achado não é roubado.",
	pln_flt_12_03 = "OK, a porta está trancada. Vamos precisar de uma chave. Acho que achar o Chavez é achar a chave. então procure por ele.",--Que maravilha de trocadilho! HAHA
	pln_flt_14_02 = "Usem a chave para abrir a porta vermelha.",
	pln_flt_17_02 = "Preparem as serras. Duas na Sala do Pânico e duas no andar de baixo.",
	pln_flt_18_01 = "Certifiquem-se de que as serras estão cortando. Se uma quebrar, consertem assim que possível. Não podemos ficar aqui por muito tempo.",
	pln_flt_19_01 = "Vocês estão de olho nas serras? Elas estão cortando?",
	pln_flt_19_02 = "Lembrem-se de manter as serras funcionando. Elas podem quebrar.",
	pln_flt_19_03 = "As serras ainda estão cortando?",
	pln_flt_20_01 = "As serras terminaram, ótimo.",
	pln_flt_22_02 = "Bom trabalho, pessoal. Agora precisamos dos explosivos do Bile. Me dê um momento. Ô Bile, tá na hora! Falta quanto tempo para você soltar o C4?",
	pln_flt_23_01 = "Ouviram isso, pessoal? O Bile vai soltar o C4 no telhado daqui a pouco.",
	pln_flt_29_01 = "Ótimo. Só falta o quinto andar.",
	pln_flt_32_03 = "Beleza. Agora só precisamos de um pouco mais no quarto e o quinto andar.",
	pln_flt_34_01 = "Já está bom pro quinto andar. Bom trabalho.",
	pln_flt_38_01 = "Isso foi bem louco! Até tremeu a estante de onde estou sentado!",
	pln_flt_39_02 = "Esse é belo de um buraco! Perfeito!",
	pln_flt_40_02 = "Hora de proteção, gente! Bile está vindo!",
	pln_flt_41_02 = "Bile! Hora de voltar e pegar a carga. Em quanto tempo você pode voltar?",
	pln_flt_45_02 = "Bom trabalho! Agora só dar o fora daí antes que esse lugar vire pó. Vamos!",
	pln_flt_46_01 = "Todo mundo, pro esgoto!",
	pln_flt_47_01 = "Todo mundo, pro esgoto!",
	pln_flt_40_03 = "Continuem atirando, pessoal! Bile estará voltando a qualquer minuto!",
	pln_flt_47_02 = "Pro porão, gente!",
	pln_flt_47_03 = "Vão pro porão que está no beco de trás!",
	pln_flt_41_01 = "Bile, está pronto para pegar a carga?",
	pln_flt_39_01 = "Esse buraco é ENORME! Perfeito!",
	pln_flt_37_01 = "Fiquem longe dos explosivos agora.",
	pln_flt_36_01 = "Ok, é isso! Agora se afastem, esse lugar está prestes a explodir!",
	pln_flt_31_03 = "Beleza, pessoal. Só falta o telhado.",
	pln_flt_28_03 = "Ótimo. Só o quinto andar e o telhado restando. Vamos logo, pessoal.",
	pln_flt_23_03 = "Bile vai soltar o C4 no telhado do prédio. Tenha certeza de pegar logo quando chegar.",
	pln_flt_22_03 = "É isso, pessoal. Vamos nessa. Só me dá um segundinho. Ei, Bile, está na hora do C4. Quão rápido você pode vir pra cá?",
	pln_flt_18_03 = "Fiquem de olho nas serras que quebrarem ou algo assim. Precisamos fazer isso rápido.",
	pln_flt_14_03 = "Hora de abrir a porta vermelha.",
	pln_flt_10_01 = "Eita, mas que maravilha de estoque de cocaína eles têm aqui. É uma boa pegar isso, se vocês me perguntam.",
	pln_flt_15_02 = "Vocês ainda precisam pegar a chave, e isso significa achar o Chavez.",
	pln_flt_15_03 = "Ainda precisamos da chave do Chavez para entrar nessa porta. Encontrem ele.",
	pln_flt_15_01 = "Gente, vocês precisam achar o Chavez para pegar a chave. Confiem em mim, vocês vão saber quem é quando virem ele.",
	pln_flt_09_03 = "A Sala do Pânico está no terceiro andar. Andem logo.",
	pln_flt_02_02 = "Entrem.",
	pln_flt_01_01 = "Beleza, pessoal. Logo a frente é a casa do Chavez.",
	pln_flt_02_03 = "Vamos nessa.",
	pln_flt_09_02 = "Vão para a Sala do Pânico.",
	pln_flt_10_03 = "Chavez não vai ter mais nenhum uso para essa cocaína, então peguem se vocês quiserem.",
	pln_flt_12_01 = "Droga, a porta está trancada. É tranqueira do Chavez, então ele deve ter a chave. Vejam se vocês conseguem achar ele no andar mais alto do prédio.",
	pln_flt_12_02 = "Nós não vamos entrar por essa porta sem uma chave... Hora de achar o Chavez. Ele está no comando e deve ter a chave.",
	pln_flt_14_01 = "Boa. Agora abram a porta vermelhas.",
	pln_flt_17_01 = "Preparem as serras na Sala do Pânico, duas no segundo andar e duas no quarto.",
	pln_flt_17_03 = "Vocês precisam usar as serras pra esse plano funcionar. Duas no segundo andar e duas no quarto. Vamos nessa!",
	pln_flt_18_02 = "Precisamos dessas serras funcionando, isso quer dizer ficar de olho nelas caso elas quebrem.",
	pln_flt_20_02 = "As serras terminaram. Bom trabalho.",
	pln_flt_20_03 = "Finalmente, as serras terminaram.",
	pln_flt_22_01 = "OK, hora do próximo passo do nosso plano. A C4 do Bile. Esperem, deixem eu ver com ele. Bile, tá aí? Precisamos da C4. Quanto tempo?",
	pln_flt_23_02 = "Vocês ouviram ele. Bile vai entregar a C4 no telhado em alguns minutos.",
	pln_flt_28_01 = "É isso, gente, mas ainda precisamos plantar mais C4 no quinto andar e no telhado.",
	pln_flt_28_02 = "Ótimo. Agora precisamos de mais no quinto andar e no telhado.",
	pln_flt_29_02 = "É isso, só falta o quinto andar.",
	pln_flt_29_03 = "Bom trabalho. Agora vão até o quinto andar e terminem o serviço.",
	pln_flt_30_02 = "Ótimo, pessoal. Agora precisamos plantar mais no quarto andar e no telhado.",
	pln_flt_30_03 = "Nós precisamos de mais C4 no quarto andar e no telhado.",
	pln_flt_30_01 = "Bom trabalho, agora precisamos de mais no quarto andar e no telhado.",
	
	-- Objetivos
	hud_heist_flat_intro = "Deixe que o Chavez permita sua entrada, e depois entre no prédio pela porta de trás.",
	hud_heist_flat_intro_hl = "Entre no Prédio",
	hud_heist_flat_key = "Localize o Chavez, ele estará nos andares mais altos do prédio, com uma touca vermelha. Pegue a chave dele.",
	hud_heist_flat_key_hl = "Encontre o Chavez e pegue a Chave dele",
	hud_heist_flat_lowerm = "Proteja o telhado e o helicóptero enquanto o imã desce no buraco.",
	hud_heist_flat_lowerm_hl = "Espere o imã descer",
	hud_heist_flat_panic = "Use a chave para abrir a porta vermelha.",
	hud_heist_flat_panic_hl = "Entre na Sala do Pânico",
	hud_heist_flat_roof = "Se livre de todos os policiais do telhado.",
	hud_heist_flat_roof_hl = "Limpe o Telhado",
	hud_heist_flat_roof2 = "Bile irá esperar a poeira abaixar, você precisa manter a polícia longe do telhado.",
	hud_heist_flat_roof2_hl = "Defenda o Helicóptero",
	hud_heist_flat_snipes = "Mate todos os Snipers dos telhados vizinhos, assim o helicóptero vai conseguir soltar o C4.",
	hud_heist_flat_snipes_hl = "Mate os Snipers",
	hud_heist_flat_start = "Vá e negocie o trato da droga. Esse é o portão que vai permitir a gente entrar.",
	hud_heist_flat_start_hl = "Continue a negociar o Acordo",
	hud_heist_flat_wait = "Espere pelo helicóptero soltar a C4 no telhado.",
	hud_heist_flat_wait_hl = "Espere pelo Explosivos",
	hud_heist_flat_wait2 = "Proteja o telhado, enquanto o helicóptero volta para pegar a Sala do Pânico.",
	hud_heist_flat_wait2_hl = "Espere pelo retorno do Helicóptero",
	hud_heist_flat_winch = "Conecte o imã do helicóptero no topo da Sala do Pânico.",
	hud_heist_flat_winch_hl = "Conecte o imã",
	hud_heist_flat_drop = "Bile está voltando com a C4. Aguente firme!",
	hud_heist_flat_drop_hl = "Espere pela C4",
	hud_heist_flat_door = "A Sala do Pânico deve estar em um apartamento no terceiro andar.",
	hud_heist_flat_door_hl = "Localize a Sala do Pânico",
	hud_heist_flat_detach = "Serre os traves da Sala do Pânico de cima e de baixo para desgrudá-la do andar.",
	hud_heist_flat_detach_hl = "Prepare as Serras",
	hud_heist_flat_detach2 = "Proteja a sala e fique de olho nas serras.",
	hud_heist_flat_detach2_hl = "Mantenha as Serras cortando",
	hud_heist_flat_c4 = "Plante a C4 no telhado, no quarto andar e no quinto.",
	hud_heist_flat_c4_hl = "Plante a C4",
	hud_heist_flat_c42 = "Vá pro andar de baixo, longe da C4!",
	hud_heist_flat_c42_hl = "Fique longe da C4!",
	hud_heist_flat_escape = "Desça as escadas para o porão e fuja pelo esgoto.",
	hud_heist_flat_escape_hl = "Fuga está Disponível",
		})
end)