Hooks:Add("LocalizationManagerPostInit", "chavesdooitoinfinito", function(loc)
	LocalizationManager:add_localized_strings({
	-- Nomes e Descrições
	--heist_flat = "Sala de Pânico (Panic Room)",
	--heist_flat_hl = "Sala de Pânico (Panic Room)",
	heist_flat_hl_briefing = "Lá fundo dos projetos tem uma sala blindado, o quartel-general de uma gangue com uma operação lucrativa de drogas. Nessa sala de pânico grudado no andar e dentro dessa sala de pânico tem uma fortuna de dinheiro.\n\nEntrar no prédio é fácil, mas abrir a sala de pânico vai dá uma dor de cabeça. Vai demorar dias para abrir. Então, se vocês não podem entrar, como vamos sair com o dinheiro? Ora, simples: roubar a sala inteira.",
	heist_flat_crimenet = "As vezes você precisa levar ao extremo para ter um bom dinheiro e é exatamente isso que vamos fazer. Entrar no prédio, achar a sala de pânico e roubar a sala toda com um helicópetero.\n\n» Entra no prédio\n» Localize e desmonte a sala de pânico\n» Roube a sala e foge",
	
	-- Introduções
	pln_flt_intro_01 = "Se conseguimos fazer esse serviço, nós vamos ter todo sub-mundo criminal falando sobre isso para sempre. Senhoras e senhores, é desse jeito que fazemos história.",
	pln_flt_intro_02 = "Vocês estão pronto para se tornarem lendas?",
	pln_flt_intro_03 = "Tô ancioso sobre isso, gente. Chavez não tem ideia sobre o que te espera.",
	
	-- Legendas
	pln_flt_03_06 = "Vamos, entrem.",--Hurry up and go inside.
	pln_flt_06_01 = "Fiquem de olho. Tem alguma merda errada.",--Keep your eyes peeled. Something's up.
	pln_flt_50_01 = "Quem diabos conseguiria fazer essa proeza? Ninguém! Isso vai entrar na história, como eu disse.",--Who the hell can do what we just did? No one! This will go down in history, just like I said.
	pln_flt_37_02 = "Fiquem longe da explosão, pessoal.",--Stand clear from the blast radius, gang.
	pln_flt_03_07 = "Vocês precisam passar por essa porta. Andem logo.",--You need to walk through those doors. Chop-chop.
	pln_flt_08_02 = "Beleza, vocês matar todo mundo desse prédio. Achem eles.",--Okay, you need to clear the joint from the remaining thugs. Find them.
	pln_flt_11_02 = "Eita, isso é uma escova grande... Posso ter ela?",--Hey now, that's a big toothbrush... Can I have it?
	pln_flt_07_02 = "Tá, hora de meter o louco. Coloquem as máscaras e vamos nessa!",--Okay, time for our move. Get the masks on and let's go!
	pln_flt_16_03 = "Tá, vamos precisar de usar as serras para tirar a sala do andar.",--Okay, we'll need to use the saws to cut the room free from the floor.
	pln_flt_06_03 = "Fiquem atentos. Isso vai ser tenso.",--Stay on your toes. This's gonna be tense.
	pln_flt_26_03 = "Hora de pegar a C4 e plantar nos andares acima da Sala de Pânico.",--Time to pick up the C4 and then plant it on the floors above the panic room.
	pln_flt_03_08 = "Pessoal, não deixa eles esperando. Entrem lá.",--Guys, don't keep them waiting. Get in there.
	pln_flt_13_03 = "Isso foi intenso, mas isso foi preciso. Pegue a chave e volta pra Sala de Pânico.",--That was intense, but you did what was needed. Pick up the key and head back to the panic room.
	pln_flt_04_03 = "Entrem lá e fazem o trato.",--Get in there and get the deal started.
	pln_flt_27_03 = "Ainda precisamos mais C4 no quarto andar, pessoal.",--We still need more C4 on the fourth floor, gang.
	pln_flt_26_02 = "Ok, peguem a C4 e plantem em cima da Sala de Pânico.",--Ok, go pick up the C4 and then plant it right above the panic room.
	pln_flt_16_02 = "Hora de cortar essa belezinha. Coloquem as serras.",--Time to cut out this baby. Place the saws.
	pln_flt_35_02 = "Boa. O quarto andar tá feito.",--Good. We're done with the fourth floor.
	pln_flt_48_03 = "Caiam fora daí! Correm!",--Get out of there! Run!
	pln_flt_32_01 = "Ainda precisamos de mais explosivos no quarto e quinto andar. Andem logo.",--We still need more explosives on the fourth and fifth floor. Let's go.
	pln_flt_46_03 = "Descem até a porta do porão, atrás do beco!",--Go down to the basement door in the back alley!
	pln_flt_16_01 = "Beleza, primeiro: prepare as serras.",--All right, first things first: set up the saws.
	pln_flt_34_02 = "Boa. Quinto andar tá feito.",--Good. Fifth floor is done.
	pln_flt_33_01 = "Excelente. Foi o telhado.",--Excellent. That's enough for the roof.
	pln_flt_06_02 = "Tenho um mal pressentimento sobre isso.",--I've got a bad feeling about this.
	pln_flt_50_03 = "Acabamos de fazer o que as pessoas diriam que ia ser impossível. Não há nada que possamos fazer, pessoal. Melhor dos melhores.",--We just did something people would have said was impossible. There's nothing we can't do, gang. Best of the best.
	pln_flt_35_01 = "Beleza, pessoal. Quarto andar já foi.",--That's it, gang. Fourth floor complete.
	pln_flt_24_01 = "Bom trabalho, gente. Com os snipers mortos, Bile vai conseguir fazer a entrega.",--Good job, gang. With the snipers gone, Bile will be able to make the drop.
	pln_flt_07_01 = "Beleza, eu diria que tá na hora de meter bala. Coloquem as máscaras!",--Alright, I'd say it's time to get blastin'. Put your masks on!
	pln_flt_21_01 = "Ok, pessoal, os policiais estão aqui, como esperado. É mais fácil matar eles na rua antes de ter a chance de entrar.",--Okay, gang, cops are here - as expected. It's easier to take them out on street level before they actually storm the building.
	pln_flt_03_03 = "O negociador vai suspeitar se vocês não entrarem.",--The bouncer will get suspicious if you don't walk in.
	pln_flt_39_03 = "Agora esse buraco é bom!",--Now that's a beautiful hole right there!
	pln_flt_03_01 = "O que vocês tão esperando? Entrem logo.",--What are you waiting for? Get inside.
	pln_flt_03_05 = "Gente, qual é da demora? Entrem logo.",--Gang, what's the hold up? Get inside the building.
	pln_flt_33_03 = "Boa, isso deve servir pro telhado.",--Nice, that should do it for the roof.
	pln_flt_24_03 = "Durmam bem, snipers! Bom trabalho, pessoal. Agora, vão pegar a C4.",--Good night snipers! Good job, guys. Now, time to get that C4.
	pln_flt_27_01 = "Bom trabalho, mas precisamos de mais do quarto andar.",--Good job, but we need some more on the fourth floor.
	pln_flt_04_01 = "Entrem na sala e faz o trato das drogas.",--Head inside the room and go through with the drug deal.
	pln_flt_38_03 = "Cê viu aquilo? É desse jeito que a gente faz.",--Did you see that? That's how we do things.
	pln_flt_21_02 = "A policia chegaram. Eles vão entrar se tiverem a chance, então, não deixem eles entrarem.",--The police are here. They'll storm the building if they get the chance, so maybe stop them before they can.
	pln_flt_50_02 = "Agora, se isso não vai fazer as pessoas falarem, não sei o que vai. Isso foi foda, pessoal, e vamos ter um dinheiro bom depois dessa.",--Now if that won't get people talking, I don't know what will. That was amazing, gang, and we're getting a juicy payday out of it.
	pln_flt_26_01 = "Peguem a C4 e plantem no andar em cima da Sala de Pânico.",--Pick up the C4 and then plant it on the floor right above the panic room.
	pln_flt_03_04 = "Vamos. Entrem.",--Come on. Get inside.
	pln_flt_49_03 = "Rápido, pessoal!",--Faster guys!
	pln_flt_43_02 = "Pronto. Tô pronto pra levar essa belezinha pra fora.",--That's it. I'm ready to lift this baby out of here.
	pln_flt_03_02 = "Não fiquem aí enrolando, entrem logo.",--Don't just stand around, get in there. 
	pln_flt_33_02 = "Já foi o telhado.",--That's good enough for the roof.
	pln_flt_07_03 = "Tá na hora. Coloquem a máscara e vamos fazer isso.",--It's time. Put on the masks and let's do this.
	pln_flt_11_03 = "Que merda é essa? Uma escova gigante? Eu poderia usar algo assim.",--What the hell is that? An enormous toothbrush? I could really use something like that.
	pln_flt_44_03 = "Nós conseguimos!",--We have a lift-off!
	pln_flt_42_03 = "Os policiais estão vindo dos andares de cima, vocês tem que ir pra cima e defenderem!",--The cops are coming in from the upper floors, you gotta move up and find a bottleneck to defend!
	pln_flt_34_03 = "Já foi o quinto andar. Excelente.",--That's it for the fifth floor. Excellent.
	pln_flt_05_02 = "Não levanta suspeitas. Façam o que eles te disserem.",--Don't raise suspicion. Do what they tell you.
	pln_flt_43_01 = "Ok, o íman está seguro. Vamos puxar essa joça daqui!",--OK, the winch is secured. Let's pull this package out of here!
	pln_flt_48_01 = "Beleza, vocês passarma do ponto de sem retorno... Só corre! Nem olha pra trás!",--All right, you're past the point of no return. ... Run! Run! Don't look back!
	pln_flt_31_01 = "Quase pronto, gente. Só mais alguns no telhado e estamos de boa.",--Almost there, gang. Just some more on the roof and we're good.
	pln_flt_21_03 = "Policiais vindo. Sugiro que vocês descem e cuidem da entrada frontal. Desse jeito, vocês podem parar eles entrarem.",--Cops incoming. I suggest you head down and take them heads-on by the front entrance. That way you can stop them before they flood the building.
	pln_flt_42_02 = "Beleza, gente, lá vem eles! Achem uma posição boa para se protegerem! Tá quase pronto!",--Okay, gang, here they come! Find a good position to defend yourselves! We're almost done!
	pln_flt_04_02 = "Vocês precisam agir como se fosse uma negociação de droga.",--You need to act like you're there to go through with the drug deal.
	pln_flt_05_01 = "Esses caras não estão de brincadeira. Não seja um idiota e entra na sala.",--These guys aren't kidding around. Don't act dumb and go in the room.
	pln_flt_05_03 = "Parem de enrolar e entrem na sala.",--Stop walking around and go inside the room.
	pln_flt_11_01 = "Eita, isso é uma escova de dente gigante... Eu quero.",--Whoah, that's a big toothbrush... I want it.
	pln_flt_13_01 = "Vocês mataram esse doido do caralho. Agora, pega a chave dele e volta pra Sala de Pânico.",--You got that crazy bastard. Now, get the key from him and return to the panic room.
	pln_flt_13_02 = "Bom, cuide do Chavez. Pegue a chave dele e volta pra Sala de Pânico.",--Well, that takes care of Chavez. Pick up the key and get back to the panic room.
	pln_flt_24_02 = "Já era os snipers, gente. Nada vai parar o Bile de soltar a C4 agora.",--That's it for the snipers, gang. Nothing will stop Bile from dropping the C4 now.
	pln_flt_25_01 = "Mas que merda, Ale... Bile! Como você pode errar o telhado? Pessoal, ainda precisamos da C4, então vocês vão ter que pegar. Lembre-se, os explosivos tem que está no andares ao redor da Sala de Pânico.",--God damn it, Ale... Bile! How could you miss the roof? Gang, we still need that C4 so you'll just need to pick it up. Remember, we want the explosives placed around the floors above the panic room.
	pln_flt_27_02 = "Beleza, gente. Só o quarto andar faltando.",--That's it, gang. Only the fourth floor left.
	pln_flt_31_02 = "Planta a última C4 no telhado e deve tá pronto pra explodir.",--Plant the last C4 on the roof and we should be good to go.
	pln_flt_32_02 = "Boa. Agora planta no quarto e quinto andar.",--Good. Now, plant the rest on the fourth and the fifth floor.
	pln_flt_35_03 = "Quarto andar tá pronto. Boa.",--Fourth floor is done. Good.
	pln_flt_36_02 = "Excelente! Agora volta, porque está prestes a explodir.",--Excellent! Now get back, because things are about to blow.
	pln_flt_36_03 = "Bom trabalho, agora saiam daí antes que o prédio caia.",--Good job, now get the hell away from there before it goes off.
	pln_flt_37_03 = "Vamos, pessoal, eu não posso detonar os explosivos com vocês perto.",--Come on, gang, I can't detonate the explosives as long as you are close.
	pln_flt_38_02 = "Eita! Isso foi doido.",--Whoo! That was crazy.
	pln_flt_40_01 = "Tá, gente, hora de aguentar a força até o Bile voltar. Metem chumbo!",--Okay, guys, time to hold the fort until Bile returns. Give 'em hell!
	pln_flt_41_03 = "Bile, tá na hora! Quando tempo vai demorar pra você chegar aqui?",--Bile, you're up! How long before you're here?
	pln_flt_42_01 = "Esse prédio tá parecendo com o queijo cheido de furos! É melhor vocês subirem alguns andares pra ter uma posição melhor.",--The building is opening up like a swiss cheese! I suggest you go up a few floors to get a better tactical position.
	pln_flt_43_03 = "O íman tá no lugar. Hora de dá o fora.",--The magnet is in place. Time to pull it out of here.
	pln_flt_44_01 = "Olha só pra essa sala voando! Conseguimos, porra!",--Look at that room go! We god damn did it!
	pln_flt_44_02 = "Olha só pra isso! Conseguimos, gente. Conseguimos.",--Would you look at that!? We did it, gang. We did it.
	pln_flt_45_01 = "Bom trabalho, gente! Mas agora vocês precisam sair daí antes desse prédio virar pó.",--Excellent work, gang! Absolutely amazing. But now you need to get out of there before the place collapses.
	pln_flt_45_03 = "Puta dum tabalho bem feito! Agora, caiam fora daí. Esse prédio não vai durar por muito tempo.",--A job well done! Now, get the hell out of there fast. That building won't keep standing for long.
	pln_flt_46_02 = "Vão para o porão, pessoal!",--Get down to the basement guys!
	pln_flt_48_02 = "Corre! Só corre!",--Run! Just run!
	pln_flt_49_01 = "Rápido! Rápido! Pra esquerda!",--Hurry! Hurry! To the left!
	pln_flt_49_02 = "Vai! Vai! Vai! Só corre!",--Go! Go! Go! Just run!
	plt_flt_01_03 = "Beleza, eu tô perto agora, mas tem snipers em todo canto. Vou precisar que vocês cuidem deles antes de soltar a C4.",
	plt_flt_02_01 = "Ei! Cadê a ajuda que preciso? Eu tô encurralado aqui!",
	plt_flt_02_03 = "Ei! Eu tô sendo pipocado aqui! Desde que esses snipers estão vivos, eu não posso chegar perto e fazer a entrega!",
	plt_flt_05_02 = "Oh, puts, eu errei... Gente, a C4 caiu na varanda. Eu sinto muito.",
	plt_flt_07_03 = "Eu tô aqui, pessoal, mas eu não posso chegar perto desde que o telhado tá cheio de políciais.",
	plt_flt_09_01 = "Parece que o telhado tá limpo. Bom trabalho. Indo aí agora.",
	plt_flt_09_02 = "Tá boa. Tô indo aí.",
	plt_flt_10_02 = "Eu tô abaixando o íman.",
	plt_flt_11_01 = "Ok, o íman tá no lugar, só preciso que vocês conectam ela no topo da sala de pânico.",
	plt_flt_14_02 = "Beleza! Tô dando fora!",
	plt_flt_14_01 = "Ok, eu tô dando o fora com essa merda. Vocês distraiem os políciais!",
	plt_flt_10_01 = "Ok, abaixando o íman.",
	plt_flt_05_03 = "Sinto muito, cavalheiros. Eu acidentalmente soltei a C4 na varanda... Sinto muito.",
	plt_flt_02_02 = "Pessoal, me protegem! Esses Snipers tão sendo um pé no saco para eu chegar perto. Vocês precisam matar eles!",
	plt_flt_01_02 = "Tô chegando, gente, mas os políciais trouxeram muito Snipers nos telhados próximos do prédio. Vou precisar que vocês cuidem deles antes de eu fazer a entrega.",
	plt_flt_05_01 = "Varanda. A C4 caiu na varanda. Eu errei o telhado. Sinto muito por isso.",
	plt_flt_06_02 = "Íra! A C4 caiu no telhado como no plano.",
	plt_flt_06_01 = "Cavelheiros, a C4 tá no telhado.",
	plt_flt_06_03 = "Tudo certo! A C4 caiu no telhado.",
	plt_flt_01_01 = "Ok, tô na área, mas os políciais trouxeram muitos Snipers nos telhados próximos do prédio. Vocês precisam se livra deles antes que posso soltar a C4.",
	plt_flt_07_01 = "Ok, tô de volta, mas não posso fazer nada com muita polícia em todo canto. Vocês precisam limpar o telhado.",
	plt_flt_07_02 = "Meu Deus, tem muita polícia aí! Não posso fazer nada, vocês vão ter que dá um jeito nisso.",
	plt_flt_09_03 = "Beleza, isso deve servir! Entrando.",
	plt_flt_10_03 = "Abaixando o íman agora.",
	plt_flt_11_02 = "Abaxei o íman, mas preciso que vocês conectam.",
	plt_flt_11_03 = "O íman tá onde deve, mas vou precisar da ajuda de vocês para conectar.",
	plt_flt_14_03 = "É isso! Tô dando fora!",
	pln_flt_01_03 = "Chegamos, gente. Logo ali é o prédio do Chavez.",
	pln_flt_01_02 = "Aqui estamos, gente. Prédio do Chavez.",
	pln_flt_02_01 = "Entram lá.",
	pln_flt_09_01 = "Vai pra sala de pânico, tá no terceiro andar.",
	pln_flt_10_02 = "Encontrado não é roubado, gente. Encontrado não é roubado.",
	pln_flt_12_03 = "Tá, a porta tá trancada. Vamos precisar de uma chave. Acho que achar o Chavez é achar a chave. então procura por ele.",
	pln_flt_14_02 = "Usa a chave para abrir a porta vermelha.",
	pln_flt_17_02 = "Prepare as serras. Dois na sala de pânico e dois na de baixo.",
	pln_flt_18_01 = "Tenha certeza que as serras tão cortando. Se um quebrar, conserta assim que possível. Não podemos ficar aqui por muito tempo.",
	pln_flt_19_01 = "Vocês tão de olho nas serras? Elas tão cortando?",
	pln_flt_19_02 = "Lembra de manter as serras funcionarem. Elas podem quebrar.",
	pln_flt_19_03 = "As serras ainda tão cortando?",
	pln_flt_20_01 = "As serras terminaram, ótimo.",
	pln_flt_22_02 = "Bom trabalho, gente, agora precisamos dos explosivos do Bile. Me dá um momento. Ô Bile, tá na hora. Falta quanto tempo para você soltar a C4?",
	pln_flt_23_01 = "Ouviram isso, gente? Bile vai soltar a C4 no telhado daqui a pouco.",
	pln_flt_29_01 = "Ótimo. Só falta o quinto andar.",
	pln_flt_32_03 = "Beleza. Agora só precisa o quarto andar e o quinto.",
	pln_flt_34_01 = "Já tá bom pro quinto andar. Bom trabalho.",
	pln_flt_38_01 = "Isso foi doido! Até tremeu as estantes de onde eu tô sentado!",
	pln_flt_39_02 = "Esse é belo de um buraco! É perfeito!",
	pln_flt_40_02 = "Hora de proteger, gente! Bile tá vindo!",
	pln_flt_41_02 = "Bile! Hora de voltar e pegar a carga. Por quanto tempo você pode voltar?",
	pln_flt_45_02 = "Bom trabalho! Agora só dá o fora daí antes que esse lugar vira pó. Vamos!",
	pln_flt_46_01 = "Todo mundo, pro esgoto!",
	pln_flt_47_01 = "Todo mundo, pro esgoto!",
	pln_flt_40_03 = "Continuem atirando, pessoal! Bile está voltando daqui a pouco!",
	pln_flt_47_02 = "Pro porão, gente!",
	pln_flt_47_03 = "Vão pro porão que tá no beco de trás!",
	pln_flt_41_01 = "Bile, tá pronto para pegar a carga?",
	pln_flt_39_01 = "Esse buraco é GRANDE! Perfeito!",
	pln_flt_37_01 = "Fica longe dos explosivos.",
	pln_flt_36_01 = "Ok, é isso! Agora se afasta, esse lugar tá aprestes a explodir!",
	pln_flt_31_03 = "Beleza, gente, só falta o telhado.",
	pln_flt_28_03 = "Ótimo. Só o quinto andar e o telhado restando. Vamos logo, pessoal.",
	pln_flt_23_03 = "Bile vai soltar a C4 no telhado do prédio. Tenha certeza de pegar logo quando chegar.",
	pln_flt_22_03 = "É isso, gente. Vamos nessa. Só me dá um segundinho. Ei, Bile, tá na hora do C4. Quão rápido você pode vir pra cá?",
	pln_flt_18_03 = "Fica de olho nas serras ou algo assim. Precisamos fazer isso rápido.",
	pln_flt_14_03 = "Hora de abrir a porta vermelha.",
	pln_flt_10_01 = "Eita, isso é um belo de cocaína que eles tem. É uma boa pegar isso, se você me perguntar.",
	pln_flt_15_02 = "Vocês ainda precisam pegar a chave e quero dizer achar Chavez.",
	pln_flt_15_03 = "Ainda precisamos da chave do Chavez para entrar nessa porta. Ache ele.",
	pln_flt_15_01 = "Gente, vocês precisam achar o Chavez para pegar a chave. Confia em mim, vocês vão saber quem é quando virem ele.",
	pln_flt_09_03 = "A sala de pânico tá no terceiro andar. Andem logo.",
	pln_flt_02_02 = "Entrem.",
	pln_flt_01_01 = "Beleza, gente, logo a frente é a casa do Chavez.",
	pln_flt_02_03 = "Vamos nessa.",
	pln_flt_09_02 = "Vão para sala de pânico.",
	pln_flt_10_03 = "Chavez não vai ter nenhum uso para essa cocaína mais, então pega se você quiser,",
	pln_flt_12_01 = "Droga, a porta tá trancada. É tranqueira do Chavez, então ele deve ter a chave. Vê se você consegue achar ele no andar mais alto do prédio.",
	pln_flt_12_02 = "Nós não vamos entra por essa porta sem uma chave... Hora de achar o Chavez. Ele tá em comando e deve ter a chave.",
	pln_flt_14_01 = "Boa. Agora abre a porta vermelhas.",
	pln_flt_17_01 = "Prepare as serras na sala de pânico, dois no segundo andar e dois no quarto.",
	pln_flt_17_03 = "Vocês precisam usar as serras pra esse plano funcionar. Dois no segundo andar e dois no quarto. Vamos nessa.",
	pln_flt_18_02 = "Precisamos dessas serras funcionando, isso quer dizer ficar de olho nelas caso elas quebrem.",
	pln_flt_20_02 = "As serras terminaram. Bom trabalho.",
	pln_flt_20_03 = "Finalmente, as serras terminaram.",
	pln_flt_22_01 = "Ok, hora do próximo passo do plano, a C4 do Bile. Esperem, deixa eu ver com ele. Bile, tá aí? Precisamos da C4. Quanto tempo?",
	pln_flt_23_02 = "Vocês ouviram ele. Bile vai entregar a C4 no telhado daqui a pouco.",
	pln_flt_28_01 = "É isso, gente, mas ainda precisamos de mais C4 do quinto andar e do telhado.",
	pln_flt_28_02 = "Ótimo. Agora precisamos mais no quinto andar e no telhado.",
	pln_flt_29_02 = "É isso, só falta o quinto andar.",
	pln_flt_29_03 = "Bom trabalho. Agora precisamos do quinto andar e termine o serviço.",
	pln_flt_30_02 = "Ótimo, gente. Agora precisamos no quarto andar e o telhado.",
	pln_flt_30_03 = "Nós precisamos C4 no quarto andar e no telhado.",
	pln_flt_30_01 = "Bom trabalho, agora precisamos mais no quarto andar e no telhado.",
	
	-- Objetivos
	hud_heist_flat_intro = "Deixe que o Chavez deixa você entrar, depois só entrar no prédio pela porta de trás.",
	hud_heist_flat_intro_hl = "Entre no prédio",
	hud_heist_flat_key = "Localize Chavez, ele tá nos andares mais altos do prédio, com uma touca vermelha. Pegue a chave dele.",
	hud_heist_flat_key_hl = "Ache Chavez e pegue a chave dele",
	hud_heist_flat_lowerm = "Proteja o telhado e o helicópetero enquanto abaixa o íman no buraco.",
	hud_heist_flat_lowerm_hl = "Espere pelo íman ser abaixado",
	hud_heist_flat_panic = "Use a chave para abrir a porta vermelha.",
	hud_heist_flat_panic_hl = "Entre na sala de pânico",
	hud_heist_flat_roof = "Se livre de todos os políciais do telhado.",
	hud_heist_flat_roof_hl = "Limpe o telhado",
	hud_heist_flat_roof2 = "Bile precisa esperar a poeira abaixar, você precisa manter a polícia longe do telhado.",
	hud_heist_flat_roof2_hl = "Defende o helicópetero",
	hud_heist_flat_snipes = "Mate todos os snipers dos telhados vizinhos, assim o helicópetero vai conseguir soltar a C4.",
	hud_heist_flat_snipes_hl = "Mate os Snipers",
	hud_heist_flat_start = "Vai e negocie o trato da droga. Esse é o portão que vai permitir a gente entrar.",
	hud_heist_flat_start_hl = "Negocie o trato da droga",
	hud_heist_flat_wait = "Espere pelo helicópetero soltar a C4 no telhado.",
	hud_heist_flat_wait_hl = "Espere pelo explosivos",
	hud_heist_flat_wait2 = "Proteja o telhado, enquanto o helicópetero volta para pegar a sala de pânico.",
	hud_heist_flat_wait2_hl = "Espere pelo helicópetero retornar",
	hud_heist_flat_winch = "Conecta o íman do helicópetero no topo da sala de pânico.",
	hud_heist_flat_winch_hl = "Conecte o íman",
	hud_heist_flat_drop = "Bile tá voltando com a C4. Aguenta firme.",
	hud_heist_flat_drop_hl = "Espere pela C4",
	hud_heist_flat_door = "A sala de pânico deve tá em um apartamento no terceiro andar.",
	hud_heist_flat_door_hl = "Localize a Sala de Pânico",
	hud_heist_flat_detach = "Serra a sala de pânico de cima e de baixo para desgrudar do andar.",
	hud_heist_flat_detach_hl = "Prepare as serras",
	hud_heist_flat_detach2 = "Proteja a sala e fica de olho nas serras",
	hud_heist_flat_detach2_hl = "Mantenha as serras cortando",
	hud_heist_flat_c4 = "Plante a C4 no telhado, quarto andar e o quinto.",
	hud_heist_flat_c4_hl = "Plante a C4",
	hud_heist_flat_c42 = "Vai pro andar de baixo, longe da C4!",
	hud_heist_flat_c42_hl = "Fique longe da C4",
	hud_heist_flat_escape = "Desce as escadas para o porão e foge pelo esgoto.",
	hud_heist_flat_escape_hl = "Fuga está disponível!",
		})
end)