Hooks:Add("LocalizationManagerPostInit", "alessoehfoda", function(loc)
	LocalizationManager:add_localized_strings({
	-- Nomes e Descrições
	heist_arena = "The Alesso Heist",--The Alesso Heist
	heist_arena_hl = "The Alesso Heist",--The Alesso Heist
	heist_arena_crimenet = "Alesso está na cidade hoje. Ele vai estar tocando na Arena GenSec, e é lá onde vocês estarão indo. Mas o Alesso não é o nosso alvo. A Arena serve como uma segunda fortaleza, e é onde a GenSec está deixando o seu novo cofre - O Cofre do Investimento. Eles acham que são impenetráveis. Vamos provar que eles estão errados.$NL;$NL;» Procure a Arena e Localize a C4$NL;» Plante a C4 na Garagem em baixo dos Cofres $NL;» Hackeie as Pirotécnicas e Detonem a C4$NL;» Perfure o Cofre$NL;» Assegure o Loot e Fuja",--Alesso is in town tonight. He's playing at the GenSec Arena, and that's where we're headed. But Alesso isn't the target. The Arena doubles as a secured fortress, and it's where GenSec are showcasing their new vault - the Investment Safe. They think it's impenetrable. Let's prove them wrong. $NL;$NL;» Search the arena and locate the C4 $NL;» Plant the C4 in the garage beneath the vault $NL;» Hack into the Pyro Booth and detonate the C4 $NL;» Drill the vault bottom $NL;» Secure the loot and escape
	heist_arena_briefing = "A Arena tem um grande andar de segurança da GenSec. Uma parte de exibição para VIPS corporativos, mas ainda com um cofre funcional. Hoje, vamos pegá-lo. Temos um homem infiltrado aqui. Ele amontoou algumas C4 na Arena. Peguem-as, explodam o cofre por baixo e peguem aquele dinheiro sujo dali. Nós temos uma grande estrela tocando aqui hoje. Ninguém menos do que Alesso. Hoje a noite é a última de sua turnê na Costa Leste, e ele prometeu destruir o telhado. Ah, e Wolf - Fique fora da pista de dança. ",--The arena has a huge security floor run by GenSec. Part exhibition for corporate VIP's, but still a working vault. Tonight, we hit it. We got an inside man on this one. He stashed some C4 around the Arena. Gather it, blow the vault from beneath and get that sweet dirty money out. There's a big star playing here. No-one less than Alesso. Tonight's the last night of his sold-out East Coast tour, and he's promised to tear the roof up. Oh, and Wolf - stay off the dance floor.

	-- Legendas
	pln_al1_intro_01_01 = "Bilhetes para o Show do Alesso estavam trocando de mãos por $400! Aconteça o que acontecer, alguém vai ficar rico nisso tudo.",--Tickets for Alesso's show were swapping hands for $400! Whatever happens tonight, someone is getting rich.
	pln_al1_intro_01_02 = "Aqui estamos - A Arena GenSec. Esse show do Alesso é o maior já visto. Vamos fazer isso entrar pra história.",--Here it is - the GenSec arena. This Alesso gig is the biggest show it's seen. Let's make sure it goes down in history.
	pln_al1_intro_01_03 = "Ah! Teve uns ótimos shows aqui. E Alesso é o maior até agora.",--Ah! Been some good gigs here. And Alesso's is the biggest one yet.
	pln_al1_09_03 = "A van teve que sair. Estou mandando o Bile com o helicóptero agora.",--The van has to split. I'm sending Bile in the chopper right now.
	pln_al1_07_03 = "O helicóptero do Bile deve vir logo.",--Bile's chopper should be here soon.
	pln_al1_28_03 = "Tudo certo, tenho o cronograma do show. Vamos fazer isso.",--All right, got the show's schedule. We can do this.
	pln_al1_20_03 = "Último porta do Armário, gangue!",--Our last closet door, gang!
	pln_al1_06_03 = "Nosso infiltrado marcou um duto de ventilação para vocês assegurarem o loot.",--The Inside Man has marked a ceiling vent for you to secure the loot at.
	pln_al1_27_01 = "Ok, gangue. Hora de fazer o nosso show.",--Okay gang. Time to put on a show.
	pln_al1_22_02 = "Bom achado. Mas vão precisar de mais C4. Continuem procurando.",--Good find. But you'll need more C4. Keep searching.
	pln_al1_15_02 = "Aí está um dos Armários. Abram esse Cadeado.",--There's one of the closets. Get picking that lock.
	pln_al1_21_05 = "As paredes são puro concreto, mas ainda da pra ouvir o concerto. Nada para a música, huh.",--The walls are thick concrete, but I can still hear that concert. Nothing stops the music, huh.
	pln_al1_17_03 = "Ali está o último Armário. Lidem com o cadeado.",--And there's the last closet. Deal with the lock.
	pln_al1_39_03 = "Ótimo. Agora, peguem o loot. Vamos finalizar esse trabalho de maneira quieta.",--Great. Now, grab the loot. Let's finish this caper quiet like.
	pln_al1_06_01 = "Assegurem todo o loot no duto de ventilação do teto marcado pelo homem infiltrado.",--Secure all of the loot at the ceiling vent in the closet marked by the Inside Man.
	pln_al1_28_01 = "Estou pegando o cronograma das pirotécnias. Eu vou guiar vocês, e sincronizar com o C4.",--I'm grabbing the pyro schedule. I'll guide you guys through, and time it with the C4.
	pln_al1_16_02 = "Outro Armário. Ótimo. Aquela fechadura não nos dará problemas.",--Another closet. Great. That lock won't give you problems.
	pln_al1_10_01 = 'A polícia tem esse lugar cercado. Vamos ter que "improvisar".',--The cops have this place surrounded. We're going to have to "gracefully improvise".
	pln_al1_56_04 = "Mais C4. Quase lá. Continuem procurando.",--More C4. Almost there. Keep searching.
	pln_al1_30_02 = "Botão da ESQUERDA!",--Console on the left!
	pln_al1_26_01 = "Vão até a cabine de pirotécnia. Andar superior. Corram!",--Head to the pyro booth. Top floor. Hurry!
	pln_al1_43_01 = "Lindo!",--Fanny's!
	pln_al1_33_01 = "O botão da ESQUERDA e o do MEIO. apertem-os!",--The left and the middle console. Hit them!
	pln_al1_41_02 = "Tem um duto transportador ali. Ele vai carregar o loot para...deixe-me ver.",--There's a conveyor chute over there. It can carry the loot to....let me check.
	pln_al1_12_02 = "Os rádios da policia estão ligando. Parece que eles possuem gente na área.",--Cops' switchboard lit up. Guess they had their people in the area.
	pln_al1_36_03 = "Ali está a barriga do Cofre do Investimento. Façam esses cortadores funcionar.",--There's the soft underbelly of the Investment vault. Get the cutter to work.
	pln_al1_21_06 = "Apenas o melhor para nosso garoto, Alesso.",--Only the best for our boy, Alesso. 
	pln_al1_03_03 = "Tudo certo, esse é o último do C4. Desçam, na garagem. Nosso homem infiltrado marcou o lugar que vocês vão precisar explodir.",--All right, that's the last of the C4. Get down to the garage. Our Inside Man has marked the spot you need to blow.
	pln_al1_19_03 = "Ótimo trabalho, gangue! Encontraram outro Armário.",--Great work, gang! Found another closet.
	pln_al1_55_02 = "Vocês conseguiram, vocês pegaram muito dinheiro e conseguiram muita atenção. E a GenSec merece sofrer publicamente.",--You did it, you got a ton of money and got a lot of attention. And GenSec deserve to suffer publicly.
	pln_al1_21_01 = "A GenSec jogou muito dinheiro nesse lugar. Deem uma olhada.",--GenSec pumped a lot of money into this place. Look at it.
	pln_al1_19_02 = "Pessoal! Aí está outro Armário!",--Guys! There's another closet door!
	pln_al1_11_02 = "É isso pelo Stealth. Pelo menos, a multidão não ouviu nada.",--That's it for the sneaking. Thankfully, crowd didn't hear a thing.
	pln_al1_42_01 = "Miso Pawny!",--Miso Prawny!
	pln_al1_35_02 = "Botão da DIREITA. E o da ESQUERDA.",--Right console. And the left.
	pln_al1_18_01 = "Ótimo! Esse é um dos Armários!",--Great! That's one of the closets!
	pln_al1_48_03 = "Vocês precisam assegurar o loot na posição que eu marquei.",--You need to secure the loot at the positions I've marked.
	pln_al1_11_01 = "Bem, lá se vai o plano A. Pelo menos a multidão não ouviu nada.",--Well, there goes plan A. Glad the crowd didn't hear any of that.
	pln_al1_01_03 = "Se conseguirem ir de forma silenciosa, vocês devem conseguir se misturar com a multidão.",--If you can get through this quietly, you should be able to just melt away with the crowd.
	pln_al1_36_02 = "O C4 já fez o seu trabalho. Agora abram aquele cofre. Impenetrável é o meu cu!",--The C4 did its job. Get that vault floor cut open. Impenetrable my ass!
	pln_al1_09_01 = "Não tem motivo pra ficar quieto agora. Helicóptero a caminho!",--No reason to stay quiet now. Chopper's on it's way!
	pln_al1_41_01 = "Eu vi um duto transportador alí. Joguem o loot nele. Ele conecta na cozinha de... esperem.",--I saw a conveyor chute over there. Throw the loot in. It connects to the kitchen of...hang on.
	pln_al1_32_03 = "DIREITA!!",--Right!
	pln_al1_49_02 = "O helicóptero não pode esperar pra sempre, grupo. Levem o loot lá!",--The chopper can't wait forever, crew. Get the loot up there!
	pln_al1_52_03 = "Pegamos nossos sete dólares de volta, gangue. Nossas metas são bem positivas.",--Got our seven bucks back, gang. Stretch goals are good.
	pln_al1_23_02 = "Mais C4, Não é o suficiente. Encontrem o último amontoado. Continuem procurando.",--More C4. Not quite enough. Find the last batch. Keep searching.
	pln_al1_27_02 = "Olhem para aquela multidão. Insano! Certo, foquem no trabalho, vamos dar a eles um show.",--Look at the crowd. Insane. Right, focus on the job, and let's give them a show.
	pln_al1_35_03 = "DIREITA! e... ESQUERDA!",--Right! And...left!
	pln_al1_33_03 = "Apertem os da ESQUERDA e o do MEIO.",--Hit the left and the middle.
	pln_al1_12_03 = "Polícia a caminho. Parece que eles tem muitos caras na vizinhança.",--Cops are on their way. Looks like they had a lot of guys in the neighborhood.
	pln_al1_13_01 = "Polícia chegando perto da arena. Fiquem em pé, isso vai ficar bem complicado.",--Cops are closing in on the arena. Stay on your toes, this will get hairy.
	pln_al1_30_01 = "Ok... botão da ESQUERDA!",--Okay... left button!
	pln_al1_32_01 = "Botão da DIREITA!",--Console on the right!
	pln_al1_28_02 = "Fazendo download do cronograma da pirotécnia agora. Vocês pressionam o botão quando eu falar, entenderam?",--Downloading the pyro schedule. You hit the button I say, got it?
	pln_al1_51_02 = "Nosso cara está esperando para acabar esse show. Só atendar o Interfone quando estiverem prontos. Tenham certeza de que o loot está assegurado.",--Our guy is waiting to shut down the gig. Just answer that intercom when you're ready. Make sure all the loot you wanna take is secured.
	pln_al1_37_02 = "Gangue. Coloquem aquele cortador no chão do cofre. Vamos fatiar aquilo.",--Gang. Get that cutter onto the vault floor. Let's slice that thing open.
	pln_al1_49_03 = "O tempo está passando, gangue. Vocês precisam mover o loot para o contêiner.",--Time is ticking, gang. You have to move the loot to the container to secure it.
	pln_al1_cnc_01_02 = "Alesso está tocando na Arena GenSec. Vamos ensiná-los que nada poderá impedir a Gangue PAYDAY.",--Alesso is playing at the GenSec arena. We're going to teach them that nothing can stop the Payday Gang.
	pln_al1_cnc_01_03 = "Alesso está na cidade hoje à noite. Vamos usar o seu concerto para cobertura e atacar a GenSec em sua própria arena.",--Alesso is in town tonight. Going to use his concert as cover to hit GenSec at their arena.
	pln_al1_38_01 = "Ótimo! O cortador acabou! Lá vem o nosso doce loot!",--Great! Cutter's done! Here comes the sweet loot!
	pln_al1_03_01 = "É isso! Agora plantem a C4 na garagem subterânea. Nosso infiltrado marcou o teto embaixo do cofre. Ali é onde a C4 vai.",--That's it! Now plant the C4 in the underground garage. Our Inside Man has marked the ceiling beneath the vault. That's where the C4 goes.
	pln_al1_32_02 = "Botão da DIREITA! da DIREITA",--Right button! The right!
	pln_al1_34_02 = "MEIO e DIREITA.",--Middle and right.
	pln_al1_33_02 = "ESQUERDA e MEIO!",--Left and middle!
	pln_al1_50_02 = "Deixem o nosso infiltrado saber que estão prontos para sair. Ele irá mover o loot, então tenham certeza de que asseguraram tudo dentro da ventilação.",--Let the Inside Man know when you're ready to de-mask. He'll move the loot, so be sure you secured what you want inside the vent.
	pln_al1_24_03 = "E esse é o último!",--And that's the last of it!
	pln_al1_18_03 = "Vocês veem a porta marcada? Esse é um dos Armários.",--You see that marked door? That's one of our closets.
	pln_al1_50_01 = "Ok, avisem para o nosso Infiltrado que estão prontos para sair. Ele vai mover o loot, então tenham certeza de assegurar tudo.",--Okay, ping our Inside Guy when you're ready to de-mask and get out of there. He'll move the loot, so be sure you secure in the vent what you want to take.
	pln_al1_48_02 = "Lembrem-se de amontoar o loot na ventilação. Eu marquei eles para vocês.",--Remember to stash that loot in the vents. I got them marked for you.
	pln_al1_56_05 = "Bom achado. Mas vão precisar de mais C4. Continuem procurando.",--Good find. But you'll need more C4. Keep searching.
	pln_al1_08_01 = "Ok, o concerto acabou. Tirem a máscara, e se disfarcem com a multidão. Vocês devem poder andar até a porta. A van vai estar esperando por vocês. ",--Ok, the concert is finished. Get those masks off, and blend in with the crowd. You should be able to walk right back out the front door. The van will be waiting for you.
	pln_al1_39_02 = "Tudo certo. Agora vamos levar o loot antes que percebam o que está acontecendo.",--All right. Now let's shift that loot before they realise what's happened.
	pln_al1_53_03 = "Sem caminho de volta. Entrem naquele contêiner, gangue. E esperem que o cabo aguente.",--No other way out. Get into that container, gang. And hope the cable holds.
	pln_al1_21_09 = "Alesso prometeu um show lendário. Eu digo que prometemos um roubo lendário.",--Alesso has promised a legendary gig. I'm promising we'll deliver a legendary heist.
	pln_al1_18_02 = "Tudo certo. Aí está um dos Armários marcados.",--All right. There's one of the marked closets.
	pln_al1_26_03 = "Vão até a cabine de pirotécnia, pessoal. Andar superior.",--Haul ass to the pyro booth, guys. Top floor.
	pln_al1_41_03 = "Aquela ventilação vai transportar o loot para uma das salas de...",--That chute there can transport the loot to the back rooms of...
	pln_al1_12_01 = "Os sinais da polícia estão loucos. Eles devem estar próximo da arena.",--Police signal's going nuts. They must've been deployed near the arena already.
	pln_al1_24_01 = "Boa! Tudo certo, ótimo.",--Nice! All right, great. 
	pln_al1_56_02 = "Mais C4. Não o suficiente. Continuem procurando.",--More C4. Not quite enough. Keep searching.
	pln_al1_14_02 = "Cabeça no jogo, pessoal. Procurem pelo Armário marcados com um X.",--Head in the game, guys. Look for the closets marked with the X.
	pln_al1_40_01 = "Eu vi um duto ali. Joguem o loot ali, e vai chegar até o Lobby.",--I saw a conveyor chute over there. Throw the loot in, and it'll shift it to the lobby.
	pln_al1_01_02 = "Ok gente, se tudo for como o plano, vocês conseguirão sair sem serem notados. Só passem com a multidão.",--Ok guys, if all goes to plan, we should be able to leave unnoticed. Just slip away with the crowd.
	pln_al1_07_01 = "Bile está a caminho com o helicóptero!",--Bile's on his way with the chopper!
	pln_al1_55_01 = "isso foi alto e tomou atenção. Trabalho excelente. Duro para GenSec. Seus novos designs são uma piada.",--It was loud and got attention. Excellent work. Tough for GenSec though. Their new design is a joke.
	pln_al1_02_03 = "Nossa C4 foi amontoada em Armários marcados com um X vermelho. Encontrem-os.",--Our C4 has been stashed in supply closets marked with a red X. Find them.
	pln_al1_01_01 = "Loud ou Stealth - sua escolha. mas se conseguirmos fazer no Stealth, seremos capazes de nos misturarmos com a multidão e sair junto a eles. Fácil e rápido.",--Loud or quiet - your call. But if we can stealth this, we'll be able to blend in and escape with the crowd. Nice and easy. 
	pln_al1_37_03 = "Não se esqueçam do cortador no cofre, ladrões. Cortem por baixo.",--Don't forget to get the cutter onto the vault, heisters. Slice it open from beneath.
	pln_al1_46_01 = "Moxie's Milkshakes!",--Moxie's Milkshakes!
	pln_al1_15_03 = "Ok, aí está um Armário marcado. Abram o cadeado.",--Okay, there's a marked closet. Get working on the lock.
	pln_al1_34_03 = "MEIO, e DIREITA!",--Center. And right!
	pln_al1_49_01 = "Vamos lá, palhaços. Levem as bolsas para a varanda e para o contêiner. O helicóptero está esperando.",--Come on, clowns. Get those bags up to the balcony and into the container. The chopper's waiting.
	pln_al1_06_02 = "Joguem o loot no duto de ventilação no teto marcado pelo nosso infiltrado.",--Stow the loot in the ceiling vent marked by the Inside Man.
	pln_al1_54_01 = "Vocês entraram e sairam sem atrair atenção. A GenSec não vai poder varrer para baixo do tapete. Ótimo trabalho, gangue.",--You got in and out without attracting notice to yourselves. GenSec won't be able to discreetly sweep this under the rug. Great work, gang.
	pln_al1_16_03 = "Segundo Armário. Boa! Abram.",--Second closet. Good. Get it open.
	pln_al1_55_03 = "A GenSec sofreu nas mãos de vocês hoje, e fazer em Loud significa que o mundo todo vai saber disso. Isso é bom.",--GenSec suffered at your hands today, and doing it loud means the world knows it. This is good.
	pln_al1_04_02 = "Bom trabalho. A C4 vai alertar a multidão se não sincronizarmos com as pirotécnias. Vão para o andar de cima na cabine e me passem para o sistema.",--Nice work. The C4 will alert the crowd unless we time it with Alesso's pyrotechnics. Head upstairs and patch me into the tech booth.
	pln_al1_11_03 = "Chega de se manterem quietos! Já é hora de entrarmos pro Show!",--No more quiet. Time to rock out!
	pln_al1_22_03 = "Esse é o primeiro amontoado. Encontrem o resto. Continuem procurando.",--That's the first batch. Find the rest. Keep looking.
	pln_al1_25_02 = "Não esqueçam - a garagem é onde vocês vão plantar toda a C4.",--Don't forget - the garage is where you need to plant the C4.
	pln_al1_04_03 = "Perfeito! Agora, vamos mascarar a explosão sincronizando com as pirotécnias do concerto. Vão até a cabine e me conectem.",--Perfect! Now, to mask the explosions, we need to time the concerts pyros. Get up to the booth and patch me in.
	pln_al1_21_04 = "Sempre quis vir nesse lugar.",--Always wanted to come and hit this place.
	pln_al1_16_01 = "Outra porta. Cuidado com os guardas e câmeras, gangue...",--Another door. Watch the guards and cameras, gang...
	pln_al1_15_01 = "Essa é uma das portas. Destranquem ela caso queiram se manter silenciosos.",--That's one of the doors. Lockpick away if you like it sneaky.
	pln_al1_50_03 = "Quase lá, pessoal. Atendam o inferfone quando estiverem prontos para tirar a máscara e sair. Assegurem o que quiserem primeiro!",--Almost done, guys. Just answer that intercom when you're ready to get your masks off and get out of there. Secure what you want to take first!
	pln_al1_40_03 = "Aquele duto pode transportar o loot para o lobby. Poderá acelerar as coisas.",--That chute there can transport the loot to the lobby. Might speed things up.
	pln_al1_14_03 = "C4 é o que estamos procurando, lembrem-se. Vocês precisam encontrar os Armários marcados com um X.",--C4 is what we're after, remember. You'll find it in the closets marked with the X.
	pln_al1_53_01 = "A polícia tem o lugar cercado. Então vocês precisarão sair com o loot. Vão até lá!",--The cops have this place surrounded. So you're going to be going out with the loot. Get in there!
	pln_al1_05_01 = "Ótimo trabalho! O cofre deve estar exposto agora. Sabem o que fazer.",--Great work! The vault should be exposed now. You know the drill.
	pln_al1_44_01 = "Delaware Popcorn!",--Delaware Popcorn!
	pln_al1_40_02 = "Tem um duto de transporte ali. Ele levará o loot para o lobby.",--There's a conveyor chute over there. It can carry the loot to the lobby.
	pln_al1_30_03 = "ESQUERDA!",--Left!
	pln_al1_21_02 = "Hoje à noite, vamos entrar para a história do Rock and Roll, gangue.",--Tonight, we go down in rock and roll history, gang.
	pln_al1_54_03 = "Uma execução estupenda. Quieta e discreta. A GenSec não vai poder se esconder diante do que aconteceu, ótimo trabalho.",--A superb execution. Quiet and discreet. But GenSec won't be able to hide what happened here. Nice work!
	pln_al1_02_02 = "Procurem pela arena por Armários marcados com um X vermelho. Lá é onde o nosso infiltrado escondeu a C4.",--Check the arena for closets marked with the red X. That's where the Inside Man has stashed the C4
	pln_al1_45_01 = "Capitol Hill Candy!",--Capitol Hill Candy!
	pln_al1_54_02 = "Foi bem feito. Quieto e Efetivo. Excelente trabalho.",--That was superbly done. Quiet and effective. Excellent work.
	pln_al1_cbf_01_01 = "A GenSec tem um cofre novinho - O Cofre do Investimento. Inquebrável, dizem eles, e estão mostrando-o na arena. A porta é feita de um novo componente - Vivinite. Mas tudo tem o seu ponto fraco. Com um pouco de C4 e um cortador circular, podemos roubar o dinheiro por baixo deles.",--GenSec have a brand new vault - the Investment Safe. Unbreakable, they say, and they're showcasing it at the arena. The door is made of their new compound - Vivinite. But everything has a soft spot. With a bit of C4 and a new circular cutter, we can steal their cash out right from beneath them.
	pln_al1_25_03 = "A garagem está em baixo do Cofre do Investimento. É onde vocês precisam plantar a C4.",--The garage is right below that Investment vault. It's where you need to plant the explosives.
	pln_al1_10_02 = "Segurem firme, gangue. O helicóptero vai voltar para pegar vocês.",--Sit tight, gang. The helicopter will be back to pick you guys up.
	pln_al1_47_01 = "Red Squares!",--Red Squares!
	pln_al1_23_01 = "E esse é o segundo amontoado de C4. Quase lá. Encontrem o último.",--And that's the second batch of C4. Almost there. Find the last batch.
	pln_al1_04_01 = "Ótimo! Não temos que alertar a multidão. Então vamos detonar a C4 com as pirotécnias do Alesso. Vão até a cabine e hackeiem ela.",--Great! We don't want to alert the crowd so we're gonna detonate the C4 in time with Alesso's pyrotechnics. Head up to the tech booth and hack in.
	pln_al1_21_08 = "Sintam o baixo.",--Feel that bass.
	pln_al1_09_02 = "Ok, talvez se misturar com a multidão não faz o nosso estilo. Enviando o helicóptero agora!",--Ok, so maybe blending in isn't our style. Sending the helicopter now!
	pln_al1_17_01 = "Essa deve ser a última porta. Quase lá, quase lá...!",--That should be the last door. Almost there, almost there...!
	pln_al1_05_02 = "Fantástico! O cofre está exposto agora. Hora da abrir.",--Fantastic! The vault should be exposed now. Time to crack 'em open.
	pln_al1_31_03 = "O do MEIO!",--The center one!
	pln_al1_14_01 = "Não se esqueçam, a C4 está amontoada nos Armários marcados com um X.",--Don't forget, the C4 is stashed in closets marked with an X.
	pln_al1_23_03 = "Tudo certo. Mais C4. Quase pegamos o que precisamos. Continuem procurando.",--All right. More C4. Almost got all we need now. Keep looking.
	pln_al1_53_02 = "Sem saída pela frente. Rápido! Entrem no contêiner. Vocês vão sair com o loot. Não fiquem pensando no drop, ok?",--No way out the front. Quick! Get into the container. You're leaving with the loot. Don't think about the drop, okay?
	pln_al1_08_03 = "Certo, é isso pelo concerto. Hora de tirar a máscara e se misturar com a multidão. Se tudo for de acordo com o plano, vocês vão conseguir sair pela porta da frente, boa sorte!",--Alright, that's it for the concert. Time to de-mask and blend in with the crowd. If all goes to plan, you'll be able to stroll right out the front door. Good luck.
	pln_al1_27_03 = "A multidão está pesada hoje. Vamos fazer um grande show.",--The crowd is heaving tonight. Let's give them a great show.
	pln_al1_22_01 = "Ótimo. Esse é o primeiro amontoado, mas vamos precisar de mais. Peguem o resto.",--Nice. That's the first batch, but we'll need more. Get after the rest.
	pln_al1_38_02 = "Aquele é o nosso cortador que acabou. Deixem chover o dinheiro!",--That's the cutter done. Let the money rain down!
	pln_al1_52_02 = "Sete dólares! Tudo certo!",--Seven bucks! All right!
	pln_al1_08_02 = "Ok, bem fácil. Só tirem as máscaras, se misturem com a multidão e não teremos problema. A van vai esperar por vocês na entrada.",--Ok, nice and easy. Just get those masks off, blend in with the crowd and we won't have any issues. The van will be waiting for you.
	pln_al1_24_02 = "Isso é toda a C4 que precisamos.",--That's all the C4 we need.
	pln_al1_07_02 = "Estou mandando o Bile para vocês!",--I'm sending Bile your way!
	pln_al1_19_01 = "Ótimo. Nossa segunda porta!",--Great. Our second door!
	pln_al1_13_02 = "Polícia na arena. Fiquem frios, gangue.",--Cops are at the arena. Stay frosty, gang.
	pln_al1_37_01 = "Vamos lá, pessoal. Vocês tem que colocar os cortadores no chão do cofre.",--Come on, guys. You have to get the cutters onto the vault floor.
	pln_al1_56_03 = "Tudo certo. Mais C4. Quase pegamos tudo. Continuem procurando.",--All right. More C4. Almost got all we need now. Keep looking.
	pln_al1_20_01 = "Essa é a última porta!",--That's the last door!
	pln_al1_02_01 = "Procurem a arena por Armários marcados com um X vermelho. Lá é onde as C4 estarão.",--Search the arena for the supply closets marked with a red X. That's where the C4 is.
	pln_al1_03_02 = "Ótimo, agora vamos para a garagem. Nosso infiltrado marcou onde vocês precisam plantar a C4.",--Great, now get down to the garage. Our Inside Man has marked up where you need to plant the c4.
	pln_al1_21_03 = "Se conseguirmos, a imprensa vai ir à loucura. Alesso. Gangue PAYDAY... Badass.",--We pull this off, and the press will go nuts. Alesso. Payday Gang... badass.
	pln_al1_10_03 = 'O telhado não é uma opção, vamos ter que "improvisar"... um pouco.',--The roof is not an option, We're going to have to "improvise"... slightly.
	pln_al1_36_01 = "Caralho.....ótimo trabalho! Ok, ali está o cofre exposto. Cortem ali.",--Holy.....nice work! Okay, there's the exposed vault. Get the cutter on there.
	pln_al1_51_03 = "Quando estiverem prontos para sair, atendam o interfone. Nosso cara vai tirar o loot, então tenham certeza de que pegaram o que querem.",--When you're ready to get out of here, answer the intercom. Our guy will get the loot out, so make sure you've secured what you wanna take.
	pln_al1_05_03 = "Isso foi insano! Tudo certo, voltem para o cofre e vamos acabar o trabalho.",--That was intense! All right, head back to the vault and let's finish the job. 
	pln_al1_13_03 = "Tem polícia por toda a parte. Soltem a batida, pessoal.",--We got cops all over. Drop the beat, guys.
	pln_al1_17_02 = "Aí está o último Armário. Abram. Fiquem quietos.",--That's the last closet. Get it open. Keep it quiet.
	pln_al1_20_02 = "E aí está o nosso último Armário.",--And there is the final closet.
	pln_al1_21_07 = "Ah cara, parece ser um puta show lá dentro.",--Oh man, sounds like a hell of a gig in there.
	pln_al1_25_01 = "Vocês tem que descer na garagem e plantar a C4.",--You gotta get down to the garage and plant that C4.
	pln_al1_26_02 = "Vocês precisam ir para a cabine de pirotécnia. Está no andar superior - vão lá!",--You need to be at the pyro booth. It's on the top floor - get there!
	pln_al1_31_01 = "O do MEIO, pessoal!",--The middle one, guys!
	pln_al1_31_02 = "Botão do MEIO!",--Center button!
	pln_al1_34_01 = "Ok, apertem o do MEIO e o da DIRETA. Vão!",--Okay, hit the middle and right console. Go!
	pln_al1_35_01 = "Botão da DIREITA! E da ESQUERDA!",--Console on the right! And the left!
	pln_al1_38_03 = "O cortador está pronto. Cuidado com a cabeça - lá vem o dinheiro!",--Cutter is done. Watch your heads - here comes the money!
	pln_al1_39_01 = "Boa. Peguem aquele loot rápido. Vamos sair daqui antes que nos notem.",--Nice. Scoop that loot up quickly. Let's get out of here before they notice.
	pln_al1_48_01 = "Não se esqueçam - Coloquem o loot no duto de ventilação.",--Don't forget - stow that loot up into one of the vents.
	pln_al1_51_01 = "Pessoal. Atendam o interfone quando estiverem prontos para sair. O que deixarem para trás ficará para trás.",--Guys. Answer that intercom when you're ready to bail. Whatever you leave behind, stays behind.
	pln_al1_52_01 = "É! Pegamos nossos sete dólares de volta. Chupa essa, parquímetro!",--Yeah! Got our seven bucks back. Suck it, parking meter!
	pln_al1_56_01 = "Mais C4. Quase lá. Continuem procurando.",--More C4. Almost there. Keep looking.
	pln_al1_cnc_01_01 = "A GenSec está mostrando o seu Cofre Inquebrável na arena. Vamos usar o concerto do Alesso para provar que eles estão errados.",--GenSec are showing their unbreakable vault at the arena. We're going to use the Alesso concert to prove them wrong.
	ism_al1_01_01 = "Pisem no Armário quando estiverem prontos.",--Step into the closet when you're ready.
	ism_al1_01_02 = "Entrem no Armário quando estiverem prontos.",--Get into the closet when you're ready.
	
	-- Legendas do cara do show
	pyr_al1_10_09 = "Não estraguem agora. Hora de acertar!",--Don't mess it up now. Time to hit it!
	pyr_al1_09_13 = "Fogo no buraco parceiro!",--Fire in the hole buddy!
	pyr_al1_14_04 = "Bom trabalho, cuzão. Trabalho bom pra caralho.",--(drolly) Good job, fuckface. Great fucking job.
	pyr_al1_19_01 = "(chegando perto do telefone)... então o Sid limpou ele por todo o sanduíche de Keith, e falou que era Maionese! (risadas)",--(coming close to the phone)...so then Sid wiped it all over Keith's sandwich, and said it was just mayonnaise! (laughs)
	pyr_al1_19_04 = "Já falei para vocês sobre o fim de semana que eu e o Jimi traficamos um fardo de grama e uma cabra para fora de Tijuana?",--Did I ever tell you guys about the weekend me and Jimi smuggled a bale of grass and a goat out of Tijuana?
	pyr_al1_01_01 = "Esse é o nosso último show, ouviu? Façam ele bombar.",--This is our final show, y'hear? Make sure it goes with a bang.
	pyr_al1_17_01 = "Algo acabou de se soltar? Verifiquem, e consertem!",--Did something just come loose? Check it, and fix it!
	pyr_al1_09_05 = "Apertem!",--Hit it!
	pyr_al1_11_02 = "Time da cabine. Tá mais pra time fudido.",--Booth crew. More like fuck up crew.
	pyr_al1_07_04 = "Ahhh merda, parceiro. Essas crianças estão indo à loucura. Whoooooooo!",--Ahhh shit, partner. These kids are going fuckin' ape shit. Whooooooo!
	pyr_al1_15_03 = "Bem-vindos a melhor noite da minha vida. Ótimo trabalho a todos!",--Welcome to the greatest night of my fucking life. Great job everyone!
	pyr_al1_18_02 = "O alarme de incêndio acendeu. Merrrrrrrda. Apaguem, agora!",--Fire warning just lit up. Sheeeeeeeeeit. Get it out, now!
	pyr_al1_04_05 = "Time da cabine. É melhor estarem no ponto. Eu dou a palavra, e vocês apertam o botão, Comprende amigo?",--Booth team. You better be on goddamn point. I'll give the word, you'll hit the button. Comprende amigo?
	pyr_al1_10_01 = "Não fodam tudo agora. Apertem!",--Don't fuck up. Hit it!
	pyr_al1_05_06 = "Vocês fizerem um trabalho ótimo aí. Querem entrar no time das ruas?",--You guys did a great job up there. You wanna join the road crew?
	pyr_al1_06_01 = "Cara, tem que fazer o melhor. Cronometragem não significa merda nenhuma se estão usando a munição errada, capische!",--Guy, ya gotta do better. Timing means shit if you're firing off the wrong ammo, capische!
	pyr_al1_19_02 = "Cara, essa música é linda pra caralho. Deveria ser tocada na Igreja.",--Man, this music is fucking beautiful. It should be played in church.
	pyr_al1_01_05 = "Eu ouvi falar que vocês na cabine eram bons. Não me desapontem, ouviram?",--I heard you guys up in the booth were good. Don't let me down, y'hear?
	pyr_al1_02_02 = "Ei, parem de relaxar, entrem no interfone!",--Hey! Put the groupie down, and get on the Intercom!.
	pyr_al1_02_03 = "Ei! Ei, cuzão! Três palavras. Atenda. Porra. do. Interfone.",--Hey! Hey, shithead! Three words. Answer. The. Fucking. Intercom.
	pyr_al1_07_05 = "É, é isso. Ah porra! Isso é lindo!",--Yeah, that's it. Ah fuck! This is beautiful!
	pyr_al1_18_03 = "Eu vejo o fogo e a fumaça daqui. Peguem um extintor e apaguem!",--I can see the fire and smoke from here. Grab an extinguisher and get it out!
	pyr_al1_20_01 = "Ei, limpa cu! O interfone!",--Hey Asswipe! The Intercom!
	pyr_al1_16_06 = "Eu vou estar fudido. Essa tela de pirotécnia está uma baita de uma merda.",--I'll be goddamned fucked. That pyro display was some sorry sack of shit.
	pyr_al1_17_02 = "Wow, acabamos de perder um balde de luzes. Consertem o hardware aí.",--Woah, we just lost of whole bucket of lights. Fix the hardware up there.
	pyr_al1_05_05 = 'Ei, posso conseguir um "hell yeah" para o time da cabine.',--Hey, can I get a hell yeah for the booth team.
	pyr_al1_17_07 = "Uhhh, só...é, algo fudeu. Consertem, pessoal.",--Ummm, just...yeah, something fucked up. Fix it, you guys.
	pyr_al1_10_02 = "Façam certo. Puxem!",--Get it right. Push it!
	pyr_al1_12_01 = "Como vocês conseguem fuder tudo pressionando um botão?!",--How can you fuck up pressin' a goddamn button?!
	pyr_al1_09_02 = "Tudo certo, dropem!",--All right, drop it!
	pyr_al1_10_06 = "Chance de redenção. Vão!",--Chance for redemption. Do it!
	pyr_al1_07_01 = "Cara, isso foi lindo. Muito lindo. Como minha antiga mamãezinha. (sniff)",--Man, that was beautiful. Just beautiful. Like my dear old momma. (sniffs)
	pyr_al1_18_08 = "Merda quente, tem um fogo ali. Vocês da cabine! Lidem com isso!",--Hot shit, there's a fire up there. You in the booth! Deal with it!
	pyr_al1_14_08 = "Eu esperava nada menos do que outra fodida. Porraaaaa.",--I expected nothing less than another fucking fuck up. Fuuuuuuuuck.
	pyr_al1_19_07 = "Veem aquela tatuagem? Consegui isso do próprio rei. Fucking A, cara.",--See this tattoo? Got this off the king himself. Fucking A, man.
	pyr_al1_07_07 = "Eu tenho uma palavra pra vocês: whooooooooooooooooooooo!",--I got one word for you: whooooooooooooooooooooo!
	pyr_al1_09_01 = "Apertem!",--Hit it!
	pyr_al1_19_08 = "Eu estava lá quando os The Cockroaches se separaram. Melhor banda do mundo.",--I was there when The Cockroaches split. Greatest fucking band ever.
	pyr_al1_18_04 = "Tem algo queimando e não tem cheiro de churrasco do Texas. Apaguem o fogo!",--Something's burning y'all and it doesn't smell like no Texas bbq i've ever had. Put that fire out!
	pyr_al1_04_04 = "Vamos para o topo com isso. Agora, quando eu der a palavra, vocês apertam o botão, entenderam?",--We're going over the goddamn top with this. Now, when I give the word, you hit the button. Got it?
	pyr_al1_05_02 = "Isso foi excelente! Wooooo! Excelente.",--That was outstanding! Whooooooo! Outstanding.
	pyr_al1_08_04 = "Porra. Cuzões! Vocês fuderam tudo. Se componham, ou vou tirar vocês daí. Pelos curtos e cachos.",--Fucks sake. Assholes! Fucked it. Shape up, or I'm pullin' you out. By the short and curlies.
	pyr_al1_09_09 = "Agora!",--Now!
	pyr_al1_14_07 = "E outra fodida. Pelo menos vocês são consistentes.",--And another fuck up. At least you're consistent.
	pyr_al1_02_08 = "Atendam o interfone. Não me façam ir até aí, filho.",--Answer the Intercom. Don't make me come over there, son.
	pyr_al1_20_05 = "Atendam o interfone!",--Answer the Intercom!
	pyr_al1_04_01 = "Tudo certo, time da cabine. Quando eu der a chamada, vocês apertam - Entenderam?",--All right, booth team. When I give you the nod, you hit it - you got that?
	pyr_al1_20_04 = "Atendam o interfone, meus filhos!",--Answer the Intercom, son!
	pyr_al1_01_02 = "Eu preciso de todos os cuzões no ponto hoje! Especialmente vocês na cabine.",--I need all y'all assholes on point tonight! Especially you up in the booth.
	pyr_al1_01_04 = "Esse é o último show da melhor turnê da Terra. Não ferrem a lata agora.",--This is the last show of the greatest tour on Earth. Don't screw the pooch now.
	pyr_al1_02_01 = "Ei! Limpa-cus! Parem de coçar seus buracos e atendam o interfone!",--Hey! Asswipe! Stop scratching ya crack and get on the Intercom!
	pyr_al1_03_01 = "(beatbox humano) Atendam. (beatbox humano) O. (beatbox humano) Interfone.",--(human beat-boxing) Answer. (human beat-boxing) The. (human beat-boxing) the Intercom.
	pyr_al1_03_04 = "Não me façam limpar vocês como uma mula do governo. Atendam o interfone.",--Don't make me whip you like a government mule. Get on the Intercom.
	pyr_al1_03_05 = "É! É! Tudo certo, ei, aí na cabine, entrem no Interfone.",--Yeah! Yeah! All right, hey, up in the booth, get on the Intercom.
	pyr_al1_04_02 = "Aqui está o negócio. Vou dar o sinal, e vocês apertam o botão, entenderam?",--Here's the deal. I'll give you the nod, and all you gotta do is hit the button. Got it?
	pyr_al1_04_03 = "Ouçam, vamos colocar esses manos no êxtase total. Quando eu falar, vocês apertam o botão, entenderam?",--Listen up, we're gonna put these folks into goddamn ecstacy. When I say, you hit the button. All right!
	pyr_al1_05_01 = "É! É! Ahhhh caralho! A multidão está amando!",--Yeah! Yeah! Awwwww fuck yeah! Crowd's fuckin' losing it!
	pyr_al1_05_03 = "Incrível! Excepcional! Merda está sendo perdida aqui em baixo!",--Amazing! Outstanding! Shit is being lost down here!
	pyr_al1_05_04 = "Ahhhh Pooooorrrrraaa. Exep-fucking-cional!",--Ohhhh shhhheeeeeeeeeeeeeeeeiiiiiiiiit. Out-fuckin'-standin'!
	pyr_al1_05_08 = "Meu caralhinho! Essa merda foi demais! Whooooooooo!",--Holy motherfuckin' shit! That shit fuckin' rocked! Whoooooooooooo!
	pyr_al1_06_03 = "Que diabos está acontecendo aí, limpando a bunda?!",--What the hell is going on up there, shitwipe?!
	pyr_al1_06_04 = "Vocês estão brincando aí? Porquê estão me tirando do sério aqui! Se ajeitem.",--You guys havin' a circle jerk up there? 'cos you're sure pulling on my shit down here! Get it tight!
	pyr_al1_06_05 = "Seus filhas da puta de merda. Assegurem suas merdas aí.",--You motherfuckin' shitbirds. Secure your shit up there.
	pyr_al1_07_02 = "Irmão, aquilo foi excepcional! Vocês estavam no ponto - whooooooo!",--Brother, goddamn that was outstanding! You guys are on fuckin' point - whoooooooo!
	pyr_al1_07_03 = "Whooooooo! É, cara. É! Whooooooo!",--Whooooooo! Yeah, man. Yeah! Whoooooooooo!
	pyr_al1_07_06 = "É! Essa merda foi apertada. Apertada pra caralho!",--Yeah! That shit was tight. Fuckin' tight!
	pyr_al1_07_08 = "Ótimo trabalho! Cara, essas crianças vão lembrar disso como a melhor noite de suas vidas.",--Great work! Man, these kids are gonna remember this as the greatest night of their lives.
	pyr_al1_08_07 = "Façam certo, ou eu ver vocês fudidos de Austin até Amarillo.",--Get it right, or I'll see you fucked from Austin to Amarillo.
	pyr_al1_09_03 = "E... agora!",--And... now!
	pyr_al1_09_04 = "Coloquem fogo!",--Fire it off!
	pyr_al1_09_07 = "Toquem!",--Hit it!
	pyr_al1_09_10 = "Façam!",--Do it!
	pyr_al1_10_03 = "Foco agora. Apertem!",--Focus this time. Press it!
	pyr_al1_10_04 = "Olho na bola. Disparem!",--Eye on the ball. Fire it!
	pyr_al1_10_05 = "Tirem as mãos da piroca, mãos no botão. Agora!",--Hands off dicks, hands on button. Now!
	pyr_al1_10_07 = "Sem fuder tudo dessa vez. Dropem!",--No fucking it this time. Drop it!
	pyr_al1_10_08 = "Não fodem com tudo de novo. Vão!",--Don't screw the pooch again. Go!
	pyr_al1_11_01 = "Você fudeu, filho.",--You fucked it, son.
	pyr_al1_11_03 = "Vocês fuderam essa merda muito bem, seus cuzões.",--You screwed that pooch good, asshole.
	pyr_al1_12_02 = "Vocês estão fazendo um desastre! Alinhem suas merdas, Filhas da puta!",--You're makin' a disaster here! Straighten your shit, motherfuckers!
	pyr_al1_12_05 = "Cara, vocês são um acidente de trem. Que bagunça do caralho.",--Man, you guys are a train wreck. What a fuckin' mess.
	pyr_al1_13_01 = "Tudo certo. (para alguém fora do telefone) Dwayne, mandem uns cara lá chutarem algumas bundas.",--All right. (to someone off phone) Dwayne, send some guys up there to kick a little ass.
	pyr_al1_13_06 = "Eu já tive o suficiente (para alguém fora do telefone) mandem a segurança lá. Eu quero dedos cortados.",--I've had enough. (to someone off phone) Send security up there. I want fingers pulled.
	pyr_al1_15_02 = "Exce-fucking-lente! Vocês são uma classe mundial (chorando) Classe mundial, ouviram!",--Out-goddamn-standing! You guys are world class (sniffling) World class, ya hear!
	pyr_al1_15_07 = "É assim que se faz um bom show. Ótimo trabalho!",--And that is how you put on a great show. Great work!
	pyr_al1_15_08 = 'Melhor equipe da história da música! Posso conseguir um "hell yeah".',--Best goddamn crew in the history of music! Can I get a hell yeah.
	pyr_al1_16_01 = "Bem, isso foi o pior show de pirotécnia que já vi.",--Well, that was just about the worst goddamn pyro show I've seen.
	pyr_al1_16_03 = "Vocês tem que voltar para a escola de pirotécnia. Que bando de merda!",--You guys need to go back to pyro school. What a bunch of horse crap!
	pyr_al1_17_03 = "Merda. Vocês estão vendo isso? Algo aconteceu aí. Time da pirotécnia - Consertem!",--Crap. You guys seeing this? Something went up there. Pyro team - fix it!
	pyr_al1_17_04 = "Que diabos! Acabamos de perder um feed. Consertem!",--What the hell! We just lost a feed. Fix it you guys!
	pyr_al1_17_05 = "Parece que tem um mal-funcionamento na cabine. Time da pirotécnica, lidem com isso!",--Looks like a hardware malfunction up at the booth. Pyro team, deal with it!
	pyr_al1_17_06 = "Tem algo fudido aí. Pessoal da Piro, vocês precisam dar um jeito nisso.",--Something's fucked up there. Pyro guys, you gotta deal with it.
	pyr_al1_17_08 = "Tem um problema de hardware. Quem consertar vai conhecer o Alesso.",--Just got a hardware problem. Whoever fixes it gets to meet Alesso.
	pyr_al1_18_01 = "Merda! Algo está queimando aí. Apaguem o fogo, rápido!",--Shit! Somethings burning over there. Get that fire out, quick!
	pyr_al1_18_05 = "Não podemos deixar esse lugar em chamas - É a cabine de pirotécnia. Apaguem o fogo!",--We can't have this place on fire - it's the pyro booth. Put it out!
	pyr_al1_18_06 = "Mantenham o piro para o show, pessoal. Apaguem o fogo, gente!",--Keep the pyro for the show, guys. Get the fire dealt with, lickety-spit!
	pyr_al1_18_07 = "Esses equipamentos são caros. Tipo, dez anos de seus salários. Apaguem o fogo!",--That gear's expensive. Like, ten years of your salary expensive. Deal with the fire!
	pyr_al1_18_09 = "Vocês estão cozinhando sanduíche de porco assado? Tirem esse fogo. (Silenciosamente ao fundo) Eu sou um Computador.",--You cooking pork chop sandwiches? Put out the fire. (quietly in the background) I'm a computer.
	pyr_al1_19_03 = "Eu queria que tivéssemos essa música quando eu era criança. Eles estão amando.",--I wish we had this music when I was a kid. They're fucking loving it.
	pyr_al1_19_05 = "Ouçam de um homem mais velho, galera. Não usem drogas. Porém beber e fumar é bom pra caralho.",--Take it from an old man, guys. Don't do drugs. Drinkin' and smokin' is fucking great though.
	pyr_al1_19_06 = "Nós tocamos aqui na época que A Caixa de Vinho de Harry ficava aqui. Era lá nos anos 70.",--We played here back when Harry's Wine Box stood here. That was '73.
	pyr_al1_20_02 = "Ei! Atendam o interfone!",--Hey! Answer the Intercom!
	pyr_al1_20_03 = "Ei ei ei, cuzões! Atendam a porra do interfone!",--Hey hey hey, shithead! Answer the fucking Intercom!
	
	-- Objetivos
	hud_heist_arena_mission11 = "Saia pelo lobby de entrada. Fiquem frios.",--Exit through the lobby entrance. Stay casual.
	hud_heist_arena_pyrofire_mission1 = "Procure na arena por um extintor de incêndio e apague o fogo!",--Search the arena for a fire extinguisher and put the fire out!
	hud_heist_arena_mission9 = "Assegure as bolsas de loot no local designado!",--Secure the loot bags at the designated drop off location.
	hud_heist_arena_mission12_hl = "Fuga Disponível",--Escape Available
	hud_heist_arena_secroom_mission1_hl = "Ligue a Energia",--Turn the power back on
	--hud_heist_arena_mission3_hl = "Não em uso",--Not in use
	hud_heist_arena_mission8 = "Use os cortadores circulares para abrir os cofres por baixo.",--Use circle cutters to open the vaults from beneath.
	--hud_heist_arena_mission4 = "Não em uso.",--Not in use.
	hud_heist_arena_mission13 = "A van está a caminho!",--The van is on its way!
	hud_heist_arena_mission5_hl = "Plante a C4",--Plant the C4
	hud_heist_arena_mission9_hl = "Assegure as Bolsas no Local marcado",--Secure the loot at the drop off
	hud_heist_arena_mission6 = "Quando hackeado, o Bain vai sincronizar a C4 com o concerto de pirotécnia.",--Once hacked in, Bain will sync the C4 with the concert pyrotechnics.
	hud_heist_arena_mission10 = "Junte todos no Armário e coloquem suas roupas de civis.",--Gather everyone into the closet and change back into your civilian clothes.
	--hud_heist_arena_mission4_hl = "Não em uso",--Not in use
	hud_heist_arena_mission12 = "A Fuga já está disponível!",--The escape is now available!
	hud_heist_arena_mission7_hl = "Faça um Bom Show",--Put on a good show
	hud_heist_arena_mission6_hl = "Hackeie o Painel de Pirotécnia",--Hack into the pyro console
	hud_heist_arena_mission7 = "Ouçam as direções dadas pelo gerente do palco. Apertem os botões quando ele falar!",--Listen to the directions given by the stage manager. Press the buttons when he says and put on a good show!
	--hud_heist_arena_mission3 = "Não em uso",--Not in use
	hud_heist_arena_mission5 = "Coloque a C4 nos locais marcados na garagem subterânea.",--Place the C4 on the marked locations in the underground garage.
	hud_heist_arena_secroom_mission2_hl = "Derrubem a Segurança",--Override the security
	hud_heist_arena_mission2 = "Procure pela arena por Armários marcados. Vocês vão encontrar a C4 amontoada dentro deles.",--Search the arena for the marked supply closets. You will find the C4 stashed inside them.
	hud_heist_arena_secroom_mission2 = "O alarme ativou o sistema de segurança dos Armários. Hackeie o computador da segurança para derrubar as travas.",--The alarm has triggered the security system of the supply closets. Hack the security computer to disable these locks.
	hud_heist_arena_mission8_hl = "Abra os Cofres",--Cut open the vaults
	hud_heist_arena_mission11_hl = "Fuga Disponível",--Escape Available
	hud_heist_arena_mission10_hl = "É hora de tirar a Máscara",--It's time to un-mask
	hud_heist_arena_mission2_hl = "Localize a C4",--Locate the C4
	hud_heist_arena_mission13_hl = "Espere pela Van",--Wait for the van
	hud_heist_arena_pyrofire_mission1_hl = "Encontre um extintor de incêndio.",--Find a fire extinguisher
	hud_heist_arena_secroom_mission1 = "A policia desligou a energia para o computador. Virem a alavanca e liguem ele denovo!",--The cops have turned off the power to the security computer. Throw the switch to turn it back on!
		})
end)