Hooks:Add("LocalizationManagerPostInit", "olanoobdopayday", function(loc)
	LocalizationManager:add_localized_strings({
	-- Nomes e Descrições
	heist_safehouse_hl = "The Safe House",--The safe house
	heist_safehouse_briefing = "A Casa Segura é sua casa longe de casa, sua fortaleza, seu lugar de meditação, o lugar onde o seu dinheiro tomará forma. A Safe House lhe oferece um lugar para melhorar suas habilidades em lugares pequenos. Você vai poder testar várias armas, mecânicas como arrombar cofres e desabilitar câmeras, admirar as grandes pilhas de dinheiro dentro do seu cofre, e também comprar diversos recursos para fazer inveja em qualquer patife daqui até a Casa Branca.",--The safe house is your home away from home, your fortress, your place of contemplation, the place where your money takes shape and form. The safe house gives you a place to sharpen your skills in a low-pressure environment. You'll be able to test out various weapons, mechanics like cracking safes and disarming cameras, admire the fat stacks of cash in your vault, and even purchase assets to make the place the envy of every crook from here to the White House.
	heist_safehouse_briefing_2 = "Bem-vindos de volta à sua Safe House.",--Welcome back to the safe house.
	heist_safehouse_crimenet = "Bain construiu uma Safe House.",--Bain has set you up with a safe house.
	
	-- Legendas
	pln_sh_int_78_01 = "Jogue a bolsa na mesa.",--Throw the bag on the table.
	pln_sh_int_64_01 = "Todo mundo gosta de olhar o seu dinheiro dinheiro, certo?",--Everyone likes to check on their money, right?
	pln_sh_int_80_01 = "Coloque sua máscara.",--Put your mask on.
	pln_sh_int_35_01 = "Coloquei aqui algumas bolsas. Você poderá experimentar os pesos diferentes. Ouro é pesado, como você já deve saber. É bom já ir se acostumando e ver o quão longe consegue jogá-las.",--Here I put some bags. You can try out the different weights. Gold is heavy, as you know.  Good to get a feel for them and how far you can throw.
	pln_sh_int_42_01 = "Câmeras. Todo mundo as odeia. Montei uma sala com algumas variações para você treinar o seu Stealth. Não tenha vergonha em falhar e não vai ter ninguém pra atirar em você, o que é bom.",--Cameras. Everybody hates cameras. I set up a room with a couple variations for you to test your stealth. No shame in failure and also no one shooting at you, which is nice.
	pln_sh_int_38_01 = "Atire neles. Eles vão voltar pra cima.",--Light 'em up. They will ping back up.
	pln_sh_int_68_01 = "Aqui você pode deixar suas armas modificadas. Vai ser uma puta prateleira.",--Here you can hang all your modified weapons. It will be quite a rack.
	pln_sh_int_59_01 = "Se conseguir o bastante... Talvez possamos melhorar o lugar, huh?",--If you get enough... Maybe we can upgrade this place, huh?
	pln_sh_int_53_01 = "Geralmente é assim, eles vão só acreditar por um tempo assim que o Pager ativar.",--Generally the rule of thumb is, they'll only believe you for a little while once the pager goes off.
	pln_sh_int_48_01 = "Dá uma rodada.",--Give 'em a whirl.
	pln_sh_int_46_01 = "Dispositivos. Poderá testar qualquer coisa que você trouxer para cá.",--Gadgets. You can try out whatever you brought over here. 
	pln_sh_int_74_01 = "Alguém devia colocar aquele lixo pra fora.",--Someone should take out that trash.
	pln_sh_int_72_01 = "Precisamos manter esse lugar aqui em segredo. Não saia falando pra cidade aonde você está ficando.",--We need to keep this place secret. Don't talk around town about where you are staying. 
	pln_sh_int_43_01 = "Só ir no interruptor e selecionar a dificuldade.",--Just go over to the switch and pick the difficulty.
	pln_sh_int_11_01 = "Boa pegada! Você já está pronto pra isso!",--Nice catch! You are ready for this!
	pln_sh_int_10_01 = "Pegue!",--Catch!
	pln_sh_int_22_01 = "Certo, agora essa é a sua Safe House. É aqui que você vai passar os seus tempos de folga. Não é muita coisa no momento, mas dê um pouco de tempo. Eu estou trabalhando nisso. Irei deixá-lo decorar o local da forma que achar melhor.",--Alright, now, this is your safe house, this is where you spend your time off duty. It's not much at the moment, but give it some time. I'm working on it. I'll let you do some decorating yourself soon.
	pln_sh_int_02_01 = "Acredito que devem ter tido umas férias dignas de bons assaltantes. Trabalharam duro, precisavam disso, mas você é preciso mais uma vez.",--I trust you have had a vacation worthy of real heisters. You worked hard, you needed it, but you are needed once again.
	pln_sh_int_40_01 = "Os cofres podem ser perfurados, até arrombados - se você tiver a Habilidade.",--So the safes can be drilled, even picked - if you have the skill.
	pln_sh_int_39_01 = "Vamos ver o que mais. Você poderá testar qualquer objetos aqui - só pegar o Equipamento e achar algo onde ele possa servir.",--Let's see, what else. You can test any of the objects out in here - just pick up the equipment and find something it fits on.
	pln_sh_int_69_01 = "A lavanderia é uma ótima fachada, e ainda é boa pra lavar coisas, como roupas, coletes e dinheiro.",--The laundry is a good front. And good for washing things, like clothes, armor and money.
	pln_sh_int_15_01 = "Vá para dentro e jogue a bolsa na mesa para você poder contar. Espero que tudo esteja aí.",--Go inside and drop the bag on the table so you can count it. I hope everything is there.
	pln_sh_int_13_01 = "Pegue aquela bolsa, é uma pequena quantia em dinheiro para você começar, leve-a para a sala de estar.",--Pick that bag up, it's some cash to start you off, get it to the living room.
	pln_sh_int_77_02 = "Gravei toda a informação, poderá acessar apertando aquele botão.",--I've recorded all of the information, access it by pressing that button.
	pln_sh_int_01_01 = "Bem-vindo de volta! Vê como nem teve que atender o telefone, estou de olho em vocês, como sempre.",--Welcome back! See, you didn't even have to answer the phone, I'm keeping my eyes on you as usual!
	pln_sh_int_25_01 = "Vê a estátua - Senhora Justiça. Entregue-a um pouco de dinheiro.",--See that statue - Lady Justice. Hand her some money.
	pln_sh_int_26_01 = "Desça lá, vou te mostrar um segredo.",--Get down there, I'll show you a secret.
	pln_sh_int_63_01 = "Pode ser bom voltar constantemente.",--It might be worth coming by consistently. 
	pln_sh_int_73_03 = "A Estação da Crime.net é sua passagem para a ação. Vá quando estiver pronto.",--The Crime.net station is your ticket to action. Go when you are ready.
	pln_sh_int_47_01 = "Bolsas de Munição, Bloqueadores ECM, Bolsas Médicas, Trip Mines, Sentinelas.",--Ammo bags, ECM jammers, medic bags, trip mines, sentry guns.
	pln_sh_int_12_01 = "Ótimo! Esse é o dinheiro que enviou. A OVERKILL o agradece!",--Nice! That's the money you sent ahead. OVERKILL thanks you!
	pln_sh_int_61_01 = "Essa Conta Offshore é o seu fundo de saída. Quando sair da cidade você vai ficar feliz que o tenha colocado ali.",--That offshore account is your exit fund. When you skip town you'll be glad you put it right there. 
	pln_sh_int_77_01 = "Se quiser a informação de novo, é só iniciar a mensagem gravada usando o botão.",--If you want the information again, just play the pre-recorded message using the button.
	pln_sh_int_37_01 = "Amo essa sala. Teste suas armas aqui.",--I love this room. Give your weapons a try in here. 
	pln_sh_int_03_01 = "Tem uma sala atrás da cozinha, vai lá, preparei um Kit de Iniciante para você.",--There is a room behind the kitchen, go there, I've prepared the starting kit for you.
	pln_sh_int_04_01 = "Coloquei um Kit de Iniciante lá atrás para você. Vá pegar!",--I got the pre-order kit in the back for you. Go get it!
	pln_sh_int_05_01 = "Ai está, agora coloque a máscara.",--There we go, now put your mask on.
	pln_sh_int_06_01 = "Ok, acredito que esteja me ouvindo alto e claro. Certo, não temos tempo a perder, vamos direto ao ponto.",--OK, I trust you hear me loud and clear. Alright, we don't have any time to waste, let's just get to it.
	pln_sh_int_07_01 = "Primeiro, além do Kit de Iniciante, um outro pacote espera por você no beco de trás.",--First of all, besides from that starter kit, another package is awaiting you in the back alley.
	pln_sh_int_08_01 = "Meu cúmplice vai lhe ajudar. Ele está esperando.",--My accomplice will assist you. He's waiting.
	pln_sh_int_09_01 = "Olhe pra cima.",--Look up.
	pln_sh_int_14_01 = "Pegue. É seu dinheiro que lavei. Tem também um pouco extra pela sua contribuição para a OVERKILL.",--Pick it up. It's your money that I laundered. Some extra in there for your generous contribution to OVERKILL.
	pln_sh_int_16_01 = "Certo, pode contar.",--Alright, count that up.
	pln_sh_int_17_01 = "Ótimo - 25 mil. Gaste bem.",--Cool - 25 large. Spend them well.
	pln_sh_int_18_01 = "Certo, isso deve ser 5 mil para começar.",--OK that should be 5k to start with. 
	pln_sh_int_19_01 = "Uma graninha, veja como um presente de boas-vindas para você começar bem. Acho que você vai conseguir muito mais.",--Some cash, look at it as a welcome gift to get you started. I expect you will pull in much more.
	pln_sh_int_20_01 = "Não se preocupe, ninguém vai te escutar aqui atrás, mas fique quieto para ficar seguro...",--Don't worry, no one will hear you back here. But keep it down to be safe...
	pln_sh_int_21_01 = "Agora pegue o dinheiro.",--Now, pick up the money.
	pln_sh_int_23_01 = "Então como deve saber, não é tudo que a Safe House tem para oferecer, deixe-me te mostrar no que estou trabalhando.",--So, as you surely know, this isn't everything this safe house has to offer, let me show you what I'm working on.
	pln_sh_int_24_01 = "Sei que quer sair e começar a trabalhar, mas tenho que ter certeza de que conhece todos os métodos. O tempo mudou, novos equipamentos, novos brinquedos. Só quero ter certeza de esteja pronto.",--I know you want to get out there and start working, but I have to make sure you know the drill. Times change, new equipment, new toys. I just want to make sure you got it all in check.
	pln_sh_int_27_01 = "Cavalheiros... Bem-vindos à sua Safe House.",--Gentlemen... Welcome to your safe house.
	pln_sh_int_28_01 = "Ok, na sua esquerda ficará a Estação Crime.net. Aqui é onde você pegará seus contratos. Na direita são as suas Câmeras de Segurança. Olhe por aí e eu te conto mais.",--OK, to your left is your Crime.net station. This is where you get your contracts. To your right are your security cameras. Look around and I'll tell you more.
	pln_sh_int_29_01 = "É, seguindo reto terá seu próprio cofre. Vamos encher ele.",--Yeah, straight ahead there is your own private vault. We're gonna stack that up.
	pln_sh_int_30_01 = "Lá na frente - seu Cofre. Na sua direita vai ter o seu Sistema de Câmeras. Na esquerda vai ter a sua Estação Crime.net. Vamos começar!",--Down there - your own vault. To the right is your camera system. Left your Crime.net station. Let's roll.
	pln_sh_int_31_01 = "Bem-vindo à Crime.net. Essa é sua comunidade no crime. Eu irei te mandar contatos crimonosos de toda a DC procurando por gente igual a você. Essa rede é toda construída baseada em confiança e dinheiro.",--Welcome to Crime.net. This is your crime community. I will hook you up with crime contacts all over DC looking for guys like you. This net is built on mutual trust and money.
	pln_sh_int_31_01b = "Estive fazendo isso por mais de dois anos. Deve ter um monte novos contatos para você fazer sozinho.",--We've been growing this for over two years. There should be plenty of new contacts for you to make on your own as well.
	pln_sh_int_32_01 = "Você tem um novo contato. Seu nome é Vlad. Procure ele na Crime.net para vermos o que ele tem para nós.",--You got a new contact. His name is Vlad. Look him up on Crime.net and let's see what he can set us up with.
	pln_sh_int_33_01 = "Pessoal, novo contato na Crime.net. É um político desonesto com ambição. Chamamos ele de O Elefante por enquanto. Deem uma olhada.",--New contact on Crime.net, guys. Got a shady politician with ambition. We call him The Elephant for now. Look him up.
	pln_sh_int_34_01 = "A Crime.net foi atualizada. Tem um novo chefão das drogas na cidade. Seu nome é Hector Moralez. Deem uma olhada.",--Your Crime.net is updated. There is a heavy duty drug cartel head in town. His name his Hector Moralez. Look him up.
	pln_sh_int_36_01 = "Portas. Poderá experimentar elas também. Tenha em mente de que há muitos jeitos de abrir uma. No nosso ramo, fechar portas é inútil - Abrir elas é o que importa.",--Doors. You can try these out too. Keep in mind that there are lots of ways to get one open. In our line of work, closing doors is pointless - opening 'em is what matters.
	pln_sh_int_41_01 = "Eu sei que você já é ótimo nisso, mas sempre é bom praticar, certo?",--I know this is elementary for you, but practice is practice, right?
	pln_sh_int_44_01 = "Boa sorte - esses negócios são complicados.",--Good luck - those things are tricky.
	pln_sh_int_45_01 = "No campo, se ativar um alarme, os policiais virão correndo. DC possui um monte deles.",--In the field, if you trip an alarm, the cops come buzzing. DC's got a lot of them.
	pln_sh_int_49_01 = "Ah é. Pagers.",--Oh yeah. Pagers. 
	pln_sh_int_50_01 = "Negócio complicado. A GenSec começou a mandar todos usá-los.",--Tricky business. Gensec started mandating everyone wear 'em.
	pln_sh_int_51_01 = "Montei um pequeno teste para você ver como isso irá funcionar.",--I set up a little test case for you to see how these work.
	pln_sh_int_52_01 = "Você vai ter que responder o pager bem rápido também.",--You'll wanna answer the pager before too long.
	pln_sh_int_54_01 = "Vivendo em tempos emprestados, por assim dizer.",--Living on borrowed time, as it were.
	pln_sh_int_55_01 = "Mas porra, se você é bom - é disso que você precisa.",--But hell, if you're good - that's the edge you need.
	pln_sh_int_56_01 = "Agora se você mente bem... É um outro jogo.",--Now if you're a good liar... That's a whole other ballgame.
	pln_sh_int_57_01 = "Oh. O melhor lugar da Safe House. O Cofre.",--Oh. The best room in the safe house. The vault.
	pln_sh_int_58_01 = "Seu dinheiro está aqui. Seu dinheiro para gastos está junto naquela mesa.",--Your money is here. Your spendable cash is piled on that table.
	pln_sh_int_60_01 = "Por enquanto só aproveite a vista. Vamos colocar mais coisas aqui, eu prometo.",--For now, just enjoy the view. We'll put more in here, I promise.
	pln_sh_int_62_01 = "Caso contrário, alguma pergunta? Tenho certeza de que poderá descobrir o resto. Pode vir aqui sempre que quiser.",--Otherwise, any questions? I'm sure you can figure out the rest. Feel free to come here whenever you want.
	pln_sh_int_65_01 = "Aqui é sua Área de Máscaras. Bem autoexplicativo.",--Here's your mask area. Pretty self-explanatory.
	pln_sh_int_66_01 = "Óbvio que poderá customizar máscaras igual consegue customizar as armas.",--Of course you can customize masks like you can customize weapons.
	pln_sh_int_67_01 = "Vamos pendurar todas as suas máscaras completas bem aqui.",--We'll hang all your completed masks right here. 
	pln_sh_int_70_01 = "Amo esse lugar. Policiais não passam por aqui com muita frequência.",--I love this place. Cops don't swing by too often.
	pln_sh_int_71_01 = "Mas fique disfarçado. Nunca se sabe quem está olhando.",--Keep a low profile though. Never know who is looking.
	pln_sh_int_73_01 = "Entre na Estação Crime.net para sair daqui.",--Hit the Crime.net station to get out of here.
	pln_sh_int_73_02 = "Vá para a Crime.net quando estiver pronto.",--Go hit up Crime.net when you are ready.
	pln_sh_int_75_01 = "Certo, é hora de ir.",--Alright, time to get to it.
	pln_sh_int_76_01 = "Vamos nessa.",--Let's do this.
	pln_sh_int_77_03 = "Se perdeu alguma informação, só aperte o botão para iniciar uma mensagem gravada.",--If you missed any info, just use the button to play a pre-recorded message.
	pln_sh_int_77_04 = "Quando você voltar na próxima vez não estarei aqui, mas pode sempre apertar aquele botão para iniciar uma mensagem gravada.",--When you return next time I won't be here, but you can always press that button to play a pre-recorded message.
	pln_sh_int_79_01 = "Saia para o beco.",--Get out to the alley.
	
	-- Objetivos
	hud_safehouse_tut4_hl = "Pegue o seu Kit de Iniciante",--Get your starter kit
	hud_safehouse_tut8 = "Dê a Senhora Justiça o que ela merece e entre no porão.",--Give lady Justice what she deserves and enter the basement
	hud_safehouse_tut8_hl = "Dê dinheiro para a Senhora Justiça",--Give lady Justice money
	hud_safehouse_tut1 = "Entre no Estabelecimento Bodhi's Lavagem à Seco.",--Enter the Bodhi's dry cleaning establishment
	hud_safehouse_tut7_hl = "Pegue o Dinheiro",--Pick up the money
	hud_safehouse_tut2_hl = "Espere o Bain ligar para você",--Wait for Bain to call you
	hud_safehouse_tut10_hl = "Pegue o seu Kit de Iniciante",--Get your starter kit
	hud_safehouse_tut5_hl = "Vá para o Beco",--Go to the alley
	hud_safehouse_tut9 = "Coloque a sua máscara.",--Put your mask on
	hud_safehouse_tut6 = "Bain quer que você jogue a bolsa que pegou na mesa.",--Bain wants you to throw the bag you picked up on the table
	hud_safehouse_tut3_hl = "Atenda o Telefone",--Answer the phone
	hud_safehouse_tut2 = "Sinta-se em casa e espere o Bain ligar para você.",--Make yourself feel at home and wait for Bain to call you
	hud_safehouse_tut10 = "Bain preparou um kit de iniciante para você.",--Bain has prepared a starter kit for you
	hud_safehouse_tut1_hl = "Entre na Safe House",--Enter the safe house
	hud_safehouse_tut3 = "Já tentou atender o telefone?",--Have you tried answering the phone?
	hud_safehouse_tut4 = "Bain preparou um kit de iniciante para você.",--Bain has prepared a starter kit for you
	hud_safehouse_tut5 = "Bain tem algo para você lá no beco.",--Bain has something more in store for you in the alley
	hud_safehouse_tut6_hl = "Jogue a Bolsa na Mesa",--Throw the bag on the table
	hud_safehouse_tut7 = "Pegue os maços de dinheiro da mesa.",--Pick up the loose cash bundles on the table
	hud_safehouse_tut9_hl = "Coloque sua Máscara",--Put your mask on	
		})
end)