Hooks:Add("LocalizationManagerPostInit", "casinobeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeemgrande", function(loc)
	LocalizationManager:add_localized_strings({
	-- Nomes e Descrições
	heist_kenaz_hl = "Cassino Sorriso Dourado (Golden Grin Casino)",--Golden Grin Casino
	heist_kenaz_full = "Cassino Sorriso Dourado (Golden Grin Casino)",--Golden Grin Casino
	heist_kenaz_crimenet = "O Cassino Sorriso Dourado em Las Vegas possui um item que o Dentista quer. Pegue isso para ele.\n\n» Usem o pré-planejamento para escolher entre uma entrada barulhenta ou furtiva\n» Entrem no cassino\n» Sigam o plano\n» Achem um meio de entrar no cofre \n» Recuperem o saque misterioso para o Dentista",--The Golden Grin Casino in Las Vegas is holding an item of loot that The Dentist wants. Get it out for him.\n\n» Use Pre-Planning to choose a loud or stealthy entry\n» Enter the casino\n» Follow your plan\n» Find a way to get into the vault \n» Recover the mysterious loot for The Dentist
	heist_kenaz_briefing = "Este é um trabalho grande. Irei falando a medida que avançamos, mas o resumo é esse: o Sorriso Dourado tem um cofre grande. Grande. Quero dizer Banco Benevolente grande. Se vocês vão entrar na furtiva, ou vão assalto total, vai ser extremamente díficil. O Dentista não irá falar o que levaremos de lá. Está sendo muito cauteloso sobre isso. Ele apenas disse que assim que terminarmos, nós terminamos. O contrato foi cumprido... o que quer que isso signifique.",--This is a big job. I'll talk you through it as we go, but the skinny is this: the Golden Grin has a big vault. Big. I mean Benevolent Bank big. Whether you sneak in, or go full assault, you're in for a tough time. The Dentist won't say what we're lifting out of there. Being very cagey about that. He just said that once we're done, we're done. The contract is fulfilled... whatever that means.
	
	-- Legendas
	pln_ca1_57_01 = "FGpC está sem energia. Reconectem as tomadas.",--BFD's without power. Reconnect the power sockets.
	pln_ca1_37_01 = "Pessoal, peguem aquele C4.",--Grab that C4, gang.
	pln_ca1_30_02 = "Aí vai o alarme. Sem problema. Plano B. Pessoal, façam um show.",--There's the alarm. No problem. Plan B. Put on a show, gang.
	pln_ca1_125_01 = "Um.",--One
	pln_ca1_03_03 = "Não esqueçam o C4 na limosine. Cara, a polícia está perto. Rápido!",--Don't forget the C4 in the limo. Man, cops are close. Hurry!
	pln_ca1_21_02 = "Aguardente Demônio Rosado? Huh. Achem ele, batizem, sirvam-no.",--Pinky Demon schnapps? Huh. Find it, spike it, serve it.
	pln_ca1_121_01 = "Trabalho incrível! Agora, subam no topo da FGpC e o guincho os levará para segurança. Ou peguem mais saque. A escolha é de vocês.",--Amazing job! Now, climb up on top of BFD  and the blimp will take you to safety. Or grab more loot. Your choice.
	pln_ca1_70_02 = "Gente, a lista de hóspedes. Peguem ela da recepção e vejam quem está no nosso quarto.",--The guest list, guys. Get it from reception and we can see who's in our room.
	pln_ca1_30_03 = "O alarme. Beleza. Hora do Plano B. Pessoal, sem piedade.",--The alarm. All right. Time for Plan B. No mercy, crew.
	pln_ca1_171_03 = "Lembrem-se de parafusar bem o guincho.",--Remember to screw that winch down good.
	pln_ca1_136_01 = "Nossa! Olhem esse lugar! Imaginem todo o saque que podemos levar daqui!",--Whoa! Look at this place! Imagine all the loot we can boost from here!
	pln_ca1_57_03 = "Porra, a FGpC perdeu a energia. Malditos policiais... reconectem as tomadas.",--Damn, BFD  lost power. Damn cops... reconnect the sockets.
	pln_ca1_164_02 = "Também... aquela coisa Italiana... uh... espaguete! Você pode ter quantas latas desejar.",--Also... that Italian stuff... uh... spaghetti! You can have as many tins as you want.
	pln_ca1_154_02 = "Uh, era o número...",--Uh, it was number...
	pln_ca1_103_03 = "Pessoal, vamos lá. Vão para o vestiário do arsenal.",--Come on, gang. Get to the locker room armory.
	pln_ca1_59_02 = "A FGpC faz coisas em seu próprio tempo. Deixem ela cuidar do cofre, vocês cuidam dos policiais chegando perto dela.",--BFD does things in her own time. Let her deal with the vault, you deal with cops getting near her.
	pln_ca1_35_01 = "Aqueles são todos os números necessários para o arsenal. Vão digitar aquele código.",--That's all the numbers needed for the armory. Go enter that code.
	pln_ca1_04_02 = "Oh, coloquem um pouco de gás do sono alí também. Não deixem isso para trás.",--Oh, put some sleeping gas in there too. Don't leave it behind.
	pln_ca1_127_01 = "Três.",--Three
	pln_ca1_76_01 = "Ótimo! Ele deve voltar a jogar em pouco tempo. Esperem ele dar um gole, deixem a natureza trabalhar. Quando ele disparar para a privada, sigam ele e peguem aquele cartão.",--Great! He should be back gambling in no time. Wait for him to take a sip, let nature do its thing. When he dashes off to the crapper, follow him and get that card.
	pln_ca1_109_01 = "Porra! Beleza, esse não era o cofre. Explodam o outro lugar!",--Damn! All right, that wasn't the vault. C4 the other spot!
	pln_ca1_111_03 = "Bile está esperendo para abandonar o guincho. Acendam o sinalizador para ele.",--Bile's waiting to ditch the winch. Light the flare for him.
	pln_ca1_116_03 = "A FGpC irá quebrar se ela ficar muito quente. Mantenham os tanques d'água cheios.",--BFD will break down if she gets too hot. Keep them water tanks full.
	pln_ca1_166_03 = "Vocês podem pegar um pedaço de pão de milho com isso. Gostoso!",--You can get a side of cornbread with that. Yummy!
	pln_ca1_110_03 = "Vocês precisam levar o C4 no Salão de Apostas. Rápido!",--You need to get the C4 down in the Gambling Hall. Hurry!
	pln_ca1_28_01 = "Nós temos todos os três digitos que precisamos para o cofre. Vão lá e digitem o código.",--We've all three digits we need for the vault. Get there and enter the code.
	pln_ca1_40_02 = "Segurem a posição. Bile trará o guincho para vocês a qualquer momento.",--Hold the ground. Bile will have that winch to you any second.
	pln_ca1_163_01 = "Nós temos umas excelentes caudas de lagosta  para vocês aproveitarem.",--We have some excellent lobster tails for you to enjoy.
	pln_ca1_54_02 = "Pessoal, temos que colocar o guincho para funcionar novamente.",--Gotta get that winch running again, gang.
	pln_ca1_131_02 = "Sete!",--Seven!
	pln_ca1_72_01 = "Gente, eu preciso da lista de hóspedes. Me enviem esse arquivos. TI, acesso de internet, enviar. Fácil!",--I need that guest list, guys. Send me those files. IT, internet access, upload. Easy!
	pln_ca1_153_02 = "Essa ventilação vai direto para o Centro de Segurança.",--Its vent goes right to the Security Center.
	pln_ca1_162_04 = "Nosso Buffet de coma tudo o que puder agora está aberto, e queria ter certeza de que você saiba.",--Our All You Can Eat buffet is now open, and I wanted to make sure that you knew.
	pln_ca1_55_03 = "Certo. O trabalho disso é mover a FGpC, seu trabalho é mantê-lo seguro.",--Okay. It's thing is moving BFD, your thing is keeping it safe.
	pln_ca1_169_01 = "A FGpC precisa de mais energia! Liguem ela na outra tomada. Mantenham ela funcionando.",--BFD needs more juice! Hook her up to the other socket. Keep it running.
	pln_ca1_104_02 = "Três números coloridos. Procurem pelas maletas de computador.",--Three colored numbers. Look for computer briefcases.
	pln_ca1_33_01 = "Esse é o primeiro número. Precisam de mais dois.",--That's the first number. Need two more.
	pln_ca1_164_03 = "Nós esquentamos tudo no microondas para que estejam o mais quente e fresco possível.",--We microwave everything so it is as hot and fresh as you can possibly want.
	pln_ca1_16_01 = "Agora achem um terminal na TI com acesso a internet. Enviem esses dados para mim.",--Now find a terminal in IT with internet access. Upload that data to me.
	pln_ca1_136_03 = "É brega, mas é divertido, e eles sabem. Pessoal, bem vindo a Vegas.",--It's tacky, but it's fun, and knows it. Welcome to Vegas, gang.
	pln_ca1_150_02 = "As plantas estão nos arquivos. Meu palpite são as áreas somente para funcionários.",--The blueprints are in the archives. My guess would be the employee only areas.
	pln_ca1_28_02 = "Aqueles são os três dígitos do código. Sigam para o cofre, vamos ver se eles funcionam.",--That's all three digits for the code. Head to the vault, let's see if they work.
	pln_ca1_156_01 = "Ótimo! Essa é a porta aberta! Só falta desativarem os lasers.",--Great! That's the door open! Only thing left is disabling the lasers.
	pln_ca1_135_02 = "Caramba! Você está sortudo!",--Hot damn! You're on a hot streak!
	pln_ca1_113_01 = "Bom trabalho! Agora reativem a FGpC!",--Good job! Now reactivate BFD!
	pln_ca1_166_01 = "Nós temos arroz. Nós temos fritas. Nós temos purê de batata. Nós temos grãos.",--We got rice. We got fries. We got mashed potato. We got grits.
	pln_ca1_116_01 = "A FGpC precisa de refrigeração. Reabasteçam os tanques com água. Rápido!",--BFD needs cooling. Refill the tank with water Hurry!
	pln_ca1_114_03 = "A FGpC já bebeu um tanque inteiro de líquido de refigeração. Pessoal, encham o tanque. O banheiro tem água.",--BFD's guzzled a whole coolant tank already. Fill her glass, gang. Bathroom's have water.
	pln_ca1_91_01 = "Um já foi, faltam mais dois. Achem os outros números e poderemos ter fácil acesso ao cofre.",--One down, two more to go. Find the other numbers and we get easy access to the vault.
	pln_ca1_121_03 = "Incrível! Apenas subam na FGpC e podemos chamar de trabalho feito. Ou fiquem para trás se quiserem limpar o lugar.",--Amazing! Just climb up onto BFD and we call it a job done. Or stay behind and really pick the place clean.
	pln_ca1_75_02 = "Esperem. Eu tenho o número de celular dele. Deixe-me chamá-lo, tentarei distraí-lo. Fiquem prontos para encher o copo dele.",--Wait. I have his cell number. Let me call him, try and distract him. Get ready to fill his glass.
	pln_ca1_123_02 = "O código é...",--The code is...
	pln_ca1_19_02 = "Nosso cara gosta de uísque Dragão Vermelho. Achem-no, batizem e sirvam-no.",--Our guy likes Red Dragon scotch. Find it, spike it and serve it.
	pln_ca1_130_02 = "Seis",--Six!
	pln_ca1_47_01 = "A furadeira não pode ser jogada através dessa barreira da clarabóia. Precisarão abrí-la do centro de segurança.",--The drill can't be dropped through that skylight barrier. Gotta open it from the security center.
	pln_ca1_162_03 = "Só queria ter certeza de que você saiba que o nosso Buffet Coma Tudo o Que Puder está disponível.",--I just wanted to make sure that you know that our All You Can Eat buffet is now available.
	pln_ca1_128_02 = "Quatro",--Four!
	pln_ca1_159_01 = "Boa noite, senhor.",--Good evening, sir.
	pln_ca1_99_02 = "Droga! Mais lasers de merda. Beleza, não temos tempo para descobrir onde é controlado o sistema. Apenas observem o padrão e atravessem rápido.",--Damn it! More frickin' laser beams. All right, no time to figure out where the system is controlled. Just watch the pattern and hurry through.
	pln_ca1_101_01 = "Beleza, nós conseguimos o que viemos buscar. Vocês podem sair ou voltar, limpar o Grin.",--All right, we got what we came for. You can bail or go back, clean The Grin.
	pln_ca1_153_01 = "A ventilação conecta com o Centro de Segurança",--Its vent connects with the Security Center.
	pln_ca1_89_03 = "O gerente do cassino tem a primeira maleta. O supervisor do cassino tem a segunda. E depois o chefe de segurança. Precisaremos dos três para o código.",--Casino manager has the first briefcase. The Pit Boss has the second. And then the head of security. Need all three for the code.
	pln_ca1_92_01 = "Belo trabalho, segundo número encontrado. Falta só um.",--Good job, that's the second number found. Just one more.
	pln_ca1_167_04 = "E o preço? 18 pratas. O que acham disso, huh?",--And the price? 18 bucks. How you like that, huh?
	pln_ca1_09_01 = "103",--103!
	pln_ca1_123_01 = "Beleza, os números do código são:",--All right, the numbers for the code are:
	pln_ca1_37_02 = "Agora se abasteçam de C4. Vocês irão precisar.",--Now load up on C4. You'll need it.
	pln_ca1_129_01 = "Cinco",--Five
	pln_ca1_94_03 = "Bom trabalho. Nós iremos precisar desses três dígitos para o cofre assim que terminarmos o Centro de Segurança.",--Good work. We'll need these three digits for the vault once we're through the Security Center.
	pln_ca1_20_01 = "Achem e batizem o Jaegerheister. Garrafa verde.",--Find the Jaegerheister and spike it. Green bottle.
	pln_ca1_31_01 = "Procurem pelo arsenal. A informação diz que ele contém C4. Para 'casos extraordinários'. Bem, esse é um desse casos extraordinários.",--Look for the armory. Intel says they're holding C4. For "extraordinary cases". Well, this is one of those extraordinary cases.
	pln_ca1_11_01 = "151",--151!
	pln_ca1_46_03 = "Boa. Agora acendam o pavio e...",--Nice. Now light the fusepaper and...
	pln_ca1_106_01 = "Nós já temos o código. Digitem ele e entrem no arsenal.",--We already got the code. Enter it and get into the armory.
	pln_ca1_50_01 = "Esperem o dirigível chegar com a furadeira.",--Wait for the blimp to get here with the drill.
	pln_ca1_19_01 = "Achem o uísque e batizem-no. Garrafa vermelha.",--Find the scotch and spike it. Red bottle.
	pln_ca1_25_01 = "Peguem aquele cartão de acesso, e vão para o quarto dele.",--Pick up that keycard, and get to his room.
	pln_ca1_10_01 = "104!",--104!
	pln_ca1_78_02 = "Coloquem ele no chão! Amarrem ele!",--Get him down! Tie him up!
	pln_ca1_05_01 = "Agora, nós temos que achar qual sala compartilha uma ventilação com o centro de segurança. Usaremos isso para desmaiar os guardas. Primeiro, peguem as plantas do prédio. Elas devem estar dentro dos arquivos.",--Now, we gotta find out what room shares a vent with the security center. We'll use it to knock out the guards. First, get building blueprints. They should be inside the archives.
	pln_ca1_90_03 = "Verifiquem o escritório do dono para a sua maleta. O supervisor do cassino estará por volta do salão principal. O vestirário é onde provavelmente estará a maleta do chefe de segurança. ",--Check the owners office for his briefcase. Pit boss will be around the main hall. The locker room is where the security chief's briefcase likely is.
	pln_ca1_62_01 = "A FGpC quebrou. Irão precisar de ferramentas para repará-la.=",--BFD broke down. Gonna need tools to repair it.
	pln_ca1_48_01 = "Hackeiem o controle da clarabóia para abrí-la. O que quer que façam, não deixem os tiras desativarem.",--Hack the skylight controls to open it. Whatever you do, don't let the fuzz disable it.
	pln_ca1_intro_02_03 = "Sorriam Dourado, ou fracassem!",--Golden Grin, or bust!
	pln_ca1_37_03 = "Pessoal, peguem tanto C4 quando puderem.",--Grab as much C4 as you can, gang.
	pln_ca1_89_02 = "A primeira maleta fica com o gerente do cassino. A segunda com o supervisor. Para a última, procurem pelo chefe de segurança.",--First briefcase is held by the casino manager. Second by the Pit Boss. Lastly, look for the head of security.
	pln_ca1_90_01 = "Pessoal, as maletas. Verifiquem o escritório do dono. Depois achem o supervisor do cassino. E, por último, procurem próximo do vestiário dos guardas.",--Guys, the briefcases. Check the owners office. Then find the pit boss. And, lastly, check near the guards' locker room.
	pln_ca1_64_02 = "Peguem o saque do Dentista. É por isso que viemos.",--Grab Dentists' loot. That's what we came for.
	pln_ca1_164_04 = "Você gosta de pão. Nós temos pão. Uh... é. Uma porrada de pães... Senhor.",--You like bread. We got bread. Uh... yeah. Assloads of bread... Sir.
	pln_ca1_135_03 = "Quanto vocês ganharam? Podemos aposentar?",--How much did you win? Can we all retire?
	pln_ca1_152_01 = "Consegui. Sala...",--Got it. Room...
	pln_ca1_107_03 = "Não esqueçam de pegar o C4 no arsenal.",--Don't forget to grab C4 from the armory.
	pln_ca1_74_03 = "Nós precisamos localizar o hóspede que está com o cartão. Provavelmente enfiando moedas nos caça-níqueis.",--We need to track down the guest with the keycard. Probably pumping nickels into the slots.
	pln_ca1_41_02 = "Beleza, agarrem aquelas partes do guincho.",--All right, snatch up those winch parts.
	pln_ca1_92_02 = "Segundo dígito para o cofre. Falta achar só o último.",--Second digit for the vault. Just the last to find.
	pln_ca1_34_01 = "Segundo número. Só mais um.",--Second number. Just one more.
	pln_ca1_130_01 = "Seis",--Six
	pln_ca1_intro_01_03 = "Papai precisa de um novo par de sapatos.",--Daddy needs a new pair of shoes.
	pln_ca1_68_01 = "Agora nós precisamso saber quem está nesse quarto, e roubar o seu cartão. Iremos precisar de uma lista de hóspedes. Baixem ela do terminal na recepção. Peguem um Pen Drive.",--Now we need to know who's in this room, steal their keycard. I'll need a guest list. Download that from a terminal in reception. Grab a USB.
	pln_ca1_143_01 = "Salão exterior. Bom para uma bebida gelada...",--Exterior lounge. Nice for a cool drink..
	pln_ca1_54_03 = "Pessoal, o guincho não está funcionando. Arrumem ele!",--Winch isn't working, crew. Fix it!
	pln_ca1_139_02 = "Este lugar é apenas para funcionários. Os escritórios podem ser acessados daqui.",--This place is for staff only. Offices can be accessed here.
	pln_ca1_155_02 = "Vocês acharão o cofre no Centro de Segurança do Sorriso. Sigam para lá.",--You'll find the vault down in The Grin's Security Center. Head there.
	pln_ca1_71_01 = "Isso aí! Baixando. Me dê um momento.",--That's it! Downloading. Give it a moment.
	pln_ca1_115_01 = "Pessoal cuidado! A FGpC superaquecerá se vocês não derem batante água para ela. Peguem do banheiro.",--Watch out gang! BFD overheats if you don't give her enough water. Get it from the bathroom.
	pln_ca1_32_02 = "O C4 está bem aqui. Por que o Sorriso precisa de C4? Só Deus sabe.",--The C4 is right in there. Why does The Grin need C4? God knows.
	pln_ca1_49_01 = "O hack foi interrompido. Retomem ele novamente.",--The hack was interrupted. Get it going again.
	pln_ca1_21_01 = "Achem uma garrafa de aguardente rosa e batizem-na.",--Find the pink schnapps bottle and spike it.
	pln_ca1_134_02 = "Ai! Espero que isso não seja um sinal da sorte que terão hoje.",--Ouch! I hope that's not a sign of the luck you'll enjoy tonight.
	pln_ca1_69_02 = "Vocês já pegaram aquele pen drive? Com certeza tem um na TI.",--You got that USB yet? Surely IT will have one.
	pln_ca1_63_01 = "A FGpC terminou. Agora, desçam no cofre!",--BFD's done. Now, down into the vault!
	pln_ca1_30_01 = "Esse é o alarme. Certo, pessoal. Plano B. Forçaremos nosso caminho.",--That's the alarm. OK, gang. Plan B. Force our way through.
	pln_ca1_22_02 = "Nosso hóspede ama Ocean's Ten vodka. Achem outra garrafa azul e batizem ela.",--Our guest loves Ocean's Ten vodka. Find another blue bottle and spike it.
	pln_ca1_56_01 = "A FGpC precisa de energia - muita energia! Liguem ela num par de tomadas. Elas estão localizadas dentro do cassino. Não deixem elas serem desconectadas.",--BFD needs power - lots of it! Hook her up to a couple of sockets. They're located inside the casino. Don't let them get disconnected.
	pln_ca1_118_02 = "Não sei o que é aquilo, mas nós conseguimos. Agora, voltem para o carro!",--Dunno what that is, but we got it. Now, back to the car!
	pln_ca1_intro_01_01 = "Aqui está. O Cassino Sorriso Dourado.",--Here it is. The Golden Grin Casino.
	pln_ca1_126_01 = "Dois",--Two
	pln_ca1_55_02 = "Aí vai ele. Deixem-no fazer a sua coisa.",--There it goes. Let it do its thing.
	pln_ca1_112_01 = "Sinalizem o dirigível com os fogos de artifício. Vamos dar ao pessoal de Vegas um show para se lembrarem.",--Signal the blimp with the fireworks. Let's give the good folks of Vegas a show to remember.
	pln_ca1_167_03 = "Tudo o que pudere comer, lembre-se. Só 18 pratas.",--All You Can Eat, remember. Just 18 bucks.
	pln_ca1_106_03 = "O código que conseguimos funciona no arsenal. Entrem lá.",--The code we got works on the armory. Get in there!
	pln_ca1_63_02 = "Ela acabou! Rápido, desçam no cofe!",--She's all done! Quickly, down into the vault!
	pln_ca1_102_02 = "Pessoal, fodam-se os alarmes. Apenas peguem o saque do Dentista e poderemos terminar.",--Screw the alarms, guys. Just grab The Dentists' loot and we can be done.
	pln_ca1_65_01 = "Excelente! Agora, sigam para a limosine e terminamos isso. Ou peguem mais saque. Sua escolha.",--Outstanding! Now, get in the limo and end this. Or grab more loot. Your choice.
	pln_ca1_105_01 = "Vocês precisam de três dígitos coloridos para entrar no arsenal. Ou advinhar.",--You need three colored digits to enter the armory. Or guess.
	pln_ca1_02_03 = "Nós temos policiais a caminho, então não demorem. Achem o C4! Verifiquem a sala dos guardas.",--We've got cops on the way, so don't dawdle. Find the C4! Check the guard room.
	pln_ca1_74_01 = "Achem o hóspede. Lembrem-se, ele é viciado em caça-níqueis.",--Find the guest. Remember, he's a slot machine addict.
	pln_ca1_102_01 = "Pessoal, esqueçam os alarmes, nós quase acabamos. Peguem o saque do Dentista, e saiam daí.",--Forget the alarms, gang, we're nearly done. Grab The Dentist's loot, and get it out of there. 
	pln_ca1_92_03 = "Segundo dígito para o código. Agora, apenas peguem o último número e estamos feitos.",--Second digit for the code. Now, just get the last number and we're set.
	pln_ca1_90_02 = "O dono provavelmente mantém o dele no seu escritório. O supervisor do cassino próximo ao salão principal. Chefe de segurança provavelmente mantém o dele em algum lugar próximo ao vestiário.",--The owner likely keeps his in his office. The pit boss will be near the main hall. Security head probably keeps his somewhere near the locker room.
	pln_ca1_110_01 = "Explodam um buraco no chão do Salão de Apostas. Isso nos dará acesso ao cofre.",--Blast a hole in the floor of the Gambling Hall. That'll give us access to the vault.
	pln_ca1_13_01 = "153",--153!
	pln_ca1_46_01 = "Acendam os fogos, e fiquem para trás.",--Light the fireworks, and stand back.
	pln_ca1_103_02 = "Mexam-se, pessoal. Achem o vestiário, e nós acharemos o arsenal.",--Move it, guys. Find the locker room, and we find the armory.
	pln_ca1_04_01 = "Também tem o gás do sono. Peguem-no. Vocês irão precisar mais tarde.",--There's sleeping gas too. Grab it. You'll need it later.
	pln_ca1_114_01 = "Um dos tanques de refrigeração da FGpC está vazio. Pessoal, ela precisa de água. Peguem um refil dos banheiros",--One of BFD's coolant tanks is empty. She needs that water, guys. Grab a refill from the bathrooms!
	pln_ca1_108_01 = "Vocês apostaram no lugar certo! Aí está o cofre!",--You bet on the right spot! There's the vault!
	pln_ca1_124_02 = "Zero",--Zero!
	pln_ca1_01_01 = "Vocês estão em modo civil. Sem armas, sem máscaras - invisíveis para a segurança. Quanto estiverem prontos, achem seus equipamentos. Micho o zelador os deixou num case de guitarra em algum lugar.",--You're in civilian mode. No guns, no masks - invisible to security. When you're ready, find your gear. Micho the janitor left it in a guitar case somewhere.
	pln_ca1_50_02 = "O dirigível está a caminho. Apenas deem um tempo.",--Okay, the blimp is on the way. Just give it time.
	pln_ca1_117_03 = "Vamos lá, o saque do Dentista está aí.",--Come on, Dentists' loot is right there.
	pln_ca1_150_03 = "Os arquivos conterão as plantas. Verifiquem as áreas para funcionários.",--The archives will hold the blueprints. Check the staff areas.
	pln_ca1_57_02 = "A energia caiu. Pessoal, reconectem a FGpC!",--Power's down. Get BFD reconnected, gang!
	pln_ca1_87_01 = "Haha, funcionou! Os guardas na segurança estão dormindo feitos bebês. Não se preocupem com as câmeras agora.",--Haha, it worked! The guards in security are sleeping like babies. Don't worry about cameras now.
	pln_ca1_62_02 = "Droga, a FGpC quebrou. Vocês precisarão de ferramentes para consertar ela.",--Damn, BFD is bust. You need tools to fix her up.
	pln_ca1_146_01 = "As áreas somente para funcionários.",--The employee only areas.
	pln_ca1_brf_01_01 = "Este é um trabalho grande. Irei falando a medida que avançamos, mas o resumo é esse: o Sorriso Dourado tem um cofre grande. Grande. Quero dizer Banco Benevolente grande. Se vocês vão entrar na furtiva, ou vão assalto total, vai ser extremamente díficil.",--This is a big job. I'll talk you through it as we go, but the skinny is this: the Golden Grin has a big vault. Big. I mean Benevolent Bank big. Whether you sneak in, or go full assault, you're in for a tough time. 
	pln_ca1_110_02 = "Pessoal, plantem esse C4 no Salão de Apostas.",--Get that C4 planted in the Gambling Hall, gang.
	pln_ca1_96_02 = "Código do chefe de segurança. Vão comer o rabo dele por deixar isso por aí.",--Security chief's code. His ass is in trouble for leaving this around.
	pln_ca1_108_02 = "E... ótimo! Aí está a parte de cima do cofre!",--And... great! There's the top of the vault!
	pln_ca1_93_03 = "Este é um dos códigos do cofre. Lembrem-se dele. Nós iremos precisar dele antes de terminar esse trabalho.",--This is one of the vault codes. Remember it. We're going to be needing it before we close this caper.
	pln_ca1_168_03 = "Pessoal, arrumem a FGpC. Vamos lá, parem de perder tempo.",--Get BFD fixed up, gang. Come on, stop wasting time.
	pln_ca1_113_02 = "Ótimo. Agora liguem ela novamente.",--Great. Now turn her back on.
	pln_ca1_129_02 = "Cinco",--Five!
	pln_ca1_147_01 = "Este é o Centro de Segurança.",--This is the Security Center.
	pln_ca1_03_01 = "Certo, vamos explodir esse lugar. C4 está na limosine. Peguem-no!",--OK, lets blow this place. C4's in the limo. Take it!
	pln_ca1_163_02 = "Você não achará um bife Nova York melhor em lugar algum, incluindo Nova York. ",--You won't find a better New York steak anywhere, including New York.
	pln_ca1_17_01 = "Consegui. Irei verificar os antecedentes desse cara. Aguardem.",--Got it! I'll do a background check on this guy. Hang on.
	pln_ca1_119_01 = "Beleza, isso aí. Joguem isso na FGpC.",--All right, that's it! Throw it up onto BFD.
	pln_ca1_43_01 = "Parafusem o guincho para que ele fique estável. Acreditem em mim, para o que está vindo, vocês precisarão disso firme.",--Screw down the winch so that it'll be stable. Trust me, for what's coming, you need it secure.
	pln_ca1_20_02 = "Nosso cara tem gosto pelo Jaegerheister. Achem a garrafa verde, batizem e sirvam-no.",--Our guy has a taste for Jaegerheister. Find the green bottle, spike it and serve it.
	pln_ca1_137_01 = "Essas máquinas são para sugar o dinheiro de otários. Não percam o seu tempo.",--These machines are for nickel-and-dime suckers. Don't waste your time.
	pln_ca1_127_02 = "Três",--Three!
	pln_ca1_26_02 = "Achem a ventilação, e comecem a bombear o gás. Nós faremos o seu centro de segurança quente e acolhedor... *bocejos*",--Find the vent, and start pumping the gas. We'll make their security center fuzzy and warm and... *yawns*
	pln_ca1_170_02 = "Pessoal, peguem aquelas mochilas, vamos lá!",--Grab those bags, gang, come on!
	pln_ca1_75_01 = "Tive uma ideia. Eu tenho o número dele. Irei chamá-lo e distraí-lo. Fiquem prontos para encher o copo dele.",--Got an idea. I got his phone number. I'll call him and distract him. You be ready to top up his glass.
	pln_ca1_159_04 = "Uma boa noite para você, senhor.",--A very good evening to you, sir.
	pln_ca1_99_01 = "A merda! Mais lasers. Deve ser um sistema independente. Observem o padrão. Não queremos acionar nenhum alarme agora.",--Ah crap! More lasers. Must be an independent system. Watch the pattern. Don't want to trigger any alarms now.
	pln_ca1_100_03 = "Aí está a coisa do Dentista. Arranquem isso daí e terminamos com ele.",--There's The Dentist's whatever. Haul it out of there and we are done with him.
	pln_ca1_76_02 = "Beleza. Acgora esperem ele tomar aquela bebida. A qualquer momento ele irá correr para o John. Sigam ele. Peguem o seu cartão.",--All right. Now let's just wait for him to try that drink. He's going to run for the John any second. Follow him. Get his keycard.
	pln_ca1_88_01 = "Último obstáculo antes do cofre. Lasers. Precisam desligá-los.",--One last obstacle before the vault. Lasers. Need to shut them down.
	pln_ca1_99_03 = "Mais defesas lasers. Esqueçam desativá-los. Apenas observem o padrão e fiquem prontos para atravessá-los.",--More laser defences. Forget disabling them. Just watch the pattern and be ready to run through. 
	pln_ca1_53_02 = "Agora liguem o guincho! Mantenham os policiais longe dele.",--Now fire up the winch! Keep the cops off it.
	pln_ca1_155_01 = "Agora, o cofre está localizado no Centro de Segurança. Vocês precisam descer e atravessá-lo para chegar.",--Now, the vault is located down in the Security Center. You have to get down and through there to reach it.
	pln_ca1_01_03 = "Vocês estão em modo civil. Suas armas e máscaras estão guardadas em algum lugar. Até pegarem elas, vocês estão invisíveis para a segurança.",--You're in civvie mode. Your guns and masks are stashed somewhere. Until you get them, you're invisible to security.
	pln_ca1_69_01 = "Ainda procurando pelo Pen Drive? Verifiquem na TI.",--Still searching for the USB? Check back in IT.
	pln_ca1_160_02 = "Uh, aqui é, Francoise. Estou chamando da mesa de Satisfação do Cliente.",--Uh, this is, Francoise. I am calling from the Customer Satisfaction desk.
	pln_ca1_100_01 = "Isso aí... o que quer que isso seja! Beleza, o ponto de entrega é no depósito. Levem lá e assegurem isso.",--That's it... whatever it is! All right, the drop off is a storage room. Take that there and secure it.
	pln_ca1_07_01 = "101!",--101!
	pln_ca1_02_02 = "Certo, os Federais não irão demorar, então hora de bater forte e rápido. Achem o C4 na sala dos guardas.",--Okay, the Fed's won't be long, so time to hit it hard and fast. Find the C4 in the guard room.
	pln_ca1_151_01 = "Pessoal, onde estão as plantas? Escaneiem elas, enviem elas. Vocês podem fazer isso na TI.",--Where are those blueprints, gang? Scan 'em, send 'em. You can do it in IT.
	pln_ca1_145_01 = "Estes são os quartos dos hóspedes.",--These are the guest rooms.
	pln_ca1_159_05 = "É muito bom falar com você, Senhor.",--So good to talk to you, sir.
	pln_ca1_91_03 = "Primeiro dígito do código do cofre. Continuem procurando. Nós precisamos dos três.",--First digit for the vault code. Keep searching. We need all three.
	pln_ca1_12_01 = "152!",--152!
	pln_ca1_132_01 = "Oito",--Eight
	pln_ca1_31_02 = "A informação do Dentista diz que eles tem C4. Tem um arsenal próximo do vestiário dos guardas. Vão lá.",--The Dentist's intel says they have C4. There's an armory near the guards' locker room. Get there.
	pln_ca1_44_02 = "Boa! Agora, nós iremos sinalizar o dirigível, e para isso precisaremos de um sinal grande. Uma queima de fogos! Achem eles!",--Nice! Next, we're going to signal the blimp, and for something like that we need a big signal. A fireworks display! Find them!
	pln_ca1_58_01 = "Liguem o interruptor da FGpC! Deixem o show começar.",--Throw the BFD's switch! Let the show begin!
	pln_ca1_118_01 = "O que quer que isso seja, nós conseguimos! Sigam para a limosine.",--Whatever it is, we got it! Get it to the limo.
	pln_ca1_67_02 = "Estão endo aquele case de guitarra alí? Aquele é seu equipamento.",--See that guitar case over there? That's your gear.
	pln_ca1_34_02 = "Esse é o segundo. Falta mais um.",--That's the second. One more.
	pln_ca1_156_02 = "Maravilhoso equipe. A porta está abrindo. Tudo o que precisam agora é desativar aqueles lasers.",--Outstanding crew. The door's opening. All you need to do now is disable those lasers.
	pln_ca1_165_02 = "Provavelmente o senhor é doceiro? O que acha de bolo o bastante para engasgar um camelo?",--Perhaps sir has a sweet tooth? How would you like enough cake to choke a camel?
	pln_ca1_125_02 = "Um!",--One!
	pln_ca1_158_01 = "Mas que porra...",--What the hell...
	pln_ca1_163_04 = "Nós temos uma boa seleção de carnes raras da África. Você já expirementou elefante?",--We have a fine selection of rare meats from Africa. You ever sampled elephant?
	pln_ca1_66_01 = "Achem o equipamento que o Micho plantou em algum lugar . Procurem por um case de guitarra.",--Find the gear Micho planted somewhere. Look for a guitar case.
	pln_ca1_138_03 = "Recepção. Certo, nós talvez precisemos mais tarde - anotem onde isso fica.",--Reception. Okay, we may need it later - note where it is.
	pln_ca1_65_02 = "Ótimo trabalho. Agora entrem no carro e vamos terminar isso. Ou fiquem por aí e realmente limpem o lugar.",--Great job. Now get in the car and let's end this. Or hang around and really clean the joint.
	pln_ca1_172_01 = "Conectem o guincho a FGpC usando o gancho.",--Connect the winch to BFD with the hook.
	pln_ca1_157_01 = "O dirigível poderia estar do outro lado de Nevada e ainda veria eles.",--The blimp could be all the way across Nevada and would see those.
	pln_ca1_170_03 = "Equipe, vocês tem que pegar as partes do guincho!",--You gotta grab the parts of the winch, crew!
	pln_ca1_151_02 = "Pessoal, vamos lá. Escaneiem e enviem as plantas por fax. Façam isso na TI.",--Come on, guys. Get the plans scanned and faxed. Do it in IT.
	pln_ca1_39_01 = "Acendam um sinalizador para sinalizar o Bile. Nós precisaremos de uma furadeira grande pra porra para descer lá, o que primeiro precisará de um guincho. Ele irá trazer as partes dele.",--Light a flare to signal Bile. We need a big damn drill to get down there, which first needs a winch. He'll bring the parts for it.
	pln_ca1_47_02 = "Essa maldita barreira está impedindo a furadeira de descer. Vão para a segurança e abram ela.",--That damn barrier is preventing the drill from coming down. Get to security and open it.
	pln_ca1_124_01 = "Zero.",--Zero.
	pln_ca1_48_03 = "Começem a hackear os controles da clarabóia e mantenham os policiais longe.",--Get hacking those skylight controls and keep the damn cops off.
	pln_ca1_25_02 = "Aquele é o cartão dele. Peguem-no.",--That's his keycard. Grab it.
	pln_ca1_95_02 = "Esse é o dígito do gerente. Bem feito para ele por ter deixado isso por aí.",--That's the managers digit. Serves him right for leaving it lying around.
	pln_ca1_165_03 = "Nós temos aquelas bolinhas de massa com chocolate e creme.",--We got those little pastry balls with the chocolate and cream.
	pln_ca1_49_03 = "Os policiais pararam o hack. Vão lá e reiniciem.",--The cops pulled the hack. Get there and reboot it.
	pln_ca1_167_01 = "Todo seu pelo preço de... que tal.... 18 pratas.",--All yours for the price of... say... 18 bucks.
	pln_ca1_49_02 = "Mas quem - malditos policiais mexeram com o hack. Reiniciem-no!",--Who the - damn cops messed with the hack. Restart it!
	pln_ca1_45_01 = "Beleza, levem esses fogos para o terraço.",--All right, get those fireworks onto the terrace.
	pln_ca1_88_02 = "Lasers na frente do cofre. Vamos desligá-los.",--Lasers in front of the vault. Let's shut them down.
	pln_ca1_48_02 = "Certo. Os controles. Hackeiem eles, e mantenham os policiais longe.",--Okay. The controls. Hack 'em, and keep the cops off.
	pln_ca1_134_01 = "Strike! Irão precisar roubar mais bancos se essa for a sua sorte.",--Strike! Gonna need to rob more banks if this is your luck.
	pln_ca1_104_03 = "O código tem três números, cada um códificado por cor. Vocês irão achá-los em maletas de computador.",--The code has three numbers, each color coded. You'll find them in computer briefcases.
	pln_ca1_95_01 = "Consegui! O código do gerente do cassino.",--Got it! The casino manager's code.
	pln_ca1_115_03 = "Pessoal, nós não precisamos da FGpC quebrando. Tenham certeza de que ela tenha muito refrigerante. Peguem água do banheiro.",--We don't need BFD breaking down on us, crew. Make sure she has plenty of coolant. Get water from the bathroom.
	pln_ca1_141_01 = "O salão principal.",--The main lobby.
	pln_ca1_61_02 = "Os tanques da FGpC estão drenados.  Vocês podem reabastecê-los no banheiro. Ela não é exigente.",--BFD's tanks are drained. You can refill them in the bathroom. She's not fussy.
	pln_ca1_168_02 = "Consertem FGpC e vamos terminar isso. Vamos lá, equipe, nós estamos tão perto.",--Fix up BFD and let's finish this. Come on, crew, we're so close.
	pln_ca1_166_02 = "E o que gostaria como acompanhamento? Uh... rissóis de salsicha? Nós temos eles!",--And what would you like as a side? Uh... sausage patties? We got 'em!
	pln_ca1_40_01 = "Agora apenas aguentem firme e esperem o Bile jogar o guincho.",--Now just hold tight and wait for Bile to drop the winch.
	pln_ca1_73_01 = "Certo. Peguei ele. Nome, número do CPF, nome do cachorro... Achem ele. Verifiquem a tela na TI. Ah, e ele é viciado em caça-níqueis, talvez seja um bom lugar para começar a procurar.",--Ok. Got him. Name, social security number, name of his dog... Find him. Check the screen in IT. Oh, and he's a slot machine addict, Might be a good place to start looking.
	pln_ca1_46_02 = "Acendam os fogos. Fiquem para trás. Fiquem seguros.",--Set off the fireworks. Stand back. Stay safe.
	pln_ca1_103_01 = "Apressem-se. Vão para o arsenal no vestiário dos guardas! Nós precisamos daquele C4!",--Hustle it. Get to armory in the guards locker room! We need that C4!
	pln_ca1_171_02 = "Firmem aquele guincho!",--Get that winch secure!
	pln_ca1_132_02 = "Oito",--Eight!
	pln_ca1_08_01 = "102",--102!
	pln_ca1_65_03 = "Vocês podem vazar agora, ou vocês podem ficar e fazer uma limpeza completa no Sorriso Dourado.",--You can bounce now, or you can stay and give the Golden Grin a thorough cleaning.
	pln_ca1_142_01 = "Piscina aquecida com bar.",--Heated outdoor pool with bar.
	pln_ca1_39_02 = "Agora que o cofre está exposto, nós iremos furá-lo. Com uma furadeira grande. Que precisa de um guincho. Sinalizem o Bile com a pistola sinalizadora assim que estiverem prontos.",--Now the vaults exposed, we're going to drill down. A big drill. Which needs a winch. Signal Bile with a flare when you're ready.
	pln_ca1_162_02 = "Só queria te lembrar que o nosso Buffet Coma Tudo o Que Puder agora está aberto.",--I wanted to remind you that our All You Can Eat buffet is now open.
	pln_ca1_64_01 = "Estamos aqui! Achem o saque do Dentista, e vamos dar o fora.",--We're here! Find The Dentist's loot, and let's get it out of here.
	pln_ca1_64_03 = "Apenas peguem o saque e vamos saír daí.",--Just grab that loot and let's get it out of here.
	pln_ca1_137_02 = "O Sorriso Dourado nunca fecha. Vocês querem perder tempo com moedinhas nos caça-níqueis...?",--The Golden Grin never closes. You want to waste time nickel-and-diming the slots...?
	pln_ca1_169_02 = "Essa é uma tomada, mas essa grande e linda garota precisa de outra.",--That's one socket, but that big beautiful girl needs another.
	pln_ca1_93_01 = "O cofre do Sorriso somente pode ser aberto com um código de três dígitos. Este é um dos números que precisaremos para abrí-lo. Anotem.",--The Grin's vault can only be opened with a three digit code. This is one of the numbers we'll need to open it. Make a note.
	pln_ca1_153_03 = "Ele divide uma ventilação com o Centro de Segurança.",--It shares a vent with the Security Center.
	pln_ca1_104_01 = "Pessoal, achem esse números! Nós precisamos dos três para entrar no arsenal.",--Find those numbers, gang! We need all three to get into the armory.
	pln_ca1_42_01 = "Agora montem aquele guincho no salão principal.",--Now get that winch put together in the main hall.
	pln_ca1_51_03 = 'Nossa, que vista! "FGpC". Ou "Furadeira Grande pra Caramba".',--Hell, that's a sight! "BFD". Or "Big Funky Drill.".
	pln_ca1_53_01 = "Começem o guincho e ele irá mover a FGpC em posição. Não deixem os policiais pararem ela!",--Start the winch and it will move BFD into position. Don't let the cops stop it!
	pln_ca1_154_01 = "Que sala era aquela mesmo?",--What was that room again?
	pln_ca1_152_03 = "É... quarto...",--It's... room...
	pln_ca1_43_02 = "Parafusem bem o guincho. Acreditem em mim, vocês irão precisar dele estável para a próxima parte.",--Screw the winch down good. Believe me, you need it stable for the next part.
	pln_ca1_32_01 = "O arsenal. Parece que eles tem um monte de C4 guardado lá. Só Cristo para saber o porque de um cassino precisar de explosivo plástico...",--The armory. Looks like they've a bunch of C4 stacked there. Christ knows what a casino needs plastic explosive for...
	pln_ca1_138_01 = "A área de recepção. Lembrem-se desse local. Pode vir a calhar.",--The reception area. Remember the location. Might come in handy.
	pln_ca1_42_02 = "Pessoal, montem o guincho no salão principal.",--Assemble the winch in the main hall, gang.
	pln_ca1_17_02 = "Isso aí! Estou verificando os antecedentes agora. Esperem.",--That's it! Doing a background check now. Hold on.
	pln_ca1_05_02 = "Depois, nós achamos a sala a qual a ventilação conecta com o centro de segurança. Nós podemos usar isso para desmaiar is guardas com o gás do sono. Então, nós precisaremos das plantas. Olhem nos arquivos.",--Next, we find the room whose vent connects with the security center. We can use that to knock out the guards with sleeping gas. So, we need blueprints. Check the archives.
	pln_ca1_152_02 = "Aí vem. Sala...",--Here it comes. Room...
	pln_ca1_22_01 = "Achem a garrafa azul e batizem ela.",--Find the blue bottle and spike it.
	pln_ca1_66_03 = "O equipamento pode estar na área de fumantes. Micho provavelmente deixou seus equipamentos lá. Procurem por um case de guitarra.",--The gear could be at the smoking area. Perhaps Micho left your gear there. Look for a guitar case.
	pln_ca1_23_02 = "Encham o copo dele. Assim que ele beber isso, bem... ele irá perder o interesse nos caça-níqueis. Sigam ele, e peguem o seu cartão.",--Fill his glass. Once he downs that, well... he's going to lose interest in the slots. Follow him, and get his keycard.
	pln_ca1_128_01 = "Quatro.",--Four
	pln_ca1_41_01 = "Golpistas, peguem aquelas partes.",--Grab those parts, heisters.
	pln_ca1_51_02 = "Certo, o dirigível está abaixando ela para vocês. FGpC. Olhem essa beleza.",--Okay, blimp is lowering her to you. BFD. Look at that beauty.
	pln_ca1_03_02 = "Peguem aquele C4 na limosine e vamos explodir esse lugar. Rápido! A polícia está a caminho.",--Grab that C4 in the limo and let's blow this place. Hurry! Cops are coming.
	pln_ca1_intro_01_02 = "Certo apostadores. Vamos apostar.",--Okay gamblers. Let's get gambling.
	pln_ca1_131_01 = "Sete",--Seven
	pln_ca1_167_02 = "E quanto isso irá lhe custar? Digamos... 18 pratas?",--And how much will it cost you? Shall we say... 18 bucks?
	pln_ca1_15_02 = "Boa. Agora vão pegar aquela lista de hóspedes da recepção.",--Nice. Now go get that guest list from reception.
	pln_ca1_67_01 = "Alí. O seu euipamento está naquele case de guitarra.",--Over there. Your gear's in that guitar case.
	pln_ca1_107_01 = "C4 no arsenal. Vão pegá-lo.",--C4 in the armory. Go get it!
	pln_ca1_101_03 = "Agora nós podemos finalizar o contrato do Dentista. Vocês podem vazar, ou dar a Vegas uma festa da Gangue do Payday e saquear o lugar.",--We can now redeem the Dentists' contract. You can bounce, or treat Vegas to a Payday Gang party and loot the place.
	pln_ca1_71_02 = "Ótimo. Aí vem a lista de convidados.",--Great. Here comes the guest list now.
	pln_ca1_97_01 = "Ótimo, esse é o número do supervisor do cassino.",--Great, That's the pit boss' number.
	pln_ca1_107_02 = "Sigam para o arsenal e carreguem-se de C4. ",--Head to the armory and load up on C4.
	pln_ca1_160_04 = "Aqui é... Gerd. Estou chamando você do Departamento de Satisfação do Cliente do Sorriso Dourado.",--This is... Gerd. I'm calling you from The Golden Grin Customer Satisfaction Department.
	pln_ca1_160_03 = "Um, meu nome é, uh... Tony. Porque não. Estou chamando da Satisfação do Cliente aqui do Sorriso.",--Um, my name is, uh... Tony. Why not. I'm calling from Customer Satisfaction here at The Grin.
	pln_ca1_58_03 = "Agora liguem a FGpC. Eles irão mostrar ela durante anos.",--Now turn on BFD. They'll display her for years to come.
	pln_ca1_111_01 = "Pessoal Bile está esperando vocês! Ele tem o guincho. Vamos lá, acendam o sinalizador!",--Bile is waiting for you guys! He's got the winch. Come on, light the flare!
	pln_ca1_50_03 = "O dirigível está sobre a cidade e seguindo para vocês. Deem um momento a ele.",--Blimp is over the city and headed for you. Give it a moment.
	pln_ca1_02_01 = "Certo, policiais estão a caminho. Primeiro passo, procurem por C4 na sala dos guardas.",--OK, cops are inbound. First step, look for C4 in the guard room.
	pln_ca1_23_01 = "Agora encham o copo dele. Assim que ele engolir, bem, vamos dizer que ele irá fazer barulho. Sigam ele, e peguem o cartão do quarto dele.",--Now top up his glass. Soon as he swallows, well, let's say he's going to go loud. Follow him, and get the card for his room.
	pln_ca1_89_01 = "Certo, as maletas. A primeira fica com o gerente do cassino, a segunda com o supervisor e a terceira com o chefe de segurança.",--Okay, the briefcases. First is held by casino manager, the second one by the pit boss and the third by their head of security.
	pln_ca1_70_03 = "Pessoal, a recepção terá a lista de hóspedes. Apenas sigam para lá, e baixem ela.",--Reception will have the guest list, guys. Just head there, download it.
	pln_ca1_170_01 = "Pessoal, vamos lá! Peguem as mochilas, e montem o guincho.",--C'mon, gang! Get the bags, and assemble the winch.
	pln_ca1_133_01 = "Nove",--Nine
	pln_ca1_101_02 = "O saque do Dentista está seguro. Saiam agora, ou realmente mostrem ao Sorriso como cuidamos de Vegas estilo DC.",--That's The Dentists' loot saved. Bail now, or really show The Grin how we treat Vegas DC-style.
	pln_ca1_96_01 = "Boa. Número do chefe de segurança. Ele não ficará feliz de perder isso.",--Nice. Security chief's number. He won't be happy to lose this.
	pln_ca1_15_01 = "Beleza. Sigam para a recepção, achem um terminal e baixem a lista de hóspedes.",--All right. Head to reception, find a terminal and download the guest list.
	pln_ca1_140_01 = "Esta é a mesa da recepção.",--This is the reception desk.
	pln_ca1_123_03 = "Certo, os números do código são...",--Right, the numbers for the code are...
	pln_ca1_72_03 = "Não esqueçam de me enviar a lista. Sigam para a TI. Pluguem ela.",--Don't forget to send me the list. Head to IT. Plug it in.
	pln_ca1_14_01 = "154",--154!
	pln_ca1_59_01 = "Esperem a FGpC quebrar através do cofre. Até esse monstro levará um tempo. Mantenham os policiais longe.",--Wait for BFD to crack through the vault. Even this monster will take time. Keep the cops away.
	pln_ca1_171_01 = "Parafusem o guincho!",--Screw the winch down!
	pln_ca1_74_02 = "Achem o hóspede para que possamos roubar o seu cartão. Lembrem-se, ele provavelmente está nos caça-níqueis.",--Find the guest so we can steal his keycard. Remember, he's likely on the slots.
	pln_ca1_35_02 = "Certo, esse é o código do arsenal. Digitem ele!",--Okay, that's the digits for the armory code. Enter it!
	pln_ca1_98_02 = "Execelente pra porra, equipe! Entrem, encham suas mochilas. Levem tanto quanto puderem, mas lembrem-se, estamos aqui pelo saque do Dentista.",--Out-goddamn-standing, crew! Get in, fill your bags. Take as much as you can, but remember, we're here for The Dentists' loot.
	pln_ca1_173_01 = "Beleza. O arsenal usa um código de três dígitos. Procurem por ele no cassino. Números e cores. Ou vocês podem apostar na adivinhação.",--All right. Armory uses a three digit code. Look for it in the casino. Numbers and colors. Or you can gamble on guessing.
	pln_ca1_112_02 = "Não esqueçam dos fogos de artifício. Vegas irá acender como 1999.",--Don't forget the fireworks. Vegas will go up like 1999.
	pln_ca1_33_02 = "Primeiro número. Pegue os outros dois.",--First number. Get the other two.
	pln_ca1_165_04 = "Não esqueça que temos sobremesas doces o bastante para lhe dar diabetes.",--Don't forget we have enough sugary desserts to give you diabetes.
	pln_ca1_156_03 = "Certo, primeiramente, procurem pelo case com os equipamentos.",--OK, first things first, look for the gear case.
	pln_ca1_93_02 = "Seu grande cofre usa um código de três dígitos. Esse é um dígito. Anotem ele. Vocês irão precisar mais tarde.",--Their big vault takes a three digit code. This is one digit. Write it down. We'll need it later.
	pln_ca1_115_02 = "A FGpC trabalha duro, mas bebe muita água. Tenham certeza de que ela tem refrigerante. Vocês podem achar água no banheiro. ",--BFD works hard, but drinks a lot of water. Make sure she has coolant. You can find water in the bathroom.
	pln_ca1_69_03 = "Aposto que qualquer departamento de TI decente terá um pen drive reserva.",--I'm guessing any decent IT department will have a spare USB.
	pln_ca1_77_01 = "Entrem depois dele, e esperem sua chance.",--Get after him, and wait for your chance.
	pln_ca1_52_02 = "Beleza. Agora é por isso que trouxemos o guincho. Conectem ele a FGpC, e ele irá colocá-la na posição correta.",--All right. Now this is why we brought the winch. Hook it to BFD, and it'll get the position right.
	pln_ca1_51_01 = 'Aí vem ela. "FGpC" significa "Broca Grande pra Caramba". Quase.',--Here she comes. "BFD". Stands for "Big Goddamn Drill". Almost.
	pln_ca1_154_03 = "Deixe-me verificar. Quarto...",--Let me check. Room...
	pln_ca1_58_02 = "Beleza. Agora liguem o disjuntor. Vamos ver o que a FGpC pode fazer.",--All right. now throw that switch. Let's see what BFD can do!
	pln_ca1_144_01 = "Esta sala de jogos é o coração do Sorriso Dourado.",--This game room is the heart of The Golden Grin.
	pln_ca1_27_02 = "O cofre precisa de um código de três dígitos, e cada digito fica com um gerente. Eles os mantém em maletas de computadores. Pessoal, achem esse código.",--Vault needs a three digit code, and each digit is held by a manager. They hold them in computer briefcases. Gang, find that code.
	pln_ca1_114_02 = "Parece que um dos tanques de refrigeração acabou. Sejam cavalheiros e peguem um refil para a garota. Uh, do merdeiro.",--Looks like one of her coolant tanks is finished. Be gents and fetch that girl a refill. Uh, from the crapper.
	pln_ca1_54_01 = "Religuem o guincho. E mantenham os malditos policiais longe dele.",--Restart the winch. And keep the damn cops off it.
	pln_ca1_135_01 = "Ka-ching, pessoal! Talvez nós possamso parar de roubar bancos e ganhar nosso pagamento nos caça-níqueis.",--Ka-ching, gang! Maybe we can stop robbing banks and earn our payday on the slots.
	pln_ca1_98_01 = "Excelente, pessoal, estamos dentro! Sirvam-se, não devolvam nada. Lembrem-se, nosso objetivo é o saque do Dentista.",--Outstanding, guys, we're in! Help yourselves, give nothing back. Remember, our goal is the Dentists' loot.
	pln_ca1_29_01 = "Ótimo. Agora vocês podem se mascarar novamente.",--Great. Now you can mask up again.
	pln_ca1_158_02 = "Eu não... sei...",--I don't... know...
	pln_ca1_117_01 = "Pessoal, achem o saque do Dentista!",--Find The Dentist's loot, guys! 
	pln_ca1_77_02 = "Agora! Atrás dele. Esperem até ele estar sozinho.",--Now! After him. Wait til he's alone.
	pln_ca1_27_01 = "A Abertura do cofre precisa de um código de três dígitos. Cada dígito fica com um gerente, e cada um está numa maleta de computador. Nós precisamos daquele código. Achem eles.",--Opening the vault needs a three digit code. Each digit is held by a manager, and each is in a computer briefcase. We need that code. Find them.
	pln_ca1_06_01 = "Ótimo! Agora achem um scanner na TI. Me enviem uma cópia das plantas por fax. Irei achar aquela ventilação.",--Great! Now find a scanner in IT. Fax me a copy of the blueprints. I'll find that vent.
	pln_ca1_116_02 = "Não deixem a FGpC superaquecer. Reabasteçam aquele tanque com água.",--Don't let BFD overheat. Refill that tank with water!
	pln_ca1_94_01 = "Fantástico! Nós conseguimos o código para a abertura do cofre. Agora, nós precisamos entrar no centro de segurança sem sermos notados.",--Fantastic! We got the code for opening the vault. Now, just gotta get inside the security center unnoticed.
	pln_ca1_68_02 = "Certo, agora achem a lista de hóspedes. Achem quem está naquela sala. Nós iremos precisar da chave dele. A recepção deve ter um terminal com essa informação. Peguem um pen drive.",--Okay, now I need a guest list. Find out who's in that room. We'll need their key. Reception should have a terminal with that info. Grab a USB stick.
	pln_ca1_18_02 = "Parece que a bebida dele está acabando. Vamos servi-lo outra, com um pegueno negócio adicionado. Achem a mesma garrafa num dos bares.",--Looks like his drink is getting low. Lets serve him another, with a little something added. Find the same bottle at one of the bars.
	pln_ca1_159_03 = "Senhor, posso perguntar se você está tendo um bom dia?",--Can I ask if you are having a good day, sir?
	pln_ca1_01_02 = "Lembrem-se, vocês estão no modo civil. Isso quer dizer sem armas ou máscaras. Vocês são invisíveis. Micho, nosso informante aqui, deixou um case de guitarra em algum lugar com os seus equipamentos.",--Remember, you in civvie mode. That means no guns or masks. You're invisibles. Micho, our Inside Man here, left a guitar case with your gear somewhere.
	pln_ca1_06_02 = "São elas. Agora escaneiem, e me enviem elas por fax. Irei descobrir a ventilação correta.",--That's them. Now scan them in, and fax me a copy. I'll figure out the right vent.
	pln_ca1_100_02 = "Agora apenas peguem essa coisa e deem o fora daí. Isso é o que viemos pegar.",--Now just grab that thing and get it out of there. It's what we came for.
	pln_ca1_105_02 = "O código de três dígitos abrirá o arsenal. Achem-no.",--A three digit code will open the armory. Find it.
	pln_ca1_106_02 = "Bom trabalho, nós já temos aquele código. Usem ele no arsenal.",--Good job, we already have that code. Use it on the armory.
	pln_ca1_109_02 = "Merda! Apenas plantem o C4 no outro lugar. Agora é certeza.",--Crap! Just plant the C4 at the other spot. It's a sure thing now.
	pln_ca1_111_02 = "Pessoal, acendam aquele sinalizador. Bile precisa deixar o guincho.",--Light that flare, gang. Bile needs to drop off the winch.
	pln_ca1_112_03 = "Lembrem-se de separar os fogos. Acendam o céu noturno.",--Remember to sort the fireworks. Light up the night sky.
	pln_ca1_117_02 = "Pode apenas um de vocês palhaços apenas pegar aquele saque, por favor?",--Will one of you clowns just grab that loot, please?
	pln_ca1_119_02 = "Ótimo. Agora joguem isso na FGpC.",--Great. Now toss it up onto BFD.
	pln_ca1_121_02 = "Agora subam na FGpC e deixem o dirigível carregar vocês, para cima e para longe. Ou fiquem e peguem mais saque.",--Now get onto BFD and let the blimp carry you up, up and away. Or stay and grab more loot.
	pln_ca1_126_02 = "Dois!",--Two!
	pln_ca1_133_02 = "Nove!",--Nine!
	pln_ca1_134_03 = "Apostar é uma doença. Pare enquanto pode, otário!",--Gambling is a disease. Stop while you can, sucker!
	pln_ca1_136_02 = "Este lugar é legitimamente rico. Vamos fazê-lo legitimamente pobre.",--This place is legit rich. Let's make it legit poor.
	pln_ca1_137_03 = "Essas máquinas são peixe pequeno. Nós estamos aqui por um prêmio maior.",--These machines are small fry. We're here for a bigger prize.
	pln_ca1_138_02 = "Esta é a recepção. Lembrem-se onde ela fica.",--This is reception. Remember where it is.
	pln_ca1_139_01 = "Esta área é somente para funcionários. Todos os escritórios são acessíveis daqui. ",--This area's employees only. All the offices are accessible from here.
	pln_ca1_139_03 = "Aqui é onde funcionários trabalham. Escritórios, TI, segurança e assim por diante.",--This is where the staff work. Offices, IT, security and so on.
	pln_ca1_150_01 = "Peguem as plantas nos arquivos. Eles estão em algum lugar nas áreas somente para funcionários.",--Get the blueprints in the archives. They're somewhere in the employee only areas..
	pln_ca1_151_03 = "Pessoal. Vocês precisam escanear e enviar as plantas por fax. Certeza que isso pode ser feito na TI.",--Gang. You gotta scan and fax over the blueprints. Sure that can be done in IT.
	pln_ca1_157_02 = "Acho que eles viram aquilo da ISS!",--I think they saw that from the ISS!
	pln_ca1_159_02 = "Senhor, obrigado pelo seu tempo.",--Thank you for your time, sir.
	pln_ca1_160_01 = "Aqui é, uh, Craig do, uh, Departamento de Satisfação do Cliente ligando.",--This is, uh, Craig in the, uh, Customer Satisfaction Department calling.
	pln_ca1_161_01 = "Eu queria perguntar se você estava pensando em experimentar hoje o nosso Coma Tudo o Que Puder?",--I wanted to ask if you were thinking of trying our All You Can Eat buffet today?
	pln_ca1_163_03 = "Se você quiser o seu bife mal passado, nós somente iremos limpar a bunda dele e levá-lo a sua mesa.",--If you want your beef rare, we'll just wipe its ass and lead it to your table.
	pln_ca1_164_01 = "Nós estamos servindo... uh... sopa. Feita com... uh. vegetais.",--We're serving... uh... soup. Made with... uh... vegetables.
	pln_ca1_165_01 = "Nós também temos sorvete. Você gosta de sorvete?",--We got ice cream too. You like ice cream?
	pln_ca1_166_04 = "E se quiser, até podemos fazer você brindar.",--And if you want, we can even make you toast.
	pln_ca1_168_01 = "Vocês estão perdendo tempo! Reparem a FGpC, coloquem ela para funcionar e vamos terminar esse negócio.",--You're wasting time! Repair BFD, get her working and let's finish this caper.
	pln_ca1_16_02 = "Essa é a lista. Agora voltem para a TI e enviem ela de um terminal online.",--That's the list. Now get back to IT and upload it from an online terminal.
	pln_ca1_172_02 = "Pessoal, conectem o guincho na FGpC.",--Get the winch hooked to BFD, gang.
	pln_ca1_172_03 = "Vocês precisam conectar a FGpC ao guincho.",--You need to hook BFD up with the winch.
	pln_ca1_173_02 = "O arsenal precisa de um código de três dígitos. Vocês podem encontrar os dígitos por todo o Sorriso. Começem a procurar!",--Armory needs a three digit code. You can find the digits throughout the Grin. Get to it!
	pln_ca1_173_03 = "Nós precisamos de um código para abrir o arsenal. Três dígitos. Codificados por cores. Eles estão em algum lugar do Sorriso. Começem a procurar!",--We need a code to open the armory. Three digits. Colour coded. They're somewhere in the Grin. Get searching!
	pln_ca1_18_01 = "Parece que o seu copo está ficando vazio. Tragam outra bebida para ele com um sabor extra nela. Tenho certeza que vocês podem achar outra garrafa em um dos bares e batizá-la.",--Looks like he's running dry. Bring him another with a little extra flavor in it. I'm sure you can find a bottle in one of the bars and spike it.
	pln_ca1_23_03 = "Coloquem uma bebida para ele. Assim que ele der um gole, o negocinho que adicionamos deve... bem, ele irá correr para o banheiro mais próximo. Sigam ele. Peguem o seu cartão.",--Pour him a drink. Once he takes a sip, the little something we added should... well, he's going to run for the nearest toilet. Follow him. Get his keycard.
	pln_ca1_24_01 = "Isso aí, parceiro. Beba.",--That's it, buddy. Drink up.
	pln_ca1_24_02 = "De uma boa, longa golada, amigo.",--Take a nice, long drink, pal.
	pln_ca1_26_01 = "Agora procurem por uma ventilação, e mandem o gás. Mandem a segurança para a Terra do Nunca.",--Now look for a vent, and get the gas pumping. Send the security to Neverland.
	pln_ca1_28_03 = "Três dígitos. Excelente! Agora sigam para o cofre e testem eles.",--Three digits. Outstanding! Now head to the vault and try them out.
	pln_ca1_29_02 = "Certo. Mascarem-se assim que estiverem prontos.",--Okay. Mask up when you're ready.
	pln_ca1_31_03 = "O Dentista me disse qe eles tem C4 aí no arsenal. Vão lá, e peguem ele.",--Dentist tells me they have C4 in the armory there. Get there, and get it.
	pln_ca1_38_01 = "Agora plantem o C4 no são principal. O cofre está bem abaixo. Dois locais possíveis para explodir. Espero que a senhora sorte esteja conosco!",--Now plant the C4 in the main hall. The vault is right below. Two possible spots to blow. Hope lady luck is with us!
	pln_ca1_38_02 = "Agora detonem o C4 no salão principal. Coloquem ele bem em cima do cofre. É difícil dizer exatamente onde. Dois locais possíveis. Rezem por um pouco de sorte.",--Now detonate the C4 in the main hall. Place it right above the vault. Hard to say exactly where that is. Two possible spots. Pray for a bit of luck.
	pln_ca1_38_03 = "Coloquem o C4 no salão principal, bem em cima do cofre. Dois locais possíveis, então é um pouco de sorte. Se necessário, explodiremos ambos!",--Put the C4 in the main hall, right above the vault. Two possible spots, so it's a bit of a lottery. If need be, we'll blow them both!
	pln_ca1_42_03 = "Equipe, montem o guincho no local que eu marquei.",--Put the winch together where I marked, crew.
	pln_ca1_44_01 = "Beleza! Sinalizem o dirigível. E façam no estilo Vegas. Achem alguns fogos de artifício e acendam eles.",--All right! Signal the blimp. And do it Vegas style. Find some fireworks and light them up.
	pln_ca1_44_03 = "Nós iremos trazer a furadeira com um dirigível. Para o piloto ver o seu sinal, vocês precisarão armar uma queima de fogos. Então procurem por eles!",--We're going to bring the drill in with a blimp. For the pilot to see your signal, you need to set off a firework display. So look for them!
	pln_ca1_45_02 = "Ótimo! Agora vão para o terraço e coloquem os fogos.",--Great! Now head to the terrace and place the fireworks.
	pln_ca1_52_01 = "Vocês precisarão colocar a FGpC bem em cima do cofre. O guincho irá movê-la, então conectem eles.",--You need to get BFD right above the vault. The winch will move her, so get them hooked up.
	pln_ca1_55_01 = "Beleza, agora deixem o guincho trabalhar.",--All right, now let the winch do its job.
	pln_ca1_56_02 = "A FGpC é uma garota gananciosa. Precisa de muita energia. Liguem ela em duas tomadas. Vocês podem achar elas no cassino. E mantenham os policiais longe.",--BFD is a greedy girl. Needs a lot of power. Hook her up to two sockets. You can find them inside the casino. And keep the cops off.
	pln_ca1_59_03 = "Certo, ela está furando para dentro do cofre. Mantenham ela segura.",--Okay, she's drilling down into the vault. You keep her safe.
	pln_ca1_60_01 = "Malditos policiais chegaram nela! Limpem a área e reativem a FGpC!",--Damn, cops got to her! Clear the zone and reactivate BFD!
	pln_ca1_60_02 = "Os policiais desligaram a FGpC. Lidem com eles, e iniciem ela novamente.",--The cops shut down BFD. Deal with them, and start her up again.
	pln_ca1_61_01 = "Os tanques d'água estão vazios. Reabasteçam eles nos banheiros. Ei, nunca prometi glamour a vocês.",--Water tanks are empty. Refill them in the bathrooms. Hey, I never promised you glamour.
	pln_ca1_63_03 = "A FGpC fez um ótimo trabalho. Pessoal. Desçam para o cofre.",--BFD did a great job. Down into the vault. gang.
	pln_ca1_66_02 = "Seus equipamentos talvez estejam perto da piscina. Vejam se o Micho deixou lá. Procurem por um case de guitarra.",--Maybe your gear is at the pool. See if Micho left the gear there. Look for a guitar case.
	pln_ca1_70_01 = "Pessoal, ainda estou esperando a lista de hóspedes. Vão para a recepção e baixem ela.",--Still waiting on the guest list, guys. Get to reception and download it.
	pln_ca1_72_02 = "Pessoal, achem a lista para mim. Apenas plugem isso num terminal online na TI.",--Find me the list, gang. Just plug it into an online terminal in IT.
	pln_ca1_73_02 = "Esse é ele. Consegui o seu nome, CPF, última vez que deu uma cagada... Verifiquem a tela na TI. Achem ele. Aqui diz que ele ama caça-níqueis, então talvez seja onde ele estará.",--That's him. Got his name, SSN, last time he took a dump... Check the screen in IT. Find him. Says here he loves the slots, so maybe that will be where he is.
	pln_ca1_78_01 = "Agora! Amarem ele.",--Now! Tie him down.
	pln_ca1_87_02 = "Isso funcionou. Eles estão todos dormindo. Agora daqui em diante não precisam mais se preocupar com as câmeras.",--That did it. They're all fast asleep. No need to worry about cameras from here on.
	pln_ca1_91_02 = "Esse é o primeiro número. Continuem procurando. Faltam dois.",--That's the first number. Keep looking. Two to go.
	pln_ca1_94_02 = "Excelente! Esse é o código do cofre. Assim que estivermos no Centro de Segurança, nós poderemos abrir o cofre com ele.",--Outstanding! That's the vault code. Once we're in the Security Center, we can open the vault with it.
	pln_ca1_97_02 = "Nós conseguimos o código do supervisor do cassino. Boa.",--We got the pit boss' code. Nice.
	pln_ca1_intro_02_01 = "Vamos arrasar!",--Let's rock!
	pln_ca1_intro_02_02 = "Chegando com estilo!",--Arriving in style!
	
	-- Objetivos
	hud_heist_kenaz_c_33a = "Agora vocês podem pegar o saque do Dentista. Procurem por um baú dourado.",--You can now grab the loot for the Dentist. Look for a golden chest.
	hud_heist_kenaz_c_08_hl = "Plantem o C4 no Salão de Apostas",--Plant the C4 in the Gambling Hall
	hud_heist_kenaz_s_010a = "Três números diferentes formam o código de acesso para o cofre. Vocês precisarão de todos eles. Um fica com o gerente, um com o supervisor do cassino e outro chefe de segurança.",--Three different numbers form the access code for the vault. You need all of them. One is held by the manager, one by the pit boss and the other by the head of security.
	hud_heist_kenaz_c_30_hl = "Reabasteçam os tanques d'água",--Refill the water tanks
	hud_heist_kenaz_c_14 = "Procurem por fogos de artifício no depósito e peguem eles.",--Look for the fireworks in the storage room and take them.
	hud_heist_kenaz_s_02b_hl = "Escaneiem as plantas e enviem elas por fax para o Bain",--Scan the blueprints and fax them to Bain
	hud_heist_kenaz_c_27b = "A FGpC está furando para dentro do cofre. Esperem por ela, e mantenham os policiais longe.",--The BFD is drilling into the vault. Wait for her, and keep the cops away.
	hud_heist_kenaz_c_09_hl = "Sinalizem o Bile com uma pistola sinalizadora",--Signal Bile with a flare
	hud_heist_kenaz_c_25_hl = "Religuem o guincho",--Restart the winch
	hud_heist_kenaz_c_27a = "A FGpC vai furar através do Salão de Apostas e dentro do cofre. Liguem ela!",--The BFD will drill down through the Gambling Hall and into the vault. Start her up!
	hud_heist_kenaz_c_24_hl = "Esperem a FGpC entrar em posição",--Wait for BFD to get into position
	hud_heist_kenaz_c_04_hl = "Achem o último número para o código do arsenal",--Find the last number for the armory code
	hud_heist_kenaz_c_18b_hl = "Esperem o hack",--Wait for the hack
	hud_heist_kenaz_c_18b = "Esperem o hack da barreira do clarabóia terminar.",--Wait for the skylight barrier hack to finish.
	hud_heist_kenaz_c_20 = "O dirigível carregando a furadeira está a caminho. Esperem por ele.",--The blimp carrying the drill is en-route. Wait for it.
	hud_heist_kenaz_s_04_hl = "Achem o hóspede dentro do Salão de Apostas",--Find the guest inside the Gambling Hall
	hud_heist_kenaz_c_10 = "Esperem o Bile chegar com as partes do guincho.",--Wait for Bile to arrive with the winch parts.
	hud_heist_kenaz_c_18a_hl = "Hackeiem o mecanismo da barreira da clarabóia",--Hack the skylight barrier mechanism
	hud_heist_kenaz_c_31_hl = "Consertem a FGpC",--Repair the BFD
	hud_heist_kenaz_s_010c = "Achem o último dígito para o código de acesso do cofre. Um eles fica com o gerente, um com o supervisor do cassino e o outro com chefe de segurança.",--Find the last number for the vault access code. One is held by the manager, one by the pit boss and the other by the head of security.
	hud_heist_kenaz_c_06 = "Montem uma furadeira nas portas da jaula e esperem elas abrir.",--Set a drill up on the cage doors and wait for them to open.
	hud_heist_kenaz_c_29_hl = "Reconectem a tomada",--Reconnect the power socket
	hud_heist_kenaz_s_07 = "A bebida agora está envenenada. Esperem a química e biologia fazerem o seu trabalho. Quando ele correr para o banheiro, sigam ele. Lidem com ele em um lugar remoto.",--The drink is now poisoned. Wait for chemistry and biology to do their work. When he runs for the bathroom, follow him. Deal with him in a remote spot.
	hud_heist_kenaz_s_012b_hl = "Digitem o código do cofre",--Enter the vault code
	hud_heist_kenaz_c_28_hl = "Religuem a FGpC",--Restart the BFD
	hud_heist_kenaz_s_09_hl = "Mandem o gás do sono na ventilação",--Pump the sleeping gas into ventilation
	hud_heist_kenaz_c_23_hl = "Liguem o guincho",--Start the winch
	hud_heist_kenaz_c_15_hl = "Coloquem os fogos de artifício",--Place the fireworks
	hud_heist_kenaz_c_26 = "FGpC precisa de muita eletricidade. Liguem ela em duas tomadas.",--BFD needs a lot of electricity. Hook her up to two power sockets.
	hud_heist_kenaz_c_11 = "Bile jogou as peças do guincho. Vão e peguem elas.",--Bile has dropped the pieces for the winch. Go and grab them.
	hud_heist_kenaz_c_08 = "Plantem o C4 no chão do Salão de Apostas. Tem dois lugares. Um deles será o ponto fraco. Tem C4 o bastante para explodir ambos.",--Plant C4 on the floor of the Gambling Hall. There are two spots. One of them will be the weak spot. There's enough C4 to blow both.
	hud_heist_kenaz_s_07_hl = "Esperem o veneno funcionar",--Wait for the poison to work
	hud_heist_kenaz_c_06_hl = "Furem a jaula",--Drill the cage
	hud_heist_kenaz_c_10_hl = "Esperem pelo Bile",--Wait for Bile
	hud_heist_kenaz_c_31 = "Parece que algo ferrou com a FGpC. Peguem as ferramentas e reparem elas.",--Looks like something messed up with the BFD. Take the tools and repair her.
	hud_heist_kenaz_s_03a_hl = "Achem e coletem um cartão de memória",--Find and collect a memory stick
	hud_heist_kenaz_c_02_hl = "Achem os três números para o código do arsenal",--Find three numbers for the armory code
	hud_heist_kenaz_c_02 = "Três diferentes números formam o código de acesso do arsenal. Vocês precisarão de todos eles. Um fica com o gerente, outro com o supervisor do cassino e outro com o chefe de segurança.",--Three different numbers form the access code for the armory. You need all of them. One is held by the manager, one by the pit boss and the other by the head of security.
	hud_heist_kenaz_s_04 = "Verifiquem a foto que o Bain mandou para vocês e vejam se conseguem achar a localização exata desse hóspede. Ele é viciado em caça-níqueis, então ele provavelmente estará jogando.",--Check the picture Bain sent you and find out the exact location of this guest. He is a slot machine addict, so he will probably be playing.
	hud_heist_kenaz_c_34 = "O saque está seguro. Agora escapem do cassino Sorriso Dourado.",--The loot is secure. Now escape the Golden Grin casino.
	hud_heist_kenaz_c_27b_hl = "Esperem pela FGpC",--Wait for the BFD
	hud_heist_kenaz_c_17 = "Abram a porta do Centro de Segurança e entrem nele para abrir a barreira da clarabóia.",--Open the Security Center door and get inside to open the skylight barrier.
	hud_heist_kenaz_s_03b = "Achem um computador conectado a internet. Pluguem o cartão de memória e enviem a lista de hóspedes para o Bain.",--Find a computer connected to the internet. Plug in the memory stick and upload the guest list to Bain.
	hud_heist_kenaz_c_17_hl = "Entrem no Centro de Segurança",--Get inside the Security Center
	hud_heist_kenaz_s_03_hl = "Baixem a lista de hóspedes",--Download the guest list
	hud_heist_kenaz_c_01_hl = "Achem o arsenal",--Find the armory
	hud_heist_kenaz_c_13_hl = "Parafusem o guincho",--Screw down the winch
	hud_heist_kenaz_c_33b = "Peguem o baú e levem-no para o ponto de entrega seguro.",--Grab the chest and get it back to the secure drop-off point.
	hud_heist_kenaz_c_16_hl = "Acendam os fogos de artifício",--Light the fireworks
	hud_heist_kenaz_s_010b = "Achem mais dois números para o código de acesso do cofre. Um fica com o gerente, um com o supervisor do cassino e outro chefe de segurança.",--Find two more numbers for the vault access code. One is held by the manager, one by the pit boss and the other by the head of security.
	hud_heist_kenaz_c_04 = "Achem o último número do código de acesso do arsenal. Um fica com o gerente, outro com o supervisor do cassino e o outro com o chefe de segurança.",--Find the last number for the armory access code. One is held by the manager, one by the pit boss and the other by the head of security.
	hud_heist_kenaz_c_25 = "Os policiais desligaram o guincho. Liguem ele novamente.",--The cops have shut down the winch. Get it started again.
	hud_heist_kenaz_c_20_hl = "Esperem o dirigível chegar",--Wait for the blimp to arrive
	hud_heist_kenaz_c_16 = "Acendam o pavio dos fogos de artifício e fiquem para trás!",--Light the firework fuse and stand back!
	hud_heist_kenaz_s_02 = "Achem e acessem os Arquivos. Procurem nos documentos as plantas do cassino.",--Find and access the Archives. Search the documents for the blueprint plans of the casino.
	hud_heist_kenaz_s_010b_hl = "Achem mais dois números do código do cofre",--Find two more numbers for the vault code
	hud_heist_kenaz_c_19 = "Retomem o hack da barreira da clarabóia.",--Resume the skylight barrier hack.
	hud_heist_kenaz_s_010a_hl = "Achem três números do código do cofre",--Find three numbers for the vault code
	hud_heist_kenaz_c_13 = "O guincho precisa estar firme. Parafusem ele no chão.",--The winch needs to be secure. Screw it down to the floor.
	hud_heist_kenaz_c_05 = "Digitem os três números no sistema de segurança do arsenal. Lembrem-se de colocá-los na ordem correta.",--Enter the three numbers into the armory security system. Remember to put them in in the correct order.
	hud_heist_kenaz_c_24 = "Esperem o guincho terminar de mover a FGpC para o local em cima do cofre.",--Wait for the winch to finish moving BFD into position above the vault.
	hud_heist_kenaz_c_21_hl = "Esperem a furadeira descer",--Wait for the drill to lower
	hud_heist_kenaz_s_05a_hl = "Achem e batizem a garrafa correta",--Find and spike the correct bottle
	hud_heist_kenaz_c_11_hl = "Peguem as partes do guincho",--Pick up the winch parts
	hud_heist_kenaz_c_09 = "Bile está circulando aí perto. Acendam um sinalizador para trazê-lo.",--Bile is circling nearby. Light a signal flare to bring him in.
	hud_heist_kenaz_s_06_hl = "Deem ao hóspede a bebida batizada",--Give the guest the spiked drink
	hud_heist_kenaz_s_01_hl = "Achem e coletem os seus equipamentos",--Find and collect your gear
	hud_heist_kenaz_s_01 = "Seu equipamento irá acionar os detectores de metal e sorá o alarme. Suas máscaras e armas foram colocadas num case de guitarra pelo Micho, o zelador. Achem ele. peguem o gás do sono e o veneno também.",--Your gear will trigger metal detectors and set off the alarm. Your mask and guns have been stashed in a guitar case by Micho, the janitor. Find it. Grab the sleeping gas and poison too.
	hud_heist_kenaz_c_03 = "Achem mais dois números do código de acesso do arsenal. Um fica com o gerente, outro com o supervisor do cassino e o outro com o chefe de segurança.",--Find two more numbers for the armory access code. One is held by the manager, one by the pit boss and the other by the head of security.
	hud_heist_kenaz_c_05_hl = "Digitem o código do arsenal",--Enter the armory code
	hud_heist_kenaz_s_09 = "Usem o cartão de acesso para entrar no quarto do hotel. Achem a ventilação e comecem a mandar gás do sono  pela tubulação. Isso irá colocar os guardas no Centro de Segurança para dormir.",--Use the keycard to get into the hotel room. Find the vent and start pumping sleeping gas into the shaft. This will put the guards in the Security Center to sleep.
	hud_heist_kenaz_c_14_hl = "Peguem os fogos de artifício",--Take the fireworks
	hud_heist_kenaz_c_22_hl = "Conectem o guincho a FGpC",--Connect the winch to the BFD
	hud_heist_kenaz_c_33b_hl = "Assegurem o saque do Dentista",--Secure the Dentist's loot
	hud_heist_kenaz_c_22 = "Conectem o gancho do guincho na furadeira.",--Connect the winch hook to the drill.
	hud_heist_kenaz_c_03_hl = "Achem mais dois números do código do arsenal",--Find two more numbers for the armory code
	hud_heist_kenaz_c_27a_hl = "Liguem a FGpC",--Start the BFD
	hud_heist_kenaz_c_34_hl = "Fujam",--Escape
	hud_heist_kenaz_c_12 = "Joguem as mochilas no local indicado no Salão de Apostas para montar o guincho.",--Throw the bags at the indicated spot in the Gambling Hall to assemble the winch.
	hud_heist_kenaz_c_07 = "Peguem o C4 da mochila na jaula do arsenal.",--Grab the C4 from the bag in the armory cage.
	hud_heist_kenaz_c_21 = "O dirigível está descendo a furadeira. Esperem por ele.",--The blimp is lowering the drill. Wait for it.
	hud_heist_kenaz_c_30 = "A FGpC precisa de muito líquido de refrigeração. Reabasteçam ambos os tanques d'água.",--The BFD needs a lot of coolant. Refill both water tanks
	hud_heist_kenaz_s_03a = "Bain precisa que vocês adquiram a lista de hóspedes do hotel. Copiem ela em um cartão de memória e enviem os dados para ele. Vocês terão mais sorte de achar um cartão de memória na sala de T.I.",--Bain needs you to acquire hotel guest list. Copy it on memory stick and upload the data to him.  The best chance to find a memory stick is in the I.T. room.
	hud_heist_kenaz_c_07_hl = "Peguem o C4",--Take the C4
	hud_heist_kenaz_c_01 = "Achem um caminho para o vestiário dos guardas do arsenal. É lá onde vocês irão coletar o C4.",--Find your way to the armory in guards' locker room. That is where you will collect the C4.
	hud_heist_kenaz_c_18a = "Abram a barreira da clarabóia hackeando o mecanismo no Centro de Segurança.",--Open the skylight barrier by hacking the mechanism in the Security Center.
	hud_heist_kenaz_s_06 = "Coloquem a bebida batizada para o hóspede. Não sejam mesquinhos. Isso é Vegas, onde todo mundo se diverte, então encham aquela taça.",--Pour the spiked drink for the guest. Don't be stingy. This is Vegas, where everyone has a good time, so fill that glass up.
	hud_heist_kenaz_c_29 = "Reconectem a FGpC nas tomadas.",--Reconnect the BFD to the power socket.
	hud_heist_kenaz_c_12_hl = "Montem o guincho",--Assemble the winch
	hud_heist_kenaz_c_15 = "Coloquem os fogos de artifício no local indicado.",--Place the fireworks at the indicated spot.
	hud_heist_kenaz_c_19_hl = "Retomem o hack",--Resume the hack
	hud_heist_kenaz_c_23 = "O guincho vai colocar a FGpC na posição coreta. Liguem ele.",--The winch will move the BFD into the correct position. Start it up.
	hud_heist_kenaz_c_26_hl = "Conectem a energia na FGpC",--Connect the power to the BFD
	hud_heist_kenaz_c_28 = "Os policiais desligaram a FGpC. Religuem ela.",--The cops have shut down the BFD. Get her re-started.
	hud_heist_kenaz_c_32 = "A furadeira acabou e o cofre está pronto. Entrem lá.",--The drill is done and the vault is ready. Get in there.
	hud_heist_kenaz_c_32_hl = "Entrem no cofre",--Get into the vault
	hud_heist_kenaz_c_33a_hl = "Peguem o saque do Dentista",--Take the Dentist's loot
	hud_heist_kenaz_s_010c_hl = "Achem o último número usado para o código do cofre",--Find the last number used for the vault code
	hud_heist_kenaz_s_012a = "Hackeiem o computador para desativarem os lasers protegendo a entrada do cofre.",--Hack the computer to disable the lasers guarding the vault entrance.
	hud_heist_kenaz_s_012a_hl = "Desativem os lasers",--Disable the lasers
	hud_heist_kenaz_s_012b = "Digitem os três números no sistema de segurança do cofre. Lembrem-se de colocá-los na ordem correta.",--Enter the three numbers into the vault security system. Remember to put them in in the correct order.
	hud_heist_kenaz_s_02b = "Achem um scanner no T.I... Escaneiem as plantas e enviem elas por fax para o Bain.",--Find a scanner in the I.T.. Scan the blueprints and fax them over to Bain.
	hud_heist_kenaz_s_02_hl = "Consigam as plantas do Sorriso Dourado",--Acquire the Golden Grin blueprints
	hud_heist_kenaz_s_03 = "Nós precisamos achar quem está ficando no quarto de hóspedes. Baixem a lista de hóspedes no cartão de memória. Vocês podem conseguir essa lista de um terminal na recepção do cassino.",--We need to find who is staying in that guest room. Download the guest list onto the memory stick. You can acquire this list from a terminal in casino reception.
	hud_heist_kenaz_s_03b_hl = "Enviem a lista de hóspedes",--Upload the guest list
	hud_heist_kenaz_s_05a = "A garrafa do hóspede está vazia. Tragam uma nova para ele, batizada com o veneno. Procurem por garrafas nos bares do cassino e coloquem o veneno nela. Lembrem-se de pegar a bebida que ele gosta.",--The guest's bottle is empty. Bring him a fresh one, spiked with the poison. Look for the bottles in the casino's bars and put poison in it. Remember to get the drink he likes.
	hud_heist_kenaz_s_08 = "O hóspede acabou de perder o cartão de acesso. Coletem ele. Vocês podem usá-lo para entrar no quarto dele.",--The guest just lost the keycard. Collect it. You can use it to enter his room.
	hud_heist_kenaz_s_08_hl = "Peguem o cartão de acesso do quarto do hotel",--Collect the hotel room keycard
		})
end)