return {
	-- Nomes e Descrições
	--heist_hvh = "Cursed Kill Room",--Cursed Kill Room
	--heist_hvh_hl = "Cursed Kill Room",--Cursed Kill Room
	--heist_haunted = "Safe house Nightmare",--Safe house Nightmare
	--heist_haunted_hl = "Safe house Nightmare",--Safe house Nightmare
	--heist_nail = "Lab Rats",--Lab Rats
	--heist_nail_hl = "Lab Rats",--Lab Rats
	--heist_help = "Prison Nightmare",--Prison Nightmare
	--heist_help_hl = "Prison Nightmare",--Prison Nightmare
	heist_haunted_crimenet = "Acorde...",--Wake up...
	heist_haunted_briefing = "Todo o trabalho e nada de diversão fazem do Wolf um garoto chato. Todo o trabalho e nada de diversão fazem do Wolf um garoto chato.$NL;Todo o trabalho e nada de diversão fazem do Wolf um garoto chato. Todo o trabalho e nada de diversão fazem do Wolf um garoto chato.$NL;Todo o trabalho e nada de diversão fazem do Wolf um garoto chato. Todo o trabalho e nada de diversão fazem do Wolf um garoto chato.$NL;Todo o trabalho e nada de diversão fazem do Wolf um garoto chato. Todo o trabalho e nada de diversão fazem do Wolf um garoto chato.$NL;Todo o trabalho e nada de diversão fazem do Wolf um garoto chato. Todo o trabalho e nada de diversão fazem do Wolf um garoto chato.$NL;Todo o trabalho e nada de diversão fazem do Wolf um garoto chato. Todo o trabalho e nada de diversão fazem do Wolf um garoto chato.$NL;Todo o trabalho e nada de diversão fazem do Wolf um garoto chato. Todo o trabalho e nada de diversão fazem do Wolf um garoto chato.$NL;Todo o trabalho e nada de diversão fazem do Wolf um garoto chato. Todo o trabalho e nada de diversão fazem do Wolf um garoto chato.$NL;Todo o trabalho e nada de diversão fazem do Wolf um garoto chato. Todo o trabalho e nada de diversão fazem do Wolf um garoto chato.$NL;Todo o trabalho e nada de diversão fazem do Wolf um garoto chato. Todo o trabalho e nada de diversão fazem do Wolf um garoto chato.$NL;Todo o trabalho e nada de diversão fazem do Wolf um garoto chato. Todo o trabalho e nada de diversão fazem do Wolf um garoto chato.$NL;Todo o trabalho e nada de diversão fazem do Wolf um garoto chato. Todo o trabalho e nada de diversão fazem do Wolf um garoto chato.$NL;Todo o trabalho e nada de diversão fazem do Wolf um garoto chato. Todo o trabalho e nada de diversão fazem do Wolf um garoto chato.$NL;Todo o trabalho e nada de diversão fazem do Wolf um garoto chato. Todo o trabalho e nada de diversão fazem do Wolf um garoto chato.$NL;Todo o trabalho e nada de diversão fazem do Wolf um garoto chato. Todo o trabalho e nada de diversão fazem do Wolf um garoto chato.$NL;Todo o trabalho e nada de diversão fazem do Wolf um garoto chato. Todo o trabalho e nada de diversão fazem do Wolf um garoto chato.$NL;",
	heist_help_crimenet = "À medida que o sono vem chegando, nós acabamos por aparecer nessa terra estranha que está além do mundo real. E quem sabe o que mais estará esperando por nós lá...",--As sleep takes us, we drift into that strange land beyond the waking world. And who knows what might be waiting for us there...
	heist_help_hl_briefing = "Bem-vindo ao meu mundo, para minha prisão! Eu vou fazer você se sentir em casa. Mas você não vai gostar nada da comida - ou de qualquer outra coisa!",--Welcome to my world, to my prison! I'll make you feel right at home. But you won't like the food - or anything else!
	heist_nail_crimenet = "Doces ou Travessuras,$NL;cheire os meus pés.$NL;Me dê algo para colocar na rua.$NL;Se você não puder,$NL;Eu não ligo.$NL;Só não cozinhe de cueca.",
	heist_nail_briefing = "Nós estamos trabalhando no Laboratório, até tarde hoje,$NL;deixando os olhos abertos para uma visão estranha.$NL;Cozinhando em cima da mesa,$NL;borbulhando e fervendo.$NL;E mantendo os policiais,$NL;encrencados e cansados.",
	heist_hvh_crimenet = "Tick tock, pequenos ladrões, tick tock...",--Tick tock little heisters, tick tock ...
	heist_hvh_briefing = "MATAR, MATAR, MATAR, COFRE, MATAR, MATAR, MATAR$NL;MATAR, MATAR, MATAR, COFRE, MATAR, MATAR, MATAR$NL;MATAR, MATAR, MATAR, COFRE, MATAR, MATAR, MATAR$NL;MATAR, MATAR, MATAR, COFRE, MATAR, MATAR, MATAR$NL;MÁÁÁÁÁÁSCARAS!!!!!!$NL;MATAR, MATAR, MATAR, COFRE, MATAR, MATAR, MATAR$NL;MATAR, MATAR, MATAR, COFRE, MATAR, MATAR, MATAR$NL;MATAR, MATAR, MATAR, COFRE, MATAR, MATAR, MATAR$NL;MATAR, MATAR, MATAR, COFRE, MATAR, MATAR, MATAR$NL;MATAR, MATAR, MATAR, COFRE, MATAR, MATAR, MATAR$NL;MATAR, MATAR, MATAR, COFRE, MATAR, MATAR, MATAR",

	-- Legendas (Lab Rats)
	pln_nai_intro_01_01 = "Estamos aqui para cozinhar um pouco de metanfetamina. Como fizemos no verão passado.",--Here to cook a little meth. Just like we did last summer.
	pln_nai_intro_01_02 = "Vocês já sabem o que fazer, gangue. Vamos cozinhar um pouco de metanfetamina.",--You know the drill, gang. Let's cook a little meth.
	pln_nai_intro_01_03 = "Vocês gostariam de jogar um jogo? Um jogo em que se cozinha metanfetamina?",--You wanna play a game? A meth-cooking game?
	pln_nai_04_02 = "Coloquem os comprimidos na batedeira.",--Get hauling those tablets to the mixer. 
	pln_nai_09_03 = "Ahhhh, a metanfetamina terminou, mas não podemos pegá-la do jeito que está. Precisamos quebrá-la. Dividam ela em pequenos pedaços, gangue!",--Ahhhh, the meth is done, but we can't get it out as it is. Need to break it down. Get smashing, gang!
	pln_nai_01_02 = "Cozinhando metanfetamina. O mesmo de sempre.",--Cook meth. Same as always.
	pln_nai_02_02 = "Ok. Isso foi inesperado, mas nós ainda temos um trabalho a fazer.",--Okay. This is unexpected, but we still have a job to do.
	pln_nai_07_03 = "Certo, aqui estão os ingredientes. Porém tem mais do que pra uma única carga. Hora de colocar a mão na massa.",--All right, there's the ingredients. But this is going to take more than a single load. Keep throwing it in.
	pln_nai_01_03 = "Estamos aqui. Estejam prontos pra assustá-los, gangue.",--We're here. Get ready to scare 'em, crew.
	pln_nai_10_03 = "A metanfetamina precisa ser divida em pequenos pedaços. Detonem com ela, pessoal!",--The meth needs breaking up into little pieces. Get angry on it, gang!
	pln_nai_20_02 = "Viemos, vimos, chutamos a bunda deles!",--We came, we saw, we kicked their ass!
	pln_nai_10_02 = "Lembrem-se: Vocês precisam esmagar a metanfetamina.",--Remember, you gotta smash up that meth. 
	pln_nai_04_03 = "Joguem esses comprimidos na batedeira, pessoal.",--Toss those tablets into the mixer, crew.
	pln_nai_09_01 = "Ok, agora vocês precisam esmagar essa metanfetamina. Acabem com ela, pessoal!",--Okay, now you need to smash up that meth. Get wrecking, crew!
	pln_nai_17_01 = "Nem mesmo uma bolsa?! Isso é um pesadelo!",--Not a single bag?! This is a nightmare!
	pln_nai_16_01 = "Bem, de acordo com o manual de rolas criminais, isso recebe um alto destaque. Posso ouvir os policiais rindo daqui. Melhor sorte da próxima vez. ",--Well, in the annals of criminal cock-ups, that ranks high. I can hear the cops laughing from here. Better luck next time.
	pln_nai_11_02 = "Certo. Agora vocês podem continuar cozinhando, ou sinalizar para o helicóptero e finalizar essa loucura.",--All right. Now you can keep cooking, or signal the chopper and end this caper.
	pln_nai_cnc_01_02 = "Travessura de Halloween, pessoal. Volte novamente pra cabana na floresta.",--Halloween treat, guys. Headed back to the cabin in the woods.
	pln_nai_14_01 = "Apenas joguem as bolsas dentro de um dos recipientes no chão. Eu vou enviar...alguém pra pegar mais tarde.",--Just throw the bags into one of the containers on the floor. I'll send...someone to pick it up later.
	pln_nai_14_02 = "Agora guardem essas bolsas no recipiente do chão. Tenho total certeza de que consigo encontrar alguém pra pegá-lo.",--Now stow those bags in the container on the floor. I'm sure I can find someone to collect it.
	pln_nai_05_03 = "Esperem, gangue. Temos mais um lote de ingredientes a caminho daqui.",--Stand by, crew. I got a batch of ingredients on their way.
	pln_nai_03_03 = "Ok. Então. A Efedrina vai começar essa alquimia. Coloquem alguns comprimidos dentro daquela batedeira.",--Okay. So. Ephedrine will start the alchemy. Get some tablets in the mixer.
	pln_nai_05_01 = "Eu vou mandar a quantia necessária de ingredientes pra vocês. Aguentem firme.",--I will send in the necessary ingredients for you. Hold tight.
	pln_nai_15_03 = "Eu escutei alguma coisa...",--I heard something...
	pln_nai_22_03 = "Isso é culinária. Que bela música isso me faz lembrar!",--It's cooking. What music it makes!
	pln_nai_cnc_01_01 = "A floresta é escura e assustadora durante a noite, gangue. Vamos cozinhar um pouco de metanfetamina.",--The forest is dark and spooky tonight, gang. Let's cook a little meth.
	pln_nai_06_01 = "Aguentem firme, meus fantasminhas camaradas. Quase lá.",--Just hang tight, my groovy ghoulies. Almost there.
	pln_nai_01_01 = 'Estejam prontos para pular e gritar "BOO!, gangue."',--Get ready to jump out and shout "boo!", gang.
	pln_nai_12_01 = "Bom ponto. Agora esperamos.",--Good spot. Now we wait.
	pln_nai_04_01 = "Fala sério, meus pequeninos - joguem os comprimidos pra dentro da batedeira.",--Come on, my little Igors - get the tablets in the mixer.
	pln_nai_14_03 = "Agora deixem as bolsas dentro dos recipientes lá do chão. Nós vamos voltar pra pegá-los.",--Now get those bags in the containers down on the floor. We'll return and collect them.
	pln_nai_22_02 = "Isso está virando um monstro!",--This is going to be a monster!
	pln_nai_08_01 = "Ok. Isso é bom. Agora vamos pegar mais.",--Okay. That's good. Now get more in there.
	pln_nai_21_03 = "Tenha medo... Tenha muito medo.",--Be afraid... Be very afraid.
	pln_nai_brf_01_01 = "Nós estamos trabalhando no Laboratório, até tarde hoje, deixando os olhos abertos para uma visão estranha. Cozinhando em cima da mesa, borbulhando e fervendo. E mantendo os policiais, encrencados e cansados.",--We're working in the lab, late tonight, letting your eyes behold an eerie sight. Get cooking on the table, bubble and boil.And keep the cops from bringin', trouble and toil.
	pln_nai_19_01 = "Grande feito! Isso irá nos trazer bons pedaços de mudança. Bom trabalho!",--Nice haul! This will bring in a nice chunk of change. Good job!
	pln_nai_18_02 = "O trabalho não foi um fiasco completo. Ainda teremos pequenas bolsas em baixo dos degraus do Leatherface.",--The job wasn't a total bust. Still, fewer stuffed bags than under Leatherface's stairs!
	pln_nai_10_01 = "Não se esqueçam. Esmaguem a metanfetamina em pedaços bem menores!",--Don't forget. Smash the meth into smaller chunks! 
	pln_nai_05_02 = "Ok, eu tenho ingredientes a caminho. Aguardem um pouco.",--Okay, I have ingredients on their way. Stand by.
	pln_nai_03_01 = "Nós precisamos adicionar comprimidos de Efedrina para iniciar o processo. Encontrem algumas e joguem na batedeira.",--We need to add ephedrine tablets to start the cooking process. Find some and add it into the mixer.
	pln_nai_22_01 = "Está vivo! Vivo!",--It's alive! Alive!
	pln_nai_12_03 = "Feito. Agora aguardem pelo sinal do piloto.",--That's it. Now wait for the pilot to signal in.
	pln_nai_07_02 = "Os Ingredientes acabaram de chegar. Podemos cozinhar mais uma leva para levarmos. Continuem jogando-as lá dentro.",--Ingredients have arrived. Going to take more than one load though. Keep throwing them in.
	pln_nai_21_05 = "Um, dois, policiais estão vindo até vocês...",--One, two, cops are coming for you...
	pln_nai_08_03 = "Certo. É, isso é bom. Talvez um pouco mais, então.",--All right. Yeah, this is good. Going to need more, though.
	pln_nai_08_02 = "Sim. tá funcionando. Apenas precisamos de mais um pouco. Continuem carregando.",--Yes. It's working. Just need more in there. Keep loading.
	pln_nai_02_01 = "Uh, ok....",--Uh, okay....
	pln_nai_02_03 = "Mamãe sempre me dizia que o mundo lá fora era gigante, mas isso...",--Momma always said it was a big world out there, but this...
	pln_nai_03_02 = "Primeiro, peguem alguns comprimidos de Efedrina e joguem eles dentro daquela batedeira.",--First, grab some ephedrine tablets and throw 'em in the mixer.
	pln_nai_06_02 = "Os ingredientes estão quase com vocês, pessoal.",--Ingredients are almost with you, crew.
	pln_nai_06_03 = "Apenas segurem um pouco mais o exército da escuridão. Os ingredientes estão quase aí já.",--Just hold off the armies of darkness. Ingredients are almost with you.
	pln_nai_07_01 = "Ok, aí estão os ingredientes. Vai precisar de um pouco mais lá, quem sabe. Mais do que uma bolsa.",--Okay, there's the ingredients. Going to need a little extra in there, though. More than one bag.
	pln_nai_09_02 = "A metanfetamina está feita, mas não podemos pegá-la do jeito que ela está. Quebrem, Esmaguem, Atirem, Explodam ela - apenas dividam isso em partes menores!",--The meth's set, but we can't get it out like that. Break it down. Smash it, shoot it, blast it - just break it down!
	pln_nai_11_01 = "Acrescente um pouco mais de comprimidos pra continuar a cozinhar. Ou dê o sinal para o helicóptero vir buscar vocês - você quem manda.",--Add more tablets to continue the cooking. Or signal the helicopter to escape - your call.
	pln_nai_11_03 = "Jogue mais comprimidos na batedeira se quiserem continuar a cozinhar, gangue. Ou acenda o sinalizador e vaze. A decisão está em suas mãos.",--Throw more tablets in the mixer if you want to keep cooking, crew. Or light the flare and bail. Up to you!
	pln_nai_12_02 = "Ok, agora esperem pelo piloto.",--Okay, now wait for the pilot.
	pln_nai_13_01 = "Aqui tá o helicóptero, gangue. Vamos!",--There's the chopper, gang. Get to it!
	pln_nai_13_02 = "Helicóptero aqui. Venham.",--Chopper's here. Get on it.
	pln_nai_13_03 = "É o helicóptero. Vamos até ele, pessoal!",--That's the helicopter. Get on it, crew!
	pln_nai_15_01 = "Não olhem agora, mas...",--Don't look now, but...
	pln_nai_15_02 = "Essa não é a música doce das crianças da noite.",--That ain't the sweet music of the children of the night. 
	pln_nai_16_02 = "Bolha, bolha, fadiga e problemas. Na maioria das vezes fadiga e problemas. Especialmente problemas.",--Bubble, bubble, toil and trouble. Mostly toil and trouble. Especially trouble.
	pln_nai_17_02 = "Vocês não conseguiram nada? Vocês estão me matando, pessoal!",--You got nothing? You guys are killing me!
	pln_nai_17_03 = "Vocês não conseguiram pegar nada?",--You didn't get anything out? 
	pln_nai_18_01 = "Bem, vocês conseguiram uma quantia decente. Um pouco mais e irá cobrir o dinheiro da gasolina. Talvez em uma próxima vez nós podemos ir um pouco mais além.",--Well, you got a decent amount. Just about covers the gas money. Maybe next time we can push it further.
	pln_nai_18_03 = "O nosso transporte de caveiras chegou. Boa sorte no próximo ano, gangue.",--It's a bare bones haul, but it'll do. Better luck next year, crew.
	pln_nai_19_02 = "Vocês pegaram uma quantidade razoável de bolsas. Muito bem!",--You snatched a decent amount of bags there. Well done!
	pln_nai_19_03 = "Foi uma ótima viagem de Doces ou Travessuras. Vamos pra casa, gangue. Vamos compartilhá-la!",--That's a nice haul of trick or treat goodies. Come home, gang, let's share it out!
	pln_nai_20_01 = "Caralho! Vocês mandaram muito bem! Curtam os seus Pagamentos - vocês mereceram.",--Hot damn! You guys did great! Enjoy your payday - you deserve it.
	pln_nai_20_03 = "Vocês são ótimos! Eu sou o fã número um de vocês!",--You guys are great! I'm your number one fan!
	pln_nai_21_01 = "Eles estão aqui.",--They're here.
	pln_nai_21_02 = "Aqui é o Johnny!",--Here's Johnny!
	pln_nai_21_04 = "Eu gostaria de ouvir o choro de medo vindo desses policiais!",--I want to hear a cry of fear from those cops!
	pln_nai_cbf_01_01 = "Doces ou Travessuras, cheire meus pés. Me dê algo para colocar na rua. Se você não puder, eu não ligo. Só não cozinhe de cueca.",--Trick or treat, smell my feet. Give me something to put on the street. If you don't, I don't care. Just don't cook in your underwear.
	pln_nai_cnc_01_03 = "Tá na hora de assar alguns doces de Halloween, gangue. Vamos pro laboratório de metanfetamina na floresta.",--Time to bake some Halloween treats, crew. Get to the forest meth lab.
	
	-- Legendas (Prison Nightmare)
	pln_hlp_10_03 = "Fumaça a caminho, pessoal!",--Smoke incoming guys!
	pln_hlp_21_02 = "Ótimo, vocês conseguiram o Cartão de Acesso.",--Great you got the keycard.
	pln_hlp_12_03 = "Furadeiras chegando!",--Drills incoming!
	pln_hlp_09_03 = "Fumaça? a roda parou na fumaça?",--Smoke? The wheel stopped on smoke?
	pln_hlp_08_03 = "Chamas, isso significa lança-chamas de novo!",--Flames, that means the flamethrower again!
	pln_hlp_20_02 = "O cronômetro terminou. Peguem o Cartão de Acesso.",--Timer has finished. Get the keycard.
	pln_hlp_11_03 = "A roda parou. está dizendo furadeiras. Eu juro que não tenho ideia do que seja.",--The wheel has stopped. It says drills. I got no clue.
	pln_hlp_22_01 = "O cartão de acesso que você pegou deve te dar acesso a prisão, use esse cartão no leitor do lado da porta.",--The keycard you got should get us access to the prison, use it on the card reader by the door.
	pln_hlp_27_03 = "Por que tá demorando tanto tempo? Apenas ative o interruptor.",--What's taking so long? Just activate that switch
	pln_hlp_28_03 = "Certifiquem-se de verificar o piso superior caso queiram sair desse lugar. Só que tem tantas bolsas...",--Make sure to check the top floor if you wanna leave this place. But there are so many bags...
	pln_hlp_26_03 = "Coloquem o cartão de acesso no painel, rápido.",--Get that keycard in the panel, quick
	pln_hlp_33_01 = "Cuidado, parece que essas bolsas vão explodir!",--Careful, looks like the bags are gonna explode!
	pln_hlp_27_01 = "Puxem o interruptor e vejamos o que acontece.",--Pull the switch and see what happens
	pln_hlp_38_01 = "Vocês por um acaso são loucos? deixem essa bolsa!",--Are you guys insane? Leave that bag!
	pln_hlp_24_02 = "Deve ter outra roda por aqui em algum lugar.",--There should be another wheel around here somewhere.
	pln_hlp_20_03 = "Boa, terminou. Peguem o Cartão de Acesso",--Great it is done. Get the keycard.
	pln_hlp_19_03 = "Quando o tempo chegar no zero ele deve começar o cronômetro normal de novo.",--When the reboot has reached zero it should start the normal timer again.
	pln_hlp_06_01 = "Parou no Sniper novamente. Estejam preparados, pessoal.",--It landed on sniper again. Get ready guys
	pln_hlp_15_03 = "Dozer? não parece ser algo legal.",--Dozer? That can't be good.
	pln_hlp_12_01 = "Isso parou em furadeiras. saiam daí!",--It stopped on drills. Move away!
	pln_hlp_26_01 = "Coloquem o Cartão de Acesso",--Place that keycard
	pln_hlp_15_01 = "Dozer? Hmmm....",--Dozer? Hmmm....
	pln_hlp_16_01 = "A roda novamente parou em dozer. Tenham cuidado, pessoal!",--The wheel stopped on the dozer again. Watch out guys!
	pln_hlp_26_02 = "Vocês já conseguiram o cartão de acesso, correto?",--You guys got a keycard, right?
	pln_hlp_28_02 = "Meus sensores estão pegando um outro painel no último andar - cheguem até lá caso vocês já tenham tido o suficiente por hoje e queiram sair.",--My sensors are picking up another panel on the top floor - get to it if you've had enough and want to leave.
	pln_hlp_05_02 = "A roda parou no Sniper. Não tenho certeza do que se trata...",--The wheel stopped on sniper. I'm not sure what that means...
	pln_hlp_05_01 = "Sniper? Isso... caiu no Sniper.",--Sniper? It... landed on sniper.
	pln_hlp_24_01 = "Eu acho que deveríamos encontrar outra roda para girar. Encontrem-na.",--I think we might need to spin another wheel. Find it.
	pln_hlp_23_01 = "Hora de verificar o que essa prisão nos reserva.",--Time to see what the prison has in store for us.
	pln_hlp_03_01 = "Nós vamos precisar de um cartão de acesso para entrar na prisão. Mas onde nós podemos conseguir um?",--We need a keycard to get into the prison. But where can we get one?
	pln_hlp_33_03 = "Tenham cuidado com essas bolsas agora!",--Watch out for those bags now!
	pln_hlp_18_04 = "Liguem esse cronômetro novamente.",--Get the timer going again.
	pln_hlp_02_03 = "Acho que precisamos entrar nessa prisão.",--I think we need to get into the prison.
	pln_hlp_33_02 = "Cuidado, essas bolsas estão esquentando!",--Watch out, the bags are getting hot!
	pln_hlp_11_02 = "A roda parou em furadeiras. Vocês sabem o que isso significa?",--The wheel stopped on drills. Do you guys know what that means?
	pln_hlp_22_02 = "O cartão de acesso nos garante o acesso. Usem para abrir a porta.",--The keycard grants us access. Use it to open the door.
	pln_hlp_01_03 = "Eu... não sei onde nós estamos...",--I... don't know where we are...
	pln_hlp_31_03 = "O relógio está correndo muito rápido. Peguem o loot e jogue-os dentro da ventilação!",--The clock on the wall's running down fast. Grab the loot and toss it into the vent!
	pln_hlp_14_01 = "Tenham muito cuidado, pessoal! A roda parou nos pontos de interrogação.",--Careful guys! The wheel stopped on the question marks.
	pln_hlp_18_07 = "O cronômetro está parado. Comecem ele novamente!",--The timer is standing still. Get it going again!
	pln_hlp_29_02 = "Ok, o mesmo de antes: assegurar o máximo de bolsas que conseguirmos ou vazar do lugar. Decidam-se",--Okay, same as before: secure as many bags as you can or leave this place. Make up your mind!
	pln_hlp_17_01 = "Protejam esse cronômetro, a SWAT vai tentar pará-lo a todo instante.",--Protect the timer, the swats will interrupt it if you don't!
	pln_hlp_10_01 = "A roda parou na fumaça!",--The wheel stopped on smoke!
	pln_hlp_39_01 = "Alí está a nossa fuga! CORRAM!",--There's the escape! RUN!
	pln_hlp_18_02 = "Pessoal, o cronômetro parou!",--Guys the timer stopped!
	pln_hlp_18_03 = "Porra, eles pararam. Coloquem pra funcionar de novo!",--Damn, they stopped it. Get it going again!
	pln_hlp_04_01 = "Eu não acho que temos escolha. Nós temos que girar essa roda!",--I don't think we have a choice. We have to spin that wheel!
	pln_hlp_03_02 = "Não vamos poder entrar sem um cartão de acesso. Precisamos encontrar um.",--We can't get in without a keycard. We need to find one.
	pln_hlp_13_03 = "O que? Parou nos pontos de interrogação. Isso pode significar qualquer merda.",--What? It stopped on the question marks. That could mean anything.
	pln_hlp_17_03 = "Não deixem a SWAT interromper o cronômetro!",--Don't let the swats interrupt that timer!
	pln_hlp_07_03 = "A roda resolveu parar em chamas, eu sinceramente acho que não é uma boa coisa.",--The wheel stopped on flames, I don't think that is a good thing.
	pln_hlp_23_02 = "Continuem indo pra dentro da prisão.",--Keep moving into the prison.
	pln_hlp_14_03 = "Parou nos pontos de interrogação de novo.",--It stopped on the question marks again.
	pln_hlp_16_03 = "Se preparem para a chegada de outro Bulldozer!",--Get ready for another bulldozer!
	pln_hlp_17_02 = "Não deixem os policiais pararem o cronômetro!",--Don't let the cops stop the timer!
	pln_hlp_14_02 = "Pontos de interrogação mais uma vez. Estejam preparados pra tudo.",--Question marks again. Be ready for anything.
	pln_hlp_36_01 = "Nós estamos pegando o trem - peguem a tirolesa até a ponte!",--We're taking the train - grab the zipline up to the bridge!
	pln_hlp_35_02 = "Não há como voltar atrás - saiam dessa porra de lugar!",--There's no turning back - get out of this goddamn place!
	pln_hlp_35_03 = "Não há volta - o lugar está ficando bem perigoso! Vazem daí!",--Point of no return - this place is getting hot! Get out!
	pln_hlp_26_05 = "Vocês com certeza demoraram um longo tempo.",--You guys sure take an awfully long time.
	pln_hlp_31_01 = "Tá vendo aquele cronômetro ali? é melhor se apressarem caso queiram garantir o loot!",--See that timer over there? Hurry up if you wanna secure the loot!
	pln_hlp_07_01 = "Chamas?",--Flames?
	pln_hlp_34_02 = "Vocês terminaram - fiquem juntos!",--You're done - get together everyone!
	pln_hlp_36_03 = "Usem a tirolesa para chegar até a ponte. O trem é o nosso único caminho!",--Use the zipline up to the bridge! The train is the only way out!
	pln_hlp_24_03 = "Continuem girando essas rodas, encontrem a próxima.",--Keep spinning those wheels, find the next one.
	pln_hlp_04_02 = "Sinceramente não gosto do visual desses prêmios dessa roda, mas eu acho que devemos girar isso de qualquer jeito.",--I don't like the look of the prizes on that wheel, but I think we have to spin it anyway.
	pln_hlp_26_04 = "Estão esperando o que? Peguem o cartão de acesso e coloquem no painel.",--What are you waiting for? Get that keycard into the panel.
	pln_hlp_18_05 = "O cronômetro parou! Reiniciem!",--The timer stopped! Restart it!
	pln_hlp_16_02 = "A roda parou. Estejam prontos para outro Bulldozer, pessoal!",--The wheel stopped. Get ready for another bulldozer guys!
	pln_hlp_23_03 = "Ótimo, vamos continuar.",--Great, let's keep going.
	pln_hlp_27_02 = "Apenas puxem o interruptor, pessoal.",--Just pull the switch, guys
	pln_hlp_09_01 = "Fumaça?",--Smoke?
	pln_hlp_01_01 = "Droga, mas que lugar é esse?",--Damn, what is this place?
	pln_hlp_01_02 = "Uma prisão? não é um dos meus lugares favoritos...",--A prison? Not my favourite thing...
	pln_hlp_02_01 = "Vamos achar uma forma de entrar nessa prisão.",--Let's find a way into the prison.
	pln_hlp_02_02 = "Nós provavelmente precisamos entrar nessa prisão...",--We probably need to enter the prison...
	pln_hlp_03_03 = "Parece que esse portão pede por um cartão de acesso. Encontrem um, pessoal!",--Looks like this gate requires a keycard. Find one guys!
	pln_hlp_04_03 = "Girem isso, vamos ver o que acontece.",--Spin it, let's see what happens.
	pln_hlp_05_03 = "Então... a roda parou em Sniper...",--Soooo the wheel stopped on sniper... 
	pln_hlp_06_02 = "A roda parou em Sniper!",--The wheel stopped on sniper!
	pln_hlp_06_03 = "A roda se decidiu, ao que tudo indica nós teremos a presença de mais Snipers logo logo.",--The wheel has decided, looks like we have some more snipers incoming.
	pln_hlp_07_02 = "Isso caiu em chamas... Não pode ser bom.",--It landed on flames... That can't be good.
	pln_hlp_08_01 = "A roda parou em chamas. as coisas estão prestes a pegar fogo!",--The wheel stopped on flames. Things are about to burn!
	pln_hlp_08_02 = "Ok, a roda novamente parou em chamas, tenham muito cuidado.",--Ok the wheel landed on flames again, watch out!
	pln_hlp_09_02 = "A roda parou em fumaça, não tenho ideia do que isso significa.",--The wheel stopped on smoke, no idea what that means.
	pln_hlp_10_02 = "Sim, é fumaça mais uma vez!",--Yep, it's smoke again!
	pln_hlp_11_01 = "Furadeiras? Não tenho tanta certeza do que isso significa...",--Drills? Not sure what that is...
	pln_hlp_12_02 = "Cuidado, pessoal! Parou em furadeiras de novo!",--Watch out! It stopped on drills again!
	pln_hlp_13_01 = "Hmm.. Eu me pergunto o que esses pontos de interrogação significam.",--Hmm.. I wonder what the question mark means.
	pln_hlp_13_02 = "Pontos de Interrogação?! que porra significa isso?",--Question marks? What could that be?
	pln_hlp_15_02 = "A roda parou no... dozer? Estejam atentos, pessoal. Eu não tenho certeza do que isso significa.",--The wheel stopped on... dozer? Be careful guys Im not sure what that means.
	pln_hlp_18_01 = "Eles interromperam o cronômetro! Reiniciem isso!",--They interrupted the timer! Restart it!
	pln_hlp_18_06 = "Reiniciem o cronômetro! Eles pararam.",--Restart the timer! They stopped it.
	pln_hlp_19_01 = "Uma vez que a reinicialização for feita, estaremos no caminho novamente!",--Once the reboot is over we should be back on track!
	pln_hlp_19_02 = "Quando a reinicialização for feita, ela irá retomar de onde parou.",--When the reboot has ticked down it should restart.
	pln_hlp_20_01 = "Ótimo, o cronômetro terminou! Peguem o cartão de acesso!",--Great the timer is done! Grab the keycard!
	pln_hlp_21_01 = "Bom trabalho. Agora vamos indo.",--Good job. Now lets get moving.
	pln_hlp_21_03 = "Agora que finalmente vocês pegaram o cartão de acesso, continuem seguindo em frente.",--Now that you got the keycard lets move on.
	pln_hlp_22_03 = "Agora vamos entrar na prisão. Usem o cartão de acesso pra abrirem a porta.",--Now let's enter the prison. Use the keycard to open the door.
	pln_hlp_25_01 = "Coloquem o cartão de acesso dentro do painel e puxem o interruptor. Vamos ver o que irá acontecer.",--Get that keycard into the panel and pull that switch. Let's see what happens.
	pln_hlp_25_02 = "Vejamos... Coloquem o cartão de acesso e ativem o interruptor. Espero que não tenhamos uma grande surpresa...",--Let's see... Place the keycard in the panel and activate that switch. Hope we're not in for a big suprise...
	pln_hlp_25_03 = "Aqui tem um slot para o cartão de acesso. Meu palpite seria apenas colocá-lo aí nesse painel e verificar o que vai acontecer...",--There's a slot for the keycard. My guess is just put it in and see what happens...
	pln_hlp_27_04 = "Vão até o painel e puxem a porra do interruptor.",--Go by the panel and pull that goddamn switch
	pln_hlp_27_05 = "O que vocês estão esperando? Esse interruptor não vai ser puxado sozinho.",--What are you waiting for? That switch isn't gonna pull itself.
	pln_hlp_28_01 = "Caso queiram sair, tem um painel de fuga no último andar. Chequem ele no caso de quererem ir embora.",--If you wanna leave, there's an escape panel on the top floor. Check it out if you wanna call it quits.
	pln_hlp_29_01 = "Mesma coisa da última vez - peguem o loot ou saiam da prisão no último andar.",--Same procedure as last time - grab the loot or leave this prison on the top floor.
	pln_hlp_29_03 = "Vocês já conhecem o negócio, pegar o loot ou fugir.",--You know the deal, grab the loot or escape.
	pln_hlp_30_01 = "Eu tenho certeza absoluta de que não tenho que explicar a vocês o que é pra ser feito.",--I'm sure I don't have to explain what you need to do.
	pln_hlp_30_02 = "Vocês já conhecem o caminho dessa prisão, já sabem o que fazer.",--You know your way around this prison, you know what to do.
	pln_hlp_30_03 = "Mesma coisa de sempre.",--Same procedure as always.
	pln_hlp_31_02 = "O cronômetro está indo bem rápido! Peguem o loot e joguem na ventição!",--That timer on the wall's ticking fast! Get the loot into the vent!
	pln_hlp_32_01 = "Cuidado, pessoal. O tempo está se esgotando! 10 segundos!",--Careful guys, time's running out! 10 seconds!
	pln_hlp_32_02 = "O tempo está quase acabando!",--Time's almost up!
	pln_hlp_32_03 = "10 segundos no relógio!",--10 seconds on the clock!
	pln_hlp_34_01 = "Estejam juntos em grupo, pessoal!",--Get together in a group, guys!
	pln_hlp_34_03 = "Fiquem juntos, time.",--Stick together team.
	pln_hlp_35_01 = "O lugar todo está começando a desmoronar, vazem daí!",--The place is starting to fall apart, get out!
	pln_hlp_36_02 = "Há uma tirolesa que os levará para o trem na ponte. Usem-a até o céu!",--There's a zipline leading to a train up on the bridge. Zip through the sky!
	pln_hlp_37_01 = "Aguentem, pessoal. Eu estou enviando um pouco de C4",--Hold on guys, I'll send some C4...
	pln_hlp_38_02 = "O que é isso, loot extra? Vocês têm certeza de que querem fazer isso?",--What's that, extra loot? You sure you wanna do that?
	pln_hlp_38_03 = "Realmente vocês têm certeza de que querem ser gananciosos justo agora?",--You sure you wanna be greedy now?
	pln_hlp_39_02 = "Corram, galera, corram!",--Run, heisters, run!
	pln_hlp_39_03 = "Cheguem até o local de fuga! RÁPIDO!",--Get to the escape! HURRY!
	
	-- Objetivos (Lab Rats)
	hud_heist_nail_1_hl = "Adicione Comprimidos de Efedrina",--Add ephedrine pills
	hud_heist_nail_7_hl = "Fuja!",--Escape!
	hud_heist_nail_4 = "O lote já está pronto. Se você quiser continuar a cozinhar outra, você vai precisar adicionar mais comprimidos de efedrina. Caso contrário, já tem um sinalizador pronto pra ser aceso no topo do barril coberto por um cobertor. O veículo de fuga estará aguardando um sinal para ir buscá-lo.",--The batch is done. If you want to cook another one just add some more ephadrine pills. Otherwise there is a flare ready to be lit ontop of the barrel covered with a blanket. An escape vehicle is waiting for the signal to come and pick you up.
	hud_heist_nail_5_hl = "Divida e pegue a Metanfetamina",--Smash up and bag the meth
	hud_heist_nail_6_hl = "Espere pela Fuga",--Wait for the escape
	hud_heist_nail_7 = "Reuná-se no topo onde foi colocado o sinalizador e fuja no helicóptero.",--Gather up and escape with the helicopter.
	hud_heist_nail_2_hl = "Aguarde pelos Ingredientes",--Wait for the ingredients
	hud_heist_nail_3 = "Siga as instruções do Bain para saber qual o próximo ingrediente a ser acrescentado e faça um lote de metanfetamina.",--Follow Bain's instruction on what ingredient to add next and cook a batch of meth.
	hud_heist_nail_1 = "O primeiro passo para a criação da metanfetamina é adicionar comprimidos de Efedrina. Ache alguns e coloque no recipiente marcado.",--The first step to the meth cooking process is to add ephedrine pills. Find some and put it in the marked container.
	hud_heist_nail_2 = "O Bain enviou um avião para entregar os ingredientes necessários.",--Bain has sent a plane to drop off the necessary ingredients
	hud_heist_nail_6 = "Um veículo de fuga está a caminho.",--An escape vehicle is on its way
	hud_heist_nail_4_hl = "Cozinhe mais ou Fuja",--Cook more or escape
	hud_heist_nail_5 = "Não se pode transportar a metanfetamina até que ela esteja em pedaços pequenos. Divida-os em pedaços menores e coloque em uma bolsa.",--We can't transport the meth until it is in smaller pieces. Break it down into smaller pieces and bag it.
	hud_heist_nail_3_hl = "Adicione o Ingrediente Certo",--Add the correct ingredient
	
	-- Legendas (Prison Nightmare)
	hud_heist_help_loud_09 = "Fogos estão engolindo a prisão.",--Fires are engulfing the prison.
	hud_heist_help_loud_03_hl = "Defenda a Roda",--Defend the wheel
	hud_heist_help_loud_05_hl = "Pegue o Cartão de Acesso",--Take the keycard
	hud_heist_help_loud_11_hl = "Chegue ao Trem",--Reach the trains
	hud_heist_help_loud_13_hl = "Exploda a Porta do Trem",--Blow up the train door
	hud_heist_help_loud_08_hl = "Hora de Fugir!",--Time to escape
	hud_heist_help_loud_13 = "A única coisa em seu caminho agora é a porta dos fundos do trem. Exploda ela usando o C4!",--The only thing in your way now is the back door of the train. Blow it up using your C4!
	hud_heist_help_loud_12 = "Resista até que o Bain envie o C4 pelo helicóptero.",--Hold out while Bain sends in some C4 via helicopter.
	hud_heist_help_loud_05 = "Você sobreviveu ao desafio, agora pegue o seu prêmio!",--You have survived the challenge, now claim your prize!
	hud_heist_help_loud_03 = "Defenda a roda, não deixe ninguém desligá-la ou haverá uma penalidade!",--Defend the wheel, don't let anyone disable it or there will be a penalty!
	hud_heist_help_loud_01 = "Ninguém gosta de prisões, mas tem algo de difente a respeito dessa. Hora de encontrar o motivo.",--No one likes prisons, but there's something that is different about this one. Time to find out what.
	hud_heist_help_loud_04 = "A roda está quebrada, você precisa reiniciá-la!",--The wheel is broken, you need to restart it!
	hud_heist_help_loud_06_hl = "Abra as Portas ou Fuja",--Open doors or escape
	hud_heist_help_loud_02_hl = "Gire a Roda",--Spin the wheel
	hud_heist_help_loud_10_hl = "Chegue até a Tirolesa",--Get to the ziplines
	hud_heist_help_loud_06 = "Use o seu cartão de acesso para ativar o painel da porta da prisão ou o painel de fuga.",--Use your keycard to activate the prison door panel or the escape panel.
	hud_heist_help_loud_14_hl = "Chegue até a Saída!",--Get to the Escape
	hud_heist_help_loud_01_hl = "Entre na Prisão",--Enter The prison
	hud_heist_help_loud_07_hl = "Assegure o Loot na Ventilação",--Secure loot in vent
	hud_heist_help_loud_12_hl = "Resista até a chegada do C4",--Hold out for C4
	hud_heist_help_loud_04_hl = "Reinicie a Roda",--Restart the wheel
	hud_heist_help_loud_14 = "Siga em direção à luz branca no final da ponte!",--Head towards the white light at the end of the bridge!
	hud_heist_help_loud_02 = "Você foi desafiado para girar a roda da desgraça. Você se atreveria?",--You have been challenged to spin the wheel of misfortune. Do you dare!?
	hud_heist_help_loud_11 = "Use a Tirolesa para chegar no trem lá na ponte.",--Use the zipline to reach the trains on the bridge.
	hud_heist_help_loud_09_hl = "Saia da Prisão",--Leave the prison
	hud_heist_help_loud_10 = "Chegue até a Tirolesa pela entrada do túnel.",--Get to the ziplines by the tunnel entrance.
	hud_heist_help_loud_07 = "O loot está saindo da prisão, tente assegurar o máximo que você conseguir antes que o tempo acabe!",--The loot is pouring from the prison, try and secure as much as you can before time runs out!
	hud_heist_help_loud_08 = "Puxe o interruptor e fuja agora ou esteja preso para sempre nesse pesadelo infernal.",--Pull the switch and escape now or forever be trapped in this nightmare.

	-- Objetivos (Cursed Kill Room)
	hud_heist_hvh_02 = "Todos precisam estar dentro do círculo ao redor do cofre. Não saia até o tempo se esgotar!",--Everyone must stand in the circle by the safe. Don't leave until the timer is finished!
	hud_heist_hvh_04_hl = "Volte para o Início",--Loop back to start
	hud_heist_hvh_04 = "Hora de começar novamente, vá para a saída e corra pelo corredor. O tempo está se esgotando!",--Time to start over again, get to the exit and run down the hallway. Time is ticking!
	hud_heist_hvh_01_hl = "Entre na KillRoom",--Enter the killroom
	hud_heist_hvh_01 = "Pressione o botão de início para começar o evento do cofre.",--Press the start button to begin the Safe Event.
	hud_heist_hvh_03_hl = "Assegure o Loot",--Secure the loot
	hud_heist_hvh_03 = "Assegure o loot do Cloaker em uma ventilação próxima.",--Secure the cloaker loot in a vent nearby.
	hud_heist_hvh_02_hl = "Defenda o Cofre dos Cloakers",--Defend cloakers safe
	hud_heist_hvh_05 = "O seu tempo acabou! Use o botão de fuga para sair.",--You have run out of time! Use the escape button to leave.
	hud_heist_hvh_05_hl = "Pressione o Botão de Fuga",--Press the escape button
	
	-- Objetivos (Safe House Nightmare)
	hud_haunted_mission1 = "...",--...
	hud_haunted_mission2_hl = "Acorde!",--Wake up!
	hud_haunted_mission2 = "...",--...
	hud_haunted_mission1_hl = "Salve o seu Dinheiro!",--Save your money!	
		}