return {
	menu_mutators_category_all = "Todos",
	menu_mutators_category_enemies = "Inimigos",
	menu_mutators_category_gameplay = "Jogabilidade",
	menu_mutators_reset_all = "Redefinir todas as mutações",--Reset all mutators
	menu_mutators_desc = "Mutações deixam você personalizar a sua experiência no PAYDAY 2 ao mudar algumas coisas ou por adicionar efeitos incomuns para a jogatina. Algumas mutações possuem mudanças bem pequenas, já outras podem mudar o jogo completamente ou a dificuldade do jogo.",
	dialog_mutators_active_text = "O Host desse Lobby possui Mutações ativadas! A sua experiência durante a partida pode ser bem diferente do que o normal. Você também pode ter problemas na performance do jogo.\n\nTem certeza de que deseja jogar com as Mutações?",--The host of this lobby has mutators enabled! Your experience during a game started in this lobby may be vastly different from the normal PAYDAY 2 experience. You may also experience adverse effects on your game's performance.$NL;$NL;Are you sure you want to play with mutators?
	dialog_leave_lobby = "Me tire daqui!",--Get me out of here!
	menu_mutators_achievement_disabled = "As conquistas e a maioria dos troféus estão desabilitados! E os níveis não vão acumular!",--The earning of achievements and of most trophies is currently disabled! Also, level completions will not accumulate!
	menu_mutators_reduction = "Você irá receber $cash_reduction% a menos de dinheiro e $exp_reduction% a menos de experiência e os custos de limpeza vão ser desativados. Esses efeitos só vão durar enquanto as Mutações estiverem ativadas!",--You will also earn $cash_reduction;% less cash and $exp_reduction;% less experience, and cleaner costs will be disabled. These effects last for as long as mutators are active!
	menu_mutators_incompatibilities = "Essa Mutação não pode ser habilitado, pois é incompatível com:\n$mutators",--This mutator can not be enabled as it is incompatible with:$NL;$mutators;
	--mutator_enemy_damage = "Alternate Arsenal",
	mutator_enemy_damage_longdesc = "Jogadores vão levar mais dano do que o normal dos inimigos.",
	mutator_enemy_damage_desc = "Modifica o quanto de dano os inimigos vão causar nos jogadores.",
	--mutator_medidozer = "BFFs",
	mutator_medidozer_desc = "Todos os inimigos normais são substituídos por Médicos e todas as unidades especiais são substituídas por Bulldozers.",
	mutator_medidozer_longdesc = "Durante as ondas das Operações Policiais, os inimigos são substituídos por Médicos e todas as unidades especiais são substituídos por Bulldozers.",
	--mutator_enemy_health = "Because of Training",
	mutator_enemy_health_desc = "Modifica a quantidade de vida dos inimigos.",
	mutator_enemy_health_longdesc = "Inimigos vão spawnar com mais vida do que o normal, fazendo eles mais fácil ou difícil de matar.",
	--mutator_specials_override = "Clone Army",
	mutator_specials_override_desc = "Define qual unidade especial vai substituir todos os inimigos.",
	mutator_specials_override_longdesc = "Todos os inimigos que spanwar durante a Operação Polícial vão ser substituídos pelo mesmo número da unidade especial que você selecionar.",
	--mutator_creeps = "Creeps",
	mutator_creeps_desc = "Todos os inimigos explodem quando morrem.",
	mutator_creeps_longdesc = "Matando um inimigo irá fazer com que ele exploda, causando dano aos jogadores.",
	--mutator_shotgun_tweak = "Extraterrestrial Heisters",
	mutator_shotgun_tweak_desc = "Espingardas agora irão abduzir os inimigos.",
	mutator_shotgun_tweak_longdesc = "Bain finalmente revelou a sua verdadeira forma como A Mãe-Bain, e as usas Espingardas agora irão abduzir os inimigos, assim você poderá retornar eles para a nave. Não desaponte a Mãe-Bain.",
	--mutator_friendly_fire = "Friendly Fire",
	mutator_friendly_fire_desc = "Jogadores podem causar dano um ao outro com armas normais.",
	mutator_friendly_fire_longdesc = "Você poderá causar dano em outros jogadores com qualquer arma.",
	--mutator_cloaker_effect = "Hurt Me More",
	mutator_cloaker_effect_desc = "Cloakers ganham um efeito especial ao chutar alguém.",
	mutator_cloaker_effect_longdesc = "Quando um Cloaker chuta alguém, será aplicado um efeito secundário.",
	--mutator_hydra = "Hydras",
	mutator_hydra_desc = "Matando um inimigo ele irá se dividir em dois inimigos mais fracos.",
	mutator_hydra_longdesc = "Matando um inimigo vai fazer com que ele se divida em dois inimigos mais fracos até não poder mais.",
	--mutator_shield_dozers = "Over Dozed",
	mutator_shield_dozers_desc = "Bulldozers são equipados com Shields.",
	mutator_shield_dozers_longdesc = "Todos os Bulldozers são equipados com Shields por proteção.",
	--mutator_titandozers = "Waking Nightmare",
	mutator_titandozers_desc = "Os Titan-Dozers Sem Cabeça sairam dos pesadelos do Wolf!",
	mutator_titandozers_longdesc = "Os Titan-Dozers Sem Cabeça sairam dos pesadelos do Wolf e se transformaram em realidade! Todos os Bulldozers normais agora vão ser os Titan-Dozers Sem Cabeça!",
	menu_mutators_reset = "Redifinir ao Padrão",
	menu_mutator_enemy_damage = "Multiplicador de Dano do Inimigo",
	menu_mutator_enemy_health = "Multiplicador de Vida do Inimigo",
	mutator_specials_override_select = "Unidade Especial",
	mutator_specials_override_medic = "Médicos",
	--mutator_specials_override_tank = "Bulldozers",
	--mutator_specials_override_taser = "Tasers",
	--mutator_specials_override_spooc = "Cloakers",
	--mutator_specials_override_shield = "Shields",
	menu_mutator_creeps_scale = "Escala da Explosão (Metros)",
	menu_mutator_creeps_nuclear = "Bulldozers Nucleares",
	menu_shotgun_tweak = "Força do Raio",
	menu_shotgun_tweak_mothership = "Para a Mãe-Nave!",
	menu_mutator_ff_damage = "Multiplicador de Dano do Friendly Fire",
	menu_mutator_cloaker_effect = "Efeito",
	menu_mutator_cloaker_effect_explode = "Explosão",
	menu_mutator_cloaker_effect_fire = "Fogo",
	menu_mutator_cloaker_effect_smoke = "Fumaça",
	menu_mutator_cloaker_effect_random = "Aleatório",
	menu_mutator_hydra_max = "Máximo de Divisão",
	menu_mutators_lobby_wait_desc = "Por favor espere enquanto verificamos se todo mundo quer jogar com as Mutações...",--Please wait while we check that everyone wants to play with mutators...
	menu_mutators_lobby_wait_title = "Mutações Ativas",
	cn_menu_contract_mutators_header = "MUTAÇÕES:",--MUTATORS:
	menu_cn_mutators_active = "Mutações Ativas",--Active Mutators

	-- Décimo Aniversário
	mutator_birthday = "Evento de Aniversário",--Anniversary Event
	menu_events_lobby_wait_title = "EVENTO ESTÁ ATIVO",--EVENT IS ACTIVE
	menu_event_a10th_info = "INFO. DO EVENTO",--EVENT INFO
	dialog_a10th_event_text = "Quando matar unidades especiais vão surgir balões que você pode atirar para conseguir Buffs para sua equipe, que seria um bônus direto ou temporário, depende da unidade que for morto. Algumas unidades fazem surgir balões mais frequentes do que os outros. Alguns Buffs podem ser ativos ao mesmo tempo.",
	--Killing special units will spawn balloons which you can shoot to give the entire team a buff, that will be either a direct bonus or timed, depending on which unit is killed. Some units spawn balloons more frequently than others. Several buffs can be active at the same time.
	dialog_a10th_event_title = "Evento de Décimo Aniversário",--10th Anniversary Event
	hud_buff_birthday_ammo_refresh = "Recuperação de Munição",--Ammo Refresh
	hud_buff_birthday_regenerate_armor = "Recuperação de Armadura",--Armor Recovery
	hud_buff_birthday_recover_health = "Recuperação de Vida",--Health Recovery
	hud_buff_birthday_god_mode = "Invencível",--God Mode
	hud_buff_birthday_inf_ammo = "Munição Infinita",--Infinite Ammo
	hud_buff_birthday_2x_damage = "Dano em Dobro",--2X Damage
}