return {
    alm_pda9_01_01 = "Beleza, assaltantes! Bora achar o Porquinho.",--Alright, heisters! Let's find that Piggy Bank.",
    alm_pda9_01_02 = "Não me pergunte do motivo da gente usar um Porquinho pro aniversário. Eu nem faço ideia.",--Don't ask me why we did a Piggy thing for the anniversary. I have no idea.",
    alm_pda9_01_03 = "O Porquinho foi avistado nessa área. Vão achá-lo!",--The Piggy Bank was spotted in this area. Go find it!",
    alm_pda9_02_01 = "O Porquinho gosta de espaços abertos, também pode ser achado vagando nas ruas, telhados e zonas de fuga.",--The wild Piggy Bank is said to prefer open spaces, and can be found grazing in streets, rooftops, and escape zones.",
    alm_pda9_02_02 = "Não consegue achar o Porquinho? Procura nos espaços abertos. Estacionamentos. Telhados. Esses lugares aí.",--Can't find the Piggy Bank? Look in wide open spaces. Parking lots. Rooftops. That kind of stuff.",
    alm_pda9_02_03 = "Eu sei que o Porquinho está aqui em algum lugar. Consigo sentir na minha barba.",--I know there's a Piggy around here somewhere. I can feel it in my beard.",
    alm_pda9_03_01 = "O primeiro Dinheiro do Porquinho acabou de surgir!",--The first Piggy Bucks dropped!",
    alm_pda9_03_02 = "Nós conseguimos a nossa primeira bolsa do Dinheiro do Porquinho!",--We got our first bag of Piggy Bucks!",
    alm_pda9_03_03 = "Oh! Esse Dinheiro do Porquinho tá bem chamativo!",--Ooh! Those Piggy Bucks are shiny!",
    alm_pda9_03_04 = "Você acha que o Dinheiro do Porquinho tem os presidentes dos porcos desenhados? Lombonaro?",--You think Piggy Bucks have little piggy presidents on them? Abra-Ham Lincoln?",
    alm_pda9_03_05 = "Aí está a primeira bolsa do Dinheiro do Porquinho! Vai lá pegá-lo!",--There's the first bag of Piggy Bucks! Go get it!",
    alm_pda9_04_01 = "São dez bolsas de Dinheiro do Porquinho!",--That's ten bags of Piggy Bucks!",
    alm_pda9_04_02 = "Peguem a décima bolsa de Dinheiro do Porquinho. Vocês merecem!",--Grab the tenth bag of Piggy Bucks. You've earned it!",
    alm_pda9_04_03 = "Dez bolsas?! Estamos nadando no Dinheiro do Porquinho!",--Ten bags?! We'll be swimming in Piggy Bucks!",
    alm_pda9_04_04 = "É a bolsa número dez!",--That's bag number ten!",
    alm_pda9_04_05 = "Isso! Temos dez bolsas do Dinheiro do Porquinho!",--Woo! We got ten bags of Piggy Bucks!",
    alm_pda9_05_01 = "O Porquinho acordou!",--The Piggy Bank has awoken!",
    alm_pda9_05_02 = "O Dinheiro do Porquinho está dentro! Peguem mais!",--First Piggy Bucks are in! Let's get some more!",
    alm_pda9_05_03 = "Quantas bolsas um Porquinho bolsaria se o Porquinho pudesse bolsar as bolsas?",--How many bags would a Piggy Bank bag if a Piggy Bank could bag bags?",
    alm_pda9_05_04 = "Primeira bolsa entrou! Já fez o mínimo!",--One bag in! You've done the bare minimum!",
    alm_pda9_05_05 = "Porquinho está vivo!",--The Piggy Bank lives!",
    alm_pda9_06_01 = "O Porquinho está no estágio 1!",--The Piggy Bank is at Stage 1!",
    alm_pda9_06_02 = "Porquinho no estágio 1! Estamos apenas começando.",--Piggy Bank at Stage 1! And we're just getting started.",
    alm_pda9_06_03 = "Oh, esse é o estágio 1 do Porquinho. Não é fofo?",--Ooh, that's a Stage 1 Piggy Bank. Isn't he cute?",
    alm_pda9_06_04 = "Porquinho no estágio 1. Vamos ir além!",--Piggy's at Stage 1. Let's go higher!",
    alm_pda9_06_05 = "Estamos no estágio 1! Continuem dando dinheiro esse Porquinho!",--We're at Stage 1! Keep paying that Piggy!",
    alm_pda9_07_01 = "O Porquinho está no estágio 2! Falou a minha língua!",--The Piggy Bank's at Stage 2! Now we're talking!",
    alm_pda9_07_02 = "Porquinho está no estágio 2! Continua assim!",--Piggy Bank at Stage 2! Keep it up!",
    alm_pda9_07_03 = "O Porquinho cresceu pro estágio 2! Será que ele pode ficar mais gordo?",--The Piggy grew to Stage 2! How big do you think it can get?",
    alm_pda9_07_04 = "Estamos no estágio 2! Não para de dar dinheiro pro Porquinho!",--We're at Stage 2! Don't stop paying the Piggy!",
    alm_pda9_07_05 = "Porquinho alcançou o estágio 2! Vai, Porquinho, vai!",--Piggy's at Stage 2! Go Piggy, go!",
    alm_pda9_08_01 = "O Porquinho chegou no estágio 3! Vocês estão arrebentando!",--The Piggy Bank hit Stage 3! You're on a roll!",
    alm_pda9_08_02 = "Conseguimos alcançar o estágio 3!",--We got a Stage 3 Piggy Bank over here!",
    alm_pda9_08_03 = "O Porquinho tá no estágio 3! Tá ficando cada vez mais fofo!",--The Piggy's at Stage 3! It just keeps getting cuter!",
    alm_pda9_08_04 = "O Porquinho está no estágio 3! Não decepcionem o Porquinho!",--Piggy Bank at Stage 3! Don't let the Piggy down!",
    alm_pda9_08_05 = "Estágio 3, assaltantes. Continuem mandando o Dinheiro do Porquinho.",--Stage 3, heisters. Keep bagging those Piggy Bucks.",
    alm_pda9_09_01 = "O Porquinho chegou no estágio 4!",--The Piggy Bank just hit Stage 4!",
    alm_pda9_09_02 = "Olha esse Porquinho no estágio 4! Olha só que bonito!",--Look at that Stage 4 Piggy! It's beautiful!",
    alm_pda9_09_03 = "Vocês conseguiram o estágio 4, assaltantes! Acham que conseguem alcançar o 5?",--You got to Stage 4, heisters! Think you can hit 5?",
    alm_pda9_10_01 = "Vocês alcançaram o estágio 5! Vocês tão fazendo isso parecer fácil!",--You got the Piggy Bank to Stage 5! You're a pig-paying machine!",
    alm_pda9_10_02 = "Não posso acreditar que alcançarão o estágio 5! Olha só o tamanho desse Porquinho!",--I can't believe you got to Stage 5! Look at the size of that Piggy!",
    alm_pda9_10_03 = "Estágio 5?! Nunca vi um Porquinho tão grande assim! E olha que já vi uns porcos grandões!",--Stage 5?! I've never seen a Piggy that big! And I've seen some big Piggies!",
    alm_pda9_11_01 = "Esse Porquinho está no máximo!",--That Piggy Bank is maxed out!",
    alm_pda9_11_02 = "Nenhum Porquinho deve ter esse todo poder!",--No one Piggy should have all that power!",
    alm_pda9_11_03 = "Esse Porquinho está pronto para explodir!",--That Piggy Bank is ready to blow!",
    alm_pda9_12_01 = "Cansou no estágio 1? Tem que começar em algum lugar, né?",--Done at Stage 1? Guess you gotta start somewhere.",
    alm_pda9_12_02 = "Ei, estágio 1 é melhor do que estágio zero!",--Hey, Stage 1's better than Stage None!",
    alm_pda9_12_03 = "Foi rápido!",--That was fast!",
    alm_pda9_13_01 = "Terminou no estágio 2. Boa noite, Porquinho.",--Gone at Stage 2. Goodnight, sweet Piggy.",
    alm_pda9_13_02 = "Estágio 2! Bom! Não tão bom quanto estágio 3, mas continua sendo bom!",--Stage 2! Good! Not as good as Stage 3, but still good!",
    alm_pda9_13_03 = "E lá se vai o Porquinho!",--And pop goes the Piggy Bank!",
    alm_pda9_14_01 = "Estágio 3! Nada mal. Eu nunca aceito menos do que o estágio 4.",--Stage 3! Not bad. I never settle for less than Stage 4, myself.",
    alm_pda9_14_02 = "Terminando no estágio 3. Digno de respeito.",--Out at Stage 3. I respect that.",
    alm_pda9_14_03 = "Isso vai ter que servir, Porquinho. Vai ter que servir.",--That'll do, Pig. That'll do.",
    alm_pda9_15_01 = "Estágio 4, bom trabalho! O Porquinho parece satisfeito.",--Stage 4, nice work! The Piggy seems pleased.",
    alm_pda9_15_02 = "Terminando no estágio 4!",--Stage 4 for the win!",
    alm_pda9_15_03 = "Vocês fizeram o Porquinho orgulhoso.",--You did the Piggy proud.",
    alm_pda9_16_01 = "Vocês conseguiram chegar no estágio 5! Estou impressionado!",--You got all the way to Stage 5! I'm impressed! ",
    alm_pda9_16_02 = "Vocês estão bem-vindos ao clube do estágio 5! O Porquinho Elite!",--You're in the Stage 5 club! The Piggy Elite!",
    alm_pda9_16_03 = "Oh, o bom banco do Porquinho, assaltante!",--Ooh, good piggy banking, heister!",
    alm_pda9_16_04 = "Graças a Deus! Aquele Porquinho já está num tamanho crítico!",--Thank god! That Piggy was at critical mass!",
    alm_pda9_16_05 = "O Porquinho vai fazer uma explosão nuclear!",--The Piggy went nuclear!",
    alm_pda9_17_01 = "Graças a Deus! Aquele Porquinho já está num tamanho crítico!",--Thank god! That Piggy was at critical mass!",
    alm_pda9_17_02 = "O Porquinho está num nível nuclear!",--The Piggy went nuclear!",
    alm_pda9_17_03 = "Porquinho no estágio 6... E eu achando que era mito!",--A Stage 6 Piggy...I thought it was just a legend!",
    alm_pda9_18_01 = "Você está ficando bom com os tiros na cabeça.",--You're a little TOO good at getting headshots.",
    alm_pda9_18_02 = "Como as cabeças deles estão fazendo esse barulho?",--How do their heads keep making that noise?",
    alm_pda9_18_03 = "Tiros na cabeça pra ontem!",--Headshots for days!",
    alm_pda9_19_01 = "Vocês são máquinas de cuspir dinheiro!",--You're a cash blasting badass!",
    alm_pda9_19_02 = "Faça chover dinheiro nesses filhas da puta!",--Make it rain on those wankers!",
    alm_pda9_19_03 = "O Lança-Grana é muito OP.",--The Money Thrower is so OP.",
    alm_pda9_20_01 = "Aw, o Dozer veio vestido pra festa! Ele tá fofo com rosa!",--Aw, the Dozer dressed up for the event! He looks so cute in pink!
    alm_pda9_20_02 = "O Warthog está aqui! Mate ele para ter mais dinheiro do porquinho!",--The Warthog's here! Take him out for some extra Piggy Bucks!
    alm_pda9_20_03 = "Eca! Eu conheço esse cheiro. É o Warthog!",--TEXTO TRADUZIDO AQUI",--Egh! I know that stink. It's the Warthog!
    alm_pda9_21_01 = "Epa, epa, epa, você está com as furadeiras mais rápidas!",--TEXTO TRADUZIDO AQUI",--Wow wow wow, you got those speedy drills now!
    alm_pda9_21_02 = "As furadeiras estão mais rápidas!",--TEXTO TRADUZIDO AQUI",--Drills gotta go fast!
    alm_pda9_21_03 = "Novo buff! Não é uma furadeira! Quero dizer, é para as furadeiras, mas... ah, foda-se também!",--New buff! This is not a drill! I mean, it's for the drill, but...Whatever! Fuck you!
    alm_pda9_22_01 = "Assim como Himura dizia, AGORA NÃO DÁ!",--Like StealthMasterFlex always says,  never skip leg day!
    alm_pda9_22_02 = "Não deixe essas bolsas sumirem!",--Don't let those bags weigh you down!
    alm_pda9_22_03 = "Agora se movem com esse dinheiro do porquinho!",--Now get a move on with those Piggy Bucks!
    alm_pda9_23_01 = "Eita! Você vai jogar essas bolsas mais longe agora!",--Wow! You're really gonna launch those Piggy Bucks now!
    alm_pda9_23_02 = "Porra! Espera até ver o quão longe você pode jogar essa bolsa!",--TEXTO TRADUZIDO AQUI",--Damn! Look how far you can throw!
    alm_pda9_23_03 = "Você é o cara mais buffado que tem!",--You're the buffest bag boy around!
    alm_pda9_24_01 = "Ooh, você tá com as balas apimentadas!",--TEXTO TRADUZIDO AQUI",--Ooo, you got the spicy bullets!
    alm_pda9_24_02 = "Que tipo de balas você conseguiu? Só há um jeito de descobrir!",--TEXTO TRADUZIDO AQUI",--What kind of bullets did you get? Only one way to find out!
    alm_pda9_24_03 = "Toda bala é especial, mas as suas são mais!",--TEXTO TRADUZIDO AQUI",--Every bullet is special, but your bullets are the special-est!
    alm_pda9_25_01 = "Acertando críticos é obrigatório!",--TEXTO TRADUZIDO AQUI",--Hitting critical hits is critical!
    alm_pda9_25_02 = "Que tipo de RPG é essa?!",--TEXTO TRADUZIDO AQUI",--What kind of RPG nat 20 shit is this?!
    alm_pda9_25_03 = "Aí 'cê está jogando com o dado viciado!",--TEXTO TRADUZIDO AQUI",--Now you're playing with loaded dice!
    alm_pda9_26_01 = "Tenha munição de graça! É por conta da casa!",--TEXTO TRADUZIDO AQUI",--Have some free ammo! It's on me!
    alm_pda9_26_02 = "Alguns tiros não vão gastar a sua minução. Não me questione como.",--TEXTO TRADUZIDO AQUI",--Some shots won't drain your ammo. Don't ask me how.
    alm_pda9_26_03 = "Você nunca pode ter muitas balas!",--TEXTO TRADUZIDO AQUI",--You can never have too many bullets!
    alm_pda9_27_01 = "Cabeças vão rolar!",--EXTO TRADUZIDO AQUI",--Heads will roll!
    alm_pda9_27_02 = "Você vai causar muitas dores de cabeça com isso!",--TEXTO TRADUZIDO AQUI",--You're gonna cause a lot of headaches with this one!
    alm_pda9_27_03 = "Se você atirar num cara na cabeça, todos os seus amiguinhos vão sentir a dor.",--TEXTO TRADUZIDO AQUI",--If you shoot a guy in the head, all his buddies will feel it.
    alm_pda9_28_01 = "Você, meu amigo, é a porra de um esponja de balas!",--TEXTO TRADUZIDO AQUI",--You, my friend, are a fucking bullet sponge!
    alm_pda9_28_02 = "Foi só um arranhão!",--TEXTO TRADUZIDO AQUI",--It's just a flesh wound!
    alm_pda9_28_03 = "Dano? Quem precisa?!",--TEXTO TRADUZIDO AQUI",--Damage? Who needs it?!
    alm_pda9_29_01 = "Você foi derrubado, mas se levantará novamente! Eles nunca vão te nocautear!",--TEXTO TRADUZIDO AQUI",--You get knocked down, but you get up again! They're never going to keep you downed!
    alm_pda9_29_02 = "Recomponha-se!",--TEXTO TRADUZIDO AQUI",--Just shake it off!
    alm_pda9_29_03 = "Vê se dá uma pausa pra descansar!",--TEXTO TRADUZIDO AQUI",--Pick yourself up for a change!
    alm_pda9_30_01 = "Não pode e não vai parar de se regenerar!",--TEXTO TRADUZIDO AQUI",--Can't stop regenerating! Won't stop regenerating!
    alm_pda9_30_02 = "A melhor ofensiva é a defensiva!",--TEXTO TRADUZIDO AQUI",--The best offense is a kickass defense!
    alm_pda9_30_03 = "Continua regenerando a armadura!",--TEXTO TRADUZIDO AQUI",--Keep the armor coming!
    alm_pda9_31_01 = "Caiu, mas passa bem!",--TEXTO TRADUZIDO AQUI",--Down but not out!
    alm_pda9_31_02 = "Podemos olhar pro lado bom dessas quedas.",--TEXTO TRADUZIDO AQUI",--We can look the other way on some of these downs.
    alm_pda9_31_03 = "O porquinho não vai te deixar desistir dessa!",--TEXTO TRADUZIDO AQUI",--The Piggy won't let you give up that easy!
    alm_pda9_32_01 = "Não desiste agora! Um golpe longo vem um pagamento gordo!",--TEXTO TRADUZIDO AQUI",--Don't bail now! A longer heist means a bigger payday!
    alm_pda9_32_02 = "Você terá mais dinheiro se ficar por mais tempo!",--TEXTO TRADUZIDO AQUI",--You'll get more loot if you stick around awhile!
    alm_pda9_32_03 = "Fique mais um pouquinho, seus lixo! Vocês terão mais bônus!",--TEXTO TRADUZIDO AQUI",--Stick around. wankers! You'll get more bonuses!
}