Hooks:Add("LocalizationManagerPostInit", "trampoalaskano", function(loc)
	LocalizationManager:add_localized_strings({
		heist_wwh = "Trato Alaskano (Alaskan Deal)",
		heist_wwh_hl = "Trato Alaskano (Alaskan Deal)",
		heist_wwh_crimenet = "Gente, eu preciso de uma mão com um trampo com as armas. Eu fiz um trato lá em Alaska, mas eu vou precisar de vocês para manter o trato seguro, beleza?",
		heist_wwh_briefing = "Locke pediu para proteger um trampo com as armas em Alaska. Diz ele que não espera problemas, mas vai que ele precisa de ajuda, caso algo dá errado. Parece que vai ser dinheiro fácil, se você concorda com o frio.",
		
		-- Introduções
		loc_wwh_intro_01 = "Bom, desculpa em fazer isso, mas é a parte onde que eu dou o fora. É nada pessoal.",
		loc_wwh_intro_02 = "Não sei como posso falar isso, mas teve uma mudança de planos. Eu vou ter que te deixa aqui.",
		loc_wwh_intro_03 = "Desculpa, eu vou ter que ir, mas deixei uma surpresa pra você.",
		
		-- Legendas (Capitão)
		cpt_wwh_01_01 = "Caralho, pensei que nunca ia sair dessa merda. Me tira daqui, fazendo favor?",
		cpt_wwh_01_02 = "Que beleza, Butcher mandou ajuda. Me ajuda aqui.",
		cpt_wwh_01_03 = "Finalmente, porra, Butcher mandou ajuda. Me tira daqui, agora!",
		cpt_wwh_02_02 = "Eu irei volta pro barco e te dizer o que deve fazer.",
		cpt_wwh_02_03 = "Vou te dizer o que deve fazer, quando eu estiver no barco.",
		cpt_wwh_03_01 = "Alô? Isso tá ligado? O navio precisa de diesel para poder ir até Águas Internacionais.", -- Tem certeza sobre isso, capitão?
		cpt_wwh_03_02 = "Tá me ouvindo? A gente vai precisa de mais diesel pro navio, pra nós irmos pra Águas Internacionais.",
		cpt_wwh_03_03 = "Ok, nós precissamos ir até Águas Internacionais, mas falta diesel.",
		cpt_wwh_04_01 = "Procura por uma mangueira e um tanque de diesel.",
		cpt_wwh_04_02 = "Mangueira e Tanque de diesel, estão em algum lugar.",
		cpt_wwh_04_03 = "Vê se consegue achar um Tanque de diesel e uma Mangueira.",
		cpt_wwh_05_01 = "Beleza, agora leva pro tanque do diesel.",
		cpt_wwh_05_02 = "Ah, ótimo. Leve a Mangueira pro tanque do navio.",
		cpt_wwh_05_03 = "A Mangueira precisa está ligado com o tanque do navio!",
		cpt_wwh_06_01 = "Agora, liga a Mangueira no navio.",
		cpt_wwh_06_02 = "A mangueira precisa está conectado no navio.",
		cpt_wwh_06_03 = "Traga a Mangueira e liga no navio.",
		cpt_wwh_07_01 = "Tá, agora bota pra encher o tanque do navio!",
		cpt_wwh_07_02 = "Bota pra encher o tanque com o diesel.",
		cpt_wwh_07_03 = "Coloca o tanque de diesel pra encher o tanque do navio.",
		cpt_wwh_08_01 = "Beleza. Tá enchendo.",
		cpt_wwh_08_02 = "Agora tá enchendo com o diesel.",
		cpt_wwh_08_03 = "Beleza! Tá enchendo o tanque.",
		cpt_wwh_09_01 = "Tem algo de errado com o tanque de diesel.",
		cpt_wwh_09_02 = "Checa o tanque de diesel. Não tá funcionando.",
		cpt_wwh_09_03 = "O tanque ficou travado. Faz o favor de checá-lo.",
		cpt_wwh_10_01 = "Tem algo de errado com a Mangueira.",
		cpt_wwh_10_02 = "A Mangueira está solta.",
		cpt_wwh_10_03 = "Vocês devem botar a mangueira de volta, ta entrando ar!",
		cpt_wwh_11_01 = "Tudo parece funcionar bem, de novo.",
		cpt_wwh_11_02 = "Beleza, tá funcionando.",
		cpt_wwh_11_03 = "O Diesel está enchendo o Tanque de novo.",
		cpt_wwh_12_01 = "O tanque tá cheio.",
		cpt_wwh_12_02 = "O Tanque tá cheio, muito bem.",
		cpt_wwh_12_03 = "Beleza, temos o suficiente.",
		cpt_wwh_13_01 = "Hora de dá o fora daqui! Tira as cordas no navio!",
		cpt_wwh_13_02 = "Será que 'cê pode tira as cordas do navio!",
		cpt_wwh_13_03 = "Tira logo essas cordas do navio!",
		cpt_wwh_14_01 = "Precisa tirar a mangueira e as cordas.",
		cpt_wwh_14_02 = "A mangueira e as cordas ainda estão ligadas!",
		cpt_wwh_14_03 = "Todas as cordas e a mangueira precisam ser tiradas.",
		cpt_wwh_15_01 = "Subam a bordo, agora!",
		cpt_wwh_15_03 = "Todo mundo, pro navio. Vamo' dá o fora daqui!",
		cpt_wwh_16_01 = "Tira a ponte e proteja o navio!",
		cpt_wwh_16_02 = "O navio tá sendo atacado. Tira logo essa ponte e proteja o navio.",
		cpt_wwh_16_03 = "As pontes precisam ser removidas e proteja o navio.",
		cpt_wwh_17_01 = "Os policiais estão no navio!",
		cpt_wwh_17_02 = "Se livra de todos os policiais!",
		cpt_wwh_17_03 = "O navio ainda tá sendo atacado pelos os policiais!",
		cpt_wwh_18_01 = "Tá na metade.",
		cpt_wwh_18_03 = "O diesel tá na metade.",
		cpt_wwh_18_02 = "50 por cento completo.",
		cpt_wwh_19_01 = "Só mais um pouquinho.",
		cpt_wwh_19_02 = "Tá quase lá.",
		cpt_wwh_19_03 = "Quase lá...",
		
		-- Legendas (Locke)
		loc_wwh_01_01 = "Desculpa, gente, eu gostaria de fazer isso de outro jeito, mas eles fizeram uma oferta que não podia dizer não.",
		loc_wwh_01_02 = "Não consegui resistir, pessoal. São só negócios, 'cêis entende isso, né?",
		loc_wwh_01_03 = "Vocês vão me odiar depois dessa, mas só quando vocês estiverem em um caixão. Nada pessoal.",
		loc_wwh_02_01 = "Até nunca mais, meus amigos.",
		loc_wwh_02_02 = "Tchau tchau, amigos, nós nunca iremos se encontra, eu acho.",
		loc_wwh_02_03 = "Tenha um dia bonito, amigos, até nunca mais!",
		
		-- Legendas (Bain)
		pln_wwh_01_01 = "Ei, que merda é essa? Locke, que porra é essa?!",
		pln_wwh_01_02 = "Locke, que porra é essa? É melhor 'cê não tenta fuder com o meu pessoal.",
		pln_wwh_01_03 = "Que merda é essa?! Locke, é melhor você não tenta fuder com a minha gente. A gente tinha um trato!",
		pln_wwh_02_01 = "É uma armadilha! O desgraçado traiu a gente. Swat tá vindo. 'Cê vai ter que achar o seu caminho.",
		pln_wwh_02_02 = "Porra, foi uma armadilha. Tem policiais vindo, se prepara.",
		pln_wwh_02_03 = "Temos problemas, gente. Locke traiu a gente. Vai ter que passar pelos os policiais, pra poder sair daí.",
		pln_wwh_03_02 = "Locke conseguiu fugir, mas nós iremos ter a nossa vingança.",
		pln_wwh_03_03 = "Locke fugiu, esse filha da puta, mas a gente vai pegar ele depois. Grave as minhas palavras.",
		pln_wwh_04_01 = "O navio que está perto das docas é da Butcher. Parece que ela foi enganada também. Bora ajuda eles, talvez eles nós dá uma carona.",
		pln_wwh_04_02 = "O navio é da Butcher! Locke traiu ela também. Ajudem eles e talvez eles vão dá uma carona para vocês.",
		pln_wwh_05_02 = "Liberta todo marítimo vocês conseguirem.",
		pln_wwh_06_01 = "Ei, alguem precisa de ajuda. Anda logo!",
		pln_wwh_06_02 = "Vai lá e ajuda eles.",
		pln_wwh_06_03 = "Eles precisam de ajuda, vai pra lá assim que puder.",
		pln_wwh_07_01 = "Tá, o bom que essa serra vai ser útil.",
		pln_wwh_07_02 = "Beleza, vocês vão precisa dessa serra.",
		pln_wwh_08_02 = "Usa a serra para abrir essa porta e ajuda o capitão ir pro navio!",
		pln_wwh_08_03 = "Vocês precisam ajuda o capitão, abre a porta com a serra!",
		pln_wwh_09_01 = "Essa serra não parece tá boa, fica de olho nela.",
		pln_wwh_09_02 = "Não fica longe dessa serra, pode ser que quebra.",
		pln_wwh_10_01 = "Porra, bota pra serra de novo.",
		pln_wwh_10_02 = "A serra ficou travada.",
		pln_wwh_10_03 = "Os policiais quebraram a serra. Conserta assim que puder!",
		pln_wwh_11_01 = "Beleza, vê se dessa vez mantenha a serra funcionando.",
		pln_wwh_11_02 = "Não deixa que os policiais quebra a serra.",
		pln_wwh_11_03 = "Serrando de boa? Ótimo.",
		pln_wwh_12_01 = "Acho que ouvi a serra terminar o serviço. Abre logo essa porta!",
		pln_wwh_12_02 = "Tá, abre essa porta!",
		pln_wwh_12_03 = "A serra terminou, entra logo!",
		pln_wwh_13_01 = "Esse navio é a sua única saída, então seja um bom garoto com o Capitão", -- comporte-se, menino! :< http://prntscr.com/lp4izd
		pln_wwh_13_02 = "Você vai ter que ajuda o Capitão, se você quer dá o fora daqui.",
		pln_wwh_13_03 = "Faça o que o Capitão pedir. Eu não vou conseguir tirar vocês daí de outro jeito, então, ele é o seu único caminho pra volta para casa.",
		
		-- Objetivos
		hud_heist_wwh_01_hl = "Lute contra os policiais",
		hud_heist_wwh_02_hl = "Salve os marítimos",
		hud_heist_wwh_03_hl = "Pegue a Serra",
		hud_heist_wwh_04_hl = "Resgate o Capitão",
		hud_heist_wwh_04b_hl = "Espere o Capitão dá as intruções",
		hud_heist_wwh_05a_hl = "Leve a mangueira pro navio",
		hud_heist_wwh_05ab_hl = "Ligue o tanque",
		hud_heist_wwh_05b_hl = "Proteja o tanque",
		hud_heist_wwh_05c_hl = "Solta as cordas",
		hud_heist_wwh_06a_hl = "Entra no navio",
		hud_heist_wwh_06b_hl = "Solta as pontes e luta contra os policiais",
		hud_heist_wwh_07_hl = "Foge!",
		})
end)