Hooks:Add("LocalizationManagerPostInit", "crossinggggggborderrr", function(loc)
	LocalizationManager:add_localized_strings({
	-- Nomes e Descrições
	heist_mex = "Border Crossing",--Border Crossing
	heist_mex_hl = "Southern Border",--Southern Border
	heist_mex_crimenet = "Bens valiosos da Murkywater estão sendo transportados para fora do continente pelo México usando um túnel secreto da Overkill MC e o cartel Coyopa. Se formos rápidos, podemos pegar tudo bem abaixo do nariz deles enquanto o Dentista está ocupado com o Bain, e desestabilizar eles.\n\n» Infiltre-se na Instalação da Overkill MC no Arizona\n» Encontre o Túnel para o Complexo Coyopa no México\n» Roube o Loot da Murkywater e Fuja",--Valuable Murkywater assets are being moved off the continent through Mexico using a hidden tunnel by the Overkill MC and Coyopa cartel. If we move quickly, we can take those resources right from under their noses while the Dentist is occupied with Bain, and deal them a crippling blow.\n\n» Infiltrate Overkill MC's facility in Arizona\n» Find the tunnel to the Coyopa compound in Mexico\n» Steal the Murkywater loot and escape
	heist_mex_briefing = "A Overkill MC tem um clube bem na borda em Miracle Valley, Arizona, com um túnel secreto que se conecta a um complexo no México pertencido aos Coyopas. A Murkywater conseguiu um avião que vai transportar os bens, mas não sei para onde. Vocês vão roubar aquele avião. Precisarão entrar no complexo da Overkill MC e encontrar o túnel para o México, e então encontrem os bens antes de saírem com o avião. Se conseguirem fazer isso quietos, seria uma humilhação e tanto para os caras da Murkywater, mas pode ir em frente se quiser sair atirando em todo mundo.",--Overkill has a club house right by the border in Miracle Valley, Arizona, with a hidden underground tunnel leading into a compound in Mexico owned by the Coyopas. The Murky's have arranged an airplane that will transport their goods, but I don't know to where. You're going to steal that plane. You gotta get into the Overkill facility and find the tunnel to Mexico, then find the goods before you get out with the plane. If you can do it quietly, it would be a nice humiliation for the Murky's, but go ahead and shoot up the place if you want to.
	
	-- Nomes e Descrições (Border Crystals)
	heist_mex_cooking = "Border Crystals",--Border Crystals
	heist_mex_cooking_hl = "Coyopa Compound",--Coyopa Compound
	heist_mex_cooking_crimenet = "Amigos, arranjei um jeitinho de nós fazermos mais uma boa grana. Vocês vão cozinhar um pouquinho de coisas não saudáveis. Aqueles idiotas do Cartel Coyopa possuem um bom laboratório de metanfetamina montado em seu complexo, bem ao sul da borda, para nós pegarmos 'emprestado' rapidinho.\n\n» Entre no Complexo\n» Encontre o Laboratório\n» Encontre os Ingredientes\n» Cozinhe Metanfetamina\n» Fuja",--Friends, I've arranged a little way to make us another big pile of nice cash. You're going to do a little cooking, of the less-than-healthy kind. Those dwankies in the Coyopa Cartel have a nice meth lab set up in their compound, just south of the border, for us to "borrow" for a bit.\n\n» Enter the compound\n» Find the meth lab\n» Find the ingredients\n» Cook meth\n» Escape
	heist_mex_cooking_briefing = "Já sabem o esquema amigos.. Apenas cozinhem o máximo que conseguirem e isso vai ser muito bom para as nossas economias. Vou ajudá-los o máximo que eu conseguir. Os Coyopas não vão ficar felizes em ver vocês, e eles têm ajuda dos meus antigos colegas da Murkywater, então vão ficar de mãos ocupadas, mas vai valer a pena, yeah?",--You know the routine friends. Just keep cooking as long as you can and this will be a nice boost to our finances. I will assist you as much as I can. The Coyopas will not be happy to see you, and they've got help from my former colleagues at Murkywater, so you will have your hands full, but it will be worth it, yeah?
	
	-- Legendas (Border Crossing)
	loc_mex_intro_01 = "Sinto que vamos ganhar um belo de um retorno com esse aqui, amigos.",--Feels like we're going to get a kakspul of payback with this one, friends.
	loc_mex_intro_02 = "Depois disso, que tal irmos naquele lugar que o Sangres sempre fala para comer uns tacos de peixe e ver um show. Twister sei lá o que era o nome.",--After this, how about we go to that place Sangres is always talking about for some fish tacos and a show. Twister-something-something it was called...
	loc_mex_intro_03 = "Não parem por muito tempo, amigos. Aqui é o país dos morcegos!",--Don't stop too long, friends. This is bat country!
	loc_mex_intro_04 = "Se vocês acharem um estojo de guitarram cheio de armas... só deixem ai, yeah?",--If you chops find a guitar case full of guns... just let it be, yeah?  
	heist_mex_transition = "EM ALGUM LUGAR NO MÉXICO...",--SOMEWHERE IN MEXICO...
	loc_mex_01_01 = "Ok, gente. Hora de encontrar a entrada do túnel.",--OK, you chops. Time to find that tunnel entrance. 
	loc_mex_01_02 = "Agora procurem aquele túnel. A entrada deve ser bem acessível.",--Now, get to finding that tunnel. The entrance should be fairly accessible. 
	loc_mex_01_03 = "Encontrem o túnel, amigos. Eles provavelmente esconderam, mas não deve ser tão difícil de achar.",--Find that tunnel, friends. They've probably got it hidden, but it shouldn't be too hard to locate.
	loc_mex_02_01 = "A entrada do túnel deve estar em algum lugar aí fora.",--The tunnel entrance should be outside somewhere.
	loc_mex_02_02 = "Eles provavelmente possuem um acesso fácil pro túnel, então olhem em volta por fora.",--They would probably want easy access to the tunnel, so check around outside.
	loc_mex_02_03 = "Provavelmente vocês vão achar o túnel se olharem em volta na parte de fora.",--You'll probably find the tunnel if you look around outside.
	loc_mex_03_01 = "Ai está, é isso.",--There you go, that's it.
	loc_mex_03_02 = "Muito bom, amigos. É isso que estávamos procurando.",--Nicely done, friends. That's what we're looking for.
	loc_mex_03_03 = "Essa é a entrada de um túnel, se eu não me engano.",--That's a tunnel entrance if ever I've seen one.
	loc_mex_04_01 = "Ah, merda. É claro que tinha que ter uma senha. Talvez consigam encontrar um jeito de descobrir o código na Sala de Reunião do clube. Vão dar uma olhada, yeah?",--Ah, blerrie. Of course it had to have a keylock. Maybe you can find some way to figure out the code in the clubhouse briefing room. Go have a look, yeah?
	loc_mex_04_03 = "É típico. Deviam dar uma olhada no clube caso esses idiotas deixaram um jeito de achar o código em algum lugar. Comecem pela Sala de Reunião.",--That's typical. You should have a look in the clubhouse in case these dwankies have left a way to access the code somewhere. Start with the briefing room.
	loc_mex_06_03 = "Deve ser um bom lugar pra procurar.",--Might be a good place to look.
	loc_mex_07_01 = "Prestem atenção para qualquer coisa estranha.",--Watch for anything odd.
	loc_mex_07_02 = "Andem com cuidado, amigos.",--Tread carefully, friends.
	loc_mex_07_03 = "Fiquem em alerta.",--Stay alert. 
	loc_mex_08_01 = "Agora entrem lá e vejam o que conseguem encontrar.",--Now, get in there and see what you can find.
	loc_mex_08_02 = "Entrem e vejam se tem uma pista do código em algum lugar.",--Go inside and see if there's a clue to the code anywhere.
	loc_mex_08_03 = "Procurem um jeito de achar o código.",--Look for a way to get the code.
	loc_mex_09_01 = "Caralho, o lugar está armado! Saiam daí se não conseguirem desarmar!",--Bliksem, the place is rigged! Get out of there if you can't disarm it!
	loc_mex_09_02 = "Eita, tá armado com C4! Cuidado, amigos!",--Ach, it's rigged with C4! Look out, friends!
	loc_mex_09_03 = "Cuidado, a sala está armada! Desarmem ou saiam daí!",--Look out, the room is booby-trapped! Disarm or get out!
	loc_mex_10_01 = "Oh, vocês vão causar um ataque cardíaco no Velho Locke. Essa foi por pouco.",--Oh, you're going to give old Locke a heart attack. That was a close one.
	loc_mex_10_02 = "Trabalho rápido, amigos.",--Fast work, friends. 
	loc_mex_10_03 = "Muito bom. Deixem para aqueles idiotas da Overkill MC por exagerarem na segurança.",--Nicely done. Leave it to those Overkill dwankies to go over the top with security.
	loc_mex_11_01 = "Quando acharem o código, voltem no teclado e tentem abrir.",--When you find the code, get back to the keypad and give it a go.
	loc_mex_11_02 = "Ok, comecem a procurar a resposta daquele código.",--Ok, get to searching for the answer to that code. 
	loc_mex_11_03 = "Vão procurar aquele código, yeah?",--Get to searching for the code, yeah?
	loc_mex_12_01 = "Encontrem o código. Olharam a sala inteira?",--Find the code. Did you check the whole room?
	loc_mex_12_02 = "Procuraram tudo?",--Did you search everywhere?
	loc_mex_12_03 = "Olhem as mesas, paredes, cadeiras... qualquer coisa.",--Check the tables, walls, chairs... wherever.
	loc_mex_13_02 = "Bom trabalho com o código.",--Groot job with the code.
	loc_mex_13_03 = "Era isso. Boooa.",--That was it. Niiice.
	loc_mex_14_01 = "O que é isso? Uma planta?",--What's that? A blueprint?
	loc_mex_14_02 = "Parece que tem um cofre subterrâneo em algum lugar.",--Looks like there might be an underground vault somewhere.
	loc_mex_14_03 = "Plantas... pra um cofre?",--Blueprints... to a vault?
	loc_mex_15_01 = "As câmeras estão desativadas agora.",--Cameras are now disabled.
	loc_mex_15_02 = "Vocês deram um jeito nas câmeras, amigos.",--You took care of the cameras, friends.
	loc_mex_15_03 = "Boa jogada, desligando as câmeras.",--Nice going, taking out the cameras.
	loc_mex_16_01 = "Ok, entrem naquele túnel. Hora de visitar o México.",--OK, get into that tunnel. Time for a visit to Mexico.
	loc_mex_16_02 = "Agora coloquem seus sombreros e entrem no túnel.",--Now put your sombreros on and get into that tunnel.
	loc_mex_16_03 = "Hora de ir para o México, yeah?",--Time to go to Mexico, yeah?
	loc_mex_17_01 = "Precisam entrar naquele túnel, amigos.",--You gotta get into that tunnel, friends. 
	loc_mex_17_02 = "Andem logo gente, entrem naquele túnel.",--Hurry up you chops, get into that tunnel.
	loc_mex_17_03 = "Precisam ir para o México. Acelerem.",--You gotta get to Mexico. Hurry.
	loc_mex_18_01 = "Uma bela noite para um roubo no deserto. Tentem ficar quietos.",--Nice night for a jol in the desert. Try to stay quiet.
	loc_mex_18_02 = "Bem-vindos ao México amigos. Tentem não causar um tumulto.",--Welcome to Mexico amigos. Try not to make a ruckus.
	loc_mex_18_03 = "Que túnel longo do caralho. Fiquem quietos e comecem a trabalhar, amigos.",--That was a long bekakin' tunnel. Stay quiet and get to it, friends.
	loc_mex_19_01 = "Primeira coisa a se fazer é achar aquele avião.",--First thing to do is find that plane.
	loc_mex_19_02 = "Sua prioridade é achar sua carona pra fora daí. Talvez nos hangares, yeah?",--Your first priority is finding your ride out of there. Maybe check the hangars, yeah?
	loc_mex_19_03 = "O avião de fuga provavelmente ainda está em um dos hangares.",--The getaway plane is probably still in one of the hangars.
	loc_mex_20_01 = "Precisam encontrar aquele avião.",--You gotta find that plane. 
	loc_mex_20_02 = "Não percam tempo. Encontrem o avião, rápido.",--No standing around. Find the plane, quickly.
	loc_mex_20_03 = "O avião, amigos, o avião!",--The plane, friends, the plane!
	loc_mex_21_01 = "Aí está a carona de vocês. Assim que assegurarem todo o loot, vão precisar reabastecer ele.",--There's your ride. Once you've got all the loot secured, you gotta get it refueled. 
	loc_mex_21_02 = "Esse é o avião. Levem o loot pra dentro, e depois coloquem o combustível.",--That's the plane. Get the loot inside, then give it some fuel.
	loc_mex_21_03 = "Ok, é isso. Quando colocarem o loot a bordo, vão precisar colocar combustível nele.",--OK, that's it. When you've got the loot aboard, you need to juice it up as well.
	loc_mex_22_01 = "Hora de procurar o loot da Murkywater. É armas que estamos atrás.",--Time to start looking for that stash of Murkywater contraband. It's weapons we're after. 
	loc_mex_22_02 = "Os recursos da Murkywater que queremos são armas. Podem estar em qualquer lugar, então comecem a procurar.",--The Murky resources we're after will be weapons. They could be anywhere so you'll just have to start looking.
	loc_mex_23_01 = "Hora de procurar o loot da Murkywater. Estamos atrás de drogas.",--Time to start looking for that stash of Murky loot. It's drugs we're after. 
	loc_mex_23_02 = "Os recursos da Murkywater que precisamos encontrar são drogas. Podem estar em qualquer lugar por aí.",--The Murky resources we've gotta find will be in the form of drugs. They could be anywhere around here.
	loc_mex_23_03 = "Comecem a procurar a mina de ouro da Murkywater, em formato de muita cocaína.",--Start searching for that Murkywater nest egg, shaped like a lot of cocaine.
	loc_mex_24_03 = "A mina de ouro da Murkywater é dinheiro puro. então comecem a procurar. Pode estar em qualquer lugar por aí.",--The Murky's nest egg is cash money, so start looking. It could be anywhere around there.
	loc_mex_25_01 = "Ótimo, é tudo o que precisamos. A Murkywater e o Dentista vão ter um problemão quando a notícia chegar.",--Groot, that's all we need. Murkywater and the Dentist will be in big trouble once this hits home.
	loc_mex_25_03 = "Não é um bom dia para a Murkywater ou pro Dentista, yeah?",--This is not a good day for Murkywater or the Dentist, yeah?
	loc_mex_26_01a = "Isso me lembra de uma operação que fiz há muitos anos atrás, quando eu ainda era um recruta, sabotando computadores ABC 80.",--This reminds me of an op I did many years ago, when I was still a laatie, jippoing ABC 80 computers.
	loc_mex_26_01b = "Estávamos nesse complexo inimigo em Cambodia e meu ajudante virou comida de tigre. Saudades dele. Do meu ajudante, não do tigre.",--We were in this enemy compound in Cambodia and my handler got eaten by a tiger. Dwankie kak he was. My handler, not the tiger.
	loc_mex_26_02 = "Vocês pensariam que os federais teriam achado esse lugar e limpado tudo.",--You would think the feds would've found this place and cleared it out.
	loc_mex_26_03 = "Sempre me pergunto quem que banca o Dentista nisso tudo. Ele está no topo da cadeia alimentar, ou tem mais caroço nesse angu?",--Gotta wonder who has the resources to back the Dentist in all this. Is he the top of the food chain, or is there more to this braai?
	loc_mex_27_02 = "Porra, é o cofre das plantas.",--Blerrie, that's the vault from the blueprints. 
	loc_mex_27_03 = "Ainda bem que vocês encontraram aquela planta. Esse é o cofre.",--Good thing you found that blueprint. That's the vault.
	loc_mex_28_01 = "Vão precisar de dois Cartões de Acesso para entrar aí.",--You're going to need two key cards to get in there. 
	loc_mex_29_01 = "Deve ter algo especial nesse negócio se eles deixaram trancado aqui. Talvez levem com vocês, yeah?",--There's gotta be something special about that thing if they keep it locked up in here. Maybe take it with you, yeah?
	loc_mex_30_01 = "Hora de abastecer o avião. Conectem a mangueira do combustível.",--Time to juice up that plane. Get the fuel hose connected.
	loc_mex_30_02 = "Vocês precisam colocar combustível naquela coisa. Vamos lá.",--You gotta get some fuel in that dinges. Get to work.
	loc_mex_30_03 = "Ok, amigos. Hora de abastecer aquele avião.",--OK, friends. Time to put some fuel in that plane.
	loc_mex_31_01 = "Não tem como sair daí com o tanque vazio. Abasteçam o avião!",--Can't get out of there on an empty tank. Fuel the plane!
	loc_mex_31_02 = "O avião precisa de combustível para poder voar.",--The plane needs juice to fly.
	loc_mex_31_03 = "Como tá indo o reabastecimento?",--How's the refueling going?
	loc_mex_32_01 = "Ótimo, agora é só esperar encher.",--Right, now just let it fill up.
	loc_mex_32_02 = "Só precisa de um tempo pra encher.",--Just gotta give it some time to fill.
	loc_mex_32_03 = "Parece estar funcionando. Vai levar um tempo até encher.",--Looks like it's working. Will take some time before it's full.
	loc_mex_33_02 = "A bomba precisa de mais gasolina.",--The pump needs to be filled with gasoline.
	loc_mex_33_03 = "Precisam levar mais gasolina naquela bomba de merda.",--You gotta get some more gas in that donnerse pump.
	loc_mex_34_01 = "Porra, a bomba de novo. Esse caralho precisa de mais gasolina.",--Ach, the pump again. Donnerse thing needs more gas.
	loc_mex_34_02 = "A bomba parou de novo.",--The pump stopped again.
	loc_mex_34_03 = "Olhem a bomba novamente, amigos.",--See to the pump again, friends.
	loc_mex_35_01 = "Provavelmente vocês vão achar combustível em um dos depósitos.",--You can probably find fuel in one of the warehouses. 
	loc_mex_35_02 = "Procurem gasolina em volta dos depósitos.",--Look around the warehouses for a can of fuel.
	loc_mex_35_03 = "Deve ter gasolina por aí em algum lugar.",--There's gotta be juice around there somewhere.
	loc_mex_36_01 = "Isso vai bastar por enquanto.",--That'll keep it going for now.
	loc_mex_36_02 = "Ok, é o bastante por enquanto.",--Ok, that's enough for now.
	loc_mex_36_03 = "Deve funcionar por mais um tempinho agora.",--Should stay running for a bit, now.
	loc_mex_37_01 = "O tanque tá cheio, já podem tirar a mangueira.",--Refueling is done, so take that hose off. 
	loc_mex_37_02 = "O avião tá cheio, podem tirar a mangueira.",--The plane is full, you can take off the hose.
	loc_mex_37_03 = "Hora de tirar a mangueira, o tanque já está cheio.",--Time to disconnect the hose, the plane is all full.
	loc_mex_38_01 = "Agora vocês devem abrir o portão da pista. Os idiotas da Murkywater e do Cartel vão ficar putos quando perceberem o que estamos fazendo!",--Now you gotta clear the runway by opening the gates. The Murkys and Cartel dwankies will go bossies, when they realise what we're doing!
	loc_mex_38_02 = "Precisam abrir o portão da pista. Vai ser legal, e os Murkywater vão ficar loucos quando decolarmos!",--You need to open the runway gates. It's gonna be jol, and the Murkys will go crazy when we take off!
	loc_mex_39_01 = "Precisam limpar a pista, amigos!",--You have to clear the runway, friends!
	loc_mex_39_02 = "Abram o portão para que tenham um caminho limpo para decolar.",--Open the gate so you have a clear path to take off.
	loc_mex_39_03 = "Quase hora de ir. Só precisam abrir o portão da pista.",--Almost time to leave. You just need to open up the runway.
	loc_mex_40_02 = "Rápido, amigos! Entrem no avião.",--Hurry, friends! Get into that plane.
	loc_mex_40_03 = "Hora de voar, amigos.",--Time to fly, friends.
	loc_mex_41_02 = "Mais inimigos chegando. Vocês precisam cair fora daí!",--More dwankies coming soon. You gotta get out of there!
	loc_mex_42_01 = "Caralho! Vocês estão bem?",--Blerrie! You guys OK?
	loc_mex_43_01 = "O complexo inteiro ouviu essa explosão.",--The entire compound heard that blast.
	loc_mex_44_01 = "Ah cara, era o código errado!",--Ag man, that was the wrong code!
	loc_mex_44_03 = "O código tava errado, eles já sabem que vocês estão aí!",--The code was wrong, they know you're there now!
	loc_mex_47_01 = "Não precisam mais se esconder. Locke tem um Plano B!",--No need to sneak about now. Locke has a plan B!
	loc_mex_47_02 = "Vão em frente. Façam um pouco de barulho, amigos.",--Go ahead. Make some noise, friends.
	loc_mex_47_03 = "Vamos continuar com o outro plano. Não precisam mais ficar quietos!",--Let's go with the other plan. No need to keep quiet!
	loc_mex_49_03 = "Provavelmente irão achar o túnel se olharem em volta lá fora.",--You'll probably find the tunnel if you look around outside.
	loc_mex_50_01 = "Ai está, é isso.",--There you go, that's it.
	loc_mex_50_02 = "Muito bom, amigos. É o que estamos procurando.",--Nicely done, friends. That's what we're looking for.
	loc_mex_50_03 = "Ah, é essa a entrada para o túnel se eu já tenha visto uma.",--Ah, that's a tunnel entrance if I've ever seen one.
	loc_mex_51_01 = "O teclado foi desativado! Vamos ter que estourar a porta e abrir caminho.",--The keypad has been disabled! You're going to have to blow your way in.
	loc_mex_51_02 = "Merda, o teclado não funciona. É preciso estourar a porta.",--Ach, the keypad doesn't work. You gotta blow the door.
	loc_mex_51_03 = "Vocês não podem usar o teclado. Hora de explodir a porta!",--You can't use the keypad. Time to blow the door open!
	loc_mex_52_01 = "Felizmente, estamos prontos para isso. Rust me disse que esses imbecis da Overkill MC deixam muitos explosivos por perto, então só precisamos achar eles.",--Luckily, we were ready for this. Rust told me these Overkill dwankies keep loads of explosives around, so all you gotta do is find some.
	loc_mex_52_02 = "De acordo com o Rust, esses motoqueiros idiotas deixam um monte de cargas explosivas por perto.",--According to Rust, these biker keks keep lots of breaching charges around.
	loc_mex_52_03 = "Vocês vão provavelmente encontrar alguns explosivos por aí para usar.",--You'll probably find explosives around there to use.
	loc_mex_53_01 = "Não sei aonde podem estar, vocês vão ter que procurar por aí pelo lugar.",--No telling where they might be though, you'll have to look around.
	loc_mex_53_02 = "Procurem em todo lugar.",--Make sure you look around everywhere.
	loc_mex_53_03 = "Talvez estejam na parte de fora.",--Might be a good idea to look outside.
	loc_mex_54_02 = "Parece ser isso. Peguem elas e coloquem na porta.",--That looks right. Grab them and put them on the door.
	loc_mex_54_03 = "Ótimo, plantem elas na porta!",--Good, now get them onto the door!
	loc_mex_55_01 = "Coloquem o detonador.",--Set up the detonator.
	loc_mex_55_02 = "Agora coloquem o detonador, amigos.",--Now hook up the detonator, friends.
	loc_mex_55_03 = "O detonador precisará ser equipado.",--The detonator needs to be rigged.
	loc_mex_56_01 = "O que estão esperando? Coloquem o detonador!",--What are you waiting for? Set that detonator!
	loc_mex_56_02 = "Vocês tem que explodir a porta.",--You gotta blow that door. 
	loc_mex_56_03 = "Rápido, amigos. O detonador!",--Hurry, friends. The detonator!
	loc_mex_57_02 = "Precisam proteger isso um pouco. Não deve demorar muito.",--You gotta protect it for a bit. Shouldn't take too long.
	loc_mex_57_03 = "Mantenham isso limpo até terminar.",--Keep it clear until it's done.
	loc_mex_58_02 = "Pararam o detonador!",--The detonator has been stopped!
	loc_mex_58_03 = "Vocês vão precisar reiniciar o detonador.",--You need to restart the detonator.
	loc_mex_59_01 = "Esperem por isso...",--Wait for it... 
	loc_mex_59_02 = "Lá vamos nós... lá... vamos... nóóóóós!",--Here we go... here... we... goooooo!
	loc_mex_59_03 = "Tapem as orelhas, seus malucos! Isso vai ser alto pra caralho!",--Hold your ears, you chops! It's going to be loud!
	loc_mex_63_01 = "Grande noite para esses babacas. É uma pena que esses idiotas do Cartel saibam que estamos acabando com tudo!",--Nice night for a barbacao. Shame the Cartel dwankies know we're crashing it!
	loc_mex_63_02 = "Bem-vindos ao México, meus queridos amigos. Não há tempo a perder!",--Welcome to Mexico, dear amigos. No time to waste!
	loc_mex_63_03 = "Achei que esse túnel não ia acabar nunca! Sem tempo a perder, amigos. Todos sabem que vocês estão aí.",--Thought that tunnel would never end! No time to waste, friends. Everyone knows you're there.
	loc_mex_64_02 = "A Prioridade é achar a carona de vocês para fora daí. Talvez nos hangares, yeah?",--Your first priority is finding your ride out of there. Maybe check the hangars, yeah?
	loc_mex_64_03 = "O Avião de fuga está provavelmente em um dos hangares. Deem uma olhada!",--The getaway plane is probably in one of the hangars. Go have a look!
	loc_mex_66_01 = "Aí está a carona de vocês. Depois de assegurar todo o loot, vocês vão precisar reabastecê-los.",--There's your ride out. Once you've got all the loot secured, you gotta get it refueled.
	loc_mex_66_02 = "Esse é o avião que estamos procurando. Coloque o loot dentro, e depois um pouco de combustível.",--That's the plane we're looking for. Get the loot inside, then give it some fuel.
	loc_mex_67_03 = "Comecem a procurar a mina de ouro da Murkywater. Ela está na forma de Armas.",--Start searching for the Murkywater nest egg we're after. It's in the form of weapons.
	loc_mex_68_02 = "Os bens da Murkywater que queremos são drogas. Podem estar em qualquer lugar por aí, então comecem a procurar.",--The Murky resources we're after will be in the form of drugs. They could be anywhere around there, so you're just going to have to start looking.
	loc_mex_68_03 = "Comecem a procurar a mina de ouro da Murkywater. Ela está na forma de Cocaína.",--Start searching for the Murkywater nest egg we're after. It's in the form of cocaine.
	loc_mex_69_01 = "Hora de procurar o loot da Murkywater. Estamos procurando por dinheiro, muito dinheiro.",--Time to start looking for that stash of Murky loot. We're looking for cash, and lots of it.
	loc_mex_69_03 = "A mina de ouro dos caras da Murkywater são dinheiro vivo, então comecem a procurar. Podem estar em qualquer lugar por aí.",--The Murky's nest egg is cash money, so start looking. It could be anywhere around there.
	loc_mex_70_01 = "Deve ser o suficiente pra chutarmos os dentes dos Murkies.",--That should be enough to kick the Murkys in the teeth.
	loc_mex_70_03 = "Não é um belo dia para a Murkywater ou pro Dentista, yeah?! Com certeza!",--This is not a good day for Murkywater or the Dentist, yeah?! For sure!
	loc_mex_70a_02 = "Coloquem essas coisas a bordo do avião.",--Those things need to be put onboard the plane.
	loc_mex_73_01 = "Deve ter algo especial nesse negócio se eles deixam trancado aqui. Talvez levem com vocês, yeah?",--There's gotta be something special about that thing if they keep it locked up in here. Maybe take it with you, yeah?
	loc_mex_74_01 = "É hora de reabastecer esse avião. Conectem a mangueira de combustível.",--Time to juice up that plane. Get the fuel hose connected.
	loc_mex_74_02 = "Precisam colocar combustível nesse negócio. Vamos lá.",--You gotta get some fuel in that dinges. Get to work. 
	loc_mex_74_03 = "Ok, amigos. Hora de abastecer o avião.",--OK, friends. Time to put some fuel in that plane.
	loc_mex_75_01 = "Porra! Alguém parou a bomba. Liguem de novo!",--Ach! Someone stopped the pump. Get it going again!
	loc_mex_75_02 = "Deixaram alguém parar a bomba. Vão lá e liguem ela!",--You let someone stop the pump. Get over there and start it up!
	loc_mex_75_03 = "Precisam religar a bomba!",--You need to restart the pump!
	loc_mex_77_01 = "Ótimo, agora mantenham eles longe da bomba!",--Good, now keep those dwankies away from the pump!
	loc_mex_77_02 = "Protejam a bomba enquanto ela funciona!",--Make sure you protect the pump while it's running!
	loc_mex_77_03 = "Precisam manter a bomba ligada. Protejam ela!",--You gotta keep the pump running. Protect it!
	loc_mex_78_01 = "Bom, agora só esperem encher.",--Right, now just let it fill up.
	loc_mex_78_02 = "Apenas esperem um pouco para que fique totalmente cheio.",--Just gotta give it some time to fill.
	loc_mex_79_01 = "O tanque encheu, agora tirem essa mangueira.",--Refueling is done, so take that hose off. 
	loc_mex_79_02 = "O avião tá cheio, tirem a mangueira.",--The plane is full, you can take off the hose.
	loc_mex_79_03 = "Hora de tirar a mangueira, o tanque do avião já está cheio.",--Time to disconnect the hose, the plane is all full.
	loc_mex_80_01 = "Agora precisam abrir a pista explodindo os portões!",--Now you gotta clear the runway by blowing the gates!
	loc_mex_80_02 = "Precisam explodir os portões da pista. Isso vai ser bem foda!",--You need to blow the runway gates. It's gonna be jol!
	loc_mex_80_03 = "Hora de explodir os portões pra decolar!",--Time to blow the gates so you can take off!
	loc_mex_82_01 = "Caralho, que barulhão! Hora de ir!",--Blerrie, what a noise! Time to leave!
	loc_mex_82_02 = "Rápido, amigos! Para o avião.",--Hurry, friends! Get to the plane.
	loc_mex_82_03 = "Hora de voar, amigos. Subam a bordo daquela coisa, rápido!",--Time to fly, friends. Get onboard that dinges, quickly!
	loc_mex_83_02 = "Hora de ir, amigos. Rápido!",--Gotta go, friends. Hurry!
	loc_mex_83_04 = "Corram seus fudidos!",--Fly you fools!
	
	-- Legendas (Border Crystals)
	loc_mex_cook_intro_02 = "Merda, eu devia ter prestado mais atenção nas aulas de química, yeah? Tudo bem, amigos... vamos dar um jeito.",--Ach, I should have paid more attention in chemistry class, yeah? No worries, friends... we'll figure it out as we go.
	loc_mex_cook_intro_03 = "Ok, amigos. Vamos lá que o Velho Locke vai ajudar vocês, com certeza!",--OK, friends. You just get to it and old Locke will have you cooking in no time, for sure!
	loc_mex_cook_01_01 = "Ok, amigos. Vamos começar a cozinhar. O Velho Locke não é o melhor cozinheiro do mundo, então não provem os ingredientes, yeah?",--OK, friends. Let's get some cooking started. Old Locke isn't the best cook in the world, so maybe, don't sample the goods, yeah?
	loc_mex_cook_01_02 = "Estão prontos para o churrasco? Eu fazia uma linguiça das boas quando morava em Cape Town, mas isso aí é meio diferente!",--You chops ready for a cookout? Used to throw a good braai in my Cape Town days, but this is a bit different!
	loc_mex_cook_01_03 = "Hora de um churrasquinho do bom, vamos lá!",--Time for a nice, old fashioned cookout, for sure!
	loc_mex_cook_02_02 = "Pera aí...",--Hold on...
	loc_mex_cook_02_03 = "Ok, o que vem agora...",--Okay, what's next...
	loc_mex_cook_02_04 = "Então o próximo é...",--So, next step is...
	loc_mex_cook_02_05 = "Agora precisam de...",--Now you're going to need...
	loc_mex_cook_02_06 = "Certo, o próximo ingrediente é...",--Alright, the next ingredient is...
	loc_mex_cook_02_07 = "Ok, agora é...",--Okay, now comes...
	loc_mex_cook_02_08 = "Agora deve ser...",--Now you should go with...
	loc_mex_cook_02_09 = "Caralho, se eu li isso direito... eh...",--Blerrie, if I read this correctly... eh...
	loc_mex_cook_02_10 = "Espero que o Velho Locke acerte isso...",--Hope old Locke gets this right...
	loc_mex_cook_03_01 = "Ácido Muriático.",--Muriatic acid.
	loc_mex_cook_03_02 = "Talvez... Ácido Muriático?",--Perhaps... muriatic acid?
	loc_mex_cook_03_03 = "...Ácido Muriático?",--...muriatic acid?
	loc_mex_cook_03_04 = "É Ácido Muriático.",--It's muriatic acid.
	loc_mex_cook_03_05 = "Eu acho que é Ácido Muriático.",--I'm going to assume muriatic acid.
	loc_mex_cook_03_06 = "Vamos de Ácido Muriático.",--We'll go with muriatic acid.
	loc_mex_cook_03_07 = "Ácido. Ácido Muriático.",--Acid. Muriatic acid.
	loc_mex_cook_04_01 = "Soda Cáustica. É, é isso.",--Caustic soda. Yes, that's it.
	loc_mex_cook_04_02 = "...Soda Cáustica?",--...caustic soda?
	loc_mex_cook_04_03 = "...Soda Cáustica, amigos?",--...caustic soda, friends?
	loc_mex_cook_04_04 = "...Soda Cáustica?",--...caustic soda?
	loc_mex_cook_04_05 = "É Soda Cáustica, yeah?",--It's caustic soda, yeah?
	loc_mex_cook_04_06 = "Aposto que é Soda Cáustica.",--I'm betting on caustic soda.
	loc_mex_cook_04_07 = "Provavelmente Soda Cáustica.",--Probably caustic soda.
	loc_mex_cook_04_08 = "Vamos usar Soda Cáustica. O que pode dar errado?",--Let's go with caustic soda. What could go wrong?
	loc_mex_cook_04_09 = "Soda. Soda Cáustica.",--Soda. Caustic soda.
	loc_mex_cook_04_10 = "Soda. Soda Cáustica. Não acho que vocês deveriam beber isso.",--Soda. Caustic soda. I don't think you're supposed to drink it.
	loc_mex_cook_04_11 = "Soda. Soda Cáustica. Eu não misturaria isso com gim e tônico.",--Soda. Caustic soda.I wouldn't mix a gin and tonic with it, though.
	loc_mex_cook_05_01 = "Cloreto... de Hidrogênio. Eca, nojento!",--Hydrogen... chloride. Ach, nasty!
	loc_mex_cook_05_02 = "...Cloreto de Hidrogênio?",--...hydrogen chloride?
	loc_mex_cook_05_03 = "...Cloreto de Hidrogênio?",--...hydrogen chloride?
	loc_mex_cook_05_04 = "É Cloreto de Hidrogênio.",--It's hydrogen chloride.
	loc_mex_cook_05_05 = "Vamos tentar um pouco de Cloreto de Hidrogênio.",--Let's try a katspoegie of hydrogen chloride.
	loc_mex_cook_05_06 = "Que tal Cloreto de Hidrogênio.",--How about hydrogen chloride.
	loc_mex_cook_05_07 = "Cloreto. Cloreto de Hidrogênio.",--Chloride. Hydrogen chloride.
	loc_mex_cook_07_01 = "Não, espera aí...",--Wait, cancel that...
	loc_mex_cook_07_02 = "Segura aí!",--Hold up!
	loc_mex_cook_07_03 = "Não, espera!",--No, wait!
	loc_mex_cook_07_04 = "Porra, não é isso!",--Ach no, that's not it!
	loc_mex_cook_07_05 = "Esperem um segundo...",--Wait a second...
	loc_mex_cook_07_06 = "Esperem a porra de um segundo!",--Wait a blerrie minute!
	loc_mex_cook_07_07 = "Desculpe amigos, não estava certo.",--Sorry friends, that wasn't right.
	loc_mex_cook_07_08 = "Espera!",--Wait!
	loc_mex_cook_07_09 = "Para! Não colocaram ainda, né?",--Stop! You didn't put it in yet, did you?
	loc_mex_cook_07_10 = "Merda!",--Blerrie!
	loc_mex_cook_08_01 = "Era pra ser Ácido Muriático!",--It's supposed to be muriatic acid!
	loc_mex_cook_08_02 = "Um pouco de Ácido Muriático!",--A katspoegie of muriatic acid!
	loc_mex_cook_08_03 = "Era pra ser Ácido Muriático!",--That should have been muriatic acid!
	loc_mex_cook_08_04 = "Precisamos de Ácido Muriático!",--We need muriatic acid!
	loc_mex_cook_08_05 = "Sim... é Ácido, Ácido Muriático..",--Yes... it's acid, muriatic acid.
	loc_mex_cook_08_06 = "É Ácido Muriático.",--It's muriatic acid.
	loc_mex_cook_08_07 = "Era pra ser Ácido Muriático.",--It should be acid.
	loc_mex_cook_08_08 = "Tem que ser Ácido Muriático.",--It has got to be muriatic acid.
	loc_mex_cook_09_01 = "Era pra ser Soda Cáustica, amigos!",--It's supposed to be caustic soda, friends!
	loc_mex_cook_09_02 = "Era pra ter sido Soda Cáustica!",--It should be caustic soda!
	loc_mex_cook_09_03 = "Deveríamos ter usado Soda Cáustica!",--We should have used caustic soda!
	loc_mex_cook_09_04 = "Precisam de Soda Cáustica, yeah?",--You need caustic soda, yeah?
	loc_mex_cook_09_05 = "É Soda, Soda Cáustica.",--It's soda, caustic soda.
	loc_mex_cook_09_06 = "É Soda Cáustica.",--It's caustic soda.
	loc_mex_cook_09_07 = "Era pra ser Soda Cáustica.",--Should have been soda.
	loc_mex_cook_10_01 = "Era pra ser Cloreto de Hidrogênio!",--It's supposed to be hydrogen chloride!
	loc_mex_cook_10_02 = "Isso deve ser Cloreto de Hidrogênio!",--It should be hydrogen chloride!
	loc_mex_cook_10_03 = "Coloquem Cloreto de Hidrogênio!",--Use hydrogen chloride!
	loc_mex_cook_10_04 = "Precisamos de Cloreto de Hidrogênio!",--We need hydrogen chloride!
	loc_mex_cook_10_05 = "Não, é Cloreto, Cloreto de Hidrogênio.",--No, it's chloride, hydrogen chloride.
	loc_mex_cook_10_06 = "Era pra ser Cloreto de Hidrogênio em vez disso.",--It should be hydrogen chloride instead.
	loc_mex_cook_10_07 = "Cloreto de Hidrogênio é o que precisam! ",--Hydrogen chloride is what you want!
	loc_mex_cook_10_08 = "Cloreto de Hidrogênio deve estar certo.",--Hydrogen chloride has to be right.
	loc_mex_cook_11_01 = "...Eu acho.",--...I reckon.
	loc_mex_cook_11_02 = "...Eu... acho.",--...I... think.
	loc_mex_cook_11_03 = "...SE os cálculos do Velho Locke estiverem certos.",--...IF old Locke's calculations are correct.
	loc_mex_cook_11_04 = "...Eu acho, pelo menos.",--...I think so, at least.
	loc_mex_cook_11_05 = "...A não ser que eu tenha visto errado...",--...unless I've missed something...
	loc_mex_cook_11_06 = "...Tenho certeza. Provavelmente.",--...I'm blerrie sure. Probably.
	loc_mex_cook_11_07 = "...com certeza. É, bem provável.",--...for sure. Or, most likely.
	loc_mex_cook_11_08 = "...acho que é isso.",--...that's my best guess.
	loc_mex_cook_11_09 = "...é o meu melhor palpite.",--...that's my very best guess.
	loc_mex_cook_11_10 = "...tem que ser.",--...it has gotta be.
	loc_mex_cook_11_11 = "...essa não é minha área de especialização.",--...this is not my area of expertise.
	loc_mex_cook_11_12 = "...não é isso que o Velho Locke faz de melhor, realmente.",--...this isn't what old Locke does best, really.
	loc_mex_cook_11_13 = "...espero que esse site esteja certo.",--...hope this website is accurate.
	loc_mex_cook_11_14 = "...o que de pior pode acontecer, né?",--...what's the worst that could happen, eh?
	loc_mex_cook_11_15 = "...esses tutoriais da internet nunca são claros.",--...bekaken internet descriptions are not too clear.
	loc_mex_cook_11_16 = "...Ok... Ok.",--...OK... OK.
	loc_mex_cook_11_17 = "...e cruzem os dedos.",--...and cross your fingers.
	loc_mex_cook_11_18 = "...e esperem que dê certo.",--...and hope it works.
	loc_mex_cook_11_19 = "...é um palpite, na verdade.",--...it's a toss-up, really.
	loc_mex_cook_11_20 = "...Tenho 93% de certeza.",--...I'm 93% sure.
	loc_mex_cook_11_21 = "...Tenho 91% de certeza.",--...I'm 91% sure.
	loc_mex_cook_11_22 = "...Tenho 86% de certeza.",--...I'm 86% sure.
	loc_mex_cook_11_23 = "...Tenho 84% de certeza.",--...I'm 84% sure.
	loc_mex_cook_11_24 = "...Tenho 79% de certeza.",--...I'm 79% sure.
	loc_mex_cook_11_25 = "...Tenho 72% de certeza.",--...I'm 72% sure.
	loc_mex_cook_11_26 = "...Tenho 68% de certeza.",--...I'm 68% sure.
	loc_mex_cook_11_27 = "...Tenho 65.5% de certeza.",--...I'm 65.5% sure.
	loc_mex_cook_11_28 = "...Tenho 57% de certeza.",--...I'm 57% sure.
	loc_mex_cook_12_04 = "Porra! não, não estava certo...",--Ach! No, that wasn't right...
	loc_mex_cook_12_10 = "Devem sempre confiar no Locke, menos nessas horas.",--You should always trust Locke, except when you shouldn't.
	loc_mex_cook_12_11 = "Não... tava errado, não tava?",--No... that wasn't right, was it?
	loc_mex_cook_12_19 = "Tenho o presentimento de que era o ingrediente errado...",--I had a feeling that was the wrong ingredient...
	loc_mex_cook_13_01 = "Um lote ficou pronto.",--Thats one batch done.
	loc_mex_cook_13_02 = "O lote está pronto, amigos.",--The batch is done, friends.
	loc_mex_cook_13_03 = "A primeira está pronta!",--First serving is ready!
	loc_mex_cook_14_01 = "Escondam a metanfetamina aí por perto e vamos cozinhar mais um lote.",--Hide the meth nearby and then let's cook another round.
	loc_mex_cook_14_03 = "Levem para um lugar seguro pra nós podermos começar mais uma.",--Get that to a safe place and we can start up another braai.
	loc_mex_cook_14_04 = "Assim que esconderam essa, podemos fazer mais.",--Once you get that stowed, you can get another one going.
	loc_mex_cook_14_05 = "Esse lote precisa ir pra um local seguro, rápido. Daí podem fazer mais um.",--That batch needs to go somewhere safe, chop chop. Then you can have another go.
	loc_mex_cook_14_06 = "Levem essa daí pra um local seguro, e depois voltem a cozinhar, amigos.",--Move that out of the way to a good place, then get back to it, friends.
	loc_mex_cook_15_01 = "Procurem nos caminhões por ingredientes para usarmos.",--Check the trucks for ingredients we can use.
	loc_mex_cook_15_02 = "Deem uma olhada nos caminhões por ingredientes.",--Have a look in the trucks for materials.
	loc_mex_cook_15_03 = "Deve ter mais produtos químicos nos caminhões.",--There might be more chemicals in the trucks.
	loc_mex_cook_16_02 = "Boa, amigos. Pegamos o que precisavámos. Façam mais se quiserem ou fujam!",--Groot, friends. We got what we need. Make more if you want or leave!
	loc_mex_cook_17_02 = "Ótimo amigos. mais cristal pra nós!",--Nice friends. More crystal gold!
	loc_mex_cook_17_03 = "E foi mais uma.",--That's another one.
	loc_mex_cook_17_04 = "Mais corrupção pros babacas!",--More corruption for the dwankies!
	loc_mex_cook_17_05 = "E mais uma...",--And another...
	loc_mex_cook_18_01 = "Deve ter mais ingredientes em algum lugar.",--There should be some more ingredients locked up somewhere.
	loc_mex_cook_18_03 = "Olhem mais por aí, não percam nenhum ingrediente.",--Have a proper look around, don't miss out on any ingredients.
	loc_mex_cook_19_01 = "Ok, vamos ver...",--OK, let's have a look...
	loc_mex_cook_22_01 = "Vamos ver no que dá!",--Now let's see what happens!
	loc_mex_cook_22_02 = "Se fizeram certo, vai cozinhar agora!",--If you did it right, it will now cook!
	loc_mex_cook_22_03 = "Deu certo, vai começar agora!",--There you go, it will start now!
	loc_mex_cook_22_04 = "Ótimo, agora só esperem cozinhar!",--Good, now watch it cook!
	
	-- Objetivos
	hud_heist_mex1 = "Encontre o túnel subterrâneo para o México em algum lugar na parte de fora.",--Find an underground tunnel leading to Mexico somewhere outside.
	hud_heist_mex1_hl = "Localize o túnel",--Locate the tunnel
	hud_heist_mex10 = "Encontre um tanque de combústivel de avião e uma bomba. Conecte ambos ao avião.",--Find a tank of airplane fuel and a pump. Connect them both to the plane.
	hud_heist_mex10_hl = "Conecte a Mangueira de Combustível no Avião",--Connect the fuel hose to the plane
	hud_heist_mex11 = "Fuja roubando o avião.",--Escape by stealing the plane.
	hud_heist_mex11_hl = "Fuga Disponível",--Escape available
	hud_heist_mex12 = "Encontre e roube cocaína do complexo.",--Find and steal cocaine from around the compound.
	hud_heist_mex12_hl = "Roube Cocaína",--Steal cocaine
	hud_heist_mex13 = "Encontre e roube dinheiro do complexo.",--Find and steal money from around the compound.
	hud_heist_mex13_hl = "Roube Dinheiro",--Steal money
	hud_heist_mex14 = "Encontre o avião em um dos hangares.",--Find the plane in one of the hangers.
	hud_heist_mex14_hl = "Localize o Avião de Fuga",--Locate the getaway plane
	hud_heist_mex15 = "Encontre latas de gasolina vermelhas e reabasteça o gerador da bomba.",--Find red gasoline cans and refuel the pump's generator.
	hud_heist_mex15_hl = "Reabasteça o Gerador",--Refuel the generator
	hud_heist_mex16 = "Localize as chaves do avião em algum lugar do complexo.",--Locate the plane keys somewhere in the compound.
	hud_heist_mex16_hl = "Encontre as Chaves do Avião",--Find the keys to the plane
	hud_heist_mex17 = "Espere a bomba reabastecer o avião.",--Wait for the pump to refuel the plane.
	hud_heist_mex17_hl = "Espere o Reabastecimento Acabar",--Wait for the refueling process
	hud_heist_mex18 = "Mantenha os soldados da Murkywater longe de desconectarem a mangueira do tanque ou da bomba.",--Keep the Murkywater soldiers from detaching the hose from the tank or the pump.
	hud_heist_mex18_hl = "Defenda a Mangueira",--Defend the hose
	hud_heist_mex19 = "Encontre o interruptor e abra os portões da pista.",--Find the switch to open the gates to the runway.
	hud_heist_mex19_hl = "Abra os Portões da Pista",--Open the runway gates
	hud_heist_mex2 = "Procure no clube dos motoqueiros pela Sala de Reunião e tenha acesso a ela.",--Search the bikers clubhouse for the briefing room and gain access to it.
	hud_heist_mex2_hl = "Localize e Entre na Sala de Reunião",--Locate and enter the briefing room
	hud_heist_mex20 = "Tire a mangueira do avião.",--Detach the hose from the plane.
	hud_heist_mex20_hl = "Tire a Mangueira",--Detach the hose
	hud_heist_mex21 = "Use C4 para explodir os portões da pista.",--Use C4 to blow open the runway gates.
	hud_heist_mex21_hl = "Exploda os Portões da Pista",--Blow up the runway gates
	hud_heist_mex3 = "Use a pista para encontrar o código certo e insira-o no teclado.",--Use the hint to locate the correct code and enter it into the keypad.
	hud_heist_mex3_hl = "Encontre e Insira o Código",--Find and enter the code
	hud_heist_mex4 = "Encontre aonde os motoqueiros guardam as cargas explosivas.",--Find where the bikers are storing breaching charges.
	hud_heist_mex4_hl = "Encontre as Cargas Explosivas",--Find the breaching charges
	hud_heist_mex5 = "Posicione as cargas explosivas na entrada do túnel.",--Place the breaching charges on the tunnel entrance.
	hud_heist_mex5_hl = "Posicione as Cargas Explosivas",--Set up the breaching charges
	hud_heist_mex6 = "Inicie a contagem para detonar as cargas explosivas.",--Start the countdown to detonate the breaching charges.
	hud_heist_mex6_hl = "Coloque o Detonador",--Rig the detonator
	hud_heist_mex7 = "Não deixe os soldados da Murkywater desativarem o detonador.",--Keep the Murkywater soldiers from disabling the detonator.
	hud_heist_mex7_hl = "Defenda o Detonador",--Defend the detonator
	hud_heist_mex8 = "Use o túnel para chegar ao outro lado da borda.",--Use the tunnel to reach the other side of the border.
	hud_heist_mex8_hl = "Pegue o Túnel para o México",--Take the tunnel to Mexico
	hud_heist_mex9 = "Encontre e roube armas pelo complexo.",--Find and steal weapons from around the compound.
	hud_heist_mex9_hl = "Roube Armas",--Steal weapons
		})
end)