Hooks:Add("LocalizationManagerPostInit", "henrysrockehfoda", function(loc)
	LocalizationManager:add_localized_strings({
		-- Nome e Descrição
		heist_des = "Henry's Rock",
		heist_des_hl = "Henry's Rock",
		heist_des_crimenet = "O lugar mais secreto da Murkywater, Henry's Rock. Possuem diversos projetos abomináveis. Eles estão fazendo uma pesquisa e experimentos nos dois báus dourados, os mesmos que a gente pegou no Golden Grin Casino, e também no FBI. Nós vamos tirá-los das mãos deles. \n\n» Entre no Henry's Rock \n» Procure pelos Báus Dourados \n» Elimine qualquer Defesa para fazer a sua Fuga",
		heist_des_briefing = "Meus amigos, isso vai ser meio complicado. Os Kataru intensificaram suas buscas ao Bain. Vamos tirar alguns brinquedinhos deles, yeah? O lugar que nós vamos invadir é o mais precioso da Murkywater e eles estão trabalhando em alguns projetos estranhos. Eles só me deixaram chegar perto do lugar uma única vez, não vi muito do que tem lá, então a gente não pode saber o que esperar. Eu recebi algumas informações de antigos contatos meus da Murky, e consegui um jeito de entrarmos lá, porém, vamos entrar às cegas. Uma vez feito, não terá mais volta. Nós estaremos declarando guerra contra a Murkywater! Mas devemos isso ao Bain. Vai ter um baita exército nos esperando, então, vejam se não ficam com medo quando ver eles, yeah?",
		
		-- Introdução
		loc_des_intro_01c = "Certo. Eu vou pegar a primeira, e você fica com a glória.",
		loc_des_intro_02c = "Acho que isso vai ser uma bela mudança no andamento do D.C. e as políticas, né?",
		loc_des_intro_01d = "Talvez a gente vai acabar descobrindo o que realmente aconteceu com Jimmy Hoffa.",
		loc_des_intro_04c = "A gente, provavelmente, vai ver os Aliens.",
		loc_des_intro_05a = "Podem me lembrar o que os Murkies trabalhavam aqui?",
		loc_des_intro_04a = "Certo, pessoal, se preparem. E não se esqueçam, eles vão estar com policiais ultramente treinados.. por tanto não enrolem.",
		loc_des_intro_04d = "Sabe, eles talvez...",
		loc_des_intro_02a = "Mas que tipo de merda a gente vai achar nesse lugar?",
		loc_des_intro_01e = "Depois de tudo isso, eu prefiro voltar pra Vegas.",
		loc_des_intro_05f = "Você, talvez, não queira responder essa.",
		loc_des_intro_01b = "Fortuna e glória, garoto.",
		loc_des_intro_04b = "Se eles tiverem uma daquelas armas de raio, eu vou querer uma.",
		loc_des_intro_03a = "Que tipo de merda a gente vai achar?",
		loc_des_intro_03d = "Ei, acabei de pensar nisso. A gente deveria ter trazido roupas de proteção?",
		loc_des_intro_05e = "Me pergunto se eles manteram o avião da Amelia Earhart por aqui.",
		loc_des_intro_05c = "Sempre me perguntei como os policiais deles se parecem.",
		loc_des_intro_02d = "Sério mesmo, se eles tiverem as armas de raio, eu vou pegar mesmo.",
		loc_des_intro_05d = "Todas as coisas consideradas, eu prefiro voltar pra Vegas.",
		loc_des_intro_01a = "Podem me lembrar a razão pela qual a gente tá fazendo isso?",
		loc_des_intro_05b = "Eles tem homens ultramente treinados.",
		loc_des_intro_03c = "Um pouquinho de drama aí, Lockezinho.",
		loc_des_intro_04e = "Se alguém descubrir o que realmente aconteceu com o Elvis, me contem!",
		loc_des_intro_02b = "Toda criança de 1980 tem esse sonho. Incluindo os pesadelos, né?",
		loc_des_intro_03b = "Apenas os segredos do universo e os significados pro fim da humanidade.",
		
		-- Legendas
		loc_des_60_05 = "Peguem a caixa e saiam daí.",
		loc_des_85_03 = "O desligamento foi cancelado. Vocês precisam ir lá e reiniciar o desligamento, amigos!",
		loc_des_13_06 = "Tem milhões de caixas aí dentro. Sim, milhões. Vocês só precisam achar a certa. Usem o terminal no laboratório de TI.",
		loc_des_102_05 = "Continuem preparando os produtos químicos certos.",
		loc_des_106_03 = "Bom, isso ainda não explodiu, então vocês podem preparar o último ingrediente.",
		loc_des_89_02 = "Quando vocês quiserem que o Bile venha, basta prepararem o sinalizador!",
		loc_des_67_02 = "Essa arma precisa carregar antes de atirar. Procurem por um painel de controle aí.",
		loc_des_70_03 = "O canhão está pronto. Atirem!",
		loc_des_44_04 = "Não tenham medo de pegá-la...",
		loc_des_62_02 = "Se apressem e cheguem ao laboratório de armas.",
		loc_des_35_03 = "Então, eles estão estudando uma das caixas no laboratório de arqueologia. Vão até lá e deem uma olhada. E cuidado com as múmias soltas.",
		loc_des_96_04 = "Vocês precisam trocar essas baterias.",
		loc_des_79_02 = "Vão em frente e peguem a caixa, amigos. Mantenham a polícia longe dela, yeah?",
		loc_des_53_01 = "Ok, isso parece... certo? Pelo menos não explodiu tudo. Hora de misturar os próximos ingredientes.",
		loc_des_63_01 = "Ok, nós precisamos passar por aquela porta. Talvez possamos usar essa merda enorme no meio da sala pra explodir. Vejam se podem apontar, yeah?",
		loc_des_15_01 = "Algo está errado com o computador. Não está conectando. Essa merda de MurkyDOS. Tentem outro.",
		loc_des_19_02 = "O terminal, pessoal. Liguem a energia de volta e reiniciem o override.",
		loc_des_102_02 = "Vocês precisam completar a fórmula, preparem o próximo ingrediente.",
		loc_des_68_07 = "Ativem o ciclo de carregamento, yeah?",
		loc_des_19_04 = "Liguem a energia, e reiniciem esse override.",--Turn the power on, then restart the terminal override.
		loc_des_97_01 = "Agora, liguem a arma de novo.",--Now, power up the weapon again.
		loc_des_89_04 = "Vocês vão precisar acender um sinalizador para o Bile se movimentar até aí.",--You've got to light a flare for Bile to land.
		loc_des_98_03 = "O canhão ainda não está carregado.",--The cannon still isn't charged.
		loc_des_03_01 = "Eu temia que isso acontecesse. Não entramos da forma que deveria ser. O lugar está sendo trancado.",--Was afraid of that. We didn't get in clean. The place is going into lockdown.
		loc_des_52_04 = "Vocês devem estar procurando por receitas, amigos!",--You should be looking for recipes friends!
		loc_des_81_03 = "Fantástico, amigos. Agora vocês precisam voltar para entrada para que eu possa tirar vocês daí.",--Fantastic, friends. Now you need to get back to the entrance so that I can pull you out of there.
		loc_des_18_03 = "Eles cortaram a energia de vocês, amigos. Encontrem a caixa de energia e coloquem-na para funcionar novamente!",--They've cut the power on you, friends. Find the circuit box and get it running again!
		loc_des_34_04 = "A segunda caixa, amigos. Encontrem ela na estrutura principal.",--The second box, friends. Find it in the mainframe.
		loc_des_71_03 = "Algo interrompeu o círculo de carga. Vocês precisam reiniciar isso.",--Something interrupted the charge cycle. You have to restart it.
		loc_des_12_03 = "Vão até o laboratório de tecnologia, hackeiem dentro da estação de trabalho e vejam se conseguem descobrir em qual prateleira está a nossa caixa.",--...Get to the tech lab, hack into a workstation and see if you can find which shelf the box is in.
		loc_des_90_03 = "Vocês precisam carregar ambas as caixas para dentro do helicóptero antes de zarpar daqui, yeah?",--You need to load both boxes onto the heli before boarding, yeah?
		loc_des_24_03 = "Sem energia no guindaste ainda?",--Still no power to the crane?
		loc_des_40_02 = "Oh, poderemos tirar essa coisa e vender.. mas precisamos encontrar uma forma de abrir isso. Esses símbolos são a chave. Procurem por pistas, yeah?",--Oh, if we could take that thing out and sell it... but we just got to open it. Those symbols are the key. Look around for some clues, yeah?
		loc_des_11_03 = "Um dos itens na qual estamos aqui para pegá-lo está sendo mantido lá nos arquivos do armazém. Vocês podem usar o guindaste lá na entrada principal para pegá-lo. Basta apenas encontrar a prateleira certa.",--One of the items we are here for is being kept in the warehouse archive. You can use the crane in the central hub to get it, once you find the right shelf.
		loc_des_22_02 = "Os policiais desligaram o guindaste, vocês vão precisar ligar ele mais uma vez!",
		loc_des_26_04 = "Tem que ter algo por ai que vocês possam usar para abrir a caixa.",
		loc_des_22_01 = "Eles pararam o guindaste, façam ele funcionar de novo.",
		loc_des_87_01 = "Quem é esse merdinha feio?... Mas que merda... é essa...!? Ach! Sem tempo para lidar com isso agora! Vazem daí! Rápido!",
		loc_des_41_05 = "Vocês já conseguiram abrir a arca?",
		loc_des_31_01 = "Parece que essa caixa é pesada né? Tem uma esteira na sala principal para a doca de carregamento, por dentro da montanha. Joguem a caixa lá e deixem a esteira carregar para vocês.",
		loc_des_98_01 = "Carreguem a arma, amigos.",
		loc_des_72_05 = "O canhão ainda não está carregando. Iniciem isso!",
		loc_des_13_05 = "Cheguem ao laboratório de computadores, e encontrem a estante certa, daí usem o guindaste.",
		loc_des_69_01 = "O canhão está pronto, apertem aquele botão brilhante e vamos ver o que isso pode fazer!",
		loc_des_64_06 = "Vamos galera, virem aquela porra.",
		loc_des_102_01 = "Vocês precisam preparar o próximo ingrediente.",
		loc_des_60_01 = "Rápido, peguem a caixa, amigos!",
		loc_des_62_03 = "Já acharam o laboratório de armas?",
		loc_des_91_02 = "Carreguem os artefatos, meus amigos.",
		loc_des_30_05 = "Peguem a caixa e vão, amigos.",
		loc_des_38_02 = "Preparem uma furadeira aí, yeah?",
		loc_des_72_01 = "Reiniciem o ciclo de carregamento.",
		loc_des_33_01 = "Vocês vão precisa voltar e chegar no painel onde está o segundo artefato. Façam isso rápido, yeah?",
		loc_des_62_05 = "Cheguem ao laboratório de armas.",
		loc_des_08_02 = "Todos os projetos que rolam aqui são temporários, então um monte de coisa mudou.",
		loc_des_58_03 = "Não esperem muito, amigos. Apenas coloquem a mistura na porta, yeah?",
		loc_des_18_01 = "A droga dos policiais cortaram a energia dos terminais. Encontrem a caixa de energia e liguem de volta.",
		loc_des_54_03 = "Ainda parece estável, amigos. Hora de adicionar o último ingrediente.",
		loc_des_15_02 = "O terminal não está conectando. A Murky sempre teve pessoas na área de TI que eram uns lixos, com uma exceção para mim, claro. Encontrem outro terminal.",
		loc_des_79_03 = "Peguem o baú, meus amigos, e não deixem ninguém com essas patas gordurosas tocarem nele, yeah?",
		loc_des_39_04 = "Reiniciem essa furadeira, yeah?",
		loc_des_93_02 = "Não deixem o helicóptero esperando, yeah?",
		loc_des_66_01 = "Achem essas baterias, amigos.",
		loc_des_84_02 = "Merda! Essa armas irão fuder o Bile se ele tentar pousar agora. Vocês precisam hackea-las pelas caixas de controle.",
		loc_des_39_01 = "Os policiais pararam a furadeira. Vocês precisam reiniciá-la.",
		loc_des_94_02 = "Tem mais uma fechadura na porta, vocês precisarão mirar e atirar de novo.",
		loc_des_96_02 = "Encontraram alguma fonte de energia?",
		loc_des_71_01 = "A merda do policiais pararam o carregamento. Quero que vocês vão lá religá-lo.",
		loc_des_60_02 = "O artefato, amigos. Peguem ele e vazem!",
		loc_des_04_01 = "...Vocês precisam achar as caixas de segurança que controlam as portas e hackea-las.",
		loc_des_92_01 = "Ok, amigos. Entrem no helicóptero!",
		loc_des_96_03 = "Vocês precisam de novas células de energia.",
		loc_des_01_01 = "Silêncio agora, amigos.",
		loc_des_41_02 = "Já consegueriam algo nos símbolos?",
		loc_des_02_03 = "Ach! Se a polícia está aqui também, Garret deve estar ajudando cada vez mais a Murky para virem até aqui. Ou ele está muito puto conosco.",
		loc_des_74_07 = "A alavanca. Encontrem ela e puxem.",
		loc_des_07_04 = "Rápido amigos, entrem lá e procurem.",
		loc_des_98_07 = "Ativem o ciclo de carregamento da arma.",
		loc_des_103_03 = "Vocês precisam abrir essa porra de arca.",
		loc_des_99_01 = "A arma está pronta, atirem e derretam aquela porta.",
		loc_des_05_02 = "Vocês precisam reniciar o override daquele caixa.",
		loc_des_97_03 = "Vocês precisam recarregar a arma para atirar mais uma vez.",
		loc_des_57_02 = "Agora, vão e coloquem esse treco para fazer o seu trabalho na porta.",
		loc_des_106_01 = "Hora de preparar o próximo componente.",
		loc_des_11_02 = "Hmm. Parece que uma das caixas que viemos buscar está nos arquivos. Sem chance de chegarmos lá andando, mas vocês podem usar um guindaste na sala central, porém antes vocês precisam achar a estante certa.",
		loc_des_13_07 = "É como uma agulha no palheiro, mas vocês precisam achar essa caixa! Vão lá para o laboratório de TI.",
		loc_des_24_04 = "Vocês precisam reconectar a energia para o guindaste!",
		loc_des_88_01 = "Bile saberá quando vocês estiverem prontos quando ver o sinalizador, yeah!",
		loc_des_28_04 = "Talvez se eu mandar uma chave de fenda pelo correio?",
		loc_des_14_03 = "Hackeiem um desses terminais, yeah?",
		loc_des_29_01 = "Ah, aqui vamos nós. Uma caixa da estranheza. Peguem e vão para o próximo.",
		loc_des_91_06 = "Joguem essas merdas misteriosas pra dentro do helicóptero!",
		loc_des_86_03 = "Reniciem a sequência de desligamentos.",
		loc_des_82_03 = "...E peguem os baús no final da esteira, na entrada. Elas devem estar aguardando por vocês, yeah?",
		loc_des_107_02 = "Agora misturem tudo isso junto. Estável... cuidado agora...",
		loc_des_102_04 = "Vocês precisam preparar a próxima parte da fórmula.",--You need to prepare the next part of the formula.
		loc_des_28_01 = "Os parafusos, amigos. Os parafusos.",--The screws, friends. The screws.
		loc_des_87_03 = "Ah, caralho! não há mais tempo para continuarem aí.. Caiam fora daí, amigos!",--Ah, blerrie! No time to stay around... just get out of there, friends!
		loc_des_40_03 = "Como brilha.. Vale uma fortuna, e só precisamos abri-la. Vejam se vocês conseguem encontrar alguma pista sobre esses símbolos estranhos aí.",--That's a lot of shiny. Worth a fortune, but we just have to get it open. See if you can find any clues to those symbols around there.
		loc_des_91_05 = "Joguem essas caixas pra dentro do helicóptero antes de entrarmos.",--Throw those cases into the helicopter before getting in.
		loc_des_31_03 = "Uma boa ideia jogar essas merdas na esteira para levá-las até a entrada. Deixemos as máquinas carregarem elas pra gente, yeah?",--Probably a good idea to throw that dinges on the conveyor belt in the main hub- let the machines carry it back to the entrance for you, yeah?
		loc_des_70_04 = "Apertem o botão. Vocês não podem perder isso.",
		loc_des_34_03 = "Vocês estão procurando pela segunda caixa?",
		loc_des_80_02 = "Voltem ao computador principal e encontrem a segunda caixa, yeah?",
		loc_des_70_01 = "Pressionem o botão, yeah?",
		loc_des_33_03 = "Vocês precisam procurar no computador principal para conseguir encontrar a segunda caixa. Rápido, agora!",
		loc_des_100_02 = "Prontos para vazarem dessa merda? Voltem para a entrada e eu vou arranjar a extração de vocês.",
		loc_des_66_03 = "Ainda precisam de mais células de energia.",
		loc_des_36_04 = "Vamos galerinha, vão para a ala de arqueologia.",
		loc_des_93_01 = "Vamos, meus amigos. O Bile não tem muito combustível restando.",
		loc_des_56_03 = "Amigos, eles pararam de cozinhar, yeah? Vocês precisam refazê-lo!",
		loc_des_22_03 = "O guindaste parou. Vocês precisam reniciá-lo!",
		loc_des_103_02 = "Os símbolos.. Tem uma ordem correta pra eles.",
		loc_des_64_01 = "Mirem a arma, amigos.",
		loc_des_83_03 = "Não esqueçam das caixas na esteira.",
		loc_des_81_02 = "Ambos os baús foram encontrados, yeah? Ótimo! Hora de cair fora daí. Voltem para a entrada e eu vou arrumar a extração pra vocês.",
		loc_des_61_01 = "Cheguem ao laboratório de armas. Ele se conecta a um depósito em que está sendo mantida uma das caixas.",
		loc_des_10_03 = "Cada segundo que se passa acaba contando, amigos.",
		loc_des_52_03 = "Vocês precisam passar por aquela porta, amigos.",
		loc_des_72_03 = "Reativem o painel de carregamento.",
		loc_des_59_01 = "Bom, agora peguem a caixa e saiam daí antes que qualquer merda que estiver no tanque acorde.",
		loc_des_29_03 = "Bom trabalho, amigos. Uma caixa secreta a menos para a Murky. Peguem ela e vão para a próxima, yeah?",
		loc_des_82_01 = "...E não se esqueçam de tirar as caixas da esteira!",
		loc_des_12_01 = "...Encontrem o laboratório de computadores, hackeiem um terminal e procurem pela localização da caixa.",
		loc_des_65_01 = "Bom, agora para poder ligá-lo.. Essa coisa funciona com baterias, então deem uma olhada por aí e vejam se vocês conseguem encontrar elas.",
		loc_des_47_02 = "Voltem até o computador principal e procurem pelo segundo artefato.",
		loc_des_03_03 = "Desculpe, amigos. Parece que não conseguimos entrar de uma forma mais tranquila. Todo o lugar está em alerta e bem trancado.",
		loc_des_01_02 = "Cuidado amigos... Acabem com eles, yeah?",
		loc_des_09_01 = "Encontrem um terminal para hackear, vejam se vocês conseguem descobrir pra onde iremos ir, yeah?",--...Find a terminal in the mainframe to hack into, see if you can figure out where to go next, yeah?
		loc_des_28_02 = "Parafusos.... parafusos... vamos lá, agora.",--Screws.... screws... come on, now.
		loc_des_41_06 = "O Lord Locke lhes deu um mandamento.. encontrem a combinação certa, yeah?",--Thy Lord Locke giveth one commandment... find the right combination, yeah?
		loc_des_17_01 = "Os policiais chegaram até o terminal. Vocês precisam reiniciar o hack.",--Kerels got to the terminal. You've got to restart the hack.
		loc_des_48_04 = "A estrutura principal... vocês precisam voltar lá, amigos.",--The mainframe... you should get back to it, friends.
		loc_des_93_04 = "Vocês precisam entrar no helicóptero!",--You need to get onboard the helicopter!
		loc_des_49_02 = "Muito estranho. Uma das caixas está dentro do laboratório biológico? É pra lá que vocês vão, amigos.",--Very strange, this. One of the boxes is in the bio-lab? That's where you go next then, friends.
		loc_des_70_07 = "Vamos lá amigos. Vai ser super divertido. Explodam essa porta.",--C'mon friends. It'll be fun. Blast that door.
		loc_des_51_02 = "O artefato provavelmente está atrás da porta, mas não trouxemos nada que seja grande o suficiente. Talvez se vocês misturarem alguns produtos químicos.. Olhem por aí e verifiquem se vocês encontram alguma fórmula para a mistura. O que poderia acontecer?",--The artifact is probably behind the door, but we didn't bring anything big enough to get through. Maybe if you mix some chemicals together... see if you can find any good formulas there. What could happen?
		loc_des_98_02 = "Vocês precisam ligar esse canhão.",--You need to power up the cannon.
		loc_des_28_03 = "Os parafusos não se desenroscam sozinhos.",--Screws don't usually unscrew themselves. You gotta help.
		loc_des_68_01 = "Carreguem essa arma, amigos.",--Get that weapon charged, friends.
		loc_des_26_01 = "Abram a caixa, amigos.",--Get the crate open, friends.
		loc_des_68_05 = "Corram amigos, carreguem essas merdas.",--Hurry friends, get that dinges charged.
		loc_des_70_05 = "O que estão esperando, atirem com o canhão!",--What are you waiting for, fire the cannon!
		loc_des_83_04 = "Vocês precisam ainda retirar as caixas da esteira.",--You still have to take the boxes from the conveyor.
		loc_des_105_03 = "O bypass precisa ser reiniciado.",--The bypass needs to be restarted.
		loc_des_03_02 = "Ah, merda. O lugar foi todo trancado.",--Ah, kak. The place has gone into lockdown.
		loc_des_59_03 = "Isso, em cima da mesa. Peguem, saiam daí e mantenham isso longe desses federais de merda, yeah?",--That's it, on the table. Pick it up, get out of there and keep it away from the kerels, yeah?
		loc_des_72_02 = "Vocês devem reiniciar a carga.",--You have to restart the charge.
		loc_des_89_05 = "O Bile está esperando o sinalizador, amigos.",--Bile is waiting for the signal, friends.
		loc_des_16_02 = "Vocês já começaram a procurar no terminal?",--Have you started looking in the terminal yet?
		loc_des_52_05 = "Estou certo de que tem algo apropriado por aqui.",--I'm pretty sure there's something suitable around there.
		loc_des_85_01 = "Os policiais resetaram a caixa de controle. Vocês precisam reiniciar o desligamento.",--Kerels have reset the control box. You need to restart the shutdown.
		loc_des_43_02 = "É isso, yeah? Peguem e continuem andando.",--That's it, yeah? Pick it up and keep moving.
		loc_des_19_01 = "Não esqueçam os terminais, amigos!",--Don't forget the terminals, friends!
		loc_des_72_04 = "Carreguem esse canhão novamente.",--Get that cannon charging again.
		loc_des_104_04 = "Vocês precisam ativar o guindaste.",--You need to activate the crane.
		loc_des_104_02 = "Usem o guindaste para pegar a caixa, amigos.",--Use the crane to get the crate, friends.
		loc_des_90_02 = "Certifiquem-se de que esses artefatos estarão a bordo do helicóptero, meus amigos.",--Make sure the artifacts are stowed aboard the helicopter, friends.
		loc_des_53_03 = "Certo, essa é a primeira parte yeah? Hora de adicionar o próximo composto.",--Right, that's part one yeah? Time to add the next compound.
		loc_des_61_03 = "Oh, parece que eles possuem um belo laboratório de armas! Eles possuem uma das nossas caixas em um armazém próximo, apenas vão até lá, yeah?",--Oh, looks like they've got a nice weapons lab! They've got one of the cases in an adjacent storage room, so get over there, yeah?
		loc_des_86_05 = "Vocês precisam destruir aqueles canhões. Reativem o desligamento!",--You need to kill those cannons. Reactivate the shutdown!
		loc_des_07_02 = "Rápido, entrem nessas portas.",--Quickly now. Get inside those doors.
		loc_des_21_03 = "Apressem-se amigos, vão até lá e liguem o guindaste.",--Hurry up friends, go out there and start the crane.
		loc_des_23_01 = "Esses Murkies arrombados cortaram a energia do guindaste. Vocês vão precisar começar de novo, amigos!",--Murky bliksems have cut the power to the crane. You gotta get it going again, friends!
		loc_des_55_01 = "Ah, vocês entenderam errado. Talvez ter trazido roupas anti-perigos fosse uma boa ideia. Aguardem até que eles parem de reagir, e depois tentem de novo.",--Ah, you got it wrong. Maybe bringing hazmat suits would have been a good idea. Wait until it stops reacting, then try again.
		loc_des_69_02 = "Ok, a arma está preparada e pronta pra atirar. Apertem o botão de fogo. E talvez não olhem diretamente para isso.",--There you go, the gun is primed and ready. Hit the fire button. And maybe don't look directly at it when it goes!
		loc_des_84_03 = "Oh, sem chance do helicóptero pousar sem que vocês desativem as defesas. Encontrem as caixas de controle e desconectem elas.",--Ach, no way the chopper can land until you shut down those guns. Find the control boxes and disconnect them.
		loc_des_17_02 = "Vocês precisam reniciar o override.",
		loc_des_92_02 = "Sua carona está pronta amigos, entrem nela!",
		loc_des_34_05 = "Por acaso vocês esqueceram onde é que está o computador principal ou algo do tipo?",
		loc_des_18_02 = "Os policiais cortaram a energia para o laboratório. Encontrem a caixa de energia e liguem ela.",
		loc_des_56_02 = "Ah, eles ferraram com toda a mistura. Vocês precisam fazer um novo, amigos.",
		loc_des_58_02 = "Rápido, coloquem a substância na porta.",
		loc_des_05_03 = "O hacking precisa ser reniciado, yeah?",
		loc_des_04_02 = "...Vejam se vocês podem abrir as portas por meio de caixas elétricas. Deve ter uma par delas por aí.",
		loc_des_92_03 = "O Bile está esperando por vocês amigos, entrem no helicóptero, yeah?",
		loc_des_13_01 = "Vamos pessoal, vocês precisam chegar no laboratório. Encontrem a prateleira certa.",
		loc_des_76_06 = "Eles estão indo pela arma!",
		loc_des_32_03 = "Usem a esteira na sala principal para carregar a caixa.",
		loc_des_30_02 = "Vamos lá, peguem ela. Isso não vai abrir um portal pro Inferno. Provavelmente..",
		loc_des_72_07 = "O processo de carregamento precisa ser iniciado novamente.",
		loc_des_101_02 = "Essa armas farão o Bile virar um queijo suiço fedorento. Tirem elas do ar hackeando as caixas de controle.",
		loc_des_55_02 = "Merda! Não funcionou. Vocês devem ter misturado algo errado. Esperem um pouco e tentem novamente, yeah?",
		loc_des_50_02 = "Vocês precisam ir até o laboratório biológico.",
		loc_des_95_01 = "As armas vão precisar de baterias novas.",
		loc_des_17_03 = "O progresso do hackeamento precisará ser reniciado, yeah?",
		loc_des_48_01 = "Voltem para o computador principal.",
		loc_des_26_02 = "Encontrem uma ferramenta, e então abram a caixa.",
		loc_des_cnc_01 = "Amigos, tiveram um pouco de diversão no deserto? Lá tem uma base da Murkywater que precisará ser roubada.",
		loc_des_89_01 = "Acendam o sinalizador quando vocês estiverem prontos para fugir daí.",
		loc_des_79_01 = "Peguem o artefato, e se certifiquem de que os policiais não vão conseguir pegá-lo.",
		loc_des_62_01 = "Cheguem ao laboratório de armas, amigos.",
		loc_des_75_01 = "Os Murkies e os policiais estão tentando desligar o canhão.",
		loc_des_36_02 = "Vocês precisa ir até a sala de arqueologia.",
		loc_des_108_02 = "Porra! Não funcionou. Vocês devem ter feito algo de errado. Esperem um pouco e tentem de novo, yeah?",
		loc_des_83_01 = "Peguem as caixas da esteira, amigos.",
		loc_des_68_06 = "Aquele canhão não irá atirar sem um pouco de energia.",
		loc_des_48_02 = "Voltem para o computador central e procurem, yeah?",
		loc_des_104_01 = "Usem o guindaste para trazer a caixa até vocês.",
		loc_des_26_03 = "Vocês acharam algo de útil aí perto para abrir a caixa?",
		loc_des_105_05 = "Vocês precisam fazer com que o hackeamento continue.",
		loc_des_45_02 = "Não tenho certeza se são iguais aos outros.",
		loc_des_82_02 = "Lembrem-se de tirar as caixas da esteira lá na plataforma de carregamento, yeah?",--...Remember to take the boxes from the conveyor on the loading dock, yeah?
		loc_des_96_05 = "O canhão não vai atirar até que vocês consigam baterias novas para ele.",
		loc_des_88_03 = "Quando vocês estiverem prontos para escapar, acendam o sinalizador para que o Bile vá aí.",
		loc_des_23_02 = "A energia foi cortada! Vocês precisam fazer ela funcionar novamente. Só depois reiniciem o guindaste.",
		loc_des_53_02 = "Eu acho que isso vai funcionar... não que eu conheça química, mas vocês já podem acrescentar o próximo ingrediente.",
		loc_des_35_01 = "Vão para a ala de arqueologia. Deve ter um artefato por lá em algum lugar.",
		loc_des_62_06 = "Por quê vocês ainda não estão no laboratório ainda?",
		loc_des_74_03 = "Liguem a alavanca de energia, rápido!",
		loc_des_76_05 = "Impeçam qualquer um de chegar até o canhão.",
		loc_des_13_03 = "Vocês precisam ir até o laboratório de tecnologia e achar a estante certa.",
		loc_des_48_03 = "Vocês precisam voltar e procurar no computador principal novamente.",
		loc_des_35_02 = "Ok, amigos. Parecem que eles estão mantendo uma das caixas na sala de arqueologia. Vão até lá agora, yeah?",
		loc_des_41_03 = "Os símbolos, amigos. Eles são a resposta que procuramos.",
		loc_des_end_01 = "Bom trabalho, amigos. Nós conseguimos o que viemos buscar, mas esse último... nós precisamos descobrir nosso próximo passo. Depois que vocês sairam de lá, a comunicação da Murkywater ficou totalmente parada, fora do ar. Nós fudemos bem os Kataru, mas não saberemos como eles vão revidar, e o Bain gostaria que nós continuassemos, independentemente do que acontecesse com ele. O Duke terá as mãos cheias de trabalho para descobrir a próxima peça desse enigma e para que essas caixas servem. Até lá, nós nos deitamos... planejamos... e sobrevivemos.",
		loc_des_50_05 = "Se apressem e vão em busca do artefato no laboratório biológico.",
		loc_des_74_02 = "Vocês precisam achar a alavanca de emergência de energia, amigos.",
		loc_des_66_04 = "Vocês têm que ligar essas baterias.",
		loc_des_20_02 = "Certo amigos, essa é a estante certa. Vão até a sala principal e usem o guindaste.",
		loc_des_47_03 = "Ainda temos mais uma caixa para pegar. Voltem até o computador principal e procurem por ela, yeah?",
		loc_des_108_01 = "Ah, vocês cometeram um erro. Talvez teria sido uma boa ideia ter trazido roupas de radiação. Esperem até parar de reagir, daí vocês podem tentar de novo.",
		loc_des_39_02 = "Vocês vão precisar reiniciar a furadeira!",
		loc_des_27_02 = "Vocês vão ter que tirar todos os parafusos, amigos.",
		loc_des_44_03 = "O artefato... essa é a razão de nós estarmos aqui.",
		loc_des_29_02 = "Heh, é quase a mesma coisa que o outro. Bom, foi por isso que viemos, então peguem ela e continuem trabalhando.",
		loc_des_40_01 = "Isso é que nem um doce para o Duke, yeah? Mas apenas precisamos do que está dentro. Esses símbolos provavelmente são a resposta para abrir isso. Procurem por aí por algumas pistas.",
		loc_des_30_03 = "A caixa, amigos.",
		loc_des_43_03 = "Um prêmio a menos para a Murky guardar. Peguem ela e movam-se, amigos.",
		loc_des_41_04 = "Vocês precisam abrir essa porra de arca.",
		loc_des_60_06 = "Vocês precisam pegar essa caixa..",
		loc_des_11_01 = "Ok, parece que um dos artefatos está sendo guardado no armazém de arquivos. Não tem nenhuma chance de vocês chegarem lá andando, mas tem um sistema que traz com um guindaste até o salão principal que vocês podem usar. Apenas encontrem a estante certa primeiro.",
		loc_des_47_01 = "Ok, vocês precisam voltar para o computador principal e procurar pela segunda caixa.",
		loc_des_43_01 = "Aqui vamos nós! Igual uma daquelas coisas de bonecas russas. Peguem a caixa e a mantenham em segurança.",--There we go! Just like one of those Russian doll-things. Take the box and keep it safe.
		loc_des_96_07 = "Conectem algumas novas baterias.",--Plug in some new batteries.
		loc_des_66_07 = "Conectem algumas novas baterias, yeah?",--Plug in some batteries, yeah?
		loc_des_16_01 = "A estação de trabalho, amigos.",--The workstation, friends.
		loc_des_70_02 = "Atirem com esse canhão, amigos.",--Shoot that cannon, friends.
		loc_des_25_03 = "Deem uma olhada por aí pra ver se encontram algo que possa ser usado para forçar a abertura da caixa.",--Have a look around for something you can use to force that crate open.
		loc_des_71_02 = "Porra, o carregamento parou. Iniciem novamente, yeah?",--Blerrie, the charging has stopped. Start it up again, yeah?
		loc_des_04_03 = "...Encontrem as caixas na parede que controlam as portas de emergência, yeah?",
		loc_des_01_03 = "Aqui vamos nós, amigos. Isso é pelo Bain, yeah?",
		loc_des_32_04 = "Movam a caixa para a entrada com a esteira do salão principal, yeah?",
		loc_des_46_01 = "Isso é... estranho, eh?",
		loc_des_80_01 = "Vocês precisam checar o computador principal de novo para encontrar o próximo artefato.",
		loc_des_77_02 = "Essa caixa precisa ser aberta com uma ferramenta.",
		loc_des_46_03 = "Alguém está sofrendo uma piada de mau gosto, yeah?",
		loc_des_99_03 = "O canhão já está preparado para disparar. Apertem o botão.",--The cannon is ready to fire, hit the button.
		loc_des_39_03 = "A furadeira parou. Malditos policiais!",--The drill has stopped. Damn kerels!
		loc_des_81_01 = "Grande trabalho, meus amigos! São as duas caixas. Voltem até a entrada para que eu possa tirar vocês daí.",--Great job, friends! That's both boxes. Head back to the entrance so that I can get you out of there.
		loc_des_85_02 = "Eles tiveram acesso ao painel de controle e pararam o desligamento. Vocês precisam ir até lá e reniciá-lo, amigos.",
		loc_des_105_04 = "Vocês precisa refazer o hackeamento nessas caixas de segurança.",
		loc_des_46_02 = "Quando vocês foram perder isso?",
		loc_des_44_05 = "Rápido amigos, peguem a caixa.",
		loc_des_38_01 = "Furem esse cofre, amigos.",
		loc_des_91_03 = "Ambas as caixas precisam estarem seguras no helicóptero antes de vocês embarcarem.",
		loc_des_04a_03 = "Já acharam as caixas de eletricidade?",
		loc_des_73_02 = "Os policiais derrubaram a energia de emergência. Encontrem a alavanca e liguem-a, amigos!",
		loc_des_20_01 = "Aí vão vocês, esse é o local. Agora saiam da sala de controle e peguem a caixa com o guindaste.",
		loc_des_102_06 = "Olhem para a fórmula, e então preparem o próximo ingrediente.",
		loc_des_66_02 = "Vocês encontraram alguma célula de energia?",
		loc_des_72_06 = "Reniciem o ciclo de recarga.",
		loc_des_22_04 = "O guindaste não está se movendo. A droga da Murkywater parou ele. Vão até lá e consertem isso, yeah?",
		loc_des_02_02 = "A porra dos policiais estão ajudando a Murky! Garrett deve ter afundado com esses filhos da puta após nossa pequena visita.",
		loc_des_42_01 = "Vocês fizeram algo errado, amigos. Ou os símbolos ou a ordem.",
		loc_des_42_03 = "Tentem uma outra combinação de símbolos e ordem, yeah?",
		loc_des_76_04 = "Policiais ainda estão indo atrás das armas.",
		loc_des_38_04 = "Você precisam fazer um grande furo nesse cofre.",
		loc_des_108_03 = "Não, algo está errado... agora vocês devem esperar a reação acabar e recomeçar, yeah?",
		loc_des_63_02 = "Ach, essa porta vai ser difícil de quebrar. Talvez um canhão fodão consiga fazer isso. Vejam se vocês podem mirá-lo.",
		loc_des_64_05 = "Eu sei que aí tem um monte de coisas engraçadas amigos, mas vocês precisam mirar o canhão!",
		loc_des_04a_04 = "Vamos amigos, vocês precisam abrir essas portas.",
		loc_des_50_01 = "Cheguem ao laboratório biológico.",
		loc_des_60_04 = "Vocês estão esperando o quê? Peguem essa caixa!",
		loc_des_54_02 = "Ótimo, amigos. Agora só mais um ingrediente, yeah?",
		loc_des_10_05 = "Encontrem o terminal, pessoal..",
		loc_des_107_01 = "Esse foi o último ingrediente, agora misturem todos juntos... cuidadosamente.",
		loc_des_31_02 = "Isso parece um pouco pesado, amigos. Usem a esteira no salão principal para mover isso para o ponto de extração.",
		loc_des_52_02 = "Acharam alguma boa fórmula, amigos?",
		loc_des_59_02 = "Aqui vamos nós! Peguem esse artefato e mexam-se!",
		loc_des_98_06 = "Esse canhão não irá atirar sem um pouco de energia.",
		loc_des_50_04 = "Talvez seja perigoso, mas vocês tem vão ter que ir até o laboratório biológico, amigos.",
		loc_des_75_02 = "Impeçam esses babacas de desligarem o canhão!",
		loc_des_74_04 = "Vocês precisam encontrar a alavanca e puxá-la.",
		loc_des_06_03 = "Abra-te sésamo, yeah? Agora vão mais fundo. As coisas agora tendem a ficar ainda mais complicadas a partir daqui.",--Open sesame, yeah? Now get going further in. It's only going to get worse from here.
		loc_des_20_03 = "Ótimo, agora vão direto para a entrada do local e usem o guindaste para levar a caixa para fora do armazém, yeah.",--Good, now get out to the main hub and use the crane to pull the box out of storage, yeah.
		loc_des_62_07 = "Vocês pensaram que todas aquelas armas teriam levado vocês até lá bem mais rápido, yeah?",--Would have thought all those weapons would have got you there faster, yeah?
		loc_des_93_03 = "É perigoso ficar por aí, amigos.",--Dangerous to stick around there, friends.
		loc_des_104_03 = "Rápido, coloquem o guindaste em movimento.",--Quickly now, get the crane moving.
		loc_des_07_03 = "Quanto mais vocês demorarem, mais difícil vai isso vai ficar.",--The longer you take, the more difficult this is going to become.
		loc_des_61_02 = "Certo meus amigos, vocês devem ir agora para o laboratório de armas. Acho que eles estão mantendo uma das caixas em uma sala próxima.",--Right friends, you should get over to the weapons lab. I think they're keeping one of the boxes in the adjacent room.
		loc_des_103_04 = "Vocês já abriram a arca?",--Have you got the ark open, yet?
		loc_des_84_01 = "O Bile não vai poder pegar vocês enquanto as armas estiverem ativas. Encontrem as caixas de controle e desliguem essas merdas, yeah?",--Bile can't pick you up while those guns are active. Find the control boxes and shut them down, yeah?
		loc_des_02_01 = "Merda! Parece que os federais também estão aqui. O Comissário Garrett parece bem, bem puto, yeah?",--Blerrie! Looks like the Feds are here too. Commissioner Garrett must be really, really pissed, yeah?
		loc_des_76_03 = "Não tirem os olhos daquele canhão.",--Don't take your eyes off that cannon.
		loc_des_25_02 = "Essa caixa está bem trancada. Talvez tenha algo que vocês possam usar para abrir ela, yeah?",--That crate is sealed tight. Maybe there's something you can use nearby to crack it open, yeah?
		loc_des_56_01 = "Porcos filhos da puta fuderam com tudo! Vocês precisam começar de novo.",--Bekakin' kerels messed it up for you! You're going to have to start over.
		loc_des_16_04 = "Rápido amigos, vocês precisam ir até aquele computador.",--Hurry friends, you need to get into that computer.
		loc_des_52_06 = "Verifiquem arquivos, quadros, paredes... tudo...",--Check the files, whiteboards,walls... everything...
		loc_des_78_02 = "Vocês precisam retirar esses parafusos também, amigos.",--You've got to get those screws off as well, friends.
		loc_des_30_01 = "Não se esqueçam da caixa, amigos.",--Don't forget the box, friends.
		loc_des_50_03 = "Vão para o laboratório biológico.",--Get going to the bio-lab.
		loc_des_10_02 = "Vão rápido, amigos. Sem tempo a perder.",--Move quickly, friends. No time to waste.
		loc_des_06_01 = "Ok, agora avançem para dentro da instalação. E tomem cuidado, yeah?",--There you go, now make your way further into the facility. And be careful, yeah?
		loc_des_33_02 = "Voltem para a entrada principal e encontrem a localização da segunda caixa.",--Get back into the mainframe and find the second box's location.
		loc_des_97_02 = "Carreguem o canhão novamente.",--Charge up the cannon again.
		loc_des_32_01 = "Coloquem a caixa na esteira, meus amigos.",--Put the box on the conveyor, friends.
		loc_des_107_03 = "Bem, esse foi o último ingrediente, é hora de combinar todos eles. fiquem firmes agora...",--That was the last ingredient, time to combine them all. Steady now...
		loc_des_37_01 = "Coloquem uma furadeira na porta do cofre, yeah? O que precisamos está em algum lugar aí dentro.",--Get a drill going on that vault door, yeah? What we need is somewhere inside.
		loc_des_57_03 = "Parece pronto, agora tudo o que vocês precisam fazer é deixar a mágica acontecer na porta, yeah?",--Looks ready, now all you gotta do it let it work some dissolving magic on the door, yeah?
		loc_des_73_01 = "Policiais filhos da puta cortaram a energia e pararam a recarga. Encontrem-na e liguem de volta, yeah?",--Damn kerels have cut the emergency power lever and stopped the charge. Find it and pull it back, yeah?
		loc_des_49_01 = "Não sei por que mas parece que eles possuem uma das caixas no laboratório biológico.$NL;Vocês já tomaram suas vacinas, yeah?",--Can't figure out why, but it looks like they've got one of the boxes in the bio-lab.$NL;You've got your vaccinations already, yeah?
		loc_des_09_02 = "Hackeiem o computador do terminal naa entrada principal e tentem localizar algumas pistas de onde podemos começar a procurar, yeah?",--...Hack into a mainframe computer terminal and try to find some clue where to begin searching, yeah?
		loc_des_67_03 = "Certo, agora encontrem o painel de controle e carreguem a arma.",
		loc_des_65_02 = "Vejam se vocês conseguem achar algumas baterias, e então preparem elas, yeah?",
		loc_des_21_02 = "Usem o guindaste para pegar o artefato, amigos.",
		loc_des_99_02 = "A arma está pronta, apertem o botão e curtam o show.",
		loc_des_94_01 = "Ok, agora vocês precisam mirar a arma aí na segunda fechadura.",
		loc_des_45_01 = "Eu me pergunto o porquê isso está do lado.",
		loc_des_23_03 = "A porra dos policiais cortaram a energia. Liguem ela e reativem o guindaste",
		loc_des_67_01 = "Hora de carregá-la. Deve ter um painel de controle por aí, yeah?",
		loc_des_44_01 = "Peguem a caixa, amigos.",
		loc_des_89_03 = "Prontos para vazar? Acendam o sinalizador!",
		loc_des_21_01 = "Saiam daí e usem o guindaste, amigos.",
		loc_des_05_01 = "Merda, vocês terão que reiniciar o hack.",
		loc_des_76_07 = "Eles não deixariam aquela arma sozinha se vocês não estivessem lá, amigos.",
		loc_des_58_04 = "Vocês devem deixar a mistura fazer o seu trabalho na porta.",
		loc_des_27_01 = "Tirem todos os parafusos, yeah?",
		loc_des_90_01 = "Protejam as caixas no helicóptero.",
		loc_des_69_03 = "Está carregado e pronto. Apertem o botão de atirar e se protejam, amigos!",
		loc_des_64_03 = "Movam aquele tambor. Depressa!",
		loc_des_30_04 = "É melhor vocês estarem trazendo a caixa, yeah?",
		loc_des_91_01 = "Vocês colocaram as duas caixas dentro do helicóptero?",
		loc_des_04a_01 = "Continuem indo amigos, sem tempo a perder. Abram aquelas portas.",
		loc_des_12_02 = "...Vocês poderão achar o número da prateleira da nossa caixa através do hackeando no terminal no laboratório de computadores.",
		loc_des_78_03 = "Parece que tem um número infinito de parafusos, yeah? Mas vocês precisam tirar todos eles.",
		loc_des_27_03 = "Tirem os parafusos daquela coisa.",
		loc_des_38_03 = "Ainda estou esperando pela furadeira.",
		loc_des_66_06 = "O canhão não atira sem baterias.",
		loc_des_68_02 = "Vocês precisam carregar o canhão.",
		loc_des_60_03 = "Vamos lá amigos, isso não vai se carregar sozinho, yeah?",
		loc_des_86_04 = "O Bile não pode pousar até ter aquelas armas deixando de funcionar.",
		loc_des_105_01 = "Vamos lá, reiniciem o hack.",
		loc_des_98_04 = "Nós precisamos do canhão carregado.",
		loc_des_36_03 = "Não acreditem nas superstições do Duke... vão para o laboratório de arqueologia.",
		loc_des_13_02 = "Já acharam a prateleira certa, amigos? Vão para o laboratório de computadores.",
		loc_des_51_01 = "Vocês vão precisar abrir aquela porta. Eu acho que o artefato está do outro lado. O que acha de cozinhar um coquetel divertido e queimar para arrombar a porta? Talvez haja um recipiente adequado para substâncias voláteis? Heh... o que pode dar errado, yeah?",
		loc_des_63_03 = "Whoa, parece algo como uma arma de energia. Nós podemos usar ela para explodir a porta. Apenas mirem para o ponto certo, amigos.",
		loc_des_60_07 = "Eu estou indo beber algo. Me avisem quando vocês pegaram a caixa, yeah?",
		loc_des_102_03 = "Depressa com a mistura, vocês precisam colocar ela na porta.",
		loc_des_100_01 = "É hora de voltar para a entrada para eu poder tirar vocês daí.",
		loc_des_76_01 = "Mantenham a porra desses Murkies longe da arma.",
		loc_des_54_01 = "Hah... tive certeza que vocês iam explodir o laboratório com aquilo, mas não se preocupem. Apenas mais um composto para adicionar.",
		loc_des_96_06 = "O canhão não pode atirar sem mais energia, troquem as baterias.",
		loc_des_101_03 = "O piloto não pode pousar até que vocês possam cuidar das turrets. Encontrem as caixas de controle e desconectem elas.",
		loc_des_37_03 = "Esse cofre precisa ser arrombado para nós conseguirmos o artefato. Coloquem uma furadeira nele, amigos.",
		loc_des_25_01 = "Certo, agora vocês precisam abrir ela. Vejam se vocês conseguem achar alguma coisa para nos ajudar, yeah?",
		loc_des_58_01 = "Vamos lá amigos, joguem essa mistura na porta.",
		loc_des_74_05 = "Puxem a alavanca!",
		loc_des_44_02 = "Não esqueçam a caixa, yeah?",
		loc_des_100_03 = "Vocês precisam ir de volta para a entrada para eu poder tirar vocês daí.",
		loc_des_87_02 = "Mas que porra.... Eu não consigo acreditar nisso... é isso...? Ach! Bastardos! Saiam daí, amigos!",
		loc_des_55_03 = "Não, essa é a mistura errada... agora vocês precisam esperar até a reação acabar e começar de novo, yeah?",
		loc_des_36_01 = "Cheguem ao laboratório de arqueologia.",
		loc_des_08_03 = "A instalação muda com frequência, então o pouco que vi não pode mais ser levado em conta.",
		loc_des_86_02 = "Voltem para aquela caixa de controle e desliguem ela.",
		loc_des_16_03 = "Já conectaram o terminal?",
		loc_des_17_04 = "O hacking foi interrompido, preciso que reiniciem ele, yeah?",
		loc_des_13_04 = "Vocês já acharam a prateleira correta, amigos? Procurem um terminal no laboratório de TI.",
		loc_des_15_03 = "Não conseguem ter uma resposta desse terminal? É essa porcaria de sistema operacional da Murkywater. Vejam se outro terminal funciona melhor, yeah?",
		loc_des_64_04 = "Mirem o canhão na direção certa.",
		loc_des_10_01 = "Precisam se apressar. amigos. A Murkywater está indo fuder vocês logo logo.",
		loc_des_34_02 = "Vocês ainda precisam achar o segundo artefato.",
		loc_des_07_01 = "Vamos amigos, não fiquem parados.",
		loc_des_06_02 = "As portas estão abertas, depressa, entrem e achem o que viemos pegar.",
		loc_des_88_02 = "Quando a costa estiver vazia, acendam o sinalizador para o Bile vir!",
		loc_des_49_03 = "Por quê a Murkywater tem um artefato no laboratório biológico? Não importa, vão lá e achem ele, yeah? E espero que vocês não precisem de roupas de radiação.",
		loc_des_24_01 = "Liguem a energia de volta amigos.",
		loc_des_39_05 = "Liguem a furadeira de novo, amigos.",
		loc_des_77_03 = "Outra caixa para abrir. Façam isso, yeah?",
		loc_des_74_01 = "Encontrem a alavanca, amigos.",
		loc_des_21_04 = "Vocês precisam ativar o guindaste, yeah?",
		loc_des_77_01 = "Vocês precisam abrir essa caixa também.",
		loc_des_62_04 = "Depressa, para o laboratório de armas!",
		loc_des_73_03 = "Ach! Eles cortaram a energia no ponto crítico do desligamento. Encontrem a alavanca e puxem ela pra continuar carregando.",
		loc_des_14_02 = "Agora, invadam um terminal de trabalho.",
		loc_des_41_01 = "Vocês precisam achar algumas pistas. Continuem procurando.",
		loc_des_51_03 = "Não pode ver ela em nenhum lugar, então provavelmente a caixa esta atrás daquela porta e vocês precisam entrar lá. Talvez vocês possam preparar algo útil e um pouco desagradável para comer, yeah? Parece que há algumas coisas por ai.",
		loc_des_68_04 = "Já encontraram o painel de controle?",
		loc_des_75_03 = "Os policiais e os murkies tão tentando parar a arma.",
		loc_des_37_02 = "Eu acho que a caixa esta atrás daquela porta do cofre, então abram ela, yeah?",
		loc_des_19_03 = "O tempo está sendo perdido, reniciem esse hack.",
		loc_des_101_01 = "Vocês precisam tirar do ar aquelas armas para o Bile poder pousar. Achem as caixas de controle e ai desliguem elas.",
		loc_des_05_04 = "Reniciem a invasão nas caixas de segurança.",
		loc_des_106_02 = "Preparem o próximo ingrediente, e esperem que nada de ruim venha a acontecer.",
		loc_des_04a_02 = "Abram aquelas portas, amigos..",
		loc_des_05_05 = "Merda, os policiais cortaram a invasão, liguem ela de novo.",
		loc_des_08_01 = "Faz muito tempo que vim aqui pela ultima vez. Eles mudaram um monte de coisas.",
		loc_des_09_03 = "...Vocês precisam hackear o terminal no computador principal e saber por onde começar a procura, yeah?",
		loc_des_103_05 = "Pressionem os símbolos na ordem correta.",
		loc_des_14_01 = "Ótimo, agora cheguem até a estação de trabalho e invadam ela.",
		loc_des_86_01 = "Reiniciem o desligamento, amigos.",--Restart the shutdown, friends.
		loc_des_93_05 = "Venham a bordo, amigos. O Bile irá partir logo.",--Get onboard friends. Bile has to leave.
		loc_des_83_02 = "Ainda tenho uma caixa na esteira.",--Still got a box on the conveyor.
		loc_des_34_01 = "A entrada principal, pessoal. Vão pra lá.",--The mainframe, gang. Get to it.
		loc_des_105_02 = "Vocês precisam reiniciar o override nessa caixa.",--You gotta restart the override on that box.
		loc_des_103_01 = "Vocês devem pressionar esses símbolos na ordem certa.",--You have to press those symbols in the right order.
		loc_des_26_05 = "Se vocês não trouxeram uma, deverão encontrar uma. Uma ferramenta, claro.",--If you don't bring one, you have to find one. A tool, that is.
		loc_des_70_06 = "O canhão não vai disparar sozinho.",--The cannon isn't going to fire itself.
		loc_des_32_02 = "Não tem necessidade de carregar esse artefato por aí, bastam colocá-lo na esteira.",--No need to carry that artifact around, just put it on the conveyor.
		loc_des_86_06 = "Parem essas armas para que eu possa trazer o Bile!",--Stop those guns so that I can bring in Bile!
		loc_des_10_04 = "Rápido, amigos. os Murkies vão afundar vocês se vocês não se mexerem logo.",--Hurry, friends. Murky are going to swamp you if you don't get moving.
		loc_des_78_01 = "Mais parafusos para desaparafusar.",--More screws to unscrew.
		loc_des_45_03 = "Nós já vimos esses símbolos antes.",--We've seen those symbols before
		loc_des_24_05 = "Coloquem a energia funcionando novamente, yeah?",--Get that power running again, yeah?
		loc_des_58_05 = "Coloquem o produto químico pronto na porta.",--Put the finished chemical on the door.
		loc_des_24_02 = "Vocês precisam reniciar a energia, amigos.",
		loc_des_28_05 = "Sentido anti-horário, amigos. É assim que se tira um parafuso. Na maioria das vezes.",
		loc_des_42_02 = "Isso não deu certo. Você precisar tentar uma combinação diferente, yeah?",
		loc_des_52_01 = "Vamos lá amigos, vocês precisam fazer a mistura.",
		loc_des_57_01 = "Ok, parece que é o coquetel certo, agora podem colocar ele na porta e deixem reagir, yeah?",
		loc_des_64_02 = "Vocês precisam mirar o canhão, yeah?",
		loc_des_65_03 = "Deve haver mais baterias por ai para vocês usarem.",
		loc_des_68_03 = "O canhão ainda não está carregado.",
		loc_des_74_06 = "Já achou aquela alavanca? Deve ser bem grande.",
		loc_des_76_02 = "Vocês precisam esperar o canhão.",
		loc_des_80_03 = "O computador principal guarda a localização da segunda caixa também, então cheguem lá, amigos.",
		loc_des_91_04 = "Carreguem as caixas, amigos.",
		loc_des_94_03 = "Vocês precisam atirar com a arma de novo, dessa vez mirada na segunda fechadura.",
		loc_des_95_02 = "Vocês precisam repor as baterias com umas outras carregadas.",
		loc_des_95_03 = "Aquela arma não vai atirar até que vocês acrescentem novas baterias.",
		loc_des_96_01 = "Troquem as baterias.",
		loc_des_98_05 = "Depressa, coloquem energia naquela porra..",
		
		-- Objetivos
		hud_heist_des1_hl = "Abra o Portão",
		hud_heist_des2_hl = "Explore o Complexo",
		hud_heist_des3_hl = "Hackeie a Rede da Entrada Principal",
		hud_heist_des4_hl = "Vá para o Laboratório de Computadores",
		hud_heist_des5_hl = "Procure nos Computadores por Informações",
		hud_heist_des6_hl = "Restaure a Energia",
		hud_heist_des7_hl = "Use o Guindaste para Pegar a Caixa",
		hud_heist_des8_hl = "Restaure a Energia",
		hud_heist_des9_hl = "Abra a Caixa",
		hud_heist_des10_hl = "Pegue o Baú",
		hud_heist_des11_hl = "Procure no Computador",
		hud_heist_des12_hl = "Vá para o Laboratório de Arqueologia",
		hud_heist_des13_hl = "Use a Furadeira na Porta do Cofre",
		hud_heist_des14_hl = "Encontre e coloque os Símbolos Corretos",
		hud_heist_des15_hl = "Pegue o Báu",
		hud_heist_des16_hl = "Procure no Computador",
		hud_heist_des17_hl = "Vá para o Laboratório de Biologia",
		hud_heist_des18_hl = "Combine os Produtos Químicos",
		hud_heist_des19_hl = "Use a Mistura na Porta",
		hud_heist_des20_hl = "Pegue o Báu",
		hud_heist_des21_hl = "Procure no Computador",
		hud_heist_des22_hl = "Vá para o Laboratório de Armas",
		hud_heist_des23_hl = "Ajuste a Mira da Arma Laser",
		hud_heist_des24_hl = "Plugue as Baterias",
		hud_heist_des25_hl = "Carregue a Arma Laser",
		hud_heist_des26_hl = "Atire com a Arma Laser",
		hud_heist_des27_hl = "Resete a Arma Laser",
		hud_heist_des28_hl = "Troque as Baterias",
		hud_heist_des29_hl = "Abra a Caixa",
		hud_heist_des30_hl = "Pegue o Báu",
		hud_heist_des31_hl = "Procure no Computador",
		hud_heist_des32_hl = "Volte para a Entrada",
		hud_heist_des33_hl = "Desative as Turrets",
		hud_heist_des34_hl = "Dê o Sinal para o Bile",
		hud_heist_des35_hl = "Aguarde a chegada do Bile",
		hud_heist_des36_hl = "Coloque os Báus no Helicóptero",
		hud_heist_des37_hl = "Fuja!",
		hud_heist_des38_hl = "Coloque o Baú na Esteira",--Place the box on the conveyor
		hud_heist_des16 = "Procure no computador da entrada principal pela próxima caixa.",--Search the mainframe for the next box.
		hud_heist_des14 = "Encontre a combinação de símbolos corretos para abrir a arca.",--Find the correct symbol combination to open the ark.
		hud_heist_des18 = "Procure no laboratório biológico pelos produtos químicos corretos para criar um composto corrosivo.",--Search the biolab for the correct chemicals to create a corrosive compound.
		hud_heist_des4 = "Vá até o laboratório de computadores.",--Go to the computer lab.
		hud_heist_des1 = "Encontre uma forma de passar pelo bloqueio de segurança do local.",--Find a way to override the security lockdown.
		hud_heist_des19 = "Use o composto para devorar a porta.",--Use the compound to eat through the door.
		hud_heist_des32 = "Volte novamente para onde você veio.",--Head back to where you came in.
		hud_heist_des34 = "Coloque o sinalizador para avisar ao helicóptero de fuga que você está pronto para fugir.",--Place a flare to signal the escape helicopter.
		hud_heist_des10 = "Pegue o baú da caixa.",--Pick up the box from the crate.
		hud_heist_des29 = "Use a ferramenta certa para abrir a caixa.",--Use the correct tools to open the crate.
		hud_heist_des23 = "Prepare a arma para encarar a porta da área de armazenamento.",--Rotate the weapon to face the door to the storage area.
		hud_heist_des9 = "Use a ferramenta certa para abrir a caixa.",--Use the correct tools to open the crate.
		hud_heist_des25 = "Aguarde até que a arma esteja poderosa o bastante.",--Wait for the weapon to be powered up.
		hud_heist_des24 = "Colete algumas baterias para ligar a arma.",--Collect batteries to power up the weapon.
		hud_heist_des5 = "Procure nos computadores os possíveis locais onde estariam sendo armazenados os artefatos.",--Search the computers for where the artifacts might be located.
		hud_heist_des33 = "Desative as turrets cortando alguns fios nas caixas elétricas.",--Disable the turrets by cutting the wires in the electrical boxes.
		hud_heist_des28 = "Coloque novas baterias na arma.",--Provide the weapon with fresh batteries.
		hud_heist_des8 = "Ligue a energia na caixa elétrica.",--Turn on the power at the electrical box.
		hud_heist_des3 = "Hackeie a rede da entrada principal para tentar localizar onde as caixas estão sendo mantidas.",--Hack the mainframe to try to find out were the cases might being kept in storage.
		hud_heist_des15 = "Pegue o baú de dentro da arca.",--Pick up the box from the ark.
		hud_heist_des6 = "Ligue a energia na caixa elétrica.",--Turn on the power at the electrical box.
		hud_heist_des38 = "Coloque os baús na esteira para enviá-las de volta para a entrada.",--Place the box on the conveyor belt to send it back to the entrance.
		hud_heist_des13 = "Use a furadeira na porta do cofre para abri-la.",--Drill the vault door to get it open.
		hud_heist_des35 = "Aguarde pela chegada do helicóptero.",--Wait for the helicopter to arrive.
		hud_heist_des30 = "Pegue o artefato.",--Pick up the artifact.
		hud_heist_des7 = "Use o guindaste para pegar a caixa direto do armazém.",--Use the crane to get a crate from the warehouse.
		hud_heist_des17 = "Vá até o laboratório biológico.",--Go to the biolab.
		hud_heist_des12 = "Vá até o laboratório de arqueologia.",--Go to the Archaeology lab.
		hud_heist_des20 = "Pegue o baú de dentro da mesa do laboratório.",--Pick up the box from the lab table.
		hud_heist_des11 = "Procure no computador da entrada principal pela próxima caixa.",--Search the mainframe for the next case.
		hud_heist_des36 = "Jogue todo o loot dentro do helicóptero para assegurá-los.",--Throw the loot into the helicopter and secure it.
		hud_heist_des27 = "Resete a arma para usá-la novamente.",--Reset the weapon.
		hud_heist_des2 = "Faça o seu caminho até a parte interna do complexo.",--Make your way further into the compound.
		hud_heist_des37 = "Fuja com o helicóptero.",--Escape with the helicopter.
		hud_heist_des31 = "Procure no computador da entrada principal pelo artefato.",--Search the mainframe for the artifact.
		hud_heist_des21 = "Procure no computador da entrada principal pelo próximo artefato.",--Search the mainframe for the next artifact.
		hud_heist_des26 = "Pressione o botão vermelho para atirar com a arma.",--Press the red button to fire the weapon.
		hud_heist_des22 = "Vá até o laboratório de armas.",--Head to the weapons lab.
		})
end)