Hooks:Add("LocalizationManagerPostInit", "hajrudinmalucaodoidao", function(loc)
	LocalizationManager:add_localized_strings({
	-- Nomes e Descrições
	heist_pex = "Breakfast in Tijuana",--Breakfast in Tijuana
	heist_pex_hl = "Breakfast in Tijuana",--Breakfast in Tijuana
	heist_pex_crimenet = "O Cunhado do Vlad, Hajrudin, foi capturado pela polícia mexicana. Aparentemente aconteceu logo depois do nosso assalto ao banco. Eles o moveram para a Estação de Polícia de Tijuana e parece que coletaram evidências que podem fazer ele ficar na cadeia por um bom tempo. Nós precisamos soltá-lo.\n\n» Encontre um jeito de Entrar na Prisão\n» Destrua a Evidência\n» Encontre o Prisioneiro e Resgate-o\n» Fuja",--Vlad's brother-in-law, Hajrudin, has been captured by the Mexican kerels. Apparently it happened right after that bank job we did. They moved him to a police station in Tijuana, and it seems they're also holding evidence that can put him away in prison for a long time. We need to get him out.\n\n» Find a way inside the police station\n» Destroy the evidence\n» Locate and free the prisoner\n» Escape
	heist_pex_briefing = "O Hajrudin está sendo mantido prisioneiro nos arredores da cidade. Mas a média de homicídios em Tijuana é absurda, e o nível da polícia reflete isso. É uma puta de uma fortaleza! Essa não vai ser fácil, mas se tem alguém que pode fazer, são vocês! Boa sorte!",--Hajrudin is being held in the outskirts of the city. But Tijuana's murder rate is infamous, and the police station security level reflects that. It's a blerrie fortress! This won't be easy, but if anyone can do it, it's you guys. Good luck!
	
	-- Legendas
	loc_pex_intro_01 = "Tudo certo... Infiltrem-se na Prisão, extraiam o prisioneiro e destruam a evidência. Boa sorte, amigos!",--Alright... Infiltrate, extract the target and destroy the evidence. Good luck, friends!
	loc_pex_intro_02 = "Vocês precisam entrar na prisão, liberar o nosso cara e destruir qualquer evidência incriminativa que aqueles desgraçados tem dele. Entenderam?",--You need to get in there, get our man out, and destroy whatever incriminating evidence the kerels are keeping on him. Got it?
	loc_pex_01_01 = "Primeiramente, vejam se conseguem entrar no lugar. Talvez vocês devam fazer isso de forma silenciosa.",--First, see if you can get inside. You might want to try a quiet approach.
	loc_pex_01_02 = "Eu sei que parece uma fortaleza, mas tem jeitos de entrar. Deem um jeito.",--I know it looks like a fortress, but there is a way in. Get to it.
	loc_pex_01_03 = "Ok amigos, hora de quebrar essa barreira. Encontrem um jeito de entrar.",--Okay friends, time to crack this nut. Find a way in.
	loc_pex_02_01 = "Podem apostar que a segurança aqui é bem forte, com câmeras e tudo.",--You can expect the security to be very tight, cameras and everything.
	loc_pex_02_02 = "Essa vai ser uma tarefa bem difícil mas vocês conseguem dar conta.",--This will be a tough one but you can handle it.
	loc_pex_02_03 = "Esperem uma segurança bem reforçada aqui.",--Expect very tight security here.
	loc_pex_03_05 = "Tem quer ter algum jeito de entrar. Encontrem-o!",--There has to be a way inside. Find it.
	loc_pex_04_01 = "Vocês provavelmente conseguem acessar os arquivos da evidência pelo computador do diretor. Eu aposto que fica no segundo andar.",--You can probably access the evidence files from the chief's computer. I'll bet it's on the upper floor.
	loc_pex_04_02 = "Eles provavelmente mantém os arquivos da evidência no computador do diretor. Tentem achá-lo no segundo andar.",--They probably keep the evidence files in the chief's computer. Try the upper floor.
	loc_pex_04_03 = "Vocês precisam achar o escritório do diretor no segundo andar. A evidência deve estar no computador dele.",--You should find the chief's office on the upper floor. The evidence should be on his computer.
	loc_pex_05_01 = "É melhor encontrar aquele computador, amigos.",--Better find that computer, friends.
	loc_pex_05_02 = "Lembrem-se, vocês estão procurando pelo computador do diretor do comando.",--Remember, you're looking for the chief kerel's computer.
	loc_pex_05_03 = "O diretor do comando terá os arquivos no computador dele.",--The kerel boss will have the files on his computer.
	loc_pex_05_04 = "Encontrem o computador do diretor para terem acesso aos arquivos de evidência.",--Find the chief's computer so you can get the evidence files.
	loc_pex_05_05 = "Encontrem o computador.",--Find that computer.
	loc_pex_06_01 = "E lá vamos nós. Hmm... aqui diz que tem evidência física do nosso amigo por aqui também.",--There we go. Hmm... it says there's physical evidence on our friend around here as well...
	loc_pex_06_02 = "Certo então. Hmmm.... aqui diz que também há evidência física.",--Alright then. Hmm... it says there's also physical evidence.
	loc_pex_06_03 = "Muito bem. Vejamos... aqui diz que também há evidência física do nosso amigo.",--Good. Let's see... it says here they have physical evidence on our friend as well.
	loc_pex_07_01 = "O sistema de portas deles utiliza etiquetas eletrônicas com códigos. Nós vamos precisar fazer uma para nós. Veja se encontram alguma em algum lugar do Escritório.",--Their door system uses coded key tags. We'll need to make one. See if you can find a blank tag somewhere around the office.
	loc_pex_07_02 = "O sistema de portas deles só pode ser aberto com etiquetas eletrônicas codificadas. Vejam se encontram alguma em branco que possamos codificar.",--Their doors open with coded key tags. See if you can find a blank one that we can code.
	loc_pex_07_03 = "Nós precisamos de uma etiqueta em branco para então modificarmos e abrir as portas. Vejam se encontram alguma.",--We need a blank key tag so we can code it to open the doors. See if you can find one.
	loc_pex_08_01 = "Já encontraram a etiqueta?",--Find that key tag yet?
	loc_pex_08_02 = "Alguma pista dessa etiqueta?",--Any luck with that key tag?
	loc_pex_08_03 = "Vocês pegaram a etiqueta?",--You got that key tag?
	loc_pex_08_06 = "Lembrem-se, vocês precisam encontrar a etiqueta em branco.",--Remember, you need to find a blank key tag.
	loc_pex_09_01 = "Agora vão até o computador para que possamos codificar a etiqueta para ter acesso.",--Now go to the computer so we can code that key tag for access!
	loc_pex_09_03 = "Agora nós precisamos codificar a etiqueta para ter acesso. Vão até o computador.",--Now we need to code the tag for access. Get it to the computer!
	loc_pex_09_04 = "O próximo passo é codificar a etiqueta. Vão até o computador.",--Next step is to code the tag. Get it to the computer!
	loc_pex_10_02 = "Vamos, vão até o computador.",--Come on, go to the computer.
	loc_pex_10_03 = "Vão até o computador, amigos.",--Go to the computer, friends.
	loc_pex_10_04 = "Levem essa etiqueta até o computador. Chop Chop.",--Get that tag to the computer. Chop chop.
	loc_pex_11_01 = "A Sala das Evidências deve estar no segundo andar, encontrem-o e utilize a etiqueta para entrar.",--The evidence storage should be on the second floor, find it and use the key tag to get in. 
	loc_pex_11_02 = "Utilizem a etiqueta para entrar na Sala das Evidências. Deve estar no segundo andar.",--Use your key to get into the evidence storage. It should be on the second floor.
	loc_pex_11_03 = "A Sala das Evidências deve estar no segundo andar. Vão!",--The evidence storage is on the second floor. Go!
	loc_pex_12_01 = "Já encontraram a Sala das Evidências?",--Found that evidence storage room yet?
	loc_pex_12_04 = "Vocês precisam encontrar a Sala das Evidências!",--You've got to find the evidence storage!
	loc_pex_12_05 = "Alguma pista dessa Sala de Evidências?",--Any luck with the evidence room?
	loc_pex_13_01 = "Tem bastante coisa interessante aqui! Eu acho que vocês vão saber o que vocês estão procurando quando vocês olharem.",--There's a lot of stuff in here! I guess you'll know what you're looking for when you see it.
	loc_pex_13_02 = "Encontre os 'bens'. Tenho certeza que vocês saberão o que é quando olharem.",--Find the goods. I'm sure you'll know it when you see it!
	loc_pex_13_03 = "É procurar e destruir, amigos! Primeiro passo - Procurar!",--It's search and destroy, friends! Step one - search!
	loc_pex_14_01 = "Já encontraram essa evidência?",--Find that evidence yet?
	loc_pex_14_04 = "Alguma pista até agora?",--Any luck yet?
	loc_pex_14_05 = "A evidência tem que estar aqui em algum lugar!",--The evidence has to be here somewhere!
	loc_pex_14_06 = "Continuem procurando e vocês vão encontrar!",--Keep looking and you'll find it!
	loc_pex_15_01 = "Agora se livrem dessa evidência. Deve ter algum jeito de destruí-la aí na Estação.",--Now get rid of that evidence. There must be a way to destroy it here in the station.
	loc_pex_15_02 = "Agora encontrem alguma maneira de destruí-la.",--Now find some way to destroy it!
	loc_pex_16_01 = "Vocês precisam destruir essa evidência!",--You have to destroy that evidence!
	loc_pex_17_01 = "Mandem por água baixo no banheiro. Vai se misturar com o resto da merda aí.",--Flush it down the toilet! It will mix with the rest of the kak.
	loc_pex_18_01 = "Utilizem o rolo de papel - é a maneira mais fácil.",--Use that paper shredder - it's the easy way.
	loc_pex_19_01 = "Utilizem o acendedor de fogo para fazer um coquetel para queimar a evidência.",--Use the kitchen blender to make an evidence cocktail.
	loc_pex_20_01 = "Hora de liberar o nosso amigo. Encontrem o bloco de celas, deve estar perto.",--Time to get our friend out. Find the door to the custody cell block, it should be near.
	loc_pex_20_02 = "Agora vamos resgatar o nosso amigo. O bloco de celas deve estar perto.",--Now let's rescue our friend. The cell block should be nearby.
	loc_pex_20_03 = "Hora do ato principal, tirar o nosso amigo daí. Procurem pelo bloco de celas, deve estar aí perto.",--Time for the main act, getting our friend out. Look for the cell block, it should be nearby.
	loc_pex_20_04 = "O bloco de celas está perto. É onde eles estão mantendo o nosso amigo.",--The cell block is nearby. That's where they'll be keeping our friend.
	loc_pex_21_02 = "Já encontraram o bloco de celas?",--Find the cell block yet?
	loc_pex_21_03 = "Vocês encontraram o bloco de celas?",--Did you find the cell block?
	loc_pex_21_04 = "Vocês precisam encontrar o bloco de celas.",--You've got to find the cell block.
	loc_pex_21_05 = "Encontrem o bloco de celas.",--Find the cell block!
	loc_pex_21_06 = "Procurem pelo bloco de celas.",--Look for the cell block!
	loc_pex_22_01 = "Essa é uma porta forte pra caralho, muito resistente para uma furadeira. Melhor checar a Sala de Armamentos para algo que possamos usar.",--That's a blerrie strong door, too tough for the drill. Better check the armory for something to open it with.
	loc_pex_22_03 = "A furadeira não vai conseguir arrombar essa porta. Procurem na Sala de Armamentos para ver se tem algo que possamos usar.",--The drill won't break that door. You should try the armory and see if there's anything you can use.
	loc_pex_22_04 = "Nenhuma furadeira vai quebrar essa porta. Mas a Sala de Armamentos talvez tenha algo que possa resolver nosso problema.",--No drill will break that door. But the armory might have something that can take care of it.
	loc_pex_23_01 = "A Sala de Armamentos, amigos. Tentem seguir esse cheio de pólvora de arma.",--The armory, friends. Try following the smell of gun oil?
	loc_pex_23_02 = "Lembrem-se, vocês estão procurando pela Sala de Armamentos.",--Remember, you're looking for the armory.
	loc_pex_23_04 = "A Sala de Armamentos não deve ser tão difícil de encontrar.",--The armory shouldn't be too hard to find.
	loc_pex_24_01 = "Parece que a Sala de Armamentos tem níveis de acesso diferentes. Vocês vão precisar codificar aquela etiqueta de novo.",--It seems the armory has a different access level. You'll need to recode the key tag again.
	loc_pex_24_02 = "Hmm, a etiqueta precisa de um nível de acesso maior para entrar na Sala de Armamentos. Vocês vão precisar recodificá-la.",--Hmm, the key must need a higher access level for the armory. You'll have to recode it.
	loc_pex_25_01 = "Andem logo, vocês precisam recodificar aquela etiqueta.",--Come on, you need to recode that tag.
	loc_pex_25_03 = "Vocês precisam recodificar a etiqueta.",--You need to go recode the key tag.
	loc_pex_25_06 = "Vamos logo, recodifiquem a etiqueta.",--Come on, recode that key tag.
	loc_pex_26_01 = "Agora voltem até a Sala de Armamentos e vejam se encontram algo que possa ser usado no bloco de celas.",--Now get back to the armory and see if you can find something to use on the cell block door.
	loc_pex_26_02 = "Agora roubem essa sala cheia de armas, amigos!",--Now go sack that armory, friends!
	loc_pex_28_04 = "Muito bem! Um Quebrador de Portas!",--Very nice! A door breaker!
	loc_pex_29_01 = "Coloque o Quebrador de Portas em posição!",--Get that door breaker in position!
	loc_pex_29_04 = "Vocês já sabem o que precisam fazer com isso!",--You know what to do with that!
	loc_pex_30_04 = "Abram! Hora de libertar o nosso passarinho da gaiola!",--Open! Time to release the jailbird!
	loc_pex_31_01 = "Talvez eles tenham movido ele de um bloco de cela para uma Sala de Interrogação.",--They might have moved him from a cell to an interrogation room.
	loc_pex_31_02 = "Não esqueçam de verificar as Salas de Interrogação. Talvez ele esteja em uma delas.",--Don't forget to check the interrogation rooms. He might be in there.
	loc_pex_33_01 = "Deem para ele o fone de ouvido.",--Give him the earpiece!
	loc_pex_33_02 = "Vocês já deram o fone para ele? Muito bem!",--Are you giving him the earpiece? Good!
	loc_pex_34_01 = "Parece que ele não fez jogo fácil para os federais aguentarem. Nós vamos precisar soltá-lo.",--Looks like he was hard for the kerels to handle. We'll need to cut him loose.
	loc_pex_34_02 = "Eles o amarraram. Nós vamos precisar soltá-lo.",--They tied him down. We'll need to cut him loose.
	loc_pex_34a_01 = "Vocês precisam de algum tipo de ferramenta para soltá-lo.",--You'll need some kind of tool to cut him loose.
	loc_pex_34a_04 = "Essas correntes precisam ceder de algum jeito.",--Those chains will have to come off somehow.
	loc_pex_34a_05 = "Já encontraram alguma coisa para dar um jeito nessas correntes?",--Find anything yet for those chains?
	loc_pex_35_01 = "Agora soltem-o.",--Now cut him loose.
	loc_pex_35_02 = "Snip snip. Usem esse alicate para cortar as correntes.",--Snip snip. Put that bolt cutter to the chains.
	loc_pex_36_05 = "Não deixem ele amarrado por mais tempo do que o necessário!",--Don't leave him tied up longer than necessary!
	loc_pex_37_01 = "Nós precisamos tirar ele daí sem essa roupa de prisioneiro. Encontrem um uniforme de policial.",--We need to get him out of that prisoner outfit. Find him a spare police uniform!
	loc_pex_38_01 = "Tem que ter uniformes de polícia nos armários, yeah?",--There should be uniforms in the locker room, yeah?
	loc_pex_38_06 = "Já encontraram o uniforme?",--Find that uniform yet?
	loc_pex_40_01 = "Ok, o nosso amigo sabe a rota de fuga, certo? Vocês só precisam ficar esperto com os guardas.",--Okay, our friend will know the way out, right? You just have to watch out for the guards.
	loc_pex_40_03 = "O prisioneiro sabe a rota de fuga. Só fiquem de olho nos guardas.",--The prisoner knows the way out. Just keep an eye out for guards.
	loc_pex_42_01 = "Deem uma ajuda para ele com a porta.",--Give him some help with the door.
	loc_pex_42_02 = "Ajudem ele com a porta.",--Help him with the door.
	loc_pex_43_01 = "Muito bem! Agora roubem um desses carros de polícia e sumam daí.",--Good! Now steal one of the police cars and get out of there.
	loc_pex_43_01a = "Ah merda. Nós não temos tempo para isso. Não tem problema, peguem esse carrinho de merda então.",--Oh blerrie hell. We don't have time for this. Fine, take his crappy car then.
	loc_pex_45_01 = "Vocês vão precisar descobrir quais chaves vão em cada carro. Isso seria bem mais fácil se nós pudéssemos roubar qualquer um dos carros.",--You need to figure out which key goes with his car. This would really be easier if we could just take any car.
	loc_pex_45_03 = "Vocês vão precisar encontrar a chave certa aqui.",--You'll need to find the right key here.
	loc_pex_47_01 = "Levem a chave até o nosso amigo!",--Bring the key to our man!
	loc_pex_47_02 = "Agora levem a chave para ele!",--Now bring him the key!
	loc_pex_47_03 = "Deem a ele a chave!",--Give him the key!
	loc_pex_50_01 = "Agora vazem daí.",--Now get out of there.
	loc_pex_50_02 = "Hora de escapar!",--Time to go!
	loc_pex_52_03 = "Perfeito e silencioso! Ótimo trabalho, amigos!",--Nice and quiet! Good job friends!
	loc_pex_52_04 = "Muito bem! O passarinho está fora da gaiola!",--Very good! The bird is out of the cage!
	loc_pex_53_01 = "Está acertando o ventilador! É hora do plano B.",--It's hitting the fan! Time for the backup plan.
	loc_pex_53_02 = "Enfim, parece que isso não vai ser mais tão silencioso.",--Looks this won't be so quiet after all.
	loc_pex_53_03 = "Eu acho que teremos que modificar o nosso plano Stealth.",--I think the stealth plan just got modified.
	loc_pex_53_05 = "Isso não soa bem! Estejam prontos para lutar!",--That doesn't sound good! Be ready to fight!
	loc_pex_56_01 = "Ok, vocês estão dentro! As informações que eu tenho dizem que eles mantém a evidência no segundo andar. Encontrem-a!",--Okay, you're in! My intel says they keep the evidence on the second floor. Go find it!
	loc_pex_56_02 = "A Sala das Evidências deve estar no segundo andar.",--The evidence lockup should be on the second floor.
	loc_pex_56_03 = "Vocês vão precisar encontrar o armário com as evidências no segundo andar.",--You'll need to find the evidence storage on the second floor.
	loc_pex_56_04 = "Agora procurem pela Sala das Evidências. Provavelmente estará no segundo andar.",--Now look for the evidence storage. It should be on the second floor.
	loc_pex_57_01 = "Continuem olhando! Vocês precisam encontrar essas evidências.",--Keep looking! You've got to find that evidence!
	loc_pex_57_02 = "A Sala das Evidências está em algum lugar no segundo andar.",--The evidence storage is somewhere on the second floor!
	loc_pex_57_04 = "A Sala das Evidências está no segundo andar!",--The evidence room is on the second floor!
	loc_pex_57_05 = "Continuem procurando pela Sala das Evidências no segundo andar!",--Keep looking for the evidence room on the second floor!
	loc_pex_58_01 = "Aqui vamos nós! Vocês terão que perfurar para abrir.",--Here we are! You'll have to drill it open.
	loc_pex_58_02 = "Aí está ela! Agora coloquem uma furadeira para abrir essa porta!",--There it is! Now drill that door open!
	loc_pex_58_03 = "Achamos a sala! Agora coloquem uma furadeira para funcionar!",--This is the room! Now put that drill to work!
	loc_pex_58_04 = "Certo! Essa furadeira deve ser o suficiente para abrir essa porta!",--Alright! The drill should open that door!
	loc_pex_59_02 = "Eles pararam a furadeira!",--They stopped the drill!
	loc_pex_59_03 = "A furadeira parou!",--The drill has stopped!
	loc_pex_59_04 = "A furadeira parou!",--The drill stopped!
	loc_pex_60_02 = "Vamos, vocês precisam reiniciar a furadeira!",--Come on, you need to restart the drill!
	loc_pex_60_03 = "Melhor colocar essa furadeira para funcionar novamente!",--Better get that drill running again!
	loc_pex_60_04 = "Liguem a furadeira!",--Go start the drill!
	loc_pex_63_01 = "Não há necessidade de correr riscos com isso. Só joguem no chão e queimem aí mesmo.",--No need to take risks with this stuff. Just put it on the floor and burn it right here.
	loc_pex_63_02 = "Apenas queimem logo no chão! Sem invenções!",--Just burn it right here on the floor! No fuss!
	loc_pex_63_04 = "Agora façam uma pilha de evidências no chão e queimem tudo!",--Now make a nice little pile on the floor and burn it!
	loc_pex_64_03 = "Coloquem no chão e queimem-as!",--Put it on the floor and burn it!
	loc_pex_64_04 = "Coloque a evidência no chão e queime tudo!",--Place the evidence on the floor so you can burn it!
	loc_pex_65_01 = "Nós deveríamos ter trazido um pouco de gasolina para queimar isso. Mas não se preocupem, tenho certeza que deve ter algo por aqui!",--We should have brought some gasoline or something to light this up with. But never mind, I'm sure they have something around here!
	loc_pex_65_02 = "Tentem encontrar algo que seja altamente inflamável para queimar isso.",--Try to find something highly flammable to light this up with!
	loc_pex_65_03 = "Nós precisamos de algum fluido inflamável para o nosso foguinho!",--We need some lighting fluid for this braai !
	loc_pex_65_04 = "Precisamos de algo para acender isso!",--We need something to help light this up!
	loc_pex_66_01 = "Já encontraram algo inflamável?",--Found anything flammable yet?
	loc_pex_66_02 = "Já conseguiram algo para queimar?",--Got that lighting fluid yet?
	loc_pex_66_03 = "Vocês vão precisar encontrar um líquido inflamável!",--You need to find a flammable liquid!
	loc_pex_66_04 = "Vocês vão precisar de algum fluido inflamável!",--You'll need a lighting fluid for the fire!
	loc_pex_66_05 = "Essa evidência não vai queimar se vocês não conseguirem algo para acendê-la!",--That evidence won't burn without some lighting fluid!
	loc_pex_67_01 = "Hora do churrasco! Defendam o fogo!",--Barbecue time! Now defend that fire!
	loc_pex_67_02 = "Muito bem! Defendam a nossa fogueira até que esteja tudo pronto!",--Good! Defend your campfire until it's all gone!
	loc_pex_67_03 = "Vejam que maravilha! Agora fiquem aí por perto e certifiquem-se de que tudo seja queimado.",--Look at that! Now stay and make sure it all burns!
	loc_pex_67_04 = "Isso, queime! Agora certifiquem-se de que os policiais não apaguem o fogo.",--Burn baby! Now make sure the kerels don't put it out!
	loc_pex_68_01 = "Eles apagaram o fogo com os sprinklers!",--They put the fire out with sprinklers!
	loc_pex_68_02 = "Os sprinklers apagaram o fogo!",--Those sprinklers put the fire out!
	loc_pex_68_03 = "Eles ligaram os sprinklers! O fogo se apagou!",--They put sprinklers on! The fire went out!
	loc_pex_68_04 = "O fogo foi apagado pelos sprinklers!",--The fire was killed by sprinklers!
	loc_pex_69_02 = "Eles estão apagando o fogo!",--They're stamping the fire out!
	loc_pex_71_01 = "Fiquem de olho nos sprinklers, nós não queremos nenhum arrombado ligando eles.",--Keep an eye on the sprinklers, we don't want the kerels to set them off!
	loc_pex_71_02 = "Fiquem de olho nesses sprinklers!",--Keep an eye on those sprinklers!
	loc_pex_71_03 = "Não deixem eles ligarem esses sprinklers!",--Don't let them start those sprinklers!
	loc_pex_71_04 = "Fiquem de olho no sistema de sprinklers!",--Watch the sprinkler system!
	loc_pex_71_05 = "Fiquem de olho nesse sistema de sprinklers!",--Keep a watch on that sprinkler system!
	loc_pex_71_06 = "Cuidem desses sprinklers!",--Watch those sprinklers!
	loc_pex_74_01 = "Essa porta é muito grossa, uma furadeira não vai ser o suficiente para ela. Talvez a Sala de Armamentos tenha o que precisamos!",--That door is too thick, the drill won't be enough. Maybe the armory has the cure.
	loc_pex_74_02 = "Nossa, essa porta é uma besta. Veja se na Sala de Armamentos tem algo que possa quebrá-la.",--My, that door is a beast. See if the armory has something that can help you break it.
	loc_pex_74_03 = "Vocês vão precisar de algo especial para abrir essa porta. Verifiquem a Sala de Armamentos!",--You'll need something special for that door. Go check the armory!
	loc_pex_75_01 = "Vocês precisam encontrar a Sala de Armamentos, amigos!",--You need to find that armory, friends!
	loc_pex_76_03 = "Vocês podem hackear a porta! Façam isso!",--You can hack the door! Get to it!
	loc_pex_76_04 = "Vocês vão precisar hackear essa porta!",--You need to hack this door!
	loc_pex_77_01 = "Eles interromperam o hackeamento! Vocês precisam recomeçá-lo.",--They interrupted the hacking! You'll need to restart it!
	loc_pex_77_02 = "O Hackeamento foi interrompido. Arrumem-o!",--The hacking was interrupted. Get on it!
	loc_pex_77a_01 = "Vocês precisam recomeçar o hackeamento!",--You have to restart the hacking!
	loc_pex_77a_02 = "Vocês precisam recomeçar o hackeamento o mais cedo possível!",--You've got to restart the hacking asap!
	loc_pex_77a_04 = "Andem logo, recomecem o hackeamento.",--Come on, restart the hacking!
	loc_pex_78_01 = "Certifiquem-se de proteger o dispositivo de hackeamento enquanto ele está funcionando.",--Make sure you protect the hacking device while it works!
	loc_pex_78_02 = "Protejam o dispositivo de hackeamento!",--Protect the hacking device!
	loc_pex_78_03 = "Vocês precisam proteger a porta enquanto ela está sendo hackeada!",--You have to protect the door while it's being hacked!
	loc_pex_78_04 = "Lembrem-se, protejam o dispositivo de hackeamento!",--Remember to protect the hacking device!
	loc_pex_78_05 = "Não deixem esses arrombados chegarem no dispositivo de hackeamento!",--Don't let the kerels get to the hacking device!
	loc_pex_79_01 = "Encontre algo para derrubar a porta desse bloco de celas!",--Find something to take that cell block door down!
	loc_pex_79_02 = "Deve ter algo por aí que dê pra usar para derrubar essa porta do bloco de celas.",--There's got to be something here that can breach the cell block door!
	loc_pex_79_03 = "Procurem por algo bom para derrubar portas.",--Look for something that's good for breaching doors!
	loc_pex_80_01 = "Vocês precisam procurar por algo que possa derrubar uma porta fortificada.",--You're looking for something that can take an armored door down!
	loc_pex_80_02 = "Algo para abrir aquela porta, lembrem-se!",--Something to open that door, remember!
	loc_pex_80_03 = "Vocês precisam de algo para derrubar essa porta!",--You need something that can breach that door!
	loc_pex_80_04 = "Procurem por algo que possa quebrar uma porta fortificada!",--Look for something that can breach a heavy door!
	loc_pex_81_01 = "Levem esse Quebrador de Portas até a porta do bloco de celas. Tenho certeza que vai funcionar!",--Take that door breaker to the cell block door. I'm sure it will do the job!
	loc_pex_81_02 = "Esse Quebrador de Portas vai ser perfeito para o que precisamos! Leve-o até a porta do bloco de celas!",--That door breaker will be perfect for the job! Take it to the cell block door!
	loc_pex_81_03 = "Muito bem! Agora levem esse Quebrador de Portas até a porta do bloco de celas.",--Good! Now take that door breaker to the cell block door!
	loc_pex_82_02 = "Abre-te, sésamo! Agora encontrem o prisioneiro.",--Open sesame! Now go find that prisoner!
	loc_pex_82_03 = "Isso foi fácil! Agora encontrem o nosso amigo!",--That was easy! Now go find our friend!
	loc_pex_83_01 = "Se ele não estiver em uma cela, ele deve estar na Sala de Interrogação.",--If he's not in a cell, he might be in an interrogation room.
	loc_pex_83_04 = "Talvez ele tenha sido movido para uma Sala de Interrogação.",--He might have been moved to an interrogation room.
	loc_pex_85_01 = "Essas correntes - vocês vão precisar de alguma ferramenta para tirá-lo daí!",--Those chains - you'll need some tool to get him out of there!
	loc_pex_85_02 = "Parece que eles amarraram ele no lugar. Precisamos achar alguma ferramenta!",--Looks like he's chained to the spot. You need to find some tools!
	loc_pex_85_03 = "Vocês vão precisar pegar algumas ferramentas. Ele está amarrado!",--You'll need to get some tools. He's chained up!
	loc_pex_86_02 = "Deve ter algumas ferramentas sobrando em algum lugar por aí!",--There should be tools lying around here somewhere!
	loc_pex_86_05 = "Vocês vão precisar de algo para cortar essas correntes!",--You'll need something for cutting those chains!
	loc_pex_87_01 = "Agora libertem o nosso amigo dessa merda!",--Now get our friend out of those restraints!
	loc_pex_87_02 = "Agora tirem essas correntes dele!",--Now get those chains off him!
	loc_pex_89_02 = "A rota de fuga de vocês é pela garagem. Vão!",--Your way out is through the garage! Go!
	loc_pex_89_03 = "Vocês devem sair dessa garagem!",--Make your way out through the garage!
	loc_pex_90_02 = "O nosso amigo vai mostrar para vocês a rota de fuga! Apenas sigam ele!",--Our friend will show you the way out! Just follow him!
	loc_pex_90_03 = "Apenas sigam o prisioneiro e ele irá mostrar para vocês a rota de fuga daí!",--Just follow the prisoner and he'll show you the way out of here!
	loc_pex_93_01 = "Muito bem! Agora roubem algum desses carros de polícia e deem o fora daí.",--Good! Now steal one of the police cars and get out of there.
	loc_pex_93_01a = "Ah merda. Encontrem as chaves do carro então! Vamos torcer para que essa pilha de lixo pelo menos engate o motor!",--Oh blerrie hell. Find the keys to his car then! Let's just hope that pile of junk even starts!
	loc_pex_96_01 = "Vocês vão precisar descobrir qual chave é a certa.",--You'll need to figure out which key is the right one.
	loc_pex_96_02 = "Certifiquem-se de que vocês pegaram a chave certa agora!",--Make sure you get the right key now!
	loc_pex_96_03 = "Peguem a chave certa para o carro!",--Get the right key for the car!
	loc_pex_97_01 = "Tentem outra chave!",--Try another key!
	loc_pex_97_02 = "Tentem outra!",--Try another one!
	loc_pex_97_03 = "Certifiquem-se de pegar a chave certa na próxima vez!",--Make sure you get the right key next time!
	loc_pex_97_04 = "Verifiquem se vocês pegaram a chave certa!",--Check to make sure you get the right key!
	loc_pex_101_01 = "Hora do plano B. Eu tenho um helicóptero esperando... nós podemos dar uma carona para vocês, com o carro e todo o resto.",--Time for plan B. I have a helicopter standing by... we'll lift you out, car and everything.
	loc_pex_101_02 = "Tudo bem, o plano B é o helicóptero. Esperem...",--Alright, plan B is the helicopter. Hang on...
	loc_pex_101_03 = "Não se preocupem, eu tenho um plano reserva. Tem um helicóptero vindo aí.",--Don't worry, I have a backup plan. There's a helicopter incoming.
	loc_pex_102_01 = "Apenas se segurem até o helicóptero chegar.",--Just hold your ground until the helicopter arrives!
	loc_pex_102_02 = "O helicóptero está chegando. Apenas aguentem um pouco mais!",--The helicopter is coming. Just hold on a little longer!
	loc_pex_102_03 = "O helicóptero está a caminho! Apenas aguentem firme!",--The helicopter is on its way! Just hold on!
	loc_pex_102_04 = "Se segurem até que o helicóptero chegue!",--Hold your ground until the helicopter arrives!
	loc_pex_102_05 = "O helicóptero não vai demorar!",--The helicopter won't be long!
	loc_pex_104_01 = "Atrelem o carro ao helicóptero!",--Attach the car to the chopper!
	loc_pex_104_02 = "Atrelem o carro ao helicóptero para que ele possa tirar vocês daí!",--Attach the car to the chopper so we can lift you out!
	loc_pex_104_03 = "Atrelem o carro ao helicóptero para poder voar pra fora daí.",--Attach the car so you can fly out of here!
	loc_pex_105_04 = "Vocês tem os cabos para atrelar o carro no helicóptero!",--You've got to connect the wires!
	loc_pex_end_loud_03 = "O cunhado do Vlad está de volta, saudável e seguro. Eu acho que mostramos para esses desgraçados que não devem mexer com gangsters Ucranianos, yeah?",--Vlad's brother-in-law is back safe and sound, mostly! I suppose we showed those dwankie kerels that you don't mess with Ukrainian gangster-types, yeah?
	loc_pex_end_stealth_01 = "Ótimo trabalho, o imbecil do cunhado do Vlad está livre. Talvez agora ele fique fora de confusões no futuro, yeah? É... provavelmente não...",--Nice job, sneaking Vlad's dwankie brother-in-law out of there. Maybe he will stay out of trouble in the future, yeah? (Heh.. not likely...)
	
	-- Cunhado do Vlad
	alm_pex_01_01 = "O que... ei! O Vlad enviou vocês para me tirarem daqui?",--What... hey! Did Vlad send you to get me out?
	alm_pex_01_02 = "Qu.. o quê.. é a Gangue PAYDAY!",--Who.. wha... hey it's the Payday Gang!
	alm_pex_02_01 = "Um fone de ouvido? Bacana!",--A radio earpiece? Sweet!
	alm_pex_03_01 = "Esses babacas me prenderam! Tirem essa merda de mim!",--These fuckers chained me up! Get this shit off me!
	alm_pex_04_01 = "Sim, me tirem dessas correntes, cara.",--Yeah get me out of these chains man.
	alm_pex_05_01 = "Ei, pessoal? Eu estou aqui!",--Yeah, guys? I'm right here!
	alm_pex_06_03 = "Valeu! Meus pulsos doem pra caralho!",--Thanks! My wrists hurt like hell!
	alm_pex_07_01 = "O que? Vocês querem que eu me vista igual um policial?",--What? You want me to dress up like a cop??
	alm_pex_09_01 = "Sim, eu conheço o caminho.",--Yeah I know the way.
	alm_pex_12_01 = "Umm... me ajudem com essa porta, pessoal.",--Umm... help me out with this door, guys.
	alm_pex_14_01 = "Ei! Eu não vou sair sem o MEU carro!",--Hey! I'm not leaving without MY car!
	alm_pex_14_02 = "O que estou ouvindo aqui é inveja, cara. Inveja.",--What I'm hearing here is envy, man. Envy.
	alm_pex_15_01 = "Vou precisar das chaves do carro aqui, pessoal.",--I'm gonna need the car key here, guys.
	alm_pex_15_02 = "Hmm, vou precisar da chave do meu carro.",--Hmm, gonna need my car key.
	alm_pex_15_03 = "Certo, eles não deixaram a chave no carro. Policiais espertos.",--Right, they didn't leave the key in the car. Smart cops.
	alm_pex_20_01 = "Ei! Que... o Vlad enviou vocês?",--Hey! Wha... did Vlad send you?
	alm_pex_20_02 = "Que porr... ei! Vocês estão aqui para me resgatarem?!",--What the fu... hey! Are you here to rescue me?!
	alm_pex_21_01 = "Esses filhos da puta me prenderam! Tirem essa merda de mim!",--These assholes chained me up! Get this shit off me!
	alm_pex_21a_01 = "Isso, tire essas merdas de correntes, cara!",--Yeah get these fucking chains off man!
	alm_pex_22_01 = "Obrigado! Muito obrigado, caralho!",--Thank you! Thanks so fucking much!
	alm_pex_22_02 = "Obrigado! Obrigado!",--Thank you! Thank you!
	alm_pex_23_01 = "Sim, eu conheço a saída. Estive mantendo meus olhos abertos!",--Yeah I know the way out. I was keeping my eyes open!
	alm_pex_23_02 = "Sim, eu conheço a saída. Eu estava planejando escapar sozinho!",--Yeah I know the way! I was planning to escape myself!
	alm_pex_28_01 = "Ei! Eu não vou sair sem o MEU carro!",--Hey! I'm not leaving without MY car!
	alm_pex_28_02 = "Não insulte minhas rodas, cara!",--Don't insult my wheels, man!
	alm_pex_29_01 = "Essa é a porra da chave errada!",--This is the wrong fucking key!
	alm_pex_29_02 = "Chave errada!",--Wrong key!
	alm_pex_29_03 = "Essa não é a certa!",--This isn't the right one!
	alm_pex_31_01 = "É essa! Vamos lá!",--This is the one! Let's go!
	alm_pex_31_02 = "Muito bom! Vamos lá!",--Awesome! Let's go!
	alm_pex_32_01 = "Aqui vamos nós. Adios amigos, policiais fudidos!",--There we go. Adios amigos, fucking cops!
	alm_pex_32_03 = "Estou feliz de poder sair desse lugar!",--I'll be glad to see the back of this place!
	alm_pex_33_01 = "Merda! Eles bloquearam as saídas! Nós não podemos sair!",--Shit! They blocked the exits! We can't get out!
	alm_pex_34_01 = "Hahaa, a cavalaria chegou!",--Hahaa, cavalry's here!
	alm_pex_34a_01 = "*Cantarolando em voz alta Ride of the Valkyries de Wagner*",--*loudly sings Ride of the Valkyries by Wagner*
	alm_pex_34_03 = "Uau!",--Woop!
	alm_pex_36_01 = "E lá vamos nós! Todos entrem no carro!",--Off we go! Get in the car everyone!
	
	-- Objetivos
	hud_heist_pex_mission1 = "Entre na Estação de Polícia para procurar pelo Hajrudin e pela evidência.",--Enter the police station to search for Hajrudin and the evidence.
	hud_heist_pex_mission1_hl = "Dê um jeito de Entrar",--Find a way inside
	hud_heist_pex_mission10_hl = "Codifique a Etiqueta RFID com acesso para a Sala de Armamentos",--Code RFID tag with armory access
	hud_heist_pex_mission11_hl = "Entre na Sala de Armamentos",--Get inside the Armory
	hud_heist_pex_mission12_hl = "Pegue o Quebrador de Portas",--Steal door breaker
	hud_heist_pex_mission13_hl = "Coloque o Quebrador de Portas",--Deploy door breaker
	hud_heist_pex_mission14_hl = "Encontre o Prisioneiro",--Find the prisoner
	hud_heist_pex_mission15_hl = "Roube um Uniforme",--Steal a Uniform
	hud_heist_pex_mission16_hl = "Corte as Correntes",--Cut the chains
	hud_heist_pex_mission17_hl = "Siga o Hajrudin para fora",--Follow Hajrudin out
	hud_heist_pex_mission18_hl = "Encontre as Chaves do Carro",--Find car keys
	hud_heist_pex_mission19_hl = "Dê as Chaves para Hajrudin",--Give keys to Hajrudin
	hud_heist_pex_mission2_hl = "Hackeie o Computador",--Hack the computer
	hud_heist_pex_mission20_hl = "Fuja",--Escape
	hud_heist_pex_mission21_hl = "Entre na Sala de Evidências",--Get inside the Evidence Room
	hud_heist_pex_mission22_hl = "Empilhe as Evidências no Chão",--Pile the evidence on the floor
	hud_heist_pex_mission23_hl = "Consiga um Líquido Inflamável",--Get flammable liquid
	hud_heist_pex_mission24_hl = "Defenda o Fogo",--Defend the Fire
	hud_heist_pex_mission25_hl = "Encontre as Celas",--Find the cells
	hud_heist_pex_mission26_hl = "Corte as Correntes",--Cut the chains
	hud_heist_pex_mission28_hl = "Siga o Hajrudin para fora",--Follow Hajrudin out
	hud_heist_pex_mission29_hl = "Espere pelo Helicóptero",--Wait for the Helicopter
	hud_heist_pex_mission3_hl = "Encontre uma Etiqueta RFID em branco",--Find an empty RFID tag
	hud_heist_pex_mission30_hl = "Atrele o Carro ao Helicóptero",--Attach car to Helicopter
	hud_heist_pex_mission31_hl = "Dê o Uniforme ao Hajrudin",--Give uniform to Hajrudin
	hud_heist_pex_mission32_hl = "Desligue a Água",--Turn off water
	hud_heist_pex_mission33_hl = "Acenda o Fogo",--Light the fire
	hud_heist_pex_mission34_hl = "Defenda a Furadeira",--Defend the drill
	hud_heist_pex_mission35_hl = "Defenda o Dispositivo de Hack",--Defend the Hacking Device
	hud_heist_pex_mission36_hl = "Reinicie o Dispositivo de Hack",--Restart the Hacking Device
	hud_heist_pex_mission4_hl = "Codifique a Etiqueta RFID",--Code the RFID tag
	hud_heist_pex_mission5_hl = "Encontre a Sala de Evidências",--Find the Evidence Room
	hud_heist_pex_mission6_hl = "Encontra a Evidência",--Find the evidence
	hud_heist_pex_mission7_hl = "Destrua a Evidência",--Destroy the Evidence
	hud_heist_pex_mission8_hl = "Encontre as Celas",--Find the cells
	hud_heist_pex_mission9_hl = "Encontre a Sala de Armamentos",--Find the Armory
	hud_heist_pex10 = "Volte até o segundo andar e codifique a etiqueta RFID para ter acesso a Sala de Armamentos.",--Go back to the second floor and code the RFID tag for access to the armory.
	hud_heist_pex11 = "Abra a Sala de Armamentos utilizando somente a etiqueta RFID.",--Open the armory door using the RFID tag.
	hud_heist_pex12 = "Pegue o Quebrador de Portas para usar na porta do bloco de celas.",--Get the door breaker so you can use it on the custody cell block door.
	hud_heist_pex13 = "Coloque o Quebrador de Portas na porta do bloco de celas.",--Deploy the door breaker on the custody cell block door.
	hud_heist_pex14 = "O Hajrudin deve estar em algum lugar pelo bloco de celas. Veja se consegue encontrá-lo.",--Hajrudin should be somewhere around the cell block. See if you can find him.
	hud_heist_pex15 = "Entre no vestiário e roube um uniforme de polícia.",--Break into the locker room and steal one of the police uniforms.
	hud_heist_pex16 = "Procure por um Alicate que vocês possam usar para soltar o Hajrudin.",--Look around for a bolt cutter that you can use to cut Hajrudin loose.
	hud_heist_pex17 = "Siga o Hajrudin para fora do bloco de celas. Mantenha-se em Stealth.",--Follow Hajrudin out from the custody cell block. Stay stealthy.
	hud_heist_pex18 = "Procure pelas chaves do carro, certifique-se de pegar as certas.",--Look for the car keys, and make sure you get the right ones.
	hud_heist_pex19 = "Dê as chaves do carro para o Hajrudin para que ele possa tirar vocês daí.",--Give the car keys to Hajrudin so you can get out of here.
	hud_heist_pex2 = "Localize o Escritório do diretor no segundo andar e o hackeiem para pegar as informações da evidência.",--Locate the Chief Officer's computer somewhere on the second floor and hack it so you can get information about the evidence.
	hud_heist_pex20 = "Entre no carro e fuja com o Hajrudin.",--Get into the car and escape along with Hajrudin.
	hud_heist_pex21 = "Use a furadeira para ganhar acesso a Sala de Evidências. Certifique-se de defender a furadeira contra os policiais.",--Use a drill to get inside the evidence room. Make sure you defend the drill against the cops.
	hud_heist_pex22 = "Colete a evidência e a empilhe no chão para queimá-la.",--Collect the evidence and pile it up on the floor outside the room so you can burn it.
	hud_heist_pex23 = "Encontre um líquido inflamável para queimar a evidência. Depois derrame-o na evidência e o acenda.",--Find a flammable liquid for igniting the evidence. Then pour it on and light it up.
	hud_heist_pex24 = "Defenda o fogo e certifique-se de que os policiais não o apague.",--Defend the fire and make sure the cops don't put it out.
	hud_heist_pex25 = "Encontre o bloco de celas da Estação de Polícia.",--Find the police station's custody cell block.
	hud_heist_pex26 = "Procure por um Alicate para soltar o Hajrudin.",--Look around for a bolt cutter that you can use to cut Hajrudin loose.
	hud_heist_pex27 = "Hackeie a Sala de Armamentos para ganhar acesso a ela.",--Hack the armory door in order to gain access.
	hud_heist_pex28 = "Siga o Hajrudin para fora do bloco de celas.",--Follow Hajrudin out from the custody cell block.
	hud_heist_pex29 = "Aguente firme até que o helicóptero chegue para te tirar daí.",--Hold out until the helicopter arrives to lift you out.
	hud_heist_pex3 = "Você vai precisar ter acesso privilegiado para entrar na Sala de Evidências. O computador do diretor pode criar etiquetas RFID com acesso para várias salas no prédio.",--You'll need door access to get inside the evidence room. The chief officer's computer can create RFID tags that give access to various rooms in the building.
	hud_heist_pex30 = "Conecte os cabos do helicóptero ao carro para ele poder te tirar daí pelos céus.",--Connect the cables to the car so the helicopter can lift you up into the sky.
	hud_heist_pex31 = "Dê o uniforme ao Hajrudin para ele poder se disfarçar de policial e vazar daí.",--Give the uniform to Hajrudin so he can disguise himself as a cop for the escape.
	hud_heist_pex32 = "Desligue a água pelo sistema de sprinklers para o fogo poder queimar a evidência.",--Turn off the water to the sprinkler system so that the fire can burn the evidence.
	hud_heist_pex33 = "Acenda o fogo para queimar as evidências.",--Light up the fire to burn the evidence.
	hud_heist_pex34 = "Proteja a furadeira dos policiais.",--Protect the drill from the cops.
	hud_heist_pex35 = "Defenda o dispositivo de hackeamento dos policiais até que o processo esteja concluído.",--Defend the Hacking Device from the cops until the hacking process is completed.
	hud_heist_pex36 = "Recomece o dispositivo de hackeamento para que ele termine de hackear a trava eletrônica da porta.",--Restart the Hacking Device so that it can finish hacking the electronic lock on the door.
	hud_heist_pex4 = "Volte até o Escritório e codifique a etiqueta RFID no dispositivo ao lado do computador.",--Go back and code the RFID tag on the device next to the computer.
	hud_heist_pex6 = "Procure pela sala e tente localizar a evidência do Hajrudin.",--Search the room and try to locate where the evidence on Hajrudin is stored.
	hud_heist_pex7 = "Encontre algo que possa ser usado para destruir a evidência.",--Find something that can be used to destroy the evidence.
	hud_heist_pex8 = "Encontre a entrada para o bloco de celas da estação.",--Find the entrance to the police station's custody cell block.
	hud_heist_pex9 = "Localize a Sala de Armamentos e veja se encontra algum meio de adentrar o bloco de celas.",--Locate the armory and see if you can find some means to get through the custody cell block door.
		})
end)